### ISSUE TITLE
CherryPY - update 0.8.x trunk

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#100]
while it 'looks' like 3.2.2 is the latest the actual latest version is 3.2.4 (bit-bucket) however that version was suppose to become 3.3 but that was about 1-2 months ago. Anyways for right now I say we just update to 3.2.3 and apply the patches if needed.

the main website for cherrpy is maintained by someone else and they are afk, for right now you can get 3.2.3 from:
https://bitbucket.org/cherrypy/cherrypy/downloads

**Comment by shypike** [comment]
We're now on CherryPy 3.8.0, the official release with some patches.
