### ISSUE TITLE
FYI: Howto create a docker image / container with SABnzbd, for testing

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1000]
**Howto create a docker image / container with SABnzbd, for testing**

I wanted a Debian Stretch 9 container with SABnzbd for testing. This is the howto.

Inside a directory, create a file named `Dockerfile` (case-sensitive):
```
#
# Dockerfile with Debian and SABnzbd
#
FROM debian:stretch
MAINTAINER Sander "blabla@example.com"

RUN sed -i -e 's/main$/main contrib non-free/g' /etc/apt/sources.list \
  && apt-get update && apt-get upgrade -y \
  && apt-get install python python-setuptools  curl sabnzbdplus nano gnupg2 -y \
  && easy_install pip && pip install cherrypy --upgrade && pip install pyopenssl --upgrade \
  && echo "deb http://ppa.launchpad.net/jcfp/ppa/ubuntu xenial main" | tee -a /etc/apt/sources.list \
  && apt-key adv --keyserver hkp://pool.sks-keyservers.net:11371 --recv-keys 0x98703123E0F52B2BE16D586EF13930B14BB9F05F \
  && apt-get update && apt-get dist-upgrade -y

EXPOSE 8080 9090 9999

```
Still in the directory that has the Dockerfile, create the image (and note the dot at the end!!!)

```
sudo docker build -t "mystuff:debianstretch" .
```
Run it (make sure ports 8080 9090 and 9999 are not in use on the host machine, so no running SABnzbd there!):
```
sudo docker run -it  -p 8080:8080 -p 9090:9090 mystuff:debianstretch /bin/bash
```
On the prompt, type:
`sabnzbdplus -s 0.0.0.0 -b0`

On the **host** machine, go to the usual http://127.0.0.1:8080/

**Comment by Safihre** [comment]
Thanks!
