### ISSUE TITLE
Include Mozilla's CA Bundle with macOS and Windows builds

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1001]
I just found this wonderful package called `certifi`, which is updated with the latest Mozilla's CA Bundle and can easily be installed with:
```
pip install certifi
```
Then all these certificates can easily be included by running this before making connections:
```python
import certifi
os.environ["SSL_CERT_FILE"] = certifi.where()
```
On Windows these are additional certificates, so if users have custom SSL certificates they are preserved as well.
We can update the `certifi` package on build, so our build always includes the latest version.

@sanderjo what do you think?

**Comment by sanderjo** [comment]
Nice catch!

Some thoughts:

- So this is like the way curl does this it: just bring your own, full set of root certificates
- What do you think of the "1024-bit Root Certificates" remark on https://github.com/certifi/python-certifi ?
- Would you *always* load (=import) it?
- would and could it also work for Linux (read: NAS devices)?

**Comment by Safihre** [comment]
Exactly, bring your own style. We need this on macOS if we want to upgrade from Openssl 0.9.8 because Python can't link into the system storage correctly anymore. 

For now I only tested it for the macOS and Windows builds, because there we are certain it has Openssl 1.0.2 and thus the 1024bit is not a problem. 

I would always load it yes, or you'd prefer a switch? 
On other platforms I'm not sure if on other platforms system SSL files are ignored if we set SSL_CERT_FILE. Would have to test this. 
If it uses both (system and certifi's) it might be good to use it if available: if we detect certifi module we use it, otherwise we don't. 
If it then ignores system certificates, I'm not sure if it's good idea?

**Comment by Safihre** [comment]
Will test this for next major release, the infrastructure for building is now setup to do it.

**Comment by sanderjo** [comment]
You're going to implement it? I thought based on our one-on-one discussion (MacOS with old openssl 0.9.8) that this was something we dit NOT want?
More general: stay away of the OS-level SSL/TLS settings.

**Comment by Safihre** [comment]
With the terrible state of OpenSSL+Python on MacOS, we seem to be left no choice.
Now macOS users will not be limited to SSLv3 or TLSv1 any more.
