### ISSUE TITLE
Disable Direct Unpack

### ISSUE THREAD

**Issue by lstrozzi** [sabnzbd/sabnzbd#1003]
Hello, I welcome the new feature to Direct Unpack, but I have the following situation (maybe common to other users), so I'd like to share with you my issue:

I have a large RAID disk array, which I try to keep OFF almost all the time I don't use it. This contains the extracted files. I have an additional disk, which I use as temporary folder. I wish that the extraction process runs only a few times a day, so that the energy consumption of the large RAID array is kept to minimum.

Thank you in advance for feedback
Best regards
LS

**Comment by Safihre** [comment]
Sure, Config > Switches > Disable Direct Unpack :)

**Comment by Safihre** [comment]
But you do have the jobs set to only +Repair and not +Unpack?  In that case they also shouldn't Direct Unpack.
