### ISSUE TITLE
7-Zip -- upgrade mac binary

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1004]
we include 7-Zip 16.02 (2016-05-21) for mac and 16.04 for windows (2016-10-04).. might want to upgrade mac so its in sync?

z-zip changelog (can see they have a major bump coming sometime, but not really anything we need):
```
17.00 beta     2017-04-29
-------------------------
- ZIP unpacking code was improved.
- 7-Zip now reserves file space before writing to file (for extraction from archive).
  It can reduce file fragmentation.
- Some bugs were fixed. 7-Zip could crash in some cases.
- Internal changes in code.


16.04          2016-10-04
-------------------------
- The bug was fixed: 7-Zip 16.03 exe installer under Vista didn't create 
  links in Start / Programs menu.
- Some bugs were fixed in RAR code.


16.03          2016-09-28
-------------------------
- Installer and SFX modules now use some protection against DLL preloading attack.
- Some bugs were fixed in 7z, NSIS, SquashFS, RAR5 and another code.


16.02          2016-05-21
-------------------------
- 7-Zip now can extract multivolume ZIP archives (z01, z02, ... , zip).
- Some bugs were fixed.
```

**Comment by Safihre** [comment]
I know, but have you found a location where you can get 7zip for Mac? Because I could not.
On their official website they list `p7zip` which I used, but to this day is still stuck on 16.02: https://sourceforge.net/projects/p7zip/files/p7zip/

**Comment by thezoggy** [comment]
i see people requesting they update the source sdk to 16.04 back in feb.. so it looks like its just abandon ware :( thankfully theres nothing we NEED in the newer version

**Comment by Safihre** [comment]
Exactly 👍
