### ISSUE TITLE
centos 7 + sabnzbd 2.2.0 wrong disk space

### ISSUE THREAD

**Issue by Arsur** [sabnzbd/sabnzbd#1007]
I missed some versions but now on version 2.2.0 i have an very strange error. The Diskspace is only about 7gb. When i download it get less and less until the download stops with errors. (Disk full! Forcing Pause...)

I installed it from git, from some repo and i tried the docker version. All on several Google compute instances with differend disk sizes, everytime the behavior. 

I think it must be an error centos 7 + sabnzbd 2.2.0 but iam not an expert.

i also opend an thread at the forum 
https://forums.sabnzbd.org/viewtopic.php?f=2&t=22917

**Comment by Safihre** [comment]
That's a pretty exotic setup..

Could you download this file and run it with the path to your disk?
https://raw.githubusercontent.com/sanderjo/disk_space/master/disk_space.py
```
python disk_space.py /xxxxxdiskxxxx
```

**Comment by Arsur** [comment]
interesting its seems to be centos is only 10gb big in size, os i guess i have to resize the partition.

thanks for your help.
