### ISSUE TITLE
Items getting stuck at 99 or 100% since 2.2.0 update:

### ISSUE THREAD

**Issue by gold007eye** [sabnzbd/sabnzbd#1010]
Seems like this is happening all the time since the update.  I rarely had any issues like this prior to the update.

An influx in errors has also been occuring since this last update.

![image](https://user-images.githubusercontent.com/4365462/29723495-740d8876-898a-11e7-837c-05f272a2cdd2.png)

**Comment by Safihre** [comment]
Try 2.2.1RC from our downloads page, it's resolved there.

**Comment by thezoggy** [comment]
or 2.2.1 -- https://github.com/sabnzbd/sabnzbd/releases/tag/2.2.1

**Comment by Safihre** [comment]
Let us know if it still stuck after 2.2.1!

**Comment by gold007eye** [comment]
Will do.  Thanks

**Comment by arcooke** [comment]
I am still getting this in 2.3.0.  This has happened more than once, I just don't download a whole lot. Should I make a new report or is this OK?

![](https://i.imgur.com/msfBwnl.png)

![](https://i.imgur.com/VMSHCff.png)

**Comment by Safihre** [comment]
Are you on 2.3.3 or 2.3.2?
