### ISSUE TITLE
NZB with Force priority is always Queued

### ISSUE THREAD

**Issue by markus101** [sabnzbd/sabnzbd#1012]
I had a paused queue with several items in it and set the top item to priority `Force`, which began downloading. When I fetched the queue via the API the status that was returned for that item was `Queued`, but I'd expect `Downloading` (which is the status if the queue is not paused).

Here it the relevant item form the queue:

```
{
  "status": "Queued",
  "index": 0,
  "password": "",
  "missing": 0,
  "avg_age": "262d",
  "mbmissing": "-4.13",
  "script": "None",
  "has_rating": false,
  "mb": "825.94",
  "sizeleft": "468 MB",
  "filename": "Linux.iso",
  "priority": "Force",
  "direct_unpack": 0,
  "cat": "linux",
  "mbleft": "467.83",
  "eta": "20:45 Sun 27 Aug",
  "timeleft": "9:56:33",
  "percentage": "43",
  "nzo_id": "SABnzbd_nzo_hx7xyf",
  "unpackopts": "3",
  "size": "826 MB"
}
```

**Comment by Safihre** [comment]
Makes sense 👍
