### ISSUE TITLE
Sabnzbd 2.2.1 direct unpack status icon only visible when window is very wide

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1013]
Just thought I would point out that the new direct unpack status icon is only visible when the window is very wide.

I think it should be relocated, maybe in the middle of the progress bar, it would work even for a narrow window like a phone browser.

**Comment by Safihre** [comment]
If that's the biggest problem with DirectUnpack, I'm happy 😃 
Yes, the CSS/HTML should be optimized.
But I am also waiting to see if Chrome 61 maybe screws things up, in the current testing-releases of 61 the Queue/History look stupid. But to fix that requires lots of messing around.

**Comment by Cpuroast** [comment]
I'm on 61 beta of chrome, nothing weird so far:

Version 61.0.3163.59 (Official Build) beta (64-bit)

**Comment by Safihre** [comment]
For me the top-border of the Queue and History is missing, particularly visible in Glitter Night.
It has something to do with the `thead` overflow changing.

**Comment by Cpuroast** [comment]
Odd, I run Glitter Night.

**Comment by Safihre** [comment]
I tried some variants, but not sure what to do with this. 
There's just too many icons when hovering if I make it always visible. Or have to hide it on hover, but then people cannot put their cursor on it to see what it means (title of icon).

And it's kinda ugly in the bar:
![image](https://user-images.githubusercontent.com/5703454/29887099-9f0290ea-8dbc-11e7-947a-a12fa9f58e7a.png)

**Comment by thezoggy** [comment]
Maybe on that small of a resolution we do two lines for the info or drop showing the progress bar and just do %

**Comment by Cpuroast** [comment]
Would probably look nicer if the directunpack info was centered on the progress bar
![29887099-9f0290ea-8dbc-11e7-947a-a12fa9f58e7a copy](https://user-images.githubusercontent.com/3321892/29899072-429f1ada-8db7-11e7-8e8d-54a60b96e1f5.png)

**Comment by Safihre** [comment]
@Cpuroast On Chrome 61 (mine is 61.0.3163.71), Glitter Night does not look like this when you hover over the first row? So the weird white top border plus the missing top border in general?

![image](https://user-images.githubusercontent.com/5703454/29994483-7e66ff90-8fd0-11e7-88e5-041cfb1c47f7.png)

**Comment by Cpuroast** [comment]
You are right, I do see a weird white line at the top of the 1st row when I hover in Chrome
Version 61.0.3163.71 (Official Build) beta (64-bit)

In Firefox 56.0b8 (64-bit), this doesn't occur.

And in Safari Version 10.1.2 (12603.3.8), it's the reverse of Chrome, the white line appears below the 1st row instead of at the top.

**Comment by Safihre** [comment]
@Cpuroast the weird lines should be fixed in 2.3.0RC2.

Regarding the direct unpack icon, I guess we should make it 3 rows on mobile to fit all the information.
