### ISSUE TITLE
feature request. Postprocess direct unpacked first

### ISSUE THREAD

**Issue by Hellowlol** [sabnzbd/sabnzbd#1014]
Having a large download que, results in my history page getting filled up. It would be greate if the queue selected "whats evers ready to postprocess" instead of waiting for some files that need to be unpacked before moving on to other files that already is direct unpacked. 

In my case my download drive is rather small (1tb) so i get out of storage space before the post processing kicks in and moves the files to unraid. Now i know i could disable direct unpack or decrease the unpacking threads (10 atm), but i thought it was worth putting it out there.

**Comment by Safihre** [comment]
Yep, this is on the to-do list.
I am think of a `FastPostprocessor` and the normal `PostProcessor`. Jobs go first into the Fast one if they have `direct_unpacker.succes_sets`, otherwise they go to the normal one.
The would involve the creation of some `PostprocessorManager` that handles the queue.

**Comment by Safihre** [comment]
So I implemented this in a kind of cheeky easy way: 
There is a fast and a slow queue in the `PostProcessor`, if we see it has completed Direct Unpack or if it is still active (might be unpacking that last volume) it is put in the fast queue.
We always check the fast queue first, then the slow one. To not have slow jobs be stuck in the post-proc queue forever, every 3 fast jobs we force a slow job (if present).

**Comment by Hellowlol** [comment]
Thanks!
