### ISSUE TITLE
direct unpack leaves dir behind on program restart

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1015]
Noticed a bunch of empty leftover dirs as well as completed jobs with a .1 or .2 at the end of the dir name despite not having been downloaded more than once. Version 2.2.1 but this bug probably already existed in 2.2.0.

To reproduce, enable direct unpack and restart the program while a job is partially unpacked. Afterwards, there'll be an empty dir with the original jobname and (once direct unpack kicks in again...) another one with .1 at the end with a file inside. Repeating the process results in dirs with .2, .3 and so on.

**Comment by Safihre** [comment]
How do you restart sabnzbd? Using the command inside the interface?

**Comment by jcfp** [comment]
From the web interface when I was testing this, don't think it makes a diff though

**Comment by Safihre** [comment]
If you ctrl-c or force kill it,  it indeed will leave directory, but on restart it should do a cleanup. I'll look into it.

**Comment by Safihre** [comment]
I can't reproduce this. For me they get nicely removed. 
Can you check the logs on Debug? It should say Aborting all unpackers and then list the files and folders it's going to delete.

**Comment by jcfp** [comment]
Weird, it seems to have stopped here as well? I'll keep an eye on things and reopen if need be. Thanks

**Comment by Safihre** [comment]
I also have noticed sometimes it leaves dirs behind, but never was able to pinpoint why. I always blamed my virusscanner for blocking the folder, but if you also see it on other platforms it might be something in the code.

**Comment by flower1024** [comment]
this happens for me as well when i do "systemctl sabnzbd restart" or restart my system on archlinux
