### ISSUE TITLE
Error importing sabyenc on Asustor

### ISSUE THREAD

**Issue by Diak** [sabnzbd/sabnzbd#1016]
Hi,

I have installed the last release of SABNzbdplus on Asustor App Central providen by Clinton Hall (version 20170815) and i still have the error message "SABYenc module... NOT found! Expecting v3.0.2 - https://sabnzbd.org/sabyenc".

So i checked the installation : 
```
# ps aux | grep sabnzbd
12383 admin      0:41 /usr/local/bin/python2.7 SABnzbd.py -f /usr/local/AppCentral/sabnzbdplus/config/sabnzbd.ini --browser 0 --daemon --pid /usr/local/AppCentral/sabnzbdplus
```

/usr/local/bin/python2.7 is a symbolink link to /usr/local/AppCentral/python/bin/python2.7

I reinstalled sabyenc : 
```
# /usr/local/bin/pip uninstall sabyenc
Uninstalling sabyenc-3.0.2:
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/DESCRIPTION.rst
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/INSTALLER
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/METADATA
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/RECORD
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/WHEEL
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/metadata.json
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2.dist-info/top_level.txt
  /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so
Proceed (y/n)? y
  Successfully uninstalled sabyenc-3.0.2
```
```
# /usr/local/AppCentral/python/bin/pip2.7 install sabyenc --upgrade
Collecting sabyenc
Installing collected packages: sabyenc
Successfully installed sabyenc-3.0.2
```

Then I checked the installation : 
```
# /usr/local/AppCentral/python/bin/python2.7 -c "import sabyenc ; print sabyenc.__version__ "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: internal error
```

What can I do to make sabyenc functional please ?

Diak

**Comment by Safihre** [comment]
Are there tools to compile on there? You could clone or download the Sabyenc repository and try `setup.py install`?

**Comment by Diak** [comment]
Thanks for the answer.
I cloned the sabyenc repository and execute the installation : 
```
# python setup.py install
running install
running bdist_egg
running egg_info
creating sabyenc.egg-info
writing sabyenc.egg-info/PKG-INFO
writing top-level names to sabyenc.egg-info/top_level.txt
writing dependency_links to sabyenc.egg-info/dependency_links.txt
writing manifest file 'sabyenc.egg-info/SOURCES.txt'
reading manifest file 'sabyenc.egg-info/SOURCES.txt'
writing manifest file 'sabyenc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_ext
building 'sabyenc' extension
creating build
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/src
arm-marvell-linux-gnueabi-gcc -fno-strict-aliasing -I/asustor/trunk_2016_01_06/arm/arm/staging/usr/include -I/asustor/trunk_2016_01_06/arm/arm/staging/usr/builtin/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/AppCentral/python/include/python2.7 -c src/sabyenc.c -o build/temp.linux-armv7l-2.7/src/sabyenc.o -O2
creating build/lib.linux-armv7l-2.7
arm-marvell-linux-gnueabi-gcc -shared -Wl,--as-needed -L/asustor/trunk_2016_01_06/arm/arm/staging/lib -L/asustor/trunk_2016_01_06/arm/arm/staging/lib64 -L/asustor/trunk_2016_01_06/arm/arm/staging/usr/lib -L/asustor/trunk_2016_01_06/arm/arm/staging/usr/lib64 -L/asustor/trunk_2016_01_06/arm/arm/staging/usr/builtin/lib -L/asustor/trunk_2016_01_06/arm/arm/staging/usr/builtin/lib64 build/temp.linux-armv7l-2.7/src/sabyenc.o -L/usr/local/AppCentral/python/lib -lpython2.7 -o build/lib.linux-armv7l-2.7/sabyenc.so
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
copying build/lib.linux-armv7l-2.7/sabyenc.so -> build/bdist.linux-armv7l/egg
creating stub loader for sabyenc.so
byte-compiling build/bdist.linux-armv7l/egg/sabyenc.py to sabyenc.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying sabyenc.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying sabyenc.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying sabyenc.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying sabyenc.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
writing build/bdist.linux-armv7l/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/sabyenc-3.0.2-py2.7-linux-armv7l.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing sabyenc-3.0.2-py2.7-linux-armv7l.egg
Copying sabyenc-3.0.2-py2.7-linux-armv7l.egg to /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages
Adding sabyenc 3.0.2 to easy-install.pth file

Installed /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2-py2.7-linux-armv7l.egg
Processing dependencies for sabyenc==3.0.2
Finished processing dependencies for sabyenc==3.0.2
```

Then i checked again the installation : 
```
# /usr/local/AppCentral/python/bin/python2.7 -c "import sabyenc ; print sabyenc.__version__ "
/usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2-py2.7-linux-armv7l.egg/sabyenc.py:3: UserWarning: Module sabyenc was already imported from /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc-3.0.2-py2.7-linux-armv7l.egg/sabyenc.pyc, but /volume1/.@root/sabyenc is being added to sys.path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/sabyenc.py", line 7, in <module>
  File "build/bdist.linux-armv7l/egg/sabyenc.py", line 6, in __bootstrap__
ImportError: /root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so: internal error
```

**Comment by Safihre** [comment]
Wow euhm I wouldn't know.. I search the internet and cannot find this `__bootstrap__` error anywhere.
This could be some C-code that doesn't compile on your system for some reason. But on other ARM systems it is working..
@sanderjo Which ARM do you have again? `armv__`

**Comment by Diak** [comment]
Try how ?
I can tell that sabnzbd tells me it's found so i guess it's functionnal.
Otherwise how can i check it's working fine ?

**Comment by Safihre** [comment]
If it's logged as found, it's working. 
Not sure how to debug this without access to the device and going over it line by line.

**Comment by Diak** [comment]
I imagine. 
If i can help you to help me don't hesitate.

**Comment by thezoggy** [comment]
the error is saying your importing a module that already exists..  
info about asustor toolchain:
http://developer.asustor.com/document/App_Central_Developer_Guide_2.0.0_0801.pdf

**Comment by Diak** [comment]
As i say in my first message, i deleted old installation beforce reinstalling it from pip command.
I will delete it again this evening (i'm at work now) and reinstalling from source.
Otherwise i don't know what i can do. Do you see another action i can try ?

**Comment by Safihre** [comment]
How about doing an upgrade of the setuptools etc?
So:
`pip install setuptools --upgrade`
Then remove and re-compile and/or re-install from pip.

**Comment by sanderjo** [comment]
Relevant terms into Google https://www.google.nl/search?dcr=0&source=hp&q=python+ImportError%3A+%22internal+error%22+%22in+__bootstrap__%22 seem to suggest different Python versions/installations on your system.

**Comment by sanderjo** [comment]
PS:

I see you now what three different (possible) location for sabyenc.so ... so let's check them: what is the output of

```
file /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so
file /root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so
file /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so
```

**Comment by Diak** [comment]
Hi.

Thanks for your help.
First I confirm I have several python installation. The default python binary location is /opt/bin/python.
But sabnzbd doesn't use this one but /usr/local/bin/python2.7 which is a symblink link to /usr/local/AppCentral/python/bin/python2.7

If i don't specify sabnzbd python path i have : 
```
# python -c "import sabyenc ; print sabyenc.__version__ "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sabyenc
```

If i specify sabnzbd python path i have : 
```
# python -c "import sabyenc ; print sabyenc.__version__ "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sabyenc
root@DKNas:/volume1/.@root # /usr/local/bin/python2.7 "import sabyenc ; print sabyenc.__version__ "
/usr/local/bin/python2.7: can't open file 'import sabyenc ; print sabyenc.__version__ ': [Errno 2] No such file or directory
```

The result of file command tests is : 
```
# file /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so
/volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
# file /root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so
/root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
# file /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so
/usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, with debug_info, not stripped
```
All paths are correct...

But the test you suggest at the end give me the same result for each path with the sabnzbd python binary launched : 
```
# /usr/local/bin/python2.7
Python 2.7.10 (default, Jan  6 2016, 14:39:32)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import imp
>>>
>>>
>>> sabyenc = imp.load_dynamic('sabyenc', '/usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: internal error
>>>
>>>
>>>
>>> sabyenc = imp.load_dynamic('sabyenc', '/root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /root/.python-eggs/sabyenc-3.0.2-py2.7-linux-armv7l.egg-tmp/sabyenc.so: internal error
>>>
>>>
>>>
>>> sabyenc = imp.load_dynamic('sabyenc', '/volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: internal error
```

Or with the default python binary it works fine : 
```
# python
Python 2.7.13 (default, May 30 2017, 23:22:25)
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import imp
>>>
>>>
>>> sabyenc = imp.load_dynamic('sabyenc', '/usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so')
>>>
>>> dir(sabyenc)
['__doc__', '__file__', '__name__', '__package__', '__version__', 'decode_usenet_chunks']
>>> sabyenc.__version__
'3.0.2'
>>>
```

I guess it means i have to install sabyenc with the default python pip command and then configure sabnzbd to use the default python binary (in the start script i guess) ?

**Comment by Diak** [comment]
I did some actions but it didn't solve the problem : 
- I uninstalled default python binary which was installed from entware-ng 
- I uninstalled python and sabnzbdplus from Asustor App Central
- I installed python and sabnzbdplus from Asustor App Central
- I executed "pip install sabyenc --upgrade" command (which pip : /usr/local/bin/pip)
- I executed "python -c "import sabyenc ; print sabyenc.__version__ " command (which python : /usr/local/bin/python = same as saznbdplus) : 
```
$ python -c "import sabyenc ; print sabyenc.__version__ "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so: internal error
```

Still same problem :(

**Comment by sanderjo** [comment]
So, with the default python you can run successfully run `sabyenc = imp.load_dynamic('sabyenc', '/usr/local/AppCentral/python/lib/python2.7/site-packages/sabyenc.so')` and use it.

I would use that as workaround for SABnzbd. 
Not nice, but "als het niet kan zoals het moet, dan moet het maar zoals het kan" ... ;-)

**Comment by Diak** [comment]
Sorry i d'on't speak german/dutch ^^

I uninstalled old default python installed with opkg (entware-ng) to avoid problem with multiple python installation.
I can reinstall it but it means that after each update of sabnzbd i have to edit start/stop script to put the python path. Not nice indeed. 
I'll try it tonight if there's not a better idea ^^

**Comment by thezoggy** [comment]
by any chance have you reached out to Clinton Hall about sab on asustor to see if others have ran into this issue?

while we produce sab we have nothing to do with the package being released at: https://www.asustor.com/apps/app_detail?id=98

**Comment by Diak** [comment]
Alleluia it works !!!

So i reinstalled python and python-pip with opkg command.
Then i installed sabyenc with pip command.
The problem was the same than before : asustor python installation show an error with sabyenc module but opkg python installation works.
So i replace sabnzbdplus python binary (/usr/local/AppCentral/python/bin/python2.7) with a symlink to /opt/bin/python.
After restart no more sabyenc module missing message 👍 

Thank you @Safihre and @sanderjo for your help :)

@thezoggy : i didn't contact even if i know you unfortunately don't provide nas packaging because i suspected a python problem with sabyenc module. Moreove on his github i don't see any sabnzbdplus project but only nzbget one so i prefered coming here and i don't regret ^^

Maybe one day i will try to install/compile par2-multiprocess command but that's all for now ;)

See ya.  

PS : should i close the topic ?

**Comment by Safihre** [comment]
Good to hear :)

**Comment by thezoggy** [comment]
@Diak the reason I bring it up is because per the asustor site you can see clinton is the one that maintains it.

**Comment by Diak** [comment]
Yes i know and i had been on his github repository (https://github.com/clinton-hall?tab=repositories).
But i didn't find information about sabnzbdplus asustor project.
And i didn't want to communicate by email too.

By the way my problem is solved and i won 2 MB/s in download speed so i'm happy and i thank you all for your help :)
