### ISSUE TITLE
Repair failed, not enough repair blocks (repair not needed)

### ISSUE THREAD

**Issue by KoalaBear84** [sabnzbd/sabnzbd#1020]
Sabnzbd 2.2.1 [bcc4dd7]

I get the error message: "Repair failed, not enough repair blocks (422 short)"

Saw that Sab didn't remove the files, so I tried to open it with MultiPar 1.2.2.9, everything OK. Everything was OK, the RAR files and all PAR2 files were downloaded.

Opened it with 7zip, unpacked the RAR's, also without problems. Did a Retry, but ends up in the same error.

I will send the details with a PM/mail!

Thanks Safihre

**Comment by Safihre** [comment]
The NZB was having par2-ception, the uploader created par2 files and then created another par2 with the whole set plus it's par2 inside it.
This is too much of uploader-error for SABnzbd to able to deal with I am afraid.
