### ISSUE TITLE
For discussion: Report if "Download size" is smaller than size reported in rar-files

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1031]
A suggestion for discussion: is this a useful, relevant use case?

**Short**: SAB can see in the rar files being downloaded what the resulting file size will be. If that is bigger than the size of the NZB being downloaded (which SAB also knows), don't bother downloading.

**Long**
I was downloading a 1.5GB file (as reported by SAB). After downloading, SAB said "RAR files failed to verify" and "Retry". Retry didn't work.

There were a few rar files. I ran "unrar l ..." on one of them:

```
 Attributes      Size     Date    Time   Name
----------- ---------  ---------- -----  ----
    ..A.... 26895094555  2017-08-06 02:20  BlaBla.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX.NLsubs/BlaBla.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX.NLsubs.mkv
----------- ---------  ---------- -----  ----

```
Ah: Size = 26895094555 = 26.895.094.555 = 26GB. So much bigger than the 1.5GB. So SAB could have known that this was not going to work. 
And thus my suggestion is: Let SAB inspect the rar file, and if it's bigger than the total post being downloaded, report that and/or stop downloading. So a bit like how SAB handles encrypted rars.

**Comment by thezoggy** [comment]
the 'size' of the nzb for the same release can be all over the place. sickbeard for example will pull down a season pack and split out the episode it needs.. thus the size of the nzb may be x gigs but the actual download is only a portion. then you have things that are cross posted, and depending on the indexer this sometimes means that it gets grouped into the same nzb file.. thus doubling+ the actual download size.. but majority of that download actually gets filtered out by sab due to duplicate articles and such.  anyways i would not want to go down this path of worrying about nzb download sizes.. plenty of scripts/apps out there that already 'worry' about it because the indexer reports back the media size and sizes are keyed off that.

**Comment by Safihre** [comment]
@thezoggy That's not what @sanderjo is proposing. He only wants detection for downloads that are too small for what they should be. For example bad indexers. I have also seen it a couple of times that only a few of the rar-files are actually included in the NZB.
Those cases @sanderjo suggests could be tackled by doing a quick compare with the full NZB size.

**Comment by Safihre** [comment]
@sanderjo As I expected, `RarFile` can give us this information:
```python
>>> import sabnzbd.utils.rarfile as rf
>>> aa=rf.RarFile('xxxx.part01.rar')
>>> aa.infolist()[0].file_size
4261709712L
```
~4GB, even though this is only the first rar-file.

**Comment by sanderjo** [comment]
> ~4GB, even though this is only the first rar-file.

No problem ... as long as SAB also is downloading something with size >= 4GB.

There would a problem if SAB thinks "hey, that's weird: a rar says 4GB, but I'm only downloading 1 GB".

@Safihre Please advice: I've put a debug-print after the META-DATA-print:

```
$ cat ~/.sabnzbd/logs/sabnzbd.log | grep "2017-09-13"  | grep -B2 -A1 SJ
2017-09-13 11:06:22,675::INFO::[nzbstuff:524] File Blareftestnzb e1db68be-234b-11e7 - "Bla.vol126+73.par2" yEnc (1/13) added to queue
2017-09-13 11:06:22,676::DEBUG::[nzbstuff:554] META-DATA = {}
2017-09-13 11:06:22,679::DEBUG::[nzbstuff:555] SJ: nzo.bytes is 121326495
2017-09-13 11:06:22,680::INFO::[__init__:613] Backing up /home/sander/nzb_backup_dir/reftestnzb e1db68be-234b-11e7.nzb.gz
```

OK ... That is right after **adding** it to the queue, correct? How can I see it of the post being downloaded?

**Comment by thezoggy** [comment]
@Safihre I guess i'm just not following or have experienced what your talking about then

**Comment by jcfp** [comment]
I suppose rar reports the size of the extracted/original file. That means the check as proposed is only reliable if the archived files cannot be compressed or the archive doesn't use compression in the first place.

I can imagine either situation being fairly common with certain types of files though, such as video. Does rarfile provide any info about the (lack of) compression in an archive or the achieved compression ratios?

**Comment by sanderjo** [comment]
Hi @jcfp, thanks for your remark!

> Does rarfile provide any info about the (lack of) compression in an archive or the achieved compression ratios?

Yes: `sabnzbd/utils/rarfile.py` tells:
```
        file_size
            Uncompressed size.

        compress_size
            Compressed size.
```


So I've put some extra logging into my SABnzbd instance, and did a download:
```
2017-09-18 21:03:11,439::DEBUG::[assembler:96] SJ101: nzo size of download is 247819448
2017-09-18 21:03:12,303::DEBUG::[assembler:263] SJ: size: 10364428 resp 5741300 filename: blabla 2017 mp3/09. bbb (Instrumental).mp3. And OS is 2
2017-09-18 21:03:12,304::DEBUG::[assembler:263] SJ: size: 9573915 resp 9475374 filename: blabla 2017 mp3/10. Gruder (Instrumental).mp3. And OS is 2
2017-09-18 21:03:12,305::DEBUG::[assembler:263] SJ: size: 8336945 resp 8294145 filename: blabla 2017 mp3/11. Surmen (Instrumental).mp3. And OS is 2
2017-09-18 21:03:12,306::DEBUG::[assembler:263] SJ: size: 10468885 resp 10431824 filename: blabla 2017 mp3/12. ccc (Instrumental).mp3. And OS is 2
2017-09-18 21:03:12,310::DEBUG::[assembler:263] SJ: size: 0 resp 0 filename: blabla 2017 mp3. And OS is 2
```
So, note the line `size: 10364428 resp 5741300` (from `i.file_size, i.compress_size`): 10MB uncompressed, versus 5.7MB compressed in the rar. "Interesting" that a mp3 can be further compressed...

Anyway: I should sum up the compress_size-s, and the sum should not be bigger than the download size.




Totally unrelevant, but funny:

```
        host_os
            Host OS type, one of RAR_OS_* constants.
```
with
```
RAR_OS_MSDOS = 0
RAR_OS_OS2   = 1
RAR_OS_WIN32 = 2
RAR_OS_UNIX  = 3
RAR_OS_MACOS = 4
RAR_OS_BEOS  = 5
```
So we can gather statistics on the favorite OS of posters ... :+1:

**Comment by sanderjo** [comment]
I'll close this issue until I have the time to implement it.
