### ISSUE TITLE
sab 2.3.0RC2 -- stats

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1032]
FF 55.0.3, can see the month+year gets cut off:
![sab](http://zoggy.net/firefox_2017-09-15_15-44-09.png)

**Comment by Cpuroast** [comment]
I can confirm, Firefox cuts the month+year, Safari also does but to a lesser extent:

Firefox: September 2
Safari: September 201
Chrome: September 2017
