### ISSUE TITLE
sabyenc - being disabled if too new

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1033]
I updated sabyenc  on a friends box expecting to update to RC2.. however due to jcfp it only updated to RC1. Thus now I get: ` SABYenc disabled: no correct version found! (Found v3.1.1, expecting v3.0.2) `

I would NOT expect to see this as 3.1.1 > 3.0.2. We should not disable sabyenc if the version installed is newer than expected.

**Comment by Safihre** [comment]
We require a specific version, like `==`.
I don't want to have to deal with potential version specific quirks in the future when there's potential breaking changes.

**Comment by thezoggy** [comment]
well thats unfortunate because all the ppa peeps will have newer sabyenc than expected.. thus 'upgrading' actually results in degraded performance because of this scenario

**Comment by Safihre** [comment]
No, because they use the `sab-addons` PPA which is on purpose still on 3.0.2.

**Comment by thezoggy** [comment]
yeah, only if its a new install.. sab-addons didnt exist when this box was originally setup with sab.. as it ended up using pip to get sabyenc, thus the issue at hand :/

**Comment by Safihre** [comment]
Only until the end of next week, then 2.3.0 should come out :)
