### ISSUE TITLE
SabNZBD 2.2.1

### ISSUE THREAD

**Issue by swedishstyle** [sabnzbd/sabnzbd#1035]
Since the update to 2.2.1, I've noticed some downloads will get 'stuck' on 100% checking, and never finish, IE start downloading. Pausing and unpausing the item in question fixes this issue, but it seems to happen at random and I can't see a pattern

**Comment by thezoggy** [comment]
upgrade to 2.3.0 and see if this fixes it for you..

**Comment by swedishstyle** [comment]
Huh - wasn't aware there was a newer version! I'll try that

**Comment by Safihre** [comment]
It's testing release, but should be final by end of the week.

**Comment by Safihre** [comment]
Reopen if issue continues in 2.3.0.
