### ISSUE TITLE
 SABYenc disabled: no correct version found (Found v3.3.0, expecting v3.0.2)

### ISSUE THREAD

**Issue by nzbjamz** [sabnzbd/sabnzbd#1036]
Using 2.2.1 it upgraded SABYenc on launch. Then I was notified via a message that:

![](https://user-images.githubusercontent.com/25286297/30598901-de2e193a-9d0f-11e7-9cb2-738a8b26431a.png)

**Comment by Safihre** [comment]
Use
```
pip install sabyenc==3.0.2
```
