### ISSUE TITLE
SABnzbd 2.3.0 doesn't run on 10.9, 10.10 and 10.11.

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1037]
I've tried every 2.3.0 build, alpha1, alpha2, rc1, rc2 and final.

The previous stable, 2.2.1, runs perfectly.

They report the same error message: 
“SABnzbd.app” is damaged and can’t be opened. You should move it to the Trash"

 spctl --assess --continue --verbose /Applications/SABnzbd.app
/Applications/SABnzbd.app: a sealed resource is missing or invalid

and yet:

codesign -v --verbose /Applications/SABnzbd.app
/Applications/SABnzbd.app: valid on disk
/Applications/SABnzbd.app: satisfies its Designated Requirement

Console logs:
CoreServicesUIAgent[300]: Error SecAssessmentCreate: The operation couldn’t be completed. (OSStatus error -67055.)
Error -60005 creating authorization

This is on a user's computer that had issues running 2.3.0.

Has something changed concerning code signing since 2.2.1?

**Comment by Safihre** [comment]
Nothing changed, the codesign is still the same. We use a very different python version, but it works fine on other version of macOS right?
Is there a way to display what file might have changed?

**Comment by Safihre** [comment]
Can you do `codesign --verify --verbose --deep`? I think it should show what the problem is.

**Comment by Cpuroast** [comment]
I don't have access to to the 10.10.5 box anymore, but even weirder is another 10.10.5 box has a diff error with all 2.3.0 releases:

2017-09-22 10:54:06.000 AM kernel[0]: AMFI: Error! There is a null code directory pointer. This is an unexpected condition.
[10:55:08] <ll> 2017-09-22 10:54:06.126 AM SABnzbd[2528]: SABnzbd+ Error

very descriptive :)

2.2.1 still runs.

As usual with the "current +2 previous versions" support pattern, Apple will be dropping support for 10.10 this year with 10.13's upcoming release, due September 25.

Maybe it's time to do so also, and require 10.11 and up.

**Comment by Safihre** [comment]
@Cpuroast Since I don't have a Mac and only a mega-slow VirtualBox with macOS I am dependent on you for debugging 😉  Or anyone else experiencing this issue!
Maybe we can resolve it..

**Comment by Cpuroast** [comment]
10.11 machine now:

Process:               SABnzbd [1237]
Path:                  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
Identifier:            org.sabnzbd.team
Version:               2.3.0 (0.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SABnzbd [1237]
User ID:               501

Date/Time:             2017-09-22 22:44:04.201 +0200
OS Version:            Mac OS X 10.11.6 (15G1611)
Report Version:        11

Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Applications/SABnzbd.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by Cpuroast** [comment]
Confirmed on another 10.11 box.
2.3.0 doesn't run on 10.10 and 10.11 it seems.
I don't have 10.9 to test.

**Comment by Safihre** [comment]
I will try to rebuild on Travis using OS X 10.10 (lowest they offer), maybe that is better.

**Comment by Cpuroast** [comment]
as per https://docs.travis-ci.com/user/reference/osx/#Xcode-version

Our Xcode 8.3.3 images have the following SDKs preinstalled:
macosx10.12

Our Xcode 6.4 images have the following SDKs preinstalled:
macosx10.9
macosx10.10

Probably worth building with xcode6.4 until you decide to drop 10.9 and 10.10 support, then you can switch to building with xcode7.3 or xcode8 which is 10.11 and up.

**Comment by Cpuroast** [comment]
Chrome and Firefox support 10.9 and up, but I suspect they may put 10.9 on the chopping block shortly after 10.13 ships on Sept 25th.

**Comment by Safihre** [comment]
@Cpuroast https://travis-ci.org/sabnzbd/sabbuild/builds/278798241
https://github.com/sabnzbd/sabbuild/releases

Not ready yet, but when it is, maybe you can test that version?

**Comment by Safihre** [comment]
Wow [this took ages](https://travis-ci.org/sabnzbd/sabbuild/builds)..
@Cpuroast Can you test these new builds on all your systems? Also Sierra ones, if possible 👍 
https://github.com/sabnzbd/sabbuild/releases/tag/2.3.0-osxtest-19

**Comment by Cpuroast** [comment]
So far osx-test-19 runs on 10.11 and and 10.12, so that's 1 more than the release build, I'm still waiting to test on 10.10 and 10.9

**Comment by Cpuroast** [comment]
I'd nearly be inclined to rollback the public download on the main web page to 2.2.1 until a fixed 2.3.1 is released when I can confirm test19 runs on all supported OSes.

There's a lot of people still running 10.9 to 10.11, I'd say ~40-50%

**Comment by Safihre** [comment]
I'll overwrite the current macOS file after you confirm the new version is better, and put a note on the downloads page and forum.
So far we had 2000 downloads but no bug reports, aside from yours. So hoping that most of them are Sierra's.

**Comment by Cpuroast** [comment]
The majority of them will be, would be nice to be able to track that.
Like maybe the update checker in sab could report OS back, to see what the mac sab user base is composed of.

**Comment by Cpuroast** [comment]
I'd consider incrementing it to 2.3.1, so people know it's a new version, silent updates aren't great.

**Comment by Safihre** [comment]
Analytics knows: 💯 
![image](https://user-images.githubusercontent.com/5703454/30774525-48009d52-a084-11e7-9666-49dce68a031b.png)

**Comment by Cpuroast** [comment]
Confirmed to run on 10.10 :)
Still waiting for 10.9.

**Comment by Cpuroast** [comment]
Setting up a copy of VMware Fusion 8.5 with macOS 10.9, 10.10 and 10.11 :)
Should simplify my life greatly and I'll be able to easily test sab on all versions of macOS :)

**Comment by Safihre** [comment]
> Should simplify my life greatly and I'll be able to easily test sab on all versions of macOS :)

Great thanks! 🥇 !

**Comment by Cpuroast** [comment]
All 3 OSes installed, doing apple updates, then it's snapshot time on all 3, and then sab test :)

**Comment by Cpuroast** [comment]
I can firm that test-19 runs on 10.9.

test-19 runs on 10.9, 10.10, 10.11 and 10.12

I would assume 10.13 also, but I don't have a VM with that until it's released on the 25th.

**Comment by Safihre** [comment]
Thanks so much!!

I looked at the numbers and since the release only ~150 people on old OSX versions downloaded 2.3.0. So instead of doing a 2.3.1 I choose to update the existing 2.3.0 file and show extra label [on the downloads page](https://sabnzbd.org/downloads).
Otherwise we will get many posts about confused 2.3.0 users on other platforms that don't understand why they didn't get update notice etc!

**Comment by Cpuroast** [comment]
OK, that works :)

**Comment by Safihre** [comment]
Will leave this open for a few days, for people having problems can read here that it was resolved!

**Comment by Safihre** [comment]
Seems we're all good!

**Comment by Cpuroast** [comment]
Just wanted to add that the new 2.3.0 build also runs in 10.13 final, also added it to my VMware Fusion setup.

**Comment by Safihre** [comment]
Good :) There was this post on the forum, so not sure what the problem is on his system: https://forums.sabnzbd.org/viewtopic.php?f=2&t=23001

**Comment by Cpuroast** [comment]
He had this error, which is the exact same error I had reported above on 10.11.
So yeah he was running the old 2.3.0 build.

-------------------
Dyld Error Message:
Symbol not found: _getentropy
Referenced from: /Applications/SABnzbd.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
Expected in: /usr/lib/libSystem.B.dylib
-------------------
