### ISSUE TITLE
SABYenc disabled: no correct version found! (Found v3.0.2, expecting v3.3.1)

### ISSUE THREAD

**Issue by Damien360** [sabnzbd/sabnzbd#1039]
Hi,

On an Asustor NAS, I keep getting this message in SAB but if I check, I get:
`/usr/local/AppCentral/python/bin/python2.7 -c "import sabyenc ; print sabyenc.__version__ "
3.3.1`
Or
`python -c "import sabyenc ; print sabyenc.__version__ "
3.3.1`

**Comment by Safihre** [comment]
Try removing it first, using `pip uninstall sabyenc` (might give error, that's oke, maybe running it twice to be sure)
And then install again the new one.

**Comment by Damien360** [comment]
Already tried this, but just tried again.
`pip uninstall sabyenc
Uninstalling sabyenc-3.3.1:
  /volume1/.@plugins/AppCentral/entware-ng/opt/lib/python2.7/site-packages/sabyenc-3.3.1-py2.7.egg-info
  /volume1/.@plugins/AppCentral/entware-ng/opt/lib/python2.7/site-packages/sabyenc.so
Proceed (y/n)? y
  Successfully uninstalled sabyenc-3.3.1
`
And
`pip install sabyenc --upgrade
Collecting sabyenc
  Using cached sabyenc-3.3.1.tar.gz
Installing collected packages: sabyenc
  Running setup.py install for sabyenc ... done
Successfully installed sabyenc-3.3.1
`
Restarted SAB: still same message

**Comment by Safihre** [comment]
Seems like a different python version is running sabnzbd then the one that installs it. Seems to be common on qnap/Asus.. Wouldn't know how to fix.

**Comment by Safihre** [comment]
In sabnzbd, om the first page of the Config, maybe you can see which python is running it?

**Comment by Damien360** [comment]
Yes, like for this issue https://github.com/sabnzbd/sabnzbd/issues/1016

The version used by SAB is /usr/local/AppCentral/python/bin/python2.7
But in my case :``/usr/local/AppCentral/python/bin/python2.7 -c "import sabyenc ; print sabyenc.__version__ "
3.3.1``

**Comment by Safihre** [comment]
Find all `sabyenc.so` files, they should be in `site-packages` directories.

**Comment by Damien360** [comment]
I've got those:
`/volume1 $ find . -name sabyenc.so
./.@plugins/AppCentral/entware-ng/opt/lib/python2.7/site-packages/sabyenc.so
./.@plugins/AppCentral/sabnzbdplus/repository/python/sabyenc.so
./.@plugins/AppCentral/sabnzbdplus/repository-32/python/sabyenc.so
./.@plugins/AppCentral/python/lib/python2.7/site-packages/sabyenc.so`

**Comment by Safihre** [comment]
That's quite a lot... Remove all of them 🔫 
Then we can find the right python instance!

**Comment by Damien360** [comment]
Thanks, Fixed!

I removed all those.
Then did `pip uninstall sabyenc` to make sure everything is removed, and then `pip install sabyenc` and now it works!

**Comment by Safihre** [comment]
Nice, good to know! 👍

**Comment by ITOpsMgr** [comment]
same issue here, deleting the 'sabyenc.so' and reinstalling sabyenc fixed the issue, cheers!
