### ISSUE TITLE
SABnzbd not able to detect new SABYenc

### ISSUE THREAD

**Issue by kaplannn** [sabnzbd/sabnzbd#1040]
Hi Guys,

So i updated SABnzbd to the latest release (2.3.0 [ba7d906]). It says now, i have to update SABYenc to 3.3.1.

I went to the wiki and updated it by repo:

"python-sabyenc is already the newest version (3.3.1-0ubuntu1~jcfp1~16.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."

If i check the version with "python -c "import sabyenc ; print sabyenc.__version__ ": is says "3.0.2".

when i do this "pip install sabyenc==3.3.1" it will cause this:

![image](https://user-images.githubusercontent.com/17184697/30917576-9f320956-a39c-11e7-81d1-1669f1111a5b.png)

Do you guys have any advice? 

Thanks :)

**Comment by Safihre** [comment]
I see in the screenshot `python3` so maybe you should repeat it but write pip2 or
```
python2 -m pip install sabyenc
```

Have you restarted your system in between?

**Comment by Safihre** [comment]
Seems maybe same problem as here: https://forums.sabnzbd.org/viewtopic.php?f=2&t=23004
In case above doesn't work, try what he did in the forum post.

**Comment by kaplannn** [comment]
The first one did it. much appreciated :)

always these different python version .... :/ Thanks!

**Comment by Safihre** [comment]
Added an extra note to the wiki page!
https://sabnzbd.org/wiki/installation/sabyenc.html
