### ISSUE TITLE
Attempt to decode and sort all article filenames first for direct unpacking

### ISSUE THREAD

**Issue by cryzed** [sabnzbd/sabnzbd#1044]
I've seen sabnzbd process a few NZBs where initially all the NZF filenames are just hashes?, and the NZFs will be sorted alphabetically based on those, instead of the later decoded actual filename (once the download of the NZF starts).

Considering the latest addition of the direct unpacking feature, it might be worth considering adding a feature that queues every NZF of a NZB until the decoder has managed to verify all filenames and then base the download order of the sorted filenames. This would allow direct unpacking to work from the very beginning of the download.

**Comment by Safihre** [comment]
Absolutely that would be great and I also thought about it, but I got stuck.
SABnzbd only loads the article list for each file when it actually starts downloading is, to conserve memory. So have to find a memory efficient way to handle all first articles seperate.
Then after downloading, what do we do with the resulting data. Say we have a job with 100 files, each article is 700KB, so we have 70MB of articles in memory that can only be written to disk when the other articles of the file are ready.

We could for example only activate this feature if enough memory is available.

**Comment by cryzed** [comment]
I'm not entirely sure how sabnzbd downloading internals work, but I don't think it would be too unreasonable to download the "part headers" first, write the decoded data to disk (directly to the real NZF filename), and later continue downloading them where we left off and append to the existing NZF.

So to sum up: at the beginning of a new NZO maybe let it enter a special state "Preload", where each NZF with the corresponding NZO stays active (in the downloading queue) until the actual filename could be determined (or it could be determined that it _couldn't_ be determined). After this, write the decoded raw data to the NZF on disk and queue the next download. Once all NZF filenames have been verified the NZO changes state to the regular download state at this point.

I _very likely_ am missing something obvious and this is much harder, correct?

**Comment by shypike** [comment]
@cryzed Looking from the outside this is a perfectly reasonable question. However, this thing is deeply embedded into the way the software was setup. We're a bit hesitant to change such a fundamental part of the download chain.
Originally (many years ago) SABnzbd indeed tried to get the real files names as soon as possible, but with many side effects (such as memory usage).
Given the way many posts are done nowadays, it is worth investigating the option though.

**Comment by aleqcz** [comment]
Great, thanks Safihre!

**Comment by cryzed** [comment]
Awesome, thanks!

**Comment by soifs** [comment]
Great job!
From what i ve seen the sorting (of these obfuscted files) is only done if direct unpack is enabled, can we have it without enabling it?

**Comment by Safihre** [comment]
@soifs the reason for that is the assumption that only slower systems have Direct Unpack disabled. Since this new method takes a bit more cpu and memory, I linked these 2 together.
Is there a benefit of having the sorting without Direct Unpack? The rename happens always.
