### ISSUE TITLE
Question: is it possible to set preferipv6 to False?

### ISSUE THREAD

**Issue by h3llrais3r** [sabnzbd/sabnzbd#1048]
I want to prefer usage of ipv4 over ipv6. Is it possible to configure this in Sabnzbd?

**Comment by Safihre** [comment]
Sure!
https://sabnzbd.org/wiki/configuration/2.3/special -> `ipv6_servers`

**Comment by h3llrais3r** [comment]
Still not clear what I should do...:(
Actually, I have a ipv6 newsserver only and a newsserver that is accessible over ipv4 and ipv6.
I only want to connect using ipv6 when only ipv6 is available. This because my ipv6 uses a tunnel, but my newsserver speed (of the one that supports both) is drastically cut when going through the tunnel.

**Comment by Safihre** [comment]
Set `ipv6_servers` to 0 will disable the use of IPv6, like it says in the text on the wiki.
You cannot set it on a per-server basis.

**Comment by h3llrais3r** [comment]
That's what I thought... So it's not really possible to prefer ipv4 over ipv6 for the servers?
Its either disable ipv6, use it when available or force usage?

**Comment by Safihre** [comment]
Exactly. The idea being that either IPv6 works well on the system, or it doesn't work at all.

**Comment by h3llrais3r** [comment]
I know, but since I'm using a tunnel, it's decreasing my download speed drastically... 😢

**Comment by h3llrais3r** [comment]
So I'm looking how I can prefer ipv4 over ipv6. Running on windows, so I found that this is possible via prefixpolicies, but this doesn't seem to have impact on Sabnzbd.

**Comment by Safihre** [comment]
You can set your IPv4-only server to a fixed IPv4-address, then it will always use IPv4 for that server. 
Just do a DNS-loopup of the servername. Usually these addresses rarely change.

**Comment by h3llrais3r** [comment]
That works indeed, but than I got a complaint above certificate validation and I need to decrease it to minimal...

**Comment by Safihre** [comment]
Have you tried changing `Server load-balancing` in Config > Switches to not prefer IPv6? (with normal server name, not IP-address)

**Comment by h3llrais3r** [comment]
Thanks for the excellent tip! That did the trick! Now my download is again at full speed!
Thanks for your excellent support!

**Comment by Safihre** [comment]
👍
