### ISSUE TITLE
DirectUnpacker still alive after download complete

### ISSUE THREAD

**Issue by gadgetking** [sabnzbd/sabnzbd#1050]
With sabnzbd 2.3.0, I see that Direct Unpacking is enabled. 

However what I am also seeing is that the 'Direct Unpacking' doesn't always complete and is left in a 'DirectUnpacker still alive' message flooding the logs. This prevents any post processing (such as nzbmedia or other post processing scripts) from completing.

**Comment by Safihre** [comment]
Can you try 2.3.1Beta1? It will abort any failing Direct Unpack after 2 minutes.

Could you maybe first enable debug-logging and then send me the logs after you abort one of these hanging jobs? safihre@sabnzbd.org
I would like to see in the logs why it can't complete and why SABnzbd doesn't detect the failure..

**Comment by Safihre** [comment]
@gadgetking Did you get more hangups?

**Comment by Safihre** [comment]
In case it happens again or to anybody else, it would be greatly appreciated if you could switch logging to Debug in the Status Window, cancel the hanging direct-unpacker and then send me the log.
