### ISSUE TITLE
Remove .'s and spaces from folder names 

### ISSUE THREAD

**Issue by DapOrp** [sabnzbd/sabnzbd#1056]
Recently upgraded from version 1.0 to 2.3 in one jump, retained configuration from 1.0

Finding that using the switches to strip spaces and .'s from folder names is not working as previously.  nzb's that contain .'s for spaces are converted to folders with spaces even with the convert spaces to underscores flag set.

Attempts to unset and reset the switches has not fixed the issue.

**Comment by Safihre** [comment]
Could you provide example filenames and how they should look after?
We did change the way the steps are processed when both switches are enabled.

**Comment by DapOrp** [comment]
Original NZB file name: The.Soup.2011.11.30.720p.HDTV.x264-MOMENTUM
With both switches (renaming .'s and renaming spaces) set the resulting folder name is: The Soup 2011 11 30 720p HDTV x264-MOMENTUM
The desired folder name would be: The_Soup_2011_11_30_720p_HDTV_x264-MOMENTUM

**Comment by DapOrp** [comment]
Thank you, the additional script is able to force the desired result.
