### ISSUE TITLE
Feature request: preserve pause state on shutdown/restart

### ISSUE THREAD

**Issue by CupricReki** [sabnzbd/sabnzbd#1062]
Just update to 2.3.1~rc2 on my Ubuntu 17.04 server. Before the update SABnzbd was paused. After the update SABnzbd automatically restarted and began downloading again.

I have a monthly data cap, if I didn't have a telegram bot I wouldn't have known that I was about to blast through it. 

Not sure if this is a bug or a feature request.

**Comment by Safihre** [comment]
@jcfp is there even something we can do about that?

On other platforms updates are manual and require user intervention. Preserving state could be interesting at some point, but has never been the way SABnzbd works so it would confusing for some users.

**Comment by thezoggy** [comment]
cant you just tell your init script or whatever to start sab in paused statue? (`-p`)

**Comment by CupricReki** [comment]
@thezoggy  I could but I don't always want to start in the pause state. I want to preserve the previous state.

**Comment by Safihre** [comment]
@thezoggy we already have the `start_paused` Special setting for that, this is a distinct future request to always preserve state.
Maybe it should indeed be an option.

**Comment by jcfp** [comment]
@Safihre I could change the package to not restart the service, but that would result in others complaining that it _isn't_ running as expected after an update, or cause a mixup of old sab with newer interfaces. Preserving state in sab would be a much nicer solution than any of that.

There is one "hack" @CupricReki could try though. Disable the service and then start it anyway via rc.local: basically do what's described [here](https://forums.sabnzbd.org/viewtopic.php?f=16&t=6125) but without out any test or check. With the service set to disabled, it gets shut down but not restarted on updates. Downside is the need to restart by hand after every package update.

**Comment by CupricReki** [comment]
@thezoggy thanks for pointing out `start_paused` this accomplishes about what I needed.

**Comment by Safihre** [comment]
I changed the title to make it into a feature request to have an option to preserve pause state on shutdown/restart.

**Comment by shypike** [comment]
There is already an option to start SABnzbd always in paused mode. Config->Special->start_paused. Isn't that enough for this use case?

**Comment by Safihre** [comment]
Maybe it is enough for this use case, but then you always have to check your SABnzbd after restarting your PC. So in general this feature request would be worthwhile.

**Comment by mesa57** [comment]
I am speaking for spotnet users who also want this feature.
So hoping this will come into a release soon.

**Comment by Safihre** [comment]
@mesa57  The Pause state of each item seperatly in the queue is definitely remember after a restart. Only the whole Queue pause state is not remembered. I use this very often.

**Comment by mesa57** [comment]
So a download item which is paused will not be unpaused after restart ?
Our observations with release 2.3.2 [1cac579] are different.

**Comment by Safihre** [comment]
It has always been like that since v0.7. Unless sabnzbd gets force killed, it's individual state is saved.

**Comment by mesa57** [comment]
Ok, we will test this further. 
We don't do a force kill, but issue an api shutdown command.
If needed, I will open a new issue.
