### ISSUE TITLE
When extracting sometimes sabnzbd deletes all the files..

### ISSUE THREAD

**Issue by plato79** [sabnzbd/sabnzbd#1063]
Well, this happened several times with the same nzb file with the direct extract. The NZB file was about 8 GB, and it had about 9 files inside. I watched the folder, and near the finish the folder had 9 mkv files with one of them a little smaller because the last archive was not complete. After job finished, sabnzbd discarded _UNPACK_ segment, and **DELETED** all the files in the folder. There are no scripts or something used and this only happened with one NZB...

Aaaand, I found the problem and this is pretty stupid. I was downloading "Body of Proof" and I think you could guess what happened. When sabnzbd sees there's a proof in the filename it assumes that it's proof file and decides to delete it because it's a sample file :P.. I should remove the sample filtering when downloading this but really, if sabnzbd decides to delete "proof" file, it should check its' extension because there are no proof files with "mkv" extension as far as I know.

**Comment by thezoggy** [comment]
can you share logs so we know what version of sab / what was going on

**Comment by plato79** [comment]
Version: 2.3.0 [ba7d906]
Python version: 2.7.14 (default, Oct 19 2017, 01:17:20) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)] [UTF-8]

.
.
.
`2017-10-27 08:39:03,190::INFO::[newsunpack:493] Set Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION completed by DirectUnpack`
`2017-10-27 08:39:03,190::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part01.rar`
`2017-10-27 08:39:03,191::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part02.rar`
`2017-10-27 08:39:03,192::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part03.rar`
`2017-10-27 08:39:03,192::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part04.rar`
`2017-10-27 08:39:03,193::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part05.rar`
`2017-10-27 08:39:03,193::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part06.rar`
`2017-10-27 08:39:03,194::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part07.rar`
`2017-10-27 08:39:03,195::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part08.rar`
`2017-10-27 08:39:03,195::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part09.rar`
`2017-10-27 08:39:03,196::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part10.rar`
`2017-10-27 08:39:03,196::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part11.rar`
`2017-10-27 08:39:03,197::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part12.rar`
`2017-10-27 08:39:03,198::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part13.rar`
`2017-10-27 08:39:03,198::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part14.rar`
`2017-10-27 08:39:03,199::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part15.rar`
`2017-10-27 08:39:03,199::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part16.rar`
`2017-10-27 08:39:03,200::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part17.rar`
`2017-10-27 08:39:03,201::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part18.rar`
`2017-10-27 08:39:03,201::INFO::[newsunpack:545] Deleting /media/download/tmp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.part19.rar`
`2017-10-27 08:39:03,202::INFO::[newsunpack:255] Unrar finished on /media/download/tmp/body of proof`
`2017-10-27 08:39:03,222::INFO::[postproc:346] unpack_magic finished on body of proof`
`2017-10-27 08:39:03,239::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E01.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,308::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,309::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E13.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,311::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E03.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,311::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E11.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,354::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E03.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,436::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E02.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,437::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E10.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,534::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E02.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,583::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E08.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,583::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E13.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,584::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E07.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,584::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E01.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,585::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E05.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,647::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E10.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,647::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E08.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,723::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E07.720p.HDTV.X264-DIMENSION.mkv`
`2017-10-27 08:39:03,795::INFO::[postproc:920] Removing unwanted sample file /media/TVtemp/body of proof/Body.of.Proof.S03E11.720p.HDTV.X264-DIMENSION.par2`
`2017-10-27 08:39:03,796::INFO::[postproc:519] Cleaning up body of proof (keep_basic=False)`

**Comment by Safihre** [comment]
Yes it will do this, it's a simple regular expression looking for the keywords.

Maybe indeed you are right, proof is never a video file. We could check for that, there must be other movies with that in the title. Although there must also be movies with "sample" in the title, there the detection would also fail. Nobody complained about that yet.

**Comment by shypike** [comment]
We used to have a feature that didn't even download "sample" files, but that failed miserably when posters put the sample and the real thing in the same par2-set.
Just remove the feature and let people add their own cleanup script?

**Comment by Safihre** [comment]
It's a nice feature, but it would be better to maybe make more clear what the limitations are in the documentation.
