### ISSUE TITLE
no history retention check on startup

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1065]
Currently, cleanup is only done at job completion and (scheduled for) midnight. Thus, the history may be retained much longer than configured on systems that aren't on 24/7 unless the user does daily downloads.

Please add a trigger so the retention check is also run at startup (or shortly thereafter).

**Comment by puzzledsab** [comment]
Are you sure it has ever done it at startup? The patch that marks it as completed only does it in postproc. `database.py` already has a `midnight_history_purge()`. I would rename it to `scheduled_history_purge()` and call it where applicable.

**Comment by Safihre** [comment]
But it should also do it at midnight using the Scheduler.. Or when the device comes back online after that.
