### ISSUE TITLE
unrar depdency is non-free

### ISSUE THREAD

**Issue by enlightenedliberal1** [sabnzbd/sabnzbd#1066]
Is there a reason to depend on the non-free component unrar as opposed to unrar-free or similar? NZBGet doesn't depend on this and doesn't seem to have any problems handling the same files sabnzbdplus handles.

Ceasing reliance on non-free versions would allow free systems like Debian to function without having to enable extra repositories and without worrying about whatever distribution or derivative development issues might arise from dependence on a non-free package.

**Comment by Safihre** [comment]
Nzbget includes the nonfree unrar inside all installers (Linux/Windows/macOS). 
 Free version is limited, as far as I understand it doesn't support RAR5 and has problems with password protected RAR3.
That seems like enough reasons for us not to take risks of users blaming us for failing downloads, while actually they just need the right unrar.

**Comment by jcfp** [comment]
The debian [bug reports](https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=unrar-free) for unrar-free say it all: no support for rar3 let alone rar5, no multipart archives, no password/encryption support, no large files, fails on 64 bit systems.

**Comment by Safihre** [comment]
Think that's more than enough reasons :)
