### ISSUE TITLE
downloads stuck "checking" with no active/used connections

### ISSUE THREAD

**Issue by brianjmurrell** [sabnzbd/sabnzbd#1068]
My sabnzbd (1.2.3) is currently in a state with 4 downloads that are are doing nothing that were in the "checking" state until I paused them and unpaused them.  They have been stuck that way for over 10h and are not progressing:

![screenshot from 2017-11-06 07-38-39](https://user-images.githubusercontent.com/559317/32441500-f91d64ae-c2c5-11e7-9ec2-7f68260fb09d.png)

I also have no active connections so it's not like they are waiting for available connections.

**Comment by Safihre** [comment]
...1.2.3? It has longgg been fixed. Please update.
https://sabnzbd.org/wiki/installation/install-unix

**Comment by brianjmurrell** [comment]
Ahhh.  So, I have been using _thecubic_'s repo referenced in the URL above that you pasted and it's what's stuck at 1.2.3.  Perhaps that URL should be removed from https://sabnzbd.org/wiki/installation/install-unix since it provides a very old version.

I'll switch to _nuxref_'s repo and get updated and see if that fixes it.

**Comment by thezoggy** [comment]
where do you see thecubic's repo referenced?
