### ISSUE TITLE
Grabber fetches indefinitely

### ISSUE THREAD

**Issue by enilfodne** [sabnzbd/sabnzbd#1069]
I've noticed sometimes when using `NZBhydra` (or anyone, using the API) to sends an `nzb` (to fetch) that there's an issue (rate/request/dl limit or simple removal), where `SABnzbd` will begin to retry, every minute, indefinitely.

I've checked the request url and indeed `NZBhydra` returns `HTTP 500` as the download fails due to rate limiting. As im not sure whether or not this is an actual issue, i will just add question that may start a discussion. Feel free to close/ignore this if not applicable.

- Should `SABnzbd` progressively increase the time to wait (i.e. 1/5/10/15 on the 1/2/3/4 attempt)?
- Should `SABnzbd` add more codes like `429/503` that some indexers are using to indicate limiting?

**Comment by Safihre** [comment]
In the case of 500/503/429, we cannot know what is happening to the server. 
You are right, it should increase the wait time. I'm not really sure why it's not doing that, I am pretty sure it used to do this in the past but can't find the code for it anymore.

**Comment by Safihre** [comment]
I propose that we do the following:
If the server does not supply a `retry-after` header, wait 60 sec, then after second failure 120 sec, then after third failure 180 sec and so on, to a maximum of waiting 600 sec.
If after that 10th retry it still fails, we abort the fetch.
What do you think?

**Comment by enilfodne** [comment]
That sounds great, I've opened an [issue](https://github.com/theotherp/nzbhydra/issues/678) in the `NZBhydra` project as-well. Hopefully `NZBhydra` can supply `retry-after` based on the limit set in the indexer settings.
