### ISSUE TITLE
Corrupt RAR...not.

### ISSUE THREAD

**Issue by plato79** [sabnzbd/sabnzbd#1071]
I was trying to download a TV show episode and I saw this problem.

The thing is the RAR was perfectly fine.. sabnzbd started downloading and it also found all of the files are there ( it started with direct unpacking ).. But after the end it said the RAR file is corrupt. There was a MKV file in the UNPACK folder too.

I downloaded the same file two more times with the same result.

After that I tried with newsleecher 7.0  and downloaded same nzb with it. It downloaded all the files ( not requiring any parity files at all ) then extracted successfully without problem.

The log doesn't say anything about Corrupt RAR or anything. It says it completed unpack magic, and deletes files after that and putting the job in history. In the history it appears as Corrupt RAR in the status not completed. The folder name remains as "_UNPACK_..."

I could post the file information or NZB file if you want to try it yourself.

Here is the sabnzbd information:

Version: 2.3.0 [ba7d906]
Python Version: 2.7.14 (default, Oct 19 2017, 01:17:20) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)] [UTF-8]
OpenSSL 1.0.2j-freebsd 26 Sep 2016

OS: FreeNAS-11.0-U2 (e417d8aa5)

unrar is 5.50 beta 4 freeware

**Comment by Safihre** [comment]
Can you send the NZB and the Debug log to safihre@sabnzbd.org?

**Comment by thezoggy** [comment]
for starters, retry your download with unrar on 5.50 final (not beta4). if rar file is corrupt, check it with .sfv and confirm if the poster just posted with bad sfv or if its actually corrupted

**Comment by Safihre** [comment]
@plato79 Any news on this? We would need that extra info to solve this. Could indeed just be the Unrar version.
