### ISSUE TITLE
share nzb files with others

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#1072]
There are to much encrypted files in usenet.
What about embedding a anonymous p2p network (i2p) where nzb files with password will be shared?

**Comment by Safihre** [comment]
There is already something like that: SpotWeb 👍

**Comment by ggzengel** [comment]
I would like to have it embedded.
If I add nzb files with passwords to my sabnzbd they should automatically be shared and if I add a nzb without a password it should search for a password.

**Comment by Safihre** [comment]
That would be great indeed, but then we kind of get into a buy of gray area of how legal it is..

**Comment by thezoggy** [comment]
I deff do not think we should support this.. way to easy to get abused and if this is a way to share nzb from indexers.. that goes against their rules.. you would just get yourself banned.

**Comment by ggzengel** [comment]
If you use a real anonymous mashed network and only store passwords related to the usenet id, than there is really nothing illegal. And nobody knows who has leaked the password if you delay this info.
