### ISSUE TITLE
Install Wizard does not allow language selection

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#1074]
OS: Windows 10
New install from source (i.e. git clone)

Starting sabnzd starts the Quick-Start wizard, but language selection does not show any options to select.

![image](https://user-images.githubusercontent.com/1867464/33195647-771fafa8-d0a7-11e7-8b36-b18c3142c197.png)

**Comment by thezoggy** [comment]
what browser, plugins (ad blockers?)

**Comment by labrys** [comment]
Chrome and Edge, no plugins or ad blockers.  I did not run the script to generate them, and had no need to generate them as the English default was fine.  However, having it ask to select in the wizard with no options to select or instructions to enable seems broken to me.

**Comment by labrys** [comment]
Install script does provide language choices after running the script to generate.

**Comment by Safihre** [comment]
Users who want to run from sources we expect to read the [README](https://github.com/sabnzbd/sabnzbd/blob/develop/README.md) or the [INSTALL](https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt)  where the need to run the generation script  is noted before the command how to run the program.

**Comment by labrys** [comment]
@Safihre Selecting the language is a mandatory part of the quick-start wizard, running the generation script is optional.  If the translations aren't available either skipping the language selection (my preference) or a note about compiling the translations would be better.

**Comment by Safihre** [comment]
You can just click Next as far as I remember?

**Comment by labrys** [comment]
It's bad interface design, but its your baby, so if you find it acceptable then issue is already closed.

**Comment by Safihre** [comment]
I added a warning and instruction now to the first page 😃
