### ISSUE TITLE
2.3.1 not working on my OSX 10.11.6 (15G1611)

### ISSUE THREAD

**Issue by grillp** [sabnzbd/sabnzbd#1075]
I updated SABNzb+ to v 2.3.1 (from 2.2.0). Start SABNzb+ and nothing happens. If I start Activity Monitor and Filter for SAB, I see the process starting and then stopping again after a few seconds away.

If I revert to 2.2.0 that works fine.

In ~/Library/Application Support/sabnzb/logs/sabnzb.logs, all I see is:
> 2017-11-24 18:47:18,079::INFO::[_cplogging:219] [24/Nov/2017:18:47:18] ENGINE Bus STARTING
> 2017-11-24 18:48:50,331::INFO::[_cplogging:219] [24/Nov/2017:18:48:50] ENGINE Bus STARTING
for 2 seperate restarts.

Changed the loglevel (in sabnzb.ini) to 9 and see:
> 2017-11-24 19:01:34,833::INFO::[SABnzbd:1141] Console logging for OSX App disabled
> 2017-11-24 19:01:34,833::INFO::[SABnzbd:1148] --------------------------------
> 2017-11-24 19:01:34,833::INFO::[SABnzbd:1149] SABnzbd.py-2.3.1 (rev=f1695ec8753fbdb07bd67bdce25eeb3ebe70b972)
> 2017-11-24 19:01:34,834::INFO::[SABnzbd:1150] Full executable path = /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
> 2017-11-24 19:01:34,834::INFO::[SABnzbd:1160] Platform = posix
> 2017-11-24 19:01:34,834::INFO::[SABnzbd:1161] Python-version = 2.7.14 (default, Oct 26 2017, 19:43:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> 2017-11-24 19:01:34,834::INFO::[SABnzbd:1162] Arguments = /Applications/SABnzbd.app/Contents/Resources/SABnzbd.py
> 2017-11-24 19:01:34,834::INFO::[SABnzbd:1167] Preferred encoding = UTF-8
> 2017-11-24 19:01:34,835::INFO::[SABnzbd:1177] SSL version = OpenSSL 1.0.2l  25 May 2017
> 2017-11-24 19:01:34,835::INFO::[SABnzbd:1184] Loaded additional certificates from /Applications/SABnzbd.app/Contents/Resources/cacert.pem
> 2017-11-24 19:01:34,854::DEBUG::[SABnzbd:1191] Available certificates: {'x509': 142, 'x509_ca': 142, 'crl': 0}
> 2017-11-24 19:01:34,854::DEBUG::[SABnzbd:1198] My local IPv4 address = 10.3.105.86

Anything else I can check?

**Comment by Safihre** [comment]
@Cpuroast we have reports of this in the forum too. Did you notice anything in your systems?

**Comment by Safihre** [comment]
@grillp Could you do this? https://sabnzbd.org/wiki/faq#freshstart

And then start SABnzbd via the terminal, like this:
```
/Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console
```
What is the whole output? Is `My local IPv4 address` really the last line?

**Comment by grillp** [comment]
Tried without th reset and got this:

> /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console
> INFO:root:--------------------------------
> INFO:root:SABnzbd.py-2.3.1 (rev=f1695ec8753fbdb07bd67bdce25eeb3ebe70b972)
> INFO:root:Full executable path = /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
> INFO:root:Platform = posix
> INFO:root:Python-version = 2.7.14 (default, Oct 26 2017, 19:43:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> INFO:root:Arguments = /Applications/SABnzbd.app/Contents/Resources/SABnzbd.py -l2 --console
> INFO:root:Preferred encoding = US-ASCII
> INFO:root:SSL version = OpenSSL 1.0.2l  25 May 2017
> INFO:root:Loaded additional certificates from /Applications/SABnzbd.app/Contents/Resources/cacert.pem
> DEBUG:root:Available certificates: {'x509': 142, 'x509_ca': 142, 'crl': 0}
> DEBUG:root:My local IPv4 address = 10.3.105.212
[1]    1542 illegal hardware instruction  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console

Will try with reset later. The illegal hardware instruction looks weird..

**Comment by grillp** [comment]
The `DEBUG:root:My local IPv4 address = 10.3.105.212 ` in the log is kinda weird.

Thats the IP address of my VPN TUN interface. So it may be trying to open port 8080 on the VPN TUN NIC? It should be on 192.168.0.204, which is my Ethernet IP Address.

Can I force it to use 192.168.0.204?

**Comment by grillp** [comment]
Tried the reset as mentioned above.

Ran `/Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console` and got:

> [1]    1715 illegal hardware instruction  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console

So no go.

**Comment by grillp** [comment]
I have also tried re-downloading the the OSX DMG and installing from the new one, but the same thing happens.

I just DLed `2.3.0` and ran it, and it works fine. Seems like it is only 2.3.1 that is a problem for me.

**Comment by Cpuroast** [comment]
2.3.1 launches perfectly in my 10.11.6 VM, obviously with a fresh ini file.

Did you try just running 2.3.1 with a fresh ini file without any special command?

Shutdown Sab
Move ~/Library/Application Support/SABnzbd/sabnzbd.ini to your desktop in case the ini file isn't to blame.
Try launching 2.3.1 by simply double clicking on the app, it should launch the wizard for initial config.

**Comment by Cpuroast** [comment]
I just retested with a fresh copy of 2.3.1 on my 10.11 VM running:

System Version:	OS X 10.11.6 (15G17023)
Kernel Version:	Darwin 15.6.0

This is the same as grillp's version and it launches perfectly.

**Comment by Safihre** [comment]
I am reading online that it is something python specific. Found some stuff about retina and non retina machines, weird things.

**Comment by Cpuroast** [comment]
We have some retina boxes at work, I can give it a whirl and see.
It would be very odd if it played a part.

2.3.1 is when Python 2.7.14 landed. 2.3.0 and 2.2.0 used Python 2.7.13.

**Comment by grillp** [comment]
@cpuroast, I did try '2.3.1' with a clean ini and just dbl clicked the icon. Same deal. Didn't work.

My spec is an old 2007 24' iMac which is still alive. (Amazingly!!) But upgraded with SSD and max mem, and perfect for background stuff like Sab. So non Retina machine. Also the reason I can't upgradefrom El Captain to High Sierra.

And again, '2.3.0' works fine. Maybe I'll stick with '2.3.0' and see when a new version comes out as it seems like "it's me, not you"?

**Comment by Safihre** [comment]
@grillp, it's not you :/ 
More users report same here: https://forums.sabnzbd.org/viewtopic.php?f=2&t=23098

Could you possible try these 2 different builds? They are just experiments to see where to start from:
https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.12
https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.11-2
That last one is still building, maybe check back in 1 or 2 hours from now if the dmg shows up :)

**Comment by grillp** [comment]
If I run the )OSX10.12 version I get:
> /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console
> dyld: lazy symbol binding failed: Symbol not found: _getentropy
>   Referenced from: /Applications/SABnzbd.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: _getentropy
 >  Referenced from: /Applications/SABnzbd.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> [1]    1522 trace trap  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console

So does not start at all. 

I am waiting for the second build to complete.

**Comment by Cpuroast** [comment]
Now testing on a Late 2013 iMac non-retina iMac running 10.11.6 with the same build number as grillp.

"OSX10.12" build obviously doesn't run on 10.11 as the "xcode9.1" image doesn't contain the SDK for 10.11
Still waiting for the xcode8 build.
It would be worth trying the xcode7.3.1 image.

The latest stable 2.3.1 version runs just fine as it did in my 10,11 VM.
Also, the regular 2.3.2RC1-build version which was built with xcode6.4 runs perfectly as it did in my 10,11 VM

As far as travis goes:

xcode6.4 is for 10.9 and up
xcode7.3.1 is for 10.11 and up
xcode8 is for 10.11 and up
xcode8.1 is for 10.12 and up
xcode8.2 is for 10.12 and up
xcode8.3.3 is for 10.12 and up
xcode9.0 is for 10.13 and up
xcode9.1 is for 10.13 and up

**Comment by grillp** [comment]
I also just tried with the the real `2.3.2-RC2` from here: https://github.com/sabnzbd/sabbuild/releases/tag/2.3.2RC1-build

Got this:
> INFO:root:--------------------------------
> INFO:root:SABnzbd.py-2.3.2RC1 (rev=0049f14d7faeb22a89865c610b058723fa42d291)
> INFO:root:Full executable path = /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
> INFO:root:Platform = posix
> INFO:root:Python-version = 2.7.14 (default, Nov 23 2017, 17:06:50)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> INFO:root:Arguments = /Applications/SABnzbd.app/Contents/Resources/SABnzbd.py -l2 --console
> INFO:root:Preferred encoding = UTF-8
> INFO:root:SSL version = OpenSSL 1.0.2m  2 Nov 2017
> INFO:root:Loaded additional certificates from > /Applications/SABnzbd.app/Contents/Resources/cacert.pem
> [1]    1731 illegal hardware instruction  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console

Waiting for the https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.11-2 build now to try that out.

**Comment by Cpuroast** [comment]
It all boils down to your mac is too old.
It's officially going out of support by Apple in Fall 2018 when 10.11 bites the bullet, with the release of 10.14 as Apple only supports current+2 previous OSes.
It's time think about an upgrade.

**Comment by grillp** [comment]
Nooo! Say it ain't so! ;-) Shame cause it works well as that work horse.

Seems strange that it happened between 2.3.0 and 2.3.1. 

I assume that the XCode version between the build/packaging updated the python version from 2.7.13 to 2.7.14? Is there a way to tie it back to the previous version? i.e. downgrade XCode/Python? Or is this something I would have to try and do myself?

Otherwise it looks like I will be stuck at 2.3.0 for a while to come then!

Thanks for looking into it!

**Comment by Cpuroast** [comment]
The build environment which built 2.3.0, 2.3.1 and 2.3.2RC1 didn't actually change, which is why it still runs on my 10.9 VM.

Starting with 2.3.0, I have been personally testing Sab on 10.9, 10.10, 10.11, 10.13 in VMs and on 10.12 on the host running those VMs which is a mid-2012 MacBook Pro running 10.12, to make sure builds run on all OSes and so far they have been working flawlessly at least on this 2012 CPU.

**Comment by grillp** [comment]
IC. So where does the python version change come into it? from 2.7.13 to 2.7.14? It's not like I change my python between installs of SAB?

`2.3.0` says `python-version: 2.7.13 (default, Jul 18 2017, 09:16:45)`
`2.3.1` says `python-version: 2.7.14 (default, Oct 26 2017, 19:43:58)`
`2.3.2-RC2` says `python-version: 2.7.14 (default, Nov 23 2017, 17:06:50)

So I assume the python version is build into the App package? Is that part of the XCode build chain? or what ever version the build server has installed at the time?

Just trying to understand a bit better ;-)

**Comment by Cpuroast** [comment]
While Safihre may find a work around to restrain the build environment in terms of CPU instructions, the simple fact is that all macs which did not make the Sierra cut and which are stuck on 10.11 are in their last year or so of useful life, once Apple stops supporting 10.11 in Fall 2018, many apps will start to follow and since the hardware cannot be upgraded to 10.12 and up, it's game over.

Web browsers like Chrome and Firefox have been very generous and currently support 10.9 and up. That's current+4 previous versions, which is 2 more than Apple supports.
So I suggested we match that for Sab and so far it's been working well, however this instruction issue on older Core 2 hardware was unexpected.

Other popular apps are more strict for example:

Office 2016 supports 10.10 and up, which is current+3 previous
Adobe CC as of 2018 supports 10.11 and up, which is current+2 previous

**Comment by grillp** [comment]
Sounds fair. Now i have to convince the Minister Of Finance that my iMac really really needs updating. ;-)

So give me a few months please ;-)

G./

**Comment by Safihre** [comment]
Oops, I made a typo in the 10.11 build. Restarting now!

**Comment by Safihre** [comment]
Build done: https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.11-2

**Comment by grillp** [comment]
Just tried `2.3.2RC1 [0049f14]` from https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.11-2 and it works!

The python version in this build is `2.7.14 (default, Sep 25 2017, 09:53:17)` so different from the 2 other that failed. So strange that it now works with a `2.7.14`

Thanks for all your efforts guys!

**Comment by Safihre** [comment]
Hmmm @Cpuroast now what do we do? 😆
Drop 10.10 support? I assume this 10.11 build doesn't work on 10.10/10.9 right?

I could also try to force the 10.10 build to use 2.7.13 and see if that maybe works?

**Comment by Safihre** [comment]
@grillp Could you maybe test this version?
https://github.com/sabnzbd/sabbuild/releases/tag/OSX10.10-3
It uses Python 2.7.13 but on a OSX 10.10 build system, to see if the newer Python version is the problem.

**Comment by Cpuroast** [comment]
In a surprising turn of events, OSX10.11-2 actually runs on 10.9 and 10.10.
That was built using the xcode8 image?

**Comment by Cpuroast** [comment]
maybe there's something weird with the xcode6.4 travis image
I know if you don't specify osx_image, it defaults to the xcode7.3.1 image.

Xcode 7.3.1 is available by adding osx_image: xcode7.3 to your .travis.yml.
– Default when no other osx_image: is specified

You could try that one.

**Comment by Cpuroast** [comment]
as I said, there might be something funky with the old xcode6.4 image.

**Comment by Cpuroast** [comment]
Python 2.7.14 is fine, I think the travis images simply have their quirks.

So we know that builds done with xcode6.4 image has issues with older CPUs
Would be worth trying Python 2.7.14 on the default xcode7.3.1 image and see what happens.

**Comment by Cpuroast** [comment]
Still need to test OSX10.11-2 on 10.11,10.12 and 10.13

**Comment by Cpuroast** [comment]
OSX10.11-2 runs on 10.9, 10.10, 10.11, 10.12 and 10.13

At least on this 2012 CPU

Looks like we might have a new winner.

**Comment by Cpuroast** [comment]
Also, Safihre you should really join the sab IRC channel on SynIRC, would be faster for testing and collaboration than github comments.

**Comment by grillp** [comment]
@Safihre , tried the version in 

It failed:
> /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console
> [1]    4144 illegal hardware instruction  /Applications/SABnzbd.app/Contents/MacOS/SABnzbd -l2 --console

No logging other than that.

**Comment by Cpuroast** [comment]
@grillp Yeah, it's pretty much the same error as before, it's trying to use an instruction your CPU doesn't have.

So far, whatever @Safihre did for OSX10.11-2, it did the trick, it runs on all versions of macOS and it runs on your 2007 CPU.

**Comment by Safihre** [comment]
Great, then `OSX10.10-2` it is 👍 Thanks both for testing!
@Cpuroast Not near computer often enough to be on IRC, so just combining everything in Github comments 😃

**Comment by Cpuroast** [comment]
@Safihre I assume you meant "OSX10.11-2" instead of "OSX10.10-2"

**Comment by Safihre** [comment]
Yes indeed!

**Comment by Cpuroast** [comment]
@Safihre I'm actually surprised it runs on 10.9 and 10.10, that completely caught me by surprise, according to travis the xcode8 image doesn't even even contain the 10.9 and 10.10 sdks.

For the hell of it though, we should try a build using xcode7.3.1.

**Comment by Safihre** [comment]
Here it is :)
https://github.com/sabnzbd/sabbuild/releases/tag/osx73

**Comment by Cpuroast** [comment]
Ok, no real differences with xcode7.3 vs xcode8, it runs fine on my VMs.
@grillp could try it to confirm on his older hardware, but I'm pretty sure it will runs just fine. 
But if xcode8 works, it's probably worth sticking with that.

I think things may start breaking for 10.9 and possibly 10.10, starting with the xcode8.1 image which is built on 10.12.

Why not make a build using xcode8.1, xcode8.2 and xcode8.3, xcode9 and xcode9.1 and I'll see if they still run on 10.9/10.10/10.11. At least we'll know exactly when things start breaking for older OSes.

**Comment by grillp** [comment]
I'm away from home for a few weeks, but will vpn in when I can to test out the new version. Will let you know when I have tried.

Thanks again folks!

**Comment by grillp** [comment]
Waiting between flights I managed to give it a try. 

https://github.com/sabnzbd/sabbuild/releases/tag/osx73 works fine on my machine.

**Comment by Cpuroast** [comment]
That's what I thought, ok, we stick with xcode8 since it seems to work fine on everything and I suspect xcode8.1 on 10.12 would break 10.9, 10.10 and potentially 10.11.

**Comment by Safihre** [comment]
@grillp @Cpuroast Travis removed the `xcode8` image and now only has `xcode8.3` for the 8 series.
Could you guys test this one? https://github.com/sabnzbd/sabbuild/releases/tag/2.3.2RC2-2
Otherwise I could also go to `xcode7.3` since that one seems to work fine to.

**Comment by Cpuroast** [comment]
@Safihre That's odd, since xcode8 is still in their docs:

https://docs.travis-ci.com/user/reference/osx/

They did remove some of the build environments, but xcode8 is still there.

And your travis config file is still specifying xcode8:

https://github.com/sabnzbd/sabbuild/blob/master/.travis.yml

**Comment by Safihre** [comment]
https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce
![image](https://user-images.githubusercontent.com/5703454/33797107-52959820-dd02-11e7-99d9-1604813c9453.png)

**Comment by Cpuroast** [comment]
Interesting, their docs need to be updated then to reflect this.

**Comment by Cpuroast** [comment]
Mid 2012 MBP
macOS 10.12.6
VMware Fusion 8.5.9

2.3.2RC2-2
10.9.5: Passed
10.10.5: Passed
10.11.6: Passed
10.12.6: Passed
10.13.2: Passed

So far so good.

If all is good with this build, It would be worth updating .travis.yml to use xcode8.3 to avoid the redirect message and to clarify exactly which build image would be used during the build.

**Comment by grillp** [comment]
Heya,

https://github.com/sabnzbd/sabbuild/releases/tag/2.3.2RC2-2 Works fine on my clunker..ehmm.. workhorse!

Mid 2007 iMac
maxOS 10.11.6

**Comment by Cpuroast** [comment]
Good, looks like xcode8.3 is our new default as I'm pretty sure the more recent images would at least break 10.9.

**Comment by Safihre** [comment]
Thanks for testing guys! 🥇
