### ISSUE TITLE
2.3.2RC1 Breaks Directunpack on Non-obfuscated Posts

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1077]
While 2.3.2RC1 works nicely with obfuscated posts and directunpack starts normally with them, it seems to not want to start at all with non-obfuscated posts, leading to a full unpack after the job is done downloading.

**Comment by Cpuroast** [comment]
Testing the same non-obfuscated post with 2.3.1 and directunpack starts as expected.

**Comment by Safihre** [comment]
Are you sure? I can't reproduce that and looking at the code I can't see why that would be the case.
Maybe try it again on 2.3.2? Otherwise enable Debug logging and look for where it says `directunpack`.

**Comment by Cpuroast** [comment]
I was paying close attention to the log with tail -f, while the job was running, it was decoding correctly, but directunpack was never starting.

**Comment by Cpuroast** [comment]
To see DirectUnpack in action, +Info is all that is needed.

**Comment by Cpuroast** [comment]
With 2.3.1, DirectUnpack is clearly underway, with 2.3.2RC1, it never triggers.

**Comment by Safihre** [comment]
Can you try a different download (or even the same download again) and then send me the log at safihre@sabnzbd.org?

**Comment by Safihre** [comment]
I suggest +Debug not because I like looking at lots and lots of lines of text, but because there might be information in there to explain the difference 😋

**Comment by thezoggy** [comment]
direct unpack is working fine for me before and after 2.3.2rc1

**Comment by Safihre** [comment]
Downloaded about 10 different shows today, all not obfuscated, all unpacked via Direct Unpack.

**Comment by Cpuroast** [comment]
Bah, it could simply be a performance issue which is sometimes preventing DirectUnpack from triggering.

I've seen some non-obfuscated nzbs which trigger it and some that don't.
I've also seen some obfuscated ones that don't trigger it

It's not a show-stopping issue and doesn't prevent 2.3.2 from moving forward.
I'll still keep an eye out and see if I can narrow down the cause of why it sometimes doesn't trigger DirectUnpack.

I'm closing the ticket.

**Comment by Safihre** [comment]
It could maybe be that not all articles of the first rar-file get received in time?
