### ISSUE TITLE
Prometheus Metrics Exporter

### ISSUE THREAD

**Issue by msroest** [sabnzbd/sabnzbd#1079]
I'm getting into prometheus (prometheus.io) and I'm wanting to add stats about my sabnzbd.  Iw as wondering if there's any interest from the maintainers in having sab itself expose the metrics directly rather then me building an external scaper that uses the API.  If so this is something I'd plan on working on and submitting a PR.  There is a first party python library for doing most of the prometheus heavy lifting (https://github.com/prometheus/client_python) that could be optionally included that should allow the sab processes to expose it's metrics.

Thanks

**Comment by Safihre** [comment]
I could add the daily statistics for each server, I see this is not available yet.
Would you like more?
If I understand correctly you suggest to add it to the SABnzbd core also?

**Comment by msroest** [comment]
Sorry what I meant was to have SAB export the prometheus metrics itself ie add a /metrics endpoint on the sabnzbd server process that returns metrics in the prometheus format to be added to a prometheus server.   Instead of writing a external process that uses the SAB API to get the statistics and then expose them to prometheus externally.  I'm planning to do the work either way, but if you're not interested in having the stats be inprocess/merging that potential PR then I'll work on writing it as a external process instead.

**Comment by Safihre** [comment]
Aaah like that.
How does it want the output? Couldn't really find it on the website upon first glance. Is it very specific to prometheus?

**Comment by thezoggy** [comment]
pretty sure this should not be baked into sab.. as most people would not want to report their sab stats to a 3rd party service.. also what benefit would it really have? seeing how many requests make it to cherrypy I wouldnt think would interest most people.

**Comment by Safihre** [comment]
Agreed that I would not want to make something specific. But maybe there's more stats we could expose that I didn't think off.

**Comment by msroest** [comment]
Prometheus isn't a 3rd party service it's something you run on your own.  It just seemed like since sab is already runing a webserver and has in process access to the stats that it would be pretty natural for it to expose it own stats directly instead of having another process running that's querying and then exposing the stats be a seperate web socket.

My thinking was it would be optional (controlled by config and/or the presence or absence of the prometheus_client module).

But if the consensus is that it doesn't make sense to others to be in process I'll write it as a separate
 module that can be run on the same or seperate box. 

@Safihre  this is the definition of the metrics formats: https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by Safihre** [comment]
@msroest I can't say I'm a huge fan of their format, I don't think I want to implement this since it's a bit exotic.
But let me know if you'd like some more metrics to be exposed 👍

**Comment by msroest** [comment]
Ok sounds good I'll work on this as an external process that access things via the API.  Thanks for the input guys.  I'll update this when I have a repo that's working etc.

**Comment by msroest** [comment]
@Safihre @thezoggy  I've got a first version of the prometheus exporter published:
https://github.com/msroest/sabnzbd_exporter

**Comment by Freakin** [comment]
I'm in favor of this as well.  It's not sending metrics to any service @thezoggy , it simply provides a `/metrics` endpoint exposing prometheus formatted metrics.  A user-maintained prometheus instance would be configured to scrape this endpoint to retrieve the metrics and add them to its TSDB.  It follows a pull model instead of a push model common to other metrics platforms.

@Safihre This format is gaining wide adoption and is used by other open source tools/platforms like

Grafana
Collectd
Kubernetes
Minio
Netdata
And others

The alternative is to build a custom exporter which is run as a separate process.  It is responsible for scraping the API to pull metrics and metadata, then exposing them in prometheus format itself, which is what @msroest has created.

**Comment by thezoggy** [comment]
to circle back to this, I deff misread how this was original presented (thought it was sab sending stuff out) not providing a nice endpoint so those that want could fetch metrics from their instance

**Comment by rekahsoft** [comment]
It would be nice to see a `/metrics` endpoint added directly to sabnzbd instead of having to run a separate exporter process. Can this be re-opened?

**Comment by rogierlommers** [comment]
Totallt agree that a native prometheus "scrapable" endpoint would be perfect.
