### ISSUE TITLE
sab 2.3.2RC1 -- space before aborted warning

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1081]
noticed that in a list of warnings, the 'aborted' one has an extra space before it:
![sab](http://zoggy.net/firefox_2017-12-04_00-38-55.png)

**Comment by thezoggy** [comment]
looking at the source I see the extra space.. looking at the sabnzbd.pot on github I dont see it.. 
looking at this install (jcpf), there is no `po` folder.. does the ppa not include our translations?

**Comment by Safihre** [comment]
Leftovers of old style warnings that included the text `WARNING`, which I clipped a few SABnzbd versions ago. 
Added a `strip()` to remove that last white space.
