### ISSUE TITLE
Password in NZB Name not always transfered

### ISSUE THREAD

**Issue by segelkma** [sabnzbd/sabnzbd#1084]
Hi,
I am not sure if this is intended, but for me it does not make sense. I have a nzb file with the password in its filename:
NZBFILEBla{{password}}.nzb
Adding the NZB as it is to SABnzbd will automatically add the password. However when you specify your own name for the download (Optionally specify a name) then the password will be ifnored and you have to add it manually.
I know that I could change the name afterwards but I like to do it instantly. I think there is no reason why SABnzbd should not take the password every time if there is one in the filename.

**Comment by thezoggy** [comment]
https://sabnzbd.org/wiki/advanced/password-protected-rars

**Comment by Safihre** [comment]
@thezoggy Actually @segelkma has a good point and it's a simple addition to also check the filename for password.
