### ISSUE TITLE
Asustor NAS: SABYenc disabled: no correct version found! (Found v3.0.2, expecting v3.3.2)

### ISSUE THREAD

**Issue by mansun37** [sabnzbd/sabnzbd#1087]
Hi,

This has been driving me crazy for a while, I keep getting the error:

_SABYenc disabled: no correct version found! (Found v3.0.2, expecting v3.3.2)_

I'm not overly technical so it's taken me awhile to figure out how to get to the command line and try some of the solutions offered.  I recently tried:

_pip install sabyenc --upgrade_

And it seemed to be going OK until the end when it said:

_unable to execute 'x86_64-asustor-linux-gnu-gcc': No such file or directory

_error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1__

I'm at a loss what to do about this to get the issue resolved.   Does anyone have any suggestions?

Thanks

**Comment by sanderjo** [comment]
How did you install SABnzbd on your Asustor? Did you use a package?

> error: command 'x86_64-asustor-linux-gnu-gcc' failed with exit status 1_

You have no GCC (C compiler) on your Asustor ... of which I don't know if it is feasible to solve.

**Comment by mansun37** [comment]
Hello,

Yes I used the Asustor provided package (this one: https://www.asustor.com/app_central/app_detail?id=98&type=)

**Comment by thezoggy** [comment]
you should tell them to update their app, `Last Update: 2017-08-31`

**Comment by sanderjo** [comment]
Ah, a package from Clinton ... I'm not sure he is updating anymore.


Worth a try: ask @Damien360 how he installed the GCC C compiler on his ASUSTOR; hij had the same problem as you, see https://github.com/sabnzbd/sabnzbd/issues/1039

**Comment by clinton-hall** [comment]
@sanderjo 
You can try a manual install from here [https://www.dropbox.com/s/6aas66ktfen106s/sabnzbdplus_20180105_any.apk?dl=0](url)

I have updated in app central, but this may take a week or 2 for them to verify and release.

**Comment by sanderjo** [comment]
@mansun37 See to the message / URL from @clinton-hall  .... meant for you, not for me.

**Comment by mansun37** [comment]
@clinton-hall thanks for the link, I'll try that now.  And thanks to all who replied to my problem.
