### ISSUE TITLE
not falling back to alternate IP addresses

### ISSUE THREAD

**Issue by brianjmurrell** [sabnzbd/sabnzbd#1089]
When sabnzbd fails to connect to the first IP address of a server that has published multiple IP addresses it does not try any of the alternate IP addresses.

Servers with multiple IP address records are not in any way, shape or form rare on the Internet.  Publishing multiple IP addresses for a server has a long history on the Internet and good IP clients will try all of the address records returned by a DNS lookup until either they have all been tried or a connection is successful.

Publishing multiple IP addresses in fact is the **only** way to operate in a dual-stack manner so IP clients that support IPv6 really really ought to try all IP address records for a name.

**Comment by sanderjo** [comment]
> When sabnzbd fails to connect to the first IP address of a server that has published multiple IP addresses it does not try any of the alternate IP addresses.

Do you have "Server Load-Balancing" activated (aka Happy Eyeballs)? You should (with "... with optimatization for IPv6"), and then that should not happen.
It's under config/switches/#load_balancing 

If you have it activated, please provide newsserver name and logging.

**Comment by thezoggy** [comment]
Which was added in sab 0.8.0Beta1 (Sep 17, 2015).

Crazy how long ago this was added, had to go dig up the old 0.7.x -> 0.8.x upgrade page:
https://sabnzbd.org/wiki/new-features-and-changes.html
> Newsserver IPv6 load balancing aka Happy Eyeballs / RFC 6555

**Comment by brianjmurrell** [comment]
I do have _Server load-balancing_ enabled with _... with optimatization for IPv6_.

When I click on the _Test Server_ button for a server that has two IPv4 and two IPv6 addresses only one server connection is attempted, as verified using `tcpdump ... port 119`.  That only connection attempt failed with a _TCP RST_ and no further connection attempts were made.

Even though I do have _happyeyeballs_ entries in my log, I don't get any new log entries when I press the _Test Server_ button.  Is this load-balancing feature not used for the _Test Server_ functionality perhaps?

**Comment by Safihre** [comment]
> Even though I do have happyeyeballs entries in my log, I don't get any new log entries when I press the Test Server button. Is this load-balancing feature not used for the Test Server functionality perhaps?

That seems to be the case.. No clue why, weird a bit. 
Let's check why.

**Comment by Safihre** [comment]
It was a bug, the bug is now fixed 👍 
Thanks for reporting!

**Comment by sanderjo** [comment]
> Even though I do have happyeyeballs entries in my log,

OK ... and what do those log entries say?

**Comment by brianjmurrell** [comment]
> OK ... and what do those log entries say?

They were orthogonal.  As has [already been identified](https://github.com/sabnzbd/sabnzbd/issues/1089#issuecomment-356608009), the issue was a bug with how Test Server was working.  It was not using Happy Eyeballs.

I just want to confirm that 9638eab has indeed resolved the issue and now Test Server is using Happy Eyeballs and working properly with load-balanced servers.
