### ISSUE TITLE
Fake SSL alert when Internet is unreachable

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1091]
If Internet (or more specific: selftest_host, by default https://self-test.sabnzbd.org/ ) is unreachable, SABnzbd will give a SSL warning:

> Warning Secure (SSL) connections from SABnzbd to newsservers and HTTPS websites will be encrypted, however, validating a server's identity using its certificates is not possible. Python 2.7.9 or above, OpenSSL 1.0.2 or above and up-to-date local CA certificates are required.

which is probably incorrect, so _fake_ in 2018 speak. ;-)

Mitigation: Let SABnzbd check if Internet is working at all. 
How can we do this? Check plain HTTP http://self-test.sabnzbd.org/ ? Do we need another HTTPS site too?
If Internet is not reachable, would should we do / say? Just ignore it? Mention it in a Warning on the front page? 
The thing to note is that you can operate SABnzbd without SABnzbd having any access to HTTP or HTTPs; only NNTP or NNTPS is needed. And, for firewall lovers, only NNTP or NNTPS access to a specific newsserver is needed ...
And as @Safihre said in https://forums.sabnzbd.org/viewtopic.php?f=13&t=23233#p114904 : Internet not accessible can be a startup/timing problem.

And while on the subject: the full message is:

> **Python Version:	2.7.14** (default, Sep 23 2017, 22:06:14) [GCC 7.2.0] [UTF-8]
> **OpenSSL:	OpenSSL 1.0.2**g 1 Mar 2016
> Warning Secure (SSL) connections from SABnzbd to newsservers and HTTPS websites will be encrypted, however, validating a server's identity using its certificates is not possible. **Python 2.7.9 or above, OpenSSL 1.0.2 or above** and up-to-date local CA certificates are required.

which is a bit redundant: SAB already knows the Python and OpenSSL versions are correct (see bold), so (assuming Internet is working), the remaining cause is certificate problems (root store, or intercepting virusscanner/firewall/malware/rootkit).

So let's discuss how to improve this.

**Background**

We (I?) Introduced this SSL checking when NAS devices were known for having no / outdated root certificate stores, and python 2.7.9 appeared, which combination caused problems.

**Comment by sanderjo** [comment]
This could help: a TLS/SSL problem gives a different error than a network problem:

TLS/SSL problem:
`urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>`

network problem
`urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>`

**Comment by Safihre** [comment]
Maybe when internet is not available we just give a positive result and enable full-verification?
Or should we really have all the retry code somewhere in the Downloader?
In that case, how often/long should we try until giving up? (maybe the selftest-host is being blocked by user firewall)

**Comment by sanderjo** [comment]
> Maybe when internet is not available we just give a positive result and enable full-verification?

Yeah, that seems best; SABnzbd is NOT a full blown security analysis tool.

And can we please get rid of the vague, cryptic message now? So improve to:

If "Python < 2.7.9" => "Sorry, no SSL/TLS certificates check possible due to Python < 2.7.9"
If "OpenSSL < 1.0.2" => "Sorry, no SSL/TLS certificates check possible due to OpenSSL < 1.0.2"

And only if Python and OpenSSL are OK, then tell something about the check?
