### ISSUE TITLE
logging to standard out

### ISSUE THREAD

**Issue by carlwgeorge** [sabnzbd/sabnzbd#1103]
Reading through the wiki I noticed a `log_dir` config setting.  It's nice to have that option, but got it me thinking.  It would be even better to have a command line flag that allows logging only to standard out.  That would integrate perfectly with systemd/journald, and avoid the need for a logrotate configuration.

**Comment by Safihre** [comment]
Sure, seems reasonable!

**Comment by thezoggy** [comment]
We already log to console? You just want to disable writing log to file?

**Comment by carlwgeorge** [comment]
Correct, I don't want to write a log file at all.  Journald capturing console output is sufficient for me.  Does the console logging respect all the same options (i.e. 
`log_level`/`--logging`, `debug_log_decoding`, `api_logging`) as the log file?

**Comment by Safihre** [comment]
Will be part of the next update.
All logging uses the same level.
