### ISSUE TITLE
API Pause request does not error on invalid values

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#1105]
SAB Commit: 1b67c9c13d9ff540f61f948ea8fcf0e00f13be15

Invalid `value` param sent to the API Pause command does not raise any errors or warnings.  I would expect the command to fail and return a False status or the command to succeed with a True status and a warning in the log stating that the queue will not resume.

Possibly related to #1104 as valid values are showing as strings instead of numbers in the log.

Code example:
```python
import requests
saburl = 'http://127.0.0.1:8080/api`
apikey = '>>INSERT API KEY HERE<<'
minutes = 'frog'
params = {
    'mode': 'pause',
    'value': minutes,
    'output': 'json',
    'apikey': apikey,
}
response = requests.get(saburl, params=params)
result = response.json()['status']
print(result)
```
Logs:
```
2018-02-17 18:36:03,861::DEBUG::[interface:464] API-call from 127.0.0.1 [python-requests/2.18.4] {'output': u'json', 'apikey': u'>>INSERT API KEY HERE<<', 'mode': u'pause', 'value': u'frog'}
2018-02-17 18:36:03,868::DEBUG::[__init__:587] PAUSED_ALL inactive
2018-02-17 18:36:03,869::INFO::[downloader:277] Pausing
```

**Comment by Safihre** [comment]
Similar to #1104, this method does not have a `value` option. So the parameter is ignored as it should be.

**Comment by labrys** [comment]
Agreed, imadumbass :D
