### ISSUE TITLE
Feature request: Support `Content-Language` header

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#1106]
It would be nice to have the current configured language available in the `Content-Language` header both for the GUI and the API.

**Comment by Safihre** [comment]
That would be possible. But what would be the use-case?
The API it makes a little less sense, since the content isn't localized really, right?

**Comment by labrys** [comment]
Well this mostly came around from playing with the api.  I was thinking of providing the ability to possibly translate warnings using the `Content-Language` returned if they are translatable with the translate method.   

However, I currently can't get the API's translate method to return properly.  I think the problem is not the translate method but setting the language.

For example:
1. Set language to `nl` with `/api?mode=set_config&section=misc&keyword=language&value=nl`
```python
{
    config: {
        misc: {
            language: "nl"
        }
    }
}
```
2. Confirm language is set with `mode=get_config&section=misc&keyword=language`
```python
{
    config: {
        misc: {
            language: "nl"
        }
    }
}
```
3. Get translation of `Watched Folders` with `/api?mode=translate&value=Watched%20Folder`
```python
{
    value: "Watched Folder"
}
```

Finally, checking SAB config through GUI to confirm that language was set showed it set to `Nederlands` but all the UI text is still in `English` (the previously set language).

![image](https://user-images.githubusercontent.com/1867464/36635147-e8224f02-197d-11e8-9939-7b3a07417eec.png)

**Comment by Safihre** [comment]
Aah now that's a bug indeed!
The language-cache seems to be refreshed when changed via the API.

**Comment by Safihre** [comment]
Oke I fixed that, maybe you can give it another try?

**Comment by Safihre** [comment]
@labrys Ping 😉

**Comment by labrys** [comment]
Sorry traveling so won't be able to test this for a couple weeks.

**Comment by Safihre** [comment]
Closing as fixed.
