### ISSUE TITLE
Don't start Windows unrar/par processes with IDLE priority

### ISSUE THREAD

**Issue by HerbCSO** [sabnzbd/sabnzbd#1109]
All of the Windows subprocesses get started with [`IDLE` priority](https://github.com/sabnzbd/sabnzbd/blob/cc61e669ef59eed583ef034f1e3297dbeed31af1/sabnzbd/newsunpack.py#L2012). On a busy system, this will cause these processes to get starved of resources. As a result, it can happen that the downloads keep going, but the unpacking only progresses extremely slowly, which means files can pile up.

Granted, it's been that way for as long as the git history goes back (since [version 0.2.5](https://github.com/sabnzbd/sabnzbd/blame/ddb200f04a1b142c11002c3ef57adc73150add26/main/sabnzbd/newsunpack.py)), so not too many people seem to have an issue with this, but I would very much appreciate it if it could be changed so that these processes start with normal priority (i.e. just remove the `IDLE` priority flag), or least make it an option to turn that off. They don't consume a whole lot of CPU anyway, so I think the idle flag is a little overkill that isn't necessary. Maybe it was different in the Windows 2000/2003 days, but these days the process scheduler seems to be perfectly capable of handling these processes - if I manually set them to normal priority using Process Explorer, nothing blows up. ;]

PS: Thanks for all the great work on this, love the project! 👍 😄

**Comment by Safihre** [comment]
Ha cool, I never saw that in 2 years of diving in this code 😆 
But I think it's probably for the `par2` process, that can be really demanding and takeover everything.
Although nowadays we use Multipar, which is *much* better at all this.
@shypike What do you think?

**Comment by HerbCSO** [comment]
As an aside for anybody else looking for a workaround for now: I scheduled a task that runs every minute and executes the command `wmic process where name="UnRAR.exe" CALL setpriority "normal"`, seems to work pretty well.

**Comment by thezoggy** [comment]
so lets look at what we have to work with:
```
Priority:

    idle: 64 (or "idle")
    below normal: 16384 (or "below normal")
    normal: 32 (or "normal")
    above normal: 32768 (or "above normal")
    high priority: 128 (or "high priority")
    real time: 256 (or "realtime")
```

looking at my windows box, task manager, showing 'base priority' column.
there are a few 'high' ones for task manager/login/desktop. all apps are 'normal' but chrome which is set to 'low'.

sab binary is listed as 'normal'.  when unrar kicked on.. it was 'low'.
so maybe we should offer a way for windows users to set the priority like we do for nice/ionice... just have low / normal / high* with a disclaimer about using high that it could negatively affect other apps.

**Comment by Safihre** [comment]
Agreed, maybe in Switches or Specials.
What should be the default thought? Keep it Idle or up to Normal or Below Normal?

**Comment by thezoggy** [comment]
Use normal. If they have a low powered machine or don't care how long it will unpack the can do low and high for the inverse. But by default.i think we should do normal as that's what Sab itself runs as.

**Comment by HerbCSO** [comment]
Shweet! Thanks for jumping right on this.
