### ISSUE TITLE
Feature Request:  Move cipher(s) selection from global flag to per-server

### ISSUE THREAD

**Issue by CollinChaffin** [sabnzbd/sabnzbd#1110]
Hi @Safihre quick question I know issue #677 is closed and in it you stated when you added the ability to select ciphers:

"Not a per-server setting, since normal users have no need to change this setting."

Yet not long ago the "normal user" also didn't have the need to change ANY cipher settings. :)

In most cases now, we "normal users" (I'm being facetious I too am a DEV albeit not Python) all have multiple NNTP providers.  In such, I myself have never needed more the ability to set the SSL ciphers PER SERVER and I give you the following real-world example:

Most do not realize this old mis-nomer that SSL ciphers will ALWAYS and must always negotiate the highest is just total BS.  For example, one of the most popular NNTP tier 1 providers I confirmed with support and also outlined very clearly here:

https://www.usenetexpress.com/blog/post/sslDefaultNow128_20170420/

That they actually despite still advertising 256bit SSL will NEVER EVER default to it.  Anyone who uses them and pays attention should easily see that SHA128 is actually their default as explained further in that blog post, but they actually support up to TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, but ONLY IF THE CLIENT IS TOLD TO REQUEST IT!

So, now try to enter this provider's server and three other providers, all similar to this one all defaulting to either higher or lower ciphers, but most importantly - offering their users the choice of others.  And to top it all off and really drive home this point, the aforementinoed provider unlike most DOES NOT support the commonly suggested RC4-MD5, so setting that globally right off the bat in switches renders this provider unusable which now means the wrong group or providers and this limitation means no choice but to blank out the manual selection and go back to relying on the providers' selection, even if it's not the strongest or the fastest.  I myself would much rather have the ability to make that selection to meet my needs, not theirs.

With that said, Sabnzbd's ability added in this issue to allow cipher selection was an AWESOME addition!  However, to continue to fit into the modern-day NNTP environment moving the existing cipher selection into the SERVERS config and out of a global switch is really becoming much more necessary.  Hopefully you'll consider it.

TIA!

**Comment by Safihre** [comment]
I guess you're right!
Now that we have the `Advanced Settings` anyway, there is less issues of non-technical users touching things they shouldn't. When I implemented it the very first time, it was per server. But we were kind of scared of people doing things they shouldn't and then calling SABnzbd stupid if it doesn't work.
