### ISSUE TITLE
[Feature Request] Add option to disable warning messages

### ISSUE THREAD

**Issue by D0MF** [sabnzbd/sabnzbd#1112]
I have a passwords file that's quite a bit longer than 30 passwords, for completely valid reasons. I'd love to be able to disable the error that's always popping up 

"Your password file contains more than 30 passwords, testing all these passwords takes a lot of time. Try to only list useful passwords."

**Comment by thezoggy** [comment]
technically its a warning:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L1478

but i do agree that there is a use case for waning to not be warned about having a large password file. 
@Safihre how did you come up with 30 as the threshold? do we want to offer a special option to disable 'negative performance' warnings?

**Comment by james-d-elliott** [comment]
Why not just an option in special to change it or disable it?

**Comment by Safihre** [comment]
I don't want to add a checkbox for every warning. Maybe in Sab 3.0 I will just add 1 switch to turn off _all_ these "helpful" warnings, not the seperate switches we have now.

**Comment by 1024mb** [comment]
Please, tell us you haven't forgotten about this!

**Comment by Safihre** [comment]
Added option `helpfull_warnings`.
