### ISSUE TITLE
url_base not being used in a few places

### ISSUE THREAD

**Issue by bramp** [sabnzbd/sabnzbd#1113]
I have url_base set (to /sabnzbd), because I reverse proxy sabnzbd and others behind a single web server. Typically this setup works fine, but in the last year I've noticed a few places in sabnzbd which aren't working correctly.

Specifically:
1) On the main page, if I click + next to something in the history, nothing happens. The chrome web tools show a request was made to http://machinename/history/?start=0&limit=5, note the missing /sabnzbd/

2) Again on the main page, when I upload a nzb, it successfully accepts the file, but redirects me to http://machinename/, where I would expect it to redirect to http://machinename/sabnzbd/.

3) The General tab on the config page, shows "Choose a skin." with a URL next to it (http://127.0.0.1:8080/sabnzbd). That URL includes the internal IP address (which in my case is 127.0.0.1), and the internal port number (8080), neither of which are accessible from another machine. It should instead show the URL that I'm using to request the config page, specifically, http://machinename/sabnzbd/.

**Comment by Safihre** [comment]
What skin are you using? Not Glitter, right?

For new features we don't support the old skins anymore. Thus feature was added very recently.

**Comment by bramp** [comment]
I'm using 'smpl - white', and have been for a long time. I didn't know the default changed. I guess I should move to Glitter. I'll report similar problems if I find them.

**Comment by Safihre** [comment]
Yes let us know if it doesn't work!
Regarding the a Config General text, there we use the internal detection of hostname (not the browser)  and Sabnzbd can't detect its being proxied. So we can't really change that.
We also hope that users that understand proxies know the right URLs 😊
