### ISSUE TITLE
Does the API use NZB data ?

### ISSUE THREAD

**Issue by JackDandy** [sabnzbd/sabnzbd#1115]
Hi,

Is it possible to send nzb data to SAB as, say a base64 encoded string instead of sending an indexer URL that SAB must then fetch ?  I hear that this is not possible, if true, can this change be added ?

Background, where nzbdata is already available, SAB doesn't needs to fetch an indexer URL and (as reported in a case) enter a "fail, wait, retry" loop in the event of a failure.  

Having nzbdata (e.g. base64'd) passed in the way suggested makes SAB a) faster to begin USP transfer and b) a reliable experience by fusing out "fail, wait, retry" flows related to failed indexer connection processing. 

Thanks.
JD

**Comment by thezoggy** [comment]
You could just do what sonarr does. Send nzb data via post

**Comment by JackDandy** [comment]
Great, any docs for that ?

**Comment by JackDandy** [comment]
Hmm, turns out that it is better to send the URL so that SAB can handle special NN headers itself rather than send the data like Sonarr does.

**Comment by Safihre** [comment]
In the latest version of Sabnzbd (2.3.2) it will stop retrying after 10 times.
Doesnt it?

**Comment by JackDandy** [comment]
Hi @Safihre 

I don't know for sure, but I hear that there are no settings for URL retrieval in SAB.  I guess that is what alerted the user as they thought SAB was stuck in a infinite loop of retries. 

If SAB _is_ set to retry 10 times, then perhaps that is a tad excessive, maybe defaulting to say 3 with a user setting, would be an improvement. For instance, NZbget has UrlInterval, UrlRetries, UrlTimeout for exactly this process.

**Comment by Safihre** [comment]
You are right, it doesn't trigger anything for failed URL grabs and I think this is probably a problem for the workflow! It was recently reported in #1108 actually. 
I intend to fix that for 2.3.3, so soon! 

Regarding the retrying: currently it will Retry 10 times with increasingly large intervals.
I don't want to introduce any new settings as this is one of the big differences between NZBget and SABnzbd: we keep it simple and try to use sensible setup that fits 95% of users. If users want to tweak details, they should use NZBget :+1:

**Comment by JackDandy** [comment]
I can appreciate the resistance for not adding settings, and also to differentiate from others, however, for this integral part in the workflow, that is error retry handling, 10 times plus increasingly large intervals at a guess could delay a completion for say 2-4 hours whereas it could of completed on an alternative indexer in minutes. perhaps reconsider this not a feature for difference when you have others that are.

**Comment by Safihre** [comment]
You think an extra setting would really help for the regular basic user?
Sure I can make it a Special to set the maximum number of retries. Just doubt many users would actually use it and have need for it. 

Wish indexers would all use the same responses, but each one seems to invent their own.

**Comment by JackDandy** [comment]
Well, first I thought about the actual flow and not a setting, 
I think that given the increasingly large interval x 10 - that this is not ideal.

Second, I totally appreciate not changing a process that may affect someones workflow without a "get out of jail" card for you - and in this case, that be a setting. I used the word `integral` because the core flow of this feature is used by every user type from basic to advanced, and sure, many would never change this related setting, but it is there for the few that want it to operate the way it is right now while at the same time giving you leverage to make the improvement for all.

So sure, "Special" is one place to put it, the default of 10 could then be lowered to a default of say, 3, and then the overall time to respond back to SickGear would be reduced from potentially hours to far more responsive 10 mins or so depending on those sliding intervals. And on those intervals,  giving an indexer 10 mins to reboot or recover from a normal error state is ample enough don't you think ?

Ha, don't even start on those indexer responses, I know exactly what you're talking about ;) But keep in mind, we are talking about how we handle what is already handled, that is, a reaction to a get_url error event.

**Comment by thezoggy** [comment]
Bad url != Incomplete

**Comment by thezoggy** [comment]
some back story, the reason for the x retries with x internal with sab was to deal with nzbmatrix and other sites that would have random downtime.. so sab didnt want to hammer the site and also didnt want to just give up if the site just was flakey (this was before apps were smarter to check sab status and retry or use nzb headers for alt nzb or handle throttling/rate limits). 

so, `MAX_URL_RETRIES` is set to 10. `DEF_TIMEOUT` is set to 60. so yes if a site is down sab could retry 10 times with 60sec timeout.. so 6 mins.

now once sab actually gets the nzb it checks it.. 

if sab see's a `Incomplete NZB` from the provider, it will retry after 5 min (in hopes it was just propagation/site issues/bad fetch)

if sab gets a `Unknown error fetching NZB` it will retry after 2 min.

so you can see that it shouldnt be THAT long for sab to try and give up...

**Comment by Safihre** [comment]
@thezoggy Actually that behavior was changed to now increase: 60, 120, 240, etc.
So by the end it really takes a while before it tries again

**Comment by JackDandy** [comment]
I totally appreciate the back story, and yup, things have moved on, settings will keep things as they always were.  But 55 minutes is **very** long to be blocking imho, and obviously for the user that raised the query.  Personally, I'm used to 3 and half minutes total with 3 retries using up to 60 second timeout plus a 10 second interval each, where an alternative URL is sent from SickGear when there is feedback of indexer failure.

**Comment by Safihre** [comment]
I see now that to fix #1108 I will need to do a bigger re-write of the urlgrabber, hopefully some day this week 👍 Then I can see to add an extra option to set number of retries.

**Comment by thezoggy** [comment]
@JackDandy the scenario is only present if the indexer in question is down for 1+hr and is offline. correct? so why is sickrage sending sab url for an indexer that is offline? unless it was online and be the time sickrage sent the url it went offline..which shouldnt be very common.. I used sb/sr/etc for years and never had an issue with how sab handles retrying urls..  feel free to hit me up on irc if you want to talk specifics/more.

**Comment by Safihre** [comment]
What I can imagine is for example API limits that are hit. This will not abort the fetch attempt and makes it Retry. 
But indeed, what is the use case exactly? Why would an indexer not respond?

**Comment by JackDandy** [comment]
@thezoggy what is sickrage?

**Comment by thezoggy** [comment]
s/sickrage/sickgear/

**Comment by JackDandy** [comment]
The site wasn't down at the time the URL was fetched from the API in SickGear. Otherwise, it would have been caught and presented on the Provider Failure History layout. But yeah this event is exactly why i considered sending just the nzbdata... in order to mitigate this flow in SABnzbd. However, it was brought to my attention that there are other things like indexer response headers that clients like SABnzbd use that can only be got at by using a URL. Therefore, my idea of sending nzbdata was dropped.

**Comment by thezoggy** [comment]
sending url is good, but sab 'trusts' that the url is good.. hence it works to make sure it can get it.

maybe a quick fix would just to extend the sab api to allow the user to override the url retry amount when adding the url. that way the app (sickgear) can just set the retry amount on their side when passing the url. that way for problematic indexers they could just pass retry=1 or something so sab knows the url isnt so trustworthy.

**Comment by JackDandy** [comment]
now that's a great idea :)

**Comment by Safihre** [comment]
> limits are, equally to errors, not ideal for SABnzbd to block, better is to return a failure so that SickGear can act and send an alternative indexer URL.

Others would disagree and say they want Sab to Retry until the API limit is no longer in effect. Especially if the manually add it.

**Comment by JackDandy** [comment]
> Others would disagree and say they want Sab to Retry until the API limit is no longer in effect. Especially if the manually add it.  

Yes, and that is exactly why, by design, at the start, i said, let's do this as an option, or in Zoggys idea, an API parameter.

**Comment by thezoggy** [comment]
sensible defaults is dependent on the use... as those using automation where the intelligence on retry/failing is on the 3rd party app.. but not all apps can/do have it.. and then there are people that dont really use it with automation so they want sab to just retry and if it doesnt work.. deal with that later. why I suggest we let the 'app' dictate how many retries/aggressive sab should be.. that way we can keep the defaults as is (since no one else has complained or asked for something different) and that way we dont have to add yet another special override/option.. and maintains backwards compatibility and easy to add the logic (set variable to default, override if passed).

**Comment by thezoggy** [comment]
about indexer 'api limits' that is pretty much on the user to deal with if they dont like sab/their app keeps running into them. indexers put limits for a reason..  user should donate / vote with the dollar.. or just run their own.

**Comment by JackDandy** [comment]
> 'api limits' that is pretty much on the user to deal with

Should SABnzbd only be able to handle the "reached limit" condition by wait...retry, blocking on it though?

**Comment by Safihre** [comment]
If the indexer provides `retry-after` header, that's what we use of course and it will deviate from the regular Retry intervals. But not every indexer implements that.

**Comment by thezoggy** [comment]
sab handles api limit/retry/etc.. at least the ones that follow nzedb/newznab/etc spec.
now just because the site does do what they are supposed to.. if there is middle ware (nzbhydra) that introduces the possibility that the headers are changed // https://github.com/theotherp/nzbhydra/issues/678

**Comment by JackDandy** [comment]
> not every indexer implements that

With all variances, the flow is constant, wait.. retry, repeat, on failure/limit, so the only thing to add is retry from 0 to configurable n times.  And if SABnzbd can do this via the API, then more uses cases than ever before, existing and otherwise can be met, no?

**Comment by Safihre** [comment]
To do this we would have to introduce another NZB-specific field that propagates through all the functions and probably will never be used.
I just don't see the general use-case so much, since no other people asked for this.
So I feel like sticking for for the Special setting, so people that really can't wait 55 minutes have an option to change it.

**Comment by JackDandy** [comment]
This change only applies to errors and not API hits.

**Comment by Safihre** [comment]
Really? It should cover all cases that result in a Retry of the fetch.

**Comment by JackDandy** [comment]
> Really? It should cover

That sounds unsure like you are guessing and not testing for the actual case condition.

Anyway, thanks.

**Comment by Safihre** [comment]
I tested it locally with a mock server, but maybe there was some other non-covered case.
Should really make more tests for the official  test battery 🤔

**Comment by thezoggy** [comment]
so having the url retry globally configurable covers only one use case (user has flaky connection).. for the purpose of JackDandy and other 3rd party app devs.. I dont honestly see this being a fix. 

use case example, user has a rss feed in sab.. but the site has cloudflare issues.. so they change the retry to 99 or something. which would make 3rd party apps even take longer...

**Comment by Safihre** [comment]
If they have Cloudflare issues, they won't be able to even send headers to tell us to Retry later.
And what's wrong with that? If the indexer knows it's available later, why abort that if it might be a unique file that's worth the wait?

**Comment by JackDandy** [comment]
I think you are missing the point @Safihre ... @thezoggy gave the example to simply illustrate an event that may trigger a user to change the setting, the actual event type (Cloudflare) is unimportant.

Think of it like this, if a user changes a global retry setting, then that setting will likely not be suitable for another case type, after all, manual vs automation operate on different flows... 

in an automated 3rd party app flow, a quick response to an error or anything else (e.g. api hit limit) is far better handled with the shortest response time (read: 0 retries) possible.  However, on the other hand, a manual or RSS addition may want to retry 10 times given that there is no automated fallback logic.

**Comment by Safihre** [comment]
I just doubt anyone will use it. That it's just not a option we introduce for 1 3rd party application. 

But we can open a Feature Request for it and maybe someone will implement it.
