### ISSUE TITLE
Remove SMPL skins and RSS Queue/History 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1117]
In an effort to clean up the giant that's `interface.py` I finally want to deprecate the SMPL skin in 2.4.0.
Even Plush uses mostly the API to operations, only SMPL doesn't and requires special functions for everything.
for 2.3.3 I already added a [note to the bottom of the page](https://github.com/sabnzbd/sabnzbd/commit/f77cc43b7d59fa77b802560998647075761e1155) and it won't be shown anymore in the [skin-selector](https://github.com/sabnzbd/sabnzbd/commit/3bdb8407d209ff19ca6bf5164d0b90c137383082) in Config > General.

Additionally I would also like to remove the RSS (`localhost:8080/rss`) endpoints. They are not described anywhere and just take up useless code.

Are there objections to this?

**Comment by thezoggy** [comment]
I personally always loved smpl and used it when plush was at it's prime. But after the last few years? Of using glitter I haven't seen the need to use anything else. I'm sure there will be some people that freak out that it's going away though.

**Comment by gevrey** [comment]
Hiya.

I just raised an issue about the /rss missing
I was actually using it. Is it gone for good? Any alternative?

Cheers

**Comment by Safihre** [comment]
With the Python 3 rewrite they will be removed.

**Comment by Safihre** [comment]
Smpl removed in the `py3` branch.
RSS removed already in 2.3.x releases.
