### ISSUE TITLE
Tls 1.3

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1119]
Tls 1.3 just got approved.
https://www.bleepingcomputer.com/news/security/ietf-approves-tls-13-as-internet-standard/

Just tossing this out there so we can update / test against once it's available

**Comment by Safihre** [comment]
Seems it's coming in 2.7.15, if compiled against OpenSSL 1.1.1. Let's see if they do that for the Windows/MacOS installers. https://docs.python.org/2/library/ssl.html#ssl.OP_NO_TLSv1_3

Might be a while before they release it: https://www.python.org/dev/peps/pep-0373/ only says "2018".

**Comment by sanderjo** [comment]
Pubquiz: when will we see the first TLS1.3 enabled news **server** ?

HTTPS server, with TLS1.3:
```
sander@haring:~/git/testssl.sh$ ./testssl.sh --protocols --ip one www.cloudflare.com:https | grep -e " SSLv" -e " TLS "
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): draft 23

```

No TLS1.3 on eweka newsserver:

```
sander@haring:~/git/testssl.sh$ ./testssl.sh --protocols --ip one newsreader3.eweka.nl | grep -e " SSLv" -e " TLS "
 SSLv2      not offered (OK)
 SSLv3      offered (NOT ok)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered

```

**Comment by sanderjo** [comment]
Ah ... nice (although a dirty trick to approach a web server with a NNTPS client ... which doesn't matter for the TLS)

```
2018-04-20 20:33:52,337::INFO::[newswrapper:228] -1@tls13.crypto.mozilla.org: Connected using TLSv1.3 (TLS_AES_128_GCM_SHA256)
```
So: SAB says **Connected using TLSv1.3** !!!

Environment details:
```
sander@debian:~$ python --version
Python 2.7.15rc1

sander@debian:~$ openssl version
OpenSSL 1.1.1-pre4 (beta) 3 Apr 2018

sander@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux unstable (sid)
Release:        unstable
Codename:       sid

```

**Comment by Safihre** [comment]
Cool! 🔒 👍

**Comment by thezoggy** [comment]
getting closer, final has been tagged.. just no binaries yet
https://github.com/python/cpython/releases/tag/v2.7.15

**Comment by thezoggy** [comment]
yes in deed. figure it would also be good to have the whole bump in python and minor changes grouped together so if something breaks.. we know it was 2.7.15 rather than x new feature (direct write)

**Comment by JackDandy** [comment]
[Py 2.7.15 Windows @python.org](https://www.python.org/ftp/python/2.7.15/python-2.7.15.msi)

**Comment by JackDandy** [comment]
Official [Python 2.7.15](https://www.python.org/ftp/python/2.7.15/python-2.7.15.msi) Windows @python.org

CRC32: 102dc8ce
MD4: 19ebc5b0b40bb962f7c83fb73ef2ea5e
MD5: 023e49c9fba54914ebc05c4662a93ffe
SHA-1: 70830dd027e250a17b2265e24440785b1e2f3a16
SHA-256: 1afa1b10cf491c788baa340066a813d5ec6232561472cfc3af1664dbc6f29f77

**Comment by thezoggy** [comment]
https://blog.cloudflare.com/you-get-tls-1-3-you-get-tls-1-3-everyone-gets-tls-1-3/

**Comment by thezoggy** [comment]
to note that appveyor has 2.7.15 now:
https://www.appveyor.com/docs/build-environment/#python

**Comment by sanderjo** [comment]
> https://blog.cloudflare.com/you-get-tls-1-3-you-get-tls-1-3-everyone-gets-tls-1-3/

From that article: 

> For our Free and Pro customers not much changes, they already had TLS 1.3 enabled by default from the start. 

So I tried for our own self-test host:

```
$ ./testssl.sh --protocols --ip one self-test.sabnzbd.org

<snip>
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): draft 23
 NPN/SPDY   h2, http/1.1 (advertised)
 ALPN/HTTP2 h2, http/1.1 (offered)

 Done 2018-05-18 07:27:01 [   6s] -->> 104.25.236.23:443 (self-test.sabnzbd.org) <<--

```
So indeed TLS 1.3. Nice.

**Comment by Safihre** [comment]
@sanderjo Pointed out to me that Python 2.7.15 for Windows only has OpenSSL 1.0.2 and as such doesn't support TLS 1.3.
But as the tests of @sanderjo show, all is going well when Python is using OpenSSL 1.1.0 👍 
I think we can see this as closed!

**Comment by sanderjo** [comment]
Yep, the magic combination is Python 2.7.15 and openssl 1.1.1 on client side, and a TLS 1.3 enabled newsserver on the server side.

And here's the magic in sabnzbd.log:

``
cat `/.sabnzbd/logs/sabnzbd.log | grep -e Python-version -e SSL -e Connected

2018-05-18 07:58:16,624::INFO::[sabnzbdplus:1149] Python-version = 2.7.15 (default, May  1 2018, 05:55:50)

2018-05-18 07:58:16,627::INFO::[sabnzbdplus:1165] SSL version = OpenSSL 1.1.1-pre6 (beta) 1 May 2018

2018-05-18 09:14:54,885::INFO::[newswrapper:228] -1@news.appelboor.com: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
```

**Comment by sanderjo** [comment]
PS: If you want to play with SABnzbd with TLS 1.3, you can use this Docker image: https://github.com/sanderjo/SABnzbd-with-TLS-1.3

**Comment by thezoggy** [comment]
might want to update readme that python 2.7.15 was used for sab 2.3.4 build which included tls 1.3 support..?
```

Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] [cp1252]
-- | --
OpenSSL 1.0.2o  27 Mar 2018

```

**Comment by Safihre** [comment]
@thezoggy when I tested it, it didn't.. Have you tested it? Also can't find it anywhere in the OpenSSL release notes for the 1.0.2 branch. Seems to be 1.1.x specific.

**Comment by thezoggy** [comment]
looks like you are right.. could have sworn 2.7.15 included tls 1.3 support :/

**Comment by sanderjo** [comment]
FYI: Ubuntu 18.10 has OpenSSL 1.1.1, and thus TLS1.3

```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```
And SABnzbd can automagically speak TLS 1.3, as shown here (talking to a local NNTPS server also doing TLS 1.3):
```
2018-11-04 22:26:23,262::INFO::[newswrapper:210] -1@127.0.0.1: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2018-11-04 22:28:57,847::INFO::[newswrapper:210] -1@fdd6:5a2d:3f20:0:bc19:5b6d:f436:c5b0: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
```

... And now we wait ... for public newsservers to speak TLS1.3 too.

**Comment by sanderjo** [comment]
Oh, I don't if I had already said this, but on Ubuntu 18.10, SABnzbd's WebGUI also speaks TLS1.3:

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      offered
 TLS 1.1    offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered

```
