### ISSUE TITLE
Dynamic Size Units

### ISSUE THREAD

**Issue by digitaldelboy** [sabnzbd/sabnzbd#1121]
Would it be possible to add an option to change the sizes from MB to GB or even KB.

**Comment by Safihre** [comment]
Why? It adapts now to what best fits the number. The display is also optimized for it (spacings).

**Comment by digitaldelboy** [comment]
No real reason, I would just prefer it.

**Comment by Cpuroast** [comment]
Safihre, that may be the case, but it doesn't seem to switch to GB fast enough, it seems to like displaying sizes well over 1024MB as MB instead of GB.

**Comment by Safihre** [comment]
That depends for the situation, in some cases we overrule the automatic switching.
Where should it switch to Gb but doesn't?

**Comment by Safihre** [comment]
@Cpuroast ping?
