### ISSUE TITLE
Accessing https://[::1]:8080/ results in `Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check`

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1122]
Accessing https://[::1]:8080/ results in `Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check` in my webbrowser. That is not good.

Inside SAB's GUI, I see `Refused connection with hostname "[" from: ::1>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

So `hostname "["` ... ?

https://127.0.0.1:8080/ works OK

FWIW: tested on Windows 10. Real test to be done on Linux.

**Comment by Safihre** [comment]
Good catch.
I should change this part:
```python
host = host.split(':')[0].lower()
```

**Comment by sanderjo** [comment]
Suggestion:

`host.rsplit(':',1)[0].replace('[','').replace(']','')`

```
>>> host1
'www.blabla.com:8080/sabnzbd'
>>> host1.rsplit(':',1)[0].replace('[','').replace(']','')
'www.blabla.com'
```

```
>>> host2
'[2001:aaaa::333]:8080/sabnzbd'
>>> host2.rsplit(':',1)[0].replace('[','').replace(']','')
'2001:aaaa::333'
```

```
>>> host3
'www.aaaa.com'
>>> host3.rsplit(':',1)[0].replace('[','').replace(']','')
'www.aaaa.com'
```

**Comment by sanderjo** [comment]
Same error for http://ip6-localhost:8080/ and http://ip6-loopback:8080/

They are in Ubuntu's /etc/hosts
```
127.0.0.1	localhost
127.0.1.1	witte

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
... so the if-line has to take care of that too, IMHO

```
    # Remove the port-part
    host = host.split(':')[0].lower()

    # Fine if localhost or IP
    if host == 'localhost' or probablyipv4(host) or probablyipv6(host):
        return True
```

I'll try some things. BRB

**Comment by Safihre** [comment]
@sanderjo But did you add `ip6-loopback` to `host_whitelist`?

**Comment by sanderjo** [comment]
No, I didn't; Just like *I* didn't add ip6-loopback to /etc/hosts (Ubuntu did).

So ... options:
- just leave it this way; indeed let (niche) user add ip6-loopback etc to host_whitelist
- let SAB add it to host_whitelist (tricky?)
- let interface.py do the work: if name resolves to ::1 or 127.0.0.1, *and* just a hostname (no dots in it), then OK.

BTW: This works for [::1]. Shall I send a PR?
```
    # Remove the port-part, and be aware of IPv6 addresses
    # OLD host = host.split(':')[0].lower()
    host = host.rsplit(':',1)[0].lower().replace('[','').replace(']','')
```

**Comment by Safihre** [comment]
> just leave it this way; indeed let (niche) user add ip6-loopback etc to host_whitelist
 
People using that address should be comfortable enough to add it. The check also needs to have good performance, so we can't do a look-up for every interface request. Too slow.

Isn't it maybe just an idea to change the `probablyipv6` function? Maybe a bit prettier code.
Make it into this, so it accepts also the `[` and `]`?
```python
def probablyipv6(ip):
    if ip.count(':') >= 2 and re.sub('[0123456789abcdefABCDEF:\[\]]', '', ip) == '':
        return True
    else:
        return False
```

**Comment by sanderjo** [comment]
Ah, another one that is refused http://witte.local.:8080/ (that is the bonjour / zeroconf / mDNS name, see https://en.wikipedia.org/wiki/.local )

**Comment by sanderjo** [comment]
> Make it into this, so it accepts also the [ and ]?

I understand the method, but [ and ] are not valid parts of an IPv6 address. So I think we should really replace() them, and not do tricks in the great function probablyipv6

**Comment by Safihre** [comment]
@sanderjo we specifically write that in the Wiki, to seperate multiple values using a comma :)

**Comment by sanderjo** [comment]
The code
```
host = host.rsplit(':',1)[0].lower()
```
does not cover all cases, specifically 
```
[::1]
[2001::333:1]
```
(so, IPv6 address without any port mentioned, thus with SABnzb running on port 80)

Luckily this RegExp can solve that:
```
host = re.sub(':[0123456789]+$', '', host).lower()
```

**Comment by Safihre** [comment]
👍
