### ISSUE TITLE
Postprocessing/Sorting behaves differently between RAR and 7Zip archive sets

### ISSUE THREAD

**Issue by Squiggles4321** [sabnzbd/sabnzbd#1124]
Hi,

Copy and paste of a Reddit post I made in which Safihre request I raise it as a bug over here.  Hope it contains everything needed.

I have a category defined that is linked to the Movie Sorting functionality, simply using the directory name and file extension to end up with a properly named file in my destination directory.  `%dn.%ext`.  When a RAR set is downloaded, this works as expected.
```
/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP.mkv
```
When a 7Zip set is downloaded it results in a sub directory of the intended name, then the obscured file name.
```
/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/876234876acd98798a987a987aaefefef78.mkv
```
When I use a category that doesn't have the renamer enabled, both archive sets result in the same output structure of sub directory properly named then obscured file name, which demonstrates that the archives were created without any additional relative folder structure being included.  To verify I created my own sets of RARs and 7Zips to confirm using.
```
7z a -t7z -mx=0 -r -v105216000b /home/username/outputdirectory7z/test.7z /home/username/sourcefiletopack.mkv
rar a -ep1  -m0 -r -v105216000b /home/username/outputdirectoryrar/test.rar /home/username/sourcefiletopack.mkv
```
From viewing the debug logs RARs have the temporary directory where it has been unpacked to, it renames the obscured name to the real name in the directory, then moves the final file to the directory above (destination directory) and cleans up the temporary directory.
```
    [sorting:633] Renaming Generic file
    [sorting:664] Rename: /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/876234876acd98798a987a987aaefefef78.mkv to /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/Filename.S02E02.All.The.Other.Data-GRP.mkv
    [misc:1108] Renaming "/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/876234876acd98798a987a987aaefefef78.mkv" to "/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/Filename.S02E02.All.The.Other.Data-GRP.mkv"
    [sorting:1088] Give files in set "Filename.S02E02.All.The.Other.Data-GRP" matching names.
    [misc:1192] [sabnzbd.misc.cleanup_empty_directories] Deleting dir /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP
    [misc:1017] Moving (overwrite: 0) /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/Filename.S02E02.All.The.Other.Data-GRP.mkv => /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP.mkv
    [misc:1108] Renaming "/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP/Filename.S02E02.All.The.Other.Data-GRP.mkv" to "/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP.mkv"
    [misc:1192] [sabnzbd.misc.cleanup_empty_directories] Deleting dir /home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP
```
When the 7Zip archive is being processed the debug logs show that the tvsort process only kicks in after the notification email is already sent and is treating it as a TV Show (it never actually does anything to it, just says 'Found TV Show'), even though the Series renamer/sorting system is disabled in my settings and not linked to any categories and the only renaming that occurs is the `_UNPACK_Filename.S02E02.All.The.Other.Data-GRP` directory to `Filename.S02E02.All.The.Other.Data-GRP` directory containing the obscured name.
```
    [misc:1186] [sabnzbd.newsunpack.seven_extract_core] Deleting file /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP/876234876acd98798a987a987aaefefef78.7z
    [postproc:391] unpack_magic finished on Filename.S02E02.All.The.Other.Data-GRP
    [misc:1592] Applying permissions 0755 (octal) to /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP
    [misc:1592] Applying permissions 0644 (octal) to /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP/876234876acd98798a987a987aaefefef78.mkv
    [misc:1192] [sabnzbd.postproc.cleanup_list] Deleting dir /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP
    [misc:1192] [sabnzbd.postproc.cleanup_list] Deleting dir /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP
    [misc:1108] Renaming "/home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP" to "/home/username/destinationdirectory/Filename.S02E02.All.The.Other.Data-GRP"
    [misc:1192] [sabnzbd.postproc.rename_and_collapse_folder] Deleting dir /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP
    [emailer:150] Notification e-mail successfully sent
    [misc:1192] [sabnzbd.postproc.cleanup_list] Deleting dir /home/username/destinationdirectory/_UNPACK_Filename.S02E02.All.The.Other.Data-GRP
    [sorting:210] Found TV Show (Filename.S02E02.All.The.Other.Data-GRP)
```
I would have thought that the renaming would be executed by passing the temporary/unpack/working directory to the renamer system once the files existed on the filesystem and by that time the way that they got there should be irrelevant.  

Software versions:
SABnzbd - sabnzbdplus-2.3.2 (rev=1cac5799eb3f74f2e39942453b7b244fb0366e9a) - JCFP non beta PPA repo build.
Python-version = 2.7.14

Any other info needed, let me know.

**Comment by Safihre** [comment]
Thanks! Could you maybe share the test-NZB's? 
Can just drag-and-drop them here on the new-comment field to upload.

**Comment by Squiggles4321** [comment]
Attached.  Same file tagged with RAR and 7Zip for each archiving mode.  Verified they are behaving as I described above.

[big_buck_bunny.zip](https://github.com/sabnzbd/sabnzbd/files/1868131/big_buck_bunny.zip)

**Comment by Safihre** [comment]
Odd, when I test it the files gets sorted as desired.
```
2018-04-02 15:24:50,486::DEBUG::[misc:1106] Renaming "\\?\C:\folder\big_buck_bunny_1080p_surround-7Zip\7f25efc3e06449adb8a5d0abde8fc630.avi" to "\\?\C:\folder\big_buck_bunny_1080p_surround-7Zip\big_buck_bunny_1080p_surround-7Zip.avi"
```
Could you maybe send me the whole log? If you click `Show Logging` in the Status and Interface settings it will anonymize your log+settings for safe sharing 💯

**Comment by Squiggles4321** [comment]
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/1868295/sabnzbd.log)

Log attached and this is the output in the destination directory.

big_buck_bunny_1080p_surround-7Zip  big_buck_bunny_1080p_surround-RAR.avi

./big_buck_bunny_1080p_surround-7Zip:
7f25efc3e06449adb8a5d0abde8fc630.avi

**Comment by Safihre** [comment]
Very strange.. 
It says:
```
2018-04-02 22:17:02,566::DEBUG::[sorting:527] Found Movie (big_buck_bunny_1080p_surround-7Zip)
```
But then just skips the actual renaming.
We seem to need to dig deeper to find out why.
Would you be able to change a file so we can get more info?

In the file `sabnzbd/postproc.py`, I think it should be in `/usr/share/sabnzbdplus`.
Change line 464 from:
```python
            # TV/Movie/Date Renaming code part 2 - rename and move files to parent folder
```
to:
```python
            # TV/Movie/Date Renaming code part 2 - rename and move files to parent folder
            logging.warning('workdir_complete: %s', workdir_complete)
            logging.warning('newfiles: %s', newfiles)
            logging.warning('all_ok: %s', all_ok)
            logging.warning('job_result: %s', job_result)
            logging.warning('file_sorter.sort_file: %s', file_sorter.sort_file)
```

**Restart SABnzbd**, then download the 7zip-file again.
It should now give you some warning messages in the interface and the log at the end of the download, could you post them here?

**Comment by Squiggles4321** [comment]
No problem.

Warnings thrown:
::WARNING::[postproc:465] workdir_complete: /home/<USERNAME>/data/nzb/big_buck_bunny_1080p_surround-7Zip
::WARNING::[postproc:466] newfiles: []
::WARNING::[postproc:467] all_ok: True
::WARNING::[postproc:468] job_result: 0
::WARNING::[postproc:469] file_sorter.sort_file: True

Full log below.

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/1870604/sabnzbd.log)

**Comment by Safihre** [comment]
> ::WARNING::[postproc:466] newfiles: []

That's the problem. I found the problem.
Didn't find this bug before because there's Windows-specific code in there which sort of accidentally fixes this problem.

**Comment by Squiggles4321** [comment]
That's good to hear, at least it isn't something really obscure.
