### ISSUE TITLE
Regression in 2.3.3RC1 when adding NZBs using sabconnect++

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1125]
I noticed a regression in 2.3.3RC1 when adding NZBs using sabconnect++.

In 2.3.3RC1 when adding NZBs using sabconnect++, while the category is correctly matched, the associated post-processing script is stripped. So you end up with the correct category for the job, it goes in the correct folder, but no post-processing script is selected.

This does not occur in 2.3.2 and 2.3.3 Beta1.

**Comment by Safihre** [comment]
Could you enable Debug logging and show the part of when it's being added? Does it add via url or upload?

**Comment by Cpuroast** [comment]
It adds it via URL. I'll look for the debug info.

**Comment by Cpuroast** [comment]
I compared the debug output on 2.3.3Beta1 and 2.3.3RC1 and they are identical.
This the call sab gets from Sabconnect++:

API-call from 127.0.0.1 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.66 Safari/537.36] {'output': u'json', 'apikey': u'APIKey', 'mode': u'addurl', '_': u'SomeNumber', 'name': u'URL'}
