### ISSUE TITLE
[Feature Request] Server Graph Scaling and Data Presentation

### ISSUE THREAD

**Issue by jamver** [sabnzbd/sabnzbd#1126]
The server traffic usage graphs are fantastic, however, it would be good if it was possible to better understand the data used by the lesser used servers, which for the most part, looks almost like a horizontal 0 line with minor, very small bumps.

![screenshot](https://user-images.githubusercontent.com/7053594/38289900-ee702822-381b-11e8-9f38-ccfe3daebe07.png)

I see four (not incompatible) solutions to resolve this issue:

1. Scale Change Button: a button could be added to the servers page which switches the graph range setting between the (default) global maximum range scale applied to all server graphs, to an local maximum range scale for each server.  This "Scale Change Button" solution could switch between: 
    1. Global Maximum Scaled View (only) (default)
    2. Local Maximum Scaled View (only)
    3. Combined Global and Local Maximum Scaled View

2. Secondary Data Set: the current graphs could be modified to have an additional Y-axis for local maximum range (scale shown on the right-hand side of the graph) and the data could either be presented as a line graph (as default graph using the same data, local maximum scaled), or as a vertical bar graph.  This secondary data set should be displayed in a different colour and set behind the global maximum range scaled view.

(Please excuse my markup) A combined graph might look something like the following, and would provide a lot more useful information than the current graph.

![screenshot_with_example_markup](https://user-images.githubusercontent.com/7053594/38290471-aa8e5c84-381e-11e8-8e75-140d955d0c97.png)

3. Manual Scale Adjustment: add a manual scale/range setting per-graph which would enable users to manually inspect and scale each graph to solve their curiosity (and allow dynamic scaling/viewing to determine the size of smaller peaks within a month).

4. Mouseover Tooltips: provide mouseover tooltips to allow users to read the exact data usage for each day (column) of a graph.

**Comment by Safihre** [comment]
Great suggestions! 
I just kind of hacked this together with the idea to use the smallest possible plotting library. 
But that also limits the functionality more than I would have liked. 
For example the tool tips would be great, but aren't really supported by this library. 

Are you by any chance experienced with Javascript plotting libraries?

**Comment by Safihre** [comment]
The scaling to the max server  was actually specifically requested in #1028. It didn't used to do that originally. 
I'd prefer to switch to a better library. I'm also quite missing the tool tips.
