### ISSUE TITLE
Let Chrome trust https://localhost:9090/sabnzbd/

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1127]
Chrome is getting pickier and pickier about security with both HTTP and HTTPS. 

With some work, Chrome does trust https://localhost:9090/sabnzbd/ and https://127.0.0.1:9090/sabnzbd/ and https://192.168.1.10:9090/sabnzbd/ and https://sammie-1710:9090/sabnzbd/ (for example).

I'll send a PR this weekend. Can you please test and review @jcfp and @Safihre . And I'm interested in results on other OSes en webbrowsers.

Steps:
1) put the desired names and (private) IP addresses into the SAN of SAB's cert. I have achieved that in SAB's certgen.py (the current code is incorrect)
2) In Chrome, go to https://localhost:9090/sabnzbd/, and export the cert
3) In your OS, import that cert
4) restart Chrome, and Chrome trusts https://localhost:9090/sabnzbd/

Maybe, if wanted, we can make 2 and 3 easier.

Rationale

1) Chrome considers HTTP as insecure
2) Chrome considers HTTPS to a self-signed certificate as insecure
3) A cert for an IP address is impossible, so insecure too

... at least ... I thought a cert for an IP address was impossible, but https://1.1.1.1/ proves it is possible. In the cert, there are these SANs:
```
DNS Name: *.cloudflare-dns.com
IP Address: 1.1.1.1
IP Address: 1.0.0.1
DNS Name: cloudflare-dns.com
IP Address: 2606:4700:4700::1111
IP Address: 2606:4700:4700::1001
```

Furthermore, https://leehblue.com/add-self-signed-ssl-google-chrome-ubuntu-16-04/ tells  how to import that into OS and Chrome. Result: Chrome trusts the site (read: SABnzbd) again.

The Cert with SANs:
![image](https://user-images.githubusercontent.com/1273502/38442336-4d511e78-39e8-11e8-8926-70947c366374.png)

```
$ file Downloads/sabnzbd-with-all.bin
Downloads/sabnzbd-with-all.bin: PEM certificate
```
Import on Linux:
`certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n Downloads/sabnzbd-with-all.bin -i Downloads/sabnzbd-with-all.bin`

Result:

![image](https://user-images.githubusercontent.com/1273502/38442669-55e8c382-39e9-11e8-90ce-8a48ed7924db.png)

![image](https://user-images.githubusercontent.com/1273502/38442704-6bf81a4c-39e9-11e8-85c1-977e65673eec.png)

![image](https://user-images.githubusercontent.com/1273502/38442722-78d88ff8-39e9-11e8-9b41-0bc3a0773de8.png)

![image](https://user-images.githubusercontent.com/1273502/38442447-a635870e-39e8-11e8-93a0-3b2b14e3e94e.png)

**Comment by sanderjo** [comment]
PR sent.

@shypike You have Windows, right? Can you check the PR (first delete the old cert), then follow http://www.nullalo.com/en/chrome-how-to-install-self-signed-ssl-certificates/ 

FWIW: In Chrome, via chrome://settings/certificates?search=certificates you can import certificates ... but not on Linux; you need the CLI tool for that.

**Comment by OmgImAlexis** [comment]
Did you test these certs on other browsers?

**Comment by thezoggy** [comment]
I personally wouldn't want a localhost cert added to the root so that other apps could use for malicious intent

**Comment by OmgImAlexis** [comment]
@sanderjo I can't see the PR being merged if it causes the certs to no longer work in other browsers.

**Comment by jcfp** [comment]
> I don't understand you. Furthermore: localhost has always been in the cert

The key difference is that it has to be added to a trusted global cert store to work around the stupidity of chrome. That might enable mitm style attacks with traffic redirected via localhost, piggybacking on that trust. Whereas before, this was an exception made at web browser level and linked to a specific domain/port combo.

**Comment by sanderjo** [comment]
> Whereas before, this was an exception made at web browser level and linked to a specific domain/port combo.

Really? Where/how?

Anyway: if true, I would say your statement is not only true for localhost, but also for 127.0.01, and ::1. And if so, the whole PR is a bad idea. And more general: importing a self-signed cert with localhost/127.0.0.1 is bad. 
Correct?

**Comment by jcfp** [comment]
> Really? Where/how?
I assume web browsers remember such an exception only for a particular address + cert combo, at least it would make sense to me to implement it that way. Didn't test though. Either way, chrome basically replaces that with distrust of its own user base to the point that they lock out anyone with basic understanding of networking from making their own informed decisions. Those that continue using chrome will either have to live with that or set themselves up with "real" certs (e.g. dyndns with letsencrypt).

The issue with the PR (didn't test further since I'm too ill atm) isn't in the code itself but the need for the whole export from browser, import to global cert store part. That makes it not work out of the box regardless of the hostnames and ip addresses sab adds to the certificate, is complicated for most users, and might be a security issue.

**Comment by thezoggy** [comment]
was traveling when I responded via phone. So to clarify, yes we allow localhost cert from sab, but its only useful if the cert is added, which the user can add an exception. If the user chooses the add the exception then that is on them for adding something with localhost... if it was in the root store, where anyone can use it / no exception is needed.. thats where i have the problem.
