### ISSUE TITLE
TLS1.2

### ISSUE THREAD

**Issue by drakex90** [sabnzbd/sabnzbd#1130]
Is there a way to force Sabnzbd to use only TLS1.2 especially for cipher AES256-SHA as some of the providers like XSnews/Cheapnews/Xennanews strongest provided cipher is AES256-SHA and they make it available for both SSLv3 and TLS1.2 and as you know SSLv3 is not really that secure.

https://www.ssllabs.com/ssltest/analyze.html?d=reader.xsnews.nl&latest

**Comment by Safihre** [comment]
We use Python's `create_default_context()`, which disables SSLv2 and SSLv3.
https://docs.python.org/2/library/ssl.html#ssl.create_default_context

**Comment by drakex90** [comment]
Thanks for the doc link.

**Comment by drakex90** [comment]
What happens with a provider like new.newsguy.com which really doesn't provide TLS 1.2 and only other less secure protocols.

**Comment by Safihre** [comment]
I'm not a true expert, but does that fixes it?
Technically we could introduce a TLSv1.2(+) switch to force it, I could understand the desire for that. 

(Python 2.7.15 will be released within next 2 weeks which supports TLSv1.3)

**Comment by Safihre** [comment]
It will use TLS 1.0 or 1.1.

**Comment by drakex90** [comment]
As for now no one is supporting TLS 1.3 as far as I have done my testing also yeah it would be good if you can introduce the TLSv1.2 switch.

**Comment by thezoggy** [comment]
from the python 2.7.15 changes,
> - bpo-29136: Add TLS 1.3 cipher suites and OP_NO_TLSv1_3.
> - bpo-33184: Update Windows build to use OpenSSL 1.0.2o.

**Comment by sanderjo** [comment]
> What happens with a provider like new.newsguy.com which really doesn't provide TLS 1.2 and only other less secure protocols.

I wanted to say: SAB will tell you, in sabnzbd.log:

```
2018-04-19 15:45:53,973::INFO::[newswrapper:122] 4@newsreader.eweka.nl: Connected using TLSv1.2 (AES128-SHA)
```
... but ... newS.newsguy.com (new.newsguy.com does not exist) is completely non-safe: 

https://www.appelboor.com/cgi-bin/check_newsserver.py?server=news.newsguy.com gives three red flags (also three red NOKs in https://www.appelboor.com/newsservers/newsservers-with-SSL.html) 

https://www.sslshopper.com/ssl-checker.html#hostname=news.newsguy.com:563 tells newsguy's certificate is incorrect.

So ... IMHO ... avoid newsguy if you care about TLS/SSL/security.

**Comment by drakex90** [comment]
> But ... newS.newsguy.com (new.newsguy.com does not exist) is completely non-safe. And not just "less secure protocols". And Sab will tell you (and will not connect)

Are you sure am not using their own cert in the cacert.pem file anymore and am not getting SSL err anymore though am using RC2 maybe you are on stable release.

**Comment by sanderjo** [comment]
@drakex90 

All RC2. But how about you: on which version of python and openssl are you running? And what does SAB say in the Config (general) page? Because on my old Ubuntu 14.04 9 (with a too old python), SAB says 

> Warning Secure (SSL) connections from SABnzbd to newsservers and HTTPS websites will be encrypted, however, validating a server's identity using its certificates is not possible. Python 2.7.9 or above, OpenSSL 1.0.2 or above and up-to-date local CA certificates are required.

... and indeed SAB does connect to news.newsguy.com without complaining ... :-(

**Comment by drakex90** [comment]
Sabnzbd: 2.3.3RC2
Python Version: 2.7.14
OpenSSL: OpenSSL 1.0.2k 26 Jan 2017
OS: Windows 8.1

Am able to connect to without the ssl cert issue.

**Comment by Safihre** [comment]
@drakex90 I am also on Windows 10 and I also get the warning just like @sanderjo. Very strange.

I am a bit hesitant to introduce a TLSv12-switch.. It feels a bit exotic. What do you think @sanderjo ?

**Comment by Safihre** [comment]
@drakex90 Do you maybe use Avast or another viruscanner? Or other security software like Malwarebytes?
What happens if you disable those and then check again for the connection?

I ask this because Avast injects itself into every connection, inserting it's own certificates. So even bad-certificate servers will suddenly show as correct in SABnzbd.

**Comment by sanderjo** [comment]
> I am a bit hesitant to introduce a TLSv12-switch.. It feels a bit exotic. What do you think @sanderjo ?

Me too. I think such a switch will cause more questions and problems. And problems are elsewhere, as this thread proofs.

And with the current tools you can already achieve that:

- https://www.appelboor.com/newsservers/newsservers-with-SSL.html will already show the TLS status. So user's responsibility is to choose a newsserver provider that provides the security he/she wants
- Python will choose the highest TLS available on both sides (client and server)
- SABnzbd will report the TLS and the cipher used.

... that should be enough to see that your safe.

**Comment by drakex90** [comment]
@Safihre My cacert file https://cloud.disroot.org/s/2m96DxHWYz4pTbd am not using any AV though I manually use Malwarebytes but its not running when am testing earlier before RC2 to bypass newsguy self cert err issue I did paste the newsguy cert from here https://acc.newsguy.com/newsguy2016.crt but after installing RC2 I haven't edited the original file.

**Comment by drakex90** [comment]
@Safihre Another issue that am facing is while using news.premium-news.de it works sometimes with cipher ECDHE-RSA-AES256-GCM-SHA384 but other times it throws err "Failed to connect: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661) 4@205.153.76.36:563" though when using cipher AES256-SHA it always works because its also present in TLSv1.0 so thats why a hardswitch to always use TLSv1.2 will help to root out these servers same with XSnews as am not sure if its TLSv1.2 which is being used every time.

**Comment by sanderjo** [comment]
news.premium-news.de has a correct TLS setup ... Again, just see https://www.appelboor.com/cgi-bin/check_newsserver.py?server=news.premium-news.de and https://www.sslshopper.com/ssl-checker.html#hostname=news.premium-news.de:563 to verify.

So, as you have problems with news.premium-news.de, the problems are on your side (=your computer). You have Windows and you say you have touched your cacert / root certificate, so I really can't help you with that.

**Comment by Safihre** [comment]
Yes, most of them use load balancers that can influence what security is used.
Personally I'd prefer to handle this by forcing ciphers. This also keeps us similar to other software like nzbget.

**Comment by drakex90** [comment]
@sanderjo Thanks what I did was edited my host file so that news.premium-news.de always uses 205.153.76.35 as for using these faulty servers am just testing them out seeing what I can squeeze the most out of them.

**Comment by drakex90** [comment]
Lastly I only want to be sure that while using
- reader.xsnews.nl
- news.cheapnews.eu
- news.usenet-server.de
Sabnzbd is always choosing TLSv1.2 as the strongest cipher available for these three is AES256-SHA which is also available in TLSv1.1 and TLSv1.0

**Comment by Safihre** [comment]
After some discussion we still think it's better not to introduce a switch for this. It's a rather specialist situation and wouldn't benefit more than very few users.
Unfortunately news-severs use shitty security, but at least with cipher-strength you can still require them to do the best possible. 
If it wasn't for @sanderjo's work, they would still all be using self-signed certificates.
