### ISSUE TITLE
Invalid NZB file - Junk after document element

### ISSUE THREAD

**Issue by bguidotti** [sabnzbd/sabnzbd#1133]
I'm suddenly receiving the error message:
"Invalid NZB file filename.nzb, skipping (reason=junk after document element, line=whatever)"

The offending line that SAB is choking on is at the end of the NZB files.  When I remove this line, and leave the EOF just as `</nzb>,` it parses and imports fine.

`<?xml version="1.0" encoding="utf-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/"><channel><newznab:response offset="0" total="0"/></channel></rss>`

Is this an indexer problem, or an SAB problem?

**Comment by Safihre** [comment]
That's junk indeed, so it's an indexer problem I would say.
The `rss` part shouldn't be in an NZB for sure.

**Comment by bguidotti** [comment]
Thanks.  I'll take it up with the indexer.
