### ISSUE TITLE
Direct Unpacking Completed but stopped in History

### ISSUE THREAD

**Issue by lysiumm** [sabnzbd/sabnzbd#1134]
Here's a screenshot after about an hour, https://i.imgur.com/MgQXieM.jpg https://i.imgur.com/TE5IGCp.jpg 

How do I make it abort correctly?

**Comment by lysiumm** [comment]
I also have a lot of files that get stuck on Waiting https://i.imgur.com/UBYc4MH.jpg

How do you actually fix these?

**Comment by Safihre** [comment]
Restart SABnzbd. It's too late to tell now what caused this.

**Comment by orenwolf** [comment]
I can confirm the same issue, started after upgrading to 2.3.3. OSX 10.13.4. Restarting or queue repair does not solve the issue.
