### ISSUE TITLE
[Feature Request] Please Add CORS Support

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1136]
Please consider adding SABNZBD server support for CORS.
Ref: https://enable-cors.org/

Currently:
![example](https://user-images.githubusercontent.com/17044982/39391931-ae9f6178-4aee-11e8-8757-b587b18435d0.png)

Normally you can just add the header:
`Access-Control-Allow-Origin: *`

_NB: This would allow for 3rd-party User Interfaces to be made, I'm making one._

**Comment by Safihre** [comment]
What do you think @beardog108?
Would make sense for the `/api` endpoint.

Cool to hear you are making a new user interface, will it be full featured or subset? If full featured, we can also integrate it in SABnzbd directly. 
Can we see it somewhere? :+1:

**Comment by hl2guide** [comment]
Most likely full featured, however it's too early on in development so far.
The main features I'm aiming for are:
- Responsive layout and font size for small and large displays
- Support for custom fonts
- Light and Dark modes
- Charts and proper progress indicators
- Colour blind modes
- High contrast mode

**Comment by Safihre** [comment]
Cool! This is also how I started with SABnzbd a few years back: I hated the Plush interface so I made a new one, Glitter.
And now I do everything 😁
I could use some help.. Too little time to take up big projects (like interface rework).

**Comment by Safihre** [comment]
If you find and API endpoint is missing, please open an issue and I can add it :+1:.
There's quite a few actions that don't have proper API implementation and are only available through "template" URLs.
Or if the API endpoint doesn't make sense or has too little information, we can change this too.

**Comment by beardog108** [comment]
If the API key is securely generated, there should be no security issue that I can think of for enabling it on /api. It would be cool to have user created interfaces.

**Comment by Safihre** [comment]
Added it 👍 
Looking forward to see what you create for new interface! ❤️
