### ISSUE TITLE
Host_Whitelist seems to be Case Sensitive

### ISSUE THREAD

**Issue by etaardvark** [sabnzbd/sabnzbd#1137]
Just upgraded to 2.3.3, and I think i found a minor issue.
By default, it's picked up the Uppercase version of the machine hostname and added it to the Host_Whitelist, but when requesting the interface via the machine name in Lowercase access was denied

Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check

Accessing the server by IP address (either v6 or v4) works correctly, as does adding the machine name in both upper and lower case.

Changing the Host_Whitelist to have the machine name in Lower Case sorted the problem.

I'm using a dual IPv6/IPv4 machine, running Server 2012 as the host

**Comment by Safihre** [comment]
Sorry about that, it was a design flaw.
Fixed it in https://github.com/sabnzbd/sabnzbd/commit/58bd12b08302f460f7387f48adfeef9ce82e4516
If many reports come in, I will maybe have to push another release..
