### ISSUE TITLE
[Feature] white list hostname if fqdn is supplied in host_whitelist 

### ISSUE THREAD

**Issue by defkev** [sabnzbd/sabnzbd#1138]
Just upgrade to 2.3.3 and got "locked out" by the new host_whitelist feature as it defaulted to my boxes fqdn (fully qualified domain name) and i make heavy use of dns-suffix within my lan, out of pure laziness.

So if `host_whitelist = host.domain.local` is set include `host` as well without the need to explicitly do `host_whitelist = host.domain.local, host`

I get that this feature is intended to protect people from dns hijacking if sab is run on a public interface, where fqdn's are used exclusively.

**Comment by Safihre** [comment]
Sorry I don't think I understand fully, the `.local` is a protected range?
How about the `domain` part in front of it?

Too bad nobody reported this during all the testing releases  :/

**Comment by thezoggy** [comment]
.local is osx specific usually.. probably why

**Comment by Safihre** [comment]
Hmm, seems like an edge-case maybe. Not a wide-spread setup.
Will leave this open to see if others want this to.

**Comment by defkev** [comment]
Its by no means game breaking, just saves people running sab within a LAN (like myself :grin:) going the extra mile.

**Comment by sanderjo** [comment]
I'm a .local user to: Ubuntu to Ubuntu. For example http://nanopineo2.local.:8080/

> Too bad nobody reported this during all the testing releases :/

Ah ... well ... during testing, I just added "nanopineo2.local." to the white list. I did not consider it a bug.

Regardless of a decision to implement it or not, we could reduce the request to "If a request comes in ending in .local or .local. , then just accept it". Regardless of host name or <fqdn>.local. (Just like a request with an IP address is always accepted.) 
I'm assuming that is safe, but please correct me if I'm wrong.

**Comment by Safihre** [comment]
I can find very little reference to this `.local.`, why is that used instead of just `.local`?

**Comment by sanderjo** [comment]
> I can find very little reference to this .local., why is that used instead of just .local?

A dot at the end means "Dear DNS, that's the full path. Do no try to put domains behind it". Works always, for example: https://sabnzbd.org./downloads (note the dot)

**Comment by sanderjo** [comment]
With my PR, SAB will automatically accept urls ending in .local and .local.

Example:
![screenshot from 2018-05-04 08-49-32](https://user-images.githubusercontent.com/1273502/39615736-1e246042-4f78-11e8-8f56-7277d2585f00.png)

**Comment by defkev** [comment]
Not really what i was looking for, as the network stack will do the dns-suffix'ing resolving the hostname but the client will still access the hostname directly.

If anything you would need to unpack the fqdn's in host_whitelist using the dot and extract the first part, like:

`Request sab -> unpack sab.domain.local -> return sab -> pass`

I'll give it another shot on the next release non the less.

**Comment by Safihre** [comment]
It is based on the `Host` send by the browser, so what you type into the address bar. Unless you have proxy magic, it should go directly to Sab where it is then checked for. Like @sanderjo showed.

**Comment by sanderjo** [comment]
@defkev , you wrote

> The host field in the GET request header send by the browser would still be sab:8080 and not sab.whatever.local:8080 causing it to miss host_whitelist

If the GET has "sab", and that is the host name, that works already because SABnzbd knows & accepts the hostname.
If the GET has "sab", and that's not the hostname (and thus SAB doesn't know), you have it add it (exactly because of security reasons).
If the GET has "sab.blabla.local" (because you typed it, or the DNS client added that), that will work with the new Pull Request.

Do you agree? If so, which use case are we missing?

**Comment by defkev** [comment]
The hostname of the server running sab is e.g. `sab.blabla.local` and `host_whitelist = sab.blabla.local` after upgrading to 2.3.3

Client accessing the server is on the same domain `blabla.local` (DNS-Suffix/Search domain = `blabla.local`) thus the server running sab can be resolved using just `sab` as the DNS client will append the DNS-Suffix/Search domain prior to quering the DNS server.

Client accesses http://sab:8080, host field in request header will be `sab:8080` causing it to miss host_whitelist as the DNS-Suffix/Search domain is omitted.

e.g. something like (from the top of my head without any testing)

```python
import re
host_whitelist = ["sab.blabla.local"]
host = "sab" # host only part of host field in request header
r = re.compile("^" + host + "\.")
if filter(r.match, host_whitelist):
    return True
```

**Comment by sanderjo** [comment]
I still don't understand your use case. So how about: let's wait for SAB 2.3.4 (containing the .local solution) and you try that.

**Comment by defkev** [comment]
Sorry but i am afraid i cannot explain it in any more detail than i already did a few times along with providing a code snippet outlining a possible solution to the feature request at hand.

As i already wrote your `.local` (`.local.`) implementation isn't addressing what i am asking for as my entire deployment (or any deployment using a local nameserver) is designed to spare the user the need of using just that in the first place.

**Comment by thezoggy** [comment]
why not just add the required hostnames to whitelist instead of us trying to programmatically guess what you want?

**Comment by defkev** [comment]
Its what i had to do to restore access after upgrading and its by no means guessing as the information is already there, all it takes is to programmatically extract it.
