### ISSUE TITLE
macOS/OSX UnRar crashing on every DL

### ISSUE THREAD

**Issue by grillp** [sabnzbd/sabnzbd#1139]
Mornign FOlks,

Me with the Old Mac 2007 iMac (Dual Core Intel, OSX 10.11.6 (15G20015)) back again with some problems with the latest and greatest 2.3.3..

This time SABnzb starts fine, but whenever a download is in progress , I get a popup saying that 'unrar' has crashed. At the end of the DL, all the RAR files are in the completed download directory, but not unRARed.

I tried running the embedded `unrar` command directly in the terminal in the 2.3.3 App bundle and I get:
> /Volumes/SABnzbd-2.3.3/SABnzbd.app/Contents/Resources/osx/unrar/unrar
> [1]    66396 illegal hardware instruction  /Volumes/SABnzbd-2.3.3/SABnzbd.app/Contents/Resources/osx/unrar/unrar

So a similar error as when SABznb was being built with newer X-Code images.
If I try it on the previous version (2.3.2) I get the help screen.

Could this be a similar issue?

G./

**Comment by thezoggy** [comment]
in 2.3.3 we included 64bit binaries for unrar but looks like it only supports macos not the now legacy osx.

* OS X El Capitan – version 10.11, released in 2015
* macOS Sierra – version 10.12, released in 2016
* macOS High Sierra – version 10.13, released in 2017

so I would try doing this..  install sab 2.3.3 but replace the rar binary included from sab 2.3.2 and see if that makes a difference?

**Comment by grillp** [comment]
Yeah, that would do it.

I am sure replacing it will do the trick.. I really am running close to being unsupportable ;-) 

Thnaks for the efforts.. may have to switch to Linux version soon..

**Comment by grillp** [comment]
So that did work to fix my problem. 

Any chance of including both and using the 32bit in older OS versions?

**Comment by grillp** [comment]
Never mind. 

Saw your comment on the other thread. ;-)

Cheers

**Comment by Safihre** [comment]
Should we compile unrar differently? 
On Travis we can use OS X 10.11, maybe if we compile it on that one we get 64bit but still compatible with all versions.

**Comment by Safihre** [comment]
@grillp could you try the `unrar` file from this link: https://homebrew.bintray.com/bottles/unrar-5.6.3.el_capitan.bottle.tar.gz (in the `bin` folder)
Does that work?

**Comment by Safihre** [comment]
@thezoggy @sanderjo So it is not the 32bit issue, it's the way it is compiled and needs to be compiled on older version of `xcode`. This is possible on Travis, I will fix this.

**Comment by Safihre** [comment]
@grillp Could you try this release?
https://github.com/sabnzbd/sabbuild/releases/tag/2.3.3-osx
I used the Homebrew version of unrar 5.5.0 that's ElCapitan compatible.

**Comment by grillp** [comment]
@Safihre, that new version works for me. Thanks.

**Comment by Safihre** [comment]
Great.
Closed by 5c78c7855b47d5076f481971120a4aa894a71d1e.

**Comment by Cpuroast** [comment]
Looks like it's specifically related to 10.11 and his older CPU as seen below on my 10.11 VM.

/Volumes/SABnzbd-2.3.3/SABnzbd.app/Contents/Resources/osx/unrar/unrar
UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
               <@listfiles...> <path_to_extract\>

system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G20015)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Test’s Mac
      User Name: Test (test)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 10 minutes
