### ISSUE TITLE
large queue performance

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1142]
Hi All, 
Running on Opensuse, latest git master, 16 gig RAM, ssd boot, 7200rpm 1TB temp disk.

After a NAS issue, i lost a giant stack of data so SB/LL/My/CP/HP are all repoppulating. I've noticed with very large queues, 15k+ that download speed drops.

I limit at 4MB/s, up to about 1000 jobs, full speed 
Now with the queue built up, i peak at about 750k/s

Is there anything i can do about this?

**Comment by Safihre** [comment]
Not really.. Sabnzbd isn't made for this. I'm surprised it even handles 5000 jobs well.
Probably not having the interface open will help, since for each refresh we have to iterate over each item in the queue. 
I think nzbget is probably better suited for your needs :)
