### ISSUE TITLE
[Feature Request] Open completed files from history view or completed notification

### ISSUE THREAD

**Issue by GFoley83** [sabnzbd/sabnzbd#1144]
Seems like an obvious one but it would be great to be able to open a file directly from the history view or by clicking on the completed notification which would remove the need to navigate to the complete folder and double-click on the file.

**Comment by thezoggy** [comment]
i have security concerns about exposing users file system in that way... also dealing with cross platform.

**Comment by sanderjo** [comment]
Yeas, nice feature, but Chrome forbids clicking on it. See http://www.appelboor.com/dump/html-to-local-drive.html

**Comment by sanderjo** [comment]
@albino1 ... in a page from a web server? So "http://" or "https://" in the URL? If so, please share a screenshot.

**Comment by albino1** [comment]
@sanderjo, I misunderstood the original test, I was just opening the URL directly, which of course works fine.  However, you're right, that trying to click an HTML link with a `file:///` destination doesn't work.  At least not without whatever tricks @Safihre is cooking up.

**Comment by Safihre** [comment]
From my experiments I learned that from Python we can't give actions to individual notifications (it is possible from native-languages like C#) so we can only track basic actions like "there was a click, bye".
We could store the directory to open in some global state-variable, but when a new notification appears it would be overwritten. Clicking on the first notification would open the directory of the second job.

That would only leave just opening the Complete Folder, but that can also be achieved by right clicking on the icon.
All together I am afraid we can't make this feature request happen 😢
