### ISSUE TITLE
Several queue items sitting in "waiting" but in the History pane

### ISSUE THREAD

**Issue by orenwolf** [sabnzbd/sabnzbd#1145]
Continuing the discussion from #1134,

Since 2.3.3 (OSX 10.13.4) several downloads are sitting in the history pane with "clock" icons and listed as either "waiting" or "direct unpack: completed". REstart or queue repair doesn't seem to change this status. The app is not paused.

Selecting the jobs in "Direct Unpack: completed" shows their status as "waiting" even though they are essentially "done", just need to move to the complete folder.

The ones in "waiting" status, however, are all aborted from not having enough articles available.

**Comment by orenwolf** [comment]
Ok, I was able to get the queue to update by force-killing the sabnzbd process via pkill. It looks like on restart it was just hanging and not restarting.

**Comment by thezoggy** [comment]
wonder if this is another issue doe to the unrar in 2.3.3 on osx.. maybe we should just release a 2.3.4 with new 7zip + unrar ?

**Comment by Safihre** [comment]
Could you enable Debug logging in the Status window and then after it happens again send me the log at Safihre@sabnzbd.org? I can then try to analyse and post relevant bits here.

**Comment by Safihre** [comment]
Could you maybe also use this version? It's a modified 2.3.3.
https://github.com/sabnzbd/sabbuild/releases/tag/2.3.3-osx

**Comment by Safihre** [comment]
@orenwolf would you have time to test the newer version linked above? 🥇

**Comment by orenwolf** [comment]
I've gone ahead and installed it. Unfortunately, I can't trigger the issue on-demand, so I suppose we'll have to wait and see.

**Comment by Safihre** [comment]
@orenwolf no more problems?

**Comment by Safihre** [comment]
Great!
