### ISSUE TITLE
URLGetter fails when HTTP 200 response omits Reason-Phrase

### ISSUE THREAD

**Issue by enilfodne** [sabnzbd/sabnzbd#1146]
During testing NZBhydra2, i found that `SABnzbd` stalls when fetching `nzb` files in Proxy mode from `NZBhydra2`.  It turns out that for some reason `NZBhydra2` responds with:

```http
HTTP/1.1 200
```
instead of
```http
HTTP/1.1 200 OK
```

`SABnzbd` [checks](https://github.com/sabnzbd/sabnzbd/blob/master/sabnzbd/urlgrabber.py#L364) the `Reason-Phrase` of the request and fails as its missing. I'm not sure if there's a reason for this check, but according to [RFC2616](https://tools.ietf.org/html/rfc2616), `Reason-Phrase` is optional part and may be omitted from the headers.

I've opened an [issue](nzbhydra2/issues/170) with `NZBhydra2` as it was the only application that i found problematic, but according to its author its not a bug in `NZBhydra2` and its not really reproducible.

**Comment by thezoggy** [comment]
we should only care about the code (200)

**Comment by Safihre** [comment]
Agreed. I guess this kinda sneaked into the code.
