### ISSUE TITLE
[Help wanted] Pauzed downloads are resumed

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1148]
We are facing some issues with sabnzbd 2.3.2 when it was update with spotnet.
Spotnet uses sabnzbd via api interface.
When a item has been set on pause, the next start of spotnet + sabnzbd will unpause that item and start downloading it.
We observed this behaviour not in the previous version we have used : 1.0.2
It only happens when sabnzbd is started with spotnet and not when run stand alone.
To start sabnzbd we pass a specific ini file with -f 
Further we use cmdline switches -d --new -l2

If have attached a log file made from start with a paused item and also the sabnzbd.ini file used.
Please could you help us solve this issue ?

[logs.zip](https://github.com/sabnzbd/sabnzbd/files/2042735/logs.zip)

**Comment by mesa57** [comment]
Found by carefully comparing the used ini file with the default ini file from sabnzbd 2.3.2
It was converted_nzo_pickles = 1 which was not in our current sabnzbd.ini file.

**Comment by mesa57** [comment]
Thank you for looking into the issue and pointing out an improvement point that next time we should carefully read the release notes 😃

**Comment by Safihre** [comment]
I would actually also suggest to use 2.3.4, since there's some annoying bugs in 2.3.2/2.3.4 that were fixed 😊

**Comment by mesa57** [comment]
Actually we will do that in our next release. We always include the latest version of sabnzbd.
I was wondering, what happens if for some users the queue's are not yet updated, but we suddenly include converted_nzo_pickles = 1 ?

**Comment by mesa57** [comment]
No, nothing is kept between restarts. Reasons for that are:
- Spotnet put's server information in the ini file. That information comes from spotnet configuration. For instance, the number of connections is calculated (maximum - spotnet usage = for sabnzbd).
- Spotnet expect sabnzbd to behave in a predefined way, we are showing queue and status on our own UI.

**Comment by Safihre** [comment]
Hmm, seems you might need some detection for that.
These are other "check" variables that might need a work-around:
`sched_converted` > Schedules converted in version 2.x to new-style. Shouldn't cause much errors, there is backwards compatibility.
`direct_unpack_tested` > Direct Unpack speed of disk tested. Now probably it will do a disk-speed-test every time Spotnet is restarted.

**Comment by mesa57** [comment]
Ok, thank you 😄 
Schedules are not used in spotnet -> sabnzbd, so that will not be a problem.
We will put direct_unpack_tested to 1.
Btw, we've tested direct unpack, but it leaves some garbage in the download folder. Could be caused by the uploader, but after putting direct unpack to false it was gone.

**Comment by Safihre** [comment]
If it leaves garbage, then please report an issue so we can fix it.
I and many others have used it with much pleasure since it can save so so much time.
