### ISSUE TITLE
[Feature request] Show per-server speed

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1150]
See here:
https://www.reddit.com/r/usenet/comments/8n77eb/see_download_speed_of_individual_servers_sabnzbd/

I can image this being usefull, if we can find a fast way to do so. Maybe less accurate than the regular BPSMeter.

**Comment by Safihre** [comment]
I was actually thinking more of a counter in the Status and Interface settings window on the Severs page.

**Comment by atg22896** [comment]
Any progress on this?

**Comment by Safihre** [comment]
Closed by #1704
