### ISSUE TITLE
sab - show par2 creator on failures

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1153]
nzbget added this in their last version, we should follow suite to provide the info in a similar fashion.
https://github.com/nzbget/nzbget/issues/467

**Comment by thezoggy** [comment]
to note while this does work it also includes the NUL byte characters at the end of the packet.

what sab logged:
![nul](http://zoggy.net/notepad%2B%2B_2018-09-11_08-56-38.png)

what multipar see's:
![nul2](http://zoggy.net/MultiPar_2018-09-11_08-57-31.png)

**Comment by Safihre** [comment]
You're right. I'll add an `.rstrip()`.

**Comment by thezoggy** [comment]
ty! man github has been crap today :/
