### ISSUE TITLE
[Feature request] Add/remove/start/stop rss url via api

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#1154]
[Feature request] Add/remove/start/stop rss url via api

**Comment by scriptzteam** [comment]
Oh jeez and i am writing php scripts like an crazy frog xD

Any quick hint for api? :D

**Comment by Safihre** [comment]
Looking at the code I experimented and found so far (can also be JSON of course):
```
http://localhost:8080/sabnzbd/api?mode=set_config&output=xml&section=rss&name=Feed1
```
Then you can change stuff by adding it's name to the request. For example to enable it:
```
http://localhost:8080/sabnzbd/api?mode=set_config&output=xml&section=rss&name=Feed1&enable=1
```
The other stuff like `filter` I think you have to specify it in the correct list-format, have to figure that out.

**Comment by Safihre** [comment]
Unfortunately it seems not possible to set filters using the API. It doesn't allow empty parameters.

**Comment by scriptzteam** [comment]
But would be cool add rss url directly from an api, so we can add/remove/reload rss urls by an api

**Comment by Safihre** [comment]
I added the new actions to the API.
Always first add the feed.


To **add**:
`api?mode=set_config&section=rss&name=XXX&filter_action=add`

Make sure to specify  the 2 mandatory options:
`filter_text`
`filter_type`

Optional arguments:
`new_index` (defaults to `0`, cannot be greater than #filters + 1)
`script`
`cat`
`priority`
`enabled` (defaults to `0`)

To **update**:
`api?mode=set_config&section=rss&name=XXX&filter_action=update&index=Y`
All options the same as above,
If you specify `new_index` it will try to move it there.
Since the indexes are array-indexes you should always check the output to see where your filter moved after an update.

To **delete**:
`api?mode=set_config&section=rss&name=XXX&filter_action=delete&index=Y`

**Comment by scriptzteam** [comment]
Yeah thats all fine, but can we add rss url by the api? :)

**Comment by Safihre** [comment]
@scriptzteam You can already do that! Just use a `name=X` that's new and it will add it.

**Comment by scriptzteam** [comment]
@Safihre now how do i tell via rss to fetch the nzbs and start the nzb download process? i did tried via api **rss_now** but this wont load them, i can load the rss nzbs via "Read Feed Button" only

**Comment by Safihre** [comment]
The `rss_now` should do the trick. Can you see what the logs say when you send the API-command?
And it still ignores jobs that were present on the first fetch, maybe that's the problem?

**Comment by scriptzteam** [comment]
Hmm in the log it says

2018-10-24 16:33:47,322::INFO::[rss:506] Starting scheduled RSS read-out for "Test"
2018-10-24 16:34:03,077::INFO::[rss:520] Finished scheduled RSS read-outs

And it just load the rss contents but wont actuall download the nzbs...

**Comment by Safihre** [comment]
Is this on `+Debug` log-setting? I would expect at least a few lines more.

**Comment by scriptzteam** [comment]
Cant we via api do something like the Force download button do ?

+Debug
```
2018-10-25 13:14:40,011::INFO::[rss:506] Starting scheduled RSS read-out for "TEST"
2018-10-25 13:14:40,012::DEBUG::[rss:280] Running feedparser on https://****
2018-10-25 13:14:40,795::DEBUG::[rss:282] Done parsing https://******
2018-10-25 13:14:40,798::DEBUG::[rss:374] Trying title *****
2018-10-25 13:14:40,798::DEBUG::[rss:385] Size 0
2018-10-25 13:14:40,798::DEBUG::[rss:423] Filter matched on rule 0
2018-10-25 13:14:40,799::DEBUG::[rss:374] Trying ...
```

**Comment by Safihre** [comment]
The difference is that it ignores the first-time items, so only new items (since first fetch) are downloaded.
Need to add a `force=1` parameter to the `rss_now` call.

**Comment by scriptzteam** [comment]
That´s what i mean the force=1 would be the super coolest :)

You are the most super duper person ;)

**Comment by scriptzteam** [comment]
Does soemthing changed in new release? when updating rss with different url the filter with order 0 is not enabled, and before was...

**Comment by Safihre** [comment]
No, not since september the code wasn't changed.

**Comment by scriptzteam** [comment]
After and update via api the order 0 got disabled tick, when manually enable it works, but then again when update via api it disables :(

https://i.imgur.com/i7cFtkx.png

Call: SABURL:PORT/api?mode=set_config&section=rss&name=NAME&uri=SOMEURL&filter_action=update&apikey=KEY&enable=1&filter_text=*&filter_type=*

**Comment by scriptzteam** [comment]
Also even if i did ` SABURL:PORT/api?mode=set_config&section=rss&name=NAME&uri=SOMEURL&filter_action=update&apikey=KEY&enable=1&filter_text=*&filter_type=*`  and the RSS NAME does not even exists it create new rss with the RSS NAME and its also has the filter 0 DISABLED!

**Comment by Safihre** [comment]
The keyword is `enabled` not `enable`.

**Comment by Safihre** [comment]
I should add these commands to the wiki.. sorry about that 😨

**Comment by scriptzteam** [comment]
How da fuk i overlooke that thx!

Also how is even possible it worked before :D

**Comment by scriptzteam** [comment]
Aaaand again :( it somehow does not want to take that wildcard `*` as filter or what?

https://i.imgur.com/3aPM2pf.png
