### ISSUE TITLE
add context to download total

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1155]
in the history footer, for example I have:
>  0 B Today 100.4 GB This month 10.4 TB Total 

the context of today and 'this month' is understood. but total is not.
should have a tooltip that shows the 'context' of the total when hover. 
so for today. show todays date.
for this month.. show the `for mm/yyyy`.
for total, should show `since dd/mm/yyyy`

because its not easy for most people to look in their .db to gleam what the actual 'start' date is for the total... to know that oh its been 6.5 years or whatever the duration is for the Total

**Comment by albino1** [comment]
It would be nice to have a tooltip/popup that told you how that was spread across your different providers as well.

**Comment by thezoggy** [comment]
@albino1 that breakdown can somewhat be found in the Servers page. But a proper 'history' breakdown page with stats would be nice.. but thats a bit outside of this GI scope

**Comment by albino1** [comment]
Fair point, that's true.

**Comment by Safihre** [comment]
We don't really keep the date of the `grand_total` so we can't show that date. 
Seems like too much work to keep track of this and push it via API..

**Comment by thezoggy** [comment]
seems pretty easy to just extend get_history_size to also share this_month/month_timest and the first history time for the grand total. just need to add it in such a way it doesnt break anything else catch wherever we reference it

doing this outside of sab also isnt too hard it turns out,
```
sqlite3.exe history1.db "select completed from history order by id limit 1"
1287910839

python -c "import time;print time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(1287910839))"
2010-10-24 04:00:39
```

**Comment by Safihre** [comment]
That's not the same thing. We don't calculate the total size from the history, it's just a integer in the BPS meter. Only when the data is somehow corrupted we fall back to the database. But if people have deleted jobs from the history, it doesn't work.

**Comment by Safihre** [comment]
The most relevant request in here would be to list the first ever measured-date, since we can expect the user to understand which month he is in.
But we just don't have that date. The history-database entries get removed when a user removes them via the GUI. 
I thought of using the creation-date of the `totals10.db` file, however, this seems [to be impossible cross-platform](https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python/237084). Seems there's no other way?

**Comment by Safihre** [comment]
Closing, seems to just be no way to do this.
