### ISSUE TITLE
/usr/bin/python not found

### ISSUE THREAD

**Issue by rubenverhoef** [sabnzbd/sabnzbd#1157]
Hi,

My python is located in /usr/bin/local/python and i have no write access to /usr/bin/ so i can not make a symbolic link.

I think it is better to use /usr/bin/env python in stead of the hard coded location of python.

This issue is present in several files.

**Comment by thezoggy** [comment]
reason why we dont do this is explained here: https://github.com/sabnzbd/sabnzbd/issues/400
need to check if its still valid

**Comment by Safihre** [comment]
This whole Linux thing is just too diversified, if I change it to `/usr/bin/env python` now I am sure within 1 year there will be another issue asking it to be `/usr/bin/python`..

**Comment by rubenverhoef** [comment]
Okay thanks for the explaination, i have edit my startup script so it would launch correctly.
