### ISSUE TITLE
2.3.4 - servers -- name vs displayname

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1159]
friend asked me why he was seeing failed logins to `eunews.blocknews.net` in sab showing up but does not have a server configured it....

sab log:
```
sabnzbd.log:2018-07-13 04:44:00,266::INFO::[downloader:490] 6@eunews.blocknews.net: Initiating connection
sabnzbd.log:2018-07-13 04:44:00,267::INFO::[downloader:490] 7@eunews.blocknews.net: Initiating connection
sabnzbd.log:2018-07-13 04:44:00,267::INFO::[downloader:490] 8@eunews.blocknews.net: Initiating connection
sabnzbd.log:2018-07-13 04:44:00,268::INFO::[downloader:490] 9@eunews.blocknews.net: Initiating connection
sabnzbd.log:2018-07-13 04:44:00,268::INFO::[downloader:490] 10@eunews.blocknews.net: Initiating connection
sabnzbd.log:2018-07-13 04:44:01,930::ERROR::[downloader:659] Failed login for server eunews.blocknews.net
sabnzbd.log:2018-07-13 04:44:01,930::DEBUG::[downloader:849] Set planned server resume eunews.blocknews.net in 10 mins
sabnzbd.log:2018-07-13 04:44:28,492::INFO::[downloader:783] Thread 3@eunews.blocknews.net: forcing disconnect
sabnzbd.log:2018-07-13 04:44:28,492::INFO::[downloader:783] Thread 1@eunews.blocknews.net: forcing disconnect
sabnzbd.log:2018-07-13 04:44:28,492::INFO::[downloader:783] Thread 2@eunews.blocknews.net: forcing disconnect
```

I logged in and confirmed that none of the servers were blocknews but clearly saw what he was talking about. I then started to look at his sab ini and found:
```
[[eunews.blocknews.net]]
username = xxxxx
priority = 0
enable = 1
displayname = Frugal (US-HW)
name = eunews.blocknews.net
ssl_ciphers = RC4-MD5
notes = ""
connections = 10
ssl = 0
host = news.frugalusenet.com
timeout = 30
ssl_verify = 1
send_group = 0
password = xxxxx
optional = 1
port = 119
retention = 0
```

so in the gui on the server page it shows up as "Frugal (US-HW)' and the host is frugal..  and 'name' is never exposed. 
Viewing the source code I can see its hidden,

`            <input type="hidden" name="server" value="eunews.blocknews.net" />`

So you can now see the dilemma. We are using the 'name' in places which may or maynot be correct.. especially if someone added a server back in the day when the server name was the host and then changed the 'host' after we stopped exposing the name and used displayname.

so now the gui and the logs report back the wrong server because it uses name not displayname..

**Comment by Safihre** [comment]
Using `host` now everywhere to make it more clear.

**Comment by thezoggy** [comment]
thanks!
