### ISSUE TITLE
Http Errors showing up all of a sudden

### ISSUE THREAD

**Issue by skaforey** [sabnzbd/sabnzbd#1160]
For the past 3 or 4 days I get random occurences of this error when I visit the main page (and also pushed to my pushbullet notification)

I turned on debugging, and see the following at the exact timestamp of the error on the webpage:
https://pastebin.com/e2490nMP
```
2018-07-20 06:59:44,319::INFO::[_cplogging:219] [20/Jul/2018:06:59:44] HTTP
Request Headers:
  Content-Length: 0
  PRAGMA: no-cache
  HOST: t20.proxy-checks.com
  Remote-Addr: 95.25.119.105
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.5.21022; .NET CLR 3.5.30729; .NET CLR 3.0.30618)
  PROXY-CONNECTION: Keep-Alive
  ACCEPT-LANGUAGE: en-US;q=0.6,en;q=0.4
2018-07-20 06:59:44,319::ERROR::[_cplogging:219] [20/Jul/2018:06:59:44] HTTP
Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 220, in __call__
  File "cherrypy\_cpdispatch.pyo", line 60, in __call__
  File "cherrypy\_cptools.pyo", line 182, in handle_func
TypeError: staticfile() got multiple values for keyword argument 'filename'
```

Each error seems to be some sort of iteration from  HOST: t20.proxy-checks.com.  This seems like they are just checking random open ports to see if it's a proxy.  Is there any way to prevent these errors from happening? I have an API key and my site is user/password protected.

**Comment by sanderjo** [comment]
Same as here https://forums.sabnzbd.org/viewtopic.php?f=16&t=21664 ?

**Comment by sanderjo** [comment]
@Safihre 

This is the same as
https://github.com/cherrypy/cherrypy/issues/983#issuecomment-251724341
and
https://github.com/cherrypy/cherrypy/issues/983#issuecomment-403885452
, isn't it?

And same-same as https://github.com/cherrypy/cherrypy/issues/1623 ?

**Comment by Safihre** [comment]
Yes indeed @sanderjo!

**Comment by Safihre** [comment]
Closing this as an upstream `cherrypy` problem. We should be able to fix that when we go to Python 3 and use the latest CherryPy releases instead if our own custom one.
