### ISSUE TITLE
Minor link typo bug in wizard, final page, (not) linking to Folders config page

### ISSUE THREAD

**Issue by cbussa** [sabnzbd/sabnzbd#1163]
Installing via wizard.  In file two.html it shows the completed and incompleted folders, with a default setting and a gear icon link to change them.  But the link itself goes to: _http://<IP>:8080/sabnzbdconfig/folders_ which is WRONG, it should be ..._sabnzbd/config_..., there's a missing slash.

The relevant code is in two places, on lines 25 and 31 in **sabnzbd/interfaces/wizard/two.html**:
a href="${access_url}config/folders"

It should be _url}/config_ instead -- so **"${access_url}/config/folders"**

**Comment by Safihre** [comment]
Thanks for reporting 👍 🥇
