### ISSUE TITLE
Provide option to log post-processing command

### ISSUE THREAD

**Issue by brianredbeard** [sabnzbd/sabnzbd#1170]
Presently in the FAQ there is [the question](https://sabnzbd.org/wiki/faq#toc14):

> An NZB just failed post-processing, how do I re-process it?
At the moment there is no method to do this automatically in SABnzbd. However, the only time doing this should actually accomplish anything is if you had to kill a stalled Par2 or Unrar process. In all other cases, having SABnzbd try to re-try a download shouldn't do anything, since if SABnzbd failed it likely failed for a good reason. However, at a future date we may implement re-try post-processing as part of a broader post-processing queue rewrite.

As an alternative, providing some mechanism for logging _what_ the command was which was ran would give the user the ability to re-run the actual post-processing command and identify any issues which may have arisen.

**Comment by Safihre** [comment]
You can already see this in the log, just not in the interface.
