### ISSUE TITLE
The RSS feed for the download history is not accessible anymore

### ISSUE THREAD

**Issue by gevrey** [sabnzbd/sabnzbd#1175]
It used to be possible to read the RSS for the download history at:
http://127.0.0.1/sabnzbd/rss?mode=history

Since version 2.3.5 (or 2.3.4) it redirects to /sabnzbd/

Cheers

**Comment by Safihre** [comment]
True. This was removed due to now everybody switching to JSON and the RSS part not having really any of the features of the history API call..
I would siggest looking at the API documentation, you can also get the results via RSS markup from the API.

**Comment by gevrey** [comment]
"you can also get the results via RSS markup from the API"

How would you do that?

**Comment by Safihre** [comment]
For now it still supports `mode=rss`, but that will probably be removed in 3.0.0. So maybe use `mode=xml`.
