### ISSUE TITLE
completed downloads dolder is not on FAT

### ISSUE THREAD

**Issue by josephpyke1987** [sabnzbd/sabnzbd#1177]
im trying to install sabznbd in a lxc container on ubuntu 18.04 but while starting i gte completed downloads folder is not on fat and it just hangs all so tested on a fresh 18.04 vm with same results

**Comment by thezoggy** [comment]
Make sure logs are set to debug level. I would suspect it's a permission issue

**Comment by Safihre** [comment]
We run the `df -T` command on your complete folder. It will report a specific code if it's FAT.
Could you run this command and post the output here?
`df -T /path/to/dir`

**Comment by Safihre** [comment]
@josephpyke1987 any update?

**Comment by sanderjo** [comment]
> i gte completed downloads folder is not on fat 

That's good.

> and it just hangs all so tested on a fresh 18.04 vm with same results

How do you know it 'hangs'?
