### ISSUE TITLE
Synology package setting wrong permissions

### ISSUE THREAD

**Issue by zaadstra** [sabnzbd/sabnzbd#1178]
The updater on Synology is trying to set permissions at install and update.  The last couple of times it ended up in a mess and my 'download' share inaccessible. 
Yesterday, updating to 2.3.5,  for the first time the a new share 'downloads' was created by the update, which could not be opened and the 'download' share was inaccessible again. This time I started to fear that if permission setting in the installer will change more, I might loose data in the correct share.
Is it possible to disable this permission management?  Permissions are working well and should not be changed.

Symptoms: the permissions on /volume1/download/sabnzbd are set to d--------- and subfolders nzb_in, incomplete, . and .. are also set to this.  Hence the complete download share is inaccessible.

Synology DSM 5.2,  SABnzbd 2.3.5

Thanks,
Hans

**Comment by Safihre** [comment]
The Synology package is made by SynoCommunity, not officially by us.
You should report your issue there. 
I did help update the SynoCommunity package, but any permissions related stuff is SynoCommunity specific and there's hopefully more people there that can help :) 
https://github.com/SynoCommunity/spksrc/issues
