### ISSUE TITLE
ssl warning after clearing self-check host

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1179]
As ssl and integration of the system certificate store in python work fine on mainstream linux platforms, running the ssl self-check check on every program startup (and the associated ping to an external system) isn't necessary. As such, I tried to disable said check by clearing the _selftest_host_ setting in config->specials, only to be greeted by a generic warning on the config main page: _"Secure (SSL) connections from SABnzbd to newsservers and HTTPS websites will be encrypted, however, validating a server's identity using its certificates is not possible. Python 2.7.9 or above, OpenSSL 1.0.2 or above and up-to-date local CA certificates are required."_.

Obviously, all of the above requirements are still met, even if that cannot be tested for anymore. Please make not running the ssl check because it was intentionally disabled the equivalent of succesfully completing it. This is already the case for the ipv6 test (which uses the same test host setting), see [\_\_init\_\_.py#L1169](https://github.com/sabnzbd/sabnzbd/blob/e8ebeb843ce74dc42966293cc6057c832daa23cd/sabnzbd/__init__.py#L1169).

**Comment by Safihre** [comment]
True!
