### ISSUE TITLE
Enable editing of DEF_TIMEOUT constant

### ISSUE THREAD

**Issue by DapOrp** [sabnzbd/sabnzbd#1180]
Suggesting to add the ability to edit the DEF_TIMEOUT constant along with the max_url_retries to achieve a longer wait period when trying to 'fetch nzb from' sites that have limits on how many retrievals are allowed during a specific period of time.   

In these cases it is more beneficial to wait hours before retrying instead of minutes/seconds. 

Thank you.
-Dap

**Comment by Safihre** [comment]
If the indexer sends a `retry-after` header, we will respect it and only fetch after that time. Maybe the indexer could implement that?
Playing with general timeout settings seems a bit broad approach for a specific problem.

**Comment by Safihre** [comment]
Closing due to lack of response.
