### ISSUE TITLE
Unpacking suddenly slow

### ISSUE THREAD

**Issue by Geekoid** [sabnzbd/sabnzbd#1189]
About a month ago, unpacking became really slow. > 40 minute to unpack.
My complete/incomplete/Watch folders are all on SSD.
After unpacking, it moves the file to my NAS. (MyCloud)

The only thing that changed is upgrade to 2.3.5. I don't know if that caused the issue or a red herring.
I haven't found anything relevant to this issue on the internet.
System:
Win 10
i7 7700k
16 GB RAM
GeForce GTX 1080

**Comment by Geekoid** [comment]
I haven't tried unpacking it myself. I guess I should for a test.
SSD is 1Tb with 100Gb available. TRIM is on, but I ran it anyway. SANDisk app isn't reporting any errors and testing was fine.

**Comment by thezoggy** [comment]
ok, so when its slow. what is the bottleneck? disk io? cpu? does sab logs report any issues? etc. 
try disabling antivirus/make sure windows update isnt updating in the background

**Comment by Safihre** [comment]
Any updates on this @Geekoid? Seems more of a local problem than a Sab specific problem.

**Comment by Geekoid** [comment]
Odd thing, while I was watching it unpack, suddenly it returned to normal. I've been trying to repeat it. It's really baffling. 
Thanks for following up, I really do appreciate it.
