### ISSUE TITLE
64-bit Code being removed from wrong OS X .app versions

### ISSUE THREAD

**Issue by dotsam** [sabnzbd/sabnzbd#119]
In package.py, only x86 and PPC binaries are kept only when OSX_SL is false. I suspect that we want to do the opposite, and only provide these binaries to the OSX_SL release, and have the other OS X .app builds keep the 64-bit binaries.

**Comment by dotsam** [comment]
Can we look in to this again? SAB is now the only 32-bit app running on my system. If SAB can still be built as a fat binary, then any users with issues running the 64-bit app can run the app as 32-bit at their own discretion.

**Comment by shypike** [comment]
0.8.0 will probably be 32/64 bit, if testing proves that it works in 64bit mode.

**Comment by dotsam** [comment]
0.8.0 Beta 1 is still stripping out the 64 bit binaries from the OS X .app?

**Comment by shypike** [comment]
Call us conservative, but when something works we're not in a hurry to change it. With the coming of El Capitan we'll have to re-examine building anyway, so this will get new attention.

**Comment by shypike** [comment]
As of 0.8.0 Beta5 we distribute 32/64 again, because that's the simplest method.
For Yosemite and El Capitan 32bit might as well be dropped. That's due for 0.8.1

**Comment by shypike** [comment]
We went back to 32-bit only.
If not, we cannot get 10.11.4 to accept the signed app.
