### ISSUE TITLE
Old python: "Connected using TLSv1/SSLv3" ... not true

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1190]
With an old Python (< 2.7.9), I'm quite sure SAB reports an incorrect (too low) TLS version: each time SAB says "Connected using TLSv1/SSLv3"
I think we old Python, SAB should say "Connected using <unknown>" to avoid confusion.

With Python 2.7.6, SAB says:

```
2018-11-06 22:03:40,732::INFO::[newswrapper:121] 1@newsreader3.eweka.nl: 
Connected using TLSv1/SSLv3 (AES128-SHA)

2018-11-07 18:46:07,343::INFO::[newswrapper:121] 1@news.vipernews.com: 
Connected using TLSv1/SSLv3 (AES128-SHA)

```
... and even "TLSv1" when talking to a TLS1.2-only webserver:
```
2018-11-07 18:56:44,672::INFO::[newswrapper:210] -1@127.0.0.1: Connected using TLSv1/SSLv3 (ECDHE-RSA-AES128-GCM-SHA256)
```
The relevant SAB code
```
def get_ssl_version(sock):
    # Python <2.7.9 doesn't have SSLConnection.version()
    try:
        return sock.version()
    except:
        # We can only give an estimation from the cipher
        return sock.cipher()[1]
```
with SSLSocket.cipher():

> Returns a three-value tuple containing the name of the cipher being used, the version of the SSL protocol that defines its use, and the number of secret bits being used. If no connection has been established, returns None.

Hmmm " the version of the SSL protocol that _defines_ its use" ... it does not say "the version of the SSL protocol used"

So ... let's leave out this information for old Python-versions?

FWIW: Proof that this old Ubuntu does speak TLS 1.2
```
$ echo | openssl s_client -connect www.appelboor.com:https 2>&1  | grep -e Protocol -e Cipher

New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
```
... Hmmm, that first line ... is Python confused by that?

**Comment by sanderjo** [comment]
Xin chào @Safihre 

OK, fair enough. I was thinking of changing just one line of python code, but no change anymore is also a good indication for no support anymore per April 2019.

**Comment by sanderjo** [comment]
Two lines of code, and I have now this warning in my SAB GUI:

![image](https://user-images.githubusercontent.com/1273502/48193445-c52dd380-e34a-11e8-9a72-ccd4eb163120.png)

@Safihre what do you think?

**Comment by Safihre** [comment]
We will do such a message, but to detect Python 3 :)
