### ISSUE TITLE
Snap issues (missing unrar binay, ANSI encoding, multicore par2)

### ISSUE THREAD

**Issue by simonsolberg** [sabnzbd/sabnzbd#1197]
Hi, 

I'm trying to install SABnzbd through snap on Ubuntu 18.10. Is there a guide somewhere on how to do this? I had file permission issues (downloads are stored under /media/storage, but with interface removable-media on sabnzbd still didn't have permission to make directories. Tried installing in "classic" mode and the permission issue is resolved: 
`snap install sabnzbd --classic`

After resolving file permission I still have 3 issues: 
1) unrar binary... NOT found! Downloads will not be unpacked. 
2) SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads. 
3) Multicore par2 is missing? 

I thought maybe I had screwed with something by enabling the --classic flag so I tried uninstalling and installing again without the --classic flag, but I still have the same issues (only now the file permission issue is back). 

Screenshots from the --classic installation: 
![screenshot from 2018-12-01 21-05-05](https://user-images.githubusercontent.com/31542525/49332472-a0c1c180-f5ad-11e8-966e-4a097a4ea86a.png)
![screenshot from 2018-12-01 21-24-01](https://user-images.githubusercontent.com/31542525/49332586-e1bad580-f5af-11e8-85c1-a9e04a008ff3.png)

**Comment by thezoggy** [comment]
did you do this?
```
sudo apt install snapd
sudo snap install snapcraft --classic
```
Then from the sabnzbd project directory,
```
snapcraft
```
And then you should get a .snap file produced.

**Comment by simonsolberg** [comment]
No, I used 
> snap install sabnzbd --classic
This installed sabnzbd just fine and resolved my file permission issue, but I still have the three issues listed above. 
Should users make their own .snap files? I thought snaps were supposed to simplify installation to 
> snap install programname

**Comment by thezoggy** [comment]
per: https://snapcraft.io/sabnzbd
`sudo snap install sabnzbd`

and it should install the dependencies (if the arch is supported)
https://raw.githubusercontent.com/sabnzbd/sabnzbd/develop/snap/snapcraft.yaml

**Comment by Safihre** [comment]
@eberkund could you look into this?
When I first created my own snaps half a year ago locally, these were exactly the problems I was having. 
I never was able to fix the ANSI problem, maybe you can?

**Comment by eberkund** [comment]
I just submitted a PR to fix these issues.

Also FYI for installation you just need the command: `snap install sabnzbd`

Then it will be running on http://localhost:8080.
