### ISSUE TITLE
password extraction pattern to greedy

### ISSUE THREAD

**Issue by kmattim** [sabnzbd/sabnzbd#1199]
In my v2.3.5 installation I have issues with password extraction from the filename if the password is more than once included (e.g. due to wrong naming convention or misslabeling of the uploader).

For example a nzb with filename `some_title{{password}}_optional_some_more_text{{password}}.nzb` will end up as an extracted password of `password}}_optional_some_more_text{{password`

After some testing, it looks like the password extraction regex is to greedy (I hope my regex assumption is correct; otherwise theres something wrong in the password extraction handling?)
1. Tested with `{{.*}}` will result in one long greedy match (wrong password)
2. Tested with `{{.*?}}` as a lazy quantifier will result in two matches with the correct password

**Comment by thezoggy** [comment]
if you look at the code you can see we arent even using a regex to extract the pw but some fuzzy logic.. which deff could be improved

https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L1996

**Comment by jcfp** [comment]
>     2. Tested with `{{.*?}}` as a lazy quantifier will result in two matches with the correct password
This isn't necessarely true. Making the matching less greedy as suggested above causes a regression whenever the substring }} is part of a correctly supplied password (e.g. some_title{{Pass}}Word}}.nzb). Seems expensive just to work around an obvious indexer or uploader error?

**Comment by Safihre** [comment]
Agreed with @jcfp, this is on purpose to support `}}` inside the password.
