### ISSUE TITLE
Odd issue with multiple servers

### ISSUE THREAD

**Issue by ravensorb** [sabnzbd/sabnzbd#1208]
I've noticed a rather odd issues when multiple usenet servers are enabled.  

Right now I have 2 servers
Server A: Priority 1
Server B: Priority 20

The behavior I am seeing is that downloads are much slower and if I go to the connections status page, under Server A, I see connections for Server B and under Server B, I see connections for Server A.  Or at least that is what it looks like from the screens.  Does this seem correct?

Note: If I disable either of the servers all of a sudden download speed picks up and the server connections look correct.

**Screen** Shots

Server A
![Server A](https://user-images.githubusercontent.com/2222472/50690166-5db69c00-0ffa-11e9-9b94-7bacace31d4f.png)

Server B
![Server B](https://user-images.githubusercontent.com/2222472/50690181-6909c780-0ffa-11e9-93c4-7ae6d5badd13.png)

In terms of versions, I have tried the latest release and the latest code in the development branch and both so the same issue.

**Comment by Safihre** [comment]
The first column is the article-identifier. So that it says `astraweb` in your first screenshot, indicates the post was uploaded there.

Also, I would suggest to reduce the number of connections. Unless you have gigabit, 10 connections can get you up to 40MB/s on Frugal for example.

**Comment by ravensorb** [comment]
Still a bit confused -- under Server A, the identifier has the name of server B in it which is what doesn't make sense to me.

If I disable astraweb, then all connections under usenet,farm so an Article ID that ends in ngroups.net which is what I would expect.  Which is what I would expect.  So why are they reversed when both are enabled?

As for connections thanks for the suggestion.

**Comment by Safihre** [comment]
The article-identifier is of no interest, it's just a way to request the article and it could have any name depending on what the uploader uses as software and newsserver.

Articles are first tried on on your Prio=1 server, then on your Prio=20 server.
Once Prio=1 server has finished all articles of your first NZB, it will go and try all the articles of the second NZB in your queue while the Prio=20 server is getting the articles of the first NZB. 
This way downloads can be simultaneous for multiple servers.

**Comment by ravensorb** [comment]
Ok, a bit add though as I only see astraweb articles when I have that server enabled, if I do not , I only see ngroups.net.

So then the question is, why do I get a lot of "hung" downloads when both are enabled.  If I disable either one things work great.  

Note: I did try moving connections down to 10 each and still has the same behavior.

**Comment by Safihre** [comment]
Again: The article identifier **does not** indicate which server it is _downloading_ from, it is the server the uploader **uploaded** it too. After the uploading by the original poster it is synced with all servers over the world, like the one you then download from. Maybe it's good to read how usenet works.

So now the second issue:
What kind of hung downloads do you mean? At what percentage do they get stuck? Do they complete eventually?

**Comment by ravensorb** [comment]
Its more like the download speed goes down to under 100k and a lot of items in the queue don't start downloading for a while (I've come back and seen the queue up to over  100 with no progress some times).

**Comment by Safihre** [comment]
This is most likely because you prio 1 server doesn't have the articles, so it has to request every single article from that server first before moving to your prio 2 server.
Requesting missing articles is slow and indeed not much data is transferred.
You can switch logging to +Debug and then after it's slow for a while, click Show Logging to see what it's been doing. Most likely "Article X is missing from server Y".

**Comment by albino1** [comment]
Even if you didn't have an Astraweb account it would *still* say Astraweb because that's where it came from originally.  It doesn't have anything to do with your servers, think of it more like origin address.

**Comment by ravensorb** [comment]
Yep, I get it :) It was just odd that astraweb items ONLY show up under the usenet.farm and ngroup,net ONLY show up under astraweb when they are both enabled (I have seen this for weeks now) -- so I thought something was not working as expected.
