### ISSUE TITLE
Feature Request: Option to change click action for windows tray Icon

### ISSUE THREAD

**Issue by snifflezak** [sabnzbd/sabnzbd#1210]
I'm proposing to add an option to chance the function performed when clicking the SABnzbd windows tray icon.
I have it visible so I can tell if downloads are in progress but often I click it by accident which has the undesired effect of pausing/resuming.

**Comment by Safihre** [comment]
Can't say I'm a huge fan of this, as I don't want to have options for everything when it's designed behavior.

**Comment by snifflezak** [comment]
Thought that might be the case and I guess less is more.

**Comment by cody1205** [comment]
I agree with snifflezak, I'm always clicking the tray icon to open the UI and before I can stop myself, I've already paused my downloads. I wish there were an option to change what the click behavior did.

**Comment by Safihre** [comment]
I will increase the timeout a bit, to double the Windows-setting of the user.
