### ISSUE TITLE
Feature Request: Colour of SABnzbd tray icon to indicate when post processing is in progress after downloads complete.

### ISSUE THREAD

**Issue by snifflezak** [sabnzbd/sabnzbd#1211]
Whilst after completion there's no data to download, there's still post processing to complete. So the files aren't actually available to the user until later than "completion" indicates.

I'm proposing to either:
A new colour tray icon that indicates downloads are finished but post-processing in progress. Or:

Have the option to change what SABnzbd counts as completed, post-processing finished vs data download complete.

Perhaps this is just a problem on older systems but on my PC post processing can take as long if not longer than the download(on gigabit fibre). Which isn't a solvable issue which is why I raise this feature request.

**Comment by Safihre** [comment]
I like that idea. What color should it be?

**Comment by snifflezak** [comment]
Not sure, I'm not good with colour design, the first colour that springs to mind is purple or turquoise. Logically a shade between the yellow and green icons kind of makes sense, though whether there's a shade between those colours which is clearly identifiable is another matter.

**Comment by Safihre** [comment]
I think this is out of reasonable scope for now and would break the general theme of SABnzbd.
