### ISSUE TITLE
Empty NZB file - When in nzb dl url is &amp;

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#1223]
```
WARNING a few seconds ago Empty NZB file &ampcode=code&ampuser=*** [https://site.url/dl.php?nzb=filenzb&ampdate=date&ampcode=code&ampuser=usr]
```

SabNZBd can not dl from url when there is `&amp;` ??

Inside Rss:

`<link>https://site.url/dl.php?nzb=nzbfile&amp;date=date&amp;code=code&amp;user=usr</link>`

**Comment by Safihre** [comment]
Could you send me the full URL via email so I can really test it?

**Comment by Safihre** [comment]
Ping @scriptzteam
