### ISSUE TITLE
Add synk intergration

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1225]
I know you are working on lgtm, but we might want to also add synk:
https://snyk.io/docs/github/

**Comment by Safihre** [comment]
Check it now to see if it picks up our stuff :)

**Comment by Safihre** [comment]
Seems to only pick up `requirements.txt`, but it doesn't hurt so will let it turned on!
For `py3` branch we rely on  `requirements.txt` instead of bundeling, so might be good.
