### ISSUE TITLE
Feature request: Keep track of failure-stats per server

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1226]
Should be simple enough to keep track of.

Based on: https://www.reddit.com/r/usenet/comments/am8tho/ninja_newsnl_missing_articles_that_are_on_eweka/

**Comment by rjwonder** [comment]
Agree that the statistics should not become false statistics. 

What about the following per server:
- articles searched + percentage
- articles downloaded + percentage
Priority 0 gets searched a lot, priority 2 a lot less. Downloaded % goes down the higher the priority number. At a certain point the downloaded % is so low that it's better to drop the server. Now if the download % of priority 5 is higher than server with priority 4, then maybe it's a signal to switch them (more factors come into play though)

Maybe to limit development time not for the first version, but something additionally interesting is having dated access to the age en size of the articles found / downloaded. Access to the data (e.g. CSV) would be enough to do some simple analysis. Purpose would be to optimize servers and priority of them. Hydra does this pretty well for indexers (but raw data would give more flexibility)

**Comment by Safihre** [comment]
So searched is the percentage of the total download volume performed by Sab?
Or how else does it improve the situation described by @sanderjo?

**Comment by rjwonder** [comment]
Searched is the total number of articles searched for at that specific server. I would not just show the percentages, but also the absolute numbers. Maybe it's not different from what @Sanderjo says, but then I don't fully understand why it's called false statistics. For me a lower priority server equals lower number of searched (only left over searches) and a lower chance that the left over article is available. This low priority server is only there to increase chances of completion. With a priority 6 scoring better than priority 5, then I might need to switch around (or dump the priority 5)

Hopefully all servers together get to something towards 100% available

**Comment by sanderjo** [comment]
While talking about stats:

With all servers set to prio 0, I get these results on a 100MB download:

eunews-v6.blocknews.net=56.7 MB
news.appelboor.com@3=560 B
newsreader3.eweka.nl=17.9 MB
newszilla.xs4all.nl=392 B
newszilla6.xs4all.nl=27.1 MB

So I would say blocknews.net is peformaning the best / fastest. *That* is relevant statistics for me ...

**Comment by sanderjo** [comment]
A waterfall chart with prio's incorporated:

![image](https://user-images.githubusercontent.com/1273502/52183107-e9436880-2804-11e9-85c5-23e8e17a4253.png)

**Comment by thezoggy** [comment]
But this is skewed by which usp the poster used. So if they posted using blocknews.. then their backend will prob be the best (unless you have crap peering to get to their backend)

**Comment by sanderjo** [comment]
> But this is skewed by which usp the poster used. So if they posted using blocknews.. then their backend will prob be the best (unless you have crap peering to get to their backend)

No, not at all.

Proof: above is about my own 100MB test upload ... which I posted via Eweka. And with downloading, Blocknews is fastest.

**Comment by rjwonder** [comment]
For same priority I think Sab selects the first one with an available connection? If article does not exist it will take the next same priority server? Blocknews seems indeed to be performing and have the availability :)

I think the feature request would provide more insight into the user servers across priorities.

BTW, if mortality is reaching a 100% at the University hospitals then we should indeed get rid of them :)

**Comment by rjwonder** [comment]
The graphics look nice, but my preference would be a table with some more data to see what was searched vs actually downloaded

Just want to highlight that i appreciate everyone's thinking in this! Great to see that there is a lot of activity :)

**Comment by Safihre** [comment]
Table sounds like a good idea. The graph is nice, but only if you know how to read it 😃
But for the table wouldn't it be easier for newbies if we listed amount of (K/M/G) bytes that were tried instead of number of articles?
I know articles can differ vastly in size, but since the rest of the statistics are also in bytes it would make sense I think?

**Comment by rjwonder** [comment]
you are right, but is that possible? Sab will need to know the size of an article before requesting it. Is that in the NZB?

I don't think articles would be a show stopper as most starters will not have several servers, priorities and/or interest in stats. That's just my gut feeling though.

**Comment by Safihre** [comment]
@rjwonder That information is indeed required of the NZB, that's also how we calculate the job-size for example 👍

**Comment by rjwonder** [comment]
Great, thanks for clarifying!

**Comment by Safihre** [comment]
![image](https://user-images.githubusercontent.com/5703454/103111823-42af1d80-4651-11eb-81ee-b73213cd8aa5.png)

Full stats per day can be retrieved from the `server_stats` API-call.
