### ISSUE TITLE
Adding 7-zipped NZBs ("Add NZB" dialog and drag-and-drop)

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1227]
Please consider the ability of adding of 7-zipped NZBs (*.7z) to the **"Add NZB" dialog** and **drag-and-drop** features 🥇

**Comment by hl2guide** [comment]
I checked that out and I have 7-zip installed to the default directory: C:\Program Files\7-Zip
The first page of SAB's config does not show a 7-zip missing message.
Drag and drop worked for me this time 💃 
But there's still an issue for doing it this way:
![upload nzb](https://user-images.githubusercontent.com/17044982/52272901-51788280-299c-11e9-91f6-4a468e5324cb.png)
The 7-zip format isn't in the file type filter.

**Comment by Safihre** [comment]
Aaah. Yes, forgot that one.

**Comment by thezoggy** [comment]
side note, we are one revision behind on 7zip,

7-Zip 18.06 (2018-12-30), changes:
```
    The speed for LZMA/LZMA2 compressing was increased by 3-10%,
    and there are minor changes in compression ratio.
    Some bugs were fixed.
    The bug in 7-Zip 18.02-18.05 was fixed: there was memory leak in xz decoder.
    7-Zip 18.02-18.05 used only one CPU thread for bz2 archive creation.
```

**Comment by Safihre** [comment]
Updated 👍

**Comment by hl2guide** [comment]
Using the latest beta, it seems like the tooltip needs some attention 💃 

![tooltip issue](https://user-images.githubusercontent.com/17044982/52661348-f45d6d80-2f55-11e9-957b-12146930f897.png)

**Comment by Safihre** [comment]
Hmm, that text is a translation. Have to see how to fix that.

**Comment by thezoggy** [comment]
the `Formats:` part itself should only be the translatable part. as the formats themselves dont need it. and in the future shouldnt block us from updating the list

**Comment by Safihre** [comment]
Yes we do. The `sabbuild` script automatically pushes/pulls them.
