### ISSUE TITLE
Download not failing

### ISSUE THREAD

**Issue by robertbaker** [sabnzbd/sabnzbd#1228]
![screenshot_20190204-163251](https://user-images.githubusercontent.com/907301/52244517-3a9e3700-289b-11e9-8e7a-608096a33b51.png)

This download is missing the first 12.5gb but it still hasn't failed.
I thought the new fast fail would take care of this?
There needs to be a slow download detection, files like these choke Sab, I'm only getting 2/kbs down. I set my connection speed (1gb).

Why hasn't this failed yet? I see this all the time, Sab will be stuck for days until I delete it myself :( 

Using docker, linuxserver container, 2.3.7

Abort download is on..note I recently forced the download, but it was doing so before even with priority normal. I just wanted to see what it would do, nothing.

**Comment by thezoggy** [comment]
The slow speed is the fact the articles are missing. If you look at the debug log you will see that Sab is asking for the articles from your indexers. The pre check (if enabled) is what is probably what you are seeing. If you don't like it, just disable that feature.

**Comment by robertbaker** [comment]
I'm not using the precheck. So something is not checking for a high number
of missing articles.

I can try turning it on, but it sounds like I don't want to do that.

**Comment by thezoggy** [comment]
Failfast is for first article missing. Precheck is for total missing. Can you share your Sab logs of your recent session

**Comment by Safihre** [comment]
- Fail-fast will only work for jobs that were added after the update to 2.3.7
- Fail-fast will only work if 80% of the first articles are missing, maybe in this case these articles were present
- If not failing-fast, it will use the usual method: 100.2% of the data needs to be available. 
So: if there is 10GB of par2 files, first 10GB of articles need to be missing before it's cancelled. 

While it is possible that something is wrong with the failing mechanism, it's been around for a long time and if it was broken it would probably have been identified earlier.

**Comment by Safihre** [comment]
Closing due to no further feedback.

**Comment by robertbaker** [comment]
I apologize,

who can I send the logs to? I don't want to make them public in case is
identifiable info in them.

**Comment by thezoggy** [comment]
you can post them on pastebin and link to them here (if you use the sab gui, wrech icon -> show logging, those logs are already obfuscate any sensitive info). but if you dont feel comfortable doing that just send the logs to bugs@sabnzbd.org

**Comment by robertbaker** [comment]
I emailed my logs since it's too long for PB
