### ISSUE TITLE
2.3.8b1 -- 'refresh'

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1230]
icon in the top right looks like it will 'refresh' the free space...
looking at the browser network requests I see its refreshing the queue/history.

I see you can click bomb that and cause a ddos to your box... especially if you have a large api response

* might want to add logic to prevent double clicking / being able to hammer it. 
* should we consider only showing the manual refresh if the skin auto-refresh setting is set to disabled?

**Comment by Safihre** [comment]
The button is only there if people have a refresh-rate set equal or higher than 4.
It's also been there since 2.3.0 so I think people understand it 😉 
https://github.com/sabnzbd/sabnzbd/blame/develop/interfaces/Glitter/templates/include_queue.tmpl#L42

**Comment by thezoggy** [comment]
odd, i never recall seeing it until after updating to 2.3.8b1...  hmm but yeah i really had no clue what it does (with empty queue it just looks like a static image to me, as clicking on it provided no user feedback and the tooltip just said refresh)

**Comment by Safihre** [comment]
Well, the tooltip says it right there, refresh ;)
