### ISSUE TITLE
sab 2.3.8b1 -- total (grand_total)

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1232]
question in irc,
> So i'm not sure if this is a bug or not, at some point over the last month or two my total downloaded reset, it's about the time it hit 100TB. Does it roll back to 0 at 100TB or is it because it coincidentally hit 1 year since the count started?

looking, it looks like we store 8 chars for the data...
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/bpsmeter.py#L176

so 99,999,999 MB would be 100TB ?

**Comment by Safihre** [comment]
It seems so, but that line means something different. The loaded data is a tuple and we only use the first 8 values of it.
But it could just be the max of the Python 2 integer: https://stackoverflow.com/questions/7604966/maximum-and-minimum-values-for-ints

**Comment by Safihre** [comment]
Should be solved in Python 3, where it's always a long-type.
