### ISSUE TITLE
ValueError: need more than 1 value to unpack 

### ISSUE THREAD

**Issue by scoobydoo1959** [sabnzbd/sabnzbd#1234]
I am receiving this error on the History tab during post processing. The file stays in my download completed folder unpacked and named. It is not transferred to the Movie directory. This has bee going on for quite awhile > 4 months at least..... I am on windows 7 running Sabnzbd sourcecode  Version: | 2.3.7 [7a8df5e]  with Python 2.7.14. Just reinstalled sabnzbd and python at the beginning of this week.
[Sabnzbd log extract.txt](https://github.com/sabnzbd/sabnzbd/files/2872117/Sabnzbd.log.extract.txt)
[Specific error .txt](https://github.com/sabnzbd/sabnzbd/files/2872118/Specific.error.txt)

**Comment by Safihre** [comment]
This error is not inside sabnzbd, but in your nzbToMedia script.
Have you updated it recently?
