### ISSUE TITLE
Suggestion: make "Sabnzd Config"-wheel a hoverable drop-menu

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1235]
I often use the "Sabnzbd Config" settings via the wheel in the upper right corner.
That is always a two-click approach, for example: click on Sabnzbd Config -> click on Servers

How about making the "Sabnzd Config"-wheel a hoverable drop-menu, so that with one click to the Servers (and other) settings.

Example: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_dropdown_hover

**Comment by sanderjo** [comment]
I still would like to see this.

**Comment by Safihre** [comment]
After consideration I don't think we will be doing this.
