### ISSUE TITLE
py3 failing to launch with --daemon

### ISSUE THREAD

**Issue by Vallimar** [sabnzbd/sabnzbd#1237]
Receive this error:
```
Traceback (most recent call last):
  File "/opt/SABnzbd/SABnzbd.py", line 1687, in <module>
    main()
  File "/opt/SABnzbd/SABnzbd.py", line 1083, in main
    out_log = open(ol_path, 'a+', 0)
ValueError: can't have unbuffered text I/O
```
I was able to work around by doing this:
```diff
--- a/SABnzbd.py
+++ b/SABnzbd.py
@@ -1080,7 +1080,7 @@ def main():
             x = sys.stderr.fileno
             x = sys.stdout.fileno
             ol_path = os.path.join(logdir, DEF_LOG_ERRFILE)
-            out_log = open(ol_path, 'a+', 0)
+            out_log = open(ol_path, 'a+')
             sys.stderr.flush()
             sys.stdout.flush()
             os.dup2(out_log.fileno(), sys.stderr.fileno())
```

**Comment by thezoggy** [comment]
https://docs.python.org/3/library/functions.html#open
> buffering is an optional integer used to set the buffering policy. Pass 0 to switch buffering off (only allowed in binary mode), 1 to select line buffering (only usable in text mode), and an integer > 1 to indicate the size in bytes of a fixed-size chunk buffer.

I agree the buffering option should be dropped since were not using the binary mode (`b`)

**Comment by Safihre** [comment]
I don't understand the daemon-code in general. Why is this part there but the `deamonize()` function only much later?
I'd expected that to be in 1 function..

**Comment by thezoggy** [comment]
the `-d` is used for those that want to run sab as a service on windows... 
daemonize is for non windows..

on windows you can run sab without the console or with... for non windows its all the same

**Comment by Safihre** [comment]
I know that, but I just don't understand why the code works this way..

**Comment by Safihre** [comment]
Fixed.
