### ISSUE TITLE
Query: Do WinRAR libraries in Sabnzbd need to be updated for security reasons?

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1238]
As per: https://www.ghacks.net/2019/02/21/winrar-has-a-critical-security-bug-here-is-the-fix/
Do WinRAR libraries in Sabnzbd need to be updated for **security reasons**?

It seems to me that the latest version of WinRAR fixes the issue.

**Comment by sanderjo** [comment]
SABnzbd does not use WinRAR (which is a GUI program). 
SABnzbd uses the CLI unrar from https://www.rarlab.com/

**Comment by hl2guide** [comment]
Ok, does CLI unrar need to be upgraded with the fix?

**Comment by sanderjo** [comment]
> Ok, does CLI unrar need to be upgraded with the fix?

Which fix ... ?

**Comment by hl2guide** [comment]
The fix is at: https://www.rarlab.com/rar_add.htm
_unrar 5.7.2 listed as "UnRAR.dll"_

**Comment by sanderjo** [comment]
> The fix is at: https://www.rarlab.com/rar_add.htm
> _unrar 5.7.2 listed as "UnRAR.dll"_

SABnzbd neither uses unrar.dll

SABnzbd uses unrar.exe. See C:\Program Files\SABnzbd\win\unrar\
The SAB maintainer will update unrar.exe if/when needed.

If you want to do that yourself, you can: put it into C:\Program Files\SABnzbd\win\unrar\ 
Or specify in sabnzbd.ini


HTH

**Comment by jeffgeorge** [comment]
Couple Notes / Clarifications:
- The [vulnerability](https://research.checkpoint.com/extracting-code-execution-from-winrar/) is with ACE support within WinRAR, so technically it's in `UnACEv2.dll`, not `UnRAR.dll`
- The vulnerability in question does appear to extend to the CLI version of WinRAR, as the fuzzing done by Checkpoint was done vs the CLI version
- It's unclear as to if the vulnerability extends to the *freeware* version of UnRAR.exe
- RARLabs have *not* released a "final" version of UnRAR binaries that mitigates this vulnerability. They have betas, but 5.70 final has not shipped yet. They've got Beta 2 and that's it.

Bonus Question:
- Do we even run ACE files through the RAR binary, or do we use 7zip to handle that format? If so, this is a complete non-issue.

Path Forward:
- Assuming we *do* run ACE files through the RAR binary, we will follow normal procedure and update the bundled Windows UnRAR binary once a stable release of UnRAR 5.70 ships
- We may ship this as a patch release that *just* updates the UnRAR binary, or may include it with the next point release, depends on how the timelines end up aligning with win RARLabs ships their stable build
- As mentioned above, if you are a Windows user who is concerned about this, you can fix it now by updating the `UnRAR.exe` directly

**Comment by Safihre** [comment]
Thanks @jeffgeorge, I agree. Since I already made a 2.3.8 Beta, I think we can just release it when the final 5.70 is released.

How do you even make ACE files? 😅

**Comment by thezoggy** [comment]
New 7zip - https://www.ghacks.net/2019/02/22/7-zip-19-00-released/

**Comment by thezoggy** [comment]
@jeffgeorge we never have supported .ace files so there is no real harm with regards to sab as they do not get processed.
and about what compression formats we do view as 'valid' which we would try to work with:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/constants.py#L99
then there is also the split format but that is just joining files (.001+)

**Comment by jeffgeorge** [comment]
Ok, cool. Since we explicitly don't handle ACE files this is a non-issue. Thanks for confirming that.

We'll definitely keep our eyes open for when RARLabs releases 5.70, though. But since we're not _directly_ impacted, upgrading will likely not warrant an urgent patch release, it'll just go into whatever our next standard release is.

**Comment by hl2guide** [comment]
Thanks for confirming all this 👍 Allays some concerns.

**Comment by thezoggy** [comment]
@Safihre side note, python 2.7.16 is incoming soon.. rc1 was last week. latest changes:
https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.16rc1.rst

**Comment by Safihre** [comment]
5.70 was released, I updated the binaries.

**Comment by chesterm8** [comment]
@jeffgeorge @thezoggy Please note that this does affect sabnzbd. WinRAR introspects a file to determine what type it is, it does not rely on the file extension. So a malicious .ace file could be renamed to .rar, which would mean sabnzbd would pass it to WinRAR, which would then recognise it as an ACR file and trigger the vulnerability. As such I would suggest an urgent patch is warranted.

See https://www.grc.com/sn/sn-703.txt for reference to file type introspection behaviour of WinRAR

**Comment by jeffgeorge** [comment]
Interesting. However, no patch is necessary as we already shipped RAR 5.70 as part of [SABnzbd 2.3.8](https://github.com/sabnzbd/sabnzbd/releases/tag/2.3.8) on 18 MAR 2019. So concerned users should either upgrade SABnzbd or upgrade WinRAR directly as described above.

**Comment by thezoggy** [comment]
Winrar bugs is one thing. We use unrar. At the end if the day, just up to the latest version of Sab for peace of mind and security.
