### ISSUE TITLE
sab -- unicode characters in unpack/repair

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1239]
unicode colon (U+003A) looks to show up as '3A' in unpack/repair?:
![sab](http://zoggy.net/firefox_2019-02-23_18-27-51.png)

sadly I can't provide any logs on this as sab logging system broke on the 18th for me..  restarted sab to fix.

why I think its a colon is because of the original name.. but release name has it replaced with a space. 

from mediainfo:
```
Complete name                            : Gu.Dan.You.Can.Lan.De.Shen.:Gui.Guai.Guardian.The.Lonely.and.Great.God.S01E01.1080p.NF.WEB-DL.DDP2.0.x264-Ao.mkv
```

**Comment by Safihre** [comment]
That's on purpose:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L307

Not sure if that's still needed with Multipar, let me check.

**Comment by Safihre** [comment]
Have to love Multipar for being so good with all the Windows-hacks ❤️ 
```
checking filename...
file 0: sanitized to "Gu.Dan.You.Can.Lan.De.Shen._Gui.Guai.Guardian.The.Lonely.and.Great.God.S01E06.1080p.NF.WEB-DL.DDP2.0.x264-Ao.part14.rar"
file 1: sanitized to "Gu.Dan.You.Can.Lan.De.Shen._Gui.Guai.Guardian.The.Lonely.and.Great.God.S01E06.1080p.NF.WEB-DL.DDP2.0.x264-Ao.part28.rar"
```

**Comment by Safihre** [comment]
Changed it in Python 3 branch.
It still won't contain the `:` since that's invalid on Windows, but at least it will be handled without the need for `3A`.

**Comment by thezoggy** [comment]
the replace_illegal would take care of the `:`  but just was noting the inconsistency in the download report :) 
but thanks for the quick fix
