### ISSUE TITLE
Timezone aware scheduling

### ISSUE THREAD

**Issue by DanielO** [sabnzbd/sabnzbd#1243]
My NZB server is in another country and has a discounted plan for 12 hour a day usage so I schedule SAB to enable/disable as necessary, however day light savings is a PITA.

It would be desirable to schedule something in another timezone so I can set and forget.

**Comment by Safihre** [comment]
So timezone aware of which timezone? The server or the client that's doing the configuring?

**Comment by DanielO** [comment]
I was thinking of just a list of time zones (the default being 'local time' ie the SAB server time), although I am not sure how easy it would be for the server to generate such a list and it probably complicates porting to Windows I imagine..

One work around would be to set the TZ env var in the startup script for SAB I suppose.. Not sure if that will cause confusion though :)

**Comment by Safihre** [comment]
This is not something we can support I think, because we want to keep things easy.
Maybe we could show the current server time in the Scheduler page so it's always clear what the server is using?

**Comment by DanielO** [comment]
OK fair enough. I know what the SAB server time is (it's local time for me) - the main issue was day light savings time changes.

I'll see if setting the time zone only for SAB works.
