### ISSUE TITLE
[py3]: block stone-old python 3.4 and lower?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1245]
On my Ubuntu 14.04, with python 3.4.3, a Test Server (with SSL set, in the Wizard), results in

` 'SSLSocket' object has no attribute 'version'`

So, probably the python is too old? If so, let's block it at startup.

So block any 3.4?

Ah: https://docs.python.org/3/library/ssl.html tells it:

> SSLSocket.version()
> Return the actual SSL protocol version negotiated by the connection as a string, or None is no secure connection is established. As of this writing, possible return values include "SSLv2", "SSLv3", "TLSv1", "TLSv1.1" and "TLSv1.2". Recent OpenSSL versions may define more return values.
> 
> New in **version 3.5.**

So, I would say: block if < 3.5

![image](https://user-images.githubusercontent.com/1273502/53426637-9fa30380-39e7-11e9-99a4-0069a7ba8723.png)

FWIW

`2019-02-26 16:56:57,084::INFO::[happyeyeballs:149] Quickest IP address for newszilla.xs4all.nl (port 563, ssl 1, preferipv6 True) is None`
... None ...

**Comment by Safihre** [comment]
Agreed, let's block it.

**Comment by sanderjo** [comment]
... it works!
````
sander@haring:~/git/py3-sab$ ./SABnzbd.py -s 0.0.0.0:8080 -f blabla.ini -b0
Sorry, requires Python 3.5 or above
You can read more at: https://sabnzbd.org/python3
sander@haring:~/git/py3-sab$
```
