### ISSUE TITLE
"Allow load-balancing" being ignored. No load-balancing being done.

### ISSUE THREAD

**Issue by Napsterbater** [sabnzbd/sabnzbd#1249]
Windows Server 2016 (Win 10 Server)
Happens on 2.3.7 and 2.3.8Beta1 (and no idea how far back)
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] [cp1252]
OpenSSL 1.0.2o 27 Mar 2018

I have 2 Different defined servers, 1 with a FQDN that returns only 2 different IPv6 addresses, the other with a FQDN that returns only 2 different IPv4 addresses.

Yet no matter the setting of "Server load-balancing" only 1 IP address is used at a time for all connections to that server/FQDN

"Allow load-balancing" should roughly split the connections between the 2 (or how ever many) addresses for each given 5+/- (in this case) connections per IP returned for the FQDN.

**Comment by Safihre** [comment]
I think the name might be misleading, it's not load balancing in that sense.
It just means that it won't pick the first IP but selects one randomly when making the first connection or find the fastest one.
It's actually very much intentional to use just 1 IP because using different IPs simultaneously gives account problems. Because the provider servers have to communicate with each other how many connections you used. If they are a bit behind (happens all the time) it will throw "Too many connections".

**Comment by Safihre** [comment]
I see the behavior is not correctly described in the wiki.. I will update that. 
https://sabnzbd.org/wiki/configuration/2.3/switches

**Comment by Napsterbater** [comment]
Then there really seems to be little to no point to this setting at all, or at least it should not be called "load-balancing", because as far as Sabnzbd is concerned its not load-balancing it just controlling server selection.

So maybe the option should be called "Server Selection" then.
With the options
"Use first IP provided by DNS"
"Use random IP provided by DNS"
"Use random IP provided by DNS, prefer IPv6"


Though I like the idea of load-balancing, and I remember specifically back in the .0.8ish days sabnzbd would use all addresses it got back with a FQDN, both IPv6 and IPv4 simultaneously for a single server. When did that change?

My though on the options would be.
Prevent load-balancing (The default) would seem to cover that concern.
Allow load-balancing (an option for providers where it can/will work) should do just what it describes, load balance across all IPs received from FQDN query.

**Comment by Safihre** [comment]
This was changed in 1.2.0 I see, the origin is #733.
But maybe it wasn't implemented correctly. Only when Disable Load balancing is chosen it should stick to 1 IP. Or what do you think at @sanderjo? Should Happy Eyeballs also be done for every seperate connection?

**Comment by sanderjo** [comment]
I agree with @Napsterbater that the 3rd option "Allow load-balancing with optimization for IPv6" is not the correct wording. 
As the SAB-Happy-Eyeballs-implementer, I would call it "Automatically select quickest IP address, with optimization for IPv6" or "Quickest IP address, with optimization for IPv6"

I don't know SAB's behaviour for the other two options. I vaguely remember Option 2 was "pick an IP address" ... meaning SAB cannot guarantee it's random.

Furthermore I cannot imagine a case where "load balancing" is good or relevant for SAB or a newsserver.  On the other hand: it can cause bad things, so I would avoid it.

**Comment by Napsterbater** [comment]
"Furthermore I cannot imagine a case where "load balancing" is good or relevant for SAB or a newsserver. On the other hand: it can cause bad things, so I would avoid it."

Using multiple IP addresses can help with multi WAN load sharing/balancing and help with performance when the connection goes across a heavily loaded LAGG group (which is how l found Sab was no longer doing this as it had).

If that is not going to be done then again this option should not be called load balancing anymore. And again it used to work fine I never had a problem with that option on my provider though a warning or disclaimer can simply be put into the wiki that it should not be used if your provider does have an issue with it.

**Comment by Safihre** [comment]
Changed the labels.
Will have to update the Wiki in the future.
