### ISSUE TITLE
Feature Request: open multiple nzb at once

### ISSUE THREAD

**Issue by HoraK-FDF** [sabnzbd/sabnzbd#125]
Hi,

i have tryed to open multible nzb files at ones with the webinterface but it only let me open one at once, can this be improved so that it is possible to open multible nzbs at one? It is possible to add multible nzbs with nzbdd but the gui somtimes crashes.

OS: Win XP Prof SP3 32bit
SABnzbd-0.7.16-win32-setup.exe

**Comment by Safihre** [comment]
This is now possible in the new skin Glitter for sabnzbd 0.8. You can drag and drop any number of NZB  files on the interface and they will be added simultaneously. 
(yes I know this issue is old, but can be closed now!)
