### ISSUE TITLE
NZB Completion in API?

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#1251]
Can we have NZB completion of message ids on usenet server(s) in API too?

I mean when it checks completion it shows up as Completion: 100% or Compleiton: 95% etc etc ... thx!

**Comment by Safihre** [comment]
Isn't that just `100-mbmissing/mb` ? Those are already in the API.

**Comment by scriptzteam** [comment]
thx but in which api mode is that?

i do use sabnzbd version: 2.3.8Beta1

**Comment by Safihre** [comment]
`queue` I think it's been there since 2.2.0, according to the API wiki I wrote long ago 😅

**Comment by thezoggy** [comment]
I believe they want the precheck data for whatever nzb the provide. Not the 100/1000 mb test.

**Comment by Safihre** [comment]
I know, that's in the `queue` API-call.

**Comment by scriptzteam** [comment]
Hmm `http://IP:PORT/sabnzbd/api?mode=queue&start=&limit=&search=&apikey=KEY` returns only error: not implemented

**Comment by Safihre** [comment]
Try adding `&output=json`.

**Comment by wtfnzb** [comment]
Thx you now works :)

But anyway would be cool if we can have something like **cli nzb check for completion** so i can write some pp scripts xD

**Comment by Safihre** [comment]
So you would use it in a PP-script? But what are you trying to do?

**Comment by scriptzteam** [comment]
like wtfnzb told, that can be useful as cli tool when for example we have tons of older nzbs in folders, we somehow need to check the failed/missing articles via cli, but seems impossible for now.

so we can iterate over all the dirs, pick up a nzb, check the articles available/missing...

if not possible than thx anyway

**Comment by fetzerms** [comment]
Sorry for commenting on a closed issue. I think some feedback without downloading a nzb file whether the nzb file can be downloaded completely and/or be repaired would be great. So one might know whether the nzb file that is at hand should be or not.
