### ISSUE TITLE
Retain Speed Throttle Setting Between Restarts

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1254]
Please consider adding a **check-box option** for _whether or not to retain the speed throttle setting between server restarts_.

**Comment by Safihre** [comment]
In Config General, the there specified throttle percentage is always applied at startup. I know that's not exactly what you would like, but can fit the need maybe?

**Comment by hl2guide** [comment]
**Thanks for making such useful software.**

Hmm not quite, please consider it for a future version. I'm really looking for a "Remember Speed from Previous Session" kind of feature.

That way it remembers the speed regardless of throttled or not.
