### ISSUE TITLE
sab -- config > general > Maximum line speed

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1257]
for `Maximum line speed` takes in a value and the drop down to the right denotes the suffix.
so for example we show `MB/s`. Really that should be `Mb/s` or `Mbps` since sab does stuff in Megabites not MegaBytes.

also, the wiki page is a bit out of date since it still talks about when the user put the suffix in the box with the value:
https://sabnzbd.org/wiki/configuration/2.3/general#toc2

**Comment by sanderjo** [comment]
> Really that should be `Mb/s` or `Mbps` since sab does stuff in Megabites not MegaBytes.

No. SAB works in MB/s. Megabytes.

Not megabits.

Your ISP works in megabits.

**Comment by thezoggy** [comment]
looking back, looks like in 1.0.3~ timeframe we went away from mbps to MB..
