### ISSUE TITLE
Forced download with missing articles causes bad behavior

### ISSUE THREAD

**Issue by rabisuz** [sabnzbd/sabnzbd#126]
When forcing a download that is not available on the main server, the next item that is available on that server and not individually paused is downloaded, regardless of the global state. For example, suppose we have three downloads, respectively called *A*, *B* and *C*. *A* is a forced download, *B* and *C* are not. *B* is paused, although it's presence does not matter for the bug to occur. Now we have two download servers. The first server contains *B* and *C* and the second server contains all articles required for the three downloads. Moreover, we enable the special setting 'start_paused' so that it starts with the global paused state, and restart SABnzbd. What we expect in this scenario is that item *A* will be downloaded, since it's priority is 'Force'. What happens however, is that *C* is downloaded as well, despite the global paused state.

This behavior is observed with SABnzbd version 0.7.16.

**Comment by dbond007** [comment]
Will this ever be fixed? Just moved from 0.7?? (been working fine so not updated) to 2.3.2 and the problem still exists.

**Comment by Safihre** [comment]
It's a bit better now, but still not fixed. It's just faster not to do a very thorough check.
