### ISSUE TITLE
Test Download => "https://sabnzbd.org/tests/test_download_undefined.nzb"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1263]
(This happens on py3 as that is what I use. But it might be unrelated to the sab/python version)

Now and then, when I click on Test Download, the result is

```
Retry 
https://sabnzbd.org/tests/test_download_undefined.nzb	
URL Fetching failed; File not on server
```

Weird. When I click again on Test Download, it works.

![image](https://user-images.githubusercontent.com/1273502/55077448-12aba280-5098-11e9-8750-a05604bbe602.png)

So instead of
https://sabnzbd.org/tests/test_download_1000MB.nzb
or
https://sabnzbd.org/tests/test_download_100MB.nzb

the url is https://sabnzbd.org/tests/test_download_undefined.nzb

Some calculation going wrong?

```
841-    // Download a test-NZB
842-    self.testDownload = function(data, event) {
843-        var nzbSize = $(event.target).data('size')
844-        // Build request
845-        var theCall = {
846-            mode: "addurl",
847:            name: "https://sabnzbd.org/tests/test_download_" + nzbSize + ".nzb",
848-            priority: self.queue.priorityName["Force"]
849-        }
```

so that `var nzbSize = $(event.target).data('size')` can go wrong ... ?

**Comment by thezoggy** [comment]
deff should default nzbsize to something if the jsfails.. or handle aborting the call if its missing..

**Comment by Safihre** [comment]
It's due to clicking on the icon instead of the text, something that should be handled.
