### ISSUE TITLE
Python Shebang in Fedora 30

### ISSUE THREAD

**Issue by recteurlp** [sabnzbd/sabnzbd#1265]
Hello,

Trying to build the RPM failed with shebang errors :

```
*** ERROR: ambiguous python shebang in /usr/share/SABnzbd/SABnzbd.py: #!/usr/bin/python -OO. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/SABnzbd/tools/msgfmt.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/SABnzbd/tools/make_mo.py: #!/usr/bin/python -OO. Change it to python3 (or python2) explicitly.
```

I will use sed to enforce python2 in the spec file.

You should enforce python2 as well until you are python 3 compatible.

**Comment by sanderjo** [comment]
Would `#!/usr/bin/python2` work for all other systems, like old Linux distro's and NAS devices and MacOS?

**Comment by Safihre** [comment]
This will be fixed for Python 3 version (see `py3 brancg). We had debates about this before and it's been working for many years, so like to keep it this way for the Python 2 version!
