### ISSUE TITLE
UNPACK folder not deleted after repair

### ISSUE THREAD

**Issue by d0m84** [sabnzbd/sabnzbd#1267]
I'm using sabnzbd version 2.3.8
Since I'm affected by #1258, I have a lot of jobs which fail or have missing articles.

Some of those are successfully repaired and unpacked after that. Since I have enabled the "Direct Unpack" option, there already is a unpack folder which doesn't get deleted after the initial try failed. It stays in the unpacked and final directory after the repair/unpack operation.

**Comment by Safihre** [comment]
You should inspect your (Debug) logs, since SABnzbd will try to remove the folder but if it can't because the system is locking it, it will skip it and not keep trying. 
Sounds like something on your device is keeping the folder locked. What kind of system is it? Windows?

**Comment by d0m84** [comment]
It's a Linux system and I guess the bug is pretty new. I switched to 2.3.8 today and experienced it the first time today as well. Before the delete worked.

**Comment by Safihre** [comment]
Please inspect the logs. The code didn't change in 2.3.8 that does the cleanup.
