### ISSUE TITLE
upload of big NZB takes a lot of time

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1268]
The upload of a big NZB (NZB 10MB, pointing to a 37GB download) takes a lot of time: More than 2 minutes (measured on localhost, so no network delay). 

My guess is that SAB is already processing the NZB (writing the 158 subject file names with 106.000 articles into the queue?), which takes time.

Would it be feasible that SAB just accepts the NZB, and does the processing later on? That would make interfacing quicker.

![image](https://user-images.githubusercontent.com/1273502/55716236-c39a3180-59f6-11e9-8ac9-fd3a11637b97.png)

```
$ time curl http://localhost:8080/sabnzbd/api -F apikey=blabla -F mode=addfile -F output=xml -F "name=@/root/blabla---37GB.nzb" 

<?xml version="1.0" encoding="UTF-8" ?>
<result><status>True</status>
<nzo_ids><item>SABnzbd_nzo_sZGc1K</item>
</nzo_ids>
</result>


real	2m14.708s
user	0m0.070s
sys	0m0.050s
```

**Comment by Safihre** [comment]
We can't, because if there's a problem we need to report this to the submitting system.
For example Sonarr needs to know if the adding failed because the NZB was broken/empty/etc.

**Comment by sanderjo** [comment]
OK, clear.

Update: 

The same NZB only takes 5 -10 seconds on a Core i5 laptop ...
So the low-spec CPU of the Synology is the real limit (not SAB).

**Comment by thezoggy** [comment]
how many parts / files does that nzb have?
