### ISSUE TITLE
Sab downloading everything twice. 

### ISSUE THREAD

**Issue by CBacchus** [sabnzbd/sabnzbd#1277]
Everything that is send to sabnzbd is picked up twice and downloaded twice. I've been using sab for a couple years now without any issue. This started happening a couple weeks ago I believe. I've attached a gif of the unwanted behavior with the test file as an example. Let me know if any logs are needed. 

![nqnUatu16n](https://user-images.githubusercontent.com/1498100/56837506-7956e400-682f-11e9-90e6-331ea0f537e5.gif)

**Comment by Safihre** [comment]
Seems you have set up your Watched folder as your NZB Back-up directory.
Could also explain why you have so many Orphaned jobs.

**Comment by CBacchus** [comment]
> Seems you have set up your Watched folder as your NZB Back-up directory.
> Could also explain why you have so many Orphaned jobs.

Orhpaned jobs are due to this issue. They are all duplicate files from things that have been downloaded 2 by sab.

What do you mean my watched folder setup as my backup directory?

**Comment by Safihre** [comment]
> My install is setup as a docker on unraid and I have not changed anything since the beginning. Currently my watched folder is set to /config which looks to be where the .nzb goes when I request one. That folder is the appdata for the docker which also contains the admin, and logs folders as well as the sab.ini and sab.ini.bak

That sounds bad. Your Watched folder should be a separate folder from all the other stuff.
Go into Config > Folders  and enable Advanced settings. Then check what the paths to your Watched folder are and the folder for NZB-Backup (at the bottom).

**Comment by CBacchus** [comment]
> That sounds bad. Your Watched folder should be a separate folder from all the other stuff.
> Go into Config > Folders and enable Advanced settings. Then check what the paths to your Watched folder are and the folder for NZB-Backup (at the bottom).

That path was set to /config. I went and made a folder named backup and set it to that. Downloads no longer duplicate. SO thank you for fixing that. I do notice now that the .nzb's are stored in the backup folder I created. Do those delete after some time or will I manually have to empty that? Also, why would this have JUST started happening? I haven't changed any settings in years.

**Comment by Safihre** [comment]
> Do those delete after some time or will I manually have to empty that?

No, the backups can be disabled by just leaving the NZB-Backup directory empty.

> I haven't changed any settings in years.

Maybe the NZB-Backup wasn't filled before? Or maybe the docker settings changed?
