### ISSUE TITLE
[py3] possibly wrong b'...' usages

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1279]
Triggered by https://github.com/sabnzbd/sabnzbd/pull/1278 ... these are possible other violations:

Brute grep find:
```
sander@witte:~/git/sj-sab-1mei2019$ grep -rn "b'" * | grep "if " | grep "\.py" 
sabnzbd/decoder.py:150:                    if nzo.precheck and data_to_check and data_to_check[0].startswith(b'223 '):
sabnzbd/nzbstuff.py:544:        if nzb and '<nzb' in nzb:
sabnzbd/urlgrabber.py:166:                            if not filename.endswith('.nzb'):
sabnzbd/urlgrabber.py:238:                if b'<nzb' in data and sabnzbd.filesystem.get_ext(filename) != '.nzb':
sabnzbd/newswrapper.py:407:        if chunk[-5:] == b'\r\n.\r\n':
sabnzbd/newswrapper.py:413:            if combine_chunk[-5:] == b'\r\n.\r\n':
sabnzbd/postproc.py:839:        if os.path.splitext(file_)[1].lower() != '.nzb':
SABnzbd.py:832:        elif opt in ('-b', '--browser'):
```

After inspection:

```
sabnzbd/decoder.py:150:                    if nzo.precheck and data_to_check and data_to_check[0].startswith(b'223 '):
sabnzbd/urlgrabber.py:238:                if b'<nzb' in data and sabnzbd.filesystem.get_ext(filename) != '.nzb':
sabnzbd/newswrapper.py:407:        if chunk[-5:] == b'\r\n.\r\n':
sabnzbd/newswrapper.py:413:            if combine_chunk[-5:] == b'\r\n.\r\n':
```

So ... all "b" to be removed?

**Comment by Safihre** [comment]
Those are very much on purpose, since there we work with the raw socket data and it's in bytes so it's faster to directly compare the bytes in those statements :)
But thanks for checking! 
Should also check for `b"`, maybe there's some wrong ones there?

**Comment by sanderjo** [comment]
These? 1 and 2 look OK, 3 and 4 not sure

sabnzbd/dirscanner.py:235:        if check_bytes == b"\x1f\x8b":
sabnzbd/dirscanner.py:239:        elif check_bytes == b"BZ":
tools/msgfmt.py:59:        if id.count(b"%s") == str.count(b"%s"):
tools/msgfmt.py:60:            if nonewlines and id and (b"\r" in str or b"\n" in str) and RE_HTML.search(str):

**Comment by Safihre** [comment]
It seems those are all good 👍
