### ISSUE TITLE
Sab deletes unexpected files when "Ignore Samples" is activated

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1284]
I'll refer to this previous issue:

https://github.com/sabnzbd/sabnzbd/issues/1063

I suggest adding a check to the "Ignore Samples" option, which would be something like this:

Identify proof or sample files as target for deletion using the existing regex.
If identified target files are the only files in the job, extracted or otherwise, skip deletion.
Else proceed with deletion.

Samples or proof files are supposed to always appear besides other files, if they are on their own, there's a VERY good chance it's a false positive.

**Comment by Safihre** [comment]
I see your point, so what do we do in the case of #1063 where we have `proof.mkv` and `proof.par2`?
Something with file size?
What would be a good way to limit this?

**Comment by thezoggy** [comment]
We shouldn't use name or size but instead the video length. As there are to many false positives that can happen due to bad naming/codec/type of releases.

**Comment by Cpuroast** [comment]
I wouldn't even bother with size or video length, if proof.mkv is all there is in the job, don't erase.
No point in checking the contents of it, when identified sample/proof files are the only items in the job, it's obviously not desirable to proceed with the removal.

**Comment by Safihre** [comment]
@thezoggy @Cpuroast So, how about implementing that plan: only delete if it doesn't result in deleting _all_ files?

**Comment by thezoggy** [comment]
probably a noteable safeguard. `if num_of_sample = num_of_files || num_of_files =1 : skip deleting`

**Comment by jcfp** [comment]
In addition to sanity checking the number of files, one could also limit the sample file size to some percentage (say 5-10%) of the job total. After all, the very concept of a sample is that it comes alongside something way bigger.
If either limit were to be exceeded, don't delete anything. That would also catch cases like #1063.
