### ISSUE TITLE
python2-yenc has been removed from the repos for Fedora

### ISSUE THREAD

**Issue by Rumbles** [sabnzbd/sabnzbd#1285]
Hi,

I'm not sure this is the right place to raise, this apologies if it's not. I just upgraded my machine from Fedora 29 to 30 and I was being blocked as there is no available package that can provide this dependency.

It looks like [they have removed it](https://bugzilla.redhat.com/show_bug.cgi?id=1627158) from the repos.

I was unable to update with this broken dependacy, I had a choice of either removing the package with dnf, which in turn removes SABnzbd or I could do this:

    rpm -e --nodeps python2-yenc

This removed the package without removing SAB, but I suspect when the next update comes through, if this is still a dependency, it will not install.

I confirmed the functionality worked with:

    python -c "import sabyenc ; print sabyenc.__version__ "

My install comes from nuxref:

    Release      : 1.fc29.nuxref
    Architecture : noarch
    Size         : 8.9 M
    Source       : sabnzbd-2.3.8-1.fc29.nuxref.src.rpm

I have it installed via pip anyway, so this really isn't a dnf dependency any more:

    pip install sabyenc --upgrade

**Comment by sanderjo** [comment]
Ouch: https://bugzilla.redhat.com/show_bug.cgi?id=1627158#c14 ... and it's gone 

This place is about the source code of SABnzbd and indeed **not** the right place to report it; the repo is a Fedora/Redhat package/packager thing. 

Anyway ... maybe you are interested in running the python3 version of SABnzbd? Because python3 is the way forward (as mentioned somewhere in that fedora/redhat thread). 

So ... Are you?

**Comment by Rumbles** [comment]
Yes I am interested in running it in python3, but I am also interested in being able to install the latest version from a repo, because I am lazy :)

**Comment by sanderjo** [comment]
> Yes I am interested in running it in python3, 

Nice. Do have "git" on your system?

> but I am also interested in being able to install the latest version from a repo, because I am lazy :)

I understand (I am lazy too), but that is a Fedora (politics?) thing. You found a workaround via pip, didn't you

**Comment by Rumbles** [comment]
Yes I have git, I can install from source. I looked at #933 do you produce binaries for linux? I see a link to a Windows binary... am I looking in the wrong place?

I have emailed the person who maintains the repo to see what they suggest in terms of fixing the issue

**Comment by jeffgeorge** [comment]
> I am also interested in being able to install the latest version from a repo, because I am lazy :)

Well that won't be happening out of the official Fedora repos until the Python 3 version of SABnzbd is finished, as last fall the Fedora Project [killed our long-standing request for inclusion](https://bugzilla.redhat.com/show_bug.cgi?id=519652#c36) over the Python 2 requirement.

Which leaves you with a few options:
- Find a third party repo with python 2 support / modules / etc (The [wiki mentions nuxref](https://sabnzbd.org/wiki/installation/install-fedora-centos-rhel) as an option, but I don't have personal experience there, or know if it's still maintained)
- Run from a [Docker Container](https://hub.docker.com/r/sabnzbd/sabnzbd)
- Sort out how to run it experimentally with Python 3 (bleeding edge, minimal docs at the moment)

**Comment by Rumbles** [comment]
Thanks for the tips, I was using nuxref to get sabnzbd, but the pyenc dep wasn't in nuxref, I have contacted the maintainer and linked him to this issue.

**Comment by sanderjo** [comment]
> Yes I have git, I can install from source. 

OK, good. See https://sabnzbd.org/wiki/extra/python3.html for instruction

> I looked at #933 do you produce binaries for linux? I see a link to a Windows binary... am I looking in the wrong place?

Binaries for Linux? No. Run from source; it's a python program (with a few compiled things (sabyenc)).

**Comment by thezoggy** [comment]
the package distro can just include sabyenc with it? (and in 3.x we should just include it natively like we do other dependencies?)

**Comment by Safihre** [comment]
We can't, due to all the weird Linux flavors there are no good binaries possible. We already have `manylinux1` packages available via pip, can't do more than that.

**Comment by sanderjo** [comment]
Actually, there _is_ a binary solution for all those weird Linux flavors ... it's called ... **docker**: "Enterprise Application Container Platform"

... and **snap**: "universal Linux packages"  
... and **flatpak**: "the future of application distribution"

SABnzbd with docker seems to work great for NAS users. Because even weirder than Linux distro's are NAS distro's with all their different hardware/CPU's even within one vendor (Hello Synology!)

**Comment by sanderjo** [comment]
Anyway ... shall we close this thread ... as the report does not belong here, but on Fedora?

**Comment by Rumbles** [comment]
Yes, sorry, should have closed it yesterday
