### ISSUE TITLE
[Feature request] - Backup and restore

### ISSUE THREAD

**Issue by modem7** [sabnzbd/sabnzbd#1287]
The ability to backup and restore sab configs, queues etc via a click of a button, plus scheduled (zip/tar) backups would be exceptionally useful.

Currently we need to backup the entire directories, and restore them in specific places, this makes it difficult when moving between setups or with new installations of a server etc.

**Comment by modem7** [comment]
Bumping to stop this feature request being closed

**Comment by pinn73** [comment]
Agreed. This would be very useful

**Comment by Safihre** [comment]
Discussing with @sanderjo we wondered if for the sake of security, should we really allow this always? Or maybe limit the ability to download the config to only localhost or when username and password are active?

**Comment by modem7** [comment]
As the web password is in plain text in the config file as is, security is a bit of a grey area imo until that gets resolved.

But, for the sake of ease of use, I'd recommend following what sonarr/radarr do, which is to backup at x time during the week locally, with an option to create a manual on-demand backup.

But yes, I would say that the app should be locked down for the backups (imo as standard (as is the case with *arr apps)) with a u+p. There are plenty of plugins that can use the API to manage the app outside of the webui as is.

**Comment by sanderjo** [comment]
What are we talking about?
1. backup sabnzbd.ini automatically & locally, like sabnzbd-2020-09-24.ini, or
2. export sabnzbd config via webgui, and import it on another SAB instance

**Comment by modem7** [comment]
@sanderjo option 2 in this is what I'm envisioning.

Basically a disaster recovery option. So stats + config if possible.

**Comment by Safihre** [comment]
> As the web password is in plain text in the config file as is, security is a bit of a grey area imo until that gets resolved.

This is exactly the reason we did not offer a backup-download from the GUI until now..

**Comment by thezoggy** [comment]
We could just choose to skip exporting the username/password. But let's be honest, if someone has access to the box they can already see it. We just should not save the file world readable/serve it up to the browser.

**Comment by modem7** [comment]
I'm more concerned with the muppets who put it over reverse proxy/open port and serve it to the world. Limiting what potential damage could be done by someone seeing plaintext password would certainly be prudent

**Comment by Safihre** [comment]
Closed by #2023
