### ISSUE TITLE
Duplicate Detection doesn't look at filenames

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1288]
This thread triggered me: https://forums.sabnzbd.org/viewtopic.php?f=3&t=24199
He's right, only with the `.nzb Backup Directory` enabled we check the name of the download. Why would that be? Wouldn't we also want to just do a simple `name_new in old_names`?

@sanderjo @jcfp @thezoggy @jeffgeorge

**Comment by jcfp** [comment]
Can't really think of a good reason. Probably just a logic error, along the lines of #390.
