### ISSUE TITLE
Saving Categories with VirtualHost

### ISSUE THREAD

**Issue by KoalaBear84** [sabnzbd/sabnzbd#1290]
Sabnzbd works perfectly behind a Apache VirtualHost configuration. The only thing I notice is that the redirect is wrong on Categories tab. It does works for Folders and Server etc. for example.

It redirects with an extra "sabnzbd" in between: http://sabnzbd.domain.nl/sabnzbd/config/categories/

```
<VirtualHost *:80>
	ServerName sabnzbd.domain.nl

	ProxyPreserveHost On
	ProxyPass "/" "http://127.0.0.1:8181/sabnzbd/"
	ProxyPassReverse "/" "http://127.0.0.1:8181/sabnzbd/"
</VirtualHost>
```

**Comment by sanderjo** [comment]
My SAB is behind a apache reverse proxy. Is that the same / same problem?

If so: can you tell how to reproduce the problem? I experience no problems via https://blablabla.com/sabnzbd/config/categories/

**Comment by KoalaBear84** [comment]
I don't have it it a subdirectory at the 'root', it's running directly on sabnzbd.domain.nl, not in sabnzbd.domain.nl/sabnzbd/.

I reproduce it with the provided VirtualHost config, and go to sabnzbd.domain.nl, go to Settings, to Categories and press Save.

**Comment by sanderjo** [comment]
Can you send a PR?

**Comment by KoalaBear84** [comment]
I don't have experience with Python. I'm not sure how difficult it is to build and test it all, for what I've just seen from the main repo page it could be easy. Currently don't have time to check it, but maybe the coming evenings.

**Comment by Safihre** [comment]
Have you tried changing `url_base` in [Config > Specials](https://sabnzbd.org/wiki/configuration/2.3/special)?

**Comment by KoalaBear84** [comment]
Thanks Safihre. That indeed fixes it. The for me strange thing is why it only is a problem on the Categories page. :)

Is the logic different?

**Comment by Safihre** [comment]
No the logic is the same, kind of weird actually.. It calls the exact same function..
Glad it worked!
