### ISSUE TITLE
SABnzbd occasionally broadcasts via systemd-journald

### ISSUE THREAD

**Issue by fryfrog** [sabnzbd/sabnzbd#1291]
This is maybe the second or third time it has happened and I'm kind of at a loss to explain it or look into it. I thought it might be worth documenting though. It was probably working on some of the below `.nzb` files from my history folder.

```
0 ✓ fryfrog@unifi ~ $
Broadcast message from systemd-journald@apollo (Tue 2019-05-21 14:18:13 PDT):

SABnzbd.py[19823]:


Broadcast message from systemd-journald@apollo (Tue 2019-05-21 14:18:22 PDT):

SABnzbd.py[19823]: Ͳ
```

```
-rw-r--r-- 1 sabnzbd users  424265 May 21 14:15  The.Red.Line.S01E01.1080p.WEB.H264-MEMENTO.nzb.gz
-rw-r--r-- 1 sabnzbd users  422608 May 21 14:15  The.Red.Line.S01E03.1080p.WEB.H264-MEMENTO.nzb.gz
-rw-r--r-- 1 sabnzbd users  427544 May 21 14:15  The.Red.Line.S01E04.1080p.WEB.H264-MEMENTO.nzb.gz
-rw-r--r-- 1 sabnzbd users  262807 May 21 14:15  The.Red.Line.S01E05E06.One.Day.We.May.Be.More.Than.A.Body-We.Turn.Up.This.Music.Louder.Than.A.Mothers.Cry.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.nzb.gz
-rw-r--r-- 1 sabnzbd users   81202 May 21 14:35  The.Red.Line.S01E01E02.We.Must.All.Care-We.Are.Each.Others.Harvest.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.nzb.gz
```

**Comment by jcfp** [comment]
Sabnzbd may be logging some warning or error, but the broadcasting of these messages is systemd-journald's doing. If you don't want it to do that, you'll have to adjust your systemd config.

**Comment by fryfrog** [comment]
It is odd that *literally* no other service has *ever* broadcast anything using systemd-journald. This is also some default behavior, as I haven't changed this and don't have a clue how to adjust it and would have to Google to do what you suggest. And this "error" that is being broadcast is literally jibberish. That `Ͳ` is not a real `T`.

It is also super rare, it hasn't happened since and maybe happened once previously that I noticed.

**Comment by Safihre** [comment]
Closing this, seems a glitch?
