### ISSUE TITLE
Port undefined Error

### ISSUE THREAD

**Issue by tmfb65** [sabnzbd/sabnzbd#1299]
Hi all, 
I can't install SABnzbd I'm getting a "Port undefined configured for this package". 
I’m using a sinology NAS DS918+, and downloading from there store.

The whole message is:
“Port undefined configured for this package is either used by another service or reserved for system use. Please disable or modify the conflicting service, or contact the developer to modify the package configuration” - see attached screenshot

Please help!!!!

**Comment by Safihre** [comment]
Most likely another application that you use is already using port 8080 on your device. You can also try to restart the system and see if that helps.

**Comment by tmfb65** [comment]
Understood, is there anyway to free that port? I can't do it through the app because I can't download it.

This app was previously installed so it should be the only thing on that port. 


Trust me I've rebooted at least 10 times.


Thank You
720 951 0665

**Comment by tmfb65** [comment]
I talked to Synology and they said:


On the matter of ports being freed up, the Synology NAS will only reserve ports that are designated for use by existing services or packages - you will often see messages regarding reserved ports if you try to assign a reserved port to something else in DSM, such as via the Application Portal or the DSM ports. There is no way to "free" these reserved ports because of their special status in the system. 

By contrast, the NAS won't be blocking/using a port that haven't been assigned to anything. As such, unless you have assigned port 8080 somewhere else explicitly in DSM or the system is not reporting that as a reserved port when you try to assign it somewhere else in DSM, the port should be accessible assuming it is not being blocked by something else on your network. 


I know this isn't the first time you've seen this issue. What normally works?


Thank You
720 951 0665

**Comment by Safihre** [comment]
You should check what's on port 8080. This is also more an issue for the SynoCommunity repository here on Github, since there is the problem :) You can create an issue there!
