### ISSUE TITLE
py3: Decoder thread crashes on uuencoded article

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1302]
Apparently in Python 3 the line in line.startswith('X-') can be a byte type, which requires different parameters. The article that caused it contains no metadata , only what seems like base64 encoded content. The header or subject has no encoding info.
```
2019-05-28 15:12:59,702::INFO::[downloader:302] Post-processing finished, resuming download
Exception in thread Thread-6:
Traceback (most recent call last):
File "C:\git\sabnzbd\sabnzbd\decoder.py", line 115, in run
data = self.decode(article, lines, raw_data)
File "C:\git\sabnzbd\sabnzbd\decoder.py", line 212, in decode
decoded_data, output_filename, crc, crc_expected, crc_correct = sabyenc3.decode_usenet_chunks(raw_data, article.bytes)
ValueError: Could not get filename
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
File "C:\Users\t\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "C:\git\sabnzbd\sabnzbd\decoder.py", line 160, in run
if not line.startswith('X-') and match_str(lline, ('dmca', 'removed', 'cancel', 'blocked')):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by sanderjo** [comment]
Same as here https://forums.sabnzbd.org/viewtopic.php?f=11&t=24226 ?

**Comment by sanderjo** [comment]
Can you share the NZB that causes this?

**Comment by sanderjo** [comment]
FWIW:

```
sander@witte:~$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> bline = b"X-ddddd"
>>> bline.startswith('X-') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
>>> 

>>> bline
b'X-ddddd'
>>> bline.decode('utf-8')
'X-ddddd'
>>> 
>>> bline.decode('utf-8').startswith('X-') 
True


```

**Comment by puzzledsab** [comment]
I assume that might work, but I've fixed it like this (only the sorting file, the part in decoder.py was only for debugging): https://github.com/puzzledsab/sabnzbd/commit/f5daf1e229d6510bbb8a278e834505fef880cab2#diff-93622f8c74302d4f51c8caf870ae9bd4

I don't think it's actually UTF-8-encoded so decoding it as such might give incorrect results.

**Comment by puzzledsab** [comment]
I just got this error as well so I guess all similar lines need to be found.

2019-06-21 02:35:18,686::ERROR::[newsunpack:536] Error "a bytes-like object is required, not 'str'" while running rar_unpack on Much-longer-filename-than-this
2019-06-21 02:35:18,687::DEBUG::[newsunpack:537] Traceback:
Traceback (most recent call last):
  File "C:\gitdevelop\sabnzbd\sabnzbd\newsunpack.py", line 522, in rar_unpack
    one_folder, nzo, rar_set, extraction_path)
  File "C:\gitdevelop\sabnzbd\sabnzbd\newsunpack.py", line 599, in rar_extract
    fail, new_files, rars = rar_extract_core(rarfile_path, numrars, one_folder, nzo, setname, extraction_path, password)
  File "C:\gitdevelop\sabnzbd\sabnzbd\newsunpack.py", line 739, in rar_extract_core
    if 'must not exceed 260' in line2:
TypeError: a bytes-like object is required, not 'str'

**Comment by thezoggy** [comment]
> TypeError: a bytes-like object is required, not 'str'

usually means file was open in binary mode.. so data read from the file is returned as bytes objects, not str. just need to drop the binary flag and everything would be back to normal... but gotta track down where.

**Comment by Safihre** [comment]
We need to update it to use bytes, because the `universal_newlines` thing doesn't work well enough on Python 3.5 through 3.7. It fails when it get's an unexpected encoding, something that often happens for us since Unrar/Par2 might output the encoding as used on the original system when the files were created.

Plus, we can't do Direct Unpack because these settings only work for whole lines (so after it detects `\n`), and for Direct Unpack we need to parse every character.

**Comment by Safihre** [comment]
Fixed the `newsunpack` one here: https://github.com/sabnzbd/sabnzbd/commit/76f0896029ea3cd611aae83e2528b683236557a9

**Comment by Safihre** [comment]
Fixed this part previously, but forgot in 1 instance to use the correct variable 🤔
