### ISSUE TITLE
sab 2.3.9 -- not using max connections

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1303]
noticed download was getting half normal speed.
saw a warning earlier about hitting max connections, looks like if that happens it sets the max connections from that point forward? status screen says 10 when 24 are configured. (no config changes recently, always been 24)
```
2019-06-20 17:12:36,114::WARNING::[downloader:639] Too many connections to server news.supernews.com
```
several mins later, still only using 10 (also tried pausing the queue and restarting):
![sab](http://zoggy.net/firefox_2019-06-20_17-16-34.png)

from log, can see it says connections is 24:
```
[[news.supernews.com]]
username=<USER>
priority = 0
enable = 1
displayname = SuperNews
name = news.supernews.com
ssl_ciphers = AES128-GCM-SHA256
notes = ""
connections = 24
ssl = 1
host = news.supernews.com
timeout = 120
ssl_verify = 1
send_group = 0
password=<PASSWORD>
optional = 0
port = 563
retention = 1500
```

**Comment by thezoggy** [comment]
paused queue, went to config and modified it from 24 to 23 and saved. then modified back to 24. started queue. now its using 24
![sab2](http://zoggy.net/firefox_2019-06-20_17-22-20.png)

**Comment by Safihre** [comment]
When getting that specific error we reduce internally the number of connections for a set amount of time. That's intended behavior to prevent more errors and it fully locking up.

**Comment by thezoggy** [comment]
is it supposed to stay that way for the whole job or a specific time?

**Comment by Safihre** [comment]
The 10 min time frame makes sense, that's usually also something that providers will consider really free again.
It should restart after 10 minutes, where it's 10 minutes after the last error. So not 12x10.
But if you get 1 error, then another one 9 minutes later the connections will only be restored 19 minutes after the first error.
Although looking at the code, I wonder if the way it's implemented this actually works..
Will have to test this!

**Comment by Safihre** [comment]
I just tested this and indeed, after the penalty is expired it will reinitialize the server with the maximum number of connections again.
So looks like it's working to me :)
