### ISSUE TITLE
Apply IP filtering permissions to X-Forwarded-For

### ISSUE THREAD

**Issue by ssa3512** [sabnzbd/sabnzbd#1307]
In #884 logging was added for the X-Forwarded-For header, but it doesn't appear that the access check function looks at this header. When I set internet access to "no access" I am still able to access as cherrypy.request.remote.ip is still 127.0.0.1

https://github.com/sabnzbd/sabnzbd/blob/b12a723a44335d5b98bfd77858b8b658cbe76aab/sabnzbd/interface.py#L131-L147

Can we add a check for the xff header in this function and using that value instead of remote.ip if it exists?

**Comment by Safihre** [comment]
@jeffgeorge and @sanderjo maybe you can help me with this one?
What is the risk? Can this header me manipulated by an attacker? Or is it configured by the user?
What if I just add a `X-Forwarded-For` header with `localhost` myself to any request? Won't it just accept it then?

**Comment by jeffgeorge** [comment]
My understanding is that you can shove whatever you want into an `X-Forwarded-For` header. It's only there as an informative header, not something to do any kind of authentication check against. If we auth'ed against it what's stopping someone from passing in `X-Forwarded-For: 127.0.0.1`?

If you're running SABnzbd in a reverse-proxy situation, SABnzbd should be listening on an internal-only IP. Yes, it'll still technically be available from the host it's running from, and yes that means this access control no longer works, but by setting up a reverse proxy in the first place you're taking access control into your own hands.

**Comment by ssa3512** [comment]
@jeffgeorge Is there any harm in checking this header in addition to the source IP if it is present? I believe if properly configured, the reverse proxy will override anything on an incoming request with the ACTUAL source IP in the xff header. Adding this additional check is more restrictive than the current behavior so it wouldn't lead to any new unauthorized access scenarios but should properly restrict them in the scenario where a reverse proxy is being used.

**Comment by jeffgeorge** [comment]
Oh that's a good point. If you've got a reverse proxy set up `cherrypy.request.remote.ip` would be some flavor of localhost, and the `X-Forwarded-For` header should be the real ip. If we've already checked and confirmed that `cherrypy.request.remote.ip` is some flavor of localhost then yes it should be safe to *then* check `X-Forwarded-For`. You wouldn't be able to forge *both* headers at the same time.

**Comment by sanderjo** [comment]
> @jeffgeorge and @sanderjo maybe you can help me with this one?
> What is the risk?

Sorry, I don't understand: is this about a security risk, or a nice-to-have regarding access control.

I only know this: my SAB is behind a reverse proxy, and I saw this:

```
$ cat ~/.sabnzbd/logs/sabnzbd.log | grep -i forward
2019-07-29 22:01:11,664::INFO::[interface:722] Successful login from 127.0.0.1 (X-Forwarded-For: 14.13.99.25)
```

That is my remote access.

**Comment by ssa3512** [comment]
@sanderjo I think this falls somewhere between the two.

I want to be able to use the External internet access setting of "API -> Add NZB Files" behind a reverse proxy. Right now if you have a reverse proxy set up, the `cherrypy.request.remote.ip` is that of the reverse proxy server, not that of the original request. Effectively, the External internet access setting is "Full Web interface" despite being set to API add NZB only.

We are correctly logging the XFF value as you note. We just aren't checking the XFF value if it exists when checking access control. This leads to unexpected behavior when trying to use SAB's built in access controls behind a reverse proxy.

**Comment by sanderjo** [comment]
FWIW: My sabnzbd is only listening to 127.0.0.1, so not reachable at all remote clients, so I think I can't verify the described problem ... ?

**Comment by ssa3512** [comment]
I believe the fix I am envisioning would look something like this.

https://github.com/ssa3512/sabnzbd/commit/0afcb1d355a319a076765f3c18a96a36fe0be925

**Comment by Safihre** [comment]
@ssa3512 Bit late now, but we can still implement this if you make a PR! Just indeed have to check that `cherrypy.request.remote.ip` is some form of local-IP before trusting the remote IP.

**Comment by Mactastic1-5** [comment]
@ssa3512 @Safihre I'm having the same problem today. Can this be added?

**Comment by thezoggy** [comment]
just to add a note, most people these days normally would handle the auth and forward ip with reverse proxy.

**Comment by Safihre** [comment]
We could add a (Specials) switch for it `trust_xforwarded_for`. 
Anyone willing to make PR?

**Comment by sanderjo** [comment]
Based on https://github.com/sabnzbd/sabnzbd/commit/c3f82e49bf0bdf3793fe2d22976cd01faeb614e5 would this logic work:

in check_access():
if xff filled out, then use that for checking.
Otherwise use remote_ip

**Comment by Safihre** [comment]
Maybe I just don't understand it well enough. Say we have a regular non-proxied SABnzbd instance, that's set to `No-access`, but I send IP=something-external and xff=localhost, how would we catch that?
