### ISSUE TITLE
TLSv1.x - wrong description

### ISSUE THREAD

**Issue by Appyx** [sabnzbd/sabnzbd#1308]
This issue is purely cosmetic...at least I hope so.

The connections tab shows `TLSv1.2 (AES128-SHA)`.
But it should show `TLSv1.3 (AES128-SHA)`, because a v1.2 cipher without key exchange doesn't exist (...correct me).

Therefore I assume that it is using a TLSv1.3 cipher, which would be valid in this case.

tldr;

The cipher suite does not fit to the protocol description in the connections tab.

my reference: https://crypto.stackexchange.com/a/62918

Edit: I'm confused:

`openssl s_client` shows the following output:

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-SHA
```

What's the key exchange algorithm?

**Comment by sanderjo** [comment]
AFAIK there is not any newsserver in the wild that speaks TLS1.3. Please provide the name of the newsserver of which you think it speaks TLS1.3.

Until then: SAB en openssl are correct

**Comment by Appyx** [comment]
Yeah the issue is not related anymore. Closed.
