### ISSUE TITLE
Large Files - Unresponsive During Unpack?

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1312]
_For the latest stable version of Sabnzbd:_

Downloading files that are over 5GB seems to have a chance to cause the system to stop responding (applications not responding) while unpacking. Visually it shows as a freeze (cannot move mouse) with white window titles showing up.

I'm experiencing this occasionally on my Intel Core i5-4690 (3.5GHz), 32 GB RAM and an SSD.

**Has anyone else experienced this?** I know technology can be temperamental.

**Comment by thezoggy** [comment]
5gb is not very large. 50gb+ would be that for most. If your system is locking up.. most likely your chipset is pegged for your io. I would look at upgrading drivers/bios update and/or moving up to non shared ports. Now you really didn't provide much to help on what is wrong. If your downloading to some external USB drive attached to a remote computer across your network..

**Comment by Safihre** [comment]
Agreed with @thezoggy, 5GB is not much at all and shouldn't cause any lock-up. Is the drive maybe external (USB or network)? Did you modify the sabnzbd settings a lot? Because it's possible to set the Windows process priority to very high, in Advanced settings.

**Comment by hl2guide** [comment]
Over 3 years I've only downloaded > 5 GB files maybe 2 times.

It was a local SATA connected SSD for both the incomplete and completed folders. No other app was running that would slow down the PC at the time.

For the moment I'll guess that I can chalk it up as an anomaly and that if it happens again some time then I'll post then.

Thanks for all the help 💃 @thezoggy @Safihre
