### ISSUE TITLE
py3: Password in nzb meta doesn't work

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1314]
The password is imported as a string attribute but Sab seems to assume it's an array when it's unpacked. This results in Error "'str' object has no attribute 'append'" while running rar_unpack.

Example nzb: https://gist.github.com/puzzledsab/5ed1fb14a6e0212dd5994dd7e3787d98

**Comment by Safihre** [comment]
Fixed, the new NZB-parser didn't account for multiple tags with same identifier.
