### ISSUE TITLE
distutils error

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1316]
Hey Guys, 
Running into an issue where I try to switch to py3 branch but i'm getting the below error and i'm not sure how to get around this. Trying to remove the rpm wants to remove everything that's using it as well. 
Opensuse Leap 15.1, py3 branch, fresh pull

ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by thezoggy** [comment]
might be helpful if you showed us the commands you are doing. buy yeah you prob dont want to uninstall 'six' as its a genric utility thats pretty much required these days by many apps for py2<>py3 compatibility.

**Comment by sanderjo** [comment]
Try to remove which rpm...?

**Comment by mgaulton** [comment]
Sorry, remove the six rpm so I can pip it instead. Since that was breaking it from what I was seeing.

I followed these steps:
We tumbleweed for Python 3.5+
Not using docker.
# sudo docker run -it opensuse/tumbleweed /bin/bash
and then

#zypper install git python3-pip
^already installed
git clone https://github.com/sabnzbd/sabnzbd.git
^already cloned, didn't replace.
cd sabnzbd/
git checkout py3
pip3 install -r requirements.txt -U
^this is the step giving me the error

./SABnzbd.py -b0

**Comment by sanderjo** [comment]
Ah. Can you try this:

`pip3 install -r requirements.txt`

... and if that doesn't work, try this:

`pip3 install -r requirements.txt -I`

... and if that doesn't work, try this:


`pip3 install -r requirements.txt -U -I`

**Comment by mgaulton** [comment]
The error does seem to not be happening now but it still thinks something is missing. 
Thanks.


> pip3 install -r requirements.txt
``Successfully installed backports.functools-lru-cache-1.5 cheroot-6.5.5 cherrypy-18.1.2 feedparser-5.2.1 gntp-1.0.3 jaraco.functools-2.0 portend-2.5 tempora-1.14.1 zc.lockfile-2.0
server6:/opt/sabnzbd #
server6:/opt/sabnzbd # ./SABnzbd.py -b0
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3
```
> ... and if that doesn't work, try this:
> 
> pip3 install -r requirements.txt -I
```
Successfully installed asn1crypto-0.24.0 backports.functools-lru-cache-1.5 cffi-1.12.3 chardet-3.0.4 cheetah3-3.2.3 cheroot-6.5.5 cherrypy-18.1.2 configobj-5.0.6 cryptography-2.7 feedparser-5.2.1 gntp-1.0.3 jaraco.functools-2.0 more-itertools-7.2.0 portend-2.5 pycparser-2.19 pytz-2019.2 sabyenc3-4.0.1 setuptools-41.1.0 six-1.12.0 tempora-1.14.1 zc.lockfile-2.0
server6:/opt/sabnzbd # ./SABnzbd.py -b0
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3

```
> ... and if that doesn't work, try this:
> 
> pip3 install -r requirements.txt -U -I
```
Successfully installed asn1crypto-0.24.0 backports.functools-lru-cache-1.5 cffi-1.12.3 chardet-3.0.4 cheetah3-3.2.3 cheroot-6.5.5 cherrypy-18.1.2 configobj-5.0.6 cryptography-2.7 feedparser-5.2.1 gntp-1.0.3 jaraco.functools-2.0 more-itertools-7.2.0 portend-2.5 pycparser-2.19 pytz-2019.2 sabyenc3-4.0.1 setuptools-41.1.0 six-1.12.0 tempora-1.14.1 zc.lockfile-2.0
server6:/opt/sabnzbd # ./SABnzbd.py -b0
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3

```
> Please report back the result.

**Comment by sanderjo** [comment]
OK. Pity SAB-py3 does not print which module is missing, so let's fix that: Can you run this code with python3. So: save to file `dummy-import.py`, and run in with python3 like this:

```
python3 dummy-import.py
```

with this code in dummy-import.py:
```
import sys

try:
    import Cheetah
    if Cheetah.Version[0] != '3':
        raise ValueError
    import six
    import feedparser
    import configobj
    import cherrypy
    import portend
    import cryptography
    import chardet
    import gntp
except ValueError:
    print("Sorry, requires Python module Cheetah 3 or higher.")
    sys.exit(1)
except ImportError as e:
    print("Not all required Python modules are available, please check requirements.txt.")
    print("Exception is", e)
    print("You can read more at: https://sabnzbd.org/python3")
    sys.exit(1)

print("OK")
```

**Comment by mgaulton** [comment]
OK, now i'm really confused.

server6:~ # python3 dummy-import.py
OK
server6:~ #

**Comment by sanderjo** [comment]
Run python3 SABnzbd.py ... quick!

**Comment by mgaulton** [comment]
server6:/opt/sabnzbd # python3 SABnzbd.py
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3

**Comment by Safihre** [comment]
This makese no sense. Can you try by just deleting some imports in SABnzbd.py? Seems we need to go trial and error now.

**Comment by puzzledsab** [comment]
Are you running dummy-import.py and SABnzbd.py using the same user and the same shell instance? Try changing SABnzbd.py so that it looks like the test script (add/edit the lines ```except ImportError as e``` and ```print("Exception is", e)```) or replace it with this file which contains the changes:
https://raw.githubusercontent.com/puzzledsab/sabnzbd/py3-test/SABnzbd.py

**Comment by mgaulton** [comment]
So, as an experiment, I cloned fresh to a temp folder, switched branches and it started.
So I use a split install, I have the repo cloned in one folder, and used a different folder for the config. I've tested just the install from the repo folder, not with production config.
I tried it both ways and it gives me the same message.
I went to my existing install folder, and tried to run it. Didn't work again.
So I nuked the repo folder, recloned, ran it, same message. 
I am so confused.


server6:/tmp # git clone https://github.com/sabnzbd/sabnzbd.git sabtest
Cloning into 'sabtest'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 56176 (delta 19), reused 24 (delta 0), pack-reused 56132
Receiving objects: 100% (56176/56176), 113.93 MiB | 5.27 MiB/s, done.
Resolving deltas: 100% (38633/38633), done.
server6:/tmp # cd sabtest/
server6:/tmp/sabtest # git checkout py3
Branch 'py3' set up to track remote branch 'py3' from 'origin'.
Switched to a new branch 'py3'
server6:/tmp/sabtest # python3 ./SABnzbd.py
2019-08-16 10:40:55,648::INFO::[SABnzbd:1095] --------------------------------
2019-08-16 10:40:55,648::INFO::[SABnzbd:1096] SABnzbd.py-3.0.0-develop (rev=unknown)
2019-08-16 10:40:55,648::INFO::[SABnzbd:1097] Full executable path = /tmp/sabtest/SABnzbd.py
2019-08-16 10:40:55,649::INFO::[SABnzbd:1107] Platform = posix
2019-08-16 10:40:55,649::INFO::[SABnzbd:1108] Python-version = 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
2019-08-16 10:40:55,649::INFO::[SABnzbd:1109] Arguments = ./SABnzbd.py
2019-08-16 10:40:55,649::INFO::[SABnzbd:1112] Preferred encoding = UTF-8
2019-08-16 10:40:55,649::INFO::[SABnzbd:1119] SSL version = OpenSSL 1.1.0i-fips  14 Aug 2018
2019-08-16 10:40:55,649::INFO::[SABnzbd:1166] Using INI file /root/.sabnzbd/sabnzbd.ini


server6:/tmp/sabtest # cd /opt
server6:/opt # cd sabnzbd/
server6:/opt/sabnzbd # git checkout py3
Already on 'py3'
Your branch is up to date with 'origin/py3'.
server6:/opt/sabnzbd # python3 ./SABnzbd.py
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3
server6:/opt/sabnzbd #

server6:/opt # rm -rf sabnzbd/
server6:/opt # git clone https://github.com/sabnzbd/sabnzbd.git
Cloning into 'sabnzbd'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 56176 (delta 19), reused 24 (delta 0), pack-reused 56132
Receiving objects: 100% (56176/56176), 113.93 MiB | 3.67 MiB/s, done.
Resolving deltas: 100% (38633/38633), done.
server6:/opt # cd sabnzbd/
server6:/opt/sabnzbd # git checkout py3
Branch 'py3' set up to track remote branch 'py3' from 'origin'.
Switched to a new branch 'py3'
server6:/opt/sabnzbd # python3 ./SABnzbd.py
Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3
server6:/opt/sabnzbd #

**Comment by mgaulton** [comment]
and for arguments sake, I pointed my startup scripts at /tmp/sabtest and it worked. 
so does it not like /opt/sabnzbd for some reason?

**Comment by mgaulton** [comment]
ok, so I nuked sabnzbd repo, moved the /tmp/sabtest to that location and now it works.
I'm at a loss

**Comment by puzzledsab** [comment]
What happens if you run dummy-import.py from /opt/sabnzbd or change SABnzbd.py to tell which module can't be loaded?

**Comment by mgaulton** [comment]
Interestingly, I was doing this all as root at the time.  You might be right, I just can't think of why.
Sadly, i didn't think of keeping a copy of the broken folder and blew it away.
Its working now with the moved folder, but I'm not sure why.

server6:/opt/sabnzbd # python3 dummy-import.py
OK

Its rebuilding the queue right now. I'll keep an eye on it. Thanks for the help guys. You rock as always.

**Comment by Safihre** [comment]
Great 👍

**Comment by Safihre** [comment]
In case anyone finds this, cached compiled Python files might cause problems and cause this error.

```
Traceback (most recent call last):
  File "SABnzbd.py", line 40, in <module>
    import six
ImportError: bad magic number in 'six': b'\x03\xf3\r\n'
```

You need to remove all `.pyc` files and try again!

**Comment by thezoggy** [comment]
@Safihre did we ever update the installer to do a py3 version?

Python 3 puts .pyc files in a separate directory called __pycache__, and adds version information to the filename. The new mechanism avoids the above two problems: per-version caches are separated, and if the .py source is missing, the .pyc file is not considered.

If your code relies on the location of .pyc files (for example, if your build/packaging system doesn’t handle Python 3), you will need to update to the new location.

**Comment by Safihre** [comment]
I experienced this when switching between Python 2 and now Python 3 for develop. The `.pyc` files were not in the pycache folder, but in the main folders.
So it's only for special cases, normally no problem.
