### ISSUE TITLE
Support for multiple Indexer Integration Feedback

### ISSUE THREAD

**Issue by jobrien2001** [sabnzbd/sabnzbd#1317]
Hello,

Sabnzb needs an enhancement to support multiple indexers for feedback.  The way it is now, users with multiple indexer cannot securely use the feature because wrong keys can be sent to the wrong indexer and the key can be stolen.

Right now there is only an input box for API key.  For multiple indexers to work there should be 2 input boxes per indexer, feedbackurl and api.

For example:

User specifies:
```
feedbackurl="https://api.nzbgeek.info/feedback"
API="12345"
```

An nzb contains meta tag:
`<meta type="x-rating-host">https://api.nzbgeek.info/feedback</meta>`

If Sabnzb finds that `x-rating-host` value matches any of the user's `feedbackurl`, then it uses `API` value to provide feedback.

Also, multiple indexers could be added that same way with +Add button (like the one found in the categories section for multiple categories).

If most of the feedbackurl are well known, a drop down could be used so that the feedbackurl does not have to be entered, instead just the name of the indexer is selected (for user friendliness)

Any feedback would be great.

**Comment by jobrien2001** [comment]
I made a suggestion mockup:

![multiple indexer](https://user-images.githubusercontent.com/12868319/62832163-06ac2180-bbf0-11e9-84db-8e96b654aab3.jpg)

**Comment by wtfnzb** [comment]
+11111% make it properly working the hell!

**Comment by Safihre** [comment]
Agreed, this way it's a bit useless with multiple indexers..

**Comment by wtfnzb** [comment]
We are gonna 100% support it if properly done ;) still undecided if this is better than some postprocessing script (*.sh or *.bat), so after finising dl of nzb script can send via curl to our api point the completion, errors etc, whats better?

i mean what about automation of it via posprocessing script? after dl, sab will auto report which news provider was used, how much articles was grabbed or missed... its a nice feature to have so the indexers will have auto feedback from different usenet providers

**Comment by Safihre** [comment]
>  after dl, sab will auto report which news provider was used, how much articles was grabbed or missed

This is indeed what we report. Although not exact article stats, only failed or not and on which servers.

**Comment by wtfnzb** [comment]
Yes but currently is really hard to integrate, its easier to make just sh|bat script, sab have hardcoded *.php url for reporting... :D

Setting posprocessing script and writting it takes 5 min, setting everything and rewriting sabnzbd could takes forever as i see :D

**Comment by Safihre** [comment]
You can supply your own URL via `x-rating-url`, not fixed to the `.php`: https://sabnzbd.org/wiki/extra/indexer-feedback

**Comment by wtfnzb** [comment]
hmm let me try that once again xD does it sending via curl?

**Comment by wtfnzb** [comment]
So sabnzbd will do a POST request to my php script on server, letz try diz one 

`<?php
$req_dump = print_r($_REQUEST,TRUE);
$fp = fopen('/home/request.log', 'a');
fwrite($fp, $req_dump);
fclose($fp);
`

**Comment by wtfnzb** [comment]
Ooooo finalllly jeezus 

```
Array
(
    [pr] => usenet
    [auto] => 1
    [apikey] => ***
    [m] => rpr
    [i] => ***
)
```

**Comment by wtfnzb** [comment]
but diz will work only for our indexer, if user wants support multiple indexers we need another option(s)

**Comment by wtfnzb** [comment]
btw is the sending feedback cached or so? i am not able to send the same all over again, i need it since debugging...

**Comment by jobrien2001** [comment]
I didnt think about a post processing script.  But how would the user specify the api to be used?  Manually editing a conf file? Might not be user friendly for some sabnzb users.

**Comment by puzzledsab** [comment]
I'm looking into this. @Safihre : Do you know what parts of the current system are actually used anywhere? I know NZBgeek has x-rating-host, but the URL gives 404 so I don't think it's active. Also, if it was following https://sabnzbd.org/wiki/extra/indexer-feedback it should have been x-rating-url and not x-rating-host.

I have currently made the config system for adding servers with the fields url, apikey and autosend (for accepting to automatically send a report about failure or success and possibly other data). I would like to change the usage of x-rating-url to not include API key. That way it can be used to fetch the data from the configuration database, and the correct API key can be used.

**Comment by Safihre** [comment]
We support both host and url, based on what the indexer wants to use. If they use host they are limited to the hard-coded path we choose, so that's not very convenient. 

Nzbgeek used to implement it, but then they were hacked a month ago and rebuild the whole platform. Guess they didn't add support for this back yet. 
Unless we can support multiple indexer, this feature isn't going to get much support from indexer. 
But when we do support multiple, I can try to push some more indexers to add support!

**Comment by albino1** [comment]
Even with the indexers that did support it, it was always kind of useless, and even more so years later.  Almost all downloads are automated, and if they fail the automation software just grabs a different release.  Very few people are going to look at an individual NZB's page on an indexer and try and determine if they have the correct server combination to download it, and even if they did, what failed or worked for people before could easily be irrelevant now.  DMCA, NTD, changes in retention, article caching, back filling from other providers, etc, all make whatever info that indexer reporting provides nearly meaningless.

**Comment by puzzledsab** [comment]
It doesn't have to be perfect to be useful. There are usually many versions of the same file. If the indexer could report what the success rate was for each nzb in the last X days then the automation software could take that into account when it picks a file. On average that would reduce the amount of time spent trying to get a good version and the amount of data wasted from block accounts.

**Comment by albino1** [comment]
I guess if the thinking is that this becomes an industry-wide standard adopted by all of the top indexers, automation software, downloaders, etc, then it would become actually useful.  That's a tall order, but I suppose it has to start with SAB and NZBGet or it will never happen.  If it's a difficult or time consuming task, maybe reach out to some of the indexers with larger user-bases first to see if they're even interested in implementing it before moving forward.  If it's easy then you can just implement it and see if anybody follows your lead and it picks up any steam.

The only potential downside I can see is if the download clients are reporting success rates to indexers, and then software now has the ability to poll various indexers for an NZB or individual post's success rate, then that seems like it could create a scenario that leads to easier and more frequent DMCA takedowns.  Probably not, but you should think through any unintended consequences.

**Comment by Safihre** [comment]
@albino1 we already have the whole system in place, the only change is the adding of support for multiple indexer. So it's not a huge change.
