### ISSUE TITLE
py3: Postprocessing scripts doesn't work in Windows

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1318]
In the py3 version the long_path function is run in SABNzbd.py, adding ```\\?\``` to almost everything including the script path. This results in the message "The system cannot find the path specified." when Popen tries to run it.

I'm not sure how to fix it properly without breaking something else. In the Python 2 version it is only run on the paths that are used as parameters. Maybe going back to that would be better.

Adding
```
if command[0][:4] == '\\\\?\\':
    command[0] = command[0][4:]
 ```
to external_processing makes it work.

**Comment by Safihre** [comment]
Strange! That normally isn't a problem I thought.
Hope to look at the issues early next week :)

**Comment by thezoggy** [comment]
>  with Python 2.x, string literals are str byte strings unless prefixed with u to create a unicode instance. Concatenating str and unicode uses the default ASCII encoding to decode the str instance, so if short_path is unicode, prepending '\\\\?\\' results in unicode; otherwise it creates a new str. The OP should prepend u'\\\\?\\'

https://stackoverflow.com/questions/1365797/python-long-filename-support-broken-in-windows
> In order to use the \\?\ prefix (as already proposed), you also need to make sure you use Unicode strings as filenames, not regular (byte) strings.

**Comment by puzzledsab** [comment]
Here are some tests I did:
```
C:\>\\?\c:\windows\system32\xcopy.exe c:\windows\system32\xcopy.exe c:\temp\
The system cannot find the path specified.

C:\>xcopy \\?\c:\windows\system32\xcopy.exe c:\temp\
Invalid drive specification
0 File(s) copied

C:\>copy \\?\c:\windows\system32\xcopy.exe c:\temp\
        1 file(s) copied.
```
So it seems that it doesn't work with the executable (at least not in the cmd shell) and only with some programs as parameters.
