### ISSUE TITLE
py3: suggestion "3" in logo? Or some other 3 indicator

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1319]
Sometimes it's unclear to me which SAB version (py2 or py3) I'm running. That will also be the case in the transition period of users going from py2 to py3.

So, how about something on the frontpage that makes that clear?

As an example, I hacked a "3" into the SVG icon on the frontpage (`inkscape interfaces/Config/templates/staticcfg/images/logo-small.svg`):

![image](https://user-images.githubusercontent.com/1273502/63104558-81be6080-bf7f-11e9-9605-0073ab8ee81e.png)

There will probably better solutions than this. 

Or white-yellow font color:

![image](https://user-images.githubusercontent.com/1273502/63214193-638a6900-c115-11e9-8225-da21dfb41b08.png)

**Comment by sanderjo** [comment]
PS: @thezoggy did you create the SVG? If so, I really look forward to your feedback.

**Comment by jeffgeorge** [comment]
Nope, that was me. Rather than tweaking the SVG, I think it might be a bit easier (and easier to roll back) if we did this in css. I'll take a look at what that might take to implement.

**Comment by thezoggy** [comment]
I think i did the .ai files but gave them to jeff to process/convert.

**Comment by sanderjo** [comment]
... and how about a "2" in to-be-released SABnzbd 2.x versions?
