### ISSUE TITLE
Comprehension Of clear_trans_cache

### ISSUE THREAD

**Issue by as900** [sabnzbd/sabnzbd#1320]
Hi there, When I was learning and trying to understand the function "clear_trans_cache" in sabnzbd/sabnzbd/api.py, I was confused about the description of its delivered function. My understanding of this code snippet is "clean cache for skin translations". Do I understand that right?

**Comment by Safihre** [comment]
Yes that's right. We cache translation-strings because it's faster. When changing language, the cache needs to be cleared.
