### ISSUE TITLE
FYI: daily test-NZB from usenet.farm

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1322]
FYI / FWIW:

a daily NZB on https://usenet.farm/nzb/ with size 500MB
for example https://usenet.farm/nzb/2019-08-17.nzb

I don't know if there is a RSS feed.
And strangely enough I can't find them via binsearch.info not https://nzbindex.com/, whereas the info looks quite ok:
```
file poster="support@usenet.farm" date="16 Aug 19 02:01 CEST" subject="Completion test 2019-08-16"
```

Source: https://www.reddit.com/r/usenet/comments/cpph4a/newsdemon_suddenly_is_not_downloading_anymore/ewqz1pt?utm_source=share&utm_medium=web2x

**Comment by Safihre** [comment]
Thanks :)

**Comment by thezoggy** [comment]
maybe offer up this nzb for the speed test as well ?

**Comment by Safihre** [comment]
It's branded to a specic usenet service, don't think we should do that.
