### ISSUE TITLE
Chrome intermittently freezing on Downloading

### ISSUE THREAD

**Issue by Sanborn32b** [sabnzbd/sabnzbd#1324]
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
SABnzbd Verision 2.3.9 [03c10dc]
Python Version 2.7.16 (v2.7.16:413a49145e, Mar 4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] [cp1252]
Windows 10, version 1803 x64 2019-07B

Problem: Whilst downloading files with SABnzbd and Google Chrome, Chrome will intermittently freeze for around 5 - 8 seconds throughout the download. This impacts the whole system ie. mouse and all keyboard functions freeze. I do not have any issues and no freezing using Newsbin or any other download application ONLY running SABnzbd in Chrome, and only with the latest SABnzbd update. 

[DxDiag.txt](https://github.com/sabnzbd/sabnzbd/files/3535203/DxDiag.txt)

**Comment by thezoggy** [comment]
if you use another browser do you see the issue? (trying to isolate it to see if it really sab causing the issue or just a plugin/something you have in chrome). if your whole machine is locking up.. would make me think either pegged cpu or diskio.

**Comment by thezoggy** [comment]
you sure do have an excessive amount of external usb drives..  try disconnecting those to see if that also alters your machines behavior.

**Comment by Sanborn32b** [comment]
All externals were disconnected. Issue still occurs... No problems till
update.

**Comment by Sanborn32b** [comment]
I will install to other browser and try. Task manager doesn't show issues
with CPU cycles, network or drive load.

**Comment by Safihre** [comment]
You can download the old version here: https://sabnzbd.org/download-stats

Sounds much more likely that your virusscanner is acting up than a change in sabnzbd.
