### ISSUE TITLE
sab2 -- Extra History > Speed column empty

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1325]
If a download is fetched in <1 seconds the "Extra History > Speed" column will be empty:
![sab](http://zoggy.net/2019-08-26_09-05-48.png)

Can see the item above it took "1" sec and showed the 7.8M.

**Comment by Safihre** [comment]
Because the API doesn't returns the time in second increments, so if it's less than 1 we can't calculate.. Only in the backend code we have the milliseconds.
