### ISSUE TITLE
py3: Post Processing Failed (Scientific Linux/RHEL Clone)

### ISSUE THREAD

**Issue by Hydranet** [sabnzbd/sabnzbd#1328]
About two months ago I changed to the py3 development branch of SABnzbd, something I have been noticing is that I am getting a lot of failed downloads with "checksum error" It's not with every download but I am seeing a lot with downloads where I never used to have problems. When I switch back to the  main master branch and download the same download, it completes without errors.
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/3625112/sabnzbd.log)

OS: Scientific Linux 7.7(RHEL Clone)
```
2019-09-18 09:03:17,697::INFO::[postproc:526] Traceback: 
Traceback (most recent call last):
  File "/opt/sabnzbd/sabnzbd/postproc.py", line 335, in process_job
    par_error, re_add = parring(nzo, workdir)
  File "/opt/sabnzbd/sabnzbd/postproc.py", line 676, in parring
    par_error = not try_sfv_check(nzo, workdir)
  File "/opt/sabnzbd/sabnzbd/postproc.py", line 713, in try_sfv_check
    failed = sfv_check(sfv)
  File "/opt/sabnzbd/sabnzbd/newsunpack.py", line 2249, in sfv_check
    if crc_check(path, checksum):
  File "/opt/sabnzbd/sabnzbd/newsunpack.py", line 2267, in crc_check
    crc = binascii.crc32('')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by sanderjo** [comment]
OK, good that you're using py3!

That `crc = binascii.crc32('')` looks like setting the default value ... but is indeed incorrect. I think it should be `crc = binascii.crc32(b'')` (note the `b` to convert the string to bytes.

So can you try that?

FWIW / BTW as `binascii.crc32(b'')` results in 0, maybe `crc = 0` would easier and cleaner.

**Comment by Hydranet** [comment]
I tried both: binascii.crc32(b'') results in 0, maybe crc = 0

With both I get a successful unpack, which of the two should I use otherwise I can just wait till it is adjusted in the git py3 branch and then pull it once it is available. I forgot to mention which python3 version I am using:
python3 --version
Python 3.6.8

I attached the file which is the same file my attached logs were about. 

[EroticaX - Gabbie Carter In The Mood HD1080p.nzb.gz](https://github.com/sabnzbd/sabnzbd/files/3634472/EroticaX.-.Gabbie.Carter.In.The.Mood.HD1080p.nzb.gz)

**Comment by sanderjo** [comment]
I think the code `crc = 0` is clearest, so use that. Are you willing & able to send a pull request? If not, I'll do it for you.

I've created a NZB that triggers the bug in py3: https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb-with-SFV-no-PAR2.nzb


Please open a separate issue for the other problem.

**Comment by Hydranet** [comment]
I have never had to do a pull request, but I can figure it out if you rather I do it myself. Every day is a good day to learn something new.

**Comment by sanderjo** [comment]
@Safihre do you agree on the `crc = 0`

@Hydranet yes, please try. I use git and git gui (standard tools) to that. Steps are roughly:
1. on github, create to clone of sabnzbd
2. git clone your own repo to your local system
3. git checkout py3
4 . make your change
5. git gui: fill out Commit Message, do Rescan, then Stage Changed, then Commit, then Push
6. on github in your own repo, swith to py3, and click Pull Request

1.

**Comment by sanderjo** [comment]
@Hydranet you can remove your NZB from your post now as I have created a reftestnzb

**Comment by Hydranet** [comment]
> @Safihre do you agree on the `crc = 0` ?
> 
> @Hydranet yes, please try. I use git and git gui (standard tools) to that. Steps are roughly:
> 
>     1. on github, create to clone of sabnzbd
> 
>     2. on your local Linux: git clone your own repo to your local system
> 
>     3. on your local Linux: git checkout py3
> 
>     4. on your local Linux: make your change
> 
>     5. on your local Linux: start git gui, there fill out Commit Message, do Rescan, then Stage Changed, then Commit, then Push
> 
>     6. on github in your own repo, swith to py3, and click Pull Request
> 
>     7. wait for your Pull Request to be accepted
> 
>     8. enjoy your world fame for contributing to open source software

I just did a pull request, technically it is you that solved the issue :) Did I keep using the fork repo from now on for updates in case I come across another issue?

**Comment by Hydranet** [comment]
> @Hydranet you can remove your NZB from your post now as I have created a reftestnzb

I removed the file and replaced it with a comment.

**Comment by sanderjo** [comment]
@Hydranet I see the PR: https://github.com/sabnzbd/sabnzbd/pull/1329/files

Nice! The description could have a bit more descriptive ("set default crc to 0") so that people understand it after a few years, but I think @Safihre can still change that.

**Comment by Hydranet** [comment]
> @Hydranet I see the PR: https://github.com/sabnzbd/sabnzbd/pull/1329/files
> 
> Nice! The description could have a bit more descriptive ("set default crc to 0") so that people understand it after a few years, but I think @Safihre can still change that.

@sanderjo 
Will keep that in mind for in the future ;) I still have learning python on my to do list so maybe someday I may be able to actually help and take credit for something. Credit for solving this should still got to you :)

**Comment by Safihre** [comment]
Thank you! Good catch and something we didn't test yet!

**Comment by Safihre** [comment]
I'll add this NZB to the automated testing!

**Comment by sanderjo** [comment]
> I just did a pull request, technically it is you that solved the issue :) 

You tested it, you found it, I helped a bit, you did the PR. Next time, with your growing python knowledge, maybe you can find the root cause & solution

> Do I keep using the fork repo from now on for updates in case I come across another issue?

@Safihre accepted your PR, so you can go back the official repo and do a "git pull"
