### ISSUE TITLE
py3: won't run

### ISSUE THREAD

**Issue by SledgeHammer75** [sabnzbd/sabnzbd#1332]
Today I did the update to the latest development version from git, requiring pyton3. I am running Ubuntu 18.04 LTS.

I ran "pip3 install -r requirements.txt -U", got the message 

`Installing collected packages: six, sabyenc3, cheetah3, asn1crypto, pycparser, cffi, cryptography, feedparser, configobj, more-itertools, backports.functools-lru-cache, cheroot, pytz, jaraco.functools, tempora, portend, setuptools, zc.lockfile, cherrypy, chardet, gntp`

`Successfully installed asn1crypto-0.24.0 backports.functools-lru-cache-1.5 cffi-1.12.3 chardet-3.0.4 cheetah3-3.2.3 cheroot-6.5.8 cherrypy-18.2.0 configobj-5.0.6 cryptography-2.7 feedparser-5.2.1 gntp-1.0.3 jaraco.functools-2.0 more-itertools-7.2.0 portend-2.5 pycparser-2.19 pytz-2019.2 sabyenc3-4.0.1 setuptools-41.2.0 six-1.12.0 tempora-1.14.1 zc.lockfile-2.0`

When I start to run SABnzbd.py, all I get is
`Not all required Python modules are available, please check requirements.txt.
You can read more at: https://sabnzbd.org/python3`

What did I do wrong? Did I miss a step?

**Comment by thezoggy** [comment]
how did you start sab (which python)
i see you noted you installed the stuff via pip3, which is linked to which python?
they two may not align, (multiple python versions can exist and using venv you could have installed stuff to a different python site-lib then you intended)

**Comment by Safihre** [comment]
Try removing all `.pyc` files in the folder and sub folders.

**Comment by SledgeHammer75** [comment]
YES, deleting `.pyc` did the trick. 
THX

**Comment by thezoggy** [comment]
oh you were switching from python2 to python3 .. hm @Safihre perhaps you should add a note about this in the readme and/or add a note to do this in that error message for py3 users since its triggering a false positive.

**Comment by sanderjo** [comment]
> Try removing all `.pyc` files in the folder and sub folders.

So the .pyc were still old versions?

**Comment by Safihre** [comment]
Added a note to the warning!
