### ISSUE TITLE
py3: non-UTF ENV-setting => traceback " UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 8593: ordinal not in range(128)"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1335]
EDIT: 

**Summary**:

1. Conclusion of this thread: problem is caused by non-UTF ENV-setting in LANG and/or LC_ALL.
2. Quick check: `python3 -c "import locale; print(locale.getpreferredencoding())"` ... if not UTF-8 as result => problem
3. I'll open a separate issue how to handle / block this

Original stuff:

py3 ppa `version 3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3`, only when running as a service

```
sander   19721     1  7 22:28 ?        00:00:00 /usr/bin/python3 -OO /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
```

when accessing via http://192.168.1.3:8080/ I get

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 121, in internal_wrap
    return wrap_func(*args, **kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 401, in index
    return template.respond()
  File "_usr_share_sabnzbdplus_interfaces_Glitter_templates_main_tmpl.py", line 452, in respond
  File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1703, in _handleCheetahInclude
    self.getFileContents(path)
  File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1506, in getFileContents
    output = fp.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 8593: ordinal not in range(128)
Powered by CherryPy 8.9.1
```

It works normally when just running sabnzbdplus ...

**Comment by sanderjo** [comment]
De-installed sabnzbdplus, removed /etc/default/sabnzbdplus and /etc/init.d/sabnzbdplus, installed sabnzbdplus, thus the ppa-3.0.0 version:
I can start it manually
But /etc/default/sabnzbdplus is not there. And thus
```

sander@nanopineo2:~$ sudo service sabnzbdplus start
Failed to start sabnzbdplus.service: Unit sabnzbdplus.service not found.
```

@jcfp is the alfa-ppa missing some settings / files?

(FWIW: this is on ARM64, but I don't think that matters)

**Comment by thezoggy** [comment]
sounds like your env isnt setup?
whats the output of: `locale` (for the user you are starting sab as)

https://stackoverflow.com/questions/10561923/unicodedecodeerror-ascii-codec-cant-decode-byte-0xef-in-position-1

**Comment by sanderjo** [comment]
```
sander@nanopineo2:~$ whoami 
sander
sander@nanopineo2:~$ locale
LANG=C.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC=C.UTF-8
LC_TIME=C.UTF-8
LC_COLLATE="C.UTF-8"
LC_MONETARY=C.UTF-8
LC_MESSAGES=C.UTF-8
LC_PAPER=C.UTF-8
LC_NAME=C.UTF-8
LC_ADDRESS=C.UTF-8
LC_TELEPHONE=C.UTF-8
LC_MEASUREMENT=C.UTF-8
LC_IDENTIFICATION=C.UTF-8
LC_ALL=
```

**Comment by sanderjo** [comment]
@jcfp I removed sabnzbdplus, re-installed `sabnzbdplus (3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3) `, and still no /etc/default/sabnzbdplus.

Still on ARM64.

Tips?



```
sander@nanopineo2:~$ sudo apt-get install sabnzbdplus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libjs-bootstrap libjs-jquery-metadata libjs-jquery-tablesorter libjs-jquery-ui libjs-moment python3-asn1crypto python3-cffi-backend python3-chardet python3-cheetah
  python3-cherrypy3 python3-configobj python3-cryptography python3-feedparser python3-gntp python3-idna python3-jaraco.functools python3-more-itertools
  python3-portend python3-sabyenc python3-six python3-tempora python3-tz
Suggested packages:
  libjs-jquery-ui-docs python-cheetah-doc python3-markdown python3-memcache python3-pygments python-configobj-doc python-cryptography-doc python3-cryptography-vectors
Recommended packages:
  javascript-common python3-openssl python3-routes python3-simplejson libavahi-compat-libdnssd1
The following NEW packages will be installed:
  libjs-bootstrap libjs-jquery-metadata libjs-jquery-tablesorter libjs-jquery-ui libjs-moment python3-asn1crypto python3-cffi-backend python3-chardet python3-cheetah
  python3-cherrypy3 python3-configobj python3-cryptography python3-feedparser python3-gntp python3-idna python3-jaraco.functools python3-more-itertools
  python3-portend python3-sabyenc python3-six python3-tempora python3-tz sabnzbdplus
0 upgraded, 23 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2525 kB of archives.
After this operation, 15.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package libjs-bootstrap.
(Reading database ... 61164 files and directories currently installed.)
Preparing to unpack .../00-libjs-bootstrap_3.3.7+dfsg-2_all.deb ...
Unpacking libjs-bootstrap (3.3.7+dfsg-2) ...
Selecting previously unselected package libjs-jquery-metadata.
Preparing to unpack .../01-libjs-jquery-metadata_12-1_all.deb ...
Unpacking libjs-jquery-metadata (12-1) ...
Selecting previously unselected package libjs-jquery-tablesorter.
Preparing to unpack .../02-libjs-jquery-tablesorter_1%3a2.29.5+dfsg1-1_all.deb ...
Unpacking libjs-jquery-tablesorter (1:2.29.5+dfsg1-1) ...
Selecting previously unselected package libjs-jquery-ui.
Preparing to unpack .../03-libjs-jquery-ui_1.12.1+dfsg-5_all.deb ...
Unpacking libjs-jquery-ui (1.12.1+dfsg-5) ...
Selecting previously unselected package libjs-moment.
Preparing to unpack .../04-libjs-moment_2.20.1+ds-1_all.deb ...
Unpacking libjs-moment (2.20.1+ds-1) ...
Selecting previously unselected package python3-asn1crypto.
Preparing to unpack .../05-python3-asn1crypto_0.24.0-1_all.deb ...
Unpacking python3-asn1crypto (0.24.0-1) ...
Selecting previously unselected package python3-cffi-backend.
Preparing to unpack .../06-python3-cffi-backend_1.11.5-1_arm64.deb ...
Unpacking python3-cffi-backend (1.11.5-1) ...
Selecting previously unselected package python3-chardet.
Preparing to unpack .../07-python3-chardet_3.0.4-1_all.deb ...
Unpacking python3-chardet (3.0.4-1) ...
Selecting previously unselected package python3-cheetah.
Preparing to unpack .../08-python3-cheetah_3.2.4-0ubuntu1~jcfp1_arm64.deb ...
Unpacking python3-cheetah (3.2.4-0ubuntu1~jcfp1) ...
Selecting previously unselected package python3-six.
Preparing to unpack .../09-python3-six_1.11.0-2_all.deb ...
Unpacking python3-six (1.11.0-2) ...
Selecting previously unselected package python3-cherrypy3.
Preparing to unpack .../10-python3-cherrypy3_8.9.1-2_all.deb ...
Unpacking python3-cherrypy3 (8.9.1-2) ...
Selecting previously unselected package python3-configobj.
Preparing to unpack .../11-python3-configobj_5.0.6-2_all.deb ...
Unpacking python3-configobj (5.0.6-2) ...
Selecting previously unselected package python3-idna.
Preparing to unpack .../12-python3-idna_2.6-1_all.deb ...
Unpacking python3-idna (2.6-1) ...
Selecting previously unselected package python3-cryptography.
Preparing to unpack .../13-python3-cryptography_2.1.4-1ubuntu1.3_arm64.deb ...
Unpacking python3-cryptography (2.1.4-1ubuntu1.3) ...
Selecting previously unselected package python3-feedparser.
Preparing to unpack .../14-python3-feedparser_5.2.1-1_all.deb ...
Unpacking python3-feedparser (5.2.1-1) ...
Selecting previously unselected package python3-gntp.
Preparing to unpack .../15-python3-gntp_1.0.3-0ubuntu1~jcfp1_all.deb ...
Unpacking python3-gntp (1.0.3-0ubuntu1~jcfp1) ...
Selecting previously unselected package python3-more-itertools.
Preparing to unpack .../16-python3-more-itertools_3.2.0-2_all.deb ...
Unpacking python3-more-itertools (3.2.0-2) ...
Selecting previously unselected package python3-jaraco.functools.
Preparing to unpack .../17-python3-jaraco.functools_2.0-0ubuntu1~jcfp1_all.deb ...
Unpacking python3-jaraco.functools (2.0-0ubuntu1~jcfp1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../18-python3-tz_2018.3-2_all.deb ...
Unpacking python3-tz (2018.3-2) ...
Selecting previously unselected package python3-tempora.
Preparing to unpack .../19-python3-tempora_1.14.1-0ubuntu1~jcfp1.1_all.deb ...
Unpacking python3-tempora (1.14.1-0ubuntu1~jcfp1.1) ...
Selecting previously unselected package python3-portend.
Preparing to unpack .../20-python3-portend_2.5-0ubuntu1~jcfp1_all.deb ...
Unpacking python3-portend (2.5-0ubuntu1~jcfp1) ...
Selecting previously unselected package python3-sabyenc.
Preparing to unpack .../21-python3-sabyenc_4.0.1-0ubuntu1~jcfp1_arm64.deb ...
Unpacking python3-sabyenc (4.0.1-0ubuntu1~jcfp1) ...
Selecting previously unselected package sabnzbdplus.
Preparing to unpack .../22-sabnzbdplus_3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3_all.deb ...
Unpacking sabnzbdplus (3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3) ...
Setting up libjs-moment (2.20.1+ds-1) ...
Setting up python3-cffi-backend (1.11.5-1) ...
Setting up python3-sabyenc (4.0.1-0ubuntu1~jcfp1) ...
Setting up python3-idna (2.6-1) ...
Setting up python3-six (1.11.0-2) ...
Setting up python3-cherrypy3 (8.9.1-2) ...
Setting up python3-more-itertools (3.2.0-2) ...
Setting up python3-asn1crypto (0.24.0-1) ...
Setting up python3-feedparser (5.2.1-1) ...
Setting up python3-jaraco.functools (2.0-0ubuntu1~jcfp1) ...
Setting up python3-chardet (3.0.4-1) ...
Setting up python3-gntp (1.0.3-0ubuntu1~jcfp1) ...
Setting up libjs-jquery-ui (1.12.1+dfsg-5) ...
Setting up python3-cheetah (3.2.4-0ubuntu1~jcfp1) ...
Setting up libjs-bootstrap (3.3.7+dfsg-2) ...
Setting up python3-configobj (5.0.6-2) ...
Setting up libjs-jquery-metadata (12-1) ...
Setting up python3-tz (2018.3-2) ...
Setting up python3-cryptography (2.1.4-1ubuntu1.3) ...
Setting up libjs-jquery-tablesorter (1:2.29.5+dfsg1-1) ...
Setting up python3-tempora (1.14.1-0ubuntu1~jcfp1.1) ...
Setting up python3-portend (2.5-0ubuntu1~jcfp1) ...
Setting up sabnzbdplus (3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3) ...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.29) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
sander@nanopineo2:~$ ll /etc/default/sa*
ls: cannot access '/etc/default/sa*': No such file or directory
sander@nanopineo2:~$ 


```

**Comment by thezoggy** [comment]
looking at 2.3.9 build log (picked a random ubuntu distro),
https://launchpadlibrarian.net/425235360/buildlog_ubuntu-cosmic-amd64.sabnzbdplus_2.3.9-0ubuntu1~jcfp1~18.10_BUILDING.txt.gz
I see the file is listed in his output:
> -rw-r--r-- root/root       718 2016-04-02 19:34 ./etc/default/sabnzbdplus

now for the ppa you are trying to use..
> PRIVATE PPA. DO NOT USE.
https://launchpadlibrarian.net/445089441/buildlog_ubuntu-bionic-amd64.sabnzbdplus_3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp3_BUILDING.txt.gz
but looking in it's build log I do see the file does exist.. but is same file as the original build..
> -rw-r--r-- root/root       718 2016-04-02 19:34 ./etc/default/sabnzbdplus

might be best to hit up ppa owner directly via ppa or forums (I dont think he looks at GHI)

**Comment by jcfp** [comment]
> De-installed sabnzbdplus, removed /etc/default/sabnzbdplus and /etc/init.d/sabnzbdplus, installed sabnzbdplus, thus the ppa-3.0.0 version:
> I can start it manually
> But /etc/default/sabnzbdplus is not there. And thus
> 
> ```
> 
> sander@nanopineo2:~$ sudo service sabnzbdplus start
> Failed to start sabnzbdplus.service: Unit sabnzbdplus.service not found.
> ```
> 
> @jcfp is the alfa-ppa missing some settings / files?

Nope, the init.d and its config file are there:
```
$ dpkg -L sabnzbdplus | grep -- ^/etc
/etc
/etc/default
/etc/default/sabnzbdplus
/etc/init.d
/etc/init.d/sabnzbdplus
```

Unless you purge the package on uninstall though, system-wide configuration files (usually anything the package installed into /etc) and any modifications you made to these will survive. Manual deletion after uninstall (apparently) included.

I am surprised about the whole ascii thing, would have expected utf8 as a default everywhere. System upgrade issue maybe?

That your system is arm64 doesn't matter, the sabnzbdplus package is architecture-independent so anyone installing it is served the exact same deb file from the repo.

**Comment by jcfp** [comment]
@sanderjo anything set for LANG in /etc/default/locale ?

**Comment by sanderjo** [comment]
```
sander@nanopineo2:~$ cat /etc/default/locale
#  File generated by update-locale
LANG=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LANGUAGE=en_US.UTF-8

sander@nanopineo2:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=en_US.UTF-8
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````

**Comment by sanderjo** [comment]
On my ARM64, I created a Ubuntu 18.04 docker, installed sabznbdplus-ppa-alfa, and the result is good.

However, during the install of sabnzbdplus, I got this peculiar interaction about timezone. I don't know if that is relevant and/or good.

`
Setting up python3-sabyenc (4.0.1-0ubuntu1~jcfp1) ...
Setting up geoip-database (20180315-1) ...
Setting up libjson-c3:arm64 (0.12.1-1.3) ...
Setting up tzdata (2019c-0ubuntu0.18.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/aarch64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa   3. Antarctica  5. Arctic  7. Atlantic  9. Indian    11. SystemV  13. Etc
  2. America  4. Australia   6. Asia    8. Europe    10. Pacific  12. US
Geographic area: 8

Please select the city or region corresponding to your time zone.

  1. Amsterdam  8. Bratislava   15. Dublin       22. Kaliningrad  29. Madrid     36. Oslo       43. San_Marino  50. Tallinn    57. Vienna
  2. Andorra    9. Brussels     16. Gibraltar    23. Kiev         30. Malta      37. Paris      44. Sarajevo    51. Tirane     58. Vilnius
  3. Astrakhan  10. Bucharest   17. Guernsey     24. Kirov        31. Mariehamn  38. Podgorica  45. Saratov     52. Tiraspol   59. Volgograd
  4. Athens     11. Budapest    18. Helsinki     25. Lisbon       32. Minsk      39. Prague     46. Simferopol  53. Ulyanovsk  60. Warsaw
  5. Belfast    12. Busingen    19. Isle_of_Man  26. Ljubljana    33. Monaco     40. Riga       47. Skopje      54. Uzhgorod   61. Zagreb
  6. Belgrade   13. Chisinau    20. Istanbul     27. London       34. Moscow     41. Rome       48. Sofia       55. Vaduz      62. Zaporozhye
  7. Berlin     14. Copenhagen  21. Jersey       28. Luxembourg   35. Nicosia    42. Samara     49. Stockholm   56. Vatican    63. Zurich
Time zone: 1


Current default time zone: 'Europe/Amsterdam'
Local time is now:      Wed Oct  9 10:24:16 CEST 2019.
Universal Time is now:  Wed Oct  9 08:24:16 UTC 2019.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up python3-webob (1:1.7.3-2fakesync1) ...
Setting up libcap2:arm64 (1:2.25-1.2) ...
Setting up python3-simplejson (3.13.2-1) ...
Setting up python3-idna (2.6-1) ...
`

**Comment by thezoggy** [comment]
hehe yeah, we load the user env locale to set preferred encoding. so yeah you just have badly setup env

**Comment by sanderjo** [comment]
In the docker, solved the traceback with this:

```
root@564d73264e4c:/# locale-gen en_US.UTF-8
root@564d73264e4c:/# update-locale LANG=en_US.UTF-8
root@564d73264e4c:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```
Service works too, including webservice

```
root@564d73264e4c:~# service sabnzbdplus start
 * Starting SABnzbd+ binary newsgrabber                                                                                                               [ OK ]
root@564d73264e4c:~# ps -ef | grep -i sabnzb
root      6426     1  7 10:59 ?        00:00:00 /usr/bin/python3 -OO /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
root      6459  6330  0 10:59 pts/0    00:00:00 grep --color=auto -i sabnzb
root@564d73264e4c:~#
```

**Comment by jcfp** [comment]
For the service, I could try to enforce the encoding by exporting PYTHONIOENCODING=utf-8 in the init.d script. The risk of that breaking something else seems low.

**Comment by sanderjo** [comment]
> For the service, I could try to enforce the encoding by exporting PYTHONIOENCODING=utf-8 in the init.d script. The risk of that breaking something else seems low.

I'm surprised that the LANG setting can result in the Traceback when running from CLI. So maybe sort that out first? Otherwise sab-cli cannot run, and sab-service can ...

**Comment by jcfp** [comment]
I think it's only environments such as docker that are so bare-bones that they don't even set a proper encoding. Most programs use the locale settings in one way or the other, for encoding, default language, and so on. Even the init script has loaded LANG, because without that unrar couldn't handle certain stuff - at least back then.

Anyway: new test version uploaded, the only change is setting the python io encoding in the init script.

**Comment by sanderjo** [comment]
@jcfp 

On plain Ubuntu 18.04 AMD64, no docker:
The git version
`sander@brixit:~/git/sabnzbd$ env LANG=POSIX ./SABnzbd.py`
is OK.

The PPA version
`env LANG=POSIX sabnzbdplus`
results in the traceback

**Comment by jcfp** [comment]
These two instances using the same config/queue etc?

**Comment by sanderjo** [comment]
> These two instances using the same config/queue etc?

Yes. 
100% proof: in git-version I started a download (via webgui), then CTRL-C, then started the ppa-version, it continued downloading (visible from CLI), and webgui access resulted in the Traceback

Weird

**Comment by sanderjo** [comment]
@jcfp : could you check on your own system that `env LANG=POSIX sabnzbdplus` results in a Traceback, and that `env LANG=POSIX <git-version-of-SAB>` works OK?

**Comment by sanderjo** [comment]
I think there are two things going on:

1. PPA not installing /etc/default/sabnzbdplus
2. certain LANG settings (for example: LANG=POSIX) leading to a Traceback

Ad 1: I tried to install the regular PPA, and that showed the same problem. So ... hosed up system? I will do a fresh Ubuntu 18.04 install. I expect the problem to go disappear.

Ad 2: @jcfp I hope you can confirm that behaviour.

**Comment by thezoggy** [comment]
the C/POSIX lang is so old.. yes we prob dont want to even try to work with it. as anything utf8 wont work with it. last time i've seen posix used was on a old solaris box a few decades ago :x

**Comment by sanderjo** [comment]
> last time i've seen posix used was on a old solaris box a few decades ago :x

The last time I've seen POSIX used was ... 1 second ago: fresh Ubuntu docker image.

**Comment by jcfp** [comment]
1. The not installing /etc/default/sabnzbdplus is a feature (of debian's handling of configuration files), not a bug. If you apt-get purge sabnzbdplus, followed by a pkg reinstall they should be back. Otherwise restore the files by hand, both are available from https://salsa.debian.org/python-team/applications/sabnzbdplus/tree/debian/master/debian

2. The traceback seems to be introduced by packaging changes in the Glitter template, will have to narrow it down later but that is a bug. Not that LANG=POSIX is any good, as it knows only ascii, but the result of running a packaged sab shouldn't be worse.

>  last time i've seen posix used was on a old solaris box a few decades ago
The only legit use I know for LANG=C is to eliminate interference from weird locale settings. Docker could at least have gone for C.UTF-8...

**Comment by thezoggy** [comment]
Did you create the dockerfile?
https://daten-und-bass.io/blog/fixing-missing-locale-setting-in-ubuntu-docker-image/

**Comment by sanderjo** [comment]
> Did you create the dockerfile?
> https://daten-und-bass.io/blog/fixing-missing-locale-setting-in-ubuntu-docker-image/

No; plain Ubuntu docker image. 
And yes I know how to solve in docker, but that is not my point nor question. My point is: SAB gives a Traceback, and is unaccessible with certain OS settings ... which is ... bad. SAB should resilient against that, or refuse to start up
I use Docker just to prove that point. To rule out I have a crappy legacy setup.

**Comment by sanderjo** [comment]
> 1. If you apt-get purge sabnzbdplus, followed by a pkg reinstall they should be back.

That worked!

```
sudo apt-get purge sabnzbdplus
sudo add-apt-repository ppa:jcfp/private
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install sabnzbdplus

```
```
sander@nanopineo2:~$ ls -al /etc/default/sabnzbdplus
-rw-r--r-- 1 root root 718 Apr  2  2016 /etc/default/sabnzbdplus
```
and the uptodate version (4):
/var/log/dpkg.log:311:2019-10-10 12:12:22 configure sabnzbdplus:all 3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp4 <none>
/var/log/dpkg.log:312:2019-10-10 12:12:22 status unpacked sabnzbdplus:all 3.0.0~alpha0~git20191001.1300-0ubuntu1~jcfp4


... but accessing the webgui still results in

![image](https://user-images.githubusercontent.com/1273502/66569201-5618ba80-eb6b-11e9-96a5-c8291ed7798b.png)

**Comment by sanderjo** [comment]
> Now it prob should just exit after giving the error/log instead of trying to move past it

I think so too. With, on POSIX, a clear instruction what is wrong (LANG setting), and hints how to solve it at OS level / the way to start SABnzbd-py3.

Full fledged Ubuntu 
```
sander@brixit:~$ printenv | grep LANG
LANG=en_US.UTF-8
```

MacOS:
```
server:~ sander$ printenv | grep LANG
LANG=en_US.UTF-8
```


Ubuntu docker:
```
$ sudo docker run -it ubuntu:18.04 /bin/bash
root@ca74c9d72fdc:/# printenv | grep LANG
root@ca74c9d72fdc:/# printenv
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
HOSTNAME=ca74c9d72fdc
PWD=/
HOME=/root
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
root@ca74c9d72fdc:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@ca74c9d72fdc:/# locale -a
C
C.UTF-8
POSIX
root@ca74c9d72fdc:/#
```

**Comment by sanderjo** [comment]
Update:

I did a fresh Ubuntu install, and still problems with sabnzbdplus and SABnzbd.py

Long story short:
With 
`env LC_ALL=C.UTF-8 sabnzbdplus`
no more Traceback.
And to be sure
`env LANG=C.UTF-8 LC_ALL=C.UTF-8 sabnzbdplus`
is probably best / catch-all.

Now two options:
1. close this issue; workaround found
2. keep issue open, implement protection / exit in SAB, then close this issue


**Long**

```
$ locale
LANG=C.UTF-8
LANGUAGE=C.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
LANG is set with UTF-8, but LC_ALL is not, so ... set that.

```
sander@nanopineo2:~$ python3 -c "import locale; print(locale.getpreferredencoding())"
ANSI_X3.4-1968
sander@nanopineo2:~$ env LC_ALL=C.UTF-8 python3 -c "import locale; print(locale.getpreferredencoding())"
UTF-8
```
Oh, and yes:
```
$ locale -a
C
C.UTF-8
POSIX
en_US.utf8
```
So C.UTF-8 is there, and I choose that over en_US.utf8 to have to country/language orientation ... :-)

**Comment by sanderjo** [comment]
PS:

@jcfp alpha4 runs perfectly as a service
