### ISSUE TITLE
Folder failed moving due to .nfs files

### ISSUE THREAD

**Issue by zejar** [sabnzbd/sabnzbd#1339]
It seems like SABnzbd doesn't ignore .nfs files during cleanup and unpacking of files.
Would it be possible to ignore these .nfs files?

One of the example errors:
```Failed moving /nzbdownloads/incomplete/Movie.Name.Year/.nfs00000000000188e1000031a7 to /nzbdownloads/complete-tv/_UNPACK_Movie.Name.Year/.nfs00000000000188e1000031a7```

SABnzbd version: 2.3.9
Running in a linuxserver/sabnzbd Docker container

**Comment by Safihre** [comment]
Cleanup is performed after moving to the final directory. What are these `nfs` files? We've never heard of these files before, if they were common I'd expected lots of people to report problems with them?

**Comment by zejar** [comment]
Those ```nfs``` files are being created by the underlaying filesystem when an open file gets deleted (or moved as in this case). It's also known as 'silly rename'. NZBGet has fixed this issue in 2015 (https://forum.nzbget.net/viewtopic.php?t=1838).
Some more info about these NFS files: http://nfs.sourceforge.net/#faq_d2

**Comment by Safihre** [comment]
Very strange that nobody reported it for so many years. Given the high number of SABnzbd users. Could there be something specific about your specific setup causing this?
Is any other program active scanning this directory?

**Comment by zejar** [comment]
I'm running a bunch of Docker containers (SAB, Radarr, Sonarr, rclone mount) but no app should be actively scanning the incomplete folder. 
Radarr and Sonarr only have access to the ```/nzbdownloads/complete-movies/``` and ```/nzbdownloads/complete-tv/``` folders. No apps aside from SabNZBD have access to the ```/nzbdownloads/incomplete``` directory.
The host is a virtual machine (qemu) running Docker 19.03.3 on Debian 10.1. 
The file server is also running Debian 10.1. I'm using NFS Version 4.2 to setup the share.

**Comment by thezoggy** [comment]
It's most likely local to your setup.

are your incomplete + complete folders on the same file system?
share output of: `df -T`

```
.nfs 
File created by Network File System, a protocol that allows files to be accessed over a network; contains either a temporary copy of a file that is opened by an NFS process, or a copy of a file that was deleted while still open by an NFS process; enables the client and file server processes to communicate file information.

NOTE: NFS files rarely have the exact ".nfs" file extension since NFS appends other characters to the end of the extension.
```

**Comment by thezoggy** [comment]
also: https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=123962105

**Comment by thezoggy** [comment]
Now why his nas/whatever is touching those files is outside our scope (maybe indexing? - which ideally he should fix).

@Safihre what zejar is wanting is to just add it to the list of files to ignore so it stops breaking the cleanup. so we would just add .nfs to:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L449

**Comment by zejar** [comment]
My incomplete and complete folders are indeed on the same filesystem. 
```
root@a4bab773649c:/# df -T
Filesystem                                                Type     1K-blocks       Used  Available Use% Mounted on
overlay                                                   overlay   24389456    8201868   14925612  36% /
tmpfs                                                     tmpfs        65536          0      65536   0% /dev
tmpfs                                                     tmpfs      8213664          0    8213664   0% /sys/fs/cgroup
/dev/mapper/media--vg-root                                ext4      24389456    8201868   14925612  36% /downloads
10.111.12.2:/bigtank/nfs/d-media/docker/sabnzbd/config    nfs4    7323774976 2494024704 4829750272  35% /config
10.111.12.2:/bigtank/nfs/d-media/docker/sabnzbd/downloads nfs4    7323774976 2494024704 4829750272  35% /nzbdownloads
shm                                                       tmpfs        65536          0      65536   0% /dev/shm
tmpfs                                                     tmpfs      8213664          0    8213664   0% /proc/acpi
tmpfs                                                     tmpfs      8213664          0    8213664   0% /sys/firmware
```

I'm using a quite basic setup on the NFS server so I'm not sure why I have this problem but others apparently not.
If .nfsXXX files could be added to the ignore list that would be great.

**Comment by thezoggy** [comment]
you should check iotop and see what process is creating the .nfs files then...
