### ISSUE TITLE
ImportError: DLL load failed while importing win32api

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#1340]
SAB fails to start with import error with the following configuration:
* Windows 10
* Python 3.8
* pywin32 225

**Comment by Safihre** [comment]
Maybe it's better to wait for `pywin32` to fix the issue? It seems they just did yesterday: https://github.com/mhammond/pywin32/commit/71afa71e11e6631be611ca5cb57cda526b5e91ab

**Comment by thezoggy** [comment]
was gonna just say, 3.8 broke a few things. wait for modules to update to deal with it.  as sab 3.x is in alpha there is no sense for us to add logic to deal with it on our end (unless we wanted to restrict 3.5-3.7 / set requirements.txt accordingly)

**Comment by labrys** [comment]
The workaround in #1341 imports `pywintypes` before `win32api`.  As `pywintypes` was already being imported, this workaround is low impact.  Without it you would need to pin an exclusion for pywin32 225 as it currently breaks sab.

**Comment by thezoggy** [comment]
pywin32 225 and py3.8 breaks on windows. which is extremely small set of people that run sab (aka, they run from source + install the dep themselves). those people can just update pywin32 to latest and be good now. now if its really worth adding some logic to warn if py3.8+ and pywin226=<226.. maybe

**Comment by labrys** [comment]
Considering pywin32 226 is broken in virtual environments I say pin the dependency to >=pywin227 and call it done.

**Comment by Safihre** [comment]
Done 👍 Thanks for making us aware of this!
