### ISSUE TITLE
quota not obeyed or incorrectly reported. 

### ISSUE THREAD

**Issue by tehniemer** [sabnzbd/sabnzbd#1342]
I'm seeing an issue where the quota is set, but doesn't seem to be obeyed or data is being reported incorrectly. 

This is what I see as the remaining monthly quota in the queue.
![image](https://user-images.githubusercontent.com/11021632/68963841-86bcc700-079d-11ea-98b6-06a80613142a.png)

And this is what is reported from history.
![image](https://user-images.githubusercontent.com/11021632/68963935-b66bcf00-079d-11ea-95a9-6544967fe0d2.png)

**Comment by thezoggy** [comment]
what version of sab? config/logs? etc

quota can have different periods and when to reset. sure monthly but maybe reset on the 20th (billing cycle). or maybe reset weekly.. etc etc.

**Comment by tehniemer** [comment]
Logs attached, version 2.3.9, quota resets on the first of the month

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/3852970/sabnzbd.log)

**Comment by thezoggy** [comment]
looks like your logging level is set for info, if you change it to debug (then restart) it will put log messages about your quota which will make it much easier to debug.

Status (wrench icon) > Status tab > Logging dropdown, select +Debug

but lets look at the data we do have, per the conifg values:
```
quota_period = m
quota_size = 500G
quota_resume = 1
quota_day = 1
```
so should reset on first day of the month (which happens at start of the day)

which you can see the schedule for the check to happen at 0000 when your sab booted.
but 
```
2019-11-11 07:16:57,412::INFO::[scheduler:188] Setting schedule for quota check daily at 0:0
```
but clearly your quota of 500G is exhausted and quota hasn't been reset its being triggered to pause:
```
2019-11-15 05:59:58,748::WARNING::[bpsmeter:249] Quota spent, pausing downloading
```

now if you set your quota in the middle of the period (lets say today) then it is going use the current months data and you really wont see it reset until next month. 

switch your logging to debug and restart and lets see what your logs say

**Comment by tehniemer** [comment]
Here's the updated debug logs, thanks for looking into this. 
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/3854417/sabnzbd.log)

**Comment by thezoggy** [comment]
Thanks for the logs, you can see that sab is loading `totals10.sab` for your quota data:
```
2019-11-16 10:27:19,509::DEBUG::[__init__:982] [sabnzbd.bpsmeter.read] Loading data for totals10.sab from /config/admin/totals10.sab
2019-11-16 10:27:19,509::DEBUG::[bpsmeter:180] Read quota q=5.36870912e+11 l=71692023516.0 reset=1575180000.0
```

which goes with:
https://github.com/sabnzbd/sabnzbd/blob/2.3.x/sabnzbd/bpsmeter.py#L179

`1575180000` = epoch time for Dec 1st 2019
500G = 5e+11 bytes.. so that looks fine
and 71692023516 bytes would be 71.69G left

so it looks like your quota isnt reached?

Did you by any chance run the python3 version of sab then switched to python2 version?
@Safihre we prob should not being using the same `BYTES_FILE_NAME ` for py2 vs py3 to prevent pickle/data differences?

Can you share your totals10.sab file?

**Comment by tehniemer** [comment]
So why would it be reporting over 500GB for the month in history? That's the part that has me confused. 
I don't think I changed from python3 to python2, I've been using the linuxserver docker image the whole time, but I did modify the dockerfile to keep python-pip installed. 

Here's the file requested with .txt appended so it would upload
[totals10.sab.txt](https://github.com/sabnzbd/sabnzbd/files/3855146/totals10.sab.txt)

**Comment by thezoggy** [comment]
need to re-check if this is outstanding in v3

**Comment by Safihre** [comment]
![image](https://user-images.githubusercontent.com/5703454/84563506-556c9f80-ad5c-11ea-86f4-18ad7fa9715a.png)
I could not reproduce this.

What can happen: if your totals-file is somehow damaged or empty, it will re-calculate the statistics based on the history-database. Which doesn't contain the actually downloaded bytes, but the reported sizes per job.
