### ISSUE TITLE
2.3.9 not working on osx catalina

### ISSUE THREAD

**Issue by createconsume** [sabnzbd/sabnzbd#1343]
Getting this error on launch and when I try to enter config.
``Traceback (most recent call last):
  File "cherrypy/_cprequest.pyc", line 670, in respond
  File "cherrypy/lib/encoding.pyc", line 220, in __call__
  File "cherrypy/_cpdispatch.pyc", line 60, in __call__
  File "sabnzbd/interface.pyc", line 468, in tapi
  File "sabnzbd/api.pyc", line 109, in api_handler
  File "sabnzbd/api.pyc", line 475, in _api_fullstatus
  File "sabnzbd/api.pyc", line 1195, in build_status
  File "sabnzbd/decorators.pyc", line 48, in call_func
  File "sabnzbd/nzbqueue.pyc", line 172, in scan_jobs
  File "sabnzbd/misc.pyc", line 141, in globber_full
OSError: [Errno 1] Operation not permitted: '/Users/xxxxx/Downloads/incomplete'``

**Comment by createconsume** [comment]
FIXED THIS!

Ok just so everyone knows...if your running catalina you have to go into your privacy settings and add SAB to the "Full Disk Access" area..

**Comment by Cpuroast** [comment]
Or Files and Folders and allow Downloads folder

**Comment by sanderjo** [comment]
> Ok just so everyone knows...if your running catalina you have to go into your privacy settings and add SAB to the "Full Disk Access" area..

Ah ... so on Catalina Apple has restricted the disk access; no more full disk access for any application. If so: wise decision by Apple. Because: why would Application X (a text editor, or a mail program, or web browser, or some handy tool you downloaded from Internet) have access to all your personal files?

The important error message is the last line of your first post:
```
OSError: [Errno 1] Operation not permitted: '/Users/xxxxx/Downloads/incomplete'
```

**Comment by Cpuroast** [comment]
Indeed, I think there's an API in Catalina for applications to request access to certain folders prompting the user.

If that isn't used, the user has to manually grant access in System Preferences, Security and Privacy, Privacy tab.

**Comment by sanderjo** [comment]
Quote about Catalina: "TCC has been expanded to the Documents, Desktop, and **Download folders**, Trash, iCloud Drive/other cloud storage providers, as well as external, removable, and network drives." with TCC = “Transparency, Consent, and Control”

**Comment by Safihre** [comment]
@Cpuroast Do you maybe have more technical details or an idea how we could implement this for SAB to request control?

**Comment by Cpuroast** [comment]
https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources
Under "Files and Folders"

This is a start, supposedly it's supposed to automatically prompt the user when the app tries to access the folder in question, but obviously it didn't for some reason.

**Comment by Safihre** [comment]
The new binary seens to work fine with Cataline.
