### ISSUE TITLE
duplicate jobs on py3

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1345]
So I keep noticing recently that with discard duplicate nzb, but allow duplicate episode, I'm getting jobs with numbers at the end, which I'm not expecting with duplicate rejection.
.41 is the highest i've seen, with x.x.x.x.x being the deepest I've seen.
Opensuse tumbleweed, py3.7, develop branch

I've written a script to clean up the queue and the temp downloads path but it keeps happening and I'm unclear why. I do see "import from <tempdownloadlocation>/something in the logs, so I'm not sure if its somehow cycling through content repeatedly or something.

I even tried:
copy all nzb and nzb.gz to a temp folder.
Delete contents of temp download folder.
Copy nzb/nzb.gz to the import folder.
It started up almost immediately.

I didn't see anything like this in the issues. How might I troubleshoot this?

**Comment by mgaulton** [comment]
I should note, this is across all categories of jobs in the queue.

**Comment by Safihre** [comment]
You don't happen to have mixed up the NZB-backup directory and the Watch Directory?

**Comment by mgaulton** [comment]
Its been basically the same config for the past couple years, I haven't
made any changes but i'll verify.

**Comment by mgaulton** [comment]
Negative.
dirscan_dir = /home/import2
nzb_backup_dir = /home/nzbbackup

**Comment by thezoggy** [comment]
It's probably what is feeding the nzbs to Sab that is the issue...

**Comment by thezoggy** [comment]
How are you giving Sab the nzb? API/manually/via 3rd party app?

**Comment by mgaulton** [comment]
Books by lazylibrarianSickchill and couch potato tooSent from my Samsung Galaxy smartphone.
-------- Original message --------From: thezoggy <notifications@github.com> Date: 2019-11-28  2:58 a.m.  (GMT-05:00) To: sabnzbd/sabnzbd <sabnzbd@noreply.github.com> Cc: mgaulton <markgaultonsecurity@gmail.com>, Author <author@noreply.github.com> Subject: Re: [sabnzbd/sabnzbd] duplicate jobs on py3 (#1345) How are you giving Sab the nzb? API/manually/via 3rd party app?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sabnzbd/sabnzbd/issues/1345?email_source=notifications\u0026email_token=ABEJRXX4LEWQC2N62PEMK63QV522VA5CNFSM4JSM3TU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFLYAYI#issuecomment-559382625",
"url": "https://github.com/sabnzbd/sabnzbd/issues/1345?email_source=notifications\u0026email_token=ABEJRXX4LEWQC2N62PEMK63QV522VA5CNFSM4JSM3TU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFLYAYI#issuecomment-559382625",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thezoggy** [comment]
now do you have the apps removing the completed files from your sab history? and do you have sab set to prune/not keep history?

**Comment by mgaulton** [comment]
If they can, they are set to do that, I believe but I keep all history as I
thought that was required for dupe checking.

**Comment by puzzledsab** [comment]
Maybe they get locked so that when Sab tries to move/delete them after import it fails, and then it later imports them again because it thinks they are new? Does it happen for any kind of automatic source and both automatic and manual adding of nzbs?

**Comment by mgaulton** [comment]
I rarely add manual jobs, sickchill and couchpotato do most of it.

**Comment by mgaulton** [comment]
I think i figured this one out. I had a script parsing out certain categories to move aside as future jobs due to space but it got into a loop of "move it there, oh wait, its current, move it back" 
or at least, that's the only thing that seems to make sense.
Sorry for the hassle.
