### ISSUE TITLE
Sab "reliably" fails to fully download a NZB that NZBget downloads perfectly.

### ISSUE THREAD

**Issue by reidjr** [sabnzbd/sabnzbd#1347]
Running on ubuntu: sabnzbdplus                                  2.3.9-0ubuntu1~jcfp1~19.10

I have recently had a number of NZBs that fail with half the blocks missing, although all rar files are downloaded. I assumed just missing articles from server.

I have a block server for backup (priority 1) , but this is never used for the files with missing articles, so I assumed that was the bug ( It should try the backup server for missing articles ?)

I made a couple of test NZBs of single rars that I have tried to download today, which repeatedly download 17 out of 45 blocks with Sab. I have just installed and configured nzbget,  the same NZBs all download completely from same servers. Something is wrong here.

Could be duplicate of other issues such as #1258 but I cant see any resolution.

**Comment by thezoggy** [comment]
cant really do much without example nzb / logs / etc

**Comment by reidjr** [comment]
[10outof46.log](https://github.com/sabnzbd/sabnzbd/files/3908004/10outof46.log)


[10outof46nzb.txt](https://github.com/sabnzbd/sabnzbd/files/3908008/10outof46nzb.txt)


Same NZB used in both sab and NZBGET.

**Comment by thezoggy** [comment]
for starters i see your using multiple free xsusenet accounts. you really shouldnt use those as your main.. you should also set those as optional and retention to something like 9 days. since they are purposely limited.

**Comment by thezoggy** [comment]
now on why you dont see your 2nd provider used.. is because your first provider says it has it
```
2019-11-30 16:29:49,189::DEBUG::[downloader:709] Article <part74of82.5&sLQDksEAqgtBusp&CS@gfunk92.local> is present
```
but then when it goes to actually grab it
```
2019-11-30 16:32:59,718::INFO::[assembler:177] <Article: article=part74of82.5&sLQDksEAqgtBusp&CS@gfunk92.local, bytes=660956, partnum=74, art_id=None> missing
```
which then results in the incomplete files... 

I've personally seen xsusenet free accounts say it has files that it doesnt when you dont set the retention on your side. Because the 'free' accounts retention while limited are oddly enforced on the server side as the server actually does HAVE the data (if you paid for the access) but the free accounts just get 0 data returned when they ask for something.. thus a CHECKj returns one thing and a GET gets another...  set your retention value for the free account correctly and try again.

**Comment by reidjr** [comment]
Thanks for looking at this, and your comments make complete sense. However the fact remains that I can download from the same servers the full file with NZBget. The backup block server is not used in either case, so its not infills from the block server. 
I set the free up as my main because I do relatively little GB/month, so free + block infill occasionally make sense for me.
The free accounts used to be limited to 9 days, but the retention was ramped up a year or so ago.

**Comment by Safihre** [comment]
Can you disable 'Check before download'? And try again.

**Comment by reidjr** [comment]
Without 'check before download', it completes r05, but par2 gives:

`Target: "2163a78d7253485398ca9d13b9c79daa.r05" - damaged. Found 12 of 46 data blocks.`

**Comment by puzzledsab** [comment]
I looked up 2163a78d7253485398ca9d13b9c79daa on nzbindex.com and 2163a78d7253485398ca9d13b9c79daa.r05 downloades and verifies successfully for me using the develop branch.
