### ISSUE TITLE
Drag & Drop RAR5 archive to Queue on Synology NAS results in BadRarFile: Corrupt file - CRC check failed

### ISSUE THREAD

**Issue by PeterCodar** [sabnzbd/sabnzbd#1348]
I have attached a RAR file (_just remove the additional .zip extension, it's just there to allow it as an attachment here to this issue_).

According to my 7Zip archive manager, it is a RAR5 archive.
If I drag & drop this rar archive to my SABNZBD waiting queue on my Synology NAS, I get this error:

```
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/dirscanner.py", line 134, in ProcessArchiveFile
    data = zf.read(name)
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 772, in read
    return f.read()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 2028, in read
    self._check()
  File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 2045, in _check
    self._inf.filename, exp, final))
BadRarFile: Corrupt file - CRC check failed: Gamestar.-.2019-12{{MeRryChrisTmaSFroMHoU}}.nzb - exp=3928222141 got=235545681
[Jahresarchiv 2019.rar.zip](https://github.com/sabnzbd/sabnzbd/files/3916040/Jahresarchiv.2019.rar.zip)


```

If I unpack this archive locally on my PC (with 7Zip 19.02 x64) and add the NZBs by drag & drop, they work fine.

Could please someone have a look why rar archives can't be unpacked on a Synology NAS?

**Comment by sanderjo** [comment]
What if you drag&drop your rar unto SABnzbd on your PC? 

I did that with your rar unto my SAB-on-Linux and ... works nicely. So ... it is not a SAB-generic problem. It might be the rar binary version on your Synology ...

**Comment by PeterCodar** [comment]
I only use SABnzbd on my Synology NAS. 
Should I ask in the Synology community about this problem?

Or do you see anything why this occurs?

**Comment by sanderjo** [comment]
> I only use SABnzbd on my Synology NAS.

But what if you take 1 minute to just install SABnzbd on your windows, and do the drag&drop test? No need to configure or to use SABnzbd.

I checked my own Synology. 
```
admin@DiskStation:/$ unrar

UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal
```
So: same same. Once at home I can do the Synology drag&drop test. If you do the Windows-test ...

**Comment by PeterCodar** [comment]
You are right: Drag & drop of the RAR archive to the windows version of SABnzbd works fine.
What I have found after the installation finished:

> ## Improvements and bug fixes since 2.3.8
> - Windows and macOS: update UnRar to 5.71

What do you think: Could I manually replace the unrar binary on the synology?
If yes, which version can I use?

**Comment by sanderjo** [comment]
Drag&drop onto my Synology-SABnzbd ... works!

So ... it must be you ... ;-)

Replacing unrar without the package system ... normally I would not advice that, but as you seem to know Linux CLI, I guess you know how to do that safely. I guess you know `which` and how to save a copy of the original unrar / rar.

![image](https://user-images.githubusercontent.com/1273502/70074750-a3f5f000-15fb-11ea-82e8-f34d846fa47d.png)

**Comment by sanderjo** [comment]
Oh, wait, what you can do first:

Copy the .rar file onto your Synology, and then on the CLI, let unrar unpack that rar ... see what happens.

**Comment by PeterCodar** [comment]
Strange thing. Do you use version 5.21 of unrar on your Synology?

As you suggested, I have extracted the RAR-archive manually with

`unrar x Jahresarchiv.2019.rar`
and I get - SUPRPISE - no error:
```
UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal

Extracting from Jahresarchiv.2019.rar

Extracting  Gamestar.-.2019-12{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-01{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-02{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-03{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-04{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-05{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-06{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-07{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-08{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-09{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-10{{MeRryChrisTmaSFroMHoU}}.nzb           OK
Extracting  Gamestar.-.2019-11{{MeRryChrisTmaSFroMHoU}}.nzb           OK
All OK

```
I don't see, why this should no work with Drag & Drop to the waiting queue of SABnzbd.
Thanks for your help so far @sanderjo !

**Comment by sanderjo** [comment]
And what if ... the problem is non in the ...nzb.rar, but in one of the nzbs? That  Gamestar.-.2019-12 looks suspicious (error in your post, error in my download) ... so I tried that ... no problem with download itself. 
The result is strange though:

```
$ ll ~/Downloads/complete/Gamestar.-.2019-12
total 28076
drwxr-xr-x  2 sander sander     4096 Dez  3 18:57 ./
drwxrwxr-x 38 sander sander     4096 Dez  3 18:57 ../
-rw-r--r--  1 sander sander 10000000 Dez  3 18:57 j6SA36b5w5.part1.rar
-rw-r--r--  1 sander sander 10000000 Dez  3 18:57 j6SA36b5w5.part2.rar
-rw-r--r--  1 sander sander  8734004 Dez  3 18:57 j6SA36b5w5.part3.rar
```


Let's check the 11:
```
$ ll ~/Downloads/complete/Gamestar.-.2019-11
total 27892
drwxr-xr-x  2 sander sander     4096 Dez  3 12:43 ./
drwxrwxr-x 38 sander sander     4096 Dez  3 18:57 ../
-rw-r--r--  1 sander sander 10000000 Dez  3 12:42 415M6iJ2cb.part1.rar
-rw-r--r--  1 sander sander 10000000 Dez  3 12:42 415M6iJ2cb.part2.rar
-rw-r--r--  1 sander sander  8544276 Dez  3 12:42 415M6iJ2cb.part3.rar

```
So strange too.

Weird stuff. Looks like that uploader did something strange. So ... are you sure you want to spend time on this?

**Comment by PeterCodar** [comment]
Hmmm...
My problem is not specific to this single RAR archive. Every RAR I try to drag & drop results in the same error. I have not found one working RAR since I started to use SABnzbd, some weeks ago.

And the error "BadRarFile: Corrupt file - CRC check failed: " occurs immediately after Drag & Drop, it has not even started to download the files itself. Thats why I believe it has to do with the unrar process. I'm totally wrong?

**Comment by PeterCodar** [comment]
I made a basic test:
a) Download https://github.com/sanderjo/test-NZBs/blob/master/SpecialCharStuff%20PlainPlainPlain%208bb5f33e%20---%202016-11-04.nzb
b) Make a RAR with the file from a) (I used Winrar 5.80 64bit)
c) Drag & Drop it to the Synology

Result:
Same error as in my initial post. 

If I repeat this steps but make a ZIP file with the help of 7Zip, it works fine without any error.
If I repeat this steps but make a 7z file with the help of 7Zip, it works fine without any error.

What can I do?

**Comment by thezoggy** [comment]
problem is only with synology? do they package/do something different? what if you run from git source?

**Comment by PeterCodar** [comment]
Yes, the problem is only with Synology. 
I don't know if they package something different, how could I check that?
And how exactly would I "run it from git source" on my Synology?

**Comment by sanderjo** [comment]
Long shot: as `dirscanner.py` gives the error ... is there something dirty in the / a dirscanner directory.
Disclaimer: I don't know how this works in SAB, but apparantly drag&drop results in calling dirscanner.py ... I don't know which directory that is.

**Comment by thezoggy** [comment]
Maybe the tmp folder on Synology doesn't have the needed permissions?

**Comment by PeterCodar** [comment]
Thanks @sanderjo and @thezoggy 
What kind of permission do I have to give to this /tmp folder?

Where exactly should I find this /tmp folder?
Is this the @tmp folder on my /volume1?
`21627 0 drwxrwxrwt   1 root root   10 Dec  3 20:29 @tmp`
Or is this /tmp in the root folder of my Synology?
` 3908 0 drwxrwxrwt  10 root root  1380 Dec  4 08:40 tmp`

**Comment by PeterCodar** [comment]
Unfortunately, the following steps were not successful for my UNRAR problem:
a) Deinstall of SABnzbd, Restart Synoloy, Install of SABnzbd
b) Setting the flag `ignore_wrong_unrar`

I can see the following entries in the Debuglog:

```
> 2019-12-04 18:31:29,664::INFO::[SABnzbd:409] SABYenc module (v3.3.5)... found!
> 2019-12-04 18:31:29,665::INFO::[SABnzbd:426] Cryptography module (v2.1.4)... found!
> 2019-12-04 18:31:29,666::INFO::[SABnzbd:431] par2 binary... found (/volume1/@appstore/sabnzbd/bin/par2)
> 2019-12-04 18:31:29,666::INFO::[SABnzbd:441] UNRAR binary... found (/volume1/@appstore/sabnzbd/bin/unrar)
> 2019-12-04 18:31:29,667::INFO::[SABnzbd:449] UNRAR binary version 5.71
> 2019-12-04 18:31:29,668::INFO::[SABnzbd:456] unzip-Programmdatei nicht gefunden!
> 2019-12-04 18:31:29,668::INFO::[SABnzbd:459] 7za binary... found (/volume1/@appstore/sabnzbd/bin/7za)
> 2019-12-04 18:31:29,669::INFO::[SABnzbd:465] nice binary... found (/volume1/@appstore/sabnzbd/bin/nice)
> 2019-12-04 18:31:29,669::INFO::[SABnzbd:471] ionice binary... NOT found!
> 2019-12-04 18:31:29,673::INFO::[SABnzbd:1397] Starting web-interface on 0.0.0.0:8080
```

The same Test1.nzb inside a 7z archive works fine.

```
> 2019-12-04 18:31:47,617::INFO::[__init__:681] Adding Test1.7z
> 2019-12-04 18:31:47,708::INFO::[misc:997] Creating directories: /volume1/NZB-DL/incomplete/Test1.1
> 2019-12-04 18:31:47,716::INFO::[nzbstuff:530] File plain-filename.part1.rar - SABnzbd_nzf_fJRXXE added to queue
> 2019-12-04 18:31:47,722::INFO::[nzbstuff:530] File plain-filename.part2.rar - SABnzbd_nzf_LB_7DJ added to queue
> 2019-12-04 18:31:47,727::INFO::[nzbstuff:530] File plain-filename.part3.rar - SABnzbd_nzf_I4cqqG added to queue
> 2019-12-04 18:31:47,733::INFO::[nzbstuff:530] File plain-filename.part4.rar - SABnzbd_nzf_yJlEMQ added to queue
> 2019-12-04 18:31:47,738::INFO::[nzbstuff:530] File plain-filename.part5.rar - SABnzbd_nzf_gU97CE added to queue
> 2019-12-04 18:31:47,740::INFO::[nzbstuff:530] File plain-filename.part6.rar - SABnzbd_nzf_XyOo2C added to queue
> 2019-12-04 18:31:47,742::INFO::[nzbstuff:530] File plain-filename.par2 - SABnzbd_nzf_epJeT7 added to queue
> 2019-12-04 18:31:47,745::INFO::[nzbstuff:530] File plain-filename.vol000+02.par2 - SABnzbd_nzf_k_uztX added to queue
> 2019-12-04 18:31:47,748::INFO::[nzbstuff:530] File plain-filename.vol002+04.par2 - SABnzbd_nzf_JY4INb added to queue
> 2019-12-04 18:31:47,750::INFO::[nzbstuff:530] File plain-filename.vol006+08.par2 - SABnzbd_nzf_5ORDPx added to queue
> 2019-12-04 18:31:47,753::INFO::[nzbstuff:530] File plain-filename.vol014+16.par2 - SABnzbd_nzf_3_X0Hx added to queue
> 2019-12-04 18:31:47,755::INFO::[nzbstuff:530] File plain-filename.vol030+32.par2 - SABnzbd_nzf_mVU8sV added to queue
> 2019-12-04 18:31:47,758::INFO::[nzbstuff:530] File plain-filename.vol062+64.par2 - SABnzbd_nzf_nV_2vy added to queue
> 2019-12-04 18:31:47,761::INFO::[nzbstuff:530] File plain-filename.vol126+74.par2 - SABnzbd_nzf_hsT4jN added to queue
> 2019-12-04 18:31:47,762::INFO::[__init__:624] Backing up /volume1/NZB-DL/incomplete/Test1.1/__ADMIN__/Test1.nzb.gz
> 2019-12-04 18:31:47,774::INFO::[nzbqueue:260] Saving queue
```

The same Test1.nzb inside a RAR says:

```
> 2019-12-04 18:31:51,986::INFO::[__init__:681] Adding Test1.rar
> 2019-12-04 18:31:52,020::ERROR::[dirscanner:136] Test1.nzb kann nicht gelesen werden
> Traceback (most recent call last):
>   File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/dirscanner.py", line 134, in ProcessArchiveFile
>     data = zf.read(name)
>   File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 772, in read
>     return f.read()
>   File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 2028, in read
>     self._check()
>   File "/volume1/@appstore/sabnzbd/share/SABnzbd/sabnzbd/utils/rarfile.py", line 2045, in _check
>     self._inf.filename, exp, final))
> BadRarFile: Corrupt file - CRC check failed: Test1.nzb - exp=967120233 got=181776908
```

Any ideas how I could further debug or solve this problem?

**Comment by sanderjo** [comment]
Hey, there a 2 different unrar binaries on a synology:

Provided and (probably) used by SABnzbd:
```
admin@DiskStation:/$ /volume1/@appstore/sabnzbd/bin/unrar | head -4

UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
admin@DiskStation:/$ 
admin@DiskStation:/$ 
```
and the system unrar:
```
admin@DiskStation:/$ /bin/unrar | head -4

UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
admin@DiskStation:/$ 
```

Can you check that both versions work, and that both can unpack an unrar?

**Comment by PeterCodar** [comment]
SABnzbd:
```
Administrator@DS412Plus:/volume1/@appstore/sabnzbd/bin$ ./unrar | head -4
./unrar: /lib/libstdc++.so.6: no version information available (required by ./unrar)
./unrar: /lib/libstdc++.so.6: no version information available (required by ./unrar)

UNRAR 5.71 beta 1 freeware      Copyright (c) 1993-2019 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
```
system unrar is identical to yours.

My results if both version can manually unrar the Test1.rar follow soon.

**Comment by sanderjo** [comment]
But don't you think the `./unrar: /lib/libstdc++.so.6: no version information available (required by ./unrar)` is bad? What if sabnzbd tries to interpret that information ... ?

So I would suggest:
save a copy of that /volume1/@appstore/sabnzbd/bin/unrar
Onto that place, copy your system's unrar
then try again ...

**Comment by PeterCodar** [comment]
> But don't you think the `./unrar: /lib/libstdc++.so.6: no version information available (required by ./unrar)` is bad? What if sabnzbd tries to interpret that information ... ?

Now that you're saying it... `*shame-on-me*`

And of course, you are absolutely right! A copy of /bin/unrar in the folder /volume1/@appstore/sabnzbd/bin/ is the ultimate solution. My RAR archive works like expected and like other archive formats too.

**THANK YOU VERY MUCH for your patience and help to find this.**

(Honestly, I have no idea why this unrar v5.71 beta version - originally included in the official Synology package - throw this "/lib/libstdc++.so.6" error).

**Comment by sanderjo** [comment]
> **THANK YOU VERY MUCH for your patience and help to find this.**

It was a pleasure to discover this together.

> (Honestly, I have no idea why this unrar v5.71 beta version - originally included in the official Synology package - throw this "/lib/libstdc++.so.6" error).

1. are you sure this 5.71 version was provided by the sab package ... ? Because, if so, why do I have a 5.50 on my Synology?
2. you can google that error and dive into linux internals (beyond my understanding). Or not ... and live with your current solution/workaround.

**Comment by PeterCodar** [comment]
1. Yes, I'm pretty sure because I have deinstalled SABnzbd in the Synology package manager, then checked if the folders in @appstore have been removed (using Putty and WinSCP), restarted my Synology and the again installed the package from scratch (the web gui shows version "`2.3.9 03c10dc`"). It would be frightening if this unrar 5.71 resurrects in a magical form...

2. I can live very well with this situation. If someone else is ever running in the same problem: Google should lead him to this thread and your solution!

**Comment by Safihre** [comment]
I am also the creator of the Synology SAbnzbd package. It does include Unrar 5.71 ([link](https://github.com/SynoCommunity/spksrc/tree/master/cross/unrar)) and has since the SABnzbd 2.3.8 package for Synology.
But it seems something might be wrong with the SynoCommunity build!
Although you would be using the `x64` package on your DS412Play, and lots of people use that one. 
Were you able to download and extract normal downloads just fine?

**Comment by sanderjo** [comment]
> Although you would be using the `x64` package on your DS412Play, and lots of people use that one.

Ah, is it a 32bit versus 64bit thing? Is @PeterCodar  running a 32-bit unrar binary on a 64-bit OS / library? Like https://gathering.tweakers.net/forum/list_messages/1822345 (warning: Dutch!)

And thus **not** a library version number mismatch like

> The "no version information available" means that the library version number is lower on the shared object. For example, if your major.minor.patch number is 7.15.5 on the machine where you build the binary, and the major.minor.patch number is 7.12.1 on the installation machine, ld will print the warning.
> 
> You can fix this by compiling with a library (headers and shared objects) that matches the shared object version shipped with your target OS. E.g., if you are going to install to RedHat 3.4.6-9 you don't want to compile on Debian 4.1.1-21. This is one of the reasons that most distributions ship for specific linux distro numbers.



Just random snippets for my own archive.

After installing `ldd` like this:
```
admin@DiskStation:/$ sudo -s
Password:
sh-4.3# ldd
sh: ldd: command not found
sh-4.3# synogear list
Tools are not installed yet. You can run this command to install it:
   synogear install

sh-4.3# synogear install
root@DiskStation:/# 
```

you can do the usual Linux check on Synology: 
```
root@DiskStation:/# file /bin/unrar
/bin/unrar: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.16, BuildID[sha1]=5772bca8b00fdb4a3a9b028e0a8140358a0da0e8, stripped
root@DiskStation:/# file /volume1/@appstore/sabnzbd/bin/unrar
/volume1/@appstore/sabnzbd/bin/unrar: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.16, stripped
root@DiskStation:/# ldd /volume1/@appstore/sabnzbd/bin/unrar
	not a dynamic executable
root@DiskStation:/# 
root@DiskStation:/# uname -a
Linux DiskStation 2.6.32.12 #24922 Tue Apr 23 17:32:06 CST 2019 armv5tel GNU/Linux synology_88f6281_212j
root@DiskStation:/# 

```
My Synology is 32bit, so I can't verify further.

**Comment by PeterCodar** [comment]
@Safihre
> Although you would be using the `x64` package on your DS412Play, and lots of people use that one.

I'm using a DS412**Plus** (not play). According to the [mentioned wiki](https://github.com/sabnzbd/sabnzbd/issues/1348#issuecomment-561247217) this Synology contains a Intel Atom processor.

```
Administrator@DS412Plus:/$ uname -a
Linux DS412Plus 3.10.105 #24922 SMP Wed Jul 3 16:35:48 CST 2019 x86_64 GNU/Linux synology_cedarview_412+

```
> Were you able to download and extract normal downloads just fine?

You ask if NZB works fine? Yes, they work great (including many rar-parts building the final file).
The problem with v5.71 unrar seems only to exist using Drag & Drop with a rar archive (including NZB) to the SABnzbd waiting queue in a web browser.

Please tell me if you need more informations. I'm not a linux/bash specialist. So please provide the commands necessary for further informations.
