### ISSUE TITLE
Repair blocks not being added in "Force" priority.

### ISSUE THREAD

**Issue by doguitar** [sabnzbd/sabnzbd#1350]
I've noticed that repair blocks don't have a priority option to select and aren't bypassing the "Play/Pause" state of sabnzbd. This has become an issue for me when the Temp directory reaches the pause limit. That situation results in the queue being frozen and no downloads completing. 

My configuration is set up so that the drive that sabnzbd is using as it's Temp directory is only used by sabnzbd so it's not possible for me to clear space from that drive to resume the queue without clearing those items in post-processing.

**Comment by thezoggy** [comment]
Jobs have priority not articles

**Comment by doguitar** [comment]
I'm talking about the Job priority. 

When an nzb moves from the post-processing queue back to the download queue to fetch more repair blocks, the job respects the play/pause state of the download queue. 

Because of that, I tried to change the priority of the job to "Force" so it would continue downloading repair blocks but the "Priority" dropdown is missing when the job is in that state (screenshot included).

![image](https://user-images.githubusercontent.com/1200188/70656721-79b1bd00-1c0f-11ea-9929-e761f0aaf081.png)

**Comment by Safihre** [comment]
This is by design, because the Repair-priority is above the Force-priority and we want to keep it that way.
But then again, indeed this state different from Force because it won't ignore the Pause-state.

**Comment by doguitar** [comment]
My issue stems mostly from not being able to change the job priority of the repair to Force so that I can recover from the disk full auto-pause (sabnzbd has a dedicated Temp drive so there's nothing else on there). The only other solution would be to go into the settings and remove the force pause then add it back.
