### ISSUE TITLE
[FR] please include the tests in -src releases

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1353]
...so these can be used for continuous integration testing in linux distributions. I realise not all of them are reliable enough, some require server credentials and so on, but I think having this could be useful as an early warning systems for incompatible changes in dependencies, etc.

**Comment by Safihre** [comment]
@jcfp I had to re-write the whole release script.
Can you check if this release contains all the files you need and would expect to be in a `src` release?
https://github.com/sabnzbd/sabbuild/releases/tag/py3-test-2

**Comment by jcfp** [comment]
Looks fine to me. Build a package based on that tag and tried running the tests as well.

**Comment by Safihre** [comment]
Good to know!
