### ISSUE TITLE
certain (small) NZBs: Badly formed yEnc article

### ISSUE THREAD

**Issue by zaadstra** [sabnzbd/sabnzbd#1356]
Hello,

There is a weird issue with some nzb's created by index sites. They want to grab very small files.
This is reproduceable with other nzb's created of the same or older csv files.
The nzb's created download correctly on Newsleecher on an old pc.

This is the error message of one of the failed downloads:
![2020-01-11 100701](https://user-images.githubusercontent.com/29779266/72201943-2757fc00-345a-11ea-9100-8aa6e208b643.png)

Name
ctp new NZBindex
Completed
2020-01-11 09:58
Status
Failed
Size
4.4 MB
Category
Default
Path
D:\DownloadNews\Incomplete\ctp new NZBindex
Source
ctp new NZBindex.nzb
Download
Downloaded in 2 seconds at an average of 2.1 MB/s
Age: 4d
4 articles were malformed
4 articles were missing
Aborted, cannot be completed - https://sabnzbd.org/not-complete
Servers
xsnews=2.2 MB, cheapnews=1.9 MB, ssl-eu.astraweb.com=375 KB

The nzb's of Binsearch and NZBindex show the same behaviour, I'll attach them. The files look ok to me if I look inside.

[ctp new NZBindex.nzb.txt](https://github.com/sabnzbd/sabnzbd/files/4049137/ctp.new.NZBindex.nzb.txt)
[NEW-CTP-update binsearch.nzb.txt](https://github.com/sabnzbd/sabnzbd/files/4049138/NEW-CTP-update.binsearch.nzb.txt)

Links to create the nzb's for these files:
http://binsearch.info/?q=NEW-CTP-update&max=100&adv_age=1100&server=2
https://nzbindex.nl/?q=ctp&max=25&minage=&maxage=&hidespam=1&hidepassword=0&sort=agedesc&minsize=&maxsize=&complete=0&hidecross=0&g%5B%5D=294&hasNFO=0&poster=

Download tested on SABnzbd version: 2.3.9 on Windows and on Synology.

**Comment by thezoggy** [comment]
tried the first nzb:
```
Servers
UNS-US=2.2 MB, SuperNews=2.2 MB, NGD=2.2 MB, UsenetExpress=2.2 MB, Astraweb (US)=2.2 MB, UNS-EU=2.2 MB, Usenet.farm=2.2 MB, Astraweb (EU)=2.2 MB, XSusenet (free)=2.2 MB
```

no matter from which usp it tried (can see from above it did all of them that i have), all the articles were malformed:
```
2020-01-11 16:22:15,349::INFO::[decoder:183] Badly formed yEnc article in LsFQF.305490$m4a.147384@fx03.dcg
2020-01-11 16:22:15,349::INFO::[decoder:183] Badly formed yEnc article in ysFQF.305486$m4a.247407@fx03.dcg
2020-01-11 16:22:15,349::INFO::[decoder:183] Badly formed yEnc article in FsFQF.305488$m4a.90020@fx03.dcg
```

do you know who posted the nzb (can you verify if its legit and not just spam/junk)?

**Comment by zaadstra** [comment]
Yes the nzb's are legit, they are created by Binsearch.info and NZBindex.nl.
And they aren't that bad, as my old-school newsreader Newsleecher 3.9 fetched the files without problems.  
So yes this is really a weird thing.  Never seen SAB failing to download nzb's from these indexers before.
You can try to create the nzb's yourself with the Links to create the nzb's for these files posted above. Even multiple days didn't make it work. Sender of the csv files (text) is Pongo.

**Comment by thezoggy** [comment]
Spammer and people post all sorts of garbage to Usenet and just because it is there doesn't mean it's 'valid' in the sense that you could actually do anything with it. Some people post with modified yenc to purposely prevent dmca or people outside in the know to do anything with it. It's another form of obfuscation badically

**Comment by zaadstra** [comment]
I see.  In this way the files are 100% safe,  I download these files (bi-)weekly for years from this guy.  With newsleacher after headering.  Since headering in that group is impossible because of a continuous crap flood I tried to pick the files via the indexers and then SABnzbd.  Then I discovered the issue.

This is an example of a post from november last year.
[CSVs 10-26-2019 Update.zip](https://github.com/sabnzbd/sabnzbd/files/4050452/CSVs.10-26-2019.Update.zip)

**Comment by Safihre** [comment]
It could be that there's a problem in our yEnc code, due to optimizations for large files it could maybe fail with smaller ones.

**Comment by zaadstra** [comment]
Is there a way I can fiddle with the switches?  I toggled fast_fail (no description on wiki page, and always (on) despite changing tick),  I do not suspect other switches to help here.  
There are no remaining download files left in the folder, so a manual action to fix or glue the files is not possible.
Is there any trick I can do?  Or deliver other test data?

**Comment by albino1** [comment]
If you click the little drop down arrow next to the job in the queue, one of the options is:

`Download`
`+Repair`
`+Unpack`
`+Delete`

Change it to just `Download` and it shouldn't delete any of the files.  You can also click the little icon at the top right to select all of them and change them all at the same time instead of changing them individually.

**Comment by zaadstra** [comment]
My default setting is +Repair,  so files would not be deleted anyway if I'm correct?
Switching to Download doesn't result in remaining files however (looking in the Incomplete folder).
The error message did change:
![image](https://user-images.githubusercontent.com/29779266/72662271-8f23bf00-39e5-11ea-9155-e4ddc52bb41a.png)
Now it says Download failed - Not on your server(s).
Oh wait, fake news. Switching back to +Repair it now also says Not on your servers.  Deleting these files from the servers has not been true in the past but you never know with that flood in that group these days. I don't have an old school newsgrabber at hand at the moment to test.
The 'malformed' part is still there, possibly the key here as Safihre mentioned.

**Comment by albino1** [comment]
I get the same errors saying 10 malformed and 10 missing.  It doesn't seem to matter which server I use.  That doesn't help, but I thought I'd confirm it.

**Comment by sanderjo** [comment]
Triggered by the wording "Trouble with small nzb's", here is a small nzb for you to verify your claim / statement:

https://nzbindex.com/?q=91136941aaa4
https://www.binsearch.info/?q=91136941aaa4

What is the download result?

**Comment by zaadstra** [comment]
Downloads both succesfull.
Please note that the csv's in my links can be small as a few KB.

**Comment by sanderjo** [comment]
OK ... so change the title to "Trouble with _certain_ nzb's"? @zaadstra

**Comment by sanderjo** [comment]
> It could be that there's a problem in our yEnc code, due to optimizations for large files it could maybe fail with smaller ones.

So ... try with
- and older sabyenc before the optimisations
- without sabyenc, and thus the old python-yenc
- another current downloader
... or more hardcore:
- manually call sabyenc with each article ?

**Comment by sanderjo** [comment]
SABnzbd is already telling what is going on: `Badly formed yEnc article`

So that should be the title of this issue, IMHO.

And the key question is: is the article really badly formed, or is it a problem inside sabyenc.

```
2020-01-21 12:56:51,851::INFO::[downloader:699] Connecting 5@newsreader.eweka.nl finished
2020-01-21 12:56:51,870::INFO::[decoder:174] Badly formed yEnc article in 5F6VF.5954$bo5.5859@fx17.dcg
2020-01-21 12:56:52,871::INFO::[downloader:490] 3@newszilla6.xs4all.nl: Initiating connection
2020-01-21 12:56:52,895::INFO::[newswrapper:105] 3@newszilla6.xs4all.nl: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
2020-01-21 12:56:53,873::INFO::[downloader:699] Connecting 3@newszilla6.xs4all.nl finished
2020-01-21 12:56:53,905::INFO::[decoder:174] Badly formed yEnc article in 5F6VF.5954$bo5.5859@fx17.dcg
```

**Comment by zaadstra** [comment]
As old school Newsleecher on old school pc can grab these NZB's I guess it is something inside sabyenc then.  Opening the nzb in Notepad++ shows a normal xml just like a nzb that does download correctly.
I've been looking in the software folder but don't see anything for me to tweak.
Or a switch or special to use old python yenc.  I read on the wiki that sabyenc is quite some time present, since v2.0.

**Comment by sanderjo** [comment]
@zaadstra If you change the subject of this issue to "certain NZBs: Badly formed yEnc article" I can help you further.

**Comment by zaadstra** [comment]
There you go! ;-)

**Comment by sanderjo** [comment]
Some result: Ubuntu 18.04, sabnzbdplus-2.3.2, hard removed sabyenc, installed python-yenc, downloaded, and SABnzbd says

```
2020-01-21 19:07:54,080::WARNING::[decoder:257] UUencode detected, only yEnc encoding is supported [PBP2020_MultiMedia_CTP_24.csv]
```
Huh?

![image](https://user-images.githubusercontent.com/1273502/72834832-e5b12780-3c89-11ea-8c22-111d3e56a39b.png)

**Comment by sanderjo** [comment]
So ... uuencoded ... ? Let's see, with a handjob:

```
$ telnet newszilla6.xs4all.nl nntp
Trying 2001:888:0:18::119...
Connected to newszilla-ipv6.xs4all.nl.
Escape character is '^]'.
201 newszilla.xs4all.nl NNRP Service Ready (dreader35) (no posting)

group alt.binaries.jph

article <5F6VF.5954$bo5.5859@fx17.dcg>
220 0 <5F6VF.5954$bo5.5859@fx17.dcg> article
Path: newszilla.xs4all.nl!nzspool06.xs4all.net!binary23.news.xs4all.nl!newsfeed.xs4all.nl!newsfeed9.news.xs4all.nl!81.171.65.13.MISMATCH!peer01.am4!peer.am4.highwinds-media.com!news.highwinds-media.com!fx17.dcg.POSTED!not-for-mail
From: ctp@net.com (Pongo)
Sender: ctp@net.com
Newsgroups: alt.binaries.jph
Subject: ===NEW=== CTP update [2|2] - PBP2020_MultiMedia_(CTP)_24.csv (1/1) - 1688 bytes
X-Newsposter: NNTP POWER-POST 2000 (Build 24c) - net-toys.8k.com
Lines: 42
Message-ID: <5F6VF.5954$bo5.5859@fx17.dcg>
X-Complaints-To: abuse@easynews.com
Organization: Forte - www.forteinc.com
Bytes: 2875
X-Complaints-Info: Please be sure to forward a copy of ALL headers otherwise we will be unable to process your complaint properly.
Date: Mon, 20 Jan 2020 00:39:29 GMT
X-Received-Bytes: 3008
X-Received-Body-CRC: 4279953106
Xref: newszilla.xs4all.nl alt.binaries.jph:1110831


begin 644 PBP2020_MultiMedia_(CTP)_24.csv
M06QI8V5?05]*87E?35]3:&%R961?4V5C<F5T<U\Q,#@P<"YM<#0L,C,Q-C8P
M.#8P+#@R0T8P-3,V+%Q':7)L9G)I96YD<UPL#0I!;&EC95]!7TIA>5]-7U-H
M87)E9%]396-R971S7S1++FUP-"PR.3$Y-C8S.38L0D-$1D%#-#8L7$=I<FQF
M<FEE;F1S7"P-"D=L;W)I85]3;VQ?06QI8V5?4VAE85]%;F-H86YT961?1')E
M86US7S$P.#!P+FUP-"PR,#,Y-C4S,SDL145!,T5&,40L7$=I<FQF<FEE;F1S
M7"P-"DIA>5]+87EL85](96%R='-?4F%C:6YG7S$P.#!P+FUP-"PQ-38X,3$U
M,38L0CDY,3<T-S(L7$=I<FQF<FEE;F1S7"P-"DIA>5]+87EL85](96%R='-?
M4F%C:6YG7S1++FUP-"PR,3`W-S@R,3`L,4%"-3(P-#0L7$=I<FQF<FEE;F1S
M7"P-"DEL=GE?2V]K;VUO7TAI9VA?06)O=F5?,3`X,'`N;7`T+#$Y,30W,3(U
M.2PR.$4W1C,Q-BQ<26YT97)N871I;VYA;%PL#0I*=6QI85]:=5]';V]D7TYA
M='5R961?,3`X,'`N;7`T+#$X-#(T,3,R,RPU-4$X03!%1"Q<26YT97)N871I
M;VYA;%PL#0I*=6QI85]:=5]';V]D7TYA='5R961?-$LN;7`T+#,P-#DX-S4W
M.2Q%-3$U.#E#,2Q<26YT97)N871I;VYA;%PL#0I-86MI7TMA=&%N85]$<F5A
M;5]#>6-L95\Q,#@P<"YM<#0L,C`S,3$V-S(R+$(T-S0Q,S9!+%Q);G1E<FYA
M=&EO;F%L7"P-"E-O<&AI95],:6UM85]396YS=6%L7U)E;&%X871I;VY?,3`X
M,'`N;7`T+#$T-#$S-S,S,RQ!.3,X-40T,RQ<26YT97)N871I;VYA;%PL#0I!
M8F5L;&%?1&%N9V5R7T9A<W1?3&%N95\Q,#@P<"YM<#0L,S$Q-C@T.#<W+$8X
M0C)!-4(P+%Q-=7-E<UPL#0I!8F5L;&%?1&%N9V5R7T9A<W1?3&%N95\T2RYM
M<#0L-#$Y,C@Q-C$X+#`Q-3E#149!+%Q-=7-E<UPL#0I!;F=E;%]#;VYS=&%N
M8V5?4W5N7U-P96QL7S$P.#!P+FUP-"PS,34W.#<R-C(L,#$Y-D-$-T,L7$UU
M<V5S7"P-"DQA=7)A7T1E=G5S:&-A=%]3;V9T7T)L;V]M7S$P.#!P+FUP-"PR
M,#`X,S`R.34L.#8S0S<T.3(L7$UU<V5S7"P-"DQA=7)A7T1E=G5S:&-A=%]3
M;V9T7T)L;V]M7S1++FUP-"PR-S`R,S$X-#(L,3,R0SDV0T(L7$UU<V5S7"P-
M"E)I;&5Y7U)E:61?1FQA<VAB86-K7T9A;G1A<WE?,3`X,'`N;7`T+#,P,3(Y
M,#(Y."PR-#A!,$,W."Q<375S97-<+`T*4FEL97E?4F5I9%]&;&%S:&)A8VM?
M1F%N=&%S>5\T2RYM<#0L-#`T-C0Y-CDW+$0Q1$%".4-!+%Q-=7-E<UPL#0I5
M;6%?2F]L:65?4V]U;&9U;%]%>'!R97-S:6]N7S$P.#!P+FUP-"PS,C$X,30X
M,38L03@U1#)#-38L7$UU<V5S7"P-"E5M85]*;VQI95]3;W5L9G5L7T5X<')E
M<W-I;VY?-$LN;7`T+#0S,3DU,S@R.2PT,#E"03,S."Q<375S97-<+`T*36%S
M:'5P7T)E<W1?;V9?0F]A=&EN9U\Q,#@P<"YM<#0L,S0Y,S4U-#<P+#,Y-$8Q
M-C@X+%Q3<&5C:6%L161I=&EO;G-<+`T*36%S:'5P7U-T87)S7V]F7U!L87EB
M;WE?4&QU<U\Q,#@P<"YM<#0L-#,S.#<S,#$V+#1".$$W-#8P+%Q3<&5C:6%L
M161I=&EO;G-<+`T*36%S:'5P7U-T87)S7V]F7U!L87EB;WE?4&QU<U\Q,#@P
M<%]/;&0N;7`T+#0S,S@W,CDX-BQ#03$T13@X-"Q<4W!E8VEA;$5D:71I;VYS
M7"P-"DUA<VAU<%]3=&%R<U]O9E]0;&%Y8F]Y7U!L=7-?-$LN;7`T+#4X,S$U
M,#@T,RPP13(Q03$V1"Q<4W!E8VEA;$5D:71I;VYS7"P-"DUA<VAU<%]3=&%R
M<U]O9E]0;&%Y8F]Y7U!L=7-?-$M?3VQD+FUP-"PU.#,Q-3`U,3,L14)#049$
7-C@L7%-P96-I86Q%9&ET:6]N<UPL#0H`
`
end
.


```

So, yes, that looks like uuencoded, and not yencoded, and thus I can understand sabyenc says it's malformed  ... this article should not reach sabyenc.

**Comment by zaadstra** [comment]
Interesting! Thanks for this view under the hood :-D
Is UUencode quite obsolete now, that I appear to be the only one encountering this issue?

**Comment by sanderjo** [comment]
> Interesting! Thanks for this view under the hood :-D

Under the hood indeed.

> Is UUencode quite obsolete now, that I appear to be the only one encountering this issue?

yenc / yencode is the standard since 2003. uuencode was that, so before 2003. Go figure. See https://en.wikipedia.org/wiki/YEnc

**Comment by zaadstra** [comment]
PowerPost2000 is indeed really old but still used ;-)  A simple and handy multi-file uploader and header text generator Blah blah [12 of 34].
I remember PP2k can do yEnc as well...

**Comment by sanderjo** [comment]
I hacked something into sabnzbd 3, and now SAb tells me it's uuencoded:

![image](https://user-images.githubusercontent.com/1273502/72841309-65dd8a00-3c96-11ea-8d11-000320f46117.png)

**Comment by zaadstra** [comment]
Now it detects UUencode, can SABNZBd 3 still decode it?  Or at least leave the file for now as work around for a manual decoder.

**Comment by sanderjo** [comment]
Oh my ... Groundhog Day! See https://forums.sabnzbd.org/viewtopic.php?t=20332#p104716

**Comment by zaadstra** [comment]
LOL!  When that movie is downloaded by SABNZBd it should auto-download every next day ... and again  ,,, and again :-D 
Looking forward to see if this can be solved. Perhaps with bringing back proper UUencode detection and then an external decoder like zip par2 and rar packs?

**Comment by sanderjo** [comment]
For refence: I created a uuencoded post. Won't work in SABnzbd; it will give `Badly formed yEnc article in u7KVF.38814$BA5.27425@fx21.am4`

https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb%20uuencoded%201MB%204f77b411e66e.nzb

**Comment by zaadstra** [comment]
Indeed!  Good for testing.
![image](https://user-images.githubusercontent.com/29779266/72930346-0a75cf80-3d5c-11ea-92ff-5c1d468d0f93.png)

**Comment by sanderjo** [comment]
Background:
https://github.com/sabnzbd/sabnzbd/commit/35607d69e0f6169421302df84b079e7572dae5c4

"Drop support for UUencode and show notice when detected", Apr 27, 2016

**Comment by sanderjo** [comment]
![image](https://user-images.githubusercontent.com/1273502/73085203-9f003f00-3ece-11ea-9e5b-556eaad02467.png)

```
2020-01-24 17:25:27,319::INFO::[decoder:181] Badly formed yEnc article in u7KVF.38814$BA5.27425@fx21.am4
2020-01-24 17:25:27,320::WARNING::[decoder:196] Badly formed yEnc article: very probably uuencode, which is not supported
```

**Comment by zaadstra** [comment]
Due to the ancientness of the protocol I understand removing.  A message and leaving the article files in "Incomplete" would be nice.

**Comment by Safihre** [comment]
@sanderjo sounds good, let's build back a nice message for these few rare posts!
Indeed uuencode never worked well, even when we did have a decoder. And we didn't support multi-part uuencode so it could only handle tiny files.

**Comment by thezoggy** [comment]
> 
> 
> For refence: I created a uuencoded post. Won't work in SABnzbd; it will give `Badly formed yEnc article in u7KVF.38814$BA5.27425@fx21.am4`
> 
> https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb%20uuencoded%201MB%204f77b411e66e.nzb

what about:
https://github.com/sanderjo/test-NZBs/blob/master/SpecialCharStuff%20PlainPlainPlain%20but%20uuencode%20984a3cfa%20---%202016-11-05.nzb

**Comment by thezoggy** [comment]
> 
> 
> @sanderjo sounds good, let's build back a nice message for these few rare posts!
> Indeed uuencode never worked well, even when we did have a decoder. And we didn't support multi-part uuencode so it could only handle tiny files.

we already have the translated message: `UUencode detected, only yEnc encoding is supported [%s]`
from back when we added logic to do this already: 
https://github.com/sabnzbd/sabnzbd/pull/565/commits/35607d69e0f6169421302df84b079e7572dae5c4

**Comment by zaadstra** [comment]
Interesting, that nzb throws a different error:

![image](https://user-images.githubusercontent.com/29779266/73119419-ce13c080-3f61-11ea-8d50-9931d79525a5.png)


![image](https://user-images.githubusercontent.com/29779266/73119411-c2c09500-3f61-11ea-9961-ad973893a079.png)

**Comment by thezoggy** [comment]
which is because the articles are missing on your usp (retention isnt good enough or really were removed)

**Comment by sanderjo** [comment]
Following @thezoggy 's advice, my patch now uses the old-but-existing SABnzbd uuencode warning. Proof: it shows the Dutch warning.

I can show two different things (now both are in the logging):
* post name
* article id

![image](https://user-images.githubusercontent.com/1273502/73135049-32a44d80-403e-11ea-9c81-1ce1b2782c12.png)


I prefer the post name: clearer for the user. Agree?

Note: the warning appears per parse (technical: per BadYenc exception) ... so often more than once.

**Comment by Safihre** [comment]
Post name is definitely the most clear to users :)
Let's also make it an ERROR since it's fatal and can't be recovered from. 
I made this a long time ago and nobody complained, so probably it's fine to throw it multiple times. I think the old code would also pause the job (not the queue).

**Comment by Safihre** [comment]
Code merged!
