### ISSUE TITLE
Improved yEnc decoder released

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1357]
Seems like Anime Tosho released a much improved yenc decoder:

https://github.com/animetosho/node-yencode
https://www.reddit.com/r/usenet/comments/end4qb/worlds_fastest_yenc_encoderdecoder/

**Comment by thezoggy** [comment]
yep, which was started because of @Safihre questions!

**Comment by ericfowler303** [comment]
Any updates on potentially getting this improved decoder into the upcoming v3?

**Comment by Safihre** [comment]
It required a huge re-work in the way we handle decoding, so not for v3 for sure.
It will also be a pain to compile, since have to get all these special required flags to work with the Python compile-system.
