### ISSUE TITLE
duplicate files being created

### ISSUE THREAD

**Issue by sjpotter** [sabnzbd/sabnzbd#1359]
I don't know why, but relatively often, I end up with a directory that has file, file(1) or if its many files, will be file1, file1(1), file2, file2(1).... for every file in the archive.

This is annoying, can be cleaned up relatively easy, but still annoying.

**Comment by thezoggy** [comment]
Post logs? I've yet to see this myself.

**Comment by sjpotter** [comment]
next time I notice it, I'll try it.  I think it might be related to sabnzbd being paused (either manually or automatically due to low disk space in temporary dir)

**Comment by jonovate** [comment]
It happens to me a lot too.

This shows in the Completed entry, but there is actually 2 files:
`Unpacked 1 files/folders in 8 mins 31 seconds`

**Comment by albino1** [comment]
I get this pretty often and I don't have any low disk space issues.  The NZB only contains one file, but when it finishes unpacking/sorting/renaming there's 2 versions.  My sort is simply set to `%dn.%ext`, nothing complicated.  I haven't looked at the logs recently when it's happened, but when I have in the past it just looks the same as the other ones.  I've just set my logging to Debug, and when it happens again I'll try and remember to post them.

**Comment by thezoggy** [comment]
Is one of the files a sample? Do you use flat unpack? Do you see this with specific type of releases?

**Comment by albino1** [comment]
Sometimes there is a sample even though I have Ignore Samples checked, but this doesn't happen very often.  I don't think `flat_unpack` exists anymore, if it does I haven't changed it and I'm not sure where it is.  I haven't noticed it happening with a specific type of release, indexer, or uploader, but I'm going to start tracking it and maybe we can narrow it down.

If it helps, a lot of time when I end up with duplicate files they're still an obfuscated filename, and not the correctly renamed `%dn.%ext`, but then sometimes they are renamed and are just `file.mkv` and `file (1).mkv`. 

This is using Windows 10 Pro with SABnzbd 2.3.9.

**Comment by Safihre** [comment]
Can you maybe see if you have logs of it? I have a feeling it has to do with the NZB backups maybe.

**Comment by albino1** [comment]
My log only seems to go back 2 days so there's nothing useful there, but next time it happens I'll grab them.

**Comment by throwaway4dev** [comment]
Author, here you go, happened today:

```
.\Homeland.S08E08.Threnodys.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
03/29/2020  09:30 AM                75 13f4427e7f7448ed4ae963a9714311ab.txt
03/29/2020  09:07 AM     1,743,338,618 Ez750nYfBUg3djxrAeACTyB6Gvf2Dc(1).mkv
03/29/2020  09:07 AM     1,743,338,618 Ez750nYfBUg3djxrAeACTyB6Gvf2Dc.mkv
```

Gist Log: https://gist.github.com/throwaway4dev/1e8157ac2d5a06526c452f386a2c7dd6

**Comment by albino1** [comment]
So, I just downloaded the exact same release that @throwaway4dev did, and I also ended up with duplicate files, but one renamed and one still obfuscated:

```
Homeland.S08E08.Threnodys.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
Ez750nYfBUg3djxrAeACTyB6Gvf2Dc.mkv
```

In the log you can see it do both filenames, which probably helps track this down a bit better:

https://gist.github.com/albino1/9a70573b9ad384d38fd2fe55d07dd3ca

And here's the NZB if anybody else wants to test:

[al-duplicate-nzb.zip](https://github.com/sabnzbd/sabnzbd/files/4400133/al-duplicate-nzb.zip)

**Comment by throwaway4dev** [comment]
So there are multiple behaviors as mine never had a chance to rename from the Obfuscated name, unless there is a SabNZBD setting I missed?

**Comment by albino1** [comment]
I think the difference is yours is just being unpacked whereas mine is being sorted by category and renamed.  If that's true, then that helps since it means it's not related to the sort functionality, but somewhere in the unpack or direct unpacking logic.

**Comment by albino1** [comment]
All right, I've just run that NZB several more times, and I haven't had a single duplicate, so I'm not sure what's changed since the first time.  Here's the latest log where it *doesn't* happen:

https://gist.github.com/albino1/ab3d87c6cfb04aebcfb743ee52f1143e

Hopefully you can compare that to the log above where it *does* happen.

**Comment by thezoggy** [comment]
From your limited logs (you should set debug level) it only extracted the one .mkv

**Comment by thezoggy** [comment]
@albino1 you should change your San logging to debug (then restart sab) and generate fresh logs

**Comment by albino1** [comment]
@thezoggy, my logging level was already set to `+Debug` before I posted those previous logs.  I just restarted SAB, ran the NZB, got no duplicate, and the log pretty much looks the same as the previous one so far as I can tell:

https://gist.github.com/albino1/064cb3f1edb2a79d3699bed8bed97014

Let me know if there's something else I should change.

**Comment by jcfp** [comment]
In @albino1's duplicate log, both directunpack and regular postprocessing run unrar. The one thing that stands out is that the directunpacker detects a "duplicate output line", caused by not getting access to rar volume 16 at first because windoze claims that file is "being used by another process".

The directunpacker thus reports "1 Error" even though extraction of the mkv file eventually does succeed (after it retries volume 16). Apparently this is lost on the regular postproc (newsunpack) which proceeds to extract the job a second time.

The log posted by @throwaway4dev lacks the necessary debugging info but appears to also have both directunpack and regular postproc running unrar.

**Comment by sjpotter** [comment]
that is similar to my experience where it seemed there were many times direct unpack and regular post processing happened, especially when system was under load.

**Comment by Safihre** [comment]
@jcfp Is right. We only list a successful Direct Unpack if UnRar reported `All OK`. It didn't do that.
But we also don't trigger the abort-and-clean code, because `Total errors` is not listed in the error-checking code.
I will add `Total errors` to the clean-up code!

**Comment by Safihre** [comment]
I ended up adding `Cannot open` to the abort-list. Since `Total errors` was only shown near the end, it would continue for too long and waste resources.

Thanks guys for the debugging!

**Comment by sjpotter** [comment]
if I had to guess, I would also guess that there are situation where you are aborting direct unpacks (i.e. I would see a direct unpack start, I would see the quickcheck pass, but then i would see it unpack again).

**Comment by thezoggy** [comment]
there is a known bug in unrar + multi-par that is used in the latest build version.
those that run from git would get the updated utilities if you run from the 2.3.x branch
