### ISSUE TITLE
If sabnzbd is behind a reverse proxy, cherryhost should be different than browserhost

### ISSUE THREAD

**Issue by cimnine** [sabnzbd/sabnzbd#136]
### Situation

Because I only want to expose one HTTP daemon to the internet I run sabnzbd behind a reverse proxy.

### Current Behavior

Most actions work perfectly fine, but some end up in a HTTP redirect to localhost.

### Expected Behavior

Sabnzbd should respect that it is binding to localhost but not accessed via localhost 'in the end'.

### Possible cause

After digging through the code (I'm not a Python guy I have to say) I think the problem is that sabnzbd does not differ between the host on which cherrypy should bind to (and therefore listen on), and the host which is public exposed. 

On my server sabnzbd should only listen on the loopback interface (127.0.0.1 aka localhost), but I access it via https://myserver.tld/sabnzbd/ .
Sometimes (for example after clicking 'retry' in the 'History') sabnzbd will redirect me to http://localhost/sabnzbd/[something].

### Possible fix
To fix this, from what I understand, the `browserhost` should become 'myserver.tld' while `cherryhost` still is set to 'localhost' in the following function:
https://github.com/sabnzbd/sabnzbd/blob/a50412a32751f4d1d555020dea20a2da43d6a309/SABnzbd.py#L540

**Comment by Safihre** [comment]
Do any of you still have this issue? I tried to reproduce but whatever I try it gives nice relative url's in the redirect, no localhost included.
