### ISSUE TITLE
Passworded RAR files can fail to automatically extract with Unrar 5.80 or newer

### ISSUE THREAD

**Issue by Starshadow** [sabnzbd/sabnzbd#1365]
If Unrar 5.80 or newer is installed on the system, SABnzbd can fail to automatically extract a passworded RAR file under certain conditions:
-RAR file version is 5.
-'Action when encrypted RAR is downloaded' setting is 'Off'.
-The correct password is only provided in the Password file (not entered manually through the UI or stored in the RAR filename).

I believe this is due to Unrar 5.80 producing a new message when passworded files are detected.
```
UNRAR 5.80 freeware      Copyright (c) 1993-2019 Alexander Roshal

Incorrect password for /mnt/storage/incoming/SABnzbd/Open.Source.Software/005-oss.rar
Total errors: 1
```
This message is not matched by any of the patterns newsunpack.py (line 760) checks for to detect a passworded RAR file, which ultimately leads to the extraction silently failing:

```
elif 'The specified password is incorrect' in line or \
     ('ncrypted file' in line and (('CRC failed' in line) or ('Checksum error' in line))):
    # unrar 3.x: "Encrypted file: CRC failed in oLKQfrcNVivzdzSG22a2xo7t001.part1.rar (password incorrect ?)"
    # unrar 4.x: "CRC failed in the encrypted file oLKQfrcNVivzdzSG22a2xo7t001.part1.rar. Corrupt file or wrong password."
    # unrar 5.x: "Checksum error in the encrypted file oLKQfrcNVivzdzSG22a2xo7t001.part1.rar. Corrupt file or wrong password."
    # unrar 5.01: "The specified password is incorrect."
```
There is more information and some example log files here: https://forums.sabnzbd.org/viewtopic.php?f=3&t=24600

**Comment by Safihre** [comment]
Thanks, fixed!
