### ISSUE TITLE
QQ: abort handling

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#1368]
I haven't been able to find anything to confirm but I believe that when using "abort when can't complete/unwanted file... Etc" it still sends it to the post processor (nzbToMedia) when the "only post process verified jobs" is unchecked.
Just trying to verify this is the case.

**Comment by thezoggy** [comment]
Does nzbtonedia check the status of the download to know if it's good to continue?

**Comment by mgaulton** [comment]
Not that I'm aware of. It seems to just pass params on the command line and never call back. I may be wrong.
The reason I ask is I had jobs where it said aborted but never seemed to call nzbtomedia but now that i'm looking at the recent ones, it does have a Script result in it.
Sorry to bother :) i"ll just close this and slink to a corner lol
