### ISSUE TITLE
Retry unpack fails if category is a number

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1369]
safe_lower(txt) in misc.py assumes it is a string and calls txt.lower(), but if it's a number it is stored as an int.

**Comment by thezoggy** [comment]
what branch/version?

**Comment by puzzledsab** [comment]
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L101

**Comment by thezoggy** [comment]
yes, sab config setup doesnt allow any numbers to be used (for any of the 'named' entries.. like servers/categories/rss) as it has to be a string. are you modifying the .ini manually ?

**Comment by thezoggy** [comment]
this still needs to be looked at.. need to prevent users from using numbers only / convert to string (prepend text?)
