### ISSUE TITLE
rar 5.9

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1381]
just friendly note to update included utilities
https://www.rarlab.com/rarnew.htm

few items that may apply to us (password/repair bug)

**Comment by thezoggy** [comment]
and side note, MultiPar 1.3.0.7 is out as well (also he now has a github page // https://github.com/Yutaka-Sawada/MultiPar )

**Comment by thezoggy** [comment]
our par2-sl is from macpar deluxe 4.1 (which is 5? years old)
I see macpar deluxe 5.1.1 is out now // https://gp.home.xs4all.nl/Site/MacPAR_deLuxe.html
in case we wanna update that as well

**Comment by thezoggy** [comment]
sure

**Comment by thezoggy** [comment]
and for multipar 1.3.0.7:
dev -- https://github.com/sabnzbd/sabnzbd/pull/1384
2.3.x -- https://github.com/sabnzbd/sabnzbd/pull/1386

note that while multipar gui shows 1.3.0.7, the par2/par2j64 command line tools still show  1.3.0.6 (as 1.3.0.7 was a cosmetic gui change), I reported it to upstream but doesnt really matter for our purposes.

**Comment by thezoggy** [comment]
and to note, i have just replaced the existing files on my local windows binary sab 2.3.9 install to test these updates (multipar+unrar)

**Comment by Safihre** [comment]
Wasn't really sure if there was a point in updating the 2.3.x branch, but guess it doesn't hurt.
Thanks!

I last checked the `par2-sl` many many years ago indeed. I do have a MacBook now that I can use to test this update.

**Comment by Safihre** [comment]
@thezoggy I just checked, and the MacPar Delux still includes the exact same `par2-sl` executable as the one we include. Nothing really changed.
We could maybe one day just switch to par2cmdline also for Mac.
