### ISSUE TITLE
sabnzb - fails to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by dutch2005** [sabnzbd/sabnzbd#1388]
sabnzb - fails to run / install on Ubuntu 20.04

The following packages have unmet dependencies:
 sabnzbdplus : Depends: python3-sabyenc (>= 4.0.0) but it is not going to be installed

The following packages have unmet dependencies:
 python3-sabyenc : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is to be installed

Ubuntu 20.04 is suposed to be deployed / released end of this month.

**Comment by sanderjo** [comment]
How did you install?

**Comment by dutch2005** [comment]
updated an Ubuntu 18.04 container to 20.04

Came across this issue.

**Comment by sanderjo** [comment]
> updated an Ubuntu 18.04 container to 20.04

You updated a container's OS? Uhhh, IMHO that's not something you should do.


> Came across this issue.

> As for python3
> 
> I followed the following steps:
> 
> https://sabnzbd.org/wiki/extra/python3.html
> 
> Ubuntu Linux 18.04: via jcfp’s private PPA. See https://forums.sabnzbd.org/viewtopic.php?f=16&t=24447

Be precise what you do where.

**Comment by dutch2005** [comment]
LXC containers can be updates just as a regular container, not using docker..

Using Proxmox - LXC, you can jus update as if its was a VM....

**Comment by dutch2005** [comment]
Version: | 2.3.9 [03c10dc]
-- | --
12m
/root/.sabnzbd/sabnzbd.ini
/usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid --server 192.168.1.20:80
2.7.17 (default, Nov 7 2019, 10:07:09) [GCC 7.4.0] [UTF-8]
OpenSSL 1.1.1 11 Sep 2018


Updated to 20.04 (ran dist update, upgrade, dist-upgrade)

End result: sabnzb wont start and asks for the python3 stuff

**Comment by sanderjo** [comment]
If you're able to run LXC containers, I think you're able to solve the dependencies you mention. It's not a problem on the repo side, IMHO.

**Comment by sanderjo** [comment]
And, the nice thing about containers: Cattle, not Pets. So, if it doesn't work, throw it away, and start with a fresh container.

**Comment by dutch2005** [comment]
> And, the nice thing about containers: Cattle, not Pets. So, if it doesn't work, throw it away, and start with a fresh container.

I did, restored a previous backup and back on 18.04 for now :-)

Got sonarr, radarr, bazarr, tautull and pihole running just fine, only this was giving me some issue's...

we'll see soon(tm) what will (or wont work :-))

thnx for the effort tho.
