### ISSUE TITLE
Dark/night theme not working on latest develop build

### ISSUE THREAD

**Issue by professionaltart** [sabnzbd/sabnzbd#1392]
Fresh OS install made me decide to check out how progress is going on the python3 rebuild.  I'm running 3.7.7 due to upstream issues with Mylar not working on 3.8 when on Windows 10.

Sab 3.0.0-develop [ac70bd8] 
Windows-10-10.0.18362-SP0 (win64)
Python 3.7.7

The build seemed to go ok - followed instructions in https://sabnzbd.org/wiki/extra/python3.html

When I'm in SAB, and go into the config menu via http://localhost:8089/sabnzbd/config/general/ - the theme options for Web interface are:

Glitter - default
Glitter - night
Plush - gold

Default and gold both work after save/restart.  Selecting night has no effect - restart shows default again.  This happens even when selecting night with gold active.

Edit:  probably worth noting I'm using my sabnzbd.ini via 2.3.9 on the previous OS isntall.

**Comment by sanderjo** [comment]
Is this "Glitter - night"? If so, it works for me on my SAB-py3.

**Comment by professionaltart** [comment]
If I manually set web_color and web_color2 to Night (or "Night"), with sab shutdown, restarting it sets color back to "", and leaves color2 as whatever I set it to.

Still not seeing the dark theme.

@sanderjo which branch are you using?

**Comment by sanderjo** [comment]
> @sanderjo which branch are you using?

develop

**Comment by Safihre** [comment]
Pushed a fix, could you try again? Windows-specific problem.
Thanks for reporting!

**Comment by professionaltart** [comment]
Thanks, confirmed working : )

**Comment by Safihre** [comment]
If you find anything else broken: let us know! 💯

**Comment by professionaltart** [comment]
@Safihre sorry for bumping a closed ticket, wasn't sure where else to let you know:

For the past 16 days I have not run into any other issues on that build.
I just pulled the latest dev branch again, so I'll see how that goes!
