### ISSUE TITLE
[py3] from source: "./SABnzbd.py: /usr/bin/python3: bad interpreter: No such file or directory"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1394]
On a certain system (macOS in this case, but can happen on other systems too), with python3 installed and in the path, running SABnzbd-py3, I get:

```
server:sabnzbd sander$ ./SABnzbd.py
-bash: ./SABnzbd.py: /usr/bin/python3: bad interpreter: No such file or directory
```

Reason: on this system python3 is in /usr/local/bin/.

So ... why the hard `#!/usr/bin/python3 -OO` and not `#!/usr/bin/env python3 -OO`. I tried and it works (see below).

**Anyway**: this is just a question / remark for discussion. Another solution / requirement could be that the user / system administrator must create a symbolic link from /usr/bin/python3 to (from?) the existing /usr/local/bin/python3 or /whatever/some/where/python3

With altered she-bang:
```
server:sabnzbd sander$ head -1 SABnzbd.py
#!/usr/bin/env python3 -OO

server:sabnzbd sander$ ./SABnzbd.py -b0
2020-04-17 11:53:58,049::INFO::[SABnzbd:1095] --------------------------------
2020-04-17 11:53:58,049::INFO::[SABnzbd:1096] SABnzbd.py-3.0.0-develop (rev=unknown)
2020-04-17 11:53:58,049::INFO::[SABnzbd:1097] Full executable path = /Users/sander/git/sabnzbd/SABnzbd.py
2020-04-17 11:53:58,049::INFO::[SABnzbd:1107] Platform = posix
2020-04-17 11:53:58,050::INFO::[SABnzbd:1108] Python-version = 3.7.7 (default, Mar 10 2020, 15:43:27)
[Clang 10.0.0 (clang-1000.11.45.5)]
2020-04-17 11:53:58,050::INFO::[SABnzbd:1109] Arguments = ./SABnzbd.py -b0
```

Settings on this system:
```
server:sabnzbd sander$ python3 --version
Python 3.7.7

server:sabnzbd sander$ which python3
/usr/local/bin/python3

server:sabnzbd sander$ /usr/bin/env python3
Python 3.7.7 (default, Mar 10 2020, 15:43:27)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

**Comment by Safihre** [comment]
https://www.google.com/search?q=python+best+shebang
https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/

Short version: all of them are bad in one way. So we stuck to this one.

**Comment by sanderjo** [comment]
OK, fair enough.
I've put `/usr/local/python3`as a requirement into the wiki https://github.com/sabnzbd/sabnzbd.github.io/commit/1d21374bb4c76db8fd40db6f20f59484a339388f
