### ISSUE TITLE
Double extraction

### ISSUE THREAD

**Issue by Spearis666** [sabnzbd/sabnzbd#1395]
OS : Debian sid
sabnzbd rev : 2a8aea43e60756999fd9d7c54d5faf630dffaa52
Post-processing script : no

Hi,

Ive currently experiencing a strange behavior on some nzb i downloaded today. Both of them (by the same uploader, so i assume the same scrambling tech) have been extracted two times. That's annoying since its bd files so i have to launch a command to remove all the duplicate.

The two download where i encountered this behavior was set to +Delete, and main settings is to extract during download. Both download have been repaired. All download from the last week was fine, so i'm pretty sure the problem is with how the upload was scrambled.

It's not the archive content that is duplicate, since i tried to just download with +Repair and 7z x manually, and the archive content is not duplicated.

The .nzb was added by putting them in watch folder, but i'm sure the nzb was downloaded only one time, so i don't understand why he get extracted two times. All the duplicated got named with a (1) before extension. I checked all the duplicates againt they original, and blake2 digest is the same.

If you need log, screenshot, link to the nzb, feel free to ask

Thanks

Edit : third nzb with the problem, same uploader, but this time the nzb just contain one file, so i got 2 times a file of 30 GB, same blake2 digest again

**Comment by sanderjo** [comment]
Hi @Spearis666 

What I normally do in such a situation:
start from scratch with a SAB without configuration, so `sabnzbdplus -f myfreshconfig.ini', fill out just one newssrver in the wizard, and then let SAB download the NZB again and see if it's reproducible.

So, without scripts, settings, sonar/radar/etc.

So ... can you do that?

You could also also share the NZB, but I wonder if I have 60GB available ... 

Furthermore: blake2 digest? Is that in the SSL communication, or within the files?

**Comment by Spearis666** [comment]
Ok i will try with fresh sabnzbd, i just finish testing by disabling direct unpack to see if it's the problem.

No the blake2 digest is by using b2sum, i use this to compute checksum of files.

**Comment by sanderjo** [comment]
> No the blake2 digest is by using b2sum, i use this to compute checksum of files.

OK ... but do _posters_ include a blake2 checksum in their post?

**Comment by Spearis666** [comment]
no no, it's just i used this to compare the file extracted for the archive downloaded and their equivalent renamed with (1), just to be sure i don't remove the good file (assuming one of the two is corrupted).

I use blake2 for upload myself, but i'm sure i just the only one to do this :D

**Comment by albino1** [comment]
@sanderjo, is this not just a dupe of https://github.com/sabnzbd/sabnzbd/issues/1359 which has already been fixed in develop?

**Comment by Spearis666** [comment]
Ok so after testing without direct unpack, ive not encountered the problem. I reactivated direct unpack, and the problem won't happened...

So i runned a clean instance of sab, and reproduced almost the same step when the double extraction happened.

1. Putting TEST1.7z (containing TEST1.nzb) and TEST2.7z (containing TEST2.nzb) into watch folder
2. Both are added to download queue, TEST1 start download with direct unpack starting some second after
3. TEST1 finish downloading, so he goes to history for checking
4. TEST2 is starting download, starting direct unpack some second after.
5. TEST1 have 1 malformed article, so go back from history to download to get .par2, pausing download of 2nd .nzb
6. TEST1 finish, and launch repair / extraction.
7. TEST2 resume download, finish downloading, so he goes to history for checking
8. TEST2 direct extraction is finished, awaiting the extraction end of TEST1 for moving to final folder
9. TEST1 finish extracting and move to final folder, TEST2 is moving to final folder

And that no happened...so i do the same step on my old instance of sab, and that won't happened.

I remember that happened 3/4 times in the past week, but because i'm busy ive not taken attention. But 3 times the same day,...

Ah ive searched for "double" in issue list, Sorry ;)

**Comment by sanderjo** [comment]
It's not clear to me if you can reproduce the problem. If not, it's hard to say what is going on.
Furthermore, it's wise to run the uptodate github version.

**Comment by Safihre** [comment]
I would also be interested to know what version of unrar is installed on the system? And indeed if updating to the latest version of Sabnzbd fixes it. This could be related to the new unrar version for which we only fixed it last week.

**Comment by Spearis666** [comment]
Yes i updated, will let you know if that happen again. Well, the TB incoming each weeks i will quickly view if that happen.

Computer is like when you lose something, you never find when you search, and you find when you completely forget about it ^^

Actually the unrar version is 5.61, to be honest i never ported interest to it since i mostly use 7z for my archive, but on newsgroup there is a lot of rar so...maybe it can be a good idea to update ^^
