### ISSUE TITLE
queue - filter by category

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1403]
is there really not a way to limit your queue history to a category?
I dont see anything nor some hidden way to do it in the search box with `cat:category_name` or something.

**Comment by Safihre** [comment]
It's not a bad idea at all, just never got around to implementing it. 
Could add some like `cat:` and `priority:` etc.

**Comment by thezoggy** [comment]
I found that I already had a issue open for this a few years ago 🤣
