### ISSUE TITLE
Recursive unpacking behavior with multi-part 7z

### ISSUE THREAD

**Issue by Spearis666** [sabnzbd/sabnzbd#1404]
OS : Debian sid
sabnzbd rev : fba38a8
Post-processing script : no

Hi,

Actually i have uploaded something in multi-part 7z, and inside another .7z (in one part).
I i download with "Recursive unpacking", it extract the multi-part, and extract the 7z inside (which is fine)

But if i disable "Resursive unpacking", it assemble the multi-part into one 7z, and put into incoming, without doing any extraction.

Is this the normal behavior ?

**Comment by Safihre** [comment]
Is it possible to either share the NZB or the logs?

**Comment by Spearis666** [comment]
I can't post the .nzb (because of the content), but i've made a test .nzb with the problem, so like my .nzb with the problem, a 7z inside a multi-part 7z with a password and "Recursive unpacking" unchecked.

Here how i generated everything :
# dd if=/dev/zero of=dummy bs=100M  count=1
# 7z a "dummy.7z" dummy
# 7z a -p12345 -v100b "splitted_dummy.7z" dummy.7z

Archive password is : 12345
Size to download : 666 bytes

[splitted_dummy.zip](https://github.com/sabnzbd/sabnzbd/files/4542198/splitted_dummy.zip)

**Comment by sanderjo** [comment]
I downloaded with SAB 3, and it unpacks correctly to the 100MB file.

**Comment by Spearis666** [comment]
Have you disabled recursive unpacking ? Actually the extraction is not the problem (i also get the 100 mb file with recursion), the problem is without, the .nzb is downloaded, sab merge the multi part in one file, and put the result into incoming.

**Comment by sanderjo** [comment]
> Have you disabled recursive unpacking ?

No. Just the default SAB setup.

Why do you want SAB to not unpack?

**Comment by Spearis666** [comment]
I don't want to not unpack, i want unpack without recursion, i explain.

Actually what i have uploaded is a collection, where final storing is one 7z for each file of the collection. Because of the content, i have to 7z each 7z with password and obfuscated name, using multi-part because i always share thing with files splitted from 50M to 250M.

Now i have to redownload all .nzb for checking everything was good, but if i want to get the final 7z of each file of the collection, i must use recursive unpacking disabled, so the multi-part obfuscated passworded is extracted, and the final 7z is ready into incoming.

But actually i only get the multi-part (assembled & passworded) into one .7z (so sab is just merging the part), where i have to get the final .7z without password. (assuming the first extraction was done). 

Recursing extraction is about extracting archive inside archive (well the tips say that), not stopping first level extraction.

**Comment by sanderjo** [comment]
Too hard for me to understand the what & why. Sorry.

**Comment by Spearis666** [comment]
The only thing to retain is that disabling recursing unpacking actually actually just stop first level unpacking (at least for 7z, not tested for RAR).

**Comment by Safihre** [comment]
@Spearis666 just to be check: are you using Usenet to backup personal data?

**Comment by Spearis666** [comment]
@Safihre no don't worry ^^

**Comment by Safihre** [comment]
I can't reproduce this, if I download the dummy file with recursive=false, then it just unpacks 1 time and gives `splitted_dummy.7z` in the folder.

**Comment by Ski-lleR** [comment]
Yeah and that's the point !

splitted_dummy.7z is a multi-part containing another dummy.7z, so you just reproduced the error ^^

The extraction process just assembled the multi-part splitted_dummy.7z, so you get one 7z, but it's splitted_dummy.7z, who contain dummy.7z (that's why i named them differently, to make all of you understand the problem).

**Comment by Spearis666** [comment]
Yeah and that's the point !

splitted_dummy.7z is a multi-part containing another dummy.7z, so you just reproduced the error ^^

The extraction process just assembled the multi-part splitted_dummy.7z, so you get one 7z, but it's splitted_dummy.7z, who contain dummy.7z (that's why i named them differently, to make all of you understand the problem).

**Comment by thezoggy** [comment]
recursive=false means you stop after the first layer.
there is a tactic called a zip bomb which would take advantage if one was to 'reset' the recursive flag on each iteration which would allow for infiniti nesting..

**Comment by Safihre** [comment]
Aaaah, so to answer the original question, like @thezoggy says:
> Actually i have uploaded something in multi-part 7z, and inside another .7z (in one part).
I i download with "Recursive unpacking", it extract the multi-part, and extract the 7z inside (which is fine)

> But if i disable "Resursive unpacking", it assemble the multi-part into one 7z, and put into incoming, without doing any extraction.

> Is this the normal behavior ?

Yes! 👍

**Comment by Spearis666** [comment]
Ok, so i will make my own patch so it extract at least the multi-part.

For me the option is not clear, since assembling a multi-part is not extracting, so actually it's not even do the first layer extraction.

**Comment by Safihre** [comment]
The multi-part is extracted using the 7zip executable, so of course it's the first layer.

**Comment by Spearis666** [comment]
Well, when i extract splitted_dummy.7z.00x manually with 7z x, i get dummy.7z who is inside, but with sabnzbd, i get splitted_dummy.7z.

**Comment by Safihre** [comment]
Finally, we get to the point, you should have mentioned that earlier!
The reason is that we unpack using the `-tsplit` option in the first round. We do this because [older versions of 7zip](https://askubuntu.com/a/420714) on Linux can't handle split-archives. So they require to first use `-tsplit` and only then do the "real" extraction.

**Comment by Spearis666** [comment]
That's what i say in the op :
But if i disable "Resursive unpacking", it assemble the multi-part into one 7z, and put into incoming, without doing any extraction.

**Comment by Spearis666** [comment]
Ok so removing -tsplit did the job, thanks for pointing me out where to look ;)

**Comment by thezoggy** [comment]
Why not use the flat unpack option?
