### ISSUE TITLE
[dev-mode] sabtraylinux.py: DeprecationWarning

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1414]
Just a note:

Running with `python3 -X dev -X tracemalloc=5  SABnzbd.py` I get the DeprecationWarning messages below.

```
2020-05-01 07:34:44,250::INFO::[config:851] Writing settings to INI file /home/sander/.sabnzbd/sabnzbd.ini
/home/sander/git/sjo-sab-1mei2020/sabnzbd/sabtraylinux.py:70: DeprecationWarning: Gtk.StatusIcon.set_from_file is deprecated
  self.statusicon.set_from_file(self.icon)
/home/sander/git/sjo-sab-1mei2020/sabnzbd/sabtraylinux.py:73: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  self.statusicon.set_tooltip_text(self.tooltip)
/home/sander/git/sjo-sab-1mei2020/sabnzbd/sabtraylinux.py:66: PyGIDeprecationWarning: GObject.timeout_add is deprecated; use GLib.timeout_add instead
  GObject.timeout_add(self.updatefreq, self.run)
2020-05-01 07:34:44,709::INFO::[SABnzbd:377] SABYenc module (v4.0.1)... found!
```

**Comment by jcfp** [comment]
Seems to whole statusicon thing is to be dropped in gtk+ v4, without replacement. In their customary infinite wisdom, Gnome docs actually suggest using (desktop) notifications instead - which obviously cannot replace a statusicon as used in sab and many other application.

Seems we're not alone in this, as the linuxmint devs have come up with [something](https://blog.linuxmint.com/?p=3795) (under "System Tray Icons"). I'll look into porting to XApp.StatusIcon when I find myself with too much time on my hands.

**Comment by jcfp** [comment]
@sanderjo could you try [this commit](https://github.com/jcfp/sabnzbd/commit/837f056af3614e2ba38921d845613e93bcc98daa) on a 20.04 install?

It seems to work in my VM but I get some weird msg in the console from lower level gdk stuff.
> Gdk-CRITICAL **: 19:40:38.509: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by sanderjo** [comment]
Of course, but you have to tell me how to apply that patch. I did a `git clone https://github.com/jcfp/sabnzbd.git sab-jcfp`, but that does not contains the patch / commit, and I don't see branches.

**Comment by sanderjo** [comment]
Oh, wait:

```
sander@witte2004:~/git/sab-jcfp$ grep -irn "from gi.repository import Gtk, GLib" *
sander@witte2004:~/git/sab-jcfp$

sander@witte2004:~/git/sab-jcfp$ git cherry-pick  837f056af3614e2ba38921d845613e93bcc98daa
[develop 677096ec] fix deprecation warning in linux sabtray
 Author: jcfp <linux@jcf.pm>
 Date: Sat May 2 17:57:53 2020 +0200
 1 file changed, 42 insertions(+), 21 deletions(-)
sander@witte2004:~/git/sab-jcfp$ 
sander@witte2004:~/git/sab-jcfp$ grep -irn "from gi.repository import Gtk, GLib" *
sabnzbd/sabtraylinux.py:23:from gi.repository import Gtk, GLib
sander@witte2004:~/git/sab-jcfp$ 
```

**Comment by sanderjo** [comment]
I get this:
```
sander@witte2004:~/git/sab-jcfp$ python3 -X dev -X tracemalloc=5 ./SABnzbd.py 
<snip>
/home/sander/git/sab-jcfp/sabnzbd/sabtraylinux.py:72: DeprecationWarning: Gtk.StatusIcon.set_name is deprecated
  self.statusicon.set_name("SABnzbd")
/home/sander/git/sab-jcfp/sabnzbd/sabtraylinux.py:73: DeprecationWarning: Gtk.StatusIcon.set_visible is deprecated
  self.statusicon.set_visible(True)
/home/sander/git/sab-jcfp/sabnzbd/sabtraylinux.py:91: DeprecationWarning: Gtk.StatusIcon.set_from_file is deprecated
  self.statusicon.set_from_file(self.icon)
/home/sander/git/sab-jcfp/sabnzbd/sabtraylinux.py:94: DeprecationWarning: Gtk.StatusIcon.set_tooltip_text is deprecated
  self.statusicon.set_tooltip_text(self.tooltip)
```

**Comment by jcfp** [comment]
Cherry-picking would get you the correct code, you could also have checked out the trac-deprec branch in git directly. I should have been a bit less concise there but was pressed for time yesterday.

Anyway, the DeprecationWarnings from Gtk.StatusIcon.* you still see indicated use of what is now the fallback codepath. Did you install 'python3-xapp' and 'gir1.2-xapp-1.0'? If you run sab with debug option -l2 it will print a msg about whether or not xapp is used.

**Comment by sanderjo** [comment]
Packages were not installed. After installing:
With `./SABnzbd.py -l2`:

`2020-05-03 11:16:53,065::DEBUG::[sabtraylinux:29] XApp found: <XAppProxyModule <IntrospectionModule 'XApp' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/XApp-1.0.typelib'>>`

Looks good, right?



Checking & installing packages:
```
sander@witte2004:~/git/sab-jcfp$ dpkg -l python3-xapp
dpkg-query: no packages found matching python3-xapp
sander@witte2004:~/git/sab-jcfp$ dpkg -l gir1.2-xapp-1.0
dpkg-query: no packages found matching gir1.2-xapp-1.0

sander@witte2004:~/git/sab-jcfp$ sudo apt install -y python3-xapp gir1.2-xapp-1.0

```
Afterwards:
```
sander@witte2004:~/git/sab-jcfp$ dpkg -l python3-xapp
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python3-xapp   1.8.1-2      all          Python 3 XApp library
sander@witte2004:~/git/sab-jcfp$ dpkg -l gir1.2-xapp-1.0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-=================================
ii  gir1.2-xapp-1.0 1.6.10-2     amd64        Introspection data for Xapp
sander@witte2004:~/git/sab-jcfp$ 
```

**Comment by jcfp** [comment]
Yeah that debug msg is the one you get when XApp is used. Deprecation warnings should be gone with that, so if you didn't get any tracebacks and the trayicon functions all worked, then all is well.
