### ISSUE TITLE
sab3 - migrate SSL Ciphers: RC4-MD5 -> AES128-SHA

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1420]
with sab 3.x it uses newer openssl 1.1+ which no longer does RC4-MD5, as users would see "'No cipher can be selected.'" error and probably have no clue whats going on. We should migrate it to AES128-SHA to help the user as that would be the closest match // history: https://github.com/sabnzbd/sabnzbd/issues/1286

**Comment by sanderjo** [comment]
(Disclaimer: I'm against filling out a cipher. And if a user is so clever to do it anyway, I think he/she should be clever enough to solve potential problems.)

What do you propose: on startup, SAB should overwrite/replace? Without warning, without confirmation? Each time? What if user fills out in the Server settings GUI?

What if there is another wrong cipher, like AES1128-SHA (note the typo)? 

What if a another cipher is removed from openssl somewhere in the future?

~~Based on my disclaimer, and the above, I would say: at startup, read filled out ciphers, and check if they exist in openssl (see code snippet below). If not, give a fat, clear ERROR to the user (and advice "Remove incorrect cipher"), and let him/her solve it.~~

Oh, wait, easier: change current

>  'No cipher can be selected.' 

to 

> 'No cipher can be selected. Remove the unknown cipher setting for this server in Server settings'

I know @Safihre just loves text changes. ;-)


Oh, and the removal of RC4-MD5 should be in the 3.0.0 release notes, @Safihre 

![image](https://user-images.githubusercontent.com/1273502/81373571-54ad7180-90fd-11ea-8323-cbeb6b668fc2.png)


```
# show available ciphers:
import ssl
ctx = ssl.SSLContext()
cipherlist = [cipher["name"] for cipher in ctx.get_ciphers()]
print("AES128-SHA" in cipherlist)
print("SHA1-BAD" in cipherlist)
```

**Comment by sanderjo** [comment]
There you go: two lines of code, no change of existing texts:

![image](https://user-images.githubusercontent.com/1273502/81374325-48c2af00-90ff-11ea-8e4f-89bedbbfeec6.png)

**Comment by thezoggy** [comment]
if a user put in a cipher its because of two reasons.. 
1) one they are smart enough and were wanting to control what is used.
2) they were told to put in RC4-MD5 because they read it in the wiki/were told because they had speed issues.. which could have been done years ago

now if the user actively knows that sab 3.x uses newer openssl and knew that at some point in the past they set this cipher but no longer is supported.. yes they will probably figure out why sab is 'broken' by changing settings/starting over/googling.  but lets be real, most of the masses wont know/think about it (because they probably havent thought about it in forever).

1) we should test/handle invalid ciphers in general more gracefully,
like doing a db migration, we should check if what the user has set even works, if not then clear the custom setting and log/warn accordingly.
2) for the specific niche RC4-MD5, we should catch it failing to work and just migrate that one to the openssl 1.1.x compatible version

**Comment by Safihre** [comment]
I updated the advice page to not mention RC4-MD5 anymore. I users run into this problem they will be notified due to the error. 
It isn't pretty, but also an "Advanced setting" that was set by the user.
I will also include it in the release-notes!
