### ISSUE TITLE
Right-to-Left Support in SABnzbd

### ISSUE THREAD

**Issue by IONILz** [sabnzbd/sabnzbd#1430]
Hi,

Please consider to add support of right-to-left display in SABnzbd. Hebrew is written from right to left.

I can help with testing it.

**Comment by puzzledsab** [comment]
Are you still there, @IONILz ? I did some small tests, and I realize that I have no idea how it should look in rtl-format. I have uploaded an image here: https://imgur.com/a/YmEeNdk

The first is with dir="rtl" attribute and all div right/left floats reversed. The one in the middle is standard ltr, and the one on the bottom is just dir="rtl".

If you could use a paint program to pick out every elements (images, text and numbers) and put them in the order they should be in proper rtl it would be helpful. Remember that it's the order that is important, not that they line up perfectly.

**Comment by Safihre** [comment]
I just checked the statistics, and in the past 1 year only 18 people (0.02%) selected Hebrew during the setup wizard.
So code changes to add RTL-support should not be too invasive, since it's an extremely small userbase.

**Comment by IONILz** [comment]
> 
> 
> Are you still there, @IONILz ? I did some small tests, and I realize that I have no idea how it should look in rtl-format. I have uploaded an image here: https://imgur.com/a/YmEeNdk
> 
> The first is with dir="rtl" attribute and all div right/left floats reversed. The one in the middle is standard ltr, and the one on the bottom is just dir="rtl".
> 
> If you could use a paint program to pick out every elements (images, text and numbers) and put them in the order they should be in proper rtl it would be helpful. Remember that it's the order that is important, not that they line up perfectly.

The third section would be just fine. In case it is possible without too much effort, I made a screenshot for a better result. Again, the third option is good enough and much better than the current state of SABnzbd.

https://imgur.com/a/PzamYhJ

**Comment by puzzledsab** [comment]
@IONILz : You can test it now by going here: https://github.com/sabnzbd/sabnzbd/pull/1776/checks?check_run_id=1808945630
Then select a download from the "Artifacts (5)" drop down located at the right side of the screen.

Also take a look at the popups. That's the file lists in the queue, the history queue, add NZB and the wrench symbol.

**Comment by IONILz** [comment]
I started testing it. On second thought, the "Queue", "Remaining size" and "Free Space" (and the list of working jobs) should be like in the first example. I made a new screenshot and wrote some comment on it. Also if it is possible to add RTL support in the quick wizard and in the settings pages - it would be great :P
I will keep testing it in the following days and I will edit the current translation that I've made in order to make it display properly with the new RTL support.

https://imgur.com/1AJc8W2

**Comment by IONILz** [comment]
@puzzledsab I started testing it. On second thought, the "Queue", "Remaining size" and "Free Space" (and the list of working jobs) should be like in the first example. I made a new screenshot and wrote some comment on it. Also if it is possible to add RTL support in the quick wizard and in the settings pages - it would be great :P
I will keep testing it in the following days and I will edit the current translation that I've made in order to make it display properly with the new RTL support.

https://imgur.com/1AJc8W2

**Comment by puzzledsab** [comment]
The config link is a bit messy to fix but I've tried to changed the rest on the front page. The order in the remaining/total MB for each queue element didn't make sense (the slash was after the first MB from the left) so I've locked it to ltr. Because of how the elements are structured I couldn't find a way to fix one thing without breaking it in a different way.
https://github.com/sabnzbd/sabnzbd/pull/1776/checks?check_run_id=1815049596

The wizard and config pages are harder because the browsers don't know how to rearrange the elements. I think they either have to be converted to tables or need a lot of tweaking.

**Comment by puzzledsab** [comment]
Hm, I think I'll misunderstood what you meant with the "Queue", "Remaining size" and "Free Space" part. I'll try again.

**Comment by IONILz** [comment]
The order in the remaining/total size is now fixed.
It would be better to leave the lines of jobs as LTR since those lines are not wirtten in Hebrew anyway. I made a screenshot.
Also, I made some changes to some strings in the Hebrew translation. How can I test the new translation?

https://imgur.com/o9FLRwc

**Comment by puzzledsab** [comment]
I've tried to adapt to the last changes here: https://github.com/sabnzbd/sabnzbd/pull/1776/checks?check_run_id=1817409559

I tried to adapt the wrench page as well but I don't know enough about styling to make it work.

**Comment by IONILz** [comment]
The main page is almost perfect :) I noticed 2 small issues.
1). The search field that appears when "multi-operations" button is pressed - the text and the icon are displayed on each other.
2). The menu of the sort button should be aligned to the right.

I attached a screenshot.

https://imgur.com/QNXowwK

**Comment by puzzledsab** [comment]
@Safihre : Do you know how to move the magnifying glass in https://imgur.com/QNXowwK to the left? It stays to the right no matter what I try.

**Comment by Safihre** [comment]
It's a css class, so probably hard to move. I can give a try in the end for the difficult parts if @IONILz approves the main changes :)

**Comment by puzzledsab** [comment]
I have updated the drop down boxes here: https://github.com/sabnzbd/sabnzbd/pull/1776/checks?check_run_id=1818259079

**Comment by IONILz** [comment]
@Safihre @puzzledsab  The main page looks good :)

 I have small fixes to ask:
1). There is an unnecessary space near the menu button (≡).
https://imgur.com/80qm7mD
2). The window "Edit NZB Details - Password" - it would be better to leave this window in LTR.
https://imgur.com/xh3oAB8
3). The tooltip "Edit NZB Details - Password" is a combination of 2 different strings in the translation, and since it contains non Hebrew letters ("NZB"), RTL support is needed here in order to make this string to be displayed correctly.
https://imgur.com/SAJkLKl
4). The tooltip "Config SABnzbd" (the gear icon) - same as number (3).
https://imgur.com/SAJkLKl

**Comment by puzzledsab** [comment]
Do you mean that the shutdown page should be right-aligned? I assume the text is ok?

**Comment by IONILz** [comment]
Yes, the shutdown page should be right-aligned. I've already fixed the text on Transifex.

**Comment by puzzledsab** [comment]
2, 3, 4 and the shutdown should be fixed, but the commit with 4 didn't build correctly so it's not included right now: https://github.com/sabnzbd/sabnzbd/runs/1822700752

I was in doubt about whether to fix 4 or not but I ended up hacking it with if and unless. I guess the lesson is to always include the whole string in the translation.

I couldn't figure out how to fix 1.

**Comment by IONILz** [comment]
2). This issue was fixed almost completely - the title of the job needs to be align to the left too.
3). Fixed
4). Not fixed
5). (shutdown page) Fixed

Will it be possible to align the settings page too? :3

**Comment by IONILz** [comment]
UPDATE:
2). Please align to the right the tooltip "Hold shift key to select a range"

**Comment by puzzledsab** [comment]
I don't think there's any alignment to the tooltip? It's just a mouse-over and appears where browser decides to put it.

**Comment by IONILz** [comment]
Ohh I see and is there no option to put a genral alignement code at the top of the page to make the page RTL?

**Comment by puzzledsab** [comment]
I have made a test with just dir=rtl here: https://github.com/sabnzbd/sabnzbd/pull/1776/checks?check_run_id=1830502442

You can check if you think it is preferable to ltr overall. There are some issues with checkboxes being placed on top of the text, and the series sorting on the sorting page doesn't look good because the file name is reversed.

**Comment by Safihre** [comment]
https://github.com/sabnzbd/sabnzbd/actions/runs/542666186
I made some changes to make the Config a bit nicer and move all the changes to CSS.
Any major things that need changing?

**Comment by IONILz** [comment]
It looks perfect! Please include it in the next version of SABnzbd :]
I have a tiny request to ask: after the button "Edit NZB Details - Password" is pressed, please leave the title of the window (the name of job) in LTR display. the text there is non-Hebrew.

**Comment by Safihre** [comment]
Added in 3.2.0!
