### ISSUE TITLE
Testing email notification seems to always says "OK" when it's not

### ISSUE THREAD

**Issue by granbebe** [sabnzbd/sabnzbd#1431]
I got an issue with the 3.0.0Alpha1 on Ubuntu 18.04LTS.
This version was unable to send email notifications.
So I use the configuration screen to test the email notification. When clicking on the test button, the response was instantaneous with a success. But no mail received.
I start adding some more logs on emailer.py to finally find out the path where the templates are was invalid.

To reproduce, just add a signe quote after the word [email] inside constants.py for the value DEF_EMAIL_TMPL.

My own issue is solved as I rewrote the variable with a valid value.
But I think that the test should be more precise and detect this kind of misconfiguration. 

This Githbub issue is a duplicate of the following thread on the sabnzb forum : 
https://forums.sabnzbd.org/viewtopic.php?f=11&t=24731

Thanks

**Comment by thezoggy** [comment]
per your forum post, you are saying its a packaging issue from jcfp and not related to sab source but sab should handle this scenario better if it cant load the template?

**Comment by granbebe** [comment]
Python isn't a language I use, but I understand to code to work exactly the same if the template is unavailable because it does not exist, or the folder does not exist, or the path is wrong or the system does not allow read access on it.

Maybe a simple solution could be that instead of just not doing anything if the template isn't readable, the method could return an error saying it can't access the template XXX. That should be enough to display an error on the test notification page. Or even just add a log to help for debugging.

I do understand that, in normal cases, this will be a no-issue.
But because I struggled on it, I thought it can be handled better.

**Comment by Safihre** [comment]
You are right, this was handled badly. Implemented a fix.
