### ISSUE TITLE
Configurable ini.bak location 

### ISSUE THREAD

**Issue by Fish2** [sabnzbd/sabnzbd#1436]
Any Chance of adding a configurable config backup location / dir

**Comment by sanderjo** [comment]
If you run SABnzbd from source (Linux?), in sabnzbd/config.py check out this line:

`bakname = filename + ".bak"`

HTH

**Comment by Safihre** [comment]
We could add that, but what is really the use-case?
Trying to only add new options if it would benefit >25% of users. SABnzbd already has so many options and switches.

**Comment by thezoggy** [comment]
One could easily cron a task to back up the file manually or move backup files to another spot as well. But really you'd be better off backing up the admin folder in general..

**Comment by Fish2** [comment]
I currently do a cron but Plex and sonarr have it build in so was interested in having sat do the same

**Comment by Safihre** [comment]
I think this will not be a feature we will want to support, sorry! 😞
