### ISSUE TITLE
Files without par2 - rename files based on sfv

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#1438]
Is it possible that sabnzbd can rename downloaded files as they are named in nzb file subject, as in subject they got original filename as it should be?

**Comment by Safihre** [comment]
No, because we trust filenames in this order: par2, yenc and only then NZB-name.
This is mostly because the NZB-name is often messed up by posters, if they wrongly place the quotes etc..
Sorry!

**Comment by scriptzteam** [comment]
Erm, what about special setting to trust nzb filenames? it could really help a lot ;) if not we will code ourself :P

**Comment by Safihre** [comment]
Why not include a par2 file? Or maybe a sfv even?

**Comment by scriptzteam** [comment]
Oh *.sfv are totally there, i forgot about that, so it will rename based on crc32 from sfv right? :)

**Comment by Safihre** [comment]
Yeah, but haven't tested this yet a lot in 3.0.0. Maybe if you send me an example NZB I can test it in SABnzbd 3.0.0. Safihre@sabnzbd.org

**Comment by z3r0byt3s** [comment]
i tested in SABnzbd 3.0.0 Alpha 2 but it wont do anything like rename based on crc32 from sfv file, is there something i need to turn on ?

**Comment by Safihre** [comment]
No, it seems you are right. It doesn't rename. But that's something I would like to implement 👍

**Comment by z3r0byt3s** [comment]
That would be sooo cooool, thx muuchhh :)

**Comment by sanderjo** [comment]
@Safihre 

Does the reftestnzb help? https://raw.githubusercontent.com/sanderjo/NZBs/master/obfuscated-posts/reftestnzb-obfuscated-rar-with-sfv---no-par2-cfe580502ff0.nzb

Currently SAB says 

> Some files failed to verify against "myimportant"

so even the deobfuscator does not kick in ... SAB stops at the sfv. :-(

**Comment by scriptzteam** [comment]
just parse lines from sfv, for each line get crc32 and original name from that given line, then do crc32 check against downloaded files, those files which match crc32 rename based on sfv

**Comment by Safihre** [comment]
@sanderjo the sfv's could also fix the names of non-rar-files, not all posts are rar's!

**Comment by scriptzteam** [comment]
yup, they can be anything like mp3 or flac etc ...

**Comment by sanderjo** [comment]
@Safihre do you want me to solve this?

based on code crc_check() we need a crc_calc()
and in try_sfv_check(), if it fails, try a rename ... ?

**Comment by sanderjo** [comment]
@Safihre 

I've created an NZB with opensource music (MP3's), obfuscated, no rar / par2, with SFV:
https://raw.githubusercontent.com/sanderjo/NZBs/master/obfuscated-posts/reftestnzb_OpenSource_Music_mp3_obfuscated_with_SFV_31a45da9849e.nzb

**Comment by Safihre** [comment]
Fixed it, will be included in 3.0.0!
If there's exotic SFV's it might fail.. It's not a super reliable file format.

**Comment by sanderjo** [comment]
Nice!

Works for https://raw.githubusercontent.com/sanderjo/NZBs/master/obfuscated-posts/reftestnzb_OpenSource_Music_mp3_obfuscated_with_SFV_31a45da9849e.nzb

However, with https://raw.githubusercontent.com/sanderjo/NZBs/master/obfuscated-posts/reftestnzb-opensource-music-obfus-SFV-two-missing-files-b228bce53692.nzb SAB does it's job correctly, but says 

> Some files failed to verify against "my_sfv.sfv"

SAB is too harsh for itself: it finds two files in the SFV, which are not in the post, and says it failed.
But SAB should think "Hey, all available files were nicely renamed, so ... everyhting fine and I'm done".

**Comment by Safihre** [comment]
It's a verification step, so it needs to verify the integrity basd on a reference. So if the reference says there should be 2 more files, then the download failed. Par2 works just the same. 
Additionally, in case a file is damaged its crc32 changes. So the code can't know if a file is actually missing or damaged, since it can't detect the damaged file (that might have a obfuscated name) anymore based on the crc32.

**Comment by sanderjo** [comment]
Ok, fair enough
