### ISSUE TITLE
Fedora 32 Unable to start

### ISSUE THREAD

**Issue by mdl054** [sabnzbd/sabnzbd#1441]
May 12 16:23:26 fedora systemd[1]: Starting SABnzbd Daemon...
May 12 16:23:26 fedora python[125989]: detected unhandled Python exception in '/opt/sabnzbd/SABnzbd.py'
May 12 16:23:26 fedora python[125989]:   File "/opt/sabnzbd/SABnzbd.py", line 20
May 12 16:23:26 fedora python[125989]:     print "Sorry, requires Python 2.7."

Fedora 32. Commenting that line out doesn't help, just continues to complain about other dependencies missing. All are installed including 2.7.

Any ideas?

**Comment by sanderjo** [comment]
Python versus python2 versus python3 ?

**Comment by mdl054** [comment]
~> sudo dnf install python python2 python3
Last metadata expiration check: 2:46:17 ago on Tue 12 May 2020 06:33:04 PM EDT.
Package python-unversioned-command-3.8.2-2.fc32.noarch is already installed.
Package python27-2.7.18-1.fc32.x86_64 is already installed.
Package python3-3.8.2-2.fc32.x86_64 is already installed.

**Comment by sanderjo** [comment]
Yeah, great, but what does `python --version` tell you?

Anyway: run `python2 /opt/sabnzbd/SABnzbd.py` ... what does that give?

**Comment by mdl054** [comment]
Sorry if I'm not providing the right information, I'm still learning.

~> python --version
Python 3.8.2

master /opt/sabnzbd> python2 /opt/sabnzbd/SABnzbd.py
The Python module Cheetah is required
exit 1

master /opt/sabnzbd> sudo pip install Cheetah3
Requirement already satisfied: Cheetah3 in /usr/local/lib64/python3.8/site-packages (3.2.4)

**Comment by mdl054** [comment]
Confirmed, thank you for your help. python was symlinked to python 3. Also.. 

Fedora 32 does not have python2-cheetah in its repositories. Manually download and install the rpm for python2-cheetah from the Fedora 30 repository https://fedora.pkgs.org/30/fedora-x86_64/python2-cheetah-3.1.0-7.fc30.x86_64.rpm.html


To execute directly python2 /opt/sabnzbd/SABnzbd.py works after manually installing Python2-cheetah

If you made a Systemd unit file then change 

ExecStart=/usr/bin/python /opt/sabnzbd/SABnzbd.py --daemon --config-file=/opt/sabnzbd/sabnzbd_config.ini -s 0.0.0.0

to 

ExecStart=/usr/bin/python2 /opt/sabnzbd/SABnzbd.py --daemon --config-file=/opt/sabnzbd/sabnzbd_config.ini -s 0.0.0.0

Everything should work then

**Comment by sanderjo** [comment]
> Confirmed, thank you for your help. python was symlinked to python 3.

And there is a reason for that: python2 is on it's way out.

So we have for you: SABnzbd 3.0.0 alpha 2, based on python3. See https://github.com/sabnzbd/sabnzbd/releases
And see https://sabnzbd.org/wiki/extra/python3.html for linux incl fedora instructions.
