### ISSUE TITLE
Alternative Retrys 

### ISSUE THREAD

**Issue by ninken** [sabnzbd/sabnzbd#1442]
This is more of a request, it could be the next big thing too. 
If parts of a NZB articles files fail, could it find alternatives ways to fill in the missing chunks? 

Allot of NZB has a torrent brother. I'm not sure if the NZB XML format could also contain a torrent tracking data, where if the file fails the CRC check that you can add a small opensource torrent application to grab the missing parts, if it stored in the NZB file.  

It would really add some redundancy to this process of downloading.

**Comment by Safihre** [comment]
While I see where you are coming from with this idea, it's really very much out of the scope of SABnzbd.
