### ISSUE TITLE
The snap package doesn't work on Manjaro 20. Any chance to make it Flatpak?

### ISSUE THREAD

**Issue by spirulin** [sabnzbd/sabnzbd#1443]
So it installs the package and when I check the snap list it's there. But doesn't show in the Application menu. Even after a restart. 
Snaps as a whole are trash to be honest.
I use Flatpaks for some stuff that are not in the repo and they work times better than snaps, they are faster and have no problem installing or launching them.

Snap list output:
sabnzbd            2.3.8                       316   latest/stable  safihre       -

trying to install it again just to check it's installed:
snap "sabnzbd" is already installed, see 'snap help refresh'

trying to start it:
sabnzbd
bash: sabnzbd: command not found

Manjaro 20 XFCE fully updated.
Tried installing it from Pacman - same result.
Terminal - same result.

**Comment by Safihre** [comment]
I think you'll have to do a bit more debugging yourself as I have never heard of Manjaro.. The snap-package is already over 1 year old and is active for many people, so I am 99% sure it works as it should. So seems OS-specific.
Maybe you can try the `edge` snap-package?
