### ISSUE TITLE
SAB-3 RSS: "ERROR DURING SCHEDULER EXECUTION dictionary changed size during iteration"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1444]
Not a big thing, but to be complete:

While setting up RSS feed http://www.nzbstars.com/?page=rss and playing with the filters, i got the traceback below. Maybe some race condition with/while changing the filter word?

Just a minor hickup. After setting up, the fetching from the RSS feed went OK

SAB-3, cache-skip

```
ERROR DURING SCHEDULER EXECUTION dictionary changed size during iteration
Traceback (most recent call last):
  File "/home/sander/git/sab-13mei/sabnzbd/utils/kronos.py", line 300, in __call__
    self.execute()
  File "/home/sander/git/sab-13mei/sabnzbd/utils/kronos.py", line 311, in execute
    self.action(*self.args, **self.kw)
  File "/home/sander/git/sab-13mei/sabnzbd/rss.py", line 88, in run_method
    return __RSS.run()
  File "/home/sander/git/sab-13mei/sabnzbd/rss.py", line 555, in run
    for feed in feeds.keys():
RuntimeError: dictionary changed size during iteration
```
![image](https://user-images.githubusercontent.com/1273502/81904146-26c7a180-95c3-11ea-80e9-6a45fd694743.png)

**Comment by Safihre** [comment]
This only happens indeed when you are changing the feed while it is being parsed.

**Comment by sanderjo** [comment]
So ... catch the traceback and pass?

**Comment by jcfp** [comment]
You don't want to outright hide errors in kronos that way; it's used for all scheduling, not just rss.

This particular problem is specific to rss feeds and should be fixed/handled in that code.
