### ISSUE TITLE
reject_duplicate_files removed from SABnzbd 3.0.0

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1453]
Oops. 
Need to restore this.

**Comment by x-limitless-x** [comment]
Is this restored? I am having an issue with duplicate NZB's being downloaded and the normal **DUPLICATE** checker is not picking up all the duplicates.
![image](https://user-images.githubusercontent.com/17127926/197369669-3d93fd02-5195-4999-b79f-1510119bfede.png)

**Version info:**
`3.6.1`
![image](https://user-images.githubusercontent.com/17127926/197369702-b4f96391-6a5b-42b7-a058-2150732f9205.png)

**Comment by thezoggy** [comment]
so dupe checking works with two possible datasets... using the history info in the sab db. and then the nzb backup folder.  

the duplicate you are seeing, is it already in sab history? 
- do you have a 3rd party app that removes failed downloads? 
- do you have sab set not to retain history

do you have sab configured to store .nzb in a backup folder?
- sab config > folders > .nzb Backup Folder

**Comment by x-limitless-x** [comment]
> so dupe checking works with two possible datasets... using the history info in the sab db. and then the nzb backup folder.
> 
> the duplicate you are seeing, is it already in sab history?
> 
> * do you have a 3rd party app that removes failed downloads?
> * do you have sab set not to retain history
> 
> do you have sab configured to store .nzb in a backup folder?
> 
> * sab config > folders > .nzb Backup Folder

I do have some of them being detected as duplicate nzb files due to being in the history, but a majority of the items are "_new_" nzb files that have the same name and contents as the previously downloaded items. It would be nice if we had an option to exclude items that have been downloaded with the same name.

Either way, I wrote the following PowerShell script that accesses the web API for sabnzbd and deletes any downloads with duplicate names, saved me a lot of time:

You just need to replace the variable in the variables section below:
```powershell
#Author: Blake Drumm
#Created: October 23rd, 2022

# =========================================================================
#Variables Section
# =========================================================================
$ServerAddress = '<sabnzb_weburl>' # Example: https://localhost/sabnzbd
$APIKey = '<sabnzb_apikey>' #Example: 1z1e31b797fs9bq6196y9uf12q3o21xz
# =========================================================================

# Grab List of Duplicates
[array]$listOfNzbs = (((Invoke-WebRequest "$ServerAddress/api?mode=queue&output=json&apikey=$APIKey" -UseBasicParsing).Content | ConvertFrom-Json).Queue.Slots |
	Group-Object -Property filename |
	Where-Object -FilterScript {
		$_.Count -gt 1
	} |
	Select-Object -ExpandProperty Group)

if ($listOfNzbs)
{
	$sizeInGB = (($listOfNzbs | Where { $_.Size -match " GB" } | Select-Object Size -ExpandProperty Size).Replace(" GB", '') -join " + ");
}
else
{
	$sizeInGB = '0 GB'
}
$calculatedSizeTotal = "$(Invoke-Command -ScriptBlock { $result = . ([ScriptBlock]::Create($sizeInGB)); return [math]::Round($result) }) GB"

$listOfNzbIds = $listOfNzbs | Select-Object nzo_id -ExpandProperty nzo_id

Write-Output @"
This script will delete duplicate items with similar nzb names, from SABNZBD via the API.

To be removed:
    Total Count: $($listOfNzbIds.Count)
    Total Size:  $calculatedSizeTotal

"@
if ($listOfNzbIds.Count -gt 0)
{
	pause
	# Actually Delete the Duplicates
	(Invoke-WebRequest "$ServerAddress/api?mode=queue&name=delete&value=$($listOfNzbIds -join "," | Out-String)&del_files=1&apikey=$APIKey" -UseBasicParsing).Content
}
Write-Output "Script completed!"
```

**Comment by thezoggy** [comment]
There might be some confusion on what you think a dupe is, 

The main dupe checker isnt mean to check for the nzb job name. its looking at the md5 of the nzb. aka is the articles inside the nzb the same ones its seen before...   the .nzb file one is checking if the nzb file exists.. which is prob what your wanting. Also note, that the proper option allows bypassing the dupe check. Then the series dupe check is just looking for the name+S#E# match to know if its seen it before. 


Detect Duplicate Downloads - Detect identical NZB files (based on items in your History or files in .nzb Backup Folder)
this is looking at the actual nzb file hash,

--- this is taking the actual .nzb file and getting the md5. then compares if its been seen before in sab history. 
--- then if that isnt true, it looks to see if the .nzb file exists already in the backup folder and if there is a match


Detect duplicate episodes in series - Detect identical episodes in series (based on "name/season/episode" of items in your History)

--- this one is extremely old and not really useful anymore in this day in age when you have 3rd party apps that can handle this so much better.

**Comment by Safihre** [comment]
@x-limitless-x what you want is #727. As you can see it's a very old request that we haven't implemented due to complexity.
So not just detecting duplicates in the queue, but also using a "duplicate" in case the first original job fails for example.
