### ISSUE TITLE
[SAB3] Internet Bandwidth measurement ... experiences?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1454]
SAB3 offers the Internet Bandwidth measurement (which I wrote).

My own experiences are mixed. On my 700 Mbps fiber line, I sometimes get measurements that are quite good:
![image](https://user-images.githubusercontent.com/1273502/82457801-298c3000-9ab6-11ea-808c-085ef1dfc0b2.png)

![image](https://user-images.githubusercontent.com/1273502/82457936-5b9d9200-9ab6-11ea-8889-780273ded443.png)

... but sometimes (on first run?), the result can be low.

Maybe it has to do with caching on the side of cloudflare? Hypothesis: it's cached X minutes / hours after usage, and un-cached if not used in Y hours? That would explain my experience (with the current little usage by others).

So: what are your experiences?

EDIT:

test from CLI:

`python3 -c "import sabnzbd.utils.internetspeed; print(int(8.1*sabnzbd.utils.internetspeed.internetspeed()))"`

**Comment by Safihre** [comment]
According to an email @inpheaux sent me about the Cloudflare caching:

> Default is 5 days, so for one user per Cloudflare farm, once every 5 days, they're going to get it served from Github instead of Cloudflare.

**Comment by Safihre** [comment]
You mentioned before that including a larger 50MB file resulted in better results. Don't you still want to add that?

**Comment by sanderjo** [comment]
The plan is now to do two runs. Experience shows the second run often yield better results (maybe because of cloudflare caching?)
