### ISSUE TITLE
Remove /tapi and only allow /api

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1460]
For some reason you can access the SABnzbd API on 2 endpoints:
```
http://localhost:8080/api
```
and:
```
http://localhost:8080/tapi
```
But the `tapi` version is the exact same as the `api` version, but without logging anything 😨. So let's say I am evil and I want to probe the SABnzbd-installation, I just do all my requests to `tapi` and nothing is logged..

I suggest we remove `tapi`, and use `api` for everything. Something we can only really do now we have this major release.

@jeffgeorge / @jcfp / @sanderjo

**Comment by jeffgeorge** [comment]
IIRC, `tapi` was a subset of the API intended for theme use. Do any of the old (but still included) themes still use it at all?

**Comment by Safihre** [comment]
It might have been intended a subset, but was implemented as just the exact same: https://github.com/sabnzbd/sabnzbd/blame/develop/sabnzbd/interface.py#L427-L458
Yes, Glitter does. But it can also switch to `api` just fine.

**Comment by thezoggy** [comment]
From what I recall, tapi isn't exposed so it shouldn't be an attack surface.. now if it's not used or we can depreciate it by updating the templates then that's probably wise

**Comment by Safihre** [comment]
It's unfortunately exposed, but instead of checking the `apikey` parameter it checks the `session` parameter for the API key.

**Comment by jcfp** [comment]
I don't see any reason for keeping it around.

Adjusting the code of legit 3rd party scripts, themes, or apps that may have used tapi -if any- should be a matter of minutes so that isn't a blocker either. Just make sure to mention it in the changelog.

**Comment by thezoggy** [comment]
and need to do pass on wiki/api docs for tapi references (and qstatus)
https://sabnzbd.org/wiki/advanced/api

**Comment by jcfp** [comment]
> and need to do pass on wiki/api docs for tapi references (and qstatus)

Tapi is only mentioned once, in [wiki/advanced/api.html](https://github.com/sabnzbd/sabnzbd.github.io/blob/master/wiki/advanced/api.html):11
`For backwards compatibility you might see tapi used in some of our templates, we recommend using api.`
