### ISSUE TITLE
Permissions not obeyed for folders on 3.x

### ISSUE THREAD

**Issue by DataWhig** [sabnzbd/sabnzbd#1462]
Folders will be set at an incorrect permission, usually 700. They have been set at 775 and 755 with no change. 

Noticed this issue over last few weeks, likely started with upgrade to 3 RC but have not looked in detail until now. 

Setup is CentOS container on proxmox Linux, settings were unchanged and always worked as expected until recently. System also has Sonarr and Radarr, which have interoperated without issue.

**Comment by Safihre** [comment]
You are sure SABnzbd is doing this? Can you inspect the log if any errors or warnings are thrown when applying the permissions?

**Comment by DataWhig** [comment]
Don't think I can see any problems in logs. One thing I notice popping up occasionally is:

`INFO::[postproc:219 Completed Download Folder /folder is not on FAT`

**Comment by thezoggy** [comment]
that info message is to be expected if you are not using FAT16/32 file system (which i seriously doubt you are using)
