### ISSUE TITLE
Network mount inside docker gives a lot of errors

### ISSUE THREAD

**Issue by victor-perez** [sabnzbd/sabnzbd#1464]
I try to run *sabnzbd* inside a docker container I use the following:
`docker create --name=sabnzbd -v /etc/sabnzbd:/config -v /downloads:/downloads -e PGID=xxx -e PUID=xxx -e TZ=Europe/Amsterdam -p 8080:8080 --cpus=".5" -m="2g" --restart always  linuxserver/sabnzbd` where `/downloads` is network mount. I get the following errors
1. `2020-05-26 19:14:04,662::ERROR::[misc:1638] Cannot change permissions of /downloads/incomplete/nzbs`
    a. `2020-05-26 19:52:31,884::ERROR::[filesystem:314] download_dir directory: /downloads/incomplete/nzbs error accessing`

But when I login in to the docker container and do `chmod 0775 /downloads/incomplete/nzbs` there is no problem

2. `2020-05-26 19:52:32,187::INFO::[postproc:219] Completed Download Folder /downloads/done/other is not on FAT`

```bash
root@767ceb128701:/# df -T  /downloads/done/other
Filesystem           Type   1K-blocks  Used   Available Use% Mounted on
 #//10.x.x.x/download cifs 12159910327   117 12159910210   1% /downloads
```

**Comment by victor-perez** [comment]
The problem was the rights on the network mount

**Comment by sanderjo** [comment]
> The problem was the rights on the network mount

It's always the rights.

But your statement 2 ... about FAT ... why did you post that ... ?

**Comment by victor-perez** [comment]
@sanderjo I saw only later that this is not a error, I only read the text and thought this also a error, but later I saw it just `INFO`

**Comment by sanderjo** [comment]
Maybe the text 'is not on FAT` should have been more like `Good: ... is not on FAT`

Anyway: back to your rights:
- how is it possible that could not do `chmod`, but you from inside the same docker could do it?
- what was wrong with the rights?

**Comment by thezoggy** [comment]
he just setup the docker incorrectly, not that sab was the issue.

**Comment by victor-perez** [comment]
@thezoggy you are correct it's not a sab issue, but no i didn't setup the docker incorrect in fact that is not what I changed.
@sanderjo sab doesn't run as root, the problem was, I was change a lot of groups and made a new group for downloads but I forgot to mount the cifs network drive with that new groep that still was using the old group, so in short I needed to change the `gid=xxx` option for the cifs mount and then everything started to work again.
