### ISSUE TITLE
remarks about INSTALL.txt

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1467]
I read INSTALL.txt and have some remarks:

https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L55-L56

Is that true? For example, on Ubuntu 20.04, with only python3 installed, no need to replace `python3 `with `python `in the commands. Just use `python3`, which is always correct and safe.

In https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L58-L68 the needed OS packages are missing, which you need before you run the pip3 requirements:

For ubuntu that's
```
git # only needed when getting from github
par2 unrar python3-setuptools python3-pip
libffi-dev libssl-dev # needed if pip starts compiling ...?
```
Those last two packages names are probably Ubuntu/Debian specific names. @jcfp do you know the general name for libssl-dev? https://packages.ubuntu.com/search?keywords=libssl-dev&searchon=names&suite=eoan&section=all says 

Port issue:

https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L74-L83 is that still what we want to advice?

**Comment by jcfp** [comment]
Generic names for that libwhatever-dev stuff would simply be "_development headers for [openssl/ffi/etc.]_". If you paste any package name into the _Debian source package_ field at [packages.qa.debian.org](https://packages.qa.debian.org/common/index.html), it will tell you what source package produced it and provide a link to the homepage of that project.

Using `python3` everywhere should be fine; and even if it were to not work on some obscure system it's self-explanatory enough.

**Comment by sanderjo** [comment]
@jcfp Additonal question: I wrote

`libffi-dev libssl-dev # needed if pip starts compiling ...?`

I want to change that to:

`libffi-dev libssl-dev # needed on non-X86 platforms to compile the python cryptography module`

OK?

Reason: On ARM (so: non-X86?), **without** those libs, I get:

```
Collecting cryptography
  Downloading cryptography-2.9.2.tar.gz (517 kB)
     |████████████████████████████████| 517 kB 5.2 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-7tecagte/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''
       cwd: None
```

Which is solved by installing `libffi-dev libssl-dev`

**Comment by jcfp** [comment]
> I want to change that to:
> 
> `libffi-dev libssl-dev # needed on non-X86 platforms to compile the python cryptography module`

Those dev. headers are required regardless of the platform, so drop the `on non-X86 platforms` part.

**Comment by Safihre** [comment]
@jcfp On x86 platforms there is a pre-compiled `cyrptography` package available from PyPi for 90% of the platforms, so thats why the non-x86 does make sense.

**Comment by jcfp** [comment]
Why not just write that then? `needed to compile (...) unless pypi provides a pre-compiled package` or something like that.
