### ISSUE TITLE
[FR] More infos in Queue rows

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1474]
Right now its only possible to add ONE more info to each row.

As a heavy use user my most wanted is cat and age.
In the history cat and speed.

I would like to request 1 more info shown or all infos shown.

All infos would also be nice with #1473

**Comment by thezoggy** [comment]
i assume you are asking for more columns not rows? you can configure how many rows are shown via the ui already

**Comment by reloxx13** [comment]
> 
> 
> i assume you are asking for more columns not rows? you can configure how many rows are shown via the ui already

no, not the item/row limit.

i mean those infos:
![grafik](https://user-images.githubusercontent.com/14855001/83312790-f5caac00-a213-11ea-96df-66bf022ace56.png)

**Comment by albino1** [comment]
+1 I would also like to have the ability to add more extra columns.

**Comment by reloxx13** [comment]
thank you so much i love it
![grafik](https://user-images.githubusercontent.com/14855001/104093674-40bd9f00-528c-11eb-914d-8a84372d0eae.png)
