### ISSUE TITLE
[FR] Make web interface settings persistent

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1475]
Currently after cookie deleting or using another pc/browser, all my web interface settings are resseted to default, which is really annoying (items shown, tab view, compact view etc. ) .

I see no reason why someone would like diffrent settings per browser?!

Suggestion: Add global persistent web interface settings.

**Comment by thezoggy** [comment]
we did this because people would access sab via their phone/desktop/etc and each place people wanted to customize what they saw because one layout or size doesnt fit all. (gotta realize that sab has been around for decade+.. well before the era of everything has an app)

**Comment by reloxx13** [comment]
Your decision.

you r right, i use nzb360 app 😆 
Todays mobile displays also have a higher resolution and showing more is possible.

**Comment by Safihre** [comment]
Indeed after testing on desktop, tablet and phone we decided not to make settings persistant. Only some settings are, like number of rows and refresh rate.

**Comment by reloxx13** [comment]
What about a possibility to change the default settings?

What is "die globalen Interface-Einstellungen verwenden" (checkbox use the global settings).
I dont see that it does anything.

**Comment by Safihre** [comment]
The top 3 settings (number of items and refresh rate) are stored on the server side, so persistant. If that box is checked.
Not very clear, I agree 🤣
