### ISSUE TITLE
[FR] Password list in settings and not as file

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1476]
To add passwords to my password.txt list, i have to open a remote session.

It would be nice to change/edit it on the webpage.

**Comment by thezoggy** [comment]
to play devils advocate here, exposing a file via sab gui is an attack vector and a huge no-no. you can already add pw manually or via the job automatically via the name.

this would be a huge security risk to do what you want.

**Comment by reloxx13** [comment]
those are rar passwords, not login passwords.

**Comment by jeffgeorge** [comment]
Agree with @thezoggy , it's not the contents of the file that's the problem, opening a configuration file up to full read/write via the webui seems like a terrible idea from a security perspective.

**Comment by reloxx13** [comment]
Not the config file!!!!!!!!!! 😭 

passwords.txt file.

![grafik](https://user-images.githubusercontent.com/14855001/83313149-3a0a7c00-a215-11ea-8907-ae585bb3f7a7.png)

**Comment by jeffgeorge** [comment]
`passwords.txt` _is_ effectively a configuration file. I'm not entirely sure if we parse it or just hand it off to unrar, though. Regardless, it'd mean ensuring we have the write bit set, which right now is not a guarantee.

**Comment by jeffgeorge** [comment]
Just looked it up, yes we parse that file: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L750

**Comment by reloxx13** [comment]
on my side this has low prio, its very rare that i have or want to add a pw manually.
But when i need to add one, its annoying cause i have to open a desktop session instead using the website over vpn.
guess its easier to handle/edit with linux&ssh.

**Comment by thezoggy** [comment]
Exposing any file is an attack surface. It is not something we would want to do.

**Comment by thezoggy** [comment]
if we were to just append user input for password to the bottom of the file, would that 'solve' your dilemma?

**Comment by Safihre** [comment]
Since these passwords are directly passed in a system open call to unrar, I don't want to expose it. It's a clear attack vector.
Also, the password list is in general a bad idea because unrar takes ages to detect bad password. 
So should just provide it during the download or in the filename of the NZB. See also the wiki section on passworded jobs.
