### ISSUE TITLE
[BUG] Long filename and alot of parts result in a higher row

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1477]
![grafik](https://user-images.githubusercontent.com/14855001/83311990-3c6ad700-a211-11ea-8ea8-e594c84f65d8.png)

The row extends and is higher than the others if the filename is long and the part count is over 99.

 would be fixed with #1473 

win10x64
firefox 76.0.1
sab  3.0.0Beta1 [4d1f36d]
python 3.8.0

**Comment by Safihre** [comment]
The problem is not as much the width of the name, but that of the Direct Unpack status. Maybe nowadays (the skin is 5 years old) I could do some trick with CSS's `calc` function that would work better..
