### ISSUE TITLE
[FR] Glitter - Night Theme, settings not dark

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1479]
Using the glitter night theme does not make the settings dark.
Naviagte to settings will hurt 👀 in the night.

![grafik](https://user-images.githubusercontent.com/14855001/83313089-092a4700-a215-11ea-9830-d3be1ff0a32a.png)

**Comment by albino1** [comment]
+1, dark themed settings would be great.

**Comment by thezoggy** [comment]
We used to do a themed config and it makes it that much harder to do anything because additional testing and variances (let alone assessibility).

**Comment by jeffgeorge** [comment]
Yeah, the configuration system itself uses its own theme. To make it respect dark / light settings we'd likely have to fork the config theme itself and switch based on what main theme a user has selected. And then we'd have two admin themes to maintain. Not likely worth the effort.

**Comment by Safihre** [comment]
It has been just too much work for something that isn't used as often as the main page.
