### ISSUE TITLE
[FR] Setting for default sort on new item added

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1480]
Mostly i like to have the queue sorted by file size, that way smaller files are downloaded first.
Right now i have to re-sort after every add.

Use-case problem:
Files added by api
I order by size
Downloads are starting, if a small file is canceled and another small file is added by api, it will be at the bottom and downloaded after all that bigger files.

Personally i would like to have a setting to define what the default sort should be.
- date added
- age
- name
- size

That way, the new smaller file would be added more to the front and it does not need to wait for those huge files.

**Comment by thezoggy** [comment]
sab's download is a queue: FIFO (first in, first out).
While it is FIFO there is a priority based sorting (paused/low/normal/high/forced), which is generally done by the 3rd party app/user/category.

Now about what your asking,
Sorting by 'date added' -- it already does this by the nature of FIFO. So, done.
Then sorting by age.. well that already exists as well: Switches > "Sort by Age". So, done.
Now sorting by name.. well what name? nzbname? release name? obfuscated name? seems just messy.
Okay, size? Well you dont really know the size until the job starts.. then what about pars or a job of multiple nzbs (rar/zip/etc)..  

You can just make a pre-processing script to analyze said job and add how you want.... which has been mentioned before. Also, apps that feed stuff to sonarr usually are the ones that would dicate the priority/how its added (older stuff with lower priority vs newer stuff with higher for example).

**Comment by reloxx13** [comment]
heya @thezoggy , 
sab is asking for ideas to improve in the feedback slider.
I know what it already does and i wrote that this can be improved by adding a possibility to change the FIFO sorting.
Not every user can write scripts to do this by itsown.

Users are not at the pc and watching the queue 24/7 to trigger "sort by filesize" after every api add. To improve this, i asked for a default setting with the existing manual sort orders (which has "name" btw).

Series sizes also varies alot between quality types (dvd, bluray). Priority would not help in this cases.
Priority is just for file age.

The name which is shown in the queue, just like the manual sort does already.

condition could be like after item added to queue done, if sort order is not fifo/default, trigger selected manual sort once.

**Comment by Safihre** [comment]
I have seen this request before and I can see the benefit to make it more flexible. Now we only have the age-sorter.
If people wanna sort weirdly, why not 🍭

**Comment by Safihre** [comment]
Will be part of 3.0.0!
