### ISSUE TITLE
requirements.txt not in source asset

### ISSUE THREAD

**Issue by asmod3us** [sabnzbd/sabnzbd#1482]
I've downloaded the release asset at `https://github.com/sabnzbd/sabnzbd/releases/download/3.0.0Beta1/SABnzbd-3.0.0Beta1-src.tar.gz` and noticed it does not contain requirements.txt

Is this intentional? The Source code asset at `https://github.com/sabnzbd/sabnzbd/archive/3.0.0Beta1.tar.gz` has it.

**Comment by Safihre** [comment]
I agree! Will be part of the next release.
