### ISSUE TITLE
Regression in 3.0.0Beta1

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1484]
It seems that there's a regression in loading large NZBs in 3.0.0Beta1.

2020-06-01 00:29:43,638::WARNING::[nzbstuff:609] Invalid NZB file Job.nzb, skipping (reason=list index out of range, line=1)
2020-06-01 00:29:43,639::INFO::[nzbstuff:610] Traceback: 
Traceback (most recent call last):
  File "sabnzbd/nzbstuff.py", line 606, in __init__
  File "sabnzbd/nzbparser.py", line 123, in nzbfile_parser
  File "sabnzbd/nzbstuff.py", line 415, in __eq__
IndexError: list index out of range

These are large 5MB+ nzbs with a ton of articles.

The same nzbs loaded just fine in 3.0.0Alpha2 and download normally.

So somewhere along the line between Alpha2 and Beta1, something changed, at least for these NZBs.

Also something to add, if I start 3.0.0Alpha2, pause, load the nzb, stop SABnzbd then start 3.0.0Beta1, it starts downloading, but I get "INFO::[__init__:1013] Restarting because of crashed assembler" multiple times.

**Comment by Cpuroast** [comment]
Looking at the commits since Beta1,

It looks like this might have been fixed in: https://github.com/sabnzbd/sabnzbd/commit/58f20959ccb65d951c62676aea976b7c0d2bfcb9

**Comment by Cpuroast** [comment]
After trying out "test-build8" which equals to https://github.com/sabnzbd/sabnzbd/commit/7cda4d9ce214f11a52aae8b5910be16e18acc359

Which also contains the commit I mentioned above, it is indeed fixed and the NZBs in question load and download normally.

I will close this issue.

**Comment by Safihre** [comment]
Indeed fixed in that commit. Will make a Beta2 soon, probably today!
