### ISSUE TITLE
python3 versions: 3.5 and 3.9

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1488]
FYI https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions gives interesting info:

**Python 3.5**
"End of security fixes": 2020-09-13. So that is only 3 months from now. So hopefully users and packagers have a newer version than python 3.5.
I checked my Synology: the python3 is ... Python 3.5.1 ... :-( I hope I'll get a python 3.6 or higher version.

**Python 3.9**
Will be released on 2020-10-05, so 4 months from now. That gives time to test.
I just installed python 3.9 on my Ubuntu 20.04, and I'm running it with SABnzbd. So far so good.

https://docs.python.org/3.9/whatsnew/3.9.html tells 

> When Python 2.7 was still supported, many functions were kept for backward compatibility with Python 2.7. With the end of Python 2.7 support, these backward compatibility layers have been removed, or will be removed soon. Most of them emitted a DeprecationWarning warning for several years.

I'll see what using python3.9 reports.

**Comment by Safihre** [comment]
Regarding Synology, it's slowly progressing to newer Python 3: https://github.com/SynoCommunity/spksrc/pull/3953
