### ISSUE TITLE
[BUG] Version 3.0.0 delivers different and invalid json then 2.3.0

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1503]
Example.
Version 2.3.0:

`{"queue": {"noofslots_total": 0, "diskspace2_norm": "1.1 T", "paused": false, "finish": 0, "speedlimit_abs": "", "slots": [], "speed": "0  ", "size": "0 B", "rating_enable": false, "eta": "unknown", "refresh_rate": "", "start": 0, "version": "2.3.9", "diskspacetotal2": "1832.77", "limit": 0, "diskspacetotal1": "1832.77", "status": "Idle", "have_warnings": "14", "cache_art": "0", "sizeleft": "0 B", "finishaction": null, "paused_all": false, "quota": "0 ", "cache_size": "0 B", "mbleft": "0.00", "diskspace2": "1091.20", "diskspace1": "1091.20", "scripts": ["None", "autoProcessTV.pyc", "hellaToSiCKRAGE.py", "mediaToSiCKRAGE.py", "autoProcessTV.py", "autoProcessTV.cfg", "__init__.py", "sabToSiCKRAGE.py"], "categories": ["*", "j", "series", "l", "familie", "docus", "films"], "timeleft": "0:00:00", "pause_int": "0", "have_quota": false, "noofslots": 0, "mb": "0.00", "loadavg": "0.12 | 0.11 | 0.13 | V=1017M R=476M", "cache_max": "522715136", "kbpersec": "0.00", "speedlimit": "100", "left_quota": "0 ", "diskspace1_norm": "1.1 T", "queue_details": "0"}}`

Version 3.0.0:

`{'version': '3.0.0Beta2', 'paused': True, 'pause_int': '0', 'paused_all': False, 'diskspace1': '43.53', 'diskspace2': '43.53', 'diskspace1_norm': '43.5 G', 'diskspace2_norm': '43.5 G', 'diskspacetotal1': '99.90', 'diskspacetotal2': '99.90', 'loadavg': '', 'speedlimit': '100', 'speedlimit_abs': '', 'have_warnings': '1', 'finishaction': None, 'quota': '0 ', 'have_quota': False, 'left_quota': '0 ', 'cache_art': '0', 'cache_size': '0 B', 'cache_max': '813590118', 'kbpersec': '0.00', 'speed': '0 ', 'mbleft': '3740.32', 'mb': '3740.32', 'sizeleft': '3.7 GB', 'size': '3.7 GB', 'noofslots_total': 1, 'status': 'Paused', 'timeleft': '0:00:00', 'eta': 'unknown', 'refresh_rate': '1', 'scripts': [], 'categories': ['*', 'movies', 'music', 'tv', 'books'], 'rating_enable': False, 'noofslots': 1, 'start': 0, 'limit': 0, 'finish': 0, 'slots': [{'index': 0, 'nzo_id': 'SABnzbd_nzo_ucra9t7u', 'unpackopts': '3', 'priority': 'Normal', 'script': 'None', 'filename': 'Shirley (2020)1080p_WEB-DL_EVO x264_ NL Subs Ingebakken', 'password': '', 'cat': 'movies', 'mbleft': '3740.32', 'mb': '3740.32', 'size': '3.7 GB', 'sizeleft': '3.7 GB', 'percentage': '0', 'mbmissing': '0.00', 'direct_unpack': 0, 'status': 'Queued', 'timeleft': '0:00:00', 'eta': 'unknown', 'avg_age': '2d', 'has_rating': False}]}`

Moveover php (7.4) json_decode (used in spotweb) indicates an SYNTAX_ERROR
Several online json validators also fail.

**Comment by sanderjo** [comment]
FWIW

I started 3.0.0 Beta2 and got the queue via http://127.0.0.1:8080/api?output=json&mode=queue like this

```
{"queue": {"version": "3.0.0Beta2", "paused": false, "pause_int": "0", "paused_all": false, "diskspace1": "27.40", "diskspace2": "27.40", "diskspace1_norm": "27.4 G", "diskspace2_norm": "27.4 G", "diskspacetotal1": "116.38", "diskspacetotal2": "116.38", "loadavg": "1.58 | 1.41 | 1.39 | V=2346M R=167M", "speedlimit": "100", "speedlimit_abs": "", "have_warnings": "0", "finishaction": null, "quota": "0 ", "have_quota": false, "left_quota": "0 ", "cache_art": "49", "cache_size": "33.2 MB", "cache_max": "3145728000", "kbpersec": "19056.01", "speed": "18.6 M", "mbleft": "67.16", "mb": "113.20", "sizeleft": "67.2 MB", "size": "113.2 MB", "noofslots_total": 1, "status": "Downloading", "timeleft": "0:00:03", "eta": "21:49 vr 12 jun", "refresh_rate": "1", "scripts": ["None", "delete_download.py", "example_pp_script.py"], "categories": ["*", "movies", "tv", "audio", "software"], "rating_enable": false, "noofslots": 1, "start": 0, "limit": 0, "finish": 0, "slots": [{"index": 0, "nzo_id": "SABnzbd_nzo_trcsae6d", "unpackopts": "3", "priority": "Force", "script": "None", "filename": "test_download_100MB", "password": "", "cat": "*", "mbleft": "67.16", "mb": "113.20", "size": "113.2 MB", "sizeleft": "67.2 MB", "percentage": "40", "mbmissing": "0.00", "direct_unpack": 0, "status": "Downloading", "timeleft": "0:00:03", "eta": "21:49 vr 12 jun", "avg_age": "83d", "has_rating": false}]}}
```

which https://jsonformatter.org/json-pretty-print pretty-prints to

```
{
  "queue": {
    "version": "3.0.0Beta2",
    "paused": false,
    "pause_int": "0",
    "paused_all": false,
    "diskspace1": "27.40",
    "diskspace2": "27.40",
    "diskspace1_norm": "27.4 G",
    "diskspace2_norm": "27.4 G",
    "diskspacetotal1": "116.38",
    "diskspacetotal2": "116.38",
    "loadavg": "1.58 | 1.41 | 1.39 | V=2346M R=167M",
    "speedlimit": "100",
    "speedlimit_abs": "",
    "have_warnings": "0",
    "finishaction": null,
    "quota": "0 ",
    "have_quota": false,
    "left_quota": "0 ",
    "cache_art": "49",
    "cache_size": "33.2 MB",
    "cache_max": "3145728000",
    "kbpersec": "19056.01",
    "speed": "18.6 M",
    "mbleft": "67.16",
    "mb": "113.20",
    "sizeleft": "67.2 MB",
    "size": "113.2 MB",
    "noofslots_total": 1,
    "status": "Downloading",
    "timeleft": "0:00:03",
    "eta": "21:49 vr 12 jun",
    "refresh_rate": "1",
    "scripts": [
      "None",
      "delete_download.py",
      "example_pp_script.py"
    ],
    "categories": [
      "*",
      "movies",
      "tv",
      "audio",
      "software"
    ],
    "rating_enable": false,
    "noofslots": 1,
    "start": 0,
    "limit": 0,
    "finish": 0,
    "slots": [
      {
        "index": 0,
        "nzo_id": "SABnzbd_nzo_trcsae6d",
        "unpackopts": "3",
        "priority": "Force",
        "script": "None",
        "filename": "test_download_100MB",
        "password": "",
        "cat": "*",
        "mbleft": "67.16",
        "mb": "113.20",
        "size": "113.2 MB",
        "sizeleft": "67.2 MB",
        "percentage": "40",
        "mbmissing": "0.00",
        "direct_unpack": 0,
        "status": "Downloading",
        "timeleft": "0:00:03",
        "eta": "21:49 vr 12 jun",
        "avg_age": "83d",
        "has_rating": false
      }
    ]
  }
}
```

So ... does this one look OK to you?

**Comment by sanderjo** [comment]
To me, it looks your SAB3 JSON is missing the start `{"queue": `

**Comment by mesa57** [comment]
It misses queue, has wrong quotes and also boolean values start with uppercase.
Btw. I used the windows installer version (W7).

**Comment by sanderjo** [comment]
I fired up Windows, with SAB3-beta2, and http://127.0.0.1:8080/api?output=json&apikey=d8f1ba3c59628c20f1c447db2b6fe2db&mode=queue gives

`{"queue": {"version": "3.0.0Beta2", "paused": false, "pause_int": "0", "paused_all": false, "diskspace1": "33.51", "diskspace2": "33.51", "diskspace1_norm": "33.5 G", "diskspace2_norm": "33.5 G", "diskspacetotal1": "118.08", "diskspacetotal2": "118.08", "loadavg": "", "speedlimit": "100", "speedlimit_abs": "", "have_warnings": "1", "finishaction": null, "quota": "0 ", "have_quota": false, "left_quota": "0 ", "cache_art": "0", "cache_size": "0 B", "cache_max": "-1", "kbpersec": "0.00", "speed": "0 ", "mbleft": "0.00", "mb": "0.00", "sizeleft": "0 B", "size": "0 B", "noofslots_total": 0, "status": "Idle", "timeleft": "0:00:00", "eta": "unknown", "refresh_rate": "1", "scripts": [], "categories": ["*", "tv", "movies", "software", "audio"], "rating_enable": false, "noofslots": 0, "start": 0, "limit": 0, "finish": 0, "slots": []}}`

So: starts with `queue`, unlike your output. "false" has no capitals.
So ... recheck your output?

In pretty print:

```
{
  "queue": {
    "version": "3.0.0Beta2",
    "paused": false,
    "pause_int": "0",
    "paused_all": false,
    "diskspace1": "33.51",
    "diskspace2": "33.51",
    "diskspace1_norm": "33.5 G",
    "diskspace2_norm": "33.5 G",
    "diskspacetotal1": "118.08",
    "diskspacetotal2": "118.08",
    "loadavg": "",
    "speedlimit": "100",
    "speedlimit_abs": "",
    "have_warnings": "1",
    "finishaction": null,
    "quota": "0 ",
    "have_quota": false,
    "left_quota": "0 ",
    "cache_art": "0",
    "cache_size": "0 B",
    "cache_max": "-1",
    "kbpersec": "0.00",
    "speed": "0 ",
    "mbleft": "0.00",
    "mb": "0.00",
    "sizeleft": "0 B",
    "size": "0 B",
    "noofslots_total": 0,
    "status": "Idle",
    "timeleft": "0:00:00",
    "eta": "unknown",
    "refresh_rate": "1",
    "scripts": [],
    "categories": [
      "*",
      "tv",
      "movies",
      "software",
      "audio"
    ],
    "rating_enable": false,
    "noofslots": 0,
    "start": 0,
    "limit": 0,
    "finish": 0,
    "slots": []
  }
}
```

**Comment by sanderjo** [comment]
So, as proof, here is what I get on http://127.0.0.1:8080/api?output=json&apikey=d8f1ba3c59628c20f1c447db2b6fe2db&mode=queue 

![image](https://user-images.githubusercontent.com/1273502/84544302-4d314780-acfd-11ea-9e56-8539c448a495.png)

You can do the same: with your web browser, go to http://127.0.0.1:8080/api?output=json&apikey=d8f1ba3c59628c20f1c447db2b6fe2db&mode=queue (fill out your own API key), and post the screen shot here.

**Comment by Safihre** [comment]
Indeed, make sure you are using `output=json`. What you are seeing is the `output=text` mode. These are serialized python objects and its the default if you don't supply an `output` or a wrong one.

**Comment by thezoggy** [comment]
@mesa57  would help if you showed exactly what api request you are making :)

**Comment by mesa57** [comment]
This is the used url : 
`http://127.0.0.1:8080/sabnzbd/api?mode=queue&output=json&apikey=0a019d38276bc9da9976446fef71a180&output=json`
What is remarkable is that output=json is used 2x.
I will try to reduce that to 1x

**Comment by mesa57** [comment]
Seems to work now. Strange effect in 3.0.0 😄

**Comment by sanderjo** [comment]
> Seems to work now. Strange effect in 3.0.0 😄

How does it work now? Coincidence? Other URL? ... ?

**Comment by Sweepr** [comment]
> 
> 
> > Seems to work now. Strange effect in 3.0.0 😄
> 
> How does it work now? Coincidence? Other URL? ... ?

Read the above comment:

This is the used url :
http://127.0.0.1:8080/sabnzbd/api?mode=queue&output=json&apikey=0a019d38276bc9da9976446fef71a180&output=json
What is remarkable is that output=json is used 2x.

**Comment by Safihre** [comment]
I understand the problem now and probably know how to fix! I did make a change.
