### ISSUE TITLE
[FR]: example API URL in GUI

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1504]
I would like to make API stuff easier by providing one or a few example API URLs in the SAB GUI.

See this example I prototyped into SAB:

![image](https://user-images.githubusercontent.com/1273502/84562464-0707d280-ad55-11ea-9033-ed7a7d4d0187.png)

Then with one click any person will get the correct URL, and the real output. 

IMHO this is much easier than my usual steps
1. google and read SAB API
2. construct URL in lynx
3. oh, forgot: find and copy API key
4. use correct URL in lynx
5. done

And it would avoid issues like https://github.com/sabnzbd/sabnzbd/issues/1503

**Comment by mesa57** [comment]
It would not avoid issues like #1503 because that url was generated by code for almost 15 years like that (and worked) until 3.0.0 came around.

**Comment by jcfp** [comment]
> I would like to make API stuff easier by providing one or a few example API URLs in the SAB GUI.
 
> Then with one click any person will get the correct URL, and the real output.

The target audience for an example url like that seems rather thin? For 99.9% of users, the api key is but a bunch of letters and numbers some tutorial told them to copy-paste into a third-party application to "make things work". Anything that distracts from the copy-pasting task is bound to lower their success rate. Developers on the other hand dig into the API reference and/or source code and go from there.

**Comment by Safihre** [comment]
I agree with @jcfp, I don't think some of the problems we see now have to do with new people using the API wrongly, but with 3rd-party software that linked to SABnzbd ages ago and was never updated.
Other users can read the API-docs. At https://sabnzbd.org it's even in the Documentation quick-menu.
If the API-reference is too difficult, you can change it 👍
