### ISSUE TITLE
"Abort jobs that cannot be completed" not working when the post contains 1 large file

### ISSUE THREAD

**Issue by Jonnehs** [sabnzbd/sabnzbd#1505]
Cross posted on support forums; https://forums.sabnzbd.org/viewtopic.php?f=2&t=24797

Articles can be 100% missing, and the job will still continue until its 100%, which is eating a lot of time for content which is missing. https://imgur.com/a/V09HnKf

The "Abort jobs that cannot be completed" flag is set, as is "Fast fail" in special. I can't see any other settings which describe changing this behaviour, so why is SAB not aborting jobs when the available par2 blocks exceed the missing articles?

**Comment by Safihre** [comment]
What version of SABnzbd are you on?
Did you maybe Retry these jobs? When retrying jobs, auto-failure is disabled.

**Comment by Jonnehs** [comment]
version is 2.3.9 on windows 2019 1809, no they are not retrys as far as I know, they get passed from Radarr and Sickchill

**Comment by Safihre** [comment]
You can try using 3.0.0 test-releases. They are pretty stable by now, at least Beta2 is for sure!

**Comment by Safihre** [comment]
You can try using 3.0.0 test-releases. They are pretty stable by now, at least Beta2 is for sure!

In 3.0.0 I did find an error that could cause this, so it's worth a try.

**Comment by Jonnehs** [comment]
Sure, I'll update and let you know

**Comment by Jonnehs** [comment]
doesn't seem to be any better https://imgur.com/a/1SWwnXe

**Comment by sanderjo** [comment]
Interesting: I can reporduce with this NZB https://raw.githubusercontent.com/sanderjo/NZBs/master/all-missing.nzb

![image](https://user-images.githubusercontent.com/1273502/84564873-5fdf6700-ad65-11ea-9083-7f5c2dcf045e.png)

**Comment by sanderjo** [comment]
Update: when I bring back to just one enabled newsserver, it fails within a second, which is good.

**Comment by Jonnehs** [comment]
I'm on supernews

**Comment by Jonnehs** [comment]
Which line in the logs am I looking for to confirm its a similar issue?

**Comment by Safihre** [comment]
@Jonnehs you only have 1 server? Can you share the NZB here or otherwise send it to me at safihre@sabznbd.org? I can share it with @sanderjo if needed.

**Comment by Jonnehs** [comment]
that domain has no MX record, can't be emailed 
![image](https://user-images.githubusercontent.com/11739441/84574863-54119600-ada1-11ea-9699-f6f184989e0c.png)

**Comment by thezoggy** [comment]
we use gmail with sabnzbd.org, 

```
 dig sabnzbd.org MX

; <<>> DiG 9.10.3-P4-Ubuntu <<>> sabnzbd.org MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29439
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;sabnzbd.org.			IN	MX

;; ANSWER SECTION:
sabnzbd.org.		299	IN	MX	20 alt2.aspmx.l.google.com.
sabnzbd.org.		299	IN	MX	30 aspmx2.googlemail.com.
sabnzbd.org.		299	IN	MX	30 aspmx3.googlemail.com.
sabnzbd.org.		299	IN	MX	30 aspmx5.googlemail.com.
sabnzbd.org.		299	IN	MX	10 aspmx.l.google.com.
sabnzbd.org.		299	IN	MX	20 alt1.aspmx.l.google.com.
sabnzbd.org.		299	IN	MX	30 aspmx4.googlemail.com.
```

**Comment by Jonnehs** [comment]
yes but he said sabznbd.org earlier, and copy and paste has no error checking!

Sent

**Comment by Safihre** [comment]
Sorry about that typo! 
Got the NZB, checking now.

**Comment by Safihre** [comment]
I tried with a bunch of different setups, and I just can't reproduce it on 3.0.0. All I could suggest is to start 3.0.0 but [with default settings (with back-up of old settings)](https://sabnzbd.org/wiki/faq#freshstart). 
I tried with just Supernews, Supernews+Newshosting and at different priority levels.

**Comment by Jonnehs** [comment]
very strange indeed, default config and re-integrated with radarr and it seems to be working. Strange, looking at a compare on the two INI files I cant see what might be stopping it

**Comment by sanderjo** [comment]
> I tried with a bunch of different setups, and I just can't reproduce it on 3.0.0. All I could suggest is to start 3.0.0 but [with default settings (with back-up of old settings)](https://sabnzbd.org/wiki/faq#freshstart).
> I tried with just Supernews, Supernews+Newshosting and at different priority levels.

I did a fresh `-f blabla.ini`, filled out speedium, and I can reproduce. Logging included.

![image](https://user-images.githubusercontent.com/1273502/84586125-d8523080-ae16-11ea-9363-83c4e4f39b43.png)

[sabnzbd---speedium-only.log](https://github.com/sabnzbd/sabnzbd/files/4775939/sabnzbd---speedium-only.log)

**Comment by Safihre** [comment]
The speedium problem is a bit different, because it is mega-slow. In your logging it has only really found 10 articles missing, it still has to try the other ones.

**Comment by sanderjo** [comment]
speedium mega-slow indeed:

newszilla6 takes 0.19 s for a 430:
```
$ time python3 check_newsserver.py newszilla6.xs4all.nl piet geheim '<ReGdVnGtDkYnAyVyExKbHkHl-1592123958586@nyuuXXXX>'
Error nntplib.NNTPTemporaryError: 430 No such article

real	0m0,192s
user	0m0,115s
sys	0m0,036s
```

whereas speedium takes 27 seconds:
```
$ time python3 check_newsserver.py newsreader3.speedium.nl  hidden xxxx '<ReGdVnGtDkYnAyVyExKbHkHl-1592123958586@nyuuXXX>'
Error nntplib.NNTPTemporaryError: 430 No such article

real	0m27,794s
user	0m0,089s
sys	0m0,005s
```
Hey, that is strange: a NNTPTemporaryError (=timeout), but also a 430 ... Maybe the 430 is already there ... but without an ENTER or so? BRB

**Comment by sanderjo** [comment]
FWIW: posted it on reddit: https://www.reddit.com/r/usenet/comments/h8t69s/speedium_40_second_timeout_on_nonexisting/

@Safihre The button Test Server for Speedium quickly says "OK". I wondered how that is possible, and here it the answer: that ARTICLE test is only run if no username/password was provided.
How about enabling this anyway, so that a slow server is clear at once?

```
    if not username or not password:
        nw.nntp.sock.sendall(b"ARTICLE <test@home>\r\n")
        try:
            nw.clear_data()
            nw.recv_chunk(block=True)
        except:
            # Some internal error, not always safe to close connection
            return False, str(sys.exc_info()[1])
```

**Comment by Safihre** [comment]
@Jonnehs Let's get back to the original issue.
Can you enable +Debug in the Status and Interface settings window and after it happens again share the logs with us here?

**Comment by Jonnehs** [comment]
Sure thing, shall I upgrade to beta4 first?

**Comment by Safihre** [comment]
Yes 👍

**Comment by Jonnehs** [comment]
Weird new manifestation which may or may not be related, it now also seems to take hours to reject blocks as missing;

![image](https://user-images.githubusercontent.com/11739441/84951114-df639200-b0e7-11ea-9ff1-772380446c42.png)

This will then also have the issue, in a few hours when it should have rejected this as an abort, it'll keep going.

Logs have been emailed

**Comment by Safihre** [comment]
I received the logs of @Jonnehs and just couldn't figure out for a longgg time why the fail-check was never called. I was digging through all the code for ages, only now to see that the NZB just contains 1 super large file instead of RAR-sets. We only trigger the fail-check when we finish a file, which doesn't happen in this case..

**Comment by Jonnehs** [comment]
any idea about the connection timeouts that makes it take so long to fail? Or is it all related? Happy I could help!

**Comment by Jonnehs** [comment]
I think it must also be related to this, as I can simply swap to another NZB and it works fine, hard to believe its a server issue. If you put the same NZB into nzbget you get timeouts at 90 seconds and then it aborts the download as missing. Currently sabnzbd will keep retrying for literally hours, stalling the whole queue.

**Comment by Safihre** [comment]
Seems Supernews specific, it's super slow to respond when asking for articles of this job. Yes, sabnzbd should cancel much quicker, but the timeouts are not it's fault 😏

**Comment by thezoggy** [comment]
you can change the timeout per server to be more aggressive to see if that helps
