### ISSUE TITLE
unzip vs 7zip

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1506]
when we start up sab binary a user sees:
```
2020-06-14 10:12:50,151::INFO::[SABnzbd:444] unzip binary... NOT found!
2020-06-14 10:12:50,151::INFO::[SABnzbd:447] 7za binary... found (C:\Program Files\SABnzbd\win\7zip\7za.exe)
```

the unzip warning is pretty pointless as we include 7zip...  but that got me thinking if logic processing for .zip are handled the same or different if the user has unzip+7za or just one of the other. it looks like we prefer 7za over unzip even if the user has both.

also, 7zip can do various formats but we only look to focus on .7z*?

do we want to start working towards removing unzip in lieu of just using 7zip (to reduce dependencies and platform normalize)

we could set enable_unzip to false by default (users could still toggle via config > specials if a need arises)

**Comment by Safihre** [comment]
Currently it's like this: if 7zip is present, we use it for both 7zip's and zip's.
If it's not present, but unzip is, we warn about missing 7zip on the first page of the Config and only zip's can be unpacked. 
If both are missing we warn about both on the first page of the Config.

It's mostly for Unix systems, where it's always a question what's available.

**Comment by Safihre** [comment]
@thezoggy is the something we should improve or change?

**Comment by thezoggy** [comment]
just seem like we have some redundant processing/dependencies. but if it works and not broken i guess no harm. the extra log noise about the windows binaries never having unzip isnt a huge thing.. and easy enough to just toggle off the option
