### ISSUE TITLE
New Beta3 API breaks Headphones & CouchPotato

### ISSUE THREAD

**Issue by myopenflixr** [sabnzbd/sabnzbd#1507]
Just updated to the new SAB 3.0.0 Beta3 and now both CouchPotato & Headphones are no longer sending nzb's to SAB.

Receiving this error on both: `Error sending NZB to SABnzbd: expects one parameter`

**Comment by Safihre** [comment]
Could you enable Debug logging in the Status window and then share the API call that Couchpotato makes? It's logged in Debug line.

**Comment by myopenflixr** [comment]
`06-14 14:12:42 ERROR
[chpotato.core.plugins.log] API log: {'file': u'https://HOST/couchpotato/static/scripts/combined.plugins.min.js?1572048877', 'message': u"chrome 83: \nUncaught TypeError: Cannot read property 'length' of undefined", 'line': u'1288', 'page': u'https://HOST/couchpotato/', '_request': <couchpotato.api.ApiHandler object at 0x7fc70f7cc6d0>}`

`06-14 14:12:14 INFO
[tato.core.plugins.release] Tried to download, but the "nzb" downloader gave an error`

`06-14 14:12:14 ERROR
[.core.downloaders.sabnzbd] Error getting data from SABNZBd: {}`

`06-14 14:12:14 ERROR
[.core.downloaders.sabnzbd] Error getting data from SABNZBd: expects one parameter`

**Comment by Safihre** [comment]
No I meant in sabnzbd to get the logging.

**Comment by myopenflixr** [comment]
Sorry....yes....give me a min to figure it out...Never had to view logging in SAB.

**Comment by myopenflixr** [comment]
Is this what you're looking for?

`2020-06-14 14:32:47,855::DEBUG::[apikey=<APIKEY>] API-call from 172.16.0.122 [CouchPotato linux - git-7260c12f - v2] {'nzbname': 'Top.Gun.1986.BluRay.1080p.DTS-HD.MA.6.1.x264-Grym.cp(tt0092099)', 'apikey':<APIKEY>', 'cat': 'movie', 'priority': '0', 'mode': 'addfile', 'output': 'json', 'nzbfile': <cherrypy._cpreqbody.Part object at 0x7f71bc398588>}`

**Comment by Safihre** [comment]
Yes, that's the one I need. And for headphones? Just to be sure. 
They seem to be using API parameters that we never officially supported, but always worked. I removed them, assuming nobody would use them. I can add them back.

**Comment by myopenflixr** [comment]
I believe the is the one from Headphones

`2020-06-14 14:43:38,575::DEBUG::[apikey=<APIKEY>] API-call from 172.16.0.123 [Headphones/-master (Linux 5.4.41-1-pve)] {'output': 'json', 'apikey':<APIKEY>', 'mode': 'addfile', 'cat': 'music', 'nzbfile': <cherrypy._cpreqbody.Part object at 0x7f719c7aac50>}`

**Comment by myopenflixr** [comment]
On a side note...Thank you for your quick response @Safihre !!!

**Comment by thezoggy** [comment]
cp's call:
https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/core/downloaders/sabnzbd.py#L65

**Comment by MrAnanas** [comment]
I just wanted to pitch-in, the new Beta3 also breaks Sonarr partially. The downloading works fine but the categories are not set... All are downloaded as "Default" despite the tag should be "tv". When I installed Beta2 again and used the same INI-file as I had in Beta3 then everything worked again...
I didn't start a new thread since I am sure it all hangs on the same issues as this thread is about.
Thanks for a great program BTW, and thanks for your efforts! Good luck with the bug-hunt...

**Comment by straying1** [comment]
Just want to chime in and say I have the exact same experience as @MrAnanas -- in beta3, all downloads being sent to Sab are being put in the "Default" category instead of my usual "tv" or "movies" category. 
Reverting back to the stable branch fixed the issue.

I know this thread is about Headphones, so please let me know if I should make a new thread or provide logs here.

**Comment by MrAnanas** [comment]
Hotio server has a direct access to the Beta2, in case you want to revert to that: hotio/sabnzbd:unstable-3.0.0Beta2

**Comment by Safihre** [comment]
Could you also share the API call you see in the sabnzbd log when Sonarr adds a job? Just to be sure.

**Comment by MrAnanas** [comment]
@Safihre Sure, I have done the following:
Cleared all logs and set SAB to debug logging, restarted the container and then added 3 random episodes to the download queue (with SAB on pause).
The whole log is here: https://pastebin.com/YZmvTjDh just so you are not missing any information.

**Comment by Safihre** [comment]
@MrAnanas Fixed the Sonarr bug to, it was unrelated to this one. But still a bug! 
Thank you for reporting, will see when I make a new release. Probably soon.

**Comment by MrAnanas** [comment]
Thank you for your quick reaction. Maybe an idea would be to take the beta3 away and have the beta2 as the unstable branch until the next beta is ready?

**Comment by Safihre** [comment]
Removed the in-app update notice and download from sabnzbd.org for now.
