### ISSUE TITLE
Beta 3 integration with Radarr broken

### ISSUE THREAD

**Issue by Jonnehs** [sabnzbd/sabnzbd#1508]
Updated to beta3 yesterday just because, but all movies being snatched were being added as 'default' not 'movies' as per my config - rolled back to beta2 and its fine

2020-06-15 11:29:01,164::DEBUG::[apikey=<APIKEY>] API-call from 10.25.1.60 [Radarr/0.2.0.1480 (windows server 6.2.9200.0)] {'mode': 'queue', 'start': '0', 'limit': '0', 'apikey':<APIKEY>', 'output': 'json'}
2020-06-15 11:29:01,179::DEBUG::[apikey=<APIKEY>] API-call from 10.25.1.60 [Radarr/0.2.0.1480 (windows server 6.2.9200.0)] {'mode': 'history', 'start': '0', 'limit': '30', 'category': 'movies', 'apikey':<APIKEY>', 'output': 'json'}

API call says 'movies' from radarr but in SAB...

![image](https://user-images.githubusercontent.com/11739441/84648167-85eb3f80-aefc-11ea-8be0-afffda294f16.png)

**Comment by sanderjo** [comment]
Related to / same as https://github.com/sabnzbd/sabnzbd/issues/1507 ?

**Comment by Jonnehs** [comment]
Could be, didnt see that one - feel free to merge

**Comment by Safihre** [comment]
Indeed it is #1507.

**Comment by thezoggy** [comment]
sadly b3 got pushed to ppa and now seeing tons of people hitting me up about sonarr being broken now because of sab upgrade (due to categories not set).

@jcfp  can you role back to beta2 or @Safihre can you push beta4

**Comment by thezoggy** [comment]
for those on ubuntu 18.04 here is a way to downgrade:
```
wget https://launchpad.net/~jcfp/+archive/ubuntu/ppa/+build/19395012/+files/sabnzbdplus_3.0.0~beta2-0ubuntu1~jcfp1~18.04_all.deb
sudo dpkg -i sabnzbdplus_3.0.0~beta2-0ubuntu1~jcfp1~18.04_all.deb
sudo apt-get install -f
```

**Comment by Safihre** [comment]
Will make a Beta4 today.
