### ISSUE TITLE
3.0.0B3 Windows 10 Retries not handled correctly and other issues

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1510]
Hi,

With 3.0.0. B3 retries are not handled correctly. As a sample I tried to download a password protected NZB without providing the proper password. It failed as expected. Then I retried by clicking on Retry in History and providing the password. SABnzbd then reports that the download is successful but the final, category based, destination folder has an empty folder for the NZB starting with _UNPACK that was created on the first try when the password was missing. I also find a folder for the NZB in the standard, not category based, complete folder. The folder creation time for this folder shows it is created when I retried with the password. But it only contains the password protected RAR with the file time of the first try without password. I have attached the debug log. The first failed try was done at 12:32 and the retry at 12:37.

Retries after the nntp server reported that an item was not available on the server are also reported as successful but the size of the download shows as 0 bytes in the history.

While checking the log I noticed something else related to API calls. My post processing script checks for certain categories the queue using the API. But not for the category that I did this test with. Also, during this test, the log of my post processing script shows that it was not started by SABnzbd. But the SABnzbd debug log (that I have attached) shows several API calls but these did not happen at the time shown in the log. So the API calls were done by my post processing script for previous downloads but are incorrectly reported in the log as occurring during the current download.

Another issue is that I cannot bulk delete History items. I can delete single items from the history by clicking on the garbage bin icon for the specific History item. But deleting history items using the garbage bin icon on the right bottom of the screen (purge history) does not appear to do anything.
[sabnzbd log.txt](https://github.com/sabnzbd/sabnzbd/files/4785947/sabnzbd.log.txt)

**Comment by Safihre** [comment]
There was something wrong with the category handling in Beta3, so I paused the release of it.
I build a new release of Beta3 that has the fixes inside. Could you give it a try?
https://github.com/sabnzbd/sabbuild/releases/tag/test-build-b3

At what time in the log did you try to bulk remove items from the history? I don't see any call in the history. Is your browser maybe showing errors in it's console window? (right-click on the page > Inspect Element)

The API-logging request can't really be wrong, what changed is that it now also logs the requests made by the interface.

**Comment by Safihre** [comment]
If it still fails with the passworded job, could you provide maybe an example NZB (can also send via email) with the correct password?

**Comment by ErikBrown2** [comment]
The download is still unsuccessful. First I tried without providing the correct password. This failed normally. The normal warnings were shown and an empty _UNPACK folder for the NZB in the category based final complete folder. The incomplete folder has a folder for the NZB with all the relevant files.

Then I retried and provided the password. The result was as follows:
-In the general complete folder there is a sub folder for the NZB but it contains only the password protected rar file.
-The _UNPACK folder in the category based final complete folder is still there and still empty.

I added the NZB at 15:23 and I retried at 15:28.

Regarding the removal of the history items, I delete successfully an individual item at 15:32. I tried unsuccessfully to purge the complete history list at 15:33 and unsuccessfully tried to purge the current history page at 15:34.

Regarding the "ghost" API calls, I just realised that SpotNet was running on my PC so maybe that caused the API calls. I will check that and let you know if it was not the cause.

I have emailed the test NZB.

**Comment by ErikBrown2** [comment]
The ghost API calls are still there. There should be nothing on my end that generates the calls. I just rebooted and did not  download anything with SABnzbd (so my post processing script did not run) and now the ghost API calls have the API key missing. Before my actual API key was shown. So I really assume that SABnzbd has some kind of cache for the API calls and that it is not cleared. Another thing is that my API calls use XML while the ghost API calls use JSON.

Ghost API call:
2020-06-16 16:05:13,306::DEBUG::[apikey=<APIKEY>] API-call from 127.0.0.1 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36] {'mode': 'queue', 'search': '', 'start': '0', 'limit': '10', 'output': 'json', 'apikey':<APIKEY>', '_': '1592309113065'}

My post processing API call:
http://127.0.0.1:8080/sabnzbd/api?mode=queue&output=xml&apikey=6f32e1d2121548b986e2450323aa977a
or from the log:
2020-06-16 16:47:51,874::DEBUG::[apikey=<APIKEY>] API-call from 127.0.0.1 [??] {'mode': 'queue', 'output': 'xml', 'apikey':<APIKEY>'}

**Comment by sanderjo** [comment]
> The ghost API calls are still there. There should be nothing on my end that generates the calls.

It's your own webbrowser accessing SAB. It's a new feature that that is logged.
You can turn that off: http://127.0.0.1:8080/sabnzbd/config/special/#api_logging

**Comment by Safihre** [comment]
Alright, I started to work on this:
1. The `_UNPACK_` folder being left isn't new, SABnzbd always did that. The reason is this: if we have 2 RAR-files inside an NZB, RAR-A and RAR-B. We first unpack RAR-A and it is a success, we then remove the data of RAR-A from the download-folder. Then we proceed to unpack RAR-B. If this fails, we leave the `_UNPACK_` folder with the unpack-result of RAR-A. In this case there is only RAR-B, so an empty `_UNPACK_` folder. I did however find old code that was supposed to renamed jobs like this `_FAILED_`. So I reactivated that code.
2. When retrying indeed all things were forgotten. I applied a patch now. Will push to develop so people can test.

**Comment by Safihre** [comment]
A new build for you to try will be available here shortly: https://github.com/sabnzbd/sabbuild/releases/tag/test-build-b3-2

**Comment by ErikBrown2** [comment]
The download retry works fine now. The empty folder is now indeed called _FAILED_xxx . But would it not be more clean to check first if the folder _UNPACK_xx is empty and if so, then delete it? 

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/4787806/sabnzbd.log)

**Comment by Safihre** [comment]
I thought about that, it would be possible.. It would have to be as the very last step.

**Comment by reloxx13** [comment]
this one is nice, thanks!
