### ISSUE TITLE
Reduce size of test-files

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1511]
Currently the `src` release became 23MB because we also include the `tests` folder.
We should reduce the size of all the test-files to the minimum required.

**Comment by thezoggy** [comment]
maybe move tests off as submodule and only check out when needed ?

**Comment by z3r0byt3s** [comment]
gzip them maybe ?

**Comment by Safihre** [comment]
This was more of a reminder ticket for myself. I just need to make them smaller, no need for 5MB test files, 100Kb is enough.
Just have to do it at some point :)

**Comment by sanderjo** [comment]
> no need for 5MB test files, 100Kb is enough.

let me know what I can do for you...
