### ISSUE TITLE
Subprocess.py issue?

### ISSUE THREAD

**Issue by moosejunky99** [sabnzbd/sabnzbd#1512]
Hi there,

I don't know if this is a bug or a known issue..

I updated to beta4 *(great work btw)*....

i get this
```
Setting up sabnzbdplus (3.0.0-beta4-0ubuntu1-jcfp1~18.04) ...
/usr/local/lib/python3.8/subprocess.py:838: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open (p2cwrite, 'wb', bufsize)
```
Just though i would pass it along...

moosejunky99

**Comment by sanderjo** [comment]
Where / when do you get this? During install? Or during running SAB?
There should be messages before that ... can you post them?

**Comment by moosejunky99** [comment]
that was a quick reply...

The following packages will be upgraded:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 sabnzbdplus
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 993 kB of archives.
After this operation, 4,096 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/jcfp/ppa/ubuntu bionic/main amd64 sabnzbdplus all                                                                                                                                                              3.0.0~beta4-0ubuntu1~jcfp1~18.04 [839 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-common a                                                                                                                                                             ll 2.4.101-2~18.04.1 [5,560 B]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm2 amd64 2                                                                                                                                                             .4.101-2~18.04.1 [32.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-amdgpu1                                                                                                                                                              amd64 2.4.101-2~18.04.1 [18.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-intel1 a                                                                                                                                                             md64 2.4.101-2~18.04.1 [60.0 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-nouveau2                                                                                                                                                              amd64 2.4.101-2~18.04.1 [16.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libdrm-radeon1                                                                                                                                                              amd64 2.4.101-2~18.04.1 [21.7 kB]
Fetched 993 kB in 0s (2,019 kB/s)
(Reading database ... 131702 files and directories currently installed.)
Preparing to unpack .../0-libdrm-common_2.4.101-2~18.04.1_all.deb ...
Unpacking libdrm-common (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.2) ...
Preparing to unpack .../1-libdrm2_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.2) ...
Preparing to unpack .../2-libdrm-amdgpu1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.2                                                                                                                                                             ) ...
Preparing to unpack .../3-libdrm-intel1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.2)                                                                                                                                                              ...
Preparing to unpack .../4-libdrm-nouveau2_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.                                                                                                                                                             2) ...
Preparing to unpack .../5-libdrm-radeon1_2.4.101-2~18.04.1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.101-2~18.04.1) over (2.4.99-1ubuntu1~18.04.2                                                                                                                                                             ) ...
Preparing to unpack .../6-sabnzbdplus_3.0.0~beta4-0ubuntu1~jcfp1~18.04_all.deb .                                                                                                                                                             ..
Unpacking sabnzbdplus (3.0.0~beta4-0ubuntu1~jcfp1~18.04) over (3.0.0~beta3-0ubun                                                                                                                                                             tu1~jcfp1~18.04) ...
Setting up libdrm-common (2.4.101-2~18.04.1) ...
Setting up sabnzbdplus (3.0.0~beta4-0ubuntu1~jcfp1~18.04) ...
/usr/local/lib/python3.8/subprocess.py:838: RuntimeWarning: line buffering (buff                                                                                                                                                             ering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
Setting up libdrm2:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-intel1:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.101-2~18.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.101-2~18.04.1) ...
Processing triggers for systemd (237-3ubuntu10.41) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for shared-mime-info (1.9-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for libc-bin (2.27-3ubuntu1) ...


hopefully that is what your looking for

**Comment by thezoggy** [comment]
Python is not buffering here and never was. The argument of buffering=1 was silently ignored.
The change to emit this warning is new in 3.8: https://bugs.python.org/issue32236

**Comment by Safihre** [comment]
This doesn't seem to be part of SABnzbd-code. Hopefully @jcfp knows!

**Comment by moosejunky99** [comment]
Ok thanks for looking into it.. Should i close it?

**Comment by jcfp** [comment]
> But anyways, as others noted this is part of the package installer (which jcfp provides via his ppa), he would have to address it. but its cosmetic and doesnt hurt anything.

This is neither sabnzbd code nor the packaging. The warning comes from python itself, specifically the one installed in `/usr/local/lib/python3.8`; the install location strongly suggest adding that was @moosejunky99's own doing.

**Comment by moosejunky99** [comment]
Haha perfect.. i knew it had to be me.. thanks for confirming it :) 

Maybe it is quickbox pro (seedbox install script) made that error come up that way..

great work on the product
