### ISSUE TITLE
Check for unwanted extensions in the NZB

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1513]
Supported by: https://forums.sabnzbd.org/viewtopic.php?f=3&t=24804

We only check inside the rar-files if there are unwanted extensions.. but what if they are just as a file inside the main NZB? We should detect those to.

**Comment by sanderjo** [comment]
can you give a hint:
- where is the loading of a NZB done?
- where is (de)selecting of a specific file in GUI done?

**Comment by sanderjo** [comment]
WIP: Detection is working, and failing works too, but in an ugly way ...

![image](https://user-images.githubusercontent.com/1273502/85043458-ab8e7800-b18c-11ea-9c38-09ee1bc32da7.png)

**Comment by sanderjo** [comment]
With the same code, and a fabricated with EXE in plain sight, and the rest just in plain RARs (NZB here: https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb_small_post_with_EXE_as_plain_file.nzb ), the code works quite nicely:

- On NZB import, the EXE file is skipped, with a warning.
- The rest is imported, and succesfully downloaded.

@Safihre I just skip the EXE (and other unwanted extensions). No pausing. I see that as the only feasible to do, without too much code overhauling. 

![image](https://user-images.githubusercontent.com/1273502/85130930-2069bc80-b236-11ea-93cb-0d16655ff16c.png)
