### ISSUE TITLE
Failed mail notifications break the download process

### ISSUE THREAD

**Issue by bambury** [sabnzbd/sabnzbd#1514]
If sabnzbd is configured to send an email notification after a download (and post-processing) is complete and such email fails to be delivered, the download in question is lost forever. No trace in the completed download folders, nor in the temp folder, nor in the orphaned jobs list.
I don't believe this is an intended behavior.

I'd be happy to help debugging this issue if needed, please let me know.

**Comment by Safihre** [comment]
Do you maybe have some logging with a traceback to show us where it went wrong?
Maybe you need to enable +Debug logging in the Status and Interface settings window.

**Comment by bambury** [comment]
You're right, I should have reproduced the problem and attached a log in the first place.
It seems it's not that simple - I just tried setting a wrong port for the SMTP server and sab gracefully completed the download and post-processing flow while showing a notification in the Web interface.

I experienced the problem when the SMTP settings were correct but the mail delivery itself failed with a 554 SMTP error and this won't be trivial to reproduce, since I'm not sure what exactly causes such failures with my mail server.

On another occasion I had a similar problem when mail notifications were disabled, but sab was unable to move the files to the destination directory after post-processing. Unfortunately, debug logging was not active at the time.

**Comment by sanderjo** [comment]
Change title from "Failed notifications ..." to "Failed MAIL notifications ..."?

**Comment by bambury** [comment]
Yes, sure, I can change that. I am not familiar enough with the codebase to make even an educated guess about whether the issue is limited to email notifications or not.
Also, I have not neglected this, but I haven't found a reliable way to reproduce the issue. I'll make sure to post here when it happens.
