### ISSUE TITLE
/etc/default/sabnzbdplus EXTRAOPTS=export LANG=en_US.UTF-8

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1517]
Pinging @jcfp 

Triggered by https://forums.sabnzbd.org/viewtopic.php?p=121181#p121181

When you put 
`EXTRAOPTS=export LANG=en_US.UTF-8`
into /etc/default/sabnzbdplus that would solve 
```
SABnzbd was started with encoding ISO-8859-1, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads.
```

Seems nice. If there is no downside (?), could that be an enrichment for the Ubuntu PPA package?

**Comment by Safihre** [comment]
And in this file? https://github.com/sabnzbd/sabnzbd/blob/develop/linux/sabnzbd%40.service

**Comment by jcfp** [comment]
@sanderjo No need, the init.d script already does this:
```
[ -r /etc/default/locale ] && {
        . /etc/default/locale;
        [ -n "$LANG" ] && export LANG;
}
export PYTHONIOENCODING=utf-8
```
Exporting LANG was added ages ago for unrar's unicode handling (at the time anyway). The PYTHONIOENCODING part is more recent and enough to get rid of the encoding warning.

When started as a regular application, users will still feed whatever their locale settings are to sab though (same as any other application), so this stuff may continue popping up every now and then.

Could make for a useful addition to the systemd example though.
