### ISSUE TITLE
sab 3.0b4 -- windows10 (build 2004) fresh install results in false "untrusted certificate" due to virus protection

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1518]
was using win7 with sab 3.0 b4.
installed new hdd and installed win10 pro (build 2004).
installed sab 3.0b4 and copied over my win7 sab admin folder. started up sab and tested each server and noticed that they are failing but worked fine on win7.

with cert validation set to minimal (what i had before)

news-us.usenetserver.com
news-eu.usenetserver.com
news-ssl.newsgroupdirect.com
news.usenetexpress.com
news.usenet.farm

now all throw the error on test:
> ('Server <server> uses an untrusted certificate [Certificate not valid. This is most probably a server issue.]

**Comment by thezoggy** [comment]
testing `news.usenet.farm` via our wiki:
https://www.appelboor.com/cgi-bin/check_newsserver.py?server=news.usenet.farm

shows that strict / default passes. so looks like bug in sab

**Comment by thezoggy** [comment]
Toggled off the default windows virus + threat protection and now it works as it did before.
Toggled it back on, and still working.. hmm. Leaving windows defender off for now.

**Comment by Safihre** [comment]
Should work with Defender turned on. We didn't change anything in the certificate validation part. But have seen before that Avast does place itself in the middle of secure connections.

**Comment by sanderjo** [comment]
@thezoggy 
With Defender ON resp OFF, can you run the command below (assuming you can run python3 on your Windows), and post the two outputs here
```
$ python3 -c "import ssl; print(ssl.get_server_certificate(('news.usenet.farm', 563))[:200])"

-----BEGIN CERTIFICATE-----
MIIFkTCCBHmgAwIBAgISA010srvdGRNabrUVc2VPSxLtMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw
```

**Comment by Safihre** [comment]
Will close, not much we can do about man in the middle by virusscanners. Have seen it more often that it required 1 or 2 restarts after Windows 10 feature updates before Sab worked again, because of all these special measures.

**Comment by thezoggy** [comment]
I tried to replicate but after I "fixed" it I couldn't unfix it. I'm guessing the system firewall/antivirus saw enough traffic to know not the mess with it.  :confused:
