### ISSUE TITLE
Sleep not prevented on macOS

### ISSUE THREAD

**Issue by aniqueta** [sabnzbd/sabnzbd#1521]
I believe this may be a new issue with recent versions of macOS. 

I'm running macOS Catalina 10.15.5, and SABnzbd 2.3.9 [03c10dc].

When downloading, SABnzbd does does successfully set the PreventUserIdleSystemSleep power assertion. However, I think in newer versions of macOS this does not have the same effect as before. 

At the moment, SABnzbd is not preventing sleep in situations when network access to SABnzbd woke the system. So, in cases of headless operation and remote upload of an NZB, what happens is that the download begins, but the system sleeps within ~30 seconds. 

Looking at other apps that are able to successfully prevent system sleep in headless and remote operation, I believe the power assertion now needs to be set to PreventSystemSleep. 

I think this is a simple change to make in sleepless.py:
https://github.com/sabnzbd/sabnzbd/blob/6d8c264e908e3d9ab0812e016c3eccd8dbe0a8d6/sabnzbd/utils/sleepless.py

Thank you.

**Comment by thezoggy** [comment]
were you testing with power nap? (as that changed how 'sleep' worked on macs)

**Comment by aniqueta** [comment]
Power Nap is disabled for my configuration.

**Comment by Safihre** [comment]
Could you try 3.0.0Beta4 and see how it behaves there? It works different than 2.3.9.

**Comment by aniqueta** [comment]
@Safihre Sorry for the delayed reply. I'll try this later this week.

**Comment by Safihre** [comment]
@aniqueta Did you find time to test this? ⌚

**Comment by aniqueta** [comment]
@Safihre Apologies for the delay. So the issue persists in 3.0.0 as described above. 

SABnzbd is still using the assertion PreventUserIdleSystemSleep but it's now set 4 times for 1 download. It also does not have the desired effect of keeping the system awake until the download completes. I do think the assertion that recent versions of macOS needs is PreventSystemSleep. This is what the built-in VNC / Screen Sharing uses, for example. 

3.0.0 also introduces a new related issue. Accessing the WebUI no longer wakes the machine from sleep. My understanding is this has to do with Bonjour advertisement. To see if there was something wonky with the settings post upgrade to 3.0.0, I toggled enable_bonjour off and on (with an app restart in between). That did not restore the earlier functionality of waking on network access. I poked around the code to see if I had an idea why this regress, but it's outside my skill to identify this. Sorry. 

Thanks!

**Comment by username4git** [comment]
I have an opposite issue but related issue. Running Mojave 10.14.6 and latest sabnzbd 3.0.1 on 2017 iMac. after a download completes, my system will no longer sleep. All activity has completed. this is new since upgrading to 3.0.

sleep                1 (sleep prevented by SABnzbd, SABnzbd, SABnzbd, SABnzbd)

   pid 8074(SABnzbd): [0x0011745f00018afa] 01:20:43 PreventUserIdleSystemSleep named: "SABnzbd is busy downloading and/or post-processing" 
   pid 8074(SABnzbd): [0x0011743d00018acf] 01:26:01 PreventUserIdleSystemSleep named: "SABnzbd is busy downloading and/or post-processing" 
   pid 8074(SABnzbd): [0x0011741c00018acb] 01:26:34 PreventUserIdleSystemSleep named: "SABnzbd is busy downloading and/or post-processing" 
   pid 8074(SABnzbd): [0x001173fb00018a87] 03:21:07 PreventUserIdleSystemSleep named: "SABnzbd is busy downloading and/or post-processing"

**Comment by Safihre** [comment]
@username4git You are right, this was a bug. I put the fix in 3.0.2RC2 that you can get from our Downloads page.
Could you let me know if it works? 👍 
I also included the change to `NoIdleSleepAssertion` discussed in this issue. I hope @aniqueta can confirm it works so this issue can be closed.

**Comment by username4git** [comment]
> Could you let me know if it works? 👍
seems to working normally again. Thanks for addressing this so quickly.

**Comment by aniqueta** [comment]
@Safihre Apologies for the delay. Will test Friday.

**Comment by aniqueta** [comment]
@Safihre Thanks for working on this. v3.0.2 resolves the sleep issue. The machine stays awake until the transfer is complete for my setup. Looks NoIdleSleepAssertion is the right one here. 

Unfortunately, I think this issue needs to stay open, or a new one needs to be created, for the wake-on-network-access issue. Connecting to the SABnzbd address and port does not wake the machine, as it used to pre v3. Other services registered with Bonjour have no such issue (e.g., ssh, vnc, transmission, etc.) Thoughts on this?

**Comment by Safihre** [comment]
@aniqueta Thanks for confirming.
Could you create a new issue with the expected behavior how it used to work?
I have to check how I can replicate it, since I only have 1 macOS machine.
