### ISSUE TITLE
python3.9 "Missing module: jaraco.collections"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1522]
I had this error before, was able to solve it, but it's back, and can't solve it right now.
I don't think it's python3.9 related, as a clean Ubuntu docker image runs well.
Tips appreciated.

```
sander@witte2004:~/git/sjo-sab$ python3.9 SABnzbd.py 
Not all required Python modules are available, please check requirements.txt
Missing module: jaraco.collections
You can read more at: https://sabnzbd.org/python3
If you still experience problems, remove all .pyc files in this folder and subfolders
```
A `find . -name "*.pyc" -type f -delete` does not help.

`jaraco.collections` is something used by cherrypy:

```
sander@witte2004:~/git/sjo-sab$ python3.9 -c "import cherrypy" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sander/.local/lib/python3.9/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/home/sander/.local/lib/python3.9/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/home/sander/.local/lib/python3.9/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
ModuleNotFoundError: No module named 'jaraco.collections'
```
Re-installing does not help
```
sander@witte2004:~/git/sjo-sab$ python3.9 -m pip install --force-reinstall --ignore-installed  jaraco.collections
Collecting jaraco.collections
  Using cached jaraco.collections-3.0.0-py2.py3-none-any.whl (9.4 kB)
Collecting jaraco.text
  Using cached jaraco.text-3.2.0-py2.py3-none-any.whl (8.1 kB)
Collecting jaraco.classes
  Using cached jaraco.classes-3.1.0-py2.py3-none-any.whl (5.7 kB)
Collecting six>=1.7.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting jaraco.functools
  Using cached jaraco.functools-3.0.1-py3-none-any.whl (6.7 kB)
Collecting more-itertools
  Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 778 kB/s 
Installing collected packages: more-itertools, jaraco.functools, six, jaraco.text, jaraco.classes, jaraco.collections
Successfully installed jaraco.classes-3.1.0 jaraco.collections-3.0.0 jaraco.functools-3.0.1 jaraco.text-3.2.0 more-itertools-8.4.0 six-1.15.0
```

grep fro jaraco in cherrypy for python3.8
sander@witte2004:~$ grep -irn jaraco /home/sander/.local/lib/python3.8/site-packages/cherrypy/
packages/cherrypy/lib/__pycache__/httputil.cpython-38.opt-2.pyc matches
sander@witte2004:~$ 

... are different then for cherrypy for python3.9:
sander@witte2004:~$ grep -irn jaraco /home/sander/.local/lib/python3.9/site-packages/cherrypy/
/home/sander/.local/lib/python3.9/site-packages/cherrypy/_helper.py:318:# Inlined from jaraco.classes 1.4.3
packages/cherrypy/lib/__pycache__/httputil.cpython-39.pyc matches
/home/sander/.local/lib/python3.9/site-packages/cherrypy/lib/httputil.py:20:import jaraco.collections
/home/sander/.local/lib/python3.9/site-packages/cherrypy/lib/httputil.py:390:class CaseInsensitiveDict(jaraco.collections.KeyTransformingDict):

**Comment by sanderjo** [comment]
Closing, as not a problem caused by SAB

**Comment by sir-wally** [comment]
Did you ever get this fixed? I'm having the same issue.

**Comment by Safihre** [comment]
@sir-wally Did you remove all the `.pyc` files before trying?

**Comment by sanderjo** [comment]
> Did you ever get this fixed? I'm having the same issue.

Yes. I thought I had written it somewhere ... but here we go:

It happened to me on Ubuntu, with **both** installed:
- python libraries (needed for SABnzbd) from the Ubuntu repo
- python libraries (needed for SABnzbd) from the python pip repo

Solution: don't install both. Most easy: install sabnzbd from the Ubuntu repo, upgrade via the JCFP PPA, and your'e done.
(so: do not install pip requirements)

**Comment by sir-wally** [comment]
@sanderjo  thanks much I'm fixed
