### ISSUE TITLE
SSL Suddenly Broken on Windows

### ISSUE THREAD

**Issue by LeeThompson** [sabnzbd/sabnzbd#1523]
Running on Windows 7 x64 (sabnzbd 2.3.9), suddenly today I've been getting this:

`SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)`

This installation has been working fine, sabnzbd hasn't even restarted in weeks.

**Comment by LeeThompson** [comment]
Not sure if this is related to https://github.com/sabnzbd/sabnzbd/issues/1130

**Comment by LeeThompson** [comment]
Got it working by setting `require_modern_tls` to true

I also had to change the cypher for Astraweb by forcing it to "`AES128-SHA`"

Going to leave this open for now just in case.

**Comment by Safihre** [comment]
The provider probably disabled the old ciphers and/or TLS/SSL versions.

**Comment by LangerFeen** [comment]
> Got it working by setting `require_modern_tls` to true
> 
> I also had to change the cypher for Astraweb by forcing it to "`AES128-SHA`"
> 
> Going to leave this open for now just in case.

THANK YOU @LeeThompson  !!!!! 
I've been going nuts the past day or so trying to sort this !!!
