### ISSUE TITLE
Update OpenSSL from 1.1.1d to 1.1.1g

### ISSUE THREAD

**Issue by Dazog** [sabnzbd/sabnzbd#1525]
Now that version 3 has hit RC1

Time to update OpenSSL 1.1.1d to 1.1.1g ?

Thanks

**Comment by thezoggy** [comment]
openssl is included in python version. depending on the platform/build you may get it. for example on macos its using 3.8.3 w/1.1.1g
windows binary still using 3.8.0 which is why you see 1.1.1d. i already hit up safihire about our appveyor settings to see if we can get it to use 3.8.3

**Comment by Safihre** [comment]
Agreed with @thezoggy! Will indeed force the use of latest Python also on Appveyor for the next Windows build.
