### ISSUE TITLE
start_paused switch causes '/queue' to return 'paused' value of 1

### ISSUE THREAD

**Issue by JagandeepBrar** [sabnzbd/sabnzbd#1542]
When using the `start_paused` switch to start the queue as paused, it causes the API call to fetch the queue to return a paused value of `1`, an integer, instead of an expected boolean. In every other situation (including if you toggle the paused/resume state), it returns a boolean of `true` or `false`.

**Comment by sanderjo** [comment]
Can you the show the relevant API output? So with start_paused off and on?

**Comment by Safihre** [comment]
@sanderjo I also start my Sabnzbd paused, so I was able to reproduce this. Will fix!

**Comment by JagandeepBrar** [comment]
I assume since you can replicate the issue you do not need the output, but I will still supply a screenshot to ensure there is no confusion. I was debugging with a user of mine, "Yours" was his output (where `start_paused` was enabled) and "Mine" was my personal instance where I do not use this switch.

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/3048295/86080428-7e797980-ba58-11ea-8748-629602b20333.png">

**Comment by sanderjo** [comment]
Thanks for the additional info, and thanks for analyzing this.

**Comment by Safihre** [comment]
Will be fixed in 3.0.0!
