### ISSUE TITLE
pause time drop-down list is click-transparent?

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1545]
Hi guys, not sure if this is a SABnzbd problem, but thought I'd report it anyway. 

I'm using SAB3 from git source/develop with the 'Glitter - night' interface accessed via FireFox 77.0 on Debian 10.4

I've just noticed an oddity. If using the tabbed UI layout, and you're on the history tab, then drop-down the "Pause for ..." list next to the main queue start/stop button, it's possible to see and click-on the search bar icon (magnifying glass icon) **through** the drop down list:

![screenshot](https://i.imgur.com/tv8gfSI.png)

I get the same behaviour with the Chromium v80 browser.

Only the icon can be selected. If the mouse cursor moves a little to the left or right of the icon, then the drop-down list item selection highlight effect reappears.

**Comment by Safihre** [comment]
Fixed 👍

**Comment by OneCDOnly** [comment]
Quick work! :+1: 

I had to clear my browser cache, but it now works fine. Thank you.

**Comment by thezoggy** [comment]
yep, cache busting is for version/when the release number changes as gets appended to urls. ex: `/static/stylesheets/glitter.css?v=3.0.0RC1`

**Comment by OneCDOnly** [comment]
Thanks @thezoggy I posted that more to help others. You guys already know what's needed. :grin:
