### ISSUE TITLE
sab - mac/osx support

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1547]
I noticed that firefox 78 came out this week and noted this being the last support for 10.9-10.11
> Firefox 78 is the last major release with support for macOS versions 10.9, 10.10 and 10.11. If you use one of these versions, you’ll be supported through Firefox ESR (Extended Support Release) 78.x for the coming year. 

Which got me thinking about how far back on osx/macos we support in sab.. I did not see anything in our wiki about specifics.
Not sure if 2.3.9 vs 3.0 has different support due to travis/xcode used. 

But anyways, thought we might want to document it.
As well as macos on arm..  as those have already started to ship to developers.

**Comment by Safihre** [comment]
@Cpuroast the current 3.0.0RC1 still works on macOS 10.9, right?

**Comment by Cpuroast** [comment]
Indeed, from 10.9 through 10.15

Would have opened a ticket if it didn’t.

On Jul 2, 2020, at 5:35 AM, Safihre <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cpuroast<https://github.com/Cpuroast> the current 3.0.0RC1 still works on macOS 10.9, right?

**Comment by Safihre** [comment]
Thanks 👍
