### ISSUE TITLE
Local LAN authentication

### ISSUE THREAD

**Issue by randompseudo** [sabnzbd/sabnzbd#1550]
It seems that local LAN authentication (the setting where you restrict internet access and list local IP ranges) isn't working as expected. 
 - Local subnet is 172.16.1.1/24
I have "172.16.1." listed in "list of local LAN ranges" in sab without the quotes. 

Sab is running on host:
 - Hostname: winserver
 - IP: 172.16.1.30
 - port: 8080

The PC I'm using to access sabnzbd has the IP 172.16.1.106.

I **can** access sab if I browse to it from another PC by typing in the IP directly: "http://172.16.1.30:8080"
I **cannot** access sab if I use the same PC and try to use "http://winserver.localdomain:8080". 

I get the error message:
`"Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check"`

.. and sab displays this message on the GUI:
`Refused connection with hostname "winserver.localdomain" from: 172.16.1.106>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0)Gecko/20100101 Firefox/78.0`
... so I'm obviously hitting sabnzbd's port and it's obviously not a DNS, hostname, firewall, etc issue. I can also use "http://winserver.localdomain:xxxx" to access services that are running on other ports, so I know that the hostname resolves OK.

How can I keep the restriction in place but access sab by hostname?

**Comment by Safihre** [comment]
I would suggest to read the documentation at the link that is shown in the error 😅 https://sabnzbd.org/hostname-check
