### ISSUE TITLE
priority not assigned correctly when importing from watched folder

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1552]
Hey guys, using SABnzbd 3 from GitHub source/develop on Debian 10.4

When SAB reads my RSS feeds and imports a movie, it correctly assigns the "movies" category and sets the priority to "force" - great!

When SAB reads from my watched folder and imports NZBs, the category is also correctly assigned "movies", but the priority is set to "normal". 

This used to work fine - import them and assign priority "force". How can we fix this? 

Cheers!

**Comment by thezoggy** [comment]
watch folder does not set priorities.. it would use whatever the 'default' is. you could always add a pre-queue script to adjust that/add intelligence.

**Comment by OneCDOnly** [comment]
This worked fine in SABnzbd 2.3.9 :confused: 

I'm hoping if this can't be fixed as an issue, maybe we could make it a feature request?

**Comment by thezoggy** [comment]
can you share logs from your 2.3.9 instance ?

**Comment by thezoggy** [comment]
and if you are running from source, you could try to back up to the commit before
https://github.com/sabnzbd/sabnzbd/pull/1502/files
to see if that is when the change was introduced

`9155ade937f21a88d5c7c3b3ff9abe83d8871088`

**Comment by OneCDOnly** [comment]
> can you share logs from your 2.3.9 instance ? (and your current instance) - full log so we see your .ini settings

No, I don't use 2.3.9 anymore. I've switched to 3.0.0

You could always install 2.3.9 yourself and try it. :wink:

**Comment by Safihre** [comment]
I can confirm something is going wrong here! It's indeed ignoring the category-priority.

**Comment by OneCDOnly** [comment]
Yup, I can confirm this now works again. Thanks @Safihre :grin:
