### ISSUE TITLE
Lubuntu (18.04 & 20.04) shows SAB icon in bottom bar, nothing with Ubuntu (18.04 & 20.04)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1553]
Pinging @jcfp 

On Lubuntu 18.04, when I start SAB, there is splash showing SAB has started, and a SAB icon in the bottom bar, with the right-mouse-click options. Nice & handy.

However, on Ubuntu 20.04, I only get the splash, not the icon. Is there a way to get the SAB on Ubuntu too?

Lubuntu:

![sabnzbd on Lubuntu 18 04](https://user-images.githubusercontent.com/1273502/87254044-f051ba00-c47f-11ea-8d2b-a99ec78ff54e.png)

FWIW:

This is SAB's logging on Lubuntu 18.04:

```
2020-07-12 20:44:20,830::DEBUG::[sabtraylinux:36] XApp not available, falling back to Gtk.StatusIcon
```

This is SAB's logging on Ubuntu 20.04:

```2020-07-12 20:33:51,048::DEBUG::[sabtraylinux:33] XApp found: <XAppProxyModule <IntrospectionModule 'XApp' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/XApp-1.0.typelib'>>```

Note: I always have the usual icons in the upper bar Wifi, Loudspeaker, Battery. Plus vlc and ksnip, when they are running:

![image](https://user-images.githubusercontent.com/1273502/87254571-cbf7dc80-c483-11ea-828e-d625b8b99cba.png)

So ... icons are possible.

**Comment by jcfp** [comment]
I don't know, I only tested only against a debian unstable vm; xapp and gtk statusicon stuff is really similar. Is there no sab 'presence' at all or is it simply not displaying the icon image (i.e. no icon shows but the menu is there when you click somewhere on the tray)? What happens if you remove the xapp support (package gir1.2-xapp-1.0), does the fallback work?

There's a number of different underlying mechanisms for displaying icons, sometimes a separate 'notification area' or something like that provides support for a subset of tray icons.

**Comment by sanderjo** [comment]
So ... you don't use SAB on Ubuntu yourself?

There is no presence at all, so not a hidden icon or so.

After removing `gir1.2-xapp-1.0` , SAB says:
```
2020-07-13 21:52:54,304::DEBUG::[sabtraylinux:36] XApp not available, falling back to Gtk.StatusIcon
```
but no icon.

I also tried this setting, but no effect at all

![image](https://user-images.githubusercontent.com/1273502/87347840-23657d80-c554-11ea-946a-8f3eaf55be77.png)

This is another setting overview, and `ksnip` is there, but SAB is not. Maybe that is the cause?

![image](https://user-images.githubusercontent.com/1273502/87348111-81926080-c554-11ea-85a5-11351dbd1593.png)

**Comment by jcfp** [comment]
> So ... you don't use SAB on Ubuntu yourself?
I use LTS releases only and wait until well after a new one was released before updating. No focal here, for now, other than in a VM.

I guess they mean the floating bubbles when it says "Notifications" in the settings. That stuff uses a notification daemon which provides a central point to toggle them on or off for certain applications.

When gnome decided that statusicons had to go, incorrectly assuming there were only used for showing notifications, that made getting statusicons to show up in various desktop environments an even bigger mess than before. My testing of the linux sabtray was in debian unstable with LXDE; both the old (gtk/fallback) and the new (xapp) work fine there. For gnome shell, some extensions are needed. I'm happy to help if you have suggestions for fixes or improvements in the current code, tracebacks, etc., but I cannot check every desktop environment out there. There's just too much variation.

**Comment by sanderjo** [comment]
Ah, so the sab status icon does appear on your Ubuntu 18.04? If so, it is version thing (18.04 versus 20.04), and not a DE thing (Lubuntu version Ubuntu)? Or ... maybe a setting thing in my Ubuntu 20.04

I will start a 18.04 in a VM, to see if a get a SAB icon. And I will start a fresh 20.04 in a VM.

**Comment by jcfp** [comment]
Yeah, it works. On Xubuntu 18.04, the sab statusicon (fallback/gtk code) is one of the icons that sits in a "notification area" which can be configured to appear on the taskbar in xfce. Xapp isn't available, the OS is too old to have a recent enough version of that. Haven't tried with xubuntu 20.04 yet.

**Comment by sanderjo** [comment]
Lubuntu 20.04 on VM: 
- correct icon in bottom bar
- FWIW: strange name in the splash screen

![image](https://user-images.githubusercontent.com/1273502/87439383-03d06280-c5f1-11ea-9ff6-a45a467a25ad.png)

So both Lubuntu 18.04 and 20.04 are OK

**Comment by sanderjo** [comment]
> Yeah, it works. On Xubuntu 18.04,

Ah, you use Xubuntu, not the plain/mainstream Ubuntu? If so: different DE ... Xubuntu uses Xfce, and Ubuntu uses GNOME, right? And Lubuntu uses LXQt. 
That might be the cause.

**Comment by jcfp** [comment]
Indeed, ymmv with different DEs. Same can probably be said for the weird title, I sure don't remember seeing that before. The string comes from the call to notify2.init() in notifier.py:173 and probably should be changed to something more sensible (like simply "SABnzbd" or so). Guess the param might well have served a different purpose in pynotify than the "app name" it sets in [notify2](https://notify2.readthedocs.io/en/latest/_modules/notify2.html), must have missed it when porting that code.

**Comment by sanderjo** [comment]
This confirms the hypothesis: also no icon with Ubuntu 18.04. I will change the title accordingly.

So it's a problem with plain Ubuntu (with GNOME), not with other Desktop Environments. Interesting to know what other Linux distro's with GNOME resp non-GNOME do.

I'll see if I can make a 10-line python program that puts a GTK icon on Xubuntu, but not on Ubuntu, and then ask in a Ubuntu forum


![image](https://user-images.githubusercontent.com/1273502/87467015-8f5cea00-c617-11ea-8203-df93a900040c.png)

**Comment by jcfp** [comment]
Might want to try your luck with some gnome shell extensions, esp. gnome-shell-extension-appindicator and gnome-shell-extension-top-icons-plus. Enable the extension(s) via gnome-tweaks util, will probably be auto-installed with the pkgs mentioned.

**Comment by sanderjo** [comment]
> Might want to try your luck with some gnome shell extensions, esp. gnome-shell-extension-appindicator and gnome-shell-extension-top-icons-plus. Enable the extension(s) via gnome-tweaks util, will probably be auto-installed with the pkgs mentioned.

Thanks.

gnome-tweaks and gnome-shell-extension-appindicator were installed. I only had to install gnome-shell-extension-top-icons-plus.
I went into gnome-tweaks, and turned on more options, started SAB but no icon in the top bar.

The strange thing: VLC and Ksnip do show an icon in the top bar. So it is possible Ubuntu-wise. Alas they are written in C/C++, so I can't check them how to do it in Python. 

![image](https://user-images.githubusercontent.com/1273502/87628256-d12d8380-c730-11ea-8db3-6515280e8843.png)

**Comment by sanderjo** [comment]
I checked on Kubuntu 20.04, and Kubuntu shows a steady icon in the lower bar, and pop-up icons for Download and Queue completes.

So the problem is Ubuntu only.
![sabnzbd icon](https://user-images.githubusercontent.com/1273502/90161192-14602e00-dd93-11ea-9010-ae697bd4eb63.png)
