### ISSUE TITLE
Feature Suggestion: build Deobfucaste.py into SABnzbd

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1555]
**Proposal**:

Build Deobfuscate.py's functionality (renaming files to the NZB name) into SABnzbd, so that it works automatically (option: build in an option "deobfuscate"), instead of a user to activate the post-processing script Deobfucaste.py, which is cumbersome, and limits the use of other post-processing scripts.

**Reason**

A lot of downloads result in a file like `2a843792ae8b4f32c0c3f9ad6979856d.mkv`. They can be played, but a meaningful name would be more handy. I checked: of my 583 mkv downloads, 232 (so about 50%) have the obfuscated 32-digit-hex format. 

We could have 3 levels of debobfuscations in the `deobfuscate` setting:

0. no deobfucation
1. only deobfuscation of files in format 32 digit hex (`^[a-f0-9]{32}`), which are certainly obfuscated. This will also work if there are >1 such files in a (combined) download
2. always, the biggest file, just like `Deobfuscate.py` does now.  `Deobfuscate.py` already excludes VOB files.

Locations to put this functionality into:
- https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L517 , so right before the usual post-processing script is run
- somewhere in https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/sorting.py , but unclear to me where/why

I'm assuming deobfuscation has no effect on external programs like sonarr etc.
I'm sure the renaming has no effect on VLC's vlsub, as that uses the hash of the file.

**Current behaviour of Deobfuscate.py**

1. find a par2 (like `rename.par2`) do to renaming
2. if not found: find biggest file (exluding VOB and BIN) and rename that the NZB name `SAB_FINAL_NAME`, keeping the extension in place. The script aborts if there are >1 big files.  

See https://github.com/sabnzbd/sabnzbd/blob/826c4057eaf816520c0e7a201498f5bf6085055f/scripts/Deobfuscate.py

Feedback welcome.

**Comment by sanderjo** [comment]
Some statistics:

```
$ find . -type f -size +100000k -exec ls -lh {} \; > files_bigger_than_100MB.txt
$ cat files_bigger_than_100MB.txt | wc -l
1053

```
So: 1053 files bigger than 100MB.

Existensions of those files:
```
$ cat files_bigger_than_100MB.txt | tr '[:upper:]' '[:lower:]' |  awk -F\. '{ print $NF }'  | sort | uniq -c
      3 1
      2 2
    241 avi
      2 divx
      3 epub
      2 img
     11 iso
      2 m2ts
      3 m4v
    533 mkv
     76 mp4
      2 par2
     76 pdf
      1 qnf9vk
     60 rar
     35 vob
      1 wmv
```

Extensions of files in 32-digit-hex format:
```
$ cat files_bigger_than_100MB.txt | tr '[:upper:]' '[:lower:]' | grep -E "[a-f0-9]{32}" | awk -F\. '{ print $NF }'  | sort | uniq -c
     16 avi
    231 mkv
     23 mp4
```

How many are obfuscated but not in 32-digit-hex format?

TBD

How many directories have >1 file >100MB? For example:


```
-rwxr-xr-x 1 sander root 4,4g jun 12  2011 ./bert g in da boat boxset nl pal dvdr-invited (3 dvd_s)/bert.g.in.da.boat.iso
-rwxr-xr-x 1 sander root 3,4g jun 12  2011 ./bert g in da boat boxset nl pal dvdr-invited (3 dvd_s)/bet.g.in.da.boatpart.2.iso
-rwxr-xr-x 1 sander root 3,3g jun 12  2011 ./bert g in da boat boxset nl pal dvdr-invited (3 dvd_s)/bert.g.in.da.boatpart.1.iso

```

**Comment by Safihre** [comment]
Considerations:
- Using Sorting would allow a user to enable it only for certain categories. It can be debated if that's actually needed to have it so specific.
- Just triggering it in PostProcessor with a switch in Config > Switches would be a bit hacky, but would still work fine.
- Having multiple levels is confusing for basic users, we just need to make it so reliable that it always works.

**Comment by sanderjo** [comment]
Does Sorting work for manually added NZBs? (I've never used Sorting, so I don't know what it does.)

If PostProcessor is acceptable, I would like to put the call there; easiest for me.

Your third remark: OK, clear. #reliable ... that means we must decide on this use case:

One download, with multiple bigger files (> 100MB) ... rename them all, so like:

My.Favourite.Download.mkv
My.Favourite.Download-A.mkv
My.Favourite.Download-B.mkv
 
Agree?

**Comment by Safihre** [comment]
Using A, B, C etc is not common. We should use 1, 2, 3 etc for which we already have a function in `filesystem.py` called something like `unique_filename` (will check later on desktop the exact name).

**Comment by sanderjo** [comment]
Do you mean `filesystem.get_unique_filename()` from https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L593 ?

**Comment by Safihre** [comment]
Yes 👍

**Comment by sanderjo** [comment]
Notes:

* use Debobfuste.py as basis
* put into /utils/ if runnable standalone (otherwise) /sabnzbd/
* use nzo.final_name and workdir_complete
* put in postprocess.py line 517
* rename file if big, AND is_probably_obfuscated() yields True, to avoid renaming files that have already a useful name

Hints for is_probably_obfuscated() 
* 32-hex-digit => certainly obfuscated
* entropy value: Below entropy 3.50 is often obfuscated or not-very-useful name. filename's entropy above 4.00 is a sign the name is not obfuscated. Entropy of filename between 3.50 and 4.00 is unclear.
* patterns that indicate a useful name: spaces, dots, underscores are signs of NOT obfuscated

**Comment by jcfp** [comment]
Note that there's already a is_obfuscated_filename() function, which simply checks the filename for the presence of an extension. If you're going for something more substantial, might as well expand that function.

**Comment by sanderjo** [comment]
Experimenting with the code and actual downloads, I realized this:

It is not alone about determining "is this filename obfuscated?".
It is about "is the info in the nzb-job-name `nzo.final_name` more useful than the plain filaneme?".

So: there is more relevant info than just the filename; we can compare.

I'll work on that.

**Comment by sanderjo** [comment]
Update: code working by inspecting filenames (not yet comparing them to the job name), and then renaming to the job name

Logging shows the reason for renaming

`699c1c9e2bdfb5224044bf25152b7ebb.bin` renamed to `reftestnzb Very Useful Subject (2020).bin`
```
2020-07-21 18:47:56,149::DEBUG::[postproc:521] Running deobfuscate on final result for dir /home/sander/Downloads/complete/reftestnzb Very Useful Subject (2020) and job name reftestnzb Very Useful Subject (2020)
2020-07-21 18:47:56,150::DEBUG::[deobfuscate:229] No par2 files found to process.
2020-07-21 18:47:56,150::DEBUG::[deobfuscate:244] Trying to see if there are large files to rename
2020-07-21 18:47:56,151::DEBUG::[deobfuscate:166] deobfus: handling 699c1c9e2bdfb5224044bf25152b7ebb.bin
2020-07-21 18:47:56,151::DEBUG::[deobfuscate:170] deobfus: 32 hex digit
2020-07-21 18:47:56,152::DEBUG::[deobfuscate:260] Renaming /home/sander/Downloads/complete/reftestnzb Very Useful Subject (2020)/699c1c9e2bdfb5224044bf25152b7ebb.bin to /home/sander/Downloads/complete/reftestnzb Very Useful Subject (2020)/reftestnzb Very Useful Subject (2020).bin
2020-07-21 18:47:56,152::DEBUG::[deobfuscate:266] Renaming done on run 1!
```


`100MB.bin` renamed to `test_download_100MB.bin`:
```
2020-07-21 18:51:08,321::DEBUG::[postproc:521] Running deobfuscate on final result for dir /home/sander/Downloads/complete/test_download_100MB.1 and job name test_download_100MB
2020-07-21 18:51:08,321::DEBUG::[deobfuscate:229] No par2 files found to process.
2020-07-21 18:51:08,321::DEBUG::[deobfuscate:244] Trying to see if there are large files to rename
2020-07-21 18:51:08,321::DEBUG::[deobfuscate:166] deobfus: handling 100MB.bin
2020-07-21 18:51:08,321::DEBUG::[deobfuscate:196] deobfus: entropy < 3.5
2020-07-21 18:51:08,321::DEBUG::[deobfuscate:260] Renaming /home/sander/Downloads/complete/test_download_100MB.1/100MB.bin to /home/sander/Downloads/complete/test_download_100MB.1/test_download_100MB.bin
2020-07-21 18:51:08,322::DEBUG::[deobfuscate:266] Renaming done on run 0!

```

**Comment by sanderjo** [comment]
I consider not using the name `deobfuscate` (because: already used for the real deobfuscating of rar files) for this feature, but `enrich filenames` or `improve filenames`.

**Comment by sanderjo** [comment]
@Safihre are you OK with naming the module and function `improve_filenames`? Or `improve_final_filenames`, if that is better?

**Comment by Safihre** [comment]
Hmm, what about `Deobfuscate final filenames`, and then we can explain as the sub-text what it means?
"Improve" is too vague (in my opinion).

**Comment by Safihre** [comment]
Done!
