### ISSUE TITLE
[Feature Request] Add some basic shortcuts/keybindings

### ISSUE THREAD

**Issue by awsms** [sabnzbd/sabnzbd#1556]
I was thinking about something similar to NZBGET, such as Shift+P to pause the current downloads, "A" to add a new nzb etc.

**Comment by sanderjo** [comment]
Nice! Just like in gmail where I use c for compose, CTRL ENTER for send, u for going back, j and k for moving up and down (Hello, VI!)

But ... after that A ... you still need mouse to select what to add, right?

**Comment by thezoggy** [comment]
If this does get added, be sure to include a way to disable the shortcuts.

**Comment by Safihre** [comment]
The shortcuts only work if you have the webpage open, right?

**Comment by sanderjo** [comment]
> The shortcuts only work if you have the webpage open, right?

Correct
Don't you use the keyboard shortcuts in Gmail? See https://support.google.com/mail/answer/6594?co=GENIE.Platform%3DDesktop ... very handy.

**Comment by sanderjo** [comment]
Suggestions:

A = Add NZB
P = Pause / Unpause
C = Config
S = Search Config
... = Status (Wrench), with in there R -> Refresh

**Comment by thezoggy** [comment]
Like in Google's apps I turn off the shortcuts commands because it messed with browser/os stuff because I would leave the webpage open but may be on a different monitor. I generally disable shortcut for apps until I know that I am okay with their shortcuts winning or I can reassign them so they don't conflict. This is a constant battle on macos where there are so many shortcuts.

**Comment by Safihre** [comment]
Anyone, feel free to contribute 💯

**Comment by Safihre** [comment]
Anyone have strong opinions about the shortcuts added by @skbotnl in #2031?
They are enabled by default.

**Comment by sanderjo** [comment]
> Anyone have strong opinions about the shortcuts added by @SKBotNL in #2031?

I love them already.

> They are enabled by default.

OK for me. How can someone disable them? I don't see anything related when I search for "key".
