### ISSUE TITLE
macOS Crash - TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by Goobaroo** [sabnzbd/sabnzbd#1557]
Getting a regular crash while downloading.

INFO:cherrypy.error:[19/Jul/2020:17:19:39] ENGINE Bus STARTED
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyc", line 801, in __bootstrap_inner
  File "sabnzbd/assembler.pyc", line 74, in run
TypeError: cannot concatenate 'str' and 'int' objects
INFO:cherrypy.error:[19/Jul/2020:17:22:36] ENGINE Bus STOPPING

OS: 10.15.5 (19F101)
SabNZB Version: 2.3.9

**Comment by Goobaroo** [comment]
Same issue in 3.0.0RC2

INFO:cherrypy.error:[19/Jul/2020:18:14:56] ENGINE Bus STARTED
multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
WARNING:root:Unsuccessful login attempt from 192.168.0.2
WARNING:root:Unsuccessful login attempt from 192.168.0.2
multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "sabnzbd/assembler.py", line 74, in run
TypeError: can only concatenate str (not "int") to str
INFO:cherrypy.error:[19/Jul/2020:18:16:13] ENGINE Bus STOPPING

**Comment by thezoggy** [comment]
Can you enable debug logging and share the log

**Comment by Safihre** [comment]
Found the issue.
What do you have set for the Config > Folder setting "Minimum Free Space for Temporary Download Folder"?

**Comment by Goobaroo** [comment]
Minimum Free Space was set to -1, so your assumption was correct.

**Comment by Safihre** [comment]
That's only a valid setting for the Article Cache, but still, fixed a function :)
