### ISSUE TITLE
History not available in Palemoon

### ISSUE THREAD

**Issue by JackDandy** [sabnzbd/sabnzbd#1559]
Hello,

When upgrading using existing data folder from git source branch 2.3.9 (master) to 3.0.0 (master), the history seems to not migrate, if I switch back to 2.3.9, the history is available again with a couple of new error warnings, so a backup dataset is restored for good measure. 

Is there a way to import and maintain the years of historical data when upgrading?  
  
Images of good times...  
  
<img src="https://i.vgy.me/Eidp6H.png">
<img src="https://i.vgy.me/6KW6Ur.png">
  
Images after an upgrade...  

<img src="https://i.vgy.me/KO7kRI.png">
<img src="https://i.vgy.me/grsG5p.png">
    
I hope I haven't missed something obvious.
  
Thanks.

**Comment by sanderjo** [comment]
Hi Jack,

I myself have never had this problem with History.

What happens when you use the Windows binary release, and do not speed the ini file?


Sander

**Comment by JackDandy** [comment]
Hi Sander, 

I've always run SABnzbd from git source, never from the Windows binary. Not sure what you mean with the verb `"speed"` the ini file.

Thanks

**Comment by sanderjo** [comment]
'speed' was a typo; corrected to 'specify'. So ... can you do that? So not specify the ini file?

And in config -> folder: what do you see at Administrative Folder in both cases?

**Comment by Safihre** [comment]
And of course, can you enable Debug logging in the Status window and then after you switch again check the logs if there is any indication what is going wrong?

**Comment by JackDandy** [comment]
Okay, 

1) If I do not specify a .ini file, then sab will default to some wizard setup thing, then that defeats the purpose of using my existing data as I've always done via my desktop shortcut.
2) both cases `admin` is the folder name, in there, my history1.db file is ~14MB.
2) logging is changed from debug to error/warnings when i switch to develop 3.0.0, so i change the setting back to '+debug' and have to restart for that change to 'take'. Doesn't matter as there is no tracebacks or any error in the logs anyhoo.

I fear this is not going to get anywhere given there are no obvious errors, so it's at least reported, and I guess we will see if others experience the same symptom, or if perhaps somewhere along the timeline only my historical data has become incompatible with 3.0.0.
 
Again, thanks for the support guys.

**Comment by JackDandy** [comment]
Oh there is one thing... in the **console** only, is this output on startup of 3.0.0 RC2....
```
2020-07-23 00:28:45,607::INFO::[SABnzbd:1403] Starting web-interface on 0.0.0.0:8195
2020-07-23 00:28:45,607::INFO::[_cplogging:213] [23/Jul/2020:00:28:45] ENGINE Bus STARTING
Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python38\lib\site-packages\cheroot\ssl\builtin.py", line 72, in <lambda>
    target=lambda: context.wrap_socket(
  File "C:\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2020-07-23 00:28:45,837::INFO::[_cplogging:213] [23/Jul/2020:00:28:45] ENGINE Serving on https://0.0.0.0:8195
2020-07-23 00:28:46,048::INFO::[_cplogging:213] [23/Jul/2020:00:28:46] ENGINE Serving on http://0.0.0.0:8196
2020-07-23 00:28:46,048::INFO::[_cplogging:213] [23/Jul/2020:00:28:46] ENGINE Bus STARTED
2020-07-23 00:28:46,050::INFO::[SABnzbd:1440] Starting SABnzbd.py-3.0.0-develop
```
I guess it could be that this error is preventing the history logic from running. This error does **not** appear in the log files.

Hope that helps.

**Comment by thezoggy** [comment]
Win10? Are you using windows defender / antivirus?

**Comment by Safihre** [comment]
Very strange. Maybe it's a limitation of Python 3, because the history code wasn't really changed at all. Could you be willing to zip your history1.db and send it to me?

**Comment by thezoggy** [comment]
just to note that i upgraded from 2.3.x to 3.x with windows binary and my 19M history file was just fine. (and going from win7 -> win10 in between upgrades).

i did have a hiccup at first when i first tried to ran sab on win10 as admin, as it was not happy with directory access. stopping and restarting as a normal user it was then happy. then a day later I had problems doing server test with it failing, but that turned out to be windows defender interfering. togging defender off then back on I couldn't reproduce the issue (but also may have just gone away due to windows 10 updates)

**Comment by JackDandy** [comment]
Okay, taking on board your offer @Safihre I decided to move the install to another machine to test there, and in light of @thezoggy comment, I checked defender, turns out defender was not enabled on one PC, the one exhibiting fault. 

So, I finally got the history working on the alt machine after some browser refresh shenanigans, at one point the failed items would not display at all, it was odd, the view just didn't want to play at first in WaterFox, but then it started working.

So, i copied the working `history1.db` back to the failing machine, and same result as before. I tried a different browser; instead of Palemoon 28.11.0, I used WaterFox 2019.12 - lo and behold, WaterFox worked, I doubled checked my other PC, and WaterFox 2020.06 was in use there, so norrowing down to... a newer vs older waterfox vs new Palemoon. It seems as though my issue is isolated and related to Palemoon. I restarted it in safe mode, the issue still persists with all addons etc. disabled.

So, there seems to be an issue displaying an upgraded history1.db in Palemoon. I reduced the db to just 10 records, the issue persists (see screenshot).

The `history1.db` with sensitive fields redacted, that is failing to display in Palemoon is [here](https://mega.nz/folder/58lnhSaT#X4F4zIh_vaHohVJqpwV6Mg)

And an image... 
<img src="https://i.vgy.me/srt3bV.png">

Hope this helps.

Thanks again everyone :)

**Comment by JackDandy** [comment]
And finally, the meat?...

<img src="https://i.vgy.me/ZLyWNg.png">

**Comment by sanderjo** [comment]
So ...
* only something in the presentation layer? or
* something in the presentation layer that is only triggered by something in history1.db?

**Comment by JackDandy** [comment]
I think presentation layer, however, I linked above to the data, in case you can't replicate the issue in Palemoon.

**Comment by JackDandy** [comment]
I think presentation layer, however, I linked above to the data, in case you can't replicate the issue in Palemoon with your existing history1.db.

**Comment by sanderjo** [comment]
Does it also happen in mainstream browsers like Chrome, Firefox (from which Waterfox is probably derived) and Edge?

In others words: generic presentation problem, or Waterfox specific?

FWIW: @Safihre has limited access to a computer right now

**Comment by JackDandy** [comment]
@sanderjo 

Umm, I did testing and narrowed down to Palemoon **not** Waterfox.

Please re-read my last three posts on the Github website as it appears you maybe reading emails that contain only a first draft of a reply, but i edited the post added info as i found more out, those edits are not sent by github via email so it seems you are out of sync here. I spent a few hours isolating this for you guys. I think you have more than enough to take over at your side now in regards to what ever other browsers may be afflicted.

**Comment by JackDandy** [comment]
@sanderjo Umm, I did testing and narrowed down to Palemoon **not** Waterfox.

Please re-read my last three posts on the GitHub website as it appears you maybe reading emails that contain only a first draft of a reply, but i edited the post added info as i found more out, those edits are not sent by GitHub via email so it seems you are out of sync here. I spent a few hours isolating this for you guys. I think you have more than enough to take over at your side now in regards to what ever other browsers may be afflicted.

No rush, @Safihre - I reverted to the version that I said works, and the things I needed to test, I can now test fine, so I'm off to answer the issues asked of me before this particular issue came to light 24 hrs ago.

**Comment by Safihre** [comment]
Hmmm, not sure what to do with this. Palemoon seems to omit a rather standard set of functions: https://caniuse.com/#feat=addeventlistener&search=Addeventlistener
So I wouldn't really call this a bug in SABnzbd.. But an omission of Palemoon.

**Comment by JackDandy** [comment]
The last updated `knockout` lib broke the UI for SAB3. Before that lib was updated, SAB3 worked just fine. But now that 3.x.x is merged to master, maybe some other Palemoon SAB3 user will voice up, or just use another browser, that's easy enough.

**Comment by thezoggy** [comment]
if its a bug with knockout lib, then ideally that bug needs to be reported over there so then sab/other apps that use it can benefit once it gets fixed.

**Comment by thezoggy** [comment]
got around to loading up palemoon 28.11.0 (portable) and it is working fine showing the history with sab 3.0 final.
my sab history is 19+M (with stuff going back to 2010-10-24). changed layout to tabbed, searched, etc.. everything working just fine

**Comment by JackDandy** [comment]
FYI; I wasn't using portable. I was first using the official installation mode on W10, and then (as I noted above) I enabled the "browser safe mode" in order to rule out extension interference. My history is also many years old.  Strange that my PM created the console output that I screen grabbed for you chaps. Anyway, I simply moved SAB over to Waterfox as it works fine on that one. If it cannot be replicated, then i'll just assume it to be a local oddity.

**Comment by Gittyperson** [comment]
I've just upgrade to 3.0.0 and also to Pale Moon 28.12.0 x64 (from 28.11.0). Everything seems to work fine, except for the fact that "Show interface" does not work. Launch Browser on Startup is also enabled and Pale Moon is set as Default Browser. This simply stopped working. Manually entering the URL works and the interface shows up normally.

**Comment by Gittyperson** [comment]
Ok, that was quick... I remembered a similar issue with another program. Solution:

1. Close Pale Moon.
2. Set it again as default browser from the W10 Settings. It can be set again, even if it is already set.
3. Problem solved, hopefully permanently although this same issue did reappear every now and then with that other program.
