### ISSUE TITLE
[Feature Requests] Improvements to the "Add NZB" modal window

### ISSUE THREAD

**Issue by jamver** [sabnzbd/sabnzbd#1560]
A number of minor changes to the "Add NZB" modal window to improve speed and avoid needing to use the mouse:

* Autofocus on the URL text entry field 
* Allow enter/carriage return to submit the form
* When using tab to switch between elements, highlight the current selected element, e.g. Category/Priority/Processing dropdown lists

**Comment by Safihre** [comment]
> Allow enter/carriage return to submit the form

That's a bit hard, since we have 2 submit buttons. For the URL and the file.
The other ones I can look into!

**Comment by jamver** [comment]
Thanks for accepting the request.

I understand the point about the 2 submit buttons, however, only the Fetch button makes sense to activate on carriage return as the Upload button requires mouse interaction

**Comment by Safihre** [comment]
> When using tab to switch between elements, highlight the current selected element, e.g. Category/Priority/Processing dropdown lists

This already happend when in the regular Glitter skin, but not in the Night-mode. I added a highlight there.
The carriage return will now submit the form.
I didn't do the autofocus when opening the modal, this was a bit tricky and 2 tabs also do the job.
