### ISSUE TITLE
Sickbeard adding repeat duplicate nzbs to sabnzbd

### ISSUE THREAD

**Issue by zeus65** [sabnzbd/sabnzbd#1561]
For some reason since upgrading to 20.04 ubuntu I notice sickbeard struggles to add nzbs to sabnzbd, It actually does it but for some reason doesn't think the response was correct?

e.g.
2020-07-27 22:38:30 SEARCHQUEUE-BACKLOG-295647 :: Unknown failure sending NZB to sab. Return text is: {'status': True, 'nzo_ids': ['SABnzbd_nzo_fhfyge7e']}

This is causing my sabnzbd to download multiple copies of the same thing.

I even tried to switch the connection to https. That hasn't helped

Just wondering if the sabnzbd response has change or some such?

**Comment by sanderjo** [comment]
Ubuntu 20.04 uses a pre-alpha version of SAB 3.
SAB 3 is more strict on the API
https://github.com/midgetspy/Sick-Beard/ is 8 years old.

Anyway: use the PPA of SABnzbd to get a more recent version of SAB 3. Then test again.

**Comment by zeus65** [comment]
> Ubuntu 20.04 uses a pre-alpha version of SAB 3.
> SAB 3 is more strict on the API
> https://github.com/midgetspy/Sick-Beard/ is 8 years old.
> 
> Anyway: use the PPA of SABnzbd to get a more recent version of SAB 3. Then test again.

Thanks Sanderjo

just mentioning I have the ppa installed and currently using 
3.0.0RC2 [aabb709]

Understood that Sickbeard is very old but its served me well over the years. I have heard of a few alternatives like sickrage but never bothered as sickbeard was working so well.

Any other project you would suggest?

**Comment by zeus65** [comment]
Ps think I found the code spot :), sab.py was expecting a response of ok. I'll try change it...

**Comment by zeus65** [comment]
Fixed in .sickbeard/sickbeard/sab.py


From:
    # do some crude parsing of the result text to determine what SAB said
    if "sabText == "ok":
        logger.log(u"NZB sent to SAB successfully", logger.DEBUG)
        return True
    elif sabText == "Missing authentication":
        logger.log(u"Incorrect username/password sent to SAB, NZB not sent", logger.ERROR)
        return False
    else:
        logger.log(u"Unknown failure sending NZB to sab. Return text is: " + sabText, logger.ERROR)
        return False



    # do some crude parsing of the result text to determine what SAB said
    if "True" in sabText:
        logger.log(u"NZB sent to SAB successfully", logger.DEBUG)
        return True
    elif "Missing authentication" in sabText:
        logger.log(u"Incorrect username/password sent to SAB, NZB not sent", logger.ERROR)
        return False
    else:
        logger.log(u"Unknown failure sending NZB to sab. Return text is: " + sabText, logger.ERROR)
        return False

**Comment by thezoggy** [comment]
You would be better off switching to any of the maintained sickbeard forks

**Comment by zeus65** [comment]
> You would be better off switching to any of the maintained sickbeard forks

Thanks Any suggestions before I go and start my research?

**Comment by thezoggy** [comment]
@zeus65 sickchill or sickgear are probably your best bet if you want to stay in the sb family. lots of people switched to sonarr for various other reasons+features that depending on your needs may be better suited.
