### ISSUE TITLE
Certificate verification issue on Windows Server Core

### ISSUE THREAD

**Issue by Veduco** [sabnzbd/sabnzbd#1564]
Upon upgrading from the stable 2.x release to the stable 3.0.0 (beta released impacted as well), I am presented with certificate verification failures that did not happen prior to the upgrade.

I initially tried the standard exe installer, but I have since moved to the standalone x64 bundle, configured it with my ini, and started the service.

    $ cat sabnzbd.log | grep INFO | grep -i -e Platform -e "SSL version" -e python-version | sort | tail -15
    2020-08-02 12:23:07,753::INFO::[SABnzbd:1169] SSL version = OpenSSL 1.1.1g  21 Apr 2020
    2020-08-02 12:38:03,801::INFO::[SABnzbd:1144] Platform = Windows-10-10.0.18362-SP0 (win64)
    2020-08-02 12:38:03,801::INFO::[SABnzbd:1149] Python-version = 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

![image](https://user-images.githubusercontent.com/59983694/89130173-07ecf300-d4c0-11ea-8b87-e65804a16711.png)

When I use the exe installation, I am not initially presented with the error shown in the 'General' tab, but instead, every URL the server receives, it claims as invalid.
sabnzbd.log in this case shows
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`
![image](https://user-images.githubusercontent.com/59983694/89130311-1be52480-d4c1-11ea-8e1f-4a066a07ba85.png)

Link to the standalone installer used:
https://github.com/sabnzbd/sabnzbd/releases/download/3.0.0/SABnzbd-3.0.0-win64-bin.zip

Link to the executable used:
https://github.com/sabnzbd/sabnzbd/releases/download/3.0.0/SABnzbd-3.0.0-win-setup.exe

    > Get-ComputerInfo
    
    
    WindowsBuildLabEx                                       : 18362.1.amd64fre.19h1_release.190318-1202
    WindowsCurrentVersion                                   : 6.3
    WindowsEditionId                                        : ServerDatacenterACor
    WindowsInstallationType                                 : Server Core
    WindowsInstallDateFromRegistry                          : 3/15/2020 10:59:56 AM
    WindowsProductId                                        : 00431-40000-00000-AA036
    WindowsProductName                                      : Windows Server Datacenter
    WindowsRegisteredOrganization                           :
    WindowsRegisteredOwner                                  : <censored>
    WindowsSystemRoot                                       : C:\Windows
    WindowsVersion                                          : 1909
    BiosCharacteristics                                     : {4, 7, 9, 11...}
    BiosBIOSVersion                                         : {INTEL  - 6040000, VMW71.00V.13989454.B64.1906190538,
                                                              VMware, Inc. - 10000}
    BiosBuildNumber                                         :
    BiosCaption                                             : VMW71.00V.13989454.B64.1906190538
    BiosCodeSet                                             :
    BiosCurrentLanguage                                     :
    BiosDescription                                         : VMW71.00V.13989454.B64.1906190538
    BiosEmbeddedControllerMajorVersion                      : 255
    BiosEmbeddedControllerMinorVersion                      : 255
    BiosFirmwareType                                        : Uefi
    BiosIdentificationCode                                  :
    BiosInstallableLanguages                                :
    BiosInstallDate                                         :
    BiosLanguageEdition                                     :
    BiosListOfLanguages                                     :
    BiosManufacturer                                        : VMware, Inc.
    BiosName                                                : VMW71.00V.13989454.B64.1906190538
    BiosOtherTargetOS                                       :
    BiosPrimaryBIOS                                         : True
    BiosReleaseDate                                         : 6/18/2019 6:00:00 PM
    BiosSeralNumber                                         : VMware-42 3d a0 8f 00 00 4f db-99 63 fc 58 0b b9 2e ba
    BiosSMBIOSBIOSVersion                                   : VMW71.00V.13989454.B64.1906190538
    BiosSMBIOSMajorVersion                                  : 2
    BiosSMBIOSMinorVersion                                  : 7
    BiosSMBIOSPresent                                       : True
    BiosSoftwareElementState                                : Running
    BiosStatus                                              : OK
    BiosSystemBiosMajorVersion                              : 255
    BiosSystemBiosMinorVersion                              : 255
    BiosTargetOperatingSystem                               : 0
    BiosVersion                                             : INTEL  - 6040000
    CsAdminPasswordStatus                                   : Enabled
    CsAutomaticManagedPagefile                              : True
    CsAutomaticResetBootOption                              : True
    CsAutomaticResetCapability                              : True
    CsBootOptionOnLimit                                     : DoNotReboot
    CsBootOptionOnWatchDog                                  : DoNotReboot
    CsBootROMSupported                                      : True
    CsBootStatus                                            : {0, 0, 0, 33...}
    CsBootupState                                           : Normal boot
    CsCaption                                               : <censored>
    CsChassisBootupState                                    : Safe
    CsChassisSKUNumber                                      :
    CsCurrentTimeZone                                       : -360
    CsDaylightInEffect                                      : True
    CsDescription                                           : AT/AT COMPATIBLE
    CsDNSHostName                                           : <censored>
    CsDomain                                                : <censored>
    CsDomainRole                                            : MemberServer
    CsEnableDaylightSavingsTime                             : True
    CsFrontPanelResetStatus                                 : Unknown
    CsHypervisorPresent                                     : True
    CsInfraredSupported                                     : False
    CsInitialLoadInfo                                       :
    CsInstallDate                                           :
    CsKeyboardPasswordStatus                                : Unknown
    CsLastLoadInfo                                          :
    CsManufacturer                                          : VMware, Inc.
    CsModel                                                 : VMware7,1
    CsName                                                  : <censored>
    CsNetworkAdapters                                       : {Ethernet0}
    CsNetworkServerModeEnabled                              : True
    CsNumberOfLogicalProcessors                             : 8
    CsNumberOfProcessors                                    : 1
    CsProcessors                                            : {Intel(R) Xeon(R) CPU E5-2695 v3 @ 2.30GHz}
    CsOEMStringArray                                        : {[MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7],
                                                              Welcome to the Virtual Machine}
    CsPartOfDomain                                          : True
    CsPauseAfterReset                                       : 3932100000
    CsPCSystemType                                          : Desktop
    CsPCSystemTypeEx                                        : Desktop
    CsPowerManagementCapabilities                           :
    CsPowerManagementSupported                              :
    CsPowerOnPasswordStatus                                 : Disabled
    CsPowerState                                            : Unknown
    CsPowerSupplyState                                      : Safe
    CsPrimaryOwnerContact                                   :
    CsPrimaryOwnerName                                      : <censored>
    CsResetCapability                                       : Other
    CsResetCount                                            : -1
    CsResetLimit                                            : -1
    CsRoles                                                 : {LM_Workstation, LM_Server, NT, Server_NT}
    CsStatus                                                : OK
    CsSupportContactDescription                             :
    CsSystemFamily                                          :
    CsSystemSKUNumber                                       :
    CsSystemType                                            : x64-based PC
    CsThermalState                                          : Safe
    CsTotalPhysicalMemory                                   : 8588865536
    CsPhyicallyInstalledMemory                              : 8388608
    CsUserName                                              :
    CsWakeUpType                                            : PowerSwitch
    CsWorkgroup                                             :
    OsName                                                  : Microsoft Windows Server Datacenter
    OsType                                                  : WINNT
    OsOperatingSystemSKU                                    : 145
    OsVersion                                               : 10.0.18363
    OsCSDVersion                                            :
    OsBuildNumber                                           : 18363
    OsHotFixes                                              : {KB4565633, KB4497165, KB4513661, KB4517245...}
    OsBootDevice                                            : \Device\HarddiskVolume2
    OsSystemDevice                                          : \Device\HarddiskVolume4
    OsSystemDirectory                                       : C:\Windows\system32
    OsSystemDrive                                           : C:
    OsWindowsDirectory                                      : C:\Windows
    OsCountryCode                                           : 1
    OsCurrentTimeZone                                       : -360
    OsLocaleID                                              : 0409
    OsLocale                                                : en-US
    OsLocalDateTime                                         : 8/2/2020 1:10:05 PM
    OsLastBootUpTime                                        : 8/2/2020 12:21:44 PM
    OsUptime                                                : 00:48:21.0979102
    OsBuildType                                             : Multiprocessor Free
    OsCodeSet                                               : 1252
    OsDataExecutionPreventionAvailable                      : True
    OsDataExecutionPrevention32BitApplications              : True
    OsDataExecutionPreventionDrivers                        : True
    OsDataExecutionPreventionSupportPolicy                  : OptOut
    OsDebug                                                 : False
    OsDistributed                                           : False
    OsEncryptionLevel                                       : 256
    OsForegroundApplicationBoost                            : Maximum
    OsTotalVisibleMemorySize                                : 8387564
    OsFreePhysicalMemory                                    : 7155532
    OsTotalVirtualMemorySize                                : 9698284
    OsFreeVirtualMemory                                     : 8585276
    OsInUseVirtualMemory                                    : 1113008
    OsTotalSwapSpaceSize                                    :
    OsSizeStoredInPagingFiles                               : 1310720
    OsFreeSpaceInPagingFiles                                : 1310720
    OsPagingFiles                                           : {C:\pagefile.sys}
    OsHardwareAbstractionLayer                              : 10.0.18362.752
    OsInstallDate                                           : 3/15/2020 4:59:56 AM
    OsManufacturer                                          : Microsoft Corporation
    OsMaxNumberOfProcesses                                  : 4294967295
    OsMaxProcessMemorySize                                  : 137438953344
    OsMuiLanguages                                          : {en-US}
    OsNumberOfLicensedUsers                                 : 0
    OsNumberOfProcesses                                     : 76
    OsNumberOfUsers                                         : 5
    OsOrganization                                          :
    OsArchitecture                                          : 64-bit
    OsLanguage                                              : en-US
    OsProductSuites                                         : {TerminalServicesSingleSession}
    OsOtherTypeDescription                                  :
    OsPAEEnabled                                            :
    OsPortableOperatingSystem                               : False
    OsPrimary                                               : True
    OsProductType                                           : Server
    OsRegisteredUser                                        : <censored>
    OsSerialNumber                                          : 00431-40000-00000-AA036
    OsServicePackMajorVersion                               : 0
    OsServicePackMinorVersion                               : 0
    OsStatus                                                : OK
    OsSuites                                                : {TerminalServices, TerminalServicesSingleSession}
    OsServerLevel                                           : ServerCore
    KeyboardLayout                                          : en-US
    TimeZone                                                : (UTC-07:00) Mountain Time (US & Canada)
    LogonServer                                             : <censored>
    PowerPlatformRole                                       : Desktop
    HyperVisorPresent                                       : True
    HyperVRequirementDataExecutionPreventionAvailable       :
    HyperVRequirementSecondLevelAddressTranslation          :
    HyperVRequirementVirtualizationFirmwareEnabled          :
    HyperVRequirementVMMonitorModeExtensions                :
    DeviceGuardSmartStatus                                  : Off
    DeviceGuardRequiredSecurityProperties                   :
    DeviceGuardAvailableSecurityProperties                  :
    DeviceGuardSecurityServicesConfigured                   :
    DeviceGuardSecurityServicesRunning                      :
    DeviceGuardCodeIntegrityPolicyEnforcementStatus         :
    DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus :

**Comment by sanderjo** [comment]
The warning is "OpenSSL 1.0.2 or above and up-to-date local CA certificates are required."
As you have OpenSSL 1.1.1 (so: good) included in the SAB-exe, the problem must be the  local CA certificates, which are part of the OS (Windows), not python nor SAB.

So ... Windows Server Core ... is that a mini-Windows? Do you know how to check the CA certificate store on that Windows?

**Comment by Veduco** [comment]
The same installation works fine on a standard GUI based datacenter install:
    > get-computerinfo
    
    WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
    WindowsCurrentVersion                                   : 6.3
    WindowsEditionId                                        : ServerDatacenter
    WindowsInstallationType                                 : Server
    WindowsInstallDateFromRegistry                          : 11/16/2018 4:05:34 PM
    WindowsProductId                                        : 00430-00000-00000-AA500
    WindowsProductName                                      : Windows Server 2019 Datacenter
    WindowsRegisteredOrganization                           :
    WindowsRegisteredOwner                                  : Windows User
    WindowsSystemRoot                                       : C:\WINDOWS
    WindowsVersion                                          : 1809
    BiosCharacteristics                                     : {4, 7, 9, 11...}
    BiosBIOSVersion                                         : {DELL   - 0}
    BiosBuildNumber                                         :
    BiosCaption                                             : Default System BIOS
    BiosCodeSet                                             :
    BiosCurrentLanguage                                     : en|US|iso8859-1
    BiosDescription                                         : Default System BIOS
    BiosEmbeddedControllerMajorVersion                      : 255
    BiosEmbeddedControllerMinorVersion                      : 255
    BiosFirmwareType                                        : Bios
    BiosIdentificationCode                                  :
    BiosInstallableLanguages                                : 1
    BiosInstallDate                                         :
    BiosLanguageEdition                                     :
    BiosListOfLanguages                                     : {en|US|iso8859-1}
    BiosManufacturer                                        : Dell Inc.
    BiosName                                                : Default System BIOS
    BiosOtherTargetOS                                       :
    BiosPrimaryBIOS                                         : True
    BiosReleaseDate                                         : 10/25/2017 6:00:00 PM
    BiosSeralNumber                                         : <censored>
    BiosSMBIOSBIOSVersion                                   : 2.6.0
    BiosSMBIOSMajorVersion                                  : 2
    BiosSMBIOSMinorVersion                                  : 8
    BiosSMBIOSPresent                                       : True
    BiosSoftwareElementState                                : Running
    BiosStatus                                              : OK
    BiosSystemBiosMajorVersion                              : 2
    BiosSystemBiosMinorVersion                              : 6
    BiosTargetOperatingSystem                               : 0
    BiosVersion                                             : DELL   - 0
    CsAdminPasswordStatus                                   : Unknown
    CsAutomaticManagedPagefile                              : False
    CsAutomaticResetBootOption                              : False
    CsAutomaticResetCapability                              : True
    CsBootOptionOnLimit                                     :
    CsBootOptionOnWatchDog                                  :
    CsBootROMSupported                                      : True
    CsBootStatus                                            : {0, 0, 0, 38...}
    CsBootupState                                           : Normal boot
    CsCaption                                               : <censored>
    CsChassisBootupState                                    : Safe
    CsChassisSKUNumber                                      :
    CsCurrentTimeZone                                       : -360
    CsDaylightInEffect                                      : True
    CsDescription                                           : AT/AT COMPATIBLE
    CsDNSHostName                                           : <censored>
    CsDomain                                                : <censored>
    CsDomainRole                                            : MemberServer
    CsEnableDaylightSavingsTime                             : True
    CsFrontPanelResetStatus                                 : Unknown
    CsHypervisorPresent                                     : True
    CsInfraredSupported                                     : False
    CsInitialLoadInfo                                       :
    CsInstallDate                                           :
    CsKeyboardPasswordStatus                                : Unknown
    CsLastLoadInfo                                          :
    CsManufacturer                                          : Dell Inc.
    CsModel                                                 : PowerEdge R630
    CsName                                                  : <censored>
    CsNetworkAdapters                                       : {vEthernet (External VLAN 30), SLOT # 2 Port 1, SLOT # 2 Port 2, SLOT # Port 1...}
    CsNetworkServerModeEnabled                              : True
    CsNumberOfLogicalProcessors                             : 28
    CsNumberOfProcessors                                    : 1
    CsProcessors                                            : {Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz}
    CsOEMStringArray                                        : {Dell System, 5[0000], 14[1], 17[EBA143AB35E79652]...}
    CsPartOfDomain                                          : True
    CsPauseAfterReset                                       : -1
    CsPCSystemType                                          : EnterpriseServer
    CsPCSystemTypeEx                                        : EnterpriseServer
    CsPowerManagementCapabilities                           :
    CsPowerManagementSupported                              :
    CsPowerOnPasswordStatus                                 : Unknown
    CsPowerState                                            : Unknown
    CsPowerSupplyState                                      : Safe
    CsPrimaryOwnerContact                                   :
    CsPrimaryOwnerName                                      : Windows User
    CsResetCapability                                       : Other
    CsResetCount                                            : -1
    CsResetLimit                                            : -1
    CsRoles                                                 : {LM_Workstation, LM_Server, NT, Server_NT}
    CsStatus                                                : OK
    CsSupportContactDescription                             :
    CsSystemFamily                                          :
    CsSystemSKUNumber                                       : SKU=NotProvided;ModelName=PowerEdge R630
    CsSystemType                                            : x64-based PC
    CsThermalState                                          : Safe
    CsTotalPhysicalMemory                                   : 34261524480
    CsPhyicallyInstalledMemory                              : 33554432
    CsUserName                                              :
    CsWakeUpType                                            : PowerSwitch
    CsWorkgroup                                             :
    OsName                                                  : Microsoft Windows Server 2019 Datacenter
    OsType                                                  : WINNT
    OsOperatingSystemSKU                                    : DatacenterServerEdition
    OsVersion                                               : 10.0.17763
    OsCSDVersion                                            :
    OsBuildNumber                                           : 17763
    OsHotFixes                                              : {KB4565625, KB4465664, KB4470502, KB4470788...}
    OsBootDevice                                            : \Device\HarddiskVolume4
    OsSystemDevice                                          : \Device\HarddiskVolume5
    OsSystemDirectory                                       : C:\WINDOWS\system32
    OsSystemDrive                                           : C:
    OsWindowsDirectory                                      : C:\WINDOWS
    OsCountryCode                                           : 1
    OsCurrentTimeZone                                       : -420
    OsLocaleID                                              : 0409
    OsLocale                                                : en-US
    OsLocalDateTime                                         : 8/2/2020 1:13:52 PM
    OsLastBootUpTime                                        : 3/11/2020 8:00:05 AM
    OsUptime                                                : 144.05:13:47.1423152
    OsBuildType                                             : Multiprocessor Free
    OsCodeSet                                               : 1252
    OsDataExecutionPreventionAvailable                      : True
    OsDataExecutionPrevention32BitApplications              : True
    OsDataExecutionPreventionDrivers                        : True
    OsDataExecutionPreventionSupportPolicy                  : OptOut
    OsDebug                                                 : False
    OsDistributed                                           : False
    OsEncryptionLevel                                       : 256
    OsForegroundApplicationBoost                            : Maximum
    OsTotalVisibleMemorySize                                : 33458520
    OsFreePhysicalMemory                                    : 17858112
    OsTotalVirtualMemorySize                                : 33458520
    OsFreeVirtualMemory                                     : 17602608
    OsInUseVirtualMemory                                    : 15855912
    OsTotalSwapSpaceSize                                    :
    OsSizeStoredInPagingFiles                               : 0
    OsFreeSpaceInPagingFiles                                : 0
    OsPagingFiles                                           : {}
    OsHardwareAbstractionLayer                              : 10.0.17763.1007
    OsInstallDate                                           : 11/16/2018 9:05:34 AM
    OsManufacturer                                          : Microsoft Corporation
    OsMaxNumberOfProcesses                                  : 4294967295
    OsMaxProcessMemorySize                                  : 137438953344
    OsMuiLanguages                                          : {en-US}
    OsNumberOfLicensedUsers                                 :
    OsNumberOfProcesses                                     : 162
    OsNumberOfUsers                                         : 18
    OsOrganization                                          :
    OsArchitecture                                          : 64-bit
    OsLanguage                                              : en-US
    OsProductSuites                                         : {TerminalServices, DatacenterEdition, TerminalServicesSingleSession}
    OsOtherTypeDescription                                  :
    OsPAEEnabled                                            :
    OsPortableOperatingSystem                               : False
    OsPrimary                                               : True
    OsProductType                                           : Server
    OsRegisteredUser                                        : Windows User
    OsSerialNumber                                          : 00430-00000-00000-AA500
    OsServicePackMajorVersion                               : 0
    OsServicePackMinorVersion                               : 0
    OsStatus                                                : OK
    OsSuites                                                : {TerminalServices, DatacenterEdition, TerminalServicesSingleSession}
    OsServerLevel                                           : FullServer
    KeyboardLayout                                          : en-US
    TimeZone                                                : (UTC-07:00) Mountain Time (US & Canada)
    LogonServer                                             : <censored>
    PowerPlatformRole                                       : EnterpriseServer
    HyperVisorPresent                                       : True
    HyperVRequirementDataExecutionPreventionAvailable       :
    HyperVRequirementSecondLevelAddressTranslation          :
    HyperVRequirementVirtualizationFirmwareEnabled          :
    HyperVRequirementVMMonitorModeExtensions                :
    DeviceGuardSmartStatus                                  : Off
    DeviceGuardRequiredSecurityProperties                   : {0}
    DeviceGuardAvailableSecurityProperties                  : {BaseVirtualizationSupport, DMAProtection}
    DeviceGuardSecurityServicesConfigured                   : {0}
    DeviceGuardSecurityServicesRunning                      : {0}
    DeviceGuardCodeIntegrityPolicyEnforcementStatus         :
    DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus :

**Comment by Veduco** [comment]
> The warning is "OpenSSL 1.0.2 or above and up-to-date local CA certificates are required."
> As you have OpenSSL 1.1.1 (so: good) included in the SAB-exe, the problem must be the local CA certificates, which are part of the OS (Windows), not python nor SAB.
> 
> So ... Windows Server Core ... is that a mini-Windows? Do you know how to check the CA certificate store on that Windows?

![image](https://user-images.githubusercontent.com/59983694/89130568-1dafe780-d4c3-11ea-8d7e-fde62b1f5408.png)
This is the list of the trusted root CA certs.

**Comment by Veduco** [comment]
I agree that this seems like certificates.
But, this also did not impact sab v2.3.9 (https://github.com/sabnzbd/sabnzbd/releases/download/2.3.9/SABnzbd-2.3.9-win-setup.exe).

Only upon upgrading to the 3.x branch, beta or stable, am I presented with this error.
It's almost like it refuses to load the CA cert store at all, as SAB also reports my valid Let's Encrypt certificate as invalid.

**Comment by sanderjo** [comment]
Indeed. Maybe python3 (or SAB3) is not seeing / not able to use your certificate root store?

**Comment by Safihre** [comment]
What is shown in the logs for the lines containing:
```
Loaded additional certificates from
Available certificates:
```

**Comment by Veduco** [comment]
2020-08-02 12:23:07,753::INFO::[SABnzbd:1176] Loaded additional certificates from C:\SABnzbd-3.0.0\cacert.pem
    2020-08-02 12:23:07,769::DEBUG::[SABnzbd:1182] Available certificates: {'x509': 19, 'crl': 0, 'x509_ca': 15}

**Comment by Veduco** [comment]
`C:\SABnzbd-3.0.0\cacert.pem` does not exist in my instance.

**Comment by Safihre** [comment]
Oh no... Something went wrong with the packaging and the `cacert.pem` file is missing 😢

**Comment by Safihre** [comment]
Oke, I fixed it.
Will release a 3.0.1 in a few days, just in case more stuff comes in.

Thanks a lot for reporting!

**Comment by Veduco** [comment]
Thank you for working with me on fixing this issue. It's much appreciated.

**Comment by Safihre** [comment]
@Veduco You can download an updated build here: https://github.com/sabnzbd/sabbuild/releases/tag/3.0.1-test1
Could you confirm if this build fixes your issue?

**Comment by Veduco** [comment]
> @Veduco You can download an updated build here: https://github.com/sabnzbd/sabbuild/releases/tag/3.0.1-test1
> Could you confirm if this build fixes your issue?

Confirming, this build fixes the issue I saw.

Thank you.

**Comment by Safihre** [comment]
Great. Leaving this open in case other people report it, for reference.
Will close after releasing 3.0.1.

**Comment by sanderjo** [comment]
But ... do we (want to) know why SAB/python cannot access the Windows Server Core's CA root certificate?
AFAIK the manual cacert.pem is a workaround?

**Comment by Veduco** [comment]
> But ... do we (want to) know why SAB/python cannot access the Windows Server Core's CA root certificate?
> AFAIK the manual cacert.pem is a workaround?

Likely, the number of certs shipped with Server Core is reduced, but I was able to show a load of 15 CA certs. So they're there, just not entirely what is needed.

Since this file was included in 2.3.9, I did not see this issue there.

https://github.com/sabnzbd/sabnzbd/issues/1564#issuecomment-667715724

**Comment by Safihre** [comment]
How many are in your root store? Mine contains 76.

**Comment by Veduco** [comment]
> How many are in your Root Certificate store? Mine contains 76.
> In the Third-Party Root Certificate store there are another 57.

You're using Windows Server Core?
What policies do you have in place to distribute certificates?


I have 16, including my personal Root CA, in the "Trusted Root CAs".
I have 3 under the "Third Party Root CAs".

Checked on two machines, they both match. One was deployed yesterday, the other, months ago.

**Comment by Veduco** [comment]
Trusted Root CA:
![image](https://user-images.githubusercontent.com/59983694/89187588-bcd3ee00-d55a-11ea-97ac-1c11b9b89006.png)

Trusted Third Party CA:
![image](https://user-images.githubusercontent.com/59983694/89187668-d412db80-d55a-11ea-80fa-b9d88c3102a4.png)

**Comment by sanderjo** [comment]
> I have 16, including my personal Root CA, in the "Trusted Root CAs".
> I have 3 under the "Third Party Root CAs".

Ah. That is low! 
New hypothesis: python3/sab3 does have access to the Trusted Root CA, ... but there are certificates mssing. And SAB tests agains a https, which uses a certificate not in your store, leading to the warning.

So @Veduco : can you check how to get your Trusted Root CA filled / uptodate?

**Comment by Safihre** [comment]
@sanderjo We already know SAB does have access, because the logging shows:
```
2020-08-02 12:23:07,769::DEBUG::[SABnzbd:1182] Available certificates: {'x509': 19, 'crl': 0, 'x509_ca': 15}
```
It would show 0 if it could not access anything.

**Comment by sanderjo** [comment]
Oh, yes: on my Windows 10 laptop:

`2020-08-03 15:43:16,821::DEBUG::[SABnzbd:1182] Available certificates: {'x509': 84, 'crl': 0, 'x509_ca': 82}`

On my Ubuntu:


```
sander@brixit:~$ cat .sabnzbd/logs/sabnzbd.log* | grep x509 | sort
2020-07-14 15:11:13,667::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-07-14 15:12:42,184::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-07-20 20:12:51,374::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-08-02 09:38:29,273::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-08-02 19:55:52,599::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-08-02 19:57:38,233::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-08-02 19:59:40,388::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
2020-08-02 20:02:15,294::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
```

Weird.

**Comment by Veduco** [comment]
> > I have 16, including my personal Root CA, in the "Trusted Root CAs".
> > I have 3 under the "Third Party Root CAs".
> 
> Ah. That is low!
> New hypothesis: python3/sab3 does have access to the Trusted Root CA, ... but there are certificates mssing. And SAB tests agains a https, which uses a certificate not in your store, leading to the warning.
> 
> So @Veduco : can you check how to get your Trusted Root CA filled / uptodate?
> 
> Maybe this helps: http://woshub.com/updating-trusted-root-certificates-in-windows-10/

I could publish a group policy to distribute certs and make my Server Cores look more like a standard windows install with 80+ trusted CAs.
But really, that's a lot of effort for me to fix something that's "broken" in the loosest sense of the word, as the workaround, the cacert.pem, has been working completely fine for ages, and is resolved once again in future versions of SAB.

**Comment by Veduco** [comment]
> Oh, yes: on my Windows 10 laptop:
> 
> `2020-08-03 15:43:16,821::DEBUG::[SABnzbd:1182] Available certificates: {'x509': 84, 'crl': 0, 'x509_ca': 82}`
> 
> On my Ubuntu:
> 
> ```
> sander@brixit:~$ cat .sabnzbd/logs/sabnzbd.log* | grep x509 | sort
> 2020-07-14 15:11:13,667::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-07-14 15:12:42,184::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-07-20 20:12:51,374::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-08-02 09:38:29,273::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-08-02 19:55:52,599::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-08-02 19:57:38,233::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-08-02 19:59:40,388::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> 2020-08-02 20:02:15,294::DEBUG::[sabnzbdplus:1182] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}
> ```
> 
> Weird. Windows-only feature?

On your Ubuntu box, are you able to successfully perform server verification in the server config/settings area?
It returns success?

**Comment by sanderjo** [comment]
> On your Ubuntu box, are you able to successfully perform server verification in the server config/settings area?
> It returns success?

Yes. Ignore the Ubuntu stuff ... that is meant for @Safihre

**Comment by Safihre** [comment]
@sanderjo On Windows the certificates get loaded right away: https://github.com/python/cpython/blob/master/Lib/ssl.py#L569-L575
While on other systems this is just passed directly to OpenSSL and seems to only be loaded when connections are made: https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html
