### ISSUE TITLE
Missing module: cgi

### ISSUE THREAD

**Issue by neofright** [sabnzbd/sabnzbd#1565]
```
Aug 03 09:45:15 FOOBAR python3[3207484]: Not all required Python modules are available, please check requirements.txt
Aug 03 09:45:15 FOOBAR python3[3207484]: Missing module: cgi
Aug 03 09:45:15 FOOBAR python3[3207484]: You can read more at: https://sabnzbd.org/python3
Aug 03 09:45:15 FOOBAR python3[3207484]: If you still experience problems, remove all .pyc files in this folder and subfolders
```

I have done `find sabnzbd/ -iname "*.pyc" -delete` etc.

I'm fairly sure I have followed all steps as described on the wiki.

What's weird about this error is that it complains cgi is a missing module, yet when reading [SABnzbd.py](https://github.com/sabnzbd/sabnzbd/blob/c4aad2a4bd03c215e05eab27d1835cb6c4291147/SABnzbd.py) I can't see where it attempts to `import cgi`.

This is an in place upgrade of sabnzbd 2.3.9 - so it's possible I've screwed something up when copying over the top of the old directory.

When I have some more free time I'll test a fresh install and respond or close this issue!

Edit: Running Fedora release 32 (Thirty Two) with Python 3.8.5

**Comment by sanderjo** [comment]
The message is from https://github.com/sabnzbd/sabnzbd/blob/c4aad2a4bd03c215e05eab27d1835cb6c4291147/SABnzbd.py#L37-L56 ... so maybe/probably one of the other modules does an import cgi.

**Comment by Safihre** [comment]
This is very strange, since `cgi` is a module that is part of base-Python:
https://docs.python.org/3.8/library/cgi.html

It seems maybe some module tries to import `cgi.escape()`, since this is all I can find when looking online for this problem: https://www.google.com/search?q=python+cannot+import+cgi

But I am also running Python 3.8.3 and I do not get any problems..
We will have to debug where this is coming from. Could you remove this whole section from `SABnzbd.py` and then start it again? The full stack-trace should show what is missing.
```python
except ImportError as e: 
     print("Not all required Python modules are available, please check requirements.txt") 
     print("Missing module:", e.name) 
     print("You can read more at: https://sabnzbd.org/python3") 
     print("If you still experience problems, remove all .pyc files in this folder and subfolders") 
     sys.exit(1) 
```

**Comment by neofright** [comment]
Thanks sanderjo and Safihre for chiming in here.

Every time a new major release comes out I usually manage to produce some strange behaviour when upgrading!

I had a spare 10 mins and I did a clean install - without trying to preserve any existing config from 2.x - this worked absolutely fine!

I can only assume there was some inconsistency in untarring the new release on top of the old one.

Once the fresh install was confirmed working, I did:
```
$ sudo systemctl stop sabnzbd
$ sudo rm -rf sabnzbd/admin/
$ sudo cp -r sabnzbd.bak/admin sabnzbd/
$ sudo cp sabnzbd.bak/sabnzbd_config.ini sabnzbd/
$ sudo systemctl start sabnzbd
```

Everything is working as expected. I'm going to close this issue as I don't think think I will be likely to get to the bottom of whatever I screwed up!

I did also test earlier without issue:
```[foo@BAR ~]$ python3
Python 3.8.5 (default, Jul 20 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
>>> exit()
```
Very glad to see in the changelog:

> Fully obfuscated RAR-sets with no verification files are detected and extracted.

Keep up the good work!

**Comment by sanderjo** [comment]
Good to hear it works now

> Very glad to see in the changelog:
> 
> > Fully obfuscated RAR-sets with no verification files are detected and extracted.
> 
> Keep up the good work!

Yes, that's a great feature. And the logic & the code is a piece of magic, if I may say so. ;-)
