### ISSUE TITLE
ignore samples - 'bug'

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#157]
added nzb to sab.. with ignore samples set to 'do not download' (shared for research)
http://nzbcache.info/nzb/43e511966388af640c7343f43a07fca6e26bafe1.nzb.gz

resulted in two entries.. one for 736 B and one for 246 KB
set ignore samples to 'off' and then it loads up one item, a 1.7gb download.. obviously its because the nzb poster accidentally used -sample in the naming :(

so.. issue.. why did it end up turning it into two queue entries?

which brought up an interesting thing.. maybe we could set the ignore samples to have a safe guard? if its going to discard more than 98%? of the nzb.. just bypass the discard since its prob due to bad name? thus I now have to turn off the ignore samples to ensure that I actually get the nzb data... ill waste some of the bandwidth/time happily to not have to deal with issue.

i did **not** test what happens if you use the delete after download option

**Comment by shypike** [comment]
Removed the "do not download" option in 0.8.0
