### ISSUE TITLE
sabnzb on Qnap fails with python 3 error even with python3.5 installed.

### ISSUE THREAD

**Issue by BVapid** [sabnzbd/sabnzbd#1578]
Hi guys,

My existing sabnzbd install has stopped working. Now when I start it, it says it requires python3, even with it installed.

= (SABnzbdplus) is not active
* updating (SABnzbdplus): OK
* updating language support (SABnzbdplus): Traceback (most recent call last):
  File "tools/make_mo.py", line 295, in <module>
    make_templates()
  File "tools/make_mo.py", line 217, in make_templates
    translate_tmpl("email", lng)
  File "tools/make_mo.py", line 193, in translate_tmpl
    with open(EMAIL_DIR + "/%s-en.tmpl" % prefix, "r", encoding="utf-8") as src:
TypeError: 'encoding' is an invalid keyword argument for this function
failed!
result=[1]
Email MO files
Compile locale/da/LC_MESSAGES/SABemail.mo
Compile locale/de/LC_MESSAGES/SABemail.mo
Compile locale/en/LC_MESSAGES/SABemail.mo
Compile locale/es/LC_MESSAGES/SABemail.mo
Compile locale/fi/LC_MESSAGES/SABemail.mo
Compile locale/fr/LC_MESSAGES/SABemail.mo
Compile locale/he/LC_MESSAGES/SABemail.mo
Compile locale/nb/LC_MESSAGES/SABemail.mo
Compile locale/nl/LC_MESSAGES/SABemail.mo
Compile locale/pl/LC_MESSAGES/SABemail.mo
Compile locale/pt_BR/LC_MESSAGES/SABemail.mo
Compile locale/ro/LC_MESSAGES/SABemail.mo
Compile locale/ru/LC_MESSAGES/SABemail.mo
Compile locale/sr/LC_MESSAGES/SABemail.mo
Compile locale/sv/LC_MESSAGES/SABemail.mo
Compile locale/zh_CN/LC_MESSAGES/SABemail.mo
Create email templates from MO files
Create email template for da
* updating (nzbToMedia): OK
* starting (SABnzbdplus): failed!
result=[1]
Sorry, requires Python 3.5 or above
You can read more at: https://sabnzbd.org/python3

python3 -v
Python 3.5.2 (default, Aug 10 2016, 18:01:45) 
[GCC 4.9.2] on linux

Any ideas? Thankyou!

**Comment by sanderjo** [comment]
what is the first line of SABnzbd.py ?

what is the output of

`python3 -c "import sys; print(hex(sys.hexversion)) "`

**Comment by Safihre** [comment]
Are you using the Sherpa script by @OneCDOnly?

**Comment by OneCDOnly** [comment]
Hi @BVapid you'll need to install the new SABnzbd package via sherpa. 

Please follow the steps shown below.

Stop your old SAB:
```
[[ -e /etc/init.d/sabnzbd2.sh ]] && /etc/init.d/sabnzbd2.sh stop || /etc/init.d/sabnzbd.sh stop
```
Backup your old settings:
```
mkdir -p $(getcfg SHARE_DEF defVolMP -f /etc/config/def_share.info)/.qpkg_config_backup
/bin/tar --create --gzip --file=$(getcfg SHARE_DEF defVolMP -f /etc/config/def_share.info)/.qpkg_config_backup/SABnzbd.config.tar.gz --directory=$(getcfg SABnzbdplus Install_Path -f /etc/config/qpkg.conf)/config .
```

Download the latest sherpa, and install SAB3:
```
cd /share/Public && curl -skLO https://git.io/sherpa.sh && chmod +x sherpa.sh && ./sherpa.sh sab
```
Then restore your old settings into the new package:
```
/etc/init.d/sabnzbd3.sh restore
```

**Comment by thezoggy** [comment]
> starting (SABnzbdplus): failed!

whats the command it is running?

**Comment by BVapid** [comment]
@OneCDOnly thankyou so much! That worked a treat. I'm on an old Atom powered Qnap too so was starting to lose hope that nothing was supported anymore. 

> /etc/init.d/sabnzbd3.sh restore

This didn't work, but a normal sabnzbd3.sh start brought it back thankfully.

Huge thanks for your work.
