### ISSUE TITLE
Some files failed to verify against a sfv

### ISSUE THREAD

**Issue by jomeister-spec** [sabnzbd/sabnzbd#1580]
When I run out of diskspace on my target drive (not temp) I get a bunch of stuff under failed. When I hit retry I get this error.
When I press retry again it redownloads everything. Even though the content in the directory is fine. And I end up with duplicate directories (one named .1) and inside the .1 duplicate files on everything.

This is new in 3.0.0. When I had this issue in previous versions, the retry just moved the folder.

**Comment by Safihre** [comment]
Could you share a sample NZB? Lots of stuff changed in 3.0.0 regarding repairs, so have to see what's the problem.

**Comment by jomeister-spec** [comment]
I think the nzb is gone. But in my temporary directory I have a folder. there is a par2. file and a ADMIN dir. 
Quickpar says repair not needed. The built in sfv checker in total commander says ok on all files.
But 3.0.0 is maybe checking my target dir? It has the directory and 2 incomplete files. 

And this only happens when my target directory runs out of diskspace. It creates the directory on target dir, tries to move files but fails.

**Comment by Safihre** [comment]
I think this happens because some stuff was already unpacked, so the files it tries to verify are no longer there. It should skip the verification if it succeeded previously.
The extensive sfv check is new in 3.0.0.

**Comment by jomeister-spec** [comment]
I'm looking at one directory here and target dir has one file, a jpg 0 size. all the files are still at the temp dir.

**Comment by jomeister-spec** [comment]
I deleted the target directory, same error

**Comment by thezoggy** [comment]
please share logs (debug level) , crystal ball only works so well

**Comment by jomeister-spec** [comment]
https://pastebin.com/u13VW7Nw

**Comment by Safihre** [comment]
I think I know how to fix it! Indeed it should skip the checks. 
Could you maybe share the NZB? I am actually surprised the sfv-check fails, so that's a different problem I want to investigate.

**Comment by Safihre** [comment]
I changed to code to skip verification if previously all sets verified successfully.
Will be part of 3.1.x, since it's a bit bigger change.
