### ISSUE TITLE
Pause download when out of diskspace on target folder?

### ISSUE THREAD

**Issue by jomeister-spec** [sabnzbd/sabnzbd#1581]
It pauses when you run out of diskspace on the temporary folder, but not the target folder.
Possible to fix?

**Comment by Safihre** [comment]
I would like this feature. Complication is that each job could be going to a different drive when people have specified different folders based on Categories.
So if category 1's drive is full, do we pause the whole queue? I guess we would.

**Comment by thezoggy** [comment]
i would say only pause the job assigned for that cat and not the whole queue by default. but then offer up an option to pause whole queue if any cat has a problem

**Comment by Cpuroast** [comment]
I'd say pause the whole queue, simpler to implement and call it a day. The vast majority of people don't have different volumes for each category. But I would say a large portion of people do have a separate volume for temporary and completed either as default or defined via a category.

**Comment by thezoggy** [comment]
i used to put movies to my slow hdd and keep everything local to the ssd due to size constraints, which i could see others doing. but in this day in age, people could also just buy bigger drives? :)

**Comment by Safihre** [comment]
So when exactly should it pause the downloading? When the items in the queue exceed the available space on the complete folder?
Or when the complete folder reaches 0 (or the already available option of Minimal Available Space)?

**Comment by thezoggy** [comment]
I would think you'd want to use min available space setting to be consistent. And have it do the check early enough to avoid costly deletions/backlog queueing

**Comment by Cpuroast** [comment]
Identical to the current mininmum space option for Temporary.

Minimum Free Space for Temporary Download Folder
Minimum Free Space for Completed Download Folder

To simplify things, you could even unify both, and have min space auto-pause affect Temporary and Completed.
There's really no point in having the download queue active if any of the volumes used for temporary or completed jobs have their free space fall too low.

**Comment by Safihre** [comment]
Thinking about this, I wondered if stead of having this check in the assembler before we start writing to the disk, we should have this check seperately in the checks we run every 3/9/30 seconds.
Doing that would also make it possible to add "Automatic resume", an often requested feature. But say we only check every 9 seconds, it could be a bit behind. 
What do you think?

**Comment by thezoggy** [comment]
Checking during the process is good, if you just had a background task I could see that unwanted disk io keep disks from spinning down?

**Comment by Safihre** [comment]
Closed by @puzzledsab in #1724
