### ISSUE TITLE
Sab no longer sorts

### ISSUE THREAD

**Issue by Superfishintights** [sabnzbd/sabnzbd#1583]
Version 3.0.1 [9a4be70] / Linux

When using the sort feature or sort API, it shows the 'sorting' dialog box like normal/returns 'True' - but the actual queue doesn't change.  This is the case for all sorting options.

This has only started happening recently, looks like since the 3.0.1 upgrade this is happening.

from the log file - 
`2020-08-22 15:06:35,254::INFO::[nzbqueue:576] Sorting by size... (reversed: False)`

**Comment by Superfishintights** [comment]
Hi Safihre, 

I'm now on 3.0.2/51cc765 and the issue still remains.  Am I still on an older version or something?  My Sab container is updated via watchtower.

**Comment by Safihre** [comment]
Jobs that were already added to the queue still have a "bad" priority due to the error in the code.
You can fix this by using Multi-edit in the front-end, select all the jobs, switch them to a new priority, and then switch them back.

**Comment by Superfishintights** [comment]
Cheers, yeah that would explain it - we only spotted it by chance of having 60 pages of downloads and me setting the big ones to low priority and paused.

thanks, we can work around this now!
