### ISSUE TITLE
Addfile api call fails in sabnzbd 3.0.1

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1584]
We get  an error 'expects one parameter' when executing an addfile POST request.
What is wrong with this api call ?

[sabnzbd log]
`2020-08-23 18:08:13,729::DEBUG::[api:121] API-call from 127.0.0.1 [??] {'mode': 'addfile', 'name': 'Airborne 44 - Compleet.752411.nzb', 'nzbname': 'Airborne 44 - Compleet', 'apikey': '7416cc21cd0293c07222abaf64da0105', 'nzbfile': <cherrypy._cpreqbody.Part object at 0x00000000066EF880>}`

Url used : 
`
http://127.0.0.1:8080/sabnzbd/api?mode=addfile&name=Airborne+44+-+Compleet.895346.nzb&nzbname=Airborne+44+-+Compleet&apikey=7416cc21cd0293c07222abaf64da0105`

The NZB is in the POST body

**Comment by thezoggy** [comment]
Wonder if it's the . In the name.

**Comment by Safihre** [comment]
No, the problem is that it first searches for the NZB-contents in the `name` property. Since that one is filled with text, it doesn't check the `nzbfile` property.
This seems to be a regression.
