### ISSUE TITLE
Strange / unexpected output from fullstatus api call sabnzbd 3.0.1

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1585]
Url used : 
`http://vmvs2010:8080/sabnzbd/api?apikey=7416cc21cd0293c07222abaf64da0105&mode=fullstatus&skip_dashboard=0&o=xml`

Output : 

`{'T': <function Ttemplate at 0x0000000004993A60>, 'Tspec': <function Tspec at 0x00000000049939D0>, 'uptime': '16m', 'color_scheme': 'gold', 'helpuri': 'https://sabnzbd.org/wiki/', 'restart_req': False, 'pid': 4768, 'active_lang': 'nl', 'my_lcldata': 'C:\\Users\\Jan\\AppData\\Local\\sabnzbd', 'my_home': 'C:\\Users\\Jan', 'webdir': '\\\\?\\C:\\Program Files\\SABnzbd\\interfaces\\Plush\\templates', 'url_base': '/sabnzbd', 'nt': True, 'darwin': False, 'power_options': True, 'pp_pause_event': False, 'apikey': '7416cc21cd0293c07222abaf64da0105', 'new_release': None, 'new_rel_url': None, 'version': '3.0.1', 'paused': False, 'pause_int': '0', 'paused_all': False, 'diskspace1': '45.34', 'diskspace2': '45.34', 'diskspace1_norm': '45.3 G', 'diskspace2_norm': '45.3 G', 'diskspacetotal1': '139.90', 'diskspacetotal2': '139.90', 'loadavg': '', 'speedlimit': '100', 'speedlimit_abs': '', 'have_warnings': '1', 'finishaction': None, 'quota': '0 ', 'have_quota': False, 'left_quota': '0 ', 'cache_art': '0', 'cache_size': '0 B', 'cache_max': '536766054', 'logfile': '\\\\?\\C:\\Users\\Jan\\AppData\\Local\\sabnzbd\\logs\\sabnzbd.log', 'weblogfile': None, 'loglevel': '2', 'folders': ['Airborne 44 - Compleet', 'Airborne 44 - Compleet.1'], 'configfn': '\\\\?\\C:\\Users\\Jan\\AppData\\Local\\sabnzbd\\sabnzbd.ini', 'cpumodel': 'Intel(R) Core(TM)2 Quad CPU Q6700 @ 2.66GHz', 'pystone': 0, 'downloaddir': 'C:\\Users\\Jan\\Downloads\\incomplete', 'downloaddirspeed': 0, 'completedir': 'C:\\Users\\Jan\\Downloads\\complete', 'completedirspeed': 0, 'internetbandwidth': 0, 'localipv4': '192.168.2.187', 'publicipv4': '??????????????', 'ipv6': None, 'dnslookup': 'OK', 'servers': [('news.supernews.com', '', 0, [], 0, True, '', 0, 0)], 'warnings': [{'type': 'WARNING', 'text': "API-sleutel incorrect; vul de API-sleutel van 'Configuratie' => 'Algemeen' in bij het externe programma: 127.0.0.1>Spotnet 1.9.6.0", 'time': 1598267296}]}
`
Expected some valid XML ?

**Comment by Safihre** [comment]
There's no `o=xml`, it should be [`output=xml`](https://sabnzbd.org/wiki/advanced/api).

**Comment by mesa57** [comment]
Thanks. Thought that o= was an abreviation of output=

**Comment by Safihre** [comment]
We indeed support that for command-line parameters, but not for the API :)
