### ISSUE TITLE
Unrar with relative folders --> error message \\?

### ISSUE THREAD

**Issue by DerzeitloseWolf** [sabnzbd/sabnzbd#1588]
Hey guys,

after having upgraded to version 3.0.1 (64) on Windows I am not able to extract file within a category using a relative folder.

Example:
```
Name Test
Fertiggestelltvor 6 Minuten
StatusFehlgeschlagen
Grösse0 B
Kategorie test
Pfad D:\ServerFolders\Download\SABNZBD\complete\tmp\
Reparieren[Test] Keine PAR2-Sätze
[b5e53c3e25be487cb46ada76892c2f11.part001] RAR-basierte Überprüfung versuchen
[b5e53c3e25be487cb46ada76892c2f11.part001] RAR-Datei erfolgreich überprüft
Entpacken[b5e53c3e25be487cb46ada76892c2f11] Entpacken fehlgeschlagen. Fehler beim Schreiben oder volle Festplatte?: \\?\D:\ServerFolders\Download\SABNZBD\complete\tmp\\b5e53c3e25be487cb46ada76892c2f11.mp4
```
When I change the category to create a subfolder the file is correctly extracted. The issue is with every file using the category.

I guess the issue is the double backslash, but when I manully execute the rar command
```
unrar e test.rar D:\ServerFolders\Download\SABNZBD\complete\tmp\\
```
everything is working fine.

Please let me know if you need some more information.

**Comment by Safihre** [comment]
What is the relative path you have set for the category?

**Comment by DerzeitloseWolf** [comment]
tmp\*

Attached some screenshots
Base:
![base](https://user-images.githubusercontent.com/43076770/91459676-307dc800-e887-11ea-902f-786db10016d6.PNG)

Not working (but working in version 2):
![not working](https://user-images.githubusercontent.com/43076770/91459679-31165e80-e887-11ea-9992-fe5373f48d44.PNG)

Working
![Working](https://user-images.githubusercontent.com/43076770/91459681-31aef500-e887-11ea-9626-14d9bd63571d.PNG)

**Comment by thezoggy** [comment]
\* definitely doesn't look valid. We prob stripped * and that's where the extra slash came from

**Comment by DerzeitloseWolf** [comment]
Hm, then I don't understand the docu ;)

The Folder or full path for final storage (relative folders are based of your complete folder, full paths are also allowed).
Ending the path with an asterisk * will prevent creation of job folders.

I have now found out that using the full path is working fine, so the following extracts the file without creating a new folder:
D:\ServerFolders\Download\SABNZBD\complete\tmp\*

Must be entered manually, because otherwise the relative path is used.

So the issue seems to be the combination of relative path + * for not creating a folder

**Comment by Safihre** [comment]
Indeed I do want the `folder\*` notation to work.
Will investigate.

**Comment by Safihre** [comment]
The problem is that we now use long-path everywhere on Windows, but this changes the behavior of `os.path.abspath`:
```python
os.path.abspath("C:\\Test\\")
'C:\\Test'
os.path.abspath("\\\\?\\C:\\Test\\")
'\\\\?\\C:\\Test\\'
```
