### ISSUE TITLE
3.x regression: .nzb opens (via windows explorer association) when sabnzbd is already running, are not added to the queue

### ISSUE THREAD

**Issue by bughit** [sabnzbd/sabnzbd#1590]
- win7  sp1 x64, sabnzbd 3.0.2
- opening an .nzb file (either from a browser or explorer), before sanzbd is running, starts it and adds to the queue
- subsequent .nzb opens do not
- procmon shows the expected "process create" operations by explorer.exe with the command `"C:\Program Files\SABnzbd\SABnzbd.exe" "c:\path\to.nzb"`, but the running sabnzbd ignores these invocations
- 2.3.9 is fine

**Comment by Safihre** [comment]
I cannot reproduce this on Windows 10 (as you know Windows 7 isn't officially supported anymore), it adds the NZB's nicely.
How do you run SABnzbd: what port do you use? What host have you set in Config > General? Do you use HTTP**S**?

**Comment by bughit** [comment]
> as you know Windows 7 isn't officially supported anymore

According to the release notes sabnzbd did not drop win7. If you mean Microsoft does not support win7, that's both false (ESU) and irrelevant. Each project is free to make its own decisions about how long to support older oses.

I narrowed it down to url_base pref value of "/". This worked in 2.3.9 and results in this issue in 3.x. A blank value works, but "/" should as well.

**Comment by Safihre** [comment]
Looking at the code, `url_base` indeed cannot end in a `/` because the way it is used in several places to construct other URL's.
The code for this wasn't really changed between 2.3.9 and 3.x, so I think it might be a change in one of the dependencies, like CherryPy.
Might just have to add a note in the documentation about this instead of putting extra code to handle the edge case that the `url_base` ends in `/`.

**Comment by bughit** [comment]
> Might just have to add a note in the documentation

"/" means root so it's the most natural value to pick if you want it opening at root. You shouldn't allow a trailing slash on a base path to break the app. You should reject it at least, or ideally handle it.
