### ISSUE TITLE
sabnzbd 3.0.1 Interface issues

### ISSUE THREAD

**Issue by whemever** [sabnzbd/sabnzbd#1591]
I'm running SABNZBD and have been doing so for about a year, in the last few days it underwent an update to v3.0.1. I'm using it on a DS3617xs running DSM 6.2.3-25426 update 2 with 32Gb of memory.

The interface is, IMHO, a major step backwards, it does not scale with screen size (nor does there seem to be any way to change the font size) moving items on the download list is extremely haphazard as the grab area is minute, possibly due to the fact I'm running it on a screen that is 2560 x 1440. deleting an entry means ticking a box then going and clicking on an x that looks more like it should close down the menu, then being told it is deleing n nzb's - but not which ones. Also the nice layout option of being able to split active and finished downloads to separate screens has gone.

So please bring back some of the better aspects of the original interface - the ability to react to screen size and change font size, the ability to easily move items in a queue ( half of it does seem present, its just used to move specific download threads instead of whole nzb's. I would love the ability to split the screen back for active and finished downloads. Finally please address the deletion aspect, the current implementation is not just ugly but time consuming, as if you have 2 or more nzb's being deleted and you expected less, you have to go through each screen of downloads looking for a place where you may have accidently clicked on a box when trying to move something, or some other cause. The delete bin on each item was far easier to understand and made much more sense

**Comment by Safihre** [comment]
What interface exactly are you using?

**Comment by whemever** [comment]
Hi Safihre - Thanks for that - that was the interface I had turned on previously, and for some reason installing 3.0.1 managed to bin it and turn plush on! - I've been checking everything else and it all seems to be right, just for whatever reason the interface was switched and I managed totally to miss it.  I suppose thats the thing with so much to check, the simple options just pass you bye.  As a suggestion could you not set glitter as the default for the synology version as it is much more suited to that use.

**Comment by thezoggy** [comment]
Glitter is the default and has been for a few years

**Comment by whemever** [comment]
Very weird, for some reason after installing the 3.0.1 update I got switched into ‘Plush’! I’ve checked all the other settings in light of this and can’t find any thing else that’s changed, so I’m putting it down to a ‘funny’

Thanks for your help. I completely missed the fact it had changed the interface in the settings and thought that as part of the 3.0.1 I got a new interface, hence the report. I’m glad that it was nothing of the sort and am sorry for having wasted your time; as you look after this beast on synology, it must almost be a full time job in and of itself, especially with idiots like me using up your time

**Comment by Safihre** [comment]
No worries 👍 
Will double check that it automatically reverses to Glitter if something is wrong.

**Comment by whemever** [comment]
Hi Safihre,

 

I know that you posted that you were waiting for the synocommunity team to upload the latest update to their server, however I was wondering if you were following the beta updates and had a version of the 3.1.0 beta available for synology that you would allow me to run as a beta. I know that again the Synocommunity team are resistant to allowing beta’s onto the system, hence the reason I had to download the v3.0.3.913 beta of Sonarr directly from source.  I want this latest version as I am starting to see more and more of the obsfuracated filenames in my downloads that Sonarr/Radarr are pulling.

 

I hope that you are able to help

 

Thanks

 

Simon
