### ISSUE TITLE
SABZBD Update

### ISSUE THREAD

**Issue by whemever** [sabnzbd/sabnzbd#1592]
I'm running SABNZBD and have been doing so for about a year, in the last few days it underwent an update to v3.0.1. I'm using it on a DS3617xs running DSM 6.2.3-25426 update 2 with 32Gb of memory.

With the new implementation of SABNZBD, I am getting a 'Update Available!' message in the top left hand corner of the screen, clicking on it takes me to a page to download the update, unfortunately this update is not available on Synology! I was wondering if like Sonarr (v3), updates would be done automatically (or with an option to enable this to happen) as it stands the current message is misleading there is an update, however it is not on Synology - better to either supress the message until the (appropriate hardware (Synology) version is available or totally delete it relying on the Synology package center to keep on top of the updates - whilst this isn't the case for windows it may be relevant for other devices.

I understand requesting that getting SABNZBD to be device agnostic and able to self update is a huge issue/request, however SONARR is doing so already so there must be a potential for it to do so and as SONARR and SABNZBD work together in a vast number of cases, there may be the possibility for some read-across/support

**Comment by jeffgeorge** [comment]
Comparing to Sonarr isn't valid as Sonarr / SABnzbd are completely dissimilar language / distribution methods.

One option you may consider is installing SABnzbd via docker rather than a native Synology package, then set it to auto-update. Docker images from linuxserver.io get updated *very* quickly when new releases ship.

**Comment by Safihre** [comment]
@jeffgeorge I am the maintainer of the SynoCommunity package and it is updated with every release right away.
Just waiting for them to push it to their servers: https://github.com/SynoCommunity/spksrc/pull/4154
