### ISSUE TITLE
clean install, missing modulues ubuntu 18

### ISSUE THREAD

**Issue by sufr3ak** [sabnzbd/sabnzbd#1594]
I followed the guide here, did an upgrade. Due to a series of unfortunate steps, I removed all of Sab, and all Python3. 

I followed the guide: https://sabnzbd.org/wiki/installation/install-ubuntu-repo

python3.6 was installed with the installation.  But then it errored and said  

> Not all required Python modules are available, please check requirements.txt
> Missing module: jaraco.collections

I had to roll everything back to the old version for now. It seems there is a missing step with some python modules.

**Comment by sanderjo** [comment]
You're double-posting, right? I'll your other post

Which OS? Ubuntu? 

Did you see https://github.com/sabnzbd/sabnzbd/issues/1522

**Comment by Safihre** [comment]
Or #1546

**Comment by sufr3ak** [comment]
I didn't realize if I did double post. My bad

Originally I did an ugprade, and all was fine. I had to remove everything and start clean, so I followed these instructions: (I did not have Python3.x installed, so it came down with the install.

https://sabnzbd.org/wiki/installation/install-ubuntu-repo

If there is a bug with Ubuntu and clean installs, it should be noted on that install page.  In a little bit, I'll try the upgrade again and confirm that easy method works.

**Comment by sanderjo** [comment]
So:
- clean install of Ubuntu 18.04
- you did not anything with pip
- you did install python 3.6 and then python 3.7
Correct?

**Comment by sufr3ak** [comment]
Sorry, I wasn't clear.
I purged sab with apt purge, I purged python 3*. (all versions). Autoclean/autoremove to ensure everything was gone.  I removed the repositories. So there was no sab or python3 on my system. Still using Python2.

I then re-added the repositories, and followed only those instructions. I did not install python 3 independently, it came with the PPA pulldown of SAB3.

Currently, I'm rolling sab2, gonna attempt the upgrade today.

**Comment by sanderjo** [comment]
back to the basics:

Clean, standard Ubuntu 18.04 (and 20.04) with JCFP's PPA will give you a working sabnzbd3 (including python3). Automagically.

My experience: you can get the jaraco problems as soon as you start with pip on top of the above. No need to do that, so easy to avoid. Do not use pip.

Upgrading python3 from 3.6 to 3.7: why do you want that? No need from SAB's point of view.

**Comment by sufr3ak** [comment]
I presume you're referring to Pip3 specifically. I unfortunately have other tools and programs which ask for pip. I'll see what I can do to avoid that, and I'll test again.

**Comment by sanderjo** [comment]
> I presume you're referring to Pip3 specifically. I unfortunately have other tools and programs which ask for pip. I'll see what I can do to avoid that, and I'll test again.

Ah, yes, I'll try to be more specific: "do not use pip for the SABnzbd dependencies". There seems to be something strange in the pip version of cherrypy.

**Comment by sufr3ak** [comment]
Would you recommend installing python3.x FIRST or let the PPA install it as a dependency? Also, should it be any specific version of Python? 3.6/3.7/3.8?

**Comment by sanderjo** [comment]
Just let the PPA take care of it.

**Comment by sufr3ak** [comment]
I got to this step:

> sudo apt-get update && sudo apt-get dist-upgrade
And I immediately got an error

From the logs:

> Unpacking sabnzbdplus (3.0.2-0ubuntu1~jcfp1~18.04) over (2.3.2+dfsg-1) ...

> Setting up sabnzbdplus (3.0.2-0ubuntu1~jcfp1~18.04) ...
> Installing new version of config file /etc/init.d/sabnzbdplus ...
> Job for sabnzbdplus.service failed because the control process exited with error code.
> See "systemctl status sabnzbdplus.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript sabnzbdplus, action "restart" failed.
> ● sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
>    Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
>    Active: failed (Result: exit-code) since Thu 2020-09-03 09:39:21 EDT; 8ms ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 6975 ExecStop=/etc/init.d/sabnzbdplus stop (code=exited, status=0/SUCCESS)
>   Process: 6981 ExecStart=/etc/init.d/sabnzbdplus start (code=exited, status=1/FAILURE)
> 

> Sep 03 09:39:20 MyServerName systemd[1]: Starting LSB: SABnzbd+ binary newsgrabber...
> Sep 03 09:39:20 MyServerName sabnzbdplus[6981]:  * Starting SABnzbd+ binary newsgrabber
> Sep 03 09:39:21 MyServerName sabnzbdplus[6981]: Not all required Python modules are available, please check requirements.txt
> Sep 03 09:39:21 MyServerName sabnzbdplus[6981]: Missing module: jaraco.collections
> Sep 03 09:39:21 MyServerName sabnzbdplus[6981]: You can read more at: https://sabnzbd.org/python3
> Sep 03 09:39:21 MyServerName sabnzbdplus[6981]: If you still experience problems, remove all .pyc files in this folder and subfolders
> Sep 03 09:39:21 MyServerName sabnzbdplus[6981]:    ...fail!
> Sep 03 09:39:21 MyServerName systemd[1]: sabnzbdplus.service: Control process exited, code=exited status=1
> Sep 03 09:39:21 MyServerName systemd[1]: sabnzbdplus.service: Failed with result 'exit-code'.
> Sep 03 09:39:21 MyServerName systemd[1]: Failed to start LSB: SABnzbd+ binary newsgrabber.
> dpkg: error processing package sabnzbdplus (--configure):
>  installed sabnzbdplus package post-installation script subprocess returned error exit status 1

> Errors were encountered while processing:
>  sabnzbdplus
> E: Sub-process /usr/bin/dpkg returned an error code (1)
>  

> The following packages were automatically installed and are no longer required:
>   libjs-excanvas libjs-jquery-metadata libjs-jquery-tablesorter libjs-mochikit python-cheetah
> Use 'sudo apt autoremove' to remove them.

Which I did...

I attempted a reinstall

> 
> Not all required Python modules are available, please check requirements.txt
> Missing module: jaraco.collections
> You can read more at: https://sabnzbd.org/python3
> If you still experience problems, remove all .pyc files in this folder and subfolders

**Comment by sanderjo** [comment]
I wanted to say "and can you show which packages have been installed via pip using the command `python3 -m pip list` " but on my Ubuntu that shows a lot of packages, of which **none** were installed via pip. :-(

**Comment by sufr3ak** [comment]
I can attempt to install Python3 first, (3.7/3.8), and then install SAB 3.0, and see what happens. I think I have the roll back set up pretty well, just a matter of time.

**Comment by sanderjo** [comment]
> I can attempt to install Python3 first, (3.7/3.8)

That is not standard Ubuntu 18.04 install: 18.04 has python3.6.

**Comment by sufr3ak** [comment]
I reinstalled python3.6

 sudo apt-get install python3.6
sudo apt-get install --reinstall python3-minimal

I had sab 2.x running.

I ran the install and had no errors.  I went to the Sab page, and saw a bunch of red error text. (I forgot to capture it)
I checked /etc/default/sabnzbdplus, added the user the tool should run as, filled that in. Restarted the service and now am receiving the python error.

running it as the install user (which used sudo, but isn't the running account), 

> $ sabnzbdplus
> Not all required Python modules are available, please check requirements.txt
> Missing module: jaraco.collections
> You can read more at: https://sabnzbd.org/python3
> If you still experience problems, remove all .pyc files in this folder and subfolders

I switched into the account that would normally run the tool and get the same error

**Comment by sufr3ak** [comment]
Update 

> sudo systemctl start sabnzbdplus
No error

> sudo systemctl status sabnzbdplus
> ● sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
>    Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
>    Active: active (exited) since Thu 2020-09-03 12:00:33 EDT; 6min ago
>      Docs: man:systemd-sysv-generator(8)
>     Tasks: 0 (limit: 4915)
>    CGroup: /system.slice/sabnzbdplus.service
> 
> Sep 03 12:00:33 MyServerName systemd[1]: Starting LSB: SABnzbd+ binary newsgrabber...
> Sep 03 12:00:33 MyServerName sabnzbdplus[1306]:  * SABnzbd+ binary newsgrabber: service not enabled, edit /etc/default/sabnzbdplus
> Sep 03 12:00:33 MyServerName systemd[1]: Started LSB: SABnzbd+ binary newsgrabber.
> 

I checked /etc/default/sabnzbdplus, and it seems fine

The only thing configured in there is:

> USER=sabaccount

**Comment by sufr3ak** [comment]
At this point, I cant even get sab 2.3 to start anymore as a service. I'm about ready to give up

**Comment by thezoggy** [comment]
what if you start sab manually, `python3  SABnzbd.py` ?
