### ISSUE TITLE
Active post processing is not filtered by category in history API call 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1595]
https://forums.sabnzbd.org/viewtopic.php?f=3&t=24943

The code is so ugly.. Want to think a bit more how to improve it in general.

**Comment by jcfp** [comment]
guess that link was supposed to point to https://forums.sabnzbd.org/viewtopic.php?f=3&t=24943 instead

**Comment by Safihre** [comment]
Closed in 691110af2c50cf47c4f55094528975f97335c74e
