### ISSUE TITLE
UI regression in 3.1.0 Beta1

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1596]
Just noticed a UI regression in 3.1.0 Beta1 concerning the "Multi-Operations" UI elements.

Went back to 3.0.2 for a sanity check and it is not present in this version.

Also checked in Incognito/Private mode to bypass any possible cache and cookies.

This is on macOS, checked in Chrome and Firefox, same regression.

As you can see, the "Multi-Operations" dropdown boxes are now vertically stacked instead of laid out horizontally.

![sabnzbd 3 1 0 Beta1 regression](https://user-images.githubusercontent.com/3321892/92241098-aa1b4480-ee8b-11ea-83e2-177a6002ae33.png)

**Comment by Safihre** [comment]
Oops 😁

**Comment by thezoggy** [comment]
due to https://github.com/sabnzbd/sabnzbd/commit/2937d8a022dff14ae503a077e839bc5fac9ce847
