### ISSUE TITLE
Error when filename exceeds filename limit of disk

### ISSUE THREAD

**Issue by skapytek** [sabnzbd/sabnzbd#1597]
Hi,
i got this error in sabnzbd on ubuntu 20:

```
/_UNPACK_[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [English Dub] [FuniDub 1080p x264 AAC] [MKV] [1EB4BBFB] [1+8] - [Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv y)
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 36] Filename too long: "/downloads/nzbs/sabnzbd/incomplete/[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [English Dub] [FuniDub 1080p x264 AAC] [MKV] [1EB4BBFB] [1+8] - [Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv y/[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv" -> "/downloads/nzbs/sabnzbd/complete/sonarrenglish/_UNPACK_[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [English Dub] [FuniDub 1080p x264 AAC] [MKV] [1EB4BBFB] [1+8] - [Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv y/[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sabnzbd/filesystem.py", line 655, in move_to_path
    renamer(path, new_path)
  File "/app/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/app/sabnzbd/filesystem.py", line 776, in renamer
    shutil.move(old, new)
  File "/usr/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 36] Filename too long: "/downloads/nzbs/sabnzbd/complete/sonarrenglish/_UNPACK_[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [English Dub] [FuniDub 1080p x264 AAC] [MKV] [1EB4BBFB] [1+8] - [Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv y/[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sabnzbd/filesystem.py", line 576, in create_all_dirs
    os.mkdir(path_part_combined)
OSError: [Errno 36] Filename too long: "/downloads/nzbs/sabnzbd/complete/sonarrenglish/_UNPACK_[Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [English Dub] [FuniDub 1080p x264 AAC] [MKV] [1EB4BBFB] [1+8] - [Golumpa] Kino's Journey - The Beautiful World (2017) - 07 (Kino no Tabi) [FuniDub 1080p x264 AAC] [1EB4BBFB].mkv y"
```

**Comment by sanderjo** [comment]
@Safihre test nzb ... https://raw.githubusercontent.com/sanderjo/NZBs/master/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.nzb

**Comment by Safihre** [comment]
I thought only Windows had path length restrictions!? 
Or is this specific to the underlying disk format?
Just to be very sure, what kind of disk is `/downloads` @skapytek?

**Comment by sanderjo** [comment]
It's not about the total length of the total path, but about the max length of individual parts of the path: The max filename length is 255 bytes. For ext4 and btrfs (so modern filesystems)

So total path can be 1000+ chars, as long as each dir name and file name is <= 255

The NZB I gave is 255 chars, and SAB introduces chars like UNPACK into it =>  bigger than 255

**Comment by sanderjo** [comment]
Interesting: Windows filesystems have the same limits: 255 chars per element, no (practical) limit on total path

Source: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

![image](https://user-images.githubusercontent.com/1273502/92277929-627cd300-eef4-11ea-95da-0cb91f233751.png)

**Comment by sanderjo** [comment]
Quick fix: cut incoming nzb to 200 chars. "200 chars should be enough for anybody!"

**Comment by skapytek** [comment]
> 
> 
> I thought only Windows had path length restrictions!?
> Or is this specific to the underlying disk format?
> Just to be very sure, what kind of disk is `/downloads` @skapytek?

Its a 2x2 nvme disk (raid 0) if this is the answer you are looking for.
Is it possible to hard cut the name directly in sabnzbd?

**Comment by skapytek** [comment]
> 
> 
> Quick fix: cut incoming nzb to 200 chars. "200 chars should be enough for anybody!"

how to do that?
Is there any kind of option for that in sabnzbd?

**Comment by thezoggy** [comment]
we had `folder_max_length` just to control this. but looks like it got removed in 3.x (still listed in our wiki though)

**Comment by Safihre** [comment]
@thezoggy You are right, I removed the `max_folder_length` option in the Python 3 conversion because I thought this was some weird Windows thing that wasn't needed anymore.
I will add it back.

**Comment by Safihre** [comment]
Looking at the list @sanderjo provided, is there a point of having a `folder_max_length` setting again or should we just set it to 256-10 (so we have space for `_UNPACK`)?

**Comment by thezoggy** [comment]
I would say keep it configurable because of edge cases like: https://github.com/Sonarr/Sonarr/issues/3888

**Comment by Safihre** [comment]
Alright. But I will rename it to `max_foldername_length` so people with older config's on Windows are not stuck with 128 if it picks up the old `max_folder_length` setting.

**Comment by thezoggy** [comment]
side note, when you install python 3.6+ on windows10 you get a prompt to disable the limit:
![img](http://zoggy.net/python-3.8.5-amd64_2020-09-06_20-34-31.png)

**Comment by Safihre** [comment]
@thezoggy that's not the same thing.. That's the limit for the whole path, while this is about the limit on each section of the path. As you can see from @sanderjo Wikipedia link, they are almost everywhere 255.
