### ISSUE TITLE
3.1.0B1 Windows 10 Priority of -2 returned by prequeue script ignored by SABnzbd

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1600]
Hi,

My pre-queue script does duplicate NZB name checking. If it finds a duplicate, then it returns the priority as -2 which means 'paused'. Also it replaces underscores with spaces in the NZB name. In SABnzbd I have configured "Detect Duplicate Downloads" to "Tag job".

When I add the same NZB to the watched folder twice, then my pre-queue script accepts the first time the NZB. The second time, it accepts it but it sets the priority to -2 which is "paused". However, SABnzbd appears to ignore the priority of -2 returned by my script and keeps the priority set to "normal". This "normal" priority was set in the category setting. The result is that the file for the second NZB is still downloaded and not paused.

The output of my pre-queue script for the second, to be paused, NZB is (as shown by it's log):

Accept:                 1 (1 = accept)
Nzb Name:               New NZB name without underscores
Post Processing Flags:  (not provided)
Category:               (not provided)
Script:                 (not provided)
Priority:               -2 (-2 = paused)
Group:                  (not provided)

and the exit code of the script is 0.

The debug log shows as script output:
```
2020-09-05 17:30:05,940::INFO::[newsunpack:2377] Pre-queue script returns 0 and output=
1

New NZB name without underscores







-2




```
I will email the debug log to Safihre.

**Comment by Safihre** [comment]
After your email, I now understand the problem.
The code to handle the duplicates is after the pre-queue script, so the duplicate-handling overwrites the pre-queue script.
It has worked like that for many years, but could indeed be improved.
