### ISSUE TITLE
Freeze/Crash on moving files

### ISSUE THREAD

**Issue by DarkTemplar87** [sabnzbd/sabnzbd#1602]
Hey there, forgive me for being a Linux noob. I'm currently hosting a plex server on a remote headless machine running Ubuntu 20.04 with SABNzbd Version 3.1.0 Beta. Currently I'm experiencing total unresponsiveness from the program periodically, only resolved by a service restart. It appears to get hung up on moving "some" files from incomplete to complete but does not seem to have any certain trigger for which files it freezes on. Here's the log from my most recent freeze, froze up moving Star Trek.
[sabnzbd (2).log](https://github.com/sabnzbd/sabnzbd/files/5190114/sabnzbd.2.log)

**Comment by sanderjo** [comment]
https://forums.sabnzbd.org/viewtopic.php?f=11&t=24949

**Comment by Safihre** [comment]
Seems so.. Will create a Debug version of postproc.py to try and see what is going on.

**Comment by Safihre** [comment]
@DarkTemplar87 Are you able to replace your `postproc.py` in the `sabnzbd` folder with this one?
https://raw.githubusercontent.com/sabnzbd/sabnzbd/bugfix/1602-freezecrash-on-moving-files/sabnzbd/postproc.py

**Comment by Safihre** [comment]
With another user I have identified the issue to be the `ARTICLE_LOCK` which I modified a bit for 3.1.0 to resolve another issue.
But I have no clue why yet.. Will have to investigate more.
