### ISSUE TITLE
sabnzbd - systray icon

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1604]
Normally the systray icon shows the app name by default. 

Apps like radarr/sonarr show their versions with it:
![img](http://zoggy.net/OUTLOOK_2020-09-08_18-30-43.png)

Symantec for example does two lines:
![img2](http://zoggy.net/firefox_2020-09-08_18-34-55.png)

sab currently just show the queue status, ex: Idle
Thoughts on updating it show `sab - <version>(<status>)`,

example:
```
sab - 3.1.0Beta1 (Idle)
```

and if there are any problems, show some verbiage as the 2nd line?

**Comment by thezoggy** [comment]
Additionally, we could add some icons to the context menu

example of others:
![img5](http://zoggy.net/2020-09-08_18-47-14.png)

![img6](http://zoggy.net/firefox_2020-09-08_18-46-20.png)

**Comment by Safihre** [comment]
I think indeed we can add icons. But someone would be willing to make them.. Probably has to be some special format again.
