### ISSUE TITLE
CherryPy 3.3.0

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#161]
can get it here: https://pypi.python.org/pypi/CherryPy

whats changed from 3.2.0rc1 to 3.3.0:
https://bitbucket.org/cherrypy/cherrypy/branches/compare/3.3.0..cherrypy-3.2.0rc1

**Comment by shypike** [comment]
I will soon upgrade to CherryPy 3.8.0.

**Comment by thezoggy** [comment]
for those curious of the change log:
https://bitbucket.org/cherrypy/cherrypy/raw/6c5250a7703b385b2dc13429ba6a17202aeaa882/CHANGES.txt

**Comment by thezoggy** [comment]
side note, wonder if this is the source of sb's handle problem..
https://bitbucket.org/cherrypy/cherrypy/issues/1304/cherrypy-leaving-hundreds-of-close_wait

**Comment by shypike** [comment]
I will include 3.8.0 and maybe 3.8.1, if out in time.
We've been asked by some package creators to start using mainstream releases (possibly with some minor patches). It looks like 3.8.0 is finally good enough to use without serious patching.
It does require one patch: to redirect http to https. That's not CP's fault: it's the broken Bonjour protocol that requires it.

**Comment by shypike** [comment]
Done
