### ISSUE TITLE
Setup Wizard step Two incorrect URLs

### ISSUE THREAD

**Issue by SunMar** [sabnzbd/sabnzbd#1617]
Hi,

Today I was setting up SABnzbd. I'm running it from a Docker container, but since port 8080 is already in use on my system I remapped the port in the container configuration to 9091. After the first step in the Wizard setting up the news server, the second step is shown "Setup is now complete!".

![image](https://user-images.githubusercontent.com/8324268/93865709-f86f7680-fcc6-11ea-9aab-688eee088e91.png)

Here I ran into the issue that the URLs on this page are broken because they're generated server side and don't take into account that SABnzbd can be behind a reverse proxy or as in my case inside a Docker container that has the port remapped. This breaks not just the list of access URLs shown (marked as A in my screenshot), but also the links to the settings page (marked as B) and the "Go to SABnzbd" button (marked as C).

The links shown at A are only (pretty much) guaranteed to work on the local machine or inside the virtual machine where SABnzbd is running. If you're accessing the Setup Wizard remotely it's very possible some or even all those URLs won't work. Remote access can be because it's running in a Docker container like in my use case, but the same applies if you're running it on a server, Raspberry Pi or NAS and are doing the setup from your regular computer. Ideally maybe something can be added client-side (AJAX?) to figure out what works and what doesn't work, but that might be over complicating things.

Would it be possible to
1. add the current URL that's used to access SABnzbd to the list at A (based on the REQUEST URI for example)?
2. do not use `$access_url` for the links at B and C, instead change them to relative links so they are guaranteed to work (`../../config/folders` and `../../`)?

For reference the applicable code:

https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/sabnzbd/interface.py#L566
https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/sabnzbd/interface.py#L582
https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/interfaces/wizard/two.html#L15-L17
https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/interfaces/wizard/two.html#L25
https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/interfaces/wizard/two.html#L31
https://github.com/sabnzbd/sabnzbd/blob/730d7179368ae96778d7fea2faf3cc6b99f7301a/interfaces/wizard/two.html#L42

**Comment by Safihre** [comment]
This advanced use-case is beyond the scope of the basic setup process we provide. I imagine there's just too many cases we can't cover properly, even if we use the requested URI.
We do have the option to set the `url_base` for proxy users.

**Comment by SunMar** [comment]
@Safihre yeah I understand that the list of URLs at A is tricky and you can't really cover all use cases there, hence my suggestion to include the URL based on the REQUEST URI. Assuming you are accessing the Setup Wizard in the same way you're going to access SABnzbd later, that should always work regardless of your use case.

But either way the issue I initially ran into wasn't the list of URLs in A, but rather that the links in B and C are broken. The entire UI seems to be using relative links, except for this "Two" page of the Setup Wizard. I don't mind making a PR myself to change those three buttons to relative paths, just always interested in some feedback first to know if a PR like that would be accepted or not :).

**Comment by sanderjo** [comment]
I, as a Docker user, would like to have the correct URLs ... if possible, of course. 

I doubt that SAB can know the real outside-docker folder names.

**Comment by Safihre** [comment]
Implemented!
