### ISSUE TITLE
Cannot start sabnzbd from source as windows service

### ISSUE THREAD

**Issue by h3llrais3r** [sabnzbd/sabnzbd#1623]
I'm running latest master version on Windows 10 with Python 3.8.5 x64.
I've followed installation instructions for installation from source:

- checkout  code
- install dependencies in virtual env.

I've created a`bat` files which activates the virtual env and then starts Sabnzbd.py with virtual env with python 3.
This `bat` file is configured to run as a service in windows (via nssm).

``` bash
@rem make sure that python.exe is in your path!
echo launching virutal environment for python 3
call %~dp0\venv\sabnzbd-py38\scripts\activate.bat

echo starting sabnzbd
cd %~dp0\sabnzbd-master-py3
python Sabnzbd.py
```

During startup, I'm getting the following error:

``` python
Traceback (most recent call last):
  File "Sabnzbd.py", line 1690, in <module>
    if not handle_windows_service():
  File "Sabnzbd.py", line 1649, in handle_windows_service
    servicemanager.StartServiceCtrlDispatcher()
pywintypes.error: (1063, 'StartServiceCtrlDispatcher', 'The service process could not connect to the service controller.')
```

Running the `bat` file directly from a command prompt works, but when running it as a windows service, it fails with the error above. Any idea what I'm doing wrong?

PS: I was running it from source as well in the past (before python3 upgrade) with the same `bat` file (except not using a virtual env) without any problems.

**Comment by Safihre** [comment]
I am not completely sure.. We only support it from the binaries, not from sources. When developing I didn't test it from sources, only by compiling the binaries and using those.

**Comment by h3llrais3r** [comment]
With the previous version (<3.0.0) it was working...
It seems that the windows service support (`handle_windows_service`) is changed and no longer works.

**Comment by Safihre** [comment]
As this is an extremely small use case, I don't think I can really take the time to investigate what the problem is.. Sorry 😕

**Comment by thezoggy** [comment]
Running as admin? Service account set to use your env?

**Comment by h3llrais3r** [comment]
> Running as admin? Service account set to use your env?

Running it as local system account, so I don't need to login with a certain user.

> As this is an extremely small use case, I don't think I can really take the time to investigate what the problem is.. Sorry 😕

😢 Find it a pity because it was working perfectly before the Python 3 upgrade... 😢

**Comment by thezoggy** [comment]
@h3llrais3r are you logging in via remote desktop or using fast user switching?

**Comment by h3llrais3r** [comment]
Its running on headless server so I login with RDP to check. But it's running as windows service so I do not see the link with how I login remotely?

**Comment by thezoggy** [comment]
are you starting sab as a service manually or is it starting on login? and did you use nssm to install the service, manually, or sab installer ?

**Comment by h3llrais3r** [comment]
It's installed via nnsm. Nssm is starting the `bat` file.
As I already mentioned: starting the `bat` file manually works, starting it via the services interface (so also when server is started) it's failing due to the code block I mentioned above.
Without that code block, it works fine.

**Comment by Safihre** [comment]
Aaah, I never saw your edit. Well, you are not really running SABnzbd as a service the way we provided it but with your own wrapper. This throws off our detection code.
I will make a change to the code so that it only executes this bit when run as part of the executable. It could be made to work when run from sources, so by running:
```
python SABnzbd.py -f "%localappdata%\sabnzbd\sabnzbd.ini" install
```
But I don't have the time to dive into that right now..

**Comment by h3llrais3r** [comment]
@Safihre Let me know then the fix is available and I'll be happy to test.
Thanks for your support.

**Comment by h3llrais3r** [comment]
@Safihre 
I've just tested the fix and it's running again from source as a windows service! 👍 

Thanks again.
