### ISSUE TITLE
Changed Router Now Can't Resolve DNS Lookup, Server Fails

### ISSUE THREAD

**Issue by spiderguy84** [sabnzbd/sabnzbd#1626]
I switched my Synology DS218+ over to a new router. Ever since then, my SABNZBD cannot work.  When I try to test my news.newshosting.com server, it gives me an error message of "Address not available check for internet or DNS problems" and when I click the wrench on the main page for SABNZBD it gives a 172.x.x.x address for IPv4 and IPv6 none  Nameserver/DNS Lookup Connection Failed. What's going on?

**Comment by thezoggy** [comment]
your network adapter isnt getting dns servers.. so its not going to figure out how to translate news.newshosting.com to <ip>. you prob had dhcp setup before on old router and this one its not done the same. this has nothing to do with sab, just user network not setup.

**Comment by Safihre** [comment]
Indeed!
