### ISSUE TITLE
Deobfuscate.py script vs built-in deobfuscate function

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#1627]
I see that the Deobfuscate.py script is now slated for removal in a later version, in favor of the new built-in "Deobfuscate final filenames" function.

I use the the Deobfuscate.py script, but not for every single download, because I'm fine with the file names of almost all downloads. For some specific categories (tv, movies) other scripts / applications take care of the file names.

That means that I use the Deobfuscate.py script just for some specific categories and RSS feeds. I don't wish to use this type of file name deobfuscation anywhere else. How do I do that with the new "Deobfuscate final filenames" function? As far as I can see, I can only turn it on for everything or turn it off.

**Comment by sanderjo** [comment]
> I don't wish to use this type of file name deobfuscation anywhere else.

Can you explain why not? What is the bad effect or side effect of it?

**Comment by anonvoy** [comment]
> Can you explain why not?

I wish to keep the original file names for (among other things) sorting purposes and don't want to change them to the job or nzb names or whatever.

**Comment by sanderjo** [comment]
Ok, but can you give examples of that sorting?

**Comment by anonvoy** [comment]
> Ok, but can you give examples of that sorting?

As I wrote in my updated comment I don't want any further debate about this. What I **do** want is an answer to my question.

**Comment by sanderjo** [comment]
I don't want to debate either. I want you to understand your use case.

**Comment by Safihre** [comment]
@anonvoy indeed I added the message to find out if there was use cases where you only want it for specific categories.
I also felt like it should be category specific, but then I don't have an exact reason why. So not a debate, we just want to be informed about yours or other's use case where it should be on per category basis.

**Comment by randallspicher** [comment]
Many downloads do not have obfucated filenames, and renaming the files in those can totally break things. 
Examples:
1. a rar set which unpacks into bdmv or video_ts folder.  renaming the .m2ts or vob files inside those will break the structure, making them un-playable.
2. a nzb which has a bunch of stuff in it (multiple episode files of a tv series, multiple flacs or mp3s of an album, or a collection of documents or images).  renaming those types of files makes it difficult (or impossible) to identify the contents.

The old method (using a post-process script) at least allowed the downloader to decide whether or not to rename the files (by having separate catagories, some with deobfucation on, some with it off)

**Comment by sanderjo** [comment]
Hi @randallspicher 

Ad 1: I thought I had excluded Bluray like files. So, can you can give example of such a set (or give the NZB)
Ad 2: The function first if the files are probably obfuscated. If not, they are not renamed. So, again, can you give examples?

**Comment by Safihre** [comment]
Indeed, the new option is smarter than the `Deobfuscate.py` script. And we want to continue to improve it so it can be a single option that's reliable in 99% of cases.
