### ISSUE TITLE
Wizard shows hostname when host in config is set to blank

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [sabnzbd/sabnzbd#1629]
When `host = ""` in config, the setup wizard shows `http://<servers hostname>:8080` as the URL to access the server, which is wrong.

Version: 3.0.2

**Comment by ThatNerdyPikachu** [comment]
Related to #1617?

**Comment by Safihre** [comment]
Why is it wrong? When the hostname is set to empty, SABnzbd will bind to the local IP-address of the system so it can also be accessed through it's hostname.

**Comment by jcfp** [comment]
Probably because that only works if the hostname resolves to localhost, which in turn requires an entry in the system's host file. While that may be standard practice these days, it isn't guaranteed to exist.

**Comment by Safihre** [comment]
In #1617 I changed that the current URL is the main URL to be shown and used in the buttons.

**Comment by Safihre** [comment]
I think that should be enough for now. The whole logic when `host = ""` is already convolueted enough. If they managed to get to this page, the URL should be clear :)
