### ISSUE TITLE
3.1.0RC3 Windows: "Failed to retrieve RSS from https://blabla : <urlopen error [Errno 11001] getaddrinfo failed>"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1631]
More RSS Warnings with 3.1.0RC3 Windows

Failed to retrieve RSS from https://www.appelboor.com/dump/rss-mini-1940: <urlopen error [Errno 11001] getaddrinfo failed>

![image](https://user-images.githubusercontent.com/1273502/95307954-90ee2500-0889-11eb-85ae-dc3718631f45.png)

Probably because network was down, but a new, unnecessarry warning, IMHO, possible to the new RSS library?

**Comment by Safihre** [comment]
Why is the warning unnecessary? 
The user setup RSS-feeds to be retrieved, but we couldn't do it. So we should let the user know.

**Comment by sanderjo** [comment]
Oh, wait: was this always like this? I just installed SAB on Windows "to run from boot", so maybe that explains why I get those warnings only now?

**Comment by Safihre** [comment]
No, it's new, and on purpose. It used to swallow the errors causing you to have failing feeds and never know.

You can disable the warnings by disabling `helpful_warnings` in Config > Specials.

**Comment by sanderjo** [comment]
So a feature not a bug. Clear.
