### ISSUE TITLE
macOS wake on network access 

### ISSUE THREAD

**Issue by aniqueta** [sabnzbd/sabnzbd#1635]
Opening a new issue per conversation here: https://github.com/sabnzbd/sabnzbd/issues/1521

Prior to 3.0.0, SABnzbd would successfully register with Bonjour services and thus if the mac was asleep (and wake on network access was enabled in the OS energy settings), accessing the web interface would wake the mac up. This is no longer the case with 3.0.0.

Not sure how to pinpoint the cause of this, but hope this is an easy fix. Happy to help debug. This experience is on macOS Catalina. Thank you!

**Comment by sanderjo** [comment]
In sabnzbd.log (somehwere on your disk, but also accessible via upper right corner -> Wrench symbol -> tab Status -> Show Logging), search for lines with "Bonjour" in them, like:

```
2020-10-11 09:20:57,315::INFO::[zconfig:71] No Bonjour/ZeroConfig support installed
```
or (after installing the correct Ubuntu libraries):
```
2020-10-11 09:25:37,480::INFO::[zconfig:84] Bonjour/ZeroConfig does not support "localhost"
```

The above is on my Ubuntu, and my Ubuntu Bonjour / Zeroconf tools like `mdns-scan` and `avahi-discover` neither see SABnzbd ...

**Comment by sanderjo** [comment]
Weird: overall SAB is listening on 0.0.0.0, but within zconfig host is 127.0.1.1?

![image](https://user-images.githubusercontent.com/1273502/95673247-4c26fe80-0ba7-11eb-9d78-66fcae22260e.png)


When I comment out that if-block, bonjour is working again for me.

Back to where set_bonjour() is called: the 127.0.1.1 is caused by gethostbyname(). But cherryhost is much better, but ignored.

![image](https://user-images.githubusercontent.com/1273502/95673372-1df5ee80-0ba8-11eb-9a0d-11d2943693ce.png)

**Comment by sanderjo** [comment]
```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname(socket.gethostname())
'127.0.1.1'
>>> 
```

but also on python2:

```
$ python2
Python 2.7.17 (default, Jul 20 2020, 15:37:01) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname(socket.gethostname())
'127.0.1.1'
>>> 

```

**Comment by jcfp** [comment]
@sanderjo I guess that is an attempt to figure out what address to advertise, since `0.0.0.0` won't work for that. Unfortunately, the local hostname it gets back resolves to an address within 127.0.0.0/8 (probably via /etc/hosts)

**Comment by sanderjo** [comment]
> I guess that is an attempt to figure out what address to advertise, since `0.0.0.0` won't work for that.

Ah, yes, of course! Thank you.

SAB does know it's own IPv4 address ... it is shown in the Wrench overview ... BRB

**Comment by sanderjo** [comment]
I hacked two lines into the code:
```
    from sabnzbd.getipaddress import localipv4
    try:
        #z_host = socket.gethostbyname(socket.gethostname())
        z_host = localipv4()
    except socket.gaierror:
        z_host = cherryhost
    sabnzbd.zconfig.set_bonjour(z_host, cherryport)
```
and now my bonjour is working again:

```
2020-10-11 10:21:58,942::DEBUG::[zconfig:90] Try to publish in Bonjour as "witte2004" (192.168.2.9:8080)
2020-10-11 10:21:58,969::DEBUG::[zconfig:111] Successfully started Bonjour service
```
And, yes, 192.168.2.9 is really my LAN address

**Comment by jcfp** [comment]
Using localipv4() here is a good thing, not so sure about the fallback to cherryhost though (esp. without any sanity checks). It can easily be nonsensical for zeroconf, even when perfectly valid for its intended purpose.

**Comment by Safihre** [comment]
Great you guys are diving into this code. I never touched a single like of it in all those years, besides the `2to3` conversion. 😅

**Comment by sanderjo** [comment]
I think we have a few use cases:

- normal setup: one interface, with a default Internet route.`localipv4()` will take care of that
- multiple interface, and user has specified a specific interface to listen on via cherryhost. We should honor that.
- no working network / LAN. Announcing on 127.0.0.1 is good enough; makes it visible on the machine itself, which can be handy
- Rare: working network, but no default gateway. I think `localipv4()` will say None.

**Comment by thezoggy** [comment]
Looking, we all know 127.0.0.1 == loopback/localhost
But looks like 127.0.1.1 is bound to hostname, which is a ubuntu/debian thing (and 127.0.0.2 in fedora)

https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in

looking, I do not see 127.0.1.1 in macos.
