### ISSUE TITLE
Feature Request: Use theme in config pages as well as the main web interface. 

### ISSUE THREAD

**Issue by dingdongbingbong** [sabnzbd/sabnzbd#1640]
Would it be possible to use the glitter theme (or any other theme) on the config pages as well? It's blinding going from the web interface to the config pages to tweak things so it would be nice to have the same theme applied to the web interface and the config pages. 

Thanks!

**Comment by thezoggy** [comment]
We used to do themes on the config and then in 0.7.x we went away since it made it cumbersome to support them on making basic changes. But the universal config is close to how glitter looks already?

**Comment by dingdongbingbong** [comment]
Sorry, I meant the Glitter - Night theme. It would be nice to have it applied to both the web interface and the config menu. 

I did not realize that it was an option that was removed due to it being cumbersome. 

Would it be possible to revisit it now, give that the backend may have changed considerably from v0.7 to v3.0?

Thanks for getting back to me!

**Comment by dingdongbingbong** [comment]
so...this won't be happening I take it? 

I guess I'll have to learn how to code! haha
