### ISSUE TITLE
FYI: SSDP / Simple Service Discovery Protocol and SABnzbd and Windows

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1641]
This could be interesting: 

- My Windows sees other devices on my LAN: a Google Chromecast, a Synology Diskstation, a Philips Hue, a router, and my linux box. 
- When I double click on the Synology Diskstation, my browser opens and goes to the Synology page http://192.168.1.1:5000/
- So how does Windows know about these devices? Answer: SSDP / Simple Service Discovery Protocol. See https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol

This could be handy for SABnzbd: it could announce itself via SSDP (just like it does via Bonjour/Zeroconf, which is more an Apple protocol) so you can find it easily (handy if SAB is on another device on your LAN).

There are implementations of SSDP in Python (like https://pypi.org/project/ssdp/ ), but I have not yet found a way to advertise yourself.

Feedback?

![image](https://user-images.githubusercontent.com/1273502/96012256-384bf880-0e44-11eb-8c58-6a1d9017fc37.png)

**Comment by jcfp** [comment]
> There are implementations of SSDP in Python (like https://pypi.org/project/ssdp/ ), but I have not yet found a way to advertise yourself.

It looks like broadcasting a one-time _notify_ at startup suffices. After that, a service only listens for incoming search requests without the need for repeat announcements.

**Comment by sanderjo** [comment]
Yes, could be. But if I run the example script, nothing appears on my Windows, and nothing appears on the stdout of my Linux running the script (so apparently no trigger of respsonse_received nor request_received with their print statements). Also nothing when I change the port from 1982 to 1990 (which seems to be the real SSDP port).

**Comment by sanderjo** [comment]
I got it working!

Functional: SABnzbd (running on my Linux) shows up on my Windows machine under Network (just like my other SSDP devices like my Synology and Philips Hue). On Windows, double clicking on the SABnzbd logo leads my webbrowser on Windows to the SAB interface on my linux.

Plain SSDP is not enough to appear on Windows: in the SSDP broadcast you have to provide a description.xml which contains the relevant info.

So, technical:

1. my Linux is broadcasting a SSDP message each second or so. A few lines of python code. That should be in SABnzbd, triggered each few seconds
2. Windows receives that broadcast and looks for an URL (a XML file) in that broadcast. Windows retrieves that URL / XML-file
3. my Linux' serves that XML. I do that with Apache, but probably easy for SAB / cherrypy to serve that page
4. WIndows parses the XML, and SABnzbd shows up in Windows!

It seems easy to implement in SABnzbd.

Proof:

![image](https://user-images.githubusercontent.com/1273502/96772424-6781dd00-13e3-11eb-90e3-967fcff5d9d8.png)

**Comment by sanderjo** [comment]
Work to do:

With two machines running SAB-with-SSD-XML, two SAB instances pop up (good), but both lead to one instance. Weird
I've already made the uuid's in both the SSDP broadcast and in the description.xml unique.

**Comment by sanderjo** [comment]
FYI: 

The broadcasts:

NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=60
LOCATION: http://192.168.1.4:8080/description.xml
SERVER: SABnzbd
NT: upnp:rootdevice
USN: uuid:11105501-bf96-4bdf-a60f-382e39a0f84c::upnp:rootdevice
NTS: ssdp:alive
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1600778333
BOOTID.UPNP.ORG: 1600778333
CONFIGID.UPNP.ORG: 1337


NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=60
LOCATION: http://192.168.1.101:8080/description.xml
SERVER: SABnzbd
NT: upnp:rootdevice
USN: uuid:ac2f6246-14a2-11eb-b024-9b0ef4da052f::upnp:rootdevice
NTS: ssdp:alive
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1600778333
BOOTID.UPNP.ORG: 1600778333
CONFIGID.UPNP.ORG: 1337


and the xmls files


$ lynx --dump http://192.168.1.4:8080/description.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.4:8080/sabnzbd</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>SABnzbd (192.168.1.4)</friendlyName>
<manufacturer>SABnzbd Team</manufacturer>
<manufacturerURL>http://www.sabnzbd.org</manufacturerURL>
<modelDescription>SABnzbd downloader</modelDescription>
<modelName>SABnzbd 3.4.5</modelName>
<modelNumber>model xyz</modelNumber>
<modelURL>http://www.sabnzbd.org</modelURL>
<serialNumber>001788721333</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-001788721f33</UDN>
<presentationURL>sabnzbd</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>



$ lynx --dump http://192.168.1.101:8080/description.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.1.101:8080/sabnzbd</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>SABnzbd (192.168.1.101)</friendlyName>
<manufacturer>SABnzbd Team</manufacturer>
<manufacturerURL>http://www.sabnzbd.org</manufacturerURL>
<modelDescription>SABnzbd downloader</modelDescription>
<modelName>SABnzbd 3.4.5</modelName>
<modelNumber>model xyz</modelNumber>
<modelURL>http://www.sabnzbd.org</modelURL>
<serialNumber>001788721333</serialNumber>
<UDN>uuid:1641d588-14a3-11eb-b024-9b0ef4da052f</UDN>
<presentationURL>sabnzbd</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>

**Comment by jcfp** [comment]
Nice to see this coming along. The serials in the xmls are still the same, maybe that triggers it?

On a side note: is it really necessary to broadcast every other second? Don't ssdp clients announce they're looking for services so the server side can back off, other than a single broadcast at startup and occasional ones thereafter at much large intervals? After all, the info provided by sab (url, program name, and version) is static inbetween restarts and there's plenty of lans with 1000s of clients in them (think university housing and the likes) where this kind of frequent chatter does add up.

**Comment by sanderjo** [comment]
Indeed, serials should probably be unique. Or removed completely. 

> On a side note: is it really necessary to broadcast every other second? Don't ssdp clients announce they're looking for services so the server side can back off, other than a single broadcast at startup and occasional ones thereafter at much large intervals?

Correct.

Background: On my LAN, I see SSDP broadcasts each few seconds from devices, so I implemtented it that way. I'm not too concerned about the 365 bytes each 1 second.
I could raise the interval to 5 resp 60 seconds, and see how Windows behaves with that.


To follow your proposal, I would have to build a listerener in SAB that responds to such SSDP search requests. Such a SSDP listener itself is easy (I think 10-2 lines to listen on socket 1900 for MSEARCH, and respond) but I would need @Safihre help to build the framework (with asyncio ?). And then I could fill it out. A bit more work & code, but probably more beautiful.

**Comment by jcfp** [comment]
I didn't consider the listener would occupy the port. That would probably cause more trouble than it's worth (unless multiple listeners are somehow allowed on the same port for multicast).

A slightly lower frequency than every 2s for the broadcasts wouldn't really have any downsides though; windoze would have already received at least one ssdp announcement before it can even show a user the desktop.

**Comment by sanderjo** [comment]
Current PR: I would call it ready for testing by others.

![image](https://user-images.githubusercontent.com/1273502/97085032-1f4cff80-161b-11eb-8021-843685c8038f.png)
