### ISSUE TITLE
3.1.0RC3 - Leftover files in /completed

### ISSUE THREAD

**Issue by cphmichael** [sabnzbd/sabnzbd#1642]
A follow up on #1630 

I have changed from: SABnzbd Version "3.2.0-develop" to "**3.1.0RC3**" but I still see leftover files in /completed.

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5390145/sabnzbd.log)

![image](https://user-images.githubusercontent.com/45288008/96232547-4ca10a00-0f98-11eb-8d54-9ed4b636932a.png)

![image](https://user-images.githubusercontent.com/45288008/96233242-7ce8a880-0f98-11eb-83bd-f8c07394afaa.png)

**Comment by Cpuroast** [comment]
FYI, you probably didn't realize that 3.1.0RC3 is behind 3.2.0-develop, the directunpack fix will most likely be included in 3.1.0RC4.

**Comment by Safihre** [comment]
It's not included in 3.1.0 because the code that broke it, was not part of 3.1.0. For 3.1.0 it should work. 
So again, we will need full Debug logs to see what is going wrong.

**Comment by cphmichael** [comment]
Today I received Helstrom S01E01 - S01E10, but only S01E03 was left behind.

I will enable the Debug logs and upload the logfile if it happens again.

**Comment by cphmichael** [comment]
As suggested I have changed to master branch Version: | 3.1.0 [23f86e9]
I still see leftover files in /completed
Unfortunately, I went back to info-log because I thought that the problem was solved in the master branch.
This download was one of the bad ones from Nzb.su, so maybe there is nothing to do about it?

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5423199/sabnzbd.log)

![sabnzbd - history](https://user-images.githubusercontent.com/45288008/96880133-1b837680-147d-11eb-8b42-461df08ec43a.JPG)

![completed](https://user-images.githubusercontent.com/45288008/96880691-c09e4f00-147d-11eb-9b95-45e967e595a9.JPG)
