### ISSUE TITLE
Error: Failed moving

### ISSUE THREAD

**Issue by conorsavage** [sabnzbd/sabnzbd#1643]
Anything I download now has the same error. Here is the logs. Can anyone suggest what is causing this?
[sab.txt](https://github.com/sabnzbd/sabnzbd/files/5396045/sab.txt)

**Comment by Safihre** [comment]
```
PermissionError: [Errno 13] Permission denied: '\\\\?\\F:\\SABnzbd\\Temporary\\Keeping.Up.With.the.Kardashians.S19E05.XviD-A.1\\<HASH>7016a9e.part01.rar' 
```
So, something is not letting SABnzbd access the files. Maybe virusscanner? 
On Windows it can help to restart the device.

**Comment by conorsavage** [comment]
Thats exactly what it was. Thank you so much.

**Comment by Safihre** [comment]
👍
