### ISSUE TITLE
mode=change_opts api call fails to set postproc option to (category) default

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1644]
Doing an [api call](https://sabnzbd.org/wiki/advanced/api#change_opts) to change the post-processing option for a given job along the lines of `http://127.0.0.1:8080/sabnzbd/api?mode=change_opts&apikey=apikey&output=json&value=SABnzbd_nzo_idididid&value2=n` returns true (and actually works) for _n_ between zero and three. For -1 however, which according to the documentation should set the job's postprocessing option to the (category) default, it returns false and doesn't change the job setting.

**Comment by Safihre** [comment]
Interesting, wondered if this ever worked because we have this input check:
```python
>>> "-1".isdigit()
False
```

**Comment by Safihre** [comment]
Also nowhere else in the code the `-1` is processed. It's only applicable when adding new NZB's.
Will update documentation.
