### ISSUE TITLE
Feature Request: On Servers show last 12 months/1 year of bandwidth 

### ISSUE THREAD

**Issue by xrequester** [sabnzbd/sabnzbd#1645]
I love SABnzbd. 

One thing I would like to see is that at the server information at /config/server/ I can also see the last 12 months/1 year of bandwidth.
That would really help on block account servers to gauge which size of block to buy when one is used up. 

I guess the UI would have room for another line then: 6 months, 2 years or 5 years in addition to the 12 months/1 year, but the 12 months/1 year would be most useful to me personally. 
It could be fully customizable on what statistics to display, but that's probably not worth the work unless the person able to implement it would love to have it ;-)

Thanks for everything you do.

**Comment by MarkCanada** [comment]
I would like to have that as well

**Comment by Cpuroast** [comment]
Yup, I was thinking exactly that.

Like right below "This month", it should have "This year".

**Comment by Safihre** [comment]
![image](https://user-images.githubusercontent.com/5703454/100525459-4f129880-31c1-11eb-952b-f8a46eb3f3e8.png)
