### ISSUE TITLE
Problems with Maximum line speed

### ISSUE THREAD

**Issue by segelkma** [sabnzbd/sabnzbd#1646]
Hi.
Two issues:
1.
I have a 200 Mbit connection so I set the maximum line speed at 20MB/s to not shut down the connection for the others (ping goes up to 1000 at full speed).
Sometimes after a fresh computer start SABnzbd will nevertheless download with full speed. I have to adjust the speed via the slider to fix this and can then only set it to max 20 MB/s.

2.
Sometimes when I try to manually adjust the speed (the dropdown on the main page) I get the message that I must set a maximum line speed first. I then have to reload the tab and it will work. This problem started since I made the SABnzbd tab sticky (in Firefox). Only occurs sometimes though.

**Comment by sanderjo** [comment]
> I have a 200 Mbit connection so I set the maximum line speed at 20MB/s to not shut down the connection for the others (ping goes up to 1000 at full speed).
> Sometimes after a fresh computer start SABnzbd will nevertheless download with full speed. I have to adjust the speed via the slider to fix this and can then only set it to max 20 MB/s.

You know 200 Mbps = 20 MB/s?

**Comment by segelkma** [comment]
I suggest you do the math again ;)
It's 25

**Comment by Safihre** [comment]
In Config > General, what do you have set for the percentage of the line speed?
Might have to enable Advanced settings to see this percentage. 
Also, how do you run SABnzbd? Windows / Linux? From sources or installer?

**Comment by segelkma** [comment]
It is set to 0. So I guess that means use all it can. Nevertheless I expected the maximum Line speed to be used then.
Putting this to 100% should fix it then, right?
Or putting the real line speed and setting it to 80%.

Windows, Installer

**Comment by Safihre** [comment]
0 means disabled speed, 100 is max line speed. This should be explained better in the wiki.
Will update it.

**Comment by Cpuroast** [comment]
> It is set to 0. So I guess that means use all it can. Nevertheless I expected the maximum Line speed to be used then.
> Putting this to 100% should fix it then, right?
> Or putting the real line speed and setting it to 80%.
> 
> Windows, Installer

FYI 200Mbit = 23.8419MiB/sec 
Multiples of 1024 and all that, which is what Sab uses as far as I know.

You have 2 choices:
You'd set "Maximum line speed" to 20MB/s and set "Percentage of line speed" to 100%.
This will allow Sab to use at most 20MiB/sec under any circumstance, then you can manually adjust the slider from 0% to 100%, meaning 0 to 20MB, if you want to temporarily restrict it even further.

Or you set "Maximum line speed" to 24MB/s and set "Percentage of line speed" to 80%. Which will restrict it to around 19.2MB/sec

Percentage of line speed set to 0% effectively disables all speed restrictions.

**Comment by Safihre** [comment]
Wiki updated.
