### ISSUE TITLE
change_complete_action api call should verify input

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1650]
The [api call](https://sabnzbd.org/wiki/advanced/api#change_complete_action) accepts a number of predefined actions as well as scripts in case the supplied _value_ starts with "script_". Unfortunately, the value of the script is not subject to any further checks. As a result, not only do invalid script values get accepted, but, using relative paths (to the script dir), any command on the system can be called. The setting should be limited to only whatever scripts actually exist in the script dir.

**Comment by Safihre** [comment]
Hmm, it's not just this call but all the calls that have `script` as input.
Such as changing the script of a job, category, RSS-feed, etc.

**Comment by jcfp** [comment]
> Hmm, it's not just this call but all the calls that have `script` as input.
Yeah, I should have mentioned not checking any of the others; change_completion_action just happened to be the one I came across while writing tests.
