### ISSUE TITLE
3.1.0 (master) - Leftover files in /completed 

### ISSUE THREAD

**Issue by cphmichael** [sabnzbd/sabnzbd#1652]
Follow up to #1642

Repository: hotio/sabnzbd:release
 
As suggested I have changed to master branch Version: 3.1.0 [23f86e9]

I still see leftover files in /completed
Unfortunately, I went back to info-log because I thought the problem was solved in the master branch.

This download was one of the bad one from Nzb.su, so maybe there is nothing to do about it?

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5423199/sabnzbd.log)

![sabnzbd - history](https://user-images.githubusercontent.com/45288008/96880133-1b837680-147d-11eb-8b42-461df08ec43a.JPG)

![completed](https://user-images.githubusercontent.com/45288008/96880691-c09e4f00-147d-11eb-9b95-45e967e595a9.JPG)

**Comment by Safihre** [comment]
Maybe I am misunderstanding, but what is the problem?
It unpacked 5 files, what did you not expect to happen?
```
2020-10-22 15:10:46,755::INFO::[postproc:429] Unpacked files [
'/downloads/completed/Series/_UNPACK_Babylon.Berlin.S03E03.German.1080p.BluRay.x264-iNTENTiON-xpost/babylon.berlin.s03e03.german.1080p.bluray.x264-intention.mkv', 
'/downloads/completed/Series/_UNPACK_Babylon.Berlin.S03E03.German.1080p.BluRay.x264-iNTENTiON-xpost/babylon.berlin.s03e03.german.1080p.bluray.x264-intention-forced.idx', 
'/downloads/completed/Series/_UNPACK_Babylon.Berlin.S03E03.German.1080p.BluRay.x264-iNTENTiON-xpost/babylon.berlin.s03e03.german.1080p.bluray.x264-intention.idx', 
'/downloads/completed/Series/_UNPACK_Babylon.Berlin.S03E03.German.1080p.BluRay.x264-iNTENTiON-xpost/babylon.berlin.s03e03.german.1080p.bluray.x264-intention-forced.sub', 
'/downloads/completed/Series/_UNPACK_Babylon.Berlin.S03E03.German.1080p.BluRay.x264-iNTENTiON-xpost/babylon.berlin.s03e03.german.1080p.bluray.x264-intention.sub']
```

**Comment by thezoggy** [comment]
Two rarsets, 1 in one and 4 in the other.. looks correct

**Comment by cphmichael** [comment]
After Berlin S03E03 is processed (Sonarr and SAB are idle) there are 5 files left in /completed
I have to manually delete the files from my SSD cache drive.

**Comment by Safihre** [comment]
SABnzbd is doing what it should be doing, it only extracted the 5 files that were expected. Previously there was an extra `xx (1).mkv` file, but that's not the case here.
It's Sonarr's job to pick it up and remove the rest of the files.

**Comment by cphmichael** [comment]
@thezoggy Thank you for you reply - I will insert idx, sub in the clean up list :-)
