### ISSUE TITLE
turning on Direct Unpack during download: errors, and ... "Completed"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1657]
During a download, I turned on Direct Unpack.
Result:
- missing rar files
- status "Completed", so I could not retry

I would be happier if
- the download would succeed, or
- the download would fail, and would say so, and I could click Retry, or
- I could not switch with a download / queue active

![image](https://user-images.githubusercontent.com/1273502/97101379-36cccc80-169d-11eb-9614-829a9e637328.png)

**Comment by Safihre** [comment]
Are you sure Direct Unpack did that? It doesn't create any `.2` files.. That's usually sign of a bad NZB or a bad repair by `par2`.

**Comment by sanderjo** [comment]
I'll do a fresh, uninterupted download to verify the NZB & download.
