### ISSUE TITLE
Python 3.5 support broke a little too early

### ISSUE THREAD

**Issue by GottemHams** [sabnzbd/sabnzbd#1658]
Judging from the release notes, SABnzbd 3.1.0 should still be compatible with Python versions below 3.6:
`Show warning that Pyton 3.5 support will be dropped after 3.1.0.`

However, commit a3ce436244f548e3561247aa911baa0b28a3748c introduced a problem when you're using SABnzbd over HTTPS in conjunction with (in my case) Python 3.5.3:
```
Traceback (most recent call last):
  File "/home/muhsabnzbd/sabnzbd/SABnzbd.py", line 1721, in <module>
    main()
  File "/home/muhsabnzbd/sabnzbd/SABnzbd.py", line 1275, in main
    trialcontext = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS_SERVER'
```

That particular attribute is only available in Python >= 3.6. :> For now I just commented out that last check so I can at least start my server, since I know for a fact that the cert is good.

**Comment by thezoggy** [comment]
Looks like we prob should just detect if it has attrib and fall back for 3.5


if hasattr(ssl, 'PROTOCOL_TLS_SERVER'):
            # python 3.6+
            protocol = ssl.PROTOCOL_TLS_SERVER
        elif hasattr(ssl, 'PROTOCOL_TLS'):
            # python 3.5.3+
            protocol = ssl.PROTOCOL_TLS
        else:
            # python 3.5.2
            protocol = ssl.PROTOCOL_TLSv1_2

**Comment by Safihre** [comment]
We can't just use `protocol = ssl.PROTOCOL_TLSv1_2` always for 3.1.0?

**Comment by thezoggy** [comment]
ssl.PROTOCOL_TLSv1_2 would be good for 3.4-3.6 but it's depreciate after that. (Protocol_tls replaced it)

**Comment by Safihre** [comment]
Seems `ssl.PROTOCOL_TLSv1_2` is still present in 3.8 and 3.9. We could just use it for now?

**Comment by thezoggy** [comment]
Sure
