### ISSUE TITLE
[Request] Restore UUEDECODE Support

### ISSUE THREAD

**Issue by LeeThompson** [sabnzbd/sabnzbd#1660]
I've run into a few binary posts in various groups that still use UUENCODING so it would be nice if there was _optional_ uudecode support in SABNZBd.

(Ran into one as recently as Oct 20 2020).

**Comment by Safihre** [comment]
Did you also have an NZB that we could use as a reference?

**Comment by sanderjo** [comment]
https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb%20uuencoded%201MB%204f77b411e66e.nzb

... but - from memory - the problem was multi-part or otherwise complicated uuencoded stuff. Therefore it was removed from SAB.

**Comment by Safihre** [comment]
Python 3 made it a bit less complicated. Indeed if @LeeThompson has a multi part example, that would be great.

**Comment by LeeThompson** [comment]
Attached, be advised it's adult in nature. 

[UUENCODED NZB.zip](https://github.com/sabnzbd/sabnzbd/files/5507142/UUENCODED.NZB.zip)

**Comment by sanderjo** [comment]
> Python 3 made it a bit less complicated. Indeed if @LeeThompson has a multi part example, that would be great.

Ah, OK, nice.

FWIW:

```
commit 35607d69e0f6169421302df84b079e7572dae5c4
Author: Safihre <safihre@sabnzbd.org>
Date:   Wed Apr 27 16:46:27 2016 +0200

    Drop support for UUencode and show notice when detected
    
    UUencode would only be interesting if we actually supported multipart-UUencode, but we don't.. Only the (never seen) singlepart one.
```

**Comment by sanderjo** [comment]
> Attached, be advised it's adult in nature.
> 
> [UUENCODED NZB.zip](https://github.com/sabnzbd/sabnzbd/files/5507142/UUENCODED.NZB.zip)

FWIW: I downloaded it with a certain other NZB downloader, and that downloader could handle it:

```
total 156936
drwxr-xr-x 2 root root     4096 nov  8 23:03 ./
drwxr-xr-x 3 root root     4096 nov  8 23:03 ../
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.001
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.002
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.003
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.004
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.005
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.006
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.007
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.008
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.009
-rw-r--r-- 1 root root 14976000 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.010
-rw-r--r-- 1 root root  5036376 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.011
-rw-r--r-- 1 root root     8484 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.par2
-rw-r--r-- 1 root root   392552 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.vol00+1.PAR2
-rw-r--r-- 1 root root   785028 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.vol01+2.PAR2
-rw-r--r-- 1 root root  1561572 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.vol03+4.PAR2
-rw-r--r-- 1 root root  3106252 nov  8 23:03 jade-7_three-akmts-and-a-akck.avi.vol07+8.PAR2
```

**Comment by puzzledsab** [comment]
@Safihre: What did you mean by Python 3 making it less complicated?

**Comment by zaadstra** [comment]
I second this request ;-)   I also need to download UU regularly.

For some examples, as @Safihre requested, this might be helpful:
https://docs.python.org/3/library/uu.html
https://github.com/bkiers/python3-parser/blob/master/src/test/python/cpython-3f944f44ee41/Lib/email/message.py
https://python.hotexamples.com/de/examples/uu/-/decode/python-decode-function-examples.html

Unfortunately I don't speak Pyhon, so I can only hope this helps ;-)
Here is a bunch of uuencoded examples: 
http://binsearch.info/?q=NEW-CTP-update&max=100&adv_age=1100&server=2
