### ISSUE TITLE
RFC: probablyipv4() and probablyipv6() to use module "ipaddress" instead of regexp?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1662]
In the past I have introduced probablyipv4() and probablyipv6(). See https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L845-L858

Inside those function: a regexp which probably works. Therefore the function name.

I could rewrite the functions to depend on the python module `ipaddress`, which can recognize addresses:

>>> import ipaddress
>>> ipaddress.ip_address('192.168.0.10').version
4
>>> ipaddress.ip_address('2001:db8::').version
6
>>> ipaddress.ip_address('blabla').version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'blabla' does not appear to be an IPv4 or IPv6 address
>>>

That would mean:
- extra module to import
- get rid of the regexps
- "probably" turns into "100% sure"

Comments? Useful? Worth it? @Safihre @jcfp

**Comment by Safihre** [comment]
Go ahead, it's already part of the standard library so no problem for extra import.
Write some unit tests so we can be sure it works for us.

**Comment by jcfp** [comment]
Seems to come with have nice methods to determine if an address is loopback, local, multicast, etc. Probably makes having a LOCALHOSTS definition in sabnzbd.constants obsolete as well.

**Comment by sanderjo** [comment]
> Seems to come with nice methods for determining if an address is loopback, local, multicast, etc. Probably makes having a LOCALHOSTS definition in sabnzbd.constants obsolete as well.

```
>>> ipaddress.IPv4Address('127.0.0.1').is_loopback
True

>>> ipaddress.IPv4Address('localhost').is_loopback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/ipaddress.py", line 1252, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.8/ipaddress.py", line 1144, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'localhost'
```


and

```
>>> ipaddress.IPv6Address('::1').is_loopback
True
>>> ipaddress.IPv6Address('::').is_loopback
False

```
