### ISSUE TITLE
Starting sabnzbd command env LANG=en_US.UTF-8 /volume1/@appstore/sabnzbd/env/bin/python3 /volume1/@appstore/sabnzbd/share/SABnzbd/SABnzbd.py -f /volume1/@appstore/sabnzbd/var/config.ini --pidfile /volume1/@appstore/sabnzbd/var/sabnzbd.pid -d  Not all required Python modules are available, please check requirements.txt Missing module: sgmllib You can read more at: https://sabnzbd.org/python3 If you still experience problems, remove all .pyc files in this folder and subfolders

### ISSUE THREAD

**Issue by ikkeenjij36** [sabnzbd/sabnzbd#1667]
After doing an update to 3.1.0 throught the synology package center i am getting the error as per title?
DO i have to start over and losse my db and start from scratch with the scripts and indexer sites and programs to replace the apikey agayn?
\

**Comment by Safihre** [comment]
There was a bug in the SynoCommunity package.
It's fixed now, you should get a new update soon and it will keep all your settings. 
https://github.com/SynoCommunity/spksrc/issues/4251
