### ISSUE TITLE
QR-code for SABnzbd's WebGUI?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1674]
Would this useful: SAB web interface showing a QR-co code for SABnzbd's WebGUI URL?

Use case: on my computer, I have access to SAB's webinterface, and it shows a QR code. With my phone, I would be able to scan that QR code to access SAB from my phone, to automatically open in the phone's webbrowser. It avoids finding out the the IP address / port and copy-pasting / typing it.

Mobile apps that communicate with SABnzbd (LunaSea?) could also build in a feature to scan the QR code. As SAB already can present the API key in a QR code, there might be apps that already have such a feature.

With https://www.qrcode-monkey.com/ I made two QR codes that work for SAB on my download box.

With LAN IP address:
<img src="https://user-images.githubusercontent.com/1273502/99144112-3b185400-2663-11eb-8e70-8ffb6390bdf3.png" width=30% height=30%>

With name, no IP address, which works on Android:

<img src="https://user-images.githubusercontent.com/1273502/99144115-3d7aae00-2663-11eb-964b-cac38399e66e.png" width=30% height=30%>

**Comment by Safihre** [comment]
We already have a QR library in sabnzbd, check out the button next to the API key in Config General.
So yes, we can easily use that. 
Where would we show it though?

**Comment by sanderjo** [comment]
> We already have a QR library in sabnzbd, check out the button next to the API key in Config General.
> So yes, we can easily use that.

Yes, indeed.

> Where would we show it though?

Frontpage?

**Comment by sanderjo** [comment]
@Safihre do we want this? 

I think we should only present the QR code if the SABnzbd Host is set to 0.0.0.0 or :: ... hey, another indicator to help users.

**Comment by Safihre** [comment]
Could you maybe provide a mockup where you think the icon should be shown?

**Comment by sanderjo** [comment]
Certainly ... two options. This works on my 14 inch screen, with my phone at about 10-12 cm from the screen

![image](https://user-images.githubusercontent.com/1273502/101992362-e6dcb000-3cb2-11eb-822b-fc849fe5a80c.png)

**Comment by jeffgeorge** [comment]
That seems a *little* excessive. *Maybe* put it on the first page of config?
