### ISSUE TITLE
"Badly formed yEnc article " => sabyenc3.decode_usenet_chunks() => Traceback "ValueError: Could not get filename"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1680]
I have 13 of these in a download:
```
2020-11-17 19:38:48,381::INFO::[decoder:196] Badly formed yEnc article in 0nvZ94ltl2OuxgGaEp84@9fhLz.cPg
Traceback (most recent call last):
  File "/home/sander/git/sjo-sab/sabnzbd/decoder.py", line 143, in run
    decoded_data = decode(article, raw_data)
  File "/home/sander/git/sjo-sab/sabnzbd/decoder.py", line 220, in decode
    decoded_data, yenc_filename, crc, crc_expected, crc_correct = sabyenc3.decode_usenet_chunks(raw_data, article.bytes)
ValueError: Could not get filename
```
Is that something decoder.py should try-except? 
Or should sabyenc3.decode_usenet_chunks() behave nicer?
Or ... leave it this way?

**Comment by Safihre** [comment]
This is on purpose, to track any errors in sabyenc when it was still in development. Now it would serve as a Debug purpose if users have issues, so we could move the Traceback to a Debug level.

**Comment by sanderjo** [comment]
do you want me to write the PR?

**Comment by Safihre** [comment]
I just would like to leave it like this :)
