### ISSUE TITLE
OS X menubar offset

### ISSUE THREAD

**Issue by Gothic860** [sabnzbd/sabnzbd#1683]
![Bildschirmfoto 2020-11-26 um 07 52 56](https://user-images.githubusercontent.com/3064815/100317442-a85daa80-2fbc-11eb-8656-9108d2cced65.png)

**Comment by Cpuroast** [comment]
I'm not seeing that odd download speed upward offset on: SABnzbd 3.1.1 running on macOS 10.15.7.

Do you have any more details?

**Comment by Gothic860** [comment]
3.1.1 [99b5a00]
macOS 11.0.1

**Comment by Cpuroast** [comment]
Ah, now that's helpful, so it's most likely an issue specifically with macOS 11 aka Big Sur.
I'll test in my Big Sur VM, see if I can reproduce it.

**Comment by Cpuroast** [comment]
Confirmed this SABnzbd UI glitch only occurs on macOS BigSur.
It does not occur on any other versions from 10.9 through 10.15.
