### ISSUE TITLE
Crash in rar-renamer when there is no first rar-file

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1687]
Triggered by:

- https://www.reddit.com/r/SABnzbd/comments/k2syxt/please_help_download_failed/
- https://forums.sabnzbd.org/viewtopic.php?f=2&t=25018

If a rar-set is fully obfuscated, but is missing the first rar-file (`part001`), post-processing wil crash.
Reproducers:
- Delete the files `tests\data\obfuscated_two_rar_sets\3b7d77bc-b95d-45b9-bb25-22b156d4ffef` and `tests\data\obfuscated_two_rar_setsaaffd55d-5282-4497-a52e-894181dd7531` and run the `test_rar_renamer` unit-test.
- [reftestnzb_100MB_obfuscated_rars_rar-only_missing_first_rar_bf1664007a71.zip](https://github.com/sabnzbd/sabnzbd/files/5615547/reftestnzb_100MB_obfuscated_rars_rar-only_missing_first_rar_bf1664007a71.zip)

**Comment by sanderjo** [comment]
I'll write a nice rar-set pre-checker, that avoids tracebacks, and gives a nice warning if the rar-set is incorrect.

**Comment by jcfp** [comment]
> If rar # 3 is missing completely, can SAB repair stuff? I think not.

Why not? Par2 can handle missing files.

**Comment by sanderjo** [comment]
> Why not? Par2 can handle missing files.

It depends on the redundancy in the par2 files. Anyway: I've written the code that in case of one rar set, I do renaming, and so SAB can try to par2 and then unrar.

**Comment by Safihre** [comment]
@jcfp the Rar renamer code is only executed when the full NZB is obfuscated and we can't find any par2 files (which we search for by first bytes signature).
