### ISSUE TITLE
Linux: "Out of memory: Killed process 2922 (sabnzbdplus)"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1690]
Wow, this is weird: my Linux killed sabnzbdplus (and only sab) because of Out of Memory.

System has 4GB RAM. Python is 3.8.5
SAB Downloads were behaving wobbly around 23:20, but sabnzbd.log says "Queue finished" at 23:20, and the OoM kill at 00:10. So the downloads were finished for quite some thing when Linux detected sab was using too much memory.

`Out of memory: Killed process 2922 (sabnzbdplus) total-vm:3193576kB, anon-rss:1172284kB, `

total-vm:3193576kB = 3GB.
anon-rss:1172284kB = 1GB

Is that too much memory @jcfp ?

Oh, this looks bad:
`Free swap  = 0kB
`

I'll restart the machine, and see if I can reproduce.

```
Dec  2 00:10:29 brixit kernel: [190714.727953] 92186 total pagecache pages
Dec  2 00:10:29 brixit kernel: [190714.727956] 27014 pages in swap cache
Dec  2 00:10:29 brixit kernel: [190714.727957] Swap cache stats: add 2858854, delete 2831840, find 8494283/9397690
Dec  2 00:10:29 brixit kernel: [190714.727958] Free swap  = 0kB
Dec  2 00:10:29 brixit kernel: [190714.727958] Total swap = 2097148kB
Dec  2 00:10:29 brixit kernel: [190714.727959] 999882 pages RAM
Dec  2 00:10:29 brixit kernel: [190714.727959] 0 pages HighMem/MovableOnly
Dec  2 00:10:29 brixit kernel: [190714.727960] 41000 pages reserved
Dec  2 00:10:29 brixit kernel: [190714.727960] 0 pages cma reserved
Dec  2 00:10:29 brixit kernel: [190714.727961] 0 pages hwpoisoned
Dec  2 00:10:29 brixit kernel: [190714.727962] Tasks state (memory values in pages):
Dec  2 00:10:29 brixit kernel: [190714.727962] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
Dec  2 00:10:29 brixit kernel: [190714.728156] [   2922]  1000  2922   798394   293071  2805760     5777             0 sabnzbdplus
Dec  2 00:10:29 brixit kernel: [190714.728470] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/sabnzbdplus.service,task=sabnzbdplus,pid=2922,uid=1000
Dec  2 00:10:29 brixit kernel: [190714.728538] Out of memory: Killed process 2922 (sabnzbdplus) total-vm:3193576kB, anon-rss:1172284kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:2740kB oom_score_adj:0
Dec  2 00:10:29 brixit kernel: [190714.845842] oom_reaper: reaped process 2922 (sabnzbdplus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB


```

**Comment by jcfp** [comment]
Sab is only using just over 1 GB according to that log entry; unfortunately, the info on the other processes and their memory stats was removed so one cannot really tell what was going on. Note that the oom-killer uses a scoring mechanism that takes into account more than just memory usage, so the process getting culled may not be the root cause of the problem.

**Comment by sanderjo** [comment]
OK, thanks. The syslog did show other processes ... which were not using too much memory, but less than SAB.

I could not reproduce with the NZBs, so I'm closing this.

**Comment by 4np** [comment]
Sounds familiair to my experiences in #1665

**Comment by sanderjo** [comment]
> Sounds similar to my experiences in #1665

It's only Out-of-Memory if /var/log/syslog says so: `Out of memory` and/or `oom-kill`

If not, it's not an out-of-memory
