### ISSUE TITLE
Exit(-1) Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh

### ISSUE THREAD

**Issue by LennyM8472** [sabnzbd/sabnzbd#1694]
Describe the bug
Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh

Technical Specs

Running on (Windows, Linux, NAS Model etc) QNAP QTS 5.4
Python version Python 3
Download Client (NZBget, SABnbzd, Transmission) SABnbzd
Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) Radarr

Hi,

I have a really strange problem:

upfront, for executing the script for SickChill everythings runs smooth with the setup of nzbToMedia.

Upon completion of a Radarr download with Sabnzbd and running the nzbToRadarr script (via the bash script nzbToMedia/nzbToRadarr.sh to access python3)
#!/bin/bash /opt/QPython3/bin/python3 /share/Applications/nzbToMedia/nzbToRadarr.py "$@"

I receive the follwoing error in Sabnzbd

Exit(-1) Cannot run script /share/Applications/nzbToMedia/nzbToRadarr.sh

The strange thing is that running the script nzbToRadarr.sh with ssh works perfectly fine

I have no clue why sabnzbd can't run script. Any ideas?

All script files have 777 or 757 permissions.

Best regards
Lenny

**Comment by sanderjo** [comment]
`#!/bin/bash /opt/QPython3/bin/python3 /share/Applications/nzbToMedia/nzbToRadarr.py "$@"`

You start bash, to start python3, to start a python script?

... what if you leave out the bash part?

**Comment by LennyM8472** [comment]
yes I use the the script because python still runs python2.

The thin is that I use exactly the same code for the SickBeard script and everything works perfectly with Sabnzbd.


Here the terminal output:
`/opt/QPython3/bin/python3 /share/Applications/nzbToMedia/nzbToRadarr.py "$@"
Changing to directory: /share/CE_CACHEDEV2_DATA/Applications/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean`

Here the terminal output:
`[~] # /share/Applications/nzbToMedia/nzbToRadarr.py "$@"
Changing to directory: /share/CE_CACHEDEV2_DATA/Applications/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /root

-- Cleanup finished --

[11:46:56] [INFO]::MAIN: Loading config from [/share/CE_CACHEDEV2_DATA/Applications/nzbToMedia/autoProcessMedia.cfg]`

**Comment by Safihre** [comment]
Can you switch logging to +Debug and try again, it will show a traceback before the `Cannot run script` part in the logs.

**Comment by LennyM8472** [comment]
> Can you switch logging to +Debug and try again, it will show a traceback before the `Cannot run script` part in the logs.

where do I find the option?

**Comment by Safihre** [comment]
In the Status and Interface settings window, the Wrench icon in the menu.

**Comment by LennyM8472** [comment]
> In the Status and Interface settings window, the wrench icon in the menu.

ahhh, I was looking for something like that for ages.

**Comment by LennyM8472** [comment]
ok, so it says the file does not exist.... but it does:

Log:
`2020-12-08 11:09:45,033::DEBUG::[newsunpack:227] Failed script /share/Applications/nzbToMedia/nzbToRadarr.sh, Traceback: 
Traceback (most recent call last):
  File "/share/CE_CACHEDEV2_DATA/.qpkg/QSabNZBd3/SABnzbd/sabnzbd/newsunpack.py", line 201, in external_processing
    p = build_and_run_command(command, env=create_env(nzo, extra_env_fields))
  File "/share/CE_CACHEDEV2_DATA/.qpkg/QSabNZBd3/SABnzbd/sabnzbd/misc.py", line 988, in build_and_run_command
    return subprocess.Popen(command, **popen_kwargs)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/QSabNZBd3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/share/CE_CACHEDEV2_DATA/.qpkg/QSabNZBd3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/share/Applications/nzbToMedia/nzbToRadarr.sh': '/share/Applications/nzbToMedia/nzbToRadarr.sh'`

Terminal file:
`[~] # cd /share/Applications/nzbToMedia/
[/share/Applications/nzbToMedia] # ls
autoProcessMedia.cfg*       _config.yml*   license.txt*          nzbToLazyLibrarian.py*  nzbToMedia.sh*     nzbToSickBeard.py*  TorrentToMedia.py*
autoProcessMedia.cfg.old*   core/          logs/                 nzbToLazyLibrarian.sh*  nzbToMylar.py*     nzbToSickBeard.sh*  tox.ini*
autoProcessMedia.cfg.spec*  eol.py*        nzbToCouchPotato.py*  nzbToLidarr.py*         nzbToNzbDrone.py*  nzbToWatcher3.py*
azure-pipelines.yml*        getffmpeg.sh*  nzbToGamez.py*        nzbtomedia.db*          nzbToRadarr.py*    setup.py*
cleanup.py*                 libs/          nzbToHeadPhones.py*   nzbToMedia.py*          nzbToRadarr.sh*    tests/`

**Comment by thezoggy** [comment]
usually an indication of permission issues

**Comment by LennyM8472** [comment]
> usually an indication of permission issues

I agree, but I have checked and reapplied 777 permissions for the folder and all files.

So frustrating.

**Comment by thezoggy** [comment]
what about the env / user+group the app runs as compared to the user/group that the file+folders are using
