### ISSUE TITLE
Windows: Download stops while starting to unrar

### ISSUE THREAD

**Issue by realtobman** [sabnzbd/sabnzbd#1698]
When the program completes the articles for the first file, it starts to unrar but is stuck not downloading more data for about 30 seconds.
Lets say the data has 30 split files, the first 15 are loaded, and immediately when rar no. 1 completes, it starts with the unrar process. The symbol for unpacking is displayed in the main section next to the release name like this: 1/30 unraring. For 30 to 40 seconds, nothing happens but the graph keeps on showing the constant speed of the last download like a flat line as if it were still loading.
Suddenly it continues to unrar and download the data for real.

It had not this behaviour in version 3.01 but since  3.11 it is definetly there.

**Comment by Safihre** [comment]
Seems like sabnzbd is crashing or being blocked by virusscanner etc. Could you enable Debug logging in the Status and Interface settings window and then after it happens again right away click Show Logging in the same window. If you could share the log file here (as an attachment) or through pastebin?

**Comment by realtobman** [comment]
Stopping Download while the first part completes and unrars : 
with debug log active was on 2020-12-15 17:09:52.

Thanks for replying and looking into it.

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5697105/sabnzbd.log)

**Comment by Safihre** [comment]
That is strange.
Could you try and see if it makes a difference if you disable Unwanted Extensions in Config Switches? Just remove the items you have listed.
And also, what happens when you try to shutdown SABnzbd through the SABnzbd interface? Does it work?
Does it print anything more in the debug log? Maybe Unrar output?
