### ISSUE TITLE
Radarr 3.0.0.4204 on Windows makes SABnzbd (with self-signed HTTPS) unreachable

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1700]
As more users are experiencing this, I'm creating an issue:

With 

- Radarr 3.0.0.4204 on Windows, and
- SABnzbd (on any OS) with HTTPS with self-signed certificate

... SABnzbd will spew out a few Tracebacks (`TLSV1_ALERT_UNKNOWN_CA` or `SSLV3_ALERT_CERTIFICATE_UNKNOWN`) and will eventually become unreachable.

Workarounds/ Solutions:

- in Radarr 3.0.0.4204: in Settings > General > Security -> "Certificate Validation" set to "Disabled for Local Addresses" (or "Disabled" if Radarr and SAB are on different devices), or
- in SABnzbd, turn off HTTPS and use HTTP (change accordingly in Radarr), or
- Hard: use a real certificate in SABnzbd (for example letsencrypt), or export the self-signed certificate to the operating system running Radarr

Background / Causes:

- Radarr https://github.com/Radarr/Radarr/issues/5512#issuecomment-740189675
- Cherrypy / cheroot https://github.com/cherrypy/cheroot/issues/346#

So: causes both outside SABnzbd itself. I think not much we can do about this ... unless SABnzbd could see the Tracebacks, give an explanation/warning, and pre-emptively restart cherrypy to avoid becoming unreachable

**Comment by Safihre** [comment]
Seems they fixed it in cheroot, so I'll remove the lock on older cheroot.
