### ISSUE TITLE
REQUEST: keep original priority of 'paused' duplicate jobs?

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1702]
Hi all. :)

Whenever my SAB 3.1.1. identifies a duplicate job, it is assigned a 'normal' priority, even when that category of job would usually get a 'high' priority. 

I'm guessing the duplicate job detector runs before any category filtering. 

Is there a way to keep the correct job priority? (with the possible exception of 'forced' jobs. 😉  )

Cheers!

**Comment by Safihre** [comment]
Can you check if it works as expected? 💯

**Comment by OneCDOnly** [comment]
Yup, works great! 👍🏽 

Thanks @Safihre.
