### ISSUE TITLE
Discussion about asyncio rewrite

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1709]
Continuation of the asyncio discussion from #1704

I've actually tried writing a very basic asyncio based usenet article downloader a while ago. Just fetching multiple articles concurrently, nothing else. It worked and had a low CPU load, but the problem is that so much in Sab is written around looping, async polling and using the results of those polls on each iteration. Switching to asyncio would require some big rewrites. You should probably freeze the development for everything except vital fixes in the mean time because lots of it won't be reusable.

I can clean it up a little and post it somewhere if you're interested. Currently it doesn't even support login because I used the free IPv6 server.

**Comment by Safihre** [comment]
Yes, absolutely a big rewrite is needed. But that doesn't have to be a problem, for Python 3 conversion we also didn't release for a long time to get things right.
The current code is based on principles from back in Python 2.5 or even earlier times. You can see it when you do a git blame, so much code from 10 years ago. So a big refresh is worth it.

**Comment by puzzledsab** [comment]
I made it work with SSL and login. For me it doesn't seem to use less CPU than Sab currently does, even with no decoding and extra logic. Maybe there's nothing to gain from it? Here's the test downloader I wrote: https://gist.github.com/puzzledsab/3605240541ee7cf2bb0eae962ba91182

It reads a list of articles from articles.txt, like this one: https://gist.github.com/puzzledsab/88fdf61c1d9a6607b24cae89e92db578

**Comment by Safihre** [comment]
Does it run concurrently?
I would imagine it can show its strength when decoding is included, since this way each server thread can also be a decoder thread, so many more at once can be active.

**Comment by puzzledsab** [comment]
Yes, you can set the number of connections using the threads variable. I think the decoding would run as separate jobs using asyncio, to avoid delays between requests for new articles. Regarding decoding, couldn't there be more decoder threads with the current version as well? I assume CPUs with many cores could benefit from it.

**Comment by mnightingale** [comment]
> I made it work with SSL and login. For me it doesn't seem to use less CPU than Sab currently does, even with no decoding and extra logic. Maybe there's nothing to gain from it? Here's the test downloader I wrote: https://gist.github.com/puzzledsab/3605240541ee7cf2bb0eae962ba91182
> 
> It reads a list of articles from articles.txt, like this one: https://gist.github.com/puzzledsab/88fdf61c1d9a6607b24cae89e92db578 You need to configure a server and login in main().

@puzzledsab It's been a long time but I wondered if you happen to have these two gists anywhere the links are dead.

**Comment by puzzledsab** [comment]
@mnightingale : Sorry, I missed your message. I'm not sure but I think the script was this file: https://gist.github.com/puzzledsab/7d6277e82bd1b53d4b8a251ae6a0e443. You fill in the connection info in main().

I don't have the articles.txt file it reads so I haven't tested it but you can generate one easily. It's just a text file with one article ID (without <>) on each line.

**Comment by mnightingale** [comment]
No worries, I did manage to put something together that kind of works, but it was way slower so I concluded asyncio wasn't a good fit.

I did notice that the streamreader could read >16KB at a time, I think it's related to use of [Memory BIO](https://docs.python.org/3/library/ssl.html#memory-bio-support) so I have been meaning to investigate that as an alternative to the unlocked ssl stuff however at the time I could barely find any information about it.
