### ISSUE TITLE
Glitter skin queue/history item removal fade out time is too long

### ISSUE THREAD

**Issue by RulerOf** [sabnzbd/sabnzbd#1710]
Followup on [this reddit discussion](https://www.reddit.com/r/SABnzbd/comments/kgtl8l/any_improved_version_of_the_glitter_skin/).

The "fade out" animation when removing items from the history or queue makes removing more than one or two entries very tedious. This fade should be shorter.

I think the maximum duration should be no more than 250ms. **I suggest 100ms or 167ms** as a sweet spot. A subjective test would be to delete ~20 items from history one-by-one and just see if it takes too long to do.

**Comment by Safihre** [comment]
Just removed the whole fading, not really adding anything usefull.
