### ISSUE TITLE
sabnzbd interface

### ISSUE THREAD

**Issue by daVe55w** [sabnzbd/sabnzbd#1712]
I can't get the SABNZBD interface to appear today. The page displays ERR_SSL_PROTOCOL_ERROR. I just reinstalled it and same problem. Using MS Edge Version 89.0.739.0 (Official build) canary (64-bit) with Win 10 Pro.

**Comment by thezoggy** [comment]
You should share logs and more details.. hard to guess what a generic message like that may mean without the context.

I'm going to guess it's just warning about your sab cert.. if so just update it.

**Comment by daVe55w** [comment]
How do I identify the sab certificate and update it?

**Comment by Safihre** [comment]
Try using a different browser, in the Config window you can hit the refresh button next to the certificate files to generate new ones.

**Comment by Safihre** [comment]
Actually, I see now that if I visit SABnzbd throught HTTPS while SABnzbd doesn't have HTTPS enabled, you get this exact error.
So try visiting SABnzbd _without_ https.

**Comment by daVe55w** [comment]
Different browsers had the same issue. Accessing SABnzbd without https:// yields a completely blank page.

Is there a windows service for the SABnzbd app that is supposed to start with it? If so, and it's not, that would be the problem.

**Comment by Safihre** [comment]
I'm not sure what you mean. But it seems you are on Windows, so sabnzbd runs on your local machine?
If so, you can just restart Sabnzbd in safe mode from the the Start menu, where it will reset the settings to 127.0.0.1:8080. You can try that.
Or, if you see the sabnzbd icon in the tray, just double click it and it will open the web interface.

**Comment by daVe55w** [comment]
Does anyone know if SABnzbd is dependent on certain services running in Windows (10 Pro)? I am not able to access the SABnzbd web interface across various browsers (Edge, Chrome, Firefox). The program is running as evidenced by its taskbar icon. Just the web interface does not work. Running in Safe Mode has the same result. Selecting Show Interface on the taskbar icon brings up the same blank web page.

**Comment by Safihre** [comment]
No services are needed.
Have you tried rebooting your pc? 
Otherwise we have to try this:
https://sabnzbd.org/wiki/faq#freshstart

**Comment by daVe55w** [comment]
PC has been rebooted multiple times.
Strangely, NZBGet works fine. I installed it as a test and no problem with its web interface. However, d/l with it is much slower than SAB. I'll take a look at the Wiki.

**Comment by Safihre** [comment]
Another alternative is that your installation got corrupted, so a reinstall could work.

**Comment by daVe55w** [comment]
Tried reinstalling before. This time I uninstalled including the settings, rebooted, reinstalled, and it's working now. Thank you.
