### ISSUE TITLE
Add a warning/disclaimer to "Enable accessing the interface from a HTTPS address."

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1713]
Proposal:

Add a warning/disclaimer to "Enable accessing the interface from a HTTPS address." like

"Note: Modern web browsers and other clients will not accept self-signed certificates and will give a warning and/or won't connect at all. So only activate HTTPS if you know what you're doing."

Rationale: more and more users are reporting problems with Chrome and Edge. Furthermore, Radarr 3.0.0.x by default does not accept self-signed, and throws an error.

![image](https://user-images.githubusercontent.com/1273502/102886310-2a72af00-4455-11eb-88aa-2f3f9bd95a84.png)

**Comment by Safihre** [comment]
Sounds good, go ahead!

**Comment by sanderjo** [comment]
@shypike How about this?

![image](https://user-images.githubusercontent.com/1273502/102915677-7556eb80-4482-11eb-96e0-7baeeca82d38.png)

**Comment by Safihre** [comment]
Sure!
