### ISSUE TITLE
SABnzbd web interface blank page

### ISSUE THREAD

**Issue by daVe55w** [sabnzbd/sabnzbd#1717]
Does anyone know if SABnzbd is dependent on certain services running in Windows (10 Pro)? I am not able to access the SABnzbd web interface across various browsers (Edge, Chrome, Firefox). The program is running as evidenced by its taskbar icon. Just the web interface does not work. Running in Safe Mode has the same result, a blank web page. Selecting Show Interface on the taskbar icon also opens a blank web page.

**Comment by Safihre** [comment]
Why are you opening multiple issues?
