### ISSUE TITLE
python tools/make_mo.py error

### ISSUE THREAD

**Issue by iljarogoff** [sabnzbd/sabnzbd#1719]
running sabnzbd 3.1.1. on debian10.
in general settings, the language dropdown was empty. so I did a 'python tools/make_mo.py' in the /opt/sabnzbd folder, giving me this output:

> /opt/sabnzbd # python tools/make_mo.py
> Email MO files
> Compile locale/ru/LC_MESSAGES/SABemail.mo
> Compile locale/sv/LC_MESSAGES/SABemail.mo
> Compile locale/es/LC_MESSAGES/SABemail.mo
> Compile locale/en/LC_MESSAGES/SABemail.mo
> Compile locale/he/LC_MESSAGES/SABemail.mo
> Compile locale/nb/LC_MESSAGES/SABemail.mo
> Compile locale/ro/LC_MESSAGES/SABemail.mo
> Compile locale/da/LC_MESSAGES/SABemail.mo
> Compile locale/cs/LC_MESSAGES/SABemail.mo
> Compile locale/fr/LC_MESSAGES/SABemail.mo
> Compile locale/pl/LC_MESSAGES/SABemail.mo
> Compile locale/zh_CN/LC_MESSAGES/SABemail.mo
> Compile locale/pt_BR/LC_MESSAGES/SABemail.mo
> Compile locale/de/LC_MESSAGES/SABemail.mo
> Compile locale/fi/LC_MESSAGES/SABemail.mo
> Compile locale/nl/LC_MESSAGES/SABemail.mo
> Compile locale/sr/LC_MESSAGES/SABemail.mo
> Create email templates from MO files
> Create email template for he
> Traceback (most recent call last):
>   File "tools/make_mo.py", line 297, in <module>
>     make_templates()
>   File "tools/make_mo.py", line 217, in make_templates
>     translate_tmpl("email", lng)
>   File "tools/make_mo.py", line 193, in translate_tmpl
>     with open(EMAIL_DIR + "/%s-en.tmpl" % prefix, "r", encoding="utf-8") as src:
> TypeError: 'encoding' is an invalid keyword argument for this function

now i have languages in my dropdown, but changing them does not affect sabnzbd
any idea where my failure is?

**Comment by Safihre** [comment]
`python` = Python 2 probably!
