### ISSUE TITLE
Text Alignment on Menu Bar Status

### ISSUE THREAD

**Issue by pushkatel** [sabnzbd/sabnzbd#1722]
Not sure if this is a known issue or not. But I think it started when I updated to Big Sur. Essentially, the status text in the menu bar during a download is not aligned. The time remaining gets cut off. 

I am running 11.1 Big Sur on a Mid 2015 15" MacBook Pro.
<img width="281" alt="Screen Shot 2020-12-19 at 12 02 42 AM" src="https://user-images.githubusercontent.com/10911227/103177054-7ef2a180-483c-11eb-81d6-c4e31d3d6c94.png">

**Comment by Safihre** [comment]
Will be fixed in next release 😊 #1683

**Comment by DaveFlowberries** [comment]
I have the same issue Monterey 12.1 on 14 inch Macbook Pro. When connected to an external monitor it gets cut off 
<img width="169" alt="Screen Shot 2022-01-14 at 11 12 33 PM" src="https://user-images.githubusercontent.com/25303159/149538901-0d131278-9533-4e60-a6d6-ac88ff81ff6c.png">

Without a external monitor it's not cut off, but it is smashed up towards the top of the menu bar. 
<img width="99" alt="Screen Shot 2022-01-14 at 11 12 44 PM" src="https://user-images.githubusercontent.com/25303159/149539065-76f4a106-b3b4-40d3-a946-e00c95de0c66.png">
