### ISSUE TITLE
incorrect claim of rar-based verification in job history

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#1737]
I noticed a weird line in the history of a job with only a single, non-obfuscated mp3 file, probably caused by [postproc.py:890-892](https://github.com/sabnzbd/sabnzbd/blob/764f7df6a788e5be14a408385c233a29928896fe/sabnzbd/postproc.py#L890-L892) unconditionally claiming rar-based verification is being tried whenever `rar_renamer` gets called, even though that function doesn't actually do any such thing.

For jobs with no par2 and no rar files at all, the resulting "Trying RAR-based verification" line is incorrect, confusing, and nonsensical, given that there are no rar files to verify against and the actual rar-based verification code (in `try_rar_check`, from where the relevant lines seem to have been copied verbatim) never runs. Meanwhile, I suspect (but didn't test) that for jobs that actually make good use of both the rar renamer and rar-based verification code the same line will appear in the history twice.

It was tempting to simply delete the offending lines...

**Comment by Safihre** [comment]
It says `Trying` 😁

**Comment by jcfp** [comment]
True, but I does that while it's actually trying the rar renamer, not the verification. I guess that was done to save an extra translation?

**Comment by Safihre** [comment]
Yes, that's mostly it..

**Comment by jcfp** [comment]
Willing to accept a pr with an extra translation or should a close this one?

**Comment by Safihre** [comment]
Sure, we can add a translation.
