### ISSUE TITLE
3.1.1 - missing close icon

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1740]
missing icon / cant close out

firefox 84.0.1:
![sab](http://zoggy.net/firefox_2021-01-03_18-15-47.png)

chrome 87.0.4280.88 (cleared cookies/cache, so no horz tab layout):
![sab2](http://zoggy.net/chrome_2021-01-03_18-17-44.png)

**Comment by Safihre** [comment]
There never was a close icon for the update notice, that's by design :)

**Comment by thezoggy** [comment]
Then we shouldn't have the mouse hover change as if there should be then. As it makes you think the icon is just missing
