### ISSUE TITLE
SSDP-listener

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1742]
SAB 3.2.0 broadcasts itself via SSDP. See release notes: "Using SSDP, SABnzbd instances are now listed in Network on Windows.". Technical: NOTIFY message

I would like to build a SSDP listener. Reason: some apps don't listen to broadcasts and only rely on a send-expect sequence ... to which SAB should listen (technical: M-SEARCH) & respond.

So ... there must be process always listening to 239.255.255.250 port 1900. I see a few options:
1. in SSDP,py instead of the time.sleep() https://github.com/sabnzbd/sabnzbd/blob/1a4ba51dec9184bedf828f39885e5cc00cd516a1/sabnzbd/utils/ssdp.py#L126 ... build the listen&respond until the interval-time has elapsed
2. in the existing SSDP.py, start a separate Threading thread to do the listen&responds
3. ... create a complete new, separate class (just like SSDP), with a name like ssdp_listen

To me 1 seems ugly. 2 looks better (but help needed how to do that). 3 looks not logical & too heavy

**Comment by Safihre** [comment]
And, how do we cope with devices that already have a SSDP listener? 
Like Synology and QNAP devices?

**Comment by sanderjo** [comment]
> And, how do we cope with devices that already have a SSDP listener?
> Like Synology and QNAP devices?

SAB should register via that existing service. In case of minissdpd (on Synolgy, I don't know about QNAP): it should be doable, but the devil is in the details. See https://miniupnp.tuxfamily.org/forum/viewtopic.php?p=5596
