### ISSUE TITLE
Make "Use global interface settings" save all the options

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1759]
I saw #1475, but it's a bit unclear if it's like that because that's what you want or because you don't think it's important. Is it ok if I try to change it so that everything on that page is persistent if "Use global interface settings" is chosen?

**Comment by Safihre** [comment]
As mentioned it's like that to be able to have different settings on your tablet than on your desktop for example. But technically they could just all be remembered of course, although I would like maybe to store the other settings as one json object instead of seperate settings for each.

**Comment by puzzledsab** [comment]
Done.
