### ISSUE TITLE
Prequeue script setting removed after upgrading to 3.2.0Beta2 from 3.2.0Beta1

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1766]
Thanks for the great upgrade. 

I use SABnzbd on Windows 10 pro 64 and upgraded  to 3.2.0Beta2 from 3.2.0Beta1. Afterwards I had a very minor issue. The selection of the prequeue script in Settings - Switches - Queue - Pre-queue user script was reset to no script. Selecting 
the script that I normally use and saving the selection solved the issue.

**Comment by Safihre** [comment]
@jcfp sounds like the validity check going wrong?
@ErikBrown2 what if you restart again, does it stick?

**Comment by ErikBrown2** [comment]
No, after a restart the prequeue script setting is cleared again.

**Comment by jcfp** [comment]
Looks like the validation function in cfg.py is the problem. Not sure on the why though...

**Comment by Safihre** [comment]
@jcfp At startup, when reading the config file `script_dir` isn't defined yet when reading the `pre_queue` setting. So the check fails and the value isn't loaded.
Unfortunately we can't do the check at startup, only when a new value is saved.

**Comment by jcfp** [comment]
Alas. For now, I'll patch beta2 on the ppa to neutralise that check and call it a night.

**Comment by ErikBrown2** [comment]
Considering that the prequeue script will not be running after a restart, why don't you upgrade the current beta2? Still call it beta2 but have the script issue fixed?

**Comment by Safihre** [comment]
I don't consider it such a breaking issue, that's just a thing that can happen with test releases.
I'll release a Beta 3 or RC 1 in a few days.
