### ISSUE TITLE
sabnzbd does not proper free allocated memory

### ISSUE THREAD

**Issue by Hubfront** [sabnzbd/sabnzbd#177]
The python process seems to keep allocated memory, even after all jobs are fully downloaded and processed and sabnzbd is idle. This behaviour is problematic on Nas machines with rather small amounts of Ram. I use a DS214play with 1GB Ram and a DS214 with 512 MB Ram.

Sabnzbd should instantly free allocated memory when it's not needed anymore.

**Comment by shypike** [comment]
Duplicate of  #439
