### ISSUE TITLE
3.2.0Beta2 won't run on my Windows 7x64 machine. 

### ISSUE THREAD

**Issue by DrakeJones** [sabnzbd/sabnzbd#1770]
3.2.0Beta2 won't run on my Windows 7x64 machine. 3.1.1 is fine.

After install trying to run or start service yields the following error msg.

"The Program can't start because api-ms-win-core-path-|1-1-0.dll is missing form your computer.  Try reinstalling the program to fix this problem."

**Comment by sanderjo** [comment]
Also https://forums.sabnzbd.org/viewtopic.php?f=11&t=25172&p=123463#p123463 

Out of curiosity: why do you use Win7, and not Win10?

**Comment by DrakeJones** [comment]
For privacy.  Windows "as a service" 10 is a data-miner front.  It's not really free - your personal data is the currency you lease it with.  I really resent MS for that.  Windows 10 "Ameliorated" (spyware removed)  is available [https://ameliorated.info/](url) but functionality is crippled badly.  I also run a Linux box.  If you don't plan to support Windows any longer, I'll stick with 3.1.1.  SABnzbd is my preferred downloader.

**Comment by Safihre** [comment]
I build the 32bit version with Python 3.8. Could you see if that works on Windows 7?
https://github.com/sabnzbd/sabnzbd/actions/runs/514800684

If that works, I can keep it that way as the legacy version to support non-64bit and Windows 7 systems.

**Comment by DrakeJones** [comment]
The installer is looking for the python39.dll - fails.

**Comment by Safihre** [comment]
No, not the installer. You'll need to use the standalone version `Windows Windows standalone binary (32bit and legacy)`.

**Comment by sanderjo** [comment]
> The installer is looking for the python39.dll - fails.

You need the "Windows standalone binary (**32bit and legacy**)"

**Comment by DrakeJones** [comment]
Okay.  That works.  Thanks.

**Comment by 1ColdAssHonkey** [comment]
Thank you Safihre for this customized legacy build.  I am in the exact boat as DrakeJones is and was having the same issue.  The standalone version works great for me too.   Just one question, why a 32-bit build?  Is it to make it accessible to more legacy systems than a 64-bit?  Thank you again for the program!

**Comment by Safihre** [comment]
@1ColdAssHonkey indeed, to make it available for all non-standard systems. There is almost no difference between 32 and 64bit in terms of performance etc :)

**Comment by 1ColdAssHonkey** [comment]
Great to hear.  Thank you for all the hard work.  You guys make a GREAT product!

    On Friday, January 29, 2021, 10:32:05 PM PST, Safihre <notifications@github.com> wrote:  
 
 


@1ColdAssHonkey indeed, to make it available for all non-standard systems. There is almost no difference between 32 and 64bit in terms of performance etc :)

**Comment by antdude** [comment]
I'm having the same problem with 64-bit v3.2.0 portable (https://github.com/sabnzbd/sabnzbd/releases/download/3.2.0/SABnzbd-3.2.0-win64-bin.zip) in my over decade old, updated 64-bit W7 HPE SP1 PC. :( 

https://github.com/sabnzbd/sabnzbd/releases/download/3.2.0/SABnzbd-3.2.0-win32-bin.zip worked. It would had been nice if both the software (installers if used, but I don't use them) and web site say to use the old 32-bit version for old 64-bit W7 HPE SP1. :/

**Comment by Safihre** [comment]
The installer will show a nice error when you try to run them on these old systems, to use the legacy/32bit version.
The changelog also mentions the dropped support for old Windows systems.

**Comment by thezoggy** [comment]
Win7 SP1 came out - February 9, 2011; so over 10 years ago!

As you are aware many things work just fine on such outdated os if you are willing to accept the lack of security or stability updates. However, most installers let alone python have dropped support. This is outside sab's control so we have to purposely make a special build using outdated software to sidestep that issue...  this is only a short term thing as the need for a 32 bit build is largely unneeded and we are using this as a hacky solution to provide a build using older python/builder to keep legacy os support. This probably will end in the near future as more and more things go against us as more dependencies stop supporting win7 and older (for example win rar/par stop supporting win7 and older).

Honestly you might be best off just controlling the dependencies yourself by running sab from source, that way you dont rely on our installer (and by proxy, what version of python we build off of). But really if that machine is connected to the internet you should upgrade to a newer os for security sake :)

**Comment by DrakeJones** [comment]
Thank you very much for the legacy side build (for as long it lasts).  Point(s) taken.  Funny thing, I live in Italy and it was only about 4 or 5 years ago that the local ATMs were upgraded from XP to Windows 7!  At least I have gigbit internet in a 600 year old building. ;-)

**Comment by thezoggy** [comment]
an "appliance" is a bit different than a general purpose desktop os. but yeah, plenty of <appliances/iot/smart-tv/whatever> out there running old os with old applications :)
