### ISSUE TITLE
disable - bonjour/zeroconf/SSDP

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1777]
There are plenty of scenarios that people would NOT want to broadcast the fact they are running sabnzbd across their network.
We should offer option to disable 'bonjour/zeroconf/SSDP' broadcast

also upnp in general can be abused if left reachable to the world:
https://blog.cloudflare.com/ssdp-100gbps/

**Comment by Safihre** [comment]
I agree, I would deprecate specific setting to Bonjour and have 1 setting `enable_broadcast`.

**Comment by thezoggy** [comment]
went to go turn `enable_bonjour` into `enable_broadcast` to use it as a generalize master switch for bonjour/ssdp/etc but I noticed that sab is not broadcasting ssdp for me.

win10 pro  w/sab 3.2.0RC1 windows binary - sab shows: `Serving SSDP on 192.168.0.2 as SABnzbd`  but not actually seeing it show up.
also running sab from git 3.2.x branch, same thing.. says its serving SSDP but not seein git.

windows does have network discovery enabled. i see other devices like philips hue/iot switches/sonos/xbox/etc but not sab. booted up win10 laptop, not seeing sab over there either.


`ssdp_broadcast_interval ` - missing from wiki

**Comment by jcfp** [comment]
I do see broadcasts in my test vm, but not on my regular desktop (probably my firewall's doing). There were/are bugs in the startup code for bonjour and ssdp though, that allow it to start although sab is only listening on localhost and make weird choices wrt the host address to use in broadcasts. I'll make a pr for that stuff plus changing the bonjour setting into an overall killswitch for the broadcasts.
