### ISSUE TITLE
Data dir removed on update when in sab folder

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1779]
Heya,
i had my data/config directoy moved into the sabnzbd/installtion directory and just noticed that on update,, the whole sabnzbd installation folder gets wiped (without hint/asking).

Ill just use a backup and move it to another location, but would appreciate if this would not get deleted on update.

**Comment by Safihre** [comment]
Installation folders are not intended for user data. Adding logic to see if all can be removed is just way too much work.
