### ISSUE TITLE
session auth no longer instance specific

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1781]
Not sure when this got introduced but it did not used to be this way.

I have two sab instances that are password protected (main instance and dev instance).
When I login to one it logs out the other instance.
Previously you only have to authenticate to each instance once until the session is killed/logged out.

Now, when switching between instances on a page refresh it is forcing me to login.
So then you get into this cycle where one is always killing the other after login, so to go back and forth you are constantly logging in.

If you remove sab username/pw for one of the instances it stops issue (session auth killing the other).
If you have one using `localhost:ip` and another doing `192.168.x.x:ip` then they play nice.
As soon as you login using the same domain (example, both localhost - http://localhost:8081 + http://localhost:8091) it will kill the other auth.

Tried to use the "List of local network ranges" to see if this also will mask the issue.
Discovered that if you put in `192.168.0.0/24` and save it breaks sab with "access denied".
I forgot we used a weak ^text match, sab ini saved with `local_ranges = 192.168.0.0/24,`.
I had to stop sab and manually fix the ini to get it happy again.

**Comment by puzzledsab** [comment]
Are you sure it's not your browser that has changed behavior? I don't think all browsers treat cookies and ports the same way.

**Comment by Safihre** [comment]
The login stuff hasn't changed in 4 years, so I am also expecting maybe it's something on your system?
We do not store any sessions on the instance itself, it's all based on the cookie. So SABnzbd instance itself can't kill a session, only by clearing the login cookie.

**Comment by thezoggy** [comment]
you are correct, i think i just had always used two different 'domain' (ip vs host) to keep the instances from clashing. i kept this open until i could try out firefox 86 since it comes with cookie segmentation ( https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/ ). no luck.
