### ISSUE TITLE
Set a limit for how much data can be missing from one file before the job is aborted

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1784]
https://forums.sabnzbd.org/viewtopic.php?f=4&t=25183

Sometimes the user will know that the posting is gone if more than a few articles are missing from the same file.

I'm working on this. It will be a simple number in MB, configurable from Special variables.

**Comment by thezoggy** [comment]
There is already a special config value for this

**Comment by puzzledsab** [comment]
I'm closing this to avoid spreading the discussion over too many places. There is also the forum thread and the PR in https://github.com/sabnzbd/sabnzbd/pull/1785
