### ISSUE TITLE
Help needed: SABnzbd on Android: how to make downloaded files accesible for Android?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1790]
Hi, I could use some help:

I've SABnzbd running on Android (with the Android app UserLAnd in between)
Setting up and downloading works: See https://sabnzbd.org/wiki/advanced/android

However ... how do I make the downloaded files accesible for Android?

I tried /host-rootfs/sdcard/data/ ... but stuff put there from Ubuntu does not appear in Android's file manager.

So ... can others help to find a solution? Also pinging @jcfp for expert advice (assuming you're an Android user)?

As per https://github.com/CypherpunkArmory/UserLAnd/wiki/Importing-and-exporting-files-in-UserLAnd I tried /storage, but nothing becomes visible to Android. 

```
sander@localhost:~$ cd /storage
sander@localhost:/storage$ ls -al
total 44
drwx------.  4 sander sander  4096 Feb  6 17:37 .
drwxr-xr-x. 24 sander sander  4096 Feb  6 17:37 ..
drwxrwx---.  2 sander   9997  4096 Feb  7 11:10 internal
drwxr-x---.  2 sander   9997 32768 Feb  7 11:11 sdcard
sander@localhost:/storage$ ls -al internal
total 12
drwxrwx---. 2 sander   9997 4096 Feb  7 11:10 .
drwx------. 4 sander sander 4096 Feb  6 17:37 ..
-rw-rw----. 1 sander   9997   10 Feb  7 11:13 blabla123.txt
sander@localhost:/storage$ ls -al sdcard
total 68
drwxr-x---. 2 sander   9997 32768 Feb  7 11:11 .
drwx------. 4 sander sander  4096 Feb  6 17:37 ..
-rwxr-x---. 1 sander   9997     7 Feb  7 11:13 blabla789.txt
sander@localhost:/storage$
```

**Comment by puzzledsab** [comment]
Did you check /Android/data/tech.ula/files/storage (from Internal storage in the Android file browser)? I tried a simple `echo test > /storage/internal/test.txt` from UserLAnd shell and it's available in that dir. I don't have an SD card so I can't test that.

**Comment by jcfp** [comment]
Same result as @puzzledsab here; no automatic shortcut in the file manager on the android side but stuff does appear in that location and is user-accesible.

**Comment by Safihre** [comment]
Hmm strange, my `/Android/data` folder is empty.

**Comment by sanderjo** [comment]
> Did you check /Android/data/tech.ula/files/storage (from Internal storage in the Android file browser)? I tried a simple `echo test > /storage/internal/test.txt` from UserLAnd shell and it's available in that dir.

Oh, yes! 
UserLAnd: /storage/internal/
Android: /Android/data/tech.ula/files/storage

I do have a sdcard, but /storage/sdcard does not appear under  /Android/data/tech.ula/files

Thank you

**Comment by sanderjo** [comment]
> Hmm strange, my `/Android/data` folder is empty.

Which 'root' / start point did you choose? Interne opslag, or SD-kaart?

**Comment by Safihre** [comment]
I only have internal on my Pixel 5.

**Comment by sanderjo** [comment]
OK, thanks. I've put it into https://sabnzbd.org/wiki/advanced/android.html

Closing this issue.
