### ISSUE TITLE
Testers wanted: instructions for SABnzbd on ChromeOS / Chromebook

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1793]
If you are an advanced user and have got a Chromebook, can you test this procedure? 
My goal is to publish this on the SAB wiki (under advanced ...)

**Install Linux (beta) on ChromeOS.** 
See https://support.google.com/chromebook/answer/9145439 and/or https://chromeos.dev/en/linux/setup

**Create shared directory**
From ChromeOS’ file manager Files, create and share a directory for SABnzbd data to be shared, for example “for-SAB”. This is where the downloads will land
See https://chromeos.dev/en/linux/setup#sharing-files-to-linux for help.

**Install Docker in Linux**
Install docker: 
`sudo apt install docker.io`
Make docker usable for normal user: 
```
sudo groupadd docker
sudo usermod -aG docker $USER
```

logout / restart Linux to take effect
As check, execute
`docker ps`

**Run SABnzbd in docker on Linux**
Execute: 
`cd && mkdir sab-config`

Start sabnzbd-docker like this:
`docker run -p 8080:8080 -e PUID=1000 -e PGID=1000  -v ~/sab-config:/config -v /mnt/chromeos/MyFiles/for-SAB/:/downloads linuxserver/sabnzbd`

**Configure SABnzbd**
From ChomeOS, configure and use SABnzbd http://127.0.0.1:8080
Very important: in http://127.0.0.1:8080/sabnzbd/config/folders/ change “Completed Download Folder”  to /downloads

You are now able to download

**Tip**
Create a file like SAB-start.sh with as contents the full docker command

**To do**
Create shortcut in ChromeOS Launcher ... so create a file like `/usr/share/applications/vim.desktop` so that sabnzbd appears on the ChromeOS desktop. But on my Chromebook even for vim there is no shortcut. Help needed!

![image](https://user-images.githubusercontent.com/1273502/107431930-7671d400-6b27-11eb-9a9c-66088f7c2d71.png)

**Comment by jcfp** [comment]
> ****
> Create shortcut in ChromeOS Launcher ... so create a file like `/usr/share/applications/vim.desktop` so that sabnzbd appears on the ChromeOS desktop. But on my Chromebook even for vim there is no shortcut. Help needed!

On most linux systems, simply putting a desktop file in ~/.local/share/applications adds it to menu. A web search suggests chromeos uses desktop files too, even various menu editors apparently work (menulibre, alacarte). Might want to try and see what they do.
