### ISSUE TITLE
Filenames not deobfuscated

### ISSUE THREAD

**Issue by hazcod** [sabnzbd/sabnzbd#1795]
**SAB Version:** SAB 3.2.0RC2

Some downloads will result in a folder called correctly but containing obfuscated filenames:
```
0675e29e9abfd2.f7d069dab0b853283cc1b069a25f81.6545
09023d8bb5a56c.c274ebbf85c3407822d5dc217fb891.9823
4ae09f6d435de8.eb01f442595c5fed8c0ec6008c603b.9502
```

NZB snippet:
```xml
<file poster="group &lt;freestuff@for.all&gt;" date="160565xxxx" subject="[PRiVATE]-[group]-[10]-[1]foo-DL.HDR.DDP5.1.H.265-ABBiE.mkv] - &quot;&quot; yEnc (1/[PRiVATE] \9f3d763715\::70aa70ecaff18d.6a51d5de2e2e7f85f3563b939cddd2.61f7201c::/2f96a8a39a7a/) 1 (1/0) (1/0)">
```

*Deobfuscate final filenames* is selected in SAB.

Possibly related to https://github.com/sabnzbd/sabnzbd/issues/1682

**Comment by sanderjo** [comment]
Nice catch! Easy to reproduce:

```
sander@haring1:~/git/sabnzbd$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sabnzbd.deobfuscate_filenames import *
>>> is_probably_obfuscated("0675e29e9abfd2.f7d069dab0b853283cc1b069a25f81.6545")
False
```

So ... current code thinks "0675e29e9abfd2.f7d069dab0b853283cc1b069a25f81.6545" is NOT obfuscated. But you and I as humans agree it is obfuscated, so I should change the code, and everything will be allright.

What is the formal criterium this is obfuscated? Because "only lower hex values, and a few dots"? Or something more clever ... ?

**Comment by sanderjo** [comment]
PS @hazcod 

Niels ... if you set sabnzbd's logging to +Debug, sabnzbd.log will tell you why SAB decided it's not obfuscated. Can you share those lines? 

```
2021-02-07 18:17:02,762::DEBUG::[deobfuscate_filenames:84] Checking: ABC.Piet.Henk.WEB-DL.H264.Fight-BB
2021-02-07 18:17:02,762::DEBUG::[deobfuscate_filenames:106] Not obfuscated: upperchars >= 2 and lowerchars >= 2  and spacesdots >= 1

```

**Comment by hazcod** [comment]
@sanderjo Hi! Thanks for getting back so quick.
I'm combing through the debug logs, but I guess it only reports this when the download is finished.

I guess something along those lines, but I could be wrong:
- all lowercase alphanumeric without symbols
- of a certain length

**Comment by sanderjo** [comment]
> * all lowercase alphanumeric without symbols
> * of a certain length

What do you mean with "symbols" and thus "without symbols"?

FYI: "my.fantastic.download.2020" is NOT obfuscated, but "0675e29e9abfd2.f7d069dab0b853283cc1b069a25f81.6545" is obfuscated.

If you're interested, see the test cases (and thus definitions) here: https://github.com/sabnzbd/sabnzbd/blob/develop/tests/test_deobfuscate_filenames.py#L61

Anyway: I'll create code that sees "0675e29e9abfd2.f7d069dab0b853283cc1b069a25f81.6545" as obfuscated.

**Comment by hazcod** [comment]
Curious how your code will recongize it. Feel free to link the commits here!
Thanks Sander!

**Comment by thezoggy** [comment]
Look at sonarr regex on the patterns that are obfuscate (number . Number of alphanumeric)

**Comment by hazcod** [comment]
Is there a way to do this deobfuscation manually?
I have a large dataset already downloaded but not correctly renamed. (season packs)

**Comment by sanderjo** [comment]
> Is there a way to do this deobfuscation manually?

Yes, via File manager -> right mouse -> rename ...
No, if you mean from SABnzbd

**Comment by hazcod** [comment]
@sanderjo There are multiple files in the same download, how am I supposed to know what's what?

**Comment by sanderjo** [comment]
> @sanderjo There are multiple files in the same download, how am I supposed to know what's what?

Oh. Can you share such an NZB with me?

**Comment by Safihre** [comment]
@hazcod The deobfuscate will never work for season-packs, because how can it know which file is which episode?

**Comment by hazcod** [comment]
@Safihre well I was hoping there's a method I am missing here.
Ping me on hello@ironpeak.be for the NZB.

**Comment by Safihre** [comment]
Even as a human, how could we know (without parsing the `.mkv` contents) which file would be which episode?

**Comment by hazcod** [comment]
That's unclear to me too, so I was hoping I was missing something for season downloads.

**Comment by sanderjo** [comment]
> That's unclear to me too, so I was hoping I was missing something for season downloads.

What other posters do: add additional info (for example a par2 file), so that a human or sabnzbd can rename. 

But ... not in the NZB you provided.

And my patch now does detect the resulting filenames as obfuscated, which triggers renaming to those files to the post name ... that won't help you.

**Comment by hazcod** [comment]
Okay, so seems the poster really borked up. odd.
Thank you for debugging @sanderjo .

**Comment by sanderjo** [comment]
@hazcod ... are you on Linux? If so, I have a (manual) solution for you to find out which file is which ...

**Comment by hazcod** [comment]
@sanderjo macOS so posix indeed, feel free to share!

**Comment by sanderjo** [comment]
OK.

In short: 
from https://www.opensubtitles.org/ downloads the English subtitles for all episodes.
From the subs for S02E01, choose a rare / unique word ... I chose  `glabella`
Then do a brute force grep:
```
$ grep -i glabella *
Binary file eb6ff044308811.96157b5c2d39ff4fc53e35a04ede93.3ed1 matches
BLABLA.2019.S02E01.Episode.1.720p.NF.WEB-DL.DDP5.1.x264-NTG-HI.srt:when injected in the glabella
BLABLA.2019.S02E01.Episode.1.720p.NF.WEB-DL.DDP5.1.x264-NTG-HI.srt:and insert it deep into the glabella,
```

So ... eb6ff044308811.96157b5c2d39ff4fc53e35a04ede93.3ed1 is S02E01 ... You can rename it now.

Other methods, that did **not** work for your download
* let VLC's VLsub search on hash
* from the MKV's SRT itself, choose a few line, and google for that.
HTH
