### ISSUE TITLE
SABnzbd doesn't work after upgrading on Truenas.. ( ipv6? )

### ISSUE THREAD

**Issue by plato79** [sabnzbd/sabnzbd#1799]
Hi,

When I try to start the service I get this error:

```
Fatal error:
  Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.
```

I'm sure that 8080 port is not used on my server.

From linuxserver/sabnzbd I found out that SABnzbd tries to bind 8080 port of ipv6 address. Although if ipv6 is not available it gives this error. Is there any way to disable ipv6 binding via configuration?

**Comment by thezoggy** [comment]
That port is either already in used or restricted to be bounded to. Pick another port or figure out what's going on locally

**Comment by plato79** [comment]
I think you didn't read my entire post. There is nothing using that port. It seems sabnzbd is trying to bind 8080 port of ipv6 and ipv4 addresses. Although ipv6 is disabled in my jail, and when sabnzbd couldn't bind ipv6 8080 port it gives this error. 

You can see a similar issue [here](https://github.com/linuxserver/docker-sabnzbd/issues/82) or [here](https://github.com/k8s-at-home/container-images/issues/7)

**Comment by sanderjo** [comment]
> I'm sure that 8080 port is not used on my server.

How do you know? How did you measure?

**Comment by plato79** [comment]
it's `sockstat` in freebsd

**Comment by puzzledsab** [comment]
You can set `ipv6_hosting = 0` in sabnzbd.ini or start it with `--ipv6_hosting 0` to disable it, but I think that's the default. It's more likely to be related to the python 2 -> 3 switch.

**Comment by Jackal830** [comment]
I have the same problem in a jail in nas4free. I "solved" the issue by commenting out the following line in /etc/hosts (within the jail)

`#::1                    localhost localhost.my.domain`

Started right up afterword. I wouldn't suggest commenting out this line if you have ipv6 enabled. That being said, if you have ipv6 enabled, you probably aren't running into this error to begin with.
