### ISSUE TITLE
glitter - night -- disabled dropdown background color

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1807]
Noticed that disabled dropdowns are unreadable due to the bg color used (not overridden in night css)
Example is a new install where the Scripts dropdown would be disabled because of no scripts:

![sab](http://zoggy.net/firefox_2021-02-26_15-01-13.png)

from bootstrap.min.css
```
.form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
	background-color: #eee;
	opacity: 1;
}
```

**Comment by thezoggy** [comment]
unrealated note, we updated the included bootstrap js to 3.3.7 awhile ago  but didnt update the .css file (still on 3.3.6)

**Comment by thezoggy** [comment]
looking back at git history, i see you did base64 for the woff/woff2 files to try and solve loading on https?

not sure what that is about, by any chance did you try dropping http/https being specified and just doing `//file.css` to have the browser use whatever protocol the page is using: https://www.paulirish.com/2010/the-protocol-relative-url/

also i see you mention that you couldnt upgrade bootstrap for glitter due to issues.. there has obviously been a ton of updates to bootstrap since, so may want to circle back to updating that. we would also probably benefit from the newer boostrap icons breakout for  maintainability let alone all the additional icons

**Comment by Safihre** [comment]
There was some specific issue with loading the font files, not just the path. Forgot what it was.

Bootstrap 4 changed all the sizes, so would have to redo the whole interface. Also required some html changes. A lot of work, while we don't have any complaints about the interface. What issues would updating fix?

**Comment by thezoggy** [comment]
i was thinking more of the goal to get to bootstrap 5 in the end (would deff take a bit to get there). 
there are a lot of minor changes with bootstrap 5 but big ones are dropping jquery dependency, RTL support, support for positional modals/toast notifications, and of course the bootstrap icons being broken apart to be its own thing which then has a ton of more icons. of course by moving to newer bootstrap means a bit of work as the change in icons (as they dropped glyphicons) and move away from the legacy grid/float stuff to flexbox. so that is deff outside the scope of this GHI. this is mainly about fixing the disabled dropdown state in glitter night

**Comment by thezoggy** [comment]
side note, found out that glitter's bootstrap folder uses older css as well as older version of glyphicons/font on purpose. it has a note that newer css+font combo is not as sharp in firefox/chrome. I discovered that when updating it to 3.3.7 the icons did look sharper but there was a slight artifact in the search icon and the ! icon was slightly skewed. guessing something with glitter/style css isnt playing nice with bootstrap and didnt want to spend the time to debug and decided to just leave it as is for now.
