### ISSUE TITLE
FR: syslog support

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1809]
Just putting some mental notes here, goal is to add syslog support to sab (redirect logger to local/remote syslog receiver).

This I think could be very useful for a few reasons:
* reduce local disk io when moving logs off the host
* send logs for aggregation + monitoring (docker/wsl/splunk/logstash/telegraf)
* make it easier to manage remote or multiple sab instances 
  example: you manage your friends/parents instance and dont want to login through ssh/web to try and keep tabs let alone triage

sab config options we would expose:
* destination [default: localhost]
* port [default: 514]
* protocol [default: udp] - options: (udp/tcp/both)

possible other options to expose
* facility [default: daemon]
* severity [default: notice]
* sanitize log [default: false]

To test local, spin up ubuntu in WSL/docker and configure rsyslog to get udp/514 (most common, could do tcp):
https://www.howtoforge.com/how-to-setup-rsyslog-server-on-ubuntu-1804/
For info on fac/sev ~ https://blog.heroix.com/blog/configuring-and-collecting-syslog

Thoughts on allowing local+remote logging?
If network becomes isolated, outbound log messages might not make it to the dest but local logger may still work.

native handler already supports it, just matter of configuring:
https://docs.python.org/3/library/logging.handlers.html

**Comment by thezoggy** [comment]
go away bot

**Comment by Safihre** [comment]
@thezoggy feel free to add!
I would suggest though to keep it simple. Have 1 Special setting `syslog_host_port` that can be set to a `host:port` notation. It's only for very advanced users anyway.
And maybe 1 transfer mode should be enough? Maybe only Tcp?

**Comment by thezoggy** [comment]
bump

**Comment by Safihre** [comment]
@thezoggy Are you going to build this? 👷‍♂️

**Comment by thezak48** [comment]
Was any progress made on this at all? and also just to add some input majority of syslog implementations are UDP not TCP, the arr stack for example is UDP

**Comment by thezoggy** [comment]
as noted per discord, this kinda fell off the map due to lack of activity but ill see if i can find some cycles and knock it out

**Comment by Safihre** [comment]
@thezoggy If you do implement this, it will definitely be a Special-setting at most. Since this is extremely exotic.

**Comment by lakenen** [comment]
I'm interested in this feature. Is anyone still planning to do this?
