### ISSUE TITLE
RFC: Refinement of "Failed to read the password file"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1810]
I want to refine "Failed to read the password file":

Currently it is triggered by any except in https://github.com/sabnzbd/sabnzbd/blob/7096a785db6be6be7dbc0f91c2f830d6445224b1/sabnzbd/misc.py#L791-L810

So it's unclear whether it's caused by:
1. specified password file does not exist
2. specified password file is not ascii (but created by Word, for example) ... but see note below.

That is confusing / annoying in error seeking.

So ... @Safihre OK if I refine that, including the message (in a nice a T())?

Ad 2: it seems Unicode text in the password file is OK for SAB, and also for unrar. I'll verify that. If so, I don't want to check for ASCII-only.

**Comment by Safihre** [comment]
We should just afd a line below it with the Traceback at Info level. Like we do for many errors. I can easily add that.

**Comment by sanderjo** [comment]
Will that be a nice message, that a normal user / noob will understand?

**Comment by Safihre** [comment]
No, but good enough to debug.
