### ISSUE TITLE
"Deobfuscate final filenames" should also rename smaller files like

### ISSUE THREAD

**Issue by D3nn3** [sabnzbd/sabnzbd#1811]
Hi,

I saw that my Sonarr instance didn't import extra files even though it worked when I set it up a couple years ago. After some investigation it seems that SABnzbd and the "Deobfuscate final filenames" feature is the culprit.

The descriptions says at follows: "If filenames of (large) files in the final folder look obfuscated or meaningless they will be renamed to the job name." Imho also smaller files like sub, srt, nfo etc. should be renames else tools like Sonarr/Radarr won't import these since the filenames don't match.

**Comment by puzzledsab** [comment]
Sonarr will do the deobfuscation if you turn it off in SABnzbd. I think that will make it find other files as well.

**Comment by D3nn3** [comment]
Thanks for the hint, I'll try it out. But my point is still valid I'd say that only renaming bigger files could lead to problems e.g. for people using filebot for automation (or other use cases).
Is there any specific reason why smaller files don't get renamed? Maybe I'm missing something here.

**Comment by sanderjo** [comment]
I don't know what filebot is.

> Imho also smaller files like sub, srt, nfo etc. should be renames
> Is there any specific reason why smaller files don't get renamed? Maybe I'm missing something here.

what if there are two srt files:
blabla_eng.srt
blabla_fra.srt

how should SAB rename these files (with job name "This_is_the_great_name_2021")?

**Comment by D3nn3** [comment]
This is absolutely true and I didn't think about it. How is this currently solved though since the problem also exists when only considering bigger files right?

But nevertheless, disabling the feature solves the problem (thanks again for the info on this) so the issue can be closed if the maintainers think that it should stay the way it is.

**Comment by puzzledsab** [comment]
@sanderjo : It would turn out correct if the main file was blabla.mkv and all instances of blabla in file names were replaced with This_is_the_great_name_2021. I think it would fix much more than it breaks to do so. Alternatively it could rename only filenames that matches the pattern blabla.<ext>. It would miss some edge cases but would usually be correct.

**Comment by sanderjo** [comment]
> It would turn out correct if the main file was blabla.mkv and all instances of blabla in file names were replaced with This_is_the_great_name_2021.

Ah, yes. So, then:

in the lead:
blabla.mkv => This_is_the_great_name_2021.mkv
which would then trigger
blabla.srt => This_is_the_great_name_2021.srt
blabla.eng.srt => This_is_the_great_name_2021.eng.srt
blabla.fra.srt => This_is_the_great_name_2021.fra.srt

... Interesting

**Comment by Safihre** [comment]
Closed by #1826
