### ISSUE TITLE
Unpacking Issues

### ISSUE THREAD

**Issue by abarber229** [sabnzbd/sabnzbd#1817]
My completed folder for Sabnzbd is leaving folders with missing rar files in the folder which causes it to not unzip properly. However Sabnzbd status page shows that it complete the download. In the past I think it would tell me that it was missing files or would abort the download. I’ve started to notice this more and the size usually gets to at least 100GBs before I notice I’m out of space. Is there a way for Sabnzbd to delete those files automatically if it can’t unzip the files? It seems odd that I have been getting quite a few of them in bulk recently. I have four different indexes to chose from. I don’t recall this happening in the past. I’m on version 3.2.0. I can post logs when I get home if you need them. Just wanted to submit this while it was fresh in my mind. Thank you for any advice/help!

EDIT - Here is an example to where it's missing a rar file at the red line. 
![sabnzbd missing rar file](https://user-images.githubusercontent.com/26965604/110637713-b5716480-817b-11eb-9228-f65102c7c7fe.png)
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/6116168/sabnzbd.log)

**Comment by puzzledsab** [comment]
You are using SABnzbd 2.3.0, not 3.2.0. You should upgrade.

**Comment by abarber229** [comment]
@puzzledsab - here is a screenshot from Sab ![image](https://user-images.githubusercontent.com/26965604/110644661-531c6200-8183-11eb-9ee1-a9910550310e.png)

**Comment by puzzledsab** [comment]
Seems like very little is logged, so the only part that included the version was from 2017. Try deleting the log file and enable debug logging (click the wrench, then select debug in the box at the bottom of the window), then download a failing nzb again.

**Comment by sanderjo** [comment]
> You are using SABnzbd 2.3.0, not 3.2.0. You should upgrade.

And not restarted SABnzbd (and thus Windows) since ...

`2017-09-28 05:38:10,444::INFO::[SABnzbd:1149] SABnzbd.exe-2.3.0`

2017 ... 3.5 year uptime ... Nice!

**Comment by abarber229** [comment]
@puzzledsab and @sanderjo - I've shut it down a couple of times, so not sure why it says that I'm still on that version. I did restart sabnzbd, created a new log file as suggested. I've downloaded a tv show and a movie and neither failed. These were two files that failed before by missing one rar file. So not sure really what to say on what fixed it. I can update you if it happens again.

**Comment by tommycahir** [comment]
I suspect this is related to the move to v3.20 as I seen similar happening at the same time, files would download and not unpack or the download would not start at all. It seems sabnzbd is not seeing the unrar dependency for some reason even though a fresh install pulled it down and even using a docker container I had it working until the upgrade to 3.20

My docker logs below also:

```
2021-03-12 11:20:11,863::INFO::[__init__:331] All processes started
2021-03-12 11:20:11,863::INFO::[SABnzbd:307] Template location for Glitter is /app/sabnzbd/interfaces/Glitter
2021-03-12 11:20:11,863::INFO::[SABnzbd:307] Template location for Config is /app/sabnzbd/interfaces/Config
2021-03-12 11:20:11,864::INFO::[misc:1053] [N/A] Running external command: ['/usr/bin/par2', '-h']
2021-03-12 11:20:11,872::INFO::[SABnzbd:401] SABYenc module (v4.0.2)... found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:420] Cryptography module (v3.4.6)... found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:425] par2 binary... found (/usr/bin/par2)
2021-03-12 11:20:11,873::INFO::[notifier:122] Sending notification: Error - unrar binary... NOT found! (type=error, job_cat=None)
2021-03-12 11:20:11,873::ERROR::[SABnzbd:444] unrar binary... NOT found!
2021-03-12 11:20:11,873::INFO::[SABnzbd:450] 7za binary... found (/usr/bin/7za)
2021-03-12 11:20:11,874::INFO::[SABnzbd:461] nice binary... found (/usr/bin/nice)
2021-03-12 11:20:11,874::INFO::[SABnzbd:465] ionice binary... found (/usr/bin/ionice)
2021-03-12 11:20:11,874::INFO::[notifier:122] Sending notification: Error - Essential modules are missing, downloading cannot start. (type=error, job_cat=None)
2021-03-12 11:20:11,874::ERROR::[SABnzbd:471] Essential modules are missing, downloading cannot start.
2021-03-12 11:20:11,875::INFO::[SABnzbd:1431] Starting web-interface on 0.0.0.0:8080
2021-03-12 11:20:11,875::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Bus STARTING
2021-03-12 11:20:11,980::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Serving on http://0.0.0.0:8080
2021-03-12 11:20:11,980::INFO::[_cplogging:216] [12/Mar/2021:11:20:11] ENGINE Bus STARTED
```

link to linuxserver container issue for same - https://github.com/linuxserver/docker-sabnzbd/issues/101

**Comment by thezoggy** [comment]
You can see from your log it says unrar not found. So check your package installer to see what happen there

**Comment by abarber229** [comment]
Sorry for the late reply. Are you thinking that I need to reinstall sab?

Thank you.

**Comment by thezoggy** [comment]
the issue should be fixed (nothing to do with sab).
issue was with os package manager when they pushed out unrar6 they broke the symlink. just grab update from your package manager (to fix unrar)

**Comment by abarber229** [comment]
I'm running on windows 10. Are you saying just to run windows updates?
Sorry if I'm misunderstanding what you're saying about grabbing the update
from my package manager.

**Comment by thezoggy** [comment]
was responding to @tommycahir 

for you, your log is years old and either the logger crashed and couldnt update (permission/access/whatever) or you shared the wrong one. just reinstall / restart and try again. make sure sab log is actually writing to file.. we cant really help when we dont have any logs to know whats going on with your system. and if it was a bigger issue we would have seen other reports.

if your running sab as a service, make sure your running it as right user / correct access

**Comment by abarber229** [comment]
@thezoggy I think you were right that the log write might have been messed up. I renamed the old was and then sab started logging to a new file. I'm not running sab as a service. I saw the unrar.exe in the sab program files folder. Is it okay to just run that exe? Also here are new logs. Let me know if that helps. 
[2021-03-15_logs.zip](https://github.com/sabnzbd/sabnzbd/files/6143231/2021-03-15_logs.zip)

**Comment by thezoggy** [comment]
Two different issues and bit of issue hijacking going on.

Tommy, your issue was related to docker/sulymlink broken on their update. Nothing to do with sab directly. Just sab complained about missing unrar. You are good if you update from your package manager.

**Comment by thezoggy** [comment]
> 
> 
> @thezoggy I think you were right that the log write might have been messed up. I renamed the old was and then sab started logging to a new file. I'm not running sab as a service. I saw the unrar.exe in the sab program files folder. Is it okay to just run that exe? Also here are new logs. Let me know if that helps.

looks like you shared the actual log files, which is not sanitized which is not ideal to be posted publicly (since it shares your apikeys). please remove that from your post and I would recommend on changing your apikeys+pw to be on the safe side.

looking at your log i dont see anything wrong, but i cant see what options are set and your categories are set to do.
can you share the sanitized version of the log (which includes a clean version of your config that goes with it) by clicking on the wrench, then click on 'show logging'. that log file is safe to share publicly.

**Comment by Safihre** [comment]
@abarber229 When I check your logs it seems to be doing fine?

@thezoggy I can see in the logs that `pp: 3`, so it's set to +Delete.

**Comment by abarber229** [comment]
I have the logging set to +debug at the moment. As for categories, I don't have anything special. Below is from Sab. I let Sonarr/Radarr pick up the files to move them. 
![image](https://user-images.githubusercontent.com/26965604/111197308-b566cf80-8594-11eb-84fa-ba980bca5ae6.png)
Does the screenshot look okay to you?

Here is an example on 3/11 where it's missing part05. I have six others that happened on 3/11 - 3/12. 
![image](https://user-images.githubusercontent.com/26965604/111197637-14c4df80-8595-11eb-9285-0b98b32a5041.png)

Also to add C:\Temp is my completed downloads folder. I think Sab thinks all of these files completed successfully when some of them are missing par files. Here is a screenshot of my completed folder.
![image](https://user-images.githubusercontent.com/26965604/111198368-db40a400-8595-11eb-9fdc-617c63ccc982.png)

**Comment by Safihre** [comment]
I am 99% sure in Config > Switches you have "Post-process only verified jobs" turned off. Turn it back on.

**Comment by abarber229** [comment]
@Safihre - yes you are correct. Turning on now.

**Comment by Safihre** [comment]
You have manually turned it off, by default its turned on.
