### ISSUE TITLE
Deobfuscate final filenames causes issues with FLAC posts

### ISSUE THREAD

**Issue by neofright** [sabnzbd/sabnzbd#1818]
With the setting in the title enabled SAB will rename audio files to something like:

> 02-artist-track_title.flac
> 03-artist-track_title.flac
> 06-artist-track_title.flac
> 08-artist-track_title.flac
> 10-artist-track_title.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.1.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.2.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.3.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.4.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.5.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.6.flac
> Artist_Name-Album_Name-CD-FLAC-0000-NMR.flac

Requiring manual renaming like this:
`for i in *.flac;do mv "$i" "$(grep -i "$(rhash --printf="%c" "$i")" *.sfv|cut -f1 -d ' ')";done`

Would it be possible to disable this for specific newznab categories or `if 'FLAC' in rls_name` etc. ?

**Comment by sanderjo** [comment]
> Would it be possible to disable this ... `if 'FLAC' in rls_name` etc. ?

Yes, easy. Or "flac" in the extension.

... but ... hardcoded in the code? Or yet another exteions-options field ...?

Or raise the minimum size?

Or declare "08-artist-track_title.flac" to be not-obfuscated?


```
>>> from sabnzbd import deobfuscate_filenames
>>> deobfuscate_filenames.is_probably_obfuscated("hallo")
True
>>> deobfuscate_filenames.is_probably_obfuscated("08-artist-track_title.flac")
True
```

... that last option would be the best. So, @neofright  is the format always "08-artist-track_title.flac", so with two decimals, and 3 dahs/underscores?

**Comment by neofright** [comment]
Hi sanderjo,

> is the format always "08-artist-track_title.flac", so with two decimals, and 3 [dashes]/underscores?

Any recent FLAC scene release will follow [this](https://scenerules.org/t.html?id=2016_FLAC.nfo) standard. So if the artist name consisted of more than one word then there would be an '_' separating each word of the name. You can make assumptions based on those rules but it would be a nightmare to maintain and probably break any P2P FLAC release. We can't and shouldn't rely on any fixed number of dashes/underscores.

I think it would be better to either raise the minimum file size (80 MiB would probably suffice for all but mix CDs where the album is a single track) OR to disable all deobfuscation routines within sab for FLAC/mp3 files. 99% of the time the par2 volumes will provide you with the correct file names anyway. This is not true of rar packed releases (movies, tv etc.).

**Comment by Safihre** [comment]
@neofright if possible, we would just like to improve our obfuscation detection to not mark these as potentially obfuscated. Step by step we can make it smarter, so thanks for letting us know these cases where it fails!

**Comment by sanderjo** [comment]
How about this:

Quick win: I enhance deobfuscate_filenames.is_probably_obfuscated() so that it sees "08-artist-track_title.flac" as non-obfuscated, so that SAB will not rename it at all.

Longer: if there a few bigger files of about the same size, which deobfuscate_filenames would like to rename all ... do not rename any file. Rationale: probably a FLAC post, or a season pack, and deobfuscate_filenames could cause more damage than good.

**Comment by sanderjo** [comment]
@neofright Are you running SAB from source (looks like it, as you post a POSIX oneliner)? 

If so: you can add ".flac" in  https://github.com/sabnzbd/sabnzbd/blob/e8eec8069698fbb4e4a0f68595d4b59d50298824/sabnzbd/deobfuscate_filenames.py#L40

... and ... solved ...

**Comment by neofright** [comment]
Years ago I used to run sab from source on Linux.

But I've since switched to using (linuxserver) Docker, and I'm happier with less sysadmin work as a result!

Thanks @Safihre for acknowledging the issue and to @sanderjo for coming up with a good solution.

I can see that you have created a new issue for improving the deobfuscation script. Do you want me to submit a PR for adding ".mp3" and ".flac" to `EXCLUDED_FILE_EXTS` ? Either way, I can probably close this issue relatively soon!

**Comment by sanderjo** [comment]
> Do you want me to submit a PR for adding ".mp3" and ".flac" to `EXCLUDED_FILE_EXTS` ?

Thanks, but no thanks: I think my Issue/PR will solve it automatically.

**Comment by sanderjo** [comment]
@neofright my code to solve this is now in sabnzbd's github version. If you use Linuxserver's version "**unstable** | Pre-releases from their GitHub", you should get that code. Can you check that it works for you on that specific post: so no renaming of the .flac files?
