### ISSUE TITLE
3.2.0 is missing from Synology community packages.

### ISSUE THREAD

**Issue by 4np** [sabnzbd/sabnzbd#1819]
@Safihre , can you please push `3.2.0` to Synology community packages? :)

Thanks!

**Comment by Safihre** [comment]
I prepared it, but they haven't merged it 😔
https://github.com/SynoCommunity/spksrc/pull/4459

**Comment by Safihre** [comment]
They added it :)

**Comment by 4np** [comment]
Thanks @Safihre 👍

**Comment by 4np** [comment]
Hmm... not seeing it yet although it's [listed on SynoCommunity](https://synocommunity.com/package/sabnzbd#). I installed Python 3.8, but it's still showing `3.1.1-46` as latest. Any idea?

**Comment by Safihre** [comment]
There is a lot of caching involved, so it might take 48h before the update shows.
