### ISSUE TITLE
Fails to delet from UI when using Glitter

### ISSUE THREAD

**Issue by thermionic** [sabnzbd/sabnzbd#1820]
Just updated to 3.2, but problem has existed on and off for a while.

If I select "Purge Failed NZBs & Delete Files", or "Purge Completed Files" when in the "Glitter Auto" skin, nothing happens, If I change to "Plush - gold",  the purge works as expected.

To confirm that this was not related to the restart of SABnzbd when changing skin, I have also tested changing from "Glitter-Auto" to "Plush-gold", and then back to "Glitter-Auto" and the purge fails, but if I then change to Plush-gold", the purge works as expected.

I see this on Linux (Ubuntu 14:04 (yes I know it's old)) and Windows (Server 2012r2 (yes old again)).

The "completed" purge is slighly more reliable than the "failed" purge

Sometimes it can take one attempt, on occcasion it has taken over 20 (I usually give up and try the Plush skin by 10 attempts).

The log only shows when the purge works, is there a logging switch I can enable to get the purge requests as well as the completed?

**Comment by thezoggy** [comment]
Set log level to debug and test command.

**Comment by puzzledsab** [comment]
Which browser(s) have you tried (type and version)? Do you have access to a newer system you could try?

**Comment by thermionic** [comment]
@thezoggy where would that be set?
@puzzledsab same experience on Chrome, Firefox, Edge and IE in private/incognito etc sessions. not possible to update either OS, and as changing to Plush fixes it every time I have tested, the age of the OS would appeart to not be an issue.

**Comment by puzzledsab** [comment]
Click the wrench and then select Debug in the box at the bottom of the window.

**Comment by Safihre** [comment]
It sounds more like something going wrong in the front-end. Could you open the Developer Tools in the browser (usually F12) and then click again on the purge buttons. Does it show anything in the Console of the Developer Tools? In Chrome for example it's at the bottom.

I can't reproduce the problems on any of my systems..

**Comment by thezoggy** [comment]
prob adblocking/user script. run from clean browser / safemode and try again. also dont run from incognito
