### ISSUE TITLE
Sabnzbd on Docker 3.2.0: essential modules are missing, downloading cannot start.

### ISSUE THREAD

**Issue by p28nay** [sabnzbd/sabnzbd#1822]
updated my SABNZB to the latest version (3.2.0 [7be9281]) from linuxserver and I now get the following errors:

    ERROR: essential modules missing, downloading cannot start.
    ERROR: unrar binary... NOT found!

I tried removing the container and re-installing it but keep getting the same error.  Had to downgrade back to previous version for it to work.

<img width="1181" alt="Screenshot 2021-03-12 at 13 07 13" src="https://user-images.githubusercontent.com/80529574/110949308-5c036400-833a-11eb-9af1-8ba8618a2dfb.png">

**Comment by Safihre** [comment]
It's a problem in the Docker, not SABnzbd.
https://github.com/linuxserver/docker-sabnzbd/issues/101

**Comment by anty57** [comment]
Me too! I am downgrade for now version is sabnzbd:3.2.0-ls19
