### ISSUE TITLE
7zip - linux

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1823]
https://www.bleepingcomputer.com/news/software/7-zip-developer-releases-the-first-official-linux-version/

Wonder if it's direct port which would allow yet another utility to be aligned within sab code

**Comment by jeffgeorge** [comment]
It's definitely an interesting development to keep an eye on, but it's got to get to a real public non-alpha release first (with code). Might be worth trying to confirm it's a drop-in replacement for p7zip, and see how it benchmarks against p7zip.

**Comment by Safihre** [comment]
Actually I'm more interested in security than performance.. At least with `p7zip` if something was badly flawed security wise, we would know by now.

**Comment by thezoggy** [comment]
also on side note,
https://github.com/animetosho/Nyuu/wiki/Stop-RAR-Uploads
https://github.com/mbruel/ngPost/issues/102

which we may see more non-rar issues crop up and push for more people to use 7zip
