### ISSUE TITLE
Cannot Access SAB GUI :: Error sabnzbd entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by gethubguy** [sabnzbd/sabnzbd#1827]
[log.txt](https://github.com/sabnzbd/sabnzbd/files/6138442/log.txt)
included is the log file.

I am running this in docker on Unraid 6.9.1. It was working fine and then suddenly stopped working. I'm not entirely sure what happened.

In addition: I run binhex's build (i think that's the right terminology here) and I use SAB in conjunction with DelugeVPN. I get the same error message with and without the VPN turned on. Sonarr, Radarr, & Jackett all run fine with the same configuration.

Please let me know if i need to provide more information to help diagnose the problem.

**Comment by sanderjo** [comment]
Just checking: Are you the same person as https://www.reddit.com/r/SABnzbd/comments/m2sked/switched_to_wireguard_and_now_i_cant_open_sab_gui/ ?

**Comment by gethubguy** [comment]
@sanderjo that post is deleted.

**Comment by Safihre** [comment]
```
2021-03-12 23:12:32,638 DEBG 'sabnzbd' stderr output:
Traceback (most recent call last):
File "/usr/lib/sabnzbd/SABnzbd.py", line 1767, in <module>

2021-03-12 23:12:32,639 DEBG 'sabnzbd' stderr output:
main()
File "/usr/lib/sabnzbd/SABnzbd.py", line 1249, in main

2021-03-12 23:12:32,639 DEBG 'sabnzbd' stderr output:
sabnzbd.initialize(pause, clean_up, repair=repair)
File "/usr/lib/sabnzbd/sabnzbd/decorators.py", line 36, in call_func

2021-03-12 23:12:32,639 DEBG 'sabnzbd' stderr output:
return f(*args, **kw)
File "/usr/lib/sabnzbd/sabnzbd/__init__.py", line 312, in initialize
sabnzbd.Downloader = sabnzbd.downloader.Downloader(sabnzbd.BPSMeter.read() or pause_downloader)
File "/usr/lib/sabnzbd/sabnzbd/bpsmeter.py", line 201, in read
self.update(server)

2021-03-12 23:12:32,639 DEBG 'sabnzbd' stderr output:
File "/usr/lib/sabnzbd/sabnzbd/bpsmeter.py", line 251, in update
if not sabnzbd.Downloader.paused:
AttributeError: module 'sabnzbd' has no attribute 'Downloader'
```

**Comment by sanderjo** [comment]
> @sanderjo that post is deleted.

By you? As "Sorry, this post was deleted by the person who originally posted it."

But again: that is you, with same question now here?

**Comment by Safihre** [comment]
It's indeed a bug, it breaks when the quota is set and the quota is spent. 
Will fix.

**Comment by gethubguy** [comment]
@Safihre cool ... let me know if i can help provide info or anything.

**Comment by Safihre** [comment]
Since you run in a Docker I think it's quite hard to get you the fix. You will have to wait for a 3.2.1, so for now maybe downgrade to 3.1.1.

**Comment by gethubguy** [comment]
@Safihre roger - will do.
