### ISSUE TITLE
Warn against too old cherrypy (if HTTPS on and listening to LAN/WAN)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1831]
Step 1 of https://github.com/sabnzbd/sabnzbd/issues/1829#issuecomment-800045976

I made a prototype, for feedback:

On a Ubuntu 18.04.5, with apparantly cherrypy 18.1.0 installed (via pip?):

![image](https://user-images.githubusercontent.com/1273502/111358646-df022280-868a-11eb-8eed-c875c8563c92.png)

On a Ubuntu 20.04, with the cherrypy from plain Ubuntu repo:

![image](https://user-images.githubusercontent.com/1273502/111358086-3eabfe00-868a-11eb-96eb-ea5635576594.png)

**Comment by Safihre** [comment]
I don't want to approach it like this. It's just a Python dependency, so not something we need to make these special constructs for.

**Comment by sanderjo** [comment]
So what approach do you want? SABnzbd bails out if cherrypy is too low? And start that at SAB 3.3.0? So no period with warnings?

Putting it in requirements.txt won't help, because normal Ubuntu users never use that: they rely on the Ubuntu and maybe PPA repo's. They will not touch pip.
