### ISSUE TITLE
RFC: at SAB startup, check that directories are readable and writable

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1833]
Proposal: at SAB startup, check that directories are readable and writable. If not: Error message in SAB gui.

Rationale: 
* SAB does already check that a directory is writable at the moment you change it under Config -> Folders. Good.
* But ... at SAB start-up, that situation can have changed: drive not there anymore, directory not writable anymore. I see this happening with Docker and/or NAS setups. Better to warn user at startup, then error messages at moment of download.

I would want to implement the check for both Temp and Completed.

So ... remarks?

![image](https://user-images.githubusercontent.com/1273502/111607879-f3eccc00-87d8-11eb-88b6-62a0a91b675e.png)

**Comment by Safihre** [comment]
It can already to this, but for some reason specifically it is disabled for these folders.
In `cfg.py` forexample it says:
```python
complete_dir = OptionDir(
    "misc", "complete_dir", DEF_COMPLETE_DIR, create=False, apply_umask=True, validation=validate_notempty
)
```
So with the `create=False` it disables this check.. And if `writeable=True` was set, it would also check for writing access..
I'm not sure why this was done this way.

**Comment by sanderjo** [comment]
and if set the 'right' way, SAB would check at startup?

**Comment by puzzledsab** [comment]
> I'm not sure why this was done this way.

It was because it's not always immediately available if Sab starts at boot.

**Comment by Safihre** [comment]
Yes exactly, so let's keep it that way.
