### ISSUE TITLE
3.2.1rc2 - extracted files not having original date

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1835]
files no longer have original date when extracted, seeing it set to current/unchanged
config > special > ignore_unrar_dates  is not checked (defaults off)

thinking this is fallout from the unrar 6 upgrade, need to dig more into it

**Comment by Safihre** [comment]
We don't add any special paramaters for this to unrar. Sure it hasn't always been like this?
It sets the correct modified date.
![image](https://user-images.githubusercontent.com/5703454/112285819-ff357100-8c8a-11eb-856f-8fe35a9a4aca.png)

**Comment by thezoggy** [comment]
Issue came from irc user, I just tossed up note here to remind myself to dig into it.
Thinking it was just unrar6 update, I tried with unrar 5.91 from sab 3.1.0 and saw same issue.
Downloaded a release from 2017, has todays created+modified dates.

upgraded to 3.2.1rc2, running test download and confirmed that the file there is good with original modified date:
![sab](http://zoggy.net/explorer_2021-03-24_10-22-00.png)

so prob change in workflow where files are being touched (de-obfuscation code or something then).
need to see if it happens after file being repaired or what

**Comment by Safihre** [comment]
Most likely deobfuscation indeed, can you confirm?

**Comment by thezoggy** [comment]
Trying random old download:
ICC.Cricket.World.Cup.2019.England.vs.Afghanistan.Highlights.HDTV.x264-WiNNiNG 
Added to usenet: 2019-06-19 12:48:07 UTC (670d ago)


newsbin 6.90B7 w/autopar options "Use internal RAR timestamps. Unchecked uses today's date" is checked.
```
D:\a.b.hdtv.x264\ICC.Cricket.World.Cup.2019.England.vs.Afghanistan.Highlights.HDTV.x264-WiNNiNG>stat *.mkv | findstr "Birth Modify"
Modify: 2019-06-19 00:00:01.000000000 -0500
 Birth: 2021-04-19 16:15:07.560127700 -0500
```
Can see the resulting file does have the Date in the past which would be expected.
![rar](http://zoggy.net/WinRAR_2021-04-19_16-25-06.png)

sab 3.2.1 (windows binary)

sab download resulted in the media file having the proper date as well, as above you see that file is not obfuscated

Deobfuscate final filenames - is not checked
Direct Unpack - is checked
```
D:\complete\ICC.Cricket.World.Cup.2019.England.vs.Afghanistan.Highlights.HDTV.x264-WiNNiNG>stat *.mkv | findstr "Birth Modify"
Modify: 2019-06-19 00:00:01.000000000 -0500
 Birth: 2021-04-19 16:24:43.298471900 -0500
```

**Comment by thezoggy** [comment]
Trying music release, so no RARset  just obfuscation + pars.. files end up with current time in both sab and newsbin. Trying to find a good test case that works in one but not the other. So it so far is just looking like fallout of obfuscation.
