### ISSUE TITLE
SAB won't accept path symlink for 'scripts'?

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#1836]
Using `master` branch on QTS 4.5.2.1594 (QNAP NAS).

After SABnzbd launch, two errors are shown in the std UI log. Both relate to the current 'scripts' path I've set in my SAB config:
```
Cannot create directory /share/Download/nzbToMedia
```
```
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/filesystem.py", line 648, in create_all_dirs
    os.mkdir(path_part_combined)
FileExistsError: [Errno 17] File exists: '/share/Download/nzbToMedia'
```

`/share/Download/nzbToMedia` already exists as a symlink to another directory, but it looks like SAB doesn't like this. 😞 

This path was previously a directory, but was later switched to a symlink to a directory. 

Is there anyway SABnzbd can be less-restrictive? 

Thanks guys. 👍🏽

**Comment by thezoggy** [comment]
What's the permissions of your path? It's looking like sab can't see the for and tried to make it which then fails

**Comment by Safihre** [comment]
Indeed, it's a simple `os.path.exists`, and if not, we try to create it.

**Comment by OneCDOnly** [comment]
> Indeed, it's a simple `os.path.exists`, and if not, we try to create it.

So, what happens if that path exists as a symlink? The answer is in the first post. 😁

**Comment by Safihre** [comment]
No, it works also for symlinks. 
It will only return False if indeed we don't have permissions or the symlink is broken, maybe that's the case?

**Comment by OneCDOnly** [comment]
No, permissions are the usual for a symlink, and the target directory is 777. Only a single admin user is creating these directories and running SABnzbd. 

No, the symlink is not broken. 

To add to this: if remove the symlink, then start SABnzbd and let it create a directory therre, then I manually remove that directory and replace it with the original symlink to another directory - no problem. Navigation via the SABnzbd UI works fine. 

It appears the problem is the symlink is seen as a file instead of a link to a directory. 

@safihre, can you please try this yourself to confirm?

**Comment by Safihre** [comment]
I cannot confirm, I tested it both from SABnzbd and with plain Python:
```python
osboxes@osboxes:~/Downloads$ ln -s test_start test_link
osboxes@osboxes:~/Downloads$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.exists("test_link")
True
```
After a restart, it stays:
![image](https://user-images.githubusercontent.com/5703454/112715487-b70f8c00-8ee0-11eb-808e-27ea55d2ff20.png)

**Comment by OneCDOnly** [comment]
Bah! Looks like it was something temporary, as now that I'm trying to replicate it, it works everytime. 😆 

Thanks @Safihre - I'll close this off.
