### ISSUE TITLE
Provided password sometimes being ignored

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1840]
SABnzbd 3.2.1RC2, Windows 10

Recently I noticed a few times that SABnzbd sometimes ignores the provided password for a job and pauses it with the orange "encrypted" tag. I had provided the valid password for the job because un-pausing the job resulted in the file being downloaded and decrypted correctly. Considering that I see this only happening lately, I assume that the issue could have been triggered by upgrading to a new SABnzbd version or by my password list slowly growing. (but note that I am not talking about jobs using the password list, only jobs for which I specifically entered the password). 

It does not happen for all jobs for which I have provided the password. It happens approximately only in one out of six jobs for which I had provided the password. It appears not to happen for encrypted jobs that have no password entered for the job but that rely on the password list.

I think that it started with 3.2.1RC1. My password list has 40 passwords. I disabled the too-many-passwords-in-the-list message by setting the special setting "helpfull_warnings" to off.

I only have an error log, not a debug log and it shows the following text:
2021-03-29 13:53:19,928::WARNING::[assembler:136] Paused job "xxxx" because of encrypted RAR file (if supplied, all passwords were tried)

The following shows the paused entry:

https://imgur.com/a/5kGiygJ

**Comment by Safihre** [comment]
RC2 was supposed to fix that, but seems it did not..
Could you send me the NZB(s) at safihre@sabnzbd.org for testing?

**Comment by Safihre** [comment]
Made a mistake. Could you test this new build of 3.2.1?
https://github.com/sabnzbd/sabnzbd/actions/runs/697764157

**Comment by ErikBrown2** [comment]
The two NZBs that had the issue before work fine now with this test build.
