### ISSUE TITLE
Notification handler errors can loop

### ISSUE THREAD

**Issue by jcs** [sabnzbd/sabnzbd#1842]
If I'm reading the code correctly, `GUIHandler`'s `emit` function calls `sabnzbd.notifier.send_notification` and each notification handler can end up calling `logging.warning` which runs through the `GUIHandler` logging handler, causing an infinite loop of an error/warning log triggering a notification, the notification handler failing, which generates a warning, etc.

**Comment by Safihre** [comment]
Yes, that's possible. But so far nobody ever reported it happening.

**Comment by jcs** [comment]
I am the developer for Pushover and I've been seeing hosts sending millions of HTTP requests per hour to our API once they get rejected (for sending too many messages or invalid input) and all of the messages they are trying to send are failure messages from SABnzbd.

**Comment by sanderjo** [comment]
Related to this: https://forums.sabnzbd.org/viewtopic.php?p=124213#p124213 ?
