### ISSUE TITLE
Latest version (3.2.1) provokes this from Norton 360.

### ISSUE THREAD

**Issue by patfla** [sabnzbd/sabnzbd#1844]
Name WS.Reputation.1
Category: Insight Network Threat
Risk: Medium

**Comment by Safihre** [comment]
Yeah it connects to the network.. 🤣
Nothing we can do, hopefully soon it will stop doing that when more users have downloaded it.

**Comment by patfla** [comment]
Thanks.   So I guess the difference for me from prev versions is that I downloaded the new version relatively sooner.

**Comment by thezoggy** [comment]
Correct, all those reputation based ones only work once it's popular. Which requires the users of that AV to grab the same release enough.
