### ISSUE TITLE
New jobs added to the top of the queue

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1845]
SABnzbd 3.2.1 Windows 10

Not sure when this started but just noticed that new jobs are now added to the top of the queue, not to the bottom of the queue. I have the setting 'Switches' - 'Automatically sort queue' set to Default. It is not a category - priority issue because it also happens to jobs of the same category. I mean all jobs in my queue are of a certain category. When I add a new job of that same category (either manually by putting a NZB file in the watched sub folder for that category or via an automated RSS feed), then the new job always ends up at the top of the queue. Not at the bottom as before and as expected.

**Comment by Safihre** [comment]
In Config Switches, can you press Save just to be sure.
Maybe the setting isn't stored correctly.
Otherwise we have to inspect the logs and see what is happening.

**Comment by puzzledsab** [comment]
If the priority is force then new items will always be added to the top.
