### ISSUE TITLE
test password file on first rar part

### ISSUE THREAD

**Issue by brianjmurrell** [sabnzbd/sabnzbd#185]
When a (to be) downloaded multipart RAR has a password one can choose to just download all of the parts and try to decrypt using a list of passwords in a password file, with the risk that the download is wasted if the password file does not contain the correct password

Or one can choose to pause encrypted RARs until the user enters the password for it.

But in my experience one can test passwords on even just the first .rar file in a multipart RAR.

I think it would be a good option to allow a hybrid of the above options.  If a multipart RAR is detected as encrypted, first try the passwords in the password file and only if none of them match, then pause the download.

**Comment by Safihre** [comment]
Finally implemented using the new ```RarFile```!
