### ISSUE TITLE
del_files history API parameter not working as intended.

### ISSUE THREAD

**Issue by SpencerXZX** [sabnzbd/sabnzbd#1850]
I've been troubleshooting this for several days, automation programs such as the *Arrs are sending an api call to remove an item from SABnzbd and includes the del_files parameter in the API call. To reproduce this issue in Sonarr, do the following:

1. Make Sonarr grab a release, and allow it to auto import. See the trace logs of Sonarr to see the specific api call that it sent to SAB, which contains the del_files parameter. It will have deleted the item from SAB history as well as the disk. This is proper operation.

2. Make Sonarr grab a release that is not a quality upgrade or any other reason for it not to automatically import. Now, go to the activy window in Sonarr and remove it from the download client. It will remove it from Sonarr as well as SABnzbd history, however it will NOT remove it from disk.

3. Check trace logs again to find that the api call sent for the manual removal of the item was the same as the automatic removal, both contain the del_files parameter but only the automatic one actually removed files from disk.

I've checked SABnzbd logs, and all it says when it receives this api call is:

'Removing nzb [nzbID]'

It says the same thing for both tests.

**Comment by sanderjo** [comment]
"which contains the del_files parameter. It will have deleted the item from SAB history as well as the disk."

I think SAB never deletes a completed file set from disk. AFAIK SAB can do two delete actions:

- delete a job from the queue. If any, this will delete intermediate files from disk
- delete an entry from History. But only the entry, not completed files on disk

See https://sabnzbd.org/wiki/advanced/api ... you can simulate with curl to see what delete actions do.


"It will have deleted the item from SAB history as well as the disk."

My guess is that Sonarr is deleting completed files from disk.

**Comment by SpencerXZX** [comment]
I think you're correct, thanks for clarifying what the del_files parameter is used for. Closing issue.

**Comment by Safihre** [comment]
Just one additional case:
If the job in the History is _failed_, then SABnzbd will delete the files depending on the del_files parameter.
So it does have a function in the history's API call.

**Comment by reallyuniquename** [comment]
@Safihre 
Is there a simple way to keep an incomplete job in history but delete its files? I mean besides manual way.

**Comment by Safihre** [comment]
@reallyuniquename no.
