### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by bhaskarraja** [sabnzbd/sabnzbd#1851]

**Comment by bhaskarraja** [comment]
Pease guide for reset password

**Comment by sanderjo** [comment]
Please ask questions here: https://forums.sabnzbd.org/viewforum.php?f=2

**Comment by sanderjo** [comment]
which password?

**Comment by puzzledsab** [comment]
Find the file sabnzbd.ini and edit the password there.

**Comment by bhaskarraja** [comment]
SABNZB site for download the movie in my computer 

Bhaskar raja
