### ISSUE TITLE
Sabnzbd seems to be blocking/delaying my websocket connections via cherrypy/ws4py

### ISSUE THREAD

**Issue by h3llrais3r** [sabnzbd/sabnzbd#1854]
I've been using _sabnzb_ for ages now, and never faced a real issue.
A few weeks ago, I upgraded to the python3 only version (latest `master`) and I'm running it from source on Windows.
I've installed all dependencies in a virtualenv and it runs smoothly.

In the meantime I have been migrating my own application (https://github.com/h3llrais3r/Auto-Subliminal) as well to python3 (`development` branch) and I have upgraded _Cherrypy_ also to the lastest version (_cheroot_: `8.5.2`, _CherryPy_: `18.6.0`).
I'm using _cherrypy_ in combination with _ws4py_ for websocket usage (https://ws4py.readthedocs.io/en/latest/_modules/ws4py/server/cherrypyserver/).
Everything runs fine here as well after the upgrade.

However, now comes the strange thing:
On my server I run all apps together (even tested in separated virtual environments), but from the moment I launch _sabnzbd_, my websockets for my application seems to be blocked/delayed... If I kill _sabnzbd_ again, all my websocket messages come through immediately again... So it seems that some process is blocking them from being sent to the browser...
Since the messages are actually sent to _cherrypy_, I first thought that it's a _cherrypy_ issue (or even _ws4py_ or even _pywin32_), but then I would have the same issue when I run 2 instances of my application at the same time as well. I tested this and the issue is not present. So that's why I'm thinking that it might be some issue with the implementation of _cherrypy_ in _sabnzbd_. 

I have been searching for almost a complete day yesterday what could be the issue, until I suddenly detected today that is was caused from the moment I started _sabnzb_ as well on my server. (On my development machine, it was running as expected because I don't have _sabnzb_ running). I even tried different python versions, and it always is the same issue... except in 1 condition: when I'm running my app again on python2, then there is no interference (but that's not the goal of course 😉).
One more remark: when both were running on python2, the issue was not present...

Anyway thanks for taking your time to read this and hopefully you have some idea what could cause this.

**Comment by Safihre** [comment]
So are each running in their own Python processes? And on different ports etc?

**Comment by thezoggy** [comment]
Are you running them behind reverse proxy or in a docker

**Comment by h3llrais3r** [comment]
> So are each running in their own Python processes? And on different ports etc?

Yes, both are running on different ports:

- sabnzbd: 8080
- Auto-Subliminal: 8085

**Comment by h3llrais3r** [comment]
> Are you running them behind reverse proxy or in a docker

None of the 2.

Running it next to each other:

- sabnzbd in it's own virtualenv (due to installed dependencies)
- Auto-Subliminal: not in virtualenv, as it has its dependencies packaged internally

**Comment by Safihre** [comment]
Have to say that I really don't know what is going on here.. We just run CherryPy, nothing special or custom about it..
When downloading we use `select.select` to loop over all sockets, no clue if that's somehow spilling over.
Sorry, not much help 😟
