### ISSUE TITLE
Radio Buttons instead of cryptic SABnzbd Host

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1858]
Currently, a user can/should fill out SABnzbd Host in the Wizard and/or http://127.0.0.1:8080/config/general/

![image](https://user-images.githubusercontent.com/1273502/115008489-771e4200-9eab-11eb-81a1-c38297e6118d.png)

I would say that is techno / cryptic for normal users, leading to incorrect and/or insecure settings.

Therefore my proposal: introduce Ratio Buttions:

**Access SABnzbd WebGUI from:**
* Localhost only
* LAN only
* Internet (needs port forwarding in your router)
* custom: [...]

LAN-only would bind to 0.0.0.0, but would only accept web access from LAN addresses so RFC1918 IP addresses. 

Oh, and SABnzbd Port: let's change that to 

**Run SABnzbd WebGUI on port:**
* Standard (8080)
* Custom port: [...]

**Comment by sanderjo** [comment]
**Notes and Edge Cases:**

* "LAN only" would be defined by `ipaddress.ip_address(ip_of_incoming_browser).is_private` to be True. 



* if you have IPv6 and want to actively use it, the fourth radio button ("custom") is for you. 
* if you have multiple network interfaces (multi-homed etc) and want to bind to a certain interface only: the fourth radio button ("custom") is for you. 
* if you're on a VPS, without NAT, so public IPv4 address. "LAN only" has little value for you: there won't be any incoming connection from a private aka RFC1918 address. So be it.

**Comment by Safihre** [comment]
I think for now I want to see the result of the changes in #1859, we can revisit this later.
