### ISSUE TITLE
article.fetcher and article.fetcher_priority not reset when resetting try list

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1863]
When testing #1861 I found that when the job is added back to the queue to fetch more par2 files it doesn't do anything at first, only when the bad-try-list check passes it starts downloading.

We do reset the try list when adding extra par2 files, but we don't reset `article.fetcher` and `artucle.fetcher_priority` so it seems to be stuck.

Only reproducible with jobs that are missing on the first-level server and need the second level server.

**Comment by puzzledsab** [comment]
I've been looking into this a bit myself. I think the same thing can happen if you for instance disable a server while it's downloading.
