### ISSUE TITLE
Test SABnzbd 3.3.0Beta1, fatal error during start

### ISSUE THREAD

**Issue by Taomyn** [sabnzbd/sabnzbd#1864]
I just updated my installation using the 64bit ZIP archive, copied the files directly over my 3.2.1 installation - just like I do every release. When I went to start the service Windows fails stating it did not start in time. When I ran from a command-prompt using:

`D:\Program Files\SABnzbd>sabnzbd.exe -f "D:\Program Files\SABnzbd\sabnzbd.ini"`

I receive:

![image](https://user-images.githubusercontent.com/4365929/115872287-ea8ef900-a441-11eb-8e55-421edf41c64f.png)

Nothing is logged at this point, but pressing "OK" allows the process to continue and SABnzbd is up and running none the wiser - no errors get logged.

Any ideas?

**Comment by thezoggy** [comment]
trying myself on win10 using SABnzbd-3.3.0Beta1-win-setup.exe to upgrade previous install.
confirm same error pops up and nothing in log. sab still starts afterwards
```
---------------------------
Fatal error detected
---------------------------
Could not read from file.fread: Invalid argument
---------------------------
OK   
---------------------------
```

**Comment by Safihre** [comment]
I can confirm. Removed the Beta for now.

**Comment by Safihre** [comment]
Something changed in PyInstaller. If build using the previous version of PyInstaller there is no error. 
Submitted an issue to PyInstaller, hopefully they can help.

**Comment by thezoggy** [comment]
@Safihre can you try using python 3.9.2 to see if its a 3.9.4 bug with pyinstaller

**Comment by Safihre** [comment]
I build using PyInstaller 4.2 and it doesn't have the problem, see: https://github.com/sabnzbd/sabnzbd/actions/runs/777872038

**Comment by thezoggy** [comment]
right, was thinking it was just bug in 4.3 + 3.9.4 (i know 4.2 + 3.9.4 was fine). but per pyinstaller dev he found the bug and fixed it. so we should be good to go once the fix makes it upstream to new pyinstaller release

**Comment by Safihre** [comment]
Closing this, will update to latest PyInstaller once they fix :)
