### ISSUE TITLE
Request: Bind outgoing connections.

### ISSUE THREAD

**Issue by ArabCoders** [sabnzbd/sabnzbd#1867]
Hi i maintain small patch on top of SABnzbd to bind outgoing connections to news servers.

````patch
--- newswrapper.py      2021-02-28 23:35:56.627867710 +0300
+++ newswrapper.py.ori  2021-02-28 23:50:04.462036861 +0300
@@ -305,6 +305,14 @@
                 # Use a regular wrapper, no certificate validation
                 self.sock = ssl.wrap_socket(socket.socket(af, socktype, proto))

+        #bind outgoing to same interface.
+        try:
+            self.sock.bind((sabnzbd.cfg.cherryhost(), 0))
+            logging.info('bind to %s worked OK', sabnzbd.cfg.cherryhost() )
+        except:
+            logging.info('bind to %s did not go well', sabnzbd.cfg.cherryhost() )
+            pass
+
         # Store fileno of the socket
         self.fileno: int = self.sock.fileno()
````

is there anything else i need to be aware of? so far it seems to be working well except it's not showing up on the connection info tab. and instead it's showing the real default IP.

**Comment by Safihre** [comment]
What are you trying to do really? I'm a bit confused, since I only know `bind` for server side usage when listening on a port. How do you need it for newsservers?

**Comment by ArabCoders** [comment]
> What are you trying to do really? I'm a bit confused, since I only know `bind` for server side usage when listening on a port. How do you need it for newsservers?

by binding the socket to the same IP as the cherryhost it will use the same IP for outgoing connections instead of default connection. what im trying to do is make sabnzbd uses specific IP for it's outgoing connections and it's working.

**Comment by thezoggy** [comment]
so you start sab binding to one host but want sab to use another host when making requests? why not just use the one you want initially? or run through stunnel?

**Comment by ArabCoders** [comment]
Ok let me try to explain the problem im trying to solve.

1. i have two internet connections. 
2. i want sab WebUI to be available on all interfaces.
3. i want sab to use ONLY specific network interface to download content from. i.e. if i have eth0 and wlan0 i want it the newsreader to use wlan0 for downloads/outgoing connections.

the way the newsreader setup currently it choose whatever available as default as the origin, which is understanble but not desired, i want to tunnel sab traffic from specific interface just like i tunnel for example qBittorent from specific interface.

i tried to use stunnel before but i honestly either didn't know how to set it up correctly or it just doesn't function which the docker setup that i have.

**Comment by sanderjo** [comment]
It has been discussed before: https://forums.sabnzbd.org/viewtopic.php?p=96582#p96579 

Did you read that?

**Comment by Safihre** [comment]
Oke I understand now. 
So is this a feature request to add this to SABnzbd?

**Comment by ArabCoders** [comment]
Indeed that would be ideal and i dont have to re-patch every time sab updates. Otherwise i was looking if there is anywhere else im leaking main ip
