### ISSUE TITLE
Deobfuscation fails when target folder ends in "*"

### ISSUE THREAD

**Issue by Taomyn** [sabnzbd/sabnzbd#1868]
Since the past few months of updates one of my categories has been constantly failing to deobfuscate the final video file name of most NZBs, but I think I have found the cause.

When the category destination folder does not end in "*" the file is left in a sub-folder with its correct name, but if the folder does end in "*" the filename is not deobfuscated. These are two categories I have been testing with and the "tv_test" nearly always fails:

![image](https://user-images.githubusercontent.com/4365929/116195010-e7418900-a731-11eb-9bb5-2cebcaf24f5b.png)

I say "nearly" because occasionally some would be fine but I'm not sure why - either they weren't obfuscated or maybe they were in a subfolder already.

Currently I am running 3.3.0Beta2 but this issue has been happening to me for nearly all the 3.2 releases - I don't recall when it first appeared as I had hope subsequent releases would fix it.

**Comment by Safihre** [comment]
Can you enable Debug logging in the Status window and then after it happens again share the logs?

**Comment by Taomyn** [comment]
Hopefully this is what you need

[deob-log.txt](https://github.com/sabnzbd/sabnzbd/files/6382775/deob-log.txt)

**Comment by Safihre** [comment]
Fixed the problem, it was Windows specific where we do special sanitization of filenames that would ignore the carefully constructed list of files that were extracted and need deobfuscation.
In a few minutes you can download an updated 3.3.0 release here:
https://github.com/sabnzbd/sabnzbd/actions/runs/788718511

**Comment by Taomyn** [comment]
Thanks and great job finding it so fast. Once I see the update is available I'll grab it and let you know if all is good again.

**Comment by Taomyn** [comment]
I confirm it's fixed the problem
