### ISSUE TITLE
Install SABnzbd from source on Fedora (34)

### ISSUE THREAD

**Issue by TuxyKey** [sabnzbd/sabnzbd#1899]
at the request of sanderjo i'm opening a new thread regarding the install of SABnzbd from source.
Sanderjo commented that he got everything working in a Fedora Docker image.
Link to discussion:
https://github.com/sabnzbd/sabnzbd/issues/1471

********* What did i already try ?

** nuxref version

Before migrating to the latest Fedora 34 i tried installing SABnzbd  using the nuxref repository  mentioned on the SABnzbd wiki that can be found here:
under the section " Third-party repository"
https://sabnzbd.org/wiki/installation/install-fedora-centos-rhel

The version on found in the nuxref repo was 190 days old as of this writing version 3.1.1
But installing it gave me sum info about the prerequisites that were installed.
i did get  SABnzbd to run, but has sum issues connecting an external drive and starting a download i thing that was related to permissions even though i followed the howto on the nuxref page here:
http://nuxref.com/2016/10/20/sabnzbd-installation-centos-7/#comments
Again i expect it was a permission problem of the mounted external disk that i needed to look at..
i did not investigate it more because i wanted to migrate to Fedora 34..

 ** From source attempt

Having accumulated all the install log from my nuxref install i thought let's throw everything but the kitchen sink at the install and that would surly work..
This does not make for a system i would like to keep running as there's to much packages installed that i don't have a clear explanation for..
 
This time i started from the SABnzbd wiki and followed the "install from source" section that starts with dnf install git.
as step 4 mentioned not all prereqs were tracked i decided to use my nuxref install log to add all possible prereqs i could find..
btw i am grateful for the install howto but when it starts by mentioning that not all prereqs are written it makes the install howto a bit sketchy or more accurate the lightly hood of this howto working less likely..

 So i did a big dnf install covering all packages i could think of and that covered the packages mentioned in the wiki:
dnf install openssl p7zip par2cmdline python3-cheetah python3-cheroot python3-cherrypy python3-configobj python3-feedparser python3-jaraco python3-jaraco-functools python3-more-itertools python3-notify2 python3-portend python3-tempora python3-toml python3-trustme python3-zc-lockfile unrar 

i also followed the SABYenc wiki / howto:
https://sabnzbd.org/wiki/installation/sabyenc.html

that made a mess of things 
giving me version 3.3.6 of SABYenc instead of the expected v4.0.0 

then i thought "Wait perhaps it's my path" ???
so i added this to my .bashrc 
export PATH=$PATH:/home/sammy/.local/lib/

in the end i tried so long to mess with my system that i can't reproduce it and still SABnzbd came with the errors..
So perhaps sanderjo can help me install it on a clean Fedora 34 install.. and perhaps that howto can help a few people that want to do the same.

**Comment by sanderjo** [comment]
This is what works on a fresh Fedora:

Install unrar and par2:
```
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm  -y

sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

sudo dnf install par2cmdline unrar -y
```

Install SABnzbd plus python libraries:
```
sudo dnf install python3-pip git -y
cd
git clone https://github.com/sabnzbd/sabnzbd.git
cd sabnzbd/
sudo python3 -m pip install -r requirements.txt -U
```


Start SABnzbd:
```
./SABnzbd.py 
```

**Comment by TuxyKey** [comment]
> This is what works on a fresh Fedora:
> 
> Install unrar and par2:
> 
> ```
> sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm  -y
> 
> sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
> 
> sudo dnf install par2cmdline unrar -y
> ```
> 
> Install SABnzbd plus python libraries:
> 
> ```
> sudo dnf install python3-pip git -y
> cd
> git clone https://github.com/sabnzbd/sabnzbd.git
> cd sabnzbd/
> sudo python3 -m pip install -r requirements.txt -U
> ```
> 
> Start SABnzbd:
> 
> ```
> ./SABnzbd.py 
> ```

Thanks for your help sanderjo .. it took a bit for me to reply because i wanted to do a clean install and try it out..
The rpmfusion part is something i always do as i always install VLC.. (that part was familiar to me )
But the rest is new to me..
Questions : 
how do i update SABnzbd in the future ??
To be honnest how to git is on my to do list.. So i will spend time to get to know it..
But for now : is there anything i need to know to keep SABnzbd up to date?
The other thing with pip , if i recall correctly that is python package manager..
There is probably a pip update thing ??

Last thing:
starting ./SABnzbd.py
Does give me sum errors : 

(SABnzbd.py:7718): Gtk-CRITICAL **: 23:38:25.621: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
(SABnzbd.py:7718): Gtk-CRITICAL **: 23:38:26.623: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
(SABnzbd.py:7718): Gtk-CRITICAL **: 23:38:27.625: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
(SABnzbd.py:7718): Gtk-CRITICAL **: 23:38:28.626: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

and reading the start up sequence : 

 2021-05-22 23:38:11,591::INFO::[SABnzbd:462] 7za binary... NOT found!

so i did a search:  (with dnf provides) and got a hit

dnf provides 7za
Last metadata expiration check: 0:04:31 ago on Sat 22 May 2021 11:46:49 PM CEST.
p7zip-16.02-19.fc34.x86_64 : Very high compression ratio file archiver
Repo        : fedora
Matched from:
Filename    : /usr/bin/7za

And did an install:
sudo dnf install p7zip

and now i says:
2021-05-22 23:50:43,396::INFO::[SABnzbd:460] 7za binary... found (/usr/bin/7za)

So the only error left is the Critical GTK stuff..

any idea what that is ???
Thanks again for your help ..appreciate you taking the time to help..

**Comment by sanderjo** [comment]
Is SABnzbd now running and usable for you?

**Comment by TuxyKey** [comment]
> Is SABnzbd now running and usable for you?

i only had time to test the install.. it's past midnight so i turned of my main laptop..Will test a download asap and see if it really works.. will let you know hopefully tomorrow..

**Comment by TuxyKey** [comment]
> Is SABnzbd now running and usable for you?

Thanks for your help .. i just tested a download and everything seems to work.
only one error but download works:
(SABnzbd.py:2714): Gtk-CRITICAL **: 16:47:18.139: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by sanderjo** [comment]
> > Is SABnzbd now running and usable for you?
> 
> Thanks for your help .. i just tested a download and everything seems to work.

OK, good.

> only one error but download works:
> (SABnzbd.py:2714): Gtk-CRITICAL **: 16:47:18.139: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

I advice: ignore.
... or spend a lot of time analyzing it. You can start by googling that error message ... it's a rabbit hole.


> how do i update SABnzbd in the future ??

Go into the SABnzbd directory, and type `git pull`. Done.

**Comment by TuxyKey** [comment]
> > > Is SABnzbd now running and usable for you?
> > 
> > 
> > Thanks for your help .. i just tested a download and everything seems to work.
> 
> OK, good.
> 
> > only one error but download works:
> > (SABnzbd.py:2714): Gtk-CRITICAL **: 16:47:18.139: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> I advice: ignore.
> ... or spend a lot of time analyzing it. You can start by googling that error message ... it's a rabbit hole with GNOME.
> 
> > how do i update SABnzbd in the future ??
> 
> Go into the SABnzbd directory, and type `git pull`. Done.

thanks... about the rabbit hole.. i did a search before asking .. and it's a rabbit hole alright.. with no clear exits.. so ill just do what you say and ignore it.. 
thanks for the clarification for the update (git pull)..

**Comment by TuxyKey** [comment]
i also wanted to know how to maintain. that is to say keep  the system /  SABnzbd up to date.. 
The git pull was clear enough..
But then there is the pip python thingy ..
sudo python3 -m pip install -r requirements.txt -U

Looking on stackOverflow it seems --upgrade does something..
python -m pip install --upgrade pip

then i wondered what the -U does ???
stack says:

    -U, --upgrade Upgrade all packages to the newest available version

So perhaps in the future when i do a git pul and there could be a new requirements file 
and if i re-run the update install command it could upgrade the requirements ?
 
The pip user guide is massive and not really helpful for a noob.
https://pip.pypa.io/en/stable/user_guide/

**Comment by sanderjo** [comment]
> So perhaps in the future when i do a git pul and there could be a new requirements file
> and if i re-run the update install command it could upgrade the requirements ?

Yes, that will work.

**Comment by TuxyKey** [comment]
cool. .. thanks noted..
after the git pul .. one can choose to do a 
sudo python3 -m pip install -r requirements.txt -U

And that will install any updates or new requirements ..

Thanks just wanted to write it all out.. here .. for future reference.. 

Thanks again for your help.. really really appreciate it..

**Comment by sanderjo** [comment]
OK.

One final note: if Fedora is a bit too difficult, I would advice Ubuntu. IMHO it's the most user friendly, big distro.

**Comment by TuxyKey** [comment]
years ago i used to be a unix (AIX) sysadmin and rhel is a bit more familiar to me. but i never ever used Linux desktop.. so i'm more familiar with sysadmin stuff like setting up samba nfs , or iscsi,.... but i'm finding out that the last couple of years not using Linux have impacted me more then realized .. and this is certainly a learning experience..i did try ubuntu my new Tuxedo Pulse 15 came pre installed with it.. but i'm so familiar with the rhel package manager that i chose to stick with it. And who knows perhaps i can get a feel for RHEL system again to help me in my next job ;-)

**Comment by sanderjo** [comment]
> years ago i used to be a unix (AIX) sysadmin

Ah, OK! Welcome back, then!
