### ISSUE TITLE
[FR] Set provider priorities per age ranges

### ISSUE THREAD

**Issue by Diniboy1123** [sabnzbd/sabnzbd#1901]
Hey,

I got plenty of providers added to sabnzbd. Some are better in speed for newer content but some are slower though definitely better with retention and older articles. Thus I would like to propose a new priority system where you could define from age X to Y this provider has priority 0 and etc etc. So basically instead of the current static priorities you could pick which providers are the best to grab from judging by the age of the nzb.

The reason behind this idea is simple. With the 8 separate providers I have added to sab, it often takes 20+ seconds to complete the download and until then the nzb is stuck at 99% of download. I would imagine this is due to the missing articles, so sab needs to try every single provider I have. I could increase the priority of those providers with worse retention rate, but then I would also end up waiting more for the fresh releases which would be faster from these I increased.

**Comment by puzzledsab** [comment]
The server priority system is already fairly complex so I don't think this will be added. However, there have been some fixes for problems with being stuck at 99% lately so maybe the newest release candidate would work better. If not then I don't think different priorities would help. If you want it to always check all servers for missing articles then it would still have to wait for the slowest one.

Having said that, there's a way which would give you almost what you want. Give the servers that are fast for new articles a priority of 0 and set the Retention time to a few days. Give the other servers a priority of 1. If you want the full retention for the pri 0 servers to be checked if the pri 1 servers don't have the articles then add them again as pri 2 with no Retention time limit.

**Comment by thezoggy** [comment]
adding more complexity wont solve the 99% bug, you just need to upgrade to 3.3.0Beta3 or newer.

btw, you can already set retention values for your servers if your wanting to segment which are used (prevent x from going to far back or whatever).  just dont put them at the same priority

**Comment by Safihre** [comment]
Both @puzzledsab and @thezoggy are right, so closing this request.

**Comment by Diniboy1123** [comment]
The issue with retention time setting is always the fact that it is rapidly changing. It would be so nice if nntp would have a way to report the days back automatically. Now I would need to keep it up to date all the time.

And setting the retention days to a small amount for fast providers would make those completely ignored in older nzbs' cases. I don't want to miss out chances, but to reduce the current in-queue time.

Right now I am on 3.3.0-develop [d2f9721], but I will see if an update will show any improvements. Thanks for your input tho.

**Comment by puzzledsab** [comment]
> And setting the retention days to a small amount for fast providers would make those completely ignored in older nzbs' cases.

Not if you add them twice, like I explained.

**Comment by thezoggy** [comment]
Retention times don't really change on providers. They set x age and data ages out. Decades ago they did increase rates as hdd grew but the amount of data posted daily grew exponential and everyone stopped increasing rentention. Several decreased since dmca/spam removal and other things play a factor now.
