### ISSUE TITLE
How much can I cripple Plush to improve code clarity?

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1902]
I have been cleaning up `interface.py` which had a lot of legacy functions to support the Plush skin.
So far I already removed from Plush the ability to:
- Restart (still possible through the Config, if needed)
- Queue repair
- See connection-details of the servers when downloading
- Retry a job in history

Now there's still a big chunk of stuff related to the job-detail page that's old ugly code: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/interface.py#L681-L862
I could consider keeping the ability to rename the job, but remove everything else (mainly the sorting of the files inside a job).

How much of a problem would that be?

**Comment by sanderjo** [comment]
I think this is the wrong place to ask ... I think Plush users are not here.

Personally I don't understand why people stick to Plush and not switch to Glitter. So I am certainly the wrong person to ask.

I'm in favor of phasing out Plush to clean up SAB. I think your approach of phasing out in steps is a nice and friendly way.

We already have a warning for Plush users, haven't we?

**Comment by puzzledsab** [comment]
I think it might be better to remove it than crippling it. Those who use it will get angry either way. If the goal is to force them over to Glitter eventually then the anger will last longer if you do it gradually.

**Comment by sanderjo** [comment]
> the anger will last longer if you do it gradually.

Hahaha, like removing a band aid?

**Comment by jcfp** [comment]
> I think it might be better to remove it than crippling it.

I agree. Not spending much time on maintenance is one thing, but removing (core) functions 'because code clarity' is merely delaying the inevitable.

**Comment by Safihre** [comment]
Oke, for 3.3.0 I will put a warning that in 3.4.0 it will be removed.
