### ISSUE TITLE
Errno 13 - SabNZB trying to create incomplete oflder, already exists. Causing errors.

### ISSUE THREAD

**Issue by Jamiermusic** [sabnzbd/sabnzbd#1903]
Heya!

I read a previous post this was a python related bug. Currently it seems to be re-creating the incomplete folder. 
Since it already exists and can't create it all files get slapped into complete instead. In turn it fails to unpack and do other jobs like sorting / folder structure properly. 

Sonarr / Radarr are doing the sorting. Haven't had this issue before updating to these newer versions.

The location is on an external drive. I've tried to chmod the folder, without any effect. 

I see debugging should be enabled. Can't seem to find it in the web interface. I'm running the compiled app, not via py via term.

Let me know if I should add the log from sab.

Any help would be greatly appreciated!

### System Info
MacOs M1 Big Sur 11.3 (20E232)
SabNZB 3.2.1 & 3.3.0 RC
Sonarr 3.0.6.1196

### Error Message 13:
```
5 minutes ago Failed making (/Volumes/NZBs/z Incomplete)
Traceback (most recent call last):
  File "sabnzbd/filesystem.py", line 672, in create_all_dirs
PermissionError: [Errno 13] Permission denied: '/Volumes/NZBs']
```

**Comment by sanderjo** [comment]
So /Volumes/NZBs/z Incomplete already exists? Sure?
What is the output of

`ls -al "/Volumes/NZBs/z Incomplete" `

**Comment by Jamiermusic** [comment]
memiru@Memiru z Incomplete % ls -al "/Volumes/NZBs/z Incomplete" 
total 0
drwxr-xr-x   2 memiru  staff   68 May 26 07:46 .
drwxrwxr-x  13 memiru  staff  510 May 25 21:24 ..

**Comment by sanderjo** [comment]
and the `z ` is intended?

If so: what if you remove the spaces, so just "zIncomplete"

**Comment by Jamiermusic** [comment]
Yea it's to push it to the bottom of the finder. It'll try :) Moment

**Comment by Jamiermusic** [comment]
I think there was an issue after moving the folder location.

Deleting content and re-adding in Sonarr seem to start downloads properly.

**Comment by sanderjo** [comment]
So ... solved?
If so, please close.

**Comment by Jamiermusic** [comment]
Not a 100% certain yet. Still having issues. Waiting a little bit to see it play out before closing.

Thank you for the help either way :) Stay safe!

**Comment by Jamiermusic** [comment]
It's back ^_^ Anyone got any other suggestions?

**Comment by Safihre** [comment]
This is not a bug, it's a permissions problem. Sab only tries to create it because it can't access it on the first place.

**Comment by Jamiermusic** [comment]
Adding chdmod in advanced for SAB and Sonarr fixed it.
