### ISSUE TITLE
SSL error reporting

### ISSUE THREAD

**Issue by herkalurk** [sabnzbd/sabnzbd#1906]
Wondering if the SSL errors could be reported better to diagnose issues.  I recently changed my SSL and the only error I got was 
```
2021-05-26 13:39:23,913::WARNING::[SABnzbd:1317] Disabled HTTPS because of invalid CERT and KEY files
2021-05-26 13:39:23,913::INFO::[SABnzbd:1318] Traceback:
Traceback (most recent call last):
  File "/home/USER/newsgroup/SABnzbd-latest/SABnzbd.py", line 1314, in main
    trialcontext.load_cert_chain(https_cert, https_key)
PermissionError: [Errno 13] Permission denied

```
I was able to trace back that the private key file was readable by only the root user, once I changed it's permissions to be readable by all users the issues removed.  I say this because another python based app i'm using the certificate on actually told me the private key was the problem in the ssl configuration.

**Comment by thezoggy** [comment]
Seems pretty spot on? You modified file as root and caused permissions problem which prevented sab from accessing?

**Comment by herkalurk** [comment]
The file permissions were given via the letsencrypt application.  For some reason everything but the private key file was 644, but the private key was 600.  Changing it to 644 allowed all the applications (including apache) to read and use the certificate.  I have a custom shell script to do the certificate renewal, and then restart any services which use the certificate.

The only thing I would say about the logging to is detail which part is the problem, since the error I received didn't point to a specific part of the certificate chain, only that the whole chain wasn't working.  If it can some how test each file and if one of them were to fail the test error on that specific file.  I feel like this could be accomplished with a simple function to test that each file in the array of files is in fact readable by sabnzbd and also a valid file for the type (private key, certificate, certificate chain/ca).  If it doesn't pass the test in all ways, then send an error saying that part of it is the problem.

**Comment by thezoggy** [comment]
The private key should be 600.. you wouldn't want any app to read it... You are supposed to use deploy hook to copy it to folder and set it properly for the app..  

https://community.letsencrypt.org/t/best-practice-for-exposing-private-key-to-locally-installed-programs/88158

**Comment by Safihre** [comment]
We can't, this is a internal Python function call. We report exactly the error it gives.
