### ISSUE TITLE
created wiki about "access denied" ... feedback please

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1911]
Hey @Safihre @jcfp @puzzledsab 

I wrote a wiki about "access denied": https://github.com/sabnzbd/sabnzbd.github.io/blob/master/wiki/extra/access_denied.md

Can you review and put your changes directly into the document?

Thanks

**Comment by sanderjo** [comment]
... talking about which:

hostname verification (https://sabnzbd.org/wiki/extra/hostname-check.html) can result in "Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check".
That is confusing: 

- "access denied" is from external internet / exposure
- "Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check" is from hostname verification

Confusing. I would propose to also give "access denied" caused by external internet / exposure an explanation or longer wording.

**Comment by Safihre** [comment]
Yes, the error could be reworded to `External access denied`.

**Comment by sanderjo** [comment]
> Yes, the error could be reworded to `External access denied`.

Can we make that `External Internet access denied`?

**Comment by puzzledsab** [comment]
I suggest replacing the "Access from a private IP address..." sentence with

Local means a private IP address (192.168.x.x, 10.x.x.x and 172.16.x.x). Access from your LAN, virtual machine docker container or similar will not lead to "access denied" unless "local ranges" have been defined (see [#define-local-ranges](url)).

**Comment by Safihre** [comment]
Updated the text a bit more and created a shorthand to use both in the error-message and on the forums.
https://sabnzbd.org/access-denied
