### ISSUE TITLE
Unable to access SABnzbd after update to 3.3.0

### ISSUE THREAD

**Issue by pmcfarland** [sabnzbd/sabnzbd#1912]
Yes I understand that the hostname verification change in 3.3.0 is almost certainly what's causing the issue as detailed [here](https://sabnzbd.org/wiki/extra/hostname-check.html). However the wiki doesn't seem to answer my particular issue.

No matter how I try to access the GUI I get "Access denied"

SAB is hosted on Windows 10
Before updating I was able to access the GUI at http://10.X.X.X:8080/sabnzbd or https://10.X.X.X:8082/sabnzbd both locally (on the host machine) and remote (within my LAN).
After updating I can't reach it from anything. 

I've tried http and https, I've tried 10.x.x.x and 127.0.0.1 and localhost, all get the same error.
I checked in the sabnzbd.ini and found the new host_whitelist setting and found the hostname for the PC it's being hosted on, but again not able to connect from there.
I checked in the sabnzbd.log file and found reports that yes it's blocking access from both the host machine as well as my other machine on the same LAN, both of which could previously access it.

Therefore it seems I need to edit the host_whitelist setting in the .ini, but I'm at a loss for what I need to add to get access.

Is there a setting I can change to temporarily turn off the whitelisting so I can get access back to fix this?

**Comment by Safihre** [comment]
This is the on you're looking for: https://sabnzbd.org/access-denied
Starting in the next release, this url will be included in the error.

**Comment by pmcfarland** [comment]
That did it, setting inet_exposure to 5 and restarting sabnzbd restored access. Thank you
