### ISSUE TITLE
SABnzbd reports incorrect password in environment variable SAB_PASSWORD

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1917]
When a NZB is added to the queue using the watched folder and a wrong RAR password is supplied but the correct password is in the password file, then the download will complete correctly. 
But SABnzbd reports in the environment variable 'SAB_PASSWORD' the wrongly provided password instead of the password from the password file that was actually used to decrypt the RAR file.

The following are some relevant parts from the logfile:

2021-06-20 19:52:55,839::INFO::[dirscanner:163] Trying to import \\?\C:\SABnzbd\WatchedFolder\books\Name_Of_My_Download_Job{{My_Wrong_Password}}.nzb

2021-06-20 19:53:02,933::INFO::[misc:739] Found a password that was set by the user: My_Wrong_Password
2021-06-20 19:53:02,934::DEBUG::[misc:760] Read these passwords from file: ['F28APT', 'daar', 'ster', '38HTS', ]
2021-06-20 19:53:02,934::INFO::[misc:762] Read 36 passwords from file \\?\C:\SABnzbd\PasswordList\MyPasswordList.txt
2021-06-20 19:53:02,934::INFO::[SABnzbd:118] Your password file contains more than 30 passwords, testing all these passwords takes a lot of time. Try to only list useful passwords.
2021-06-20 19:53:02,935::INFO::[assembler:339] Trying password "My_Wrong_Password" on job "Name_Of_My_Download_Job"
2021-06-20 19:53:03,131::INFO::[assembler:339] Trying password "F28APT" on job "Name_Of_My_Download_Job"
2021-06-20 19:53:03,282::INFO::[assembler:339] Trying password "daar" on job "Name_Of_My_Download_Job"
2021-06-20 19:53:03,383::INFO::[assembler:375] Password "daar" matches for job "Name_Of_My_Download_Job"

 'SAB_PASSWORD': 'My_Wrong_Password', 'SAB_PP': '3',

**Comment by jcfp** [comment]
As documented, the environment variable provides the password _supplied by the NZB or the user_ - and it did exactly that. It's not guaranteed to be the one that eventually succeeds in extracting the job.

**Comment by ErikBrown2** [comment]
In the above described case, the user provided multiple passwords, a wrong password appended to the NZB filename and multiple passwords in the password file. So it is not a matter of "the" password that was provided. 

Also when only a password file is used, then the user has provided multiple passwords. It goes then without saying that the correct password, if found, will be reported in the environment variable. This should also be the case when the password provided in the NZB filename is incorrect but a correct password is found in the password file.

I know that it is a small issue and it will not show up often, but on the other hand it appears also to be easily rectified.

**Comment by jcfp** [comment]
Not really: that variable is also available for the pre-queue script, at which point the successful password -if any- is unknown. If you want that specific password, it'd probably make more sense to have a separate env. var. for that, available to the post-processing script only.

**Comment by Safihre** [comment]
Indeed, it is specifically build this way. But I don't think I considered this case when adding this:
https://github.com/sabnzbd/sabnzbd/blob/c90a93661bfdd6a93f01d410e5148891be74275b/sabnzbd/assembler.py#L358-L360

I'm a bit conflicted, as I would also expect `SAB_PASSWORD` to have the "correct" one.

**Comment by ErikBrown2** [comment]
The comment in the code says "We always trust the user's input". I do hobby programming in vb.net but the code of SABnzbd goes way above my head so I cannot say what this exactly relates to. But if the password in the environment variable is supposed to show only the password provided by the user as part of the NZB filename or NZB file, then it should be blank in case of only using the password file. But that is not the case. When SABnzbd finds a correct password in the password file, then the environment variable shows that password.

**Comment by puzzledsab** [comment]
I don't understand the use cases. Why do you need the password after it's unpacked? And why would the nzb have the wrong password? I agree with jcfp that the safest solution is to add another variable which contains the correct password if there is one, or is empty if there are no matches.

**Comment by ErikBrown2** [comment]
The use case is to manage the password file automatically. SABnzbd complains when the password file is longer than 30 passwords so my postprocessing script adds the used password to the top of the password file and removes passwords that were not used for a long time. This works because often passwords are re-used. Also there is now no need to maintain the password file manually.

The case of the wrong password came up because of a spot that showed a wrong password while the correct password was in the password file. But this will not happen often so maybe we should just leave it at this. It was just that, in my opinion, it does not make any sense to report a wrong password while the correct password is known.

**Comment by jcfp** [comment]
![-](https://user-images.githubusercontent.com/6666432/125621886-d25a245c-942c-4ddb-b157-545ca9f00c6d.gif)
