### ISSUE TITLE
pystone.py: keep in util/ (add __init__.py) or move to sabnzbd/ ?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#192]
I would like to discuss something:

Should module pystone.py stay in util/ (where I put it when I made the patch), or should it move to sabnzbd/ ?

Reason of my question: it appears Python needs a file __init__.py in util/ to be able to import pystone.py as a module, which currently is not the case. See http://forums.sabnzbd.org/viewtopic.php?f=2&t=18506&p=98248#p98244 . So putting it in would solve the problem in that thread.

However, someone (jcfp?) said util/ is a directory for Windows stuff? If so, we could move pystone.py to sabnzbd/ (which already contains a (large) __init__py), but I don't know if only sab's own stuff should be there?

So ... please advice.

**Comment by shypike** [comment]
Indeed, util/ contains Windows support files.
The best place would be sabnzbd/utils where other third-party modules reside.
The import path would be sabnzbd.utils.pystone.

**Comment by sanderjo** [comment]
OK, thanks.

Pull request sent (against develop), but looking at https://github.com/sabnzbd/sabnzbd/pull/193 I'm not sure it only contains the moved pystone patch ...
