### ISSUE TITLE
sab - fails to show download speed if downloaded in 0 seconds

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1926]
1) if sab d/ls something too fast (<1sec) it doesnt show the speed in the column (speed is shown for the details though)
![sab-download](https://user-images.githubusercontent.com/500882/125208535-b1a03c80-e258-11eb-9b57-5aa692a075f2.png)

2) apikey is not obfuscated from download details in the gui

**Comment by Safihre** [comment]
This has been the case for many many years, because for the column we use the bytes/time, if the time is 0 we can't do that.
Point 2 is not really an issue in my opinion, since this is private history and that's just the URL it came from.

**Comment by thezoggy** [comment]
Yep I'm aware it's been a quirk forever, but probably something we should fix since we do have the data?
