### ISSUE TITLE
Upgrading to 3.4.0 Beta 1 from 3.3.1 results in error "Failed to execute script SABnzbd"

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#1927]
After upgrading from 3.3.1 to 3.4.0 b1 I get the error ![Screenshot 2021-07-12 000419](https://user-images.githubusercontent.com/32511867/125208811-c8b94b80-e2a5-11eb-869a-48d47f6912d3.jpg) in a popup window. The error log does not show anything about the new version. I use Windows 10 pro.

**Comment by Safihre** [comment]
Indeed, retracted the release for now: #1925
