### ISSUE TITLE
SABnzbd does not open in browser

### ISSUE THREAD

**Issue by Thursten4Moore** [sabnzbd/sabnzbd#1929]
This is sporadic - it sometimes works OK but mostly it does not.

I can't figure out what made things different.
For several weeks after I first installed, I start SABnzbd (using the Start menu) and it opens in a browser.
Then one day it doesn't open in a browser anymore.
Then suddenly one day it does.
After restarting it no longer opens in a browser again.
I can tell it's running when I open Task Manager.
I don't know how to use SABnzbd without the browser interface, so I am stuck without it at this point.

Any help on how to get it to open the browser?

I have:
Windows 10 most recent update.
Firefox browser is default.
SABnzbd 3.3.1.

Also I installed NZB Unity -- but it isn't successful when doing the Test Connection, so is SABnzbd really running?

Please help.
Thanks.

**Comment by sanderjo** [comment]
> I don't know how to use SABnzbd without the browser interface, so I am stuck without it at this point.

SAB normally is on http://127.0.0.1:8080/sabnzbd/ or https://127.0.0.1:8080/sabnzbd/ . Does that work for you?

**Comment by Thursten4Moore** [comment]
When I open SABnzbd using the Start menu, no browser opens. Previously, I had bookmarked the SABnzbd page in Firefox, and that bookmark is the same as you mentioned:
http://127.0.0.1:8080/sabnzbd/

So I first start SABnzbd using the Start menu, then when I enter this as a URL in the address bar in Firefox, I get the same result:
"Firefox can’t establish a connection to the server at 127.0.0.1:8080."

When I enter that as the Host for NZB Unity and try the Test Connection, I get a message that the test was not successful:
"Could not connect to host"

:-(

**Comment by sanderjo** [comment]
That (probably) means SABnzbd is not running at all

**Comment by Cpuroast** [comment]
On Windows, you should see a yellow downward arrow icon near the clock when it's running and you can right-click on it and and pick "Show Interface" and it should open.

**Comment by Thursten4Moore** [comment]
> On Windows, you should see a yellow downward arrow icon near the clock when it's running and you can right-click on it and and pick "Show Interface" and it should open.

Thanks for the info. I didn't know this. However, it's making me wonder if SABnzbd is running at all. It shows up when I open Task Manager, but I don't see what you describe. There is no small yellow down arrow icon near the clock, and there is none in the system tray or anywhere else I look.

If it's not running, how do I get it to run? I uninstalled it and reinstalled it a couple of times and I thought that would work, but it's still giving the same problem.

**Comment by Cpuroast** [comment]
Uninstalling preserves the config files, unless you specifically check "Delete Settings", so you don't gain much by re-installing.

Try this, make sure sab is shutdown and you don't see it in task manager, then move the entire sabnzbd config folder out of its original location, it's located here "YourUserName\AppData\Local\sabnzbd", to your desktop

Then start sabnzbd, it should start and greet you with the wizard, if it does, you can either re-configure everything from scratch or figure out what's wrong with your original config file, sabnzbd.ini and try and copy it back.

For reference see here: https://sabnzbd.org/wiki/advanced/directory-setup

**Comment by Thursten4Moore** [comment]
@Cpuroast - Thanks for the info. That seemed to work SABnzbd now opens in a browser like it did before. I did compare the two copies of the .ini file but I could not see any difference. Nevertheless, it worked, at least for now. Hopefully it will stay working. Thanks again.

**Comment by puzzledsab** [comment]
Could have been a broken database file.
