### ISSUE TITLE
"Restarting because of crashed downloader" is INFO-level? I propose at least WARNING

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1936]
Triggered by https://forums.sabnzbd.org/viewtopic.php?p=125326#p125326, I'm surprised a "Restarting because of crashed downloader" is only INFO-level? That crash happening is a bad thing, but it stays quite hidden, so problem huntig is difficult.

```
2021-07-29 17:17:03,652::INFO::[__init__:1004] Restarting because of crashed downloader
2021-07-29 17:17:03,653::INFO::[SABnzbd:1578] Performing triggered restart
```
I propose at least WARNING level, so it gets into the WebGUI.

Here. in the relevant crashed part
https://github.com/sabnzbd/sabnzbd/blob/2aa0dbd93d6c35af6665001728b012333ebda3b0/sabnzbd/__init__.py#L1005-L1006

and/or a WARNING here
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1569-L1571

@Safihre If OK, I create a PR

**Comment by sanderjo** [comment]
BTW: is there any check that the sabnzbd.Downloader thread was succesfully started at all?

I don't see it in

https://github.com/sabnzbd/sabnzbd/blob/2aa0dbd93d6c35af6665001728b012333ebda3b0/sabnzbd/__init__.py#L348-L349

**Comment by Safihre** [comment]
> BTW: is there any check that the sabnzbd.Downloader thread was succesfully started at all?
> 
> I don't see it in
> 
> https://github.com/sabnzbd/sabnzbd/blob/2aa0dbd93d6c35af6665001728b012333ebda3b0/sabnzbd/__init__.py#L348-L349

Not needed, since we do the check `is_alive`.

**Comment by sanderjo** [comment]
> > BTW: is there any check that the sabnzbd.Downloader thread was succesfully started at all?
> > I don't see it in
> > https://github.com/sabnzbd/sabnzbd/blob/2aa0dbd93d6c35af6665001728b012333ebda3b0/sabnzbd/__init__.py#L348-L349
> 
> Not needed, since we do the check `is_alive`.

Well, that is my point: as there is no `is_alive()` check immediately after `sabnzbd.Downloader.start()`, can SABnzbd be sure  the thread started at all?
Later on, `is_alive()` can say "crashed", but maybe the thread never started (and thus did not crash)?

Again, triggered by the mysterious https://forums.sabnzbd.org/viewtopic.php?p=125326#p125326 ... SAB says Downloader crashed, but I doubt it ever started.
