### ISSUE TITLE
Add a "Required" flag for a server

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1939]
This is a request to add a "Required" flag to a server and appropriate logic, so that if this server stops responding, say due to a billing or login issue, sabnzbd does not blindly proceed to empty a configured block account.

It should instead stall until the "Required" server starts responding again.

**Comment by puzzledsab** [comment]
I'll look into this of nobody else has already started.

**Comment by Safihre** [comment]
@puzzledsab I am a bit afraid this will mess with all the TryList's resulting in forever stuck downloads.. 
Or maybe there's a smart way to implement this?

**Comment by puzzledsab** [comment]
I was thinking of pausing SAB like the disk space check and trying again every few minutes. There might be edge cases where that's not ideal but I think it's preferable for most users.

**Comment by sanderjo** [comment]
> This is a request to add a "Required" flag to a server and appropriate logic, so that if this server stops responding, say due to a billing or login issue, sabnzbd does not blindly proceed to empty a configured block account.

This probably complicates things, so you can ignore it, but I'm wondering:
* your goal is to avoid exhausting your block accounts if Server1 is not serving articles, right?
* if so, what do you want if Server1 is responding correctly to the login, but saying "article not found" to the first x% of the articles of a certain post? You can expect Server1 to also not have the rest of the articles of that post, so you might consider stopping that post ... ?

**Comment by sanderjo** [comment]
> I was thinking of pausing SAB like the disk space check and trying again every few minutes.

Simple and clever!

I have one general wish for SAB: if SAB pauses itself, on the frontpage write in clear big letters WHY.
Could be:
- disk space
- schedule
- user pause
- required server not there
- ...

**Comment by Safihre** [comment]
> I was thinking of pausing SAB like the disk space check and trying again every few minutes. There might be edge cases where that's not ideal but I think it's preferable for most users.

Sounds actually like a good idea! 💡

**Comment by thezoggy** [comment]
sounds like an easy way to implement this would be to just add a flag on the server page that says, 'pause on issue/failure' so that way users can toggle that for whatever server. it may be their primary it may just be their block or whatever ?
