### ISSUE TITLE
[develop] WARNING: Cannot find web template: ... interfaces/Classic/templates/main.tmpl, trying standard template

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#194]
With the develop git version, I get:

WARNING: Cannot find web template: /home/sander/git/sabnzbd-2015-01-01/interfaces/Classic/templates/main.tmpl, trying standard template

Is this a bug, has Classic been discontinued in develop, or should I run a pre-init script (can't remember which one)?

**Comment by shypike** [comment]
Classic has been removed, but not thoroughly enough it seems.
I'll check.

**Comment by shypike** [comment]
It's not a bug.
Classic has been removed and you'll get the warning until you deselect "Classic" in Config_>General.
