### ISSUE TITLE
3.4.0 Beta 1 regression with "Ending the path with an asterisk * will prevent creation of job folders."

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1942]
Since 3.4.0 Beta 1, having a job pointing to a complete folder ending in * still creates a job folder.

**Comment by Safihre** [comment]
I tried, but couldn't reproduce with 3.4.0Beta2. 
What is your Category setting? And is there any Sorting involved?

**Comment by Cpuroast** [comment]
Hi,

No sorting involved, would have mentioned this as I know it can affect this. 

For anything affected by sorting, %dn.%ext drops the job folder.

**Comment by Cpuroast** [comment]
Ok, my bad, that issue was fixed in 3.4.0 Beta 2.

Didn't give Beta 2 much of a chance as it breaks most of my workflow without sorting, Beta 3 should be good.

**Comment by Safihre** [comment]
You could just download the latest build here: https://github.com/sabnzbd/sabnzbd/actions/runs/1130079507
