### ISSUE TITLE
sabnzbd for Synology DSM 7.0-41890

### ISSUE THREAD

**Issue by StrangeTrousers** [sabnzbd/sabnzbd#1944]
I recently upgraded my Synology NAS to DSM 7.0-41890 from 6.?. Everything works except that sabnzbd, installed from the community repo now fails due to an incompatibility of some sort. Python 3.8 is installed. Are there any plans to get this updated ?

**Comment by sanderjo** [comment]
Overview of packages supported on DSM7: 
https://github.com/SynoCommunity/spksrc/issues/4524

Sabnzbd DSM7:
https://github.com/SynoCommunity/spksrc/pull/4748
