### ISSUE TITLE
Upgrade DSM 6.2 to DSM 7 Sabnzbd reports Invalid file format, contact package developer.

### ISSUE THREAD

**Issue by Sweepr** [sabnzbd/sabnzbd#1945]
![afbeelding](https://user-images.githubusercontent.com/2857865/131890452-195b753e-d285-4f96-ab60-df4a75d9ac07.png)

**Comment by albino1** [comment]
DSM7 isn't supported yet.  Follow this pull request for more info:

https://github.com/SynoCommunity/spksrc/pull/4748

**Comment by Sweepr** [comment]
Thank you, i will close this as it is w.i.p.
