### ISSUE TITLE
Installer fails to update version number (Windows)

### ISSUE THREAD

**Issue by Gittyperson** [sabnzbd/sabnzbd#1954]
Just updated from 3.4.0 to 3.4.1 on two Windows 10 x64 PCs. 3.4.1 installs normally but Windows still reports 3.4.0 as the installed version.

HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\SABnzbd:
DisplayName and DisplayVersion both contain a 3.4.0 entry.

I assume this does not occur on a fresh SABnzbd installation (haven't tested).

**Comment by Safihre** [comment]
I can't reproduce, both clean installs and updates show the correct version.
This also didn't change between versions so it would be surprising if it just broke.
![image](https://user-images.githubusercontent.com/5703454/134964115-45872d4a-5859-4bc2-af85-836973393d49.png)

**Comment by thezoggy** [comment]
can confirm that normal install worked just fine on win10:
![ApplicationFrameHost_2021-09-27_18-54-57](https://user-images.githubusercontent.com/500882/135000649-3da4b993-f29d-4032-b677-f883c8fbc600.png)

**Comment by Gittyperson** [comment]
No, that "modern app" list was also on 3.4.1 for me.

**Comment by Gittyperson** [comment]
I can confirm the standard (non-silent) install properly updated the version numbers from 3.4.0 to 3.4.1 in the above registry entries. I will try a bit later with a silent install.

**Comment by Gittyperson** [comment]
Ok, did several re-checks. Looks like I cannot reproduce. Sorry for the time-waste.
