### ISSUE TITLE
Adding of .rar extension to rar parts (.r00 -> .r99)

### ISSUE THREAD

**Issue by HaArD2000** [sabnzbd/sabnzbd#1955]
Using 3.4.0 and 3.4.1

When downloading an nzb that contains a multi-part rar archive (r00-r99) the resulting files are saved with an extra .rar extension added to the end of the filename.

This is DOWNLOAD +REPAIR only, 

While queued the file list shows the proper file names (r00-r99)
While downloading the files in the Incomplete folder are correct (r00-r99)
After finished, the files in the Complete folder have an extra rar extension (r00.rar - .r99.rar)

This does not happen to the primary rar archive file (I do not get a .rar.rar file)

Downgraded to v3.3.1 and the behaviour stopped.

**Comment by Safihre** [comment]
@HaArD2000 can you confirm that the newer version that @thezoggy linked works for you?
Because I'm not 100% sure it's the same as #1952.

**Comment by Safihre** [comment]
If it doesn't work, could you enable Debug logging in the Status window and then after it happens again share the full log (click Show Logging in the Status window) through pastebin here?

**Comment by Safihre** [comment]
I can actually reproduce this, by just downloading a post set to just `Download` and not `+Unpack` etc and having `Deobfuscate finale filenames` turned on.

**Comment by Safihre** [comment]
Fixed!
