### ISSUE TITLE
Queue history API call does not return utf-8 in XML or JSON

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1956]
We have executed a test with some special characters in the nzb name.
The 3.4.0b webbrowser returns the following : 
![afbeelding](https://user-images.githubusercontent.com/6350469/135465687-4f3153b2-f878-4659-a4eb-f91e6d6200a0.png)

However, when we issue an api call to retrieve the history queue, in the XML or JSON everything is returned as ascii and not as utf-8. See files

[sab_hist_json.txt](https://github.com/sabnzbd/sabnzbd/files/7259913/sab_hist_json.txt)
[sab_hist_xml.txt](https://github.com/sabnzbd/sabnzbd/files/7259916/sab_hist_xml.txt)

**Comment by Safihre** [comment]
I think you didn't UFT-8 decode the response. We send the data with `Content-Type: application/json;charset=UTF-8` to indicate this. 
So you will need to decode the response with the UTF-8 codec.
The browser already does this, as you can see from the data being displayed correctly in the interface.

**Comment by mesa57** [comment]
Thank you for this hint.
It is solved now.
