### ISSUE TITLE
API: nonsense NZO value in change_opts leads to "ok"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#196]
API: nonsense NZO value in change_opts leads to "ok"

$ lynx --dump 'http://localhost:8080/api?mode=change_opts&value=SABnzbd_nzo_NONSENSE&value2=1'
ok

I would expect in something like "Not OK" or "not found"

**Comment by shypike** [comment]
It will return {Status:false} when the ID does not exist.
