### ISSUE TITLE
Sample-detection broken for `.par2` files

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1964]
Some users reported it on the forums, but now I also saw it myself: the sample detection based on `guessit` is just not working well enough.
Files like `last.week.tonight.with.john.oliver.s08e26.1080p.web.h264-glhf-sample.par2` or not detected as a sample.
@jcfp Maybe we should just go back to the old method with the super-simple regex?
Despite theoretical cases in which it would fail (as shown in the unittests), did we even get real-life complaints? I don't remember any.
Seems `guessit` just can't handle this well.

**Comment by thezoggy** [comment]
We have (I have). Why I ended up turning off sample detection and just let sonarr handle it. But I do agree the false positive is very rare
