### ISSUE TITLE
Sabnzbd causes high CPU use of GPU process in chrome

### ISSUE THREAD

**Issue by brianjmurrell** [sabnzbd/sabnzbd#1968]
When I have a sabnzbd window open on Chrome (95.0.4638.54 (Official Build) (64-bit) on Linux), the GPU process of the browser is **significantly** higher.  I don't see this with any other of 131 tabs I have open at the moment, so sabnzbd is definitely an outlier in this.

Observe:

Fresh chrome installation with no extensions, only 1 tab open on www.google.com:

![image](https://user-images.githubusercontent.com/559317/138159820-a842a039-767e-4510-9be0-fadaccec4649.png)

Now open sabnzbd in the only tab:

![image](https://user-images.githubusercontent.com/559317/138160012-3a3df50a-0d7e-4b38-ba43-05bd4e50bda4.png)

Why so much GPU process usage in chrome?  Particularly for what should be a pretty graphically un-intensive web-app.

**Comment by thezoggy** [comment]
from your output:
```
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

you have several things disabled, looking it appears that you have some unsupported hardware config which causes some of this. you could try using chrome://flags to force on with "Override software rendering list". 

but anyways I would say try another video driver / another computer and see if you can replicate it there. so far I cant replicate causing any gpu impact by sab gui (but granted I dont have anything in the queue but one thing or nothing at all).

are you seeing this issue when its idling or only with a lot of activity in the queue/history/page to be updating?

the fact that you had it set to not display update automatically (thus just idling) makes me highly think it has nothing to do with sab specifically. theres not really anything special on sab gui (basic html + javascript)
