### ISSUE TITLE
python[..]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by linuxfreak90** [sabnzbd/sabnzbd#1972]
This is on the latest SABnzbd running on KDE, anyone else having this issue?

I already tried to reset the configuration, but the issue keeps logged to the journal.

**Comment by puzzledsab** [comment]
Does it actually say [..] after python? If not, you should include it. You can remove the local part of the path.

**Comment by linuxfreak90** [comment]
@puzzledsab Sorry for leaving that part out, this is what journal is reporting:
```
nov 04 12:02:29 desktop python[11158]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
nov 04 12:02:30 desktop python[11158]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
nov 04 12:02:31 desktop python[11158]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
nov 04 12:02:33 desktop python[11158]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
nov 04 12:02:34 desktop python[11158]: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```
IT seems to happen every second.

**Comment by jcfp** [comment]
Once per second gtk or gdk logging is likely to be from the system tray icon. If you don't use that, try disabling it in the special settings (uncheck _win_menu_). The underlying issue is probably something in gtk rather than sabnzbd though.

**Comment by linuxfreak90** [comment]
@jcfp Thanks, this seems to fix it. :)

Could it be a package issue? If the tray should be shown, it may be caused by a missing dependency.
I'm using [SABnzbd](https://aur.archlinux.org/packages/sabnzbd/) on Arch (btw.).

**Comment by jcfp** [comment]
There are two different backends that can be used for the statusicon in sab. If you don't currently have `xapp` installed, you might try and see if that makes a difference (after re-enabling the win_menu, of course). If installed, the Xapp code is automatically used in favour of the (deprecated) Gtk statusicon; with both unavailable (or no DISPLAY environment variable), the systray is simply not loaded.

**Comment by linuxfreak90** [comment]
@jcfp Thanks for the detailed information.

I don't have `xapp` installed. I'll the pkg and report back if this fixes the issue without having to uncheck `win_menu`. :)

**Comment by puzzledsab** [comment]
Might be related to #1970, it seems to be flashing once per second.

**Comment by thezoggy** [comment]
googling i see many bug reports all reporting it, looks like this is the main one though: 
https://gitlab.gnome.org/GNOME/epiphany/-/issues/1281
