### ISSUE TITLE
7zip - 21.xx

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1973]
21.04 beta is out and you can see the recent changes
https://www.7-zip.org/history.txt

just tossing this here so we can check back before sab 3.5 to see if there is final build thats worth including

**Comment by Cpuroast** [comment]
He usually has a really long dev cycle for any new major version, so I would be extremely surprised if 21 is declared stable by the time sab 3.5 is ready.

**Comment by Safihre** [comment]
> He usually has a really long dev cycle for any new major version, so I would be extremely surprised if 21 is declared stable by the time sab 3.5 is ready.

I was thinking the same! Didn't he also release a 20.x alpha last year (since version number is year number) and still no stable?

**Comment by thezoggy** [comment]
yes, 19.x = 2019, 20.x = 2020, and since its 2021 its 21.x. anyways if stable happens it will be 21.x. we've included alpha/beta releases before for utilities but mainy thing was just to put this on the horizon due to all the upgrades that 21.x has had and possible argument/cli output changes that come with it

**Comment by Dazog** [comment]
https://sourceforge.net/p/sevenzip/discussion/45797/thread/edcb38bbab/

21.05 is NON beta finally.

**Comment by thezoggy** [comment]
yep,

https://www.7-zip.org/

the 21.04->21.05 pretty minor but anways happy to see a non beta release finally out.
```
21.05          2021-11-20
-------------------------
- The window "Add to Archive" now allows to set a limit on memory usage (RAM) 
  that will be used for compressing.
- New switch -mmemuse={N}g / -mmemuse=p{N} to set a limit on memory usage (RAM) 
  for compressing and decompressing.
- Some bugs were fixed.
```
