### ISSUE TITLE
Sorting doesn't respect job name case

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1975]
Consider the following with these sorting options: %dn.%ext

Job Name: Some File with Some File Name.ext
File Name inside rar set: some file with some file name.ext

When unpack and sorting run, the end result is "some file with some file name.ext" and not "Some File with Some File Name.ext"

since %dn targets "Original Job Name", the expected file name is "Some File with Some File Name.ext"

As in the case of "Job Name" is completely ignored.

This happens with 3.4.2 and cbeab4dd55a12499ff3cc32d1fca440e0f24cfa7

**Comment by thezoggy** [comment]
as a side note, you should be able to wrap the sorting token with `{}` to lowercase the end result.

but post logs so we can see exactly what the logic is doing as there are things like flat unpack / direct unpack / and other options that may be coming into play

**Comment by Safihre** [comment]
Could you send me an example NZB? All my test NZB's have same casing inside+outside or have nonsense-filenames inside.

**Comment by Safihre** [comment]
@Cpuroast you didn't have any example NZB's for me anymore? Then I can try to fix it.

**Comment by albino1** [comment]
Seems like this would be pretty easy to test without a specific NZB.  Just rename the NZB file with aLtErNaTiNg caps or something and see what the result from sorting with `%dn.%ext` is.

Correct: aLtErNaTiNg.mkv
Incorrect: Alternating.mkv

**Comment by Safihre** [comment]
@albino1 Of course, I did exactly that and I can't reproduce..
So I need an example NZB..
