### ISSUE TITLE
Sabnzbd 3.4.2 again slower

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#1977]
We delivered a new spotnet version together with sabnzbd 3.4.2 (windows).
And again a high-speed downloader reports an issue.

(translated from dutch with google)

__
Hey
the requested information.
I had already figured out how to connect an external sabnzb to spotnet.
When I work with spotnet original with the built-in sabnzb 3.4.2 the download speed comes to a max of 74 mb/sec.
Now I still had the sabnzb 3.2.0 and I linked it again to spotnet and the download speed is as usual, namely 110 mb max per sec
I have no idea why this is but I prefer the high speed anyway. :D
I think the limitation comes from the higher version of sabnzb 3.4.2 anyway.

BEST REGARDS
++

**Comment by Safihre** [comment]
I want to help.. but with this limited information, what are we supposed to do?

**Comment by mesa57** [comment]
Because the information has been passed to us by a user, we also have not more info.
None of our team members have a high speed download connection, so we cannot execute a test.
We are trying to get as much info as possible from the user.
What information do you want ?

PS. De user reported his setup

```
OS: Windows 10 Home (v10.0.19043) | X64 | | Nederlands
Windows directory: C:\WINDOWS
Processor: Intel(R) Core(TM) i7-9700T CPU @ 2.00GHz
Geïnstalleerd geheugen (RAM): 16 GB
Microsoft Net Framework 4 v4.8.04084
Anti-Virus/Firewall: Ziggo Safe Online by F-Secure - Ingeschakeld
C:\WINDOWS\System32\ieframe.dll v11.0.19041.1348
ieframe.dll gemaakt op: 09-11-2021 23:34 | gewijzigd: 09-11-2021 23:34
C:\Program Files (x86)\Spotnet\Spotnet.exe v1.9.0.7 | SABnzbd.exe v3.4.2
Downloadknop: Externe SABnzbd 

```
usp : hitnews via ssl

**Comment by Safihre** [comment]
The user can report here or on our forums directly. I'm a bit annoyed by the style of this ticket: "it's slower, go fix". 
There can be numerous reasons for it, but we would need some direct contact with the user.
If the release in general was significantly slower, we would expect to have many reports. But we don't... We have thousands of installs a week, so plenty of people would have noticed.

**Comment by mesa57** [comment]
Sorry that we have bothered you.

**Comment by thezoggy** [comment]
new install prob being flagged or no longer whitelisted/excluded by their antivirus. which is prob inspecting/slowing things down
> Anti-Virus/Firewall: Ziggo Safe Online by F-Secure - Ingeschakeld

tell them to disable that stuff and try again. but yes use forums or other places better for support. this is for bugs

**Comment by mesa57** [comment]
Thanks, we will do that (did already ask that, but received no reply yet).
And yes, it is better the user opens his problem on the forum.
