### ISSUE TITLE
Handle multiple passwords in the same nzb

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#1979]
As discussed in https://forums.sabnzbd.org/viewtopic.php?f=2&t=25621

**Comment by jcfp** [comment]
I'll look into this one when I have some spare time.

**Comment by puzzledsab** [comment]
I started looking at this because I wanted to make a branch called feature/multipass ;). The web interface part is a bit of a road block for me, though. It's only made for one password, so sharing data for the passwords(s) from the nzb and the user interface gets a bit messy. I think the easiest solution would be to have a password string attribute that contains a single password from the file name or entered from by the user, and an nzbpasswords list that contains the password(s) from the nzb. It would not be possible to edit the nzbpasswords attribute.

@Safihre : What do you think?

**Comment by Safihre** [comment]
Agreed, we can't show them all. It's exotic anyway.
Do we need to have an extra attribute? Why not just use the existing `NzoObject.nzo_info` or `NzoObject.meta` dicts?
