### ISSUE TITLE
OpenVPN issues

### ISSUE THREAD

**Issue by DrewL4** [sabnzbd/sabnzbd#1980]
When starting my Unraid container I am receiving this issue within the logs.

Options error: Unrecognized option or missing or extra parameter(s) in /config/openvpn/ord-004.ovpn:24: data-ciphers (2.4.7)

Thanks

**Comment by Safihre** [comment]
What are you talking about? This is for Sabnzbd issues..

**Comment by DrewL4** [comment]
My bad. I used the project page link on my sabnzbdvpn docker and it sent me here.

All good.
