### ISSUE TITLE
Bad CPU type on Apple Silicon M1 without Rosetta 2 installed

### ISSUE THREAD

**Issue by mreid-tt** [sabnzbd/sabnzbd#1991]
**Setup**

sabNZBd Version: 3.5.0Beta2 [b922274]
Python Version: | 3.10.0 (v3.10.0:b494f5935c, Oct 4 2021, 14:59:19) [Clang 12.0.5 (clang-1205.0.22.11)] [UTF-8]
OpenSSL 1.1.1l 24 Aug 2021

**Error Log**

```
2021-12-05 03:05:37,502::DEBUG::[nzbstuff:389] Finishing import on siDh4K3Fx1gKOSBt02a9oHz.part22.rar
2021-12-05 03:05:37,503::DEBUG::[__init__:923] [N/A] Loading data for SABnzbd_nzf_szele5vz from /Users/<USERNAME>/Documents/Transmission Files/incomplete/Invasion.2021.S01E09.Full.of.Stars.720p.ATVp.WEB-DL.DDP5.1.H.264-NTb/__ADMIN__/SABnzbd_nzf_szele5vz
2021-12-05 03:08:20,260::ERROR::[newsunpack:1158] Error [Errno 86] Bad CPU type in executable: '/Applications/SABnzbd.app/Contents/MacOS/osx/par2/par2-sl64' while running par2_repair on set <HASH>8ff2a3a
```

Details on the binary file called:

```
file /Applications/SABnzbd.app/Contents/MacOS/osx/par2/par2-sl64
/Applications/SABnzbd.app/Contents/MacOS/osx/par2/par2-sl64: Mach-O 64-bit executable x86_64
```

This seems to be an executable that needs to be upgraded to an arm64 version for those who do not have Rosetta 2 installed (like myself). This would also apply to the following other binaries:

```
file /Applications/SABnzbd.app/Contents/MacOS/osx/unrar/unrar      
/Applications/SABnzbd.app/Contents/MacOS/osx/unrar/unrar: Mach-O 64-bit executable x86_64
file /Applications/SABnzbd.app/Contents/MacOS/osx/7zip/7za
/Applications/SABnzbd.app/Contents/MacOS/osx/7zip/7za: Mach-O 64-bit executable x86_64
```

**Comment by sanderjo** [comment]
> for those who do not have Rosetta 2 installed (like myself)

Daredevil! ;-)

For now: how technical are you?

https://www.rarlab.com/download.htm ... provides RAR 6.10 beta 2 for macOS ARM binary. That should be enough for a clean download & test

https://github.com/Parchive/par2cmdline provides source code for par2 ... are you able to compile?

**Comment by thezoggy** [comment]
The par2-sl64 we use is years old.. I checked recently and still no updates.

**Comment by mreid-tt** [comment]
Thanks for the tip @sanderjo, I manually installed arm64 versions as you suggested. I was able to get them from the following sources:

unrar: https://www.rarlab.com/rar/rarmacos-arm-610b2.tar.gz
7zip: https://www.7-zip.org/a/7z2106-mac.tar.xz

For par2 I did have to get this via homebrew as this was easiest:

```
brew install par2
cp /opt/homebrew/bin/par2 ~/Desktop
```

Once I had all the files, I renamed all the originals in `/Applications/SABnzbd.app/Contents/Resources` with a `.old` suffix and copied the new files in there. In some cases the new files were not the same name so I changed them to match the old name when I copied them in.

I attempted a re-download of the same file and everything went flawlessly. I think this was the reason I got another error before when it was trying to do an unpack while downloading -- 'restarting because of crashed assembler'. I'll do a few more tests but everything seems to be resolved with this workaround.

**Comment by sanderjo** [comment]
Cool. Well done.

Can you provide that par2 M1 binary somehow? Maybe via github?

FWIW: this is how SABnzbd source code handles par2 resp unrar for Windows 32-bit resp 64-bit, but I suppose @Safihre has a plan how to do it for AppleOS Intel versus M1

```
sander@stream13:~/git/sabnzbd$ file win/multipar/par2j.exe 
win/multipar/par2j.exe: PE32 executable (console) Intel 80386, for MS Windows

sander@stream13:~/git/sabnzbd$ file win/multipar/par2j64.exe 
win/multipar/par2j64.exe: PE32+ executable (console) x86-64, for MS Windows

```

```
sander@stream13:~/git/sabnzbd$ file win/unrar/UnRAR.exe 
win/unrar/UnRAR.exe: PE32 executable (console) Intel 80386, for MS Windows

sander@stream13:~/git/sabnzbd$ file win/unrar/x64/UnRAR.exe 
win/unrar/x64/UnRAR.exe: PE32+ executable (console) x86-64, for MS Windows

```

**Comment by mreid-tt** [comment]
Sure @sanderjo, I've created a repository at the following location and uploaded the originally download download cache from HomeBrew. This allows you to verify that the file digest matches the one which is published here: https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/par2.rb for arm64_monterey

This is the repository I created:
https://github.com/mreid-tt/par2--0.8.1.arm64_monterey

**Comment by Safihre** [comment]
For 3.5.0 I should have made the release notes more clear that indeed we still require Rosetta for the external tools. I spent enough time as it is on this M1 build.
@mreid-tt is there a problem with having Rosetta installed?

For the next release I can invest in getting dual-arch binaries for everything. Or maybe some external tools will require 2 seperate binaries to be included. For example the par2 version we currently include is faster than par2cmdline.
Hopefully by that time Unrar will also have a stable release for M1.

**Comment by sanderjo** [comment]
@Safihre I thought it was a matter of:
* detecting AppleOS on M1 / AppleSilicon / ARM, just like it's done for WIN32 versus WIN64, so in SABnzbd.py and/or __init__.py
* providing the binaries in the directory osx
* biggest thing: decide on a name for the above: MACARM, DARWINARM, OSXARM, or something with "Apple Silicon". Not "M1" as that is only the name of the first processor.

Am I missing something? If not, is it OK if I provide a PR?

**Comment by mreid-tt** [comment]
> For 3.5.0 I should have made the release notes more clear that indeed we still require Rosetta for the external tools. I spent enough time as it is on this M1 build. @mreid-tt is there a problem with having Rosetta installed?

Hey @Safihre, there is no problem have Rosetta 2 installed per-se. I guess you would say I'm an M1 purist and I don't have anything installed that needs it. I really appreciate all the effort you and other developers have put towards the arm64 transition.

> For the next release I can invest in getting dual-arch binaries for everything. Or maybe some external tools will require 2 seperate binaries to be included. For example the par2 version we currently include is faster than par2cmdline on x86, even though it's ancient. Hopefully by that time Unrar will also have a stable release for M1.

That would be great! If there is anything I can assist with testing or feedback I'd be happy to do so.

**Comment by mreid-tt** [comment]
This still occurs in the most recent SABnzbd 3.5.0 Beta 3 so it's not resolved yet...

**Comment by sanderjo** [comment]
Maybe add to issue title: "with no Rosetta 2 installed"?

**Comment by mreid-tt** [comment]
> Maybe add to issue title: "with no Rosetta 2 installed"?

done

**Comment by Safihre** [comment]
> Current binaries which I used to patch SABnzbd 3.5.0 Beta 3 (`/Applications/SABnzbd.app/Contents/Resources/osx`):
> 
> unrar: https://www.rarlab.com/rar/rarmacos-arm-610b3.tar.gz 7zip: https://www.7-zip.org/a/7z2107-mac.tar.xz par2: https://github.com/mreid-tt/par2--0.8.1.arm64_monterey/raw/main/par2--0.8.1.arm64_monterey.bottle.tar.gz

@mreid-tt I spun up my cloud-M1 and the `brew` version isn't compiled with OpenMP (multi-threading) support.
I am now building a version that does include multi-threading support and will add that one.

**Comment by mreid-tt** [comment]
> @mreid-tt I spun up my cloud-M1 and the brew version isn't compiled with OpenMP (multi-threading) support.
> I am now building a version that does include multi-threading support and will add that one.

That's fantastic @Safihre, thanks for keeping me in the loop on this.

> Hopefully by that time Unrar will also have a stable release for M1

Just in time for your next build, they have as of this month:
https://www.rarlab.com/rar/rarmacos-arm-610b3.tar.gz
