### ISSUE TITLE
Modify/overide Show Name: %sN

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#1995]
Hi, I was wondering if there was a way to modify the default `%sN` script to make it respect Article capitalization (a, an, the) and a few other prepositions (of) in the middle of Titles. The reason behind this is I use the `%sN` and a lot of times I end up with multiple folders when release groups do not properly capitalize releases e.g Made up title
`Day of the Dead S01`
`Day Of The Dead S01`

Being able to select a list of words in the middle of the title to capitalize will go a long way in ensuring I only have one folder for any given show. It might not necessarily match the Capitalization used by TMDB/TVDB but for the most part, I'm just after being able to modify that %sN...preferably in the GUI.

Thanks.

**Comment by thezoggy** [comment]
Why not just wrap it on {} to lower case it always?

**Comment by ItsME6969** [comment]
> Why not just wrap it on {} to lower case it always?

OCD. I was using `%sn` before and I do not recall this problem, but my OCD preferred proper capitalization so I switched to `%sN` .
