### ISSUE TITLE
Setting ionice to anything breaks unrar version detection

### ISSUE THREAD

**Issue by gregf** [sabnzbd/sabnzbd#1996]
When I set the ionice value to say -n19 on my nas sabnzbd thinks my version of unrar is 0.0 and stops extracting files. I'm on sabnzbd version. 3.4.2 [cc831e1].

**Comment by puzzledsab** [comment]
Are you sure 19 is a valid selection on your system? It's not the same values as nice.

**Comment by Safihre** [comment]
Seems indeed it should be `0-7`: https://linux.die.net/man/1/ionice

**Comment by gregf** [comment]
Oops, that is a big screw-up on my part. Sorry everyone.

**Comment by Safihre** [comment]
This solved the problem?

**Comment by gregf** [comment]
@Safihre Seems to have, I'll reopen if it crops back up. Sorry I wasted everyone's time!
