### ISSUE TITLE
snap of 3.5 rev 3520+ ships Python 3.6.9, fails to run, says it requires Python 3.7 or above

### ISSUE THREAD

**Issue by degville** [sabnzbd/sabnzbd#1997]
sabzbd snap rev 3515 on x86 works as expected, even with Python 3.6.9.

sabzbd snap revs 3520, 3531, tested on x86 and a Raspberry Pi 4, fail to run the daemon:

## Log output

```bash
$ sudo snap logs sabnzbd
2021-12-16T14:44:55Z sabnzbd.sabnzbd[2445]: Sorry, requires Python 3.7 or above
2021-12-16T14:44:55Z sabnzbd.sabnzbd[2445]: You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Failed with result 'exit-code'.
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Scheduled restart job, restart counter is at 5.
2021-12-16T14:44:55Z systemd[1]: Stopped Service for snap application sabnzbd.sabnzbd.
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Start request repeated too quickly.
2021-12-16T14:44:55Z systemd[1]: snap.sabnzbd.sabnzbd.service: Failed with result 'exit-code'.
2021-12-16T14:44:55Z systemd[1]: Failed to start Service for snap application sabnzbd.sabnzbd.
```

## Snap runtime environment

```bash
$ snap run --shell sabnzbd
graham@raspberrypi:/$ python3 --version
Python 3.6.9
```

**Comment by Safihre** [comment]
I know, that's why 3515 is the latest stable.

I tried to fix this, but got hit so many weird snapcraft errors.
Snapcraft is a terrible system for developers, it's a pain to work with.
I wish we never made a snap.

**Comment by degville** [comment]
Fair enough - thanks for the update. Stable on the Raspberry Pi is stuck on 3520 for some reason, so that isn't working. I'll try and fix the snap myself and propose a PR if I get it working. Thanks again.

**Comment by Safihre** [comment]
That would great, if you have the time.
I configured a Ubuntu 20.04 VM to make the changes and build locally (already taking quite some time), but it refuses to run even 3 seconds of the `snapcraft` build steps, failing with some weird error. So I gave up.

**Comment by Safihre** [comment]
@degville It seems to have worked.
Can you confirm the 3532/3533/3534 versions are working?

**Comment by degville** [comment]
They do seem to be working for me. I've not been able to try 3533, but:
3534 is working for me on Rapberry Pi OS/armv7l
3532 is working for me on amd64 KDE Neon.

**Comment by Safihre** [comment]
I'll publish them and see if users start to complain!

**Comment by timeu** [comment]
So I tried 3534 on Raspberry Pi4 (Raspbian GNU/Linux 10 (buster, armv7l) and it seems to work fine in general however for some reason, the 7zip-full dependency is not properly installed inside the snap package. 
I get following error: 
```
root@raspberrypi:~# snap run --shell sabnzbd
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
root@raspberrypi:/root# which 7za
/snap/sabnzbd/3534/usr/bin/7za
root@raspberrypi:/root# 7za
/snap/sabnzbd/3534/usr/bin/7za: 2: exec: /usr/lib/p7zip/7za: not found
```
Install 7zip-full manually (outside of the snap package) works fine and will also install the binaries into `/usr/lib/p7zip/`:
```
root@raspberrypi:~# ls -la /usr/lib/p7zip/7za
-rwxr-xr-x 1 root root 1132724 Feb  5  2018 /usr/lib/p7zip/7za
root@raspberrypi:~# dpkg -l | grep 7zip
ii  p7zip                                                       16.02+dfsg-6                            armhf        7zr file archiver with high compression ratio
ii  p7zip-full                                                  16.02+dfsg-6                            armhf        7z and 7za file archivers with high compression ratio
```
Due to the confinement the sabnzbd inside the snap can't access/see the `/usr/lib/p7zip/`

**Comment by Safihre** [comment]
Could you open a new issue for it? Maybe @degville can be of help 😊
