### ISSUE TITLE
Suggestion: let SABnzbd tell on main page the status of (non)downloading

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#200]
Based on the questions in the forum it seems SABnzbd sometimes is not downloading for a reason unclear to the user.

So, suggestion: let SABnzbd tell on main page the status of (non)downloading. I'm assuming SABnzbd does know why it is not downloading.
Possible status messages:

"SABnzbd is downloading"
"SABnzbd is overall paused"
"SABnzbd is not downloading, because there is nothing the queue"
"SABnzbd is not downloading, because there are only paused items in the queue"
"SABnzbd is not downloading, because there is no working newsserver defined or available"
"SABnzbd is not downloading, because there is no networking connectivity"
"SABnzbd is not downloading, because the scheduler instructed so"

Would this be feasible and useful?

**Comment by war59312** [comment]
+1 Very useful.

**Comment by shypike** [comment]
I suppose the status could be a bit clearer, but SABnzbd doesn't always know the reason. "No network connectivity" is not a trivial thing to find out without probing some external site all of the time.
An empty queue is visible and "no servers" is already reported.

**Comment by sanderjo** [comment]
"probing some external site." ... I think that would be an interesting idea too: at SAB startup, or in Test Server, pick a newsserver from a long list of known newsserver, a see if NNTP session can be initiated.

**Comment by thezoggy** [comment]
sab already hits up google on start...

**Comment by Safihre** [comment]
Could it possibly be put in the API a notification if the scheduler has paused the queue?
This way I can put a notification in Glitter template. 
Together with the dashboard function, we can then deal with all situations.

**Comment by shypike** [comment]
Which API function do you suggest?

**Comment by Safihre** [comment]
last_schedule_event: <timestamp> <action> <parameter>

In that case we can put in the template a little clock-icon if there was an event in the last 6(?) hours, on hover it would show what the event was.

**Comment by Safihre** [comment]
Although I really like this idea, over the past year I couldn't come up with a reliable way of giving such information.
So closing it for now. Unless somebody has a good idea when to throw warnings?
