### ISSUE TITLE
7z: better, explicit detection of problems with password protected 7z files in newsunpack.py ... also to make the code cleaner

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2003]
Summary: better, explicit detection of password protected 7z files in newsunpack.py, with goals:
1) make 7z error handling more correct: detect password problems explicitly. No more false reports
2) make the code cleaner. Now it looks hacked together.

So ... @Safihre  ok if I do that (after my existing PR is accepted)?

Long:

sabnzbd/newsunpack.py does not explicitly detect problems due to missing/wrong passwords, but defaults to it. See (https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1001) if other checks (https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1052-L1055) did not kick in.

That caused the false password-error-message, now solved by https://github.com/sabnzbd/sabnzbd/pull/2000 (hooray for PR 2000!)

Anyway, from `man 7z`
```
DIAGNOSTICS
       7-Zip returns the following exit codes:
              0      Normal (no errors or warnings detected)
              1      Warning (Non fatal error(s)). For example, some files cannot be read during compressing, so they were not compressed
              2      Fatal error
              7      Bad command line parameters
              8      Not enough memory for operation
              255    User stopped the process with control-C (or similar)
```

So `ret == 2` is Fatal (so not just Password-problem).

7z across OS and versions is clear if there is password problem:

`ERROR: Data Error in encrypted file. Wrong password? : 100MB.bin`

So my proposal:
* check for that error message, and report it as such
* else: say something like "unknown 7z error message". The Debug logging should then help.

**Comment by Safihre** [comment]
Closed by f3cd5b06fa9b80d6eb16f29d71dcd176145599f1
