### ISSUE TITLE
Suggestion: Save hosts for Auto reporting

### ISSUE THREAD

**Issue by jeff2001** [sabnzbd/sabnzbd#201]
When clicking report on a failed download and choosing "out of retention" one has to manually select the host each time. If you have a setup where you have a main host with a few block hosts as backup then reporting a few times for each download that's out of retention becomes tedious. It would be great if you could setup the hosts used in the config and then just click  "out of retention" once without selecting hosts.

**Comment by Safihre** [comment]
Now possible in the new skin Glitter:
![untitled](https://cloud.githubusercontent.com/assets/5703454/8765650/3b31d7f4-2e16-11e5-9a04-e0eb013768d2.png)
