### ISSUE TITLE
"Deobfuscate final filenames" unwanted rename: .xml >. xml.txt

### ISSUE THREAD

**Issue by AbsenceJam** [sabnzbd/sabnzbd#2014]
3.4.2, Windows 10, Brand new & existing configs

With "Deobfuscate final filenames" enabled .xml files from blu-rays (at least) are being renamed to .xml.txt.

They're definitely named .xml in the RARs and with "Deobfuscate final filenames" disabled they are not renamed.

I've tested .nzbs for 4 different blu-rays, example paths across these:
BDMV\META\DL\bdmt_xxx.xml (xxx=eng,deu,etc)
BDMV\AUXDATA\bdtmdlist.xml
Various in BDMV\JAR/00001 (except resourcesettings.xml for some reason)

**Comment by sanderjo** [comment]
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/utils/file_extension.py contains the list of well-known extensions.

... and .xml is not in there. Ouch. I'll take care of that.

Thanks for reporting.

**Comment by sanderjo** [comment]
Oh, PS:

can you give an overview of all extensions on Bluray disk?

**Comment by AbsenceJam** [comment]
These are all the extensions found across about 400 discs:
.bbd,.bdjo,.bdl,.bdmv,.bin,.cci,.cer,.cfg,.clp,.clpi,.cmap,.crl,.crt,.csv,.dat,.db,.evt,.fontindex,.grn,.hcf,.iav,.in,.inf,.jar,.jpg,.lst,.m2ts,.map,.mdk,.miniso,.mpl,.mpls,.nbi,.otf,.png,.pqj,.properties,.sf,.sig,.sn,.tbl,.tca,.txt,.tym,.vyz,.wy,.xig,.xml,.xrl,.xrt
In addition some have an extensionless file "_dsa_version_"

Quite a few of the above extensions are one-offs in the Java folders where it appears arbitrary extensions were used/chosen for a given disc. So there could be more...

**Comment by thezoggy** [comment]
perhaps it might be easier to just detect if its a bluray from the release/job name rather than the extracted results?

also could do some dir checks to assume if its a bluray, like  `BDMV` or `BDSVM`
https://en.wikipedia.org/wiki/Blu-ray#Directory_and_file_structure

**Comment by Safihre** [comment]
Closed by #2020

**Comment by sanderjo** [comment]
@AbsenceJam can you try the Windows binary on https://github.com/sabnzbd/sabnzbd/actions/runs/1674226667 with your Bluray download wrongly getting renamed? And then report back the result.

**Comment by AbsenceJam** [comment]
I tried a couple of the problem NZBs. First was good, .xml stayed as-is.

The second contained .crt files that were renamed to .crt.cat:
BDMV|CERTIFICATE\BACKUP\app.discroot.crt
BDMV|CERTIFICATE\BACKUP\bu.discroot.crt
BDMV|CERTIFICATE\app.discroot.crt
BDMV|CERTIFICATE\bu.discroot.crt

**Comment by sanderjo** [comment]
> The second contained .crt files that were renamed to .crt.cat:
> BDMV|CERTIFICATE\BACKUP\app.discroot.crt
> BDMV|CERTIFICATE\BACKUP\bu.discroot.crt

Is there a vertical line / pipe symbol between `BDMV` and `CERTIFICATE` ?

The new code triggers on `"video_ts", "audio_ts", "bdmv"` , so a directory with name `bdmv` should stay untouched

**Comment by AbsenceJam** [comment]
Pipe is a typo and the path is plain wrong, sorry. It's \CERTIFICATE not BDMV\CERTIFICATE. So that'd be the problem. :)

It should trigger on these directories (all found in the root):
0012FA,ANY!,AUDIO_TS,BDMV,CERTIFICATE,FAB!,JACKET_P,KDM,VIDEO_TS
And .miniso wants adding to file_extension.py

Should all be good then.

Thanks

**Comment by sanderjo** [comment]
@AbsenceJam new binaries on https://github.com/sabnzbd/sabnzbd/actions/runs/1676452818 ... can you try again, and report back?

**Comment by AbsenceJam** [comment]
That's done the trick. Tested with a few previous problem ones and a couple of randoms - all files present with the correct names.

Thank you very much
