### ISSUE TITLE
Docker images are stale

### ISSUE THREAD

**Issue by ieure** [sabnzbd/sabnzbd#2015]
My sabnzbd has been complaining that there's a new version for a while, but it looks like the [`latest` tag on Docker Hub](https://hub.docker.com/layers/sabnzbd/sabnzbd/latest/images/sha256-2ef9ebaacd299729ebd9dc9d7fc6f980a1abc1e96a96ff2f4e918b52fcfecc2f?context=explore) is still 3.3.1, even though the latest stable version is 3.4.1.

Is there an automated process that updates the Docker images which broke?  Or is it manual & not part of the release checklist?

**Comment by sanderjo** [comment]
not provided by the SABnzbd team.

See https://hub.docker.com/r/sabnzbd/sabnzbd ... it says "domibarton/docker-sabnzbd" ... so nudge him?

FWIW: linuxserver.io aka lsio provides uptodate images.

**Comment by ieure** [comment]
Hmm, okay.  I figured that since the organization was sabnzbd and [the user page](https://hub.docker.com/u/sabnzbd) says it's a community organization, that these were official images.

**Comment by sanderjo** [comment]
> I figured that since the organization was sabnzbd and [the user page](https://hub.docker.com/u/sabnzbd) says it's a community organization, that these were official images.

Confusing and annoying indeed.

**Comment by kudos** [comment]
Would it make sense to reach out to Dockerhub to eliminate what could be considered impersonation? I'm sure it's completely innocent, but it's still a risk for the actual sabnzbd org and their users.
