### ISSUE TITLE
[Suggestion] Per Category Cleanup

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2019]
The clean-up list at the moment applies globally but it would be nice if you could override at the Category level.
Usecase:
I usually delete all other files and samples when grabbing movies and tv but with music, I would like to keep the .nfo, the .jpeg, etc but my cleanup list deletes all, and I have to work around that.

**Comment by Safihre** [comment]
@ItsME6969 I don't think this is a feature that would be needed for many users. As such I would recommend you use a post-processing script instead to remove unwanted files. This way you can only run that script on the categories you want.
In Python this would be quite easy: https://sabnzbd.org/wiki/scripts/post-processing-scripts

**Comment by ItsME6969** [comment]
@Safihre I understand. I have no coding skills and would appreciate if you could guide/provide me with a sample script that does just that. What I need is simple... if category==music...skip post processing. Thats all I need. Thanks.

**Comment by thezoggy** [comment]
Just set that category not to do +delete?

**Comment by ItsME6969** [comment]
@thezoggy I guess that works but now the problem becomes I have to manually delete the .rar files. I guess maybe i'm complicating a simple issue and I didnt mean to skip post processing entirely. My normal clean-up list is `jpg, png, srr, txt, idx, sub, nzb, exe, bat, url, com, par2, nfo, sfv, nfo` but with music I want it to but post process as usual except do not touch these `.nfo, .sfv, .jpg`  (which are usually a part of scene releases) and still delete the split rar files.

**Comment by thezoggy** [comment]
So don't use cleanup and just set a post processing script for the categories you need it for

**Comment by ItsME6969** [comment]
... and back to step 1 again...I have no programming skills.
Anyway it's all good it's not too much a bother as it is, I was just trying to better automate my setup. Thanks for the help.

**Comment by thezoggy** [comment]
Perhaps you could use this existing script
https://github.com/Drewster727/sabnzbd-postprocess-videos

**Comment by ItsME6969** [comment]
I'll look into it @thezoggy . Thanks.
