### ISSUE TITLE
Ignore video rating for certain categories.

### ISSUE THREAD

**Issue by jeff2001** [sabnzbd/sabnzbd#202]
The filtering for downloads works very well if the download has both audio and video, however if the download is Audio only (mp3 etc) often people rate the video as 0, as such it then gets filtered when it is a perfectly good download. It would be great if you could set the filter to ignore video rating on certain categories.

**Comment by oznzb-dev** [comment]
a zero is treated as not rated and shouldn't stop it downloading.  likewise a release with 0 audio and 0 video will not be stopped on these scores as it is considered not rated.

**Comment by jeff2001** [comment]
My mistake, it must be lower ratings like a half star or 1 star that stop the downloads. Either way audio downloads can get rated by video.
