### ISSUE TITLE
nscript_parameters value does not accept quotes

### ISSUE THREAD

**Issue by brunobraga** [sabnzbd/sabnzbd#2021]
I am using NZB-Notify for Slack notifications, with the settings:
`
nscript_script = sabnzbd-notify.py
nscript_parameters = complete "%2" "%3" slack://<...>/<...>/<...>/sabnzbd
`

 From the UI, I noticed it only shows "complete" in the parameters even though everything is in  the INI file. But if you press "Save" in that section, it actually overrides the value to "complete", which means that integration no longer works.

The UI's HTML code is as below:

`
<input type="text" name="nscript_parameters" id="nscript_parameters" value="complete " %2"="" "%3"="" slack:="" <...>="" <...>="" <...>="" sabnzbd"="">
`
which is clearly broken. 

Maybe you are meant to wrap it on another script and just point to this but it would be nice to work as intended.

**Comment by Safihre** [comment]
That's indeed pretty basic HTML-escaping stuff that we should fix!

**Comment by Safihre** [comment]
Fixed, could you try the new builds?
https://github.com/sabnzbd/sabnzbd/actions/runs/1677078777
