### ISSUE TITLE
FYI: UnRar 6.10 breaks Direct Unpack

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2024]
If anyone is already trying to use the UnRar 6.10 beta releases with SABnzbd, we (@sanderjo + me) noticed that it breaks Direct Unpack.
The option `-vp` that we use for Direct Unpack no longer pauses UnRar before each file, as soon as it sees the next file, UnRar just continues.
As the Assembler might still be decoding that file, UnRar will crash with some CRC/checksum error.

As the `-vp` option is listed in `unrar --help` as:
```
  vp            Pause before each volume
```
I reported this to Rarlab as a bug, and hope they fix it for the final release.

**Comment by sanderjo** [comment]
FWIW: 
unrar 6.02 is OK with directunpack.  https://www.rarlab.com/rar/rarlinux-x64-6.0.2.tar.gz
There seems to be no versions available between 6.02 and 6.10 beta3

**Comment by sanderjo** [comment]
Update: thanks to @Safihre's report , newer version of unrar 6.10 beta 3 (released 2022-01-11) is working OK again on my Ubuntu: SAB is doing Direct Unpack again.

Strangely enough, the name is the same: unrar 6.10 beta 3. But, luckily enough, you can see a difference by running it:

```
sander@brixit:/usr/bin$ ./unrar.610.beta3.2021 | head -3

UNRAR 6.10 beta 3 freeware      Copyright (c) 1993-2021 Alexander Roshal
```
versus
```
sander@brixit:/usr/bin$ ./unrar.610.beta3-2022-jan-11 | head -3

UNRAR 6.10 beta 3 freeware      Copyright (c) 1993-2022 Alexander Roshal
```


The difference is ... the year in the copyright: 2021 (bad) versus 2022 (good)

... which you can also check in your sabnzbd.log (if DEBUG is on):


```
$ cat ~/.sabnzbd/logs/sabnzbd.log | grep -i Roshal
UNRAR 6.10 beta 3 freeware      Copyright (c) 1993-2022 Alexander Roshal
```

**Comment by thezoggy** [comment]
Side note, change in 6.10

> Warning is issued if entered password exceeds the allowed limit
      of 127 characters and is truncated. > Previously such passwords
      had been truncated silently.


Might need to handle that warning / or just truncate pw to be under length limit?

**Comment by Safihre** [comment]
I have been into contact with Eugene Roshal and he fixed my blocking-problem, the Beta3 has been updated and it works again!

**Comment by sanderjo** [comment]
Nice. Still all under the name 6.10beta3 ... So hopefully this helps:


```
$ ll /usr/bin/unrar.*
-rwxr-xr-x 1 root root 347152 okt 19  2020 /usr/bin/unrar.5*
-rwxr-xr-x 1 root root 355344 dec 13 20:55 /usr/bin/unrar.610beta3___2021*
-rwxr-xr-x 1 root root 355344 jan 12 11:06 /usr/bin/unrar.610beta3___2022-01-11*
-rwxr-xr-x 1 root root 355344 jan 13 14:27 /usr/bin/unrar.610beta3___2022-01-13*
```



```
$ md5sum  /usr/bin/unrar.610beta3*
3c57a56464d219c86155425e782f7f10  /usr/bin/unrar.610beta3___2021
a6c3366e35baf4925cd7c7545008ba39  /usr/bin/unrar.610beta3___2022-01-11
25d0592f20c30578568ec45887b625fd  /usr/bin/unrar.610beta3___2022-01-13
```
... so you now need the md5sum the determince what you have ...
