### ISSUE TITLE
Cannot delete failed job from history

### ISSUE THREAD

**Issue by TheGeneral007** [sabnzbd/sabnzbd#2025]
I am unable to delete an item, by pressing the Waste-bin-icon. 
I was doing this before and it all worked, but then a question popped up and I misinterpreted this one and thought it asked me to not confirm again, but now it totally doesn't ask me to delete again. 
Where can I find this option to undo this setting ? 
I know I have mistakenly put a checkmark to not ask again, but now I cannot find it anywhere in the properties, to undo this setting. 
Can you please advise on where to find it ?

**Comment by TheGeneral007** [comment]
I restarted the SABnzbd-service for the second time and now it works again.

**Comment by Safihre** [comment]
It's a browser setting, not Sab.
