### ISSUE TITLE
A recent change interferes with RSS feeds

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#2026]
I'm running sabnzbd from source, python 3.9.9 on OpenSUSE Leap 15.3. After updating to commit de484646613dea711590e3a8ad743aa28412ad31 two days ago and restarting sabnzbd, the next day I noticed a problem with my RSS feeds when trying to add a new feed.

The feeds I use have the format `https://<indexer API URL>/api?t=search&apikey=<apikey>&cat=<category number>&q=<search terms>`. The feeds overview page (/sabnzbd/config/rss/) usually shows them like this. Yesterday however they all looked like `https://<indexer API URL>/api?t=search&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;apikey=<apikey>&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;cat=<category number>&qamp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;q=<search terms>`. `&amp;` is HTML code for the ampersand (&) sign used by those URLs, so I suspect that might have been caused by commit fd28a8b42726eae8e9c10e882905ccb60c456629 (Escape all HTML on template-based pages ).

The malformed URLs with the many `amp;s`were also shown in the window that opens when editing a feed URL. While the existing feeds apparently still worked (I found several very recent downloads from those feeds sitting on my disk), copying the URL with the many `amp;s` from the edit window to use as a basis for a new feed URL resulted in that feed not working. So I went back to the commit immediately prior (b390e5de985f5cb2b81f6381a2195dbc04f70eb4) to the suspected culprit, and as of today, one day later, I can say that this seems to have solved part of the problem. Only part, because the malformed feed URLs were still there in the feeds overview page (which means they were probably written to the RSS data file), and now those feeds did not work anymore. I spent several hours cleaning up those URLs by hand (yes, I have that many feeds). With all of the URLs cleaned, the feeds are working again, and I didn't see any more `amp;s` being created in the URLs.

Sorry, I can't provide any logs, I looked, but all of them are from today, and unfortunately I did not save any from yesterday (was busy and had to go after cleaning up URLs for hours). And right now I won't update and repeat this whole experience. Only one observation: The 17 `amp;s` in the feed URLs I saw yesterday could correspond to the number of sabnzbd restarts - I have an automated restart every hour, started that a long time ago (probably with some 0.7 version) to combat memory leaks.

**Comment by thezoggy** [comment]
adding an rss feed to sab 3.5rc3 I can confirm that `&` get replaced with `&amp;`. then if you edit the rss then save without changes. `&amp;` turns into `&amp;amp;`

**Comment by sanderjo** [comment]
Ouch! I tried by adding one RSS feed, and now all my RSS feeds have amp's in them. Brrr.

**Comment by ErikBrown2** [comment]
Also filters with a ' are affected.

**Comment by Safihre** [comment]
Interesting, the problem seems to be that the HTML-filtering actually modifies the original settings dictionary, since it's a direct reference. Even navigating between pages on the RSS page creates the problem, no need to save.

I can fix it with a `copy.deepcopy` but I want to understand it a bit better.

**Comment by Safihre** [comment]
New builds available: https://github.com/sabnzbd/sabnzbd/actions/runs/1708090447

Can you confirm this fixes it?

**Comment by ErikBrown2** [comment]
It works indeed fine now

**Comment by sanderjo** [comment]
... and solved in SAB 3.5.0 RC4 "RSS-feed URLs were corrupted."
