### ISSUE TITLE
Text Alignment on Menu Bar Status

### ISSUE THREAD

**Issue by DaveFlowberries** [sabnzbd/sabnzbd#2028]
I have Monterey 12.1 on 14 inch Macbook Pro using SABnzbd 3.4.2 [cc831e1]. When connected to an external monitor it gets cut off like this:
<img width="169" alt="Screen Shot 2022-01-14 at 11 12 33 PM" src="https://user-images.githubusercontent.com/25303159/149538901-0d131278-9533-4e60-a6d6-ac88ff81ff6c.png">

Without a external monitor connected it's not cut off, but it is smashed up towards the top of the menu bar like this: 
<img width="99" alt="Screen Shot 2022-01-14 at 11 12 44 PM" src="https://user-images.githubusercontent.com/25303159/149539065-76f4a106-b3b4-40d3-a946-e00c95de0c66.png">

**Comment by Safihre** [comment]
Strange, I can't reproduce on my Mac Pro with macOS 12.1.
It also seems something is going wrong with the color, since the arrow should be white.
Very strange..
Anyone else experiencing this?

**Comment by thezoggy** [comment]
@DaveFlowberries are you using any 3rd party apps that modifies the menubar?

**Comment by Cpuroast** [comment]
You could also try 3.5.0RC4 and see if it behaves the same:

https://github.com/sabnzbd/sabnzbd/releases/download/3.5.0RC4/SABnzbd-3.5.0RC4-osx.dmg

**Comment by DaveFlowberries** [comment]
> @DaveFlowberries are you using any 3rd party apps that modifies the menubar?

Nope no 3rd party app that modifies the menubar. 



> Strange, I can't reproduce on my Macbook Pro with macOS 12.1. It also seems something is going wrong with the color, since the arrow should be white. Very strange.. Anyone else experiencing this?

There was other people experiencing the same issue but it was a closed issue and I was told to open a new issue, so I did.

**Comment by Cpuroast** [comment]
I also don't experience this on my test macOS 12.1 VM in VMware Fusion, so I'm not sure what's going on.

**Comment by DaveFlowberries** [comment]
> I also don't experience this on my test macOS 12.1 VM in VMware Fusion, so I'm not sure what's going on.
> 
> 14" Macbook Pro is M1 for which there was quite a bit of work done in 3.5.0, so its definitely worth trying 3.5.0RC4:
> 
> https://github.com/sabnzbd/sabnzbd/releases/download/3.5.0RC4/SABnzbd-3.5.0RC4-osx.dmg

Boom! That did it. Thanks for the help, it's perfect now on both the laptop screen and external monitor!

<img width="100" alt="Screen Shot 2022-01-24 at 1 15 20 PM" src="https://user-images.githubusercontent.com/25303159/150725958-46b35938-dc1a-49f2-abb6-6c1bc8b3f7d2.png">
 
<img width="148" alt="Screen Shot 2022-01-24 at 1 13 40 PM" src="https://user-images.githubusercontent.com/25303159/150725955-c6e40824-417c-4f9b-ac60-8d0c58c1dd61.png">

**Comment by Safihre** [comment]
Great!
