### ISSUE TITLE
[Suggestion] External Access Message

### ISSUE THREAD

**Issue by PaulMDUK** [sabnzbd/sabnzbd#2029]
Any way to change the following text to something that doesn't tell external users what the underlying service is?

In interface.py:
_MSG_ACCESS_DENIED = "External internet access denied - https://sabnzbd.org/access-denied"

perhaps just
_MSG_ACCESS_DENIED = "External internet access denied"

TIA

**Comment by sanderjo** [comment]
> Any way to change the following text

Yes, like you say, in interface.py, with a sed command, or any other tool.
But if you want that, why is your SAB exposed to Internet?

Or do you mean in SAB for everybody? If so: if you promise that you will help all users then asking for help in the forum. 

It's a balancing act between security and user friendliness.

**Comment by Safihre** [comment]
Changed it so that if you disable `api_warnings` in Config > Specials, it will also prevent returning any textual responses.
It will just respond with HTTP 403.
