### ISSUE TITLE
network test host is not configurable

### ISSUE THREAD

**Issue by carbin** [sabnzbd/sabnzbd#203]
sabnzbd currently tries to connect to google.com for network diagnostics and to check IPv6 connectivity. This is hard-coded.

https://github.com/sabnzbd/sabnzbd/blob/6840a2ffa0e6a0004721b4ce4535aaa8b687c089/SABnzbd.py#L891
https://github.com/sabnzbd/sabnzbd/blob/6840a2ffa0e6a0004721b4ce4535aaa8b687c089/sabnzbd/newswrapper.py#L437

It would be preferable if the host that is used is configurable, for networks that cannot access google.com for whatever reason, or for people who simply don't want sabnzbd connecting to google.

**Comment by thezoggy** [comment]
could change out google for: http://ipv6.whatismyv6.com/
the problem with netflix, facebook, google, any about any major site that has v6 setup is that it could be blocked/not allowed.

**Comment by shypike** [comment]
Does whatsmyv6.com also have the phenomenal uptime of google.com?
I mean, if google.com is off-line, the internet might as well not exist :)

**Comment by thezoggy** [comment]
Google while may be up but could be blocked.. China for example.  

Could use github instead of google to test against

-----Original Message-----

**Comment by exussum12** [comment]
or an array of < 10 domains to check ? Best checks only google, internet down checks all 10 ?
