### ISSUE TITLE
keybinding: CTRL-C (Copy) jumps to Config. Plus: keybinding wishes

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2038]
Running https://github.com/sabnzbd/sabnzbd/commit/c1a8470

On the frontpage, when I select a text with my mouse ("History" for example), and type CTRL-C to copy ... SAB jumps to Config.

That is not what I want.

Wanted:
Plain C keypress: jump to Config
CTRL-C: do not catch that, do not jump to Config. Keep it a Copy command

Pinging @SKBotNL

**Comment by SKBotNL** [comment]
Ill try to fix this right now

**Comment by Safihre** [comment]
Fixed it. Leaving this open in case anyone finds more problems with the keyboard shortcuts.

**Comment by SKBotNL** [comment]
> Fixed it. Leaving this open in case anyone finds more problems with the keyboard shortcuts.

Seems good

**Comment by sanderjo** [comment]
> Leaving this open in case anyone finds more problems with the keyboard shortcuts.

May I also tell more wishes?

After pressing C (-> Config), I would to press a key to back to the main screen. "M"? "ESC"? "Backspace"?

Within Config, I would like to key-navigate to sub-options. Press G to go to General, F to Folders? Or press cursor-right (and cursor-left) to walk through the sub-options?

![image](https://user-images.githubusercontent.com/1273502/150682568-10947d84-4ae0-44ef-8b2f-ec70a48ff6f0.png)

**Comment by SKBotNL** [comment]
@sanderjo 
Seems like an interesting thing to add, I can try to do it (unless Safihre does it).

**Comment by Safihre** [comment]
@SKBotNL Go ahead :)

**Comment by SKBotNL** [comment]
> > Leaving this open in case anyone finds more problems with the keyboard shortcuts.
> 
> May I also tell more wishes?
> 
> After pressing C (-> Config), I would to press a key to back to the main screen. "M"? "ESC"? "Backspace"?
> 
> Within Config, I would like to key-navigate to sub-options. Press G to go to General, F to Folders? Or press cursor-right (and cursor-left) to walk through the sub-options?
> 
> ![image](https://user-images.githubusercontent.com/1273502/150682568-10947d84-4ae0-44ef-8b2f-ec70a48ff6f0.png)

Or just using 'C' again or would that be inconvenient?

**Comment by sanderjo** [comment]
> Or just using 'C' again or would that be inconvenient?

Well ... strange and confusing, IMHO. Pressing S gives Status, and then again S a new, refreshed Status (good!). So pressing C to go back would be counter-intuitive.

**Comment by SKBotNL** [comment]
> > Or just using 'C' again or would that be inconvenient?
> 
> Well ... strange and confusing, IMHO. Pressing S gives Status, and then again S a new, refreshed Status (good!). So pressing C to go back would be counter-intuitive.

You are right, that if you press S again it gets refreshed is unintended but pretty handy lol
