### ISSUE TITLE
Verify & Roll out new "Self-test" endpoint

### ISSUE THREAD

**Issue by jeffgeorge** [sabnzbd/sabnzbd#2039]
I'm working on streamlining some infrastructural things related to SABnzbd, and one thing I'd _really_ like to improve is the self-test endpoint, presently at https://self-test.sabnzbd.org

Self-Test is used [various places](https://github.com/sabnzbd/sabnzbd/search?q=selftest_host) throughout SABnzbd, primarily when we need to know about a user's public IP, if it's IPv4 or IPv6, and if they actually have outbound internet access, and presently it is managed on a server I run.

I've set up an alternative using [Cloudflare Workers](https://workers.cloudflare.com/), temporarily available at https://new-self-test.sabnzbd.org.

It's dead simple, One line of Javascript to return the requesting IP, but it needs testing before I can swap the hostnames around so the new CF Worker version is at `self-test.sabnzbd.org`, and the old one is moved to `legacy-self-test.sabnzbd.org` before eventually being deprecated. I've updated my personal SABnzbd instance and it seems to be working fine, but I have two limitations: I can't test the IPv6 side, and I'm not familiar enough with SABnzbd's internals to be sure I've hit all possible use-cases.

So this is a request for testing help. Once we're confident in this alternative I'll swap the hostnames around.

@sanderjo -- @Safihre suggested you may be able to help with the testing, specifically around IPv6. Does it seem to be working as expected from your side?

**Comment by jcfp** [comment]
The new-self-test address does return the correct ipv6 address when visited with a browser.

**Comment by sanderjo** [comment]
https://self-test.sabnzbd.org/ correctly reports my IPv6 address in my browser
https://new-self-test.sabnzbd.org/ also correctly reports my IPv6 address in my browser
https://legacy-self-test.sabnzbd.org/ does not work. Maybe I misread your comment?

new-self-test.sabnzbd.org does work within my SABnzbd: both IPv4 and IPv6 are shown.

**Comment by sanderjo** [comment]
> It's dead simple, One line of Javascript to return the requesting IP

That is **server-side** JS, I presume?

Out of curiosity: good old REMOTE_ADDR is not usable?

**Comment by jeffgeorge** [comment]
`legacy-self-test` hasn't been set up yet. When we're ready, I'm going to flip around like this:
* `self-test` -> `legacy-self-test`
* `new-self-test` -> `self-test`

. . . so we don't have to actually change anything withing SABnzbd, and it all just cuts over to the new service.

Regarding the implementation, the old implementation couldn't use PHP's `$_SERVER['REMOTE_ADDR']` because we're behind Cloudflare, but Cloudflare helpfully provides an environment variable for the requestor's IP. Same situation is available when running Javascript in Cloudflare's Workers environment, same environment variable and everything, I just have to extract it via JS.

For full transparency (and because it's so dead simple) I intend to publish our worker code (many lines of boilerplate, one line that Actually Does Stuff) in a new SABnzbd-owned repo, just want to get it tested first.

**Comment by Safihre** [comment]
@jeffgeorge go ahead and apply the change :)

**Comment by jeffgeorge** [comment]
All set, `self-test.sabnzbd.org` now routes to the CF worker. While it's not set up on a hostname, the old self test will still be running so we could revert to it for at least the next week if we encounter any errors if absolutely necessary.

If people report any errors with the self test please ping me directly in the issue to make sure it's on my radar to debug.
