### ISSUE TITLE
SABnzbd 3.5.0 crashes on launch in Mojave and older

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2046]
@Safihre SABnzbd 3.5.0 crashes launch in Mojave and older.

3.5.0 RC4 was fine, so something changed in the build process or the code between RC4 and Final.

Doing a full run test on 10.9 through 12 at the moment.
Will update the issue when I have tested all versions of macOS

**Comment by Safihre** [comment]
Could you run on terminal to see if maybe it's same as #2045? Because nothing changed indeed..

**Comment by Cpuroast** [comment]
macOS 10.9
macOS 10.10
macOS 10.11 Crash
macOS 10.12 Crash
macOS 10.13 Crash
macOS 10.14 Crash
macOS 10.15 Pass
macOS 11
macOS 12

**Comment by Cpuroast** [comment]
./SABnzbd 
Segmentation fault: 11

**Comment by Safihre** [comment]
Yes, we switched to Python 3.10.2 over 3.10.1.
Maybe you can confirm by testing this release: https://github.com/sabnzbd/sabnzbd/actions/runs/1729550319

**Comment by Cpuroast** [comment]
That build runs just fine:

Version:	3.5.0RC4 [a544548]
Uptime:	0m
Config File:	/Users/test/Library/Application Support/SABnzbd/sabnzbd.ini
Parameters:	"/Volumes/SABnzbd-3.5.0RC4/SABnzbd.app/Contents/MacOS/SABnzbd"
Python Version:	3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] [UTF-8]
OpenSSL:	OpenSSL 1.1.1m 14 Dec 2021

**Comment by Cpuroast** [comment]
Also, just tried this one:

https://github.com/sabnzbd/sabnzbd/actions/runs/1761064004

That one crashes on launch, the same as final.

**Comment by Safihre** [comment]
I think I found the problem, PyObjC is updated to 8.2 while the previous build was with 8.1.

**Comment by Cpuroast** [comment]
I can test a 3.5.0 build with the final code using PyObjC 8.1 to confirm.
If that fixes it, rolling back to 8.1 for now seems like the way to go, and release 3.5.0.1 using PyObjC 8.1.

**Comment by thezoggy** [comment]
Introducing a new number version scheme would not be good. But yes 3.5.1 would make sense since it's been a min since 3.5.0 has been released and a few hundred downloads already for the Mac binary

**Comment by Safihre** [comment]
@Cpuroast Build will be here: https://github.com/sabnzbd/sabnzbd/actions/runs/1763269074

If this one works, I do want to report this upstream. However, we have to identify if this is a PyInstaller+PyObjC problem or just a PyObjC problem.
Therefore, on one of the macOS versions on which it crashes, could you download Python 3.10.2 from www.python.org and run SABnzbd from sources.
By just running `pip3 install -r requirements.txt` it will pull in PyObjC 8.2.
If it also crashes when you run SABnzb from sources, it's just a PyObjC problem.

**Comment by Cpuroast** [comment]
As I mentionned earlier, the sab build with 3.10.2 and PyObjC 8.1 ran just fine:
https://github.com/sabnzbd/sabnzbd/actions/runs/1729550319

Version: 3.5.0RC4 [a544548]
Uptime: 0m
Config File: /Users/test/Library/Application Support/SABnzbd/sabnzbd.ini
Parameters: "/Volumes/SABnzbd-3.5.0RC4/SABnzbd.app/Contents/MacOS/SABnzbd"
Python Version: 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] [UTF-8]
OpenSSL: OpenSSL 1.1.1m 14 Dec 2021

I'll test the new build when it lands.

**Comment by Safihre** [comment]
@Cpuroast It's not about testing the release, in order to report this problem at the right place upstream we need to run it from sources so we can exclude the PyInstaller step that packs it into a release.

**Comment by Cpuroast** [comment]
The new build runs fine on 10.9, 10.11, 10.13 and 10.14 and I assume everything else in between, so yeah it does seem like PyObjC 8.2 is to blame.

https://github.com/sabnzbd/sabnzbd/actions/runs/1763269074

Version:	3.5.0 [b8f3677]
Uptime:	0m
Config File:	/Users/test/Library/Application Support/SABnzbd/sabnzbd.ini
Parameters:	"/Volumes/SABnzbd-3.5.0/SABnzbd.app/Contents/MacOS/SABnzbd"
Python Version:	3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] [UTF-8]
OpenSSL:	OpenSSL 1.1.1m 14 Dec 2021

**Comment by Safihre** [comment]
So could you run SAB from sources on an older macOS version to verify if PyInstaller is involved in any way?

**Comment by Cpuroast** [comment]
Hi,

Grabbed the source zip file for 3.5.0 and manually changed requirements.txt changed to "pyobjc<8.2".

Ran "python3 -m pip install -r requirements.txt -U" which triggered the clang install.
Then ran python3 ./SABnzbd.py

It runs just fine.

Version:	3.5.0 [e586ead]
Uptime:	0m
Config File:	/Users/test/Library/Application Support/SABnzbd/sabnzbd.ini
Parameters:	"./SABnzbd.py"
Python Version:	3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] [UTF-8]
OpenSSL:	OpenSSL 1.1.1m 14 Dec 2021

**Comment by Safihre** [comment]
👍 Thanks. Will report upstream!

**Comment by Safihre** [comment]
Closed by 96e9528046e888c312c81c4dde0749c965a92c50
Will not release 3.5.1 just yet, maybe more bugs come in and this really only affects old macOS versions.
