### ISSUE TITLE
In error messages include URL pointing to explanation and help

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#205]
SABnzbd currently gives error and warning messages like 
```
"Too many connections to server newsreader3.eweka.nl:119"
"Download failed - Out of your servers retention?"
```

Users typically then go to the forum and ask what they should do. Experienced forum members will then give the standard explanation and/or point to the FAQ.

My suggestion is that SABnzbd will not just print the message, but also a URL to a page explaning what is going on and what to do. For example

```
Too many connections to server newsreader3.eweka.nl:119. See http://www.sabnzbd.org/info/too-many-connections-to-server.html for more info.
```
That way more users should should be able to solve their problem themselves.

This looks a bit like what Gmail does in SMTP sessions: give the SMTP error, plus the URL to the explanation.

```
550-5.7.1 [2001:aaa:bbb::2] Our system has detected
550-5.7.1 that this message is likely unsolicited mail. To reduce the amount of
550-5.7.1 spam sent to Gmail, this message has been blocked. Please visit
550-5.7.1 http://support.google.com/mail/bin/answer.py?hl=en&answer=188131 for
550 5.7.1 more information
```

Looking forward to opinions on this.

**Comment by thezoggy** [comment]
not sure the url really does anyone any good though...  the message seems pretty self explanatory.
also your wanting to add this to debug output? most users dont even look at that :/

**Comment by Safihre** [comment]
@sanderjo 
What error messages specifically should include a link?
You gave the example of the too many connections, although I think that one is pretty clear.
