### ISSUE TITLE
Crash with FileNotFoundError attempting to access missing .par2 file

### ISSUE THREAD

**Issue by jxyzn** [sabnzbd/sabnzbd#2054]
sabnzbd.error.log:
> Exception in thread Thread-8:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/share/sabnzbdplus/sabnzbd/assembler.py", line 111, in run
>     if rarfile.is_rarfile(filepath):
>   File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 412, in is_rarfile
>     rar_ver = _get_rar_version(xfile)
>   File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 395, in _get_rar_version
>     with XFile(xfile) as fd:
>   File "/usr/share/sabnzbdplus/sabnzbd/utils/rarfile.py", line 2487, in __init__
>     self._fd = open(xfile, "rb", bufsize)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/jason/nzbs/incomplete/blahblah/blahblah.vol-03.par2'

I don't see any sort of failure or message regarding .par2 files in the main log at the time of the crash other than:
> 2022-01-16 20:42:34,133::INFO::[__init__:1026] Restarting because of crashed assembler
> 2022-01-16 20:42:34,133::INFO::[__init__:755] [__main__.main] Performing SABnzbd shutdown

If _get_rar_version() is modified to catch or avoid the FileNotFoundError and return 0 instead of crashing, an error is logged and the failure ignored and operation continues.

**Comment by thezoggy** [comment]
post full debug log, (you have it set to info), we need to know what version of sab and its utilities its using.

**Comment by Safihre** [comment]
Please follow my instructions.

**Comment by jxyzn** [comment]
> 2022-01-16 20:42:23,793::INFO::[nzbstuff:1537] [sabnzbd.postproc.process_job] Purging data for job blahblah (delete_all_data=True)
> 2022-01-16 20:42:23,793::DEBUG::[filesystem:759] Removing dir recursively /home/jason/nzbs/incomplete/blahblah
> 2022-01-16 20:42:23,816::DEBUG::[sorting:209] Found TV Show (blahblah)
> 2022-01-16 20:42:23,905::INFO::[database:290] Added job blahblah to history
> 2022-01-16 20:42:23,905::INFO::[postproc:123] Saving postproc queue
> 2022-01-16 20:42:23,905::DEBUG::[__init__:951] [sabnzbd.postproc.save] Saving data for postproc2.sab
> 2022-01-16 20:42:23,905::DEBUG::[__init__:883] [sabnzbd.save_admin] Saving data for postproc2.sab in /home/jason/.sabnzbd/admin
> 2022-01-16 20:42:23,905::INFO::[downloader:301] Post-processing finished, resuming download
> 2022-01-16 20:42:28,165::DEBUG::[bpsmeter:241] bps: 119161553.99069573
> 2022-01-16 20:42:28,478::DEBUG::[__init__:951] [sabnzbd.bpsmeter.save] Saving data for totals10.sab
> 2022-01-16 20:42:28,478::DEBUG::[__init__:883] [sabnzbd.save_admin] Saving data for totals10.sab in /home/jason/.sabnzbd/admin
> 2022-01-16 20:42:31,949::DEBUG::[downloader:549] Downloader-slowdown: 117597.5
> 2022-01-16 20:42:33,165::DEBUG::[bpsmeter:241] bps: 117860403.26269083
> 2022-01-16 20:42:34,133::INFO::[__init__:1026] Restarting because of crashed assembler
> 2022-01-16 20:42:34,133::INFO::[__init__:755] [__main__.main] Performing SABnzbd shutdown
> 2022-01-16 20:42:34,134::INFO::[__init__:376] SABnzbd shutting down...
> 2022-01-16 20:42:34,134::INFO::[directunpacker:463] Aborting all DirectUnpackers
> 2022-01-16 20:42:34,134::DEBUG::[__init__:389] Stopping URLGrabber
> 2022-01-16 20:42:34,134::INFO::[urlgrabber:78] URLGrabber shutting down
> 2022-01-16 20:42:34,135::DEBUG::[__init__:396] Stopping rating
> 2022-01-16 20:42:34,369::DEBUG::[rating:155] Stopping ratings
> 2022-01-16 20:42:34,369::DEBUG::[__init__:403] Stopping dirscanner
> 2022-01-16 20:42:34,369::INFO::[dirscanner:361] Dirscanner shutting down
> 2022-01-16 20:42:34,576::DEBUG::[__init__:411] Stopping downloader
> 2022-01-16 20:42:41,624::INFO::[downloader:514] Shutting down
> 2022-01-16 20:42:41,624::DEBUG::[__init__:414] Stopping assembler
> 2022-01-16 20:42:41,625::DEBUG::[__init__:421] Stopping postprocessor
> 2022-01-16 20:42:42,135::INFO::[nzbqueue:204] Saving queue

> 2022-01-16 20:42:43,164::INFO::[_cplogging:219] [16/Jan/2022:20:42:43] ENGINE Re-spawning /usr/bin/python3 -OO /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
> 2022-01-16 20:42:44,814::INFO::[sabnzbdplus:1096] --------------------------------
> 2022-01-16 20:42:44,814::INFO::[sabnzbdplus:1097] sabnzbdplus-3.0.0-develop (rev=unknown)
> 2022-01-16 20:42:44,814::INFO::[sabnzbdplus:1098] Full executable path = /usr/bin/sabnzbdplus
> 2022-01-16 20:42:44,814::INFO::[sabnzbdplus:1108] Platform = posix
> 2022-01-16 20:42:44,815::INFO::[sabnzbdplus:1109] Python-version = 3.8.10 (default, Nov 26 2021, 20:14:08) 
> [GCC 9.3.0]
> 2022-01-16 20:42:44,815::INFO::[sabnzbdplus:1110] Arguments = /usr/bin/sabnzbdplus --daemon --pidfile /var/run/sabnzbdplus/pid
> 2022-01-16 20:42:44,815::INFO::[sabnzbdplus:1114] Not inside a docker container
> 2022-01-16 20:42:44,815::INFO::[sabnzbdplus:1117] Preferred encoding = UTF-8
> 2022-01-16 20:42:44,815::INFO::[sabnzbdplus:1124] SSL version = OpenSSL 1.1.1f  31 Mar 2020
> 2022-01-16 20:42:44,818::DEBUG::[sabnzbdplus:1137] Available certificates: {'x509': 0, 'crl': 0, 'x509_ca': 0}

**Comment by Safihre** [comment]
Still missing bits. Maybe you can just email me the whole log at safihre@sabnzbd.org? This way you don't have to change filenames etc and it will include an anonymous copy of your Config file so I better understand your setup.

**Comment by Safihre** [comment]
After inspection of the logs, the problem experienced by @jxyzn is the one described here: #1509.
Closing this issue as a duplicated of that one and will try to come up and implement a solution.

**Comment by Safihre** [comment]
Closed by 9ad5bd477b1a10c326f340583da2de3bfb15d132 in 3.5.1RC2.
