### ISSUE TITLE
Synology DSM7 Permissions 3.5.0

### ISSUE THREAD

**Issue by dasbacon** [sabnzbd/sabnzbd#2055]
after 3.5.0 update the folders are using the correct inherent permissions, but my files are still using "sc-sabnzbd" and "Everyone".

i was using the "Permissions for completed downloads" set to 777 temporary which gave permission for "Everyone". 

it seems now this Permission setting is stuck as only the extracted file is getting the "sc-sabnzbd" and "Everyone" permission. 

currently in the settings the "Permissions for completed downloads" is blank, however there is no change to the extracted file. if i change the permission to 0750 and restart sab, it removes "Everyone" and only shows "sc-sabnzbd" so it does have some effect.

i'm unable to set this back to defaults it seems. 

every time i delete the string within "Permissions for completed downloads" I will see the users "sc-sabnzbd" and "Everyone" on the extracted file.

**Comment by Safihre** [comment]
As a Synology users you should not use Sab to set your permissions.
You should use DSM File manager to set them. You can configure how and which permissions are inherited on the main folder in File Manger.
If you use Sab, it will screw up Synology permissions system.

**Comment by dasbacon** [comment]
yes i agree and i do not want to use sab to set permissions. 

the problem is that i have already used sab to set permissions and now it seems i cannot undo sab from setting permissions. 

even after clearing out the permissions field in sab, it still seems to be effecting the permission of the extracted file. i’m trying to figure out how to not have this happen. i’ve removed and reinstalled the package, but i’m still seeing the extracted file’s permissions set to “sc-sabnzbd” and “Everyone”. the folder that sab is creating for the extracted file is using the correct permissions but the extracted file is not.

**Comment by Safihre** [comment]
If Permissions is left empty, Sab will not apply any permissions anymore. So that's left to the file system that's now in charge.

**Comment by vierins** [comment]
Same here. The permissions will not set correctly if you let sabnzb sort your tv series.
