### ISSUE TITLE
QQ: api to get runtime

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#2072]
I'm trying to get just the uptime property and what format it will display in.
The goal: have a "restart+rebuild" on queue empty, but trying to find a way to prevent a rebuild loop.
reason: i just discovered 500GB of orphaned jobs because I hadn't checked on it since its been so realiable :)

**Comment by jcfp** [comment]
The uptime visible in the web interface on the main page of the config is available via `api?mode=status&skip_dashboard=0`, see [wiki](https://sabnzbd.org/wiki/advanced/api#fullstatus); formatting is done by the [`sabnzbd.misc.calc_age()`](https://github.com/sabnzbd/sabnzbd/blob/c3d826df8c41221e0bd57a5e978756e1e0e81e7e/sabnzbd/misc.py#L120) function. The data isn't very precise (especially for longer uptimes), but good enough to prevent a loop.

**Comment by Safihre** [comment]
Exacty!

**Comment by mgaulton** [comment]
Thanks!

**Comment by mgaulton** [comment]
OK, followup, is it returning a JSON?

geturl = "http://localhost:8085/sabnzbd/api?mode=status&skip_dashboard=0&apikey=APIKEY"
response = requests.get(geturl)
data = response.json()
pprint(data)

returns
```
Traceback (most recent call last):
  File "uptime.py", line 20, in <module>
    data = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

```
