### ISSUE TITLE
To add in self-test: 1) pure IPv4 connect. 2) measure DNS lookup time

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2074]
**Short**: I will add to SAB's self test: 
1. pure IPv4 connect, to circumvent DNS problems
2. measure DNS lookup timing. Maybe it takes longer than the 3 seconds time-out enforced by SAB.

**Long**:
I had a very weird Wrench result:

![image](https://user-images.githubusercontent.com/1273502/153709539-5d7c69ea-aa56-4749-9b6f-62518b4f0458.png)

So according to SAB's wrench: no IPv4 address, no DNS, but still an Internet download speed? How is that possible?
And also a lower Internet speed than expected.

After a lot of analysis (helped by logging by https://github.com/sabnzbd/sabnzbd/pull/2071 and some CLI commands), I found the cause:
* DNS lookop took longer than 3 s (so timed out according to SAB)
* (and thus) connect to sabnzbd.org for the publicipv4() also a timeout

And possible root cause seems to be a weird network setup ... the device thinks it has IPv6

With the proposed additions, you can more easily pinpoint the problem

Prototype on my weirdly behaving system:

```
sipeed@sipeed:~$ python3 sj_measure_pure_ipv4_and_dns_speed.py
Pure IPv4 connect to 1.1.1.1
Seconds: 0.2178647518157959
b'<!DOCTYPE html><html theme="light" lang="en-US" prefix="og: http://ogp.me/ns#"><head><meta charset="utf-8"><title>1.1.1.1 \xe2\x80\x94 The free app t'
```
Very good: connect to http://1.1.1.1/ in 0.2 seconds.

```
DNS host lookup
Seconds: 5.02992582321167
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2606:4700:4700::1001', 80, 0, 0)), (<AddressFamily.AF_INET6: 10>, <Soc
sipeed@sipeed:~$
```
Ouch: DNS lookup does succeed, but takes 5.0 seconds. That will result in all kinds of strange results.

**Comment by Safihre** [comment]
Added timing of DNS, pure IPv4 connect is not feasible at the moment.
