### ISSUE TITLE
3.5 - failed to de-obfuscate

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2084]
using sab hotio docker
sharing from discord, user using 3.5 and having problem with release not unpacking.

logs:
https://0bin.net/paste/gmWq4hXw#HoQiX90LBz57Fg-OW+P4H7t1MueElo144cNVAsuL4h6

and incomplete folder, multiple rar parts missing:
https://0bin.net/paste/DJi3t6Iu#Ou4gM9Kl7zWLB+iVShjL4Tw6PgDh-CuMe2GAiH8ZhHO

tried myself on 3.5.1rc2 win binaries and confirmed the same just to make sure it wasnt an already known bug

tried in another app, nzb is handled just fine. so just looks like sab failing to de-obfuscate all the files

sent nzb to bugs@sab for others to test

**Comment by puzzledsab** [comment]
I think some files must be missing from the PAR2 set. It should have said "Cannot Quick-check missing file <filename>" if it didn't find them.

**Comment by thezoggy** [comment]
The quick check only seemed to report on the subs rarest not the actual main rarest. But the par2 rename happened for a partial list of files. Newsbin handled the nzb just fine.

**Comment by Safihre** [comment]
I found the problem: all `.par2` files have the same name, so we identify them as the same set. 
So we correctly parse the `.par2` files, but the overwrite the `nzo.md5packs[setname]`.
I've seen this before, but forgot why I didn't fix it.

**Comment by Safihre** [comment]
Another issue I found is that it doesn't correctly report the download as failed due to the unpack error.
Also fixed that.
