### ISSUE TITLE
Feature request: text filter in download queue

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2085]
Sometimes with a large download queue spanning several pages it could be great if there was a text input box that could act as a filter, e.g. enter GERMAN (case insensitive) and get a list of all files matching that keyword.

user case: you could then select all/delete...

**Comment by Safihre** [comment]
We already have that? The search box at the bottom of the queue-list?

**Comment by DarrenPIngram** [comment]
Oh, for the blind who cannot see. For some reason it was "invisible" yet I
saw all the other options to the right of it.

I've only been using SAB for a long time and all.

I can't even blame Monday morning, as it came to a head last night with a
lot of stuff I didn't want from an automated search and I was frustrated
manually deleting :)

**Comment by Safihre** [comment]
👍
