### ISSUE TITLE
[FR] Notification Gotify

### ISSUE THREAD

**Issue by wuast94** [sabnzbd/sabnzbd#2091]
Support for Gotify would be awesome 🙂

Project Page:
https://github.com/gotify/server
API:
https://gotify.net/api-docs

**Comment by Safihre** [comment]
I would like to refer you to our recommended notification "plugin": nzb-notify.
https://github.com/caronc/nzb-notify
They support Gotify!

We stopped adding new notification options, as they require a lot of code in SABNzbd while the support of nzb-notify is so much more extensive, we could never match it.
