### ISSUE TITLE
any way to fail jobs automatically exceeding a certain file size?

### ISSUE THREAD

**Issue by mohitjoshi155** [sabnzbd/sabnzbd#2098]
any way to fail jobs automatically exceeding a certain file size?
would be helpful to me ....

**Comment by Safihre** [comment]
You can use a Pre-queue script, the example even uses size: https://sabnzbd.org/wiki/scripts/pre-queue-scripts
Then you just have to modify the return value to fail it so it shows up History, or you can just reject it and it won't show up anywhere.

**Comment by Safihre** [comment]
Almost forgot: you can also use the Special setting `size_limit`. This will pause any jobs that exceed the limit and label them, you still have to manually remove them though:
https://sabnzbd.org/wiki/configuration/3.5/special
