### ISSUE TITLE
Episode naming all but one is good in each folder

### ISSUE THREAD

**Issue by TheGeneral007** [sabnzbd/sabnzbd#2112]
In each folder there is one .mkv named wrong. 
Sometimes it's the E01 or the last or somewhere in the middle. 
I haven't found a pattern yet in it.
But it is consequently there and I don't think I can change any of the parameters. 
So what goes wrong and what needs to change this behaviour ?

It gets the name of the .nzb-file
The .txt is also named wrong, but that is of less importance

![image](https://user-images.githubusercontent.com/82135186/157409566-73ab7245-3530-4d7c-a284-a287c913ab2b.png)

**Comment by sanderjo** [comment]
I guess you have "deobfuscate" on?

Can you share such a NZB, for example via pastebin?

**Comment by TheGeneral007** [comment]
No, deobfuscate is off.

via pastebin and because of the size I had to split it in two.
I was not able to get a Pro - account there, so I couldn't send larger files.

https://pastebin.com/kEHvYBMg
https://pastebin.com/i06wy4yY

**Comment by sanderjo** [comment]
I get "Unpacking failed, archive requires a password" ...

**Comment by TheGeneral007** [comment]
https://pastebin.com/0gH0pDDu

**Comment by sanderjo** [comment]
> Could it have something to do with the Episode-sorting ?

Yes, it could be. But I'm not good at that part of SABnzbd

Can you do this:

1. in SAB: Wrench-symbol -> right-lower corner: "+Debug" so that SAB does debug-logging
2. Redownload the post
3. Then: in sabnzbd.log, search for lines containing deobfuscate. Post them here

**Comment by TheGeneral007** [comment]
2022-03-09 09:21:49,261::DEBUG::[deobfuscate_filenames:88] No par2 files found to process, running renamer
2022-03-09 09:25:34,477::DEBUG::[deobfuscate_filenames:88] No par2 files found to process, running renamer
deobfuscate_final_filenames = 0

Hopefully this helps

**Comment by sanderjo** [comment]
> 2022-03-09 09:25:34,477::DEBUG::[deobfuscate_filenames:88] No par2 files found to process, running renamer

As that is the only line with "deobfuscate", that is the proof debofuscate is not the the cause.

So, yes, it must be the sorting ... of which I know nothing.

**Comment by TheGeneral007** [comment]
I think I have found it.
I changed the Sort String into: %sn (%y)/Season %0s/%fn.%ext
Taking the filename instead of the jobname.
It seems to have fixed it. 

Thank you for helping.

**Comment by ItsME6969** [comment]
I thought I was also trippin but it happens quite alot with season packs.
I have sorting as `Show Name/Season 1/Show Name - S01E05.mkv`
When this error happens, mostly the `Show Name` also fails to rename properly and gets truncated and what was `Show.Name.S01.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264` ends up as `Show Name S01 1080P Amzn Web-Dl Ddp5 1 H`.
The folder name clearly has `S01` but the resulting structure is `Show Name S01 1080P Amzn Web-Dl Ddp5 1 H/Season 2/...`
Note the `Season 2` and how the `H.264` lost the `.264`.
And then the `last episode` of the pac is the one that **mostly** fails to rename for me and usually gets labelled as S02E64. Presumably the 2 and 64 came from H.264 and SAB took that as the season and episode numbers. So it ends up as
`Show Name S01 1080P Amzn Web-Dl Ddp5 1 H - S02E64.mkv` without the episode number and I have to rename that file with the last episode number.
The same nzb with nzbget and post processing enable works with no problem.
