### ISSUE TITLE
Possible issue with 3.5.3 upgrade

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2136]
I cannot see any other reason but when upgrading a working 3.5.0 to 3.5.3 it seemed to replace all my Usenet server addresses with 127.0.0.1., meaning obviously no downloads could happen.

I can't obviously repeat this unless I downgrade and try again (it is not running in a Docker, so it can be more difficult).

Providing FYI in case any other reports do emerge (would it be an idea to error trap usenet providers from being 127.0.1.1 anyway)? 

Debian 11, this was upgraded through the "Swizzin" platform wrapper but I can't immediately see how this would make a difference (it did not on earlier versions).

**Comment by Safihre** [comment]
We never modify the server addresses in our code, it's always set to what the user inputted.
There are a couple of suggestions:
- Your browser is auto filling it from the General page (takes the value from the Host setting there).
- the upgrade system that you use does modification on the ini file.

But the browser one we have seen many, many times on the forums.

**Comment by DarrenPIngram** [comment]
Thanks. It can't be the first suggestion as the "change" was noted even
before one hovered/focussed to the field.

As for the second suggestion, I don't know, but I will feed it back to the
Swizzin people in any case.

Just thought I'd throw the feedback up in case there was a
problem somewhere. All was fine on my local (Mac) upgrade in any case.

D
