### ISSUE TITLE
0.8.Alpha1 gets stuck on checking/downloading

### ISSUE THREAD

**Issue by John-Gee** [sabnzbd/sabnzbd#216]
Hello,

I am not exactly sure what's going it, but it seems that when either checking or downloading and it can't find some parts, sabnzbd gets stuck on that nzb, instead of maybe saying it cannot be completed (or checking all my servers?).
While the nzb in question is stuck, sabnzbd proceeds onto the other ones.
I have no warning, just the %/Mb that doesn't move anymore...

I have disabled checking to see if that would help... but now it gets stuck in downloading instead...

What should I provide you to help with this?

Thanks!

**Comment by John-Gee** [comment]
I just rolled-back to stable and now the stuck downloads are failing, guessing as they should in 0/8 as well.

**Comment by shypike** [comment]
There seems to be a potential stalling problem in 0.8.0
Keep in mind that you cannot reuse an 0.8.0 queue in 0.7.x
You need to do a queue repair from the Status page.

**Comment by John-Gee** [comment]
The queue repair sort of worked when I rolled back, but I think it restarted redownloading from 0% though.

Thanks!
