### ISSUE TITLE
[Feature Request] Ability to Pause after specified time (not for an amount of time)

### ISSUE THREAD

**Issue by cedwards** [sabnzbd/sabnzbd#2161]
I run my instance in a paused by default (Settings > Special > Start Paused), so the pause dropdown logic is backwards for me.

Instead of pause _for_ an amount of time I would like to see pause _in_ an amount of time. ie; go back to being paused after these downloads finish in X minutes.

**Comment by thezoggy** [comment]
prob should just use the scheduler or have a post script to pause the queue (submit sab api request to pause) if the needed criteria on your side are met.

**Comment by Safihre** [comment]
At this time, I do not think this is a feature that we will implement.
We already have the option to trigger actions (like pause) after the queue finishes. Click on the menu icon on the top right, at the bottom you can set the Queue-finish-action.
These can also be made persistent by setting Config > Specials > `queue_complete_pers`.
