### ISSUE TITLE
[Feature Request] Grabbed Stats

### ISSUE THREAD

**Issue by Redundant1** [sabnzbd/sabnzbd#2162]
**[Feature Request]**
I'd like to have the ability to see how many monthly grabs I have, ideally, by category.  I'm primarily interested in successful grabs, but failures sometimes use up a decent chunk of bandwidth and that could be useful info, even though I don't have failures very often.  On the off chance I wind up with 10GB worth of multiple failed downloads, that would probably be fairly important for me to know, but I feel that would overly complicate this request.  If I could even just export all this data and then manipulate it in Excel, that would be fine.

**[Reasoning]**
I'm one of the unlucky ones with a bandwidth cap, so I'm very particular about whether or not something gets grabbed.  I also keep track of my usage on a monthly basis, using an Excel spreadsheet, so I know what months are lower usage months.  This allows me to hold a potential grab until one of those lower months.  Also, if there's a spike, I can investigate the cause, so I know if I screwed up, my settings got messed up in one of the other apps, etc.

Truth be told, I'm not sure if this is a feature better suited to SAB or in something else like Prowlarr, so I'm open to suggestions/discussion on the topic, but I'm starting with SAB as it was where I started looking to manually gather this info.

**Comment by thezoggy** [comment]
Sab already had a quota system. Have you tried it out?

**Comment by sanderjo** [comment]
Do you mean the stats in History?
If so, it's all in sabnzbd admin/history1.db, which is in sqlite-format, to easy to parse.

**Comment by Redundant1** [comment]
@thezoggy 
> About tracking grabs, prowlarr already does what you want with that.
> 

Yes and no.  Can I see total grabs?  Yes, but not by month and I also can't break it down by month and category (tv, movies, etc); it's just a total since installation for overall grabs or overall client (aka user agent).  I could manually count everything by day in the history (and I have), but that's very tedious and time consuming.

> About caps, Sab already had a quota system which you could use to manage that.
> 

I do use that, but tracking where that bandwidth is going is what I'm trying to figure out how to do.

> To really do what you want you would want is a bit of a niche management that you might be able to script but would have to prob feed into another system to build your data set to work off of.

While I'm sure others would find this info useful, I do agree it could also be a niche case.  That's why I wanted to bring it up and see what people thought or might suggest.

@sanderjo 
> Do you mean the stats in History? If so, it's all in sabnzbd admin/history1.db, which is in sqlite-format, to easy to parse.

That definitely has all the data I'd need.  If I could figure out how to pull the requisite data from there, it'd be great.  I just haven't done much work with SQL queries.  If you've got some tips on where to start, I'm all ears.  I have used DBeaver Community Edition to visually poke around my Kodi MariaDB... database (seems redundant to write it that way... LOL), so I'm not completely inept.

**Comment by sanderjo** [comment]
with GUI:

`sqlitebrowser history1.db`

... and took a look around.

Or CLI:

`sqlite3 history1.db .dump`

with an ugly example: print download name plus download size (in MB):

`sqlite3 history1.db .dump | grep INSERT | awk -F, '{ print $3  " size: " $(NF-4)/1000111 " MB" }'`

Probably better to write a (python) program to get the info you want.

HTH

**Comment by sanderjo** [comment]
Oh, maybe better for you: also possible to get the history info via SAB's API. See https://sabnzbd.org/wiki/advanced/api#history_main

**Comment by thezoggy** [comment]
grab stats
hydra: https://imgur.com/gallery/TI6YGqF

prowlarr can do it too

you can even just get it from sonarr via accessing the db, `sqlite sonarr.db` then:
```
SELECT SUBSTR(DATA, INSTR(DATA, '"indexer": ') + 12, INSTR(SUBSTR(DATA, INSTR(DATA, '"indexer": ') + 12), '",') - 1) AS IndexerName, COUNT(*) AS GrabCount FROM History WHERE DATA LIKE '%indexer%' GROUP BY IndexerName ORDER BY GrabCount DESC;
```

now about trying to do stuff by month, you can just do different grouping of your database data. easier if timestamp is provided.

but anyways for the question at hand with sab,
```
select count(*) as jobs, category, strftime("%Y-%m", completed, 'unixepoch', 'localtime') as 'month-year' from history group by strftime("%Y-%m", completed, 'unixepoch'), category order by strftime("%Y-%m", completed, 'unixepoch', 'localtime') desc, jobs desc;
```
![DB_Browser_for_SQLite_2022-05-10_15-54-18](https://user-images.githubusercontent.com/500882/167720142-81beb463-0831-4adc-8368-efc43ac03c7b.png)

**Comment by Safihre** [comment]
With that extensive explanation by @thezoggy (thanks!) I'll close this issue.

**Comment by Redundant1** [comment]
@thezoggy It took me a little while to return to this and give it a try, but... holy cow!  I sincerely appreciate you taking the time to post all of that.  I can't thank you enough!  It's more than I needed and works beautifully!

**Comment by Redundant1** [comment]
@thezoggy I ran that last query you posted and noticed that some months are missing category entries and others have two separate entries for the same category.  Browsing in the SAB GUI, I can clearly see that some of those missing months do have data which isn't represented in the output of the query.

For example, in this snippet, the SAB GUI displays completed tv entries for the month of April 2022, but that category doesn't show in the query results.

```
126	Completed	tv		2022-05
10	Completed	movies		2022-05
4	Completed	music-dls	2022-05
2	Completed	music-rips	2022-05
11	Completed	movies		2022-04
7	Completed	music-dls	2022-04
14	Completed	movies		2022-03
128	Completed	tv		2022-03
105	Completed	tv		2022-03
5	Completed	music-dls	2022-03
1	Completed	*		2022-03
```

In this snippet, November 2021 has 2 entries for the tv category for some reason.

```
1	Completed	music-rips	2021-12
95	Completed	movies		2021-11
182	Completed	tv		2021-11
105	Completed	tv		2021-11
6	Completed	music-dls	2021-11
1	Completed	*		2021-11
1	Failed		movies		2021-11
45	Completed	movies		2021-10
```

Any idea what might be causing either of these anomalies?

**Comment by thezoggy** [comment]
Check the query you are running, look at source data.. I suspect you prob had trailing space or something that made it a different name since it's grouping by category + status..

Feel free to jump on sab's discord and hit me up and I look at your db if needed.
