### ISSUE TITLE
Extracting to FAT fails, because of FAT-illegal chars, but SAB history says "Completed".

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2165]
Extracting to FAT fails, because of FAT-illegal chars in a resulting filename, but SAB history says "Completed". IMHO: false, and confusing.
I think SAB should say that things went wrong, preferrably with the cause (the offending filename ... already known in the last unrar output line)

![image](https://user-images.githubusercontent.com/1273502/165942557-e68e592e-37dd-4c4f-ac4f-075e9b3798a7.png)

https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb__special_chars__545ddc9be613.nzb

The use case "FAT" is not so relevant anymore, but it seems it can happen with Linux-on-VM-on-Windows, which is more relevant. See https://www.reddit.com/r/SABnzbd/comments/ue8uht/sabnzbd_constantly_pausing/ 

sanitize_safe is ON, but not relevant, because it happens 'inside' unrar, and AFAIK there is no way to tell unrar to automagically rename illegale filenames

```
2022-04-29 13:53:19,092::DEBUG::[newsunpack:724] Analyzing rar file ... RAR5 found
2022-04-29 13:53:19,093::INFO::[misc:1160] [sabnzbd.newsunpack.rar_extract_core] Running external command: ['/usr/bin/ionice', '-c2', '-n4', '/usr/bin/unrar', 'x', '-idp', '-scf', '-o-', '-or', '-p-', '/media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part1.rar', '/media/sander/SANDERSTICK/complete/_UNPACK_reftestnzb__special_chars__545ddc9be613.5/']
2022-04-29 13:53:19,093::DEBUG::[misc:1161] Popen arguments: {'stdin': -1, 'stdout': -1, 'stderr': -2, 'startupinfo': None, 'creationflags': 0}
...
2022-04-29 13:53:19,313::DEBUG::[downloader:220] Resetting article queue for <Server: newsreader.eweka.nl:563>
2022-04-29 13:53:40,759::DEBUG::[newsunpack:851] UNRAR output 
UNRAR 5.91 freeware      Copyright (c) 1993-2020 Alexander Roshal


Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part1.rar

Extracting  /media/sander/SANDERSTICK/complete/_UNPACK_reftestnzb__special_chars__545ddc9be613.5/blabla.bin

Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part2.rar

...         blabla.bin

Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part3.rar

...         blabla.bin

Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part4.rar

...         blabla.bin

Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part5.rar

...         blabla.bin

Extracting from /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar

...         blabla.bin                                                OK
Cannot create /media/sander/SANDERSTICK/complete/_UNPACK_reftestnzb__special_chars__545ddc9be613.5/Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt
2022-04-29 13:53:40,760::INFO::[newsunpack:299] Unrar finished on /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613
2022-04-29 13:53:40,761::INFO::[postproc:426] Unpacked files []
2022-04-29 13:53:40,762::INFO::[filesystem:320] Checking if any resulting filenames need to be sanitized
```

**Comment by sanderjo** [comment]
```
sander@witte2004:/media/sander/SANDERSTICK/complete/reftestnzb__special_chars__545ddc9be613.5$ unrar x *1.rar

UNRAR 5.91 freeware      Copyright (c) 1993-2020 Alexander Roshal


Extracting from special_chars.part1.rar

Extracting  blabla.bin                                                19%

Extracting from special_chars.part2.rar

...         blabla.bin                                                39%

Extracting from special_chars.part3.rar

...         blabla.bin                                                59%

Extracting from special_chars.part4.rar

...         blabla.bin                                                79%

Extracting from special_chars.part5.rar

...         blabla.bin                                                99%

Extracting from special_chars.part6.rar

...         blabla.bin                                                OK 
Cannot create Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt
Invalid argument
Total errors: 1
sander@witte2004:/media/sander/SANDERSTICK/complete/reftestnzb__special_chars__545ddc9be613.5$ echo $?
9

```

**Comment by sanderjo** [comment]
Ah, nice, next level: rename the offending filename inside the rar, then unrar:

```
...
Extracting from special_chars.part6.rar

...         blabla.bin                                                OK 
Cannot create Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt
Invalid argument
Total errors: 1

sander@witte2004:/media/sander/SANDERSTICK/complete/reftestnzb__special_chars__545ddc9be613.5$ rar rn special_chars.part6.rar "Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt" renamed.txt

RAR 5.91   Copyright (c) 1993-2020 Alexander Roshal   25 Jun 2020
Trial version             Type 'rar -?' for help


Processing archive special_chars.part6.rar
Renaming Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt to renamed.txt
Done

sander@witte2004:/media/sander/SANDERSTICK/complete/reftestnzb__special_chars__545ddc9be613.5$ unrar x *1.rar

UNRAR 5.91 freeware      Copyright (c) 1993-2020 Alexander Roshal


Extracting from special_chars.part1.rar

Extracting  blabla.bin                                                19%

Extracting from special_chars.part2.rar

...         blabla.bin                                                39%

Extracting from special_chars.part3.rar

...         blabla.bin                                                59%

Extracting from special_chars.part4.rar

...         blabla.bin                                                79%

Extracting from special_chars.part5.rar

...         blabla.bin                                                99%

Extracting from special_chars.part6.rar

...         blabla.bin                                                OK 
Extracting  renamed.txt                                               OK 
All OK
sander@witte2004:/media/sander/SANDERSTICK/complete/reftestnzb__special_chars__545ddc9be613.5$ 
```

and there it is:

```
-rw-r--r-- 1 sander sander 104857600 apr 29 12:48 blabla.bin
-rw-r--r-- 1 sander sander      2649 apr 29 12:49 renamed.txt
```

**Comment by Safihre** [comment]
I contacted Unrar to ask if there's a way to force unrar to create Windows-safe filenames, and the answer is:

> Hello,
> Sorry, there is no such way.
> Eugene

So what we should at least fix is that it does not say "Completed". 
Are you sure you did not have `Post process only verified jobs` turned _off_?

**Comment by Safihre** [comment]
@sanderjo could you check my question above? Does it really support success?

**Comment by sanderjo** [comment]
> Are you sure you did not have `Post process only verified jobs` turned _off_?

It is off. Un-checked.

Does that explain it to you?

**Comment by Safihre** [comment]
Yes, because then it will approve any job. Even if it fails. 
Please turn it On and then try again.

**Comment by sanderjo** [comment]
Turned on Post process only verified jobs

Checked with NZB https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb__special_chars__545ddc9be613.nzb

First: stalling:
![image](https://user-images.githubusercontent.com/1273502/169861011-4a740d8b-076e-4b1c-ba62-7c4960450c4d.png)

and finally

![image](https://user-images.githubusercontent.com/1273502/169861241-6f9cbe81-20fb-4def-a9da-cc6fe37b3462.png)

so: Unpacking failed, write error or disk is full? /media/sander/6E9E-5461/c

**Comment by sanderjo** [comment]
After turning on `Make Windows compatible `

After a long "Unpacking: 06/06" again "Unpacking failed, write error or disk is full? /media/sander/6E9E-5461/co"

![image](https://user-images.githubusercontent.com/1273502/169862162-84875a95-2914-496f-9dac-4df1be28369a.png)


All on SAB 3.6.0RC2

**Comment by sanderjo** [comment]
The above with both Incomplete and Complete on FAT.

Test with Incomplete on ext4, and Comple on FAT: same result

**Comment by sanderjo** [comment]
So I would say this is not good and not as we expected: with Make Windows compatible on, I would expect that SAB would take care of removing non-Windows characters from the resulting files.

@Safihre can you try with the given https://raw.githubusercontent.com/sanderjo/NZBs/master/reftestnzb__special_chars__545ddc9be613.nzb on your Windows and NTFS? Based on theory, I would expect no problems, but based on the above, I do expect problems ...

**Comment by sanderjo** [comment]
So that means Make Windows compatible = sabnzbd.cfg.sanitize_safe() cannot solve that? If so, I should remove that check from:

https://github.com/sabnzbd/sabnzbd/commit/df8859d49e27daefbdc413c491b06355f621de25#diff-db363ac9b90f46184c420b28c372136cff39bb5de103238aae125e0d1f4a1471R1269

**Comment by Safihre** [comment]
Yes you're right, I missed that!

**Comment by Safihre** [comment]
@sanderjo I tested your NZB on WIndows, and there it works because there unrar does a correction:
```
Extracting  \\?\C:\Users\xxx\Downloads\complete\Lorem ipsum dolor sit amet, consectetur adipiscing elit _ blabla _ dead__beef_0.txt  OK
```
