### ISSUE TITLE
non-Unicode-popup when trying münchen.de as newsserver

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#217]
As a unicode test, I filled out "münchen.de" as newsserver in SAB 0.8.0 alpha 1 (git version).

When I click on Test Server, the popup shows garbled text (not "münchen.de")
![sabnzbd - unicode test server](https://cloud.githubusercontent.com/assets/1273502/7805761/777bd796-0378-11e5-91da-71b4a0400d00.png)
&#252 looks like the HTML code of ü.

When I add the server anyway, the output on command line is correct:

```
2015-05-26 07:24:18,588::INFO::[downloader:399] 1@münchen.de: Initiating connection
2015-05-26 07:24:18,611::INFO::[newswrapper:235] Failed to connect: (110, '[Errno 13] Permission denied') 1@münchen.de:119
```

I also tried a Chinese server name, with the same results

![sabnzbd unicode chinese](https://cloud.githubusercontent.com/assets/1273502/7805779/d26b1cb6-0378-11e5-9288-ca8135128dd4.png)

```
2015-05-26 07:28:51,003::INFO::[downloader:399] 1@見.香港: Initiating connection
2015-05-26 07:28:51,096::INFO::[newswrapper:235] Failed to connect: (110, '[Errno 111] Connection refused') 1@見.香港:119
```

I had a look in Chromium, and the problem is in the TAPI response:

![sabnzbd - unicode test server - network](https://cloud.githubusercontent.com/assets/1273502/7805894/b6587b34-037a-11e5-9945-e3b58c49a3a4.png)

![sabnzbd unicode - test server response](https://cloud.githubusercontent.com/assets/1273502/7805898/bba5bfa2-037a-11e5-9149-665a0a9bcb46.png)

**Comment by shypike** [comment]
When using the numerical IP of the servers, do you get the same response?
What happens if you replace your patch (for PyOpenSSL 0.13) with this:
self.nntp.sock.sendall(command.encode('latin-1', 'ignore'))
That could fix the münchen.de problem, not the Chinese one.

**Comment by sanderjo** [comment]
Numerical IP: no unicode involved, so normal message

Find out IPv4 address:
```
$ curl -v -4 http://www.münchen.de/ 2>&1 | grep Connected
* Connected to www.münchen.de (194.246.148.31) port 80 (#0)
```

Result:
![sabnzbd plaatje](https://cloud.githubusercontent.com/assets/1273502/7842063/244d4d32-04a1-11e5-8706-d90386bb4b22.png)


My patch is about the the commands within the SSL session. That is not related to this problem.

**Comment by shypike** [comment]
It's a display issue. I'll look at this later.

**Comment by shypike** [comment]
Solved.
Needed to remove double Unicode conversions.
