### ISSUE TITLE
Issue? Folders being created when instructed not to

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2179]
I understand that folders would NOT be created in the download directory if an * is added to the path. It seems not to be doing this. I have tried both adding a * to the explicit path, as well as (an alternate) just an * in the categories/default tab (I don't use specific categories).

_Ending the path with an asterisk * will prevent creation of job folders.
Indexers can supply a category inside the NZB which SABnzbd will try to match to the categories defined below. Additionally, you can add terms to "Indexer Categories / Groups" to match more categories. Use commas to separate terms. Wildcards in the terms are supported.
More information can be found on the Wiki._

E.g. under default / path
`/home/user/storage/DB1-ENC/Masters/GDAU/S/Usenet*`

and 

`*`

Evidence:
History view: https://monosnap.com/file/SHS4OcOjAKk6yMcZ9aRKXPdCCtsd0p

Info from above:
NameA.Farmers.Life.S01E01.1080p.WEB.H264-WEBTUBE
Completeda day ago
StatusCompleted
Size842.1 MB
Categorytv
Path/home/user/storage/DB1-ENC/Masters/GDAU/S/Usenet/A.Farmers.Life.S01E01.1080p.WEB.H264-WEBTUBE
SourceA.Farmers.Life.S01E01.1080p.WEB.H264-WEBTUBE.nzb
DownloadDownloaded in 5 seconds at an average of 168.0 MB/s
Age: 40d
ServersNews.eweka.nl=841.9 MB
Repair[7616ad0f9b9f08a959e664fe16d93cf1] Quick Check OK
Unpack[R3Bw3PZSMn4J9cxvVhsV] Unpacked 1 files/folders in 1 min 1 sec

Yet it appears in a folder when downloaded:

https://monosnap.com/file/JTDI2YhWbEBmn40X46xUwcG6gl5vAH

Note it also seems to not deobscure the filename (?) yet the directory created is correct.

This behaviour is not consistent, but happens a lot, so having trouble knowing what to isolate.

Parameters:

Version: | 3.5.3 [cad8a9a]
/home/user/.config/sabnzbd/sabnzbd.ini
"/opt/sabnzbd/SABnzbd.py" "--config-file" "/home/user/.config/sabnzbd/sabnzbd.ini" "--logging" "1"
3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] [UTF-8]
OpenSSL 1.1.1n 15 Mar 2022

**Comment by Safihre** [comment]
It only works for Categories, so set your TV category path to end with `*` and it will not create job folders.

**Comment by DarrenPIngram** [comment]
OK. I don't use categories at all though... https://take.ms/TeEo4

So, could
1. the documentation be a little more explicit on-screen?
2. could consideration be given to make a "default" function also work?

I better make a default to a category in the meantime.

**Comment by Safihre** [comment]
SABnzbd will automatically pick up the category defined inside the NZB, so that's why sometimes your jobs are not in the Default category but in, for example, the TV category.
So the documentation is a bit short, but correct, the Default category is a category on it's own to which you can apply a specific path.

I see your point, if a Category-specific Path is left empty, why is the Default Path not used?

**Comment by DarrenPIngram** [comment]
Thanks, now I know the "logic" I can work with it, but certainly if a
"default override" or something could be implemented that would be good I
think.

**Comment by Safihre** [comment]
Will be fixed in 3.6.0: 
Use directory of Default Category if the NZB-Category doesn't have one.

**Comment by tgozed** [comment]
This actually broke something for me. I had my TV category going into my root download folder and my default in a sub directory. Is there a way to disable the feature you've added, or should I set my download folder a folder up in the tree, and have TV going into a subfolder and default a sub-sub folder?

**Comment by Safihre** [comment]
You can still do this by specifying a directory for each of your categories, including the Default one.

**Comment by tgozed** [comment]
I understand. If I manually type the full path of my download folder to the TV categories folder section it works. I thought it would only accept relative paths which would mean leaving it blank. 

Thank you for your help and quick response.
