### ISSUE TITLE
Queue paging doesn't work if too many jobs are paused

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#2187]
I'm not sure what the limit is but when I used multi select to pause all except one job then page links below the queue disappeared.

**Comment by thezoggy** [comment]
pagination is only shown if there is more than 1 page of items. the number of items to show on history/queue per page is configured in the little wrench, web interface options.

**Comment by Safihre** [comment]
I made a mistake during the refactor! Thanks for reporting
