### ISSUE TITLE
Restarting because of crashed decoder

### ISSUE THREAD

**Issue by Sparklingx** [sabnzbd/sabnzbd#2196]
[Version: 3.6.0RC3 [7974421]
 Python Version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] [cp1252]]

https://i.redd.it/r1wr7lq1wn291.png

**Comment by sanderjo** [comment]
In title: can you correct "crushed" into "crashed"?

Did it happen once, or more times (also check sabnzbd.log for that text)?
Can you reproduce with a certain NZB?
This is on Windows, right? What kind of CPU and hardware?
