### ISSUE TITLE
Feature Request: allow more than one URL per server

### ISSUE THREAD

**Issue by John-Gee** [sabnzbd/sabnzbd#220]
Hello,

I would like the ability to input more than one URL (/host) per server.
The reasons are simple:

1- Some providers have a few different URLs pointing to the exact same server (astraweb in the US has 2 URLs for example). One URL could be problematic but not the other and so balancing it would be useful. 
2- Some providers offer servers in different region and it usually is a good thing to be able to check multiple servers in case of missing parts...

Currently the only way to solve these, is to have multiple servers in sabnzbd for the same provider but that leads to a few issues:

1- Too many connection issues, which can be solved by splitting connection between servers.
2- Slower downloads as there is no priority between the servers, we will download from all of them instead of just from the closest one.

Being able to specify multiple URLs in order of priority would be great.

Thanks!

**Comment by shypike** [comment]
Release 0.8.0 (currently in Alpha1) supports server priorities instead of primary/backup.
Would that solve your problem?

**Comment by John-Gee** [comment]
Hmmmm I think it's better than current, but I am not sure if it would solve this exact problem.

Let's look at Astraweb: I get 20 connections, and there is 2 servers and 3 URLs (one server has 2 URLs).
If I set up 3 servers in 0.8.0 with proper priorities and 20 connections each, I am afraid it would still end up getting the "too many connection" issue, don't you think?
The trick with the alternate DNS is to only use it if the original doesn't work at all, there is never a use for it if the original DNS works (but it doesn't hurt at all to do 10 connections each... it's just that when one won't work, we only get half the connections..)
As for the 2nd server, since it's a different region we want to connect to it to check for missing parts, but to do so we'd have to disconnect some connections (if not all) from the 1st server.

Thank you!

**Comment by shypike** [comment]
Just flag these servers as "optional". This means that they will be locked out for 10 minutes when they look to be off-line. In that 10 minute window, the other server(s) will be used instead.

**Comment by John-Gee** [comment]
Hmmm yes, but what about when they're not offline?
Won't it connect to both and get the too many connections thing?

**Comment by shypike** [comment]
Not if they have different priorities.
Give your favourite server prio 0 and the other one 1.
If you have a block server as backup, give that prio 2.

**Comment by John-Gee** [comment]
I am not really getting it.
Let me look at an example to see, but if it works with priorities that's great!

Let's say I have 4 servers in priority:
0- Astra US 1 as optional
1- Astra US 2 as optional
2- Astra EU
3- Some Block

It will usually only connect to Astra US 1, but if US 1 is down connect to US 2 and not check for 10 minutes US 1. Cool.
If US 1 is missing parts, won't it connect to US 2 to check for them? If so how does that work? Does it disconnect from US 1 to do so?
Same question for US 1 missing parts and checking EU.
Finally if none of the Astra have it, it will connect to Block (same behavior as today's Backup but better configurability). Cool.

Thanks!
