### ISSUE TITLE
Google stopped supporting email passwords, can OAuth2 be supported?

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#2203]
Google states: "To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password."

So SMTP from SABnzbd to a Google email account does not work any more. Would it be possible to support OAuth2 so that SABnzbd still can send email using Google accounts?

**Comment by thezoggy** [comment]
You should create app password.

**Comment by Safihre** [comment]
Which is also specifically described in the Gmail example in the documentation:
https://sabnzbd.org/wiki/configuration/3.6/notifications
