### ISSUE TITLE
Feature Request: History Details overlay to include source RSS feed responsible for the download

### ISSUE THREAD

**Issue by 4np** [sabnzbd/sabnzbd#2206]
The details overlay for a downloaded item in the history section already contains quite some information. However it is is not clear what RSS feed exactly triggered the download. It would be nice to include that information so it is always possible to see which RSS feed was responsible for a particular download.

**Comment by Safihre** [comment]
You can of course see the list of downloads from a specific feed already, but I understand indeed it would also be useful information straight in the history.

**Comment by 4np** [comment]
Nice, thanks @Safihre
