### ISSUE TITLE
[Feature Request] - Reduce "download status" column size

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2210]
It could be just me but I think the space allocated to it can be reduced so as not to truncate release names especially when not using full-width. Sort of like the screenshot.
![Screenshot 2022-06-15 193105 - Copy](https://user-images.githubusercontent.com/89707006/173980375-203a5131-643c-4ff3-ac1b-9c481ac29d9f.jpg)

**Comment by Safihre** [comment]
In your screenshot it looks like the only content is 'Completed', but of course during post-processing this column also shows all the status information of the active post processing.
Currently there's no width set on this column. But I can look into maybe setting some sort of maximum width.

**Comment by Safihre** [comment]
I played around with this, but because we use a standard `<table>` there is no such thing as a `max-width`. 
So there's not much I can do without breaking it on smaller screens.

**Comment by ItsME6969** [comment]
No biggie, thanks for looking into it.
