### ISSUE TITLE
virustotal on 3.6

### ISSUE THREAD

**Issue by djeear-github** [sabnzbd/sabnzbd#2211]
3 security vendors and no sandboxes flagged this file as malicious.
It concerns version 3.6.
With 3.5.3 only one message was found.

**Comment by Safihre** [comment]
So.. What do you want us to do?
They are false positives.

**Comment by thezoggy** [comment]
files that are new to the internet wrongly get flagged until reported to build its rep. you should submit it to them to say its good.
