### ISSUE TITLE
par3cmdline

### ISSUE THREAD

**Issue by modem7** [sabnzbd/sabnzbd#2212]
Heya, 

I understand that this isn't ready at all currently, but just making this issue to keep an open eye for when things start moving (repo was recently updated) in case you weren't aware as it'll probably be useful for the sabnzbd project.

https://github.com/Parchive/par3cmdline

This has come from the discussion in https://github.com/Parchive/par2cmdline/issues/130

Please close if not useful. 

Cheers!

**Comment by Safihre** [comment]
Thanks for letting us know, I was not aware of it! Subscribed to the repo now.
