### ISSUE TITLE
Support for Lokinet low-latency onion routing for enhanced privacy

### ISSUE THREAD

**Issue by jan-kleks** [sabnzbd/sabnzbd#2213]
I have recently been reading about an interesting WIP lower latency alternative to Tor -- Lokinet. Maybe it is something that could potentially be integrated (as an option) into sabnzbd in the future for those interested in higher anonymity?

Lokinet on GitHub: https://github.com/oxen-io/lokinet

[Blog post about Lokinet's speed](https://www.oxen.io/blog/lokinet-speed-and-scale)

**Comment by albino1** [comment]
I don't know anything about Lokinet, but if it's anything like Tor then I'm sure they would frown upon people unnecessarily pumping petabytes of Usenet data through their network and wasting precious bandwidth that could be used for much more important things.  Tor developers would hate that, and I imagine Lokinet devs would too.

**Comment by jan-kleks** [comment]
@albino1 You might be right, but they mention BitTorrent [in their FAQ ](https://lokinet.org/faq):

>The only thing Lokinet can’t handle is protocols that embed bare IPs in their protocol, like WebRTC and BitTorrent — but these still work through exit nodes, just not within Lokinet itself.

Also (which I think you currently can't do on Tor)
>This means Lokinet can be used for much more than just web browsing — it can also handle things like media streaming and video conferencing.

It generally seems to be more versatile, but it still might be worth to ask Lokinet devs about the Usenet idea.

Regards

**Comment by Safihre** [comment]
Thanks for bringing this up. At this time this is too exotic for us to implement. Maybe if this becomes a mainstream thing, it will be different.

**Comment by jan-kleks** [comment]
@Safihre Yeah, I suggested this, so that it could be considered in the future. Keep up the great work!
