### ISSUE TITLE
Dashboard: updates & discussion

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#222]
As the subject of https://github.com/sabnzbd/sabnzbd/pull/213 does not cover "Dashboard", I'm opening a separate thread for Dashboard updates and possible disucssion.

Current state of the code:

Normal system state, with Complete on a USB stick .. that appears to very slow:
![sabnzbd dashboard - with comple on usb stick](https://cloud.githubusercontent.com/assets/1273502/7893111/ca75fe42-065a-11e5-8480-f7a612f772c2.png)

Bad system state, with no network and no writable Complete directory:
![sabnzbd dashboard 2015-05-29](https://cloud.githubusercontent.com/assets/1273502/7893113/ce84d530-065a-11e5-83d1-afce7d3d2f8c.png)

Feedback welcome.

**Comment by Safihre** [comment]
Why did the status-messages and coloring not make it into the final Alpha2?
Seems now it only has a result or nothing?

**Comment by shypike** [comment]
Being too busy and becoming forgetful therefore.
Will be picked for the next alpha.

**Comment by Safihre** [comment]
Will put it in Glitter then ;-)

**Comment by sanderjo** [comment]
AFAIK I have not yet sent a pull request to Shypike.

**Comment by Safihre** [comment]
I wonder when diskspeed would be of diagnostic usage? Are there many users with diskspeed related problems?

**Comment by sanderjo** [comment]
I don't know the number of 'many users', but I do see users complaining in the SAB forum about SAB speed when they're saving to a NAS drive from another device running SABnzbd (like a diskless or a disk-sparse Raspi).

A harddisk is around 50 MB/s, a SSD is about 150 MB/s. However, a NAS-over-LAN is typically only a few MB/s or even less than 1 MB/s when accessing it via Wifi.

**Comment by Safihre** [comment]
Aaah like that indeed it makes sense. I will also put it in Glitter status-window then.

**Comment by Safihre** [comment]
It's probably hard to determine if the download/complete are on the same disk so test is not done twice on same disk? (especially in the network I guess)

This is what I made for it in Glitter (the label is only when the user hovers over the refresh icon)
![untitled](https://cloud.githubusercontent.com/assets/5703454/8145862/212c5216-121a-11e5-8f67-5394f8517e58.png)

**Comment by sanderjo** [comment]
Yes, hard to determine. C: and D: could be on the same drive, or not.
Probably there are OS-specific tools, but that's more difficult than just two plain tests.

Remarks about your screenshot:
Cool that you implemented that in Glitter
Good that you have IPv6.
Why is your nameserver "Not OK"?

**Comment by Safihre** [comment]
Those are just test-values to verify if Glitter is doing it's job, normally it shows OK and a good diskspeed.

**Comment by sanderjo** [comment]
I've sent my Dashboard pull request to @shypike . See https://github.com/sanderjo/sabnzbd/commit/248bfbde996f2dc58c1eaad2d2eadc8aff15c8bb

**Comment by shypike** [comment]
I'm closing this. Re-open if further discussion is needed.
