### ISSUE TITLE
7zip 22.01

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2220]
new 7zip out, 

showed up on security feed:
https://www.bleepingcomputer.com/news/microsoft/7-zip-now-supports-windows-mark-of-the-web-security-feature/

not that we really care for our uses, but figure in case we need to fiddle with any arguments to maintain support.
also i see they also provide additional arm binaries as well now

https://www.7-zip.org/download.html
```
22.00          2022-06-15
-------------------------
- 7-Zip now can extract APFS (Apple File System) images that can be used in DMG files.
- 7-Zip now can create TAR archives in POSIX (pax) tar format with the switches
    -ttar -mm=pax or -ttar -mm=posix
- 7-Zip now can store additional file timestamps with high precision (1 ns in Linux) 
  in tar/pax archives with the following switches:
    -ttar -mm=pax -mtp=3 -mtc -mta
- New switches for Linux version for TAR archives:
  -snoi : store owner/group ids in archive or set owner/group ids from archive to extracted files. 
  -snon : store owner/group names in archive
- New -snz switch to propagate Zone.Identifier stream to extracted files (Windows).
- New option "Propagate Zone.Id stream" in Tools/Options/7-Zip menu.
- New "Options" window in "Add to archive" allows to select what metadata must be 
  included to archive. Also it allows to select new option 
  "Do not change source files last access time".
- Some bugs were fixed.
```

```
22.01          2022-07-15
-------------------------
- UDF support was improved to UDF version 2.60.
- HFS and APFS support was improved.
```

**Comment by Safihre** [comment]
FYI: I was waiting until he would also update the macOS release, but he didn't yet..

**Comment by thezoggy** [comment]
Saf, I saw you were working on a Mac build for this, have any luck?

**Comment by Safihre** [comment]
Yes, it worked. But only after 2 code changes and I don't have an M1 Mac to test it there.
I had expected some support from the maintainer, but he stayed silent after my success.
See: https://sourceforge.net/p/sevenzip/discussion/45797/thread/c43cbc5f18/?limit=25#5ba2

**Comment by Pentaphon** [comment]
> I don't have an M1 Mac to test it there.

You can get free access to an M1 Mini here: https://www.macstadium.com/opensource

The Transmission project used it lately for their torrent client.

**Comment by Safihre** [comment]
Oke, I should rephrase: I don't want to test it. 
I'm not the maintainer of 7zip so it shouldn't be my responsibility, plus I also don't know how to test it well.

**Comment by thezoggy** [comment]
yeah, seeing more people hound him about macos update.. so maybe he will get on that.
