### ISSUE TITLE
Renaming from par2 loses some files when there are multiple identical copies

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#2223]
If an nzb contains multiple files with the same hash then the renaming gets messed up. For instance, if the nzb is supposed to contain fileA.jpg, fileB.jpg and fileC.jpg (all copies of the same image) then they will instead be renamed to fileA.jpg, fileA.1.jpg and fileA.2.jpg.

There is an entry for alle these files in the par2-file(s) but duplicates are being discarded. My suggestion is to keep a list of all the filenames for each hash. Then we could skip renaming if the file already has a name that corresponds to the correct hash. If not it should go through the list of filenames and only rename if a file with that name does not already exist.

This is somewhat related to #2204.

**Comment by Safihre** [comment]
Is this really something we care about fixing? It's just an uploader making things a mess..
If you have an elegant solution, we can implement it of course.
Note that this would then be for QuickCheck and that if par2cmdline/Multipar is used for repair, it would still create the 'bad' output.

**Comment by thezoggy** [comment]
ive ran into this off and on over the years, it used to be a common thing where the subpack for a media file would have the same name. this then became really messy when its a season pack...  i could have sworn i had a github issue about this in the past which we made tweaks to handle (basically handle subpack before rarset so the subpack rar didnt clobber the rarset one)
