### ISSUE TITLE
Aggressive deobfuscation occasionally renames files that shouldn't be renamed

### ISSUE THREAD

**Issue by bambury** [sabnzbd/sabnzbd#2225]
I've noticed lately that in some cases, when downloading MP3 music scene releases, one or two (empirically it's either none, one or two, never more) MP3 files are renamed to the NZB name.

Today I took a look at the debug log and it looks like it's an aggressive (and unnecessary) deobfuscation attempt that causes the issue.

I've uploaded an extract of the debug log [here](https://0bin.net/paste/sk+GZxjF#CS6fs-iVQuqoN3JEjXh2iN7dGhhu7IpFBhqSAlHtiVS), the relevant bit starts at line 451.

Also, it's probably unrelated but there are two mentions of using the "tv sorter" for the download, even though it's categorized and music and eventually treated as such (lines 74 and 510).

The NZB file is [here](https://anonfiles.com/d8Gf9es0y6/Mark_Knopfler-Down_The_Road_Wherever-_Deluxe_Edition_-2018-RiBS_nzb).

Thanks for the attention, I'll be happy to do tests or provide more information if necessary.

**Comment by sanderjo** [comment]
I see.
The code https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/deobfuscate_filenames.py#L220-L240 could use some improvement.

Are you running SABnzbd from source (on Linux)? Can you find the file sabnzbd/deobfuscate_filenames.py ?

**Comment by bambury** [comment]
I am running SABnzbd 3.6.0 in a Docker container on LibreElec at the moment, but I can run a second instance from source on my Linux machine if it helps. Would you like me to make some changes to deobfuscate_filenames.py and see if the problem is fixed?

**Comment by sanderjo** [comment]
I'm still thinking about a real solution, but in the meantime this should work for you:

https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/deobfuscate_filenames.py#L44

add ".mp3" somewhere in that line defining EXCLUDED_FILE_EXTS

**Comment by bambury** [comment]
Got it, thanks!

**Comment by bambury** [comment]
I just wanted to confirm that the workaround you suggested works. I took a quick look at the code you mentioned (lines 220-240) and I'm not sure I can see what's wrong there. Then again, I didn't sleep much and I'm pretty tired today :) Maybe it should iterate on the extcounter array after the for loop?

**Comment by sanderjo** [comment]
New reference NZBs:

https://raw.githubusercontent.com/sanderjo/NZBs/master/Very%20Nice%20System%201234.nzb

```
-rw-rw-r--  1 sander sander 104857600 jul 17 12:05 blabla.iso
-rw-rw-r--  1 sander sander    102400 jul 17 12:05 blabla.srt
-rw-rw-r--  1 sander sander    102400 jul 17 12:05 somethingelse.txt
```

The new deobfuscation method will deobfuscate blabla.iso (because it's much bigger than the second-biggest file, and obfuscated), and also accompanying file blabla.srt (because same base name), but not somethingelse.txt.




https://raw.githubusercontent.com/sanderjo/NZBs/master/Nice%20MP3%20Set%205678.nzb

```
-rw-rw-r--  1 sander sander 10485760 jul 17 12:10  bla1.mp3
-rw-rw-r--  1 sander sander 15728640 jul 17 12:11  bla2.mp3
-rw-rw-r--  1 sander sander  9437184 jul 17 12:11  bla3.mp3
-rw-rw-r--  1 sander sander 12582912 jul 17 12:11  bla4.mp3
```

The new deobfuscation method will not touch these files: yes, they are deobfuscated, but the biggest file (15MB) is not much bigger than the second-biggest file (12MB)

**Comment by Safihre** [comment]
Closed by #2241

**Comment by sanderjo** [comment]
@bambury the github version of SAB now contains the code that solves your case. No more need for your manual "mp3" in the EXCLUDED_FILE_EXTS
I tested with the NZB you posted, and ... no more renaming because SAB sees it's a about-same-size file set. Good.

So ... if you're able to test & confirm that would be nice.

**Comment by bambury** [comment]
> Sure, I'll run a couple of tests as soon as possible. And thanks again for addressing this!

@sanderjo Just tested 3 NZBs that were problematic, all good. Just one question: I saw that you set a threshold of 3 for file size comparison, so what happens if an MP3 file is more than 3 times larger than another (think main suite vs intro of an album)?

**Comment by bambury** [comment]
> It compares the biggest file to the next biggest file (not to the smallest).
[...]

Got it! Thanks for the clarification.

**Comment by bambury** [comment]
Hi, could you please release a numbered version of SABnzbd that includes this fix? I'm running it in a Docker container and can't really work with git releases. Thanks! :)

**Comment by sanderjo** [comment]
> Hi, could you please release a numbered version of SABnzbd that includes this fix? 

I can't

> I'm running it in a Docker container and can't really work with git releases. Thanks! :)

LSIO provides "nightly"; see https://docs.linuxserver.io/images/docker-sabnzbd

**Comment by bambury** [comment]
Thanks. I checked [here](url=https://fleet.linuxserver.io/image?name=linuxserver/sabnzbd) before posting but they don't list the nightly in that page. I'll give it a shot.
