### ISSUE TITLE
ENGINE Error in HTTPServer.serve, cheroot, old issue.. back again?

### ISSUE THREAD

**Issue by pcm1ke** [sabnzbd/sabnzbd#2228]
I've been doing some googling and looking at the past issues and I saw a lot of relevant discussion about this issue and how it was something upstream and a really old issue that was supposedly now resolved.. however, I'm getting it today on latest sabnzbd installed from ppa on Ubuntu 22.04 LTS. How can I go about rectifying it?

As an aside, if I click on the status and interface options.. sabnzbd cannot find my public IP (Public IPv4 address   Connection failed!), despite everything working just fine. This was also mentioned a long time ago, but again it's happening to me now too.

Finally, also have issues with warnings about special characters (not writable with special character filenames. This can cause problems.), despite UTF8 specified on mount and in locale. Any way to fix this?

`[01/Jul/2022:21:47:17] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cheroot/server.py", line 1810, in serve
    self._connections.run(self.expiration_interval)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 201, in run
    self._run(expiration_interval)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 218, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "/usr/lib/python3/dist-packages/cheroot/connections.py", line 272, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cheroot/ssl/builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)`

**Comment by thezoggy** [comment]
Lower level ssl error when connection is closed during handshake. Can see it's happening in python itself not in sab code. So nothing sab can do.

**Comment by pcm1ke** [comment]
pcmike@ubuntu:~$ python3 -c "import cheroot;print(cheroot.__version__)"
8.5.2+ds1

**Comment by pcm1ke** [comment]
Yes, actually. I never thought about that. I’m using a Ubiquiti UDMP as my DNS and the UDMP is using NextDNS as it’s upstream DNS.

**Comment by Safihre** [comment]
We don't control that part. It's in a depency and we have tried many times with them to improve their logging, to no avail.

**Comment by thezoggy** [comment]
Looks like there is some traction again on it, https://github.com/cherrypy/cheroot/pull/518
