### ISSUE TITLE
keyboard shortcut - 3.6.0

### ISSUE THREAD

**Issue by fuzzzor** [sabnzbd/sabnzbd#2229]
shortcut for Azerty keyboard is "Q", not "A" for ADD

**Comment by thezoggy** [comment]
we use javascript event.code "KeyA":
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Glitter/templates/static/javascripts/glitter.main.js#L1241


Per: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

> For example, the code returned is "KeyQ" for the Q key on a QWERTY layout keyboard, but the same code value also represents the ' key on Dvorak keyboards and the A key on AZERTY keyboards. That makes it impossible to use the value of code to determine what the name of the key is to users if they're not using an anticipated keyboard layout.

> To determine what character corresponds with the key event, use the [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) property instead.

So yeah, looks like we need to revamp logic to fix. Also recently others had request to add google type shortcuts to navigate through pagination (queue/history) pages as well.

**Comment by Safihre** [comment]
@thezoggy want to open PR for a fix? :)

**Comment by thezoggy** [comment]
sure, https://github.com/sabnzbd/sabnzbd/pull/2231
