### ISSUE TITLE
Post process cleanup

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2230]
Not sure if its a bug or maybe a file or maybe obfuscation in the NZB but occasionally I end up with an unwanted file with extension `.nfo]-[2+2] - '' yEnc  12 (1+1)`  tried putting that as a file extension in cleanup but it never gets deleted.
The only thing I can see in the logs regarding that file is

`05:22:59,485::INFO::[nzbparser:477] File [PRiVATE]-[WtFnZb]-[WtF[nZb].nfo]-[2+2] - '' yEnc  12 (1+1) added to queue`

Could they be remnants of SABs internal post-processing? I have no post-processing scripts running in that category other than SABs TV Sorting.

**Comment by Safihre** [comment]
When adding the NZB, we try to determine the filename based on a number of common patterns. There is a common pattern where the filename is between `[]` which we can parse. However, here the filename itself contains `[]` so it fails to match correctly and includes part of the garbage text in the filename. 
I don't think there's much you can do, as such patterns are not supported in the clean-up list.

**Comment by ItsME6969** [comment]
Just to clarify the mkv file renamed correctly it's just an `extra file` is created and left behind. A file of a few kb. I'll just write a bash script to delete them.

Speaking of scripts, I had a few scripts that I was using on a `remote` server a pre and post process script that stopped completely working when moving from SAB 3.2. Is there anything under the hood that changed with regards to scripts? The scripts use external apps like jq for processing but the post-processing script will just loop without stopping because it does not recognize any commands.
looking at the script output on SAB
`$HOME/scripts/script.sh: line 38: 90: command not found`
**$HOME/scripts/script.sh: line 39: tput: command not found**
**$HOME/scripts/script.sh: line 40: tput: command not found**
`grep: unrecognized option: P`
```
File "<string>", line 1
import sys,urllib;print urllib.quote(sys.stdin.read().strip())
^
SyntaxError: invalid syntax
```

The script works perfectly running it in bash and it used to work in an older sab I was using. The pre-processing scripts just rejects all because `grep`, `jq` , and `tput` are not recognized in the scripts.

**Comment by thezoggy** [comment]
nothing has changed on sab side for scripts directly, indirectly of course sab moved to python3 with sab 3.x. all sab does basically does with the script is run it. so if the script isnt working, generally its because something on your system changed.. or you changed how you ran sab (where the script env is no longer correct).

**Comment by ItsME6969** [comment]
@thezoggy Yea that might be the case coz the seedbox provider did change some stuff in the backend including the default installations and whatnot. I was gonna open up a ticket with them and thought why not ask it now given I had another issue with postprocessing. Anyways I might reach out to them and see. Thanks.
