### ISSUE TITLE
warning in tests -- selenium find_elements_by_class_name 

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2236]
https://github.com/sabnzbd/sabnzbd/blob/develop/tests/test_functional_config.py#L51

```
   /home/runner/work/sabnzbd/sabnzbd/tests/testhelper.py:262: DeprecationWarning: find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead
    return func(*args)
```

looks like our code should be updated to:
```
            submit_btns = self.selenium_wrapper(self.driver.find_elements(By.CLASS_NAME, "saveButton"))
```

**Comment by thezoggy** [comment]
actually there are several, looks like most of these are just replacing the legacy find_elements_by_x with find_elements(By.x, "whatever") instead.

https://github.com/sabnzbd/sabnzbd/blob/develop/tests/test_functional_downloads.py#L43

```
  /home/runner/work/sabnzbd/sabnzbd/tests/testhelper.py:262: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead
    return func(*args)
```
would be:
```
        self.selenium_wrapper(self.driver.find_element(By.CSS_SELECTOR, "button.btn.btn-default").click()
```

etc

i can submit a pr, looks like we just do `pytest -s`. 

>       Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

working on that now..

**Comment by Safihre** [comment]
They just removed it, that's why I forced lower its version: https://github.com/sabnzbd/sabnzbd/commit/b028258cbd01f3a0daa920203cceec7c3f41fa07#diff-27c5febcc9ce93e8e5341f263b7d68962733b8a2a86c583723d025a1db39d7a3R2

**Comment by thezoggy** [comment]
looking through our builder output it doesnt look like extract_po is actually ran, and during the pytest the test set that should test it fails clean_cache_dir and moves along:
```
tests\test_functional_misc.py ....sUnable to remove cache dir (try 0)

tests\test_getipaddress.py ....
```

**Comment by thezoggy** [comment]
I see the issue in extract_pot.py as i have sab installed in a dir with a space so the abspath part,
`PYGETTEXT = os.path.abspath(os.path.normpath(os.path.join(path, "pygettext.py")))`

results in the space in the folder path not being escaped:
`C:\\Python310\\python.exe c:\\Program Files\\sabnzbd-dev\\tools\\pygettext.py -d SABnzbd -p po/main -w500 -k T -k TT -o SABnzbd.pot.tmp SABnzbd.py sabnzbd/*.py sabnzbd/utils/*.py`

dropping the abspath, so:
`PYGETTEXT = os.path.normpath(os.path.join(path, "pygettext.py"))`

then it works just fine

```
C:\Program Files\sabnzbd-dev>c:\Python310\python.exe tools/extract_pot.py
Creating POT file
*** sabnzbd\api.py:287: Seen unexpected token "kwargs"
*** sabnzbd\api.py:1531: Seen unexpected token "SKIN_TEXT"
*** sabnzbd\misc.py:743: Seen unexpected token "single"
*** sabnzbd\misc.py:744: Seen unexpected token "single"
*** sabnzbd\notifier.py:203: Seen unexpected token "NOTIFICATION"
*** sabnzbd\notifier.py:224: Seen unexpected token "NOTIFICATION"
*** sabnzbd\notifier.py:263: Seen unexpected token "NOTIFICATION"
*** sabnzbd\notifier.py:326: Seen unexpected token "NOTIFICATION"
*** sabnzbd\notifier.py:360: Seen unexpected token "NOTIFICATION"
Finished creating POT file
Post-process POT file
Finished post-process POT file
Creating email POT file
Finished creating email POT file
Creating NSIS POT file
Finished creating NSIS POT file
```

**Comment by Safihre** [comment]
@thezoggy You'll fix this?

**Comment by thezoggy** [comment]
@Safihre sure I can submit something for the selenium stuff, the extract pot I'm  not sure why the abs path was used there.. can I fix that too?

**Comment by Safihre** [comment]
Sounds good!

**Comment by thezoggy** [comment]
thanks for the reminder bot

**Comment by thezoggy** [comment]
ok found a few things to cleanup, and some things i need to re-test before i'll submit

```
tests\test_newswrapper.py ....[22500:23156:0812/031410.763:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
```
https://stackoverflow.com/questions/18026391/selenium-webdriver-in-python-files-download-directory-change-in-chrome-prefere

i want to see if we can optimize our webdriver.. so it doesnt try to update? (also to see if headless makes it quickier)


before updating selenium syntax :
```
= 1261 passed, 57 skipped, 1 xfailed, 1 xpassed, 77 warnings in 187.32s (0:03:07) =
```
after:
```
= 1261 passed, 57 skipped, 1 xfailed, 1 xpassed, 3 warnings in 211.65s (0:03:31) =
```

changing the syntax made your selenium_wrapper unhappy due to passing functions with () and such, but just dropped passing *args and it happy again.


- in configtest - clean_cache_dir  if i add sleep(1) before the shutil.rmtree it stops the "Unable to remove cache dir (try 0)" from showing up. using py3.10.0. going to try to upgrade to py3.10.6 later on to see if it changes anything (as it seems to be a race condition)
- with the changes the tests are happy now with update and selenium 4.2.0. (need to retry on 4.4.0)

i noticed there are a few things that actually arent happy on tests if you run sab from a dir with a space...

i still need to track down where this one is coming from:
```
fatal: C:\Program: 'C:\Program' is outside repository at 'C:/Program Files/sabnzbd-dev'
.s2022-08-12 03:59:39,459::INFO::[__init__:441] [sabnzbd.interface.shutdown] Performing SABnzbd shutdown
```
