### ISSUE TITLE
Windows 7 64 Bit/Chrome memory leak

### ISSUE THREAD

**Issue by corruption42** [sabnzbd/sabnzbd#224]
If I pin a sabnzbd tab in Win7 64 Chrome while there are active transfers, invariably the tab will begin leaking memory. Due to the way Chrome is functioning, it seems to tie up two separate chrome processes -- one will balloon to approximately 4-500MB within 12 hours and will remain that size, the other seems to increase by ~750MB per 12-18 hours and will continue to grow unabated. The largest I have seen the larger process, was in excess of 2.5GB of consumption.

I have not found rhyme or reason for what is causing it; regardless of the size or amount of content in sab, as long as transfers are active, the memory leaking will occur within 12 hours. Simply killing the errant processes and reloading the tab will provide a clean slate, but the buildup recurs without fail.

I have generated dump files via Task Manager, and uploaded them to the following location:

http://binarybuccaneers.org/chrome.DMP
http://binarybuccaneers.org/chrome2.DMP

Both of these processes (400 and 600 MB respectively in memory consumption when active, as per Task Manager's reporting) were cleared from memory when the first process was killed, so the second is definitely related.

Please let me know if any additional details will assist.

Host OS: Ubuntu 14.04.2
Host SAB Version: 0.7.20

Client OS: Windows 7 64 bit, Service Pack 1 + all current updates
Client Browser: Chrome 43.0.2357.81 m

**Comment by shypike** [comment]
Looks like a Chrome bug. Does the same happen with Firefox?

**Comment by corruption42** [comment]
Let a tab run in both Firefox and Chrome side by side -- over 24 hours, the Chrome tab had achieved 4.2gb, and firefox had hit almost 300mb. Definitely appears to be a Chrome bug.

Thanks!

**Comment by thezoggy** [comment]
at work we noticed that chrome (osx) lately has been a memory hog (10gb+ in a day) just from our own internal stuff...  something is seriously messed up in latest chrome
