### ISSUE TITLE
Synology DSM7 Permissions 3.6.0

### ISSUE THREAD

**Issue by vierins** [sabnzbd/sabnzbd#2240]
Same like issue #2055 but Version 3.6.0

The folders are using the correct inherent permissions, but my files are still using "sc-sabnzbd" and "Everyone". The permissions will not set correctly if you let sabnzb sort your tv series.

**Comment by thezoggy** [comment]
Correct as we noted, syno package controls that not the app. Outside of our control. The recommendation is that you should just run app under docker rather than use syno package.

**Comment by Safihre** [comment]
@thezoggy no that's not true. I maintain the SynoCommunity package and as such also know what's going on. Using Docker can break even more on Synology as they have implemented the ACL permissions, so Docker permissions also mess things up quite badly.

@vierins If you leave Folders > Permissions to empty, it will automatically inherit permissions set through DSM. SABnzbd will not set permissions, even in Sorting if that setting is empty. You can enable Debug logging in the Status window and see exactly what permissions SABnzbd applied.
The only exception is if a file has Execute permissions for some reason, then we will strip it.

**Comment by thezoggy** [comment]
> @thezoggy no that's not true. I maintain the SynoCommunity package and as such also know what's going on. Using Docker can break even more on Synology as they have implemented the ACL permissions, so Docker permissions also mess things up quite badly.
> 
> @vierins If you leave Folders > Permissions to empty, it will automatically inherit permissions set through DSM. SABnzbd will not set permissions, even in Sorting if that setting is empty. You can enable Debug logging in the Status window and see exactly what permissions SABnzbd applied.
> The only exception is if a file has Execute permissions for some reason, then we will strip it. 

That's odd then, cause over the last few years of watching everyone deal with fallout of dsm6 permissions changes people have been turning more to using docker rather than use syno packages and in the *adarr discords and guides by several the push is just to use docker for the whole stack to keep it simple and avoid running into niche distro issues by nas providers.

**Comment by Safihre** [comment]
It will work if you also use *arr as a Docker, but not for people that don't use that.
