### ISSUE TITLE
Feature Request: Check before download notice

### ISSUE THREAD

**Issue by matthewlenz** [sabnzbd/sabnzbd#2249]
When you have Check before download turned on the "check" looks just like the download progress, only faster.  It would be nice if it indicated that a check was being performed.  It might be obvious what it's doing on small downloads but on large ones it can be slow.

**Comment by Safihre** [comment]
The progress bar should be blue for Checking status, is it not anymore?

**Comment by matthewlenz** [comment]
I'm using the default theme. Glitter? I think it's called.  Maybe a different theme has it?

**Comment by matthewlenz** [comment]
I just checked.  On Glitter both the check and the normal download progress are the same green.  Either way (if possible it would be nice if it just said 'Checking' or something in italics next to the filename during checks.

**Comment by thezoggy** [comment]
can confirm on default its green on the check and download
http://zoggy.net/firefox_2022-07-24_17-48-44.gif

**Comment by Safihre** [comment]
It was a bug, in the next version it will look again like it's supposed to:
![image](https://user-images.githubusercontent.com/5703454/180739582-a10e21e6-8bfb-4f98-8b5e-b812f9f992c9.png)
