### ISSUE TITLE
Request - Select which servers can be used for a category or vice versa

### ISSUE THREAD

**Issue by cdheiser** [sabnzbd/sabnzbd#225]
Make it possible to restrict which servers can be used to download content for a specific category.  This would allow users to block low priority content from using more expensive servers or block accounts.

**Comment by shypike** [comment]
Maybe for a later release. We just implemented server priorities, lets first test that.

**Comment by cdheiser** [comment]
I have a preliminary version of working code off the devel branch that has thus functionality.  It could probably use a few more.  Would you be interested in a pull request?

**Comment by shypike** [comment]
I'm always interested in code contributions.

**Comment by cdheiser** [comment]
Created pull request #228

**Comment by Safihre** [comment]
I like the idea! Reading your pull, I would actually have done it the other way around. When creating a category, you can select which servers to use. 
Categories feel 'out of place' in the server settings.

But that's just my opinion ;)

**Comment by cdheiser** [comment]
I contemplated doing it the other way around, but it made the UI clunky and
unwieldy.  If you have an idea for how to offer a multi-select option in
the categories UI without making it hideous, there's no reason it couldn't
be implemented through both interfaces.

**Comment by Safihre** [comment]
You are right, this works best. 
Only suggestion would be to expand the text in the server-settings with what the (by default selected) "Default" option means?

**Comment by shypike** [comment]
Implemented by cdheiser. Thanks.
