### ISSUE TITLE
Post Processing Failed when Quick-check renaming occurs

### ISSUE THREAD

**Issue by alexmaras** [sabnzbd/sabnzbd#2251]
I'm using version 3.6.0 of sabnzb in docker. For some downloads, I'm seeing a post-processing error. With debug loggin on, I get the following:

```
DEBUG::[newsunpack:2096] Quick-check will rename 188275-3.0 to (new-file-name-here).jpg
      1 2022-07-26 21:06:38,038::INFO::[notifier:123] Sending notification: Error - Post Processing Failed for (download name here) (see logfile) (type=error, job_cat=
        None)
      2 2022-07-26 21:06:38,038::ERROR::[postproc:596] Post Processing Failed for (download name here) (see logfile)
      3 2022-07-26 21:06:38,038::INFO::[postproc:597] Traceback:
      4 Traceback (most recent call last):
      5   File "/app/sabnzbd/sabnzbd/postproc.py", line 388, in process_job
      6     par_error, re_add = parring(nzo)
      7   File "/app/sabnzbd/sabnzbd/postproc.py", line 751, in parring
      8     need_re_add, res = par2_repair(nzo, setname)
      9   File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1123, in par2_repair
     10     qc_result = quick_check_set(setname, nzo)
     11   File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1980, in quick_check_set
     12     new = quick_check_set_new(setname, nzo)
     13   File "/app/sabnzbd/sabnzbd/newsunpack.py", line 2100, in quick_check_set_new
     14     new_path = renamer(
     15   File "/app/sabnzbd/sabnzbd/decorators.py", line 36, in call_func
     16     return f(*args, **kw)
     17   File "/app/sabnzbd/sabnzbd/filesystem.py", line 857, in renamer
     18     oldpath, _ = os.path.split(old)
     19   File "/usr/lib/python3.9/posixpath.py", line 103, in split
     20     p = os.fspath(p)
     21 TypeError: expected str, bytes or os.PathLike object, not NoneType
```

From what I can see, the `old` filename (in this case `188275-3.0`) is coming through as NoneType. Not sure if this is because it's being misunderstood as a number or not.

**Comment by Safihre** [comment]
I sounds the same as #2204. Are you able to run the develop version?

**Comment by alexmaras** [comment]
I've updated to `develop` from the current git repo to see if I still have the same issue. Now I'm getting:


```
2022-07-27 19:15:10,765::INFO::[postproc:597] Traceback:
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/postproc.py", line 388, in process_job
    par_error, re_add = parring(nzo)
  File "/app/sabnzbd/sabnzbd/postproc.py", line 748, in parring
    need_re_add, res = par2_repair(nzo, setname)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1123, in par2_repair
    qc_result = quick_check_set(setname, nzo)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 1980, in quick_check_set
    new = quick_check_set_new(setname, nzo)
  File "/app/sabnzbd/sabnzbd/newsunpack.py", line 2125, in quick_check_set_new
    if os.path.getsize(nzf.filepath) != par2info.filesize:
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

so strangely, a little _closer_ to the linked issue, but without a File Not Found error - instead, the path doesn't seem to come through.

**Comment by Safihre** [comment]
Strange, `nzf.filepath` should never be empty.
Did you hit Retry on the previous job?

**Comment by alexmaras** [comment]
![image](https://user-images.githubusercontent.com/7509232/181277483-fd352f82-c569-4cda-bd8e-e70f0c33ed2a.png)

Commenting out the `quick_check_set_new` function fixes this issue. As far as I can tell, it's experimental while the results are checked, so disabling it doesn't do any harm as the results aren't used yet. The PAR2 process is happily chugging away and checking everything now, which it never got to previously. 

I would suggest popping a `Try` around the new function too - might help catch these things without them causing unexpected failures. 

Here's a link to one of the NZBs that has caused issues.
https://cloud.at.alexmaras.com/s/dHiHz3iX53feF9C
This link will expire in a few days.

**Comment by Safihre** [comment]
The new QuickCheck was removed.

**Comment by opello** [comment]
> Strange, `nzf.filepath` should never be empty.
> Did you hit Retry on the previous job?

I was digging into this for fun on my own test environment and saw that `nzf.filepath` is marked `Optional` so it can be default initialized to `None` and the "new QuickCheck" missed setting it in the `if` case, but the "Obfuscation rename" `else` case was setting it.

The resolution I came to was updating `nzf.filepath` in the `if` block:

```python
                # Do a simple filename based check
                if file == nzf.filename:
                    logging.debug("Quick-check of file %s OK", file)
                    nzf.filepath = os.path.join(nzo.download_path, file)
                    result &= True
```

This may be moot since 2ac08dd0e6659b24e283ca2d3f9f62963d82a565 landed, but just in case someone goes through this again it might be worth capturing the debugging effort.

And just to note, this still didn't resolve all the issues I saw, specifically what sounds like #2223 was still occurring.
