### ISSUE TITLE
getting unpack error

### ISSUE THREAD

**Issue by mohitjoshi155** [sabnzbd/sabnzbd#2254]
nzb file with which i am getting error

same nzb works in nzbget so i think there must be some issue in sab

**Comment by sanderjo** [comment]
That NZB is not retrievable for me:
When I click on it in the github gui, I get an empty page
When i get it with wget, it's javascript stuff

So can you try to re-upload it?

**Comment by sanderjo** [comment]
Ouch, what an ugly NZB. Where did you get it from?

SAB's deobfuscate does that not help. And I think the par2 files are renaming the already ugly named rar files to something else ugly.

FWIW: renaming the file names inside the NZB leads to a working NZB & download.

```
sed -i -e 's/\&quot; /.rar\&quot; /g' Good.nzb 
sed -i -e 's/489ac38./489ac38.part/g' Good.nzb
```

Meaning: put in ".rar" at end of rar files, and put ".part" before just the end of

Example:
Rename
`subject="&quot;0209d1df8fe3539d87db9451e489ac38.001&quot; yEnc (1/17)"`
to:
`subject="&quot;0209d1df8fe3539d87db9451e489ac38.part001.rar&quot; yEnc (1/17)"`

**Comment by mohitjoshi155** [comment]
ya i was also confused by its renaming when i saw the files in sabnzbd download folder but when it tried on nzbget it worked so i thought it must be normal

**Comment by reallyuniquename** [comment]
NZB file is no longer available. Where do those weird characters come from? Poorly constructed PAR2?

@mohitjoshi155 
There is an awful lot of API keys in your log. Don't forget to revoke your Telegram bot token as well.

**Comment by mohitjoshi155** [comment]
> NZB file is no longer available. Where do those weird characters come from? Poorly constructed PAR2?
> 
> @mohitjoshi155 There is an awful lot of API keys in your log. Don't forget to revoke your Telegram bot token as well.

heres the new nzb link https://www21.zippyshare.com/v/QcnQxlI8/file.html
i did redact api keys i found maybe missed some....thanks for telling me....will revoke

**Comment by Safihre** [comment]
I investigated the NZB. The par2 files seem invalid, even Multipar can't open them so no clue how NZBGet does it.
@sanderjo I do see this in the logs:
``` 
2022-08-03 22:06:25,761::DEBUG::[postproc:915] Detected volume-number 1 from RAR-header: \\?\C:\Users\x\Downloads\incomplete\Good.Luck.Jerry.2022.1080p.DSNP.WEB-DL.DD+5.1.x264-Telly_290722082338\0209d1df8fe3539d87db9451e489ac38.416 
2022-08-03 22:06:25,762::DEBUG::[postproc:915] Detected volume-number 1 from RAR-header: \\?\C:\Users\x\Downloads\incomplete\Good.Luck.Jerry.2022.1080p.DSNP.WEB-DL.DD+5.1.x264-Telly_290722082338\0209d1df8fe3539d87db9451e489ac38.417 
2022-08-03 22:06:25,766::DEBUG::[postproc:915] Detected volume-number 1 from RAR-header: \\?\C:\Users\x\Downloads\incomplete\Good.Luck.Jerry.2022.1080p.DSNP.WEB-DL.DD+5.1.x264-Telly_290722082338\0209d1df8fe3539d87db9451e489ac38.418 
2022-08-03 22:06:25,766::DEBUG::[postproc:915] Detected volume-number 1 from RAR-header: \\?\C:\Users\x\Downloads\incomplete\Good.Luck.Jerry.2022.1080p.DSNP.WEB-DL.DD+5.1.x264-Telly_290722082338\0209d1df8fe3539d87db9451e489ac38.419 
```
Can we maybe fix the volume-number detection?

**Comment by sanderjo** [comment]
> Can we maybe fix the volume-number detection?
> 
> EDIT: or is this not possible due to the password-protection?

... bingo:

```
sander@stream13:~/git/sabnzbd$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabnzbd.utils.rarvolinfo as rarvolinfo
>>> rarvolinfo.get_rar_extension("/home/sander/post_this/nopass.part4.rar")
(4, 'part004.rar')
>>> rarvolinfo.get_rar_extension("/home/sander/post_this/withpass.part04.rar")
(1, 'part001.rar')
```
... it does not work on the rar archive created with "-hpblabla", so with data and headers encrypted.

```
       -hp<password>
              Encrypt both file data and headers.  The password is case-sensitive. If you omit the password on the command line, you will be prompted  with  message
              "Enter password".
```

**Comment by sanderjo** [comment]
But there is hope: if provide the password, and you use unrar (so not pure python code), 

```
sander@stream13:~/post_this$ cp withpass.part4.rar unclear_which_part

sander@stream13:~/post_this$ unrar l -pgeheim unclear_which_part

UNRAR 5.61 beta 1 freeware      Copyright (c) 1993-2018 Alexander Roshal

Archive: unclear_which_part
Details: RAR 5, volume 4, encrypted headers

 Attributes      Size     Date    Time   Name
----------- ---------  ---------- -----  ----
*-rw-rw-r--  52428800  2022-08-04 15:23  blabla.bin
----------- ---------  ---------- -----  ----
                    0                    0

```

**Comment by sanderjo** [comment]
I can change sabnzbd.utils.rarvolinfo in two ways so that rarvolinfo also works on fully-encrypted rar files:

1. on fully-encrypted rar files: fallback to os.system("unrar -p<password>..."), and get the volume number from there
2. always use os.system("unrar ...")

Notes:
* it's easy to see if a rar is fully encrypted ("Encrypt both file data and headers"): the `unrar l` and `rarfile.RarFile()` do not yield anything (without password) 
* `rarvolinfo.get_rar_extension(file_to_check)` would need to know the password from `rar_renamer()`. At that phase, is the one and only correct password known? We don't want to try-run all 20 passwords on all rars. Is it filled out in `nzo: NzbObject` ?

**Comment by sanderjo** [comment]
@Safihre what do you think about the above? So: if SAB sees a rar files that is fully encrypted, then use os.system("unrar ") with the password in the NZB (and thus in nzo.password) to get the rarvolnr (and contents) to correctly handle this case?

If you're OK, I can create a PR.

**Comment by sanderjo** [comment]
... or for now only build in detection and logging of fully-encrypted rars. No performance hit, the user gets informed, and we get statistics how often this occurs: N=1, or is this going to occur more?

@Safihre ... ?

**Comment by Safihre** [comment]
The new version of rarfile module is actually able to get the volume number from encrypted rarfiles. However, it needs modifications for use in SABnzbd. This edge case doesn't make it worth it for me to add extra complexity of calling unrar. 

Although maybe we should make it a bit smarter that if it gets a whole list of volume "1" results it knows its bad? Why does it output anything if it can't read the file?

**Comment by sanderjo** [comment]
> Although maybe we should make it a bit smarter that if it gets a whole list of volume "1" results it knows its bad? 

Yes, possible.
But easier IMHO: if rarfile.RarFile() yields nothing, it's fully encrypted. Then let utils.rarvolinfo.get_rar_extension(file_to_check) return -1 as volumenumber and "" as extension.

> Why does it output anything if it can't read the file?

Because of https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/utils/rarvolinfo.py#L79-L85 : it just reads certain bytes, which adds 1 to the found rar volumer integer, and it now does not check/know if it's fully encrypted. And apparantly that integer is 0 for all fully encrypted rar files.

I don't know which flag in a rar file tells it's fully encrypted; I tried to get it from the rar specs https://www.rarlab.com/technote.htm, but I did not understand it. So ... let rarfile.RarFile() do that check? No checking-with-password, no clever stuff, just detection

Ah: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L918-L920 already does rarfile.RarFile() ... so use that result ... ? If it's empty, we know enough?

**Comment by sanderjo** [comment]
Maybe code with examples makes my point clearer:

The code is able to 

- generate the volnr and extension (as SAB does now already)
- or detect & report it is fully encrypted
... without knowing the password.

Clearer?


```
#!/usr/bin/python3
import os, sys
import sabnzbd.utils.rarfile as rarfile
import sabnzbd.utils.rarvolinfo as rarvolinfo

filename = sys.argv[1]

if not rarfile.is_rarfile(filename):
        print("not a rar file!")
        exit()

rar_file_contents = rarfile.RarFile(filename, single_file_check=True).filelist()

if rar_file_contents:
        print(rar_file_contents)

        rar_vol, new_extension = rarvolinfo.get_rar_extension(filename)
        print(rar_vol, new_extension)
else:
        print("Fully encrypted rar file!")
```

with these results:

```
sander@haring1:~/git/sabnzbd$ ./scan_my_rar.py /home/sander/post_this/levels_of_encryption/nopass.part3.rar
['blabla.bin']
3 part003.rar

sander@haring1:~/git/sabnzbd$ ./scan_my_rar.py /home/sander/post_this/levels_of_encryption/onlydatawithpass.part4.rar
['blabla.bin']
4 part004.rar

sander@haring1:~/git/sabnzbd$ ./scan_my_rar.py /home/sander/post_this/levels_of_encryption/fullypass.part5.rar
Fully encrypted rar file!

sander@haring1:~/git/sabnzbd$ ./scan_my_rar.py /home/sander/post_this/levels_of_encryption/fake.bin
not a rar file!
```



```
rar a nopass  -v10m -m0 blabla.bin
rar a onlydatawithpass  -pgeheim  -v10m -m0 blabla.bin
rar a fullypass  -hpgeheim  -v10m -m0 blabla.bin
```

**Comment by Safihre** [comment]
Great, let's do that!

**Comment by sanderjo** [comment]
Possibly even cleaner code:

```
#!/usr/bin/python3
import sys
import sabnzbd.utils.rarfile as rarfile
import sabnzbd.utils.rarvolinfo as rarvolinfo

def fully_encrypted_rar(rarfilename):
	return rarfile.RarFile(rarfilename, single_file_check=True).filelist() == []
	

filename = sys.argv[1]

if not rarfile.is_rarfile(filename):
	print("not a rar file!")
	exit()

if fully_encrypted_rar(filename):
	print("Fully encrypted rar file!")
	exit()

# if we get here: it's a rar file, and it's not fully encrypted. So

rar_vol, new_extension = rarvolinfo.get_rar_extension(filename)
print(rar_vol, new_extension)
```
with correct results:
```
sander@witte2004:~/appelboor/git/sabnzbd$ ./scan_my_rar.py ../../post_this/levels_of_encryption/nopass.part2.rar
2 part002.rar
sander@witte2004:~/appelboor/git/sabnzbd$ ./scan_my_rar.py ../../post_this/levels_of_encryption/onlydatawithpass.part3.rar 
3 part003.rar
sander@witte2004:~/appelboor/git/sabnzbd$ ./scan_my_rar.py ../../post_this/levels_of_encryption/fullypass.part4.rar 
Fully encrypted rar file!
sander@witte2004:~/appelboor/git/sabnzbd$ ./scan_my_rar.py ../../post_this/levels_of_encryption/fake.bin 
not a rar file!
```
