### ISSUE TITLE
Feature Request - RSS Downloaded Filter column

### ISSUE THREAD

**Issue by RealTracat** [sabnzbd/sabnzbd#2257]
Hi,

Could you add another column in the RSS feed under "Downloaded" that shows which filter has allowed the nzb download?
This would help if something was downloaded that was unwanted so the filtering could be amended.

This is already available in the "Not Matched" tab so hopefully that code can be replicated over?

Thanks

**Comment by Safihre** [comment]
I think we can do this!

**Comment by Safihre** [comment]
Implemented. If you need the macOS/Windows release, it will be available here in a few minutes:
https://github.com/sabnzbd/sabnzbd/actions/runs/2792101754

**Comment by RealTracat** [comment]
I use your Synology build, so i'll wait for that.
Many thanks for getting this done!
