### ISSUE TITLE
Direct Unpack

### ISSUE THREAD

**Issue by Slava46** [sabnzbd/sabnzbd#2264]
Hi, I don't know when it started but in last 3.6.0 version when using "Direct Unpack" happening next thing:

Before was: downloading big files like ~100 GB etc (just fo example), using Direct Unpack - it's going fine without damaged files etc.
While process not finished you can see what archive exactly already unpacked like for example "50/98" done.
So you can delete 01-50 archives and next that will be finished unpacked while downloading and direct unpacking process going. Downloading process finished, unpack finished too while downloading and all fine. All happy.

Now on 3.6.0 version with the same situation like: "50/98" archives done unpacked already, downloading going, you delete archives that already unpacked.
Then downloading finished and then you got that SABnzbd deleting already fine unpacked files and write "Post-processing was aborted".

This thing was useful if need download something big, files not damaged (you can use Direct Unpack and for last versions Direct Unpack can be continued from last complete file after repairing, not from start - this amazing) but no need twice free space for downloading and unpacking.

**Comment by thezoggy** [comment]
Can you try 3.6.1rc1

**Comment by Safihre** [comment]
Does it not say to inspect the log files for details? Because this sounds like a crash. If so, can you post the log entry why it crashed?

**Comment by Slava46** [comment]
Tryed 3.6.1 final and for this version seems fine. Will test and looking more. Thx.

**Comment by Safihre** [comment]
Let's hope it stays that way, otherwise we'll need that logging.

**Comment by Slava46** [comment]
Hi, for 4.0.1 version it's again broken and don't work properly...

**Comment by Safihre** [comment]
For any diagnosis we need the full logs. Enable Debug logging in the Status and Interface settings window and then after it happens again click Show Logging in the same window. You can send the logs to me at safihre@sabnzbd.org

**Comment by Slava46** [comment]
Deleted message mistakally.
For 4.0.1 version it's broken again.
I can reproduce it so send you a log file with debug mode enabled to e-mail.

Just one difference between old issue - seeems now don't deleting files that upacked during Direct Unpack (in old issue files deleted after finished with error).

**Comment by Safihre** [comment]
This is not something we support. After the download we verify all the files and because you deleted already some rar files, this fails because it can't find those files anymore.
You can disable "Post-process only verified jobs" in Config > Switches, then jobs will always succeed even if one of the steps fails.

**Comment by Slava46** [comment]
But before it worked fine and here will be some not complete job on files.
Because while downloading verifing files process going and if files complete and fine it'll countinue unpack during download.
So files fine and should be work with this switch enable.

Why files during download process already verified - them fine OK and complete, unpacked and after that it going check files again after dowload last files and failed because I deleted some files already unpacked?

**Comment by thezoggy** [comment]
> But before it worked fine and here will be some not complete job on files. Because while downloading verifing files process going and if files complete and fine it'll countinue unpack during download. So files fine and should be work with this switch enable.
> 
> Why files during download process already verified - them fine OK and complete, unpacked and after that it going check files again after dowloaded last files and failed because I deleted some files already unpacked?
> 
> The point in Direct Unpack mode - Verify files and Unpack during download process (files that not need repair of course) not after downloaded all the files and this worked before.

are you running sab within docker? if so, which maintainer are you using

**Comment by thezoggy** [comment]
> > are you running sab within docker? if so, which maintainer are you using
> 
> No, just usual Windows x64 version.

Windows 10? Windows 11?  and what build 23H1?

**Comment by Slava46** [comment]
> Windows 10? Windows 11? and what build 22H2? 23H1?

Windows 11 22H2

**Comment by Safihre** [comment]
We don't support deleting files during download. No clue why it possibly worked before but it's not something we want to support.
