### ISSUE TITLE
[BUG] SAB can't handle accented characters

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2267]
Steps to reproduce
1. Find any .NZB
2. Rename the file to anything with accents eg `Làm thế nào bạn làm gì hôm nay.nzb`
3. Add it SAB
4. The result.. A file with a whole different name
...
![Screenshot 2022-08-13 155513 - Copy](https://user-images.githubusercontent.com/89707006/184515966-a5d3ba3a-7a3a-41c7-9308-1271bab3d6d8.jpg)

**Comment by sanderjo** [comment]
![image](https://user-images.githubusercontent.com/1273502/184520743-2f99e71b-4384-4686-a6a4-843bd49c6e18.png)

if you Add it to SAB ... via watched folder

**Comment by Safihre** [comment]
Are you on Windows?

**Comment by ItsME6969** [comment]
He's on linux but if it was directed at me... I'm on Windows....and yeah it seems like its a GUI issue coz I renamed an nzb to Chinese and tried both watch folder and GUI and watched folder works fine
![Screenshot 2022-08-14 013501 - Copy](https://user-images.githubusercontent.com/89707006/184529143-c2e2e5b1-5bb8-4382-9c21-bcae27b42a1e.jpg)

**Comment by sanderjo** [comment]
I think it's pure the filename that get mangled if input via SAB's GUI, becaue if I explicitly fill out an Name, that gets nicely into the download name:

Input

![image](https://user-images.githubusercontent.com/1273502/184529634-b0445874-f928-4b50-8501-70eae2d599d7.png)

results in

![image](https://user-images.githubusercontent.com/1273502/184529660-65037df3-3096-4299-aa0b-9fe79bfb5a67.png)

**Comment by sanderjo** [comment]
Ah, from sab source code nzbparser.py:

```
        # File from file-upload object
        # CherryPy mangles unicode-filenames: https://github.com/cherrypy/cherrypy/issues/1766
        filename = correct_unknown_encoding(nzbfile.filename)
        logging.info("Attempting to add %s", filename)
```

https://github.com/cherrypy/cherrypy/issues/1766

**Comment by Safihre** [comment]
Yeah I was trying to find the past bug report about this, where we also had a long discussion about this.

**Comment by Safihre** [comment]
I labeled it as bug, and hope it will be fixed when we get rid of CherryPy: #2180.

**Comment by Safihre** [comment]
@sanderjo Fixed the problem in a nice way.

**Comment by sanderjo** [comment]
@ItsME6969 on https://github.com/sabnzbd/sabnzbd/actions/runs/2862472029 you can get the fresh Windows build ... can you try and feedback?

Higher entry in History: NZB with unicode smileys in the filename added via GUI of github SAB ... all good!

(Lower entry in History: NZB with unicode smileys in the filename added via GUI of old SAB ... not good)


![image](https://user-images.githubusercontent.com/1273502/184691949-4196bba6-bbff-4557-8032-6077165fde71.png)

**Comment by ItsME6969** [comment]
Preciate the quick fix @sanderjo works like a charm thanks.
![Screenshot 2022-08-15 145508 - Copy](https://user-images.githubusercontent.com/89707006/184725185-b766b657-3e10-4146-96af-a3330deee296.jpg)
