### ISSUE TITLE
Jobs can never be retried in 0.8 (on Windows)

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#227]
In 0.8 failed jobs (on Windows) never have the status retry:1
Looking at the code, failed jobs should get retry:1 if the job-download-dir is still there.. But seems this check always fails.
Maybe this is because of the long directory name support making any of these functions fail?
**starts_with_path(path, cfg.download_dir.get_path()) and \
os.path.exists(path)) and \
not bool(globber(os.path.join(path, JOB_ADMIN), 'SABnzbd_n*')**

Also I noticed when I delete a failed job SAB always seems unable to remove the job folder from the temporary download folder, leaving Orphaned folders all the time. I changed the rights on the folder so everyone and everything had read/write/execute privileges.

**Comment by Safihre** [comment]
Well it seems it is the long-directory support making the 'starts_with_path' fail since this is the input:
path -->    \\?\C:\TempDownload\incomplet
cfg.download_dir.get_path() -->   C:\TempDownload\incomplete

**Comment by Safihre** [comment]
Well I tried to create a separate pull request for just this, but think I failed.
Here is the easy solution:
https://github.com/Safihre/sabnzbd/commit/92614aa0f30fdb752e4917b17870cc2b649103a2

**Comment by shypike** [comment]
Yeah, that's an easy fix.
Apparently I forgot to test this on Windows.
Thanks!

**Comment by shypike** [comment]
Fixed with slightly different code.
https://github.com/sabnzbd/sabnzbd/commit/2f4cebf37a58ad8d96863d95ffbdc7cb0b99e10e
Thanks.

**Comment by Safihre** [comment]
Oke almost fixed, but not completely. It only works when removing a single download.
If you do the same thing I described before, but then use the button "Purge failed NZB's and delete files":

2015-07-04 12:20:34,039::INFO::[postproc:539] Cleaning up Carly Rae Jepsen like (keep_basic=True)
2015-07-04 12:20:34,040::INFO::[__init__:891] \\?\C:\TempDownload\incomplete\Carly Rae Jepsen like\__ADMIN__\SABnzbd_nzf_21xosv removed
2015-07-04 12:20:34,042::INFO::[misc:1309] Cannot remove folder \\?\C:\TempDownload\incomplete\Carly Rae Jepsen like\__ADMIN__
2015-07-04 12:20:34,045::INFO::[misc:1309] Cannot remove folder \\?\C:\TempDownload\incomplete\Carly Rae Jepsen like\__ADMIN__

**Comment by shypike** [comment]
Ok, same problem in another place.
Solved now: https://github.com/sabnzbd/sabnzbd/commit/1994e0535ed60a9ae9a55d7d6abb63f35f893282
