### ISSUE TITLE
Test failure in TestPar2Repair.test_basic

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2274]
Been seeing this one for a while on some CI environments ([debian ci](https://ci.debian.net/data/autopkgtest/testing/amd64/s/sabnzbdplus/25082821/log.gz), [ubuntu ci](https://autopkgtest.ubuntu.com/results/autopkgtest-kinetic/kinetic/amd64/s/sabnzbdplus/20220823_010337_9057a@/log.gz), salsa.debian.org) but not others (github). At first I assumed it was a fluke, but it keeps popping up so the time for a bug report has come. No clue what's causing this one.

Log excerpt:
```
__________________________ TestPar2Repair.test_basic ___________________________

self = <tests.test_newsunpack.TestPar2Repair object at 0x7ffb54f54af0>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7ffb57e2d240>

    def test_basic(self, caplog):
        # Run code
        nzo, dir_contents = self._run_par2repair("tests/data/par2repair/basic", caplog)
    
>       assert dir_contents == [
            "__ADMIN__",
            "notarealfile.rar",
            "par2test.part1.rar",
            "par2test.part2.rar",
            "par2test.part3.rar",
            "par2test.part4.rar",
            "par2test.part5.rar",
            "par2test.part6.rar",
        ]
E       AssertionError: assert ['__ADMIN__',...rt4.rar', ...] == ['__ADMIN__',...rt4.rar', ...]
E         Left contains one more item: 'stillrarbutnotagoodname.txt'
E         Full diff:
E           [
E            '__ADMIN__',
E            'notarealfile.rar',
E            'par2test.part1.rar',
E            'par2test.part2.rar',
E            'par2test.part3.rar',
E            'par2test.part4.rar',
E            'par2test.part5.rar',
E            'par2test.part6.rar',
E         +  'stillrarbutnotagoodname.txt',
E           ]

tests/test_newsunpack.py:148: AssertionError
```

**Comment by Safihre** [comment]
This is strange. 
'stillrarbutnotagoodname.txt' should be renamed to "par2test.part4.rar".
It seems it just made a copy.
Is there a way to see which par2cmdline is running on these runners?
Maybe from the CI output of the functional tests?

**Comment by jcfp** [comment]
Full logs on the debian and ubuntu CI are linked in the bug report, par2 is the regular one from https://github.com/Parchive/par2cmdline/ at version 0.8.1-2. While that package does carry a few [patches](https://salsa.debian.org/jcfp/par2cmdline/-/tree/master/debian/patches), those only deal with issues in the testsuite and don't touch the code of the program itself.

**Comment by Safihre** [comment]
The difference is caused by the par2cmdline version.
I used the one from Parchive/par2cmdline and get:
```
File: "stillrarbutnotagoodname.txt" - is a match for "par2test.part4.rar" 
```
While in the Debian logs it says:
```
File: "stillrarbutnotagoodname.txt" - no data found.
```
And then it proceeds to repair `par2test.part4.rar` from blocks instead of doing the rename.

Not sure what to do with this.. Sounds like a bug in par2cmdline?

**Comment by jcfp** [comment]
> Not sure what to do with this.. Sounds like a bug in par2cmdline?

Did you use the binaries they publish for windows, or compiled the source without any further options or mods? In the latter case, what os and compiler versions?

**Comment by Safihre** [comment]
The published binaries for Windows. But here on Github Actions for the Linux CI it also just pulls in the par2 from the same source as yours, right?

**Comment by Safihre** [comment]
@jcfp any time to further investigate?
