### ISSUE TITLE
FR: Auto-save of "backup" data

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2288]
Could this be added as a feature, e.g. instead of (hopefully) remembering to back up SAB using the web interface, there could be an optional automatic back up offering.

E.g. menu option: auto-backup every [x) days to [state file location on the server].

**Comment by Safihre** [comment]
You can schedule it using the Scheduler. That's also in the wiki text, but indeed not in the main interface.
Still planning to maybe improve the backup, allow configuring of a seperate folder for example and more convenient way to schedule backup.

**Comment by Safihre** [comment]
Ah yes, it's only part of 3.7.0, so the current development version

**Comment by sanderjo** [comment]
In the git version:
![image](https://user-images.githubusercontent.com/1273502/188451962-841ee994-ddca-4fa0-b036-c2d3740ba1c2.png)

**Comment by Safihre** [comment]
Added the Backup Folder option and clarified the text that the Scheduling can be used to create recurring backups.
You can download the test-release in a few minutes here:
https://github.com/sabnzbd/sabnzbd/actions/runs/3016088062
