### ISSUE TITLE
sab - not extracting nested rar within rarset

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2290]
grabbed a few things tonight, noticed that the the main rarset extracted which had the .mkv/.nfo/.sfv and then there was a sub folder rarset for the sub. that sub rarset has a .idx and a .rar (which matches the name of the main rarset) which has the actual .sub in it.

I know we've talked about this before and per previous optimizations it does handle the conflict and does the main rarset.. so gets the media file. then does the smaller rarset.  but then the issue is when there is a rar extracted, that rar is never processed..  then silently cleaned up by radarr.

so again, the end result is:
 - cls-goldfinger.idx
 - cls-goldfinger.mkv
 - cls-goldfinger.nfo
 - cls-goldfinger.rar
 - cls-goldfinger.sfv

with the .sub in the .rar that is never extracted. now we probably don't want to go crazy in case there is a zipbomb type of thing going on, but at least another pass on extracted files wont hurt?

if you need example nzb, from any of the normal sites grab `*.1080p.BluRay.x264-CLASSiC`   or hit me up on discord / or let me know and I can send you one.

**Comment by Safihre** [comment]
Can you send me one at safihre@sabnzbd.org? Easier to test for me if you already have one :)

**Comment by Safihre** [comment]
I tested one of these NZB's, and it worked as expected:
```
2022-09-07 10:15:19,244::INFO::[newsunpack:559] Extracting rarfile \\?\C:\Users\<USERNAME>\Downloads\complete\_UNPACK_Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Subs\cls-goldfinger.subs.rar (belonging to cls-goldfinger.subs) to \\?\C:\Users\<USERNAME>\Downloads\complete\_UNPACK_Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Subs
2022-09-07 10:15:19,247::INFO::[misc:1163] [N/A] Running external command: "C:\Program Files\SABnzbd\win\unrar\x64\UnRAR.exe" "x" "-idp" "-scf" "-o-" "-or" "-ai" "-p-" "\\?\C:\Users\<USERNAME>\Downloads\complete\_UNPACK_Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Subs\cls-goldfinger.subs.rar" "\\?\C:\Users\<USERNAME>\Downloads\complete\_UNPACK_Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Goldfinger.1964.INTERNAL.1080p.BluRay.x264-CLASSiC\Subs\"
2022-09-07 10:15:19,537::INFO::[newsunpack:862] Unpacked 2 files/folders in 0 seconds
```

**Comment by thezoggy** [comment]
And you see the subs folder now has a .rar and a .idx file. The .sub is not extracted because the nested rar never gets extracted.

**Comment by Safihre** [comment]
Yes it has extracted it, check the command above, it's running from the `complete` folder.
Resulting in:
![image](https://user-images.githubusercontent.com/5703454/188919282-fd6ad345-c168-4a29-aa24-ee9ada8f47f1.png)

**Comment by thezoggy** [comment]
It does not extract it if you use the flat unpack option

**Comment by Safihre** [comment]
Oke I found the problem:
This job is double-packed, so after unpacking the main `ABC.rar, ABC.r01, ABC.r02, etc` it results in the Complete Folder: `Movie.rar, Movie.r01, Movie.r02` (no, not obfuscated, just twice packed!).
Then it unpacks `Movie.rar, Movie.r01, Movie.r02`, which results in `Movie.mkv` and `Movie.rar` (with the subs).
However, we then skip this new `Movie.rar` because we already unpacked a file with the same name before.
This check is there because if a job is not set to `+Delete`, the rar files are not removed after each recursive run and we might get stuck in a loop.

This only happens because you have flat-unpack enabled, as otherwise the subs-rar would be `Subs\Movie.rar` and SABnzbd would see it as a new file and unpack it.

Not sure yet if I can easily fix this without the risk of breaking other exotic cases.

**Comment by thezoggy** [comment]
could we not add size to the rar list to use it as a distinguishing thing to know if we have processed the file, that way for this scenario it would know the same file but different sizes was actually two different files?

**Comment by thezoggy** [comment]
config switches > Ignore any folders inside archives -- unchecking this. 

results in the Subs subfolder with the .idx + .sub in it, and then radarr came along and imported the movie and the idx+sub within it. so yeah looks like i can just toggle that option off to get things working for me. ive had flat unpack on for so long (back before *arr apps, which did not look at subfolders). so anyways might be something we can at least note as suboptimal with the option since this isnt the first time ive ran into this exact issue over the years

**Comment by Safihre** [comment]
I tried another refractor, but the code just becomes unmanageable. Will close this as known issue, if you don't object.
