### ISSUE TITLE
Auto Pause of Free Space error

### ISSUE THREAD

**Issue by SirLaffalot** [sabnzbd/sabnzbd#2291]
Running version 3.6.1 [[fa844a6](https://github.com/sabnzbd/sabnzbd/commit/fa844a6)] with 3.10.7 Python on Archlinux (up to date). 
In Settings/Folders (Advanced), if I set Minimum Free Space for Temp/Down Folder value, it immediately pauses the download. For example, I set free space to 90G, command df says the partition has 153G, and SABnzbd shows 153G free space, but it's in red and the download is paused.
The only way I can get it to download is by not using that option at all.

**Comment by Safihre** [comment]
And what size is the download?
Did you read how this option works?

**Comment by Safihre** [comment]
Or this is the bug report about Direct Unpack from the forums?

**Comment by SirLaffalot** [comment]
My understanding of the option is that the downloading will be paused if the free space on the disk is smaller than the entered limit. There is also an auto-resume check box that says it will restart the option when free space climbs above the limit entered.
The download in question was about 5GB and the option set was '90G', and I'm not using Direct Unpack.

**Comment by SirLaffalot** [comment]
I'm not using var/lib/sabnzbd as a home for it, although both that and the home for it are on the same disc. Both are on the same partition p2 in case that's a question. p1 of that device is actually smaller than 90G if the actual bug is that it's checking the wrong partition.

**Comment by Safihre** [comment]
Could you provide a screenshot of the main page when this problem occurs? So that it shows the space free and the download information.

**Comment by SirLaffalot** [comment]
Dang! I can't replicate this problem today. I don't know why because I tried making the settings exactly the same. I'll try to close the issue, but if I can't, please do.
