### ISSUE TITLE
Show the custom job name in case of fetch-failure

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2294]
Could some greater logging be made within the visible GUI. At times I am getting errors with NZBHydra stored on the same machine.

Namehttp://127.0.0.1:5076/nzbhydra/getnzb/api/XXXXXX?apikey=XXXXX
Completeda few seconds ago
StatusFailed
Size0 B
Categorytv
Path
SourceURL Fetching failed
Maximum retries

e.g. (API and API Key mangled for this post) but it would be great if it could know WHAT file it was as presumably NZBHydra first communicated get something 1x01.mkv and the magic key, but the above only tells me something was wrong - this can be a challenge if you are downloading a lot.

From what I can see none of the indexers have reached a limit, but I have to guess as the info is not shown.

TVM!

**Comment by thezoggy** [comment]
set you logging to DEBUG in sab if you want to see more info. also enable api logging if not enabled (config > special), and for lower level you can enable cherrypy logging to see whats hitting the webserver directly

**Comment by thezoggy** [comment]
but anyways why something is failing to be added on sab side, is usually due to dupe detection. which you might have set to discard, and even if you remove it from history it will check your .nzb backup folder. so you'd have to turn that off or not use the .nzb folder if you really want to not have that possibly mess up adding a nzb

**Comment by Safihre** [comment]
@thezoggy no, he wants us not to just show the URL in history in case of a failed URL fetch, but also the name. As you can see from, the logging, we do have the name.
Will have to check if this is easy to fix.

**Comment by Safihre** [comment]
Fixed! Was really easy because we already stored this information.
