### ISSUE TITLE
SABnzbd deletes music files that contain the string 'sample'

### ISSUE THREAD

**Issue by neofright** [sabnzbd/sabnzbd#2296]
With the option to:

```
Ignore Samples
Filter out sample files (e.g. video samples/proofs). Delete after download. 
```
SABnzbd is deleting .flac files that end with* the word sample. This behaviour would have been silent if it wasn't for the fact I am using my [post processing script ](https://github.com/neofright/sabnzbd_srrdb).

EDIT: proof SABnzbd is detecting this as a sample:
```
2022-09-17 16:59:56,633::INFO::[postproc:1163] Removing unwanted sample file /shortened/path/GZA_Genius-Beneath_The_Surface-CD-FLAC-1999-FiXIE/02-gza_genius-amplified_sample.flac
```

I'm not sure how we should handle this, but the scene rules do not include samples for music - so maybe exclude .mp3 and .flac for sample deletion?

**Comment by sanderjo** [comment]
So SAB is behaving as it should: if Ignore Samples is on, it deletes *sample. And if not, not. Correct?

If so, what is the problem?

**Comment by neofright** [comment]
Seems like its a bit crude - just literally deleting any file with the string 'sample'. I mean your code base even has false positives in it like "Crime_Scene_S01E13_Free_Sample_For_Sale_480p-OhDear" etc.

Surely it would make sense to run some kind of file(1) check against the file to confirm if its a video file before deleting it, or checking the extension first like I suggested above?

Its fine if you have no plans to improve this, you can close the issue, and I'll use my own post processing script to delete samples.

**Comment by neofright** [comment]
@sanderjo How about changing `RE_SAMPLE` [here](https://github.com/sabnzbd/sabnzbd/blob/ac6fc37c7dc7f79c99c752ede8848683ff141af7/sabnzbd/misc.py#L70) to the regex I demonstrate below:
```
import re
RE_SAMPLE = re.compile(r"((^|[\W_])(sample|proof)\.(?!mp3$|flac$))", re.I)  # something-sample or something-proof

def is_sample(filename: str) -> bool:
    """Try to determine if filename is (most likely) a sample"""
    return bool(re.search(RE_SAMPLE, filename))

print(is_sample('02-gza_genius-amplified_sample.mp3'))
print(is_sample('02-gza_genius-amplified_sample.flac'))
print(is_sample('02-gza_genius-amplified_sample.mp4'))
print(is_sample('02-gza_genius-amplified_sample.avi'))
```
```
$ python3 sab_test.py 
False
False
True
True
```

**Comment by neofright** [comment]
Just to show that this issue is not isolated to a single album:
```
2022-09-17 19:54:59,069::INFO::[postproc:1163] Removing unwanted sample file /shortened/path/Arcane Atlas - Constellation Plus (2014) MP3/06 Sample.mp3
```
https://www.discogs.com/release/23966648-Arcane-Atlas-Constellation-Plus

**Comment by Safihre** [comment]
But, what if a sample file is included with an album or some other recording? Then users would come and complain here that we didn't delete it.
The detection is dumb on purpose, because trying to be smart about it is just creating more problems. 
And just adding the 2 extensions you care about is not helpful.. What about all the other audio formats?

**Comment by neofright** [comment]
Have you ever downloaded music in a format other than mp3 or flac from usenet?
I have never, ever seen an album that contains a sample.
The scene rules don't require it, and I don't think it makes any sense to include them. You would just download a single track and use that as your sample?
https://scenerules.org/t.html?id=2021_MP3.nfo
https://scenerules.org/t.html?id=2016_FLAC.nfo
You can see that [BLURAY](https://scenerules.org/t.html?id=2014_BLURAY.nfo) requires samples:
`P1)  Sample, nfo and sfv are required for each release.`

If you don't think my suggestions are helpful, I'm more than happy for someone to close the issue!

**Comment by thezoggy** [comment]
The intent of the option is to get rid of samples that usually come with media files. To do it properly, we would use ffprobe/mediainfo or something and get the runtime to know if its a sample vs using the crude check of a filename/text to make the decision which can run up against false positives such as this.  This is what *arr apps do and is a much better solution, so just turn off the option in sab and let those apps handle it during post processing.  There is also 3rd party sab post processing scripts that can do some of this stuff.

Now for sab, we could prob improve this ignore samples option to limit it to to x categories that the user sets, vs just doing it by all. As most people put their media related stuff in its own category (movies/tv/etc) and you'd want it ran on that, not on something like 'music' or some other category.  That way it would offer up a way to narrow the chance of this being a false positive.

**Comment by neofright** [comment]
Okay, thanks to all for your responses.

I'll disable sample deletion in SABnzbd and add removal to my post-processing script.

Because it is tailored only to work with scene releases (P2P don't have samples?), for my use case skipping flac and mp3 is good enough!

**Comment by neofright** [comment]
I hacked together the functionality to delete video samples in my post processing script.

It checks the filename inside of a "*sample.srs" file (extracted from the srr).
To prevent triggering on srs files like this:
```
02-gza_genius-amplified_sample.srs
10-bad_meets_evil-living_proof.srs
```
I check if the srr file has any archived files. Generally you can be pretty sure that the srr file is for music if there are no archived files.
If anyone wants to :shit: on my scripting skills a link is [here](https://github.com/neofright/sabnzbd_srrdb/commit/f3417896e59ca9d26aa579fac3d2c48698fe1532) :smile:
