### ISSUE TITLE
Error "No file given, or not found (None)" in case of "Aborted, cannot be completed - https://sabnzbd.org/not-complete"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2297]
... caused by deobfuscate(), from this code:

```
    if not biggest_file or not os.path.isfile(biggest_file):
        # no file found, which is weird
        logging.error("No file given, or not found (%s)", biggest_file)
        return
```
So ... deobfuscate() is called, even if the download cannot be completed?

**Comment by Safihre** [comment]
Just a double check, is Post process only verified jobs turned _On_?

**Comment by sanderjo** [comment]
> Just a double check, is Post process only verified jobs turned _On_?

No, it was off.
Turned it on now.
Thanks

```
Post-Process Only Verified Jobs
Only unpack and run scripts on jobs that passed the verification stage. If turned off, all jobs will be marked as Completed even if they are incomplete.
```

**Comment by Safihre** [comment]
Shall we just remove this `logging.error` then?

**Comment by sanderjo** [comment]
> Shall we just remove this `logging.error` then?

Change it to logging.debug() ?
