### ISSUE TITLE
Corruption of sabnzbd.ini with name change on RSS feed

### ISSUE THREAD

**Issue by muggsyd** [sabnzbd/sabnzbd#2300]
Using 3.6.1 via docker I was about to corrupt my ini file by changing the display name within multiple RSS feeds.

For example, I normally tag my RSS feed with the category of the feed, and the feed name
i.e. [TV] Survivor
Here are the steps to replicate
- Create new RSS Fed title "[TV] Survivor"
-  Upon saving the initial "**[**" is actually removed without a warning
-  Edit the existing RSS feed and add back the "**[**" and save without issue
- Everything works as expected, until restart Sabnzbd at which point Sabnzbd doesn't not start and states **Fatal error** "sabnzbd.ini" is not a valid configuration file

Once the sabnzbd.ini file is opened it's clear that there are extra characters and the field in the ini is now **[[[TV] Survivor]]**
This is resolved by manually editing the sabnzbd.ini and removing the etc "**[**"

A fix should be to make the initial "**[**" character a banned character in the title field to avoid this

**Comment by Safihre** [comment]
We indeed have filtering to just remove it before saving it to the INI, so I am surprised it allowed you to save it the second time.
Will investigate.

**Comment by Safihre** [comment]
Turned out that during the rename we did not filter it. Fixed that.
