### ISSUE TITLE
7z support does not detect "7z" binary if the "7za" binary is not found

### ISSUE THREAD

**Issue by KaraokeStu** [sabnzbd/sabnzbd#231]
This was tested in a Synology device running DSM 5.2, which has 7z support installed as part of DSM

Unfortunately, this is installed as the binary "7z"

You can get around the issue by doing the following:

    update-alternatives --install /usr/syno/bin/7za 7za /usr/syno/bin/7z 50

However, this is not ideal and ideally we wouldn't want to be messing around with the synology directories as these can be modified with new upgrades.

Could you get the 7z check to fall-back and search for the 7z binary if the 7za binary is not found?

**Comment by shypike** [comment]
Sure

**Comment by KaraokeStu** [comment]
Great stuff :+1: Thanks

**Comment by shypike** [comment]
Will be fixed in 0.8.0 Alpha3
