### ISSUE TITLE
NZBs from nzbindex.nl do not get filtered by the RSS filters

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#2314]
NZBs from nzbindex.nl do not get filtered by the RSS filters. For instance I have the following RSS feed configured:

https://nzbindex.nl/rss/?q=eBook | magazine | truepdf | auto &maxsize=50&complete=1&hidepassword=1&max=250

and the filters:

Reject fiat default default default none
Accept bmw default default default default

I expect that SABnzbd will only queue NZBs with bmw in the name as long as fiat is not in the name. But it queues all NZBs it received from the RSS feed. Filtering RSS feeds from other indexers works fine.

Not sure if this is relevant, but I have the special setting: 
rss_odd_titles ( nzbindex.nl/, nzbindex.com/, nzbclub.com/ )
set to its default, which is:
nzbindex.nl/, nzbindex.com/, nzbclub.com/

**Comment by sanderjo** [comment]
I believe I put a "Reject *" as last entry in each of my RSS settings.
So ... does that work for you?

**Comment by sanderjo** [comment]
rules, plus Matched:
![image](https://user-images.githubusercontent.com/1273502/196717580-f5d8a0bf-da85-4524-8a82-fad1606612d7.png)

rules, plus Not Matched: "rona", and after else:

![image](https://user-images.githubusercontent.com/1273502/196717749-0cd0f78d-900d-4876-a305-bd4dc03da19a.png)

**Comment by thezoggy** [comment]
Yep we make no implicit reject all at the end. Users may want all but only reject something or the inverse.. which requires you to accept only x and reject the rest. Also different uses of rss where some are carts so nothing is ever on it unless explicitly added on far side
