### ISSUE TITLE
Pointless update reminder

### ISSUE THREAD

**Issue by anonvoy** [sabnzbd/sabnzbd#2319]
I'm running SABnzbd from the Github source, currently I'm at commit 5fa7bea, version 3.7.0Beta1. For some days now, I get a rather pointless "INFO Update Available! 3.7.0RC1" with every start of the program. Is it possible to turn that off?

**Comment by sanderjo** [comment]
Me too. Will be fixed soon.

**Comment by Safihre** [comment]
Just disable the update check......
https://sabnzbd.org/wiki/configuration/3.6/general
