### ISSUE TITLE
Cosmetic: Show disabled checkboxes as un-checked if unavailable

### ISSUE THREAD

**Issue by KaraokeStu** [sabnzbd/sabnzbd#232]
Hi,

On the back of my previous 7zip issue, it was a little strange to see that disabled checkboxes are checked, despite the fact they cannot be enabled.

In the case of multi-core par2 and 7zip, it would be good to both disable and un-check the box if it is unavailable.

**Comment by shypike** [comment]
The reason to keep the enabled fields, is that people re-use ini files on different platforms.
Maybe it's possible to just show such an option as disabled.
I'll see what is possible.

**Comment by KaraokeStu** [comment]
Ah that makes sense now - I'd suggest showing an un-checked checkbox with no name, and storing the underlying actual checked value in a hidden field :smile:
