### ISSUE TITLE
Pause all selected aborts the selected entries instead of pausing

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#2324]
Version: 3.7.0RC1 

As the title says, when you use the multiselect function, select a few running entries from the download queue, and now select "pause" in the bottom dropdown, the entries will abort and move to finish queue, where they cannot get unpacked because they are not completed.

The selected entries should stay in download queue and just pause/stop downloading until user continues them.

**Comment by reloxx13** [comment]
Hello,

No, i wrote i used the pause from the dropdown, not the button.
Where u set the priority

**Comment by Safihre** [comment]
Yes, so that actually is "Stop".
I think we should update that translation to "Halt"?

**Comment by reloxx13** [comment]
> Yes, so that actually is "Stop". I think we should update that translation to "Halt"?

Ahh okay, i would suggest "Abbrechen" (Cancel).

**Comment by Safihre** [comment]
I updated the translation in the translation platform.
It will be updated for the next release.

**Comment by Safihre** [comment]
See https://github.com/sabnzbd/sabnzbd/commit/a14a2f6c96410f109a1c600ec98aabfb125065d5

**Comment by reloxx13** [comment]
Thank you 👍🏻

**Comment by Safihre** [comment]
@reloxx13 In case you see other translations that are not correct or not nice, it's actually very easy to correct them :)
See: https://sabnzbd.org/wiki/translate

**Comment by reloxx13** [comment]
I translate some other projects and ill add sab to my list 👍🏻

**Comment by reloxx13** [comment]
This is still strange, why is the cancel in the priotity? And there is no way to add entries and have them initially paused (cause u could select "Anhalten(Pause)/Cancel" in the priority dropdown by the categories setting.

Who would need to at downloads canceled ??? This is a bug or was recently changed. It was pause and not cancel.

**Comment by thezoggy** [comment]
I believe the wrong translation was changed.

**Comment by Safihre** [comment]
No, the translations are causing the confusion here.
If you switch to English, you'll see that when adding the NZB's (so in Categories but also in the Add NZB window) you can select Paused (Angehalten) as priority. During downloading the Paused priority is not there, as we have the pause button for that. But, during downloading you have the priority Stop, which of course is not there when adding NZB's. 
Both Paused and Stop were translated as Anhalten.

**Comment by reloxx13** [comment]
Ahhhhh okay i see now i get it, thank you.

**Comment by Safihre** [comment]
If you have time, there's still some German translations open. Then I can include those in 3.7.0 final :)
https://www.transifex.com/sabnzbd/sabnzbd-translations/translate/#de/po-main-sabnzbd-pot--develop/407397707?q=translated%3Ano

**Comment by reloxx13** [comment]
done 👍🏻
