### ISSUE TITLE
3.7 - wrong priority

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2332]
per api priorities are:
![firefox_2022-11-06_12-16-57](https://user-images.githubusercontent.com/500882/200187959-f167d20b-adf4-41c7-abd5-4303f81bd24b.png)

When adding a nzb, there is no Paused but gui shows Stop
![sab](http://zoggy.net/firefox_2022-11-06_12-16-27.png)

I assume this is fallout from that recent german request

**Comment by thezoggy** [comment]
skintext is good
```
    "pr-paused": TT("Paused"),  #: Priority pick list
    "pr-stop": TT("Stop"),  #: Priority pick list
```

looks like issue is:

glitter.queue.js
```
    // But when you want to set Priority you need the number..
    self.priorityName = [];
    self.priorityName["Force"] = 2;
    self.priorityName["High"] = 1;
    self.priorityName["Normal"] = 0;
    self.priorityName["Low"] = -1;
    self.priorityName["Stop"] = -4;
    self.priorityOptions = ko.observableArray([
        { value: 2,  name: glitterTranslate.priority["Force"] },
        { value: 1,  name: glitterTranslate.priority["High"] },
        { value: 0,  name: glitterTranslate.priority["Normal"] },
        { value: -1, name: glitterTranslate.priority["Low"] },
        { value: -4, name: glitterTranslate.priority["Stop"] }
    ]);
```

so there is a Stop and a Pause or just really Pause thats mis named?

**Comment by thezoggy** [comment]
adding a job with "stop" priority per gui results in a "paused" job being added

**Comment by Safihre** [comment]
The reason is that for the Add NZB box we use the same list of `priorityOptions` as for the dropdown in the queue.
It's been like that since ages, but indeed that seems wrong. Add NZB should have the same list as the Config Categories list.

**Comment by ItsME6969** [comment]
@Safihre not sure if this is also the same bug or if it works as intended, but I've always had issues with the ordering of my categories. When I install and setup SAB, the category order mirrors the one in the settings but after a while the order always changes for some reason. I usually like `Default` at the top but looking at the screeenshot its found its way to the bottom of the list. I'm on 3.7 linux currently.

![Screenshot 2022-12-09 114333 - Copy](https://user-images.githubusercontent.com/89707006/206762848-c68e3941-f275-44e1-8b67-eed22d11662a.png)
![Screenshot 2022-12-09 114610 - Copy](https://user-images.githubusercontent.com/89707006/206762852-92cafb49-4637-42af-8eb2-b5fd0f094485.png)

**Comment by Safihre** [comment]
It's unrelated, but deserves it's own issue indeed.

**Comment by ItsME6969** [comment]
Alright thanks guys I'll open a new one.
