### ISSUE TITLE
Unchecking Tray Icon does not remove from menu bar in Mac OS Ventura 13.0

### ISSUE THREAD

**Issue by eoren1** [sabnzbd/sabnzbd#2336]
Unchecking tray icon in Sabnzbd 3.7.0 and clicking save does not remove it from the top menu on MacOS Ventura. I've tried restarting after checking - saving then restart - uncheck - save - restart but the icon keeps showing up on every restart of SAB.

Don't see anywhere other than 'Special' to remove it so assume it is a bug possibly with the new OS?

**Comment by thezoggy** [comment]
you are unchecking  special > tray_icon ?

**Comment by Safihre** [comment]
I can't reproduce this on my Mac, it's nicely hidden. 
Because the code also didn't change, the previous `osx_menu` was exactly at the same spot..

Did you really shutdown the whole of SABnzbd?

**Comment by eoren1** [comment]
Thanks for trying to reproduce
Yes I did do a restart from the SAB program after checking then unchecking and saving each time
Just updated to 13.0.1 which included a restart and tray icon now gone so I'll take as a temp issue.
