### ISSUE TITLE
sab backup - include cert?

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2338]
perhaps we should include the relevant sab cert/key so it makes the backup that much easier to restore..

- HTTPS Certificate
- HTTPS Key
- HTTPS Chain Certificates

**Comment by Safihre** [comment]
Sounds good!
One concern: when restoring these allow a custom path. To prevent malignant use I think we should reset these 3 settings to the default value and place the restored files there. Otherwise malignant files could be placed anywhere.

**Comment by thezoggy** [comment]
So, we should place in the admin folder and set path to that (which is default, so just filename)

**Comment by Safihre** [comment]
Yes. And if the files have a different name on the source system (also possible) they should be renamed to their defaults when creating the backup so it's uniform.

**Comment by thezoggy** [comment]
forgot about this, thanks bot

**Comment by Safihre** [comment]
I worked on this a couple of times but never got a pretty solution..

**Comment by thezoggy** [comment]
Bump

**Comment by thezoggy** [comment]
bump
