### ISSUE TITLE
typing "S" in new Tab results in "Local IPv4 address  Connection failed!" (until clicking on Wrench symbol with mouse)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2346]
open new tab, go to SAB's interface, type "S" on keyboard ... immediatly results in:

![image](https://user-images.githubusercontent.com/1273502/202868534-bf72380a-0777-43c2-96da-b56e505ce112.png)

Close it, type "S" again, and again that "Local IPv4 address  Connection failed!".  And again, and again.

But: Click with mouse on Wrench symbol, and filled out popup appears. Close it, type S, and nicely filled too.

So ... a problem with pre-filling? Once it's filled via Wrench, it's OK ... ?

```
Local IPv4 address  Connection failed!
Public IPv4 address  Connection failed!
IPv6 address  
Nameserver / DNS Lookup  Connection failed!

Internet Bandwidth  MB/s  NaN Mbps
```

**Comment by sanderjo** [comment]
Typing S does not result in any logging.
Whereas clicking on Wrench results in loggin

```
2022-11-19 20:47:41,558::DEBUG::[getipaddress:101] Local IPv4 address = xxx
2022-11-19 20:47:41,582::DEBUG::[getipaddress:155] Public IPv4 address = xxx (in 0.02 seconds)
2022-11-19 20:47:41,582::DEBUG::[getipaddress:168] IPv6 address = 2001:bbb
2022-11-19 20:47:41,587::DEBUG::[getipaddress:88] DNS Lookup = True (in 0.00 seconds)
```
So that confirms my hypothesis that typing S only shows the popup without actually doing any work

**Comment by Safihre** [comment]
Introduced by #2346.
So it works fine in 3.7.x, only develop was broken.
Fixed now.
