### ISSUE TITLE
Pre-queue - Exclamation marks removed from SAB_FILENAME and SAB_FINAL_NAME 

### ISSUE THREAD

**Issue by mrboring** [sabnzbd/sabnzbd#2351]
Hi

Sabnzbd Version: 3.7.0 [b6fd915]
Window 10 x64 build 10.0.19045

I use RSS to get nzb files. I have a pre-queue batch file script that calls a PowerShell script. Unfortunately the environment variables `SAB_FINAL_NAME` and `SAB_FILENAME` have exclamation marks removed from them before calling the batch file. This stops my pre-queue script from working.

Example nzb file name:

```
American.Dad!.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD+5.1.H.264-NTb.nzb.gz
```

The batch file receives:

```
SAB_FILENAME     : American.Dad.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD+5.1.H.264-NTb.nzb
SAB_FINAL_NAME   : American.Dad.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD+5.1.H.264-NTb.nzb
```
Note the missing exclamation mark.

Below are the contents of the `pre-queue.bat` batch file:

```batch
@ECHO OFF

REM https://sabnzbd.org/wiki/scripts/pre-queue-scripts

SETLOCAL ENABLEDELAYEDEXPANSION

SET debug=%USERPROFILE%\Desktop\debug.txt
REM SET debug=NUL

ECHO pre-queue.bat ---------------------------------------- >> %debug%
ECHO Pre-queue Start  : %date%%time% >> %debug%
ECHO Current Directory: %CD% >> %debug%
ECHO Arguments        : %* >> %debug%
ECHO ERRORLEVEL Before: %ERRORLEVEL% >> %debug%
ECHO SAB_FINAL_NAME   : %SAB_FINAL_NAME% >> %debug%
ECHO SAB_FILENAME     : %SAB_FILENAME% >> %debug%
ECHO SAB_BYTES        : %SAB_BYTES% >> %debug%

REM To enable detailed logging add: -EnableLogDetail
REM %~dp0% returns the folder the script is in with a trailing \
pwsh.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -NonInteractive -File "%~dp0%pre-queue.ps1" ^
	"%SAB_FILENAME%" "%SAB_BYTES%"
REM -EnableLogDetail

ECHO ERRORLEVEL After:  %ERRORLEVEL% >> %debug%
ECHO %ERRORLEVEL%
```

**Comment by Safihre** [comment]
I can't reproduce this, just before we call the script this is the input:
![image](https://user-images.githubusercontent.com/5703454/204774083-566c03da-8181-4ecf-8cdb-69b5ac202584.png)

Seems to be something `.bat` specific, because if I use the `Sample-PostProc.py` included with SABnzbd you can see it's passed correctly:
```
SAB_FILENAME American.Dad!.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD+5.1.H.264-NTb.nzb
SAB_FINAL_NAME American.Dad!.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD+5.1.H.264-NTb
```

**Comment by mrboring** [comment]
I think you're right about it being a batch file related issue. In the past I had another issue with file names containing commas.

Unfortunately I'm not familiar with Python (don't mind learning a bit though).

I can see several ways to try to get around this:

* Call the PowerShell directly without going through the batch file. Not sure that this is possible with Sabnzbd.
* Call the PowerShell using a script based on `Sample-PostProc.py`. Best for a quick solution.
* Convert the batch file/PowerShell script to a Python script. Might be the best solution, but not sure what is involved.

Do I need to install a version of Python (if yes, what version?), or does one come with Sabnzbd?
I use VSCode. Are there any guidelines on how to setup a development environment for Python and Sabnzbd?

Any help on the above would be appreciated.

**Comment by Safihre** [comment]
SABnzbd will allow to run any scripts with extensions that are listed in the `PATHEXT` environment variable.
You could try to add `ps1` to that and see if SABnzbd can run the script directly.

Regarding Python: it's super easy, just download it from python.org and run the installer. 
VSCode has native support for Python scripting and Python itself is easy. Of course, I don't know what your script needs to do.

**Comment by mrboring** [comment]
Thanks, I appreciate you taking the time to help.

**Comment by thezoggy** [comment]
you should look at "setlocal EnableDelayedExpansion" in your batch script. otherwise your going to see it remove `!` and such.
https://ss64.com/nt/delayedexpansion.html

and look at:
https://stackoverflow.com/questions/4094699/how-does-the-windows-command-interpreter-cmd-exe-parse-scripts/4095133#4095133


but yes you might want to use another scripting language you are more familiar with, or atleast use python3 since many sab example scripts exist out there using it.

**Comment by mrboring** [comment]
@thezoggy Thanks for the info. BTW that stackoverflow post has so much detail!

I've had several issues relating to batch files and have had to spend a lot of time working around them. I've decided it's time to use Python instead. Initially I'll just use it to call my PowerShell script, eventually I may replace the PowerShell script with a Python script.

**Comment by mrboring** [comment]
I've converted my batch file to a Python script. However, it only works if I do at least one `print` before doing `sys.exit(0)`. Is this the expected behaviour?

The following are from `sabnzbd.log`.

No `print` but returned 0. Should refuse, but accepts:

```
2022-12-01 10:13:42,471::INFO::[newsunpack:2317] Pre-queue script returned 0 and output=
2022-12-01 10:13:42,472::INFO::[newsunpack:2342] Pre-Q accepts American.Dad!.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD.5.1.H.264-NTb
```

A `print` and returned 0. Refuses:

```
2022-12-01 10:14:54,071::INFO::[newsunpack:2317] Pre-queue script returned 0 and output=
got here
2022-12-01 10:14:54,072::INFO::[newsunpack:2338] Pre-Q refuses American.Dad!.S19E19.Jambalaya.1080p.AMZN.WEB-DL.DD.5.1.H.264-NTb
```

Contents of `pre-queue.py` test script:

```python
import sys

print('got here') # When commented out accepts

sys.exit(0)
```

**Comment by mrboring** [comment]
D'oh! I didn't do enough reading. Thanks for the explanation.
