### ISSUE TITLE
[BUG] Speed limit tuning doesn't work after restarting container

### ISSUE THREAD

**Issue by adamyeager** [sabnzbd/sabnzbd#2355]
I'm experiencing an issue where the setting for setting the maximum speed (General -> Tuning -> Maximum Line Speed) doesn't work initially when restarting my sabnzbd container.

I currently have it set to 85 MB/s and when I go back to the main page and click the down arrow near the current download speed I can see it says "100% 85 MB/s". However it doesn't work if I restart the application. If I start downloading something it will max out my connection speed and only when I click the drop down and throttle it to some random percentage and then back to 100% will it actually use the setting I've set.

![over speed](https://user-images.githubusercontent.com/3915838/205122248-a3a687d3-0868-4226-9cee-a0b3e5c7ef83.png)

**Comment by Safihre** [comment]
In Config General set Percentage of line speed to 100.
This was a bug that this wasn't prefilled on old configs.

**Comment by adamyeager** [comment]
Ah, I see it's under the advanced options. Thanks for the help!
