### ISSUE TITLE
Crash on Windows shutdown: `sys.stdout` and `sys.stderr` not defined by new PyInstaller version

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2360]
Change in latest PyInstaller: https://github.com/pyinstaller/pyinstaller/pull/7217

Resulting in crash when SABnzbd is shutdown on Windows:
![image](https://user-images.githubusercontent.com/5703454/205653454-59158eb7-d144-4180-bc2f-3c476cdabef4.png)

Needs a fix and check if we don't use these on other spots.

**Comment by thezoggy** [comment]
looks like just when we shutdown sab or when we start sab up in daemon mode (-d)

**Comment by puzzledsab** [comment]
I only find it twice in `misc.py` with grep. Just try/except and pass on the error?
