### ISSUE TITLE
Native Android device support? 

### ISSUE THREAD

**Issue by Pentaphon** [sabnzbd/sabnzbd#2365]
NZBGet made it possible to install nzbget to Android using: https://github.com/nzbget/android

I'm aware of https://sabnzbd.org/wiki/advanced/android.html but it's not the same as an easy to use solution that can be downloaded from the sabnzbd homepage. 

Will it ever be possible to install and run sabnzbd on an Android device in a similar manner with a simple APK and then connect to the localhost instance using your default web browser? That would make sabnzbd amazing for phones and especially tablets. 

Any long terms plans for making it simple for the average user to install sabnzbd on their Android device with just an APK from this project?

**Comment by thezoggy** [comment]
just because you can run something on an android device doesnt mean you should. usenet downloaders generally require a bit of disk io + memory then let alone cpu for yenc/repair. i cant see it being an overly good experience for people to try and run sab on an android tablet/phone/set top box (most of them are underpowered)

**Comment by Pentaphon** [comment]
> i cant see it being an overly good experience for people to try and run sab on an android tablet/phone/set top box (most of them are underpowered)

Even a budget phone that I had nzbget-android on downloaded and unpacked just as quickly as my laptop did. I didn't use it for HUGE files, of course, but for anything smaller than 5GB, it did just fine. My current phone has flagship specs and probably many times faster doing the same job.

**Comment by thezoggy** [comment]
sab is a python based app which uses various libs. python on android isnt really a thing, so its a bit more to it all...  besides things like arm/32bit only support and all the other oddities that come with android env let alone with sandboxing/permissions and other stuff that came with newer android

**Comment by Pentaphon** [comment]
Can we not have the stale bot close this? This is a long term feature request that could happen someday. It doesn't make sense to just close it because nobody comments on it for a month.
