### ISSUE TITLE
Sample Config File with Comments?

### ISSUE THREAD

**Issue by iwinux** [sabnzbd/sabnzbd#2374]
Hi,

I've searched the repo and could not find any sample config file to use. And the [manual](https://sabnzbd.org/wiki/configuration/3.7/general) does not seem to explain every option available in the default generated `sabnzbd.ini`. For example, what should be the correct value for `nice = ""` and `ionice = ""`?

**Comment by sanderjo** [comment]
nice and ionice are explained in https://sabnzbd.org/wiki/configuration/3.7/switches -> https://sabnzbd.org/wiki/configuration/3.7/switches#nice

> I've searched the repo and could not find any sample config file to use.

SABnzbd generates one for you on the first start of SABnzbd (via the wizard). And the SAB GUI shows all options plus (pointer to) explanation.

**Comment by iwinux** [comment]
Thanks for explanation :)

As for the manual editing part - for any service that has a text config file, I would try to automate its setup via Ansible. Otherwise I'll need to repeat the setup whenever I deploy a new instance.

(BTW: I just finished deploying SABnzbd on two servers and they work great!)

**Comment by sanderjo** [comment]
For Ansible, I would do this:

1. Let the SAB wizard create a standard sabnzbd.ini once, inclusing newsserver(s). Save it as sabnzbd.ini.org. Maybe it's good enough for Ansible installs
2. via the SAB GUI, change the settings you want, if any. Possibly the directories you want SAB to use.
3. use diff to what has changed, and apply that via Ansible.
