### ISSUE TITLE
SABnzbd 3.7.1 Seven security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by coolsudheera** [sabnzbd/sabnzbd#2378]
SABnzbd 3.7.1 
Seven security vendors flagged this file as malicious.
Please fix this.
https://www.virustotal.com/gui/file/d7d62f2130dd0b65cf48c9dd7301cf5c86f178ba672a8ba0cf4ec012be5b6985/detection

**Comment by sanderjo** [comment]
New here? Welcome

Those security vendors will fix that themselves; it takes them a few days to learn it's not malicious.

**Comment by Safihre** [comment]
@sanderjo is already proven right, as now only 6 indicate it as malicious.
