### ISSUE TITLE
End of queue script to be moved to it's own configuration menu item

### ISSUE THREAD

**Issue by ErikBrown2** [sabnzbd/sabnzbd#2385]
About the end of queue script, why is it not taken seriously like the other scripts that have their own configuration menu entry? I have implemented my own duplicate NZB detection solution and for that I use the end of queue script. It removes NZBs that were added by the pre-queue script to the list for duplicate detection but that were manually removed before downloading from the download queue.

Having this end of queue script causes me not to be able to use any other option of the on queue finish pull down list such as shutting the PC down on end of queue. I used to keep the PC with SABnzbd always on but with the current power prices I prefer to shut it down after the queue is completed.

I assume that there will be also other users that have implemented an end of queue script. So I would like to suggest to remove it from its current place in the on queue finish pull down list and give it it's own entry in the configuration menu.

**Comment by Safihre** [comment]
Sounds reasonable indeed.

**Comment by Safihre** [comment]
Note that the value is not automatically converted when updating SABnzbd version, so after the update to this version you need to go into Config > Switches and select the script once. 
I will add that to the release notes.

**Comment by ErikBrown2** [comment]
Thanks for the change. This will be very useful.
