### ISSUE TITLE
Dark mode for SABnzbd Config

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2386]
Since the main UI has a light/dark mode

It would probably be a good idea to provide a dark mode for the config section also.

**Comment by xxcriticxx** [comment]
Great idea! I have seen this request by a few people on Reddit.

**Comment by Cpuroast** [comment]
Would probably need to be linked to the "Web interface" selection.

**Comment by thezoggy** [comment]
We used to have themed config but it was removed to make things simpler and streamline things. It was a pain to update each theme for any config change let alone testing it all. The whole just dark/light may not make things too complex. Besides the config the login page also a fixed light theme.

**Comment by Cpuroast** [comment]
Config page is actually used quite a bit, add new filters to RSS feeds, make changes to usenet servers, tweak/add categories, etc etc etc.

And going from a dark mode OS UI, with a dark mode sab webUI, to the blinding config UI is extremely jarring.

**Comment by Safihre** [comment]
It's been requested so much I'll just attach the Feature Request label if someone else wants to pick it up.
We could make it behave just like Glitter Auto, so using the system settings using the special css media query. I do not want to make it rely on main template selection.

**Comment by puzzledsab** [comment]
I'm no good with CSS and Javascript but I can help with the Python and config part if it's needed.

**Comment by modem7** [comment]
It'd be lovely to also have a "default" theme we can set via an env var.

This would allow for a more global theme, including at the login page.
