### ISSUE TITLE
Please update the Docker container on Dockerhub

### ISSUE THREAD

**Issue by jameskitt616** [sabnzbd/sabnzbd#2389]
Please update The [sabnzbd/sabnzbd](https://hub.docker.com/r/sabnzbd/sabnzbd/tags) container, it got it's last update 2 years ago.

**Comment by Safihre** [comment]
We are not the maintainers of that image, even though it might look like that.
That's why we also don't list it as an official installation option: https://sabnzbd.org/wiki/installation/install-unix
