### ISSUE TITLE
Use walrus operator, removing Python 3.7 support 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2394]
I would like to start using the new walrus operator that was introduced in Python 3.8.
This would break Python 3.7 support for the next major SABnzbd release.
The official EOL for Python 3.7 is in a few months, so doesn't seem like a big problem?
I also saw that Ubuntu uses Python 3.8 in 20.04 LTS so we are good there.
Anything I'm overlooking here?

**Comment by thezoggy** [comment]
Hopefully in this docker relevant world we won't be held back by nas with outdated python... But jcfp for example hacks back in py3.6 support... So he might be the best sounding board on why not to do it

**Comment by sanderjo** [comment]
> But jcfp for example hacks back in py3.6 support for his ppa.

Possibly because:

Ubuntu 18.04 is still supported until April 30, 2023 (so 4 more months)
Ubuntu 18.04 has Python3.6

**Comment by sanderjo** [comment]
About walrus operator:

```
>>> a=5
>>> if (b:=a+100) > 10: print(b)
... 
105
>>> 
```
Ah, so finally the C assignment + value in Python? Good.

And "walrus" because of the long teeth in ":=" ?

**Comment by Safihre** [comment]
Thanks for the input 👍 will go ahead with the changes.
