### ISSUE TITLE
URLdecode on api addurl 

### ISSUE THREAD

**Issue by DirtyDutch** [sabnzbd/sabnzbd#241]
When doing a request using jQuery to the API url of Sabnzbd, it automatically encodes the URL. Would it be a good idea to decode the url before adding to sabnzbd? Currently sabnzbd states: 'Trying to fetch URL:  https%3A%2F%2Fnzbindex.com%2Fdownload%2F'...

Seems to look like #73.. The URL is properly encoded (just like any other onlne url encode tool would do).

**Comment by shypike** [comment]
Which API call are you talking about?

**Comment by DirtyDutch** [comment]
The addurl call

**Comment by thezoggy** [comment]
just encode it before sending it. if your doing this via the command line its pretty easy..
`curl -G "http://localhost:8092/api?mode=addurl&cat=tv&priority=0&output=json&apikey=cebf71d1cb1122e84faa3b3a0d77bd79&" --data-urlencode "name=https://nzbsite.in/getnzb/a5fe5a99eeacd7842042db24a4fc48e2/Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb/?i=5674&r=apikey_removed"`

**Comment by DirtyDutch** [comment]
I'm calling like below:
http://sab/api?apikey=xxx&mode=addurl&name=https%3A%2F%2Fnzbindex.com%2Fdownload%2F123208330%2FDescription-ubuntu-12.04.1-desktop-i386.iso-695.29-MB.nzb&output=json&nzbname=-+Description+-+%22ubuntu-12.04.1-desktop-i386.iso%22+-+695.29+MB+-+yEnc

**Comment by thezoggy** [comment]
yes for the url you are urlencoding it. now not sure why your urlencoding the nzbname.. let alone giving such an awful/invalid name for the nzbname..

**Comment by DirtyDutch** [comment]
But my example is not working, and your example is working. What is the difference?

**Comment by thezoggy** [comment]
the `=` is part of your url?

**Comment by shypike** [comment]
SABnzbd does it right.
