### ISSUE TITLE
Docker image not updated for 2 years

### ISSUE THREAD

**Issue by intel352** [sabnzbd/sabnzbd#2415]
Last release pushed to Docker was 2 years ago, v 3.2.1. Why is this not being maintained?
https://hub.docker.com/r/sabnzbd/sabnzbd

**Comment by albino1** [comment]
That's just some guy who used the name, nothing to do with the maintainers of this project.

Try the LinuxServer.io version or one of the other ones:

https://hub.docker.com/r/linuxserver/sabnzbd/

**Comment by thezoggy** [comment]
@intel352 because it has nothing to do with us 🤐 some random person prob trying to help community out but isn't keeping it up to date. 

Thought we have something on our wiki/site that talks about the Dockers that are maintained (lsio/hotio) being the main two. Then there is a few others for nas specific variants

**Comment by intel352** [comment]
Good to know, thanks!

**Comment by Safihre** [comment]
If anyone has a good spot where I can submit a takedown/takeover request? Couldn't find obvious contact information.

**Comment by sanderjo** [comment]
https://hub.docker.com/support/contact

**Comment by Safihre** [comment]
Ah 😂 submitted a ticket to get it removed.

**Comment by thezoggy** [comment]
looks like it was done by this person: https://github.com/sabnzbd/sabnzbd/issues/188

**Comment by Safihre** [comment]
Ah yes here they are: https://github.com/domibarton/docker-sabnzbd/issues

**Comment by thezoggy** [comment]
Can see the history of abandonment for the repo and dockerhub changes resulted in auto builds stopping. So might be best to kill it off lin lieu of established Dockers that are maintained

**Comment by Safihre** [comment]
My complaint to Docker Hub was successful, apparently there is a procedure for this ("account squatting") and they have now given me access to this Docker!

**Comment by Safihre** [comment]
So what shall I do with it? Just delete it?
@sanderjo @jcfp

**Comment by sanderjo** [comment]
> So what shall I do with it? Just delete it?

or point with a URL to https://hub.docker.com/r/linuxserver/sabnzbd ? Always uptodate & maintaned, and seems to be the default one / most used (right?).

**Comment by Safihre** [comment]
Yes, but the people that are already using this Docker won't see that.
I will indeed put a big notice that the images will be removed in 3 months and to switch.

**Comment by sanderjo** [comment]
and maybe a note for Synology users? They use the sab-docker provided by ... Synology, or at least the Synology package manager? I have no Synology, so I can't check.

Maybe a note to the LSIO people that we plan to do this, and get their confirmation/agreement? I guess they will be happy.

**Comment by Safihre** [comment]
Updated the About page that I will remove the image in 3 months:
https://hub.docker.com/r/sabnzbd/sabnzbd
Also notified the source-repo, in case anyone checks out the source:
https://github.com/domibarton/docker-sabnzbd/issues/74

**Comment by Safihre** [comment]
Due to changes at Docker, I will delete the image already as I might loose access to it otherwise:
https://blog.alexellis.io/docker-is-deleting-open-source-images/

**Comment by thezoggy** [comment]
docker already announced the reversal of the stuff that came out a few days ago

**Comment by Safihre** [comment]
Yeah I tried but it still says the username is occupied. Right after I deleted the organization and also at the moment.
There should be some squatting protection in place according to their announcement.
