### ISSUE TITLE
Segfaults in buffered_reader branch

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#2419]
I got some segmentation faults in this branch. I think it's somewhat timing related because I got them in a specific spot until I added some logging. After that I haven't gotten any so I don't know what causes it. I did find out that some uploaders actually do use part sizes of just under 4 MB, though.

**Comment by Safihre** [comment]
Hmm, now the question is if this is in the SSL read or the decode?
Maybe disable SSL to test?

Are you sure about those giant articles? Do you have an example NZB? Because I've often seen 384.000 bytes, but not 4MB.

**Comment by puzzledsab** [comment]
Grepping through my done dir it turns out that about 2% of the nzbs have > 3 000 000 byte segments. It's mainstream content.

`zgrep -m 1 -H -P 'segment bytes="3\d{6}"' *.nzb*`

**Comment by thezoggy** [comment]
in my nzb backup folder, mostly just tv there are 4857 nzbs...  only one hit with that zgrep - `3840000`

**Comment by mnightingale** [comment]
Don't you already increase the buffer by 1MB?

https://github.com/sabnzbd/sabnzbd/blob/ac32d3c835dfc6ef557e4236ed56d8f82fe6c1bc/sabnzbd/newswrapper.py#L190-L191

Maybe a pointless micro-optimisation there to avoid a calculation with `if self.data_view.nbytes == self.data_position:`
Perhaps it should grow if its 'near' being full - i.e. buffer has 1 byte left?

---

I did just try a generated 3,840,000 bytes segment nzb without issue, may have to find a way to loop feeding it the NZB => delete output => repeat and see if I can trigger a crash.

---

Now that the data is a big bytes array have you considered finding the headers and start/end in python?
The C code for that is confusing, the GIL isn't dropped at that point anyway and python should be quick at string searches (also have rfind)

**Comment by Safihre** [comment]
Indeed I forgot I already increased it by 1MB 😅

> The C code for that is confusing, the GIL isn't dropped at that point anyway and python should be quick at string searches (also have rfind)

The code for the chunked approach is ugly, however, do you really find the code in `decode_buffer` confusing? It's pretty straightforward now we have just 1 buffer: https://github.com/sabnzbd/sabyenc/pull/79/files#diff-507abba6877e4f263d778a243063a187e86588da0259e065cbbd4b8158c02e24R613

**Comment by mnightingale** [comment]
I's certainly simpler than the lists, personally I'd probably have tried to split some of the parsing and repetition into inline functions just so its clearer what a line is doing.

**Comment by puzzledsab** [comment]
I did get a segfault with the newest sabyenc so I tried without SSL. That worked for a while and then I got this error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\git\sabnzbd\sabnzbd\decoder.py", line 157, in run
    decoded_data = decode_yenc(article, raw_data, raw_data_size)
  File "C:\git\sabnzbd\sabnzbd\decoder.py", line 251, in decode_yenc
    yenc_filename, crc_correct = sabyenc3.decode_buffer(data, raw_data_size)
ValueError: Invalid yEnc footer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\git\sabnzbd\sabnzbd\decoder.py", line 205, in run
    for line in b"".join(raw_data[:2]).split(b"\r\n"):
TypeError: sequence item 0: expected a bytes-like object, int found
```
Then it restarted by itself and crashed after a few minutes with no message. After I started it again (still without SSL) I got a segfault after only a couple of minutes.

**Comment by thezoggy** [comment]
@puzzledsab on windows just fyi there is pyenv-win // https://github.com/pyenv-win/pyenv-win
which makes it so much easier to test multiple python versions / switch between what you want to globally use

**Comment by mnightingale** [comment]
I got a C0000005 earlier, probably need the decoder suggested change.

I should really finish my fake nntp server and maybe test some malformed articles like missing footers.

**Comment by Safihre** [comment]
I'll close this now, lets open new issue if it continues on develop branch.
