### ISSUE TITLE
Watched folder polling CPU usage

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#2425]
I noticed a [reddit thread ](https://www.reddit.com/r/usenet/comments/10kddup/sabnzbd_much_slower_than_nzbget_on_my_setup_why/) earlier and a couple of people commented that the watched folder feature causes significant CPU usage even when it's not finding any changes.

By default SAB appears to poll the directory every 5 seconds, reading and comparing the directory tree.
I'm not familiar with the equivalent for all platforms but I have used inotify on linux in the past to monitor for changes without polling.

There does appear to be a Python package [watchdog](https://github.com/gorakhargosh/watchdog) which seems simple to setup, basically create a handler for FileSystemEventHandler events and start monitoring for "created" events.
It would probably also result in a simplification of a lot of the dirscanner logic.

Just wanted to raise awareness of the issue, I may take a look at it myself unless anyone else fancies investigating it.

**Comment by sanderjo** [comment]
I don't know about CPU usage by current polling, but watchdog is cool!

With the example program .... watching my home dir just works:

```
<ObservedWatch: path=., is_recursive=True>
2023-01-25 13:19:40 - Modified file: ./ddddd.txt
2023-01-25 13:19:40 - Modified directory: .
2023-01-25 13:19:40 - Modified file: ./.cache/tracker/meta.db-wal
2023-01-25 13:19:40 - Modified file: ./.cache/tracker/meta.db

2023-01-25 13:19:51 - Modified file: ./ddddd.txt
2023-01-25 13:19:51 - Modified directory: .
2023-01-25 13:19:51 - Modified file: ./.cache/tracker/meta.db-wal
2023-01-25 13:19:51 - Modified file: ./.local/share/tracker/data/tracker-store.journal
2023-01-25 13:19:51 - Modified file: ./.cache/tracker/meta.db

2023-01-25 13:19:55 - Created file: ./dddddaaaaaaaaaa.txt
2023-01-25 13:19:55 - Modified directory: .
2023-01-25 13:19:55 - Modified file: ./dddddaaaaaaaaaa.txt
2023-01-25 13:19:55 - Modified directory: .
2023-01-25 13:19:55 - Modified file: ./.cache/tracker/meta.db-wal
2023-01-25 13:19:55 - Modified file: ./.local/share/tracker/data/tracker-store.journal
2023-01-25 13:19:55 - Modified file: ./.cache/tracker/meta.db
2023-01-25 13:19:55 - Modified file: ./.cache/tracker/meta.db
2023-01-25 13:19:55 - Modified file: ./.cache/tracker/meta.db
2023-01-25 13:19:55 - Modified file: ./.cache/tracker/meta.db
```

**Comment by Safihre** [comment]
Looks cool. The current implementation is probably more than 10 years old, one of the first features of SABnzbd!
You want to implement it? 😎

**Comment by mnightingale** [comment]
There does appear to be some 13 year old code in there!

I'd expect the currently polling only really becomes a problem because it may wake up disks, or if it need to traverse a large directory tree - for instance if the user points it at their home directory or something, and any os.stat files to determine if they have changed.

I'm happy to take a look at putting something together with watchdog.

**Comment by mnightingale** [comment]
I've got the majority of it working, I think I understand the current behaviour so for instance apart from watching it also needs to read the directories whenever the main directory changes.

The biggest issue is there doesn't appear to be any tests for any of it 😭 so that's going to be the first step to protect against any regressions, going to need to figure out pyfakefs and mocking add_nzbfile.

**Comment by Safihre** [comment]
Some features that might not be clear right away, but are important:
Many users set the Watched Folder to their Downloads folder, so it can contain a lotttt of useless files we don't want.
When starting it compares to it's previous state so it will import NZB's that were created when SABnzbd was not running.
It has the mechanism to make sure we are not reading files that are still being written to.

**Comment by mnightingale** [comment]
😆 yes I noticed that behaviour as it went through my own Downloads folder trying to add all the .gz DB backups it could find.
As you say I'd expect that for users that are not automating or just don't leave SAB running watching their Downloads folder is quite common.

There is a note from watchdog that it's automatic choice of an observer won't work with a remote CIFS share, so if that functionality would be required I think we'd probably need an option somewhere to let the user continue using polling - watchdog has a PollingObserver.

Similarly if polling was no longer required the polling frequency setting could be removed.

Which approach do you think we need? on one hand I doubt many users watch a remote share but on the other it is functionality that would work with the current polling system.

---

I thought it was curious that SAB uses a lot of flat files for storage of state, it's not really an issue with watched_data since the ignored list is usually small - although it does have to keep those paths around in memory.
However for something like the queue, from a quick glance it appears to save every time an item is added/removed/changed, that must cause performance problems for some system when working with large queues?
Has their never been any desire to replace it with SQLite?

**Comment by mnightingale** [comment]
Just to check I understand your examples:
On the seedbox - SABnzbd sharing local directory /mnt/share via CIFS/SMB
The end user mounting the CIFS share from the seedbox to access the completed and watched directories.

I think this is a relatively common way someone may wish to utilise SAB with a seedbox and watchdog which is just providing a nicer API to inotify/fsevents/ReadDirectoryChangesW would pickup those local changes to the watched directory on the seedbox.

What the use of inotify or it's platform equivalent wouldn't work for is if the seedbox was mounting a remote directory for its watched folder, but that seems a pretty strange use case - I can't really think why someone would want it that way around, you'd need the seedbox and whatever is hosting the remote watched directory both online.

However it is what I think the rare case where polling would still be required.

I can't think of a reason why anyone would want to monitor a remote directory, so in my opinion I don't think it's worth adding a config option to allow polling.
I think it's more likely to confuse users who enable it when it is not needed, removing any of the benefits of an event based system, unless it was hidden away in the special switches - which I doubt @Safihre likes adding to.

---

I agree on the watched folder guard although I note the watching isn't recursive into directories so I'm not sure how much of an issue this is but it's probably out of scope of any changes to the actual dirscanner, with what ever managed the config being responsible for handling it if it doesn't already.

**Comment by thezoggy** [comment]
just to give a use case why the watch folder may be a remote mount.
you have sab on seedbox or remote place because they have faster connection. 

while maybe you send nzb's to it via app/api/etc, but at times you might get a nzb manually some how.
rather than having to login to the seedbox to add it, user setups sab's watch folder to be remote mount to their home machine (different os than seedbox). now, you just save the nzb locally to this folder.. and it shows up on the on seedbox sab's watched folder to process.

**Comment by Safihre** [comment]
We could add a special setting with the polling frequency, have it empty by default. If users fill a value, we use the polling?
We can add this information to the wiki.

**Comment by mnightingale** [comment]
Yeah I think that's what it would need:

**dirscan_dir: ""** - not watching or polling
**dirscan_dir: "some watched directory"** - filesystem events
**dirscan_dir: "some watched directory" and special value dirscan_speed > 0** - filesystem events and polling

Not sure if we'd want dirscan_speed to reset to "" or if it would just have a new id but not really important at this stage.

---

I started looking at how I might test dirscanner, initially I just want to test that .nzb files would be attempted to be added to the queue.

I didn't really want to test the implementation by calling things like `sabnzbd.dirscanner.DirScanner().scan()` directly because that probably won't exist once it uses events, so I though of just starting the thread and waiting to see if a mocked `add_nzbfile` is called.

It's not a great example and I just made it stop after scan is called once for but this is what I have so far: https://gist.github.com/mnightingale/85fa54062b3995ba0f8f4fc21d5b6371
It uses pytest-mock, a minor change to set_config to use functools.wraps so that fixtures are injected and I couldn't figure out how to use fixtures this way with a class to group tests.

I thought maybe something like adding a threading.event() flag that gets after every time `run` is called, so I can wait for it in the test, but that won't really help when its event based, so maybe just waiting until number of mocked calls == expected?

Can you think of a better approach?

I have in mind that eventually I'll want to be able to test adding multiple .nzb after the initial startup, so as far as I can see I'll need the thread running and want control over the result of `add_nzbfile` to test some of the other behaviours.

**Comment by thezoggy** [comment]
what if someone is downloading a large nzb (season pack or something..) so a tmp/partial file exists for some period of time until download completes.  will this wrongly think its time to process said partial file because new file event was triggered?

**Comment by mnightingale** [comment]
> what if someone is downloading a large nzb (season pack or something..) so a tmp/partial file exists for some period of time until download completes. will this wrongly think its time to process said partial file because new file event was triggered?

The current implementation handles this by waiting until the file attributes are stable for at least 1 second but only waits for up to 3 seconds.

I think an event system could do something like:

- on "created" event
- try checking if stable for 1 in 3 seconds
- add to queue, 
- if not stable or add_nzbfile < 0 then remember the path and try it again later within the thread.run method if the attributes change
  - there are few other states to handle such as permanent failures so ignore the path and persist it, cleanup of removed files.

If it makes the flow simpler the "created" event could just add the path to a list of suspected files, notify the run loop and handle stable attribute checking in one place - basically replacing the os.listdir calls with list of suspected files.

**Comment by puzzledsab** [comment]
I asked those reporting this in the thread about their system and got one reply so far:
Ubuntu 22.10, locally mounted zfs raidz1 with 4 spinning disks, OpenZFS v5, only one watched folder containing no other files.

In this case I assume it's slow because of the raid and that watchdog could help a lot.

**Comment by puzzledsab** [comment]
Another one:
unRAID 6.11.5, Docker (linuxserver), Local drive, Spinning disk (RAID, unknown number), xfs, No other files.

So also RAID and Docker.

**Comment by mnightingale** [comment]
I noticed are that it currently uses listdir instead of scandir, scandir won't have existed when it was written but would use less memory since it's an iterator, I'm not totally clear but the docs says helpers like `is_file` "doesn’t require a system call in most cases" - I'm not sure if that's just because its cached after the first call (so of no use to us) or if while walking the directory it is populated.

But the main thing is the polling approach calls os.listdir(), os.path.isdir() and os.stat() a lot, which depending on the filesystem and what metadata is cached my require hitting the disks.

There are little things like the ordering of checks `if os.path.isdir(path) or path in self.ignored or filename[0] == ".":` where just the order of checks means it always calls os.path.isdir even if it already knows its an ignored path.

For now I'm just trying to black box test it before I start making any changes, I'm fairly happy with the testing approach.
