### ISSUE TITLE
ValueError: Invalid yEnc footer not handled well

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#2427]
I mentioned this error in the segfault issue. I got it again now:
```
Traceback (most recent call last):
  File "sabnzbd\sabnzbd\decoder.py", line 158, in run
    decoded_data = decode_yenc(article, raw_data, raw_data_size)
  File "sabnzbd\sabnzbd\decoder.py", line 252, in decode_yenc
    yenc_filename, crc_correct = sabctools.yenc_decode(data)
ValueError: Invalid yEnc footer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sabnzbd\sabnzbd\decoder.py", line 206, in run
    for line in b"".join(raw_data[:2]).split(b"\r\n"):
`TypeError`: sequence item 0: expected a bytes-like object, int found
```
I fixed it locally by catching the `TypeError` but I think the yenc decoder should ideally decode what it can and return it with an empty `crc_correct`. The broken post had a proper start and seemed almost complete but did not have any part of the footer. It might be useful for par2 if it were decoded.

**Comment by Safihre** [comment]
Ah yes this should be handled better. When there's a footer error we can't decode anything, we need to know the end before we start decoding.

**Comment by puzzledsab** [comment]
Can't you just assume that if there is no footer then the last byte is the end? Possibly also skipping the last line in case it's broken at for instance \r\n=ye.

**Comment by Safihre** [comment]
@animetosho why exactly do we need to know the exact length before decoding?

**Comment by animetosho** [comment]
Most things in C will need to know where the stopping point is, so that it doesn't try to wander off into invalid memory.

If you're trying to process incomplete data, you could just use the last byte (or length) as the end point, as @puzzledsab suggests.
