### ISSUE TITLE
sabnzbd do not recognize {{password}} in filename

### ISSUE THREAD

**Issue by Flake16** [sabnzbd/sabnzbd#243]
Hey sabnzbd-team,

my sabnzbd instance (based on master branch from 2015-07-11) don't recognize {{password}}  or =password attachment in uploaded and read nzbs from the watch-folder.
After the upload, the whole {{password}}-part disappear and only the correct filename is set.
however =password is pasted into the file-name.
I think there is something broken with the regex.

cherrs

**Comment by shypike** [comment]
The "master" branch? Are you sure? We're working on "develop" now.

**Comment by Flake16** [comment]
You're  right, I assumed master was the default. My fault!

**Comment by shypike** [comment]
Recently the password recognition in the "develop" branch was indeed damaged.
Fixed now. Thanks for reporting.
