### ISSUE TITLE
Profiling with line_profiler

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#2430]
I wondered if anyone has managed to use https://github.com/pyutils/line_profiler with SAB?

The quick start instructions are:
- `pip install line_profiler`
- Decorate a function with `@profile` - don't import anything
- Run `kernprof -lv script_to_profile.py`

It should print the output and write it to a file, I tried it with a simple .py script, and it works.
However I can't seem to get it to work with SABnzbd, I've tried killing the process, a graceful shutdown and neither output anything.

**Comment by puzzledsab** [comment]
It created a file when I ran it for a while with `kernprof -l -o profile.prof -i 5 SABnzbd.py` but it wasn't readable.
```
$ python -m pstats profile.prof
ValueError: bad marshal data (unknown type code)
Welcome to the profile statistics browser.
```

**Comment by mnightingale** [comment]
😄 I got it to work

Windows/Mac combined changes:

```diff
diff --git a/SABnzbd.py b/SABnzbd.py
index a5e71ec1f..bd2b467a4 100755
--- a/SABnzbd.py
+++ b/SABnzbd.py
@@ -1630,12 +1630,10 @@ def main():
             AppHelper.stopEventLoop()
         except:
             # Failing AppHelper library!
-            os._exit(0)
+            pass
     elif sabnzbd.WIN_SERVICE:
         # Do nothing, let service handle it
         pass
-    else:
-        os._exit(0)
 
 
 ##############################################################################

```

- Decorate a function with `@profile`
- `kernprof -lv SABnzbd.py`

For Mac it doesn't work with the extra thread for the tray icon, presumably similar issue with the way it is shutdown so I just made a simple bootstrap script:

```py
import multiprocessing
import signal

import sabnzbd
from SABnzbd import main

if __name__ == "__main__":
    # Require for freezing
    multiprocessing.freeze_support()

    # We can only register these in the main thread
    signal.signal(signal.SIGINT, sabnzbd.sig_handler)
    signal.signal(signal.SIGTERM, sabnzbd.sig_handler)

    main()

```

- `kernprof -lv LineProfiler.py`

Should be useful for profiling specific functions.

@Safihre any idea why it's os._exit(0) calls? it works with pass which should fallthrough to an exit(0) or using sys.exit(0).
os._exit(0) seems an abrupt way of exiting without performing additional cleanup which I presume is what line_profiler was is hooking into.

**Comment by Safihre** [comment]
I don't know! I think it's also some 13+ years old code that I never dared to change 🤣

**Comment by mnightingale** [comment]
If I had to guess it looks like it wants to make really sure the process gets ended, seems like the equivalent of a `kill -9`.

I've leave it alone, just glad I managed to get the line profiler to work.

**Comment by Safihre** [comment]
@mnightingale Many months later this turned out to be very helpful, thanks!
I am using https://plugins.jetbrains.com/plugin/16536-line-profiler and it's working great after applying the changes!
