### ISSUE TITLE
sabnzbd Unauthorized Access

### ISSUE THREAD

**Issue by Enoki-web** [sabnzbd/sabnzbd#2442]
https://fofa.info/result?qbase64=U0FCbnpiZCBJbnN0ZWxsaW5nZW4%3D

Unauthorized Access Vulnerability exp:

http://your target/config/server/

http://your target/config/folders/

....more

**Comment by Enoki-web** [comment]
![image](https://user-images.githubusercontent.com/45222311/216306074-3482c505-c822-41e7-9c1d-0622b0a3bdc1.png)

**Comment by Safihre** [comment]
What exactly are you reporting? You found an exposed SABnzbd instance?
If they don't setup any of the security settings, then indeed it's exposed. Doesn't seem like a bug?

**Comment by Enoki-web** [comment]
Inadvertently saw unauthorized access to a large number of sites. Since the user has not configured security, the attacker can obtain the user's information. Hope that user authentication can be enforced

**Comment by Enoki-web** [comment]
> 你到底在报告什么？你找到了一个暴露的 SABnzbd 实例？ 如果他们不设置任何安全设置，那么它确实暴露了。好像不是bug？

Inadvertently saw unauthorized access to a large number of sites. Since the user has not configured security, the attacker can obtain the user's information. Hope that user authentication can be enforced

**Comment by Safihre** [comment]
We warn the users at a number of spots that they are exposing , however, we cannot enforce it..
