### ISSUE TITLE
sabnzbd SSRF vulnerability

### ISSUE THREAD

**Issue by Enoki-web** [sabnzbd/sabnzbd#2446]
step 1: Voeg server toe
![image](https://user-images.githubusercontent.com/45222311/216305439-2a28c18e-0321-4dfa-b4b0-0fbb0ae341ea.png)

step 2: add dnslog
![image](https://user-images.githubusercontent.com/45222311/216305125-1aeca803-77b9-4d5d-9205-996d0a4448f5.png)

step 3: dnslog response
![image](https://user-images.githubusercontent.com/45222311/216305247-4d8f95f8-eac9-44d1-98b9-757007ecd982.png)

**Comment by Safihre** [comment]
Are you a SABnzbd user? Of course it will do this.. It's intended behavior.

**Comment by Enoki-web** [comment]
> 您是 SABnzbd 用户吗？当然它会这样做......这是预期的行为。

I am a security researcher, and these seemingly normal behaviors often leave security risks for users. Convenient things are also convenient for attackers

**Comment by Safihre** [comment]
This is the same underlying issue as #2442, if the SABnzbd instance is exposed then there's nothing we can do. 
This is exactly what the application should do: it connects to servers that you tell it to connect to.

**Comment by Enoki-web** [comment]
![image](https://user-images.githubusercontent.com/45222311/216505898-bfb87190-e563-479c-be6d-de08d8fceab4.png)
![image](https://user-images.githubusercontent.com/45222311/216505966-74395d98-d279-4e01-8447-5dd37b7df428.png)
![image](https://user-images.githubusercontent.com/45222311/216506011-a0c8cc5f-57d6-4070-9f47-2852fb8163b0.png)

**Comment by jeffgeorge** [comment]
This is equivalent to complaining that if you instruct cURL to connect to a malicious server it will connect to a malicious server.

**Comment by JackDandy** [comment]
I understand both sides of this thread and I think offering an idea is perhaps what the OP missed.  For example, no matter how pw access is set up normally, a solution _could_ specifically protect URL configuration fields behind a pw, (or even require a pw to **_save_** settings - more annoying UX this one though). Much like how services like gmail/ghub require pw to access entire, or critical parts of user account settings, even when already logged in.
