### ISSUE TITLE
Support for tavern >= 2.0

### ISSUE THREAD

**Issue by mgorny** [sabnzbd/sabnzbd#2467]
Please update the package to support the current version of tavern. Dependency on tavern-1 prevents Gentoo users from upgrading to 2.0.0 and newer versions.

**Comment by Safihre** [comment]
Why? It's only a test dependency, not a program dependency.

**Comment by mgorny** [comment]
> Why? It's only a test dependency, not a program dependency.

Gentoo is a source distribution which means that the majority of our users build everything from source. Building Python packages from source also (optionally) involves running their test phase — given pretty much no static API compatibility checking in Python, this is pretty much a necessity if you don't want things being suddenly broken in production.

> No issues with tavalidate either, despite the comment in t/req.txt suggesting otherwise.

Oh, that's reassuring. I was quite concerned about that comment, especially that I couldn't find any bug report for tavalidate and the package looked untouched for 3 years.
