### ISSUE TITLE
Add Flathub package

### ISSUE THREAD

**Issue by francoism90** [sabnzbd/sabnzbd#2469]
I have created a forked Flathub package for SABnzbd, including instructions how to build: https://github.com/francoism90/flatpak-org.sabnzbd.SABnzbd

It's pretty easy if you know how it works. :)

Things not working (yet):
- dbus support
- Tray-icon
- ujson==5.7.0, using the inbuilt Python one

If you have any questions and/or suggestions, please let me know.

So far it seems stable.

**Comment by thezoggy** [comment]
is this a follow up of https://github.com/sabnzbd/sabnzbd/issues/1471 ?

**Comment by francoism90** [comment]
@thezoggy A yes, sorry about opening another issue, forgot about that one.

Yeah, I've clean-up the yaml file, bumped the deps, added p7zip and added instructions how to build the Flatpak.

It's pretty easy, thanks to the help of other existing packages and howto's.
It would be great if you could support this, I don't use snap and the Docker image isn't that friendly in my opinion.

Things I want to take a look at:
- dbus support (if useful)
- tray icon (if possible, as it doesn't seem to be when using Wayland?)
- `--filesystem=host`, maybe it's possible to give a more srict permission?

**Comment by thezoggy** [comment]
Saw this today:
https://www.phoronix.com/news/Ubuntu-No-Flatpak-By-Default

**Comment by francoism90** [comment]
@thezoggy Let's not forget about other distro's: Linux Mint, Fedora, elementaryOS, Pop! OS.. al have flatpak.

Ubuntu is the only one not using Flatpak by default.

**Comment by francoism90** [comment]
@jcfp Could you give more details about the dbus module?

It seems to work perfectly fine without, and it seems not recommended by the author itself?
See doc: https://dbus.freedesktop.org/doc/dbus-python/

**Comment by francoism90** [comment]
https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access

Hmm, I don't know if this is full dbus access:

> Limited access to the session D-Bus instance - an app can only own its own name on the bus

I don't fully understand if this works without explicit setting `dbus` access, and it just needs the package to be installed?

**Comment by francoism90** [comment]
https://github.com/flathub/org.qbittorrent.qBittorrent/blob/a03a5c07b76aeb637f51e002abf6c14af3f339d9/org.qbittorrent.qBittorrent.yaml#L2

I'm thinking of adding PowerManagement permissions, don't know if Login manager is also needed.

Is there any way to debug power management from SABnzbd it self? Or get some logging?

**Comment by Safihre** [comment]
The functions and their logging are here: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L1280

**Comment by francoism90** [comment]
Success! I enabled log debugging and `Standby PC` when queue finished, and the system did suspend successfully:
```
2023-02-26 21:25:44,703::DEBUG::[filesystem:1176] [sabnzbd.nzbqueue.save] Saving data for queue10.sab
2023-02-26 21:25:44,703::DEBUG::[filesystem:1108] [sabnzbd.filesystem.save_admin] Saving data for queue10.sab in /var/home/user/.sabnzbd/admin
2023-02-26 21:25:44,704::DEBUG::[filesystem:1176] [sabnzbd.bpsmeter.save] Saving data for totals10.sab
2023-02-26 21:25:44,704::DEBUG::[filesystem:1108] [sabnzbd.filesystem.save_admin] Saving data for totals10.sab in /var/home/user/.sabnzbd/admin
2023-02-26 21:25:44,704::DEBUG::[filesystem:1176] [sabnzbd.dirscanner.save] Saving data for watched_data2.sab
2023-02-26 21:25:44,704::DEBUG::[filesystem:1108] [sabnzbd.filesystem.save_admin] Saving data for watched_data2.sab in /var/home/user/.sabnzbd/admin
2023-02-26 21:25:44,704::INFO::[postproc:129] Saving postproc queue
2023-02-26 21:25:44,704::DEBUG::[filesystem:1176] [sabnzbd.postproc.save] Saving data for postproc2.sab
2023-02-26 21:25:44,704::DEBUG::[filesystem:1108] [sabnzbd.filesystem.save_admin] Saving data for postproc2.sab in /var/home/user/.sabnzbd/admin
2023-02-26 21:25:44,705::DEBUG::[filesystem:1176] [sabnzbd.rss.save] Saving data for rss_data.sab
2023-02-26 21:25:44,705::DEBUG::[filesystem:1108] [sabnzbd.filesystem.save_admin] Saving data for rss_data.sab in /var/home/user/.sabnzbd/admin
2023-02-26 21:25:44,705::INFO::[notifier:123] Sending notification: SABnzbd - Queue finished (type=queue_done, job_cat=None)
2023-02-26 21:25:44,705::INFO::[postproc:1047] Queue has finished, launching: <function system_standby at 0x7fbb1c4b5750> (None)
2023-02-26 21:25:44,705::INFO::[misc:1324] Performing system standby
2023-02-26 21:25:44,705::DEBUG::[postproc:1057] Triggering garbage collection and release of memory
```
You can checkout the change here: https://github.com/francoism90/flatpak-org.sabnzbd.SABnzbd/commit/6d11e6e36aaea95f5690ea591112f2bca7194012

I don't know if the login stuff is required, but I think it's need to be for suspend/power-management to work.

Maybe we should sent it to Flathub for review? :)

**Comment by Safihre** [comment]
But who will maintain this?
The Python depencies can be automated using Github Actions. But I'm quite turned off that all the versions and urls are hardcoded for things like unrar and cryptography, this would place the responsibility on us to keep fixing them if they break and updating them if new versions are released..

**Comment by francoism90** [comment]
@Safihre I would be happy to stand in, as I do want to maintain some Flatpak's myself. :)

It's pretty easy, it turns out one can add `x-checker-data`, to check for latest versions. From what I do understand, Flatpak is also able to scan the deps on Flathub:
https://release-monitoring.org/project/13306/
https://release-monitoring.org/project/2583/
https://release-monitoring.org/project/12843/

It seems even you guys are listed: https://release-monitoring.org/project/44529/

Information: https://github.com/flathub/flatpak-external-data-checker

I don't think you can check the Python deps, as they depend on the project. So sometimes I don't think you want to bump.

**Comment by francoism90** [comment]
I've sent SABnzbd as Flatpak for review: https://github.com/flathub/flathub/pull/4092

It would be really cool if you guys could still consider helping me out: https://github.com/flathub/flathub/pull/4092#discussion_r1174457239

If this can be adopted upstream, it allows the community (and you as developer) to maintain and push updates. :)

**Comment by thezoggy** [comment]
you can prob just refer to the snap version and make minor changes to make it do what you want

**Comment by francoism90** [comment]
@jcfp I think it expects the release format to be in XML not JSON. Not sure if the GitHub API has XML support?
I've asked upstream, and will take a look at other flathub's.

Almost ready! Hope this is the last thing we need to fix, so it can be submitted. :)

**Comment by francoism90** [comment]
https://github.com/flathub/org.sabnzbd.sabnzbd

@jcfp @Safihre It has been merged into Flathub! I don't see it in the Flathub store yet, but I think we need to give it a little bit more time. :)

If you want, I could add you guys as developers. I'm still new, but it should be possible.

Thanks for your work and efforts to get this on Flathub.

**Comment by Safihre** [comment]
Great! 
I actually split up the release process code so we now technically could modify the file to add a new version after every release. 
Or you could manually do it after each releaser.

**Comment by Safihre** [comment]
@francoism90 just to confirm:
When I release a new version, the `appdata.xml` file needs to have the release that I am currently releasing?
It does not need to be N+1?

Only problem with that is that our release is based on git-tags. So either the tag needs to be moved after adding the new release to the `appdata.xml` or we need to somehow automatically patch the `releases`-tag _before_ we tag for the release.
Hmmm, not convenient.

**Comment by francoism90** [comment]
@Safihre Correct, you have to update `appdata.xml` **before** creating a Git-commit tag. The same you did last time. :)
