### ISSUE TITLE
Feature request: Build system for Python

### ISSUE THREAD

**Issue by fabricionaweb** [sabnzbd/sabnzbd#2483]
Im not python expert and I might say something wrong, apologies in advance. 

Is there any plan to add support to something like the setuptools? https://setuptools.pypa.io/en/latest/userguide/index.html

The idea is to support a build-system and wheel installer, so the person can install it to the site-packages.

**Comment by Safihre** [comment]
SABnzbd is an application and not a package, as such we don't distribute it as a wheel.
Whay benefit would it bring to package it like that?

**Comment by fabricionaweb** [comment]
> SABnzbd is an application and not a package, as such we don't distribute it as a wheel.
Ah ok, I have not think like that. Thanks

> Whay benefit would it bring to package it like that?
You know this more than me, I wouldnt have much to say about benefits. I thought having a build-system was a good or a common practice - even for apps. 

Having a build-system would help in the way of distribution the package more standard (and reliable) across any system that just runs Python. It would help to maintain the package.

I mean, you dont need to provide the wheel itself but just provide the build instructions to generate a valid one (like setup.py or pyproject.toml).

**Comment by thezoggy** [comment]
we have a build system, we build binaries (just look at github actions /  our .builder). i think what your curdely trying to get towards is just a simplier install, which you would use a ppa for that. which exists. but theres no plans or does it make sense to offer up sab (which uses several packages) to make one giant python wheel to install. besides the fact we use more than python code.
