### ISSUE TITLE
Proposal: "Deobfuscate final filenames" on by default

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2484]
How about setting "Deobfuscate final filenames" on by default? For example in SAB 4.0.0

There was one reason to not turn it on yet, but I can't remember it, so I'm not sure if it is still a valid blocker.

@Safihre do you know it?

**Comment by Safihre** [comment]
Seems like a valid option.
You can submit a PR to enable it by default.
