### ISSUE TITLE
Not an issue, just a quick typo to fix in the new sorter UI

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2488]
Not an issue, just a quick typo to fix in the new sorter UI:

"provided at least one file meets the minumum filesize requirement."

 "minumum filesize" should be "minimum file size"

https://github.com/sabnzbd/sabnzbd/blob/32515172d3c35f68ba6f0abc43e5734b2be409bb/sabnzbd/skintext.py#L762

**Comment by Safihre** [comment]
Feel free to submit a PR! You can even do it online through the Edit button in GitHub.
Or if you feel the wording should be different in general, let us also know.

**Comment by Cpuroast** [comment]
nothing to do with wording, just errors

"minumum" is not a word and neither is "filesize"
