### ISSUE TITLE
sab 4.x - old sorting

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2489]
the old sorting stuff is still shown on the api when pulling from get_config

`/api?mode=get_config&apikey=(removed)&output=json`
```
         "enable_tv_sorting":0,
         "tv_sort_string":"%sn/Season %s/%sn - S%0sE%0e - %en.%ext",
         "tv_categories":[
            "sonarr"
         ],
         "enable_movie_sorting":0,
         "movie_sort_string":"%title (%y)/%title (%y).%ext",
         "movie_sort_extra":" CD%1",
         "movie_categories":[
            "movies"
         ],
         "enable_date_sorting":0,
         "date_sort_string":"%t/%t - %y-%0m-%0d - %desc.%ext",
         "date_categories":[
            "*"
         ],
```

which *arr apps would be looking at to know if sorting is enabled/warn to disable. i've let them know that for sab 4.x to not look at those values / look at `sorters_converted` being 1 

_Originally posted by @thezoggy in https://github.com/sabnzbd/sabnzbd/issues/2461#issuecomment-1458603890_

so if user had sab set to do sorting for sonarr/radarr/whatever cat. (which *arr would yell about, since its not supported).
then user upgraded to sab 4.x and fixed the sorting to not sort anymore.. then sonarr would wrongly be yelling about the old values which the user cant really correct (unless they go modify ini).

while i understand we might want the old values for right now to allow upgrade/downgrades.. perhaps we should just disable the old sorting during the migration so if apps poll for those they at least dont get triggered by it. or just drop them from being stored in the config and users just will have to redo sorting if downgrading.  

also do we want to update our config version since sab 4.x would easily qualify as major change.

**Comment by puzzledsab** [comment]
I think this should be fixed before the final release so that Sonarr doesn't complain, preferably by someone more familiar with the sort code than me. Ideally the config should be kept for a while in case the user wants to downgrade.

**Comment by Safihre** [comment]
Agreed.
@thezoggy but will Sonarr not trip if the values are not present in the API anymore?

**Comment by thezoggy** [comment]
> Agreed. @thezoggy but will Sonarr not trip if the values are not present in the API anymore?

sonarr is getting the config (get_config) and looking at stuff there. 

to do things properly, imho we should have increase version of our config for 4.x. 
which then we make backup of previous config before we convert. that way users can revert to that config if needed.
with the new config not having the old vlaues anymore, and then also dont need a variable to know if the old values have been converted.

in sickbeard days we used a lot of sab's code for config.. but we actually included newer code for doing backups+migrations (and newer sickbeard forks even have more stuff/python3 code). so shouldn't be too hard to leverage some of that code back in to improve sab's config stuff. some examples:
https://github.com/SickChill/sickchill/blob/master/sickchill/oldbeard/config.py#L897
https://github.com/pymedusa/Medusa/blob/master/medusa/config.py#L823



now, we have a bad history of not increasing our version numbers for config or doing backups..  which is why i still have many things in my sab config from 10 years ago that havent been used. so many things sit stale because we stopped being explicit about what we load/save...

now *arr needs to update their code to figure out if sorting is disabled in the new method.
but right now in 4.x there can be the old pre 4.x + 4.x variables so they have to jump through some hoops to figure out which one matters. crudely i suggested we could just set the old enable_xxx_sorting to 0 so the old values are disabled and sonarr wouldnt choke on that. which should be the same as if the values arent there, assumed its not set. then they can just add logic to check for new value, and assume if not there its not set. so they cover 4.x and pre 4.x.

**Comment by Safihre** [comment]
I am leaning towards agreeing that these vars should not be public anymore.

**Comment by Safihre** [comment]
Added option to hide settings for the API. 
Tested with Sonarr and it did not seem to care that the old Sorting values weren't there anymore.
