### ISSUE TITLE
queue repair - delete all orphan'd jobs

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#249]
is there an easy way via the gui to nuke all orphan'ed jobs? as clicking on 'X' and waiting for it to refesh is a bit painful when you have a thousand items.. also is there a way to nuke the duplicate nzb cache and/or only apply that to a specific category.. things to ponder for 0.8.x.

![Sab queue](http://i.imgur.com/e3gPl4j.png?1)

**Comment by Safihre** [comment]
It was on my to-do-list for Glitter, might as well just add it now

**Comment by Safihre** [comment]
Delete-all was actually pretty simple, added it now. Will send it with some next commit.
Per Category seems maybe a little too much, that seems out of the scope of what the function is meant for.

**Comment by thezoggy** [comment]
i guess people may want an add all too..  could just make the list have a check box in front, and then a toggle all checkbox up top.. do ctrl+select for multi/range.. then at bottom offer bulk action (delete/add/remove)

**Comment by thezoggy** [comment]
rather than sending 1000 delete requests.. should just add a 'purge' which then internally it just removes them all.
https://github.com/sabnzbd/sabnzbd/blob/0.7.x/sabnzbd/interface.py#L2477

**Comment by Safihre** [comment]
True, but I made it this way with check boxes in mind that can be added later.

**Comment by thezoggy** [comment]
makes sense

**Comment by mariothiel** [comment]
what happened to this?

**Comment by shypike** [comment]
Fixed in Beta2

**Comment by Safihre** [comment]
What will be fixed in Beta 2? The delete all was already in Beta 1 for Glitter..
Was not planning to make those checkboxes..

**Comment by shypike** [comment]
Forget my remark. I thought it was about the bug that also erased the running post-processing job.
