### ISSUE TITLE
Regression in Sabnzbd 4.0.0 Alpha 3 ignores job folder creation prevention

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2490]
Sabnzbd 4.0.0 Alpha 3 ignores job folder creation prevention.

As in "Ending the path with an asterisk * will prevent creation of job folders."

**Comment by Cpuroast** [comment]
Tested with 4.0.0 Alpha 2 and 3.7.2 they both honor a * at the end of the path in categories and avoid creating a job folder

**Comment by Safihre** [comment]
@jcfp :)
