### ISSUE TITLE
0.8.x - add category scope to history

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#250]
in sonarr, it queries sab for the history to check in on items... it'd be nice if it could be more efficient and only get back results for a specific category (or categories?). if requested cat doesnt exist, fall back to no cat results.

should be a pretty easy change.. just putting this reminder here in case someone gets to it before i do

**Comment by shypike** [comment]
See: e331a57303574a15ae4c23d2779b8190c514e275
api?mode=history&category=ONE&category=TWO
Will filter for ONE or TWO

**Comment by thezoggy** [comment]
tested, so far so good.. need to test to see what happens if user's category contains characters that should be urlencoded...
