### ISSUE TITLE
deobfuscate dependency? BSD

### ISSUE THREAD

**Issue by natetheskate** [sabnzbd/sabnzbd#2512]
Hi, Running 3.7.2 in a iocage jail (BSD) which is working great. Recently I've had a lot of obfuscated files so I enabled the check box to leverage deobfuscate however I'm getting an error message: "rarset 2 is missing completely, so I can't deobfuscate." Seems simple enough, install "rarset 2" only I can't find a package anywhere named rarset or rareset 2. Can someone please point me in the right direction for whatever the dependency is and where to find it? Even if I need to compile it myself.

**Comment by thezoggy** [comment]
its not a dependency that you install, its just saying its a file missing from the post. you need to talk to the person posting/place you got the nzb. 

Please use one of the support channels: [forums](forums.sabnzbd.org/), [subreddit](https://www.reddit.com/r/sabnzbd/), [discord ](https://discord.gg/KQzDe7fvNU), or [IRC](https://sabnzbd.org/live-chat.html) for support/questions.

**Comment by natetheskate** [comment]
Thank you for the clarification.
