### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not bool

### ISSUE THREAD

**Issue by uhthomas** [sabnzbd/sabnzbd#2515]
```
ERROR a few seconds ago Error while adding <redacted> removing
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/nzbparser.py", line 319, in process_single_nzb
    nzo = nzbstuff.NzbObject(
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 744, in __init__
    admin_dir = os.path.join(self.download_path, JOB_ADMIN)
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool
```

Seems like a permission error, but thought I'd open this issue anyway as it is probably a good idea to not panic.

```
ERROR a minute ago Failed making (/media/downloads/incomplete/<redacted>)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 717, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/media/downloads/incomplete/<redacted>'
```

**Comment by uhthomas** [comment]
Whilst Googling, I found https://forums.sabnzbd.org/viewtopic.php?t=26097. The comments suggest that `JOB_ADMIN` is the problem here?

May be unrelated, but I did change the paths in the config UI from the default to something else. Maybe a culmination of permissions and this is enough to get SABnzbd into this state?

**Comment by Safihre** [comment]
The problem is that when there's something wrong with creating the temporary directly, this function returns False:
https://github.com/sabnzbd/sabnzbd/blob/d22f2296c24ea2c705ad5109a9e53214bdb32068/sabnzbd/nzbstuff.py#L746

We just don't check the result of that. We could do that, but it would still result in some form of exception. However, we would be able to display a nicer error.

**Comment by uhthomas** [comment]
Yeah, I see it now.

https://github.com/sabnzbd/sabnzbd/blob/d22f2296c24ea2c705ad5109a9e53214bdb32068/sabnzbd/filesystem.py#L733
