### ISSUE TITLE
[Feature Request] Schedule - Change Server Priority

### ISSUE THREAD

**Issue by RandomLegend** [sabnzbd/sabnzbd#2520]
Hello,

i'd love to have a scheduler to change a servers priority. I have two usenet providers and one of them gives me much more speed at nighttime.

However i experienced issues when i have a download queue open at the time i want to switch servers.
I tried it with enable / disable servers at specific times to disable the regular server and enable the nighttime server. But with an open download queue i often got issues.

So i'd love to have the option to simply change priorities instead of enabling and disabling. That way i could simply increase the prio of the nighttime provider so the next item in the queue will be loaded from that server. No need to enable / disable anything.

That would be awesome!

Thanks for your time and that wonderful project!

**Comment by Safihre** [comment]
It seems what we need to fix is not adding another Scheduler option, but fix the problem with enabling/disabling.
What kind of problems were you experiencing?
Can you reproduce them?

**Comment by RandomLegend** [comment]
The issues were that downloads would take very long to resume if the enable / disable process would happen while something was downloading.

And then there was a 50/50 chance that the download could not be verified after finishing and could not be repaired.

**Comment by Safihre** [comment]
Oke let's try to fix that.
Can you download 4.0.0Beta1, enable Debug logging in the Status window and then after it happens again click Show Logging in the same window. Send the logging to safihre@sabnzbd.org 

Your feature request is a bit too exotic to add, so I want to help fix the underlying issue.

**Comment by RandomLegend** [comment]
i am using docker to run sabnzbd.

I assume that new version is not available as docker?

**Comment by thezoggy** [comment]
> i am using docker to run sabnzbd.
> 
> I assume that new version is not available as docker?

Depends on the docker maintainer, if your using lsio they have a nightly tag which builds off latest develop branch for each commit.

**Comment by RandomLegend** [comment]
I am using binhex maintained dockers

Tbh i currently don't have the time to troubleshoot. I am sorry i'd love to help but time is sparse right now.
It's possible that the error i had was my own fault and has nothing to do with sabnzbd anyways.

**Comment by thezoggy** [comment]
For binhex, you are stuck on "stable" releases. So 3.7.2 is latest until we push out final 4.0.0 build.

**Comment by RandomLegend** [comment]
Got it,

thanks anyways! The issue i got here is 1) as i said possibly on my own fault anyways and 2) not really that big.

The speed difference in the two providers is not that big at night and i can live with manually switching it before starting a big queue when i know i want it to be done overnight. So no big deal.

I just thought that being able to change priorities would be a minor thing to add and would greatly benefit the usecase i explained here. I know that us people who have two different providers based on time are not that many but the way of enabling and disabling the servers is not ideal even if it doesn't cause any issues on sabnzbd.

When i completely disable the "daytime" provider and only use the nighttime one...if the nighttime provider has issues on their side i don't have any working provider enabled. So the approach with priorities would be much more stable and convenient.

**Comment by thezoggy** [comment]
Shuffling server priority while simple can be a bit disruptive if there is active jobs. 

Having sever priority at your disposal to mange which server gets used rather than just the existing enable x, disable y. 
Would handle the scenario when server x is down/missing articles and server y could be used.

But one would just argue to not disable servers and just set the one you want to use first, or if both can be used just set them to the same priority.
