### ISSUE TITLE
Long title names causing issues

### ISSUE THREAD

**Issue by hulleyrob** [sabnzbd/sabnzbd#2529]
I have max folder length name set to 226 which I thought would be low enough for any BTRFS limitations.

However when a long title name is added to the list I always get a warning with the below.

Any ideas if/how I can resolve/fix this?

```Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/nzbparser.py", line 319, in process_single_nzb
    nzo = nzbstuff.NzbObject(
  File "/app/sabnzbd/sabnzbd/nzbstuff.py", line 744, in __init__
    admin_dir = os.path.join(self.download_path, JOB_ADMIN)
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool```

**Comment by Safihre** [comment]
Do you not see another traceback before that? Saying `Failed making X`.
This one should tell you what is actually the problem reported by the OS.

**Comment by hulleyrob** [comment]
I see two errors I just gave the last one the previous one was:

`Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 717, in create_all_dirs
    os.mkdir(path_part_combined)
OSError: [Errno 36] Filename too long:`

Which was why I was saying that I have reduced the max folder length setting to try and avoid this but I do see this error a lot with NZBs with long filenames. Im not really sure what else I need to change to stop this?

**Comment by Safihre** [comment]
Good. Maybe it's unicode characters that take of up more space per char?
Closing this as it's not something we can improve and we provide the settings to make sure things keep working.

**Comment by sanderjo** [comment]
> Maybe it's unicode characters that take of up more space per char?

Seems so:

```
sander@haring1:~$ touch `python -c "print(100 * '界')"`
touch: cannot touch '界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界界': File name too long
```

`sander@haring1:~$ touch `python -c "print(70 * '界')"` # no error, so good`

```
sander@haring1:~$ python -c "print(len('界'))"
3
```
