### ISSUE TITLE
0.8.x - smpl white - 'Retry all |'

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#253]
![smpl white](http://zoggy.net/sabnzbd2.png)

**A** should be capitalized to match the other options. Trailing `|` should not be included.

**Comment by thezoggy** [comment]
smpl-retryAllJobs - is the template string that needs to be fixed
```
#: sabnzbd/skintext.py:971 [Link in SMPL for "Retry all failed jobs"]
msgid "Retry all"
msgstr ""
```

**Comment by thezoggy** [comment]
note also in plush the dropdown 'retry all failed' is no only hard to get to (sort takes over and blocks it) but also suffers from the same case indifference

![plush](http://zoggy.net/sabnzbd3.png)
```
#: sabnzbd/skintext.py:970
msgid "Retry all failed jobs?"
msgstr ""
```

**Comment by thezoggy** [comment]
misspelling in multiple skintext, should be `priority` not `prioirty`:
```
    'sch-pause_all_low'  : TT('Pause low prioirty jobs'), #: Config->Scheduler
    'sch-pause_all_normal':TT('Pause normal prioirty jobs'), #: Config->Scheduler
    'sch-pause_all_high' : TT('Pause high prioirty jobs'), #: Config->Scheduler
    'sch-resume_all_low' : TT('Resume low prioirty jobs'), #: Config->Scheduler
    'sch-resume_all_normal':TT('Resume normal prioirty jobs'), #: Config->Scheduler
    'sch-resume_all_high': TT('Resume high prioirty jobs'), #: Config->Scheduler
```

**Comment by shypike** [comment]
Misspellings are a problem, correcting them means that all translations of that text become invalid.
I have thought about adding an "English" translation for the sole purpose of correcting English texts without having the translations thrown out.
It does mean that you are stuck with misspellings "forever" in the source text.

**Comment by shypike** [comment]
OK, it is possible to use an "en" translation file, which will only contain the texts that need correction.
We can maintain this file outside of Launchpad in the repo.
Periodically the texts should be corrected in the source and the PO files, which can be re-uploaded to Launchpad. That should be scriptable.

**Comment by shypike** [comment]
>>note also in plush the dropdown 'retry all failed' is not only hard to get to (sort takes over and blocks it)
Is the solution to move Sort to the bottom?

**Comment by thezoggy** [comment]
thats probably an the easier quick fix for the sort hover

**Comment by shypike** [comment]
Done.
