### ISSUE TITLE
[4.0.0b2] indefinite job stall with 'Resetting bad trylist' and zombie DirectUnpacker

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2533]
I've seen this happen multiple times with various 4.x pre-releases, but only now caught one with debug logging enabled. The trigger seems to have been a server closing all connections at one point during download, even though the affected connections could immediately be re-established:
```
2023-04-17 09:07:59,075::DEBUG::[downloader:983] Thread 7@test.xsnews.com: server closed connection
2023-04-17 09:07:59,075::DEBUG::[downloader:1006] Re-adding article _ID_ from _HEX_.part38.rar to server <Server: test.xsnews.com:563>
[similar msgs for the other threads to the same server stripped for clarity...]
2023-04-17 09:08:00,990::INFO::[downloader:665] 7@test.xsnews.com: Initiating connection
2023-04-17 09:08:00,991::DEBUG::[downloader:182] test.xsnews.com: Re-using address 91.223.220.236
2023-04-17 09:08:01,029::INFO::[newswrapper:348] 7@test.xsnews.com: Connected using TLSv1.3 (TLS_AES_256_GCM_SHA384)
```
The above affected all configured connections to a single server, all at the same time. Connections to other servers at the same priority level remained active, and no general dns or network failure happened at any time during the download.

After this hickup the download continues at full speed, but the direct unpacker never moves beyond part37 and at the end of the download, the web interface indicates there's 15.5 MB of data (13 articles?) left. All enabled servers test OK on the server config page, yet the job then hangs indefinitely with the following message logged ad nauseam every 30 seconds (also my timeout setting for all configured servers):
```
2023-04-17 10:04:20,502::INFO::[nzbqueue:922] Resetting bad trylist for job _JOB_
2023-04-17 10:04:50,503::INFO::[nzbqueue:918] Resetting bad trylist for file _HEX_.part38.rar in job _JOB_
```

Changing the job priority to Force has no effect, setting it to Stop causes the job to proceed to postprocessing immediately, go through par2 verification, then back into the queue to successfully download a bunch of par2 files only to go back to the same old 'Resetting bad trylist' logging (about part38, same as before).

Setting priority to Stop a second time makes the job go through par2 verification again, get repaired using the par2 blocks downloaded as part of the previous post-processing attempt and moved to the history, but then gets stuck there apparently thinking the directunpacker is still active even though it already knows it's completed:
```
2023-04-17 11:06:01,976::INFO::[directunpacker:315] DirectUnpacked volume 51 for _HEX_
2023-04-17 11:06:01,982::INFO::[directunpacker:239] DirectUnpack completed for _HEX_
2023-04-17 11:06:01,982::DEBUG::[directunpacker:248] DirectUnpack Unrar output 
UNRAR 6.11 beta 1 freeware      Copyright (c) 1993-2022 Alexander Roshal
[...]
Extracting from /home/_ME_/downloads/incomplete/_JOB_/_HEX_.part51.rar

...         _JOB_.mkv  OK
All OK
2023-04-17 11:06:02,868::DEBUG::[newsunpack:536] DirectUnpacker still alive for _JOB_: 51/51
```
That last line is repeated every 2 seconds for one minute, then this:
```
2023-04-17 11:08:04,988::INFO::[directunpacker:454] Aborting DirectUnpack for _HEX_
2023-04-17 11:08:05,189::DEBUG::[filesystem:945] Removing dir recursively /home/_ME_/downloads/sickbeard-queue/_UNPACK__JOB_
2023-04-17 11:08:05,432::DEBUG::[newsunpack:536] DirectUnpacker still alive for _JOB_: 0
```
And that last line gets repeated indefinitely, every 2 seconds, while the job is in history with an animated icon and the status stuck at 'Direct Unpack: Completed'. Attempting to delete the job from the history results in no actual changes but a single line about ionice in the log on the first try:
```
2023-04-17 11:20:22,051::INFO::[postproc:201] Killed external process /usr/bin/ionice
```

After that, it's back to `DEBUG::[newsunpack:536] DirectUnpacker still alive for _JOB_: 0`every 2 seconds. Trying to stop the application by sending signal 15 has no effect, only a hard kill (signal 9) works. Upon restart, the job is extracted yet again and postprocessing finally manages to complete.

Edit: once the job completes after the restart, the downloaded file is fine but some info (Source, Download and Servers details) is missing from the history entry, and the download speed column is empty.

Full log sent via email.

**Comment by Safihre** [comment]
Aai, will have to see how to reproduce.
Or maybe @puzzledsab @mnightingale know of some of the Downloader changes that could be related to this?

**Comment by thezoggy** [comment]
ive seen a few people report this on discord but no one really providing much details, here is on snippet that shows the same thing about directunpacker being alive:
![Discord_2023-04-17_14-30-15](https://user-images.githubusercontent.com/500882/232591254-f6c7bfc3-bee9-4e09-a1f6-339be72de24f.png)

**Comment by thezoggy** [comment]
@jcfp do you have more than one usenet server? 

i wonder if it only happens if multiple servers are involved.. like one gets tried.. doesnt get killed because download is still ongoing but then the missing stuff gets filled by next server and then some sort of race condition happens at that point with cleanup of connections

**Comment by Safihre** [comment]
I really wonder how the direct unpack is related.. Could be a whole problem on it's own?

**Comment by Safihre** [comment]
Added some additional locking. Tried to reproduce, but couldn't so far.

**Comment by Safihre** [comment]
@jcfp Let me know if you experience it again with RC1!

**Comment by Safihre** [comment]
We haven't changed direct unpack code at all since 3.7.2.
https://github.com/sabnzbd/sabnzbd/commits/develop/sabnzbd/directunpacker.py
Can you try without ionice/nice?

**Comment by puzzledsab** [comment]
I haven't looked at the direct unpacker before but from I can tell SAB will stop logging and assume it's done when it sees "All OK". Maybe RAR is trying to do something after that? Or maybe the unfinished RAR files is broken in such a way that RAR breaks when it is fixed by PAR2? I think the bad try list is only indirectly related to the RAR problem.
