### ISSUE TITLE
Very long filename problem

### ISSUE THREAD

**Issue by hulleyrob** [sabnzbd/sabnzbd#2534]
Hi again, did have an issue I thought I had fixed with max folder length being reduced to 100 but im still having problems with long filenames. 

The one is question is 199 characters being returned by the indexer. 

Can we have an option to truncate the filename after say X characters?

If not how is it best to deal with these as it seems to happen a lot on foreign grabs.

Thanks

**Comment by Safihre** [comment]
So what is actually too long? The filename or the folder name?
What error are you getting now? The whole error.

**Comment by hulleyrob** [comment]
Invalid NZB file Is It Wrong to Try to Pick Up Girls in a Dungeon S04E12 (Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka - Familia Myth IV | DanMachi S4).nzb, skipping (error: [Errno 36] Filename too long: '/incomplete-downloads/Is It Wrong to Try to Pick Up Girls in a Dungeon S04E12 (Dungeon ni Deai o Motomeru no wa Machigatte/__ADMIN__/Is It Wrong to Try to Pick Up Girls in a Dungeon S04E12 (Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka - Familia Myth IV | DanMachi S4).nzb.gz')

**Comment by thezoggy** [comment]
How are you adding the nzb to sab?

**Comment by hulleyrob** [comment]
It was automatic via Sonarr, if I download it manually and add it it works.

**Comment by thezoggy** [comment]
Can you share the logs of sonarr adding (trace/debug) ?

**Comment by hulleyrob** [comment]
Hi its Sonarr v3, I suspect its the BTRFS filename length limit (255) causing extra issues for me and not you.

I am however unable to find any errors for this in the Sonarr logs and it came via RSS so I don't think I can replicate.

As I use NZBHydra also I can probably regex most of the title out but I have found that a lot of NZBs from AnimeTosho have this issue as they include both the English and Japanese titles in the name.

**Comment by Safihre** [comment]
I don't think I understand the error though.. What is actually too long? Because the filename is only 153 characters. Is the whole path maybe too long? Is this a common limitation @jcfp @sanderjo ? Or is this some mounted Windows drive @hulleyrob ?
IBecause even if we make the NZB name shorter, it still depends on the base path if it will exceed 255.

**Comment by hulleyrob** [comment]
Nope its on a Synology NAS, I agree but my request was to have a filename limitation in addition to the existing folder name length setting. Between the 2 I should be able to reduce to under 255?
 
Here is what ive found on the Synology KB:
Btrfs File System
Maximum file name length: 255 bytes (See limitation 6)
Maximum path name length: 4,096 bytes (See limitation 6)

**Comment by hulleyrob** [comment]
Looks like it's a Synology limitation and the filename limit is 143 characters due to the implementation of enryptfs. This is probably in addition to the total file path limit of 255.

**Comment by Safihre** [comment]
Wonder why we haven't made this configurable but only the folder name length?

**Comment by Safihre** [comment]
We should include this in the start-up test in any case.

**Comment by sanderjo** [comment]
> We should include this in the start-up test in any case.

You mean: discovery of max file name length? And a bit of max folder length?

If so: I'll make that.

**Comment by Safihre** [comment]
@sanderjo Nothing too smart, just a check: can we write a file with 250 chars filename?

**Comment by Safihre** [comment]
No, for now just the same warning that they can experience problems.

**Comment by thezoggy** [comment]
> Looks like it's a Synology limitation and the filename limit is 143 characters due to the implementation of enryptfs. This is probably in addition to the total file path limit of 255.

yeah, you will want to adjust values WAY down if your using encryptfs since file names are limited to no longer than 143 bytes. (which you can easily reach from just some unicode characters alone). or just move sab incomplete folder to a non encryptfs drive. or switch to using a drive encrypted setup (if supported) so you dont have limits you have when doing a virtual file system inside of a filesystem like your doing.

**Comment by Safihre** [comment]
Yeah but even if we fix the size on SABnznd side, there's still par2 and unrar that most likely (assumption) don't adjust for this limited filename lengths so there will always be failing downloads.
So yes, all we can do is warn at startup and educate the user when they come to complain/ask.

**Comment by thezoggy** [comment]
also usually a performance hit with eCryptfs as well. just noting this here also to gently nudge poster to think about switching to something better

> [eCryptfs](https://en.wikipedia.org/wiki/ECryptfs) is an alternative filesystem-level encryption solution. It is a stacked filesystem, which means it sits on top of a real filesystem, rather than being directly integrated into the real filesystem. Stacked filesystems have a couple advantages (such as working on almost any real filesystem), but also some significant disadvantages.

> eCryptfs shouldn't be used, if at all possible. eCryptfs's use of filesystem stacking causes a number of issues, and eCryptfs is no longer actively maintained. The original author of eCryptfs recommends using Linux native filesystem encryption instead. The largest users of eCryptfs (Ubuntu and Chrome OS) have switched to dm-crypt or Linux native filesystem encryption.

**Comment by hulleyrob** [comment]
yeah the next version of DSM is bringing they LUKS based version but it looks like im stuck with what im using for many reasons. I guess if you can't/won't add a filename limit ill have to just keep creating hydra regex to fix the issue as it comes up.

**Comment by Safihre** [comment]
We can introduce a filename limit, but as I wrote above, it won't stop unrar and par2 from creating filenames that your system can't handle... So your downloads will still fail.

**Comment by hulleyrob** [comment]
Hmm weird. When I manually downloaded the nzb and added it via drag and drop it worked. What's different?

**Comment by thezoggy** [comment]
> Hmm weird. When I manually downloaded the nzb and added it via drag and drop it worked. What's different?
> 
> (By worked I mean didn't instantly error maybe that's the difference that the automatic one actually tried to download and unzip as you said but I'm pretty sure it errors instantly when it's automatic)

look at the logs, but prob has to do where your saving/loading the nzb from vs whats its name.   taking in something via api vs gui

**Comment by sanderjo** [comment]
Don't we do that already with `DEF_FILE_MAX` ?

`sabnzbd/constants.py:33:DEF_FILE_MAX = 255 - 10  # max filename length on modern filesystems, minus some room for extra chars later on`


Usage:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L241
... which is incorrect with unicode names, which I will fix.

**Comment by hulleyrob** [comment]
That's not user definable is it?

**Comment by sanderjo** [comment]
> That's not user definable is it?

As you run from source: yes, it is: fill out in sabnzbd/constants.py

**Comment by hulleyrob** [comment]
ill give it a go and see what happens, if it works can it be added to the specials page as im guessing an update will reset all the constants?

**Comment by sanderjo** [comment]
> can it be added to the specials page

Because of your N=1, with ecryptfs, which is not maintained anymore (per quote Zoggy)?
