### ISSUE TITLE
[4.0.0rc1] re-ordering of sorters broken by recent interface changes

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2536]
Re-ordering sorters in the Config no longer works, in at least Firefox and Chrome. Although one can still drag a sorter up or down, dropping it somewhere no longer changes the order. The visual hint with the flag icon also fails to move around while dragging.

**Comment by thezoggy** [comment]
also to note that you no longer can copy text off the pattern key like before as it thinks you want to reorder the section
