### ISSUE TITLE
[4.0.0rc1, firefox] very low contrast for affected categories preview in config->sorting

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2537]
In Firefox the 'affected categories' preview in config->sorting (displayed below the sort string while sorter details aren't visible) has very little colour difference between the affected (#f0f0f0) and unaffected (#eeeeee) categories.

No such problem in Chrome (with #f3f3f3 vs. #dddddd):
![cat_contr](https://user-images.githubusercontent.com/6666432/233768513-8335f7c8-fcba-49df-8b87-5e0f03730703.jpg)

**Comment by Safihre** [comment]
Didn't know we set specific styles for that? Isn't it browser and/or bootstrap default?

**Comment by thezoggy** [comment]
its because its 'disabled' applied which triggers the browser built in css to get loaded which you can see with chrome just has some additional things that firefox doesnt.

**Comment by Safihre** [comment]
Seems it depends on OS?
On Windows Firefox 112:
![image](https://user-images.githubusercontent.com/5703454/233861393-a1ee96c1-a07a-4912-8fb7-2ec0412f80e4.png)

**Comment by thezoggy** [comment]
Firefox is fine, it's chrome that changes font color+opacity

**Comment by Safihre** [comment]
Not based on @jcfp's screenshot.

**Comment by thezoggy** [comment]
I was focusing on the font/opacity. The bf color is another thing. But I believe that's also address in that pr

**Comment by Safihre** [comment]
We don't apply any styling, so this should be a problem in any website that uses a disabled multi select.
I'll check on macOS, but if it's also displayed correctly there I consider this more a bug of Firefox on this platform and not of Sabnzbd. I don't want to mess with default styles unless really needed.

**Comment by Safihre** [comment]
Also on macOS it looks fine.
Chrome left, Firefox right.
Closing this, as it seems specific to the OS and we don't apply any styling here.
<img width="896" alt="Screenshot 2023-04-24 at 14 19 28" src="https://user-images.githubusercontent.com/5703454/233994707-80e29313-6be7-4b91-9aab-2d33a3134c82.png">
