### ISSUE TITLE
Don't queue aborted jobs

### ISSUE THREAD

**Issue by hr1232** [sabnzbd/sabnzbd#2543]
**Error description:**
When a job is aborted for not having enough parts available (option "Abort jobs that cannot be completed"), it doesn't get failed directly. Instead it is queued for post processing. Depending on how many entries the post processing queues has, that aborted job will sit there for quite some time. Search for an alternative NZB in Sonarr/Radarr/Lidarr will be delayed until SABnzbd has finally marked the job as failed.

**Suggested change:**
If the job gets aborted, there's no need for post processing. Just mark ist failed directly, so Sonarr/Radarr/Lidarr can remove it from the queue and search for an alternative.

**Comment by thezoggy** [comment]
Do you have only pp successful jobs enabled?

**Comment by hr1232** [comment]
BTW, I'm using version 3.7.2 (fab36ec)

**Comment by Safihre** [comment]
You can also set it to run post processing scripts even if jobs fail. If users want that is only checked during Post Processing.
Mostly the reason is that it's easier to maintain the code and logic this way. Because if all jobs follow the same logic steps and we don't have to extract part of it, there's less room for introducing bugs.

However, I could imagine we extend to concept of the Fast and Slow queues that we already have internally. Allowing failed jobs and jobs that succeeded with Direct Unpack to be processed in parallel to slow jobs that need all professing.

**Comment by hr1232** [comment]
You don't seem to grasp the point of this ticket. I'm talking about jobs that were **ABORTED** because none or not enough articles were available for download.

What part of the non-existent data do you want to verify or post-process for such a job? What should be the point in running a post-processing script? When aborting the job, you are 100% sure that neither verification nor post-processing makes any sense. Just mark the job failed instead of queuing it for verification and postprocessing. That way, Sonarr/Radarr/Lidarr can pick them up and start searching for alternatives without waiting for needless dumbfuck-operations that do nothing except make the system slower.

**Comment by Safihre** [comment]
There are some users that want to run post processing scripts on also failed jobs so they can use the script to trigger a new job.

I understand your ticket very well and just wanted to give you context.

However, I don't understand why you use this tone..

**Comment by hr1232** [comment]
Since the club of sissies only wants to whine about their feelings here is a workaround cron-script for everyone who's running into the same problem. It will turn on a speedlimit whenever post-processing queue is needlessly filled up because of SABnzbd's bad design and allow post-processing to catch up. When the queue is nice and small again, it will automatically turn off the speedlimit. Just run it every few minutes and the problems cause by sissy-design-flaws will go away.

```
<?php

  // take action when history tab contains this many or more elements
  $maxqueue = '100';

  // limit speed to this level (in percent) to allow post-processing to catch up
  $speedlimit = '3';

  // sabnzbd api-key and api-hostname (NO TRAILING /)
  $key = '11112222333344445555666677778888';
  $host = 'http://127.0.0.1:8080/api';

  // ----------------------------------

  $base = $host.'?output=json&apikey='.$key;
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, $base.'&mode=history');
  curl_setopt($curl, CURLOPT_HEADER, FALSE);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  $result = curl_exec($curl);
  $httpCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
  curl_close($curl);
  if ($httpCode == 200) {
    if ($result = json_decode($result)) {
      if (count ($result->history->slots) > $maxqueue)
        $limit = $speedlimit;
      else
        $limit = 0;
      $curl = curl_init();
      curl_setopt($curl, CURLOPT_URL, $base.'&mode=config&name=speedlimit&value='.$limit);
      curl_setopt($curl, CURLOPT_HEADER, TRUE);
      curl_setopt($curl, CURLOPT_NOBODY, TRUE);
      curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
      $result = curl_exec($curl);
      $httpCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
      curl_close($curl);
      http_response_code($httpCode);
      if ($httpCode != 200)
        exit(1);
    } else {
      http_response_code(500);
      exit(1);
    }
  } else {
    http_response_code($httpCode);
    exit(1);
  }

?>
```
