### ISSUE TITLE
SABnzbd does not unpack archives when started as a Windows service

### ISSUE THREAD

**Issue by dom6770** [sabnzbd/sabnzbd#2544]
This issue started some weeks ago, I already tried a reinstallation of SABnzbd, but without success.
It's present on 3.7.2 and 4.0.0

Whenever I start SABznbd on my Windows Server 2019 machine, SABnzbd will not unpack any download. 
When the download is finished, it's been moved to the history section, and the post-processing starts. 
At one point it shows briefly "unpacking 00/xx" and immediately switches to "completed".
The directory of the download only contain all the archives, nothing is unpacked.

Expected behavior at this point is, that SABnzbd unpacks all archives and deletes the archives.
This expected behavior is present when I launch SABnzbd not as a service, but rather as a Windows user directly through the start menu.

Here's a log of the 3.7.2 installation with the bug: https://wastebin.neus.xyz/SPBAKd.txt

**Comment by thezoggy** [comment]
what user do you run sab service as? is E:\ a local drive or network?

as we say in the wiki
https://sabnzbd.org/wiki/advanced/sabnzbd-as-a-windows-service

> When using network shares with the SABnzbd service, you must use network (UNC) paths (\\server\share) instead of drive letters (P:\).

> Even after doing the above to enable network share access, you will still be restricted to local drives only for the admin, log and incomplete folders due to limitations in those functions. Make sure, in your SABnzbd web interface configuration that those folders are not pointing to network shares.

**Comment by dom6770** [comment]
E: is a local drive, I tried using my Windows user and the default option as logon, there's no difference.

I had the same setup working for ages, it just broke since 3.7.x or something, can't tell. I try to downgrade to 3.6 and look if it works again.

**Comment by dom6770** [comment]
Welp, I don't know why is it working now, but before I submitted the issue I absolutely tried it with my Windows user account as service user, and the result was the same. Somehow, now it's working. Don't ask me why.
