### ISSUE TITLE
Sabnzbd service doesn't start on Dietpi after 4.0.0 update

### ISSUE THREAD

**Issue by githubchonger** [sabnzbd/sabnzbd#2545]
I have sabnzbd running as a service on my Raspberry Pi 4 running Dietpi. I updated sabnzbd to 4.0.0 and now the sabnzbd service fails to start. I see the syntax error below when I run `journalctl -u sabnzbd.service`.

```
-- Logs begin at Thu 2019-02-14 10:12:00 GMT, end at Fri 2023-04-28 21:33:19 BST. --
Apr 28 21:05:47 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 28 21:05:48 NAS SABnzbd[449]:   File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:48 NAS SABnzbd[449]:     if home := os.environ.get("HOME"):
Apr 28 21:05:48 NAS SABnzbd[449]:              ^
Apr 28 21:05:48 NAS SABnzbd[449]: SyntaxError: invalid syntax
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 1.
Apr 28 21:05:48 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 28 21:05:48 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 28 21:05:48 NAS SABnzbd[477]:   File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:48 NAS SABnzbd[477]:     if home := os.environ.get("HOME"):
Apr 28 21:05:48 NAS SABnzbd[477]:              ^
Apr 28 21:05:48 NAS SABnzbd[477]: SyntaxError: invalid syntax
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 21:05:48 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 2.
Apr 28 21:05:49 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 28 21:05:49 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 28 21:05:49 NAS SABnzbd[478]:   File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:49 NAS SABnzbd[478]:     if home := os.environ.get("HOME"):
Apr 28 21:05:49 NAS SABnzbd[478]:              ^
Apr 28 21:05:49 NAS SABnzbd[478]: SyntaxError: invalid syntax
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 3.
Apr 28 21:05:49 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 28 21:05:49 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 28 21:05:49 NAS SABnzbd[482]:   File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:49 NAS SABnzbd[482]:     if home := os.environ.get("HOME"):
Apr 28 21:05:49 NAS SABnzbd[482]:              ^
Apr 28 21:05:49 NAS SABnzbd[482]: SyntaxError: invalid syntax
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 21:05:49 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 4.
Apr 28 21:05:49 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 28 21:05:50 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 28 21:05:50 NAS SABnzbd[484]:   File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:50 NAS SABnzbd[484]:     if home := os.environ.get("HOME"):
Apr 28 21:05:50 NAS SABnzbd[484]:              ^
Apr 28 21:05:50 NAS SABnzbd[484]: SyntaxError: invalid syntax
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Service RestartSec=100ms expired, scheduling restart.
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 5.
Apr 28 21:05:50 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Start request repeated too quickly.
Apr 28 21:05:50 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 28 21:05:50 NAS systemd[1]: Failed to start SABnzbd (DietPi).
```

**Comment by thezoggy** [comment]
you prob should report issues from where you got sab from (dietpi):
https://github.com/MichaIng/DietPi

and if i understand dietpi stuff correctly, you should just use their package manager to uninstall old version and install new version of sab.  but also, from lack of info i assume your just trying to run sab with python2 not python3.

**Comment by sanderjo** [comment]
Apr 28 21:05:48 NAS SABnzbd[449]: File "/etc/sabnzbd/SABnzbd.py", line 403
Apr 28 21:05:48 NAS SABnzbd[449]: if home := os.environ.get("HOME"):
Apr 28 21:05:48 NAS SABnzbd[449]: ^



Which python3 version? Because

**Comment by githubchonger** [comment]
python3 -V shows Python 3.7.3.  Does that mean I need to update to a newer version of Python?

**Comment by sanderjo** [comment]
Yes.

But can you check something: in you SABnzbd.py, around line 20, what is around the line `if sys.hexversion < 0x03080000`
Because that is the check for the correct python3 version. How you can beyond that line?

**Comment by githubchonger** [comment]
```
if sys.hexversion < 0x03080000:
    print("Sorry, requires Python 3.8 or above")
    print("You can read more at: https://sabnzbd.org/wiki/installation/install-$
    sys.exit(1)
```

Not sure how the install got past this line?

**Comment by sanderjo** [comment]
Can you do this?

```
$ python3
Python 3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.6.9 (default, Mar 10 2023, 16:46:00) \n[GCC 8.4.0]'
>>> sys.hexversion
50727408
>>> sys.hexversion < 0x03080000
True

```

**Comment by sanderjo** [comment]
plus:

`md5sum /etc/sabnzbd/SABnzbd.py`

```
$ md5sum SABnzbd.py 
accb074da542d4b1521a7da70ea6fc40  SABnzbd.py
```

I wonder if running from systemd has impact? What if you run SABnzbd from the CLI from `/etc/sabnzbd/SABnzbd.py`

**Comment by thezoggy** [comment]
diepi uses debian buster as its base that os is a bit dated which is why it has outdated python 3.7
https://packages.debian.org/buster/python3-dev

so the tl;dr; sab 4.x is not supported at this time on your os.
you should report issue to dietpi so they can guard against them installing a now unsupported version of sab. they could just hardcode to just do 3.7.2 as latest on their side.. or ideally they just update their python to something more modern.

**Comment by githubchonger** [comment]
```
python3
Python 3.7.3 (default, Oct 31 2022, 14:04:00)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.7.3 (default, Oct 31 2022, 14:04:00) \n[GCC 8.3.0]'
>>> sys.hexversion
50791408
>>> sys.hexversion < 0x03080000
True
```

and 

```
md5sum /etc/sabnzbd/SABnzbd.py
accb074da542d4b1521a7da70ea6fc40  /etc/sabnzbd/SABnzbd.py
```

**Comment by githubchonger** [comment]
> diepi uses debian buster as its base that os is a bit dated which is why it has outdated python 3.7 https://packages.debian.org/buster/python3-dev
> 
> so the tl;dr; sab 4.x is not supported at this time on your os. you should report issue to dietpi so they can guard against them installing a now unsupported version of sab. they could just hardcode to just do sab 3.7.2 as latest on their side.. or ideally they just update their python to something more modern (but they might have to update debian to newer if they dont want to install ppa).

Thanks for the explanation, that makes sense.  I'll log something with Dietpi now.

**Comment by sanderjo** [comment]
> I wonder if running from systemd has impact? What if you run SABnzbd from the CLI from `/etc/sabnzbd/SABnzbd.py`

@githubchonger  can you that?

**Comment by Joulinar** [comment]
> diepi uses debian buster as its base

This is not correct. Dietpi is a set of bash script and not related to a Debian version. We don't offer Buster images anymore since more than an a year. You would need to update your system Debian Bullseye. For this we created a guide. https://dietpi.com/blog/?p=811

**Comment by githubchonger** [comment]
> I wonder if running from systemd has impact? What if you run SABnzbd from the CLI from `/etc/sabnzbd/SABnzbd.py`

How would I do this?

**Comment by Safihre** [comment]
I think the problem here is that Py files are compiled to bytecode before being executed. Only when executed will the check for Python version be done.
But already during compilation to bytecode is when it crashes.
Nothing we can do about that....

**Comment by thezoggy** [comment]
> > diepi uses debian buster as its base
> 
> This is not correct. DietPi is a set of bash script and not related to a Debian version. We don't offer Buster images anymore since more than an a year. You would need to update your system to Debian Bullseye. For this we created a guide. https://dietpi.com/blog/?p=811

yes i understand its just bash scripts but i was just going off what i read on dietpi's github repo and docs
> DietPi is an extremely lightweight Debian-based OS. It is highly optimised for minimal CPU and RAM resource usage, ensuring your SBC always runs at its maximum potential.

https://dietpi.com/docs/usage/ - buster galore
and then google searched for py3.8 you mention it installs from buster
https://dietpi.com/forum/t/updating-to-python-3-8/5362

so anyways just sounds like user is just running legacy dietpi. if so, perhaps the best solution is to prevent legacy users from installing newer sab since its not supported?

**Comment by Joulinar** [comment]
> so anyways just sounds like user is just running legacy dietpi. if so, perhaps the best solution is to prevent legacy users from installing newer sab since its not supported?

We simply did not know that you guys dropped support for old python version. We will for sure include this ins our next release to install an old version and did not update to version 4 on Buster systems.

**Comment by thezoggy** [comment]
> > so anyways just sounds like user is just running legacy dietpi. if so, perhaps the best solution is to prevent legacy users from installing newer sab since its not supported?
> 
> We simply did not know that you guys dropped support for old python version. We will for sure include this ins our next release to install an old version and did not update to version 4 on Buster systems.

All good, if you could pin 3.7.2 for legacy dietpi that might be good compromise for users that don't want to upgrade their box so atleast they can use the latest version that supports them.  Otherwise if I see anymore users that join our discord about it I'll kindly toss them the blog about updating to newer os/dietpi

**Comment by Joulinar** [comment]
> legacy dietpi

Let's call it oldstable Debian Buster. Because the version of DietPi is always same on Buster, Bullseye and Bookworm 😉

**Comment by githubchonger** [comment]
@Joulinar Thanks for that blog post.  I followed the steps and successfully upgraded to bullseye

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
I've confirmed that Python 3 has been updated from 3.7.3 to 3.9.2

```
$ python3 -V
Python 3.9.2
```

At this point sabnzbd still wasn't running so I tried reinstalling. I ran `dietpi-software reinstall 139` and it choked on something, not sure what.

```
APT update
- Command: apt-get -y -eany update
- Exit code: 100 
- DietPi version: v8.16.2 (MichaIng/master) | HW_MODEL: 4 | HW_ARCH: 3 | DISTRO: 6
- Image creator: DietPi Core Team
- Pre-image: Raspberry Pi OS Lite (64-bit) 
- Error log:     
Hit:1 https://downloads.plex.tv/repo/deb public InRelease 
Hit:2 https://deb.debian.org/debian bullseye InRelease 
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease 
Hit:4 https://deb.debian.org/debian-security bullseye-security InRelease 
Hit:5 https://deb.debian.org/debian bullseye-backports InRelease
Ign:6 https://download.mono-project.com/repo/debian bullseye InRelease 
Ign:7 https://apt.sonarr.tv/debian bullseye InRelease
Err:8 https://download.mono-project.com/repo/debian bullseye Release 
   404  Not Found [IP: 72.21.81.200 443]
Hit:9 https://archive.raspberrypi.org/debian bullseye InRelease
Err:10 https://apt.sonarr.tv/debian bullseye Release 
   404  Not Found [IP: 37.187.255.43 443]
Reading package lists...
E: The repository 'https://download.mono-project.com/repo/debian bullseye Release' does not have a Release file.
E: The repository 'https://apt.sonarr.tv/debian bullseye Release' does not have a Release file.                         
```

`journalctl -u sabnzbd.service` shows the following

```
Apr 29 16:34:13 NAS systemd[1]: Started SABnzbd (DietPi).
Apr 29 16:34:14 NAS SABnzbd[1677]: Not all required Python modules are available, please check requirements.txt
Apr 29 16:34:14 NAS SABnzbd[1677]: Missing module: sabctools
Apr 29 16:34:14 NAS SABnzbd[1677]: You can read more at: https://sabnzbd.org/wiki/installation/install-off-modules
Apr 29 16:34:14 NAS SABnzbd[1677]: If you still experience problems, remove all .pyc files in this folder and subfolders
Apr 29 16:34:14 NAS systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 16:34:14 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 29 16:34:14 NAS systemd[1]: sabnzbd.service: Scheduled restart job, restart counter is at 5.
Apr 29 16:34:14 NAS systemd[1]: Stopped SABnzbd (DietPi).
Apr 29 16:34:14 NAS systemd[1]: sabnzbd.service: Start request repeated too quickly.
Apr 29 16:34:14 NAS systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
Apr 29 16:34:14 NAS systemd[1]: Failed to start SABnzbd (DietPi).
```
Any ideas?  Are there additional Python modules I need to download?

**Comment by Joulinar** [comment]
Mono and Sonarr source list need to be switched back to Buster as they don't offer Bullseye repository. But this should be documented on our blog post

**Comment by sanderjo** [comment]
> Any ideas? Are there additional Python modules I need to download?

Well, did you check the URL in the error message?

**Comment by Joulinar** [comment]
just for the records, I just tested sab on 32bit as well as 64bit system without issues. It has been successfully installed on both systems.

@githubchonger you would need to fix your source files and reinstall sab. This should pull all dependency and packages.

**Comment by githubchonger** [comment]
> you would need to fix your source files and reinstall sab. This should pull all dependency and packages.

@Joulinar and @sanderjo That did the trick. sab is now back up and running.  Thanks to everyone here for your help!

**Comment by Safihre** [comment]
I "hacked" a better error, it will now show on Python 3.7 and below:
```
  File "SABnzbd.py", line 20
    if Python_38_is_required_to_run_SABnzbd:= sys.hexversion < 0x03080000:
```

**Comment by Joulinar** [comment]
Will test this on a Buster VM within the next days.

**Comment by Joulinar** [comment]
ok tested Sab 4.0.1 on a Buster system, following error message is shown now

```
May 01 21:50:32 DietPiVM2 systemd[1]: Started SABnzbd (DietPi).
May 01 21:50:32 DietPiVM2 SABnzbd[3885]:   File "/etc/sabnzbd/SABnzbd.py", line 22
May 01 21:50:32 DietPiVM2 SABnzbd[3885]:     if Python_38_is_required_to_run_SABnzbd := sys.hexversion < 0x03080000:
May 01 21:50:32 DietPiVM2 SABnzbd[3885]:                                              ^
May 01 21:50:32 DietPiVM2 SABnzbd[3885]: SyntaxError: invalid syntax
May 01 21:50:32 DietPiVM2 systemd[1]: sabnzbd.service: Main process exited, code=exited, status=1/FAILURE
May 01 21:50:32 DietPiVM2 systemd[1]: sabnzbd.service: Failed with result 'exit-code'.
```

will go to blog the update to Sab 4 for our Buster users now. This should become available in a week time once we released a new DietPi version.
