### ISSUE TITLE
0.8.x - glitter -- add nzb

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#255]
![glitter](http://zoggy.net/sabnzbd4.png)

example with a normal tv show length (not even one that uses ep title):
![glitter](http://zoggy.net/sabnzbd4b.png)

The add nzb modal is not very friendly for any nzb/url/filename that is any decent length... this could really benefit from a layout change / using tabs.

should try to maximize the input to the full width, put the legend/title above. change browse to icon.. 
the icons for the cat/priority/etc are somewhat pointless without tooltip/labels.. as I even had no clue what each was until I looked at the drop downs and could infer what is what. most people arent going to add by url and by file.. so focus only on one at a time, reduce clutter.. put each on a tab.

**Comment by thezoggy** [comment]
other comments about glitter.. cant tell what version of sab. the sab settings and the skin settings being next to each other with similar icons is confusing.. and then the skin settings being one ultra long modal.. seems dumb. lack of tooltip/title on images is a bit troubling for accessibility.

**Comment by thezoggy** [comment]
also to see the nzb completion you need to click on the tiny hit target for the dropdown arrow.. which is awfully close to the trash can icon.. easy to hit the wrong one (especially on mobile/fingers). anyways not sure glitter is ready just yet to be the default skin just yet...

**Comment by Safihre** [comment]
Thanks for the feedback!
The idea kind of is to get rid of extra clicks and tabs etc, indeed in the *Status and interface options* it has become long and that might need a better solution. But for the *Add-NZB* it is a design choice to keep it all in 1 modal, to see it all in 1 glance. The input box in Plush shows the same amount of text of the URL/file-name, so I kept that as a reference. 
The cat/priority/etc have tooltips if you hold your mouse on the icon or the dropdown. I will make them the more clear black tooltips!
The version can be seen in the Help menu, the user doesn't need that info when there's no trouble.
Indeed the free-space was missing the label 'Temp', somehow disappeared in making it multi-language. I' have placed that back!
Let me know where you are missing tooltips!

**Comment by thezoggy** [comment]
lets say by default it shows add via upload, and then the next tab is add via url. well then its only one extra click if you need to do url. but the benefit for both sections is that you can actually see what your uploading/adding now. useability should trump some magical click count. yes you dont want to click 10 times to add a nzb. but you also dont want to be able to click once to format your computer. make sense?

**Comment by thezoggy** [comment]
no tooltip/titles for the icons like the trash cans.. do delete an item from the queue/history. or the download stats.. or the free space.. or power icon up top.. etc

**Comment by Safihre** [comment]
The trashcans have title's, no need for tooltips there since it is very obvious.
Download stats have text. Free space has text.
Power icon indeed, that could use some clarification.
I added tooltips to the cat/priority/etc for ongoing downloads (when clicking the little arrow at a job).

**Comment by Safihre** [comment]
Changed the Add-NZB window so file-upload is now better handled visually and tooltips for the bottom options.
![untitled](https://cloud.githubusercontent.com/assets/5703454/8911383/75f44364-348c-11e5-92a7-3f96117dd667.png)

**Comment by Safihre** [comment]
Submitted the changes illustrated above: #266
