### ISSUE TITLE
Change in how the release is saved?

### ISSUE THREAD

**Issue by abusenet** [sabnzbd/sabnzbd#2551]
Before v4.0, an NZB file named "big_buck_bunny_2000_1080p_h264.nzb" containing "big_buck_bunny_1080p_h264.mov" would be saved into "completed/Big Buck Bunny (2000)/big_buck_bunny_2000_1080p_h264.mov" with the sorting pattern `%sn (%y)`.

However, from v4.0, it is saved into "completed/Big Buck Bunny (2000)/big_buck_bunny_2000_1080p_h264/big_buck_bunny_2000_1080p_h264.mov" instead.

Was this an intentional change with the new generic Sorter?

**Comment by Safihre** [comment]
Yes. It's also described like that in the wiki. You need to include %fn or %ext.
But it's a change of behavior from 3.7.2, more users have reported it. What was the rationale @jcfp ?

**Comment by Safihre** [comment]
Change your Sorting string to  
%sn (%y)/%fn
And it will work like before.

**Comment by Safihre** [comment]
@jcfp Do you maybe remember why this was changed? I remember it being on purpose.

**Comment by Safihre** [comment]
@jcfp Do you maybe have time to fix this one? :)
