### ISSUE TITLE
Re-enable or remove ipv6_servers setting

### ISSUE THREAD

**Issue by topranks** [sabnzbd/sabnzbd#2553]
Hi,

Firstly thanks for much for Sab, been using many years and really can't thank you guys enough.

I'm just checking what the situation is with this particular setting, "ipv6_servers".  As per issue [1276](https://github.com/sabnzbd/sabnzbd/issues/1276) this setting no longer affects whether the software attempts to use IPv6 or not.  For instance I see in logs with this set to 0:
```
2023-05-08 20:10:33,544::INFO::[happyeyeballs:97] Quickest IP address for supernewsgroupserver.org (port 563, preferipv6 False) is 2001:1234:5678::1
```

Instead it uses Happy Eyeballs.  Which to be honest is great.  I am 100% not trying to push back on IPv6 adoption, and in some ways I'd be happy if you removed the "ipv6_servers" option completely (having it only encourages disabling v6 which isn't good).

My own situation is rather unique.  I have 2 ISPs.  The first ISP I have a much faster connection from, but they only provide IPv4.  The second ISP I got connected soley for connectivity to the IPv6 internet.  For most things the speed difference isn't of much concern.  But for Usenet downloads I want to use the fast link (and thus, sadly, IPv4).

Anyway I can approach this another way by preventing DNS resolution of AAAAs for my usenet provider hostnames.  But it would be simpler for me if "ipv6_servers" could still be used.  

Or otherwise perhaps it should be removed from the docs and default config, as it no longer seems to have an effect?

thanks!!

**Comment by sanderjo** [comment]
Dirty workaround for now: as newsserver, fill out the IPv4 address of your newsserver, and, if using NTTPS, set "Certificate verification" to disable.

Does that work for you? Higher speed, via IPv4.

**Comment by topranks** [comment]
Hi @sanderjo thanks for the feedback.

My trick using DNS RPZ failed (it can only affect entire names, not just block AAAA records).  I solved it by simply adding a blackhole route for the entire RIPE allocation of my usenet provider (seems they are a LIR and have their own dedicated space so should be no other "collateral damage").

Working perfectly.

> Dirty workaround: as newsserver, fill out the IPv4 address of your newsserver, and, if using NTTPS, set "Certificate verification" to disable.

This slightly confused me, was that a typo, and you mean add the IPv6 address there?  So TLS fails for IPv6?

Or is the idea to speed up the v4 by skipping the certificate validation so the connection completes before the v6 one?  I like the creativity :)

**Comment by thezoggy** [comment]
had a talk in discord today with another user which this kinda came up, they use newshosting which provides v4 and v6 names for their servers. with `news.newshosting.com` for v4 and `news6.newshosting.com` for v6. Not sure if your usenet server offers something similar.. but it is an easy way to go to control it that way as well.

**Comment by topranks** [comment]
> had a talk in discord today with another user which this kinda came up, they use newshosting which provides v4 and v6 names for their servers. with `news.newshosting.com` for v4 and `news6.newshosting.com` for v6. Not sure if your usenet server offers something similar.. but it is an easy way to go to control it that way as well.

That's cool.  Yeah I had a look on my providers site to begin with they didn't seem to have any protocol-specific names.  Not that they really should need to, it's a fairly niche requirement I have.

**Comment by sanderjo** [comment]
https://www.appelboor.com/newsservers/newsservers-with-SSL-TLS-OK.html gives a nice overview of newsserver names and their capabilites

**Comment by sanderjo** [comment]
> you mean add the IPv6 address there? So TLS fails for IPv6?
> 
> Or is the idea to speed up the v4 by skipping the certificate validation so the connection completes before the v6 one? I like the creativity :)

Not a typo. It forces IPv4, which you want.

**Comment by topranks** [comment]
> Not a typo. It forces IPv4, which you want.

Ok will read up on it.  Thanks again for your time and thoughts.

**Comment by topranks** [comment]
Hey so overall here feel free to close this one.  My solution is working nicely (thanks to the excellent Happy Eyeballs implementation), so it's no particular problem for me :)

I do think it would make sense to at least remove the _ipv6_servers_ setting from the docs, but absolutely your call.

Thanks!

**Comment by Safihre** [comment]
Yeah I'm also a bit confused..
I would have expected if `ipv6_servers=2` we would only allow IPv6 servers, which is not the case. 
Seems also like it's like that for a number of years already 😕 
Thoughts why that could be @sanderjo?

**Comment by sanderjo** [comment]
I would say: KISS, and thus let HappyEyeballs handle it, so remove ipv6_servers

Reasoning:

Normal users should not use the option ipv6_servers. 
And if they want to control IP type, it's clearer via the newsserver name, for example news6.eweka.nl versus news.eweka.nl . Note: only works for newsproviders that have provided different names.
https://www.appelboor.com/newsservers/newsservers-with-SSL-TLS-OK.html gives an overview

Network-techie users (like @topranks )  can steer special things/routings/etc outside SABnzbd (OS, firewall, router, resolving method), or within sab by hard-entering the IP address.

Related: CLI option

`--ipv6_hosting <0|1>    Listen on IPv6 address [::1]`

Redundant, because you can steer it via the option `--server`

**Comment by Safihre** [comment]
@sanderjo the current logic is a bit strange to me:
Why do we even try to get IPv6 addresses if our test in `sabnzbd.misc.test_ipv6()` returned False anyway?

**Comment by sanderjo** [comment]
> the current logic is a bit strange to me:
> Why do we even try to get IPv6 addresses if our test in `sabnzbd.misc.test_ipv6()` returned False anyway?

I don't know. The SAB IPv6 code is a collection of seperate settings and tests, introduced over a long period of time.

So, yes, we could introduce "if test_ipv6() is False, do not try to get IPv6 addresses" ... but ... that is even more code and more logic. IMHO not the way to go.

**Comment by sanderjo** [comment]
So the question is: what is the ideal SABnzbd IPv6 design?

* the normal user should not have anything to do / worry about
* it should in non-IPv6 setups (still 50% of the users, and 100% of docker setups)
* power users can steer via the newsserver name (if available) ... or a separate setting
* let happyeyeballs do the work (?)
* binding to IPv6 localhost should be possible.

**Comment by Safihre** [comment]
> I don't know. The SAB IPv6 code is a collection of seperate settings and tests, introduced over a long period of time.

I checked and the code is from 2012 😅

> So, yes, we could introduce "if test_ipv6() is False, do not try to get IPv6 addresses" ... but ... that is even more code and more logic. IMHO not the way to go.

Well, that's already the current way of working. The test (result) determines if we try to get IPv6, _or_ if HappyEyeBalls is enabled.

So the current way sounds like a good setting then that matches your requirements? 
Get all addresses if IPv6 reachable (test is performed during startup) or HappyEyeBalls is enabled.

**Comment by sanderjo** [comment]
I don't understand the SAB logic you're describing. 

But to answer your question: of course the current method is correct, because it works. :-)

But my proposal is to scrap code and settings. Why not just only keep HappyEyeballs, and scrap all the rest: test_ipv6(), ipv6_servers, "Server IP address selection"-options. Reasoning: Goole Chrome does not offer that either and it works. I doubt SAB users use those SAB ipv6 settings


And a long shot: to introduce a benchmarking: if user fills out "news.eweka.nl" (IPv4-only), let SAB also test "news6.eweka.nl" for speed. Mabye via IPv6 it's faster ... as that is a IPv6 promise: IPv6 has no NAT.
