### ISSUE TITLE
Disabling a server during download doesn't stop it from downloading

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2555]
I think we broke something @mnightingale @puzzledsab:
If you start a download with 2 active servers, then go into the Config and disable 1 server it just keeps downloading from the disabled server.

**Comment by mnightingale** [comment]
So I can observe that server.active is True and so is server.restart but this is going to keep the threads busy:

https://github.com/sabnzbd/sabnzbd/blob/fde8f9d13370ba19b6b3c7dcc679af2ebdf8fb29/sabnzbd/downloader.py#L873-L878

The bit that handles removing the server, this path is taken, I think it just needs to also check `not server.restart` before eagerly requesting the next article?

https://github.com/sabnzbd/sabnzbd/blob/fde8f9d13370ba19b6b3c7dcc679af2ebdf8fb29/sabnzbd/downloader.py#L627-L629
