### ISSUE TITLE
GuessIt Add Open Matte as an Edition

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2563]
Is it possible to add Open Matte to guessIt's list of Editions? 
Edit
Or better yet make it a user editable list that one could edit, add or remove at anytime coz I could think of alot of different additions to the list that i would personally want eg widescreen edition, fullscreen edition, etc

**Comment by thezoggy** [comment]
https://github.com/guessit-io/guessit/blob/develop/guessit/config/options.json#L230

**Comment by thezoggy** [comment]
you can see Open Matte is there:
https://github.com/guessit-io/guessit/blob/develop/guessit/config/options.json#L506

but anyways you might be better off using a 3rd party media manager or application which can do far more naming things. such as radarr or filebot.

**Comment by Safihre** [comment]
I think we provide quite a lot of options with all the GuessIt properties, beyond that indeed we suggest to use the 'real' tools like Sonarr/Radarr.
