### ISSUE TITLE
How do I get SABnzbd to use a Show Name with apostrophes?

### ISSUE THREAD

**Issue by spencerthayer** [sabnzbd/sabnzbd#2564]
For example the directory my files need to save in is `/Bob's Burgers/Season 2/` not `/Bobs Burgers/Season 2/`. How can I do this?

**Comment by thezoggy** [comment]
sab only has limited information to go off of, which is the release name and some metadata info inside the container via guessit. It does not pull down data from a scraper to know series names how they have it. If you want that sort of naming you would need to use a 3rd party script or media manager.  You might want to look at sonarr or filebot for that sort of thing.

**Comment by Safihre** [comment]
Exactly what @thezoggy said 👍
