### ISSUE TITLE
0.8a3 - Cannot change server host

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#257]
In 0.8a3 you cannot change the host of an already existing server. You can change everything of a server, except the host-name. When you press Save, it just goes back to the old value.

**Comment by shypike** [comment]
Not a new complaint.
The reason is that the server name is also the index to the byte counters.
It takes quite a few changes to allow this AND remain backwards compatible.

**Comment by thezoggy** [comment]
yeah, just have sab internally use an id number to keep track of the server and have the name not be the unique primary key. then would sidestep the issues where people try to use really long names / unicode / etc.

**Comment by Safihre** [comment]
Okay, making it *readonly*

**Comment by shypike** [comment]
@thezoggy : that's a solution, but tricky to implement in a way that also handles existing byte-counters. BTW: the names are also used in the scheduler.
Of course it can be done, just a bit of work...

**Comment by thezoggy** [comment]
well with 0.8.x you just blow away legacy stuff and focus on the new way (if migration is that much of a pain). most people would be okay with it.. especially if your having to nuke the queue before going to 0.8.x.

**Comment by shypike** [comment]
Maybe I can implement it without losing compatibility.

**Comment by shypike** [comment]
@thezoggy
Can you have a look at this implementation?
https://github.com/sabnzbd/sabnzbd/tree/rename-server

**Comment by thezoggy** [comment]
@shypike sure I'll check it out in a moment

**Comment by thezoggy** [comment]
appears to work so far, not sure if the 'test server' button is testing the old or the new host info.. no log entries in the console.. prob should show that there and update the popup to show what it tried..

**Comment by shypike** [comment]
Given a working server:
- Add a character to the name and test
- This should fail
- Restore the name and test
- This should succeed

**Comment by shypike** [comment]
Small fix: the download report still used the "internal" names.
