### ISSUE TITLE
Slow speed over OpenVPN on SABnzbd V4+ Windows

### ISSUE THREAD

**Issue by Obscurax** [sabnzbd/sabnzbd#2570]
I am using SABnzbd on Windows (Server 2022) over an OpenVPN connection. 
Since I upgraded to V4+ I cant get speeds over +- 1 MB/s. 
The moment I downgrade to 3.7.2 I am getting normal speed of 8,8 MB/s.

![sab](https://github.com/sabnzbd/sabnzbd/assets/6681453/b055da8b-07a5-495d-823a-b60c6c6b2c71)

logs
[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/11514477/sabnzbd.log)

**Comment by Safihre** [comment]
Try setting downloader_sleep_time to 0 in Config Specials, then restart SABnzbd. Does that help?

**Comment by Obscurax** [comment]
Yep this fixed it.

**Comment by mnightingale** [comment]
It's quite a drop in performance with the defaults, probably warrants a bit of further investigation.

https://github.com/sabnzbd/sabnzbd/blob/63c7dbdb4d70318548cdbe4b7a2450ed529bbcf7/sabnzbd/downloader.py#L693-L700

Maybe something odds goes on with OpenVPN buffers and this ends up sleeping more often than usual?

I've never liked the use of sleep in the downloader, but I can set it to 0 or other low value and not worry about it.

**Comment by Obscurax** [comment]
> @Obscurax Does the VPN start on your machine running SABnzbd? (Or is on another device, like a router?). If VPN is on your SAB machine ... can you see it's there via the interface, for example via `ipconfig `?

Yes runs on the same machine, and the interface in there.

![ovpn](https://github.com/sabnzbd/sabnzbd/assets/6681453/ab1822c4-219c-4024-be48-23d4358aa6c1)

**Comment by sanderjo** [comment]
Thanks. 

So: "OpenVPN", but Default Gateway is empty? Is that a Windows thing?

**Comment by sanderjo** [comment]
@Obscurax 

Do you have python3 installed on your Windows? If so, can you do this while your VPN is active:

```
import netifaces
netifaces.gateways()

```

On my Linux
```
>>> import netifaces
>>> netifaces.gateways()
{'default': {2: ('192.168.1.254', 'wlo1')}, 2: [('192.168.1.254', 'wlo1', True)]}


```

**Comment by Obscurax** [comment]
> Thanks.
> 
> So: "OpenVPN", but Default Gateway is empty? Is that a Windows thing?

Seems so...


> @Obscurax
> 
> Do you have python3 installed on your Windows? If so, can you do this while your VPN is active:
> 
> ```
> import netifaces
> netifaces.gateways()
> ```
> 
> On my Linux
> 
> ```
> >>> import netifaces
> >>> netifaces.gateways()
> {'default': {2: ('192.168.1.254', 'wlo1')}, 2: [('192.168.1.254', 'wlo1', True)]}
> ```

Tried to install the netifaces module but building failed. Lacking time to troubleshoot will dig deeper later.
