### ISSUE TITLE
Series Sorter Season Pack Bug

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2578]
{%sn} (%y)/{%sn} (%y) - s%0se%0e.%ext
The series sorting works perfectly for individual episodes but on season packs with the above it creates a file name with the curly braces.

instead of `showname/showname - s01e01` it ends up as `showname/{ShowName} - s01e01` the filename still capitalized

only affects packs. running 4.0.1

**Comment by Safihre** [comment]
@jcfp You'll send a PR right? 😊

**Comment by thezoggy** [comment]
> Is this patch on 4.0.2? If so it's still present.

You'd prob want to check 4.0.3 or 4.1.0

**Comment by thezoggy** [comment]
> Didn't know 4.0.3 was out and this was closed and completed before 4.0.2 was released. But I've seen the release notes for 4.0.3 now, thanks.

yes, but pr got pulled into develop not 4.0.x before 4.0.2 was released. 
4.0.x didnt synced with dev until 4.0.3rc1 to pick up that change, changelog would confirm

the tl;dr;, you need to run 4.0.3 or latest nightly/dev (4.1.0-dev) to get it
