### ISSUE TITLE
Unable to edit Sorters

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2586]
Upgraded to 4.0.2 and for some odd reason I cannot edit the sorters. Have tested on different browsers and multiple machines.

**Comment by thezoggy** [comment]
i can confirm seeing the same, it wants to re-order the sorter when you click anywhere.. rather than just the drag icon

**Comment by thezoggy** [comment]
I see what happen, when i added support to stop doing the sorting on the pattern key (so you can actually highlight text) it replaced the previous cancel setting of not doing the sorting on `input,textarea,button,select,option` elements.  doh, let me submit a quick pr to fix that
