### ISSUE TITLE
0.8.x - tvsort errenous log

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#259]
I do not have tv sorting (or any sorting for that matter) enabled in sab, but i still see logs appearing:

```
F:\>curl "http://localhost:8092/api?mode=get_config&section=misc&keyword=enable_tv_sorting&output=json&apikey=cebf71d1cb1122e84faa3b3a0d77bd79"
{"config":{"misc":{"enable_tv_sorting":0}}}
```

sab log:
`2015-07-27 09:28:13,348::DEBUG::[tvsort:216] Found TV Show - Starting folder sort (Humans.S01E04.720p.WEB-DL.DD5.1.H.264-NTb)`

**Comment by shypike** [comment]
0.8.0 scans each incoming title for S01E01 or 1x01 constructions to enable "intelligent" duplicate checking. The logging is an side-effect of re-using TVSort functions.
Check your sabnzbd.ini file; do you have "no_series_dupes = 0". This is the default setting and it will analyze the titles.
I see now that this setting wasn't added to config_switches.tmpl, despite interface.py supporting it.

BTW: the naming is a bit odd.
"no_dupes" means "do not allow duplicates into the queue"
"no_series_dupes" means "do not allow duplicates season/episode" into the queue.
Both have an "off/pause/discard" pick list.

**Comment by thezoggy** [comment]
yes both those options are set to 0 in the config

**Comment by shypike** [comment]
Duh, the option is present in the Config skin, I was looking at the original Plush Config.
"Detect duplicate episodes in series"

**Comment by Safihre** [comment]
So what happend with this one? Does it still show?

**Comment by shypike** [comment]
There is no problem.
