### ISSUE TITLE
Hang during postprocessing due to DirectUnpacker not finishing.

### ISSUE THREAD

**Issue by SippieCup** [sabnzbd/sabnzbd#2593]
This bug stops from the rest of the history from being post-processed. Files will be fully downloaded, and verification will start, and it'll always hang on the final piece when Verifying.

Enabling Debug logs show whats is happening:

```2023-06-16 09:51:09,080::DEBUG::[newsunpack:535] DirectUnpacker still alive for XXXXXXXX: 37/37
2023-06-16 09:51:11,080::DEBUG::[newsunpack:535] DirectUnpacker still alive for XXXXXXXX: 37/37
2023-06-16 09:51:13,080::DEBUG::[newsunpack:535] DirectUnpacker still alive for XXXXXXXX: 37/37
```

This loops forever, the unpacking thread is _not_ running, but it seems that sabnzbd misses that notification.

When you delete the folder, it still does not work:

```2023-06-16 09:51:15,281::DEBUG::[filesystem:946] Removing dir recursively /mnt/nzbget/complete/_UNPACK_XXXXXXXX
2023-06-16 09:51:15,428::DEBUG::[newsunpack:535] DirectUnpacker still alive for XXXXXXXX: 0
```
this also continues every second indefinitely until the application is restarted. Once restarted, the job is removed and postprocessing starts back up again.

Full logs of the issue can be found here: https://gist.github.com/SippieCup/0b69eb9f021a0b26556beae6fd12746c

**Comment by Safihre** [comment]
Could you try 4.0.3Beta1?

**Comment by SippieCup** [comment]
Sure. I'll build it now and start re-running it. happens a few times a day for me, So i should be able to see it again quickly.

**Comment by SippieCup** [comment]
Everything seems to be working for me and I have yet to experience another hang on 4.0.3Beta1. @Slava46 are you saying that the files are getting deleted immediately after finishing? Sure they aren't getting picked up from something else?

**Comment by Safihre** [comment]
> Seems for 4.0.3Beta1 after fully download during Direct Unpack and complete job after that files fine completed just deleting ...

Sorry, what do you mean?

**Comment by Slava46** [comment]
> Sorry, what do you mean?

I mean what I wrote. In 4.0.3Beta1.
Start download with Direct Unpack. While downloading Direct Unpack working fine until complete download. Got message that all fine and complete but just after finishing unpacked files deleting. I checked it twice.

**Comment by Slava46** [comment]
> @Slava46 are you saying that the files are getting deleted immediately after finishing? Sure they aren't getting picked up from something else?

Yeah, files deleting immediately after finishing.

**Comment by Safihre** [comment]
Can you shares a Debug log of a download of the 100MB test job in the Status window? So first enable Debug mode there and click Show Logging after the download is finished and the files were deleted?

**Comment by Slava46** [comment]
> Can you shares a Debug log of a download of the 100MB test job in the Status window? So first enable Debug mode there and click Show Logging after the download is finished and the files were deleted?

Tested twice, it's the same. Sent debug file to safihre@sabnzbd.org

**Comment by Safihre** [comment]
Indeed something is wrong. It's aborting for some reason after it finished, resulting in deleting the final folder. Very strange.

**Comment by Safihre** [comment]
@Slava46 Could you try this build?
It might not fix the problem, but if you could send me a log maybe I can better understand it (I added additional logging).
https://github.com/sabnzbd/sabnzbd/actions/runs/5305553299

**Comment by Slava46** [comment]
> @Slava46 Could you try this build? It might not fix the problem, but if you could send me a log maybe I can better understand it (I added additional logging). https://github.com/sabnzbd/sabnzbd/actions/runs/5305553299

Tried this one, seems file not deleting now after finished. Sent to e-mail new debug.

**Comment by Safihre** [comment]
Great. I did see that I made a mistake in 4.0.3Beta1. In develop it was already fixed.
Let us know if you have any more problems related to Direct Unpack. Otherwise I can release in a few days a new version of 4.0.3.

**Comment by Safihre** [comment]
Closing as solved, since we got no new reports!
