### ISSUE TITLE
 Failed to connect: _ssl.c:985: The handshake operation timed out

### ISSUE THREAD

**Issue by angelgtc87** [sabnzbd/sabnzbd#2597]
I'm getting these errors throughout the day

Failed to connect: _ssl.c:985: The handshake operation timed out news.easynews.com:563 (85.12.62.230)
Failed to connect: _ssl.c:985: The handshake operation timed out news.newshosting.com:563 (85.12.62.225)

SABnzbd version: 4.0.3Beta1

**Comment by thezoggy** [comment]
You should reach out to newshosting/check local connection issues. Nothing to do with sab.

**Comment by angelgtc87** [comment]
@thezoggy NZBget has no issues, I don't think it's the newsservers since I can download just fine, and if it was an outage a bunch of people would have said something

this is now
<img width="1172" alt="Screenshot 2023-06-22 at 4 56 39 PM" src="https://github.com/sabnzbd/sabnzbd/assets/28854275/467c42f0-aeb2-46c9-be4c-4291ee7a42f9">

**Comment by Safihre** [comment]
This is a pretty low level connection error.
You could try increasing the timeout, that's all.
Like @thezoggy said, nothing SABnzbd can do about that.
