### ISSUE TITLE
Request - In app version update

### ISSUE THREAD

**Issue by water1309** [sabnzbd/sabnzbd#26]
Like Couchpotato and Sickbeard have.. When a new version is available, let it auto-update via the web interface...
Saves me a pain in the but logging in to my server every once in a while :)

**Comment by PhoenixYseven** [comment]
Would love to have an auto-update, especially with the new v1!

**Comment by albino1** [comment]
+1.

It's probably much easier now with Github and Glitter.

**Comment by Safihre** [comment]
Closing this as we cannot do this on Windows or macOS, where we have no permissions to write to the directories where SABnzbd is located in.
