### ISSUE TITLE
Feature Request: Blocking on "Download Add"

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2602]
Would it be possible to add a "download received" block?

Case: Sonarr [other clients are available] can add on new series add downloads in the form S01 S02 and the like and I've discovered no reliable way to block them and they do not extract as a full series either.

Example, this screen shot: https://shottr.cc/s/Jpkq/SCR-20230626-jjqp.png

It would be thus desirable if it could be user-selectable to block clear S01 S02 S03 and the like rather than the user fiddling with syntax that would block S01 E01 in a title of a legitimate download. The programmers are going to be better coders than the average user and it is likely that these S01 etc are in many cases appearing before a resolution, such as the example above, so a combination of S[numeric] and then resolution might be a likely target.

It can be an "edge case" but a welcome one as it does affect a lot of situations when adding through Sonarr.

**Comment by thezoggy** [comment]
Indeed you can favor or not favor season packs in sonarr. Trash guides also has examples.of how to do so
