### ISSUE TITLE
Feature Request: Multiple Selection in "Completed"

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2603]
Could a "multiple selector" be added in completed history?

User-case, occasionally I have had the case where I've downloaded something in error and before it processed [big queue] I've realised and could stop this and delete it. In a big queue it would save a few strokes if I could multi-select and delete.

Such already exists to the primary queue, so it feels a no-brainer to offer such a facility to the "completed" history queue.

**Comment by Safihre** [comment]
Indeed, a workaround for now could be to muse the search function to only show the relevant items and then use the 'Delete all items on current page' option.

**Comment by ricci2511** [comment]
I just recently thought about this too. I'll give this a shot even though I've never used jquery, but using the queue's multiselect should be enough guidance to implement this.
