### ISSUE TITLE
0.8.x - dropping python 2.5 support

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#261]
just to confirm that 0.8.x will **NOT** support python 2.5 correct?

* id really love to drop 2.5.. i keep running into coding stuff where 2.5 holds back better solutions

to do python 2.5 you have to do a mixture of urllib/urllib2/httplib2 to get some things done.. its crap and buggy as hell. python 2.5 also does not have ssl or json.. means your stuck including libs and can introduce bugs that only affect 2.5 users... thus you spend wasted time to deal with the bugs via hacks.

python 2.5, 201's come back as a urllib2.URLError (which is wrong)
ex: http://stackoverflow.com/questions/7032890/why-does-pythons-urllib2-urlopen-raise-an-httperror-for-successful-status-cod

python 2.5 xml parser is pretty slow and crap.. mindom is just bad. etree while better still a bit lacking.. no xpath and a bit buggy (try grabbing `newznab:attr` sometime in a nzb and you will see).

python 2.6+ allows to set timeouts for calls instead of using a global timeout. which really makes sense for things like notifications where they are less important and you dont want it stalling other things that do matter.

python 2.6+ allows the use of .format() for strings.. 

most libs nowdays have just dropped 2.5 or 2.5 didnt have support.. I ran into this on twitter libs or things that use oauth. 

--

use beautifulsoup instead of minidom/etree (you can even have bs4 use lxml as its internal parser for the best performance)

 > http://www.crummy.com/software/BeautifulSoup/

use requests instead off urllib/urllib2/httplib2

 > http://docs.python-requests.org/en/latest/

**Comment by thezoggy** [comment]
to note why i bring this up, i see in the sab helper its check is for 2.5+.
https://github.com/sabnzbd/sabnzbd/blob/develop/SABHelper.py#L19

**Comment by shypike** [comment]
0.8.0 refuses to run on Python 2.5: check in SABnzbd.py
I overlooked SABHelper, which technically can run on 2.5, because it doesn't do very much.
I'll change that too.

**Comment by thezoggy** [comment]
i figured as much as i did already see the sabnzbd.py, why i just mention the sabhelper. just wanted to confirm before i submitted any code changes that did not support 2.5 (didnt want to waste my or your time)

**Comment by shypike** [comment]
Also dropped the separate json library, now using the built-in json support.
