### ISSUE TITLE
Switching to par2cmdline-turbo

### ISSUE THREAD

**Issue by Tristar7** [sabnzbd/sabnzbd#2613]
Currently the fastest par2 verify/repair tool

https://github.com/animetosho/par2cmdline-turbo

**Comment by Safihre** [comment]
I think you are not asking this in the right place. We don't include par2cmdline, only for macOS but I doubt that's the OS you are on.
It's the package manager for the OS you are on that determines which one to use.
We could ask @jcfp if he could update the Ubuntu repo to use this one?
Or I could use it for Synology package.
I could use it for snapcraft but I hate snapcraft so don't want to do that.
Maybe @francoism90 wants to use it for the flatpack?

**Comment by francoism90** [comment]
@Safihre I would like to stay as close as possible to the SABnzbd defaults. Yeah, the lib versions may differ, but in most cases it's the same as building it from source.

**Comment by thezoggy** [comment]
the solution for linux has just to use docker mod to load par2cmdline-turbo   instead of normal one.

i have a branch for par2cmdline-turbo for mac/win i just havent gotten around to tossing pr to add it upstream as I had been working with animetosho to work out the kinks last few months for mac (mainly arm stuff). but its been good for a bit.

my plan is to depref multipar and just have us use par2cmdline-turbo across the board (mac/win) with included binaries. also works for win arm but not going to include that one for now

**Comment by Tristar7** [comment]
> I think you are not asking this in the right place. We don't include par2cmdline.. It's the package manager for the OS you are on that determines which one to use.

ok... such an answer seriously confuses me.

I'm on win, and **you are including multipar there**.

I'm saying to throw that snail out and replace it with par2cmdline-turbo instead.

I'd expect command-line parameters to be different so it would require some changes on Sab's side, but if not I'll just switch it myself..

**Comment by Safihre** [comment]
You even want to replace Multipar? I guess that's possible indeed.
I didn't see that it's even faster than Multipar nowadays.
@thezoggy you want to do this or want me to do it?

**Comment by Tristar7** [comment]
Multipar could stay as an option, but I see no point in keeping it.

Turbo is overall twice as fast / needs half the time in some benches, so it should become the default, or at least a choice to switch to.

**Comment by thezoggy** [comment]
> You even want to replace Multipar? I guess that's possible indeed. I didn't see that it's even faster than Multipar nowadays. @thezoggy you want to do this or want me to do it?

either or, ive been dragging my feet on if i wanted to offer option to prefer one or the other (incase we wanted fallback) but means we have to bloat having multiple binaries. it would be a lot cleaner to just rip it out.

**Comment by Safihre** [comment]
Having played with this, the major drawback is that the file handling is still using the original par2cmdline which sucks at unicode filenames. Multipar handles that without problems on Windows.

**Comment by Safihre** [comment]
@thezoggy maybe you can submit that PR? If you already made the changes.
Then we can see what CI does with it.

**Comment by thezoggy** [comment]
> @thezoggy maybe you can submit that PR? If you already made the changes.
> Then we can see what CI does with it.

Gonna be a bit, on holiday for next few weeks on a cruise

**Comment by Safihre** [comment]
@thezoggy Ping!

**Comment by thezoggy** [comment]
hadnt forgotten, just have to redo a bit of stuff since its gone stale (par2cmdline-turbo has static builds now), should have some time to work on this weekend with it

**Comment by Safihre** [comment]
I already added it for macOS, but for Windows will be more interesting how it fairs.

**Comment by Safihre** [comment]
@jcfp any chance of adding it to the PPA?

**Comment by Safihre** [comment]
We should re-write: https://sabnzbd.org/wiki/installation/multicore-par2

I also opened an issue for the linuxserver.io Docker to start using it linuxserver/docker-sabnzbd/issues/204

**Comment by francoism90** [comment]
I'm also tracking this; if I understand correctly, users can install both par2cmdline and par2cmdline-turbo, as they don't conflict each other?

Or do they use the same path?

**Comment by thezoggy** [comment]
It's a fork, so a replacement. If using lsio docker use their  dockermod to load it. If running ppa/package manager just install it.

**Comment by Crowley007** [comment]
This interesting. I installed sab from the source on ubuntu, if I install par2-turbo from the link above, do I need to do anything else for this to work?

**Comment by thezoggy** [comment]
> This interesting. I installed sab from the source on ubuntu, if I install par2-turbo from the link above, do I need to do anything else for this to work?

nope

**Comment by Crowley007** [comment]
Ok thanks, I'll give it try.

**Comment by Crowley007** [comment]
Something strange happening with this, not sure if it's just a UI bug:

<img width="638" alt="sab" src="https://github.com/sabnzbd/sabnzbd/assets/23026322/0597065f-505e-4a42-b669-ce364dcd601b">
<img width="509" alt="multipar" src="https://github.com/sabnzbd/sabnzbd/assets/23026322/14871e61-3d98-41cc-bdc3-15c5198e9824">

**Comment by Crowley007** [comment]
Looks that way yeah. It seems to work just fine though.

**Comment by Safihre** [comment]
@Crowley007 if you pull the last commit it will be fixed.

**Comment by Crowley007** [comment]
Will do, thanks

**Comment by sanderjo** [comment]
> We should re-write: https://sabnzbd.org/wiki/installation/multicore-par2

So: Change the paragraph "Installation on Ubuntu via PPA", and mention -turbo in the introduction?
If yes, then I can do that.

Or complete overhaul of that page?

**Comment by thezoggy** [comment]
the whole page really needs to be decom as its so much legacy stuff, theres really no reason for people to use the defunct par-tbb/old -mt forks. even the generic par2cmdline is multicore, and par2cmdline-turbo being the optimized version across all the platforms and in most modern package managers now.. dont think we really need a special page anymore.

**Comment by francoism90** [comment]
Another question; is it possible to compile this package into another path, and include both par2cmdline implementations?

**Comment by Safihre** [comment]
I already created a new page specifically for turbo, that's the one that's linked from the notice in the wiki.

**Comment by thezoggy** [comment]
> I already created a new page specifically for turbo, that's the one that's linked from the notice in the wiki.

had to go look at repo to find your page,
https://sabnzbd.org/wiki/installation/par2cmdline-turbo

I do not see your new paged linked anywhere, the old page still linked on
https://sabnzbd.org/wiki/installation/install-off-modules

was it supposed to just be re-directed?


and to note for anyone that stumbles across here:
archlinux - https://aur.archlinux.org/packages/par2cmdline-turbo

**Comment by Safihre** [comment]
It's linked (just like the old page) on the first page of the Config if you don't have turbo installed. The main place people could be made aware of it.

**Comment by Safihre** [comment]
> Another question; is it possible to compile this package into another path, and include both par2cmdline implementations?

No, we only detect 1.

**Comment by Safihre** [comment]
With the [utf8 patch](https://github.com/animetosho/par2cmdline-turbo/pull/36), we finally switched for Windows!
