### ISSUE TITLE
0.8.x - connection interrupted on startup

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#262]
just putting this here in case others see similar thing...  I've seen this happen a few times today and so far the trigger appears to be when i start my dev 0.8.x instance.. and its internment.

windows 7 pro x64 (windows firewall is off) , python 2.7.5

when i start 0.8.x via command line via:
`sabnzbd_0.8.x>python SABnzbd.py -f D:\test --new`

I see mirc connection get reset... throws the message:
`[10053] Software caused connection abort` now this is a generic winsock error...

**Comment by shypike** [comment]
Never seen it.
I'm experimenting with Python 2.7.10 for Windows based on the python.org distro instead of ActiveState. I've had a few hard crashes. I suspect the OpenSSL libraries.

**Comment by Safihre** [comment]
@thezoggy did you ever see this again? I had some weird Wifi-crashes before where SAB-start or download-start would disconnect my Wifi, but that is fixed now I'm on Win10.

**Comment by thezoggy** [comment]
the kicker on pyopenssl is that most of the stuff provided out there is only for 32bit python not 64bit.. you have to jump through some hurdles to get it to work..

of all of its dep `pip install cffi-1.3.1-cp27-none-win_amd64.whl --upgrade` was the ultimate solution to get it sorted.
