### ISSUE TITLE
Feature Request: Support status of "Unpacking" even if Download "Paused" but is unpacking

### ISSUE THREAD

**Issue by war59312** [sabnzbd/sabnzbd#2622]
Hi,

Noticed when a download finished, my browser tab was showing "Paused".

Quickly then realized its real state is "Unpacking".

Be nice if the tab was titled correctly "Unpacking" when indeed a download is "Unpacking".

Thanks,

Will

**Comment by thezoggy** [comment]
do you have the sab option checked? 
config > switches > Post processing - Pause Downloading During Post-Processing

**Comment by war59312** [comment]
Yes, that setting is enabled.

Glad it's respecting the setting. That's good.

But still, either way, the title of the tab should reflect real status.

**Comment by Safihre** [comment]
There is no queue-level status of _Unpacking_, it's just _Paused_ because that setting is turned on.

**Comment by war59312** [comment]
Bad bot.

**Comment by Safihre** [comment]
At this time it's not something we want to implement.
