### ISSUE TITLE
FR: Increased duplicate detection/manual report option

### ISSUE THREAD

**Issue by DarrenPIngram** [sabnzbd/sabnzbd#2624]
Would there be scope for increased duplicate detection on waiting downloads, even if it is a manual report with the option THEN for the user to select items to delete with a dialogue (select) and then bulk delete? Even better, if so [maybe another option] to then pre-select ALL but one option for deletion :) but maybe no-one wants that risk?!]

Sometimes, for whatever reason, perhaps due to automation and multiple sources, multiple items of a very similar item can be entered into the queue, and often it is not noticed when there is a lot pending...

Even a report if ran by the user might detect things that otherwise are harder to detect when the queue can be spread over tens or much larger pages without a lot of work which is not always so friendly with less than stellar vision.

I don't pretend to know how simple it would be to program it, but if the item(s) in the queue could be examined, even in the context of a manual report, maybe up to to the presence of some (selectable?) often constants, such as a S [for series) number, e.g. Sx as in S01 S02 etc [I'm sure the programmers can figure out that element], especially since the user has to make the judgement call over possible deletion anyway and then present the _possible duplications together in context_ and select which, if any, to delete there is no real risk, just a possible upside.

_Title of the Item S0
Title of the Item being Downloaded S01
This Is the Item In Question S01

and so on might catch 90+% of items and this is going to be a "life saver"_

Sometimes the duplicate detection picks it up, but often I've deleted the history and by then it can have downloaded a copy again and again [a lot can happen in a very busy download session when automation keeps picking up things].

One example from a multi tb queue https://shottr.cc/s/JRST/SCR-20230718-fg8p.png

So if the idea had searched up to Sx it would have highlighted the examples in the report and I could have opted to delete manually all but one of those files in the queue. I wouldn't have expected necessarily the existing download detection to have picked it up as the nzb could have came from different indexers and theoretically been slightly different [not checked, since I had picked it up and deleted before it came to that].

**Comment by Safihre** [comment]
I agree, we have wanted this for years: #727.
Just never gotten around to implement it.

**Comment by Safihre** [comment]
Closing this as it's part of #727. Not forgotten, but nobody dared to spend time on it yet.
