### ISSUE TITLE
bluray structure - not able to extract

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2626]
windows 11 and 4.0.3 [9fafe64]

user shared issue he found with sab via discord
>  made an nzb by parring the parent folder of BDMV and letting sab reconstruct the folder structure and sab did manage to get the the folder structure reconstructed but it throws some errors

issues on windows:
![discord1](https://cdn.discordapp.com/attachments/976737548019830786/1131306293580267711/WINDOWS.png)

worked on linux:
![discord2](https://cdn.discordapp.com/attachments/976737548019830786/1131306308071596133/image.png)

no sorting enabled. had him retry on windows + debug logs:
https://privatebin.net/?4141411598639c0d#13VAKzfNVVXKMGXLURgB17yRaKftPMMRZK1o2PtwP7EU

**Comment by Ravencentric** [comment]
[Uploading Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1.zip…]()

**Comment by Ravencentric** [comment]
[Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1.zip](https://github.com/sabnzbd/sabnzbd/files/12113357/Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1.zip)

**Comment by Safihre** [comment]
I don't think we support multiple levels within par2, only 1 sub-directory.
What an exotic way to do things..

**Comment by sanderjo** [comment]
FWIW:

```
2023-07-20 19:32:08,788::INFO::[notifier:123] Sending notification: Error - Failed making (D:\data\usenet\incomplete\Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1\BDMV/STREAM) (type=error, job_cat=None)
2023-07-20 19:32:08,781::ERROR::[filesystem:733] Failed making (D:\data\usenet\incomplete\Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1\BDMV/STREAM)
Traceback (most recent call last):
  File "sabnzbd\filesystem.py", line 716, in create_all_dirs
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\D:\\data\\usenet\\incomplete\\Liz.and.the.Blue.Bird.2018.1080p.US.Bluray.AVC.DTS-HDMA.5.1\\BDMV/STREAM'
```

... forward slash as in `BDMV/STREAM` is not allowed on NTFS

**Comment by Ravencentric** [comment]
nzb was made on linux, probably why the path is using forward slash

**Comment by mnightingale** [comment]
I think that is "a" issue and the par2 rename, I believe par2 spec is always forward slashes for directory seperators, so there should be something sanitising them to the current platform.

But it's not going to succeed with a par2 based rename anyway `[par2file:245] Par2-16k signature of CERTIFICATE/BACKUP/id.bdmv not unique, discarding` (several)

Can an NZB support path seperators in the subject and if not should it?
Then it wouldn't have to rely on par2 to rename.

**Comment by Safihre** [comment]
The notice about `Par2-16k` doesn't matter for the final restore, but only _if_ the files are not actually identical.
Otherwise we, or any par2 software, cannot know where the files need to go. We only have the hashes to go on.

> Can an NZB support path seperators in the subject and/or if SAB doesn't should it? Then it wouldn't have to rely on par2 to rename.

Not allowed by SABnzbd, and as far as I know no other downloader supports it. 
Because: why? What's the problem with just using trusty old rar files for these complicated multi-directory cases?

**Comment by mnightingale** [comment]
> Not allowed by SABnzbd, and as far as I know no other downloader supports it. Because: why? What's the problem with just using trusty old rar files for these complicated multi-directory cases?

@animetosho makes a better argument for it on https://github.com/animetosho/Nyuu/wiki/Stop-RAR-Uploads
Basically with RARs every download ends up as write (temp), read (rar), write (extract), it's just a bit wasteful of requires more disk space.

I'm not sure if it should be supported, catch-22 if no client supports it RARing will continue, but if only one client supported it then it probably wouldn't be used anyway.

**Comment by Ravencentric** [comment]
Sab is probably one of the first choice downloaders for people now, I'm hoping if Sab supports it, others will follow

**Comment by Safihre** [comment]
Alright, but if the files have identical hashes par2 can't fix the directory tree..
Only solution would be if we allow it as part of the filename in the NZB. However, those are often so misformed that I'm not sure if we also wouldn't be creating crap..

**Comment by animetosho** [comment]
Subject formats are somewhat messy (and not standardised anyway), so not trying to interpret paths there seems fair. But the *name* field in the yEnc header seems like fair game (and should be more reliable than subject/NZB parsing).  
(I wish the yEnc and NZB spec would get updated with clarifications on matters like these; also the NZB spec is particularly bad)

The PAR2 spec permits subdirectories (delimited by `/` in the file name), so programs not handling them when dealing with PAR2s would arguably not be spec compliant.

**Comment by Safihre** [comment]
> The PAR2 spec permits subdirectories (delimited by `/` in the file name), so programs not handling them when dealing with PAR2s would arguably not be spec compliant.

Agreed, this is indeed a bug on Windows.
We just simply need to convert the slashes. Which can be done using `os.path.normpath("BDMV/STREAM")`.

**Comment by Safihre** [comment]
I tried the NZB and with this patch it works.
Nice.

**Comment by Safihre** [comment]
You can download the patched binary here in a few minutes:
https://github.com/sabnzbd/sabnzbd/actions/runs/5622410844
