### ISSUE TITLE
0.8.x - python code style guideline (pep8)

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#263]
while I agree with most things of pep8 there are a few things that I dont..  if you recall awhile back I started to do a code style passes on develop ( https://github.com/sabnzbd/sabnzbd/pull/176 ) but later backed out because there were a few things I was being aggressive on (non whitespace changes / making pydev happy) and we needed to talk about them before I moved forward.

@shypike one thing I did notice is that you seem to like putting a space before your colons in a dict most of the time.. curious if that is something that your are doing on purpose or are opposed to changing?

your way:
```
    'de-de' : 'de',
    'dk-da' : 'da', # Should have been "da-dk"
```

pep8 way (no space before colon):
```
    'de-de': 'de',
    'dk-da': 'da', # Should have been "da-dk"
```

also not sure what IDE you use anymore (still wingware? I ended up moving to liclipse awhile back and have been very happy), but most allow collapse or jump to a def/class/etc and colorize them to stand out.. 

@shypike when I see commented lines like these (below) above def statements, it makes me think they are just legacy placeholders.. you opposed to me removing them?
```
#------------------------------------------------------------------------------
def HandleCommandLine(allow_service=True):
    """ Handle command line for a Windows Service
        Prescribed name that will be called by Py2Exe.
        You MUST set 'cmdline_style':'custom' in the package.py!
    """
    win32serviceutil.HandleCommandLine(SABHelper)
```
or
```
################################################################################
# Signal Handler                                                               #
################################################################################
def sig_handler(signum = None, frame = None):
    global SABSTOP, WINTRAY
    if sabnzbd.WIN32 and type(signum) != type(None) and DAEMON and signum==5:
```

**Comment by shypike** [comment]
I must have taken over the dict/colon notation from the original code.
I try to stick to PEP8, but I wasn't aware of this.
Still using WingWare.

The HandleCommandLine comment is still valid and all too true, especially the last line.

The blocked comment is outdated yes, although I like to put some singe-line bars at strategic places.

**Comment by thezoggy** [comment]
the docstring isnt what im talking about... its the:
`#------------------------------------------------------------------------------`
and
```
################################################################################
# Signal Handler                                                               #
################################################################################
```

**Comment by shypike** [comment]
Alright.
I still like some properly placed lines, like the top one, to indicate sections.
The "Signal Handler" block can be removed.

**Comment by thezoggy** [comment]
@shypike so in sabhelper for example, you want to keep things like:
https://github.com/sabnzbd/sabnzbd/blob/develop/SABHelper.py#L38

but are okay on removing things like:
https://github.com/sabnzbd/sabnzbd/blob/develop/SABHelper.py#L99-L102

**Comment by shypike** [comment]
Yes.

**Comment by thezoggy** [comment]
ok, so pep8 wants to put blank lines above the def... thus blank lines would be before the dash-lines... you okay with that? (if not, I'll just try and find the code that causes that fix and disable it.. which is fine as I've disabled other stuff because some of it causes more grief and noise than its worth)

```
         return ''

 #------------------------------------------------------------------------------
+
+
 def fix_webname(name):
     if name:
         name = deunicode(name)
@@ -405,6 +425,8 @@
         return name

 #------------------------------------------------------------------------------
+
+
 def GetProfileInfo(vista_plus):
     """ Get the default data locations
     """
@@ -511,12 +533,14 @@
```

**Comment by shypike** [comment]
> thus blank lines would be before the dash-lines... you okay with that? 

Please do.

**Comment by thezoggy** [comment]
hmm so noticing a bit of inconsistency..  some def have the marker line and some dont... will have to do another pass to go back and manually add them I suppose.. 

```
#------------------------------------------------------------------------------
def all_localhosts():
    """ Return all unique values of localhost in order of preference """
    ips = ['127.0.0.1']
    try:
        # Check whether IPv6 is available and enabled
        info = socket.getaddrinfo('::1', None)
        af, socktype, proto, canonname, sa = info[0]
        s = socket.socket(af, socktype, proto)
        s.close()
    except socket.error:
        return ips
    try:
        info = socket.getaddrinfo('localhost', None)
    except:
        # localhost does not resolve
        return ips
    ips = []
    for item in info:
        item = item[4][0]
        if item not in ips:
            ips.append(item)
    return ips


def check_resolve(host):
    """ Return True if 'host' resolves
    """
    try:
        info = socket.getaddrinfo(host, None)
    except:
        # Does not resolve
        return False
    return True


#------------------------------------------------------------------------------
def get_webhost(cherryhost, cherryport, https_port):
    """ Determine the webhost address and port,
        return (host, port, browserhost)
    """
    if cherryhost == '0.0.0.0' and not check_resolve('127.0.0.1'):
        cherryhost = ''
    elif cherryhost == '::' and not check_resolve('::1'):
```

**Comment by thezoggy** [comment]
just for future reference, what I'm doing:
> autopep8 --ignore E501,E127,E128,E402 -d SABnzbd.py

**Comment by shypike** [comment]
Hmm, automated.
I am still a bit wary of massive changes, which make it hard to get a grip on the history.
Especially the "blame" tool is effectively stopped short by changes that hit a large number of lines.

**Comment by thezoggy** [comment]
by default autopep8 does not make any agressive changes (nothing that could cause any issues, only whitespace minor stuff), you can make it do agressive (different levels, but even then I would still review stuff and discard checks that I am not comfortable with). Also using a script is probably safer than a person manually fixing stuff.. which can introduce issues...  but anyways check out (dont pull just yet):

https://github.com/sabnzbd/sabnzbd/compare/develop...thezoggy:develop--minor2
