### ISSUE TITLE
password in exported log file 

### ISSUE THREAD

**Issue by CMTriX** [sabnzbd/sabnzbd#2630]
When exporting the log file, i see the password for login is printed, it is not hidden

2023-07-25 16:13:37,808::DEBUG::[interface:143] Request POST /login/ from 127.0.0.1 [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0] {'username': 'admin', 'password': '1111111', 'remember_me': '1'}

**Comment by CMTriX** [comment]
> Yes. And what's the risk in that?

on top of the exported log file"

_**The log includes a copy of your sabnzbd.ini with
all usernames, passwords and API-keys removed.**_

**Comment by thezoggy** [comment]
what is 'exporting' the log? we do not sanitized the log file we store on disk. 
we only sanitized the log when using the `show logging` button to cleanse it

**Comment by Safihre** [comment]
@CMTriX was right, the password was not removed when clicking `Show Logging`.

I cleaned up the code a bit and found that also usernames and passwords with a space in them would not be removed fully. So fix that also.
