### ISSUE TITLE
Request for new UI options to purge logs

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2633]
This is a request for new UI options to purge logs, instead of having to shutdown sab, drill down to the sab log folder, erase logs and start sab again.

**Comment by Safihre** [comment]
Could you give a use case why one would do this?

**Comment by Cpuroast** [comment]
For troubleshooting and possibly submitting logs, hit purge logs from the UI, do something, download logs from UI.
Instead of having to shutdown sab, dig to the log folder, erase logs, start sab, do something, download logs from UI.

**Comment by Safihre** [comment]
Closed by df23bf21eabf5338bb9f08f8bf53c63be5ee4ce6
