### ISSUE TITLE
Feature request: Open downloaded folder from Windows system tray Toast message

### ISSUE THREAD

**Issue by zaadstra** [sabnzbd/sabnzbd#2641]
When a download job is finished, on Windows a Toast message pops up from the system tray: "Download completed".
It would be nice if a click on the message is passed back to sabnzbd, and it opens the folder containing that download.
On the toast message "Queue finished" the default Completed Download Folder could be opened.

**Comment by Safihre** [comment]
Of course, but unfortunately the 'click' event doesn't contain which popup was clicked. So when multiple popups are fired, we don't know what to do. There's no way around that with the current Windows APIs that we are using. 
Maybe somebody already made a Windows 10 Notification Center python implementation. It wasn't the case 2 years ago when I last checked.

**Comment by zaadstra** [comment]
I am not into programming in Windows this deep,  but I found a [page](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp) on this topic, and this passage gives me some hope:

"When the user clicks your notification (or a button on the notification with foreground activation), your app's App.xaml.cs OnActivated will be invoked, **and the arguments you added will be returned**."

This page is for C## but I suspect the system works the same when called from Python?
Also, here is some package used "NuGet" but still the Windows API has to provide the response.
Another [page](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-other-apps) is using a different approach, if I understand correctly what they are writing then the answer comes via a COM activator. 
I hope this gives some ideas :-)

**Comment by Safihre** [comment]
https://gist.github.com/MarcAlx/443358d5e7167864679ffa1b7d51cd06

This is what I need I think!

**Comment by thezoggy** [comment]
> https://gist.github.com/MarcAlx/443358d5e7167864679ffa1b7d51cd06
> 
> This is what I need I think!

not sure if it matters, but looks like win10+ only.

**Comment by zaadstra** [comment]
Maybe because versions before W10 do not have toasts?  But the older "comic text balloon" popup from the tray?

**Comment by Safihre** [comment]
Yes that's true, but I'm fine with that. We only barely support anything older than Win 10.

**Comment by zaadstra** [comment]
Well stuff like a NAS doesn't have popups either :-)

**Comment by Safihre** [comment]
Sadly the Windows 10/11 toast packages that are actively maintained actually use the `winsdk` Python package, but that's a 12MB binary package. If I include that it would bump the file size of SABnzbd Windows binaries by the same amount 😢 
No solution for now, but I'll keep this open as a future request.

**Comment by zaadstra** [comment]
Ouch that's quite a lot indeed.

I thought of a variant, a click on the toast always opens the browser tab with the download list and history, and the history lines have a small folder icon (or click on the name) opens the corresponding download folder.  The item on the toast will be at the top of the history list (or nearby).

Thanks for investigating on the possibility, and it's not a bug, just a nice to have :-)

**Comment by Safihre** [comment]
Seems there is the option to create a lightweight fork! 
https://github.com/pywinrt/python-winsdk/issues/1#issuecomment-1672022839

**Comment by libantheworld** [comment]
Is there a similar feature request for macos? I dont want to make a duplicate issue just in case.

**Comment by Safihre** [comment]
@libantheworld there is none yet.
Could you describe what kind of actions you want and examples of notifications of other applications that have such notifications? I'm not a Mac user so it's not obvious to me.

**Comment by libantheworld** [comment]
@Safihre The feature I'm talking about is pretty identical to what OP is describing, i.e. when the nzb download is completed and the notification pops up when a user clicks on it should open the complete folder (or straight to the download items content folder if possible). I hope that makes sense. Thanks.

**Comment by Safihre** [comment]
@zaadstra I implemented it. It was actually much easier than expected because somebody [already did all the hard work](https://github.com/DatGuy1/Windows-Toasts)!

You can download the updated release here:
https://github.com/sabnzbd/sabnzbd/actions/runs/7196268889

Only if you run the installer will it add a nice icon and title to the notification (needs registry keys), otherwise it will probably show as `SABnzbd.exe`.

@libantheworld I think I will create a separate feature request for the macOS notification changes, it indeed must also be possible there.

**Comment by Safihre** [comment]
So it works as you described, if you click on any of the notifications it will open a browser window. For the `Job finished` there will be a button to open the folder of the job. For the `Queue finished` it will have a button to open the `Complete folder`.

**Comment by libantheworld** [comment]
@Safihre Thanks for all your work. 🙏

**Comment by zaadstra** [comment]
Wow cool! Thanks guys!  I will testdrive this very soon! :-)

**Comment by zaadstra** [comment]
How nice, it works perfectly!  Thanks @Safihre !
