### ISSUE TITLE
Filename truncated when source contains square bracket

### ISSUE THREAD

**Issue by JSS3M3** [sabnzbd/sabnzbd#2649]
Example filename: XXX.YYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost

Download succeeds but ends up in the path "C:\Downloads\complete\TV\XXX.YYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost\eztv.1.re"

Windows doesn't recognize it as an .MKV file and it is not moved into the "C:\Downloads\complete\TV\XXX YYY\Season 2" folder.

Problem seems to be connected with series sorting. Series Sorting is enabled and set to: "%sn/%sn - S%0sE%0e - %en.%ext"

In the debug log, the filename appears to be truncated in the Incomplete folder right after download completes. e.g.

```
2023-08-06 13:07:25,291::DEBUG::[deobfuscate_filenames:112] Checking: <HASH><HASH>4e5392b1b7a77f
2023-08-06 13:07:25,291::DEBUG::[deobfuscate_filenames:124] Obfuscated: starting with 40+ lower case hex digits and/or dots
2023-08-06 13:07:25,292::DEBUG::[nzbstuff:1902] Saving attributes {'cat': 'tv', 'pp': 3, 'script': 'None', 'priority': 0, 'final_name': 'XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost', 'password': None, 'url': None} for XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost
2023-08-06 13:07:25,293::DEBUG::[assembler:79] Decoding part of \\?\C:\Downloads\incomplete\XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost\eztv.re
2023-08-06 13:07:25,293::DEBUG::[filesystem:1119] [sabnzbd\nzbstuff.py.save_to_disk] Saving data for SABnzbd_nzo_9v7es620 in \\?\C:\Downloads\incomplete\XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost\__ADMIN__
2023-08-06 13:07:25,344::INFO::[assembler:87] Decoding finished \\?\C:\Downloads\incomplete\XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost\eztv.re
2023-08-06 13:07:25,365::DEBUG::[nzbstuff:453] Removing article database for SABnzbd_nzf_v3_7rd1a
2023-08-06 13:07:25,365::DEBUG::[filesystem:913] [sabnzbd\nzbstuff.py.remove_admin] Deleting file \\?\C:\Downloads\incomplete\XXXX.YYYYY.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost\__ADMIN__\SABnzbd_nzf_v3_7rd1a
```

The problem does not occur with all NZBs with square brackets in the file name e.g. https://raw.githubusercontent.com/sanderjo/NZBs/master/RefTestNZB_1234_Brackets%5Bfake.re%5DMoreMore.nzb works ok - the resulting filename is "C:\Downloads\complete\RefTestNZB_1234_Brackets[fake.re]MoreMore\MyRandomFile_100MB[fake.re]MoreMore.bin"

Sample NZB attached.

[Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-xpost.nzb.txt](https://github.com/sabnzbd/sabnzbd/files/12287355/Dark.Winds.S02E01.1080p.WEB.h264-EDITH.eztv.re.mkv-xpost.nzb.txt)

See discussion at https://forums.sabnzbd.org/viewtopic.php?t=26313

**Comment by sanderjo** [comment]
With Sorting set to the default value of `%sn/%sn - S%0sE%0e - %en.%ext` (same as @JSS3M3 , right?), I do get something else:

```
-rw-rw-r--  1 sander sander 2990558544 aug  8 07:41 'Dark Winds - S02E01 -.re'
-rw-rw-r--  1 sander sander         12 aug  8 07:37  eztv.re
```


Without Sorting, with Deobfuscate, I get:

```
-rw-rw-r--  1 sander sander 2990558544 aug  8 07:46 Dark.Winds.S02E01.1080p.WEB.h264-EDITH.eztv.re.mkv-xpost.mkv
-rw-rw-r--  1 sander sander         12 aug  8 07:43 eztv.re.txt
```

Without Sorting, without Deobfuscate, I get:

```
-rw-rw-r--  1 sander sander 2990558544 aug  8 07:52 eztv.1.re
-rw-rw-r--  1 sander sander         12 aug  8 07:50 eztv.re
```

That big file is a mkv file, but named wrong by the uploader (spoiler: no)?

Just downloading, no unpacking, no Sorting, no Deobfuscate, I get:

```
-rw-rw-r--  1 sander sander 2990558544 aug  8 08:00 eztv.1.re
-rw-rw-r--  1 sander sander         12 aug  8 07:58 eztv.re
```



While in the Queue, the contentst as presented by SAB:

```
100% eztv.re(10d - 0.00 MB)
50% eztv.1.re(10d - 2942.91 MB)
```

So: no rars, and weird naming.

However, the .NZB tells it has real names in subject:

```
$ cat ~/Downloads/Dark.Winds.S02E01.1080p.WEB.h264-EDITH.eztv.re.mkv-xpost.nzb  | grep subject
<file poster="WtF[NZB] &lt;freestuff@for.all&gt;" date="1690606180" subject="[N3wZ] \d8b2lG104035\::[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/WtF[nZb].nfo]-[2/2] - &quot;&quot; yEnc  12 (1/1)">
<file poster="WtF[NZB] &lt;freestuff@for.all&gt;" date="1690606101" subject="[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv]-[1/2] - &quot;&quot; yEnc  2990558544 (1/4173)">
```

Only the subject:

```
$ cat ~/Downloads/Dark.Winds.S02E01.1080p.WEB.h264-EDITH.eztv.re.mkv-xpost.nzb  | grep subject | cut -c69-
subject="[N3wZ] \d8b2lG104035\::[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/WtF[nZb].nfo]-[2/2] - &quot;&quot; yEnc  12 (1/1)">
subject="[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv]-[1/2] - &quot;&quot; yEnc  2990558544 (1/4173)">
```

**So I think: on the parsing of the .NZB itself into the Queue, SAB rewrites those subjects to eztv.re and eztv.1.re (the last one to avoid double names?).

But why?** Maybe SAB picks the part `[eztv.re]` as the subject name ... ?

**Comment by sanderjo** [comment]
The problem is in the subjects in the .NZB and/or SAB's parsing of the subjects. Proof: when I rewrite the subject to

```
$ cat Dark6.Winds.S02E01.1080p.WEB.h264-EDITH.eztv.re.mkv-xpost.nzb | grep subject
<file poster="WtF[NZB] &lt;freestuff@for.all&gt;" date="1690606180" subject="thetext.txt - &quot;&quot; yEnc  12 (1/1)">
<file poster="WtF[NZB] &lt;freestuff@for.all&gt;" date="1690606101" subject="themkv.mkv - &quot;&quot; yEnc  2990558544 (1/4173)">
```

the download goes correct:

```
-rw-rw-r--  1 sander sander 2990558544 aug  8 08:30 themkv.mkv
-rw-rw-r--  1 sander sander         12 aug  8 08:28 thetext.txt
```

**Comment by sanderjo** [comment]
The empty `&quot;&quot` in the NZB's subject is weird/bad, isn't it?

However, I have another, unrelated .NZB with empty `&quot;&quot;` and SAB can handle that correctly:

`subject="[PRiVATE]-[WtFnZb]-[bla.bla.s01e03.dutch.1080p.web.h264-tripel.r01]-[4/12] - &quot;&quot; yEnc  200000000 (1/280)"`

In this case, SAB understands the file name is `bla.bla.s01e03.dutch.1080p.web.h264-tripel.r01`

**Comment by Safihre** [comment]
Now I finally understand.
We have encountered this weird naming scheme with nothing between `&quot;&quot;` some time ago and have since then adjusted the code to first try and find based on things between `&quot;&quot;` and after that we try to find anything "filename like". So some text followed by a dot and then 2-4 characters (code below).
But in this case because we find `eztv.re` we don't look beyond that.
https://github.com/sabnzbd/sabnzbd/blob/cab5c26e3e5a48b02ea55ec1d8fa3683bc410625/sabnzbd/nzbstuff.py#L2148-L2166

We have a large test set:
https://github.com/sabnzbd/sabnzbd/blob/cab5c26e3e5a48b02ea55ec1d8fa3683bc410625/tests/test_nzbstuff.py#L144-L191

Not sure if we can fix this reliably. But the base is those 2 regexes.

**Comment by sanderjo** [comment]
Ah, yes, reproducible:
```
>>> from sabnzbd import nzbstuff
>>> nzbstuff.name_extractor("[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv]-[1/2] - &quot;&quot; yEnc  2990558544 (1/4173)")
'eztv.re'
>>>
```

After removing the `[eztv.re]` part, it works

```
>>> nzbstuff.name_extractor("[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/Dark.Winds.S02E01.1080p.WEB.h264-EDITH.mkv]-[1/2] - &quot;&quot; yEnc  2990558544 (1/4173)")
'Dark.Winds.S02E01.1080p.WEB.h264-EDITH.mkv'
>>>
```

So:

- make name_extractor() accept the [] part? I assume it's ok to have it in the filename. I guess on Windows it will get sanitized?
- or pre-remove the [] part?

**Comment by Safihre** [comment]
> * make name_extractor() / regexp accept the [] part? I assume it's ok to have it in the filename. I guess on Windows it will get sanitized?
> * or pre-remove the [] part?

We cannot included `[]` because then it will also match the outer ones, so then cases like:
`[PRiVATE]-[WtFnZb]-[Supertje-_S03E11-12_-blabla_+_blabla_WEBDL-480p.mkv]-[4/12]`
Would result in:
`[PRiVATE]-[WtFnZb]-[Supertje-_S03E11-12_-blabla_+_blabla_WEBDL-480p.mkv`

But, we can "improve" things already by requiring the base part of the filename (so before the extension) to be at least 6 charters.

**Comment by sanderjo** [comment]
```
>>> import re
>>> RE_SUBJECT_FILENAME_QUOTES = re.compile(r'"([^"]*)"')
>>> RE_SUBJECT_BASIC_FILENAME = re.compile(r"([\w\-+()'\s.,]+\.[A-Za-z0-9]{2,4})[^A-Za-z0-9]")

>>> subject = "[PRiVATE]-[WtFnZb]-[/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv-WtF[nZb]/Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv]-[1/2] - &quot;&quot; yEnc  2990558544 (1/4173)"
>>>
>>> re.findall(RE_SUBJECT_FILENAME_QUOTES, subject)
[]
>>> re.findall(RE_SUBJECT_BASIC_FILENAME, subject)
['Dark.Winds.S02E01.1080p.WEB.h264', 'eztv.re', 'Dark.Winds.S02E01.1080p.WEB.h264', 'eztv.re']

```

Adding random \[ and \] into the regexp:

```
>>> RE_SUBJECT_BASIC_FILENAME = re.compile(r"([\w\-+()'\s.,\[\]]+\.[A-Za-z0-9]{2,4})[^A-Za-z0-9]")
>>> re.findall(RE_SUBJECT_BASIC_FILENAME, subject)
['Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv', 'Dark.Winds.S02E01.1080p.WEB.h264-EDITH[eztv.re].mkv']

```
Correct filename?

**Comment by Safihre** [comment]
With the updated code the result will be `Dark.Winds.S02E01.1080p.WEB.h264`, so not a valid extensions.
However, if you have Deobfuscate enabled it will fix that to mkv.

**Comment by sanderjo** [comment]
@Safihre 
Rename this report to "Problem with malformend NZB subject and SABnzbd Sorting" so that others can find it. And not be misled with "square bracket", as that is not the problem.

And the malformed NZB subject is not a problem without Sorting.

**Comment by Safihre** [comment]
Even without Sorting only if Deobfuscate is turned on it will be fixed.
The square brackets are exactly the problem why the subject can't be parsed.
Will update title.
