### ISSUE TITLE
0.7.x -- rescan with large amount of orphan jobs kills sab

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#265]
about 1000 items on the status page..  in hopes of trying to nuke them all.. I ran the command:
`http://ip:port/api?mode=rescan&output=json&apikey=xxx`

sab ui became unresponsive, went to look at sending api to try and restart server... 
`http://ip:port/api?mode=restart&output=json&apikey=xxx`

after 10mins? eventually the rescan command returned:
```
Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 79, in setapp
    s, h, b = self.get_response()
  File "/usr/share/sabnzbdplus/cherrypy/_cpwsgi.py", line 219, in get_response
    response = self.request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 579, in run
    raise cherrypy.TimeoutError()
TimeoutError
```

Now sab is unreachable.. trying to get admin to check logs/restart process.

**Comment by thezoggy** [comment]
got sab going again on the box... looks like it ended up adding 1,460+ items into the queue.. cant really offer much more info as sabs log looked to have eaten itself when sab freaked out.

**Comment by shypike** [comment]
The internal processing by SABnzbd takes so much time that CherryPy times out, tired of waiting for an answer. It is a bit odd that it becomes completely unresponsive. CP allows multiple parallel requests. Possibly there's simply no time to do anything else, with the NZB parsing being mostly CPU bound and Python not being truly multi-threaded.

**Comment by shypike** [comment]
@thezoggy Does it make any sense to return the list of nzo_id's or is it better to make rescan return an bland "OK" answer immediately?

**Comment by thezoggy** [comment]
well i was thinking maybe rescan just needed more sensible defaults/safeguards from blowing up sab in the situation. like dont default to `all` or `retry` etc..  now i dont know what/how others use the commands to know if changing the defaults or if the api response matters..  

personally i think any bulk operation needs a few things in place.. so you can make better choices on what your doing.. for example, most large 'queue' things it offers a way to limit,filter,paginate (offset). thus you offer a way to get the amount of data or list of items, thus the user can sensibly act upon it. instead of blindly pass a command which could take 1ms or 100000ms... with no way to know.

**Comment by Safihre** [comment]
Yes exactly, I always use the delete job+files in both queue and history, and somehow there are always some openhanded jobs after a week or so..
But it never throws errors, probably there will be notices in the logs but it not easy to find later on.

**Comment by Safihre** [comment]
The only one I can consistently reproduce is #237. 
Just tested it now and even at 200KB/s and then using delete, I get an orphaned job because there are still 2 *SABnzbd_article_...*-files left in the *__ADMIN__* folder.
When I look in the log it will mention
```
2015-08-01 18:14:42,105::INFO::[__init__:906] \\?\C:\TempDownload\incomplete\malcolm.in.the.middle.s01e15.ws.dvdrip.xvid-ingot-NZBgeek\__ADMIN__\SABnzbd_nzf_90sqr3 removed
2015-08-01 18:14:42,121::INFO::[__init__:906] \\?\C:\TempDownload\incomplete\malcolm.in.the.middle.s01e15.ws.dvdrip.xvid-ingot-NZBgeek\__ADMIN__\SABnzbd_nzf_zivtlu removed
..etc
```
But searching the log, I can never find a mention of the 2 files that are still in the *__ADMIN__* folder.
