### ISSUE TITLE
Speed limit broken in 4.0.3

### ISSUE THREAD

**Issue by AYColumbia** [sabnzbd/sabnzbd#2651]
Looks like the speed limit is NOT working in 4.0.3.  Both the slide bar and using the schedule are not working.  I use this quite a bit to manage bandwidth throughout the day.  I tried pausing and restarting but it does the same thing, i.e., goes to max.  In my case I have a 40Mb connection so you can see it at max, in the image, even though I have it throttled to 46%.
![2023-08-08 21_41_30-SABnzbd speed limit slider](https://github.com/sabnzbd/sabnzbd/assets/6758781/6a090a45-3824-4662-af62-926cfabe296e)

Running on Windows 10 Pro with latest patches/updates.

Let me know if you need any other info please.

**Comment by sanderjo** [comment]
You set it to "46% (2208 MB/s". So 46% = 2208 MB/s.

Check your http://127.0.0.1:8080/sabnzbd/config/general/#bandwidth_max_value ... you must have filled out an absurd big value. My guess: 4800 MB/s. If so: correct that. If you 40Mb as in 40 Mbps, then set the value there to 4 MB/s

**Comment by AYColumbia** [comment]
Hi, you nailed it! :)  My bad, I did set it to 4800 MB/s instead of KB/s which is what I thought I had it set at but I must have forgotten or inadvertently changed it MB/s and didn't' notice.  Thanks much. :)
