### ISSUE TITLE
Scheduler speed limit without maximum line speed

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#2652]
I didn't have "Maximum line speed" set however at some point I'd set a speed limit schedule:

![image](https://github.com/sabnzbd/sabnzbd/assets/9887246/ed3647ae-15c9-4581-a7b4-ccf30985f5b9)

There is no indication in the UI that a speed limit is being enforced:

![image](https://github.com/sabnzbd/sabnzbd/assets/9887246/1089465b-a303-4cd1-a4ae-824234f26ff8)

Additionally there is no way to disable the speed limit, although setting "Maximum line speed" seems to reset the limit back to 100%

What should the expected behaviour be for using the scheduler without a max speed?

Should the scheduler not allow speed limits if max speed isn't set?

Should the UI at least show the icon that it's being limitted? which can be clicked to remove the limit.

**Comment by Safihre** [comment]
This is a known issue indeed, but one that I am willing to accept.
The interface only knows the percentage, since that's all it works with.
For this specific case, I don't want to make extra code for it.
