### ISSUE TITLE
Sorter bug

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2654]
The sorter thinks its a multiple episode release when the episode name starts with a number in the range of the actual episode number +2 e.g
Show.Name.1969.S01E02.2.Kings.1080p.......DDP5.1.H.264 --> S01E02
Show.Name.1969.S01E02.3.Kings.1080p.......DDP5.1.H.264 --> S01E02-03
Show.Name.1969.S01E02.4.Kings.1080p.......DDP5.1.H.264 --> S01E02-04
Show.Name.1969.S01E02.5Kings.1080p.......DDP5.1.H.264 --> S01E02

I cleared out the logs but with season packs the capitalization is still hit and miss with {%sn (%y)/%sn (%y) - S%0se%0e}.%ext

**Comment by Safihre** [comment]
I will close this as an upstream problem, there's just very little we can do about it.
You could open an issue: https://github.com/guessit-io/guessit/issues
Unfortunately the project seems a bit stale at the moment..

**Comment by Safihre** [comment]
Thanks!
