### ISSUE TITLE
SABnzbd 4.0.3 error after upgrade to sabctools 7.1.1

### ISSUE THREAD

**Issue by louisvd** [sabnzbd/sabnzbd#2663]
On page:  https://sabnzbd.org/wiki/installation/sabctools.html
Under the section:  Installation on Fedora / RedHat
it states to enter:  pip install sabctools --upgrade

I did so and it upgraded to 7.1.1 - on starting I get this error:

```

ERROR                         a minute ago                         Essential modules are missing, downloading cannot start.
--
ERROR                         a minute ago                         SABCTools disabled: no correct version found! (Found v7.1.1, expecting v7.0.2)

```
Do I need to downgrade sabctools, or change the requirements file?

**Comment by sanderjo** [comment]
... or upgrade SABnzbd to the github version
