### ISSUE TITLE
Feature request: Repack passworded archives without a password

### ISSUE THREAD

**Issue by treyturner** [sabnzbd/sabnzbd#2670]
I prefer to store some downloaded content as archives rather than unzipped. However, content is increasingly being posted with passworded archives. In these cases, it would be extremely helpful for SABnzbd to have an option to automatically repack these archives without a password so that I don't have to worry about keeping the password with the files for later extraction.

It seems in order to support this, some configuration parameters would needed to store the preferred archive format and compression level (at a minimum).

This would save me a ton of time repacking releases by hand after downloading, so please let me know if you have any questions! Thanks for your consideration.

I also just realized that something like this is presumably possible via user scripts, so I'll investigate that path as well.

**Comment by Safihre** [comment]
This is indeed something perfect for user scripts, as it's a functionality that's extremely specific.
You can find in the documentation all you'll need! We also provide the paths to unrar/7zip as enevioment variable so you can use those in your script.
