### ISSUE TITLE
On Windows, install start menu shortcuts globally

### ISSUE THREAD

**Issue by anthonyvdotbe** [sabnzbd/sabnzbd#2675]
SABnzbd itself is installed globally in `$env:ProgramFiles`, but its start menu shortcuts are placed in the user-specific location (`$env:APPDATA\Microsoft\Windows\Start Menu\Programs`) instead of the global location (`$env:ProgramData\Microsoft\Windows\Start Menu\Programs`). In my experience, this is uncommon: either applications install both their program files and shortcuts globally (most applications), or they install both in user-specific locations (e.g. VS Code).

**Comment by Safihre** [comment]
Seems logical. Probably leftover from ancient times when we made the NSIS script.
Do you want to submit a PR to fix it?
