### ISSUE TITLE
Downloads non-force priority articles while paused

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#2676]
## Steps
- Pause queue
- Add a couple of items
- Set first item to force priority

## Outcome
Some of the normal/paused items download.

## Observations
It depends on how many connections there are but with 50 at 1 Gbps I downloaded 1GB of a paused item before it idled again.

## Why
I think it'll be hitting [this section](https://github.com/sabnzbd/sabnzbd/blob/667ffec667aaf85356220f15863a02d1240fd5a9/sabnzbd/downloader.py#L614-L645) and there is an active job until the force one finishes post-processing, so it'll execute line 645.

So it can get a normal non-force article to request here:

https://github.com/sabnzbd/sabnzbd/blob/667ffec667aaf85356220f15863a02d1240fd5a9/sabnzbd/nzbqueue.py#L720-L722

I'm not sure what logic is needed to prevent it downloading a non-force nzo while paused, but I think those are the relevant parts.

**Comment by Safihre** [comment]
Indeed, a known issue that should be added to the known issues list.
Is there an easy fix? :)

**Comment by mnightingale** [comment]
Had an idea that seems to fix it but I want to test it a bit more so created a draft PR
