### ISSUE TITLE
Handle (or avoid) error: (10049, "Can't assign requested address")

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#268]
Thread to discuss better handling of (or avoiding) 'error: (10049, "Can't assign requested address")'

Suggestion to handle it: fall back to 0.0.0.0 in case this error happens.
Rationale: apparently the user has filled out something else than 127.0.0.1, so he/she wants SABnzbd to listen broader than localhost.

Or, avoid it at all: make the Host option just like the check box as the wizard offers it:

* I want SABnzbd to be viewable by any pc on my network.
* I want SABnzbd to be viewable from my pc only.

That makes it impossible to fill out an IP address that might cause a problem. High-tech users can still edit sabnzbd.ini if they want a specific IP address on a multi-homed/multi-interface system.

Remarks:
* I don't know if an "0.0.0.0" can ever cause the error message. If so, there should be a second fallback to 127.0.0.1
* I have the feeling "127.0.0.1" is safer than "localhost" (which seems not always to resolve)
* As an IPv6 user, I would also like "::" as option, so I would prefer a third option "I want SABnzbd to be viewable by any pc on my network (IPv4 and IPv6)"

**Comment by shypike** [comment]
0.0.0.0 doesn't always work.
V0.8.0 already defaults to 127.0.0.1

The basic problem is that on some systems is hard to find out the local IP address. I'm not sure why this is so. Possibly multiple network interfaces?
Currently I'm testing CherryPy 3.8.0, I'll also check whether it has any improvements in this area,

You're suggestion of limiting choices is OK, but it will fail on a minority of systems.

**Comment by sanderjo** [comment]
"0.0.0.0 doesn't always work.": oh? I didn't know that. Strange.

"hard to find out the local IP address": why do you want to find out the local IP address? In case binding to 0.0.0.0 does not work?
Doesn't my localipv4() from sabnzbd.utils.getipaddress work in such cases?

Another security measure if cherrpy-binding to the desired port does not work in case a non-local address is filled out: trying - in a certain order - binding to other IP addresses:

preferred IP address
0.0.0.0
localipv4()
12.0.0.1
localhost
::

**Comment by shypike** [comment]
0.0.0.0 can fail on badly configured Unix systems. I forgot the details, it's been years since reports came in. I'm not sure how CP fares when there are multiple active network interfaces (like WiFi + wired).
It needs a lot of work (and simplfication) and testing on multiple platforms. The current code is a mess, although your code contributions made diagnostics easier.
I'm not sure how to go forward from here.
