### ISSUE TITLE
Schedule based on attributes other than time

### ISSUE THREAD

**Issue by GlenNicholls** [sabnzbd/sabnzbd#2680]
It would be really nice to schedule resume/pause/throttle/etc. based on attributes other than time. For example, it'd be nice to throttle or pause when a monthly quota is hit (percentage of ISP monthly BW limits for example).

I'm interested in doing something like this through the API, but I'm not entirely sure how to do so. Any feedback is welcome, but for some folks having this built into the web UI would be very helpful.

**Comment by thezoggy** [comment]
This already exists for quota, config>switches>quota. 

https://sabnzbd.org/wiki/configuration/4.0/switches

**Comment by GlenNicholls** [comment]
Not sure how I missed that... Thanks!
