### ISSUE TITLE
found an old "Browse..." button, can it be updated?

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#2681]
Hi guys. :)

While checking out the new 4.1.0RC2, found a old-style browse button:

![image](https://i.imgur.com/QuSoSiP.png)

This is also present in the current stable 4.0.2 SABnzbd. 

Can this please be updated to the more modern-looking button? 

![image](https://i.imgur.com/VwsLPUd.png)

Thank you.

**Comment by Safihre** [comment]
These browse buttons are to select folders, while the other one is specifically to select and upload a file from disk (also places SABnzbd can't access). 
For now I'm fine with having the 2 different functions having different buttons!

**Comment by OneCDOnly** [comment]
Cheers mate. :)
