### ISSUE TITLE
Browse-button to select files on disk

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#2682]
Hi guys. :)

Found a couple of places where it seems a button to select a path or file might be mildly-useful. 

For the HTTPS Chain Certificates (also, "Certificates" is spelt incorrectly):

![image](https://i.imgur.com/tCyET9W.png)

And for selecting the password file:

![image](https://i.imgur.com/GB5LxlN.png)

Cheers!

**Comment by Safihre** [comment]
We only have Browse buttons for folders, not files. As you also have seen in #2681. Not sure if I want to add that, although it's of course not impossible.

Regarding the spelling, you should compile the  translation files (see README) and restart, it will be fixed.

**Comment by OneCDOnly** [comment]
No worries, thanks @Safihre :)

**Comment by Safihre** [comment]
This turned out to be way more work than expected, for just a few fields 🥲

**Comment by OneCDOnly** [comment]
Good work @Safihre!

Although I must admit, I'd completely forgotten about this. 🤓

**Comment by OneCDOnly** [comment]
Just tried this out: they work very well. 😄 👍🏽

**Comment by Safihre** [comment]
Note that the backup upload is specifically a regular file input field, since we also want to allow upload from remote systems.
