### ISSUE TITLE
Some sort of promo box isn't appearing properly in 4.1.0.RC2

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#2683]
![image](https://i.imgur.com/9NCBLDE.png)

Appears the same in FireFox 117 and Chromium 116. Happens on full-width application windows, and narrower windows as shown above.

**Comment by sanderjo** [comment]
I can confirm: Chrome incognito on Chromebook, accessing fresh SAB on Ubuntu

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/eeb8a168-1aa7-466f-a588-c63e70874b90)

**Comment by sanderjo** [comment]
Ah, as soon as I set Chrome's zoom to 80%, I can see the ad:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/13415428-1602-42e7-a629-cc314b24e562)

**Comment by Safihre** [comment]
Fixed!

**Comment by sanderjo** [comment]
With Chrome incognito, fresh git pull ('Commit = 8e2972eda'), I see no promo box at all anymore?

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/1456df82-5c04-4233-9782-34885569e833)

**Comment by Safihre** [comment]
The screen isn't wide enough to fit, only loads when it can fit on page load.
