### ISSUE TITLE
0.8.0 - UTF8 par2_repair problem

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#269]
Tried this download today, where the filenames were a little weird. 
Download went fine, but then it failed.

Error in the interface:
*Error 'utf8' codec can't decode byte 0xb8 in position 0: invalid start byte while running par2_repair on set ©.U.T.SBUS.LN.462xLD-BEW.CHP0801.5102.YPS*

Error in the console:
*2015-08-04 13:01:35,101::ERROR::[newsunpack:1086] Error 'utf8' codec can't decode byte 0xb8 in position 0: invalid start byte while running par2_repair on set ¸.U.T.SBUS.LN.462xLD-BEW.CHP0801.5102.YPS*

It really doesn't seem to like the copyright sign?
I ended up using the Windows par2, that one worked fine.

**Comment by shypike** [comment]
"I ended up using the Windows par2". What did you use before? So, on which OS ran SABnzbd?

**Comment by Safihre** [comment]
Windows 8.1.
With "Windows par2" I mean QuickPar.

**Comment by shypike** [comment]
Please email the NZB to the usual bugs address.

**Comment by shypike** [comment]
Found it. I forgot a few TRANS() calls when processing output from par2.exe.
The 8bit ASCII coming from par2.exe needs to be converted to Unicode (and mapped from CP850 to Latin-1).

**Comment by shypike** [comment]
fixed now.

**Comment by Safihre** [comment]
There is one more place to fix:
![untitled](https://cloud.githubusercontent.com/assets/5703454/9082007/54348276-3b61-11e5-8f1c-6695faffc450.png)

**Comment by shypike** [comment]
No, this is the way it is in the NZB, the poster is a clumsy one. SABnzbd shows what's coming from the NZB. The actual file name is embedded in the yEnc record, but you can only know that after the first article of a file has been downloaded.

**Comment by Safihre** [comment]
:sweat_smile: Those posters..

**Comment by thezoggy** [comment]
its a form of obfuscation.. notice backwards name with it as well.

**Comment by shypike** [comment]
@thezoggy 
Yes it is, but no excuse for SABnzbd to crash :)
