### ISSUE TITLE
4.1.0 - disable dark theme for config

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2691]
user complaint on discord:
>  Just upgraded to 4.1.0 - is there a way to set dark for the main front end but light for the settings page? I prefer dark for the front end but the back end is very text heavy and dark mode makes that very hard to read. I can't see an option or switch for it, but just wondered if there was a way.

thoughts on us adding a checkbox or something to force using light theme for config?

**Comment by Safihre** [comment]
....hahahha. You can't please people how hard you try 😅

**Comment by Safihre** [comment]
This is too niche to implement.

**Comment by thezoggy** [comment]
I'll probably still submit something for it, I personally do not like the dark the e for the config but so like ha ing the ability to have a dark/light front end to designate between my sab instances (dev/normal)
