### ISSUE TITLE
Users report multi-edit in the queue doesn't work but I cannot reproduce it

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2702]
### SABnzbd version

4.1.0

### Operating system

N/A

### Using Docker image

None

### Description

Reported already during testing-phase, but I was never able to reproduce:
https://forums.sabnzbd.org/viewtopic.php?t=26329
But now more people report:
https://forums.sabnzbd.org/viewtopic.php?t=26365
https://www.reddit.com/r/usenet/comments/16sokqt/comment/k370294/?context=3

Seems to be OS and browser independent.
So far I was able to investigate that the API-call is just not being made. But I have no clue why not.
The Reddit user also suggested a different approach than I was testing: first set the desired cat/prio/etc and only then select the jobs.
But even that way I cannot reproduce it.
If anyone with a developer setup can reproduce it, let me know.

Pinging @ricci2511, who implemented the change to the code. Maybe he has some insights!

**Comment by ricci2511** [comment]
Now I've had half an hour to try to reproduce it and unfortunately I wasn't able to. I tried it in windows 10 and the [linuxserver](https://registry.hub.docker.com/r/linuxserver/sabnzbd/) docker image, both with chrome and firefox. I tried with the latest 4.1.0 release and in the dev environment from the latest changes in `develop`, but I couldn't notice any differences.
I tested by first setting the desired cat/prio/etc and then selecting queue items, and first selecting queue items and then setting the desired cat/prio/etc.
Could you maybe elaborate a bit more on the "API-call is just not being made" part? Which API-call exactly?

Change category on selected item triggers API call
![category_change](https://github.com/sabnzbd/sabnzbd/assets/80476005/dccd6e44-78cd-4029-9463-9cefe5169182)

Change prio on selected item triggers API call
![prio_change](https://github.com/sabnzbd/sabnzbd/assets/80476005/1d6cae3a-a138-443a-b10c-b3c159bad1f1)

Result of selected item
![result](https://github.com/sabnzbd/sabnzbd/assets/80476005/8d76b2f7-ff1b-4b98-8348-90ea8d411d76)

Let me know if I misunderstood something!

**Comment by Safihre** [comment]
Thank you for also checking it! 🥇

The forum user reach out to me through email and I asked him to open Developer Tools to see what requests were made. In his case, when he change the Category, the `change_cat` request was not made.
Since he is on macOS, I could not send him a modified `.js` file to do more debugging since on macOS modifying program files is not allowed and he couldn't run SABnzbd from sources.

**Comment by ricci2511** [comment]
Interesting. Tomorrow, I might be able to try it on macos and check there myself if the requests are working as expected. Still curious what could've broken it through :thinking:

**Comment by thezoggy** [comment]
loading up dummy queue on my dev instance. working fine here, latest dev branch on windows x64 + firefox 118.01

changed multiple queue items priority/category just fine. was a little jarring when i changed items to 'stop' priority and they vanish then checking off other stuff they just go poof (because theres no submit button, just takes action if checked). but thats how it was created to work and all.

**Comment by Safihre** [comment]
For anyone experiencing this issue, I created a debug build that logs all the steps in the Developer Console.
https://github.com/sabnzbd/sabnzbd/actions/runs/6449903707
Please open the Developer Console first, and then perform all the multi-edit steps the way they used to work in 4.0.3.

**Comment by Safihre** [comment]
So far the results show that the `addMultiEdit` is just not called.. I have no idea why not.
![image](https://github.com/sabnzbd/sabnzbd/assets/5703454/abf4326a-6fc0-44e2-a3f3-e1258e7d89c2)

**Comment by Safihre** [comment]
I decided to abanond having shared code between Queue and History and just duplicate everything.
This way I was also able to fix some bugs (check-all-checkbox state wasn't always updated).
Lots of duplicate code, but at least 1 user with this problem confirmed that these changes fix the problem for him.
https://github.com/sabnzbd/sabnzbd/commit/461267865b4f7a470aab32531b172b717fbbb910

**Comment by Safihre** [comment]
Closed (for now) by 12dedb7cff3c56e0c041868a96a4c1e7a409568e
