### ISSUE TITLE
Multi-queue category change oddities

### ISSUE THREAD

**Issue by mnightingale** [sabnzbd/sabnzbd#2703]
### SABnzbd version

4.1.0

### Operating system

Ubuntu 22.04

### Using Docker image

linuxserver

### Description

I noticed this while testing for #2702 I don't think it's related so didn't want to pollute that issue.
Hopefully someone else can reproduce this.

Not sure if its a UI or API issue - maybe empty string vs None or something.

# Setup 

For the below presume the queue has the following items all **paused** and with category **tv**

1. S01E01
2. S01E02
3. S01E03
4. S01E04

When I later refer to "3" I mean the item which was originally in position 3 so S01E03

Pause SABnzbd - just so items don't download and disappear

# 1. Unpaused on category change

Use multi-edit to tick 3 and change category to **Default**.

Expected: item to remain paused, stay at same position with only its category changing

Result: along with changing category the item becomes un-paused and moves to the top of the queue - I'm not sure if the moving is intentional?

# 2. Back to tv and sort

With the previous item (3) still selected change it back to TV category then clear item selection and close the multi-queue interface

"Sort By Name A>Z"

Expected: back to 1,2,3,4

Result: order doesn't change 3,1,2,3

n.b. I also tried pausing the item so all items are paused again

# 3. Strange way to fix it?

Drag (3) to the second position (1,3,2,4)

"Sort By Name A>Z"

Result: sort works 1,2,3,4

n.b. Leaving 3 in the 1st position and moving the other items (3,4,1,2) then sorting returns them back to 3,1,2,4

**Comment by Safihre** [comment]
Just to be sure, what are your category settings? If you check your sabnzbd.ini, are Default and TV the exact same?

**Comment by mnightingale** [comment]
As far as I know they are left at the defaults, so difference appears to be pp and priority.

But I think I've figured out what's going on.

Sonarr is adding as low priority because of the "Older Priority" setting.

So priority goes TV (forced low) > Default (normal) > TV (normal) hence it stays at the top of the queue and sorting by name doesn't work.

But I'm not sure why then dragging the item then resets the priorty and allows it to be sorted by name again?

```
[[tv]]
name = tv
order = 0
pp = ""
script = Default
dir = ""
newzbin = ""
priority = -100
[[*]]
name = *
order = 0
pp = 3
script = None
dir = ""
newzbin = ""
priority = 0
```

**Comment by mnightingale** [comment]
Thanks for the explanation, it's clear to me that this is not a bug but I do think the UI could be improved a bit.

I've added the priority column so it's a bit clearer what's going on - I do prefer the way NZBget provides quick access to change some aspects of the queue and uses the icon indicate priority:

![image](https://github.com/sabnzbd/sabnzbd/assets/9887246/2b4fc736-e4a2-48bc-b6be-b75f4b460b94)
