### ISSUE TITLE
Disk Error on Creating .par2 file

### ISSUE THREAD

**Issue by Johannes-m-TK** [sabnzbd/sabnzbd#2710]
### SABnzbd version

4.1.0

### Operating system

Debian Linux

### Using Docker image

linuxserver

### Description

I read a few sabnzbd forums where this error occured. Weirdly, this doesnt occur on all downloads but roundabout every 20 downloads. The Download still is processed correctly. Permissions are set correctly. This woulnd be a big issue, but the whole queue is paused when the error occurs and i dont want to force all categories.  Otherwise, everyting works perfectly, thank you for that :)

[SAbnzbd_Bug_Log.txt](https://github.com/sabnzbd/sabnzbd/files/12904203/SAbnzbd_Bug_Log.txt)

**Comment by sanderjo** [comment]
So

```
2023-10-14 02:11:14,785::ERROR::[assembler:107] Disk error on creating file /downloads/tmpDownloads/redacted/redacted.par2
2023-10-14 02:11:14,786::INFO::[assembler:115] Traceback: 
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/assembler.py", line 80, in run
    self.assemble(nzo, nzf, file_done)
  File "/app/sabnzbd/sabnzbd/assembler.py", line 169, in assemble
    with open(nzf.filepath, "ab", buffering=0) as fout:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/downloads/tmpDownloads/redacted/redacted.par2'

```

SABnzbd/python is just telling the error that the operating is giving back. Docker, so I guess /downloads is not inside docker, but on the host? Hint to circumvent (not solve) this: put your SABnzbd Temp/Incomplete inside your docker, on on the host filesystem

Anyway: Nothing SABnzbd can do about this. Contact the administrator of your docker and/or host, which might be you.

**Comment by Johannes-m-TK** [comment]
Thank you.
