### ISSUE TITLE
SABnzbd as a Windows Service

### ISSUE THREAD

**Issue by Thilas** [sabnzbd/sabnzbd#2712]
### SABnzbd version

4.2.0Alpha1

### Operating system

Windows

### Using Docker image

None

### Description

Hi,
I'm maintaining the chocolatey package for SABnzbd and I started to fail with the latest alpha version because of `SABnzbd-console.exe` removal. Since the documentation is not yet updated (see https://sabnzbd.org/wiki/advanced/sabnzbd-as-a-windows-service), I'd like to confirm with you guys what needs to be done to work with a service on this last version.
Especially, it seems that both CLI works:
- `SABnzbd.exe --console -f sabnzbd.ini install`
- `SABnzbd.exe -f sabnzbd.ini install`
Which one are you recommending?

**Comment by Safihre** [comment]
You can no use `SABnzbd.exe -f sabnzbd.ini install`.
Did not want to update the manual just yet, to not confusing 4.1.0 users 😊

**Comment by Safihre** [comment]
You can now use `SABnzbd.exe -f sabnzbd.ini install`.
Did not want to update the manual just yet, to not confusing 4.1.0 users 😊

**Comment by Thilas** [comment]
Duly noted, thanks

**Comment by Safihre** [comment]
@Thilas unfortunately I had to revert this due to problems in Windows 11. So in the next SABnzbd release, `SABnzbd-console.exe` will be back.

**Comment by Thilas** [comment]
Thanks for the heads up. Can you confirm I can keep the new way to set up the service, the one based on `SABnzbd.exe` despite your rollback?

**Comment by Safihre** [comment]
I think it will work, but no return code or output is given so you can't check if it succeeded. 
So best to use console, since we know that works.
