### ISSUE TITLE
[BUG] Temporary Download Folder creates subdirectory

### ISSUE THREAD

**Issue by Kazuto** [sabnzbd/sabnzbd#2717]
### SABnzbd version

4.0.3

### Operating system

Windows (Docker)

### Using Docker image

linuxserver

### Current Behavior

Selecting a directory except `/incomplete-downloads` creates a subdirectory called `incomplete`, so basically choosing `downloads/incomplete` creates `downloads/incomplete/incomplete`.

Choosing just `downloads` is not allowed because `The Completed Download Folder cannot be the same or a subfolder of the Temporary Download Folder`.

**Example 1**
- `/downloads/complete` -> Completed downloads
- `/downloads/incomplete` -> Incompleted downloads

The latter will be `/downloads/incomplete/incomplete` even though they are already two distinct directories.

**Example 2**
- `/downloads/complete` -> Completed downloads
- `/incomplete-downloads` -> Incompleted downloads

The latter does not create a subdirectory.

**Example 3**
- `/downloads/complete` -> Completed downloads
- `/downloads` -> Incompleted downloads

The latter won't work even though it would automatically create a subdirectory called `incomplete` making it `/downloads/incomplete` and again two distinct directories.

This means that somewhere in the codebase a path/string match is done for `/incomplete-downloads` and if the path does not match a subdirectory is created, though not checking if the path base dir is the same as as `Completed Download Folder` and creating a subdirectory then.

### Expected Behavior

The application checks the path, compares it to the base path of `Completed Download Folder` and only throws the error if both paths truly are the same.

If `Temporary Download Folder`
- is `/incomplete-downloads` => do nothing
- is a sibling of `Completed Download Folder` => do nothing
- is the parent of `Completed Download Folder` => create directory `incomplete` and update path
- is the same as `Completed Download Folder` => throws the error

I hope this gets my point across.

This was the behaviour when switching from the official `sabnzbd/sabnzbd` image which I've used before, but ran on version 3.2.1 and is not available anymore unfortunately.

**Comment by sanderjo** [comment]
Weird. Do you have logging from sabnzbd.log to prove this?

**Comment by Safihre** [comment]
The `incomplete` folder is only created if Complete is a sub-folder of Incomplete or if they are the same folder.
So in case of your Example 3, no sub-folder is automatically created so that's why it is blocked.

There is no specific logging I think, but the code is here:
https://github.com/sabnzbd/sabnzbd/blob/0cdfdd82d454d705430f1dcff7739318002d3b88/sabnzbd/filesystem.py#L1196-L1207

**Comment by Safihre** [comment]
Looking at this, maybe it's time to just get rid of all this unexplained magic and keep it simple.
Block same folders or being a sub-folder, nothing more.

**Comment by thezoggy** [comment]
On discord I see people get confused with absolute vs relative paths as they are fighting against using the predefined paths a docker maintainer might use. They don't realize they can just change names or really want to do something bad like nest incomplete inside complete ..  once they figure out that incomplete and complete should be adjacent. It usually clicks.

**Comment by Safihre** [comment]
No objects against removing the magic additional 'incomplete' folder?
