### ISSUE TITLE
Pausing URL grabber regression

### ISSUE THREAD

**Issue by Marsup** [sabnzbd/sabnzbd#2719]
### SABnzbd version

4.1.0

### Operating system

Linux

### Using Docker image

linuxserver

### Description

Hi,

I'm a new user to SABnzbd and am trying to use something that was mentioned in [an old issue](https://github.com/sabnzbd/sabnzbd/issues/988). This feature supposedly pauses the URL grabber under certain conditions, but unsuccessfully so far. I asked on Discord and was advised to create an issue.

I was under the impression that maybe having both SABnzbd paused and a RSS defaulting downloads to paused would simply create an entry in the queue without actually downloading the nzb file, but it looks like it does. I have a succession of those lines in the log:
```
[rss:474] Starting scheduled RSS read-out...
[rss:656] Adding https://...
[urlgrabber:400] Fetching https://...
[urlgrabber:120] Grabbing URL https://
```
Indicating that it is indeed fetching the file, but it is confirmed by the indexer anyway.

Am I misunderstanding the original issue? (in which case this would become a feature request)
Was there a regression at some point in history?

Thanks.

**Comment by Safihre** [comment]
Yes indeed, this is broken when the URL's come from the RSS.

**Comment by thezoggy** [comment]
What's the actual use case of passing a paused job. Pausing the feed/in pausing should just be that.

**Comment by Safihre** [comment]
People want that, to decided themselves when or if they want to download a job at all.
That's why we also have it in the Categories settings and it can be set from pre-queue script.

**Comment by Marsup** [comment]
My own use case is that I can decently filter RSS entries with advanced regexes, but it's never flawless (and probably won't ever be), and I want to evaluate manually whether I actually want to download or not after that 1st pass of filters. If paused jobs coming from RSS are not grabbed until unpaused, that would work for me as well, I don't need a global pause, I just thought it was the way it would work.

**Comment by Safihre** [comment]
But what's the problem if they are grabbed, but are then paused? You have a grab limit?

**Comment by Marsup** [comment]
Kind of, since RSS is a bit unpredictable, sometimes filters are not that effective, and I've found myself grabbing way too many entries on some occasions and got reprimanded for that as it was way beyond an acceptable use limit.

**Comment by Safihre** [comment]
I don't think I want to fix this, because adding jobs (not the fetch) as paused is the more expected behaviour.

**Comment by Marsup** [comment]
So is there a workaround that I could use to make it happen? A pre-queue script maybe?

**Comment by thezoggy** [comment]
your workflow sounds a bit abnormal and niche, perhaps a revisit to what your doing would make more sense. like maybe you want stuff to just go to a watch folder? use 3rd party automation apps that has far more logic than what we can do via rss? 

if your objective is just to have sab paused, you can use the scheduler to do that 
https://sabnzbd.org/wiki/configuration/4.1/scheduling

if your objective is to add jobs at whim with paused state then you can use nzb360/lunasea and just add them from that app using sab api on demand from the indexers/or adding jobs manually

you of course could make a pre-queue script to do whatever and leverage api commands with logic to fine tune whatever you want.

**Comment by Marsup** [comment]
My goal is to have a RSS source but avoid hitting the indexer if the filtering rules weren't good enough. It felt easier to do in sab as it was already supported before, but I guess I'll try to find another way. Thanks for considering it anyway.

**Comment by Marsup** [comment]
I think we can close the issue, I've set up an instance of flexget, their pending list feature satisfies my requirements, it's one more place to check, but it's probably better to separate those concerns. Thanks again for your answers.
