### ISSUE TITLE
Moved item to the top gets FORCE state

### ISSUE THREAD

**Issue by EdwinKM** [sabnzbd/sabnzbd#2724]
### SABnzbd version

4.1.0

### Operating system

TrueNAS

### Using Docker image

Other

### Description

* Start sabnzbd in paused mode
* Add some nzbs
* Change all of them to Paused mode by clicking the individual icon button
* Change sabnzbd state to resume
* Note: the priority of all items is now "normal"
* Change the last item at the bottom to "force". It is moved to the top and the priority is changed
* While it is downloading, just move another item to the top. The paused state of this item is changed to "force"

**Comment by Safihre** [comment]
This is not a bug, it's a feature 😄
The jobs in the queue are guaranteed always sorted by priority, so a High job is never allowed to be below a Normal job. This is required for the internal working and also just expectations of users with a priority.
So when a user manually moves a job, we change the priority to match the desired position.
