### ISSUE TITLE
Sort by Date Added, Filter by Category/ Priority

### ISSUE THREAD

**Issue by nviraj** [sabnzbd/sabnzbd#2730]
### Description

Hi,
Started using sabnzbd recently. Thank you!

Is there a way to sort by when an item was added to the program? Basically looking for a way to go back to Default sort after sorting by Age or Percentage. Or is the default sort lost forever once sorted in some other way?

On a similar vein, is there a way to filter by category/ priority? 

My queue size is huge after my home lab crashed and apart from search, I can't seem to prioritize ones that are needed quickly. Not sure if I am doing something incorrectly.

**Comment by thezoggy** [comment]
Sorting in the queue would change how things are processed, but yes you can change that 'default' sort by config>switches>sort by..  just may not be what you really want.

For history you can search by cat/pri, by using the prefix like `cat:whatever` or `priority:x`
https://sabnzbd.org/wiki/extra/glitter-tips-and-tricks

**Comment by nviraj** [comment]
Thanks for the quick response! 

You're right, sorting by date added is what I needed. Think I'll leave the request open to see if it's something that could be added in the future, to be able to revert to the unmodified default sort any time.

Thanks for the filtering options! Exactly what I needed. Is there a way to filter by whether something is paused or not? Couldn't find it in the wiki.

**Comment by Safihre** [comment]
I don't see a strong use case for being able to sort by original added-order, as it doesn't really say much as would require use to keep extra bookkeeping just for this niche feature.
I do agree it would be nice to filter by paused status, so I added it to this one: #2376 2376

**Comment by nviraj** [comment]
Hi Safihre, I completely understand your perspective, especially if it involves modifying your data structure. I had initially assumed that the 'date added' might be a stored attribute, but after reviewing the API, it seems that's not the case? 

Please don't take this as a critique, I'm just trying to share the thought process behind the request. The request was prompted by a couple of factors:
- I've grown accustomed to having options like sorting and filtering as UI features, particularly for tabular displays. So, it was a bit surprising to see it have a lasting impact on the queue. For instance, sorting out of curiosity to view the item with the largest size.
- While FIFO is the default option, once you sort in a different way, there's no way to revert back to it.

For smaller queue sizes, the order by 'date added' might not be significant. However, for larger queues, especially when recovering from backups, it can be useful to prioritize earlier requests. 
As long as I remember not to sort in any other way, I should be okay in the future. 

On a positive note, I'm thrilled to hear about the 'filter by paused status' update! Thanks for considering that.
