### ISSUE TITLE
sanitize job source for history

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2732]
### SABnzbd version

4.2.0Alpha2

### Operating system

unraid

### Using Docker image

linuxserver

### Description

when adding adding from remote url (ex: using nzb360 -> sent to sab)

it results in the url being shown as the source, which can contain apikeys
![sab](http://zoggy.net/firefox_2023-11-17_11-19-05.png)

do we want to sanitize this field in the same we do the log (show logging)?

**Comment by sanderjo** [comment]
Why? That is only visible to the user themself, not shared with others, and handy for debugging (you can copy-paste it into your webbrowser or SAB)

And in the sabnzbd.log it is not sanitited either (obfuscated by hand)

`2023-11-17 12:01:37,020::INFO::[urlgrabber:401] Fetching https://api.nzb.su/getnzb/3e873xxxb5e8d533abxxx6b3bc.nzb&i=245333&r=0d4d86xxxxxxx9486c91df1d1935706b&del=1
`
It's only sanitized if the user decides to upload it.

**Comment by thezoggy** [comment]
Same argument to be said with the log.. but we sanitize that in case it's to be shared.

**Comment by sanderjo** [comment]
> Same argument to be said with the log.. 

So ... obfuscate in sabnzbd.log itself? IMHO not handy

> but we sanitize that (wrench>show logging) in case it's to be shared.

Exactly: when/if a user shares it. Same as you did yourself with your screenshot.

**Comment by thezoggy** [comment]
> > Same argument to be said with the log.. 
> 
> So ... obfuscate in sabnzbd.log itself? IMHO not handy
> 
> > but we sanitize that (wrench>show logging) in case it's to be shared.
> 
> Exactly: when/if a user shares it. Same as you did yourself with your screenshot. 
> 
> 


One could argue people can sanitize their own log file. But it's a convenience and prevents someone accidentally leaking stuff. It's a long the same vein and why I felt it warrant to talk if we should since it does take effort to sanitize the data like I did. With *arr apps they don't add url to sab but actually upload the nzb directly, so these never will include it. Why it caught me off guard to see it as I was testing to replicate recent changes that broke stuff and saw it.

**Comment by Safihre** [comment]
I still don't understand why it would be a problem?
It's not a bug, it's a feature!
