### ISSUE TITLE
Duplicates via RSS not being detected from nzb-backup folder

### ISSUE THREAD

**Issue by RealTracat** [sabnzbd/sabnzbd#2742]
### SABnzbd version

4.1.0

### Operating system

Synology Nas

### Using Docker image

None

### Description

Multiple copies of the same episode, only the one in the history is detected as a duplicate. I have this episode previously and removed it from history, then today 2 more copies tried to be downloaded, the first successful then the second paused as a duplicate as it's in the history. But the first should have been detected as a duplicate as there are already, at that time, 4 copies on the same episode.
Below is a screenshot of the nzb-backup folder, showing the now 6 copies of the same episode with all their dates.

![bob](https://github.com/sabnzbd/sabnzbd/assets/63046325/3a58d3e7-ff50-45b3-aab5-c7274fee1605)

I would prefer to send the log via email, will send to safihre as I have their email from previous.

**Comment by Safihre** [comment]
I understand now what you mean, but this is not how it works or how it can work:
The .nzb backup-folder is only used for the Identical Duplicate Detection, not for the Smart Duplicate detection.
That's also in the description: https://sabnzbd.org/wiki/extra/duplicate-detection.html
