### ISSUE TITLE
unable to delete history items "waiting" to be processed

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd#2745]
### SABnzbd version

4.1.0

### Operating system

Debian 12.2

### Using Docker image

None

### Description

Hi guys,

I'm using SABnzbd 4.1.0 on Debian 12.2, and accessing it via Firefox 120 on a separate workstation (also running Debian 12.2).

Just noticed I'm unable to delete history line-items that are in "waiting" state. I have to wait for each one to be processed before I can actually delete it. The delete button is shown while in "waiting" state, but doesn't seem to do anything except refresh the display.

I'm trying to delete these particular "waiting" items as I already know they're going to fail post-processing, and I don't want SABnzbd to attempt to process them.

Any thoughts please?

**Comment by Safihre** [comment]
Hmm I can't reproduce this. 
I just put a very long `time.sleep()` in the PostProcessor so I get a job in the Waiting status and when I delete it, it's removed with a message in the log:
```
2023-12-10 21:37:03,532::INFO::[postproc:165] Removed job basic_rar5 from postproc queue
```
Could you maybe see if you have Debug logging when you click the delete button?

**Comment by OneCDOnly** [comment]
Hi @Safihre, I'm trying to replicate this and I can't. I'm now unable to recall the exact circumstances that led to the jobs waiting in the history queue to be post-processed. :(

I've searched my debug log and there's no mention of the phrases _"removed job"_ or _"from postproc queue"_. Weird. 

I guess we should close this issue then. My apologies for the trouble.

**Comment by Safihre** [comment]
Let me know if it happens again!
