### ISSUE TITLE
Local/Public IPv6 address

### ISSUE THREAD

**Issue by L2501** [sabnzbd/sabnzbd#2755]
### Description

IPv6 can be behind NAT same as IPv4, for example when using a VPN or container. Sab could display the address similarly to the IPv4 ones

**Comment by sanderjo** [comment]
Correct. I've already written code that takes care of that. Hopefully the PR will be accepted.

**Comment by Safihre** [comment]
You are in luck! #2753 addresses this.

**Comment by sanderjo** [comment]
@L2501 
If you want, you can test that version already:


If you're on Windows or Mac: you can use the binary from https://github.com/sanderjo/sabnzbd/actions/runs/7265583028 ... github account, which you have.

If you run from source (Linux), you can run the github version https://github.com/sanderjo/sabnzbd/ and select the correct branch

**Comment by Safihre** [comment]
Implemented and part of SABnzbd 4.2.1!
