### ISSUE TITLE
SABnzbd 4.2.0RC3 is not unrar/unpacking .rar files

### ISSUE THREAD

**Issue by Oxhellfire** [sabnzbd/sabnzbd#2759]
### SABnzbd version

4.2.0RC3

### Operating system

Linux

### Using Docker image

None

### Description

Here are logs: https://pastebin.com/jMrPe9LY
![image](https://github.com/sabnzbd/sabnzbd/assets/128453072/981d58a7-961d-4cf5-9e08-e5e993823dbf)

**Comment by Safihre** [comment]
Could you please enable Debug logging in the Status window and then run the job again?
These are only Info logs so I can't see much.

**Comment by Oxhellfire** [comment]
> Could you please enable Debug logging in the Status window and then run the job again? These are only Info logs so I can't see much.

Debug Logs: https://pastebin.com/dnXAvMBg

**Comment by Safihre** [comment]
How did you add the url? Through the interface or some other application?
What are your Category settings?

**Comment by Oxhellfire** [comment]
I'm using this repo https://github.com/sanjit-sinha/Tg-UsenetBot 
and here is category settings

![image](https://github.com/sabnzbd/sabnzbd/assets/128453072/7437023c-21b2-4eb6-b779-c0523d3bcaf7)

**Comment by Oxhellfire** [comment]
I just tried with .nzb file directly from status page and got same result unpacking/unrar files

**Comment by Oxhellfire** [comment]
I'm using v4.1.0 now it's working fine thanks for replying

**Comment by sanderjo** [comment]
Can you share the .NZB? I'm on Linux, but I can't reproduce with the .NZB I can find for "Targeted..."

**Comment by Oxhellfire** [comment]
here is .nzb file: https://filetransfer.io/data-package/x2aWRIdF#link
btw i got to know what was the issue 

I've just changed this Download to +Delete
![image](https://github.com/sabnzbd/sabnzbd/assets/128453072/4a6041e7-d57d-4c23-976c-8da4eefba7d6)

**Comment by sanderjo** [comment]
Ah, yes.

But how can it work for 4.1.0 ... ?

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/d76bf5d2-7235-48a7-b747-4c94dabed93e)

**Comment by Oxhellfire** [comment]
if i'm using Download in 4.1.0 it also giving me same unrar/unpacking error but after changing to +Delete it's working fine so i assume it was the issue in latest version too cuz i was using Download in that version

**Comment by sanderjo** [comment]
So you still think there is an issue in 4.2.0 RC2?

**Comment by sanderjo** [comment]
> here is .nzb file: https://filetransfer.io/data-package/x2aWRIdF#link

Works fine for me on 4.2.0RC2.

When you put it into the queue again, what is the setting on the right hand side, like in the picutre?

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/670ef2d9-fc61-41da-8ab2-4153eae63f02)

**Comment by Oxhellfire** [comment]
Yes I've just tested on  4.2.0RC2. and it's working fine with Processing +Delete

**Comment by Safihre** [comment]
Your settings are all set to Download only, on no version this would unpack anything.
