### ISSUE TITLE
Can't deobfuscate certain releases

### ISSUE THREAD

**Issue by ayykamp** [sabnzbd/sabnzbd#2772]
### SABnzbd version

4.2.1

### Operating system

Debian

### Using Docker image

hotio

### Description

Some releases from a certain indexer are not deobfuscated correctly, related #2649 #1682.
I can gladly provide a nzb via email. [Relevant logs](https://pastebin.com/y5uRvpPE)

**Comment by thezoggy** [comment]
You would need debug logs. And certain indexers/releases purposely won't work unless you have the parset to go with them..

**Comment by Safihre** [comment]
Can you send me the NZB at safihre@sabnzbd.org? I can take a look. But as you saw in the other issues, their weird naming scheme and missing par2 files are something that I deem just too exotic to make special code for.

**Comment by Safihre** [comment]
@ayykamp shared an NZB with me, but it's another one of these Blu-ray uploads that don't contain any directory information.
There's nothing SABnzbd can do about that.
They should include a par2 file and then we can restore the folder structure, without that, it's just a bunch of files.

**Comment by Safihre** [comment]
@thezoggy You are a bit much deeper into the usenet scene, is there a way to reach OMG and ask them what they expect from us how to fix these uploads? Or for them to make the uploads better? Post on /r/usenet?

**Comment by Safihre** [comment]
@scriptzteam Maybe you could help us how we should "fix" the (your?) cblu-ray uploads which are just a flat collection of files without the actual blu-ray structure? Are these NZB's missing the par2 file that could fix the directory-tree? Or is this really how it was intended?

**Comment by thezoggy** [comment]
@Safihre sure, but I've never had an issue with anything on their site with regards to this.. so I'd need to see a specific example to refer to (ID is fine)

**Comment by thezoggy** [comment]
> On 2024-01-17 17:53, thezoggy wrote: @DarrenPIngram [1] they do..
> They DON'T, at least of a month or so ago, as confirmed by a staff message and I raised it in this Github when tracking down a problem. Well I guess I have to accept the NZBs I checked did not have the relevant flag, and assume the staff member knows what they are talking about - their site and all of that.

correct they didnt, and when you brought it up i had it fixed that day. so its been there for 3+ weeks now
