### ISSUE TITLE
Hidden History for duplicate detection (Archive)

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2782]
### Description

Add a way to remove jobs while still preserving enough information for duplicate detection.
This way users can have a clean history, but duplicate detecton can still do it's job.
The 'hidden' history could be shown through an additional filter/button if users still want to clear it.
As things are stored in an SQLite database, performance isn't really an issue.

nzbget already implements this. When deleting a file it asks how exactly you want to delete it, with/without preserving enough attributes to still be able to perform duplicate detection.

Often suggested by @thezoggy.

**Comment by thezoggy** [comment]
Additional it's so users can keep history and have apps like sonarr/radarr hide things that it's imported so it doesn't show up on API so things work better at scale. This is a common request from those coming from nzbget which are used to that behavior, *arr apps only get last 60 history items for the category with sab to have a fixed amount of things to look at. which is why they by default recommend removing completed/failed items so it does allow things they haven't looked at to get outside that view.. so if we added similar behavior then ideally those apps would just hide after import to keep it for dupe detection/stats/whatever and expire it out on sab side at some point if they want or not.

**Comment by Safihre** [comment]
So these programs would still be configured to remove completed, but instead of removing they would archive?

**Comment by thezoggy** [comment]
Yes that would prob the desired option, so things that they process get archive. Now we would add option to API to dictate if it was hidden/archive or actually removed.. not sure if changing default behavior makes sense or what.  

Then of course all the relevant things with history would need option to deal with it.. history retention/dupe check/filtering by it/changing that archive state.

**Comment by Safihre** [comment]
This actually should be called 'Archive', like is common in email apps.

**Comment by Safihre** [comment]
Made some good progress already:
https://github.com/sabnzbd/sabnzbd/tree/feature/archive

**Comment by thezoggy** [comment]
Sweet, will have to check out. Already been enjoying the modal addition on removal.

**Comment by Safihre** [comment]
Merged to develop.

**TODO:**
- Adjust History Retention to include options to archive instead of Delete.
- Same for Scheduler.

**Comment by thezoggy** [comment]
hmm yeah i just saw sonarr nuke my history on removing stuff....  as it doesnt pass archive at all... so i assume they need to pass archive=1 to make it archive otherwise no archive it just gets nuked..

**Comment by Safihre** [comment]
Will fix!

**Comment by thezoggy** [comment]
right now when you go to delete an item from the archive, it doesnt make too much sense to still offer up the ability to still archive (not perm delete). minor quibble, but could just gray out like gmail does. 

there is prob scenarios where someone wants to un-archive something? 

do we want to offer up user convince to just archive/un-archive all history in one go:
`UPDATE history SET archive = 1` / `UPDATE history SET archive = NULL`

as i quickly found that i wanted to basically archive everything as I have a long running sab db with 20k rows.. and doing 250 items at a time per page in the gui was going to take way too long.

**Comment by Safihre** [comment]
> right now when you go to delete an item from the archive, it doesnt make too much sense to still offer up the ability to still archive (not perm delete). minor quibble, but could just gray out like gmail does.

Yeah but using multi-edit you could have both History and Archived items selected. However, if you are on the Archive page it should be selected by default.

> there is prob scenarios where someone wants to un-archive something?

Yeah.. Don't know yet how to solve that.

> do we want to offer up user convince to just archive/un-archive all history in one go: `UPDATE history SET archive = 1` / `UPDATE history SET archive = NULL`
> as i quickly found that i wanted to basically archive everything as I have a long running sab db with 20k rows.. and doing 250 items at a time per page in the gui was going to take way too long.

You could use the History Retention for that, setting it shortly to 1 Day or 1 Item. Will probably get that working today or tomorrow.

**Comment by Safihre** [comment]
Added the History Retention options.
Might just leave the Scheduler, only add it if someone asks for it.

**Comment by Safihre** [comment]
@thezoggy Let me know if you find any more things that don't work or need to be improved about this.

**Comment by Safihre** [comment]
Implemented a4540b8debabc33d4a00edad3441dcce097c40cc
