### ISSUE TITLE
[BUG] Wrong archive password is used for Retry when unpacking failed

### ISSUE THREAD

**Issue by ArchBertus** [sabnzbd/sabnzbd#2790]
### SABnzbd version

4.2.1 and 4.2.2

### Operating system

Synology

### Using Docker image

linuxserver

### Description

To reproduce:
Download a NZB, while downloading enter the wrong archive password "X". Wait until the download finished and unpacking fails with message "Trying to unrar with password "X". Press Retry, enter correct password "Y" in the optional password field. Sabnzbd will retry unpacking with password "X", resulting in another fail.

Good work, HTH!

**Comment by Safihre** [comment]
Thank you for reporting, indeed a clear bug!
Fixed it!
