### ISSUE TITLE
Postprocess Scripts no longer selectable since 4.2.2

### ISSUE THREAD

**Issue by Apex-DE** [sabnzbd/sabnzbd#2791]
### SABnzbd version

4.2.2

### Operating system

macOS

### Using Docker image

None

### Description

I updated to 4.2.2 (skipped 4.2.1, was on 4.2.0 before) and my postprocess scripts are no longer selectable in the webinterface ("when finished")
Re-Selected the Folder with the Scripts, saved the config, restarted - the Scripts are still gone.

**Comment by Safihre** [comment]
They moved already in 4.2.0 to Config Specials. It's in the release notes.

**Comment by thezoggy** [comment]
Please provide debug logs. Click wrench, set logging level to debug. Replicate the issue. Then click wrench > show logging. And share that sanitized log+config.

Usually if it's not showing the scripts it's because of permissions or there is no scripts in the folder...

**Comment by Apex-DE** [comment]
ok, to be a bit clearer: i still can set a script in Config->Switches but i can't set a script "on demand" within the Webinterface directly (not in settings)

**Comment by Safihre** [comment]
That's true, that has been changed. It's now a persitant script that always used. Because this way you can have both a script and one of the other actions, like shutdown.
There's no on demand anymore.

**Comment by Apex-DE** [comment]
thats too bad. Is there any chance to get the old behavior back with a switch? 
I only used scripts "on demand" and never the other options available.

**Comment by Safihre** [comment]
Maybe you can explain your use case why sometimes you need a script and sometimes you don't?

**Comment by Apex-DE** [comment]
i can't send my machine to sleep using the usual system sleep function, i execute a script which does all the magic. If i want to send my machine to sleep after a finished job, i need that script to be executed rather than the system sleep function, which now is the only option that sabnzbd offers.
I always have "special" problems of that kind ;) sigh

**Comment by Safihre** [comment]
You could put the script as a post processing script and assign it to the last job in the queue when you need it?

**Comment by Apex-DE** [comment]
that would be a option. Maybe you can put in a switch to swap the "usual" options against the available scripts? That would be nice.

**Comment by Safihre** [comment]
Unfortunately the use case is too limited for that.

**Comment by Apex-DE** [comment]
OK, i understand.

I tried both available options for sleep and hibernate on my mini m1 with sonoma 14.3.

None of the options does trigger the wanted task. The computer won't sleep when selected nor hibernate when selected.
So, also on my mac i need my scripts. Besides some logging i set my mac mini to sleep via "pmset sleepnow" in that script. Which method are you using in sabnzb?

**Comment by Safihre** [comment]
Then that's the bug we need to fix of course.
Can you open a bug report for that?
