### ISSUE TITLE
Excessive warnings about ignored duplicates from RSS feed

### ISSUE THREAD

**Issue by schumi4** [sabnzbd/sabnzbd#2792]
### SABnzbd version

4.2.2

### Operating system

Debian

### Using Docker image

linuxserver

### Description

Since the update, every automated reading of the RSS feed produces new warnings about ignored duplicates, one for every single item. Ignoring already downloaded entries seems to be intended behaviour and does not warrant a warning in my opinion.

This was not the case in previous versions.

**Comment by Safihre** [comment]
In Config Specials, disable duplicate_warnings.

**Comment by schumi4** [comment]
Of course there is an option there... thank you for the swift response!

**Comment by Safihre** [comment]
On new installations it's disabled right away but I didn't want to mess with existing installations.
