### ISSUE TITLE
setting Sleep or Hibernate in Webinterface doesn't work

### ISSUE THREAD

**Issue by Apex-DE** [sabnzbd/sabnzbd#2794]
### SABnzbd version

4.2.2

### Operating system

macOS Sonoma 14.3

### Using Docker image

None

### Description

setting "sleep or hibernate after finished jobs" in the Webinterface doesn't trigger either of it under macOS, the system stays awake after finished jobs.

**Comment by sanderjo** [comment]
what's in your sabnzbd.log? for example

```
2024-02-03 14:26:30,646::INFO::[notifier:197] Send to NotifyOSD: SABnzbd / Queue finished
2024-02-03 14:26:30,661::INFO::[postproc:1108] Queue has finished, launching action: <function system_hibernate at 0x7f738b2d6170> 
2024-02-03 14:26:30,662::INFO::[misc:1276] Performing system hybernation
```

**Comment by sanderjo** [comment]
> setting "sleep or hibernate after finished jobs" in the Webinterface doesn't trigger either of it under macOS, the system stays awake after finished jobs.

And "shutdown" ... does that work?

**Comment by Apex-DE** [comment]
I tested today and it did work with hibernation selected! Shortly before macOS requested permission for some input settings to be allowed, which i granted. For some reason, i didn't see that request made. After allowing sabNZB the permissions it worked. Never mind, sorry.

`2024-02-04 10:18:43,643::INFO::[postproc:1108] Queue has finished, launching action: <function system_hibernate at 0x107632e80> 
2024-02-04 10:18:43,643::INFO::[misc:1321] Performing system hybernation`

**Comment by Safihre** [comment]
Great! Just to be sure, Sleep also works?

**Comment by Apex-DE** [comment]
sleep does not work, i guess that's not supported under macOS as Hibernate sends the system to "sleep" ?

`2024-02-04 13:17:27,649::INFO::[postproc:1108] Queue has finished, launching action: <function system_standby at 0x107632f20> 
2024-02-04 13:17:27,649::INFO::[misc:1332] Performing system standby`

**Comment by Safihre** [comment]
The code is here and it seems we also use some system call. Hibernate and standby call the same command indeed. But both should work.
https://github.com/sabnzbd/sabnzbd/blob/60e1dfb380ac7dfc27ddbeb7a4066e1d998db0b6/sabnzbd/powersup.py#L92

**Comment by Apex-DE** [comment]
my last test with hibernate after finish kept my mac mini awake also. Weird. Sometimes it works, sometimes not.
I now know why i used the sleep script on macos ;)

"pmset sleepnow" on console/script always works.

**Comment by Safihre** [comment]
I used that command now.
Can you try the new build? Because it's not notarized you'll have to right click SABnzbd and select Open for it to start.
Could you also try if shutdown does work for you?

https://github.com/sabnzbd/sabnzbd/actions/runs/7784387010

**Comment by Apex-DE** [comment]
Tested: Hibernate worked three times in a row now. So it seems to be fixed :-D

nextup i will test shutdown...

**Comment by Apex-DE** [comment]
Shutdown worked, at least one time ;)
mainly, hibernate works at all tests.

**Comment by Safihre** [comment]
Awesome, thanks 🤗
