### ISSUE TITLE
Better error message(s) for users mixing up newsservers and indexers. Better than "[Errno 99] Invalid server address."

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#2802]
### Description

(New) users mix up newsservers and indexers. And SAB refuses that with an error message "[Errno 99] Invalid server address.", after filling out "nzbfinder.ws" as Host. For example: https://www.reddit.com/r/usenet/comments/1alt557/stuck_adding_host_to_sabnzbd/

IMHO better if SAB would say "not a valid newsserver". SAB could even know it's an indexer, and say "that looks like an indexer, not a newsserver" or "You must fill out a newsservers, not an indexer or webpage"

Also where in that page does it say "newsserver"? Just "Server" and "Host". Too abstract wording?

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/3aa61816-2db3-46cb-8daa-e5bf31c827de)

**Comment by sanderjo** [comment]
![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/6e777eef-dc45-4559-98ff-760343df5946)

... then Add Server ...
```
2024-02-16 20:05:23,883::DEBUG::[happyeyeballs:136] Available addresses for www.nzb.su (port=563, IPv4 and IPv6): 1 IPv4 and 0 IPv6

2024-02-16 20:06:23,887::DEBUG::[happyeyeballs:179] Failed Happy Eyeballs lookup: No addresses could be resolved
2024-02-16 20:06:23,946::DEBUG::[happyeyeballs:88] Happy Eyeballs failed to connect to 209.208.67.181 (nzb.su) in 60062ms
```
so after a minute waiting:

```
Incorrect parameter
Server address "www.nzb.su:563" is not valid.
```

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/d3978114-93bf-4380-8a30-679cc2573323)

I think we can do better:
* no 60 seconds timeout, but 5 seconds
* host does resolve, but no NNTP(s) connection: "not a newsserver"
* or ... have a list of well-known newsservers and indexers, and check against that list.

PS

Test Server gives quicker result, but still confusing:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/52f157b0-dbfa-41b3-a660-0410789ab6ef)

**Comment by thezoggy** [comment]
I would vote no to making a list of indexers.

**Comment by sanderjo** [comment]
> I would vote no to making a list of indexers.

... because ...

**Comment by thezoggy** [comment]
People don't want their sites documented nor do we want to give others ammo about what sites sab works with.

**Comment by sanderjo** [comment]
If a nntp(s) connection does not work, but http(s) does, SAB could say "not a newsserver, but a webserver. Not good"

The Test Server gives a nice in-GUI message in case of a wrong newsserver, but the Add Server dumps you in an ugly html1.0 / text screen of SAB

I would make the timeout even lower than 10seconds. 5 seconds should be enough?

**Comment by OneCDOnly** [comment]
> Agreed. We can add an additional message, just like we do for SSL errors. Rewording: "Could not open connection to %s:%s. Make sure you are connecting to a news server and not to an indexer." Any suggestions welcome.

And include a link to a wiki page explaining the difference between the two in plain-language (whichever language you use)? 💡

**Comment by Safihre** [comment]
I like the check for port 80, smart. Will work on that.
The ugly html page is a last resort check for users that skip the Test Sever button, preventing them (hopefully) from entering bad hosts.

Maybe a link isn't a bad idea 😅

**Comment by sanderjo** [comment]
> The ugly html page is a last resort check for users that skip the Test Sever button, preventing them (hopefully) from entering bad hosts.

Is this possible: when user clicks Add Server: always let SAB first do the test-server-test. If that fails: show the nice error message, within the GUI. If the test succeeds: indeed add the server

**Comment by Safihre** [comment]
Implemented these 2 changes:

1. `Add Server` is disabled until `Test Server` is successful. 
2. If during `Test Server` the connection fails to the defined port, try port 80. If that succeeds, show: 
![image](https://github.com/sabnzbd/sabnzbd/assets/5703454/0d64efdf-e77a-4c4b-86c4-dce1be8a9eda)
Otherwise the usual error:
![image](https://github.com/sabnzbd/sabnzbd/assets/5703454/e3c6f7f5-b38f-4ab7-a66d-edb9ae71b17e)

**Comment by sanderjo** [comment]
Perfect. Thank you!
