### ISSUE TITLE
Error code 451 should be treated like 430

### ISSUE THREAD

**Issue by ShaneMcC** [sabnzbd/sabnzbd#2807]
### SABnzbd version

4.2.2RC1-35-gb1a9ff708

### Operating system

Linux

### Using Docker image

None

### Description

Some providers such as giganews return error code 451 instead of 430 for some removed articles (https://support.giganews.com/hc/en-us/articles/9952660678285-What-are-errors-430-and-451)

At the moment, sabnzbd just ignores this response and the article request eventually times out and is retried a few times before being abandoned and allowing other servers to try the article.

This code should be treated the same as 430.

It may also be worth having some better handling for unknown error codes rather than just timing out despite the server actually responding.

**Comment by Safihre** [comment]
Are you slated to Giganews?
If so, are you aware of other codes we are missing that could be outputted by Giganews?
Strange that this was never reported before...

**Comment by ShaneMcC** [comment]
I'm not - just a regular user.

I noticed the issue when migrating from nzbget (back) to sabnzbd.

The built-in test nzbs worked perfectly, then I picked a random nzb to test with and saw it seemingly freezing on sab (as it insisted on timing out every article 3 times on giganews before failing back to alternative servers) so dug into it a bit to see what was actually going on.

**Comment by ShaneMcC** [comment]
I didn't include it in the PR (but happy to add it), but it might be worth adding something like this to `downloader.py` on line 773 to handle other codes:

```python
            else:
                logging.info("%s@%s received unknown status code %s for article %s: %s", nw.thrdnum, nw.server.host, nw.status_code, article.article, nw.nntp_msg)
                done = True
                nw.reset_data_buffer()
```

Then the logs would include something like:

```
2024-02-16 10:04:54,763::INFO::[downloader:774] 5@news.giganews.com recieved unknown status code 451 for article aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: 451 0 <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa> cancelled
```

May want to be a bit smarter about it though (ie handling unknown `2xx` codes differently rather than just treating them all as failures like this would)

**Comment by sanderjo** [comment]
FWIW: From the RFC https://datatracker.ietf.org/doc/rfc3977/#:~:text=October%202006%0A%0A3.2.-,Response%20Codes,-Each%20response%20MUST it seems x5x and thus 451 is undefined? 

So Giganews' "451 will be present when a file cannot be found because it was removed as part of a DMCA request." is a special? But a useful special: DMCA. So "we've been forced to do this; not our fault". I wonder if SAB can do more clever things with this ... like reporting it in the statistics. It might be clearer to users and avoid all kinds of confusion & questions


```
   The first digit of the response broadly indicates the success,
   failure, or progress of the previous command:

      1xx - Informative message
      2xx - Command completed OK
      3xx - Command OK so far; send the rest of it
      4xx - Command was syntactically correct but failed for some reason
      5xx - Command unknown, unsupported, unavailable, or syntax error

   The next digit in the code indicates the function response category:

      x0x - Connection, setup, and miscellaneous messages
      x1x - Newsgroup selection
      x2x - Article selection
      x3x - Distribution functions
      x4x - Posting
      x8x - Reserved for authentication and privacy extensions
      x9x - Reserved for private use (non-standard extensions)
```

**Comment by ShaneMcC** [comment]
At least for now, it would be good to handle the known-and-documented case of "451 is also bad" that giganews is doing (At least it's a `4xx` code still) then consider extra logging for other codes (to help other people in future if another server decides to use yet-another different code), and perhaps some generic handling of `4xx` or others)

**Comment by sanderjo** [comment]
Ah, it's a loan / inheritance from HTTP: "HTTP 451 Unavailable For Legal Reasons "

https://en.wikipedia.org/wiki/HTTP_451

Cool.

**Comment by Safihre** [comment]
> I didn't include it in the PR (but happy to add it), but it might be worth adding something like this to `downloader.py` on line 773 to handle other codes:
> 
> ```python
>             else:
>                 logging.info("%s@%s received unknown status code %s for article %s: %s", nw.thrdnum, nw.server.host, nw.status_code, article.article, nw.nntp_msg)
>                 done = True
>                 nw.reset_data_buffer()
> ```
> 
 I think we should add that indeed. But make it a warning (with translation).
So like this:
```python
            else:
                logging.warning(T("Thread %s@%s: Unknown status code %s for article %s: %s"), nw.thrdnum, nw.server.host, nw.status_code, article.article, nw.nntp_msg)
                done = True
                nw.reset_data_buffer()
```

**Comment by sanderjo** [comment]
> maybe even add a 'please report' or something along those lines in that msg

Report to whom? SAB dev? News provider?

**Comment by Safihre** [comment]
Report to us.
But the user's screen will be full of warnings so I assume they'll flock to the support channels to ask why.
In the mean time I asked our friends at Newshosting if they could give me a list of all the NNTP codes they use to check it against the ones we know.

**Comment by thezoggy** [comment]
I looked last night around and rfc spec, 45x is not used. So it looks to be only giganews that does this as about a year ago.

**Comment by ShaneMcC** [comment]
I've rebased my PR against changes made earlier today in the same area (d2c6c6e564499a608cefd1641886a141de26363f) and added a warning log for unknown status codes as discussed.

This should stop sab stalling and timing out in future if another code is added by some provider.

Right now i'm just treating unknown codes the same as "article not found" rather than trying to guess what to do with it

**Comment by ShaneMcC** [comment]
Looking at nzbget (https://github.com/nzbgetcom/nzbget/blob/develop/daemon/nntp/ArticleDownloader.cpp#L418) this should behave fairly similarly now.

They basically treat any code starting with a `2` as a success and anything else is an error (this function looks to used to check responses to any command they send, so is a bit looser as to what it will accept as "success")

**Comment by Safihre** [comment]
Yeah we try to be all smart about it and show better messages for specific error codes 😅

**Comment by Safihre** [comment]
For reference, Newshosting's list:
```
100 Legal Commands – start of multi-line response to the HELP command

101 Capabilities list: - start of multi-line response to the CAPABILITIES command

111 <date> - response to the DATE command

200 or 201 – response to “MODE READER”. Will indicate if the user is allowed to POST articles

205 Goodbye – response to QUIT command

211 list of article numbers follow – Response to LISTGROUP command

211 – response to GROUP command

211 – response to the GROUP command

215 NewsGroups Follow – Response to LIST command

215 Order of fields in overview database. – response to LIST OVERVIEW.FMT

220 – successful response to ARTICLE command

221 – response to XHDR command

221 – successful response to HEAD command

222 – successful response to BODY command

223 – successful response to STAT command

224 Overview Information Follows – response to XOVER command

224 overview information follows – response to XOVER command

230 list of new articles by message-id follows – response to NEWNEWS command – no lines will be returned

231 list of newsgroups follows – response to NEWGROUPS command though generally no newsgroups are listed

240 Article Posted – successful POST command response

281 OK – Successful authentication

290 Feature Enabled – Response to a successful XFEATURE COMPRESS GZIP [terminator] command

340 Send Article to be Posted – response to initiating a POST command

400 DENIED – if there is an internal issue related to authentication. Sent in response to AUTHINFO commands

400 Unrecognized Command

411 No Such Group – response to GROUP command where group doesn’t exist

412 No Group Selected – If a command requiring a current selected group is issued when no current group is selected

420 No articles selected – Response to an xover command where the given range doesn’t intersect with any articles in the current group

421 no next article in this group – response to NEXT command

422 no previous article in this group – response to LAST command

430 No Such Article – A variety of commands can return this

440 Posting Not Available at this time

440 posting not allowed – Possible response to POST command

441 Posting Failed. – unsuccessful POST command response

480 Authentication Required – command for articles submitted before successful AUTHINFO

500 Syntax Error – an internal failure relating to interpretation of a received command

501 Bad Command Usage – there is a syntax error in the command sent in

501 Please disconnect and reconnect to change username – sent if multiple AUTHINFO USER/PASS commands are received on the same session

501 command syntax error

502 Authentication Failed

502 System Error – an internal failure of some kind has occurred

503 – An internal failure
```
