### ISSUE TITLE
Don't showing history details

### ISSUE THREAD

**Issue by Slava46** [sabnzbd/sabnzbd#2815]
### SABnzbd version

SABnzbd 4.2.3RC2

### Operating system

Windows 11

### Using Docker image

None

### Description

Hi, for SABnzbd 4.2.3RC1 and RC2 when I click on something downloaded in history nothing happening but should showing details of downloads.

For SABnzbd 4.2.2 and previous versions all were fine.

**Comment by Slava46** [comment]
> Have you tried a different browser?
Tried now and seems in Chrome it's showing, but in last FF not showing.

**Comment by thezoggy** [comment]
Please use one of the support channels: [forums](https://forums.sabnzbd.org/), [subreddit](https://www.reddit.com/r/SABnzbd/), [discord ](https://discord.gg/KQzDe7fvNU), or [IRC](https://sabnzbd.org/live-chat.html#) for support/questions.

also if your going to file a bug on github please do provide the required info and logs. so for browser issues you would share things like browser version not just generic name. also with any browser type issue make sure your not just running into an issue with your extensions/addons like adblockers coming into the mix.

**Comment by Slava46** [comment]
Yeah, Firefox v. 123.0 last stable.
Adblock etc disable.

**Comment by thezoggy** [comment]
testing with win 10 and firefox 123, history showing just fine here.  have you tried clearing browser cache/cookies?
