### ISSUE TITLE
sabnzbd does not unrar anymore

### ISSUE THREAD

**Issue by phit42** [sabnzbd/sabnzbd#2823]
### SABnzbd version

SABnzbd version: 4.2.3

### Operating system

Docker

### Using Docker image

linuxserver

### Description

With no known changes, suddenly SAB does not unpack any downloads anymore that contain rar archives. Rar files (usually split out into multiple .rar, .r01, .r02 etc) are placed unpacked and unchanged in the correct complete folder.
Other archives do work fine.
Manual unpacking of said downloads works without any issue. (Obviously archives are not password-protected, and no permission errors appear anywhere.)

Excerpt from a sab log: https://pastebin.com/Hcws2JQ9 

I cannot find any error message besides the statement "0 Datei(en)/Ordner entpackt in 0 Sekunden".

**Comment by Safihre** [comment]
It's a problem with linuxserver image.
See https://github.com/linuxserver/docker-sabnzbd/issues/219

Might be good to also raise another issue there so they are aware that the problem is present for multiple users.

**Comment by sanderjo** [comment]
@phit42 did you get a warning in the GUI about wrong version of unrar (unrar 0.0)? I would expect that, as unrar seems to crash on old hardware ... which would lead to SAB not getting a unrar version.

Not sure, so checking with you.

**Comment by Safihre** [comment]
From another report, it is able to print the version but only crashes when starting any unpack action.

**Comment by thezoggy** [comment]
its a known issue for those running really old cpu where they get illegal instruction..   hotio/lsio have both seen it (alpine musl)
the fix for lsio users is to just use the dockermod to load up the unrar 6 https://github.com/linuxserver/docker-mods/tree/universal-unrar6

**Comment by phit42** [comment]
Thank you all for the quick pointer in the right direction and the potential workaround/resolve, I'll try the dockermod now.
@sanderjo yes it is old, ds712+ x86_64 aka intel atom d425, but never had any issues. unrar also printed the version 7.00 just fine in the log without any error messages, no illegal instruction.

**Comment by thezoggy** [comment]
> Thank you all for the quick pointer in the right direction and the potential workaround/resolve, I'll try the dockermod now. @sanderjo yes it is old, ds712+ x86_64 aka intel atom d425, but never had any issues. unrar also printed the version 7.00 just fine in the log without any error messages, no illegal instruction.

the help doesnt try to use the instructions which is why its fine, but if you would have tried to just run the actual command sab does to extract something .. youd see it. 

from a recent DS412+ user on discord, (which has intel atom d2700)
```
<REMOVED>:/usr/bin# /usr/bin/unrar x -idp -scf -o- -or -ai -p- /data/usenet/complete/_UNPACK_test_download_100MB/

UNRAR 7.00 freeware      Copyright (c) 1993-2024 Alexander Roshal
Illegal instruction (core dumped)
```

**Comment by aacater** [comment]
I also encountered this problem, I am not using docker. I think it was caused by me using `unrar-free`. I was able to fix the problem by installing the nonfree version of `unrar`.
