### ISSUE TITLE
Build failure because of missing appstream

### ISSUE THREAD

**Issue by francoism90** [sabnzbd/sabnzbd#2827]
### SABnzbd version

4.2.3

### Operating system

Linux

### Using Docker image

None

### Description

See:
- https://buildbot.flathub.org/#/builders/25/builds/13346
- https://github.com/flathub/org.sabnzbd.sabnzbd/pull/36#issuecomment-1948445643

Unfortunately this would require a new version bump. Is this possible?

Thanks!

**Comment by Safihre** [comment]
I don't get it? The 4.2.3 version is there?

**Comment by francoism90** [comment]
@Safihre This file needs to be fixed according to the linter: https://github.com/sabnzbd/sabnzbd/blob/develop/linux/org.sabnzbd.sabnzbd.appdata.xml

But you need to generate a new build.

**Comment by francoism90** [comment]
@Safihre I've added a patch on the Flathub package for the current package, so I'll wait till it get fixed in the next release. :)

**Comment by thezoggy** [comment]
Recently we've had users using flatpak and then run into issues where sab things they have no free space but in reality their /mnt are just read only. Any way to have our flatpak by default make /mnt read+write without having users to use flatseal?

**Comment by francoism90** [comment]
@thezoggy See https://github.com/flathub/org.sabnzbd.sabnzbd/blob/master/org.sabnzbd.sabnzbd.yaml

This controls the r/w permissions, and the following are set by default:
```bash
  - --filesystem=xdg-download
  - --filesystem=/media
  - --filesystem=/run/media
```
I can add more, as seen here: https://github.com/flathub/tv.kodi.Kodi/blob/3889b0f58ed02bc4f4b708d608c94294b5099248/tv.kodi.Kodi.yml#L14

You should have rw permissions to the Flathub repo, so you could also add them yourself. :)

However, I would encourage users to use something like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal). Sometimes having full access to `/mnt` is unwanted, but I'm happy to add more paths if requested. :)
