### ISSUE TITLE
sab and in-app restart with docker

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2835]
### Description

generally you dont update/restart/do much with the app when you run it in a container like docker as you let the docker itself manage the life cycle of the app. however we do push restarting the app on people at times in our config or people just dont know better and restart sab there themselves..  and noticed that sab 'breaks' (basically doesnt fully restart) so gui isnt working. 

after some debugging we found that restarting sab via glitter (just calling api restart) seems to always work just fine.
when you go to config>general and restart there.. that one will cause it sometimes for sab to get stuck and you have to rebuild the container to fix.

the other quirk restarting from the config>general is that we try to handle the scenario if users change http/https ports.. or enable http->https.. so on that restart we redirect them to the host:http port that we have in sab config..but that port not actually be what the user is using (as docker maintainers would use 8080 inside the container but users then remap outside container that port to something else) thus sab is redirecting them 8080 because thats what it knows and is wrong.

docker maintainer dev:
> OK so this is interesting. If I recreate the container then the restart works from either the hamburger or the config/general page until the first time I do a restart from the config/general page (which works) but then any further restart attempts hang.
> So I can restart endlessly from the main page and it always works
> But as soon as I restart from config/general any subsequent restart attempt hangs until I recreate the container
>  I wonder if it's related to the redirect being wrong
>  If you restart from the homepage it refreshes the page correctly, but from config/general it tries to redirect to, in my case, http://sabnzbd.hostname:8080 which is not the URL I'm accessing it from and not one that would work under any circumstances.

--

so to fix this i'm suggesting that we just leverage the `sabnzbd.DOCKER` to know if sab is being ran in docker.
and if so then have our config restart be 'dumb' and restart like glitter does (just calling api command restart) rather than the config js do_restart method that tries to do redirect logic and more.

**Comment by Safihre** [comment]
I'm a bit surprised by this, because the `do_restart` already checks if the HTTPS setting or the port changed and only then does logic. If those 2 are not changed, it just reloads the current URL.
Why does dat not work on Docker?
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Config/templates/staticcfg/js/script.js#L266-L267

Oh, I see now. My change to make correct Javascript comparison broke things.
`$('#port').val() === $('#port').data('original'))` broke because `$('#port').val()` returns string while `$('#port').data('original'))` returns int.

I will fix that.

**Comment by Safihre** [comment]
So what should it do on Docker then, if the user does decide to change the port settings? Because they should never do that..
Do we really need special logic for that?

**Comment by thezoggy** [comment]
> I'm a bit surprised by this, because the `do_restart` already checks if the HTTPS setting or the port changed and only then does logic. If those 2 are not changed, it just reloads the current URL. Why does dat not work on Docker? https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Config/templates/staticcfg/js/script.js#L266-L267
> 
> Oh, I see now. My change to make correct Javascript comparison broke things. `$('#port').val() === $('#port').data('original'))` broke because `$('#port').val()` returns string while `$('#port').data('original'))` returns int.
> 
> I will fix that.

ill have to see if this fixes the issues the lsio dev get reports of with restart..  

on a side note, apps like sonarr/radarr recently added "Hide reboot and shutdown UI buttons on docker" to try and prevent that from causing odd issues and triggering multiple instances warnings that can come from it.

**Comment by thezoggy** [comment]
> So what should it do on Docker then, if the user does decide to change the port settings? Because they should never do that.. Do we really need special logic for that?

Ideally users shouldnt change the port inside the app, they would remap the port exposed (host port, not container port). as many docker maintainers hardcode sab host and the port and if you change it, it can break the container because their startup init expects it to be set to what they want..

**Comment by sanderjo** [comment]
> > So what should it do on Docker then, if the user does decide to change the port settings? Because they should never do that.. Do we really need special logic for that?
> 
> Ideally users shouldnt change the port inside the app

I agree. I propose: if SAB in docker, do not allow the user to change the listening port (at least: via GUI). As it is not what the user intends to do.

**Comment by thezoggy** [comment]
even something as simple as adding disabled=disabled to the input field for host/port fields if sabnzbd.docker is set would prob work well to prevent normal user mistakes. and hopefully they would then read their docker maintainer docs about how they should just update their docker compose/settings instead

**Comment by Safihre** [comment]
Wonder if we should also trigger this when on the command line the `--server` parameter is specified. Because in that case it will always overrule what is in the sabnzbd.ini.

**Comment by Safihre** [comment]
Hmm, but when using Docker like Linuxserver you can set as many ports and do the mapping any way you like. 
So what about users that do have a valid reason to set a different port?
We want to force them to manually edit their `sabnzbd.ini`?

**Comment by sanderjo** [comment]
> Hmm, but when using Docker like Linuxserver you can set as many ports and do the mapping any way you like.

"as many"?

` -p 8080:8080` ... just one. Or do you see / mean something else?

LSIO documentation should be clear to always keep the internal port (=second port number) on 8080 in that docker config parameter

> So what about users that do have a valid reason to set a different port?

I think there is no valid reason to change the inside port of SABnzbd inside a docker container: always 8080. Also if your outside port is 80, 443, 9999, 44444, or whatever.

**Comment by Safihre** [comment]
The recommended and common way is to use Docker compose and not the command line.
You can specify multiple ports there in easy fashion, for example to have https on different port. https://hub.docker.com/r/linuxserver/sabnzbd

**Comment by sanderjo** [comment]
I have the idea I don't understand you or the discussion, but let's try anyway:

> The recommended and common way is to use Docker compose and not the command line.

OK. Does that change my statement?

> You can specify multiple ports there in easy fashion, for example to have https on different port.

Yes. On the outside port, right?

**Comment by Safihre** [comment]
Closing this, now that we resolved the redirect.
