### ISSUE TITLE
Keep winget version updated?

### ISSUE THREAD

**Issue by n-ster** [sabnzbd/sabnzbd#2836]
### Description

Currently latest version on winget repo is 4.1.0, could we have some kind of automation to keep the winget repo updated please?

Last winget repo request: https://github.com/microsoft/winget-pkgs/pull/121029
Manifest location: https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/SABnzbdTeam/SABnzbd
4.2.3 update request: https://github.com/microsoft/winget-pkgs/issues/150214

**Comment by CoolPlayLin** [comment]
Hello, I have pushed some new commits to make this package publish to winget automatically.
- CoolPlayLin/AutoPublish#26
