### ISSUE TITLE
Delete nzb's from watched folder to waste-bin

### ISSUE THREAD

**Issue by CpV99** [sabnzbd/sabnzbd#2842]
### Description

When I download nzb files to the watched folder, they are deleted after they have been processed. 
But they are not deleted to the waste-bin. When I want to process the nzb files again, it would be helpful if they are recoverable from the waste-bin. 
Is it possible to delete the nzb files to the wasite-bin?

**Comment by Safihre** [comment]
Interesting. Not sure if more people would be interested in this.

For now, if you enable the NZB backup folder in Config Folders, you also have a backup in case you want a Retry!

**Comment by CpV99** [comment]
Ok, I will enable the backup folder. 

The difference with the waste-bin is that I have to clean up the backup folder regularly, but it is a solution to the problem.

 

Thanks,

Kees.

 

Van: Safihre ***@***.*** 
Verzonden: zondag 28 april 2024 20:51
Aan: sabnzbd/sabnzbd ***@***.***>
CC: CpV99 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [sabnzbd/sabnzbd] Delete nzb's from watched folder to waste-bin (Issue #2842)

 

Interesting. Not sure if more people would be interested in this.

For now, if you enable the NZB backup folder in Config Folders, you also have a backup in case you want a Retry!

**Comment by thezoggy** [comment]
Yep, definitely always just set nzb backup folder in case I ever needed to retry something or use for dupe detection..  and then of course can micromanage with crown to delete stuff older than x mtime or whatever criteria
