### ISSUE TITLE
archive - additional options

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2848]
### Description

tossing quick note here from discord discussion of archive feature

user used to remove jobs after x days but with the archival feature and apps now archving stuff.. hes got stuff archived and some stuff not. 

User wants 'delete ARCHIVED jobs after specified number of days'
While our option is only to move jobs to archive after x days, but he wants to delete instead. So another option? or we just add a checkbox there "include archive" to augment that option so it removes archive+non-archive when we remove jobs...

I went to offer up using scheduler but looks like we never added that bit over there to  move stuff to archive or delete archive history with it. So another piece to add to give flexibility there..

**Comment by Safihre** [comment]
> User wants 'delete ARCHIVED jobs after specified number of days'
While our option is only to move jobs to archive after x days, but he wants to delete instead. So another option? or we just add a checkbox there "include archive" to augment that option so it removes archive+non-archive when we remove jobs...

The `Delete jobs if the history exceeds specified number of jobs` and `Delete jobs after specified number of days` delete from both History and Archive, not just from History. Do we really need to split this up? I don't see why..

I will add `disable_archive` flag for users that always want to skip the Archive.

**Comment by thezoggy** [comment]
> > User wants 'delete ARCHIVED jobs after specified number of days'
> > While our option is only to move jobs to archive after x days, but he wants to delete instead. So another option? or we just add a checkbox there "include archive" to augment that option so it removes archive+non-archive when we remove jobs...
> 
> The `Delete jobs if the history exceeds specified number of jobs` and `Delete jobs after specified number of days` delete from both History and Archive, not just from History. Do we really need to split this up? I don't see why..
> 
> I will add `disable_archive` flag for users that always want to skip the Archive.

Gotcha, we just have some items that call out archive and some that dont. If those items cover history+archive then it might just be a wording thing that confused the user.  

Ack on the disable_archive flag, i assume this will be special option ?

**Comment by Safihre** [comment]
You're right, I'll update the wording!
Would there be a benefit of adding `Delete jobs from the archive after specified number of days` if there's already history+archive? 
Same for `Delete jobs if the archive exceeds specified number of jobs`?

**Comment by thezoggy** [comment]
im sure there is someone out there that wants to micromanage archive vs non-archive... which is why when i first saw the option i was thinking damn it only does one.. guess we need to add the other (not knowing it covered both).

so we are prob good there on not adding more options as I dont want to make it more confusing than it needs to be.. 
when i first thought of us adding the archive stuff to the history retention option i thought it was going to keep our original stuff and just add a checkbox. so that way archive was included or not on the relevant option. 

but is it worth the rework now ?

**Comment by Safihre** [comment]
Do we still need additional Scheduler options?
Only the `Remove Archived jobs`?

**Comment by thezoggy** [comment]
> Do we still need additional Scheduler options? Only the `Remove Archived jobs`?

i say we are good for now.
