### ISSUE TITLE
Defunct process

### ISSUE THREAD

**Issue by John-Gee** [sabnzbd/sabnzbd#285]
Hello,

I am not sure if the issue is within sabnzbd or my configuration, but I thought I'd post here just in case.
For the past few months, when sabnzbd (v 0.8) crashes, it leaves behind a defunct process that through my systemd services become a child of PID1 so cannot be killed.
It also seems to still be connected to its ports as netstat show them still in use and restarting sabnzbd's service gets sabnzbd to run on a different port.

I don't see anything of values in the log though.
Example:
Last lines of logs:
"2015-08-16 16:15:57,724::DEBUG::[interface:423] API-call from 127.0.0.1 [curl/7.44.0] {'apikey': u'XXXXXXXXXXXXXXXXXXXXXXX', 'mode': u'shutdown'}
2015-08-16 16:15:57,745::INFO::[__init__:364] SABnzbd shutting down...
2015-08-16 16:15:57,745::DEBUG::[__init__:371] Stopping URLGrabber
2015-08-16 16:15:57,745::INFO::[urlgrabber:61] URLGrabber shutting down
2015-08-16 16:15:57,745::DEBUG::[__init__:378] Stopping dirscanner"

That would look good right? but then in ps:
"USER      1309     1  6 Aug15 ?        01:10:43 [python2] <defunct>"

and netstat on 8085 (the post used by sabnzbd in my case):
"tcp        0      0 127.0.0.1:8085          0.0.0.0:*               LISTEN      -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33770         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33827         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33837         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:54449         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33840         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:54288         CLOSE_WAIT  -                   
tcp        0      0 127.0.0.1:54587         127.0.0.1:8085          ESTABLISHED 3141/chromium       
tcp        0      0 127.0.0.1:8085          127.0.0.1:54587         ESTABLISHED -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33849         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:33848         CLOSE_WAIT  -                   
tcp        1      0 127.0.0.1:8085          127.0.0.1:54590         CLOSE_WAIT  -" 
(forget the chromium line, it's just the browser open on it, though it does not work)

In case it matters, here's my service file:
"[Unit]
Description=NZB Grabber
After=NetworkManager-wait-online.service

[Service]
Type=simple
ExecStart=/usr/bin/sabnzbdStart
ExecStop=/usr/bin/sabnzbdStop
Restart=always
RestartSec=10
User=user
Group=users
TimeoutSec=150

[Install]
WantedBy=multi-user.target"

and the start and stop scripts:
"ionice -c 3 -p $$
renice -n 10 -p $$
/usr/bin/python2 /opt/sabnzbd/SABnzbd.py -f ${HOME}/Media/sabnzbd "${@}" > /opt/sabnzbd/mylog 2>&1"
"curl -s "http://localhost:8085/sabnzbd/api?mode=shutdown&apikey=XXXXXX"

Thanks!

**Comment by shypike** [comment]
I'm a bit surprised to see that SABnzbd isn't started in daemon mode.
In server situations we recommend to use the --daemon option.
Or this this option already passed with the "${@}" construct?

**Comment by John-Gee** [comment]
Oh no it isn't.
I will switch to this and report if it makes a difference, thank you!

**Comment by thezoggy** [comment]
@John-Gee can you try again with latest sab 0.8.x?

**Comment by John-Gee** [comment]
I haven't had any issue since I reported this.
Up till a few minutes I was on Beta1, just updated to Beta3 but I'm assuming it'll be the same so I guess --daemon (with a pidfile) did the trick.

Thanks!
