### ISSUE TITLE
upgrade removed my custom desktop shortcut (did not replace)

### ISSUE THREAD

**Issue by rbenard1** [sabnzbd/sabnzbd#2850]
### SABnzbd version

4.3.0 [b07b434]

### Operating system

win 11 64bit

### Using Docker image

None

### Description

upgrade version: 4.3.0 [[b07b434](https://github.com/sabnzbd/sabnzbd/commit/b07b434)] removed customized desktop shortcut for the program.

**Comment by Safihre** [comment]
Did you check Dekstop Shortcut in the Installer options?

**Comment by rbenard1** [comment]
No and one I had was customized with large .ico file.  Many upgrades,
indeed first that removed a desktop icon. Not major just had to rebuild
the. shortcut

**Comment by Safihre** [comment]
Because setting a Desktop icon is an installer option, we first remove the icon and then restore it.
This is not really the most optimal, but the code we had previously would sometimes fail to remove the Desktop shortcut.
I don't think I can fix this at the moment.

**Comment by rbenard1** [comment]
Thanks for checking it out. Nothing was ‘restored’ in this case. Just hit the upgrade button on the web interface page.
