### ISSUE TITLE
Allow using same folder for TEMP and COMPLETED downloads

### ISSUE THREAD

**Issue by ryehamstrawberry** [sabnzbd/sabnzbd#2852]
### Description

Please consider implementing the ability to use the same folder for both TEMP and COMPLETE downloads since this is currently not permitted.

It isn't a unique concept, many other applications allow this.
Unsure why this isn't allowed, it seems quite arbitrary. 

If this isn't possible, an explanation would be appreciated.

**Comment by Safihre** [comment]
Because of the many different ways you can configure download folders, including Sorting and unpack-without-subfolders. It just creates too many spots where filenames of ongoing downloads can overlap with completed ones.

So I return the question: why do you need them in the same folder? You don't need to really check the temp folder, only the Complete is what matters. The temp folder can be anywhere on the disk, just being there.

**Comment by ryehamstrawberry** [comment]
> So I return the question: why do you need them in the same folder? You don't need to really check the temp folder, only the Complete is what matters. The temp folder can be anywhere on the disk, just being there.

It's not that anyone *NEEDS* their temp files to write to their final download folder, but it's certainly a nice quality of life improvement.
More efficient. Less redundancy by not requiring a separate temp folder. Who likes unnecessary folders saved everywhere?

Another use case: for users that may need to change their download directory often (think servers with new constant new storage), it's a huge PITA to be forced to fuss with creating unnecessary temp folders over and over.

If you're confident this would break SABnzbd, maybe you could implement a "use at own risk" option that would allow use of same temp+complete location for user's that keep organized, clean incoming/completed folders that aren't just unattended cesspools of downloaded files.

This isn't an issue for other P2P applications/download managers that allow multiple incoming downloads to a final location without the incoming downloads being temporarily stored elsewhere. I see no reason how SABnzbd is functionally different.
All of these managers/p2p apps allow numerous concurrent downloads without the interference you mention.
Even for download managers that have the option to automatically unpack.

This has been my only annoyance with SABnzbd over the years, but otherwise it's a great app and I'm grateful for your work.
Just a friendly suggestion, maybe you can figure something out.

**Comment by thezoggy** [comment]
sab downloads to incomplete and extracts/moves to complete folder. you can of course shove both within the same mount/drive, and many people do. for performance reasons you really shouldnt as you want to segment disk io. 

if you think you know better, feel free to fork sab and proceed at your own risk.

**Comment by Safihre** [comment]
So, with our current experiences of people getting into trouble when mixing Complete/Incomplete and the limited (none?) benefit of having 1 folder. I will close this feature request.
