### ISSUE TITLE
Paho-mqtt requirement too new for Apprise MQTT 

### ISSUE THREAD

**Issue by ukmoose** [sabnzbd/sabnzbd#2855]
### SABnzbd version

4.3.1 [41de133] 

### Operating system

 Alpine 3.19

### Using Docker image

linuxserver

### Description

I've been trying to get MQTT notifications working using Apprise Notifications. When I try testing the connection it fails with the following messages:

```
ERROR There are no service(s) to notify
ERROR Could not load MQTT Notification URL: mqtt:{redacted}
```

If I get a terminal in the docker image and use apprise on the command line I get further information

```
Exception ignored in: <function Client.__del__ at 0x7f1756036170>
Traceback (most recent call last):
File "/usr/local/paho/mqtt/client.py", line 874, in __del__
self._reset_sockets()
File "/usr/local/paho/mqtt/client.py", line 1133, in _reset_sockets
self._sock_close()
File "/usr/local/paho/mqtt/client.py", line 1119, in _sock_close
if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
```

which is the same as [https://github.com/caronc/apprise/issues/1078](https://github.com/caronc/apprise/issues/1078) which suggest it is due to the version of paho-mqtt being v2.0.x rather than v<2

sabnzbd/requirements.txt has paho-mqtt==2.1.0 (line 61)

**Comment by Safihre** [comment]
Will fix!
@caronc are you aware of any other depencies that should be pinned to older versions? I have to exclude them from the Renovate auto updater :)

**Comment by caronc** [comment]
Yes, my [original merge request has this set knowing of this](https://github.com/caronc/sabnzbd/blob/a34ef8997b49f624cef3e0cdba62781433df218a/requirements.txt#L57). It was broken in some merge request later performed. You can look up `git blame` if it really matters 🤷‍♂️

**Comment by Safihre** [comment]
Thanks for checking  👍
