### ISSUE TITLE
Host whitelist allows external web interface access when external access limited to API

### ISSUE THREAD

**Issue by michaelotis** [sabnzbd/sabnzbd#2869]
### SABnzbd version

4.3.1

### Operating system

Windows 11

### Using Docker image

None

### Description

I have a reverse proxy to allow API calls out, however if I put the domain into host_whitelist to get hostname verification to work, it allows web access even when my external is closed to just API.

**Comment by thezoggy** [comment]
config > general > External internet access
https://sabnzbd.org/wiki/configuration/4.3/general

now to control what sab is deemed local, you would use that config>special>local_ranges  

Hopefully you haven't put your reverse proxy ip block in there..

**Comment by michaelotis** [comment]
> config > general > External internet access https://sabnzbd.org/wiki/configuration/4.3/general
> 
> now to control what sab is deemed local, you would use that config>special>local_ranges
> 
> Hopefully you haven't put your reverse proxy ip block in there..

I only have API only set for external access. I didn't have anything set for local_ranges, but if I set it to my local ip range, I'm still able to access the web interface from anywhere regardless

**Comment by thezoggy** [comment]
non routable ips are 'local' (rfc1918) and you should have access. look at sab debug logs to see where the request is coming from and confirm the ip that the request is coming in from. 

if your still having issues, make sure sab is set to debug logging (wrench > set logging to debug), replicate the issue.
Then go to the wrench>show logging and share that sanitized log+config so we can review your settings.

**Comment by michaelotis** [comment]
> non routable ips are 'local' (rfc1918) and you should have access. look at sab debug logs to see where the request is coming from and confirm the ip that the request is coming in from.
> 
> if your still having issues, make sure sab is set to debug logging (wrench > set logging to debug), replicate the issue. Then go to the wrench>show logging and share that sanitized log+config so we can review your settings.

The hostname is what is required to prevent the hostname verification error, however, if you put the hostname into the host_whitelist it explicitly states that hostname bypasses the external check and is shown the web interface. So I think there's really no way around it

**Comment by Safihre** [comment]
The hostname check is secondary to the ip ranges check. First the ip is checked. Which is probably a local one because of your proxy.

**Comment by Safihre** [comment]
Oh yeah of course, I forgot about that!
