### ISSUE TITLE
checkdir util fails when the directory path contains spaces

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#2872]
### SABnzbd version

4.3.2rc2

### Operating system

linux, mac; windows unknown

### Using Docker image

None

### Description

The code runs `df` by passing both the command and the directory argument in a single string, which may result in lack of proper quoting. If the directory path contains spaces (etc...), this causes the util to fail at detecting FAT32 or in some circumstances even report info for another partition/directory.
https://github.com/sabnzbd/sabnzbd/blob/b1d42c7c222b059fb3fdb0a5cd1fd36996c31dfe/sabnzbd/utils/checkdir.py#L43-L44
https://github.com/sabnzbd/sabnzbd/blob/b1d42c7c222b059fb3fdb0a5cd1fd36996c31dfe/sabnzbd/utils/checkdir.py#L86-L87
both calling `os.popen` which wraps [subprocess.Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen):
https://github.com/sabnzbd/sabnzbd/blob/b1d42c7c222b059fb3fdb0a5cd1fd36996c31dfe/sabnzbd/utils/checkdir.py#L13-L16

**Comment by Safihre** [comment]
Will you submit a PR to fix? 😇
