### ISSUE TITLE
Rename request

### ISSUE THREAD

**Issue by tewhite79** [sabnzbd/sabnzbd#2877]
### Description

I'm an avid user of this excellent program.

I bought a number of BTCs years ago.

I would like to donate 15 BTC on my birthday.

The transaction is scheduled for the 17th of June at 8:00 AM ET.

My only request is to change the program name. I would like it to be called satenzb.

I would donate additional 15 BTC after my request is honored, but it is totally optional.

Thank you for creating such a jewel. There's a reason it has millions of users.

Sincerely,
Terry

**Comment by Safihre** [comment]
That's a nice offer. Just wondering why you want that specific name? 😄

**Comment by Safihre** [comment]
Ohh.. I did not get any BTC 😪
