### ISSUE TITLE
Some smaller files not correctly renamed / deobfuscated

### ISSUE THREAD

**Issue by swindmill** [sabnzbd/sabnzbd#2880]
### SABnzbd version

4.3.2

### Operating system

Fedora 40

### Using Docker image

linuxserver

### Description

When retrieving at least one nzb, the largest / main `.mp4` file is named correctly, but smaller additional image and subtitle files are left with names like the following:

- `'[N3wZ] \SAA8Ya311417\::[PRiVATE] \4c1364e8a9\::a1dcc7cc5a5706.c0c06e530978b33ede7057745e3505.d34f94fe::+c1774e456437+ [newzNZB] [11+12] - yEnc  52127 (1+1).jpeg'`
- `'[PRiVATE] \073152052d\::94e87fcdd83495.a8abae491d4c709b054020ebffcaed.75234e79::+bc9fb05a653d+ [newzNZB] [7+12] - yEnc  92807 (1+1).jpeg'`
- `'[PRiVATE] \f506747fd0\::e0fa915c514b52.855ee665aa804562bee98a15f6fbed.215a90d5::+e80ad65074d9+ [newzNZB] [2+12] - yEnc  100531 (1+1).txt'`

Other downloaders like the [Newshosting newsreader](https://www.newshosting.com/newsreader/) or [NZBGet](https://github.com/nzbgetcom/nzbget) more correctly rename these files to look like the following:

- `i_8.jpg`
- `i_4.jpg`
- `4_English.srt` (notice the correct `.srt` extension vs the `.txt` extension SABnzbd is using

I enabled debug logging and retrieved this nzb, here is a log excerpt: [sabnzbd.log](https://github.com/user-attachments/files/15797710/sabnzbd.log)

**Comment by thezoggy** [comment]
there is a long sorid history of newznzb/wtfnzb/xpost stuff that is purposely done in a way that if you get the nzb from their site its good but if you get it from a site like .su or sites that 'index' it it will be  pretty crappy. you can look at reddit for countless things about it. most newznab sites have blacklisted them for a reason.. but sadly .su isnt really maintained so it never did. so you prob see it slipping in from there.  

now generally sab is actually better than other stuff on handling them compared to nzbget and others..
nzbget used to not handle it at all, but the recent updated fork can handle some but still
https://github.com/nzbgetcom/nzbget/issues/105

now with all that said is it worth trying to see what we can improve.. prob not. but the release your talking about is 3.5+ years old..  and theres plenty of other releases that arent this xpost variant. that you should be able to handle just fine.

**Comment by sanderjo** [comment]
> the largest / main `.mp4` file is named correctly, but smaller additional image and subtitle files are left with names like the following:

You describe how it is designed and implemented:

1. the biggest file is handled, and renamed (if obfuscated)
2. if renamed: smaller files, with the same basename, are renamed with the same base name

So: how would you rename the files you mention, making there is no collision?

**Comment by swindmill** [comment]
> So: how would you rename the files you mention, making there is no collision?

What I find interesting (but don't pretend to fully understand) is that NZBGet is somehow able to derive what I suspect is the correct original filename of `4_English.srt` from a file that SABnzbd leaves named `[PRiVATE] \f506747fd0\::e0fa915c514b52.855ee665aa804562bee98a15f6fbed.215a90d5::+e80ad65074d9+ [newzNZB] [2+12] - yEnc  100531 (1+1).txt`

Is `4_English.srt` somehow encoded into the file subject in the NZB file?

**Comment by sanderjo** [comment]
> Is `4_English.srt` somehow encoded into the file subject in the NZB file?

The SABnzbd deobfuscator uses the name of the NZB file itself. As it seems NZBget copied the functionality, I assume they do the same.

4_English.srt could get renamed to My_Linux_ISO_image_4_English.srt (and that would be handy), but I wouldn't dare to rename a .txt to .srt: that way a readme.txt would get renamed to ...srt, which would be likely false.

The SABnzbd deobfuscator cares about the biggest file, and the directly related (related as in: same basename) files. Not about all kinds of smaller files.

**Comment by sanderjo** [comment]
I did some reverse engineering.

Example srt files 
```
$ ll | awk '{ print $NF }'  | grep srt | head -8
10_Finnish.srt
11_French.srt
12_German.srt
13_Greek.srt
14_Hebrew.srt
15_Hungarian.srt
16_Indonesian.srt
17_Italian.srt
```
These are **not** understood / self-detected by VLC. 


So I did some tests (with another file, and created some srt files with different filename formatting):
```
short.mp4

short.12.ger.srt
short.14_swe.srt
short.44.rum.srt
short.56_pol.srt
short.Latin.American.spa.srt
short.rus.srt
short.SDH.eng.srt
short_swe.srt
```
And the result in VLC is:

![image](https://github.com/sabnzbd/sabnzbd/assets/1273502/1a3b4163-0823-4dc2-9818-982a485dbde1)

Nice. VLC picks the penultimate part between dots.

I then created short.88_Dutch.srt, which appears as "88_Dutch". OKish, but not beautiful; the 88_ is a bit ugly

OK:
just the language name (short or long)
the langauge name, with a number plus dot before it

Not OK: underscore.

I think I can add this functionality into SABnzbd's deobfuscator.

**Comment by thezoggy** [comment]
The base for subs is that the media basename and subs name need to match..  so movie.mkv + movie.srt
Then to support multiple subs you can use the 2 or 3 letter iso code of the lang

Related Page: [ISO-639-1 codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (2-letter)
Related Page: [ISO-639-2/B codes](http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) (3-letter)

So movie.mkv + movie.en.srt / movie.eng.srt 

But then you can also do different type of subs, like: (forced|foreign|default|cc|psdh|sdh) 
Which there could be multiple ones of those..

So movie.mkv + movie.eng.srt / movie.en.cc.srt / movie.en.sdh.forced.srt

so roughly:
`<basename>.[Language_Code].[Sub_Type+].ext`

for more info:
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/

how sonarr does its regex for it:
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/LanguageParser.cs#L32C1-L35C1

**Comment by Safihre** [comment]
So what to do here?

**Comment by sanderjo** [comment]
I'll do the feature request as described.

I had implemented something last weekend weekend, but covered not all cases (did not kick in when no obfuscated main file was found), so have to put the code in another place: in its own function call.
