### ISSUE TITLE
Priority Label

### ISSUE THREAD

**Issue by martinkeat** [sabnzbd/sabnzbd#2886]
### Description

Hi There, I was wondering if it would be at all possible to add a priority numbering option.

At the minute you obviously have Force, High, Normal, Low, Stop options in Sab, but I was wondering if perhaps you could add a small text box to the download line (maybe on the far left) where you can put a number priority (with 1 being the highest priority) so that users can set a priority list within the Force, High, Normal etc.

E.G. A person has 100 things transferring from their personal server. 10 are set to High, 20 to Normal, the rest at low. However, the 10 that are set at high order themselves only by the "Automatically sort queue" switch and the user may want the 1st, 5th and 9th downloads to come down first. Therefore they could set 1,2,3 and those three would be at the top of the list within the "High" group.

**Comment by Safihre** [comment]
Have you tried enabling the Extra queue column in the Status and Interface settings window?
