### ISSUE TITLE
Replace Par2.exe with ARM native build on Windows ARM Platform

### ISSUE THREAD

**Issue by jgershgorin** [sabnzbd/sabnzbd#2896]
### Description

By default on Windows SABnzbd uses multipar instead of par2 command line. So first, we have to turn off multipar by going to:

Settings->Special, uncheck "enable_multipar" and press the "Save Changes" button at the bottom.

Then download the ARM64 native par2 from:

https://github.com/animetosho/par2cmdline-turbo/releases 

Latest is "par2cmdline-turbo-v1.1.1-win-arm64.7z" as of this post. Uncompress the par2.exe in this file to the \SABnzbd\win\par2\x64 folder, replacing the existing par2.exe

**Comment by Safihre** [comment]
Closing this, we will make a proper ARM64 release when it's possible.
