### ISSUE TITLE
Add fail/abort download to the API

### ISSUE THREAD

**Issue by PhattestMattest** [sabnzbd/sabnzbd#2906]
### Description

While i'm fairly new into coding, I would like to monitor the downloads with a python script for certain variables ie; missing articles, keywords, etc.. and fail / abort the download if they meet the criteria. Sonarr / Radarr should then blocklist those items which is what i'm looking for. It appears I can only delete the items from the queue which would not illicit the same response from the arrs.

**Comment by thezoggy** [comment]
Not sure what your wanting to do with the data, but Sonarr/radarr already look at failed status and react (remove job and move onto the next nzb).

**Comment by Safihre** [comment]
You can set the priority to `stop`. This wil stop the download and move it to post-processing.
This will most likely fail, due to being incomplete. This will then be picked up by Radarr and Sonarr.
https://sabnzbd.org/wiki/configuration/4.3/api#priority
