### ISSUE TITLE
Sabnzbd crashing on macOS

### ISSUE THREAD

**Issue by FoUStep** [sabnzbd/sabnzbd#2910]
### SABnzbd version

4.3.2

### Operating system

macOS Sonomo 14.5 (23F79)

### Using Docker image

None

### Description

macOS 14.5 on my Mac Mini 2018 with 32 GB RAM restarts (kernel panic) after a crash with Sabnzbd 4.3.2:
![crash macOS 2024-07-18 at 09 29 38](https://github.com/user-attachments/assets/329f6e53-b556-49e0-81d7-43aa266d2727)

Some issue with par2-turbo, I also noticed not all files will be extracted appropriately (some are just extracted partially and are then incomplete).

Never had these issues before, it feels like this is since 4.3.0. I never had crashes, but after 4.3.0 I never really gave it a thought.

**Comment by sanderjo** [comment]
Mac Mini 2018 => Intel CPU. Not M1/M2/M3 related.

"Your computer was restarted"?! Wow!

The crash reports says something about smbfs, so a Samba / Windows share is involved? Problem might be there (or even MacOS itself), not in par2-turbo itself.


Probably better to report it on https://github.com/animetosho/par2cmdline-turbo

Also: what happens when you run par2-turbo from the commandline? Always a crash, or now and then? Report on the given github page.

**Comment by FoUStep** [comment]
> https://github.com/animetosho/par2cmdline-turbo

I will troubleshoot if par2-turbo itself has issues and report there. I tried the beta (4.3.3) but it did not fix anything. I'm using samba/smb with macOS to my Synology indeed. Have it like this for years, I never had issues with sabnzbd (and it's unrar/par2). I reported this issue because of the kernel panic, which is weird because the app is not an installer.

I could try and go back to the 4.2.X branche but the app will tell me to update it with a banner.

**Comment by sanderjo** [comment]
if it's a MacOS kernel panic, I guess you should get an award from Apple for reporting it: an application should never be able to trigger a kernel panic.

If you go back to 4.2.x: I believe there is parameter you can set how often to check for a new version. 
= blue pill


Red pill: from the CLI (not SABnzbd) do tests with par2-turbo against local fileystem, resp Samba. And do random disk write and read tests against Samba ... maybe that already triggers the kernel panic.

**Comment by thezoggy** [comment]
And just fyi you can drop another version of par2cmdline-turbo in your sab/osx/par2 folder and replace the existing file to try something out if you believe it is the culprit.

**Comment by sanderjo** [comment]
I used chatgpt to convert your screenshot to text.

If you google 'Kernel Extensions in backtrace: "com.apple.filesystems.smbfs(5.1)"' you see more reports. Not related to SABnzbd nor par2-turbo.

So a generic MacOS problem?

You did click the button "Send to Apple", I hope?

```
panic(cpu 3 caller 0xffffff80155e0ebf [vm pages]: element modified after free (off:16, val:0x0000000000004000, sz:64, ptr:0xffffff80425a300)

16: 0x0000000000004000

Panicked task 0xffffffa7dee37d8: 10 threads: pid 6446: par2-turbo
Backtrace (CPU 3), panicked thread: 0xfffff8b7d9f2b30, Frame: Return Address
0xffffff8014e26481
0xffffff8014fabb10
0xffffff8014f7bacc
0xffffff8014e267d3
0xffffff8014e25e13
0xffffff80155db27f
0xffffff80155e0ebf
0xffffff8014f2f30a
0xffffff8014fe66a
0xffffff7faa59cef3
0xffffff8014f7f362
0xffffff7faa5d0d25
0xffffff7faa5d336d5
0xffffff8015032a87
0xffffff80152eabb7
0xffffff801454f450
0xffffff8014f0fbd6

Kernel Extensions in backtrace:
com.apple.filesystems.smbfs(5.1) [D945E081-25C0-3852-AB01-7B5E4AEDE490]@0xffffff7faa50d00->0xffffff7faa591fff
dependency: com.apple.kec.corecrypto(14.0) [A9D9B3D6-1F98-357A-AE06-E1DB85BD31F2]@0xffffff80179ec000->0xffffff8017a68fff
dependency: com.apple.kext.triggers(1.0) [5CC62F5F-4087-310E-BC9A-7F5840AA0704]@0xffffff7faa59c000->0xffffff7faa59efff

Process name corresponding to current thread (0xfffff8b7d9f2b30): par2-turbo

Mac OS version:
23F79

Kernel version:
Darwin Kernel Version 23.5.0: Wed May 1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
Kernel UUID: 78071FD2-9FDC-344E-8483-47EC972A105E
roots installed: 0
KernelCache slide: 0x0000000014200000
KernelCache base: 0xffffff8014c00000
``` &#8203;:citation[oaicite:0]{index=0}&#8203;

```

**Comment by thezoggy** [comment]
also if your going to report an issue, please share debug logs of the issue. click the wrench, set logging level to debug. reproduce the issue. then go back to sab wrench > show logging. then share that sanitized log+config with us. so we can see what settings/what sab was doing at the time. 

im not sure if your trying to have sab save stuff to an external hdd or remote computer or what, but if you want to try and isolate your issue make sure your incomplete+complete is on your local drive. see if it happens then. as if you have smb  involved i'd assume your trying to do it remotely.. which now your talking a bunch of other variables
