### ISSUE TITLE
api history endpoint: retry is now a bool / was an int

### ISSUE THREAD

**Issue by davidnewhall** [sabnzbd/sabnzbd#2911]
### SABnzbd version

4.3.3Beta2

### Operating system

any

### Using Docker image

Other

### Description

I wrote an application that processes SABnzbd history items. In a recent release the `history.slots.retry` field was converted from an integer to a boolean. This breaks my strongly-typed model for this api endpoint. I can fix my code to deal with a bool and an int, but I first want to make sure this breaking change was intentional.

[This appears to be the breaking commit](https://github.com/sabnzbd/sabnzbd/commit/b8fd9e6e31aa98351fcdafc3293ce164c871b124), but I'm not super familiar with this code base and may have misidentified the culprit. 

Please advise if this was intentional, and if a major version will be release due to API changes.

Thank you!

EDIT: I had it backward originally. Just working from an error message, so it wasn't a full picture.

**Comment by sanderjo** [comment]
I think @Safihre is away from his keyboard, so you need a some patience to get the answer.

But I see you've already changed your code?

**Comment by Safihre** [comment]
I didn't consider this a breaking API change, because it was inconsistent before. If an item was in active post-processing, it would return a bool while from history it would return an int.
In any case, from now on it will be a bool, just like it should be :)

**Comment by davidnewhall** [comment]
It was definitely a breaking change on the one endpoint my app uses.
