### ISSUE TITLE
Server Bandwidth History, Month Selection Process Change

### ISSUE THREAD

**Issue by Redundant1** [sabnzbd/sabnzbd#2913]
### Description

I was writing this up as a bug, but, as I was documenting it, I realized what's happening and am now requesting a functionality change.  I'm currently on 4.3.2 under Windows 11.

**What's happening:**
If you first enter a 'start date', followed by an 'end date', you will no longer be allowed to select a month's 'end date' AFTER the 'end date' you just chose.
_CONVERSELY:_
If you first enter an 'end date', followed by a 'start date', you will no longer be allowed to select a month's 'start date' BEFORE the 'start date' you just chose.

After any selection is displayed, you now need to change EITHER the start or end date, DEPENDING on which way you're want to go.  This is not very intuitive, which is why I initially thought it was a bug.  You can also refresh the page to 'reset' it.  I'm not certain when this "regression" happened, but I'm fairly certain this isn't the way it used to function.

**Desire:**
Allow us to select whatever date ranges we want without restrictions.  If it isn't valid, just don't show anything.

**Comment by thezoggy** [comment]
I'm not sure what bug you are trying to explain, perhaps showing an image or animated gif would eliminate confusion on that part.

Additionally, what browser + version are you using?
Are you clicking the little calendar icon to set the date?

**Comment by Safihre** [comment]
I think you are experiencing a browser bug, not a SABnzbd bug.
Can you try a different browser?
