### ISSUE TITLE
IPv6 turned off, but still IPv6 address visible on status and webinterface page

### ISSUE THREAD

**Issue by Thermoskannetje** [sabnzbd/sabnzbd#2920]
### SABnzbd version

4.3.2-70

### Operating system

Synology

### Using Docker image

None

### Description

Situation: 
I have set:
ipv6_servers=0
ipv6_hosting=0
ipv6=0 (not sure this is a valid option)

Problem/bug: 
When I open sabnzbd, click on the wrench symbol a IPv6 address is still visible. This suggests that sabnzbd can still connect to newsgroups using IPv6. 

Why is this important: 
This is important as most (mine) VPN provider doesn't support IPv6 and all requests via IPv6 are processed without VPN protection. 

Suggest resolution:
Not sure what goes wrong. Or Sabnzbd doesn't use IPv6. In that case I would suggest to mention this explicitly in stead of showing the IPv6 address. Or Sabnzbd still uses IPv6 for connections and the ipv6_servers=0 setting doesn't work correctly. 

Side question or feature request: 
Can I somehow verify whether Sabnzbd is using ipv4 only and connecting to my newsgroups via VPN? If not this is a feature request. Privacy and protection become more and more important in the future.

**Comment by thezoggy** [comment]
sab webserver and how you bind it, is one thing. (config>general>host)
ipv6_servers - sab doing v6 to your usenet service provider is another.
ipv6_staging  - sab doing v4 and v6 speedtest (vs just doing happy eyeballs and picking fastest) is another thing.

if you dont want v6 to work you can just turn off v6 to your docker, some docker maintainers will expose this by setting the correct env, some others force you to add additional option for the container.. some dont give you anything and you have to just manually set it on the os.

**Comment by sanderjo** [comment]
> This is important as most (mine) VPN provider doesn't support IPv6 and all requests via IPv6 are processed without VPN protection.

It's 2024. Find a VPN provider that supports IPv6. Vote with your money.

> This suggests that sabnzbd can still connect to newsgroups using IPv6.

SAB's special settings page starts with the text "Rarely used options. For their meaning and explanation, click on the Help button to go to the Wiki page. Don't change these without checking the Wiki first" 
So ... did you read the Wiki https://sabnzbd.org/wiki/configuration/4.3/special first?

**Comment by sanderjo** [comment]
Or, if you don't want to read the wiki or don't trust it, do a full block of IPv6: run SABnzbd on docker (in default config) on your Synology. Default docker does IPv4-NAT, and no IPv6. Bingo!

**Comment by Safihre** [comment]
During downloading, in the Status and Interface settings window on the Connections tab you can see which IP address is being used for your newssever connection.

However, I do have to agree with Sander that the explanation on the Special Settings wiki says exactly what each option does.

**Comment by Safihre** [comment]
In the Status window you can only see which IP we used of the news server, not which VPN.
Based on your screenshot it seems you might be using an older SABnzbd version?

![image](https://github.com/user-attachments/assets/a4990076-3411-4678-96b0-1da8fce4e2b1)

**Comment by Thermoskannetje** [comment]
Yes, that was the wrong screenshot from an older version (I tried to delete the image), but I'm using the most recent version now. 

I'm sorry that I'm not very experienced in all this, but maybe the feature request would be:
"It would be great if I can see in Sabnzbd what public IP address is used for downloading, so I can check whether this is linked to my VPN connection."

The IP addresses under status do not give the full answer as it also shows two IP addresses and only one is used for downloading I guess.  

The IP address under connections doesn't give the answer because this doesn't show the public VPN address that is used for downloading. 

So, the only thing I'm trying to do is to find a way to verify I'm using the VPN connection for downloading so my privacy is ensured.

**Comment by mnightingale** [comment]
I wonder if it is possible to bind Python sockets to specific interfaces and if that could be what @Thermoskannetje is looking for?

Something like the following?
I've only tested on Mac for the usenet connection checked with `sudo nettop -d`, it'd need similar for wherever else it makes outgoing connections.

```py
# NNTP.connect

# Bind to interface
if sabnzbd.WIN32:
    # not researched for Windows
    pass
elif sabnzbd.MACOS:
    IP_BOUND_IF = 25
    self.sock.setsockopt(socket.IPPROTO_IP, IP_BOUND_IF, socket.if_nametoindex("en0"))
else:
    self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_BINDTODEVICE, b"eth0\x00")
```

From a privacy standpoint, I wonder what the stance would be on a switch to disable the "call home" behaviour entirely (self-test.sabnzbd.org)?

**Comment by Safihre** [comment]
Of course that's possible, and has been requested before. But it's so exotic that I don't see the added maintenance burden.

You can disable the call home by emptying the self test host setting in Special settings.
It's required to get the external IPv4  address, it's not there just to call home..

We don't do anything privacy unfriendly. We don't collect any statistics or send any info back home. Compare that to the *arr suite which has extensive analytics services enabled by default..

**Comment by thezoggy** [comment]
In case you weren't aware there is no real need to be using a VPN with sab.. just use https to your indexers/ssl to your usenet service providers.

**Comment by Safihre** [comment]
Closing this, as we will not be adding a feature to select the outgoing connection.
