### ISSUE TITLE
OZnzb downloads do not have url_info anymore

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#293]
@oznzb-dev 
New NZB's downloaded from OZnzb do not have the url_info anymore (the link to the info on the OZnzb website).
I don't know if either the format of the NZB changed or something goes wrong when SAB tries to extract it.

**Comment by shypike** [comment]
The NZB itself doesn't carry the information, maybe it did in the past.
When you get NZBs from an oznzb.com RSS feed, you still get the url_info.
However, neither Plush nor Glitter show it, although it is in the database.
It's also present in the history RSS-feed: ..../sabnzbd/rss?mode=history

**Comment by Safihre** [comment]
Sorry I don't get it.. 
I used to see it in Plush and Glitter with all NZB's from OzNZB that were added through Sonar or Sickbeard (nothing with Rss) now I don't. 
What changed then?

**Comment by Safihre** [comment]
Could this be due to the addurl change?

**Comment by shypike** [comment]
No, the url_info is still returned by the API-call "history".

**Comment by Safihre** [comment]
I see now. No clue how the info_url got in some of the NZB's before when added through Sonar/Sickbeard. When I re-add some of those NZB's now (from my NZB backup-folder) they also don't have info_url anymore.

However: since the link would be 
https://www.oznzb.com/details/x-oznzb-rating-id
It can just be added when the **x-oznzb-rating-id** field is found in the NZB?

**Comment by Safihre** [comment]
I would do it myself.. but I would probably do it in the wrong place in the code!

**Comment by oznzb-dev** [comment]
there haven't been any changes to the content provided in the NZB files from the site or the api. I checked some older downloaded nzb's and confirmed its not in there either.

**Comment by shypike** [comment]
OK, I'll see whether I can convert the x-oznzb-rating-id into a url_info value if that field isn't already filled.
But as far as I can tell, Glitter still won't show it.

**Comment by Safihre** [comment]
If the info_url is present in the API output it will show it, here:
![image](https://cloud.githubusercontent.com/assets/5703454/9488011/e3881ad4-4bd6-11e5-8c34-b4d3221877fd.png)

**Comment by thezoggy** [comment]
note that sonarr doesnt add nzb via addurl but by addfile. thus it wont have the header info.
sickbeard normally tries to add by url, but in specific scenarios it will fallback to doing the addfile method.

**Comment by Safihre** [comment]
I closed the issue because while looking through the code I realized it would be very-very OZnzb specific to add it through x-oznzb-rating-id, for such a tiny feature I did not think it worth the effort.
