### ISSUE TITLE
Paginated RSS Filter Page

### ISSUE THREAD

**Issue by timbuckiii** [sabnzbd/sabnzbd#2931]
### Description

Hello, thank you for all of your great work!

## Current challenge
Right now, all filters for a given RSS feed are loaded concurrently when the config page for an RSS sub is opened. This causes the UI to freeze up when a particular RSS feed contains many filters.

## Feature request
Paginate the filters on the config page for individual RSS feeds to enable faster loading.

Please and thank you! 🎉

**Comment by Safihre** [comment]
Interesting.. How many rules do you have?😱

**Comment by timbuckiii** [comment]
> Interesting.. How many rules do you have?😱

300ish. It's for music :)

**Comment by thezoggy** [comment]
> > Interesting.. How many rules do you have?😱
> 
> 300ish. It's for music :)

perhaps you should look into the app called 'lidarr'

**Comment by timbuckiii** [comment]
> > > Interesting.. How many rules do you have?😱
> > 
> > 
> > 300ish. It's for music :)
> 
> perhaps you should look into the app called 'lidarr'

Thanks - I know it well. Most of my filters are exclusionary rather than inclusionary though, so I'm casting a wide net which is the opposite of what Lidarr is typically used for.

**Comment by Safihre** [comment]
Unfortunately, I don't think we will be implementing this because it is only relevant to a really small section of users.
