### ISSUE TITLE
Replace newsunpack's rar handling with rarfile

### ISSUE THREAD

**Issue by bgermann** [sabnzbd/sabnzbd#2935]
### Description

Please consider replacing the rar extraction in the newsunpack modules with the rarfile module. Is there a specific reason why it is not used there already?

Edit: Remove request for directunpacker change.

**Comment by bgermann** [comment]
This would allow using unar as unrar alternative, as requested by #1120.

**Comment by thezoggy** [comment]
it looks like this person is just trying to push 'unrar-free' and assumed the fallout of support was somehow related to not using rarfile...  newer rar format and things that are not part of unrar-free would prevent it from being used regardless of how it was implemented.

**Comment by thezoggy** [comment]
it is not a drop in replacement for unrar.. it is not feature parity. last i recall it had issues with utf-8 related things and didnt handle various things dealing with multiple platform differences. additionally it would be more work to cater towards unar for debian than just have the debian user install the unrar-nonfree.  and in this day in age most people just run things within docker containers so the debian os itself is moot.

**Comment by bgermann** [comment]
Okay, thanks for the feedback.
