### ISSUE TITLE
Ensure the behavior changes to url_base in 4.4.x are fully documented

### ISSUE THREAD

**Issue by jeffgeorge** [sabnzbd/sabnzbd#2936]
### Description

We should consider defaulting the value of `url_base` to "sabnzbd". If we don't, it's going to have some serious backwards compatibility impact, breaking basically everything that relies on the URL of SABnzbd.

Here's an off-the-top-of-my-head list of things that'd break if we change the Base URL:
- Reverse-Proxy configurations (which may be used to provide SSL certs, SSO authentication, etc)
- Media Management / Sourcing Apps (Sonarr, Radarr, etc)
- Alternative UIs (LunaSea, etc)
- Browser Extensions (NZBUnity, etc)

Personally, I use a custom managed nginx reverse proxy setup to map sabnzbd's port to a subdirectory, but it was easy enough for me to directly connect to the local non-proxied port, go to special settings and set the `url_base` to restore all my integrations . . . but if I didn't have direct access to the port (a reasonably common approach for installations where port access is severely locked down to force everything through Authelia/Authentik or just generally to reduce the attackable surface area), then fixing this would have required direct access to the sabnzbd.ini and restarting the service.

If pre-filling a `url_base` isn't an option, then I suggest we promote this release from 4.4 to 5.0 due to the level of breakage involved.

**Comment by Safihre** [comment]
If we do that, then any users that go to the version without /sabnzbd won't work anymore.
We have to drop 1 of the 2.

**Comment by jeffgeorge** [comment]
So once we swap out CherryPy we won't support alternative `url_base` values at all?

**Comment by thezoggy** [comment]
just so we are on the same page from what i understand, 

4.3.3 and older.. sab had / and /sabnzbd (url_base basically set) out of the box.
4.4 (dev) now sab does /.  and url_base not set. you could just set url_base to `/sabnzbd` if you want to restore the 4.3.3 and older behavior

correct?

**Comment by Safihre** [comment]
Correct.

**Comment by jeffgeorge** [comment]
Ok, I must have missed a change some time in prehistory, because I thought we always redirected `host:port` -> `host:port/sabnzbd`. But I just checked 4.3.3 and confirmed that yes we supported both `host:port` and `host:port[/base_url]`, which previously defaulted to `/sabnzbd`.

So we _are_ stuck at a point where an indeterminate number of users may be using either `host:port` or `host:port/sabnzbd`, and we can't tell which, and either approach will impact _somebody_. If we keep the behavior in 4.4.0A1 anybody depending on `/sabnzbd` will break. If we use a default value of `/sabnzbd` anybody using a bare `host:port` will break.

If some level of backwards compatibility breakage is unavoidable then I'm back to suggesting this be 5.0.0.

**Comment by Safihre** [comment]
Well not fully, because if you use /sabnzbd in the browser it will automatically redirect to /. This happens for every unknown page, so that's why I chose that.

**Comment by jeffgeorge** [comment]
That'll work for direct links / browsing straight to the web ui, but won't necessarily work for integrations that don't follow a redirect, or that are looking for the api endpoint. It looks like [NZBUnity](https://github.com/tumblfeed/nzbunity) expects a `/sabnzbd` url_base and requires overrides to get it working again with 4.4.0. Sonarr, if it was configured with a url base, also fails because `/sabnzbd/api` is returning a 404.

**Comment by Safihre** [comment]
I realesed this Alpha op purpose to see how many users get upset. So let's see.
The *arr's do not use a base by default, so those are not a problem really. If those had used /sabnzbd I would not have considered it.
So now other programs also have time to implement the change.
We really don't have enough features to justify a 5.0.0. No regular user (a.k.a. Windows person) cares what web server we use. If we have some killer feature, we can call it 5.0.0 easily, otherwise I want just wait it out and see how breaking this change is.

**Comment by sydlexius** [comment]
FYI, this change broke the reverse proxy rule that comes with LSIO's SWAG distro.  I suspect other reverse proxy solutions might not handle it gracefully.  If this change sticks, someone might want to update the default config files made available to SWAG that can be found [here](https://github.com/linuxserver/reverse-proxy-confs).

**Comment by jeffgeorge** [comment]
> I realesed this Alpha op purpose to see how many users get upset.

To be clear, 100% not upset! This is just something we need to work through the full scope of the impact of, which I fully agree is the point of getting this in the first alpha. It seems my specific config is in a weird edge-case, and I'd be fine with chucking this in the FAQ. If you feel it isn't substantial or widespread enough of a break to warrant bumping to 5.0 that's fine, we just need clear docs about the impact and how to work around it.

> FYI, this change broke the reverse proxy rule that comes with LSIO's SWAG distro.

From discussing this on Discord, the solution for SWAG and other folder-based solutions is going to be to manually set a `base_url`, and possibly to add docs at the top along those lines similar to [what already exists in Sonarr's proxy config](https://github.com/linuxserver/reverse-proxy-confs/blob/master/sonarr.subfolder.conf.sample#L3), for instance. Subdomain based solutions should be fine with the default.

It looks like "manually set a `url_base`" is the solution in most cases. I need to do some further testing to see if you can explicitly set a `url_base` in 4.3.3 and have it persist when you upgrade.

**Comment by jeffgeorge** [comment]
Is there a way we could have CherryPy (and whatever our future planned web server is) emit an _actual_ 301 redirect for these paths?
- `/sabnzbd` -> `/`
- `/sabnzbd/api` -> `/api`

The javascript redirect is fine for direct links / browsing, but obviously won't work at all for something trying to access the API and relying on the http status code for if it's working.

**Comment by juliemars** [comment]
> I realesed this Alpha op purpose to see how many users get upset. So let's see. The *arr's do not use a base by default, so those are not a problem really. If those had used /sabnzbd I would not have considered it. So now other programs also have time to implement the change. We really don't have enough features to justify a 5.0.0. No regular user (a.k.a. Windows person) cares what web server we use. If we have some killer feature, we can call it 5.0.0 easily, otherwise I want just wait it out and see how breaking this change is.

So all my arrs were failing linuxserver/sabnzbd:unstable  - and it's due to this change. The arr shows an error of

Unable to connect to SABnzbd, HTTP request failed: [404:NotFound] [GET] at [http://IP:8080/sabnzbd/api?mode=get_config&apikey=APIKEY&output=json]

I don't see any setting to set the base url in the arr itself to fix this but if I set the base url in Sabnzbd itself back to /sabnzbd it works after a restart of the container.

Not a major issue once I figured it out but thought I would flag.

**Comment by Safihre** [comment]
Enable Advanced Settings in *arr. Then it's shown in the connection settings of Sabnzbd. The default is empty, as far as I could see.

**Comment by juliemars** [comment]
found that - I never set it initially but maybe it autodetected it or something. I will leave the urlbase set for now as its easier.  thanks!

**Comment by statik1983** [comment]
Just noticed my reverse proxy to Sabnzbd is broken now, and I see it updated to this latest version.  The only URL_Base option I see is in the sabnzbd.ini file, and mine is blank.  

my reverse proxy is:

location /sabnzbd {

        proxy_pass http://192.168.1.250:8085/sabnzbd;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect http:// $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;


}

**Comment by thezoggy** [comment]
> Just noticed my reverse proxy to Sabnzbd is broken now, and I see it updated to this latest version. The only URL_Base option I see is in the sabnzbd.ini file, and mine is blank.
> 
> my reverse proxy is:
> 
> location /sabnzbd {
> 
> ```
>     proxy_pass http://192.168.1.250:8085/sabnzbd;
> 
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_redirect http:// $scheme://;
>     proxy_http_version 1.1;
>     proxy_set_header Connection "";
>     proxy_buffering off;
> ```
> 
> }

right so your using `/sabnzbd` in your reverse proxy. so set url_base in sab to match that, so you restore the previous setting.   just login to sab at the ip:port to bypass your reverse proxy..  config>special>url_base. update and restart. then verify reverse proxy is good again.

**Comment by statik1983** [comment]
> > Just noticed my reverse proxy to Sabnzbd is broken now, and I see it updated to this latest version. The only URL_Base option I see is in the sabnzbd.ini file, and mine is blank.
> > my reverse proxy is:
> > location /sabnzbd {
> > ```
> >     proxy_pass http://192.168.1.250:8085/sabnzbd;
> > 
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     proxy_redirect http:// $scheme://;
> >     proxy_http_version 1.1;
> >     proxy_set_header Connection "";
> >     proxy_buffering off;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> right so your using `/sabnzbd` in your reverse proxy. so set url_base in sab to match that, so you restore the previous setting. just login to sab at the ip:port to bypass your reverse proxy.. config>special>url_base. update and restart. then verify reverse proxy is good again.

do you mean "/sabnzbd" or "sabnzbd" ?

**Comment by mrblond18** [comment]
I just spent >1hr figuring this out... I suspected the apache reverse proxy I am using. In the end I found out that the webroot of sabnzbd had changed. I think it should be more clear that this is a breaking change.

**Comment by sanderjo** [comment]
Can SABnzbd see (in cherrypy?) the "X-Forwarded-For"? 

If so, SABnzbd could detect it's behind a proxy, and in the grace period, notify the user about the upcoming change?

**Comment by rodalpho** [comment]
> I realesed this Alpha op purpose to see how many users get upset. 

Well, mission accomplished. You forced me to do half an hour of investigation and read a github issue to fix the problem. Thanks!

**Comment by thezoggy** [comment]
> Can SABnzbd see (in cherrypy?) the "X-Forwarded-For"?
> 
> If so, SABnzbd could detect it's behind a proxy, and in the grace period, notify the user about the upcoming change?
> 
> EDIT
> 
> I set up a proxy config (with `sudo tinyproxy -d -c tinyreverseproxy.conf`), and don't see an X-Forwarde-For, but I do a Referer
> 
> `Referer: http://127.0.0.1:1111/sabnzbd/config/folders/\r\n`
> 
> and
> 
> `[Full request URI: http://127.0.0.1:8080/config/general/]`
> 
> So ... different ports (and different base)... so proxy involved. So SAB can detect a proxy, and warn about upcoming change?
> 
> ![image](https://private-user-images.githubusercontent.com/1273502/373810337-69769a9c-a246-4fd5-805a-71ce7c1129fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODA2NTgsIm5iZiI6MTcyODA4MDM1OCwicGF0aCI6Ii8xMjczNTAyLzM3MzgxMDMzNy02OTc2OWE5Yy1hMjQ2LTRmZDUtODA1YS03MWNlN2MxMTI5ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjIxOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljNTU5ODQxM2Q4YWQ3NTBmMDE3ZDM5NzdjMmZiMmEyNzliYmUwOTVhYmQ1MmE0M2YxMTE4MzJlMzVkNjM3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8WVb-EHMCnleXGpcAJ--Gtwy-rb018nYdwFiKR1xXLo)

sab can yes - we have the whole validate xff stuff  (config>special), but not everyone uses that to get forward ips from their proxy

**Comment by Safihre** [comment]
> Obviously on me for running an alpha but still, not cool.

It's an Alpha, not a beta or release candidate. If you run Alpha software you should be ready for such things.

I will take it into consideration, probably I can make the double mounting for Starlette as well.

**Comment by rodalpho** [comment]
I do expect alphas to break and I have the experience to fix them or at least come here to find out what's up. I really don't expect them to be broken _on purpose_ just to screw with users, though. 

Anyway, problem solved now, 'nuff said. Thanks for developing useful software for free.

**Comment by Safihre** [comment]
tye change is intended to see if a feature we have is actually used. It's not to just annoy. 
We have so many features due to legacy reasons of which we have no clue how many people,rely on them.

**Comment by thezoggy** [comment]
sab in the past set url_base to /sabnzbd and sab worked at / or /sabnzbd out of the box.   

this change was to drop mounting at both places and just the proper `/` + url_base if set.
so either we broke everyone at `/` by making them have to do `/sabnzbd` to keep the url_base set.. or we drop url_base and those that actually do need it can just re-add it. 

as we dont know how many people actually need the url_base set to /sabnzbd (those that use reverse proxy with subfolder setup), that was what Saf was getting at, break it and find out.  

the overall scenarios isnt great because you break things for one or the other and picking the lesser evil so to speak is kinda what we have to do... if were going to fix the mount/change. and the question may be, why now? well something that does make sense to do at 4.4 and not 4.3.4..  and behind the scenes we have talked about switching our underlying webserver to something else and the change is to simplify the setup on how things work so that new system can benefit from it.

**Comment by rodalpho** [comment]
To be clear, I do not use a reverse proxy and had never customized URL_BASE before and this change to default behavior broke my setup, with nzb clients getting 404 errors with no explanation when connecting to sabnzbd after the update. 

So barring any reasons otherwise, I would suggest choosing whichever behavior matches what the arr stack expects by default, because that’s why most people use sabnzbd and thus retaining what they expect will negatively impact as few users as possible.

**Comment by Safihre** [comment]
I changed it now to the old behaviour.
Only for new installs it will just use `/`, but for existing ones it will support `/` *and* `/url_base`.

**Comment by thezoggy** [comment]
> To be clear, I do not use a reverse proxy and had never customized URL_BASE before and this change to default behavior broke my setup, with nzb clients getting 404 errors with no explanation when connecting to sabnzbd after the update. 
> 
> So barring any reasons otherwise, I would suggest choosing whichever behavior matches what the arr stack expects by default, because that’s why most people use sabnzbd and thus retaining what they expect will negatively impact as few users as possible.

That's what saf did.. by default sonarr/radarr and such doesn't expect people to be using a reverse proxy for sab..

**Comment by rodalpho** [comment]
I noted in the post you responded to that I do not use a reverse proxy. 

Good to hear about the change!
