### ISSUE TITLE
 Failed to connect: timed out 49@news-nl.newshosting.com:563 (news.ams.newshosting.com)

### ISSUE THREAD

**Issue by sykoONE1** [sabnzbd/sabnzbd#2938]
### SABnzbd version

4.3.3

### Operating system

Linux

### Using Docker image

linuxserver

### Description

Receiving warning near completion, Download gets to near end and stops, waning appears and download completes.
"connect: timed out 49@news-nl.newshosting.com:563 (news.ams.newshosting.com)"
Happens with test file downloads also
Sabnzbd routed through Gluetun with Proton VPN.

I have tried the following,
- disable ssl and change to unencrypted port
- change vpn dns address,
-  change server, 
- change Certificate Verification 

It seems to only happen when connected to Proton VPN, was not an issue with Nord or Mullvad.

Is this warning something to worry about?

**Comment by thezoggy** [comment]
Don't use a VPN. Just use ssl to your provider
