### ISSUE TITLE
Issues with Paths, \\? Appened to start of paths

### ISSUE THREAD

**Issue by FrozenAtlas** [sabnzbd/sabnzbd#2950]
### SABnzbd version

4.4.0Alpha2

### Operating system

Windows

### Using Docker image

None

### Description

Recently sabnzbd has not been able to begin downloads related to this error:

![image](https://github.com/user-attachments/assets/4094d009-0144-4d24-a901-2cc223cdbc3f)
![image](https://github.com/user-attachments/assets/8d6a52b3-b586-4c86-9f57-7655f47dad48)

Previously I was able to use network paths fine but now neither work.

**Comment by Safihre** [comment]
This is Windows internal network path notation. SAB has always used that for many years.
The fact that even with drive letter it can't reach it probably just means it's not available. So maybe the user that runs Sab doesn't have rights etc? Or maybe Windows needs a restart after updates, etc

**Comment by FrozenAtlas** [comment]
Turned out to be a failed RAID drive.
