### ISSUE TITLE
Restart SABnzbd fails for Windows service

### ISSUE THREAD

**Issue by ittroll** [sabnzbd/sabnzbd#2953]
### SABnzbd version

4.3.3

### Operating system

Windows Server 2022

### Using Docker image

None

### Description

When running SABnzbd as a Windows service, the Restart SABnzbd feature on the Config - General screen does not work correctly. It stops the service but then cannot start it leaving the server offline. Probably best to include a warning if this cannot be fixed easily. Restarting the server is useful in the case of an HTTPS cert renewal (see related feature request #2954).

**Comment by Safihre** [comment]
I cannot reproduce this. 
It always works for me and looking at the code, I also can't see how it would fail. 
If you just do a restart from the main page, does it work as expected? What do you see in the logs?

**Comment by ittroll** [comment]
OK, I've worked out the issue. Not a bug, but a config gotcha.

My SABnzbd service is configured to log on as a non-admin user account. This so that the SABnzbd service is not running as a privileged user and also so it can access a network share. This restricted user did not have permission to start or stop services.

To fix, I granted the user the advanced service permissions to start/stop SABnzbd. After which it works as expected.

I didn't think of this immediately because SABnzbd was shutting down cleanly.

**Comment by ittroll** [comment]
Yes, I do. I am running the service as a user (me) with access to the share. However, this account is not an administrator and so cannot manage services. This is best practice from a least privilege principal.

Conversely, if you leave it configured to use the default account it will have permission to restart the service.

**Comment by ittroll** [comment]
I note that the wiki https://sabnzbd.org/wiki/advanced/sabnzbd-as-a-windows-service does recommend:

> Specify a different "Log on" account. (Make sure it is one that has administrative privileges and access to network shares).

Which will work, but running a web-service as a full admin is not great from a security point of view. The required privileges can be parred back to just those that are required, as detailed above.

**Comment by ittroll** [comment]
> Run the service in a specific security context. To help secure your system from attacks, run the service with minimal user rights. If you require more user rights than those that are granted to the minimal user accounts, do not run the service as a user with administrative credentials
[https://support.microsoft.com/en-gb/topic/descriptions-of-some-best-practices-when-you-create-windows-services-13ca508e-231d-43e6-b960-3b04ccf79064](url)
Nothing requires full admin, it is always possible to minimise permissions to only those that are strictly necessary. It may take a little longer to setup, but then you have full functionality and maximum security.
