### ISSUE TITLE
Reload / Refresh HTTPS Certificate

### ISSUE THREAD

**Issue by ittroll** [sabnzbd/sabnzbd#2954]
### Description

It would be useful to have an option to either manually or automatically reload the HTTPS certificate. Let's Encrypt certificates are only valid for 90 days and are setup to renew automatically. SABnzbd may continue to use an expired certificate which was loaded previously. Restarting SABnzbd will fix this, but atempting this via the UI will fail if it is running as a Windows service (see related bug #2953).

**Comment by mnightingale** [comment]
There are a few ways this could be accomplished.

SAB could monitor the certificate files for changes and reload/reconfigure, but I'm not sure that's typical since you could use certbot to restart the service directly.

`certbot renew --pre-hook "net.exe stop SABnzbd" --post-hook "net.exe start SABnzbd"` or may be `--deploy-hook "net.exe restart SABnzbd"`

**Comment by ittroll** [comment]
Thanks, I will look into that. The slight concern is interrupting any processing that SABnzbd may be doing at the time. If it is possible for SABnzbd to reload the certificate without interrupting downloads, decompression, or file copies, then that would be a safer solution.

**Comment by Safihre** [comment]
We could do that, but too much logic related to the hosting is part of the loading script.
I really like @mnightingale's suggestion!

**Comment by Safihre** [comment]
Closing this because it is currently just too much of an exotic use case to support. For possible work-around, see above!

**Comment by ittroll** [comment]
OK fair enough. I'm not convinced having an external app arbitrarily restart the service is the best solution (SABnzbd could be mid repair or transfer). But I understand this may be a fringe case. It is a shame that the web server cannot easily perform a cert refresh.

**Comment by Safihre** [comment]
My feeling is that most people with advanced setups that include certificates probably use reverse proxy to handle the ssl part. The webservice inside Sab is just a bit basic.
