### ISSUE TITLE
Include provider Backbone on Servers Page

### ISSUE THREAD

**Issue by arcticfoxwpg** [sabnzbd/sabnzbd#2957]
### Description

It would be nice if under the Provider name, right above the "Enabled" checkbox, if there was a space to list which Backbone the provider was on. Maybe selectable in the Show Details screen by a drop down menu, or even better, automatic.

**Comment by Safihre** [comment]
We already have the comments field for this, isn't that enough?

**Comment by arcticfoxwpg** [comment]
> We already have the comments field for this, isn't that enough?

No, because the comments don’t show on the Main Server page without diving into the advanced. 

Even a blank “Backbone” box for us to write in what the backbone is that shows under the name of the Provider would be nice to help keep track, and probably appreciated by more than just me.

**Comment by arcticfoxwpg** [comment]
> as a compromise would it work if we just showed the server personal note there on the right side of the server if the user has 'advanced settings' checked off. as it still makes logical sense to show 'advanced' info on the non-drill down and drilled down view.
> 
> crudely like ![firefox_2024-11-02_13-50-11](https://private-user-images.githubusercontent.com/500882/382498052-50b32812-ef7a-4180-b200-03c575df9623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzYzMDksIm5iZiI6MTczMDU3NjAwOSwicGF0aCI6Ii81MDA4ODIvMzgyNDk4MDUyLTUwYjMyODEyLWVmN2EtNDE4MC1iMjAwLTAzYzU3NWRmOTYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxOTMzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWE5OWI3OGIyZGMzYzkwZjY3M2Y0YTljMDcxMjg5NDI3YjliZWRjOTA1YmM4YzNmYTJiMWIxZDJiYWYwNWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nvAWHZW-TLtMsLhAs2hG_eo46po4A68lAG8H12lyku4)

I like that.

**Comment by Safihre** [comment]
Added it, for 4.4.0:
![image](https://github.com/user-attachments/assets/10a3b35d-e5f5-40ce-bb4f-97090e5104c9)

**Comment by sanderjo** [comment]
"The network is the administration" ... so I wrote a few lines of python which determine the hoster of a news provider. Example output:

news.eweka.nl hosted by ['Eweka Internet Services BV']
news.hitnews.com hosted by ['Abavia S.r.l. Technical Role account']
news.newshosting.com hosted by ['BaseIP Network Operations', 'Eweka Internet Services BV']
news.bulknews.eu hosted by ['Abavia S.r.l. Technical Role account']
news.usenetexpress.com hosted by ['US-VITALNG-20160517', 'UsenetExpress-IAD', 'us-vitalng-IAD']
news.xsnews.nl hosted by ['Abavia S.r.l. Technical Role account']
news.thundernews.com hosted by ['UsenetExpress-IAD']

So ... would it be useful if SABnzbd itself determined the hoster = backbone?

**Comment by arcticfoxwpg** [comment]
> "The network is the administration" ... so I wrote a few lines of python which determine the hoster of a news provider. Example output:
> 
> news.eweka.nl hosted by ['Eweka Internet Services BV'] news.hitnews.com hosted by ['Abavia S.r.l. Technical Role account'] news.newshosting.com hosted by ['BaseIP Network Operations', 'Eweka Internet Services BV'] news.bulknews.eu hosted by ['Abavia S.r.l. Technical Role account'] news.usenetexpress.com hosted by ['US-VITALNG-20160517', 'UsenetExpress-IAD', 'us-vitalng-IAD'] news.xsnews.nl hosted by ['Abavia S.r.l. Technical Role account'] news.thundernews.com hosted by ['UsenetExpress-IAD']
> 
> So ... would it be useful if SABnzbd itself determined the hoster = backbone?
> 
> EDIT:
> 
> Or ... we create this list, put it on github, and a SABnzbd client can consult it.

This would be an excellent feature, if you could automate it.

That way notes can stay open for other things (but should still be moved to the main providers page like shown above)

Helping where I can as I am not a dev, but this map should be of some assistance:

https://svgshare.com/i/14t2.svg

@Safihre can we reopen this to solicit further ideas and discussion? The notes added to the main page was a nice addition, but the work being done by @sanderjo would be another desirable feature.

**Comment by arcticfoxwpg** [comment]
https://whatsmyuse.net/

This one is updated.

**Comment by arcticfoxwpg** [comment]
> > https://whatsmyuse.net/
> > This one is updated.
> 
> that one sadly stale (common complaint on reddit about it).

No it isn't.

I try to do my best to update the info in a timely manner but if I am missing anything or updates are needed please email me at hanswurst09@protonmail.com

Website Last Updated: Oct 2nd, 2024

**Comment by arcticfoxwpg** [comment]
Yeah for sure - but I think that one is the best one. It was updated a month ago, but the UzoReto change was not then, I just copied that to show that they have made some of the latest updates, as well as the Frugal change etc.

No perfect solution, but that one likely stays most up to date. It would be cool if you could just use that list and implement it into Sab.

**Comment by Safihre** [comment]
@sanderjo your info was from a whois call?

**Comment by sanderjo** [comment]
> @sanderjo your info was from a whois call?

Yes. So a SAB instance can do that for the newsservers the user filled out. My implementation uses the whois binary on the OS, so not for standard Windows. I tried some whois python packages, but no success so far. I believe there are online whois services, but I'm not sure about open API's.

Or we can automatically create a central list of all known newsservers with their hosters. Like https://www.appelboor.com/newsservers/newsservers_hosters.txt

**Comment by sanderjo** [comment]
For example:
```
news-eu.usenetexpress.com hosted by ['AMS-Hosting-LLC']
uswest.newsdemon.com hosted by ['UsenetExpress-FMT']
de.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
europe.newsdemon.com hosted by ['UsenetExpress-IAD']
europe-ssl.newsdemon.com hosted by ['UsenetExpress-IAD']
green.usenetnews.net hosted by ['UsenetExpress-IAD']
news.binaryboy.com hosted by ['UsenetExpress-IAD']
news-eu.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
news-eu-ssl.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
news.maximumusenet.com hosted by ['UsenetExpress-IAD']
news.newsdemon.com hosted by ['UsenetExpress-IAD']
news.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
news-ssl.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
news.thecubenet.com hosted by ['UsenetExpress-IAD']
news.thundernews.com hosted by ['UsenetExpress-IAD']
news.usenetprime.com hosted by ['UsenetExpress-IAD']
nl.newsdemon.com hosted by ['UsenetExpress-IAD']
secure.news.thecubenet.com hosted by ['UsenetExpress-IAD']
secure.us.thundernews.com hosted by ['UsenetExpress-IAD']
useast.maximumusenet.com hosted by ['UsenetExpress-IAD']
useast.newsdemon.com hosted by ['UsenetExpress-IAD']
us.newsdemon.com hosted by ['UsenetExpress-IAD']
us.newsgroupdirect.com hosted by ['UsenetExpress-IAD']
us-secure.maximumusenet.com hosted by ['UsenetExpress-IAD']
us-secure.newsdemon.com hosted by ['UsenetExpress-IAD']
us.thundernews.com hosted by ['UsenetExpress-IAD']
news.usenetexpress.com hosted by ['us-vitalng-IAD', 'UsenetExpress-IAD']

```

**Comment by Safihre** [comment]
Only thing that doesn't cover is when providers use multiple backbones internally.

I just don't think we as a download client should get into this..

**Comment by arcticfoxwpg** [comment]
> Only thing that doesn't cover is when providers use multiple backbones internally.
> 
> I just don't think we as a download client should get into this..

Why not? It would be such an awesome feature and it looks like it isn’t too hard to implement.
