### ISSUE TITLE
Classic skin does not get removed on upgrade to 0.8 (on Windows)

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#298]
When upgrading to 0.8 from 0.7.2 using the installer on Windows, the Classic skin does not get deleted. 
If the user has chosen Classic as his skin before upgrading, the skin will still be used after upgrade. Going to the History-tab will then result in an fatal error due to the incompatibility.

The installer should delete the directory and after first-run the settings of 1st and 2nd web-interface should be changed to Glitter if they were set to Classic.

**Comment by shypike** [comment]
Solved.
