### ISSUE TITLE
Web GUI Displays Tab Layout Despite Being Disabled

### ISSUE THREAD

**Issue by loxoron218** [sabnzbd/sabnzbd#2981]
### SABnzbd version

4.3.3

### Operating system

Arch Linux

### Using Docker image

None

### Description

When running SABnzbd, the browser automatically opens the web GUI, but the interface displays the tab layout even though the tab layout setting is turned off in the configuration. 

This issue occurs upon starting the application. However, after refreshing the website, the tab layout issue is resolved in most cases.

**Comment by loxoron218** [comment]
I'm not using any reverse proxy and actually, I'm using Firefox in private mode, so I shouldn't have any cache after rebooting...

**Comment by mnightingale** [comment]
@loxoron218 I think that PR will fix it, for now you may wish to edit your `sabnzbd.ini` and remove `"displayTabbed":false,` from `interface_settings`
