### ISSUE TITLE
Improve archive password accessibility

### ISSUE THREAD

**Issue by ryehamstrawberry** [sabnzbd/sabnzbd#2986]
### Description

Upon importing an nzb with password, the password is displayed in the queue but it isn't easily copied, which leaves the user with only a few inconvenient options:
- enable auto-unrar (not always ideal if queue contains an assortment of items that don't all require extraction, which can be mitigated by placing all passworded files at the beginning or end of the download queue then enabling/disabling auto-unrar but this process itself is inconvenient and requires babysitting);
- open the nzb file in text editor, copy password;
-  attempt to highlight then copy the password while viewing the queue, which requires trial and error text selection via drag-and-drop cursor positions due to queue item behavior on mouseover;
- click "Edit NZB Details - Password" (which seems the most practical relevant to the other options, but still requires additional action to reach)
In my opinion, users should be able to just simply Ctrl+C copy the password that's displayed in the queue without having to perform any supplemental actions. There is a lot of wasted time and energy having to workaround this currently for something that shouldn't be an issue.

Would it be possible to implement an easier way to copy/access the archive passwords that are displayed in the main queue, but become hidden on mouseover?
Maybe you could implement a toggle, say holding Ctrl key (or a simple toggle box) when viewing the queue to temporarily disable the reordering functionality (and the mouseover effect that hides passwords)?
What if the password remained visible for selection after mouseover, which would allow the opportunity to simply cursor select+copy the password without removing the queue's drag-n-drop reorder functionality?

These are just some initial suggestions, please consider improving or implementing a more efficient way to copy archive passwords, thank you.

**Comment by Safihre** [comment]
Just click the folder icon? 
It shows the password right there. The 1 extra click is bothering you?

**Comment by ryehamstrawberry** [comment]
> Just click the folder icon? It shows the password right there. The 1 extra click is bothering you?

I can see how this would be a non-issue for casual users, but for power users, yes, it is bothersome. 
One item, fine. Multiplied by multiple items x days, inconvenient.
Should be able to simply copy any text that's visible on the screen without jumping through hoops.
A simple toggle to disable drag-n-drop behavior might be a good compromise if nothing else.

**Comment by Safihre** [comment]
That would make it more complicated, only to benefit a very tiny fraction of users. SABnzbd is really tailored to keeping it as simple as possible, in contrast to for example nzbget.
So the 1 click is acceptable.
