### ISSUE TITLE
Failed to connect: Server <server> uses an untrusted certificate [Certificate not valid. This is most probably a server issue.]

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#2993]
### SABnzbd version

4.4.0

### Operating system

Windows

### Using Docker image

None

### Description

I've had several people today come report this on discord but have seen it now for a bit with 4.4.0 release which looks to be fallout of us updating to newer python/cryptography lib.  I've not had time to submit an update to our wiki docs but figure low stakes I'll just create something here so I can reference and if we wanted to see if there is anything we wanted to tweak with cryptography with regards to this.

----

Antivirus/malware apps like Avast/Norton360 when certain features are enabled they insert their own root cert so they can do TLS interception (MITMing the traffic). And while sab 4.3.3 had no problems with that, but with sab 4.4.0 it now those certs in the chain breaks strict validation (which imho is good thing). 

If you google ssl blocking and these apps you can see its a pain for many people but this is the first time I've seen it come up so often for SAB.

User then have two options:
- disable strict cert checking for their usenet server(s)
- or disable the feature in their antivirus app that is inserting the root cert into the chain.

For norton360 you can fix this by disable 'email scanning':
![example](https://github.com/user-attachments/assets/9b35d19d-5d04-4873-a27e-c01a5cd77777)

For avast you can do:
https://support.avast.com/en-us/article/use-antivirus-https-scan/#pc

I had one user debate if this was really the issue, had him install git on windows (https://git-scm.com/) so he would have openssl so he could do `openssl s_client -showcerts -status -connect news.newshosting.com:563`   and see the cert chain. Should only have the two certs (ISRG Root X1 and then newshosting Lets Encrypt) but instead he had 4, 2 being his antivirus webshield ssl crap.

**Comment by Safihre** [comment]
It's probably Python version.
Cryptography isn't used for the connection.

Avast has been doing this for years though..

**Comment by mesa57** [comment]
AVG too

**Comment by sanderjo** [comment]
Nice work, @thezoggy 

BTW: "This is most probably a server issue" is outdated. It was true when we introduced this feature, but now not anymore. Time for a text update?

... for which this could be useful self-analysis:

As you can see the certifcate chain with openssl, maybe also with python? If so, would it be useful that SAB detects such "antivirus webshield ssl crap." to give the user a better clue?

**Comment by Safihre** [comment]
Good one! Did you maybe catch what certificates were listed for them?

Or we can just update the text in general to add this as a possibility.

**Comment by sanderjo** [comment]
I tried https://stackoverflow.com/q/66900982 , but get an empty list.

There's a pip module that works https://pypi.org/project/get-certificate-chain/


```
sander@zwarte:~$ get-cert-venv/bin/python3 
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from get_certificate_chain.download import SSLCertificateChainDownloader
>>> downloader = SSLCertificateChainDownloader()

>>> downloader.run({'host': 'www.google.com'})
{'files': ['./2-CN_www_google_com.crt', './4-CN_WR2_O_Google_Trust_Services_C_US.crt', './1-CN_WR2_O_Google_Trust_Services_C_US.crt', './3-CN_GTS_Root_R1_O_Google_Trust_Services_LLC_C_US.crt', './5-CN_www_google_com.crt', './0-CN_GTS_Root_R1_O_Google_Trust_Services_LLC_C_US.crt']}

>>> downloader.run({'host': 'news.newshosting.com', 'port': 563})
{'files': ['./3-CN_ISRG_Root_X1_O_Internet_Security_Research_Group_C_US.crt', './0-CN_ISRG_Root_X1_O_Internet_Security_Research_Group_C_US.crt', "./1-CN_R11_O_Let's_Encrypt_C_US.crt", './2-CN_www_google_com.crt', "./4-CN_R11_O_Let's_Encrypt_C_US.crt", './2-CN_newshosting_com.crt', './4-CN_WR2_O_Google_Trust_Services_C_US.crt', './2-CN_eweka_nl.crt', './1-CN_WR2_O_Google_Trust_Services_C_US.crt', './3-CN_GTS_Root_R1_O_Google_Trust_Services_LLC_C_US.crt', './5-CN_eweka_nl.crt', './5-CN_www_google_com.crt', './0-CN_GTS_Root_R1_O_Google_Trust_Services_LLC_C_US.crt']}
```



Is that true for newshosting? Google? No:

```
sander@zwarte:~$ echo Q | openssl s_client -showcerts -status -connect news.newshosting.com:563 2>&1 | grep -i google
sander@zwarte:~$
```

Bug, feature, adding up results, or PEBKAC?

**Comment by sanderjo** [comment]
@thezoggy 
"ssl.create_default_context(): add VERIFY_X509_STRICT and VERIFY_X509_PARTIAL_CHAIN to the _default_ verify_flags "

Can't we just remove it from verify_flags, and keep using python3.13?

```
$ python3.13
Python 3.13.1 (main, Dec  4 2024, 08:54:15) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.create_default_context().verify_flags
<VerifyFlags.VERIFY_X509_STRICT|VERIFY_X509_TRUSTED_FIRST|VERIFY_X509_PARTIAL_CHAIN: 557088>
```

**Comment by sanderjo** [comment]
What do we see as the real solution?

- python 3.13, with default checking, and user should disable his virusscanner for SABnzbd?
- python 3.13, with default checking, but with extra SABnzbd loose check solution "strict, but without VERIFY_X509_STRICT and VERIFY_X509_PARTIAL_CHAIN"?
- python 3.12?
- ...

**Comment by Safihre** [comment]
I feel we shouldn't do anything? Just let them disable their virusscanner for NNTP scanning?
I saw a few of these pop up, but not really a landslide of issues like we had before with the false-positive detections on the exe.

**Comment by mesa57** [comment]
SabNZBD is solely a usenet downloader. So if multiple virusscanner handle NNTP trafic the same as mail (IMAP, SMTP, POP3) i think Sab should not do VERIFY_X509_PARTIAL_CHAIN or make it optional in the settings.

**Comment by Safihre** [comment]
Do we even need to remove `VERIFY_X509_STRICT`?
Seems `VERIFY_X509_PARTIAL_CHAIN` is enough?

**Comment by mesa57** [comment]
I had same thoughts, but are not able to test that.

**Comment by Safihre** [comment]
I made a build here:
https://github.com/sabnzbd/sabnzbd/actions/runs/12317221941

Only on Windows though. Or should it be for all OS?

**Comment by Blackbat007** [comment]
> I made a build here: https://github.com/sabnzbd/sabnzbd/actions/runs/12317221941
> 
I'm happy to test on Windows 11 if you can point me in the directory of the binary.

**Comment by Blackbat007** [comment]
Having tested with the build linked to above I'm still getting the "untrusted certificate [Certificate not valid. This is most probably a server issue.]  error" with Avast anti-virus and anti-track running.

**Comment by OJBakker** [comment]
I have tested the installer from the link posted by thezoggy. The problem is still the same.
My system: Windows 10 x64
antivirus: AVG free
sabnzbd installed with the windows installer.

**Comment by sanderjo** [comment]
I can reproduce with SABnzbd 4.4.0 on Windows with AVG Free:

![image](https://github.com/user-attachments/assets/01b62197-729c-4bfb-b58f-dcb9aab45b59)

... and alas also with the patched version provided by @Safihre 

![image](https://github.com/user-attachments/assets/9aede777-ecb7-4bcf-93fc-4e4faaf4ad0e)

**Comment by sanderjo** [comment]
Pity: with get-certificate-chain I don't see anything strange.

![image](https://github.com/user-attachments/assets/5e8e9ec7-15e3-4518-a102-35160e4a087c)

**Comment by Safihre** [comment]
I'll try to make a build with both flags later today.

**Comment by sanderjo** [comment]
@thezoggy no openssl on this Windows?

Note: I'm not good with Windows.

![image](https://github.com/user-attachments/assets/0326e95f-3e39-4a07-9827-4fccda720fc1)

**Comment by sanderjo** [comment]
OK, installed git from git-scm.com. Still no openssl in PATH, but after some searching, I found it. And/but: no error when connecting with openssl.

![image](https://github.com/user-attachments/assets/7c6fecfd-7a85-46f0-b6ca-da633c4d256d)

SABnzbd: still an error.

![image](https://github.com/user-attachments/assets/abe5977e-92fd-4537-a997-c14b597236ba)

**Comment by mnightingale** [comment]
You are testing different ports (443 vs 563) is presumably AVG is only intercepting 563?

**Comment by sanderjo** [comment]
> You are testing different ports (443 vs 563) is presumably AVG is only intercepting 563?

Ah, yes:

![image](https://github.com/user-attachments/assets/1da676ac-364e-4c14-afae-88061e1c872d)

**Comment by sanderjo** [comment]
> After installing git your path should have been updated, just need to launch a new session or reboot.

I would think so too. But after a few reboot: nothing.

![image](https://github.com/user-attachments/assets/047b00a2-f5e8-481b-abd2-6469a155da25)

Sorry for all the screenshot: Windows is running in side Gnome Boxex VM, and text copy-paste between guest and host is not working

**Comment by sanderjo** [comment]
and I can now reproduce with a simple python script

port 443 (https): no SSL problem
port 563 (nntps): certificate problem

![image](https://github.com/user-attachments/assets/e4802230-8401-40b4-877d-2603b70a5d4c)

**Comment by sanderjo** [comment]
OK, back to my python script: 

With ssl.VERIFY_X509_STRICT unset in context.verify_flags , no more problem when on port 563 (NTTPS)

(and ssl.VERIFY_X509_PARTIAL_CHAIN doesn't matter).

So @Safihre was very close with his intermediate release: just the other option!


![image](https://github.com/user-attachments/assets/86300f42-f042-4a73-92da-4cb534853858)

**Comment by sanderjo** [comment]
Nice: same for news.eweka.nl ... via Advanced set port to 443 (HTTPS), and no certificate problem.

So that is a nice workaround for newsservers serving on port 443 with the mainstream SABnzbd 4.4.0. At least: proven for AVG Free ... I don't know about other virusscanners, but I have hope.

![image](https://github.com/user-attachments/assets/93b6cae1-38be-47c5-a3a7-857ffb22694d)

**Comment by sanderjo** [comment]
So ... how many servers are listening on port 443?

```
$ cat port443_checking.txt | grep PORT | wc -l
165
```

And nothing on port 443:

```
$ cat port443_checking.txt | grep -vi PORT | wc -l
137
```


```
$ cat check_nntps_port443.sh 
echo -n $1
echo -n " "
echo "HELP\r\n" | timeout 2 openssl s_client  -connect $1:443 2>&1 | grep DONE | sed -e 's/DONE/PORT443 OK/g' | tr -d "\n"
echo " "
```

```
$ cat run_on_all_servers.sh 
lynx --dump https://www.appelboor.com/newsservers/newsservers-with-SSL---2024-11-30.csv | grep -vi NOK | awk -F\" '{ print "./check_nntps_port443.sh " $2 }' | sh
```

**Comment by sanderjo** [comment]
Listening on port 443
```
123.sslusenet.com PORT443 OK 
beta.usenetserver.com PORT443 OK 
block.cheapnews.eu PORT443 OK 
blue.usenetnews.net PORT443 OK 
bonus.frugalusenet.com PORT443 OK 
bonus.usenetprime.com PORT443 OK 
chicago.usenetserver.com PORT443 OK 
east.usenetserver.com PORT443 OK 
eco.freediscussions.com PORT443 OK 
eu.astraweb.com PORT443 OK 
eu.bintube.com PORT443 OK 
eunews2.blocknews.net PORT443 OK 
eunews2.usenetnow.net PORT443 OK 
eunews2-v6.blocknews.net PORT443 OK 
eunews2-v6.usenetnow.net PORT443 OK 
eunews.blocknews.net PORT443 OK 
eunews.usenetnow.net PORT443 OK 
euro.fastusenet.org PORT443 OK 
eu.usenetprime.com PORT443 OK 
farm.newsgroupdirect.com PORT443 OK 
gold.usenetnews.net PORT443 OK 
green.usenetnews.net PORT443 OK 
hsplus.usenetserver.com PORT443 OK 
hspsecure.usenetserver.com PORT443 OK 
my.usenetserver.com PORT443 OK 
news20.forteinc.com PORT443 OK 
news2.newshosting.com PORT443 OK 
news4.dwld.link PORT443 OK 
news4.pfcorner.nl PORT443 OK 
news4.usenet4u.nl PORT443 OK 
news4.usenet.farm PORT443 OK 
news.aeton.nl PORT443 OK 
news.ams.newshosting.com PORT443 OK 
news.ams.usenetserver.com PORT443 OK 
news.astraweb.com PORT443 OK 
news.bulknews.eu PORT443 OK 
news.caiway.nl PORT443 OK 
news-central.giganews.com PORT443 OK 
news.cheapnews.eu PORT443 OK 
news-de.newshosting.com PORT443 OK 
news.dwld.link PORT443 OK 
news.easyusenet.nl PORT443 OK 
news.eternal-september.org PORT443 OK 
news-eu.newshosting.com PORT443 OK 
news-europe.giganews.com PORT443 OK 
news-eu.usenetexpress.com PORT443 OK 
news-eu.usenetserver.com PORT443 OK 
news.eu.usenetserver.com PORT443 OK 
news.eweka.nl PORT443 OK 
news.extremeusenet.nl PORT443 OK 
news.fastusenet.org PORT443 OK 
news.forteinc.com PORT443 OK 
news-fr7.eweka.nl PORT443 OK 
news.fr7.newshosting.com PORT443 OK 
news.fr7.usenetserver.com PORT443 OK 
news.gebruikhet.net PORT443 OK 
news.giganews.com PORT443 OK 
news.hitnews.com PORT443 OK 
news.iad.newshosting.com PORT443 OK 
news.iad.usenetserver.com PORT443 OK 
news.kpn.nl PORT443 OK 
news.ls.nl PORT443 OK 
news.newsgrabber.nl PORT443 OK 
news.newshosting.com PORT443 OK 
news.newsxs.nl PORT443 OK 
news-nl.newshosting.com PORT443 OK 
news.pureusenet.nl PORT443 OK 
newsreader1.eweka.nl PORT443 OK 
newsreader6.eweka.nl PORT443 OK 
newsreader.eweka.nl PORT443 OK 
news.smsusenet.nl PORT443 OK 
news.solani.org PORT443 OK 
news.sonic-news.com PORT443 OK 
news.stingyusenet.com PORT443 OK 
news.sunnyusenet.com PORT443 OK 
news.supernews.com PORT443 OK 
news.tweaknews.eu PORT443 OK 
news.u2day.nl PORT443 OK 
news.usenetbucket.com PORT443 OK 
news.usenetdeal.com PORT443 OK 
news.usenetexpress.com PORT443 OK 
news.usenet.farm PORT443 OK 
news.usenetfarm.eu PORT443 OK 
news.usenetmax.com PORT443 OK 
news.usenetnow.net PORT443 OK 
news.usenet.org PORT443 OK 
news.usenetprime.com PORT443 OK 
news.usenetserver.com PORT443 OK 
news-us.newshosting.com PORT443 OK 
news-us.usenetserver.com PORT443 OK 
news.vipernews.com PORT443 OK 
news.xennanews.com PORT443 OK 
news.xlned.com PORT443 OK 
news.xs4all.nl PORT443 OK 
news.xsnews.nl PORT443 OK 
newszilla.xs4all.nl PORT443 OK 
nhxl.newshosting.com PORT443 OK 
nntp10.usenetserver.com PORT443 OK 
nntp1.usenetserver.com PORT443 OK 
nntp2.usenetserver.com PORT443 OK 
nntp3.usenetserver.com PORT443 OK 
nntp4.usenetserver.com PORT443 OK 
nntp6.usenetserver.com PORT443 OK 
nntp7.usenetserver.com PORT443 OK 
nntp8.usenetserver.com PORT443 OK 
nntp9.usenetserver.com PORT443 OK 
nntp.usenetserver.com PORT443 OK 
post.eweka.nl PORT443 OK 
power.freediscussions.com PORT443 OK 
pro.sslusenet.com PORT443 OK 
reader2.newsxs.nl PORT443 OK 
reader443.eternal-september.org PORT443 OK 
reader.5eurousenet.com PORT443 OK 
reader6.xlned.com PORT443 OK 
reader.easyusenet.nl PORT443 OK 
reader.extremeusenet.nl PORT443 OK 
reader.high-way.me PORT443 OK 
reader-intern.xsnews.nl PORT443 OK 
reader.i-telligent.com PORT443 OK 
reader.i-telligent.net PORT443 OK 
reader.newsxs.nl PORT443 OK 
reader.simply-premium.com PORT443 OK 
reader.turbousenet.com PORT443 OK 
reader.usenet.agency PORT443 OK 
reader.usenetbucket.com PORT443 OK 
reader.usenetdiscounter.com PORT443 OK 
reader.usenight.com PORT443 OK 
reader.xsnews.com PORT443 OK 
reader.xsnews.co.uk PORT443 OK 
reader.xsnews.de PORT443 OK 
reader.xsnews.es PORT443 OK 
reader.xsnews.fr PORT443 OK 
reader.xsnews.it PORT443 OK 
reader.xsnews.nl PORT443 OK 
reader.xsnews.pt PORT443 OK 
reader.xsusenet.com PORT443 OK 
secure-beta-eu.news.easynews.com PORT443 OK 
securebeta.usenetserver.com PORT443 OK 
secure-beta-us.news.easynews.com PORT443 OK 
secure-eu.news.easynews.com PORT443 OK 
secure.fastusenet.org PORT443 OK 
secure.news.easynews.com PORT443 OK 
secure.news.eu.easynews.com PORT443 OK 
secure.usenetserver.com PORT443 OK 
secure-us.news.easynews.com PORT443 OK 
ssl.astraweb.com PORT443 OK 
ssl-eu.astraweb.com PORT443 OK 
ssl.hitnews.com PORT443 OK 
sslreader.eweka.nl PORT443 OK 
ssl-us.astraweb.com PORT443 OK 
ssl.xlvonline.com PORT443 OK 
super.newsgroupdirect.com PORT443 OK 
test-secure-eu-ipv4.news.easynews.com PORT443 OK 
test-secure-eu.news.easynews.com PORT443 OK 
test-secure-us-ipv4.news.easynews.com PORT443 OK 
test-secure-us.news.easynews.com PORT443 OK 
test.usenetserver.com PORT443 OK 
textnews.eweka.nl PORT443 OK 
unlimited.newshosting.com PORT443 OK 
upload.eweka.nl PORT443 OK 
us.astraweb.com PORT443 OK 
us.bintube.com PORT443 OK 
usnews.blocknews.net PORT443 OK 
usnews.usenetnow.net PORT443 OK 
west.usenetserver.com PORT443 OK 

```

**Comment by sanderjo** [comment]
Nothing on port 443:

```
ams2.sslusenet.com  
aviteo-ams-flatrate-v2.xennanews.com  
aviteo-ams-v2.xennanews.com  
beta-eu.news.easynews.com  
beta-us.news.easynews.com  
de.newsgroupdirect.com  
de.sslusenet.com  
eco.usenet.nl  
eu6.astraweb.com  
eunews2.frugalusenet.com  
eunews2-v6.frugalusenet.com  
eu.newsdemon.com  
eunews.frugalusenet.com  
eu.newsleecher.com  
eunews-v6.blocknews.net  
eunews-v6.frugalusenet.com  
eunews-v6.usenetnow.net  
europe.frugalusenet.com  
europe.maximumusenet.com  
europe.newsdemon.com  
europe.newsgroupdirect.com  
europe-ssl.maximumusenet.com  
europe-ssl.newsdemon.com  
europessl.usenet-access.com  
europe.thecubenet.com  
eu.thundernews.com  
eu-tst.newsgroupdirect.com  
flat.usenext.de  
high2.usenext.de  
high.usenext.de  
highwinds.zeelandnet.nl  
iad.sslusenet.com  
news1.usenet.nl  
news2.snelnl.com  
news3.snelnl.com  
news4.easynews.com  
news6.ams.newshosting.com  
news6.ams.usenetserver.com  
news6.astraweb.com  
news6.easynews.com  
news6.eu.easynews.com  
news6.eu.usenetserver.com  
news6.eweka.nl  
news6.fr7.newshosting.com  
news6.fr7.usenetserver.com  
news6.iad.newshosting.com  
news6.iad.usenetserver.com  
news6.newshosting.com  
news6.pureusenet.nl  
news6.sunnyusenet.com  
news6.tweaknews.eu  
news6.tweaknews.nl  
news6.us.easynews.com  
news6.usenet.farm  
news6.usenetserver.com  
news6.xlned.com  
news-de6.newshosting.com  
news-de.newsgroup.ninja  
news.easynews.com  
news-eu6.newshosting.com  
news-eu6.usenetserver.com  
news.eu.easynews.com  
news-eu.newsgroupdirect.com  
news-eu-ssl.newsgroupdirect.com  
news.frugalusenet.com  
news.maximumusenet.com  
news.newsdemon.com  
news.newsgroupdirect.com  
news.newsgroup.ninja  
news.newsleecher.com  
news-nl6.newshosting.com  
news-nl.newsgroup.ninja  
news.premium-news.de  
news.shemes.com  
news.snelnl.com  
news-ssl.newsgroupdirect.com  
news.ssl.nl.prepaid-usenet.de  
news.ssl.usa.prepaid-usenet.de  
news.sslusenet.com  
news.thecubenet.com  
news.thundernews.com  
news.tweaknews.nl  
news-us6.newshosting.com  
news-us6.usenetserver.com  
news.us.easynews.com  
news.usenext.com  
news.usenext.de  
news-us.newsgroup.ninja  
news-v6.frugalusenet.com  
nl.newsdemon.com  
nl.newsgroupdirect.com  
nl.sslusenet.com  
nl.thundernews.com  
post6.eweka.nl  
power2.usenet.nl  
power.usenet.nl  
proxy.news.easynews.com  
reader6.newsxs.nl  
reader.snelnl.com  
secure6.news.easynews.com  
secure6.news.eu.easynews.com  
secure6.news.us.easynews.com  
secure.europe.thecubenet.com  
secure.eu.thundernews.com  
secure.newsgroup-binaries.com  
secure.news.thecubenet.com  
secure.nl.thundernews.com  
secure.us.thundernews.com  
ssl-news2.snelnl.com  
ssl-news.snelnl.com  
ssl.usenet-access.com  
tele2.sslusenet.com  
test-eu-ipv4.news.easynews.com  
test-eu-ipv6.news.easynews.com  
test-eu.news.easynews.com  
test-secure-eu-ipv6.news.easynews.com  
test-secure-us-ipv6.news.easynews.com  
test-us-ipv4.news.easynews.com  
test-us-ipv6.news.easynews.com  
test-us.news.easynews.com  
test.xsnews.com  
us6.astraweb.com  
useast.maximumusenet.com  
useast.newsdemon.com  
usenetnl-ams-flatrate-v2.xennanews.com  
usenetnl-ams-v2.xennanews.com  
usenet.premiumize.me  
usenet.premium.to  
us.newsdemon.com  
us.newsgroupdirect.com  
us.newsleecher.com  
usnews-v6.blocknews.net  
us-secure.maximumusenet.com  
us-secure.newsdemon.com  
us.sslusenet.com  
us.thundernews.com  
uswest.newsdemon.com  

```

**Comment by Safihre** [comment]
New build that removes both flags:
https://github.com/sabnzbd/sabnzbd/actions/runs/12333023293

**Comment by sanderjo** [comment]
Bingo! Works with port 563 and AVG Free:

![image](https://github.com/user-attachments/assets/6bd61661-4391-4f36-b5fe-68e4a6caf594)

**Comment by OJBakker** [comment]
I have tested the latest build  from the link posted by Safihre. 
This build seems to have fixed the certificate-errors.
My system: Windows 10 x64
antivirus: AVG free
sabnzbd installed with the windows installer.

**Comment by mesa57** [comment]
Here the same.
![afbeelding](https://github.com/user-attachments/assets/7aea82c3-8833-4f82-97a1-4ee0774f1dee)

Thank you @Safihre !

**Comment by Blackbat007** [comment]
The new build has fixed the certificate error for me too, thanks.

Windows 11 with Avast

**Comment by Safihre** [comment]
@sanderjo @thezoggy how about we introduce Certificate Validation level High? Which disables these checks?
Then we can update the error to say they can try High instead of Strict in case of certificate errors. 
Default stays Strict.

**Comment by sanderjo** [comment]
So "High" is lower than "Strict"? 

I would like SABnzbd to be clever and self-analysing. Do not put the burden on the user.

So: if Strict, and no connection: SABnzbd itself could try the connection (without login) with the flags unset. If that works, give a clear message to the user he/she can lower from Strict to High. That could/should also be in the wizard.

And High could also be more descriptive. "allow local virusscanner/firewal".

I'm not sure what happens with a MitM attack from somewhere else (so outside the user's computer). They will still fail, even with High setting, right?

And let's change the text "This is most probably a server issue" to ... "security problem between your client and the newsserver", with a URL

**Comment by Safihre** [comment]
No because Minimal disables the Hostname verification. That's quite essential, otherwise any random certificate can be used.

**Comment by sanderjo** [comment]
"Medium - allow certificates locally injected (firewall, virusscanner)"?

![image](https://github.com/user-attachments/assets/01c9fc1a-6b88-44cf-b386-f1093b32e0f3)

**Comment by mesa57** [comment]
Very nice change !

**Comment by Safihre** [comment]
Please check if 4.4.1 fixes it for you. Of course after setting Certificate verification to Medium.
https://sabnzbd.org/downloads

**Comment by Blackbat007** [comment]
> Please check if 4.4.1 fixes it for you. Of course after setting Certificate verification to Medium. https://sabnzbd.org/downloads

It works for me, many thanks :-)

**Comment by sanderjo** [comment]
@mesa57  @Blackbat007 as users, what do you prefer:

1) Sabnzbd 4.4.1, security set to Medium, so using newsserver via official nntps port 563 works. And your firewall/virusscanner is monitoring that traffic
 2) SABnzbd 4.4.0+, security set to Strict, using newsserver via https port 443, which you have to manually set. And your firewall/virusscanner not scanning that traffic
3) same as 2, but SABnzbd automatically sets port to 443.

**Comment by Blackbat007** [comment]
I don't really have a preference, as long as it is clear how to get it working in the event of errors.

**Comment by OJBakker** [comment]
@sanderjo 
I strongly prefer 1. This solver the problem.
2 and 3 are merely circumventing the problem.
With 2 and 3 it is very likely those security programs will notice usenet traffic moving to a different port, see this unmonitored traffic as a security risk and update their programs to 'increase security' by also monitoring port 443. This will then resurface the problem for SABnzbd and we will have the same problem and same discussions again.

**Comment by OJBakker** [comment]
Just tested 4.4.1RC1
It works ok after changing the setting at per-server advanced setting.
This change will be easier for users if the changelog has a note reporting where this setting can be changed.
Change this setting at SABnzbd Config tab: Server, check 'Advanced Settings' and click on button 'Show Details'.

**Comment by mesa57** [comment]
> @mesa57 @Blackbat007 as users, what do you prefer:
> 
>     1. Sabnzbd 4.4.1, security set to Medium, so using newsserver via official nntps port 563 works. And your firewall/virusscanner is monitoring that traffic
> 
>     2. SABnzbd 4.4.0+, security set to Strict, using newsserver via https port 443, which you have to manually set. And your firewall/virusscanner not scanning that traffic
> 
>     3. same as 2, but SABnzbd automatically sets port to 443.

I prefer 1 because most users don't know what they are doing. They just cry "it doesn't work"
