### ISSUE TITLE
More detailed notifications control

### ISSUE THREAD

**Issue by vertigo220** [sabnzbd/sabnzbd#2999]
### Description

I'd like to be able to control specifically which notifications are shown, not just generalized error and warning messages. I get a lot of

`Failed to connect: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

and

`Failed to connect: [WinError 10054] An existing connection was forcibly closed by the remote host`

and

`[downloader:905] Too many connections to server ... [502 Too many connections.]`

messages that keep popping up spamming both Windows notifications and the log in the UI. These happen all the time, don't affect or mean anything, and I don't care about them, and so they're just a major nuisance. It would be great to specify messages, perhaps via keywords or regex, and select which notifications to show, i.e. Windows only, UI only, both, or neither.

**Comment by vertigo220** [comment]
Sure, I could spend (waste) time digging into it, or I could not, since it doesn't affect anything other than throwing a bunch of annoying errors. I don't have the time to troubleshoot every little thing. I have the connections set properly, so it shouldn't be giving that error. And I seem to typically get most of the errors when downloading on a slower connection that's being pushed to its limits, not to mention it can be highly variable in the speed. SAB simply does not seem to do well with connections like these. I've made another issue related to that, but the bottom line is, unless it is made to better handle such a connection, errors like these will continue to occur, and they do nothing but get in my way.

**Comment by Safihre** [comment]
Just reduce your number of connections. It's not Sab that can't handle it, it's your device.
It's closing connections on the lowest level due to problems.

**Comment by vertigo220** [comment]
Never mind, then. God forbid you just make it stop spamming the shit out of me.

**Comment by Safihre** [comment]
God forbid you might actually listen to our advice, the people who make the software.
