### ISSUE TITLE
0.8 - Reported local IPv6 address not really the address when not on IPv6 connection

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#301]
@sanderjo 
On Windows when you're not on a real Ipv6 connection, it will give the IPv6 address of the Tunneling Interface on the dashboard.
This is a little deceptive because you can't do anything with it, even on the same PC going to http://[that-address]:8080 will not let you connect to SAB, also not from any other device.
Makes sense, because the Tunnelling Interface is only made for outward connections.

I was looking on Google but seems there is no uniform way of getting the Windows/Linux/Mac IPV6. But my knowledge about the subject is limited, so I might be Googling the wrong stuff.

**Comment by sanderjo** [comment]
I tried on a Windows 7 machine with 0.8.0 Alpha 3, and ... I can access SABnzbd locally via the IPv6 address of the format http://[2001:0:9d38:6abd:87b:580a:bc57:1119]:8080/

Note: to access SABnzbd over IPv6, you need the set the listening host "SABnzbd Host" to "::" (without quotes) and the restart SABnzbd. First test is then http://[::1]:8080/ 

I tried http://[2001:0:9d38:6abd:87b:580a:bc57:1119]:8080/ from another machine, and that did not work. That might be Windows' default behaviour "IPv6 should be like NAT; accept no unexpected connections from the outside world"

Does this help?

**Comment by Safihre** [comment]
Interesting! 
I changed the listening address to :: and indeed, it works now with the local address.
