### ISSUE TITLE
 Error "local variable 'password' referenced before assignment" while unpacking

### ISSUE THREAD

**Issue by doc-heisenberg** [sabnzbd/sabnzbd#302]
Any NZB now failed with following Error

    Password is Provided with   file{{password}}
    Password is Correct and can be extracted local.

When I try it from WEBUI with the retry Function and give the Password a 2nd time same Issue exist. 

NZB File Status in Webui
######################
Unpack	[xxxxxxxxxx] Error "local variable 'password' referenced before assignment" while unpacking RAR files
Repair	[QboRjxxxxxx] Quick Check OK

This is after the new version from today from github "develop" branch. 

Log File Server: 
###################
2015-08-28 12:52:53,937::ERROR::[newsunpack:551] Unpacking failed, archive requires a password (xxxxxxxxxx.part1.rar)
2015-08-28 13:04:34,072::ERROR::[newsunpack:471] Error "local variable 'password' referenced before assignment" while running rar_unpack on xxxxxxx

Here is the complete Logfile in Debug Mode

http://pastebin.com/GrtTKnJJ

**Comment by shypike** [comment]
Fixed now. Sorry about that.
