### ISSUE TITLE
0.8.x -- glitter - hit target for images/icons

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#310]
Right now there no padding on the glyphicon thus when you go to click on them you have to be right ontop of them.. then when they get focus it makes the image hard to see as it has focus.. you could solve this by using them as bootstrap intended in a button/link element or manually by adding the padding. also the hit target to show the item history (down caret) is really tiny and dangerously close to the delete image.. i dont like this...  

For an example click on the 'Multi-Operations & Sorting' icon. Notice this also is bad for accessibility.

**Comment by thezoggy** [comment]
also only showing actions on hover = death to mobile/touch users (like the modify nzb item/view item)

**Comment by thezoggy** [comment]
config > servers - make the 'Enable' a label for the checkbox toggle..  like it is on the details page..
quite annoying you have to click on the tiny checkbox.. also why is this all in a table :/ also long names get cut off.. also the two enable buttons (when looking at details) can be out of sync...  seems clumsy..

**Comment by Safihre** [comment]
Oke I will look into it!

**Comment by thezoggy** [comment]
note you added the padding yourself on the bottom buttons where you can clear the history.. something like that would work welll

**Comment by Safihre** [comment]
Actually which icon's are you talking about specifically?
Almost all of the glyphicon's are in an a-element with padding to increase the hit-target.

**Comment by thezoggy** [comment]
Various ones, look at the delete one next to the history drop down area. Look at the multi queue ones. Look at how you applied the padding yourself on the queue actions. You aren't using them how bootstrap intended thus your missing the padding that comes with a href or button schema 

-----Original Message-----

**Comment by Safihre** [comment]
Fixed in #399, did not increase the hit size for the delete button's to avoid unintended clicks.
