### ISSUE TITLE
Time-out for user scripts

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#313]
While I see the post-processing script is being ran from the history entry.. I do not see any mention of it in the logs (debug+).

Why I bring this up is because I'm trying to track down what the actual path sab tells the script, as I see some trailing dots:
`2015-09-04 23:28:06 - SABPostProcess - DEBUG - Path: C:\Users\zoggy\downloads\complete\TV\Blue.Bloods.S01E02.720p.HDTV.X264-DIMENSION\Blue.Bloods.S01E02.720p.HDTV.X264-DIMENSION\...`

at the very start i see:
`2015-09-04 23:27:44,799::INFO::[postproc:283] Starting PostProcessing on Blue.Bloods.S01E02.720p.HDTV.X264-DIMENSION => Repair:True, Unpack:True, Delete:True, Script:SABPostProcess.py, Cat:bypass`

But never does sab actually log that it is kicking off that script / what it passed to it.

**Comment by thezoggy** [comment]
Per: http://wiki.sabnzbd.org/user-scripts

argument 3:
`Clean version of the job name (no path info and ".nzb" removed)`

I find that .nzb is not removed on 0.8.x...

**Comment by thezoggy** [comment]
looking at when the user script is called, we see things have changed.. 

0.8.x:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L447
`
                script_log, script_ret = external_processing(short_path(script_path, False), short_path(workdir_complete, False), nzo.filename,
                                                             dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

0.7.20:
https://github.com/sabnzbd/sabnzbd/blob/0.7.x/sabnzbd/postproc.py#L442
`
                script_log, script_ret = external_processing(script_path, workdir_complete, nzo.filename,
                                                             msgid, dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

**Comment by shypike** [comment]
The script call should be logged, but I just found out that it doesn't. The current log call has one parameter too much; the result is not a crash but simply no logging. Weird.
Argument 3 is without ".nzb", as it should be.
Argument 2 and 3 are shortened when above 259. It's still a correct working path. I'd think that changing the documentation would confuse more than enlighten. Scripts generally cannot handle long paths, so it's 0.7.x that fails to do the right thing.

I fixed the logging in commit 62e80940a0d6de4df33d26027b168dbef87e41a8

**Comment by thezoggy** [comment]
odd, i see the .nzb still being left on in 0.8.x:
`2015-09-05 00:37:00 - SABPostProcess - DEBUG - NZB: Blue.Bloods.S01E09.Re-Do.720p.WEB-DL.DD5.1.H.264-NT.nzb`

looking at sab logs, can see that .nzb is not part of the actual name:
```
2015-09-05 00:34:20,729::INFO::[__init__:617] Adding Blue.Bloods.S01E09.Re-Do.720p.WEB-DL.DD5.1.H.264-NT.nzb
...
2015-09-05 00:41:49,808::INFO::[postproc:550] Cleaning up Blue.Bloods.S01E09.Re-Do.720p.WEB-DL.DD5.1.H.264-NT (keep_basic=False)
```

**Comment by shypike** [comment]
I test using Sample-PostProc.cmd for testing and that one shows #3 withhout .nzb

**Comment by thezoggy** [comment]
Confirmed that arg 3 is good, the script I am using was doing arg 2. 

-----Original Message-----

**Comment by Safihre** [comment]
As a side note when changing this: why not also add nzo_id as a parameter as requested by #91 and that issue that was there before?

**Comment by shypike** [comment]
@Safihre Which "issue what there was before"?
I didn't add nzo_id because there already too many positional parms.
My idea was to add environment variables instead, like SABnzbd_fullpath, SABnzbd_title, SABnzbd_nzo_id.

**Comment by Safihre** [comment]
This one:
https://github.com/sabnzbd/sabnzbd/issues/149
It was closed so I thought it was already on there.

**Comment by thezoggy** [comment]
also, in 0.7.x you return `msgid` while 0.8.x returns `nzo.filename`.. is that the same thing?

**Comment by thezoggy** [comment]
also, in 0.7.x you return `msgid` while 0.8.x does not.. thus the argument amount change thus legacy scripts will expect different things.. thus this breaks them and makes the wiki out of date.

**Comment by shypike** [comment]
"msgid" has been empty since we dropped newzbin support.

**Comment by thezoggy** [comment]
can you add it back, so that it doesnt break legacy scripts?

**Comment by shypike** [comment]
It's never been gone. It simply always gives an empty string, like it always has when the item didn't come from newzbin. It's just there to maintain backward compatibility.

**Comment by Safihre** [comment]
No it's gone now, for example Category is now the 5th argument passed to a script while in 0.7 it was the 6th. That would mess up some scripts!

**Comment by thezoggy** [comment]
as noted earlier:

looking at when the user script is called, we see things have changed.. 

0.8.x:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/postproc.py#L447
`
                script_log, script_ret = external_processing(short_path(script_path, False), short_path(workdir_complete, False), nzo.filename,
                                                             dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

0.7.20:
https://github.com/sabnzbd/sabnzbd/blob/0.7.x/sabnzbd/postproc.py#L442
`
                script_log, script_ret = external_processing(script_path, workdir_complete, nzo.filename,
                                                             msgid, dirname, cat, nzo.group, job_result,
                                                             nzo.nzo_info.get('failure', ''))
`

**Comment by shypike** [comment]
This is what matters: https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L157
```command = [str(extern_proc), str(complete_dir), str(filename), str(nicename), '', str(cat), str(group), str(status)]```
Note the empty fifth argument.

**Comment by thezoggy** [comment]
side note: Sample-PostProc.* need to be updated to reflect 8th argument, the failure_url

**Comment by shypike** [comment]
Yeah, maybe but picking the right time-out. Should at least be configurable.
Moving the scripts may be a good idea.

**Comment by thezoggy** [comment]
sure, why i said a sensible default is probably 30mins.. but of course there are those that would want to lower/increase depending on their needs

**Comment by Safihre** [comment]
Instead of a timeout, I implemented that scripts can now also be aborted (from Glitter) while running.
