### ISSUE TITLE
0.7.20 NotifyOSD not working

### ISSUE THREAD

**Issue by Geyup** [sabnzbd/sabnzbd#320]
I'm using 0.7.20 with Firefox 38.2.1 ESR and I noticed that the NotifyOSD does not work when a download is completed...

Also when a download completes and I shut down SABnzbd the shutdown notification does not appear, but, if I just start sabnzb like for the first time and shut it down then I get a shutdown notification.

The startup notification always appears, and when I add a nzb it appears, but when a download completes it's not appearing.

If I go into the settings and click on ```Test Notification``` I get; ```NotifyOSD not working``` after it's completed a download. But if I start sabnzb for the first time and click on ```Test Notification``` it works. Something is messing this up after completing a download of a nzb for some reason... hmm

**Comment by shypike** [comment]
I have looked at this, but cannot reproduce the issue. I tested on Mint.
Which OS are you using?

**Comment by Geyup** [comment]
Sorry Linux...

**Comment by shypike** [comment]
Linux can mean a few hundred different distributions. So, which one and which version?

**Comment by Geyup** [comment]
Slackware 14.1 x86_64

This use to work in the past, so for the life of me I don't know why now, other than SABnzbd doesn't like the Firefox version 38.2.1...

**Comment by shypike** [comment]
Firefox has nothing to do with OSD notifications. Try Chrome, it probably gives the same result.
The problem is that there are so many Linux versions, so many desktop managers and a NotifyOSD library over which we have no control.

**Comment by Geyup** [comment]
I know Firefox has nothing to do with OSD Notifications, I was talking about SABnzbd I meant with the version of Firefox not working correct...

So what are the possible reasons this goes from working to now, not working?

Please go back and read over the first posted I re edited it over...

**Comment by Geyup** [comment]
The problem ONLY happens once a download completes, then it breaks, this seems to indicate a bug in SABNzbd, I don't see how this could be a issue on some other application...

**Comment by Geyup** [comment]
SORRY, actually, my bad, once an nzb has completed a download the notification does not appear at all telling you it's completed. NOW the only other breakage that occurs once a download is completed, is if I shutdown SABnzbd the shut down notification will not appear. BUT if I don't download anything and just start and shutdown SABnzbd then the shutdown notification will appear.

I use xfce4-notifyd for my OSD Notifications and there is nothing in it, that would cause this behaviour. xfce4-notifyd does not care about the way in which something occurs or happens, as long as it's triggered it will send out a notification.

**Comment by shypike** [comment]
> other than SABnzbd doesn't like the Firefox version 38.2.1...

You suggested a connection.
Can you enable "Debug" log in the  Status screen, restart SABnzbd, download a job and then download the log file? Look for the text "Traceback".

**Comment by Geyup** [comment]
ok will do and brb... :)

**Comment by Geyup** [comment]
Here;

http://pastebin.ca/3157364

I don't get this, in the log above I was using a Firefox Addon Random Agent Spoofer;

https://github.com/dillbyrne/random-agent-spoofer

Using this addon, or using Firefox without any addons I was having this problem, now I downloaded a small 28MB PDF and the download complete notification appeared, so I'm confused...

Brb, let me try downloading something larger to see if it matters...

**Comment by Geyup** [comment]
Everytime I download something small like a 30MB PDF the notifications work, then I download a video a few hundred megs in size and it doesn't hmm

Below link is without any addons;

http://pastebin.ca/3157438

**Comment by shypike** [comment]
Hmm, not enough logging.
Can you add this line after line 304 in the file /opt/sabnzbd/sabnzbd/growler.py?
``` logging.info("Traceback: ", exc_info = True)
```
The indentation should be the same as the previous line.
Then download another item.

**Comment by Geyup** [comment]
Look good?

 # Apparently not implemented on this system
                    logging.info(error)
                    logging.info("Traceback: ", exc_info = True)
                    return error

**Comment by Geyup** [comment]
http://pastebin.ca/3157995

**Comment by shypike** [comment]
This is the relevant bit:
```
GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.18 was not provided by any .service files
```
The interface to NotifyOSD is effectively three lines:
```
pynotify.init('icon-summary-body')
note = pynotify.Notification(title, message, icon)
note.show()
```
My conclusion is that there is some setup problem with OSD on your system, or Python's pynotify library module isn't working properly. Both are outside my control.
How did you install SABnzbd on your system?

**Comment by Geyup** [comment]
Slackware build script;

http://slackbuilds.org/repository/14.1/network/sabnzbd/

I have python 2 & 3 both installed, but when sabnzbd is called it's from;

python /opt/sabnzbd/SABnzbd.py "${@}"

Hmm

**Comment by Geyup** [comment]
But if it was something on my end, what does size of file have to do with any of this, that makes no sense.

As I mentioned, if I download a small file it works, download something bigger it doesn't.

I don't see how OSD or pynotify cares about file sizes for notifications. That to me, makes me feel, more like sabnzbd issue.

**Comment by Geyup** [comment]
I mentioned this before, if I go to the Config > Notifications when first starting sabnzbd and click on Test Notification it works, but if I download then click it, it says it fails. I also don't see how that can be an issue on my system, hmm

**Comment by shypike** [comment]
I'm not saying it's an issue on your system. However, pynotify is a Python module that is rather old. All the intelligence is in that module. The only thing SABnzbd does, is call a few functions of it. Given that it does work on multiple other Linux systems, what can I say? I don't have the resources to test all systems and cannot debug yours.
It seems that there is a more modern-style module for doing OSD notifications. I'll have a look at that.

**Comment by Geyup** [comment]
For now I don't get what would of broke it. It's been some time that I've used sabnzbd, but the last time it all worked, and I'm not sure what, if any system updates would create a conflict here.

I also still don't get how when starting sabnzbd for the first time it works, then breaks from a download. I just don't get how notifications would be effected in this way... errrr :(

Does sabnzbd work with python3?

**Comment by shypike** [comment]
It's perfectly possible that something outside of SABnzdb goes wrong. PyNotify and DBUS are way more complicated than the three lines used by SABnzbd. SABnzbd may very well do something which is not quite right, which still worked until recently. Hard to tell.
SABnzbd does not run on Python3.
I'll have a look at an alternative solution, but low priority, we're too busy with release 0.8.0

**Comment by Geyup** [comment]
I'll look into it on my end and let you know if I come up with anything...

thanks

**Comment by Geyup** [comment]
I see you closed this, so how's this looking now?

**Comment by Safihre** [comment]
As mentioned before it seems to be specific to the setup, it wasn't reported by anyone else. So for now we can't really do anything about it from the SAB side of things.. unfortunately!

**Comment by Geyup** [comment]
Well it would sure be nice if someone installed Slackware even in a VM and tested this.

I personally don't get how the Notifications work and only die after a download completes...

**Comment by Geyup** [comment]
So now running 1.0.0 with the below specs it's working! :)

Firefox 38.7.1 ESR
Python Version: 2.7.5 (default, May 29 2013, 02:28:51) [GCC 4.8.0]
OpenSSL: OpenSSL 1.0.1s 1 Mar 2016 [t1, v23, v3, v2]
pyOpenSSL: 0.13.1
