### ISSUE TITLE
FR: Allow multiple feeds per RSS filter

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#323]
I saw this was posted in the forums a long way back, but thought i'd bring it up again

yahoo pipes is dying and I haven't found something that works locally to provide the rss merging. Planet Venus really doesn't like opensuse hehe

If someone has better options for online aggregrators that allow editing of existing feeds, feel free to point me there too.

**Comment by jeffgeorge** [comment]
Can you explain what the benefit would be of implementing multiple-feeds-per-filter rather than just adding multiple feeds as they exist today? Do you just want to prevent having to duplicate the potentially complicated filters?

**Comment by mgaulton** [comment]
Correct. I have multiple RSS which I wanted treated the same way, but
managing filters per RSS would be a nightmare

**Comment by Safihre** [comment]
Duplicate for #680, let's continue discussions/progress there 👍
