### ISSUE TITLE
0.8.x -- not saving randomize_server_ip 

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#324]
config > switches > Server load-balancing
I see that it is always defaulting to `Allow load-balancing with optimization for IPv6`.

If I try to set it to one of the other values, hit save. Coming back to the page you can see that it in fact did not change.

**Comment by thezoggy** [comment]
looking at: https://github.com/sabnzbd/sabnzbd/commit/dbac3a463d17759c6737a60932eb2a1740b83c29

looks like the var was changed to `load_balancing` but the config page didnt get updated

**Comment by Safihre** [comment]
Oops, fixed: #325
