### ISSUE TITLE
sabnzbd - clear dupe info

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#327]
when adding a nzb it can be flagged as a dupe. now i know you can simply turn this feature off.. is there a way to clear the dupe data via the gui? (without deleting physical files from the box)

also, should possible enhance dupe calculation (refer to nzbget)

**Comment by shypike** [comment]
You can resume the duplicate, after that it will just download. Or did you have something else in mind?
0.8.0 already uses the md5sum of the message-id to detect duplicates and it does a series/season/episode scan.

**Comment by thezoggy** [comment]
i want to clear that stored data without resorting to nuking the admin folder. reset the dupe info data.

**Comment by shypike** [comment]
Best way now is to select what you want to get rid of in History and delete those entry/entries.
I'll see what can be improved.

**Comment by thezoggy** [comment]
I dont want to touch history / same nzb name is used but nzb is actually different.... Maybe false dupe detection is happening. 

-----Original Message-----

**Comment by shypike** [comment]
Only History is used as a source for duplicate detection. What you want would mean a substantial redesign, so definitely not for 0.8.0

**Comment by thezoggy** [comment]
so there may be a few issues/feature being asked here.

you say the item in the history is what is used to determine if its a dupe..  so maybe thats what we should focus on.. maybe if a dupe is found, offer a little icon next to the item to show those results in the history (aka, take release name and search for it in history). very easy to do.

and then about the feature, if we wanted to allow users to keep the history but discard the fact people have d/led them (because lets say they lost a hd / deleted stuff on accident).. could just store a ignoreDupe flag with the item that defaults to false, and if the user clicks a button to 'clear dupe info' it just sets all items in history ignoreDupe to true. then in the logic to detect dupe, ignore those items. that way you dont have to have people blow away history or manually click on pause (or bulk set) -- especially for those that dont use sab's ui very often (automation tools).
