### ISSUE TITLE
sab 0.8.x -- config - servers (priority)

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#330]
should show priority / sort by it. sucks to recall which is what when you have 4+ servers... expanding to show the details makes the page so long that you can really see which is which also.

* show priority on collapsed view (config > servers)

* sort server rows as they would be used in sab (priority)

  > so if multiple servers have the same priority... whats the next thing they sort by? or does it randomize between them

**Comment by thezoggy** [comment]
reason i bring this up, i just had one of my block accounts get burned up this week because it seems like it was the default in that priority group..

**Comment by shypike** [comment]
Your sorting proposal makes sense, I'll see what I can do.

**Comment by thezoggy** [comment]
@Safihre including him so he sees the glitter/config change request

**Comment by Safihre** [comment]
Think this is more for @shypike, the line in Glitter and the order in config is output from the Python code.

**Comment by thezoggy** [comment]
Showing priority # on collapsed view 

-----Original Message-----

**Comment by Safihre** [comment]
I can add the priority # on the collapsed view, but I have no clue how to order the servers. I have been trying now for almost an hour with all kind of sorting functions on *conf['servers']* in *interface.py*, but I get so many errors I don't understand (unicode/tuple/dict errors etc) with everything I try, that I will give up now. If @shypike can sort them by priority, I can fix the interface!

**Comment by shypike** [comment]
II will order the servers in both places. But after Beta1.
