### ISSUE TITLE
sab copyright year

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#333]
looking through the code we see that the header on the files is showing different years/ranges/missing. 
https://github.com/sabnzbd/sabnzbd/commit/687ab5d4f59e8d160249fb591e553e8c12d5ba8c

curious if you want me to normalize them (if so, what range?) or if you had a specific reason or if its just an oversight

`# Copyright 2007-2015 The SABnzbd-Team <team@sabnzbd.org>` ?

**Comment by shypike** [comment]
I usually change the "end" year when I touch a module and some haven't been touched for quite a while, The start year varies because new modules were added over the years.
Given that copyright will only expire 75 years after the death of the last contributor, I don't really worry :)

**Comment by thezoggy** [comment]
* conflicting declares across project, should all python files use: '#!/usr/bin/env python -OO' ?

**Comment by shypike** [comment]
@thezoggy 
Only SABnzbd.py and SABHelper.py should have this header.
I want to postpone further changes to 0.9.0
