### ISSUE TITLE
sab 0.8.x -- update gntp?

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#334]
we currently use 0.8, latest is 1.0.2. not really seeing anything major but just to note since our version is from 2012. 

https://github.com/kfdm/gntp/

change log:

```
v1.0.2

        Fix bug with incoming password hash
        Added info about license in each source file

v1.0.1

        Fix bug with binary data (images) being encoded incorrectly

v1.0

        Python 3.3 Support

v0.9

        Remove duplicate code from gntp.config
        Catch all errors and rethrow them as gntp.errors to make it easier for other programs to deal with errors from the gntp library.
        Ensure that we open resource files as “rb” and update the documentation

v0.8

        Fix a bug where resource sections were missing a CRLF
        Fix a bug where the cli client was using config values over options
        Add support for coalescing
```

**Comment by shypike** [comment]
So far: it brings nothing new.
The bug that prevents SABnzbd's icon from showing in Growl isn't fixed (my guess is that it's not caused by GNTP).

**Comment by thezoggy** [comment]
gotcha, well thanks for looking

**Comment by Safihre** [comment]
There's now a version 1.0.3. 
It now allows to use ```file://``` for the icon, does that help us?
https://github.com/kfdm/gntp/

**Comment by shypike** [comment]
Hmm, that would be nice if it worked.
SABnzbd 1.0.0 doesn't show the SABnzbd icon any more.
