### ISSUE TITLE
[req] please include a dark style for Glitter

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#335]
Really like Glitter, but do find it rather bright for everyday use. Would be nice if there were a choice between a light and a dark style, similar to how smpl provides that.

**Comment by Safihre** [comment]
I am going to try to make that!
Just have to play around to find a pretty combination of grey's and black.

**Comment by Stanzilla** [comment]
@Safihre https://www.google.com/design/spec/style/color.html#color-color-palette :)

**Comment by Safihre** [comment]
#338 
My first try :grin:

**Comment by Stanzilla** [comment]
Got a screenshot?

**Comment by jcfp** [comment]
:thumbsup:

**Comment by Safihre** [comment]
![capture](https://cloud.githubusercontent.com/assets/5703454/10079814/7d267b8c-62ec-11e5-8ada-e7b56cde1149.PNG)

**Comment by Stanzilla** [comment]
very nice!

**Comment by jcfp** [comment]
#338 was merged, closing the issue. Safihre, thanks for your hard work!
