### ISSUE TITLE
sab 0.8.x -- logging messages with translation

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#336]
I see that there are some uses of `T` in logging messages but quite sparingly and even when used not consistently.. 

for example in SABnzbd.py `print_modules`:
```
    if sabnzbd.decoder.HAVE_YENC:
        logging.info("_yenc module... found!")
    else:
        if hasattr(sys, "frozen"):
            logging.error(T('_yenc module... NOT found!'))
        else:
            logging.info("_yenc module... NOT found!")
```

I doublt that the string is translated.. if anything maybe do the status (found / not found) but not the whole line..

**Comment by shypike** [comment]
Only errors and warnings are translated, because those appear in the UI. The info and debug statements are for the developers.
This particular example is the way it is because it's a serious issue when _yenc is missing in our Windows and OSX packages.

**Comment by thezoggy** [comment]
plenty of errors that need to be translated then.. 
`logging.error('HTTP and HTTPS ports cannot be the same')`

**Comment by shypike** [comment]
Yes, they should be.
