### ISSUE TITLE
API mb/mbleft/size/sizeleft (and noofslots) only counts found search items

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#352]
I was adding a search-box to the queue but ran into a problem:
When doing a request to the Queue API with something in the search field, the total size of the queue and how much is left is only counted for the ones that match the search query.
This is probably a design choice, but to me it doesn't make sense and causes really weird effects in the GUI where the MB-left goes down when you search (this also happens in Plush).
Can we change this behavior?

Also I was hoping to add maybe some indication of "showing 5 of 144" in both queue/history, but noofslots also goes down when you search. This makes sense, you need it for pagination to know how many results there are in total. 
So I propose adding noofslots_total to the queue/history output?

**Comment by shypike** [comment]
Why doesn't it make sense to show the size of the selected items?

The last suggestion is OK with me.

**Comment by Safihre** [comment]
Because mb/mbleft/size/sizeleft are (to me) about the total queue, not just the selection. 
Now it's almost as if the queue shrinks and seemingly less has to be downloaded, when you search for something.

**Comment by shypike** [comment]
Yeah, I'll add it to the todo.

**Comment by shypike** [comment]
@Safihre  Is this what you had in mind?
https://github.com/sabnzbd/sabnzbd/pull/355
