### ISSUE TITLE
sab 0.8.x -- format_source_url - now useless

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#357]
so back in the day `format_source_url` was used for newzbin, but looks like when that code was cleanup ( https://github.com/sabnzbd/sabnzbd/commit/944568d6dc4926dae401ba23c9d3f50450d1760c ) this is still in use but does nothing..

old code:
https://github.com/sabnzbd/sabnzbd/commit/af54add4715b9533ea845395223bbe8dfc67f8ad

now:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L1258

didn't know if you had plans to use this else where or want to just clean it up (which i can do in this pull request im working on).

note this is only used in one place now:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L1204

**Comment by shypike** [comment]
It's still useful. When let SABnzbd get an NZB from an indexer, it will store and show the URL.

**Comment by thezoggy** [comment]
yeah, but also can see it doing more harm than good as if you grabbed a nzb on one system that can do ssl, send it to sab which cant? it then documents source as http which may or may not be valid. as plenty of sites are https only.

**Comment by shypike** [comment]
SABnzbd always tries to show what the source of the NZB is, so it shows what was actually used on the system.  Not show it because some other installation of SABnzbd might not be able to grab it? Not good enough a reason.
