### ISSUE TITLE
sab 0.8.x -- add_handler -- id vs url

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#358]
`add_handler` which is used by addID and addURL,
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/interface.py#L333

we can see it uses *id* if passed, if not then it uses *url* as the *id*. then eventually it calls the `add_url` with the *id* as the first param.

so if you look at the `add_url` we can see that if the first param doesnt have *http* then return:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/__init__.py#L492

so it seems a bit pointless to accept an id to only have it fail?

**Comment by shypike** [comment]
Ancient code from when we supported newzbin.
Needs cleaning up.

**Comment by thezoggy** [comment]
https://github.com/sabnzbd/sabnzbd/pull/362
