### ISSUE TITLE
sab 0.8.x -- rss config - save button

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#359]
@Safihre on all other config pages, the save button visually shows an action of it saving then returning to the normal state. on the rss page, the save button does not.

**Comment by thezoggy** [comment]
the use of `save` on the rss feeds is fine like it is for the categories. but the rss interval should probably have a `save changes` with the visual changes so it matches the rest of the config pages

**Comment by Safihre** [comment]
Because on the RSS page it is an actual form-submit, not an AJAX call.

**Comment by thezoggy** [comment]
understandable
