### ISSUE TITLE
sab 0.8.x -- startup arguments lost on restart

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#361]
launched sab:
`C:\Program Files (x86)\sabnzbd_0.8.x>python SABnzbd.py --no-api-log`

click on config,
`Parameters: 	SABnzbd.py --no-api-log`

now go to config > general. hit restart. after sab restats, go to config base page
`Parameters: 	SABnzbd.py`

can see that startup arguments are lost

**Comment by shypike** [comment]
True, because it is just a debug tool, I didn't bother to add it to the restart parameters.
You want that?

**Comment by thezoggy** [comment]
Yes please

-----Original Message-----

**Comment by shypike** [comment]
Fixed by removing the cmdline switch and adding a "special": api_logging.
Commit: 5c298520332077e6bd9b7a0cec7ae51d7a1bb25b

**Comment by thezoggy** [comment]
thank you kind sir
