### ISSUE TITLE
Empty special->ipv6_test_host setting shouldn't disable ipv6

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#367]
For users that have problem-free ipv6 connectivity and/or just don't feel like pinging the test host on every program startup and decide to clear out the setting, doing so should cause the program to simply skip the test (and keep ipv6 enabled).

Currently, it tries to run the test anyway despite not having an ipv6_test_host defined, resulting in test failure and disabling of ipv6 capabilities.

**Comment by shypike** [comment]
One could also clear ipv6_test_host to disable the test.
Or should we assume he will have set "no_ipv6"?

**Comment by jcfp** [comment]
Imho, clearing ipv6_test_host should mean: disable the test but don't restrict ipv6 use in sab just because the test wasn't run. So basically mimicing what things were like before the test was added to the code in the first place.

Users that prefer to get rid of ipv6 in sab altogether have the no_ipv6 switch for that. Obviously, in case ipv6 is killed via no_ipv6 anyway the test becomes irrelevant and can also be skipped.
