### ISSUE TITLE
Logout functionality is missing when http login is enabled

### ISSUE THREAD

**Issue by lpallard1** [sabnzbd/sabnzbd#369]
While login functionality is enabled in the application's options, there are no ways to logout of the program.  To "logout" the browser needs to be closed and cookies deleted.

To me it is obvious that a way to logout is needed for privacy & safety considerations.  If you can login you should be capable of logging out.

**Comment by shypike** [comment]
The "basic authentication" protocol we now use, doesn't provide a logout method.
Someday we'll implement better login that will also allow logout.

**Comment by thezoggy** [comment]
note we use basic auth for sab login.. 
for cookies thats only used to store skin specific info.. (plush mainly) for glitter we use localstorage

**Comment by Safihre** [comment]
Close! Added in #442 :)

**Comment by Safihre** [comment]
Not closing? It's in there for a while now.. 
Already for so long maybe we can release 1.1.0 beta1 soon.. With the open pull requests and improvements in Glitter, Config and other details  we have plenty to add.
