### ISSUE TITLE
sab 0.8.x -- glitter - completed timestamp

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#371]
the current format I think is less than ideal.. and no matter what format we pick.. there is always going to be others that want something else. 

for example it shows currently:
`03-10-15 17:09`

the fact I look at it and can't tell if it is MM-DD-YY HH:MM or DD-MM-YY HH:MM at a glance is an issue. also is not any date standard.. personally if we have to go with just one, I'd use YYYY-MM-DD as it sorts nicely. however, we should just offer a set of options and let the user pick?

Taking a page from Sonarr they do a decent job offering a set of options:

Short Date Format:
```
<option value="MMM D YYYY">Mar 5 2014</option>
<option value="DD MMM YYYY">5 Mar 2014</option>
<option value="MM/D/YYYY">03/5/2014</option>
<option value="MM/DD/YYYY">03/05/2014</option>
<option value="DD/MM/YYYY">25/03/2014</option>
<option value="YYYY-MM-DD">2014-03-05</option>
```

Long Date Format:
```
<option value="dddd, MMMM D YYYY">Tuesday, March 25, 2014</option>
<option value="dddd, D MMMM YYYY">Tuesday, 25 March, 2014</option>
```

Time Format:
```
<option value="h(:mm)a">5pm/5:30pm</option>
<option value="HH:mm">17:00/17:30</option>
```

Also offer a switch for **Show Relative Dates**
Which shows Today/Yesterday/1 Week ago/etc instead of absolute dates.

**Comment by Stanzilla** [comment]
http://timeago.yarp.com maybe?

**Comment by Safihre** [comment]
The reason is simply that we don't have the translations for other than regular numeric dates. There are of course international time libraries available for Javascript, but didn't have the time to use those. 
The very long date format will just not fit in all the columns. The history, the error times, etc. 
I already included a commit in my PR that includes some extra numeric date formats.

**Comment by thezoggy** [comment]
@Stanzilla  i like MomentJS better, http://momentjs.com/

**Comment by Safihre** [comment]
@thezoggy I like MomentJS, but it is just so heavy (40kb extra).. Especially with the localisations (125kb..).
I tried just removing the localisations we don't use, but my system translates all the Chinese/Russian/etc characters to question marks when I save the file. I also tried cloning their Github and then removing all the localization files we don't use. But the building fails on my system (even without removing any files).
So, if anyone can build a minimized version with only the languages we use, then I will gladly implement it!

**Comment by thezoggy** [comment]
moment+local is 45kb (minified). personally id rather us use something like this where we have the flexibility of several more lang and formats than trying some crude hack of our known translations that may or maynot be right.

**Comment by Safihre** [comment]
Adding momentjs minified increases the main document from 120kb to 192kb. I think that's a lot.
It also slows down the initial load on mobile devices even more (and it's already slow due to KnockoutJS bindings).
I also want fancier dates, but not convinced it's worth this whole library..

**Comment by thezoggy** [comment]
lets be honest, 60kb isnt much. its not like sab user base is targeted towards those that dont understand downloading/have the tendency to have faster connections. also its a one time hit, you'd cache after that. no differences than you using a font/or other asset.

id much rather have better dates with slightly longer loading than an app that i cant use.

also, to be fair.. and if were talking about some optimized mobile experience.. there are plenty of pitfalls in sab ui/glitter that dont lend itself too well to mobile/small resolutions (some not your fault, but sab in generally). if your so worried about making a mobile first optimized experience.. you could always make a mobile specific skin or use libs like modernizer to know if its a mobile user and dynamically load what you want.

**Comment by Safihre** [comment]
@shypike can put the Feature request  and Fixed  label on this. Was in the PR mentioned above.
