### ISSUE TITLE
sab 0.8.x -- windows + files named Con.*

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#373]
`Con.Man.s01e01.Stalled.720p.WEB-DL.AAC2.0.H.264` - https://nzbcache.info/nzb/64ce652425293504ab056d4f52eb81bb6d99517a.nzb.gz

sab 0.7.x wont even load the nzb without puking on it.
sab 0.8.x loads it, d/les it and extracts.. but then you hear a series of beeps.. and windows internally is freaking out? sab logs look okay oddly. but thought it was interesting. ill send you logs via email.. not really anything for you to do.. but thought it was different :p

**Comment by shypike** [comment]
Known problem in WIndows. You cannot have files called con.* or *.con.
In the (very) old days MSDOS reserved the name "con", so you could not create a file called "con", but you could create "con.txt". Then some complete moron in the Windows NT team decided that "*.con" or "*.con" were also forbidden. This problem is in all versions of Windows since NT.
The same is true for "prn", "aux" and few more of those. BTW: "con" means console.

**Comment by thezoggy** [comment]
yep, i knew about the reserved words.. just thought its odd how sab loading that nzb causes system beeps..

**Comment by Stanzilla** [comment]
*.con works, just con.* works here, I just created a con.txt on Win8.1 just fine.

**Comment by shypike** [comment]
@Stanzilla. What, Microsoft finally solved that problem?

**Comment by Stanzilla** [comment]
Yeah well `con.txt`still fails so... :D

**Comment by thezoggy** [comment]
Stanzilla, 'con' isnt the issue. but 'con.' so try 'con.man' and see.. but then try `mkdir \\?\E:\Test\Con.man` will work just fine.

**Comment by shypike** [comment]
@thezoggy That is odd, because 0.8.0 uses long path notation. I'll look into it further.

**Comment by Stanzilla** [comment]
I said exactly that :p

**Comment by thezoggy** [comment]
@shypike yes, which is why sab 0.8.x can handle it but 0.7.x cant..

**Comment by Stanzilla** [comment]
I reported it as a problem via the Windows 10 feedback app for good measure..

**Comment by shypike** [comment]
Should be fixed now: https://github.com/sabnzbd/sabnzbd/commit/d3d5f37d49e563bfb2a60b72ad9f58a20580608a

**Comment by thezoggy** [comment]
does that only sanitize the file or both the file and folder?

**Comment by shypike** [comment]
The folder name only.
It would be of limited use for file names, because par2 would rename the files back.
What comes out of unrar cannot be influenced anyway: if unrar doesn't handle that well, you're out of luck.
There may be some limited use of applying it to file names as well.

**Comment by thezoggy** [comment]
looks like this is good.. but somewhat hard to directly test.. but providing the 'bad' name when adding the nzb results in a prepended `_` which invalidates it being a reserved word..  so prob safe to say that this is good to go now.
