### ISSUE TITLE
sab 0.8.x -- server priority (load balance)

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#377]
can we add a toggle that allows sab to load balance (randomize/round robin) the requests for servers at the same priority level. that way the 'first' one isnt just used... which becomes an issue for those that have multiple block accounts and you see one just do all the heavy lifting vs spreading it out. 

example, right now i have 5 servers in sab... 

Priority | Name
--------- | -------------
0 | SuperNews
1 | NewsGroupDirect
1 | XSusenet (free)
2 | Astraweb (EU)
2 | BlockNews

do to the current logic.. astraweb vs blocknews.. since astraweb comes first.. it gets hit.. if it has it.. it just burns through that block account. and only if astra doesnt have it.. does it hit blocknews. thus doesnt really matter if blocknews was priority 3 or 2.. the same sab downloading logic outcome happens.

and why i say we should just offer a switch that alters the selection is because there are times where the current logic works well.. for example something like:

Priority | Name
--------- | -------------
0 | SuperNews
1 | XSusenet (free)
2 | Astraweb (EU)
2 | Astraweb (US)

thus hit supernews.. if doesnt have it.. try free account (limited retention and connections.. so performance hit but can help with propigation issues), then fall back to blocks and try eu/us (split connections? try both or just one then the other)

**Comment by shypike** [comment]
I see servers of the same priority share the download.
The fastest one and/or the one with the most connections will take the largest share.

**Comment by thezoggy** [comment]
wonder if we should sort by priority then number of connections? as most likely the ones with more connections can/could yield better speeds...

**Comment by shypike** [comment]
Not necessarily. Speed is often determined by what you pay, independent of number of connections.
It's tough to find a good method that covers all cases.

**Comment by shypike** [comment]
I cannot reproduce the issue.
I tried with two and three servers of the same priority, they balance nicely.
Even tried it with a random generator that fails messages with a 25% chance, to force usage of the other servers. Same result: works fine.
