### ISSUE TITLE
sab 0.8.x -- server changes result in sab download lockup

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#378]
have a download going, change server priority.. you see the d/l stall.. something isnt handled properly and no way to start it going.. pause/resume has no effect. only fix is to restart sab.

**Comment by shypike** [comment]
I did a few simple tests, but could not reproduce the problem.
Can you provide a more detailed scenario?

**Comment by Safihre** [comment]
@thezoggy any more of these problems? I also tried to reproduce it, but couldn't..

**Comment by thezoggy** [comment]
i havent tested this in awhile.. ill try to see if i can reproduce it again this weekend

**Comment by Safihre** [comment]
I can confirm this now, scenario:
Start with 2 servers, 1 being priority 0 and the other priority 2.
Download starts, go into config and change the priority of the second server to 1.
Lockup, doesn't continue unless I restart SABnzbd.

Retried but then changed from priority 2 to priority 0, so same as the other server.
Lockup again..

**Comment by thezoggy** [comment]
i think also if you change the priority around and then ask it to do a download its 'stuck' until you restart

**Comment by shypike** [comment]
So far I have been able to reproduce (once) a situation where the low prio server was used before the high prio server. That was after changing priorities several times during a download.
However (like with Safhire) this was a case where the post was missing completely on the highest prio server. Something isn't right, but it's elusive and I'm not sure how bad it is in reality.
I'll try to debug this further.

**Comment by shypike** [comment]
The problem of not obeying priorities can happen in more situations where priorities are changed "on the fly". I've now managed to cause it with a post that is present on both servers. This does suggest that deadlock situations may also occur.

**Comment by shypike** [comment]
I think I found the cause!

**Comment by thezoggy** [comment]
yay!
