### ISSUE TITLE
Add option to disable backup of .ini file

### ISSUE THREAD

**Issue by rogierlommers** [sabnzbd/sabnzbd#379]
It would be nice to be able to disable the automatic backup of the `.sabnzbd.ini.bak` file during startup.

**Comment by Safihre** [comment]
Why?

**Comment by rogierlommers** [comment]
Because I don't need the backup file :). Don't think it looks nice in my home dir...

**Comment by thezoggy** [comment]
just run sab from git/source, and modify the code so it doesnt do it?

**Comment by Safihre** [comment]
Or, you can just move the config-file and run SABnzbd with the *-f /to/config/file* parameter!

**Comment by rogierlommers** [comment]
Thanks @Safihre , this will indeed solve my problem.
