### ISSUE TITLE
Themes display misleading speed limit when using absolute values

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#388]
Max line speed set to 125M
Speed limit set to an absolute value of 3M using API.
Plush and Simpl displays 2%, Gliiter displays 2% - 2.5MB/sec
I assume this is the rounded percentage of max line speed represented by 3M.
This should be 2.4%, but since the speed-limit UI element doesn't display floats, it gets rounded down to 2%.
The speed-limit enforced is actually 3MB/sec, so it's purely a UI issue.

**Comment by Safihre** [comment]
I fixed this now for Glitter, but's it's too complicated to fix for Plush..

**Comment by thezoggy** [comment]
@Cpuroast can you update and confirm this resolves your concerns?

**Comment by Cpuroast** [comment]
Yup, significantly better.

**Comment by thezoggy** [comment]
mind closing this out?
