### ISSUE TITLE
Automatically unpause when disk space becomes available

### ISSUE THREAD

**Issue by aewne** [sabnzbd/sabnzbd#391]
Feature request.

My sabnzbd instance runs on a remote host with limited disk space so out of necessity sabnzbd is configured to pause downloads whenever disk space reaches a set minimum. Then a cron job pulls these files from the remote host and cleans up, thus freeing up the disk space again. However, if I now want sabnzbd to continue downloading, I'll have to manually unpause it from the interface. So, I humbly ask, can we have an option to autoresume when disk space is available again please?

**Comment by Safihre** [comment]
I can see how this is useful in general, but for your case specific with the cronjob:
Why don't you use the task scheduler of Sabnzbd to unpause at a set time after your moving cronjob? When you're sure it should have moved all files. 
See Config > Scheduling

**Comment by aewne** [comment]
Good idea! I'll have to look into that.

**Comment by thezoggy** [comment]
usually if someone runs out of space, its a pretty big reason.. which requires human interaction. if we just restarted when there was space.. it could cause other issues (core dumps not being written / other stuff to crash).

honestly the best thing to do is just set a min space required for sab... config>folders>Minimum Free Space for Temporary Download Folder. set it to something like 10G or something applicable (take normal download and multiply it by 2.5 to accommodate extraction+pars), that way sab will pause if that folder is that size or smaller.. thus preventing the chance to run out of space...

**Comment by aewne** [comment]
@thezoggy That's exactly what I'm doing now. However, I'd like an option for sabnzbd's space logic to smarten up a little and be able to detect when there's free space available again. Option being the keyword here.

**Comment by thezoggy** [comment]
can you use the scheduler for that?

**Comment by aewne** [comment]
The scheduler doesn't support running custom scripts as far as I can tell. Just unpausing unconditionally is not viable.

**Comment by thezoggy** [comment]
you could run a script (cron) and then fire off curl request to sab's api to unpause?

**Comment by aewne** [comment]
Yup, as discussed with @Safihre, that's what I'll end up doing.

In my opinion though, that's rather hackish for something that should arguably be a feature.

**Comment by pefman** [comment]
Could really need this feature for then you have insanely fast internet, the sab will never keep up moving the files and thus you will need to throttle using the auto resume feature.

**Comment by Safihre** [comment]
Get a bigger disk :wink:

**Comment by RandomNinjaAtk** [comment]
Yeah, I could use this also, but in my case. I'm telling the app via Scheduling, on the hour, every hour to resume. This will be my first test using it that way, but I feel like if there wasn't really space available it would just auto-pause again till the next hour.

**Comment by dweidenfeld** [comment]
Has this been implemented already?

**Comment by vanhecke** [comment]
I currently have an "unpause" scheduled every 1 hour. Works for me because my post-processing is the bottleneck.

WARNING 8 hours ago Too little diskspace forcing PAUSE
WARNING 10 hours ago Too little diskspace forcing PAUSE
WARNING 10 hours ago Too little diskspace forcing PAUSE
WARNING 13 hours ago Too little diskspace forcing PAUSE
WARNING 19 hours ago Too little diskspace forcing PAUSE
WARNING 20 hours ago Too little diskspace forcing PAUSE
WARNING a day ago Too little diskspace forcing PAUSE

**Comment by newb23** [comment]
I have a use case for this as well. I currently have ~45GB of RAM that I am using as a temp download/unrar location, then moving to my array. Having an option to auto-unpause after downloading to RAM (and after processing moving it to disk) would be awesome. 

Additionally, once I get an enterprise SSD (with a bajillion WRITE operations before failure), it would be useful for that case as well. Unless you were able to get a biggun (say, 250GB). But that gets a tad pricey.

**Comment by thezoggy** [comment]
can you really download 45G faster than you can process it to have it move stuff off it?

**Comment by newb23** [comment]
One of the benefits and disadvantages of 1Gb internet speeds and slightly older server hardware, yes. I download significantly faster than the un-raring process takes. Downloading straight to ram helps with the IO wait process both on disk and CPU cycles.

**Comment by thezoggy** [comment]
i have 1g as well (d/l 80-104M/s), personally what I do is check off `switches > post processing > Pause Downloading During Post-Processing` which lets the machine focus its disk io cycles on the job at hand. with directunpack its only paused briefly (few seconds) so it can extract the last file. then it moves the job to the final destination (takes the most time due to 1G to nas). but this has allowed me to d/l using a small ssd without any problems (so similar to your small ramdrive)

**Comment by Davst** [comment]
For me the bottleneck is that I move data offsite at times, and have a difference in dl/ul speed. so it clogs, but auto starting after a while would solve this nicely. Or when there was space again.

**Comment by mraniki** [comment]
any reason not to make this as a feature (vs cron) ?
