### ISSUE TITLE
Setting the speed-limit using the OSX sab menu bar controls is broken

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#392]
In 0.8 beta 2, using the Glitter night theme,
setting the speed-limit using the OSX sab menu bar controls is broken. It doesn't make any changes.

Haven't tried the other themes, but I doubt it should be theme-dependant.
This is on OSX 10.10.5.

**Comment by shypike** [comment]
Will check, we're currently working on speed controls.
