### ISSUE TITLE
Bundle Windows version with up to date OpenSSL

### ISSUE THREAD

**Issue by Geblaat** [sabnzbd/sabnzbd#393]
The windows installer is bundled with OpenSSL 0.9.8l(way behind, released in 2009!), the current latest version of the 0.9.8 branch is at 0.9.8zg. Most updates usually fix multiple security issues, so I would recommend keeping it up to date. Note that both the 0.9.8 and 1.0.0 branch will be discontinued at the end of this year.

**Comment by shypike** [comment]
We're looking at Python 2.7.10 with PyOpenSSL, which will take the OpenSSL level to 1.0.1k
We do need stability testing, because we've had bad experiences with several combinations of Python and OpenSSL.
