### ISSUE TITLE
develop-branche: UnicodeEncodeError(s)

### ISSUE THREAD

**Issue by kooimens** [sabnzbd/sabnzbd#397]
I've got many of them. Especially when downloading music with artists names as Tiësto or Fränkel.

http://pastebin.com/bTQTqcST

**Comment by Safihre** [comment]
What platform are you on?
I cannot reproduce this on Windows. Could you maybe send us one or some of the NZB's it fails on at bugs@sabnzbd.org with a link to this issue?

**Comment by kooimens** [comment]
I'm running Ubuntu Server 14.04.3. An example nzb can be found here:
http://spotweb.be/?page=getnzb&action=display&messageid=H4CADjO6AVUR4hQVg4bsb%40spot.net
(not sure if this is allowed). If you still prefer email, let me know.

**Comment by Safihre** [comment]
Hmm, I tried and cannot reproduce any error with that NZB on Windows or Ubuntu 14 (Desktop).

**Comment by shypike** [comment]
Check the file system settings of your server.
It's likely that what system reports is not the actual file system encoding.
Otherwise force the issue, checkout http://wiki.sabnzbd.org/configure-special-0-8
the option fsys_type.

**Comment by kooimens** [comment]
Thanks for the support! Tried option fsys_type --> 2. That did the job!
