### ISSUE TITLE
0.8.x -- config>server -- change server priority, resort

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#398]
when you load the config>server page, it sorts the servers by priority,name.
thus if you change the server priority, we should resort the page? 
right now you have to manually refresh to reflect the new server order...

**Comment by Safihre** [comment]
Well, we could. Just remove the whole ajaxForm from this page so that it always reloads after save. 
I noticed this behavior but decided it not worth the work to make exceptions for server priority and server name.. Since users use this so so little.

**Comment by Safihre** [comment]
Decided to do a 'real' submit when server priority or name is changed, instead of Ajax submit.
Will be in a PR soon.

**Comment by Safihre** [comment]
Fixed in #399
