### ISSUE TITLE
SABnzb.py shebang python path

### ISSUE THREAD

**Issue by colby-swandale** [sabnzbd/sabnzbd#400]
The sheabng path to the python path will not work on FreeBSD environments as python is linked to the `/usr/local` directory. Can i ask why we're not using `#!/usr/bin/env python` instead?

**Comment by shypike** [comment]
Because that also doesn't work on all systems and the -OO parameter will not be passed by "env".

**Comment by colby-swandale** [comment]
thanks for the explanation.
