### ISSUE TITLE
python 2.7.11 -- just fyi for future builds

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#401]
2.7.11rc1 came out a few weeks ago, 2.7.11 final should be out within the next few weeks.. 
change log: https://hg.python.org/cpython/raw-file/82dd9545bd93/Misc/NEWS

Python 2.7.11 will be 15-20% faster by using computed gotos instead of a switch statement, thanks to a patch from Intel. 

about:
  http://lwn.net/Articles/646888/
benchmarks:
  http://article.gmane.org/gmane.comp.python.devel/153401

not sure how much this will mean to sab.. but figure anything that helps python run faster cant be a bad thing..

**Comment by Safihre** [comment]
Tried it on my Windows10 PC and didn't really see a difference in CPU usage, used the speedlimit to keep it stable at 20MB/s with cache set to 1G and CPU usage seemed the same. Did you notice a difference?

**Comment by shypike** [comment]
I'll use 2.7.11 when a stable version comes out.
It also uses more recent OpenSSL libs.

**Comment by Cpuroast** [comment]
Python 2.7.11 has been released: 2015-12-05

**Comment by shypike** [comment]
@Cpuroast Recent OSX releases use more recent Python versions. However, there is limited backward compatibility and we try avoid having a build for each OSX release.
Currently the latest build we have is created on "Mountain Lion".
I will create a specific "El Capitan" build, which will (at least on that OSX) use the latest and greatest. I'll also check compatibility with "Mountain Lion" and "Yosemite".
"Snow Leopard" will probably be dropped.

**Comment by Cpuroast** [comment]
Snow Leopard, Lion and Mountain Lion should be dropped for 0.8.0.

The upgrade from Mountain Lion to Mavericks, Yosemite or El Capitan is free, so it's not like there's a financial barrier.

There is no reason for someone running Mountain Lion, to not upgrade to at least Mavericks.
Mavericks(10.9), Yosemite(10.10) and El Capitan(10.11) should be the only versions supported.
Would simply the build by reducing the number of versions to maintain.

**Comment by thezoggy** [comment]
Not everyone can or wants to jump to the latest OS... Like why drop win7 support because there's been win8 & 10. Should try and maintain support for largest user base without sacrifice of code/quality. 

-----Original Message-----

**Comment by Cpuroast** [comment]
That's different, Windows 7 is supported till 2020, Window 8.1 is supported till 2023.
On the other hand, Mountain Lion and older have lost all Apple support.

**Comment by thezoggy** [comment]
We could follow chrome... And drop 10.8 and older:

Per chrome:
•Mac OS X 10.6 or later
Note: Support for Mac OS X 10.6, 10.7, and 10.8 will end soon. Learn more - http://chrome.blogspot.com/2015/11/updates-to-chrome-platform-support.html



-----Original Message-----

**Comment by Cpuroast** [comment]
That's exactly what I suggested :)

**Comment by Cpuroast** [comment]
I just saw the 3 builds available in beta4.

I think keeping Mountain Lion around is useless. Apple has dropped support for it quite some time ago, Chrome will be dropping support for Snow Leopard, Lion and Mountain Lion in April 2016 and I'm pretty sure many more will follow.

If you want to at least keep 2 versions around then:

1. Lion, for all the older Intel macs, which never got support for the newer versions of OSX
2. Mavericks, Yosemite and El Capitan, for anything that did.

The small percentage of Mountain Lion users remaining can upgrade for free to Mavericks, Yosemite or El Capitan. The support mac hardware is the same for Mountain Lion all the way to El Capitan.

In the current build, Mavericks and Yosemite, which are the majority of OSX users, are stuck with Python 2.7.2 and TLS 1.0.

And for people that absolutely insist on using Mountain Lion, for whatever reason, it's not like 0.7.20 will stop working.

**Comment by shypike** [comment]
The next release will be:
Build for Mavericks(10.9) 
Build for Yosemite(10.10)
Build for El Capitan(10.11)
The older builds will run on newer OS-ses, but only the El Capitan build running on El Capitan will give you TLS1.2
I cannot get the newer builds to run on older OS-ses.

Not sure our fans will like this...

As for Windows: I'd sooner drop Win8 support than Win7 support...

**Comment by Cpuroast** [comment]
Dropping 10.6 to 10.8 won't be too bad, I've had a look at few market share overviews for those versions and they've shrank to less than 10% of the users.

People on Snow Leopard, Lion and Mountain Lion can simply run 0.7.20 or upgrade to Mavericks, Yosemite or El Capitan if their hardware and software situation allows it and run 0.8.x.

**Comment by shypike** [comment]
Windows and OSX El Capitan binaries will be based on 2.7.11 (TLS1, 1.1 and 1.2)
OSX Yosemite has 2.7.10 (TLS1)
OSX Mavericks has 2.7.9 (only SSL)
Linux and others: whatever your system has.
