### ISSUE TITLE
Symlinks being deleted [Windows]

### ISSUE THREAD

**Issue by Annihilator6000** [sabnzbd/sabnzbd#403]
I have a large TV library that spans multiple drives. I deal with it by using symlinks. The issue with this is that after an episode downloads, repairs, extracts, and is moved, SAB then deletes the symlink in my TV directory.

I've dealt with this by running a background application (Watch 4 Folder) at system startup that monitors the main TV directory for any folders that are deleted (it can't tell the difference between a symlink and an actual folder). When a folder/symlink is deleted it runs a PowerShell script that I wrote that recreates the deleted symlinks. It creates the symlinks with the New-Symlink cmdlet: `New-Symlink -LiteralPath $SymlinkLiteralPath.GetValue($y) -TargetPath $SymlinkTargetPath.GetValue($y)` Symlinks that are created by other means are also deleted.

I've tried setting the logging to debug to see what's going on, but it doesn't return anything about the symlinks being deleted.

Here's my post processing settings:
![image](https://cloud.githubusercontent.com/assets/8271857/11605113/45967eae-9ac5-11e5-8a65-56f46013f867.png)

And my TV sorting settings: 
![image](https://cloud.githubusercontent.com/assets/8271857/11605134/adc0d5b0-9ac5-11e5-9ba9-3b2ed9fc8b61.png)

Directories are as follows:
**C:\Program Files (x86)\SABnzbd** - SAB installation directory
**K:\TV** - SAB TV download directory that contains symlinks to TV show directories on other drives
**E:\TV**, **F:\TV**, etc. - actual tv show directories

Relevant information:
Windows 7 Ultimate x64
SAB 0.7.20 (it's been doing this far before this version)
NTFS file system on all drives

**Comment by Safihre** [comment]
@Annihilator6000 does this still happen with the more recent sabnzbd versions?

**Comment by thezoggy** [comment]
ideally the management of disk is not something within the scope of sab.. have a feeling your hacked together workflow probably got broken when we added long path support by using the `\\?\` syntax.

is K a junction point of E + F ?

**Comment by thezoggy** [comment]
looking back at this, it just looks like bad workflow. dont put your incomplete folder in your complete folder.
