### ISSUE TITLE
URL does not resolve to NZB, must delete manually

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#404]
Python: 2.7.10 x86
OS: Win 10 x64
SAB: d8d261132c203d6cd2ca534790376f02ab55523a

When a URL from an NZB provider gets added to SABnzb via the API, it does not always resolve.  The only way to fix, is to manually delete each one individually.

**Comment by labrys** [comment]
Sorry, forgot to clarify.  The URL is valid.  For example if you click on the edit pencil, copy the url and paste it into the browser, the NZB downloads.  Adding the NZB to the SAB (either through clicking on it or putting it in the blackhole folder) adds it just fine.

**Comment by shypike** [comment]
Does an error message show up in History (or in the log file)?
Even so, using a URL that works in a browser is no guarantee. Chances are that you are logged into the site with that same browser. An usable indexer URL usually contains user credential codes.

**Comment by labrys** [comment]
Unfortunately I cleared the logs when I updated to the latest commit, however its fairly easy to reproduce.  I will add a bunch of files and give them some time to resolve.  It is unlikely (but possible) that I was logged in with the browser since I never use the indexers via browsers.  In addition many others from the same provider resolve in SAB just fine.

**Comment by shypike** [comment]
>  In addition many others from the same provider resolve in SAB just fine.

That sounds more like a provider problem...
You still need the logs for more detailed info. Don't forget to set logging to "Debug".

**Comment by labrys** [comment]
It's set and I have added a bunch of files.. I also get this issue with three separate providers.

**Comment by labrys** [comment]
Even if this does prove to be just a local issue with the providers, would it be possible to make the unresolved NZBs selectable with multi-operations so that they could be deleted en-masse instead of individually?

**Comment by Safihre** [comment]
Will add that!

**Comment by labrys** [comment]
That would be awesome! You guys rock! :+1:

**Comment by labrys** [comment]
Here's my log all NZBs were added approx 18 hours ago.
https://gist.github.com/labrys/f6713adf310e534a0f6c

**Comment by shypike** [comment]
@labrys So far nothing found in the log. There's isn't a single log of an URL entering the queue.
Can you email the URLs that fail to bugs@sabnzbd.org ?

An unrelated question, how do you run SABnzbd?
I'm asking because I see this in the log "_yenc module... NOT found!".
This suggests that you are not running the binary distribution. Although it has nothing to do with the problem, there is a performance hit if when decoding articles.

**Comment by labrys** [comment]
Installed via git-clone and run via command line python.  I'll email the URLs when I get a chance.

**Comment by Safihre** [comment]
Install yEnc by copying the compiled yEnc for Windows files to your Python installation in:
C:\Python27\Lib\site-packages\

The files are here:
https://www.dropbox.com/s/wgtzs4vxmtniq5g/yEnc_0.4_for_Windows.zip?dl=1

You should see a reduction in CPU and memory usage!

**Comment by labrys** [comment]
CPU / memory usage isn't really a concern as I have more than enough of both available, its more the speed.  I kept intending to install yEnc but kept putting it off, I guess I should really get around to it, eh? :grinning:

**Comment by thezoggy** [comment]
heres yenc for windows python 2.7.x, 32bit and 64bit: http://zoggy.net/yenc-0.4_py2.7.rar
copy files from the relevant subfolder to `C:\Python27\Lib\site-packages`

**Comment by Safihre** [comment]
Oh great that you managed to compile the x64 ones, I couldn't get that working! Thought I also used 0.4 one, but guess not.
I already talked with @shypike and @inpheaux about updating the Run from source Windows-guide on the website, we should get that fixed and include your builds then!

**Comment by labrys** [comment]
@Safihre @shypike  Sorry i havent had a chance to email the failed urls yet.  I'll try to get to it in the morning.  Is there a faster way then individually editing each item to get a full list of URLs?

**Comment by shypike** [comment]
@labrys I'm sorry: no.
Except maybe getting them from the log files. Long shot, they might be gone, overwritten by subsequent logging.
Just a few failed ones are enough.

**Comment by labrys** [comment]
K. I'll email them in a few hours when I get a chance.
