### ISSUE TITLE
Indicator for priority

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#406]
Python: 2.7.10 x86
OS: Win 10 x64
SAB: 4e20004f7b6315c97e18958b900e2d2dbf096233

Currently (using the Glitter-night theme) there is no indication of what the priority is set to.  Could an indicator of some sort (change color of line-item, an icon, section separators, or something else) be added to give feedback when a change is made.  

The same could also be done for some of the other operations.  To avoid clutter possibly some of the information could go in a tooltip, although I think priority should be immediately visible.

**Comment by Safihre** [comment]
Did you try in the Interface settings to turn on the extra queue column? 
Glitter is meant to be more bare than Plush, as little clutter and buttons as possible.. But always open to suggestions to improve :)

**Comment by labrys** [comment]
Actually that was exactly what I was looking for, can't believe I hadn't seen it there before.  I was actually under the impression that Glitter was meant to replace Plush which is why I began using it to begin with :).

**Comment by Safihre** [comment]
Plush will stay for quite a while, this is just a 'modern'  alternative :)

**Comment by labrys** [comment]
Glad to hear that as while I really prefer the look of Glitter-night, Plush is way more responsive and has features such as `Apply selected` which provides the user interface much needed functionality.

**Comment by Safihre** [comment]
What do you mean by Plush being more responsive? Is Glitter slow for you?

**Comment by labrys** [comment]
Well for one thing, I keep getting Lost Connection to Server on Glitter (running on localhost, so its not a network issue).  

With really long queues I can display more items on Plush than Glitter before it starts to show issues.

With extremely long queues and with everything displayed Glitter just keeps spouting lost connections so I can't even access settings to reduce the number of items displayed.  Plush, on the other hand, can slow to a near standstill I can at least, with patience, click the dropdown to reduce the items.

**Comment by labrys** [comment]
In addition, when reordering the lists in Glitter, or changing priorities, etc.  Sometimes Glitters interface doesn';t update and I have to reload page.  Changing priority in plush, the list reorders near instantaneously.

**Comment by Safihre** [comment]
When you say long and really long, what numbers are we talking about? 
What to make a good test case for very high usage so I can optimize!

**Comment by labrys** [comment]
Well iirc, about 300+ for long and way more than that for really long... didnt really count but >20 pages at 50/page.  My solution was to clear the downloads, throttle back the additions, and restart sickrage.

**Comment by labrys** [comment]
For example, right now I have approx 300 (6 pages at 50/page) and I'm using Plush.  Switching to everything listed, and its there immediately, no lag.  Ill switch to Glitter and restart so I can compare.  And also per #404 Nearly all of those are unresolved NZBs since I cleared and restarted the queue earlier today.  I'll post the logs their shortly.

**Comment by labrys** [comment]
Took about 1.5 secs to switch from 50 per to everything in Glitter - Night.  So not terrible, Ill continue adding and let you know at what point it starts to choke.

**Comment by labrys** [comment]
With approx 1700 items in queue getting constant disconnects when limited to 50/page.  With everything, page won't even load.

**Comment by Safihre** [comment]
Yes, with that many items it takes sabnzbd backend more than the timeout to calculate the statistics.. 
@shypike why does the API call, even when limited to only return for example 30 items, take soo much longer when the whole queue gets larger? Is it for the statistics? Is there a way to speed up the process? 
I also noticed when I go to 300 jobs the API call for 20 items suddenly takes 200msec, where 25-20msec is for 5 jobs

**Comment by Safihre** [comment]
Just found a specific bit of code that slowed load and changes for Glitter with large queues > 100 down a lot when set to Everything. I fixed this now and put it in the pull-request! :) 
Still not super fast for even larger queues (500+), but it's a start!

**Comment by Safihre** [comment]
Also found that priority bug you mentioned! It was a small coding mistake, now the sorting is updated properly after any changes :)
