### ISSUE TITLE
Slow to start

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#407]
Python: 2.7.10 x86
OS: Win 10 x64
SAB: 4e20004f7b6315c97e18958b900e2d2dbf096233

With a long queue, starting SABnzb is extremely slow.  Current start is still in progress and has taken > 1hr and has still not completed.

**Comment by labrys** [comment]
Total start time 1 hr 8 minutes.  Queue size approx 1700.

**Comment by Safihre** [comment]
For your other question you enabled debug mode, making sabnzbd printing to the log every single thing it does.. Which is a lot with so many items! 
Put debug level back to Errors/warnings

**Comment by labrys** [comment]
@Safihre It takes just as long with debug level at info.

**Comment by Safihre** [comment]
And with debug level at Errors/Warnings?

**Comment by shypike** [comment]
@Safihre  That will not make a difference.
SABnzbd hasn't been tested with, nor been optimized for, such queue sizes.

**Comment by labrys** [comment]
Alright, well my queue sizes are regularly that large or larger, not that I restart SAB often so its not generally an issue.
