### ISSUE TITLE
sab 0.8.x -- SQL Command Failed, see log 

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#413]
sadly sab log doesnt show anything since it was set to warning/failed.. just set it to debug.. will let you know if it happens again

**Comment by MarshallCS** [comment]
I"m having SQL issues as well. Here is the log file
[sabnzbd.log.txt](https://github.com/sabnzbd/sabnzbd/files/92519/sabnzbd.log.txt)

**Comment by shypike** [comment]
Does restarting SABnzbd help?
Or the system.
Could be the result of a uncontrolled stop of SABnzbd (crash, system down etc.)

**Comment by MarshallCS** [comment]
Clean install on a new ubuntu 15.10 vm. I haven't had any real issues running sab (everything is working fine download wise) I just keep getting the errors. 

I've restarted again and I'll wait to see if / when it repeats. Any way to clear the log from the webgui to make it easier to decipher new issues?

**Comment by shypike** [comment]
You cannot remove the logs from the UI.
Stop SABnzbd, remove files, restart...

**Comment by thezoggy** [comment]
someone messaged me yesterday that this is still going on
`ERROR 21/04/2016 20:27 SQL Command Failed, see log in sabnzbd`

**Comment by shypike** [comment]
And what's in the log?
