### ISSUE TITLE
Why is sabnzbd.ini world readable?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#417]
Question: Why is sabnzbd.in 'world readable'?
```
$ ll .sabnzbd/sabnzbd.ini
-rw-rw-r-- 1 sander sander 15463 dec 21 18:18 .sabnzbd/sabnzbd.ini
```
Because home directories are readable for other users on the systems (at least on Ubuntu), this makes sabnzbd.ini readable for other users, including accounts and passwords.

I manually set sabnzbd.ini to ```-rw-------``` and that works for my setup; SAB is a running as daemon under my own account.

The relevant code seems to be in ```sabnzbd/config.py```:
```
        # No file found, create default INI file
        try:
            if not sabnzbd.WIN32:
                prev = os.umask(077)
            fp = open(path, "w")
            fp.write("__version__=%s\n[misc]\n[logging]\n" % CONFIG_VERSION)
            fp.close()
            if not sabnzbd.WIN32:
                os.umask(prev)
        except IOError:
            return False, 'Cannot create INI file %s' % path
```
I don't understand why the ```prev = os.umask(077)``` is used, as umask is not set afterwards (other than setting it to prev again).

I played with os.open() instead of open(), and this works:
```
import os
fh1 = os.open("myfile.txt", os.O_CREAT, 0600)
os.close(fh1)
```
Not saving umask seems to have NO impact on later file creation.

**Comment by shypike** [comment]
I'll check. It should be private of course.

**Comment by sanderjo** [comment]
A different result:

```sabnzbdplus -l2 -f .sabnzbd/sabnzbd$$.ini``` results in:

```
ll .sabnzbd/sabnzbd$$.ini*
-rw------- 1 sander sander 6014 dec 23 17:17 .sabnzbd/sabnzbd2781.ini
-rw-rw-r-- 1 sander sander 6014 dec 23 17:17 .sabnzbd/sabnzbd2781.ini.bak
```

So that .ini has correct settings (contrary to what I reported earlier, but that might have been on another Ubuntu system, so other settings?), but .ini.bak is world readable ... and contains passwords:

```
grep geheim .sabnzbd/sabnzbd$$.ini*
.sabnzbd/sabnzbd2781.ini:username = geheim
.sabnzbd/sabnzbd2781.ini:password = geheim
.sabnzbd/sabnzbd2781.ini.bak:username = geheim
.sabnzbd/sabnzbd2781.ini.bak:password = geheim
```

@shypike maybe you can wait and focus on other stuff, and let me figure this out a bit further?

**Comment by shypike** [comment]
@sanderjo Sure, sounds serious though.

**Comment by sanderjo** [comment]
@shypike Could you check on your OSX?

**Comment by Safihre** [comment]
On my Ubuntu VM I looked and it was just like you reported (installed using JCFP repro):
```
-rw-rw-r-- 1 osboxes osboxes 5607 Dec 24 08:44 sabnzbd.ini.bak
-rw------- 1 osboxes osboxes 5691 Dec 24 08:44 sabnzbd.ini
````
I deleted them so the Wizzard would run and it creates the same files with the same rights: world-readable sabnzbd.ini.bak

**Comment by shypike** [comment]
On OSX, the access to sabnzbd.ini is always forced to user-only access. However, the ini.bak file just follows the "umask" of the session. Obviously the bak file should also have restricted access.
I think it works the same for Linux systems.
Only on Windows SABnzbd doesn't bother, assuming the parent directory will have proper access settings which will be inherited.

**Comment by shypike** [comment]
This patch should solve the issue.

[umask.patch.txt](https://github.com/sabnzbd/sabnzbd/files/71641/umask.patch.txt)

**Comment by sanderjo** [comment]
Solved with https://github.com/sabnzbd/sabnzbd/commit/f28bcbf8017a226ca140042dde9fe029a1add2ca
