### ISSUE TITLE
Replace par2-tbb with alternatives

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#420]
the version of par2 that comes with sab is 0.4 from 2003... but has modifications.. 

```
C:\Program Files (x86)\sabnzbd_0.8.x\win\par2\x64>par2
Not enough command line arguments.
par2cmdline version 0.4, Copyright (C) 2003 Peter Brian Clements.
Modifications for concurrent processing, Unicode support, and hierarchial
directory support are Copyright (c) 2007-2015 Vincent Tan.
Concurrent processing utilises Intel Thread Building Blocks 4.3 Update 1,
Copyright (c) 2007-2014 Intel Corp.
Executing using the x64 (64-bit) instruction set.
```

have you seen the forked and continue development of par2cmdline?
0.6.14 @ https://github.com/Parchive/par2cmdline

specifically I hear that this allows a lot more stuff to get repaired and runs a bit faster than the included one:
`-N       : No data skipping (find badly mispositioned data blocks)`

also to note there is:
https://github.com/jkansanen/par2cmdline-mt (multi-threaded for the brave)

performance comparison mention:
https://github.com/Parchive/par2cmdline/issues/27#issuecomment-102522465

havent taken the time to compile my own version yet, but they provided 0.6.13, so grabbed that real quick:

```
P:\>par2.exe -V
par2cmdline version 0.6.13

P:\>par2.exe --help
Usage:
  par2 -h  : show this help
  par2 -V  : show version
  par2 -VV : show version and copyright

  par2 c(reate) [options] <par2 file> [files] : Create PAR2 files
  par2 v(erify) [options] <par2 file> [files] : Verify files using PAR2 file
  par2 r(epair) [options] <par2 file> [files] : Repair files using PAR2 files

You may also leave out the "c", "v", and "r" commands by using "par2create",
"par2verify", or "par2repair" instead.

Options:

  -a<file> : Set the main par2 archive name
  -b<n>    : Set the Block-Count
  -s<n>    : Set the Block-Size (Don't use both -b and -s)
  -r<n>    : Level of Redundancy (%%)
  -r<c><n> : Redundancy target size, <c>=g(iga),m(ega),k(ilo) bytes
  -c<n>    : Recovery block count (Don't use both -r and -c)
  -f<n>    : First Recovery-Block-Number
  -u       : Uniform recovery file sizes
  -l       : Limit size of recovery files (Don't use both -u and -l)
  -n<n>    : Number of recovery files (Don't use both -n and -l)
  -m<n>    : Memory (in MB) to use
  -v [-v]  : Be more verbose
  -q [-q]  : Be more quiet (-q -q gives silence)
  -p       : Purge backup files and par files on successful recovery or
             when no recovery is needed
  -R       : Recurse into subdirectories (only useful on create)
  -N       : No data skipping (find badly mispositioned data blocks)
  -S<n>    : Skip leaway (distance +/- from expected block position)
  --       : Treat all remaining CommandLine as filenames
```

wondering if its worth while to offer another par2 option..

**Comment by Safihre** [comment]
Similar discussion on the forums, or maybe you already saw that ;-) 
Multicore:
http://forums.sabnzbd.org/viewtopic.php?f=16&t=18793&start=15#p103735
N option:
http://forums.sabnzbd.org/viewtopic.php?f=2&t=19998

**Comment by thezoggy** [comment]
ty i had not seen it, i havent been to sab forums in ages :(

**Comment by Safihre** [comment]
It's really too bad that the multi-core version of the 0.6.12 is slower than par2-tbb.. 
The -N option seems very useful though, so maybe switching to new Parchive with optional MT might not be such a bad idea?
For version 0.8.1 I mean then..

**Comment by Safihre** [comment]
I just learned about PhPar2 and found [this thread](http://forums.sabnzbd.org/viewtopic.php?t=5029) about it.
For me it is SO much faster, I made a broken download (3500MB, 200MB 'missing'). The TBB version took 9:06min while PhPar2 took 5:20min.

Haven't tested new par2cmdline yet with this download, but maybe we should make a proper test?
A few large and small downloads and then test TBB, par2cmdline, PhPar2 on Windows and Linux..

**Comment by Safihre** [comment]
I wanted to share these results while I am testing the best (Windows) solution for SABnzbd's Par2.
Test system is a Core i5-4200 with 2 cores and a Samsung 850 Pro SSD on Windows 10. 
**This is the average of 5 runs**
Unfortunately I can't build the par2cmdline-mt myself, but from the results below the 'winner' seems clear.. I will repeat these test now with smaller and differently 'broken' data to see other effects.

MultiPar is only available on Windows, but these results really show that switching for Windows could save lots and lots of time.. :flushed:

```
Data size: 3.28GB
Blocks 4485/4541 (156 missing)
464 Repair Blocks

---------------

VERIFY: 0.4 TBB x64
15.1515566 Seconds

VERIFY: par2cmdline 0.6.13 x86
41.3655667 Seconds

VERIFY: phpar2 version 1.4 x86
36.135805 Seconds

VERIFY: MultiPar 1.2.9.0 x64
16.8486896 Seconds

---------------

REPAIR: 0.4 TBB x64
195.0399945 Seconds

REPAIR: par2cmdline 0.6.13 x86
376.7458003 Seconds

REPAIR: phpar2 version 1.4 x86
186.3957853 Seconds

VERIFY: MultiPar 1.2.9.0 x64
75.6073459 Seconds
```

**Comment by Safihre** [comment]
Now a test-set not made by deleting RAR-files, but the way it actually comes from SABnzbd with missing articles in almost every file. 
Again, average of 5 runs:
```
Data size: 1.51GB
Blocks 2078/2164 (76 missing throughout all files)
213 Repair Blocks

---------------

VERIFY: 0.4 TBB x64
7.6988215 Seconds

VERIFY: par2cmdline 0.6.13 x86
20.1532372 Seconds

VERIFY: phpar2 version 1.4 x86
17.7300754 Seconds

VERIFY: MultiPar 1.2.9.0 x64
8.6438294 Seconds

---------------

REPAIR: 0.4 TBB x64
54.0448524 Seconds

REPAIR: par2cmdline 0.6.13 x86
100.3952918 Seconds

REPAIR: phpar2 version 1.4 x86
56.1471169 Seconds

REPAIR: MultiPar 1.2.9.0 x64
23.9853376 Seconds
```

Seems phpar2 is not always faster as I stated 2 messages up, but MultiPar blows them all away..:grin:

**Comment by thezoggy** [comment]
Yes, multipar is awesome... Sadly not supported in sab..  

-----Original Message-----

**Comment by Safihre** [comment]
Indeed, I was mistaken about it being drop in. We would need to write a new interpreter for its output, but this shouldn't be such a problem, right?

**Comment by albino1** [comment]
I think shypike said he didn't want to try and support different par programs for different platforms.  Also, he said he didn't want to support par3 since it's closed source and only works with MultiPar, which means it only works in Windows, and he didn't want to encourage that behavior.

FWIW, purely anecdotally, I tried switching from QuickPar to MultiPar a couple of years ago, but I stumbled across some posts that would fail in MultiPar but work in QuickPar so I eventually gave up on it.  Since then when something fails in QuickPar but is only missing a few blocks I'll try MultiPar just for fun, but I've never seen it succeed.

With all of that said, if you want to create a MultiPar interpreter that isn't officially supported or sanctioned by SABnzbd, I'd be willing to give it a try.

**Comment by shypike** [comment]
We need to evaluate our options, but not for release 0.8.0.
Multipar is an option and if it's really that much faster, while being just as reliable, it's worth a shot,

**Comment by thezoggy** [comment]
you want to offer feature parity across platforms..  that deff is the goal. while other par apps may have some features.. ideally stable+speed is ultimately the most important. I see it the same thing as using x lib or y lib if its installed..

**Comment by Safihre** [comment]
Have to also mention this result that I found while implementing MultiPar, the verify part isn't always faster than TBB! Unfortunately this post did not have enough blocks to test the repair!
```
Data size: 865 MB

VERIFY: 0.4 TBB x64
9.2763101 Seconds
VERIFY: par2cmdline 0.6.13 x86
11.2973181 Seconds
VERIFY: phpar2 version 1.4 x86
18.7943604 Seconds
VERIFY: MultiPar 1.2.9.0 x64
15.8236561 Seconds
```

**Comment by Safihre** [comment]
Also found that some of the time MultiPar will find more available blocks than Par2-tbb.
So verify takes longer, but it finds more. I downloaded a whole season of a series and in the failed ones, often it found 1 or 2 blocks more. Not huge difference, but just wanted to mention it.

**Comment by shypike** [comment]
@Safihre Looks like multipar has the -N built-in and always on?

**Comment by Safihre** [comment]
TBB does not have the -N, and as you can see below it will find the same as MultiPar and par2cmdline with the -N option. In none of my tests the -N reduces speed so I have no clue why they made this an 'option'.

However, in my other damaged downloads, MultiPar finds more blocks **('Need 58 more blocks to repair')** than TBB **('Need 60 more blocks to repair')**, but par2cmdline finds even less **('Need 63 more blocks to repair')**.

```
Data: 10.4 GB
SABnzbd reports: 71 articles were malformed

---------------

VERIFY: 0.4 TBB x64
You need 70 more recovery blocks to be able to repair.
53 Seconds

VERIFY: par2cmdline 0.6.13 (1 core) x86
You need 73 more recovery blocks to be able to repair.
153 Seconds

VERIFY: par2cmdline 0.6.13 (1 core) x86  -N
You need 70 more recovery blocks to be able to repair.
153 Seconds

VERIFY: MultiPar 1.2.9.0 x64
Need 70 more slice(s) to repair 55 file(s)
69 Seconds
```

Now for the whole process of verify and repair, Multipar again takes the lead by a **two-fold** increase in speed!
```
Data: 10.4 GB
SABnzbd reports: 71 articles were malformed

---------------
TOTAL: 0.4 TBB x64
415 Seconds

TOTAL: MultiPar 1.2.9.0 x64
212 Seconds
```

**Comment by Safihre** [comment]
Also found somewhat of a bug: if par2 fails because there's not enough disk-space, SAB won't tell you this but just fail and start the SFV check. That will fail and it will show no status at all.

**Comment by shypike** [comment]
@Safihre That's weird, why would a full disk hamper the SFV check?
The first issue is serious. Any idea whether you can detect the "disk full" in par2's output?

**Comment by hurda** [comment]
> That's weird, why would a full disk hamper the SFV check?
It would fail due to broken and, due to par2 failing, unrepaired files.

**Comment by Safihre** [comment]
No I meant that the SFV check runs the way it should, but Par2 already detected it needed repair so running the SFV will also report that the download is broken.
Is there some way to tell from within ```par2_repair``` that it should skip the SFV check?

**Comment by shypike** [comment]
Maybe. Postpone to 0.8.1

**Comment by shypike** [comment]
@Safihre I'll move your remark to a new issue.

**Comment by domibarton** [comment]
As mentioned in #188 my updated [Docker image](https://hub.docker.com/r/sabnzbd/sabnzbd/) supports the `-t` and `-N` flags. Don't know if this helps :)

Cheers from Zurich as well ;)

**Comment by Safihre** [comment]
I tried it again (there is a `feature/multipar` branch, that works, in case anyone is interested)  with the new multipar, but it's just so much slower on validation. 
Not just initial validation, but also validation after a long repair. So total repair time is (99%) always shortest with par2tbb. 
It seems especially slow with detecting/scanning obfuscated files, something very relevant nowadays. 

Would be nice if there was a Linux port, since Windows devices are usually not underpowered as much. 
Closing this now, feel free to reopen if something changes.

**Comment by thezoggy** [comment]
i hit up par3cmdline devs recently about about adding par2 support into to leverage some of the speedups from par3cmdline code there was a bit of improvements from phpar2/multipar work in it. while that didnt happen, what did happen was a fork of par2cmdline now exists "par2cmdline-turbo" which has various speedups from that work backported (mainly phpar2). should be able to compile and be a dropin replacement, need to do some testing to see how well it all works out but may be a good step forward for our uses:

https://github.com/animetosho/par2cmdline-turbo

**Comment by sanderjo** [comment]
... that name ... @animetosho ... somehow that rings a bell ...  ;-)

Compiling took quite some time, but it's there:

```
~/git/par2cmdline-turbo$ ./par2 --version
par2cmdline-turbo version 0.9.0

```
I can try it on my download machine if it works (I guess so), but I wonder if there are benchmarks. Repairing can take a lot of time, so if this is faster, that would be nice.

**Comment by thezoggy** [comment]
lsio now has docker-mod for par2cmdline-turbo to make it easier for others to try out with sabnzbd docker:
https://github.com/linuxserver/docker-mods/tree/sabnzbd-par2cmdline-turbo
