### ISSUE TITLE
0.8.0 Beta 4 shows a lock symbol for *unwanted* downloads.

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#421]
@Safihre 

0.8.0 Beta 4 shows a lock symbol for *unwanted* downloads. And *encrypted* downloads show no lock.

I would expect it the other way round.

Is this as designed?

![sabnzbd unwanted with a lock](https://cloud.githubusercontent.com/assets/1273502/12224384/2d49431c-b7ef-11e5-9c80-d9ebcd4a369d.png)

**Comment by Safihre** [comment]
What's behind the lock is supposed to be the password for passworded-jobs.
But because the 'UNWANTED \ ' is in front of it, it's not handled properly..

Fixed in #423
