### ISSUE TITLE
URLGrabber failing on certain files sent from Mylar

### ISSUE THREAD

**Issue by bguidotti** [sabnzbd/sabnzbd#422]
I am experiencing an issue where, seemingly upon a large stack of comics downloads getting queued in SAB, I have multiple URL Grabber errors. I checked with evilhero, the developer of Mylar.  He wanted me to inquire here, as the behavior seems different in the newest beta(s).

I am running DEV branch of Mylar and 0.80beta4 on Windows of SAB.

The errors look similar to the below:

ERROR 01/10/2016 23:52 URLGRABBER CRASHED
Traceback (most recent call last):
File "sabnzbd\urlgrabber.pyo", line 204, in run
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\Users\Bruce\AppData\Local\sabnzbd\admin\future\api?apikey=REDACTED&cmd=downloadNZB&nzbname=Invincible.126.2015.Digital.Zone-Empire.nzb'

Any idea what could be causing this?

Thanks in advance for your insight.

**Comment by Safihre** [comment]
Do you use an indexer? It seems the URL's coming from the indexer are not properly formed or SABnzbd is handeling them wrongly.
Is there some way to see which URL Mylar has send to SAB?

**Comment by bguidotti** [comment]
Yes, I use NZBGeek.

I just tried another:

Trying to fetch NZB from http://192.168.1.2:8090/api?apikey=REDACTED&cmd=downloadNZB&nzbname=Gotham.by.Midnight.012.2016.Digital-Empire

Then SAB shows:
ERROR 01/12/2016 08:52 URLGRABBER CRASHED
Traceback (most recent call last):
  File "sabnzbd\urlgrabber.pyo", line 204, in run
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\Users\\Bruce\\AppData\\Local\\sabnzbd\\admin\\future\\api?apikey=REDACTED&cmd=downloadNZB&nzbname=Gotham.by.Midnight.012.2016.Digital-Empire.nzb'

**Comment by thezoggy** [comment]
sounds like a permission issues...  move your sab d/l folder outside of the protected users folder or fix your permissions.

**Comment by bguidotti** [comment]
This is on a Windows 10 box.
I checked the security permissions, and they seem to be correct.
I will look into trying to move the spot where SAB throws temp nzbs.
Why would this only happen on every few files, and not in a previous version of SAB, though?

**Comment by shypike** [comment]
It seems to be that Mylar sends odd headers and the new CherryPy web framework doesn't handle this well. I guess SABnzbd must clean up the alleged file name coming from CherryPy.

**Comment by evilhero** [comment]
@shypike: do you know what headers mylar is sending that's considered odd? 

If mylar is sending invalid headers I'd like to patch things so it doesn't - I'm guessing something is grabbed from the headers, as the only file that mylar requests is the one in thr addurl reference.

**Comment by shypike** [comment]
I wouldn't be surprised if it turn out to be a bug in the CherryPy framework.
The current patch should do, but if I have some time left, I'll look further into it.
