### ISSUE TITLE
SABnzbd performance improvement plans

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#427]
# SABnzbd performance improvements

Besides bugfixes, for the next release *(0.8.1?)* one aspect where SABnzbd could use some improvements, is performance. 

So where to start.. 
I thought I make a small overview/plan, with what knowledge I have gathered so far, but could use some help :blush:

----------
- **Python code**
  - [ ] Identify CPU (memory) intensive parts
	  - [ ] yEnc (see below)
	  - [ ] Identifying next article to download is not efficient
	  - [ ] Get rid of legacy stuff for Python < 2.6
	  - [ ] Disk I/O improvements
	  - [ ] Others?
  - [ ] Restructure or move to C-code
  - [ ] Evaluate performance improvements of using (for example) PyPy 

----------
-  **C-code**
	- [ ] Do complete yEnc in C (including the writing the file), not just line by line
	- [ ] Other parts that should be in C?

----------
- **External programs**
	- [ ] Update
	- [ ] Par2
		- [ ] Include MultiPar for Windows (#420)
		- [ ] Multicore or best solution for other platforms?

----------
Discussing with @shypike a possible bottleneck would be the yEnc *(now done 'line by line')* and the identification which article to download next *(now requested for every article through objects NZB -> File -> Article)*.

How do we identify the 'slow' parts? What can we use to profile?
@thezoggy, do you maybe know any tools or browsing through the code, have seen things that could be important performance bottlenecks?

I tried PyPy (which claims dramatic improvements) but couldn't even get SABnzbd to start because of import-errors on the Win32Api..

**Comment by thezoggy** [comment]
yenc encoding/decoding is already in C, just have to install the lib.. 
now for optimizing sab (python) in general.. there are numerous things to do.. a lot of sab's code is from pre python 2.5 days.. thus json/ordereddict/ssl/etc were not around. There is a lot of legacy cruft in sab that could really benefit from some code rewrites/look at using better/efficient data types..etc. Also there are a few libs out there that sab should use instead of trying to re-invent the wheel.. drop urllib/urlib2/httplib for Requests. which you can benefit from connection pooling/reuse/etc.

https://wiki.python.org/moin/PythonSpeed/PerformanceTips

anyways, the big slow downs with sab (assuming you have yenc/ssl/etc installed) is when you have a large queue..  badly set settings (extract and download on same slow disk? / too many connections / etc) or sab's external apps (rar/par). 

the major bottleneck with sab is when disk i/o is involved.. as reading/writing to disk is obviously expensive compared to memory. I'm not sure how bad sab's logging contributes (debug can get very verbose) but that may be another thing to look at... queue logging to write in chunks or something (write one 500 entries or flush every 30 secs vs each article).

**Comment by thezoggy** [comment]
about  multicore par on windows.. the included par2 with sab does support it (has tbb/unicode/threaded support)..  can see the `-t` options:

```
C:\Program Files (x86)\sabnzbd_0.8.x\win\par2\x64>par2
Not enough command line arguments.
par2cmdline version 0.4, Copyright (C) 2003 Peter Brian Clements.
Modifications for concurrent processing, Unicode support, and hierarchial
directory support are Copyright (c) 2007-2015 Vincent Tan.
Concurrent processing utilises Intel Thread Building Blocks 4.3 Update 1,
Copyright (c) 2007-2014 Intel Corp.
Executing using the x64 (64-bit) instruction set.

par2cmdline comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it and/or modify
it under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version. See COPYING for details.


Usage:

  par2 c(reate) [options] <par2 file> [files] : Create PAR2 files
  par2 v(erify) [options] <par2 file> [files] : Verify files using PAR2 file
  par2 r(epair) [options] <par2 file> [files] : Repair files using PAR2 files

You may also leave out the "c", "v", and "r" commands by using "parcreate",
"par2verify", or "par2repair" instead.

Options:

  -b<n>  : Set the Block-Count
  -s<n>  : Set the Block-Size (Don't use both -b and -s)
  -r<n>  : Level of Redundancy (%)
  -c<n>  : Recovery block count (Don't use both -r and -c)
  -f<n>  : First Recovery-Block-Number
  -u     : Uniform recovery file sizes
  -l     : Limit size of recovery files (Don't use both -u and -l)
  -n<n>  : Number of recovery files (Don't use both -n and -l)
  -m<n>  : Memory (in MB) to use
  -v [-v]: Be more verbose
  -q [-q]: Be more quiet (-q -q gives silence)
  -z<n>  : Number of "Opening: <file>" messages when creating parity files (zero for no limit)
  -t<+<n>|0<n>|-<n>>: Threaded processing. The options are:
     -t+ to checksum and create/repair concurrently - uses all available logical CPUs - good for hard disk files - [default]
     -t0 to checksum serially but create/repair concurrently with all available logical CPUs - better for slow media such as CDs/DVDs
     -t- to checksum/create/repair serially - uses a single logical CPU - good for testing this program
     -t+n to checksum and create/repair concurrently - uses n logical CPUs (up to all of the available logical CPUs)
     -t0n to checksum serially but create/repair concurrently - uses n logical CPUs if n > 0, or all available CPUs minus n if n < 0
     -t-n to checksum and create/repair concurrently - uses available logical CPUs minus n, eg, -t-1 on a 6 CPU system will use up to 5 CPUs
  -p<N|L|I>: Processing priority. The options are:
     -pN to process at normal priority [default]
     -pL to process at low priority
     -pI to process at idle priority
  -d<dir>: root directory for paths to be put in par2 files OR root directory for files to repair from par2 files
  -0     : create dummy par2 files - for getting actual final par2 files sizes without doing any computing
  --     : Treat all remaining CommandLine as filenames

If you wish to create par2 files for a single source file, you may leave
out the name of the par2 file from the command line.
```

now to use it you just have to configure it.. by defualt it is enabled:
config > switches > `Enable MultiCore Par2`

to configure:
http://wiki.sabnzbd.org/configure-switches-0-8#multi-core

**Comment by thezoggy** [comment]
right now on sab startup it detects some vaulable info.. really should store that on the config base page..

example snippet (also note we should log what version of yenc/par2/unrar/etc it detects as well):
```
2016-01-14 17:19:19,213::INFO::[SABnzbd:483] _yenc module... found!
2016-01-14 17:19:19,213::INFO::[SABnzbd:491] par2 binary... found (C:\Program Files (x86)\sabnzbd_0.8.x\win\par2\x64\par2.exe)
2016-01-14 17:19:19,213::INFO::[SABnzbd:496] par2-classic binary... found (C:\Program Files (x86)\sabnzbd_0.8.x\win\par2\par2-classic.exe)
2016-01-14 17:19:19,230::INFO::[SABnzbd:499] UNRAR binary... found (C:\Program Files (x86)\sabnzbd_0.8.x\win\unrar\x64\UnRAR.exe)
2016-01-14 17:19:19,230::INFO::[SABnzbd:505] unzip binary... found (C:\Program Files (x86)\sabnzbd_0.8.x\win\unzip\unzip.exe)
2016-01-14 17:19:19,230::INFO::[SABnzbd:511] 7za binary... found (C:\Program Files (x86)\sabnzbd_0.8.x\win\7zip\7za.exe)
2016-01-14 17:19:19,230::INFO::[SABnzbd:527] pyOpenSSL... found (True)
2016-01-14 17:19:19,230::INFO::[SABnzbd:1361] SSL version OpenSSL 1.0.2d 9 Jul 2015
2016-01-14 17:19:19,230::INFO::[SABnzbd:1362] SSL potentially supported protocols ['SSLv2', 'SSLv23', 'SSLv3', 'TLSv1', 'TLSv1_1', 'TLSv1_2']
2016-01-14 17:19:19,244::INFO::[SABnzbd:1363] SSL actually supported protocols ['t12', 't11', 't1', 'v23', 'v3', 'v2']
```

**Comment by thezoggy** [comment]
@shypike prob should upgrade our 7zip
http://www.7-zip.org/history.txt

```
C:\Program Files (x86)\sabnzbd_0.8.x\win\7zip>7za.exe -h
7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
```

**Comment by Safihre** [comment]
@thezoggy 
For the yEnc I mean specifically that everything should be moved to C, so after all data is received: the re-order, decode and write to file (suggestion from @shypike). So *extend* the current functions of the C-code.

For the Par2 I meant to implement MultiPar for Windows (updated the text now) and test it. The benchmarks show it as a major improvement over par2-tbb (benchmarks in #420).
Already working on the interpreter for that, so far seems to be going pretty well. But of course requires much testing!
And have a look at what to do with the Par2 on other platforms, now with this -N parameter of the new par2cmdline..

Interesting about the legacy stuff, is there any in there that is actually for the download-process? Or just the requests such as fetching an NZB? 
The NNTP connection seems a plain socket-connection (to me), what can be improved there?

**Comment by thezoggy** [comment]
Why not then switch to nzbget

-----Original Message-----

**Comment by thezoggy** [comment]
Why not then switch to c/c++ like nzbget is in

-----Original Message-----

**Comment by shypike** [comment]
@thezoggy Concerning 7zip: this is the first non-Beta since 9.20 (5 years ago). I'll update it.
Biggest issue being: finding an NZB that actually uses 7Z files, so that I can test.

**Comment by thezoggy** [comment]
@shypike maybe one of these: http://binsearch.info/?max=250&g=alt.binaries.multimedia&a=okamelem%40yahoo.com+%28Oka%29
