### ISSUE TITLE
sab 0.8.x -- cherrypy upgrade

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#428]
just fyi 4.0 offically came out 12/20/2015... looking at the dev changelog we see that 5.x is just a placeholder with some notable changes.. but more importantly is the 4.x where they dropped python 2.5 and windows installers... not sure if we check/catch for versions of cherrpy off the top of my head but just to note here.

```
-----
5.0.0
-----

* Removed deprecated support for ``ssl_certificate`` and
  ``ssl_private_key`` attributes and implicit construction
  of SSL adapter on Python 2 WSGI servers.
* Default SSL Adapter on Python 2 is the builtin SSL adapter,
  matching Python 3 behavior.

-----
4.0.0
-----

* Drop support for Python 2.5 and earlier.
* No longer build Windows installers by default.

-----
3.8.2
-----

* Pull Request #116: Correct InternalServerError when null bytes in
  static file path. Now responds with 404 instead.

-----
3.8.0
-----

* Pull Request #96: Pass ``exc_info`` to logger as keyword rather than
  formatting the error and injecting into the message.

```

**Comment by thezoggy** [comment]
looking through the commits, i see they have the 3.x trunk set to `3.8.3` so looks like 3.8.2 is going to be the last planned version there..  so not sure if you want to mess with updating to that from our 3.8.0...

changes from 3.8.0->3.8.2
https://bitbucket.org/cherrypy/cherrypy/branches/compare/3.8.2%0D3.8.0

looking through changes, looks like there was a python 2.6 bug that they fix..  most of it is just tests/docs updates.. so looks pretty minor to update (excluding your mods)

**Comment by shypike** [comment]
Addressed in PR https://github.com/sabnzbd/sabnzbd/pull/515
