### ISSUE TITLE
sab 0.8.x -- upgrade notice

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#429]
finally got around to upgrading sab 0.7.20 -> 0.8.0b5 (using binary) on my older win7 box.. 
had nothing in the queue, shut it down.. did the upgrade.. now I see this on startup:
![sab](http://zoggy.net/sab_0.8_upgrade.png)

**Comment by thezoggy** [comment]
i use smpl as my default theme.. no banner/info about the new skin.. except warning thats logged:
` 2016-01-17 10:56:10,905 WARNING: Try our new skin Glitter! Fresh new design that is optimized for desktop and mobile devices. Go to Config -> General to change your skin.`

**Comment by thezoggy** [comment]
go to queue / status.. nothing in the queue.. so not sure why sab is throwing that detect message..

glad to see that python 2.7.11 is used..
`2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]`

**Comment by thezoggy** [comment]
going to my config > general.. i see that glitter is already set as my secondary web interface.. however trying to navigate to it.. does not work. i assume that sab just did this on this load..thus i need to restart.. thus we may want to show a banner/something on the config page if a restart is needed.... that way in this instance people would know why its not working

**Comment by Safihre** [comment]
We decided not to do a banner for the new skin so not too push it to much, just the warning should suffice. 

There is already the warning that you need to restart in the config when you save and it's nesseacry. 
I think you never set up a secondary skin, so it automatically selects Glitter as the top of the select, even though the config value isn't set at the point. I noticed this behavior on another install as well.

**Comment by shypike** [comment]
The "old-queue" warning will now only come when the old queue is not empty: 1cb9bbe7cc554c33f53dc4cf7dc7f0f5adbe32eb

**Comment by thezoggy** [comment]
ty!
