### ISSUE TITLE
sab 0.8.x -- upgrade broke completed folder

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#431]
noticed the issue after upgrading from 0.7.20 to 0.8.0b5 (win binaries).

on glitter > Status and interface options
trying the speed test, if i click the 'repeat test' icon for either download or completed it only reports back a speed for downloaded..  looking at logs (debug) all I see is:
```
2016-01-17 11:34:17,696::DEBUG::[interface:2663] Dashboard: Refresh button pressed
2016-01-17 11:34:18,210::DEBUG::[interface:2672] Dashboard: Refresh had a problem
```

which needs work to help out wtf is the problem...
both on the modal show
` (C:\Users\zoggy\downloads\…) ` as the path

which doesnt help much either...

going to config > folders.. both have the default entered..
Temporary Download Folder: `downloads\incomplete`
and
Completed Download Folder: `downloads\complete`

thats when i noticed that the base folder has changed now in 0.8...
from: `C:\Users\zoggy\Documents`
to: `C:\Users\zoggy`

when I renamed the folder `C:\Users\zoggy\Documents\downloads\complete` to complete-old the issue was fixed... as the next time I tried it it ended up creating the folder:

`2016-01-17 11:43:24,713::INFO::[misc:434] complete_dir directory: C:\Users\zoggy\downloads\complete does not exist, try to create it`

what i can guess that sab for some reason it still thought internally to use the old folder but then try the new location..thus no completed folder at new location but was one at old location. thus craps itself.

**Comment by shypike** [comment]
Did you do (and were told to do) a queue repair?
The default folders for Windows have indeed moved, they were wrong in all previous releases.
I'll look again at the upgrade process.

**Comment by thezoggy** [comment]
i have now just in case.. is sab supposed to load up in a paused state after doing so?

**Comment by shypike** [comment]
Normally it shouldn't, unless your default category has priority "Paused".

**Comment by thezoggy** [comment]
hmm nope, 'Normal'. I've seen this behavior on other setups as well (linux) so thought maybe it was by design... 

```
2016-01-17 19:52:22,744::DEBUG::[misc:604] Checked for a new release, cur= 80045, latest= 72099 (on https://sourceforge.net/projects/sabnzbdplus/files/sabnzbdplus/0.7.20/)
2016-01-17 19:52:22,746::INFO::[SABnzbd:1581] Starting SABnzbd.exe-0.8.0Beta5
2016-01-17 19:52:22,746::DEBUG::[__init__:359] Starting postprocessor
2016-01-17 19:52:22,746::DEBUG::[__init__:362] Starting assembler
2016-01-17 19:52:22,746::DEBUG::[__init__:365] Starting downloader
2016-01-17 19:52:22,746::DEBUG::[scheduler:202] Starting scheduler
2016-01-17 19:52:22,747::DEBUG::[__init__:370] Starting dirscanner
2016-01-17 19:52:22,747::INFO::[dirscanner:302] Dirscanner starting up
2016-01-17 19:52:22,747::DEBUG::[__init__:375] Starting urlgrabber
2016-01-17 19:52:22,749::INFO::[urlgrabber:69] URLGrabber starting up
2016-01-17 19:53:02,894::INFO::[downloader:241] Resuming
2016-01-17 19:53:02,895::DEBUG::[__init__:547] PAUSED_ALL inactive
2016-01-17 19:53:02,895::INFO::[downloader:241] Resuming
2016-01-17 19:53:02,895::DEBUG::[__init__:547] PAUSED_ALL inactive
```

**Comment by shypike** [comment]
I tried your upgrade scenario with the latest commit and I cannot reproduce your problem.
I admit that the moving of the default locations is inconvenient as there is no easy way to "repair" the old queue.
The folders had to move, having them in "Documents" is so wrong.

What is a good solution?
Detect <Home>\Documents\Downloads\incomplete and keep using that? (By quietly changing the "download_folder" setting in the INI file).
Moving folders is just too hard on Windows, too many things can interfere.

**Comment by thezoggy** [comment]
just sent you my sab admin folder from a time when i was using `0.7.20` so you can try and upgrade it like i did.. 

yeah deff dont want to **move** folders -- especially without telling the user / prompting if they want to do so.. as can run into all sorts of permissions/file space issues..  for new installs just set the proper location, for old installs just offer way to migrate?

**Comment by shypike** [comment]
I fixed it up, I hope: 1cb9bbe7cc554c33f53dc4cf7dc7f0f5adbe32eb
Now for someone using the default profile-based location, the relative path for "download_folder" will be changed to "Documents\old\path". Only for Windows and only if the queue is not empty.

**Comment by shypike** [comment]
I managed to fix the problem with the disk speed meter on Windows.
Read the comments of commit c6687163f09c9a3c926bfd7ded27cf0d0f501169 and try to explain this weirdness.

**Comment by thezoggy** [comment]
http://stackoverflow.com/questions/13215716/ioerror-errno-13-permission-denied-when-trying-to-open-hidden-file-in-w-mod ?

**Comment by shypike** [comment]
It's not a hidden file, but I can try anyway. Thanks.

**Comment by thezoggy** [comment]
updated sab, ran the speed test.. im getting half the speeds I got before... 170mb -> 65mb now...

**Comment by shypike** [comment]
The "w+" doesn't solve the permissions problem.
I'll have look at actual speed figures tomorrow, stared too long at the other problem :(

**Comment by shypike** [comment]
I found it. I have the os.system() call within the loop. Duh!
Tomorrow.

**Comment by shypike** [comment]
Moved the fix outside of the loop. The test file cannot be removed until after the test, otherwise the problem just comes back. Commit 917b18ab093e031e266d7d1ddbd84f36de58826b

**Comment by thezoggy** [comment]
with latest patch I see:
```
Download folder speed
485.4 MB/s (C:\Users\zoggy\downloads\…)
Complete folder speed
504.9 MB/s (C:\Users\zoggy\downloads\…)
```

grabbed `AS SSD` to test, 
http://www.majorgeeks.com/files/details/as_ssd_benchmark.html

Running 1gb test on my “intel ssd 530 series (240gb)”, the Seq results are: 512 MB/s read and 256MB/s write. Thus the latest patch is much closer to what the hardware can actually do.. but does bring up the point that sab looks to only check the read speed...  we should prob show read and write? or at least note its read only...  now we also could run a few test and avg the results to get a true readout.. and probably should just move all of this to a diag section in the config or something..

**Comment by Safihre** [comment]
Are we not trying to make this more than it is, spending so much time on it? 
This was never intended by @sanderjo to be a proper speedtest tool, just an indicator for diagnostics when people report problems..

**Comment by shypike** [comment]
Jon

True, I just wanted to fix the issues you reported. I think my latest patch is good enough.
I'm not going to spend more time on it, I'd sooner drop it.

Kind regards 
Con

**Comment by sanderjo** [comment]
> I think my latest patch is good enough.
I agree

> I'd sooner drop it.
Please not; I introduced it because of users using a NAS as SAB drive, and then complaining SAB is slow. This measurement will make clear the cause: slow disk access. A NAS drive can show a speed of 1 MB/s. 
This feature is not a testing tool to benchmark SSD drives: 100 or 200 or 400 MB/s will suffice and will not have a speed impact on SAB.
I just ran it on my 219 euro laptop with an eMMC: 57.0 MB/s. Enough information for me.

**Comment by thezoggy** [comment]
whats the point of having a speedtest if its not reliable? 
all were trying to do is get it to the point where it doesnt do more harm than good.. i just noted that to make proper use of it in the future it prob needs to go to a diag page where its flushed out better.

**Comment by thezoggy** [comment]
@sanderjo yes i agree its a valuable tool, my only beef with it was that i noticed my speeds dropped by half after a code change..  and if im running a 4ghz i7 with ssd.. i can only imagine what crappy results someone on a nas would get.. thus they may think there is something wrong with the hd.. not realizing its just the code.

**Comment by thezoggy** [comment]
anyways people can always install glances if they want stats..
https://nicolargo.github.io/glances/

i tried out that monkeytest disk io python app, its awful.
