### ISSUE TITLE
Glitter: "Optionally specify a filename" should read "... download name"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#432]
Hi,

Glitter says in the Download menu:  "Optionally specify a filename" 

I think it should say "Optionally specify a download name" as it does nothing with a filename, only with the *download* name. 

And yes, if no download name is specified, the NZB filename will be used, but it is not the other way round.

**Comment by Safihre** [comment]
I know, but this is the way it's in the translations since Plush (see add NZB there)  ;) 
We can change it for English, but no idea what it says in the other languages!

**Comment by Safihre** [comment]
I changed it for English to:
*Optionally specify a name*
But in for example Nederlands (and other langauges) it will still say:
*Geef eventueel een bestandsnaam op*

**Comment by sanderjo** [comment]
So ... it now 'just' takes time for the translators to translate? Until that time the message is the same for non-English?

**Comment by Safihre** [comment]
I put it in the English over-writes file, if I change the text in the translations template it would show in all languages the English text there. So only the English is corrected.
With 0.8.0 so close it probably won't be translated in time, so better to keep a semi-false text there in other languages then a sudden line of English.
All translations for the new 0.8.0 texts have been finished before Christmas :)
