### ISSUE TITLE
Skip SFV check if par2 check already failed

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#434]
Doing an SFV after par2-verify/repair fails serves no purpose.
SFV should be limited to cases where there are no (usable) par2 files.

**Comment by Safihre** [comment]
I only saw this happen on the Disk-full error, where a more common scenario would be that it will go back in the queue to find more blocks.
When it finished downloading them and (somehow?) it already knows they are not enough it will stop there without launching par2. Only saying in the log:
> 2016-01-19 15:18:04,867::INFO::[postproc:280] Starting PostProcessing on Friends.S09E05.720p.BluRay.x264-PSYCHD => Repair:True, Unpack:True, Delete:True, Script:dd.py, Cat:*

So I guess only on rare occasions it will actually do the SFV after the par2.

**Comment by shypike** [comment]
There are also smaller uploads without par2 files and just an SFV. Like a few mp3.

**Comment by thezoggy** [comment]
yes, cant assume every release has par2 or sfv. it may have neither or both or just one.

**Comment by war59312** [comment]
So no situation were par2 fails, but sfv check succeeds?

I can think of one. Were the release has bad par2 files themselves. And sfv is correct.

**Comment by Safihre** [comment]
I agree with @war59312, I actually found a download in which this happens. All the par2 were botched somehow (so couldn't do QuickCheck) but the sfv was fine and all the files were also fine.

Think we can close this one.

**Comment by shypike** [comment]
@Safihre But did SABnzbd handle this correctly?

**Comment by Safihre** [comment]
It did!
