### ISSUE TITLE
Clean Notification class

### ISSUE THREAD

**Issue by domibarton** [sabnzbd/sabnzbd#437]
I think we could probably clean up a lot of the code because there's repetition of code everywhere. I tried to clean it up, but that requires more than just a day ^^ Would be great to get a proper abstract `Notification` class to inherit all concrete notification implementations from. 

The "management" of the priorities and additional custom parameters per notification type will become much easier. Something like that:

```python
class ProwlNotification(Prowl):
    ''' Notification class for Prowl. '''
    help_text = 'Requires a Prowl account'
    parameters = (
        NotificationParameter('apikey', 'API key for prowl', 'Personal API key for Prowl', required=True),
    )

    def notify(self, parameters):
        ''' Sends Prowl notification. '''

        # do some business logic here
```

The Notification class can handle then all the use cases, for example verifications and sending test messages (i.e. getting parameters from GET/POST instead from `sabnzbd.cfg`).

In this case someone could easily add new Notification types by just creating a new `Notification`-based class. Of course the HTML on the config front-end has to be rendered dynamically, but that's not very hard.

What do you think?

**Comment by shypike** [comment]
You're right, but that's something for the longer term.
There is such a long list of bugs & features, that (for me) this has a low priority.
Although, if you like to volunteer for this as well, go ahead.

**Comment by thezoggy** [comment]
right now the notifiers are single serving.. either you have it or not. if you wanted to do multiple of the same notifier (different settings) and put them to different categories.. you cant. the paradigm of one per cat is fine.. but not one per instance (current way). thus if you are going to spend time on this, we should do it correctly this time around.
