### ISSUE TITLE
Freeing memory after job

### ISSUE THREAD

**Issue by Hubfront** [sabnzbd/sabnzbd#439]
When the python process allocates memory, it's not freed after the job is completed. In my case, after the job, python reserved 137MB memory, after restarting sab python allocated 16 MB RAM.
5 jobs later, python did allocate over 300MB of RAM while downloading the last job.  "Cache used" says 97MB. 

This may be not a problem on PCs, but it may be a problem with NAS with low RAM.
I know, this may be hard to solve, because it may be a problem within phyton. I'm using diskstation 5.2 on x86 dsplay 214. I just wanted to mention it, so that that this bug is not forgotten and maybe someone accidentially may find a solution for it. Maybe it's a just bug that only occurs with python version from SynCommunity? I did not test memory allocation behaviour on another platform. I verified this problem with sab 8.x beta 5, but had the same issue with version 7.x a over a year or so ago.

**Comment by shypike** [comment]
It is indeed de behaviour of Python. We see it behave wildly different between versions and platforms.
On some systems Python refuses to return free memory to the operating system.

We will work in the future on taming memory usage, because it's now a bit too liberal with it.
Setting the cache value to something decent will tame memory usage, but not under all circumstances.

**Comment by Safihre** [comment]
Has been on the backlog for a while already: #177

**Comment by shypike** [comment]
@Safihre the specific behaviour described by Hubfront isn't on the roadmap, because it's very likely a Python issue.

**Comment by thezoggy** [comment]
to note that i looked for memory leaks back on 0.8.x in sept 2015 and never found anything of concerns. but granted i was only testing windows w/ vanilla python x64 2.7.10: 
https://github.com/sabnzbd/sabnzbd/issues/329

memory usage with 'sab' is a bit complex as there are many different states/processes that a nzb goes through. from fetch -> downloading -> repairing -> extracting -> process, so theres a lot of variables that come into play on the user env/setup and how they are using sab. also not every nzb is the same..

**Comment by Hubfront** [comment]
It seems to be a problem only on certain platforms and apparently is related to python, i did not manage to test it on windows though, because it seems rather complicated to setup the source version of sabnzbd with python for windows. Problem is, that i dont know, how to install module cheetah. iI tried that with the setup install cmd, but then an error msg occurs saying python could not find "byteyears". So i gave up. ;-) Looks like installing modules for python in windows isnt as easy as with perl.

**Comment by Safihre** [comment]
It is easy, type in the command window:
```pip install cheetah```

**Comment by shypike** [comment]
@Hubfront 
Installing Cheetah is either "easy_install cheetah" or "pip install cheetah". You'll get a warning about a missing "namespace" binary, but that won't stop SABnzbd from working.

**Comment by Hubfront** [comment]
In the python shell?

>>> easy_install cheetah
SyntaxError: invalid syntax
>>> pip install cheetah
SyntaxError: invalid syntax
>>>

**Comment by shypike** [comment]
from a command prompt (cmd.exe).

**Comment by Hubfront** [comment]
got it.

C:\Users\Matthias\Downloads\SABnzbd-0.8.0Beta5-src\SABnzbd-0.8.0Beta5>sabnzbd.py
Traceback (most recent call last):
  File "C:\Users\Matthias\Downloads\SABnzbd-0.8.0Beta5-src\SABnzbd-0.8.0Beta5\SABnzbd.py", line 85, in <module>
    import sabnzbd
  File "C:\Users\Matthias\Downloads\SABnzbd-0.8.0Beta5-src\SABnzbd-0.8.0Beta5\sabnzbd\__init__.py", line 98, in <module>
    import sabnzbd.api
  File "C:\Users\Matthias\Downloads\SABnzbd-0.8.0Beta5-src\SABnzbd-0.8.0Beta5\sabnzbd\api.py", line 54, in <module>
    from sabnzbd.utils.pathbrowser import folders_at_path
  File "C:\Users\Matthias\Downloads\SABnzbd-0.8.0Beta5-src\SABnzbd-0.8.0Beta5\sabnzbd\utils\pathbrowser.py", line 23, in <module>
    import win32api, win32con, win32file
ImportError: No module named win32api

**Comment by shypike** [comment]
Right, you're not using ActiveState Python.
You need another module: "pip install pypiwin32".
BTW: this is documented in our INSTALL.txt file.

**Comment by Hubfront** [comment]
Where do i have to put unrar and par2? I copied it even in the systems32 dir, but sabznbd could not find it on startup.

**Comment by shypike** [comment]
Start at the point where SABnzbd.py resides:
win\7zip                      
win\par2                      
win\unrar                     
win\unzip                     
win\7zip\7za.exe              
win\7zip\license.txt          
win\par2\x64                  
win\par2\COPYING              
win\par2\par2.exe             
win\par2\par2-classic.exe     
win\par2\README_FIRST.txt     
win\par2\x64\COPYING          
win\par2\x64\par2.exe         
win\par2\x64\README_FIRST.txt 
win\unrar\x64                 
win\unrar\license.txt         
win\unrar\UnRAR.exe           
win\unrar\x64\license.txt     
win\unrar\x64\UnRAR.exe       
win\unzip\LICENSE             
win\unzip\README              
win\unzip\README.NT           
win\unzip\unzip.exe           
win\unzip\WHERE

**Comment by Hubfront** [comment]
BTW: these special paths for unrar & Co. are NOT documented in your INSTALL.txt file. So you should update it accordingly. If someone doesnt know the exaxt path locations, there is no chance to get sabznbd src to work correctly on Windows, because par2 and unrar are critical.

No problems with memory allocation found on Windows. At beginning, the python process did allocate ~25MB, while downloading it did go up to ~150MB, at end it was ~50MB. The difference of 25MB seems neglible and normal to me. I even tested both the official python for Windows and ActivePython in current versions, no problems with memory allocation with both. All programs were 32bit.

**Comment by thezoggy** [comment]
theres no reason to document paths for apps that sab provides.. as they work.. so theres no reason that the user should even be messing with them.

**Comment by Hubfront** [comment]
Sure there is: without documentation of these paths above there is no chance getting sabznbd src to useful work - as par2 and unrar functionality will not be available under windows. If u dont bother, then write in INSTALL.txt, that installation of sabznbd src on windows is not officially supported and one should rely on the official compiled version.

**Comment by Safihre** [comment]
What we mean is that if you do a normal clone of the Github repository, the par2 and unrar exe will exactly be in the place they should be.
I have installed it many times from source using ```git clone``` or the zipped archive and it always works..
We have no idea why yours weren't in the right location!

**Comment by thezoggy** [comment]
yep, have been running sab from src for years on many machines.. never a problem here too.

**Comment by Hubfront** [comment]
Wrong answer: download src from official mirror as 99,9 percent of users do and try install it on Windows without knowing those paths. Impossible.

**Comment by Safihre** [comment]
If you download this zip from the top of our github page you will see that the executables are exactly where they should be:
https://github.com/sabnzbd/sabnzbd/archive/develop.zip

I have no idea how this can be a problem..

**Comment by thezoggy** [comment]
how are you downloading the source? are you cloning from github? are you downloading a zip? if your getting a zip.. from where? github? sourceforge? etc

**Comment by Safihre** [comment]
He's right.. The src from sourceforge.net doesn't contain the win or osx folders.. Now I finally understand!

**Comment by thezoggy** [comment]
of course.. cause thats linux source.

**Comment by thezoggy** [comment]
https://github.com/sabnzbd/sabnzbd/releases

if you want the src (source) you notice its only for linux.

**Comment by thezoggy** [comment]
dont think ive ever hear of someone trying to grab linux src and using on windows before.. why we were like wtf is he talking about :)

**Comment by Hubfront** [comment]
Normally i would use the compiled version, but the nature of this bug forced me to download and install src and python separately, in order to study memory management of python. ;-)

**Comment by thezoggy** [comment]
perhaps a workaround for your setup is to use sab's scheduler and tell it to reboot sab every x <hour/day/week/etc>. that way you ensure any memory that wasnt released by the garbage collector is dealt with...

**Comment by shypike** [comment]
To explain the src package: we only distribute it as a source for package creators for various UNIX/Linux systems. Packagers do not accept anything binary and executable.

**Comment by Hubfront** [comment]
Can restarting sab often make problems with processing jobs like extracting files or par-jobs?

**Comment by thezoggy** [comment]
due to the lack of any proof of memory issues it will be hard to get it sorted..  but restarting sab should be fine.. ideally you'd want to do it when there is an empty queue.. so schedule it for a day/time that theres less likely to be anything going on. and im not suggest restarting sab daily.. but something like monthly.

**Comment by Hubfront** [comment]
I could only verify this memory issue with the python version compiled with spsrc, but on two different hardware platforms (Synology Arm and Intel). I could not check it with the official python version from synology because the sab package required the spsrc version.

**Comment by Safihre** [comment]
Unfortunately, nothing we can do about this from the SABnzbd side.

**Comment by maran** [comment]
Just chiming in here since I think my 'problems' might be related.

I run a hosting provider that offers one-click install for various apps, Sabnzbd being one of them. I've noticed that Sab is often the highest memory using on my cluster.

I've looked up the memory usage of 230 running processes and 70 processes had memory usage > 300MB RSS (not VIRT). 40 processes of those had a memory usage > 500MB RSS and 20 > 1GB RSS. The highest had 2.3GB of RAM in use. (which is close to the 2.5GB OOM range for my cgroups).

From what I can tell even when I simulated high RAM pressure the memory was not being reclaimed. 

Is there anybody that can tell me if this is just 'normal' behaviour and I should setup some auto-restart scripts or if there is something I can do about this behaviour.

**Comment by thezoggy** [comment]
@maran what os / python / etc. how do you run sab and what things have you dont to prove its sab at fault?

**Comment by maran** [comment]
I tested the following on: Ubuntu 16.04, Python 2.7.12 and sabnzbdplus-2.3.3 and Ubuntu 18.04, Python 2.7.15 and sabnzbdplus-2.3.8Beta1.

1. Download a file or two and note the RSS. In my case on my test server the RSS sits at 716MB (37% of the total memory)
2. Now I run `stress` with the request to allocate more memory then is currently free in the hopes that Sab would release it's memory to facilitate stress's allocation. However stress can't or won't.

```
stress --vm-bytes 1024M --vm-keep -m 1
stress: info: [7614] dispatching hogs: 0 cpu, 0 io, 1 vm, 0 hdd
stress: FAIL: [7615] (494) hogvm malloc failed: Cannot allocate memory
stress: FAIL: [7614] (394) <-- worker 7615 returned error 1
stress: WARN: [7614] (396) now reaping child worker processes
stress: FAIL: [7614] (451) failed run completed in 0s
```

Looking at free, I would assume that I could have assigned that as the currently 'available' plus the current usage by sab would have been more than 1GB. 

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1991        1088         696           0         207         723
Swap:           511         505           6
```

Alternatively it's quite possible I misunderstand the way allocations for stress work.
