### ISSUE TITLE
Unsafe content (plain HTTP google link) in https://<sabhost>/sabnzbd/config/rss/

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#444]
Unsafe content (plain HTTP google link) in https://< sabhost >/sabnzbd/config/rss/

Cause: interfaces/Config/templates/config_rss.tmpl 
```
<div class="favicon" style="background-image: url(http://www.google.com/s2/favicons?domain=$rss[$feed_item]['baselink']&amp;alt=feed);"></div> $feed_item 
```
which is plain HTTP and thus considered unsafe. 
I changed the line to
```
<div class="favicon" style="background-image: url(https://www.google.com/s2/favicons?domain=$rss[$feed_item]['baselink']&amp;alt=feed);"></div> $feed_item
```
and that worked for me.

**Comment by Safihre** [comment]
Added the fix to #443.
Wonder how long this Google service will keep on working, not that it's a very essential feature.

**Comment by sanderjo** [comment]
That google link retrieves the favicon of the URL specified? Strange indeed that Google offers that service.

FWIW: SABnzbd itself could retrieve the corresponding favicon:

RSS URL: https://api.nzbgeek.info/rss...
favicon on:
https://www.nzbgeek.info/favicon.ico
https://nzbgeek.info/favicon.ico
(not https://api.nzbgeek.info/favicon.ico)

But ... switching to that could make the "unsafe content" problem re-occur: if someone fills out a plain-HTTP RSS feed, the favicon content would be unsafe.

**Comment by thezoggy** [comment]
hehe sanderjo, yeah I added that google link a long time ago... its been working for many years :)

**Comment by Safihre** [comment]
It's fairly simple to do ourselves with a PHP or other server-side script to correctly extract the favicon.
But if Google stops offering it we can just stop using it, just for the looks anyway :P
