### ISSUE TITLE
Local network range issues when bound to IPv6 address

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#446]
Testing #442 I noticed that putting '192.168.' as *List of local network ranges* somehow did not see any of the devices on my network as local.
Debugging I found out that because I filled ```::``` for Host CherryPy returns this when I visit SAB with another device on the network:
```cherrypy.request.remote.ip = ::ffff:192.168.0.10```

So this check in ```check_access``` returns false:
```range_ok = (not cfg.local_ranges()) or bool([1 for r in cfg.local_ranges() if referrer.startswith(r)])```

Can we do anything about this?

**Comment by thezoggy** [comment]
do believe that was fixed in newer version of cherrypy than we are using...

**Comment by sanderjo** [comment]
How about this:
```
>>> '::ffff:192.168.0.10'.split(':')[-1]
'192.168.0.10'
>>> '192.168.0.10'.split(':')[-1]
'192.168.0.10'
```

**Comment by sanderjo** [comment]
... but how about specifying IPv6 addresses?

If I fill out ```2001:aaaa:bb00:```, will that work?

**Comment by sanderjo** [comment]
Oh, and if SABnzbd Host is localhost or 127.0.0.1, I guess filling out List of local network ranges / External internet access is not useful?

**Comment by thezoggy** [comment]
i would love to just provide the ip/subnet to whitelist.. like you do in fail2ban/iptables/etc.
can provide specific blocks.. for example work ip, vpn ip, local, etc etc


http://www.fail2ban.org/wiki/index.php/Whitelist
`ignoreip = 127.0.0.1 192.168.1.0/24 8.8.8.8`

**Comment by Safihre** [comment]
I was doing some more testing on this, and I found that this is the IPv6-hybrid notation for dual-stack.
So we could do a count of ```:``` and ```.``` (or some better reg-exp) to know if we should cut off the ```::ffff:``` part?

**Comment by Safihre** [comment]
@sanderjo so after reading I found that it will always start with ```::ffff:``` in case of a hybrid notation, 
https://www.google.com/search?q=::ffff:+ipv6

So I implemented this change:
https://github.com/Safihre/sabnzbd/commit/fa801e1366ec2f0b66767c1041601a6eef9c11c1
Since I noticed it also reported my localhost visits now as ```::ffff:127.0.0.1``` when SABnzbd host was set to ```::```.

What do you think?

**Comment by sanderjo** [comment]
Looks good.

I tried it on my dual-stack machine, and it works. I've tested with the following listening hosts:
```
0.0.0.0
::
127.0.0.1
127.0.1.1
```

I was surprised that last entry (127.0.1.1) was working; that's Ubuntu (Debian?) talk for the localhost. But it works. Good.

**Comment by shypike** [comment]
Closed? But has anything been implemented?

**Comment by Safihre** [comment]
ab0d8e0 in #508 fixes the problem. Taking into account a possible ```::ffff:``` was all that was needed.
