### ISSUE TITLE
Servers in Scheduling

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#447]
it is not very clear about why the usenet servers show up in the scheduling list... 
prob add the comment from the wiki there: `Number for a speed limit value. 0 or 1 for disabling or enabling a server` also need to update that to reflect you can use % now?

@Safihre we should use opt-groups to segment the usenet servers from the normal actions..
also the description is used.. thus really easy to break the scheduler as the description could change.. needs to be reverted back to the server...  then for the display using the description is fine -- but we do need to make sure we strip out characters that would break the html there

**Comment by Safihre** [comment]
Done: #443. Clicking on either the disable or enable one will auto-fill the arguments field.
It is now also based on server-id, not ```displayname```.
![image](https://cloud.githubusercontent.com/assets/5703454/12539334/c8857114-c2f0-11e5-9104-fc10db3b66dd.png)

**Comment by thezoggy** [comment]
nice!

**Comment by thezoggy** [comment]
wonder if we should add the ability to set an indexer's priority via the scheduler...

**Comment by Safihre** [comment]
Changed the javascript so it will only show the arguments field for Speedlimit. For the server's it's filled, but hidden.
I don't see a point to setting priority on a specific time, newsservers aren't really time-bound..

**Comment by thezoggy** [comment]
i have like 5 block accounts.. most of them are all at the same priority.
since sab doesnt load balance them in any way.. the only hack I can think of is to just change priorities of them periodically so that way I dont just eat up one block account. not a huge deal and deff a niche feature for my use case.

**Comment by shypike** [comment]
Maybe confirmed by another user in a different scenario.

**Comment by shypike** [comment]
I cannot reproduce the issue.
I tried with two and three servers of the same priority, they balance nicely.
Even tried it with a random generator that fails messages with a 25% chance, to force usage of the other servers. Same result: works fine.

**Comment by Safihre** [comment]
@shypike I think you are in the wrong issue here? It's #377, but you changed the title of this one.
The problem of this one about the scheduler labeling is already fixed but #377 is still open for the load-balancing thing.
