### ISSUE TITLE
Downloading of articles while SABnzbd being Paused

### ISSUE THREAD

**Issue by Ravefiend** [sabnzbd/sabnzbd#448]
This is an issue I've been seeing since 0.7.x and still exist in 0.8.0 beta 5.

Configuration - Schedule:
00:00 Daily Resume
12:00 Daily Pause All

Purpose: download from midnight till noon and not during the afternoon nor evenings.

NZBs can still be added while SABnzbd is on Pause, queuing up the work that'll kick off at midnight. If one of those items in the queue is one I don't want to wait upon, I switch it it's priority to Force which starts the download. All the other NZBs in the queue should remain Paused.

SABnzbd starts downloading the one having Priority set to Force, but some articles of the next item get also downloaded while the last articles of the NZB that I had switched to Force, are being retrieved. In other words, downloading of articles is overflowing to the next NZBs in the queue.

I have a primary usenet server and a few optional block servers configured. What can happen is that the NZB I switched to Force is getting downloaded till 95% completeness, and at the end it needs to obtain the remaining articles from a block server which can be a lot slower. During that time, SABnzbd starts to download articles of the next NZB in the queue, which state is set to Pause so it should not be downloading any articles. As these are getting downloaded from my fast primary usenet server, there can be a significant amount of 'overflowing'. 

Worst case scenario I came discovered today. I have an NZB in the queue that ran till 99% with a few dozen articles remaining. It got stuck in the queue at 99% as the username/password of one my block accounts got expired, causing "Authentication failed, check username/password". The current state, while having SABnzbd set to Paused, any new NZB I add automatically starts downloading, despite them not having priority set to Force. Expected behavior is for any new ones to be queued up.

This behavior poses a risk for users whom have a download limit enforced by their ISP.

**Comment by albino1** [comment]
Can confirm.  I've had this happen with 0.7.20 many times in the past, and yeah, it is annoying.  You Pause SABnzbd, switch one NZB to forced, and other NZBs start downloading as well.  Haven't tried to replicate it in 0.8.x though.

**Comment by Safihre** [comment]
@shypike I made a fix (pretty simple):
https://github.com/Safihre/sabnzbd/commit/4c5d1aa2c50e4855372ab64994cca1e58b6e4b54
What do you think?

_(this issue is same as #126)_
