### ISSUE TITLE
sab 0.8.x -- develop branch

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#451]
just fyi develop branch is a few betas old now..  didnt realize you moved 0.8.x dev to `R0.8.0` thus I havent had any of the new code in awhile now :(  i assume theres many others that prob got hit by this as they just do git pull and assume it was going to be updated.

**Comment by thezoggy** [comment]
also we need to do some branch cleanup.. as long as we use TAGs we dont need to create branches for specific versions.. unless you really want to branch code and work on separate things..  
I see no need for these: `0.6.x`, `R0.6.10`, `0.7.x`, `R0.8.0`

**Comment by Safihre** [comment]
It's a bit weird because I do see the same commit's looking at the messages, but when comparing R0.8.0 and develop it still shows all these file differences that shouldn't be there..

**Comment by shypike** [comment]
R0.8.0 and develop are not in sync.
I did some commits into develop that I don't want in R0.8.0

**Comment by thezoggy** [comment]
but the latest and greatest wasnt in develop is the point i was making. i had to switch to R0.8.0 to go from b4 to b6

**Comment by shypike** [comment]
B6 is only tagged in R0.8.0. The develop branch has all content of R0.8.0 (and more), except Readme.md and PKG-INFO.

**Comment by thezoggy** [comment]
you want me to submit code against develop or R08.0 ?

**Comment by shypike** [comment]
No, develop. I'll CherryPick what must go into R0.8.0
