### ISSUE TITLE
sab 0.8.x -- binary found

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#452]
sometimes we wrap the logging for translation.. sometimes not.. 
sometimes its a warning.. sometimes info.. sometimes error... 

not sure why were translating the whole line with the module/binary and not just the result part which is ultimately what needs to be translated (found/not found)..  thus could get away with just two translations and provide better flexibility.

`logging.warning(T('unrar binary... NOT found'))`

vs 

`logging.info("ionice binary... NOT found!")`

vs

`logging.error(T('par2 binary... NOT found!'))`

**Comment by shypike** [comment]
Just forgotten, I guess. The warning should be translated, not the info.
The warning and the error should be parameterized for the actual name.
It can be that some info-s have been translated because they were intitially warnings and later became info-s.

**Comment by thezoggy** [comment]
@shypike is this right? https://github.com/sabnzbd/sabnzbd/blob/develop/po/main/fi.po#L195

**Comment by shypike** [comment]
@thezoggy Looks normal to me. What do you think is wrong here?

**Comment by thezoggy** [comment]
the warning line being on its own line after the previous ""

**Comment by Safihre** [comment]
It's like that in all languages, seems to work still.

**Comment by shypike** [comment]
@thezoggy That's the way Launchpad happens to format the files. It's valid syntax for GNU translation files. Consecutive quoted lines are pasted together by the parser.

**Comment by thezoggy** [comment]
gotcha, just looked odd to me.. why i checked :)
