### ISSUE TITLE
Glitter Theme

### ISSUE THREAD

**Issue by Tfalwell** [sabnzbd/sabnzbd#454]
Just updated the beta and it wouldnt load with Glitter theme.  Went into the settings file and changed it back to plush.  Opened fine.  Then went into SAB settings and set it back to Glitter and it gives me the 500 internal error code again.

**Comment by Safihre** [comment]
Could you uninstall and then make sure the program directory is empty before re-installing? 

@shypike, I saw this also on the forums and 2x on reddit, people upgrading the beta. 
Could it be some left over .pyd files or something like that?

**Comment by shypike** [comment]
@Safihre if old files remain, there's no telling what will happen.
.pyd files are not the problem, left over .pyc files are not likely to cause issues, left-over template files are.

**Comment by Safihre** [comment]
It's usually a 500 error about preload_queue not being available, so meaning that the template got updated but interface.py was not.

**Comment by Safihre** [comment]
@Tfalwell, did you managed to fix it?
