### ISSUE TITLE
[REQ] Add seperate web interface refresh frequency option to be used while idle

### ISSUE THREAD

**Issue by noodle-** [sabnzbd/sabnzbd#455]
use case: Only refresh SABnzbd web interface every second while downloading and set it to disabled or any low frequency while nothings happening.

This would reduce the idle cpu usage a bit.

Interface options could look like this:
```
Refresh rate while active  <dropdown menu>
Refresh rate while idle    <dropdown menu>
```

**Comment by Safihre** [comment]
The idle CPU usage is already really low (less that 1%) and is barely impacted by that. 
Why keep the interface open at all when you see nothing is downloading?

**Comment by noodle-** [comment]
Well it's a little more cpu usage for my little banana pi.
I keep the tab pinned on the browser of my PC so the tab lights up when it starts downloading some show automatically.

On Jan 31, 2016 15:18, Safihre <notifications@github.com> wrote:

The idle CPU usage is already really low (less that 1%) and is barely impacted by that.
Why keep the interface open at all when you see nothing is downloading?

-

**Comment by Safihre** [comment]
Exactly the problem, the interface cannot know if something has happened in the background. There are ways of 'listening' and only getting data when something has happened, but sabnzbd Webserver doesn't support that. I looked into it before.. 
Maybe you missed it because I edited my initial response, but:
> Glitter also automatically only updates the browser title and no history/queue when you have the browser minimized or are not viewing the tab.
Are you using Glitter?

**Comment by noodle-** [comment]
>Exactly the problem, the interface cannot know if something has happened in the background. There are ways of 'listening' and only getting data when something has happened, but sabnzbd Webserver doesn't support that. I looked into it before.. 

Ah shame, thanks for the info!

>Maybe you missed it because I edited my initial response, but:
>>Glitter also automatically only updates the browser title and no history/queue when you have the rowser minimized or are not viewing the tab.
Are you using Glitter?

Yea sorry, missed that as I was replying by mail.

Yes to using glitter but the feature you're describing doesn't seem to work for me. Does it not work with every browser? I'm using the latest Firefox.

CPU usage is < %1 when the tab is closed. Between %5 and %10 while opened, and this doesn't seem to change while the browser is in the background & minimized. No difference when the tab is pinned or unpinned.

Just wondering btw, it's not like this is a major issue. :)

**Comment by Safihre** [comment]
@noodle- In 1.1.0 we will have this feature for the history (only updates when something happens), not the queue.
The Queue is most likely to be updated many times, so only implemented it for the History. 
It's already in the development, in case you run from Git source :)

**Comment by thezoggy** [comment]
yeah, trying to add another option to bandaid the issue is not a proper fix. being __smarter__ about when to update is the fix. which we've started to do with the history now.
