### ISSUE TITLE
Rename 0.8.0 release to 1.0.0

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#456]
We should finally start using [semantic versioning] (http://semver.org/).
This is a good time, since we have breaking changes.
Our major release 0-\>1 doesn't break the API, but it does break the queue.
Also, after 9 years it's time for 1.0.0 :)

**Comment by Safihre** [comment]
:+1: :smiley:

**Comment by Safihre** [comment]
You even already altered the wiki, nice!
Only the links to the help-pages in the Config probably need a rename: ```http://wiki.sabnzbd.org/configure-notifications-0-8``` to ```http://wiki.sabnzbd.org/configure-notifications-1-0```

**Comment by shypike** [comment]
@Safihre I wait for that until 1.0.0RC1 is actually out, otherwise current Beta's will fail.

**Comment by jeffgeorge** [comment]
:+1: :shipit:

Sad that it breaks the queue, is there any way around that?

**Comment by shypike** [comment]
@jeffgeorge It isn't so bad. You're warned and all it takes is a queue repair. The only thing that's lost (and that's also why it doesn't upgrade automatically) is the queue order.

**Comment by jeffgeorge** [comment]
Oh that's not terrible, so long as it can be repaired and there's messaging that's worth it.
