### ISSUE TITLE
ssl for servers no longer available after update

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#457]
#I've recently updated from OpenSUSE 13.2 to Leap 42.1 and it appears something is different. I noticed today that while python-pyopenssl openssl and other related modules appear to be installed, SAB is no longer recognizing ssl. 0.7.x branch, using git repo.

Any suggestions would be appreciated.

**Comment by thezoggy** [comment]
does your python come with ssl? do you have pyopenssl installed?

**Comment by mgaulton** [comment]
Yes i do. I verified the packages are installed as a first step. I referred to several forum posts. Everything appears to be in place. I even installed python-pyopenssl and python3-openssl to be on the safe side.

**Comment by shypike** [comment]
Open a Terminal, start python, and then type:
```
  from OpenSSL import SSL
  SSL.SSLeay_version(SSL.SSLEAY_VERSION)
```
What does that show?

**Comment by thezoggy** [comment]
Python 3.x is not supported

-----Original Message-----

**Comment by mgaulton** [comment]
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import SSL
>>>   SSL.SSLeay_version(SSL.SSLEAY_VERSION)
  File "<stdin>", line 1
    SSL.SSLeay_version(SSL.SSLEAY_VERSION)
    ^
IndentationError: unexpected indent
>>> SSL.SSLeay_version(SSL.SSLEAY_VERSION)
'OpenSSL 1.0.1i-fips 6 Aug 2014'
>>>

**Comment by mgaulton** [comment]
@thezoggy python 2.7.9 is my default. py3 is installed and called explicitly for scripts that need it.

**Comment by shypike** [comment]
OK.
Set logging to debug and restart SABnzbd.
Then look at the end of the log file, search for anything with "ssl" in it (search case-insensitive).

**Comment by thezoggy** [comment]
SSL and python is a confusing beast. python itself may or maynot have ssl (python 2.5 and older / certain compiled versions for low powered devices). Then there is the system openssl.. then the wrapper pyopenssl. So end the end, openssl version in python could be the system or dynamic linked version.

now why the version of openssl matters:

  * `The installed version of OpenSSL may also cause variations in behavior. For example, TLSv1.1 and TLSv1.2 come with openssl version 1.0.1.`

  * `OS X installers use their own versions of OpenSSL and thus no longer depend on the now-deprecated system OpenSSL as of Python 2.7.9`


example from my sab instance on Win7 running from git:
```
2016-02-07 10:37:08,786::INFO::[SABnzbd:527] pyOpenSSL... found (True)
2016-02-07 10:37:08,789::INFO::[SABnzbd:1367] SSL version OpenSSL 1.0.2d 9 Jul 2015
```

python version:
```
C:\>python -V
Python 2.7.11
```

Python 2.7.11 changelog: https://hg.python.org/cpython/raw-file/53d30ab403f1/Misc/NEWS
```
- Issue #24603: Update Windows builds and OS X 10.5 installer to use OpenSSL
  1.0.2d.
```

OpenSSL version:
```
C:\>openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

OpenSSL version that python uses:
```
>>> import ssl
>>> print ssl.OPENSSL_VERSION
OpenSSL 1.0.2d 9 Jul 2015
>>> print ssl.__file__
C:\Python27\lib\ssl.pyc
```

pyOpenSSL wrapper version:
```
>>> import OpenSSL
>>> print OpenSSL.__version__
0.15.1
>>> print OpenSSL.__file__
C:\Python27\lib\site-packages\OpenSSL\__init__.pyc
```

@sanderjo prob should add the ability to get pyOpenSSL version to the sab sslinfo utility...

**Comment by sanderjo** [comment]
I don't understand what the problem is:
"ssl for servers no longer available after update": does that mean SSL is not selectable in the SAB GUI for newsservers?
" SAB is no longer recognizing ssl." I don't understand that either.


So I installed a docker image of opensuse:leap, and then:

```
zypper --non-interactive install  python python-pyOpenSSL git mozilla-nss-certs wget tar python-Cheetah python-xml par unrar

wget 'http://downloads.sourceforge.net/project/sabnzbdplus/sabnzbdplus/0.7.20/SABnzbd-0.7.20-src.tar.gz?r=http%3A%2F%2Fsabnzbd.org%2Fdownload%2F&ts=1454871477&use_mirror=kent' -O SABnzbd-0.7.20-src.tar.gz

wget 'http://downloads.sourceforge.net/project/sabnzbdplus/sabnzbdplus-beta/1.0.0RC1/SABnzbd-1.0.0RC1-src.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fsabnzbdplus%2Ffiles%2Fsabnzbdplus-beta%2F1.0.0RC1%2F&ts=1454873174&use_mirror=netix'  -O SABnzbd-1.0.0RC1-src.tar.gz
```
... and I have **no** problems with selecting SSL for newsservers, so I don't know what the OP is experiencing. 

Answering @shypike 's question:
```
bash-4.2# python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import SSL
>>> SSL.SSLeay_version(SSL.SSLEAY_VERSION);              
'OpenSSL 1.0.1i-fips 6 Aug 2014'


bash-4.2# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
bash-4.2# 

```

**Comment by sanderjo** [comment]
So ... maybe @mgaulton can post image of the the problem he/she is experiencing in SABnzbd?

**Comment by sanderjo** [comment]
@thezoggy 

Which info would you like to add? This (from openSuSE leap):
```
bash-4.2# python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
>>> print OpenSSL.__version__
0.14
>>> print OpenSSL.__file__
/usr/lib/python2.7/site-packages/OpenSSL/__init__.pyc
>>> 

```

**Comment by thezoggy** [comment]
just the pyOpenSSL version (OpenSSL)..

**Comment by thezoggy** [comment]
on another box in my network,

```
C:\>python -c "import ssl;import OpenSSL;print ssl.OPENSSL_VERSION;print OpenSSL.__version__"
OpenSSL 0.9.8y 5 Feb 2013
0.15.1

C:\>openssl version
OpenSSL 0.9.8zb 6 Aug 2014

C:\>python -V
Python 2.7.5
```

**Comment by thezoggy** [comment]
@sanderjo I went ahead and just added it myself, will toss it in the config pull request

**Comment by mgaulton** [comment]
For clarify, i get a message in the logs that openssl isn't found and the SSL checkbox is disabled in the UI>

**Comment by mgaulton** [comment]
Using the zypper install cmdline used above.

server6:~ # zypper --non-interactive install  python python-pyOpenSSL git mozilla-nss-certs wget tar python-Cheetah python-xml par unrar
Loading repository data...
Reading installed packages...
'python' is already installed.
No update candidate for 'python-2.7.9-21.1.x86_64'. The highest available version is already installed.
'wget' is already installed.
No update candidate for 'wget-1.17.1-79.1.x86_64'. The highest available version is already installed.
'git' is already installed.
No update candidate for 'git-2.6.2-1.1.x86_64'. The highest available version is already installed.
'python-xml' is already installed.
No update candidate for 'python-xml-2.7.9-21.3.x86_64'. The highest available version is already installed.
'python-pyOpenSSL' is already installed.
No update candidate for 'python-pyOpenSSL-0.14-5.2.noarch'. The highest available version is already installed.
'tar' is already installed.
No update candidate for 'tar-1.27.1-6.1.x86_64'. The highest available version is already installed.
'unrar' is already installed.
No update candidate for 'unrar-5.3.3-1.3.x86_64'. The highest available version is already installed.
'mozilla-nss-certs' is already installed.
No update candidate for 'mozilla-nss-certs-3.21-9.1.x86_64'. The highest available version is already installed.
'python-Cheetah' is already installed.
No update candidate for 'python-Cheetah-2.4.4-10.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...

The following NEW package is going to be installed:
  par

1 new package to install.
Overall download size: 36.0 KiB. Already cached: 0 B. After the operation, additional 76.4 KiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package par-1.1-190.2.x86_64                                                                                 (1/1),  36.0 KiB ( 76.4 KiB unpacked)
Retrieving: par-1.1-190.2.x86_64.rpm ..................................................................................................................[done]
Checking for file conflicts: ..........................................................................................................................[done]
(1/1) Installing: par-1.1-190.2 ..........................................................

**Comment by mgaulton** [comment]
server6:/tmp/sabnzbd # python -c "import ssl;import OpenSSL;print ssl.OPENSSL_VERSION;print OpenSSL.__version__"
OpenSSL 1.0.1i-fips 6 Aug 2014
0.14

server6:/tmp/sabnzbd # python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2


server6:/tmp/sabnzbd # openssl version
OpenSSL 1.0.1i-fips 6 Aug 2014

**Comment by sanderjo** [comment]
> For clarify, i get a message in the logs that openssl isn't found 

Copy-paste the **exact** error mesage here, please.

> and the SSL checkbox is disabled in the UI>

Copy-paste a screenshot of that here, please.

**Comment by mgaulton** [comment]
sabnzbd.log.1:2016-02-10 23:41:45,114::INFO::[SABnzbd:501] pyOpenSSL... NOT found - try apt-get install python-pyopenssl (SSL is optional)

![image](https://cloud.githubusercontent.com/assets/4757726/12970013/0ff2ab70-d057-11e5-8801-1ba85764437e.png)

**Comment by thezoggy** [comment]
are you installing pyopenssl after sab started... what happens if you tell sab to restart (does it pick it up then)?

**Comment by sanderjo** [comment]
@mgaulton 

 On your openSuSE, open a terminal, and execute:

```
python -c "from OpenSSL import SSL; print 'done' "
```
Post the output, between ` ` ` 's

AND:

On your openSuSE, open a terminal, start python, and then type
```
from OpenSSL import SSL
```

Post the output here.

**Comment by thezoggy** [comment]
so long story short, 

if users want SSL when connecting to their usenet service providers (e.g. TLSv1.2) they need openssl ( `python -c "import ssl;print ssl.OPENSSL_VERSION"` ) and pyOpenSSL ( `python -c "import OpenSSL;print OpenSSL.__version__"` ).

the version of openssl AND pyOpenSSL will dictate what ssl they can/cant do:

  > TLSv1.1 and TLSv1.2 come with openssl version 1.0.1

  > Support for TLSv1.1 and TLSv1.2 came with pyOpenSSL 0.14

so first step on trying to weed out issues going forward with https verification is getting actual ssl detection sorted..

**Comment by mgaulton** [comment]
FYI, i just ran the below and noticed that I have pyOpenSSL 0.15.1, where you mention 0.14. Any chance something changed wth the newer ver?

server6:/tmp/sabnzbd # python -c "import ssl;print ssl.OPENSSL_VERSION"
OpenSSL 1.0.1i-fips 6 Aug 2014
server6:/tmp/sabnzbd #  python -c "import OpenSSL;print OpenSSL.__version__"
0.15.1

**Comment by mgaulton** [comment]
@sanderjo for python -c "from OpenSSL import SSL; print 'done' ", i get 'done' as output.

**Comment by thezoggy** [comment]
0.14+ is fine for pyopenssl.
but anyways i'm curious if restarting sabnzbd results in a change of it saying you have ssl.. if so then it proves my theory that when you boot your machine.. it launches sab and detects you dont have ssl installed, but then when your testing it is... thus if you restart sab it should pick up the fact you do in fact have it.. thus your init script/boot process is the issue.

**Comment by mgaulton** [comment]
i've done numerous restarts of SAB, numerous reboots of the box. Hell, i even migrated to a VM from Physical last week with a clean install. All Leap 42.1, all showing this behaviour. Any suggestions or recommendations for a init script to replace mine? I can try that.

**Comment by thezoggy** [comment]
have you tried starting sab manually (`python SABnzbd.py`) and see if it works? if so then yes its an init script problem.. 

looking for python ssl and leap, I see reports of others having to install these packages to make other apps happy:
```
ca-certificates-cacert
python-M2Crypto
```

**Comment by mgaulton** [comment]
I loaded those modules, no change after a forced start.

**Comment by thezoggy** [comment]
that is quite baffling how you can load the lib from command line but manual start sab doesnt see them.. so far you are the only person that has report having any problems..  im at a lost on what is wrong with your setup...  with sab log set to debug, can you post your startup log (use pastebin) or send to zoggy@sabnzbd.org

**Comment by mgaulton** [comment]
I will when i have a chance tomorrow. I'll include the shell scripts i use for startup etc. Hopefully you see something i'm missing.

**Comment by mgaulton** [comment]
Email sent.

**Comment by thezoggy** [comment]
sure you've heard about the SSLv2 (DROWN) attack thats been going around, openssl's latest release takes care of it by disabling sslv2...

https://www.openssl.org/news/secadv/20160301.txt
`NOTE: With this update, OpenSSL is disabling the SSLv2 protocol by default, as
well as removing SSLv2 EXPORT ciphers.`

not sure if this will cause us any issues (connecting to servers / sending emails / etc).. but may change the landscape as sites start disabling sslv2 to deal with it.. 

https://test.drownattack.com/?site=ssl.astraweb.com

**Comment by mgaulton** [comment]
Funny story i discovered the other day that git updated me to the 0.8.x branch (master) and i was delighted to discover that SSL was again available, everything was detected. A couple days and a reboot or two later, it is now no longer being detected. I'm wondering of OpenSuse is just being weird now.

**Comment by mgaulton** [comment]
And they're gone again *sigh*

Is there a way to set the server priority to user SSL when available but then fall back to the non-ssl when they time out?

**Comment by thezoggy** [comment]
you could always just add the same server with both variants.. but quite a hacky workaround for whatever is going on with your box.. as no one else has reported this issue...

**Comment by mgaulton** [comment]
I hear you. I'm completely baffled. one restart, its fine, some random time later, its missing again.

**Comment by Safihre** [comment]
Seeing this whole issue I would just start from scratch on this box and install everything on a fresh install, it just seems so random.

**Comment by mgaulton** [comment]
I know. it comes and goes, and only since leap 42.1. 13.2 was perfectly fine.

**Comment by mgaulton** [comment]
@Safihre its been rebuilt once since this started. came back.

**Comment by thezoggy** [comment]
does sab always have ssl if YOU start it manually?
does sab not have ssl if you start it with your init/cron job?
does sab have ssl until you tell it to restart?

**Comment by mgaulton** [comment]
let me go through those scenarios and see what happens.

fyi, after its disabled and comes back, the ssl checkbox insn't checked/the setting isn't restored so even setting the priority as a workaround doesn't work.

**Comment by mgaulton** [comment]
Aaaand i discovered something interesting. Using the restart functionality within the sab interface restores ssl?



Manual shutdown from interface.

does sab always have ssl if YOU start it manually?
cmdline = /opt/sabnzbd/SABnzbd.py -d -f /opt/.sabnzbd/sabnzbd.ini --pid /tmp/sabnzbd --logging 2 & #--repair

started manually with commandline options = OpenSSL not avail, pyOpenSSL not avail
started manually with no commandline options = wizard is presented, pyopenssl not detected

does sab not have ssl if you start it with your init/cron job?
started with /etc/init.d/sabdaemon start =  OpenSSL not avail, pyOpenSSL not avail
reboot system and let /etc/init.d/sabdaemon start it =OpenSSL not avail, pyOpenSSL not avail

does sab have ssl until you tell it to restart?
tell sab to restart from queue repair tab = OpenSSL AVAIL, pyOpenSSL AVAIL
tell sab to restart from Options in top right = OpenSSL AVAIL, pyOpenSSL AVAIL

**Comment by mgaulton** [comment]
Pulling from the log after the restart.

2016-03-24 14:57:15,088::INFO::[SABnzbd:527] pyOpenSSL... found (True)
2016-03-24 14:57:15,088::INFO::[SABnzbd:1367] SSL version OpenSSL 1.0.1i-fips 6 Aug 2014
2016-03-24 14:57:15,088::INFO::[SABnzbd:1368] pyOpenSSL version 16.0.0
2016-03-24 14:57:15,089::INFO::[SABnzbd:1369] SSL potentially supported protocols ['SSLv2', 'SSLv23', 'SSLv3', 'TLSv1', 'TLSv1_1', 'TLSv1_2']
2016-03-24 14:57:15,089::INFO::[SABnzbd:1370] SSL actually supported protocols ['t12', 't11', 't1', 'v23', 'v3', 'v2']
2016-03-24 14:57:15,091::INFO::[SABnzbd:1516] Starting web-interface on 0.0.0.0:8085

**Comment by thezoggy** [comment]
interesting, pyOpenSSL 16 just came out.. something to note for future notice.. will have to be on the lookout when they drop python 2.6 (right now its just deprecated):

http://www.pyopenssl.org/en/stable/changelog.html
```Python 2.6 support has been deprecated. Our main dependency cryptography deprecated 2.6 in version 0.9 (2015-05-14) with no time table for actually dropping it. pyOpenSSL will drop Python 2.6 support once cryptography does.```

**Comment by mgaulton** [comment]
I just wanted to note something that recently resolve this. I had an issue with the web ui / process restarting randomly and adding an explicit PATH= statement to the init file corrected that. I noted additionally that I have not had this SSL issue since i had made that change. every restart/reboot has had SSL active since. Just thought i'd update you guys.
