### ISSUE TITLE
Feature Request: Updates for Pause feature

### ISSUE THREAD

**Issue by thefotios** [sabnzbd/sabnzbd#46]
Here are a couple of ideas I've had for the Pause button.
 * Instead of counting down, show "Paused until ..."
 * Provide a way to pause for "n hours" instead of just minutes
 * Provide a way to pause "until xx:xx"
   * This might be able to be done by Pausing and then creating a one-time scheduled event to unpause

**Comment by shypike** [comment]
Fixes and adding option for custom pausing #342
