### ISSUE TITLE
SABnzbd 1.0.x shutdown message incorrect

### ISSUE THREAD

**Issue by marka65** [sabnzbd/sabnzbd#461]
When closing down SABnzbd from web ui, message displays 0.8, but version is 1.0.x.

Message displayed:

Initiating shutdown...
SABnzbd-0.8.x shutdown finished

**Comment by shypike** [comment]
Is that when running from source directly from git?
If so, that's OK. In the distribution files we patch the version number.

**Comment by marka65** [comment]
Yes, downloaded from git and ran with python.....

**Comment by thezoggy** [comment]
cached? just tried this on windows binary
```
Initiating shutdown...
SABnzbd-1.0.0RC1 shutdown finished
```

**Comment by shypike** [comment]
No, in the distribution packages the version.py file is patched with the actual version number.
The version.py from hit has a generic branch number in it.
I did not change that in 1.0.x to avoid later merging conflicts.
