### ISSUE TITLE
Suggestion: SAB checks system's SSL/TLS setup by connecting to well-known HTTPS site

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#465]
A suggestion:

At startup, let SABnzbd check if a well-known HTTPS site is correctly reachable. If not (as that request results in ```[SSL: CERTIFICATE_VERIFY_FAILED]```), we know the that local system setup is not correct. Possible cause is no/incorrect local certificates. We can then warn the user.

Such incorrect local setups lead to warnings in SABnzbd 1.0.0 RSS setup like ```Server https://nzbindex.com/ uses an untrusted HTTPS certificate``` ... which is not true; the problem is on the local system.

A dummy NNTP over SSL/TLS connection to a well known newsserver *could* also be useful. Although I just checked, and SAB 1.0.0 does **not** complain with such a connection on a incorrectly setup system. I'll investigate further.

Example below. This is a default OpenSuSE:leap docker image ... :-(

```
$ python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> f = urllib.urlopen("https://sabnzbd.org/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 574, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 796, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
>>>
>>> f = urllib.urlopen("https://www.google.com/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 574, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 796, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
>>>
```

As a one-liner:
```
python -c "import urllib;  f = urllib.urlopen('https://sabnzbd.org/');"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 574, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 796, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by sanderjo** [comment]
For the record: the above problem on openSuSE is caused by missing package "ca-certificates-mozilla".


```
bash-4.2# zypper install ca-certificates-mozilla
Retrieving repository 'OSS Update' metadata .............................................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  ca-certificates-mozilla

1 new package to install.
Overall download size: 217.9 KiB. Already cached: 0 B. After the operation, additional 388.3 KiB will be used.
Continue? [y/n/? shows all options] (y):
Retrieving package ca-certificates-mozilla-2.2-5.2.noarch                                                                                                                 (1/1), 217.9 KiB (388.3 KiB unpacked)
Retrieving: ca-certificates-mozilla-2.2-5.2.noarch.rpm ..................................................................................................................................................[done]
Checking for file conflicts: ............................................................................................................................................................................[done]
(1/1) Installing: ca-certificates-mozilla-2.2-5.2 .......................................................................................................................................................[done]
bash-4.2# python -c "import urllib;  f = urllib.urlopen('https://sabnzbd.org/');"
bash-4.2#

```

Afterwards:
```
bash-4.2# zypper search certificates
Retrieving repository 'OSS Update' metadata .............................................................................................................................................................[done]
Loading repository data...
Reading installed packages...

S | Name                    | Summary                                               | Type
--+-------------------------+-------------------------------------------------------+--------
i | ca-certificates         | Utilities for system wide CA certificate installation | package
i | ca-certificates-cacert  | CAcert root certificates                              | package
i | ca-certificates-mozilla | CA certificates for OpenSSL                           | package
bash-4.2#
```

**Comment by Safihre** [comment]
Instead of yet another startup check, can we not add this to installation guides and the Wiki what needs to be present?

**Comment by sanderjo** [comment]
> Instead of yet another startup check, can we not add this to installation guides 
> and the Wiki what needs to be present?

Because from now on users will read the installation guides and the Wiki before installation and in case of problems ... ? ;-)

I prefer systems (applications like SABnzbd, my car, my OS, my computer, my TV, my heating) doing self-analysis and giving possible solutions ("put water into system", "oil system almost empty"), instead of giving no or cryptic error messages or just failing.

**Comment by shypike** [comment]
I agree with Sander that a startup test would be very useful.
A plain connection to https://google.com would be enough to know the status.
A failure means: non-functioning certificate checks.

**Comment by Safihre** [comment]
Let's use sabnzbd.org, since it's backed by Cloudflare. Just like for the ipv6 check :)

**Comment by sanderjo** [comment]
Or create a ```ssl_test_host``` entry in sabnzbd.ini, just like ```ipv6_test_host``` already there. That way, experienced users could change it, or make it empty if they don't want a check.

I suggest a default value of ```sabnzbd.org``` because I expect less user questions than with google.com.
However, a downside of ```sabnzbd.org``` is that it could feel like 'phone home'.

```
$ cat .sabnzbd/sabnzbd.ini | grep -i test_host
ipv6_test_host = test-ipv6.sabnzbd.org
```

**Comment by thezoggy** [comment]
From release version 2.7.9/3.4.3 on, Python by default attempts to perform certificate validation.
https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection

The changes affect all relevant stdlib modules (urllib/urllib2, http, httplib).
Note that the new built-in verification is based on the system-provided certificate database. Opposed to that, the Requests package ships its own certificate bundle.

**Comment by sanderjo** [comment]
@thezoggy I suppose you mean what's described here: http://forums.sabnzbd.org/viewtopic.php?f=1&t=18565 ?

**Comment by sanderjo** [comment]
Sidenote on incorrect SSL setups (client side or server side) and NNTPS connections:

SABnzbd does not complain. So apparently Python's SSL / OpenSSL is "forgiving" and does not check for correct SSL.

Starting with Python 2.7.9, there is ssl.SSLContext / create_default_context. You could set SSL / OpenSSL to check for correct SSL stuff with ```context.verify_mode = ssl.CERT_REQUIRED```.
I think that is not something we must do now.

Ugly code snippet hacked together:
```
import socket, ssl

if hasattr(ssl, 'create_default_context'):
	print "Yes, create_default_context is there"
else:
	print "No, create_default_context is not there"

try:
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    print context.verify_mode
    context.verify_mode = ssl.CERT_REQUIRED
    print context.verify_mode

    context.check_hostname = True
    context.load_default_certs()
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    ssl_sock = context.wrap_socket(s, server_hostname='www.google.com')
    ssl_sock.connect(('www.google.com', 443))
except:
    # old python: < 2.7.9, so no ssl.SSLContext. See https://docs.python.org/2/library/ssl.html#ssl.SSLContext
    pass

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
ssl_sock = ssl.wrap_socket(s)
ssl_sock.connect(('www.google.com', 443))
```

**Comment by Safihre** [comment]
Currently the host we use to get the user's IP4 address is also not configurable and an external service (http://api.ipify.org)
@jeffgeorge Could we also have an service that reports just the plain user's IP running on sabnzbd.org? Something like ```get-ip.sabnzbd.org```

Together with this verification of HTTPS, we could then have all 3 in our own control. IPv6, external IPv4 and HTTPS check all on sabnzbd.org.

**Comment by thezoggy** [comment]
most of the indexers people use prob dont have https setup with anything but a self signed cert.. if they have it at all. also with the issues that also comes with it.. maybe we just default to cert not being verified like python always did before 2.7.9... then let people turn it on if they want/care. as most of the time its just a nzb link being passed. so only api key really being exposed.. which is easily changeable and not like were sharing user sensitive info.  thats why a lot of python apps that use sab have it disabled..

**Comment by Safihre** [comment]
Or at least we should put in the message that they can disable certificate check in the Config.

**Comment by sanderjo** [comment]
@thezoggy  wrote:
> most of the indexers people use prob dont have https setup with anything but a self signed cert.

On what do you base that info? Let's do some analysis:

I wrote a HTTPS/HTTP checker:
```
#!/usr/bin/env python
import sys, urllib2
url = sys.argv[1]
print "Checking ", url,
try:
   f = urllib2.urlopen(url, timeout=5)
   print "Good"
except:
   print "Not good", sys.exc_info()[0], sys.exc_info()[1]
   pass
```
Results (requirement: run on Python 2.7.9+!)
```
./check-this-https.py https://www.nzbindex.com/
Checking  https://www.nzbindex.com/ Good
```
and
```
./check-this-https.py https://www.nzbindex.nl/
Checking  https://www.nzbindex.nl/ Not good <class 'ssl.CertificateError'> hostname 'www.nzbindex.nl' doesn't match either of 'www.nzbindex.com', 'nzbindex.com'
```
OK, that works.

Now let's get a lot of NZB indexer sites ... https://www.reddit.com/r/usenet/wiki/indexers looks like a good choice.

```
lynx --dump 'https://www.reddit.com/r/usenet/wiki/indexers' | grep -i dereferer | awk -F? '{ print $NF }' | sed -e 's/http:/https:/' | sort -u | awk '{ print "./check-this-https.py " $1 }'  | /bin/sh > checker-result2.txt
```

59 sites tested:
29 have correct HTTPS connections
11 have SSL problems with their HTTPS connection
19 have other kinds of problems with the HTTPS connection (like no connection at all)

The correct HTTPS sites, generated with ```cat checker-result2.txt | grep Good | awk '{ print $2 }' ``` :
https://althub.co.za/
https://dognzb.cr
https://drunkenslug.com/
https://dusky.deepcave.net/
https://dutplanet.net/
https://github.com/DariusIII/newznab-tmux
https://github.com/Spotweb/Spotweb
https://headphones.codeshy.com/vip
https://lulunzb.com/
https://newztown.co.za/
https://nzb.cat/
https://nzb.is/
https://nzbfriends.com/
https://nzbgeek.info/
https://nzbindex.in/
https://nzbs.io/
https://nzedb.github.io/nZEDb/
https://omgwtfnzbs.org/
https://pfmonkey.com/
https://usenetor.net/
https://www.binsearch.info/
https://www.gingadaddy.com/
https://www.miatrix.com/
https://www.nzbclub.com/
https://www.nzbfinder.ws/
https://www.nzbindex.com/
https://www.nzbndx.com/
https://www.nzbporn.org/
https://www.oznzb.com/


The wrong HTTPS sites, generated with ```cat checker-result2.txt | grep Not | grep SSL | awk '{ print $2 }' ``` :

https://6box.me/
https://enzybee.com/
https://fanzub.com/
https://fastnzb.info/
https://newseros.com/
https://simplynzbs.com/
https://www.newshost.co.za/
https://www.nzbgrabit.cz/
https://www.nzbhangout.info/
https://www.town.ag/
https://www.usenet-town.com/


NOTE: chromium does not agree on https://6box.me/ and https://simplynzbs.com/ being insecure ... I'll investigate that

**Comment by thezoggy** [comment]
your list should only contain actual indexers and not links to their source code/public facing sites..   so no github, no codeshy. so that removes 4 of the 'correct' sites. then the raw search sites (not typical indexers that sab would be using to hit up for cart/rss - they have no api) somewhat fall in the same boat of not ever going to be an issue for sab...  another 6 removed (also there are dupes)..  so anyways that brings down the good list to 19. anyways for every valid https site i could prob share 5 that arent..

ideally yes we should be security focused in mind, but at the trade off for peoples first exposure to sab being 'it doesnt work' and then move onto another app? not sure the trade off is worth it..

**Comment by thezoggy** [comment]
http://serverfault.com/questions/692110/error-with-python2-as-a-https-client-with-an-nginx-server-and-ssl-certificate-ch

side note:
http://stackoverflow.com/questions/22027418/openssl-python-requests-error-certificate-verify-failed

**Comment by Safihre** [comment]
Since this is new 1.0.0, should we maybe append a link in the message about the certificate being invalid? Example: http://wiki.sabnzbd.org/certificates
Here we can explain that they should contact the indexer about it but that they can also disable certificate validation at their own risk in the specials.
Because otherwise I already see all the Forum/Reddit topics popping up about failing grabs..
To match @sanderjo's idea in #205 :grinning:

**Comment by shypike** [comment]
Can you have a look at this: https://github.com/sabnzbd/sabnzbd/pull/468
It does a reliability check at startup.
For now it uses www.google.com.

**Comment by jeffgeorge** [comment]
Hey guys, so here's a thing which may help:

https://self-test.sabnzbd.org/

1) It's available on https and uses what should be a high quality cert issued by Cloudflare, so it should work as a test host for determining if SSL is working correctly (this ticket)
2) It's available on ipv6 and ipv4, so it should be usable as a replacement for test-ipv6.sabnzbd.org
3) It returns the user's IP address, so it should be usable as a replacement for api.ipify.org
4) It's hosted externally from the main domain, so when we eventually move the main sabnzbd.org domain to Github Pages we won't have to change anything about self-test. For transparency purposes I intend to publish everything hosted on this subdomain, along with "resources" stuff like the little script i use for the Giganews ad in the wizard, and the latest-version script.

Thoughts? Would this host actually work for everything I think it can replace? Anything else it would need to do?

**Comment by thezoggy** [comment]
pretty nifty... just tried it at home/work.. returns v4 or v6 address just fine..

**Comment by sanderjo** [comment]
Result with python 2.7.6:

```
$ python -c "import urllib2;  f = urllib2.urlopen('https://self-test.sabnzbd.org/');"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

```

Result with python 2.7.11:
```
$ ./python -c "import urllib2;  f = urllib2.urlopen('https://self-test.sabnzbd.org/');"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/sander/nzb-index-sites/python/Python-2.7.11/Lib/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jeffgeorge** [comment]
Well that sucks. Can either of you provide theories as to why browsers think the SSL is totally 100% cool but urllib2 freaks out? The 403 is the most confusing one, no idea how you'd be getting a 403.

**Comment by thezoggy** [comment]
python and SSL have had a long history of being a pain in the ass.. you can look at the countless ssl related forum posts / issues lately with sab alone. One of the reasons I've seen people try out sab 1.x and get pissed it doesnt work and move onto other apps.. why I suggested we DONT validate by default but do offer the option to enable it..  since in the grand schemes of things.. https validation is very minor for sab since the url being passed generally are not showing any sensitive info.. 

long story short, httplib/urllib is buggy as shit. its awful. urllib3 is better but still has its quirks.

the cert you are using is `COMODO CA Limited`..  which is one of the newest certs and just wont be included in a lot of CA unless the user updates or we included it (use Requests or something). 6box.me uses it which is why @sanderjo noted that the browser was happy with it but python wasnt.

using my vps box which noted before python would not validate the cert.
if you use other utilities that include updated certs you can see that yes it is fine:

using curl:
```
$ curl https://self-test.sabnzbd.org/ -v
* Hostname was NOT found in DNS cache
*   Trying 104.18.41.215...
* Connected to self-test.sabnzbd.org (104.18.41.215) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni26711.cloudflaressl.com
*        start date: 2016-02-01 00:00:00 GMT
*        expire date: 2016-08-07 23:59:59 GMT
*        subjectAltName: self-test.sabnzbd.org matched
*        issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*        SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: self-test.sabnzbd.org
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< Date: Sat, 13 Feb 2016 22:03:24 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dc106522b7c4bfb56110738ab3eeae71c1455401004; expires=Sun, 12-Feb-17 22:03:24 GMT; path=/; domain=.sabnzbd.org; HttpOnly
< X-Powered-By: PHP/5.3.10-1ubuntu3.14
< Vary: Accept-Encoding
< CF-RAY: 2743d2b2f9712036-DFW
< 
* Connection #0 to host self-test.sabnzbd.org left intact
```

or wget:
```
wget -d -O- https://self-test.sabnzbd.org/
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.15 on linux-gnu.

URI encoding = ‘UTF-8’
--2016-02-13 22:14:00--  https://self-test.sabnzbd.org/
Resolving self-test.sabnzbd.org (self-test.sabnzbd.org)... 104.18.40.215, 104.18.41.215, 2400:cb00:2048:1::6812:28d7, ...
Caching self-test.sabnzbd.org => 104.18.40.215 104.18.41.215 2400:cb00:2048:1::6812:28d7 2400:cb00:2048:1::6812:29d7
Connecting to self-test.sabnzbd.org (self-test.sabnzbd.org)|104.18.40.215|:443... connected.
Created socket 3.
Releasing 0x00000000015aa820 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00000000015aab40
certificate:
  subject: /OU=Domain Control Validated/OU=PositiveSSL Multi-Domain/CN=sni26711.cloudflaressl.com
  issuer:  /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Domain Validation Secure Server CA 2
X509 certificate successfully verified and matches host self-test.sabnzbd.org

---request begin---
GET / HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: self-test.sabnzbd.org
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Sat, 13 Feb 2016 22:14:00 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d03b793a6426551e8df460b6c5942957c1455401640; expires=Sun, 12-Feb-17 22:14:00 GMT; path=/; domain=.sabnzbd.org; HttpOnly
X-Powered-By: PHP/5.3.10-1ubuntu3.14
Vary: Accept-Encoding
CF-RAY: 2743e2401eca03ee-DFW

---response end---
200 OK
cdm: 1 2 3 4 5 6 7 8
Stored cookie sabnzbd.org -1 (ANY) / <permanent> <insecure> [expiry 2017-02-12 22:14:00] __cfduid d03b793a6426551e8df460b6c5942957c1455401640
Registered socket 3 for persistent reuse.
Length: unspecified [text/plain]
Saving to: ‘STDOUT’

    [<=>                                                                                                                                                                                                                                  ] 0           --.-K/s              1    [ <=>                                                                                                                                                                                                                                 ] 14          --.-K/s   in 0s      

2016-02-13 22:14:00 (1.95 MB/s) - written to stdout [14]
```


now my old win7 box that has pretty old python, but latest version of Requests:
```
C:\Python27>python -V
Python 2.7.5

C:\Python27>python -c "import requests; print requests.__version__"
2.9.1

C:\Python27>python -c "import ssl;print ssl.OPENSSL_VERSION;import OpenSSL;print OpenSSL.__version__"
OpenSSL 0.9.8y 5 Feb 2013
0.15.1
```

we see that Requests has an issue validating the cert because of SNI (which is a whole other issue of ssl, and may or maynot be supported depending on the version of ssl or python used):
```
C:\Python27>python -c "import requests; requests.get('https://self-test.sabnzbd.org', verify=True)"
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on
this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html
#snimissingwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately a
nd may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

** Python3 and Python 2.7.9+ include native support for SNI in their SSL modules.
bugs: https://github.com/kennethreitz/requests/issues/749#issuecomment-19187417


now using same version of Requests but on newer python which has SNI we see success:
```
C:\Python27>python -V
Python 2.7.11

C:\Python27>python -c "import requests; print requests.__version__"
2.9.1

C:\Python27>python -c "import ssl;print ssl.OPENSSL_VERSION;import OpenSSL;print OpenSSL.__version__"
OpenSSL 1.0.2d 9 Jul 2015
0.15.1

C:\Python27>python -c "import requests; requests.get('https://self-test.sabnzbd.org', verify=True)"

C:\Python27>python -c "import requests; print requests.get('https://self-test.sabnzbd.org', verify=True)"
<Response [200]>
```

**Comment by thezoggy** [comment]
By default, if you need to use SNI on Python 2.6 or Python 2.7.0-2.7.8, you have to install PyOpenSSL, ndghttpsclient, and pyasn1 separately. Further, to use certifi you have to install it separately. If you know that you want these dependencies when you install urllib3, you can now do:
`pip install urllib3[secure]`

did that on my old python install, and sure enough it allowed Requests to work now (installed support for SNI basically):
```
C:\Python27>python -V
Python 2.7.5

C:\Python27>python -c "import requests; print requests.get('https://self-test.sabnzbd.org', verify=True)"
<Response [200]>
```

**Comment by thezoggy** [comment]
tried self-test.sabnzbd @ https://www.digicert.com/help/

```
DNS resolves self-test.sabnzbd.org to 104.18.40.215

HTTP Server Header: cloudflare-nginx
SSL certificate

Common Name = sni26711.cloudflaressl.com

Subject Alternative Names = sni26711.cloudflaressl.com, *.aglawpa.com, *.aglawpa.mobi, *.aglawpa.net, *.buzzio.com.ar, *.directel.mo, *.dvlfreight.com, *.exactbyte.com, *.flagrasreais.com, *.paginasamarelas.com.mo, *.pro-depot.com, *.sabnzbd.org, *.turningwatersbandb.com, *.wabashavbs.com, aglawpa.com, aglawpa.mobi, aglawpa.net, buzzio.com.ar, directel.mo, dvlfreight.com, exactbyte.com, flagrasreais.com, paginasamarelas.com.mo, pro-depot.com, sabnzbd.org, turningwatersbandb.com, wabashavbs.com

Issuer = COMODO ECC Domain Validation Secure Server CA 2

Serial Number = CDB15CDF71A6F5CD9D130C94F12757E3

SHA1 Thumbprint = E90A4DE19F40807BEEF671DF3EBE8D1BDC11D934

Key Length = 256

Signature algorithm = SHA256 + ECC (excellent)

Secure Renegotiation: Supported
SSL Certificate has not been revoked
OCSP Staple: 	Not Enabled
OCSP Origin: 	Good
CRL Status: 	Good

SSL Certificate expiration

The certificate expires August 7, 2016 (175 days from today)
Certificate Name matches self-test.sabnzbd.org
Subject	sni26711.cloudflaressl.com
Valid from 01/Feb/2016 to 07/Aug/2016
Issuer	COMODO ECC Domain Validation Secure Server CA 2
	 
Subject	COMODO ECC Domain Validation Secure Server CA 2
Valid from 25/Sep/2014 to 24/Sep/2029
Issuer	COMODO ECC Certification Authority
	 
Subject	COMODO ECC Certification Authority
Valid from 30/May/2000 to 30/May/2020
Issuer	AddTrust External CA Root
SSL Certificate is correctly installed

Congratulations! This certificate is correctly installed.
```

**Comment by thezoggy** [comment]
so long story short, 

if users want SSL when connecting to their usenet service providers (e.g. TLSv1.2) they need openssl ( `python -c "import ssl;print ssl.OPENSSL_VERSION"` ) and pyOpenSSL ( `python -c "import OpenSSL;print OpenSSL.__version__"` ).

the version of openssl AND pyOpenSSL will dictate what ssl they can/cant do:

  > TLSv1.1 and TLSv1.2 come with openssl version 1.0.1

  > Support for TLSv1.1 and TLSv1.2 came with pyOpenSSL 0.14

so first step on trying to weed out issues going forward with https verification is getting actual ssl detection sorted..

**Comment by Safihre** [comment]
That's a great summary, makes more things clear for me as an ssl novice. But if we incorporate the check proposed by @shypike of connecting to well known SSL site, this should take away issues for the end users, right? 
In later releases we can then indeed improve the situation and make it more uniform.

**Comment by shypike** [comment]
There's stil the issue of SABnzbd disapproving sites that are accepted by browsers.
I'm following Zoggy's suggestion and will set the default to off.
We need more time for this.

**Comment by thezoggy** [comment]
I would also suggest adding a one time fix of disabling httpscheck for python 2.7.8 and older to fix those beta users config for the future (2.7.9 is when python turned on the verification.. Thus those users would get a surprise when they later upgrade python and didn't realize that sab has that setting enabled when now its default is off). 

-----Original Message-----

**Comment by Safihre** [comment]
@jeffgeorge So it turns out that https://self-test.sabnzbd.org failed because Python as a navigator is blocked by the server: http://stackoverflow.com/questions/3336549/pythons-urllib2-why-do-i-get-error-403-when-i-urlopen-a-wikipedia-page
Using this it works perfect:
```
req = urllib2.Request("https://self-test.sabnzbd.org/", headers={"User-Agent" : "SABnzbd"}) 
con = urllib2.urlopen( req )
print con.read()
```
Returns my IP over HTTPS.

**Comment by Safihre** [comment]
Judging from that StackOverflow page there's more servers blocking Python as a bot or might start doing that in the future.
So again I want to vote in favor of introducing ```self_test_host``` https://self-test.sabnzbd.org for all 3 tests (HTTPS, IPv6 and IP-address), since we have control over it :blush:

**Comment by jeffgeorge** [comment]
Oh, duh, I got a similar thing when I was trying to access the Github API from PHP for our latest-version script.

So @sanderjo does setting a User Agent fix *all* versions of Python you have available for testing?

**Comment by sanderjo** [comment]
Hi @jeffgeorge 

@shypike wrote "I will set the default to off. We need more time for this."

So ... my interpretation is to first release 1.0.0, and then investigate thus further.

@shypike Am I correct about this?

**Comment by thezoggy** [comment]
yes, but we could/should prob just port all the check urls over to the one.. since its much easier to fix things now before 1.0 is final. migrate users over/set it for new users..  now if shy wants to default the httpscheck of off or not, thats a different issue.

**Comment by shypike** [comment]
@sanderjo Yes

**Comment by Safihre** [comment]
@thezoggy 
Reading your nice explanation above again after our SSL update (basically forcing Python 2.7.9 for SSL support), am I correct that we can now use https://self-test.sabnzbd.org to test for correct certificate-validation on the host using ```urllib2```?
https://self-test.sabnzbd.org does use a certificate from ```COMODO CA Limited```, this could give false-negatives?

We had some reports on the forums about QNAP users that were on the develop branch and for them certificate validation failed, probably because of bad certificate store on the devices.

**Comment by thezoggy** [comment]
COMODO certs is the latest CA to be added..  depending on how up to date their system is..  it may or maynot be validated against... hence why you see python complain about a site but a browser is fine with it..  

i do believe the user can update `ca-certificates` to fix.. for windows thats a different story
