### ISSUE TITLE
[FR] Drag-and-drop nzb files

### ISSUE THREAD

**Issue by sestolk** [sabnzbd/sabnzbd#467]
Is it possible to show the progress of the upload when you drop a nzb file into the gui. Sometimes it takes a while for it to complete because the nzb file is > 5mb.

**Comment by shypike** [comment]
It isn't so much the time needed for upload, but for SABnzbd to process the file.
It is rather problematic to give feedback on the the latter.

**Comment by sestolk** [comment]
Ow I see, thats a pity :(. Thanks for the reply tho

**Comment by Safihre** [comment]
On a side note to anybody who's reading it: I do want to add more clear visual queues (small notification box) for things like uploads and deleting orphaned jobs. Sometimes these things take time but there's not any visual queue, sometimes the interface just freezes while sabnzbd in the back is doing its thing. 
So more visual info is coming in some future release ;)
