### ISSUE TITLE
[0.8.0Beta6] Series sorting + unpacking only in lower case.

### ISSUE THREAD

**Issue by zion2k** [sabnzbd/sabnzbd#470]
Hi, after updating to 0.8 I have the problem that new downloads get unpacked in lower case dirs.

0.7.x: Series Name\Series.S01E01.BlaBlaBla\filename.ext
0.8.0: series name\Series.S01E01.BlaBlaBla\filename.ext

Accessing this dirs by SMB share I only can see the content of the lower case dirs.

Do I miss new switches or is it really a bug?

**Comment by thezoggy** [comment]
are you telling sabnzbd to rename the files? if so, what is the naming scheme/pattern your using. (because yes you can explicitly say to use only lower case)

**Comment by zion2k** [comment]
Didn't change the pattern.   --->   %sn/Season %0s/%dn
I just saw that there is a new option "case-adjusted". What does this mean? I didn't find an explanation.

**Comment by shypike** [comment]
"case-adjusted" means that casing of titles is adjusted, like this:
"my SHOW" ==> "My Show".
It's not a new option.
You should be using %sn.

BTW: you can test the result by adding a title to the "Test Data" section.
"The SHOW S01E04 Hey man" ==> "The Show/The SHOW S01E04 Hey man".
You see that the first part is case-adjusted.
I'll do a little test later, you never know, there might be a bug.

The problem with a Linux server running SMB is that for the server "show" and "Show" are two different folders, while not for Windows. Therefore the server will pick just one of the two to show to the Windows client.
Once you have a double folder like this, you can only remove by logging into the server itself (not from Windows).

**Comment by shypike** [comment]
I tested with this expression:
 %sn/Season %s/%sn %0s%0e - %en.%ext
Works fine, the %sn parts are case-adjusted.
If you use %sN they will not be.

SABnzbd has a bit of an issue with your Sort expression.
It translates to something like:
The Show/Season 09/the show S09E01 Hey/the show S09E01.avi
You'd better use my Sort expression and I'll check later what's going on with yours.

**Comment by shypike** [comment]
Your Sort expression %sn/Season %0s/%dn isn't completely correct.
It should be %sn/Season %0s/%dn.%ext
Otherwise SABnzbd will assume that you specified a folder path instead of a file path, that's why it creates an extra folder level, without case-adjusting it.

Not quite intuitive, but technically correct. The %ext at the end is really needed, because %dn is the original job name without the ".nzb" extension.
