### ISSUE TITLE
sab 1.0.0RC1 - invalid nzb due to invalid token

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#482]
see the error:

`2016-02-17 22:24:52,144::WARNING::[nzbstuff:721] Invalid NZB file <removed>.nzb, skipping (reason=not well-formed (invalid token), line=465)`

sent you nzb via email
the nzb actually gets processed just fine and the download completes+extracts just fine.

looking at the code:
https://github.com/sabnzbd/sabnzbd/blob/00de72b127bb1473f891063c0f95ca9bcd99ab41/sabnzbd/nzbstuff.py#L721

looking at the nzb line number reported.. i do not see anything wrong with the file...

**Comment by shypike** [comment]
The NZB you sent me is fine. No error/warning on Windows 10 or OSX.
The log message would be coming from Python's XML parser, but I don't see it.

**Comment by shypike** [comment]
Exactly which Python version are you using?

**Comment by thezoggy** [comment]
```
C:\Users\zoggy>python -V
Python 2.7.5
```
