### ISSUE TITLE
Job Timed Release aka Quarantine

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#483]
Feature suggestion:

I suggest Sab should have a quarantine feature, which would hold all or some jobs in a paused state for a user determined period of time before releasing them for download.

This could be defined globally or on a per category/RSS feed basis.

This would allow users with usenet server that have slower propagation to avoid failed jobs on recent posts.
It could also be interesting for other scenarios.

**Comment by sanderjo** [comment]
FWIW: mentioned here:

http://forums.sabnzbd.org/viewtopic.php?f=11&t=20238
https://forums.sabnzbd.org/viewtopic.php?f=3&t=18224

**Comment by Safihre** [comment]
A 'Minimal post age'  (so pause until post is that age at least) would not suffice? You would suggest to delay all posts?

**Comment by Cpuroast** [comment]
@sanderjo If you define the delay as a category or rss feed attribute, then it would only delay jobs from those sources.

**Comment by Cpuroast** [comment]
Any reason the commit was reverted and yet the issue remains closed?

**Comment by Safihre** [comment]
No this can stay closed, the commit was done later under a different name without the # reference to this issue. This feature is in develop branch. 

 I think @Cpuroast also saw that and deleted his post ;)

**Comment by Cpuroast** [comment]
I did nuke my post, but the the new commit should be referenced in this issue for future...reference :)

**Comment by shypike** [comment]
Implemented here: adde58101b0996d9d9c7ecaeff3557023dcc3da5
