### ISSUE TITLE
Unable to launch 1.0.0RC1

### ISSUE THREAD

**Issue by amgreenwalt** [sabnzbd/sabnzbd#488]
I have tried upgrading from 0.7.20 to 1.0.0RC1 but I keep getting an error when I try to launch the application.

"The application has failed to start because its side-by-side configuration is incorrect."

I have tried completely removing Sabnzbd from my computer, rebooting, download from https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.0RC1 and install but still getting the same error.  I am running windows server 2008r2.  Has anyone else encountered this problem?  I guess I will re-install  0.7.20 for now.

**Comment by thezoggy** [comment]
googling for what 'side-by-side configuration is' looks to be a windows error talking about runtime packages missing.. googling with regards to other py2exe compiled apps refer to you needing to install "MS Visual C++ 2008 Redistributable Package (x86)"

**Comment by shypike** [comment]
The easiest way to fix this is to install Microsoft's Python compiler support package.
https://www.microsoft.com/en-us/download/details.aspx?id=44266
It contains the right run-time libraries.

**Comment by amgreenwalt** [comment]
@thezoggy, I had MS Visual C++ 2015 Redistributable Package (x86) installed originally.  
After installing the 2008 package I was able to install and launch 1.0.0RC1 and it is currently running.  Perhaps that is something that can be fixed in the upcoming versions?

**Comment by thezoggy** [comment]
We cant really "fix" an issue of your is missing something that every other ns one has... All we can do is put a note for ms server 2008 users to run Ms update/install it manually if your going to try running exe files compiled with visual studio 

-----Original Message-----

**Comment by shypike** [comment]
@thezoggy I have tried that a year ago, it wasn't a success.

**Comment by beneficadoramocaba** [comment]
I just wanted to add that **you must install the x86 version** of the VC++ 2008 package, even if you are running the 64-bit version of Windows.

The link above (Ableton discussion board) contains links to both versions, and I instinctively chose x64 to match my system, which didn't work. The Python package shypike referred to didn't fix the problem either.

For future-users searching this, I'll also include the Event Log text, since that's what the "side by side" error message advises you to check:

> _Activation context generation failed for "C:\Program Files (x86)\SABnzbd\SABnzbd.exe". Dependent Assembly Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis._

**Comment by thezoggy** [comment]
@beneficadoramocaba correct, as the builds are using 32bit python...
`2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]`
