### ISSUE TITLE
sab 1.0.0RC2 -- glitter - parsing &

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#489]
noticed that in my queue it shows: 
`Law.&amp;.Order.Special.Victims.Unit.S17E16.Proper.720p.HDTV.x264-KILLERS `

click the drop down to show the details and it changes the name to
`Law.&.Order.Special.Victims.Unit.S17E16.Proper.720p.HDTV.x264-KILLERS`

refresh the page, it goes back to `&amp;`

**Comment by Safihre** [comment]
Could you send me the NZB? I tried a couple of them with ```&``` but I couldn't replicate this. safihre@sabnzbd.org

**Comment by thezoggy** [comment]
sent

**Comment by Safihre** [comment]
Fixed now in #493!

**Comment by thezoggy** [comment]
Sweet thanks 

-----Original Message-----
