### ISSUE TITLE
Git workflow for SABnzbd

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#491]
Simplified "GitFlow".
Basically:
- "master" contains only stable releases (which have been merged to master)
- "develop" is the target for integration
- "release/1.0.x" is a maintenance branch for 1.0.x: 1.0.0 -> 1.0.1 -> 1.0.2
- "release/1.1.x" is a maintenance branch for 1.0.x: 1.1.0 -> 1.1.1 -> 1.1.2
- "feature/my_feature" is a temporary feature branch
- "hotfix/my_hotfix is a temporary branch for bugfix(es)

Condtions:
- Merging of a stable release into "master" will be simple: the release branch is always right.
- "master" is not merged back to "develop"
- "develop" is not re-based on "master".
- Release branches branch from "develop" only.
- Bugfixes specifically for a release branch are done there (because they are specific, they're not cherry-picked to "develop").
- Bugfixes done on "develop" may be cherry-picked to a release branch.
- We will not release a 1.0.2 if a 1.1.0 has already been released.

Comments are welcome.
I'm not sure about the need for a "master" to contain all stable releases, but it may make life simpler for users. It's always safe to use the most recent "master".
Due to the lack of comprehensive automated testing, one cannot assume "develop" is always safe.

**Comment by bdewater** [comment]
I have no beef in this as a user, but what's the need for master to be stable? And how/when do you promote develop to master? I'd recommend to keep it simple and point users to release branches if they want stability.

https://about.gitlab.com/2014/09/29/gitlab-flow/ might be an interesting read, especially the 'release branches' variant.

**Comment by shypike** [comment]
Closed with commit e10ca1c852ab3be7cc86b0c502cac0402a1b466b
