### ISSUE TITLE
Disable IPv6 support by default

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#492]
Given the number of complaints about the failure of SABnzbd to attach itself to the IPv6 address of the computer, why not disable this by default?
We now have an obscure --no_ipv6 command line option to solve issues with it.
Would it not be better to disable it by default and have a "special" to enable it for people who actually need it?
SABnzbd now tries to bind itself to both ::1 and 127.0.0.1 because "localhost" is an ambiguous address.
Since we now default to 127.0.0.1, ::1 issues have mostly gone.
But we keep getting complaints from people who have to use 0.0.0.0 and get IPv6 trouble for "free".

**Comment by thezoggy** [comment]
while v6 is the way of the future.. sadly its far off for consumers.. especially if they wanted to do full v6 not some 4to6 or 6to4 solution. then the whole wan vs lan battle with it.. lots of people sadly run os that dont fully support it, or have browsers that have it disabled/issues.. then their routers lack the ability to handle it.. etc etc etc :( now does python play well with v6 (httplib/urllib/openssl/etc)? what about the user having v6 lan but v4 wan or vice versa.. point being, +1 for the change

**Comment by Safihre** [comment]
:+1:

**Comment by sanderjo** [comment]
Do you really mean "Disable IPv6 support by default", or do you mean "Disable IPv6 WebGUI listening support by default"?

**Comment by shypike** [comment]
The latter.
