### ISSUE TITLE
Windows 10, insufficient priveleges

### ISSUE THREAD

**Issue by eddively** [sabnzbd/sabnzbd#495]
When running the setup exe, even with "Run as Admin", the installer kicks back an error regarding privileges and suggests installing within a User folder instead. I have previously installed SAB at the System level without issues.

**Comment by Safihre** [comment]
First shutdown Sab before updating. This seems to cause this error in others.

**Comment by shypike** [comment]
I fixed the detection of a running SABnzbd instance in the Windows installer.
Fix is in 1.0.0RC4

**Comment by Slivicon** [comment]
Would it be possible to have the installer check if sab is running and shut it down or prompt to shut it down as an enhancement request?
