### ISSUE TITLE
1.0.0RC4 -- launch

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#500]
RC2 and older, when sab launched it took me to `localhost`, now with RC4 it does `127.0.0.1`.
was this a planned change? (localhost still works fine/resolves)

**Comment by sanderjo** [comment]
probably https://github.com/sabnzbd/sabnzbd/blob/1cbff28f67e2818540757e55133207e5fe0d2c6a/sabnzbd/panic.py#L269
as an effect of https://github.com/sabnzbd/sabnzbd/issues/492 ... in which you commented too.

**Comment by thezoggy** [comment]
yeah, im all for the no v6 thing and change how we bind, just wasnt expecting serving up a different url on launch. thus pw manager wasnt happy.

**Comment by sanderjo** [comment]
so ... can you close this issue?

**Comment by shypike** [comment]
I force 127.0.0.1 because when you don't bind to ::1, localhost may still resolve to ::1 first. If you want to keep localhost, enable ipv6_hosting.
