### ISSUE TITLE
sab 1.1.x -- qrcode

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#507]
right now we pass the apikey to google's api to generate qrcodes.. we could easily just keep this inhouse and do it in javascript or python

* https://larsjung.de/jquery-qrcode/
which uses: https://github.com/kazuhikoarase/qrcode-generator

**Comment by Safihre** [comment]
That was easy to implement:
8444155ba82ff1b746a00849ad99bb6cb1efe613
Will put it into a next pull request!

**Comment by thezoggy** [comment]
sweet thanks!
