### ISSUE TITLE
Stop+Retry forgets job postprocessing setting

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#509]
The joys of automation made me go a bit over the api limit of some indexer recently, so I ended with a bunch of jobs just trying to fetch their nzb files in vain. Decided to set them aside by setting priority to "stop", then used "retry" the next day to re-add them to the queue.

All that worked fine, except the jobs all had their postprocessing set to "download" only, rather than the standard setting for their category of "delete". All the other job settings (category, script, and priority) were retained as they should be.

1.0.0rc5 with glitter; looking at the history I suspect similar behaviour already existed in rc1.

**Comment by Safihre** [comment]
Tried to reproduce, but with a regular NZB instead of URL, the settings are preserved correctly. So it only happens when retrying an URL?

**Comment by jcfp** [comment]
All jobs I noticed this issue with were in the "trying to fetch from <indexer url>" phase, otherwise I would have simply paused them rather than use the stop priority (which prevents any further fetching attempts).

Just tried with a job that was fully queued (i.e., nzb already fetched) and it preserved all settings indeed just as you found. So I guess it's indeed limited to the stop-while-still-fetching scenario.

**Comment by shypike** [comment]
Any idea whether 0.7.20 does the same?

**Comment by Safihre** [comment]
And it could also be a Glitter issue, due to #464 is sometimes behaves odd. So if you have a chance to test it again, maybe also try in Plush (and Glitter not open anywhere).

**Comment by jcfp** [comment]
Same result with plush in 1.0.0rc5, all job settings retained except postproc.

As for 0.7.20, reproducing the issue wasn't possible because sab immediately discards the nzb as "empty" and the job thus never enters into a state of repeatedly "trying to fetch..." in the queue.

**Comment by shypike** [comment]
OK, I'll examine. Not sure whether to postpone 1.0.0 for this.

**Comment by jcfp** [comment]
IMHO not worth postponing over this: the whole reason for using this stop+retry routine is already an exceptional situation. Retrying jobs already requires manual intervention anyway, so once you realise what's going on it's quick and easy to fix the job settings there and then.

**Comment by shypike** [comment]
This is not an intended use case. URL-fetches can not normally get priority Stop. You can however use the "multi-ops" method.
I'll see if there's an easy fix.

**Comment by shypike** [comment]
There's an error in saving the PP flag to the database, this can be fixed.
Priority isn't saved to the database, so that will indeed be lost. Future enhancement.
