### ISSUE TITLE
Scripts Tag/Name Stays On GUI

### ISSUE THREAD

**Issue by Geyup** [sabnzbd/sabnzbd#517]
Hello,

I'm not sure if this has been reported.

My Specs:

Linux
Firefox 38.7.1 ESR
SABnzbd 1.0.0
Python Version: 2.7.5 (default, May 29 2013, 02:28:51) [GCC 4.8.0]
OpenSSL: OpenSSL 1.0.1s 1 Mar 2016 [t1, v23, v3, v2]
pyOpenSSL: 0.13.1 

I'm not sure what the section is called with the drop down next to the trash can on the far right.

When I drop the window down and go down to the Scripts section, as the name Scripts pops out and then I close the window, the Scripts Tag/Name stays stuck on the GUI and doesn't get removed when the window closes.

See this screen shot to see what I am talking about;

![sabnzbd](https://cloud.githubusercontent.com/assets/13072581/13940914/224d1370-ef86-11e5-9083-5b7bb2adc929.jpg)

**Comment by Safihre** [comment]
I know it might stay when you close it, but doesn't it disappear after you move the cursor again?

**Comment by Geyup** [comment]
No from moving the mouse, I have to click on something....

It's a bug though...

**Comment by Safihre** [comment]
I cannot reproduce the issue, but I am also on Firefox 45.0 on Ubuntu so that might be the difference.
But I added an extra force hide of the tooltips just in case:
https://github.com/Safihre/sabnzbd/commit/0f744f7d66455c5e3b51f7d185fab66824b8f4f7

Don't know when it will be in one of the releases though.. Might be 1.0.1 or 1.1.0.

**Comment by Geyup** [comment]
Sounds good, I'll keep an eye out for the next release...

**Comment by Safihre** [comment]
Can close this one, fixed in #519 to the best of our abilities.

**Comment by Geyup** [comment]
@Safihre so the GUI will show a 'Downloads' section when downloading?

**Comment by Geyup** [comment]
Thanks, keep up the great work!

**Comment by Safihre** [comment]
No this is your other issue, about the tooltip staying on top of the gui when you close one of the windows ;)

**Comment by Geyup** [comment]
ok
