### ISSUE TITLE
Modernize SABnzbd's Branding & Logos

### ISSUE THREAD

**Issue by jeffgeorge** [sabnzbd/sabnzbd#521]
(Picking up where we left off in #408, around [here](https://github.com/sabnzbd/sabnzbd/issues/408#issuecomment-180875625).)

Goals:
- [x] New Arrow icon to use, with an original flat design
- [x] New Overall logo (so, arrow icon + type)
- [x] Vector assets for use on a new SABnzbd.org homepage and the Glitter theme
- [ ] Primary (orange) .ico assets to use throughout the application itself (
- [ ] Secondary (green) .ico assets to use for .nzb file associations

I've been working with a friend to iterate on where we got in the previous issue, and have ended up with this for the first two items:

https://resources.sabnzbd.org/logo/sabnzbd_arrow_sharp_3.ai

![sabnzbd_logo_composited](https://cloud.githubusercontent.com/assets/806112/14032006/594bd610-f1e6-11e5-81e2-a648deaf059e.png)

Some notes:
- @Safihre recommended in the previous thread to only use "sharp" corners in the strokes. Turns out that's basically impossible in Photoshop. If you do an outside stroke it's always rounded. If you do an inside stroke it's sharp, but then you're eating into the inside dimensions, so the "stripes" going to the upper corners no longer go straight to the corner. Someone may be able to fix this in Illustrator or some other vector-based tool that can read .ai's, but I'm both terrible with Illustrator and don't have access to a copy.
- I went back and forth on colors (various [Material colors](https://www.google.com/design/spec/style/color.html#color-color-palette) out of the "amber" segment) and number of segments (3 vs 5) multiple times. I landed on Amber 400 (#FFCA28) / Amber 600 (#FFB300), and 3 segments. I'm totally open to fiddling with exactly which Ambers to use, but think it should stay at 3 segments.

Next Steps:
- **Feedback**! Please provide it! Please tell me why this sucks!
- Once we like something, drag in someone competent with Illustrator to composite some new svgs with strokes and such
- Once we've got the Amber version we like, we need to make a green version
- Once we've done all that, we get to compile new icons, which is the worst and most thankless job in the world
- Then, finally, after all that, we can open a PR to implement all these new icons throughout Glitter and the file build process

**Comment by shypike** [comment]
Looks very nice.

**Comment by Safihre** [comment]
Yes looks good! :+1: 
Those non-rounded strokes could be achieved by adding a black arrow behind the front arrow, but actually because the text and its strokes is also rounded, it looks good like this!

So we cannot just 'Save as SVG' and use that? :smiley:

**Comment by thezoggy** [comment]
'Save as SVG' while would 'work' would not produce a clean svg.. as a lot of crap gets added. it'd be like using office and say save page as html.. it works in a pinch but no sane person would want to use this publicly :)

**Comment by jeffgeorge** [comment]
Saving as SVG is also a huge pain in CS6. It's apparently slightly less awful in Creative Cloud, but instead I've just started a trial of a nice Illustrator alternative called "Affinity Illustrator", which has native exporting to SVG.

But before we get into that, I'd like some feedback on options for the actual application icon and nzb filetype association icons:

![sabnzbd_iconset](https://cloud.githubusercontent.com/assets/806112/14053280/748505c6-f2a6-11e5-8028-874165f9c959.png)

For reference, here are the old filetype association icons:

![sab2_128](http://sabnzbd.org/icon/sab2_128.png) ![nzb_128](http://sabnzbd.org/icon/nzb/nzb_128.png)

I'm leaning towards either 1 or 2, depending on if we want it spelled out or just the first letter.

**Comment by jeffgeorge** [comment]
Also, here's the full logo re-comped in Affinity:

![sabnzbd_logo_composited_2](https://cloud.githubusercontent.com/assets/806112/14053447/a4e2386e-f2a7-11e5-85e2-ab48c52a427f.png)

The "s" is now actually properly centered in the arrow.

Re: Strokes, Affinity lets you have sharp strokes on text (!!!), but doesn't appear to give the same control to arbitrary shapes. Lame.

**Comment by thezoggy** [comment]
can you do a #5 where it is the new arrow but sab/nzb on the bottom like before with less kerning so the letters border touch again/stuff is filled

**Comment by Safihre** [comment]
3 looks really great, but also @thezoggy's suggestions of top/bottom could be interesting!

**Comment by jeffgeorge** [comment]
@thezoggy -- Your recommendations for Option 5:

- less kerning
- lower text 
- slightly larger text

![sabnzbd_iconset_5](https://cloud.githubusercontent.com/assets/806112/14068726/c6324694-f45a-11e5-8176-b0c079ecc2b9.png)

And 5b, same thing, but "filled in", like the old icons, quick and dirty.

![sabnzbd_iconset_5b](https://cloud.githubusercontent.com/assets/806112/14068830/54cf6fec-f45d-11e5-9e07-954d706115e8.png)

I sort of like the normal 5's. Here's them rendered out at various "normal" icon resolutions:

![sabnzbd_iconset_5_sizes](https://cloud.githubusercontent.com/assets/806112/14068990/c4228fca-f460-11e5-8d72-b30fd7e7af84.png)

....which makes me think i need to seriously beef up the amount of stroke to keep it legible. I'll tweak that tomorrow.

I don't think I'm following you for your other recommendations around moving the text up significantly. Care to mock something up for me? Just putting a baseline on the "clean" arrow should give me enough direction.

**Comment by jeffgeorge** [comment]
Doubling the stroke width looks better, but now it's uneven between the letters and the stroke. Here it is just doubled, and then doubled and with the kerning set back to normal.

![sabnzbd_iconset_5_cs](https://cloud.githubusercontent.com/assets/806112/14069220/24e39e2c-f465-11e5-8ec8-4de660f3faf5.png)

All options look pretty terrible rasterized down to 16px but I swear it's still legible vectorized.

I think this set back to normal kerning looks best out of all the ones I've presented.

**Comment by Safihre** [comment]
Looking good! How does this extra stroke work out for the logo + whole name? Indeed for the 16px version your last result looks best. 
Maybe indeed the original stroke was too thin, but maybe this one is too thick to be used everywhere? Starting to look like the original ;)

**Comment by jeffgeorge** [comment]
I just spent the past few hours wrestling with vector graphics and I think I've got it. I had to re-do everything from scratch since some imported image parts weren't actually vectors despite looking and working like vectors. Affinity Designer is also apparently pretty weird about effect layers and vectors. Apply a stroke to a vector object via an Effect Layer? Whoops everything's automatically rasterized. Apply a stroke via the native object? *Now* it stays as a vector. 

I've got it sorted now, and the result is pretty amazing and totally worth it. The "big" main logo I'll be using for the site is a tenth of the size of the one we have right now, a mere 632 _bytes_ gzipped.

Here's a zip of raw and optimized SVGs, compressed with the wonderful tool [SVGOMG](https://jakearchibald.github.io/svgomg/):

[sabnzbd_assets_20160329.zip](https://github.com/sabnzbd/sabnzbd/files/192947/sabnzbd_assets_20160329.zip)

Sadly, Github Issues don't let you attach or render raw SVGs, so here are rendered comps of the logo and various resolutions of the two icons.

![sabnzbd_full_logo_v7](https://cloud.githubusercontent.com/assets/806112/14099513/237f7052-f554-11e5-91f4-a2a32b5a331c.png)
![sabnzbd_contact_sheet_v7](https://cloud.githubusercontent.com/assets/806112/14099514/26d37604-f554-11e5-86a5-e1758649c5d8.png)

(Again, the smaller icon views look pretty blurry rasterized. It's perfect as a vector.)

If everybody's happy with this iteration I'll move on to figuring out how exactly you make vector-based application icons that work cross-platform in 2016.

**Comment by Safihre** [comment]
Great you managed to get all the vector stuff working :)
Would still suggest to use some less stroke, especially on the big-logo it feels like the S takes over the whole logo behind it. Compared for example to the old big-logo I like the reduction in kerning, just seems like the logo is barely visible behind the text. 
Or maybe just increase the logo part of the big-logo?
![image](https://cloud.githubusercontent.com/assets/5703454/14106097/75115394-f5af-11e5-861c-b2106854d097.png)

**Comment by Safihre** [comment]
Was testing how it looks in Glitter, but it seems the text in the big-logo maybe also needs a tiny nudge down in the logo?
![image](https://cloud.githubusercontent.com/assets/5703454/14110392/80df0718-f5c6-11e5-8fd5-07a80805f440.png)

**Comment by jeffgeorge** [comment]
Well, the text isn't centered, it's aligned so that the top of the ascenders in b's and d's align with the top of the arrow.

I'll fiddle with dimensions further tonight to see if i can reasonably cut down the amount of stroke on the full size, and also adjust the size of the arrow vs the size of the text.

**Comment by Safihre** [comment]
Maybe it's also nicer actually with the smaller logo. Looks especially good on Glitter Night:
![image](https://cloud.githubusercontent.com/assets/5703454/14110531/1e6f99b6-f5c7-11e5-98aa-9a508ea88ccb.png)

**Comment by Safihre** [comment]
Or even more simplistic:
![image](https://cloud.githubusercontent.com/assets/5703454/14110631/9010ef34-f5c7-11e5-9696-8815e92c0b13.png)

**Comment by Safihre** [comment]
Have had the new logos in place now for a bit to see the 'feel', I really think we should make a version where the SABnzbd text is lower in the arrow. See here for the effect also on the Config pages:
![image](https://cloud.githubusercontent.com/assets/5703454/14135182/56ad2b32-f65c-11e5-9ee6-52a866921e37.png)

Have now had this logo for a while and it's really growing on me!
![image](https://cloud.githubusercontent.com/assets/5703454/14135210/7e16f2ac-f65c-11e5-82c2-5a4751555c6a.png)
![image](https://cloud.githubusercontent.com/assets/5703454/14135228/a4c82fba-f65c-11e5-92d2-8d97c31ace5a.png)

**Comment by thezoggy** [comment]
upgraded to latest dev and i see the new icon..  sure seems like the top part of the arrow is a little wider than before and with so much stroke the dark version looks tiny (only see the tip on the bottom)

**Comment by jeffgeorge** [comment]
Fiddled with the "full" logo a bit. Lighter stroke, smaller text, and pushed the text down a bit. The midline isn't quite centered with the arrow, but it's closer than having the ascenders match up with the top of the arrow. I also added one great big black rectangle behind the text so there aren't any "dips" in the stroke between glyphs.

![sabnzbd_full_logo_v8](https://cloud.githubusercontent.com/assets/806112/14237761/3dd6166c-f9f6-11e5-92f8-9c47013a278b.png)

Here it is in-situ:
<img width="368" alt="screen shot 2016-04-03 at 11 41 03 pm" src="https://cloud.githubusercontent.com/assets/806112/14237754/333bf9d8-f9f6-11e5-991c-302ea7c5efad.png">

If this is good I'll see about addressing @thezoggy's comments re: the small icon. I intentionally pushed the "sab" text there far down to make it more in line with the old icon, since it sounded like we generally wanted positioning closer to the old icons. I'll poke at it tomorrow night, but generally I think we're getting very close to final stuff.

**Comment by Safihre** [comment]
This seems good to me! I only used the smaller logo in Glitter (which was probably only supposed to be used as a shortcut icon) because the big one didn't look so good yet, but maybe now we just need to smaller logo to look good at 16x16 etc, so that should probably be the focus for that! 

But on other hand, I do need a smaller logo that looks like the big logo for the mobile Glitter and the Config (for languages in which all the menu options don't fit in the Config menu otherwise). So if you could make one with the same stroke etc but not the whole text, that would be nice ;)

**Comment by Safihre** [comment]
Any luck with the last improvements to the big logo? :)

**Comment by jeffgeorge** [comment]
Ok, here we go, I think these might be the finals:

![sabnzbd_full_logo_v8](https://cloud.githubusercontent.com/assets/806112/14413840/2557dc2a-ff54-11e5-85e2-4579b1651dc3.png)

![sabnzbd_contact_sheet_v8](https://cloud.githubusercontent.com/assets/806112/14413843/2c91d89c-ff54-11e5-8439-036c6c95f09d.png)

(as usual, I promise the tiny sizes look fine if they're SVGs.)

And here are the associated svgs, plus a "clean" version of the orange arrow, plus the raw .afdesign files. All SVGs have been run through the most aggressive optimization I could get from [SVGOMG](https://jakearchibald.github.io/svgomg/), so they should be ready to use.

[sabnzbd_assets_20160410.zip](https://github.com/sabnzbd/sabnzbd/files/212076/sabnzbd_assets_20160410.zip)

For the "icon" types, I normalized the stroke size to match the arrow, and based on @thezoggy's feedback I nudged the sab/nzb text up a few percent so it's centered vertically within the lower part of the arrow.

If we all like where I've ended up, then @Safihre can get to implementing it throughout Glitter (preferably with a reasonably sized .png fallback), and I'll start figuring out how you make cross-platform vector icons these days for use as the actual application icons.

Note on Fallback Support: Do we care about browsers that don't support SVG? According to [Can I Use...](http://caniuse.com/#feat=svg), SVG is supported pretty much everywhere but IE8 and below. We can support them with a [PNG fallback](https://css-tricks.com/a-complete-guide-to-svg-fallbacks/#fallback-svg-as-img-image), but I don't know if we care or not.

**Comment by shypike** [comment]
Forget IE8 and below, Microsoft did.

**Comment by Safihre** [comment]
Glitter doesn't support IE8 and the Config might work, but not too well. Since we didn't get any complaints since 1.0.0, dropping IE8 hasn't been a bad choice!
@jeffgeorge something is wrong with those files, this is how they render in Chrome/IE for me:
![image](https://cloud.githubusercontent.com/assets/5703454/14420482/914dbb48-ffcc-11e5-9f2c-2ea26e2c1389.png)

**Comment by jeffgeorge** [comment]
Bah, I need to convert to curves and re export. I'll fix that shortly.

On Monday, April 11, 2016, Safihre <notifications@github.com> wrote:

> Glitter doesn't support IE8 and the Config might work, but not too well.
> Since we didn't get any complaints since 1.0.0, dropping IE8 hasn't been a
> bad choice!
> @jeffgeorge <https://github.com/jeffgeorge> something is wrong with those
> files, this is how they render in Chrome/IE for me:
> [image: image]
> <https://cloud.githubusercontent.com/assets/5703454/14420482/914dbb48-ffcc-11e5-9f2c-2ea26e2c1389.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sabnzbd/sabnzbd/issues/521#issuecomment-208214787>
>


-- 
--
Jeff George            < jeff.george@gmail.com >

**Comment by jeffgeorge** [comment]
Sorry about that, here's a fixed set of optimized SVGs:

[sabnzbd_assets_20160411.zip](https://github.com/sabnzbd/sabnzbd/files/213319/sabnzbd_assets_20160411.zip)

**Comment by Safihre** [comment]
I think the smaller logo is best for both Glitter and Config, because the wide one is just never rendered properly. There is no height in that range that gives a nice round with, always a float. And you can see that in the way Chrome (at least on Windows) renders it, it just feels off:
![image](https://cloud.githubusercontent.com/assets/5703454/14438786/232814d6-0028-11e6-905a-66f473a1af2e.png)
While the square one fits in just perfectly:
![image](https://cloud.githubusercontent.com/assets/5703454/14438823/45c28eae-0028-11e6-9338-370f13fcfed4.png)

The wide one is probably good for the login page though :+1:

**Comment by Safihre** [comment]
@jeffgeorge might have to manually edit the 16x16 and 32x32 versions, seems also the previous version of those sizes had some manual optimization to make the edges so clear.

**Comment by Safihre** [comment]
Now also added the new logo in Plush, fitting very well also there! 
I have added it to #544.

**Comment by Safihre** [comment]
Do we need the text SAB in the 16x16 logo? It's just so ridiculously small and the arrow is pretty self-exploratory.

**Comment by Safihre** [comment]
Update to latest develop to see the new favicon! 

I also created new ICO files and manually edited 16x16 images for the NZB and SAB icons.
https://github.com/Safihre/sabnzbd/commit/d6ca4dd1b355edf9b96fe5dfa4553f365a72ef92

**Examples:**
![image](https://cloud.githubusercontent.com/assets/5703454/14586904/a8474136-04a7-11e6-8b7d-16754c0998df.png)  
![image](https://cloud.githubusercontent.com/assets/5703454/14586937/8b9931d8-04a8-11e6-94a9-5397a9b34a99.png)


![image](https://cloud.githubusercontent.com/assets/5703454/14586909/bd085632-04a7-11e6-8127-7840ac58e4ff.png) 
![image](https://cloud.githubusercontent.com/assets/5703454/14586915/e54f4db2-04a7-11e6-8b18-cd72314082f3.png)

**Comment by Safihre** [comment]
Tweaked the 16x16 a little more:
![image](https://cloud.githubusercontent.com/assets/5703454/14587007/2cd00f76-04aa-11e6-814b-d8fbb5a74229.png) ![image](https://cloud.githubusercontent.com/assets/5703454/14587011/47aa90e6-04aa-11e6-93e3-083d10ee0f8e.png)

**Comment by jeffgeorge** [comment]
Woo thanks for getting those ico files. Do they work cross platform? Obviously it looks like they're fine on Windows. I'll check on OSX tonight and if needed I can spin up an ubuntu VM to see if they render right over there as well.

Out of curiosity -- and so we can document the tool-chain -- what'd you use to generate the .ico files? I was looking at starting with imagemagick's svg to ico conversion, but didn't get there yet (Sunday night seems to be the night I end up with time to work on SAB stuff).

**Comment by Safihre** [comment]
I just converted the svg to png using the online tool https://cloudconvert.com/svg-to-png
And then setting it to high resolution. 

Then I converted those using http://icoconvert.com/ 

Which I then edited using Junior Icon Editor for the 16x16 version. 

I tweaked some more! I rebased them on my latest commit https://github.com/Safihre/sabnzbd/commit/b161d47fbec4536db00850b12e9c00e5053d2e60

**Comment by jeffgeorge** [comment]
OK, so then they're raster icons, not vector. I *think* vector icons should
work these days with the platforms we support, but I haven't fully
researched it. I'll dig into that tonight.

**Comment by Safihre** [comment]
Windows doesn't support it, haven't look into the other ones. It now just used up to 256x256 in the ico file. 
Also browsers all effectively keep using 16x16, whatever you supply them..  Did not expect that in 2016.
Spent quite some time tweaking the favicon for the browser (in the Config folder), quite happy with that!

**Comment by thezoggy** [comment]
dont do it..
http://caniuse.com/#feat=link-icon-svg

**Comment by jeffgeorge** [comment]
Lame. Then I guess we might be more or less done? Have you got a PR that wraps up implementing all these changes @Safihre?

**Comment by Safihre** [comment]
Starting to only see pixels everywhere, but I think I did the best possible with the number of pixels available at each size: #551 

![image](https://cloud.githubusercontent.com/assets/5703454/14632586/e48332e0-0619-11e6-9c68-2d73fc093660.png)

**Comment by thezoggy** [comment]
the text doesnt seem as crisp on those icons except on the smallest two sizes...

**Comment by Safihre** [comment]
Yes, on 24x24 and 32x32 it's very hard because the letters and the border are not a whole number of pixels in size. 
If I make them crisp, it will also look weird:
![image](https://cloud.githubusercontent.com/assets/5703454/14638234/b63d5e20-0636-11e6-8346-feab24d1a15e.png) or ![image](https://cloud.githubusercontent.com/assets/5703454/14638261/df1e6b72-0636-11e6-9642-85cef74dad17.png)

**Comment by Safihre** [comment]
Tried to sharpen things a bit more. How about this?
![image](https://cloud.githubusercontent.com/assets/5703454/14639333/7bb28630-063c-11e6-8a6e-7df83d547d9b.png) ![image](https://cloud.githubusercontent.com/assets/5703454/14639349/93ddc864-063c-11e6-87d3-8bde57cf94c5.png)

**Comment by thezoggy** [comment]
3rd icon looks good now. 4th is fine too.. now the biggest one is the last one to fix.. the anti-alias thats enabled makes it blury because of the gray insert around the edge..

**Comment by Safihre** [comment]
Redid all the lines inside and out of the big logo, no more grey line:
![image](https://cloud.githubusercontent.com/assets/5703454/14643297/3102b1b6-064e-11e6-8af8-2ad465154cb5.png) ![image](https://cloud.githubusercontent.com/assets/5703454/14643284/2585de62-064e-11e6-9b3b-6c3d715e6ddd.png)

**Comment by Safihre** [comment]
Did some more touch ups, every pixel is perfect now for all sizes included.

**Comment by shypike** [comment]
Is this complete now?

**Comment by Safihre** [comment]
Yes, all the files (vector and .ico) are in there somewhere. Icons folder or the images folder of the Config template.
