### ISSUE TITLE
[Feature Request] Glitter: Allow some more columns to be shown by default

### ISSUE THREAD

**Issue by skaforey** [sabnzbd/sabnzbd#522]
I have widescreen monitors and I think it would be nice to allow certain fields to be viewed on the main page (such as download speed, category, size, etc).

**Comment by Safihre** [comment]
Did you already see you can add 1 extra column in the queue? In Status and interface settings.

**Comment by Safihre** [comment]
@skaforey did this solve your request? Or you want more info in the History?

**Comment by skaforey** [comment]
Yeah I was requesting more info in the history

**Comment by Safihre** [comment]
Will check, but can't make any promises. Shouldn't look weirdly. And would mean yet another interface option, but that's manageable.

**Comment by Safihre** [comment]
I have added Size and Category as options, there is no API field for speed and I also don't think that's very interesting information.
Path is just too long to serve any purpose of putting that, since it gets cut off anyway!

Closed by #525 _(for develop, not 1.0.1)_.

**Comment by skaforey** [comment]
Thank you!  I thought the old interface, and even the current history will display the speed if you click on the details.  Speed is actually the column I was most looking forward to, but if it's not readily available, not much you can do I guess.

**Comment by Safihre** [comment]
Well, there is a way.. The download time in seconds and the size in bytes is available, so I could just calculate the speed. 
@shypike, is the ```bytes``` in the history  api the actually downloaded bytes or the size it was supposed to be?

**Comment by Safihre** [comment]
@shypike so I figured out that ```bytes``` is only the actually downloaded bytes. But still at higher speeds, dividing ```bytes``` by ```download_time``` gives me a different result than in the download report. 

But I think actually the download report is wrong, for example:

> Size: 814 MB
> Downloaded in 21 seconds at an average of 38.0 MB/s

But when you do 814MB / 21s = 38.7MB/s...

**Comment by Safihre** [comment]
@skaforey I added the Speed option in pull request #525, so if you run from source you should be able to use it now :) Otherwise in version 1.1.0!
Still unclear why the download-report differs from ```size/time```, but I'll leave that one to @shypike :wink:

**Comment by Safihre** [comment]
That's a browser thing, we don't implement anything like that.
Try a different browser. It's indeed CTRL+Click.

**Comment by ItsME6969** [comment]
@Safihre Thanks for the prompt response. Can confirm it is a browser issue just tried with firefox and it worked not sure why chrome is not, but could be one of the many extensions I have running. I'll try and find the issue. Cheers.
