### ISSUE TITLE
"Download all par2 files" doesn't download all par2 files after verify fails

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#527]
*Reported on Reddit and confirmed by me*
With these settings:
![image](https://cloud.githubusercontent.com/assets/5703454/14084175/c84b274c-f519-11e5-8081-532424781288.png)

And a download that needs extra par2 blocks after first verification, this happens:
*(bottom ones were not downloaded, as you can see from the checkbox being greyed out)*
![image](https://cloud.githubusercontent.com/assets/5703454/14084190/e722cecc-f519-11e5-9508-0de1b7376015.png)

**Comment by shypike** [comment]
Is your interpretation that partially downloaded par2 files aren't completed?

**Comment by Safihre** [comment]
No, it will only download those top 4 par2 files, not all the rest. While I have the Download all par2 files turned on. 
I watched this download finish and it really only downloaded the top 4 (probably the minimum it needed).

**Comment by shypike** [comment]
OK, good clue. That probably means they're not coming back from being hidden.

**Comment by Safihre** [comment]
This line is the problem:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1070

In all my test-cases, nzo.files is empty (I am guessing because that one contains the files that still need to be downloaded?).
Removing that line makes it behave the way it should!
Maybe that line should be 
```python
if extrapar not in nzo.files:
```
To avoid duplicate re-additions?

**Comment by shypike** [comment]
You analysis is right.
In fact there's more redundant code. The section can be reduced to this:
```Python
    if not result and cfg.enable_all_par():
        # Download all par2 files that haven't been downloaded yet
        readd = False
        for extrapar in parfile_nzf.extrapars[:]:
            nzo.add_parfile(extrapar)
            readd = True
        if readd:
            return readd, result
```
The check for presence in nzo.files and the removal from extrapars is already done in nzo.add_parfile().

**Comment by Safihre** [comment]
I just checked and this code does not work, because the ```add_parfile``` gets the argument ```parfile```, which is only that 1 extra parfile.
So ```parfile.extrapars``` in ```add_parfile```  is ```None```.

**Comment by Safihre** [comment]
Oke fixed, it has to be ```self.extrapars``` of course.

Put the fix in my PR:
https://github.com/Safihre/sabnzbd/commit/517c701eef1d00501b07926f67ff35f5ca5b7ce5

**Comment by shypike** [comment]
I'm not sure if this is right. Your change in nzbstuff.py may have side effects.
I'll need to spend some more time on this.

**Comment by Safihre** [comment]
It seems to me it has just been always wrong.. 
Because in all its usages (only 2 other) the function is also passed an NZF object of the par2-file. And an NZF object doesn't have an ```extrapars``` property.
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1338
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1404

**Comment by shypike** [comment]
An "nzf" object does have an "extrapars" attribute, set at the top of the postpone_pars() method.
```Python
nzf.extrapars = self.extrapars[parset]
```

**Comment by Safihre** [comment]
Aaah I see, in case an NZB contains (multiple) single files with their own par2-sets?
I'll leave this one to you then :dash:

**Comment by Safihre** [comment]
Ok, I reverted it to being only the 1 line fix in newsunpack.py!
