### ISSUE TITLE
Language can't be chosen in latest develop version

### ISSUE THREAD

**Issue by r33mi** [sabnzbd/sabnzbd#528]
When upgrading SABnzbd to the latest development commit, Language cannot be chosen from the general settings.

**Comment by Safihre** [comment]
When you are on development you have to run ```python tools\make_mo.py``` (or with / for Linux) in the SABnzbd directory to get languages compiled and available.

It's always been like that, it's also in the readme on the main page:
https://github.com/sabnzbd/sabnzbd

**Comment by r33mi** [comment]
That was fast! Thanks, will look into that.
