### ISSUE TITLE
Space after newsserver OK for wizard, not for SAB downloader [1.0.0]

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#529]
Hi, see https://forums.sabnzbd.org/viewtopic.php?f=2&t=20482#p105250

Sabnzbd 1.0.0

So: if, by accident, you fill out a space after the newsserver FQDN:

1. it's accepted by the wizard,
2. the wizard will report "Connection succesful!". Looks good.
3. but the main SAB download will not use that newsserver at all.

Expected behaviour:
SAB's wizard refuses the newsserver-with-space, and gives a warning
(Or, theoretically: SAB's main download program is OK with the space, just like the wizard)

```
$ cat sab----eweka-with-a-space.ini | grep -i eweka
[[newsreader3.eweka.nl]]
displayname = newsreader3.eweka.nl
name = newsreader3.eweka.nl
host = "newsreader3.eweka.nl "
```
Note the last line: a space for the last double quote ...

I'll try to find out what is going on, and report back.

**Comment by Safihre** [comment]
Should be easy to fix, adding ```s.strip()``` everywhere involving hostname? Maybe also for the username? 
Both people are likely to copy-paste.

**Comment by sanderjo** [comment]
```

def test_nntp_server_dict(kwargs):
    # Grab the host/port/user/pass/connections/ssl
    host = kwargs.get('host', '').strip()
```

... the strip() looks like the problem!

If we strip() (which could be handier than giving an error), we should put that stripped value back into the stored values.

I'm _assuming_ a space will never be a part of a username or password. Am I correct?

**Comment by Safihre** [comment]
Seems to me you are correct!

**Comment by shypike** [comment]
Passwords can contain spaces. Leading and trailing spaces are not allowed.

**Comment by Safihre** [comment]
I found the problem! It's in the config object ```OptionString``` which should do the stripping, but it doesnt because it assumes that the input is a string, not a unicode string:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/config.py#L303
```python
if type(value) == type('') and self.__strip:
```
But what is actually the case for all input:
```type(value)```  is ```<type 'unicode'>```
```type('')``` is ```<type 'str'>```

**Comment by sanderjo** [comment]
Remarks:

1) So ... was this bug introduced with the Unicode introduction in SAB, so SAB 0.8.0 / 1.0.0? It worked before that moment?


2)
```
class OptionStr(Option):
    """ String class """
<snip>
        if type(value) == type('') and self.__strip:
            value = value.strip()
```
As we are in a in String class / function, why is the type checking ```type(value)``` needed at all? It can't be number, can it?

**Comment by Safihre** [comment]
The try-except seems easiest, put it in #525 / deb5690

**Comment by Safihre** [comment]
Fixed and merged in #525, close? :dart:

**Comment by sanderjo** [comment]
I tested the git version: I added a space both in the Wizard and the Server setup, and the space were nicely removed, and everything worked.

Well done!

**Comment by brynnb** [comment]
Might be worth pointing out, this happens with a space before the server URL as well. Not sure if the fix added would also fix that.

**Comment by Safihre** [comment]
The fix trims spaces before and after!
