### ISSUE TITLE
QuickCheck OK on broken files when cleanup list contains .rar

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#530]
This bug took me a long while to figure out after a user reported many ["Unpacking failed, an expected file was not unpacked"](https://www.reddit.com/r/usenet/comments/4c17c6/lots_of_problems_with_sabnzbd_unpacking_failed_an/).

I reduced the problem to having ```.rar``` in the Cleanup list, this causes QuickCheck to approve every download even though they are damaged, because of these lines:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L1691-L1693

I think we should change this to not skip ```.rar``` (and maybe others?), even if it's in the cleanup list?

**Comment by shypike** [comment]
You may very well be right.
The idea behind this code makes sense: why check files when they are discarded anyway.
However, if RAR files are involved, it makes no sense.
It's best to remove the test altogether, because a real par2 run will not discount any file on the clean list either.

**Comment by Safihre** [comment]
Yep let's get rid of that check :+1:
