### ISSUE TITLE
This is hardly an issue, but why doesn't SABNZBD quickcheck every file when it completes downloading?

### ISSUE THREAD

**Issue by sharpdev121212** [sabnzbd/sabnzbd#532]
I don't get it. Why does it have to wait until the completion of all files to download to check each and every one of them

**Comment by Safihre** [comment]
The QuickCheck only takes like 1-20 seconds to do it for all files at once. So why do it after the download of every file? If it fails we have to run par2 anyway, which takes much longer.

**Comment by Safihre** [comment]
@sharpdev121212 your issue inspired me to add #533, which basically makes sure enough par2 is always downloaded for when the QuickCheck fails and par2 is started. 
I did some extra testing and it really only takes seconds to do the QuickCheck at the end for all of the files.
Hope this addresses your issue? :)

**Comment by sharpdev121212** [comment]
Great job!
