### ISSUE TITLE
sab 1.0 -- glitter

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#534]
![sab](http://zoggy.net/firefox_2016-04-04_15-51-49.png)

* tab is round on left side but not on the right.. 

* table header missing left border

* modal header border looks off?

* should show how many connections out of the max available per server... 

  > saw that speeds dropped, have to dig to find why... perhaps it would best to move this info out of a skin specific modal/sub menu and put it next to the the bandwidth to show a connection details modal thats wider/better.. since it would explain why they are getting crap speeds...

**Comment by Safihre** [comment]
Your screenshot is not from _develop_ but _1.0.x/1.0.0_, in _develop_ the modal will extend on Connections page with _Show active connections_ checked

- Cannot fix that tab rounding, it's just how FF renders two borders intersecting. It's the default Bootstrap CSS and on Chrome/IE the corners look not (so) different.
- Fixed those borders on header and table, they were off.
- Will add the active connection count.

**Comment by shypike** [comment]
enough to close this?

**Comment by thezoggy** [comment]
@Safihre -- http://stackoverflow.com/questions/20954944/stop-lastpass-filling-out-a-form

**Comment by Safihre** [comment]
@thezoggy that adding ```search``` worked great, thanks!

**Comment by shypike** [comment]
Fixed in 2ce125789c138cf549a101a05f7b2817c0f344e9
