### ISSUE TITLE
Jobs get loaded from disk into memory when they don't need to be

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#535]
person in irc just posted:

```
helllo, i'm running sabnzb 1.0.0 on windows 10, and i'm having an issue where sabnzbd crashes shortly after starting, i assume this is because of my queue, it's around 10tb of downloads, what would be advised for me to clean out the queue?

i see in task manager before i see a tray icon, that sabnzbd process is taking up more than 1.5gb ram and 1 entire core of cpu power

then after a few minutes, it'll open the web browser, then it will exit the process shortly after
```

spoke to the person briefly in another channel, they had already 'fixed' the issue by just nuking their queue...  asked some questions so we can try and reproduce/handle this more gracefully

```
them> sab 1.0 win exe installer -- xeon 8 core, 32gb ram, 1tb ssd
me> what does logs say ?
me> permission issues? out of space concerns?
them> i think it was going out of memory
them> it hit 2gb of ram and would crash
them> now everything works :)
me> how many items were in your queue ?
them> ~3000 ?
me> how fast is your internet speed ?
them> 250/25
them> i had 'sort by age' enabaled i wonder if that helped the crash
```

**Comment by Safihre** [comment]
Same as #407, there's just nothing we can do with those sizes.. Not just the starting of Sab, api calls also take multiple seconds with those kind of queues..

**Comment by shypike** [comment]
SABnzbd needs some memory per job. It postpones loading the complete job-admin until it's the jobs term. However, I have seen that sometimes way too many jobs get loaded fully into memory.
That needs to be looked at. As is the awkward way in which the admin is kept...

**Comment by sanderjo** [comment]
@Safihre your patch shows active connections, not "memory used by the queue", right?

**Comment by thezoggy** [comment]
@sanderjo it shows how many active connections out of the possible limit set by the user.. i requested it since counting the 'rows' is no fun :)

**Comment by Safihre** [comment]
Yes. But if you refer to the commit (	399881e) that references this issue above, that was a typo. I used the wrong issue number, should have been 534 instead of 535. 
Corrected that typo later, but the old commit with this title/link stays somewhere on Github even though it's not used anywhere.

**Comment by sanderjo** [comment]
@shypike Out of curiosity: does SAB load all NZBs and it's individual messages ID's in the queue into an array, and thus memory?

**Comment by shypike** [comment]
@Safihre No, the NZF parts stay on disk until needed. Having said that, there are circumstances in which too many jobs are fully loaded into memory.

**Comment by Safihre** [comment]
Updated the title to reflect the work that needs to be done still. 
I also noticed that sometimes jobs get loaded that don't need to be yet, but couldn't pinpoint it yet.

**Comment by Safihre** [comment]
While testing yesterday with about 50 jobs I saw this behavior, making SAB spike to 700MB memory while my article cache was only 450M. 
But more strangely: after I deleted all the jobs, the memory usage idle stayed at 150M, while normal idle usage is 35M. I waited for a few hours with SAB idle, but it never went below 145M.
I think this is one of those mysterious memory leaks that I read about online, because what more can we do besides delete the objects? That's all we can do in python, right?

**Comment by shypike** [comment]
That it stays on 145M has to do with the garbage collector not doing its work.
Once I thought this was caused by circular dependencies, but when I removed those, nothing changed.
The memory peak is a very old bug, which I have never been able to solve. For some reason, sometimes too many jobs get loaded into memory. BTW: were all of those jobs enabled (not paused)?

**Comment by sanderjo** [comment]
> That it stays on 145M has to do with the garbage collector not doing its work.

Does a restart of SABnzbd solve that? 

If so, how about a automatic, periodic restart of SABnzbd, for example when SAB is not active or between download jobs? Ugly, but as they say "Als 't niet kan zoals het moet, dan moet 't maar zoals 't kan" ;-)

**Comment by shypike** [comment]
@sanderjo Of course SABnzbd will decide to reset itself, just when you were entering a bunch of jobs...
It is already possible to schedule a restart.

**Comment by thezoggy** [comment]
@sanderjo you can use the scheduler and just say, restart sab at x time (2pm daily) or something..  of course this also could be accomplished via a script using api or cron job with init script

**Comment by Safihre** [comment]
Should we limit the amount of jobs that sabnzbd will look ahead to for example 20?

**Comment by thezoggy** [comment]
whats the benefit of sab looking ahead at any job number of jobs?

**Comment by Safihre** [comment]
So that your highest priority can continue with other jobs while secondary servers handle the first jobs that were missing on the highest priority. 
Look ahead is disabled completely when `Only download top of queue` is turned on.

**Comment by thezoggy** [comment]
Perhaps we should just do a percentage of the queue.. 20% with artificial​ Max of 20 items? That way it scales up and down.. but 20 Blu-ray downloads is much different than 20 music ones..

**Comment by Safihre** [comment]
This is mostly fixed, but what needs to happen now is that de article database goes back to disk when not used for a while. I'll create a new issue for that for 2.3.0.
