### ISSUE TITLE
[feature] 'Add All' option on the Queue Repair screen

### ISSUE THREAD

**Issue by slug1982** [sabnzbd/sabnzbd#538]
It would be useful to have a 'Add All' option on the Queue Repair screen, similarly a 'Remove All'.

Thanks.

**Comment by Safihre** [comment]
In Glitter, there is already a Remove All. No Add All yet, will see what I can do!

**Comment by Safihre** [comment]
Oke I have added it, just for Glitter though!

**Comment by slug1982** [comment]
Can Plush get the love too?

**Comment by Safihre** [comment]
Maybe from someone else, I want to stay just on Glitter for new functionality.
