### ISSUE TITLE
Glitter stopped working due to %22 in .js/.png urls

### ISSUE THREAD

**Issue by GregSawin** [sabnzbd/sabnzbd#542]
Recently both Glitter themes stopped working properly.  Using the dev tools in Chrome I can see the issue is that all the javascript and image files have %22 (double quote) in the url.  For example:
http://192.168.1.2:8080/%22/js/parsers.js?9516\%22 
http://192.168.1.2:8080/%22/js/lib/jquery.cookiejar.js?2160\%22 http://192.168.1.2:8080/%22/images/sickrage.png/%22 404 (Not Found)

The page is completely unusable in this state, looks like an un-formatted log file.  Plush and smpl themes don't have this problem.

I'm on v1.0.0 [a58bb38] on Windows 10 x64.

**Comment by Safihre** [comment]
The problem is known to us and already fixed, waiting now on the release of 1.0.1. (@shypike pretty please? :wink:)

**Comment by Safihre** [comment]
@GregSawin could you maybe send (safihre@sabnzbd.org) me your history.db file so I can verify it is also fixed for your case? The file is located in the ```admin``` folder of the folder where your ```sabnzbd.ini``` file is located (see first page of the Config).

**Comment by Safihre** [comment]
Just received his database and indeed the fix we implemented (and that's already in the 1.0.x branch) works also for this case!

Case closed ;)

**Comment by kingmotley** [comment]
Can you also check mine?

**Comment by Safihre** [comment]
Got your email, checked and our patch also fixes yours :+1:

**Comment by kingmotley** [comment]
Thanks safihre, that's great news.

**Comment by Safihre** [comment]
@kingmotley @GregSawin You can download 1.0.1 that has the fix here:
https://github.com/sabnzbd/sabnzbd/releases/tag/1.0.1RC1
