### ISSUE TITLE
Feature request getapikey without the existing apikey or with disabled api.

### ISSUE THREAD

**Issue by Hellowlol** [sabnzbd/sabnzbd#545]
I would love to have some sort of functionality like to grab the apikey i like couchpotato has.

My idea is to:
If api is disabled enable it and make a new apikey, if webauth is enabled, username and password is required

This would nice to use with the zerfoconfig to automatically find the url and use the api to get the apikey :)

I can send a pr for this if your interested in this type of feature

**Comment by Safihre** [comment]
Sure go ahead and make a PR, seems no harm in this feature.
There are already some supporting functions to check username/password and if API access is allowed externally (```check_access()```) etc in interface.py.

**Comment by shypike** [comment]
Can you give us some more details? Because how I read it, it sounds like a security gap.

**Comment by Hellowlol** [comment]
I dont think anybody uses sabnzbd without using the api. If your using sabnzbd without a username and password you already have a huge security gap. It doesn't really change the status que regarding this. 

If no auth: enable Apii and generate apikey
If auth: enable api generate apikey requires the username and password
If apikey exist, raise a error and point to the regenerate api that already exist

I'm open to other suggestion, but that was what I had planned.

**Comment by shypike** [comment]
There's no security issue if you don't have a password. Most people use SABnzbd within their own PC or within their local network (which may or may not be safe). The API key (as a session key) was originally introduced to protect against cross-site scripting vulnerabilities where an external website could gain access to your purely locally running SABnzbd instance.

How does a third-party tool gain access to SABnzbd?
I don't know how CP does this, can you explain?

**Comment by Hellowlol** [comment]
I guess that depends on the app. In this case I'd pla to use https://github.com/home-assistant/netdisco to find sabnzbd (it simply construct the sab URL) and query sabnzbd to get the apikey if the apikey wasn't in ha config file.

Cp:

../getKey?username=xxx&password=yyy 

If a username and password is set you need to md5 them if not just remove xxx and yyy
I don't think it will enable the api, i think the ui requires it and handles that that seperatly.

I'm sorry for the lack off formatting I only have access to my phone.
