### ISSUE TITLE
Feature Requeset - Extend Scheduler to unpause based on category 

### ISSUE THREAD

**Issue by cdloh** [sabnzbd/sabnzbd#549]
It'd be nice to have the ability to unpause jobs in the queue based on the category they are in and then on the flip side be able to pause them again.

That way you can have a queue that you only want downloading during a specified time.

**Comment by cdloh** [comment]
I just updated to the latest version and realised you could do this with Priorities.

I still think it might be good to extend that all the way to categories as well.

**Comment by Safihre** [comment]
Indeed somethings that's not possible yet.. You could change indeed the main Priority setting of the category in Settings to for example Low and then pause/unpause the Priority. 
How can a download start paused? Only if you do it manually, right?

**Comment by cdloh** [comment]
You can setup a category that has the default priority set to Paused. 

This then adds the NZB to the job queue as Paused with a Priority of Normal.

**Comment by Safihre** [comment]
Yes of course, forgot about that! 
Indeed seems like a feature that can't be achieved any other way, let's see what we can do :+1:
