### ISSUE TITLE
IPv6: No proper listening socket

### ISSUE THREAD

**Issue by flashover** [sabnzbd/sabnzbd#55]
Situation:

--------------------------
C:\Users\Flashover>netstat -an | findstr 9090
  TCP    0.0.0.0:9090           0.0.0.0:0              LISTENING
  TCP    [::1]:9090             [::]:0                 LISTENING

--------------------------

This isn't the same thing for IPv4 or IPv6 connectivity.

"0.0.0.0" (IPv4) == "::" (IPv6)

::(double colon)  != ::1 (double colon and the number one)

The IPv4 socket is global, listening on all NICs for incoming connections.
The IPv6 is bound to "localhost" only, so this is not accessible from other PCs across the network.

The correct should be without the number "1" in the address, so "[::]:9090" would be the correct thing.

My "host" parameter in the sabnzbd.ini file can be set to either "0.0.0.0" or "::" but can't be used at the same time. When only using "::" it does work correctly for IPv6, but then IPv4 isn't assigned at all.

Running:
Windows 7 Pro.
SABNzbd 0.7.2.

Please fix.

Same as https://bugs.launchpad.net/sabnzbd/+bug/1029007

**Comment by Safihre** [comment]
This is fixed it seems? 
I just noticed I already have ```::``` and not ```::1```  for months and can access it through my network.

**Comment by shypike** [comment]
Likely fixed with CP 3.8.0
