### ISSUE TITLE
SABnzbd 1.0.1RC1: full cherrypy traceback in Queue overview

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#552]
SABnzbd 1.0.1RC1: full cherrypy traceback in Queue overview

![sabnzbd 1 0 1rc1 - strange error](https://cloud.githubusercontent.com/assets/1273502/14686041/6c0c2c6c-0737-11e6-85d0-0abfadbde931.png)

Is this how it should be?
(FWIW: cause = disk full)

**Comment by Safihre** [comment]
What's the end of the last lines? Only the multipart line? 

What we're you doing when it happened?

**Comment by shypike** [comment]
It **is** clear what's happening...
Not sure if we can catch all possible CP crashes.
This particular crash, starting in database.py should be caught of course.

**Comment by shypike** [comment]
The SQLite error is caught properly, resulting in a simple error message and details in the log.

The error is the screenshot is unclear to me. Is there a relation with the SQL error?
Looks like a failure of an NZB upload through the UI where CP hits "disk full".
I'm afraid that that will be hard to catch.
Disk full situations are next to impossible to handle gracefully. So much under water can fail.

**Comment by sanderjo** [comment]
> Looks like a failure of an NZB upload through the UI where CP hits "disk full".
I indeed believe it happened at the moment I uploaded an NZB


> I'm afraid that that will be hard to catch.
> Disk full situations are next to impossible to handle gracefully. So much under water can fail.

I was especially surprised to see the traceback in the Queue overview. If that is how it should (with an uncatchable exception), I will close this issue.

**Comment by Safihre** [comment]
Kind of similar to this one about saving of the config file when disk is full: #186 
Indeed how much can SAB do about a full system disk, guess not a lot!

**Comment by shypike** [comment]
Not so similar. SABnzbd should try hard not to lose the INI file.
It already does convoluted things, but not enough it seems.
