### ISSUE TITLE
Feature Request: Anonymized Debug Logs

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#558]
I would like to request anonymized debug logs for posting on Github, the forums, or anywhere else.  Rather than having to go through line-by-line to censor anything sensitive it would be handy to just be able to copy/paste without worry.

I can see why logs being anonymized 100% of the time could make it harder to debug, so I would suggest maybe just and additional option in the drop down dialogue called `+ Anonymized`.

NZBHydra recently implemented something like this and it's very useful for bug reporting without having to worry about your IP or API key leaking out onto the internet.  Thanks!

**Comment by shypike** [comment]
I see that nzbhydra uses a rather simple method, I guess we can do such a thing too.
They do not hide URLs to be fetched from indexers, which  may be a bigger issue. I can see why they don't: it's very hard to do afterwards.

**Comment by Safihre** [comment]
How about doing a regex-replace for IP-addresses (always ```.``` for IPv4 or ```:``` for IPv6) and [for a hash of 32 characters](http://stackoverflow.com/questions/4505641/using-grep-to-match-md5-hashes)? 
That's what almost everybody uses anyway.

**Comment by shypike** [comment]
OK, looking for hashes like that will cover most access tokens used by indexers.

**Comment by Safihre** [comment]
I was looking into this, but found that matching a hash doesn't always work so well, for example in obfuscated files things like this will be in the log:
```
2016-04-27 10:25:43,907::INFO::[SABnzbd:1244] SABnzbd.exe-1.0.1 (rev=<HASH>ae287cc5)
2016-04-27 10:57:54,381::INFO::[nzbstuff:479] File 481e366ae7a450a9988d613c9c342eab [002/104] - "<HASH>.100" yEnc (1/66) added to queue
```
Is that bad?
Otherwise for example OZnzb's hashes will not be matched correctly:
```
2016-04-27 19:59:07,099::INFO::[urlgrabber:99] Grabbing URL https://api.oznzb.com/getnzb/9385034deccf83ee6c7e34f3c73695fe.nzb&i=215641&r=70cdfed588ac94ef73531539xxxxx&del=1
```

**Comment by Safihre** [comment]
I propose to partially hide the hash, after already replacing the obvious ones in the way NZBHydra does.
This will give:
```
2016-04-27 10:25:43,907::INFO::[SABnzbd:1244] SABnzbd.exe-1.0.1 (rev=<HIDE-HASH>3b2a481ae287cc5)
2016-04-27 10:57:54,381::INFO::[nzbstuff:479] File <HIDE-HASH>c342eab [001/104] - "<HIDE-HASH>8fc600a.10" yEnc (1/66) added to queue
```
This still hides most of the hash but makes it more clear to later find which files it is actually about.

Will implement a question when clicking Show Logging if they should be anonymized.

**Comment by shypike** [comment]
Shouldn't we simply always obfusticate?

**Comment by Safihre** [comment]
Yes you are right, just pushed the commit to #565 so now all logging is anonymized!

**Comment by albino1** [comment]
It looks good!  But I'd also like to request anonymized paths too.  For example in Windows the log might say:

`2016-05-15 13:13:03,994::INFO::[__init__:919] Saving data for totals9.sab in C:\Users\Michael Johnson\AppData\Local\sabnzbd\admin\totals9.sab`

I'm sure Mr. Johnson doesn't want his name out there, so it would great if it could be replaced with `\USERNAME\` or `\<username>\` or something.

**Comment by Safihre** [comment]
Maybe, but it's very hard to detect what is the username. Maybe on Windows whatever is after ```\Users\```. But don't know if Windows is set to Dutch for example if it will be ```\Gebruikers\```?
And all those Linux flavours probably also have something else than ```/home/username```.
Could make some standard replacements like that, but probably will be some situation we don't catch..

**Comment by albino1** [comment]
Yeah, that makes sense, I can see how that might be difficult.  What you've already added is already a big improvement though, so I thank you for that :)

**Comment by albino1** [comment]
FWIW, I know in Windows you can get the username from the system using `%USERNAME%` (type `echo %USERNAME%` in a cmd prompt to see it in action), and in Linux you have `$USER`, so maybe you can just match/replace those in path lines.  Just a thought.

**Comment by Safihre** [comment]
Found a way using the ```getpass``` module that works cross-platform. Tested Windows, Ubuntu and OSX, all worked. In case of exotic situations I encapsulated it in a try/except just to be sure.

**Comment by albino1** [comment]
Great, thanks Safihre!

**Comment by Safihre** [comment]
Implemented, close?

**Comment by thezoggy** [comment]
I see the anonymizer works.. but the ocd in me is bothered by some saying HIDE while some are just a placeholder for what was there. I'd rather see `<removed>` or at least no pre-fixed name (no hide-).

```
2016-06-10 23:18:03,828::INFO::[assembler:88] Decoding \\?\C:\Users\<USERNAME>\downloads\incomplete\After.the.Black.S01E04.1080p.B\After.the.Black.S01E04.1080p.BBCA.WEBRip.AAC2.0.H.264-BTW.part21.rar yenc
2016-06-10 23:18:03,828::DEBUG::[decoder:103] Decoding Part13of66.<HIDE-HASH>6475817@1462580846.local
```
