### ISSUE TITLE
Glitter FR: NZB Upload Progress Bar

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#559]
When uploading a large NZB to a remotely hosted instance of SABnzbd using the Glitter interface it's unclear if anything is happening after you click the button.

In Plush when you click Upload a working circle spins next to the button letting you know that something is happening until the NZB appears in the actual Queue.

On the other hand, in Glitter when you click Upload there's no notification that it worked or that anything is happening at all.  If it's a particularly large NZB it will sit there for quite a while appearing completely blank until suddenly the NZB appears in the queue.  On slower connections I imagine this effect is magnified even more so with an apparently "frozen" interface creeping up into the minutes.

Some sort of progress bar would be a nice way to indicate that something's going on, but if that's overkill then even just a spinning circle like Plush has would alleviate that feeling that nothing is happening and something has gone wrong.

**Comment by Safihre** [comment]
This is already in ```develop``` and will be in 1.1.0. 
It will show an overlay notification while uploading and a counter if you drag-and-drop a couple.

**Comment by albino1** [comment]
Great, that works, thanks!
