### ISSUE TITLE
Nzb waiting for post-processing shows up with status Deleted in history

### ISSUE THREAD

**Issue by Taloth** [sabnzbd/sabnzbd#561]
Version: Sabnzbd 1.0.1 RTM

Repro:
Queue one big download and one small one. Once the first one finishes download, it will start being post-processed, in the meanwhile the second download finishes downloading quickly and has to wait before being post-processed.
During that time the second download shows up on the history api with the status Deleted.

Obviously the expected behavior is another status code, although I'm not sure which would be the most appropriate status.

**Comment by shypike** [comment]
That status is not correct, we're fixing that for 1.0.2

**Comment by shypike** [comment]
Fixed in f0a243e3d3ef47eacd4a73b2f2df164e1dce93d8
