### ISSUE TITLE
Retry loses Servers breakdown

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#564]
SABnzbd: 1.0.1RC1 [4eb486d]

I love the Servers breakdown in 1.x telling you which ones got used to complete a file, but I noticed that if a file fails and you later click Retry to run it again then the Servers breakdown no longer appears.  Here's a screenshot showing that the Servers portion of the details isn't there:

![al-sab-serverdetails](https://cloud.githubusercontent.com/assets/12164957/14943980/fea01b26-0f9b-11e6-8558-53e9cc1dcb39.jpg)

I'm not sure if this is a Bug or a Feature Request, but either way it would be nice to retain that information.  Particularly because aren't failed NZBs the ones you'd want to know the most about? :)

**Comment by Safihre** [comment]
Looking at the code, there seems to be no real way to transfer that information back from the history into the queue.

**Comment by albino1** [comment]
Ah, okay.  Well, it would have been nice!  Thanks.

**Comment by thezoggy** [comment]
yeah, its not a 'retry' but more of a redo... hence we try a clean slate and go at it again...

**Comment by albino1** [comment]
Ah, when you think about it like that then it does make sense.
