### ISSUE TITLE
App tries to create and save to paths more than 260 chars, leading to failure and inability to download.

### ISSUE THREAD

**Issue by jkoebel** [sabnzbd/sabnzbd#566]
On Windows 10, the app is generating temporary paths like:

H:\T\317400_FULL_a_b_teevee_EFNet_Full_Frontal_With_Samantha_Bee_S01E10_720p_HDTV_x264_MiNDTHEGAP_full_frontal_with_samantha_bee_s01e\__ADMIN__\317400_FULL_a_b_teevee_EFNet_Full_Frontal_With_Samantha_Bee_S01E10_720p_HDTV_x264_MiNDTHEGAP_full_frontal_with_samantha_bee_s01e.nzb.gz 

This string is 279 characters long; the maximum allowable path length for Windows is 260 characters. So, the downloads fail to even start because the application can't write to the paths it is generating.

**Comment by sanderjo** [comment]
Is it really "H:\", because AFAIK SAB 1.0.0 should have switched to the notation "\\\\H"\\" (or something like that) to go beyond that old limit. So ... can post the log?

See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

> The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the GetVolumeInformation function (this value is commonly 255 characters). To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".

**Comment by thezoggy** [comment]
honestly it looks like he just got some really crappy name returned from some raw search site.. 

`317400_FULL_a_b_teevee_EFNet_Full_Frontal_With_Samantha_Bee_S01E10_720p_HDTV_x264_MiNDTHEGAP_full_frontal_with_samantha_bee_s01e.nzb`

**Comment by jkoebel** [comment]
That is literally the case, a crappy name from a crappy raw search site indeed. I added the NZB by having sabnzbd auto-watch a folder into which I downloaded NZBs, which I'd say is probably "manual". Definitely not an RSS.

I shall make sure I am on the latest version, and that the paths are using the correct format, and post the logs if it proves unsuccessful. Thanks for the pointers so far.

**Comment by sanderjo** [comment]
@jkoebel can you give (a pointer to) the NZB so that others can try to download too? I expect it to work on Linux (which I use). If so, it's a problem with SAB on Windows, so indeed possibly due to the Windows path length.

**Comment by RechardSanders** [comment]
try long path tool software for this error

**Comment by FredTorris** [comment]
On my opinion Long path tool program is better option

**Comment by Joaopossagnoli** [comment]
I was suffering from from error more than 248 characters, then i use Long path tool Software, which was proved very helpful for me................... I love it

**Comment by Eduarido** [comment]
I suggest Long path tool.........the only simple solution

**Comment by Eduarido** [comment]
try long path tool

**Comment by FredTorris** [comment]
i suggest Long path tool software
