### ISSUE TITLE
FR: Retry and Send Back to Queue

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#567]
Currently when you click Retry all it does is retry the existing par/rar set.  I know you can add a supplemental NZB when you Retry, but it doesn't retry any of the actual previously missing blocks, it just downloads whatever supplemental files you added.

Because you may have various servers enabled/disabled at any given moment It would be nice to be able to send a file back to the Queue and actually have it retry downloading the missing blocks after you've enabled any servers that were disabled.  Another reason might be because you think the failure could be a propogation problem so you're waiting a few minutes to retry again.
&nbsp;

Also, completely unrelated and not that important, but I noticed these `&nbsp;`'s accidentally showing up in the Connections dialogue under Interface Options:

![al-sab-nbsp](https://cloud.githubusercontent.com/assets/12164957/15007173/a9966b52-118b-11e6-8254-36e251324cc1.jpg)

**Comment by shypike** [comment]
It's way too complicated to patch files up with missing blocks, this has to do with shortcomings of the NZB format.
SABnzbd only tries to "retry" missing files, not incomplete ones.

**Comment by albino1** [comment]
Fair enough, it was worth a shot!  Thanks shypike.

**Comment by thezoggy** [comment]
@Safihre look at the `&nbsp;` issue
