### ISSUE TITLE
ERROR Failed login for server news.caiway.nl, without detailed reason 482 Too many connections for your user (nntpswitch)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#568]
With SABnzbd version: 1.0.1 I get an ERROR `Failed login for server news.caiway.nl`

A manual Test Server says `482 Too many connections for your user (nntpswitch) `, which I find more useful and thruthful.

So can't we change that ERROR message to

`Failed login for server news.caiway.nl: 482 Too many connections for your user (nntpswitch)
`

**Comment by shypike** [comment]
All these server have different fancy error messages.
The problem is that SABnzbd needs to interpret them.
482 isn't even a valid error code, at least not one used by other servers.
What does it mean? Too many connections as such or you're using the account from multiple locations?

**Comment by Safihre** [comment]
Oke so 482 is an official code, but it definition differs, according to this standard it should be:
```482 Authentication commands issued out of sequence```
https://tools.ietf.org/html/rfc4643 

However, this standard says:
```Authentication rejected```
http://www.mibsoftware.com/userkt/nntpext/0032.htm

So I think SABnzbd is following at least the standard that it's an authentication problem, and not a too many connections problem..

**Comment by Safihre** [comment]
Seems other NNTP implementations encountered this problem of servers using the 482 for too-many-connections:
https://sourceforge.net/projects/nntpgolverd/files/

@shypike I will add it to the checks for too-many-connections, just like 481 already is!
That one is also supposed to mean an authentication problem according to the standards
```481 Authentication failed/rejected```

**Comment by Safihre** [comment]
Implemented, close?

**Comment by sanderjo** [comment]
In the main GUI: `Too many connections to server news.caiway.nl`
In the "Test Server": `482 Too many connections for your user (nntpswitch)`

Well done! Thank you
