### ISSUE TITLE
sab 1.0.x -- glitter - removing failed item borks active items of same name

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#573]
a download failed, i queue up a new release of it (same name, different post/group/etc). I then click to remove the failed one, it results in it killing the new download with these errors:

` Disk error on creating file C:\Users\zoggy\downloads\incomplete\Fear.the.Walking.Dead.S02E05.C\59bca670474c482e9740c9389d42eea4.part01.rar `
` Saving \\?\C:\Users\zoggy\downloads\incomplete\Fear.the.Walking.Dead.S02E05.C\__ADMIN__\SABnzbd_nzo_bnv9kq failed `

not sure if it is a glitter only bug (dont know if its passing nzb name to remove or internal nzo id)

**Comment by Safihre** [comment]
It uses the nzo id, not the name!

**Comment by shypike** [comment]
Weird, your second job's folder should end with .1

**Comment by thezoggy** [comment]
the failed download went to an orphan job, i requeued it, that didnt work. so i went and found a new nzb to add.. when it started. i clicked on remove from history for the failed item. upon doing so it nuked the dir of the new download as well and it was aborted after 12%.

**Comment by Safihre** [comment]
Requeing the orphaned job didn't work? Is that where it went wrong?

**Comment by thezoggy** [comment]
so whats jacked up is that the 'failed' download actually completed... but said failed in sab and i didnt realize it actually finished. i moved all the completed sub items to a flash drive and there was already a folder for the release and another with -1. so i wonder if its just a bug where it got flagged as failed incorrectly or never got set to not failed after the orphan job... or what... and then later when i went to remove the failed download it couldnt find it and nuked the matching named one? i have the logs on a flash drive which i left at my current home (which doesnt have internet, why i have a janked setup at the new home with a laptop).. so i'll look at it tomorrow/send logs.

**Comment by Safihre** [comment]
Re-open in case other reports come in!
