### ISSUE TITLE
SABnzbd reports Disk Full -- improvement

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#574]
right now sab sends this email when it reaches a full disk or if the min required space is reached:

subject: `SABnzbd reports Disk Full`
body:

```
Hi,

SABnzbd has stopped downloading, because the disk is almost full.
Please make room and resume SABnzbd manually.
```

probably should report back what the size free was being reported and if/what the min required space is set to..  because i just ran into this and forgot i had it set to require 11gig free... first time i've had a large enough queue that I got hit with this. thankfully i knew about the setting as i would have been puzzled when i got the email and saw that i had 12 gig free (by the time i got the email the previous d/led had finished and did its cleanup)

**Comment by shypike** [comment]
Useful.
Not for 1.1.0, the side effect is that it invalidates all translations of this message.

**Comment by Safihre** [comment]
@thezoggy can you do this maybe? 
Since I never use this function I wouldn't know what is interesting.
Maybe instead of changing the existing translation, just add an additional one that gets appended with the extra info.

**Comment by thezoggy** [comment]
sure

**Comment by Safihre** [comment]
Any news on this?

**Comment by thezoggy** [comment]
forgot about this one, ill see what i can do this weekend

**Comment by Safihre** [comment]
Closing this, but feel free to still make the improvements when you have time 👍
