### ISSUE TITLE
"Configuration is locked" because of ... "External internet access: No Access" setting?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#579]
I'm not sure whether this is an issue/bug, or a feature. I would say it's a matter of incorrect wording

Using SABnzbd.py-1.1.x, with `./SABnzbd.py --server 0.0.0.0:9999`

Via the webinterface from a **remote** system I get:

> Incorrect parameter
> 
> Configuration is locked 

![screenshot from 2016-05-24 22 08 27](https://cloud.githubusercontent.com/assets/1273502/15518306/9d81c9ca-21fc-11e6-80dd-09bdeb8676d8.png)

At that moment the stdout says:
`2016-05-24 22:00:35,313::DEBUG::[interface:105] Refused connection to 62.x.y.z
`

Setting in SAB
External internet access: No Access

![screenshot from 2016-05-24 22 07 38](https://cloud.githubusercontent.com/assets/1273502/15518314/a9f2cf92-21fc-11e6-876b-3ecd4d3f792e.png)

Conclusion:
SAB is not granting access because I told SAB so, but I would expect another (or no) message instead of " Incorrect parameter ... Configuration is locked". Suggestions: "Connection refused" or (more secure) just an empty page.

PS: I must note that this the SAB config that is normally behind a proxy, so listening only to 127.0.0.1. BUT I don't think that matters. Just a note.

**Comment by Safihre** [comment]
Agreed, this message makes no sense.
We could just return a plain ```No access```, that's what is also returned by the API.

**Comment by Safihre** [comment]
https://github.com/Safihre/sabnzbd/commit/9acfbd616dbc943fed0e300f7c4c9256134057c3
Now it will sen a 403-Forbidden status code and show ```Access denied```.

Will put in next pull request.

**Comment by Safihre** [comment]
Fixed now, can be closed!
