### ISSUE TITLE
Download 'size left' or 'total size' not correct

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#580]
@shypike this one is for you I think, I cannot find the problem.

Near the end of download there is still an overshoot, although much smaller than before, showing things like ```1423 / 1413 MB``` at the end of download.
I initially thought it had to do with my prospective par2 download function, however it also happens when you turn that off.

Here is sample NZB on which it happens. On a fast connection you barely see it because it's such a small difference, but it's clearly there.
[TestNZB.zip](https://github.com/sabnzbd/sabnzbd/files/281591/TestNZB.zip)

**Comment by Safihre** [comment]
The French download that gets stuck at 100% also shows this behavior and it being stuck at 100% makes it easy to see how it's showing ```286 / 285 MB``` :sweat_smile:
![image](https://cloud.githubusercontent.com/assets/5703454/15567220/53dcc1c4-2325-11e6-9ef8-ee4c549ebab2.png)

As side-information for that issue, this is what's shown when it gets stuck at 100%:
![image](https://cloud.githubusercontent.com/assets/5703454/15567252/8bd69eb0-2325-11e6-94d1-12e6aad079c9.png)

**Comment by shypike** [comment]
Jiri,

Welke "franse download" is dat dan?
Heb je een NZB?
Blijft ie consistent hangen op 100%?

grtz Con


2016-05-26 9:38 GMT+02:00 Safihre <notifications@github.com>:

**Comment by shypike** [comment]
Solved?

**Comment by Safihre** [comment]
Not yet.
Other things are going wrong when the ```Prospective par2``` adds blocks but not enough. When a download is then re-added it will show something like ```500MB``` left while if you click on the files it will only show for example 2 files of 100MB left. It seems it again counts all the par2 blocks as left.
Right now I don't have the screenshots to prove it.

But I also found another one where things go wrong:
When I try this [SuperSecret.gz](https://github.com/sabnzbd/sabnzbd/files/323291/SuperSecret.gz) download (using only Nextgenusenet) slowly it will start to show that it's missing articles and then near the end it will cancel it because of not enough blocks.
However, when I click Retry. This happens (click for bigger version):
![image](https://cloud.githubusercontent.com/assets/5703454/16193332/d1fd9d44-36ee-11e6-9838-948c3850945f.png)
While actually it already downloaded wayyy more than 355MB, as the filelist shows:
![image](https://cloud.githubusercontent.com/assets/5703454/16193344/e7faef02-36ee-11e6-8adb-5892144e9ea9.png)
