### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by ChristopherHaws** [sabnzbd/sabnzbd#586]
I seem to be having a binding issue on the queue screen that is causing the page not to load. The error that I am getting is:
```
Uncaught TypeError: Unable to process binding "sortable: function (){return { data:queue.queueItems,afterMove:queue.move,options:{ start:queue.dragStart,stop:queue.dragStop,axis:'y',containment:'.queue',distance:10}} }"
Message: Unable to process binding "text: function (){return extraText }"
Message: Cannot read property 'name' of null
Uncaught TypeError: Cannot read property 'name' of null
```

After digging into this a little bit, it appears to be happening at this bit of code:
```
case 'processing':
                // Onload-exception
                if(self.unpackopts() == undefined) return;
                return ko.utils.arrayFirst(self.parent.processingOptions(), function(item) { return item.value == self.unpackopts()}).name;
```

It looks like the value for unpackopts that is comming back from the server is "None" which is then stored in the observable as NaN due to the parse int:
`self.unpackopts(parseInt(data.unpackopts))`

I am not exactly sure what should be in this value, but there either seems to be an issue on the server side where it is returning "None" when it should be a number, or the if statement `if(self.unpackopts() == undefined) return;` should be handling the case of NaN as well.

I am using:
SABnzbd: 1.0.2 [b7e2bd9]
Chrome: 51.0.2704.63 m (64-bit)
Windows: 10 Pro [10.0.10586]

**Comment by Safihre** [comment]
```data.unpackopts``` should only be a value between 1 and 4, never None.
Can you inspect the API data that is send to what it is sending for the ```unpackopts``` for each slot? We have never seen this.

**Comment by Safihre** [comment]
@ChristopherHaws is this still happening? Could you answer my question above if it is still happening?
