### ISSUE TITLE
FR: marked failed and PP when duplicate

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#591]
I'd like to see the option "mark failed and PP" in addition to Off/Paused/Discard. so that SR etc can still get notified.

**Comment by Safihre** [comment]
+1, would also be helpful for Sonarr. Often downloads duplicates when you have multiple indexers.

**Comment by thezoggy** [comment]
but with multiple indexers.. it may not really be a dupe.. just because it is the same name (which triggers sab's dupe detection) its not actually a dupe.. as it was a repost/different group/etc. really should do a dupe score like nzbget computes which is useful to handle this scenario....

**Comment by Safihre** [comment]
@thezoggy No, it also checks using the MD5 of the NZB contents, not just name.

**Comment by thezoggy** [comment]
doh, yeah forgot it does that now.. i think i recall it only does that in certain scenarios (you have nzb folder configured / nzb was provided to sab)..

**Comment by thezoggy** [comment]
just to note, that sonarr shouldnt be d/ling dupes...  it would only send the nzb again or grab another release of the show because it thinks sab failed/lost track of the fact sab completed it....

**Comment by Safihre** [comment]
That's the point, for it to grab another release. 
I've seen it just today: it downloaded the same release (same NZB content) from 3 different indexers sequentially, which all failed, before it tried an actually different release.
