### ISSUE TITLE
Suggestion: if all local, make download PATH clickable

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#597]
A suggestion, especially for @Safihre 

**Short**
If the SAB Webgui is accessed locally (so: from 127.0.0.1 or ::1), make (read: present) the Path clickable as a FILE:// URL

**Long**
Setup / pre-condition: a laptop/desktop, with SAB, saving to a disk in the laptop/desktop (or maybe even a mounted NAS). So: NOT a remote desktop/NAS running SAB.

Currently (SAB 1.0.3 /1.1.0 beta) the Glitter-dropdown-popup will show all details about the download, including the Path (all in plain text). In my case:

> /media/sander/4760a33b-fcbf-4a18-ae6d-e55de0597f30/sander/Downloads/complete/Big.Buck.Bunny.2008.1080p.x264-60fps FIXED

I can use my OS' directory/file browser to go there. But I can also manually copy-paste that Path into my Chrome. Chrome will then show this URL in the URL bar:

> file:///media/sander/4760a33b-fcbf-4a18-ae6d-e55de0597f30/sander/Downloads/complete/Big.Buck.Bunny.2008.1080p.x264-60fps%20FIXED/

... and I can then browse that folder and even play the video from Chrome. Handy.

So, let's use that and skip the manual copy-paste:

Suggestion:
If the SAB Webgui is accessed locally (so: from 127.0.0.1), make the Path clickable.

**Remarks / Things to consider**

* this works for me with Chrome/Chromium and Firefox on Ubuntu Linux. To be tested: MacOS and Windows
* It could go wrong (as in: not accessible) if SAB is running under another account with different rights than the webbrowser user. So be it.
* more info on format and usage: https://en.wikipedia.org/wiki/File_URI_scheme
* ...

**Screendumps**

![sabnzbd and path](https://cloud.githubusercontent.com/assets/1273502/16093547/917500ec-333c-11e6-9d6c-0cc78a07c14b.png)

![sabnzbd path in chrome](https://cloud.githubusercontent.com/assets/1273502/16093550/933d08d4-333c-11e6-8406-de3b0cde6073.png)
![sabnzbd path chrome play](https://cloud.githubusercontent.com/assets/1273502/16093553/9a4e03c6-333c-11e6-8871-d3df07229557.png)

**Comment by Safihre** [comment]
Someone on reddit just asked exactly the same thing last week, and it's not possible. 
Brewers do not allow (for very obvious security reasons) you to click on a file:// link while on a http:// page. So yes, it works when you directly out the file:// in the browser bar, or make a html file locally and open that in the browser. But it won't work from Glitter or any of the skins. 
See Google for "open local file from html page". It used to be possible 10 years ago or so.

**Comment by sanderjo** [comment]
> Brewers do not allow 

Hahaha, cool!

Seriously: I verified your statement, and you're correct: a FILE:// in a HTTP-page is converted to http://localhost/media/sander/4760a33b-fcbf-4a18-ae6d-e55de0597f30/sander/Downloads/complete/Big.Buck.Bunny.2008.1080p.x264-60fps%20FIXED and thus not found.

Pity.

Thanks.
