### ISSUE TITLE
smpl status page doesn't display: cannot find 'lastmail'

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#598]
> Traceback (most recent call last):
> 2016-06-15 22:09:48,399::ERROR::[_cplogging:216] [15/Jun/2016:22:09:48] HTTP 
> Traceback (most recent call last):
>   File "/tmp/SABnzbd-1.1.0Beta1/cherrypy/_cprequest.py", line 670, in respond
>     response.body = self.handler()
>   File "/tmp/SABnzbd-1.1.0Beta1/cherrypy/lib/encoding.py", line 217, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "/tmp/SABnzbd-1.1.0Beta1/cherrypy/_cpdispatch.py", line 60, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "/tmp/SABnzbd-1.1.0Beta1/sabnzbd/interface.py", line 2568, in index
>     return template.respond()
>   File "_tmp_SABnzbd_1_1_0Beta1_interfaces_smpl_templates_status_tmpl.py", line 214, in respond
> NotFound: cannot find 'lastmail'

1.1.0beta1(a) on ubuntu. Originally reported on irc by nrk666.

**Comment by shypike** [comment]
Fixed.
