### ISSUE TITLE
API Queue action - add by fileupload: not implemented

### ISSUE THREAD

**Issue by danielweisss** [sabnzbd/sabnzbd#599]
See: http://wiki.sabnzbd.org/api#toc29
I tried to build a post request in fiddler with the following parameters: 

http://127.0.0.1:8080/sabnzbd/api?apikey=abc&mode=addfile

Header: 
`Content-Type: multipart/form-data; charset=UTF-8; boundary=--<CUSTOM_BOUNDARY>`

Body: 
```
--<CUSTOM_BOUNDARY>
Content-Disposition: form-data; name="output"

json
--<CUSTOM_BOUNDARY>
Content-Disposition: form-data; name="name"

Freaky NZB Name
--<CUSTOM_BOUNDARY>
Content-Disposition: form-data; name="nzbfile"; filename="Freaky NZB Name.nzb"
Content-Type: application/x-nzb

<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.nzbindex.com/nzb-1.0.dtd">
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
<file>
[...]
</file>
</nzb>
--<CUSTOM_BOUNDARY>
Content-Disposition: form-data; name="apikey"

abc
--<CUSTOM_BOUNDARY>--
```

Return Code is 200 with content: not implemented

I tried the latest V1.1.0Beta1 Build and V1.0.3. 

Have i made some errors or is it really not implemented? Could it be fixed? I have no clue about python. 

Best regards
Daniel

**Comment by Safihre** [comment]
You're missing the  ````mode=addfile``` parameter!

**Comment by danielweisss** [comment]
@Safihre: Yeah, sorry. I forgot to write the mode in the sample. It's still the same error - even if it's in URL or body. Did the same request work for you if you add the mode to the URL?

Thanks in advance.

**Comment by Safihre** [comment]
Seems to work fine here? But I use a html request using a form, so not sure if that's the same?

**Comment by shypike** [comment]
With curl it works like this:
```curl
curl http://localhost:8080/sabnzbd/api -F apikey=APIKEY -F mode=addfile -v -F output=json -F "name=@$HOME/my_show.nzb" -F "cat=tv"
```
