### ISSUE TITLE
Plush doesn't show Retry for a failed job

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#600]
Scenario:
- Load an NZB in paused mode
- Remove all files
- The job drops to History
- Glitter shows "Retry" symbol
- Plush does not show Retry link

**Comment by Safihre** [comment]
Cannot reproduce.
Does Glitter show only the symbol, or also the actual *Retry* text? Because without the text, you can't retry in Glitter either. Has to look like this:
![image](https://cloud.githubusercontent.com/assets/5703454/16172356/49ed7be4-3587-11e6-9381-c6ad81372604.png)

**Comment by shypike** [comment]
Glitter shows the symbol.
Plush shows nothing.
BTW: glitter sometimes needs a full refresh to actually show the symbol. Apparently the transition from being in the history and being retryable is not w trigger for an update.
