### ISSUE TITLE
smpl black & smple white themes can no longer access warnings page

### ISSUE THREAD

**Issue by MrsAngelD** [sabnzbd/sabnzbd#602]
I can no longer access the warnings page on either the smple black or smple white themes. Clicking warnings doesn't access anything.

**Comment by Safihre** [comment]
Yep, we broke it! :hamster: 
Already fixed, for next beta (#598)

**Comment by MrsAngelD** [comment]
Hi @Safihre just curious, but any idea when the next update is coming :)
