### ISSUE TITLE
Suggestion: Check for not-the-same directories as that causes problems

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#604]
In https://forums.sabnzbd.org/viewtopic.php?f=2&t=21002#p106899 , shypike writes:

> Completed and watched should not be the same folder.

If so (and yes, it's so), I propose SAB should check for it and not allow "same directories". So complete and incomplete (aka temp) should be different, completed and watched should be different.

```
$ cat ~/.sabnzbd/sabnzbd.ini | grep _dir | grep "/"
dirscan_dir = /home/sander/Downloads/sab-watch
nzb_backup_dir = /home/sander/.sabnzbd/nzb-backup/
download_dir = /media/sander/4760a33b-fcbf-4a18-ae6d-e55de0597f30/sander/Downloads/incomplete
complete_dir = /media/sander/4760a33b-fcbf-4a18-ae6d-e55de0597f30/sander/Downloads/complete
script_dir = /home/sander/sabnzbd/post-processing-scripts
```

So these are all directories? And they all should be different, shouldn't they?

How do you think on checking for that? At startup? @Safihre It is also possible to check for in the GUI?

**Comment by shypike** [comment]
It's not absolute.
If they're the same you run some risk of picking up NZB files that were downloaded.

**Comment by shypike** [comment]
Same for scripts.
Only incomplete and complete must be really be different, which is checked.

**Comment by thezoggy** [comment]
maybe just add a warning on startup ?

**Comment by Safihre** [comment]
It is **not**  possible to set the same directory for complete and incomplete, just try to do it. 
SAB will automatically change it (need to refresh the Config page to see it) to unique directories.
So no clue how this user managed to set the same directories, shouldn't be possible.

**Comment by thezoggy** [comment]
its not possible via the gui? what about manually? startup arguments? init scripts?

**Comment by sanderjo** [comment]
Guys, if we do not agree if it's OK / a bit OK / real bad when directories are the same, we should not find a programmatic solution. 

I still think it is unwise as it can cause problems (and thus it will #murphy) so I would forbid it, but shypike said:

> Only incomplete and complete must be really be different, which is checked.

So ... shall I close this issue?

**Comment by shypike** [comment]
I think the current check is sufficiënt.
