### ISSUE TITLE
AttributeError: NzbObject instance has no attribute 'to_be_removed'

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#605]
Windows 10, latest dev.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27x64\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "H:\usr\local\sabnzbd\sabnzbd\postproc.py", line 198, in run
    if nzo.to_be_removed:
AttributeError: NzbObject instance has no attribute 'to_be_removed'
```

**Comment by shypike** [comment]
Did you upgrade with an existing queue?
Just us full queue rebuild to solve the issue.
This is the risk you run when using the "latest".

**Comment by labrys** [comment]
Yes i upgraded with existing queue.  I appreciate the quick response.

**Comment by Safihre** [comment]
I am guessing that queue rebuild on your mega queues might take a while ;)

**Comment by labrys** [comment]
lol probably will, so I'll let you know in a few days when it's done :stuck_out_tongue_winking_eye:

**Comment by shypike** [comment]
We'll fix the incompatibility.

**Comment by shypike** [comment]
Should be fixed now.
528c7c14104b466bb1ec5524319eccdf672383d6

**Comment by labrys** [comment]
After testing for a while i can confirm this no longer occurs.
