### ISSUE TITLE
Feature request: Disk free calculation with category

### ISSUE THREAD

**Issue by hawkeye73** [sabnzbd/sabnzbd#608]
When downloading the system calculates disk free based on your default download location. If you are downloading more than free on this location via a category which is located on another disk it still mentions not enough disk space. Would be nice, in the future, if choosen category which has another disk assigned it calculates the space free on that drive :)

**Comment by shypike** [comment]
This rather tricky.
SABnzbd can be working on multiple jobs at once. So which one to show?
In retrospect, may we shouldn't have shown free disk space for the "final" drive...

**Comment by Safihre** [comment]
We cannot really do this, I just don't see a way to do this in a performance effective manor.

**Comment by hawkeye73** [comment]
I understand. Performance is king so don't worry. Thanks for replying. 


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Safihre <notifications@github.com> Datum: 06-07-17  11:37  (GMT+01:00) Aan: sabnzbd/sabnzbd <sabnzbd@noreply.github.com> Cc: hawkeye73 <rdevrede@yahoo.com>, Author <author@noreply.github.com> Onderwerp: Re: [sabnzbd/sabnzbd] Feature request: Disk free calculation with category (#608) 
We cannot really do this, I just don't see a way to do this in a performance effective manor.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sabnzbd/sabnzbd","title":"sabnzbd/sabnzbd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sabnzbd/sabnzbd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Safihre in #608: We cannot really do this, I just don't see a way to do this in a performance effective manor. "}],"action":{"name":"View Issue","url":"https://github.com/sabnzbd/sabnzbd/issues/608#issuecomment-313347359"}}}
