### ISSUE TITLE
Forum: login is in plain text / HTTP, so eavesdropping is easy

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#613]
Hi,

Fact: a login via http://forums.sabnzbd.org/ sends the forum username & password in plain text over HTTP. So someone listening on the line can harvest the login credentials. See wireshark screendump.

I would say: not good.

I would suggest doing **all** the forum stuff via HTTPS. Just like other sites (like Github and Google and Facebook for example) do it. It is 2016, after all, so HTTPS should be the default.

And if that is not possible for some reason: at least do the login encrypted and/or via HTTPS.

Wireshark log: See the orange lines for the login "piet" / "ikbengek":

![sabnzbd forum login](https://cloud.githubusercontent.com/assets/1273502/16595747/0bf508a8-42f1-11e6-98e9-76288b7a09d7.png)

**Comment by jeffgeorge** [comment]
Now that we've removed the main SSL host from that server, I think I can safely set up a full 301 from http > https for forums.sabnzbd.org. I'll put that in place tonight and see how it goes.

**Comment by shypike** [comment]
Yes, please. I keep ending up in HTTP when I follow links in notification emails :(

**Comment by jeffgeorge** [comment]
```
$ curl -I http://forums.sabnzbd.org
HTTP/1.1 301 Moved Permanently
Date: Tue, 05 Jul 2016 21:24:50 GMT
Connection: keep-alive
Set-Cookie: __cfduid=d26e9a61bb932e218326c90b24476d9c11467753890; expires=Wed, 05-Jul-17 21:24:50 GMT; path=/; domain=.sabnzbd.org; HttpOnly
Location: https://forums.sabnzbd.org/
Server: cloudflare-nginx
CF-RAY: 2bdde2d5118b50d4-MIA
```

Works for me now, does this work for everybody else?

**Comment by Safihre** [comment]
:+1: works here! Redirected automatically to https.

**Comment by Safihre** [comment]
Time to update the logo and favicon? ;)

**Comment by jeffgeorge** [comment]
Yeah that's on my list for tonight as well.

**Comment by sanderjo** [comment]
Yes, works for me with Chrome and Firefox.

I will close this issue.

Thank you

**Comment by sanderjo** [comment]
Nice: https://forums.sabnzbd.org/search.php?search_id=unreadposts now directly leads me to the page with posts I've not yet read, without the annoying separate login screen that was always there.

:-)
