### ISSUE TITLE
sab - 1.1.x -- enable_https_verification

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#614]
noticed that in sab 1.1.0b1 that this looks to be defaulted to off.. per wiki it says it defaults to on. just placing this here to see if we need to update wiki or if theres a bug

![https](http://zoggy.net/2016-07-05_14-29-37.png)

**Comment by shypike** [comment]
The Wiki needs updating.
We decided to turn off verification to avoid endless complaints.
Not good perhaps.
We should probably enable it in 1.2.0

**Comment by thezoggy** [comment]
i'd suggest that dropping python 2.6 and enabling https verification by default should prob happen at the same time..

**Comment by shypike** [comment]
Older 2.7's don't support verification either. It only started with 2.7.10

**Comment by thezoggy** [comment]
correct, but just saying that if your going to force people to 2.7.x they most likely are going to be on the 'latest' which at this time is 2.7.10+

**Comment by Safihre** [comment]
By default QNAP seems to be on 2.7.3 though:
https://github.com/sabnzbd/sabnzbd/issues/594#issuecomment-225467034

Although most people will use his packages, so they should get 2.7.10+ installed.

**Comment by sanderjo** [comment]
I turned on Special -> enable_https_verification, filled out bad site https://nzindex.nl/  and the **stdout** says:

```
2016-07-07 19:47:51,628::INFO::[rss:570] Starting scheduled RSS read-out for "foute nzbindex.nl"
2016-07-07 19:47:51,628::DEBUG::[rss:370] Running feedparser on https://nzbindex.nl/rss/?q=blabla&sort=agedesc&max=25
2016-07-07 19:47:51,673::DEBUG::[rss:372] Done parsing https://nzbindex.nl/rss/?q=blabla&sort=agedesc&max=25
2016-07-07 19:47:51,674::INFO::[rss:396] Failed to retrieve RSS from https://nzbindex.nl/rss/?q=blabla&sort=agedesc&max=25: hostname u'nzbindex.nl' doesn't match either of 'www.nzbindex.com', 'nzbindex.com'
```
So `hostname u'nzbindex.nl' doesn't match either of 'www.nzbindex.com', 'nzbindex.com'` on stdout, but no message/warning in the SAB GUI. **Is that clear enough for users?**

I would say: turn on enable_https_verification by default, BUT
1) with a clear message in the SAB GUI
2) in the error message, point out that the user can turn off enable_https_verification if he/she want so ...


**Then some remarks FWIW**

It started with Python 2.7.9: see my post from Jan 2015 https://forums.sabnzbd.org/viewtopic.php?f=1&t=18565 

The SSL/TLS setup problems can be 
- server side. Like https://nzindex.nl/
- client side. Probably minimal-OS devices likes NASes

**Comment by Safihre** [comment]
If we indeed could print the error plus the message that they can disable it, that would be great. 
Is there a general way to specifically catch these errors?

**Comment by shypike** [comment]
Hmm, this used to work. It showed a proper error message.
I'll check.

**Comment by shypike** [comment]
It does work properly though, it shows URL Fetching failed; Server uses an untrusted HTTPS certificate.
Tested just now on Windows.
@sanderjo  Do you get other results on Linux?

**Comment by sanderjo** [comment]
Yes, on Linux. But don't get alarmed: it might a problem specific with NZBindex: nzbindex.com itself is unreliable with RSS, and nzbindex.NL adds the problem with SSL/TLS. So: "Vlek op vlek"?

So: which RSS feed site did you test against? I will test again with your RSS site.

**Comment by shypike** [comment]
I  just added the URL directly (no RSS): https://nzbindex.nl/bla.nzb

**Comment by sanderjo** [comment]
> I just added the URL directly (no RSS): https://nzbindex.nl/bla.nzb


When I do that, I only get
`Failed to retrieve RSS from https://nzbindex.nl/bla.nzb: hostname u'nzbindex.nl' doesn't match either of 'www.nzbindex.com', 'nzbindex.com'`
This is on 1.1.0RC1 on Linux

**Comment by sanderjo** [comment]
the relevant sabnzbd/rss.py:
```
            if 'bozo_exception' in d and not entries:
                msg = str(d['bozo_exception'])
                if 'CERTIFICATE_VERIFY_FAILED' in msg:
                    msg = T('Server %s uses an untrusted HTTPS certificate') % get_urlbase(uri)
                    logging.error(msg)
                else:
                    msg = T('Failed to retrieve RSS from %s: %s') % (uri, xml_name(msg))
                logging.info(msg)
                return unicoder(msg)
```
So `if 'CERTIFICATE_VERIFY_FAILED' in msg:` apparantly is False, as I don't get the 'Server %s uses an untrusted HTTPS certificate' ...

TBC

**Comment by Safihre** [comment]
Tested the RSS on Windows, the behavior is identical to Linux. Only an Info message about it.

**Comment by shypike** [comment]
Ah, right. The error handling of the actual RSS-feed doesn't check for this specific error.
Only the urlgrabber does for NZB requests.

**Comment by Safihre** [comment]
So if the error is caught correctly, should we maybe add a link to the Wiki or something where we can explain the reason and how to disable the verification?
After this we could enable certificate checking by default? Maybe change the special from ```enable_https_verification``` to ```disable_https_verification``` so it's enabled by default for everyone?

**Comment by sanderjo** [comment]
> So if the error is caught correctly, should we maybe add a link to the Wiki or something 
> where we can explain the reason and how to disable the verification?

Please keep it self-contained in SABnzbd. Just like the current "Orphaned Jobs ... click on blabla to solve this", which I like very much
And yes, additionally provide a link to the Wiki. But we can't solve certificate problems on peoples' NAS-devices ...

**Comment by shypike** [comment]
When you define a new RSS feed with a bad certificate or read it manually, it will show a visible error message.
Subsequent automatic read-outs will not.
It seems to me that this is good enough.

I'm not sure yet whether setting it by default to ON is a good idea.
We should move it from Special to Switches though.

**Comment by Safihre** [comment]
Agreed.
In the General section of the Switches page?

**Comment by shypike** [comment]
Switches. General is 90% about the webserver.
Some more reorganization is needed for a later release.

**Comment by Safihre** [comment]
I meant the sub-header General on the Switches page ;)

**Comment by shypike** [comment]
"General" or "Server". It's arbitrary; you choose.

**Comment by Safihre** [comment]
Option is now available in Switches, clearly for the user to see and choose.
