### ISSUE TITLE
Update icons in OSX installer

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#615]
The old logo is still shown on the DMG and in the installer. See below for a PNG version of the full logo :)

Could you maybe also remove that background gradient? Make the background all white or all grey?

![image](https://cloud.githubusercontent.com/assets/5703454/16610559/3b14923c-435c-11e6-8d18-2cecb53285ec.png)

![logo-full](https://cloud.githubusercontent.com/assets/5703454/16610592/7cb07ee0-435c-11e6-8f23-f507ced8d552.png)

**Comment by Safihre** [comment]
Also the logo in the notifications is not updated:
![image](https://cloud.githubusercontent.com/assets/5703454/16831896/d5414b9c-49a7-11e6-9344-535f4be35903.png)

**Comment by shypike** [comment]
Icon was updated in RC2.
The installer will be updated in Final.
