### ISSUE TITLE
Restarting SABnzbd behind reverse proxy redirects to incorrect URL

### ISSUE THREAD

**Issue by phobozad** [sabnzbd/sabnzbd#618]
When restarting the server after e.g. a config change, the browser is redirected to an incorrect URL.

This is seen with the following setup:

Reverse proxy (nginx) listening on port 80
SABnzbd listening on port 8079

URL used to access SABnzbd: http://sabnzbd.example.com
URL that SABnzbd redirects to after restarting: http://sabnzbd.example.com:8079

**Comment by thezoggy** [comment]
can you post your redirect/proxy info?

**Comment by phobozad** [comment]
Here is the nginx config:
```
server {
        listen          [::]:80;
        server_name     sabnzbd sabnzbd.example.com;
        location / {
                proxy_pass              http://127.0.0.1:8079;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_buffering off;
        }
}
```

**Comment by sanderjo** [comment]
@phobozad 

No problems with my SAB-behind-a-proxy (Apache, BTW).

So:
which SABnzbd version do you use?
which skin do you use?

**Comment by phobozad** [comment]
This is on 1.0.3 with the Glitter skin. 

@sanderjo Are you running your SAB server on a different port than your reverse proxy?

**Comment by sanderjo** [comment]
> This is on 1.0.3 with the Glitter skin.

OK, good; so the skin is not the problem.

> Are you running your SAB server on a different port than your reverse proxy?

Of course (two servers on one port is not possible):
SAB on port 127.0.0.1:11111
Reverse proxy on [::]:80

**Comment by Safihre** [comment]
@sanderjo He is right, this does not work and also can't work in your case:
When you change a setting on the _General_ page of the Config that requires a restart and you click yes when it asks you to, you will be redirected to the port that is specified on the General page.
This is by design.. How can SAB know what your proxy settings are? All it knows is that on that page you set port 8079, so this is what it will redirect you to. Maybe you changed it, that's why we redirect to that port, and not the port you came from.

Technically we could only redirect to the port set in the Config when it's changed, of course.

**Comment by sanderjo** [comment]
> When you change a setting on the General page of the Config that requires a restart and you click yes when it asks you to, you will be redirected to the port that is specified on the General page.

Ah ... we were talking about different Restart use cases:

I did a restart via the three-lines icon "Restart SABnzbd". I then get "Lost connection to SABnzbd.. In case of SABnzbd restart this screen will disappear automatically!". Which indeed works, also via the proxy.

You are talking about Config Change -> Restart. I tried that, and I indeed get "Restarting SABnzbd." and then an incorrect URL (mix of unproxied SAB port and proxied FQDN).

So ... can't SABnzbd combine best of both worlds: with the ConfigChange->Restart no URL mentioning or redirect, but just use / cause the "Lost connection" feature, which will pick up automagically?

**Comment by Safihre** [comment]
Yes, but that wouldn't work if someone changed the port.
I guess I will have to add a hidden field to check if the port actually changed, relatively easy to do.

**Comment by sanderjo** [comment]
> Yes, but that wouldn't work if someone changed the port.

Correct. But I would says that's a niche use case. 

> I guess I will have to add a hidden field to check if the port actually changed, relatively easy to do.

Why? If a user changes the SAB port of SAB behind a proxy, he/she also needs to change the settings in the proxy. SAB can't solve that.

So I would ignore the niche use case "user changes sab port setting of sab behind proxy" ... let the user take care of it.

**Comment by Safihre** [comment]
> Why? If a user changes the SAB port of SAB behind a proxy, he/she also needs to change the settings in the proxy. SAB can't solve that.

I meant for non-proxy users, when they change port it should be picked up (like it does now).

**Comment by shypike** [comment]
@sanderjo @Safihre 
My interpretation is: not a use case important enough to spend time on.
Agree?

**Comment by Safihre** [comment]
Agreed, I could fix it, but this would be for a very limited user group.

**Comment by phobozad** [comment]
I'm glad to see this is only an issue when saving changes on the general page.  I assumed when I saw this it would be problematic for all restarts.

Although it would be ideal that the app only redirects to the new port if that setting is actually changed, I understand that the number of cases where this messes things up is likely fairly small.

It looks like the challenge is that the redirect logic is happening entirely on the client site, but the client has no way to tell if the settings change that required us to restart was the port setting.  As far as I can tell that would be the only setting that would require the client to actually change the URL it is attempting to reload, correct?
