### ISSUE TITLE
Retry timer & count for failed NZB indexer

### ISSUE THREAD

**Issue by keithbarrett** [sabnzbd/sabnzbd#620]
Note: I don't believe my problem is the same as discussed in the close thread a#326 

I use a mixture of NZB indexers. Some "low priority" ones have an access limit like "1 every 4 hours" or if you hit a cap you have to wait 7 hrs before trying avain. The end result is that you end up with entries in SABnxbs that look like this:

"Wait 37 sec / Trying to fetch NZB from ..."

Then it fails and retries again....    for hours...

For this specific indexer, my account has a wait of "7 hours" in effect before it will accept this request.

I'd like to set this "retry" interval so that after 3 initial Wait failures, it waits for nnnn minutes before trying again. I realize ideally this would be a "per indexer" setting, but I can live with a global one. In my case, I'd want to set it to about every 3hrs. It would end up looking like:

Trying NZB.... fails
"Wait 60 sec / Trying"...   then fails
"Wait 60 sec / trying" ... then fails
"Wait 10800 sec" ... then fails
"Wait 10800 sec" ... WORKED!

A bonus would be an automatic drop to "low" priority also, so it "sorts" out of the way.

An alternative solution is an automatic geometric climb in time.

wait 1 minute
wait 2 minutes
wait 4 minutes
wait 8 minutes

but this would take many wasted attempts before it waited 3 hours.

**Comment by thezoggy** [comment]
stop being cheap and donate to the sites that have heavy restrictions on api... or just dont use those sites?

**Comment by keithbarrett** [comment]
So your response to a request to improve the wait retry to be more
efficient, more accomodating to real life, and reduce the bandwidth/service
use is to insult your user?

Although it's none of your business how much I spent on what, including the
5 nzb lifetime memberships (counting the 2 that took my money and ran) I
have, I'm not aware of an SABnzbd requirement that it can only be used with
services you pay to subscribe to. These are fallback connections.

Now can we focus on the technology instead of religion please?

**Comment by thezoggy** [comment]
sab already retries urls and already has built in support for sites that do rate-limiting (retry-after). 

but regardless, you want us to sit there and exponentially hit a site because you lack the appropriate api hits..  sounds like something you can easily fix by donating to get higher api limits or applying logic before having sab attempt to fetch the url.. change your method to having sab process a folder, then you just have a script that fetches the nzb and place it in a watch folder.

**Comment by thezoggy** [comment]
i see no reason to waste time and resources to cater to sites with little to no api limits. the sites purposely place low api limits so you can try it out.. if you see value you donate. if you dont like their practice.. then dont and move along. there are plenty of other sites out there. 

and about the money you've spent.. one could easily make the claim you have saved more than you spent? and normally the sites that are asking for a donation are less than what an american spends at a fast food restaurant in a day.

**Comment by keithbarrett** [comment]
I didn't come to debate money religion, or listen to a "buy this" pitch. IThe reality is that some indexers, as well as the option of using their free service, operate this way. The code COULD handle it better, but rather than take pride in doing that you want to ridicule users. I'm sorry your attitude is to "buy more things" than address it in the code so it scales to match reality. I don't buy bigger computers to fix poor programming programs, and I don't pay for additional indexing services because the software is making assumptions instead of providing configurable code.

I'll fork it and add the change in for myself. Thanks for not even considering it.

**Comment by thezoggy** [comment]
sab already retries urls and already has built in support for sites that do rate-limiting (retry-after).

**Comment by keithbarrett** [comment]
In my view, I'm going to help the site by reducing the "ping" demands to them that would go unrewarded, PLUS reduce the overhead on my own computer when I had 45 of these keep retrying for half a day, PLUS reduce the screen clutter of sleeping jobs being shown on the first page PLUS give the user a bit more control over how the retries function. I do not agree with your money dogma, and it disappoints me you started this by dragging that in instad of keeping this technical. You should just have said something more professional like "there isn't enoung demand for it" or "I'll add it to the list but it will have a low priority". Seriously; you have no power to dictate when and where I spend money.

**Comment by keithbarrett** [comment]
BTW the REASON this happens once in a while is because I often watch shows from the 1950s, and the top indexers don't have them. I already pay for 3 services - that is enough.

**Comment by thezoggy** [comment]
so if you only can do "1 every 4 hours" and have 45 of them in your queue already.. maybe its time to donate? since its apparent that you see benefit in using their site...

**Comment by keithbarrett** [comment]
Or you can blow it out your ass since this is a backup site that doesn't accept payments, and fix your bloody software so that it handles reality better.

**Comment by keithbarrett** [comment]
You should give me money for all the contributions I made to Linux for free if you've ever used it.

**Comment by thezoggy** [comment]
Sorry to learn you're such a dick because you didn't get your way.

**Comment by keithbarrett** [comment]
Has nothing to do with getting my way. I had no problem with you saying no
in a technical discussion. You were a dick because the VERY first thing you
said in response was an insult to a user, and madw this about paying or
avoiding capped sites instead of discussing the technical failing of
handling a proper retry protocol.
On Jul 10, 2016 9:16 AM, "thezoggy" <notifications@github.com> wrote:

Sorry to learn you're such a dick because you didn't get your way.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/sabnzbd/sabnzbd/issues/620#issuecomment-231588570>, or mute
the thread
<https://github.com/notifications/unsubscribe/AALZluQ5gGXCxje92iK2Pv4h02x6Sj3Lks5qUPDJgaJpZM4JIqPX>
.

**Comment by keithbarrett** [comment]
And I will get my way. I'll just fix it myself. The only reason I contacted
you was, as a professional developer of communications middlware and Linux
for over 20 years, I'd given you the respect of making the change yourself
in the master for everyone. I can live with it being for just me.

--
*Keith Barrett*

**Comment by shypike** [comment]
Met vriendelijke groet,
Con

**Comment by shypike** [comment]
Guys, this discussion is going nowhere. Please moderate your tone and try to be constructive.

**Comment by keithbarrett** [comment]
Agreed. I had closed this request a while back.
