### ISSUE TITLE
Attempting to unpack split 7z archive can succeed while reporting failure

### ISSUE THREAD

**Issue by rincebrain** [sabnzbd/sabnzbd#624]
On 1.0.3, if I have an nzb which contains things of the form X.7z.001, 002, ..., it will attempt to unpack it and successfully unpack the 7z (and delete the 7z split archive in the incomplete/X/ directory after), but then mark the download as "Failed" and neither copy any other things from the incomplete folder nor rename the folder under the complete dir from "_UNPACK_X".

Since the unpack status looks like "[X.7z][INCOMPLETEDIR/X_foobar/X.7z.001] Unusable RAR file", I would guess that the problem is that it's also trying to treat the partial archive as a rar file and failing, but I'm not familiar enough with the codebase to guess where.

It seems like, from the logfile, it's trying to unrar first, then 7za (probably because the unrar regex matches .\d\d\d and the 7z regex matches .7z.\d\d\d), and the failure of the former is causing it to bail out.

I'm not sure if the desired behavior is to try all and continue if any succeed or fail if any fail, but the latter appears to be the current behavior.

**Comment by shypike** [comment]
You mean, there's no way to tell whether these are split RAR files or split 7Z files?
(Except by looking at the content).
Anyway, it would be helpful if you could email the NZB to bugs@sabnzbd.org

**Comment by shypike** [comment]
Looked at your NZB.
It doesn't come further as a failed verification, due to too many missing articles.
What I see in the code is that SABnzbd first checks for 7z files and only after that for RAR.
Unless you have a better example, there's not much that I can do.

**Comment by rincebrain** [comment]
@shypike I mean, it didn't have missing pieces for me; I can try to find a better example.

**Comment by shypike** [comment]
@rincebrain  Which Usenet provider did you use (please just email me)?
I have 4 different ones, none had it complete.
