### ISSUE TITLE
Notification script doesn't get message

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#627]
Maybe this was a design choice, but the notification script only gets the notification-type and the notification-title send to it.
Why is the ```msg``` not send to it?

```python
ret, output = external_script(script_path, title, gtype)
```

**Comment by shypike** [comment]
Not correct, it should receive the message too. I see. I reason why not.

**Comment by Safihre** [comment]
Discussing with this guy (https://github.com/caronc/nzbget-notify/issues/5) who wrote a Notification script for NZBGet supporting basically _every_ possible notification service and him making a version for SABnzbd, I was wondering if we can add a Parameters field to the Notification script, to be send as a 4th argument.
This way we can supply any script with a config or a setting or something.

**Comment by shypike** [comment]
@Safihre OK, I will.
Interesting conversation BTW :)
