### ISSUE TITLE
FR: Show hidden folders in path browser

### ISSUE THREAD

**Issue by isochronous** [sabnzbd/sabnzbd#63]
I'd really like the ability to show "hidden" folders in linux (folders that begin with a '.' character).  I'm using unraid with an sabnzbd plugin that's stored on the unraid install's cache drive.  The cache drive is a drive that sits outside of the array that's used to cache writes, but also to store data that you don't want on the array itself.  The way it works is a mover script is run every few hours that looks for any directory on the root of the cache drive not beginning with a '.' character, and copies that folder into the array.

Because I want all of SAB's downloads to go to the cache drive, then let sickbeard/headphones/couchpotato do the actual moving to the array, I need to have the downloads folder either be a folder beginning with '.', or be inside a folder beginning with '.', and the default location within the SABNZBD directory won't work because I have two other content downloading applications, and they all need to go to the same directory.

So, I'd like to have the ability to set the default download directory to something like /mnt/cache/.downloads/.incomplete, and have the completed directory just be /mnt/cache/.downloads.  I looked through the pathbrowser.py file and saw the culprit:

```python
# starting at line 81 in pathbrowser.py
try:
    for filename in os.listdir(path):
        fpath = os.path.join(path, filename)
        try:
            if NT:
                doit = (win32api.GetFileAttributes(fpath) & MASK) == TMASK and filename != 'PerfLogs'
            else:
                doit = not filename.startswith('.')    ## <= This line right here
        except:
            doit = False
        if doit:
            file_list.append({ 'name': unicoder(filename), 'path': unicoder(fpath) })
```

While I can understand the reason you'd not include hidden folders by default, it would be nice to at least have a checkbox in the path browser that toggles the setting.  For the time being, I have to modify the source myself, which is great until the plugin auto-updates and overwrites my changes.

I should mention that I've tried manually setting the paths both by editing the .ini file and by typing the correct paths into the text fields associated with the path browser, and it seems to work when I click save, but if I go to a different page in the admin and go back, the folders are back to their original values.

I also did manage to set the proper download location on a per-category basis, and those settings seem to stick, but I'd like to truly make that the default location rather than having to set it per-category.

**Comment by Safihre** [comment]
Added this in PR #423.
