### ISSUE TITLE
Server Username not being saved.

### ISSUE THREAD

**Issue by pmele** [sabnzbd/sabnzbd#632]
Web Interface page: /config/server/
Using Safari on Mac to -
Linux Mint 17.2
AMD 64
Version: 1.1.0RC1 [aa12e21]
Python: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014 [t1, v23, v3]
pyOpenSSL: 0.13
yEnc: Check

Have attempted to modify my username then click save.  It looks like the save completed correctly but the username remains the same when I reload or exit and go back in.  All other settings are saved when changed although I am unable to view the password.

**Comment by Safihre** [comment]
Most probably your browser or Lastpass/KeePass auto filling it. Try again in a different browser, if it also fails there it's a sabnzbd problem.

**Comment by pmele** [comment]
Correct.  Disabled LastPass for Sabnzbd.  Thanks.

I am having an issue in which IPv4 Connection Failed and nothing is being downloaded.  Any ideas, please?

**Comment by pmele** [comment]
The IPv4 connection was finally resolved by restarting the server a couple of times along with apt-get update && apt-get upgrade.
