### ISSUE TITLE
1.1.0RC2 post process script-output "more" link broken

### ISSUE THREAD

**Issue by OldskoolOrion** [sabnzbd/sabnzbd#634]
As the topic states. It's of course not an urgent issue : minor glitch that's all.
Included a clear partial screenshot of the issue - I don't think much more additional info is needed from the logfile (of sab and/or script), but if need be I can post it.

![sabnzbd_1 1 0rc2_small_issue](https://cloud.githubusercontent.com/assets/13029885/17080447/7b2e53d0-5130-11e6-9df5-fe11b6a6aec8.jpg)

**Comment by Safihre** [comment]
Oops, my fault. Will fix!

**Comment by OldskoolOrion** [comment]
Damn.. i'll have to find the location in the source first, so I won't race you :-)  Thanks for all the effort put in !
