### ISSUE TITLE
Force does not start downloads

### ISSUE THREAD

**Issue by pmele** [sabnzbd/sabnzbd#637]
I only allow downloading thru the scheduler at certain times due to working from home.  Went in to force a paused download that was almost complete.  All worked fine.  Then tried to complete a couple more.  Would not continue with Force priority.  Had to restart Sabnzbd for it to continue.

When those were complete I selected a few to Force that have not started.  Once again the downloads would not start.  Had to restart Sabnzbd again to have them start.

**Comment by thezoggy** [comment]
check logs.. prob due to lack of free space (over the free space required threshold) / unable to write to admin or incomplete folder...

**Comment by pmele** [comment]
That setting is blank.

Trying to Force one already in the queue does not work without a restart whereas if I Add a NZB and select Force before upload it works fine without restarting.

**Comment by Safihre** [comment]
I tried to reproduce it.. But I can't.
Are you on RC2 now? Does it help if you pause and unpause the download that you put to force?

**Comment by pmele** [comment]
I am on RC1.  Can I just copy the new files into the current directory and overwrite the current files to update my copy?  I tried apt-get update and upgrade but it stays at the same RC1.

I did try pausing and unpausing.  When paused it properly displays 0 time left and 0 KB/s.  Unpause and it just display a dash and nothing happens.  Still have to restart to get it working.

**Comment by thezoggy** [comment]
check logs, should say why its blocking the downloads.. (lack of free space / unable to write to dir)

**Comment by pmele** [comment]
Nothing mentioned.  Looked at the debug logs.  Checked space on the server.  I have gigabytes free on all volumes.  TB on the download directories.

**Comment by Safihre** [comment]
Could you send us the logs? Set it to Debug in the Status window, then try to force a download. After that, download the log and send it to us at bugs@sabnzbd.org or Safihre@sabnzbd.org.

**Comment by Safihre** [comment]
No more response, can be reopened if occurs again!
