### ISSUE TITLE
Very high load by downloaden with mac version 0.7.7

### ISSUE THREAD

**Issue by whitecollar17** [sabnzbd/sabnzbd#64]
OS: Mac osx 10.6.8
Processor: 2.66ghz intel core 2 duo
memory: 2 gb

When we download a movie the download speed is extremely slow. I have a fiber 100/100 connection and a usernet account with 30 connection and a unlimited speed limit.

When i test my connection with speedtest.net  the results are: download: 95 mbit and upload 90 mbit
I check the load on my cpu and its 85% +/-. Maybe its a bug in sabnzbd?

**Comment by shypike** [comment]
Cannot reproduce.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
