### ISSUE TITLE
Notes on os.path.join()

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#646]
<Work in progress>

Here are some notes on os.path.join() used by SABnzbd in 142 lines of code, which can cause new problems as of SAB 1.0.0, which introduced Unicode as the default encoding.

Goal of this post: document, possible solutions, constructive and concrete feedback.

**The problem with os.path.join()**
 
Examples of reported problems caused by os.path.join() in SAB 1.x:
- https://github.com/sabnzbd/sabnzbd/issues/644#issuecomment-238053518
- https://github.com/sabnzbd/sabnzbd/issues/570#issuecomment-219504191

**Examples of bad and good**

In a nutshell: a join of a unicode string with a string with non-ASCII chars in a non-unicode encoding gives a traceback. Example:

```
>>> print os.path.join( u"/blabla", u"müller".encode('cp1252') )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 2: ordinal not in range(128)
```

Please note the following joins go OK:

Join of unicode and cp1252 but no special characters in the cp1252:
```
>>> print os.path.join( u"/blabla", u"muller".encode('cp1252') )
/blabla/muller
```

Join of plain ASCII with a cp1252-with-non-ASCII-characters:
```
>>> print os.path.join( "/blabla", u"müller".encode('cp1252') )
/blabla/m�ller
>>> print os.path.join( u"/blabla".encode('ascii'), u"müller".encode('cp1252') )
/blabla/m�ller

```

**So ... what could we do**

- We could do nothing; we consider the above problem a niche aka edge case
- We could build a 'fence' around SABnzbd to only accept ASCII or unicode as input, and actively reject any other encodings of files and strings
- We could re-actively wait for problems, and then solve/workaround it
- We could pro-actively replace all os.path.join() with a safe function

**Solve/workarounds and Safe function**

1) In https://github.com/sabnzbd/sabnzbd/issues/644#issuecomment-238054629 I just remove characters >= 128. That looks safe in that situation.
2) in `path` variables, only use Unicode if necessary. If not necessary, use ASCII encoding. Then, if a strange `file` name appears, much less change that the os.path.join() gives a traceback
3) Another solution could be: if the os.path.join(path, file) gives a traceback, we could try to downgrade 'path' to plain ASCII, and then try to join.

```
>>> path = u"/blabla"      # unicode, but NO special characters
>>> file = u"müller".encode('cp1252')
>>> 
>>> os.path.join(path, file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 2: ordinal not in range(128)
>>> 
```
... Ah, traceback ... let's try this 
```
>>> os.path.join(path.encode('ascii'), file)
'/blabla/m\xfcller'
>>> 
```
Hey, that works! Explanation: `path = u"/blabla"` can be safely converted to ASCII encoding.
The result of the join looks a bit strange, but the OS seems to be able to handle that:

Let's start:

```
>>> path = u"/tmp"
>>> file = u"müller".encode('cp1252')
>>> os.path.join(path, file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 2: ordinal not in range(128)
```

Ouch. Let's try to fallback to ASCII for the `path` :

```
>>> 
>>> os.path.join(path.encode('ascii'), file)
'/tmp/m\xfcller'
```

Good, no traceback, so let's continue:

```
>>> fullname = os.path.join(path.encode('ascii'), file)
>>> with open(fullname, "w") as text_file:
...     text_file.write("hello, world")
... 
>>> 
```

Let's check if it worked:

```
sander@flappie:~$ ll /tmp/m�ller 
-rw-rw-r-- 1 sander sander 12 aug  8 22:16 /tmp/m?ller
sander@flappie:~$ 

```

So the OS (Linux) is fine with it.

Just my thoughts so far ...

**Comment by shypike** [comment]
If I understand this correctly, this happens on systems that have a mismatch between the name encoding as reported by the Python library and the actual encoding?

**Comment by sanderjo** [comment]
> If I understand this correctly, this happens on systems that have a mismatch between the name encoding as reported by the Python library and the actual encoding?

No, it happens on perfect systems.
It happens where SAB 1.x.x tries to handle a file with a special character encoded with something else than unicode.

**Comment by thezoggy** [comment]
@sanderjo  http://bugs.python.org/issue9425 ?

**Comment by sanderjo** [comment]
> @sanderjo http://bugs.python.org/issue9425 ?

I read that, but I couldn't find a relation. It was a patch in python in 2010, so to be sure I tried python 3:

```
$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> path = u"/tmp"
>>> file = u"müller".encode('cp1252')
>>> os.path.join(path, file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/posixpath.py", line 89, in join
    "components") from None
TypeError: Can't mix strings and bytes in path components
>>> 
```
So, also a problem in python3.

> how kodi dealt with it: http://kodi.wiki/view/Add-on_unicode_paths

Seems to be about the difference between  unicode and utf-8? Not about other encodings?

Maybe I'm wrong, so if you could post a few lines of code how to solve it, I would appreciate it. So code that starts with
```
>>> import os
>>> path = u"/tmp"
>>> file1 = u"müller".encode('cp1252') # western-european
>>> file2 = u"ΔΠ".encode('cp1253')   # Greek
```
... and then a successful os.path.join ...

**Comment by shypike** [comment]
@sanderjo 
> No, it happens on perfect systems.
>It happens when SAB 1.0.x tries to handle a file with a special character encoded with something else than unicode.

Where does the "special character encoded with something else than unicode" come from? It's either a bug in SABnzbd (for not converting some path parts to Unicode) or a less than perfect system.
I'll look into it further, but so far I haven't been able to reproduce it.

**Comment by sanderjo** [comment]
@shypike I'm working on this. It's quite hard to solve it in a nice way. One of my workarounds resulted in:
```
/home/sander/git/sab-sanderjo-11aug2016/sabnzbd/dirscanner.py:239: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if os.path.join(folder, name) == path:
```

To be complete, I'll send you a problematic nzb file that will cause the dirscanner crash.

**Comment by Safihre** [comment]
So we don't need #654 anymore? The current fixes are enough?
