### ISSUE TITLE
Retry not shown

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#647]
I noticed since a few commits (cannot pinpoint it), that jobs that were aborted because hopeless don't show 'Retry' and show up in Orphaned Jobs.
![image](https://cloud.githubusercontent.com/assets/5703454/17510103/c7002ab4-5e1d-11e6-9200-038b9ca374bc.png)

I did detective work and in ```build_history``` there is this check:
```python
        item['retry'] = int(bool(item.get('status') == 'Failed' and
                                 path and
                                 path not in retry_folders and
                                 starts_with_path(path, cfg.download_dir.get_path()) and
                                 os.path.exists(path)) and
                                 not bool(globber(os.path.join(path, JOB_ADMIN), 'SABnzbd_n*'))
```
This one is the "problem":
```python
not bool(globber(os.path.join(path, JOB_ADMIN), 'SABnzbd_n*'))
```
Because there is a file matching ```SABnzbd_n*``` left in the job's folder:
![image](https://cloud.githubusercontent.com/assets/5703454/17510157/004c1c56-5e1e-11e6-8db1-573ea7fc6d3e.png)

Judging from this check, there shouldn't be any  ```SABnzbd_n*``` files left, but there are. 
I have seen it a couple of times already over the past month or so. 

Could be related to #573?

**Comment by shypike** [comment]
This code section was introduced in 2010 with commit 68b7c5f04934a08ebc1228213f7ce61df8ed785d, described as `Only show retry links in History when associated incomplete folder exists`. It was moved later from `interface.py` to `api.py`.
It was added as one block and never meaningfully changed.
I don't know why the test for SABnzbd_nzo* was included. The text suggests that any failed incomplete folder is eligible for retry, as long as it's actually present.

We could remove the test, but it did work properly before.
We should probably look first why the files were left behind.
I don't see the relation with #573.
Can you see in the logging why the admin files were not removed?
Any error messages?

**Comment by shypike** [comment]
Only items with status "Failed" qualify and this is an end state.
However, there is a time window between setting the status to "Failed" and the actual removal of the admin files. It's likely that the test for admin files prevents the job from being "retry-able" before the post-processor has finished its work.

**Comment by Safihre** [comment]
I queued up a bunch of files that I knew would fail and it fails half of the time.
When I look in the job folder I see:
![image](https://cloud.githubusercontent.com/assets/5703454/17511765/cd95d6e2-5e24-11e6-9639-90b4d4edaa81.png)
But SAB actually thinks it removed it succesfully:
```2016-08-09 11:21:53,960::INFO::[__init__:918] \\?\C:\SABnzbd\The Big Bang Theory S09E18 1080p HDTV x265-KRAVE\__ADMIN__\SABnzbd_nzo_gq8gwa removed```



![image](https://cloud.githubusercontent.com/assets/5703454/17511753/bf54942e-5e24-11e6-8dd8-1300e7e2cd16.png)

**Comment by shypike** [comment]
Maybe the file is being recreated after the delete. Do the timestamps (in the log and of the actual files) tell you anything?

**Comment by Safihre** [comment]
On Windows I can only see seconds in PowerShell, but it seems indeed that it was still modified somehow after being deleted:
```
11:44:07 CreationTime (powershell)
11:45:08,141 SAB says removed
11:45:09 LastAccessTime (powershell)
11:45:16 LastWriteTime (powershell)
```

**Comment by Safihre** [comment]
Aaaannddd it's back.
