### ISSUE TITLE
sab 1.1.x -- glitter tabbed layout

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#649]
on tabbed layout, errors show up at the bottom for the queue but up top for history..  shouldnt they be in the same spot on either tab?

**Comment by Safihre** [comment]
You are right, but since I can't move the HTML I opted to just make the warnings into their own seperate tab. Kind of like NZBGet, but only when there's warnings/errors.

![image](https://cloud.githubusercontent.com/assets/5703454/17642387/89f0afac-6144-11e6-8596-15b85958a1b4.png)

**Comment by Safihre** [comment]
Solved in #658, can be closed.
