### ISSUE TITLE
Suggestion: move switches to Specials for Unrar/Unzip/7zip/FileJoin/TSJoin

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#656]
They have always been on the Switches page.. but why? What regular user would ever disable them?
I suggest to move them to Specials, so in the exotic use-case it should be disabled, the user can still do that.

**Comment by shypike** [comment]
Agreed.
Personally, I have unzip disabled, because ZIP files usually carry nonsense I don't want unpacked.

**Comment by Safihre** [comment]
Solved in #658.
