### ISSUE TITLE
Feature Request: Option to show days remaining when past 23 hours

### ISSUE THREAD

**Issue by altech6983** [sabnzbd/sabnzbd#657]
I have rather slow internet and frequently I will have queues that span multiple days. Would it be possible to add an option to have the remaining timer show days:hours:minutes:seconds if hours are over 23?

**Comment by Safihre** [comment]
Makes sense, what do you think @shypike ?

**Comment by shypike** [comment]
Yes, makes sense. Also for people with those really big queues...

**Comment by Safihre** [comment]
No, they all use the output of the python-code directly, no-reformatting in Plush or SMPL.

Fixed it (see referenced commit above), had to also make some changes to Glitter to make it work since Glitter does do some time-reformatting (0:09:30=>9:30).

**Comment by Safihre** [comment]
Solved in #658, can be closed.
