### ISSUE TITLE
Don't use hardcoded icon path on Linux (Fedora "Hansvon" repo)

### ISSUE THREAD

**Issue by Paviluf** [sabnzbd/sabnzbd#659]
Hello,

SABnzbd have a non-standard hardcoded icon path `Icon=/usr/share/SABnzbd/icons/nzb.ico`. Is it possible to use the standard way to use an icon please ?

Something like that, put the icon in `/usr/share/icons/hicolor/[size]/apps/SABnzbd.png` and use this in the .desktop `Icon=SABnzbd`

Thanks !

**Comment by shypike** [comment]
@jcfp  Can you answer the question and/or solve the issue?

**Comment by jcfp** [comment]
This seems to be a distribution issue, as the program's source releases do not include a desktop file or an installer script of any kind. There's nothing for the developers of sab to fix here.

@Paviluf Please file a bug with whoever maintains your distribution's sab package and have them fix the install location for the icon and their desktop file.

**Comment by Paviluf** [comment]
What do you think that, if it's possible, rather than letting each distro make whatever they want because there is no .desktop file provided instead provide a .desktop file according to the freedesktop.org standards ?

**Comment by jcfp** [comment]
Desktop files to use as a reference aren't exactly a scarce resource on any linux desktop, even plenty of sab specific examples such as [this one](https://anonscm.debian.org/viewvc/python-apps/packages/sabnzbdplus/trunk/debian/sabnzbdplus.desktop?view=markup) used in Debian and Ubuntu are readily available online. And without some build system configuring these automatically, tailoring stuff such as the (distro specific) filenames of the executable and icon, command line arguments and so on would still leave plenty of oppertunity for screwups of the sort you opened this issue over.

**Comment by Paviluf** [comment]
Maybe if the .desktop file come from you the distros will just use it rather than create their own.

**Comment by Paviluf** [comment]
By the way I just thought that it's not the distro that don't use the standard way in my case. Sabnzbd is not packaged by Fedora so I use [this repo](https://forums.sabnzbd.org/viewtopic.php?f=2&t=4305) to install it.

**Comment by sanderjo** [comment]
Hi @Paviluf 

Aha, you use Fedora! 

> Sabnzbd is not packaged by Fedora so I use this repo to install it.

And that Fedora package https://forums.sabnzbd.org/viewtopic.php?f=2&t=4305 is neither provided by the SABnzbd team, but by "Hansvon"

So you could ask Hansvon in that Fedora thread https://forums.sabnzbd.org/viewtopic.php?f=2&t=4305 if he agrees with you and, if so, if he could do it for you.

To summarize: "nzb.ico" is not provided by the SABnzbd team nor SABnzbd source (proof: https://github.com/sabnzbd/sabnzbd/search?utf8=%E2%9C%93&q=%22nzb.ico%22 ... file not there). It's put in the Fedora package by Hansvon.

**Comment by Paviluf** [comment]
> Aha, you use Fedora and you're talking about a Fedora issue! Maybe change "Linux" in your thread title to "Fedora" to make it clearer?

Done

> I see "Waz" (you?) has already done that: https://forums.sabnzbd.org/viewtopic.php?f=2&t=4305&start=195#p107860

You are right, that's me :)
