### ISSUE TITLE
'Checking' does not show progress in 1.1.0

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#661]
When 'Check before downloading' is turned on, no progress of the checking is shown in 1.1.0.
In 1.0.3 you nicely see the progress by the blue-progress bar in Glitter, but in 1.1.0 the API doesn't report the progress anymore, all you see is the general 'Queue size left' counter go down untill all is checked, then it goes back up again when the actual download starts.

**Comment by shypike** [comment]
Must be a side effect of all those optimizations, but which one?
