### ISSUE TITLE
How to disable safe mode?

### ISSUE THREAD

**Issue by retorquere** [sabnzbd/sabnzbd#662]
I was asked at some point whether I wanted to use safe mode and I did, but I can't find how to disable it again.

**Comment by Safihre** [comment]
It's not really a safe *mode*, it just resets settings like login and skin back to the default settings.
So after this you can change the settings back to whatever you want. Just don't start using that link again.

@shypike I did see that it sets the default skin to Plush, maybe change this to Glitter?

![image](https://cloud.githubusercontent.com/assets/5703454/17837944/4cd8c7bc-67c0-11e6-8f0d-83111ec2534e.png)

**Comment by retorquere** [comment]
Ok, thanks, that did the trick.

**Comment by shypike** [comment]
@safihre Yes, it should default to Glitter.

**Comment by shypike** [comment]
Oh right, this is the ancient Safe start in the Windows installer? Forgot all about it.
