### ISSUE TITLE
Lots of missing articles, correct download-report?

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#664]
Not sure if this intended behavior, or due to our optimizations in 1.1.0.
If a download is 1000MB (**including** par2) and 100MB is missing, it will currently show in the Queue that it downloads until 900MB and then goes to post-processing. So it really indicates how much it has actually _downloaded_, not how much it has _progressed_ through the amount of MB declared in the NZB.

For example this NZB, it says in the Queue 765MB/2542MB, after having finished 9 files of 103MB. So shouldn't it show 900MB / 2542MB? 
![image](https://cloud.githubusercontent.com/assets/5703454/17847800/49a4f7d8-6850-11e6-9610-8a2c3496137f.png)

**Comment by shypike** [comment]
Same cause as pre-download-check no longer showing progress.
So far, I don't know why either happens.

**Comment by Safihre** [comment]
I see the reason is simple: before we used to loop over ```nzo.files``` to determine the number of bytes left, so would only count the bytes of files that still needed to be done.
How to fix it.. I dunno..

**Comment by thezoggy** [comment]
due to: https://github.com/sabnzbd/sabnzbd/commit/f17d3bd6b31f185b036157944ed36e0fd72089d5 ?

**Comment by Safihre** [comment]
No, a change long ago to improve the speed of the API to not loop over *all* files in *every* download.
This will fix it even better than 1.0.x-behavior: 134ebc2 
Keeps proper check of bytes that were tried.

But, when there's an old queue loaded on startup the loaded ```nzo``` objects will not have the ```nzo.bytes_tried``` and give errors. 
Maybe @shypike can take and improve my idea or maybe has a better one ;)

**Comment by shypike** [comment]
I was thinking of adding an NZO level byte counter and update that together with the update of the counter at NZF-level. Or go back to looping over the NZFs, or is that already too expensive? I mean, just to get the totals.

**Comment by Safihre** [comment]
That's exactly what is in my commit 134ebc2, a counter of all bytes tried at NZO level.

**Comment by shypike** [comment]
In `nzbstuff.NzbObject.__setstate__()` add these lines just before `TryList.__init__(self)`:
``` python
        if self.nzo.bytes_tried is None:
            self.nzo.bytes_tried = 0
```

**Comment by Safihre** [comment]
:+1: 
And how to copy this attribute when a job is Retried?
Now it will show 0% completed when Retried because ```nzo.bytes_tried``` is empty.

**Comment by shypike** [comment]
And all of this went OK before? If so, I will look at restoring the original situation (preferably without looping all the time).

**Comment by Safihre** [comment]
Yeah in 1.0.x it works better.
Never noticed it before as a user, but there it would 'jump', for example: if a file 100MB was missing 99% of its articles it would add 100MB at once after trying all articles in a file. Since then the file moves to ```finished_files``` and doesn't get counted anymore.

The thing is: it's not just the looping there, it **also** loops over all the files in ```nzo.total_and_remaining()```, which is called in ```queue_info``` for each item in the queue.
Maybe we can combine somehow?

**Comment by Safihre** [comment]
With the ```bytes_tried``` we could combine the calculation in ```nzo.total_and_remaining()``` and ```nzo.gather_info()``` with a helper function to calculate the size of ```extrapars```. 
No need for a for-loop in ```nzo.total_and_remaining()``` anymore.
Would need some tweaking of the Retry, but seems worth the reduction in for-loops for big-queues.

**Comment by Safihre** [comment]
Removed the ```bytes_tried ``` thing for now since the difference was fairly small, from 62ms to 55ms when all loops were removed. 
Probably best to make a good combination of ```remaining(), total_and_remaining() and gather_info()``` to fix this problem for now.
