### ISSUE TITLE
1.1.0rc3: includes outdated cherrypy patch

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#666]
the -src release of rc3 contains an outdated patch in cherrypy/Patch-for-CP-3.8.0.diff (while the included cherrypy version is actually 6.0.2). No such file existed in rc1. If the inclusion of the patch was intentional, it should be up-to-date.

**Comment by shypike** [comment]
Thanks for the tip. Will be cleaned up.
