### ISSUE TITLE
1.1.0rc3: keeps showing glitter tips

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#669]
The code comment suggests the glitter tips introduced in commit 3464450 should show up only once, but unfortunately it relies on 'local storage'. That results in repeatedly showing the alert whenever a user visits with a 'fresh' browser/system/mobile device etc., and requires local storage to be available and persistent in the first place, which is far from guaranteed with privacy conscious users given how widely this feature gets abused for tracking purposes.

On my own system, the tips message keeps reappearing after every restart even within the same browser. Please consider switching to the same mechanism used by previous similar alerts in sab (e.g. 'notified_new_skin'), that stored this info in the ini.

**Comment by shypike** [comment]
Now that you mention it, I've seen this happening too.

**Comment by Safihre** [comment]
I'd feel another in variable was a little overkill, sure I can do that of course. 

But how am I supposed to save any settings if people even start disabling local storage on their sabnzbd domain? I personally don't understand this at all.. Maybe for the general internet, but why for the sabnzbd domain?

**Comment by sanderjo** [comment]
... or create/use a database in ~/.sabnzbd/admin ?

**Comment by Safihre** [comment]
The browser (Glitter) can't access that unfortunately.

**Comment by sanderjo** [comment]
> The browser (Glitter) can't access that unfortunately.

But SAB can. So as soon as SAB has shown it to the user, SAB can set that in a database, can't it?

**Comment by Safihre** [comment]
That's exactly what the ```cfg``` does. 
My suggestion is to make a WARNING message like for the notify new skin, otherwise it will take quite some code in Glitter just to check if the value was already set in the cfg and then update the cfg from the skin. 
I don't feel that's worth it.. Since realistically, people will maybe use 2 devices so only have to remove it twice. And a user just shouldn't disable local storage on the sabnzbd domain.

**Comment by thezoggy** [comment]
but some people do browse in private/incognito mode..  also switching from http<>https.. all these scenarios will result in having to get rid of the tip.

> When you fire-up a browser in private/incognito/safe mode (sometimes more crudely- and accurately- referred to as "porn mode"), it will create a new, temporary database for LocalStorage values. That means anything saved to LocalStorage will be destroyed when the private browsing session is closed, making LocalStorage behave more like SessionStorage.

**Comment by jcfp** [comment]
> But how am I supposed to save any settings if people even start disabling local storage on their
sabnzbd domain? I personally don't understand this at all.. Maybe for the general internet, but why for the sabnzbd domain?

Browsers (esp. on mobile) may not have fine enough control options for cookie handling to make this distinction. Users may not be in control of such settings even if they exist, say in corporate environments or with overzealous antivirus.

At least everyone here understands how this mechanism and its implementation work, but for end users such repeated displays of the tips will likely appear as a program malfunction.

**Comment by shypike** [comment]
Let's just use the extra variable in sabnzbd.ini
