### ISSUE TITLE
sab 1.1.0RC4 -- tvsort - errenous logging

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#671]
anytime I start a download I see:
`2016-08-30 14:46:19,411::DEBUG::[tvsort:731] Date Sorting - Starting folder sort (Show Name 2009-01-02)`

I do not use any sorting, all of them are unchecked.. and per ui logs:
`enable_date_sorting = 0`
`date_sort_string = %t/%t - %y-%0m-%0d - %desc.%ext`

**Comment by shypike** [comment]
That's juist the season/episode analysis which is part of the new duplicate detection for series.
If I make that dependent on the option, it would mean that if you later enable the option, it won't work on already downloaded episodes.

**Comment by thezoggy** [comment]
why not just wrap the log in the logic that sees if the higher level option is enabled?

**Comment by Safihre** [comment]
@shypike he as a point, it's a bit weird.
I also see it in my logs, even though I have no sorting at all enabled.
In the function is this check:
```
        if force or (cfg.enable_tv_sorting() and cfg.tv_sort_string()):
            if force or (not self.cats) or (self.cat and self.cat.lower() in self.cats) or (not self.cat and 'None' in self.cats):
```
Why is it forced?

**Comment by shypike** [comment]
Like I said. If you enable it later, it will not take earlier season/episodes into account.
The analysed show/season/episode will be stored in the database.
If it makes you feel happy, I'll modify the logging text. But this is *debug* logging, guys.

**Comment by Safihre** [comment]
:smiley: true
