### ISSUE TITLE
Sab RC4 notifications tab in config

### ISSUE THREAD

**Issue by sparklyballs** [sabnzbd/sabnzbd#672]
Hi i'm part of linuxserver.io and author of the sabnzbd docker we make.
https://github.com/linuxserver
https://github.com/linuxserver/docker-sabnzbd

Testing out RC4 in my personal repo and the notifications tab in settings gives 

Unable to connect

(in firefox at least)

same container but using 1.0.3 and the notifications tab loads.

**Comment by Safihre** [comment]
Is there any more information? Like an error?
Does it work in Chrome?

**Comment by sparklyballs** [comment]
I don't have chrome.

the error is the tab doesn't load, surely ?

**Comment by sparklyballs** [comment]
it doesn't work in safari (mac latest version, if relevant) either

**Comment by Safihre** [comment]
Is it a 404, 500 or just a timeout? 
Maybe try to see what happens if you get the files from the repro as a zip instead of the src file?

**Comment by sparklyballs** [comment]
kk.
![screen shot 2016-08-31 at 12 16 04](https://cloud.githubusercontent.com/assets/4343808/18126789/bc60c2c2-6f74-11e6-909c-7a16ecd39da6.png)

firefox ^^^

![screen shot 2016-08-31 at 12 16 40](https://cloud.githubusercontent.com/assets/4343808/18126802/cb0578ea-6f74-11e6-8df7-6fd547250072.png)

safari ^^^

**Comment by sparklyballs** [comment]
same result using 

https://github.com/sabnzbd/sabnzbd/archive/1.1.0RC4.zip

**Comment by shypike** [comment]
Did you set a fixed numerical IP in Config->General?
Is this the correct one or did your router assign a new IP address to the system?
We usually recommend "127.0.0.1" for local only or "0.0.0.0" if you need external access.

**Comment by shypike** [comment]
Maybe I missed something. The problem only happens for the Config->Notify page?

**Comment by sparklyballs** [comment]
it's a docker container, 0.0.0.0 and 127.0.0.1 are not going to work

the ip used is the ip of the host system running docker.

the tab works in 1.0.3 but not in RC4 in an identical docker

@shypike, yes only the notifications tab.

**Comment by shypike** [comment]
@sparklyballs Right, then I misinterpreted the problem.
We'll get to the bottom of this.

**Comment by sparklyballs** [comment]
sidenote, have you checked out our docker ? lol.

https://github.com/linuxserver/docker-sabnzbd

**Comment by shypike** [comment]
@sparklyballs It's something that has been forever on my to-do list: have a good lock at Docker in general and SABnzbd's docker specifically :(

**Comment by sparklyballs** [comment]
we'll be more than happy to help, or you could link us as an install option ? 

some of the other containers we build, the original app authors do that.

couchpotato for example.

**Comment by shypike** [comment]
@sparklyballs That is a good suggestion. I'll talk to the webmaster about offering it as an install option.

**Comment by sparklyballs** [comment]
cool, i don't turn every other support issue into a "sell" , honest...

**Comment by Safihre** [comment]
I tried to reproduce it by downloading the src file and running it in with ```python SABnzbd.py``` in my Ubuntu linux.
Granted, it does have the PPA installed so all dependencies available, maybe that helps?

**Comment by Safihre** [comment]
Looking at the code (https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/interface.py#L2851-L2892) I cannot see anything special about this page that would make it fail?

Could you maybe try with any of the other RC's? Does it fail from the first beta/RC of 1.1.0?

**Comment by Safihre** [comment]
It is also very strange that the browsers say 'Cannot connect', because if you request a nonsense address from SABnzbd, say:
[http://localhost:8080/sabnzbd/config/categoriessssssssssssssss](http://localhost:8080/sabnzbd/config/categoriessssssssssssssss)
CherryPy will redirect you to SABnzbd main page.
So something like a timeout must happen for it to say 'Cannot connect'.
Does the loading take really long before the browsers say 'Cannot connect'?

**Comment by sparklyballs** [comment]
the loading is less than 2 seconds or so, a little longer than usual for a normal page.

it's weird it's the only tab that doesn't load.

i tried this file 

https://github.com/sabnzbd/sabnzbd/releases/download/1.1.0Beta1/SABnzbd-1.1.0Beta1a-src.tar.gz

with the same result as the RC4.

**Comment by Safihre** [comment]
I have no clue how this could happen.. No timeout *and* no redirect? It almost seems impossible.. 
Maybe @shypike will have am answer.

**Comment by sparklyballs** [comment]
this is the dockerfile of the baseimage used for our sab docker

https://github.com/linuxserver/docker-baseimage-alpine-python/blob/master/Dockerfile

if there's anything that you can see that may be missing..

**Comment by shypike** [comment]
I tried the 1.0.3 docker release. I cannot get it working: I see it starting up and listening to 0.0.0.0:8080, but I cannot get Firefox to connect to it at all.
(Using Ubuntu Desktop 15.10)

**Comment by sparklyballs** [comment]
you have to use the ip of the host system and not 127.0.0.1 etc.

**Comment by shypike** [comment]
That's what I do, but no response. I assume this is the actual IP and not the one listed by ifconfig for "docker0"?

**Comment by sparklyballs** [comment]
docker0 is a bridge usually (it varies from host to host)
 to allow communication between the host and docker containers and containers to the host and the outside world etc..

my ifconfig output 

docker0   Link encap:Ethernet  HWaddr XXXXXXXX
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

enp2s2    Link encap:Ethernet  HWaddr XXXXXXXXX
          inet addr:192.168.1.40  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fXXXXXXXX/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2056604 errors:0 dropped:6 overruns:0 frame:0
          TX packets:2249 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:711275586 (711.2 MB)  TX bytes:1362577 (1.3 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:11840 (11.8 KB)  TX bytes:11840 (11.8 KB)


in this instance i would use 
192.168.1.40

**Comment by shypike** [comment]
Yes, similar to mine. I picked the address equivalent to yours.
Now, my Ubuntu is running under VMWare Desktop for Windows.
Does that complicate matters?

**Comment by sparklyballs** [comment]
not sure, have no experience with VMWARE and little with windows, lol.

but i shouldn't imagine so, that output is from a VM on unraid as the host, my dev server so to speak.

**Comment by sparklyballs** [comment]
if you ssh in to the VM , use the same ip you use for that...

**Comment by sparklyballs** [comment]
did you use either 

`-p 8080:8080`

or 
`--net=host` 

in the run command for the docker ?

**Comment by shypike** [comment]
-p 8080:8080

**Comment by sparklyballs** [comment]
i love my little videos, lol.

https://www.youtube.com/watch?v=1kWsaBoLBuE&

it might still be processing.

note , i should have included `-d` in the run line for daemon mode.

**Comment by sparklyballs** [comment]
the full line i should have typed

docker run -d --name=test --net=host linuxserver/sabnzbd

**Comment by shypike** [comment]
Right, that did it.
Well, off to testing now.

**Comment by shypike** [comment]
@Safihre @sparklyballs 
Regarding Safihre's remark about using the ZIP from GitHub.
Not a good idea, the ZIP doesn't contain the compiled translation files, but the tar.gz does.

**Comment by shypike** [comment]
@sparklyballs Is there a way to reach you by email?
Mine is shypike at sabnzbd.org

**Comment by sparklyballs** [comment]
indeed

sparklyballs@linuxserver.io

**Comment by shypike** [comment]
I cannot get it to work properly when I create my own Docker. Instead I just "bash"-ed the running 1.0.3 docker and upgraded within that container. I had to remove CherryPy from the site-repositories.
I can confirm that the problem exists.
The problem goes away as soon as I replace the 1.1.0RC4 config_notify.tmpl with the one from 1.0.3.
Wel'll see how far we get with this.

**Comment by sparklyballs** [comment]
kk, i was afk yesterday (50th birthday) and my head is still a little fuzzy today, lol

at least know it wasn't my imagination there is something going on with that tab.

**Comment by shypike** [comment]
We don't understand what's going on. It looks like the Notify template runs into some limit. If we remove one section (any), it works. Why this only happens in a docker, no idea.

**Comment by shypike** [comment]
Whenever you call up the Notifications page, SABnzbd simply crashes. The Docker service starts it again immediately. What kind of crash it is, I don't know. There absolutely zero logging available.
@sparklyballs  Are there limits (memory, file handles, threads, responsiveness) for Docker apps that do not apply for native apps?

**Comment by sparklyballs** [comment]
on a test version local to me i moved the startup of sab to an init routine in the dockerfile, the services files in our dockers restart crashed apps.

about the only extra infomation i can get is that it is a segmentation fault.

as for the docker specifics you asked about, not sure.

**Comment by sparklyballs** [comment]
2016-09-04 11:46:21.011311500  /var/run/s6/etc/cont-init.d/30-startup: line 5:   205 Segmentation fault      (core dumped) s6-setuidgid abc python /app/sabnzbd/SABnzbd.py -l 2 -f /config/sabnzbd.ini -b 0 -s 0.0.0.0:8080
2016-09-04 11:46:21.011912500  [cont-init.d] 30-startup: exited 139.

**Comment by Safihre** [comment]
Looks more like a Docker/python problem than a Sabnzbd problem?

**Comment by sparklyballs** [comment]
@Safihre  looks like you could be right, just spun up an ubuntu xenial version of the docker running sabnzbd RC4 from the ppa and the notifications page is loading.

**Comment by sparklyballs** [comment]
so there is something in the alpine version of the docker. 
that between 1.0.3 and the 1.10 of the notifications tab is causing it to crash.

**Comment by sparklyballs** [comment]
noticed something strange...

https://youtu.be/v4eU0j2uRZQ

**Comment by thezoggy** [comment]
each time you check off the box its trying to save..  if you told sab to change apikey but havent restarted.. that might explain the session key not being right. just tried 1.1.0RC4 on windows and ubuntu.. no problems here. you can load up firebug and see what is being passed and see whats going on.. 

the only thing on the config page that I cant really test is the whole ncenter part.. but thats osx related. 

speaking of, if you want to debug some.. navigate to where sab's installed, go modify the file `interfaces/Config/templates/config_notify.tmpl` and nuke out the segments and see if that makes a difference.. just be sure to revert the file when you are done so you dont have local changes that would prevent git/package manager from updating.

**Comment by thezoggy** [comment]
ok loaded up the docker image, confirmed that when clicking on config > notifications it doesnt work.. looking at the logs i see that it causes sab to restart like 5 times before just giving up... digging into it more..

**Comment by shypike** [comment]
@thezoggy 
There is some problem in the Alpine image, according to sparklyballs.
If you remove any random section from Notify, the problem goes away.
The crash occurs when Cheetah is creating the HTML from the template.
Something is overflowing, but it doesn't seem to be in SABnzbd or Cheetah.

**Comment by thezoggy** [comment]
https://github.com/linuxserver/docker-baseimage-alpine-python

```
[08:09am] <_zoggy_> cherrypy honestly shouldnt be installed...
[08:10am] <_zoggy_> the apps that use it generally provide their own version and have mods/hacks applied to fix bugs
[08:10am] <_zoggy_> sab pretty much stopped supporting user installed versions due to how many bugs we ran into
[08:10am] <_zoggy_> and just included much newer version with bugfixes applied
```

mention that earlier in irc chat.. after finding out the issue is cherrypy bug.. i suggested trying to just drop cherrypy from alpine to see if that makes a difference...

**Comment by sparklyballs** [comment]
further to @thezoggy's message...

built a version without installing cherrypy, issue persists.

**Comment by shypike** [comment]
CherryPy is not a factor, only Cheetah is.

**Comment by shypike** [comment]
Is it possible to use another version of Cheetah on your Docker?

**Comment by sparklyballs** [comment]
i could build from source i suppose, do you mean version number or alternative cheetah author ?

**Comment by thezoggy** [comment]
on another docker image there is issues with alpine:
http://forum.kodi.tv/showthread.php?tid=290259&pid=2411449#pid2411449

wonder if this is also causing this issue...

**Comment by sparklyballs** [comment]
@thezoggy  that's a red herring with kodi, since that particular problem is also happening with an ubuntu based kodi-headless docker.

**Comment by shypike** [comment]
@sparklyballs 
Try an older official version first. Cheetah has good compatibility between versions.

**Comment by sparklyballs** [comment]
i compiled python from scratch using the offiicial python alpine docker recipe and adding in the requirements for sab.

the notify issue remains with that,  but interestingly the same issue then happens on the switches tab of the config section, which doesn't happen in the current linuxserver.io python base.

**Comment by shypike** [comment]
@sparklyballs Like thezoggy said, it seems to be connected to the amount of variables Cheetah has to substitute. So it must be that Cheetah crosses some internal limit inside Python. I have no clue what that limit would be. Incidently: Cheetah uses a file called `_namemapper.so`, which is compiled C. Can you try to remove that file? Cheetah will print an ugly warning, but it will function.

**Comment by sparklyballs** [comment]
i see the warning, but the notifications tab is still not loading after removing the file.

**Comment by shypike** [comment]
I give up.
It works fine on any other platform, except this Alpine Docker.
Or does the problem also occur in Dockers based on other distros?

**Comment by sparklyballs** [comment]
yeah, i don't get it either.
i'm convinced there's something in python itself that gets tripped by too many variables when it's running on alpine.

With various different compiles of python, different sections of the configuration tabs fail with the same error, again still on alpine.

I have a ubuntu xenial based image in a branch of my personal repo, i've been trying to put off using it, it's 100MB+ bigger than the alpine version, but it's looking increasingly like there may not be any option but to use it.

**Comment by shypike** [comment]
Well, it's really an Alpine issue. I just made a VMWare image of Alpine 3.4.3 64bit and it gives a segfault as soon as you open Notifications.
Plain Alpine, installed git, unpacked the Cheetah-tgz file (so without `_namemapper`), cloned SABnzbd repo, ran tools/make_mo.py.

**Comment by sparklyballs** [comment]
I've made a PR from my personal repository branch using xenial to the linuxserver image.

Thanks for your assistance.

**Comment by shypike** [comment]
@sparklyballs You're welcome. I really appreciate your effort to make SABnzbd available as a Docker image.
