### ISSUE TITLE
1.1.0 RC4 fails to verify servers with Test Server Function

### ISSUE THREAD

**Issue by FedoraTipper** [sabnzbd/sabnzbd#673]
Hello,

Not sure if this has been reported. It seems that when trying to test details to a server, SAB always reports back with  "Server requires username and password." Regardless if the details are correct or wrong.

<img width="447" alt="chrome_2016-09-04_02-02-34" src="https://cloud.githubusercontent.com/assets/19745176/18228219/dcaa5468-7243-11e6-8123-bc5c2cac927e.png">

When just adding the server, everything verifies properly. It seems that Test Server is the only thing broken.

**Comment by Safihre** [comment]
Oops, my fault.. Thanks for reporting.
Fixed in 2ee63f6

**Comment by shypike** [comment]
Will be fixed in the next release
