### ISSUE TITLE
sab -- 1.1.x - install.txt

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#676]
install.txt hasnt been touched in awhile..

several of the dependencies probably could use a review..  do we support python 2.6?
`Most versions will work: 2.7.10 recommended` probably should change that to 2.7.12?

par2cmdline should put the version that supports -n at least..

http://www.info-zip.org/UnZip.html
***  All versions of UnZip through 5.50 have a number of directory-traversal vulnerabilities, and version 5.50 also has a textmode data-corruption bug that affects 16-bit ports such as MS-DOS. See the FAQ page for details.  ***
per the site, UnZip 6.0, released 20 April 2009...  

```
Embedded modules (preferably use the included version)
    CherryPy-3.8.0 with patches  http://www.cherrypy.org
```
prob could be dropped since we include the one we want..

**Comment by shypike** [comment]
Right, I'll correct it.

**Comment by thezoggy** [comment]
prob can update our checks for cherrypy, right now we catch for 3.8.0+
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L55

might want to bump that to the version we include now?

**Comment by shypike** [comment]
@thezoggy I'll bump the check.
Although older versions may very well work.
It looks like we could just use an unpatched 8.1.0, but there's no guarantee that later ones will work.
Unix package creators don't like us including CherryPy.

**Comment by thezoggy** [comment]
- `ISSUES.txt`
all the links point to 1.0 wiki pages.. should update to latest? or just move issues.txt to its own wiki page and just replace the data here with that link? (since the issues arent version dependent)

- `README.md`
need to state we only do python 2.7 now..

**Comment by thezoggy** [comment]
should note that `python-dbus` is optional, only required for linux if you want sab to do power related things to the system..

**Comment by thezoggy** [comment]
>  Unix package creators don't like us including CherryPy.

I would think that we SHOULD include it, since we have patches applied.. we could not include it if were using native code / can require a version thats good enough that wont cause support nightmare to deal with it.

**Comment by Safihre** [comment]
@thezoggy I saw the update of ```-N``` for par2cmdline, but he hasn't released a new version since 2015. 
So will add a note about the existence of ```-N```, since this will stay relevant for a while.
