### ISSUE TITLE
sab 1.2.x -- history retention

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#678]
right now sab keeps its history for better and for worse..  which can cause issues for dupe checking or for the paranoid.

suggesting we add a history section under config > switches to tweak how and what we do with it.

have a switch to use history or not? (if no history, this could break apps ex: sonarr. thus we should show warning)
if enabled (default), then have field to to input to only keep history upto this day, so 1y/365d/1w/whatever..  0 = keep all (default).

note that we have `history_limit` as a config>special, which sets an artificial upper limit for the api commands.

note that nzbget has this, but they use it to just toggle visibility to the ui, they still keep it after the cut off.. but just minimal details so it can still be used for dupe checking.

nzbget related history features:

```
        - when deleting downloads from queue there are three options now:
          "move to history", "move to history as duplicate" and "delete
without history tracking";

        - when history item expires (as defined by option "KeepHistory")
          and the duplicate check is active (option "DupeCheck") the item
          is not completely deleted from history; instead the amount of
          stored data reduces to minimum required for duplicate check
          (about 200 bytes vs 2000 bytes for full history item);

        - such old history items are not shown in web-interface by default
(to avoid transferring of large amount of history items);

        - new button "Hidden" in web-interface to show hidden history items;
the items are marked with badge "hidden";
```

**Comment by thezoggy** [comment]
for example, my sab history had 7345 items, oldest being from `10/24/2010 4:00am`. thats a lot of wasted resources to dupe check through if I didnt manage/had issues with apps or rss feeds that went crazy at some point. also doing bulk removal of parts of history doesnt work too well.. you can either nuke one item or what you can see on the ui.. (havent checked all skins), but dont think you can prune history after x date or all of it very easily.. which is what this feature request would allow...

**Comment by thezoggy** [comment]
does sab rely on history for its totals or quota? if so.. we shouldnt... since history can be modified.

**Comment by shypike** [comment]
@thezoggy totals and quota are kept in totals9.sab
Do you suggest to keep the history, but just not show it after the cut-off date?
I suppose we could use a cut-off date for duplicate checking as well.
So far I don't know how expensive SQLite queries really are.

**Comment by thezoggy** [comment]
well its up in the air if we want to do one or the other.. or both. for starters.. I know there is a set of people that would be happy to just auto prune history / empty out history. As I personally do not use sab for dupe checking.. the whole keeping history but just hiding it.. isnt a huge deal to me. But, its easy enough to just add a isVisible flag to the items in the history and just toggle this value and use it to filter out stuff on the sql queries..

**Comment by Safihre** [comment]
Always found the NZBGet options for history a bit overly controlling and a bit confusing (when deleting an item from the Queue).
If someone wants to get rid of the whole queue, he can do it with just 2 clicks.

**Comment by thezoggy** [comment]
history retention:

- on/off (master switch)
> enable history or not, now if one chooses not to keep history... will this break dupe checking? for simplicity sake.. could just not offer a master switch.. but prob someone would complain about not having it?

- keep last x items
> that way someone could just have a lean history, and lets say just keep last 100 items.. might be more logical for someone since they may not have daily sab activity
> if they say to keep only 1 item, would it be pointless? as the limit would be so low that the last history data could easily keep getting replaced (small size nzb in queue) which would cause thrashing? or just be worthless to apps that rely on it... maybe offer some pre-defined limits? or set artificial min...

- keep last x days
> this i view is mainly for those that want to keep a somewhat lean history geared towards efficient dupe checking data.. as I wouldn't want stuff from a year ago to interfere with what I'm doing today.. with either pruning method (days/items), the value of `0` (default) would be to keep everything for either option.

**Comment by thezoggy** [comment]
@Safihre `[03:28pm] <Marvin-> hello, 1.1.0, clear history makes my server go boom(kernel panic i assume). im rebooting atm. will the sabnzbd log show anything? how can I be of help?`
