### ISSUE TITLE
RSS evaluation really slow with many regexes or SxxEyy analysis

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#679]
Should be optimized.
As an intermediate solution, don't re-evaluate automatically after each filter change but use a "Check" button.

**Comment by Safihre** [comment]
Implemented in 5948d6c that if the feed comes from a newznab/nZEDb indexer we will now use the season/episode information from the feed. 
This is *much* faster: from 50ms to 0.1ms!

But if the user uses regexes, it's still slow..

**Comment by Safihre** [comment]
@shypike What can we still do about this?
Have some good ideas for me? 👍

**Comment by thezoggy** [comment]
Only reason I can think of is for reverse proxy.. but that's outside my wheelhouse
