### ISSUE TITLE
sab - 1.2.x -- macOS/sierra

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#682]
prob will want to update the related items to mention macOS..  backgrounds/install/notifications? also with this update i know they changed quite a few cipher/ssh stuff.. so hopefully nothing odd pops up for us in python/ssl..

**Comment by Safihre** [comment]
Will update the website soon.
Guessing it's working well on this new version, since we had no complaints on the forums and the beta's have been out for a while.

**Comment by Safihre** [comment]
The wiki is updated now.
I barely see any OSX references in SABnzbd? Only in the install/issues/readme.

**Comment by thezoggy** [comment]
@Safihre  mainly this was for the installer

**Comment by thezoggy** [comment]
also just to note, firefox 49 ( https://www.mozilla.org/en-US/firefox/49.0/releasenotes/ ),

* Ended Firefox for Mac support for OS X 10.6, 10.7, and 10.8. 

> https://blog.mozilla.org/futurereleases/2016/04/29/update-on-firefox-support-for-os-x/

Mac OS X v10.6 "Snow Leopard" was released on August 28, 2009. 
Mac OS X v10.7 "Lion" was released on July 20, 2011.
Mac OS X v10.8 "Mountain Lion" was released on July 25, 2012.

and mountain lion comes with Python 2.7.5...

**Comment by shypike** [comment]
We already dropped Snow Leopard, Lion and Mountain Lion.
1.2.0 will support: Yosemite, El Capitan and Sierra.
Dropping Mavericks.

**Comment by thezoggy** [comment]
updated above list.. looks like El Capitan+ is idea for our purpose (with SSL) but anyways with the whole 2.6+ requirement in 1.1.0..  Mavericks was is already dropped. 

With 1.2.0? (new SSL) we actually are dropping Yosemite since were requiring 2.7.9+

**Comment by shypike** [comment]
Any installation still relies on the resident Apple-Python.
The only way not to do this, is to drop the OS integration: hence no more icon in the top menu.
Not dropping Yosemite, just supporting it on a lower level for SSL.

**Comment by thezoggy** [comment]
yeah, looks like @Safihre isnt forcing it to be 2.7.9+ anymore, just needs it for ssl.. shows warning about verification if older python.. so yeah Yosemite is still good
