### ISSUE TITLE
sab - 1.1.0 -- glitter > warning tab

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#684]
@Safihre  -- fyi, warning tab with 0 warnings results in 'None' with no padding... should add padding so it matches other tabs / when there is actual warnings

**Comment by thezoggy** [comment]
@Safihre also fyi, http://blog.jqueryui.com/2016/09/jquery-ui-1-12-1/

**Comment by Safihre** [comment]
Closed by e2a6517
