### ISSUE TITLE
OpenSSL only detected upon UI Restart

### ISSUE THREAD

**Issue by PsychoGTI** [sabnzbd/sabnzbd#686]
After upgrading today to 1.1.0 from 1.0.3, I am experiencing the exact issue as outlined in the following ticket:

[https://github.com/sabnzbd/sabnzbd/issues/457](https://github.com/sabnzbd/sabnzbd/issues/457)

I am also running OpenSuse Leap 42.1 as in the linked ticket. Not sure if there's something specific with how python 2.7.12 operates in Suse or something specific to the upgrade of SAB. 

When it is detected, I'm running OpenSSL 1.0.1i-fips 6 Aug 2014   [TLS v1.2, TLS v1.1, TLS v1, SSL v3, SSL v2] and pyOpenSSL 0.14. Any guidance would be great... the log even at the highest level does not give me much other than it's not detected on initial start, but on UI Restart it is. Thanks.

**Comment by shypike** [comment]
The ticket you refer to, does not exist.
Please describe your problem in more detail.

**Comment by Safihre** [comment]
@shypike, yes it does and I am sure you remember it, it was a very long one! 
Working link https://github.com/sabnzbd/sabnzbd/issues/457

**Comment by PsychoGTI** [comment]
Sorry, link repaired in the original post. 

It is a long post, and I went through it... doesn't seem as though it was resolved as it was difficult to reproduce. Just my luck. ;-)

Key difference between the linked ticket and my issue would be I upgraded SAB, while the old ticket they upgraded their OS. Otherwise, behaviour is the same.

**Comment by thezoggy** [comment]
this on a nas? your nas installing stuff while your still booting sab or have funky permission issues? rule it out by just starting sab manually instead of using init script.. once everything is fully loaded and see if that changes your outcome

**Comment by PsychoGTI** [comment]
K, I figured it out. Your comment led me to look closer at the init.d script starting SAB. If I run SAB from the command line, I get the same results. But if I run it from Python (ie. /usr/local/bin/python SABnzbd.py), it works! There's something with how the SAB script initiates Python, or some system variable somewhere. 

So I edited the init.d script to have Python run the script, and it works now! Thanks!

**Comment by shypike** [comment]
There only two possible causes, I think.

* The -OO flag at the top of the SABnzbd.py file is possibly ignored if you use "python SABnzbd.py" instead of "./SABnzbd.py"
* Your default "python" interpreter is not /usr/bin/python

**Comment by PsychoGTI** [comment]
Checking the system now, the default interpreter is /usr/local/bin/python, which when examined is a symbolic link to /usr/bin/python.

**Comment by thezoggy** [comment]
@PsychoGTI can you paste the contents of your sab init script? (link to pastebin or here directly is fine.. just wrap it in three ticks to quote it)

**Comment by PsychoGTI** [comment]
Here you go, included with the change to now run it under /usr/local/bin/python, and slightly edited for security reasons (users/passwords masked):
```
#!/bin/sh
#
# /etc/init.d/SABnzbd
#
### BEGIN INIT INFO
# Provides:                     SABnzbd+
# Required-Start:               $all
# Required-Stop:                $all
# Default-Start:                3 5
# Default-Stop:                 0 1 2 6
# Short-Description:            SABnzbd+ Client
# Description:                  Start the SABnzbd+ Client
# PIDFile:                      /var/run/SABnzbd.pid
### END INIT INFO

case "$1" in
        start)
                echo -n "Starting SABnzbd... "
                /usr/bin/sudo -u MASKED -H nohup /usr/local/bin/python /home/MASKED/Programs/Usenet/SABnzbd+/SABnzbd/SABnzbd.py -d -l2 -f /home/MASKED/.sabnzbd/sabnzbd.ini 2>&1 > /dev/null
                ps -ef | grep python | grep SABnzbd.py | cut -d' ' -f5 > /var/run/SABnzbd.pid
                echo "Done!"
                ;;
        stop)
                echo -n "Shutting down SABnzbd... "
                /usr/bin/wget -q --delete-after "http://localhost:8080/sabnzbd/api?mode=shutdown&ma_username=MASKED&ma_password=MASKED&apikey=MASKED"
                rm -f /home/MASKED/SABnzbd.pid
                echo "Done!"
                ;;
        restart)
                ## Stop the service and regardless of whether it was
                ## running or not, start it again.
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit 0
```
This was written ages ago, and there's probably a lot better way to doing stuff in here... but it works (usually). I'm open to suggestions, so feel free to drop them to me.

**Comment by thezoggy** [comment]
heres the init script that comes with sab (from ppa)

```
#!/bin/sh
#
# Copyright (C) 2008-2014 by JCF Ploemen <linux@jcf.pm>
# released under GPL, version 2 or later

################################################
#                                              #
#  TO CONFIGURE EDIT /etc/default/sabnzbdplus  #
#                                              #
################################################

### BEGIN INIT INFO
# Provides:          sabnzbdplus
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:      $named dbus avahi network-manager wicd
# Should-Stop:       $named dbus avahi network-manager wicd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SABnzbd+ binary newsgrabber
# Description:       SABnzbd+ is a web-based binary newsgrabber with nzb
#                    support, designed to download files from Usenet.
#                    This script provides that functionality as a system
#                    service, starting the program on boot.
### END INIT INFO

NAME="sabnzbdplus"
DAEMON="/usr/bin/sabnzbdplus"
SETTINGS="/etc/default/$NAME"

([ -x "$DAEMON" ] && [ -r "$SETTINGS" ]) || exit 0

DESC="SABnzbd+ binary newsgrabber"
PIDFILE="/var/run/$NAME/pid"
DEFOPTS="--daemon --pidfile \"$PIDFILE\""

# these are only accepted from the settings file
unset USER CONFIG HOST PORT EXTRAOPTS

[ -r /etc/default/locale ] && {
	. /etc/default/locale;
	[ -n "$LANG" ] && export LANG;
}

. /lib/lsb/init-functions

is_running() {
	# don't try to match --name: it changes after restarting via the web interface
	start-stop-daemon --status --quiet --user "${USER%:*}" --pidfile "$PIDFILE"
	RET=$?
	[ $RET -gt 3 ] && exit 1 || return $RET
}

load_settings() {
	if [ -z "$USER" ]; then
		. "$SETTINGS"

		[ -z "${USER%:*}" ] && {
			log_action_msg "$DESC: service not enabled, edit $SETTINGS";
			return 1;
		}

		OPTIONS="$DEFOPTS"
		[ -n "$CONFIG" ] && OPTIONS="$OPTIONS --config-file \"$CONFIG\""
		[ -n "$HOST" ] && SERVER="$HOST" || SERVER=
		[ -n "$PORT" ] && SERVER="$SERVER:$PORT"
		[ -n "$SERVER" ] && OPTIONS="$OPTIONS --server \"$SERVER\""
		[ -n "$EXTRAOPTS" ] && OPTIONS="$OPTIONS $EXTRAOPTS"
	fi
	return 0
}

start_sab() {
	load_settings || exit 0
	if ! is_running; then
		install --directory --owner="${USER%:*}" --group=root --mode=0700 "$(dirname "$PIDFILE")" || exit 1
		log_daemon_msg "Starting $DESC"
		eval start-stop-daemon --start --quiet --chuid "$USER" --exec "$DAEMON" -- $OPTIONS
		log_end_msg $? || exit $?
	else
		log_action_msg "$DESC: already running (pid $(cat "$PIDFILE"))"
	fi
}

stop_sab() {
	load_settings || exit 0
	if is_running; then
		log_daemon_msg "Stopping $DESC"
		start-stop-daemon --stop --quiet --user "${USER%:*}" --pidfile "$PIDFILE" --retry 30
		log_end_msg $? || exit $?
	else
		log_action_msg "$DESC: not running"
	fi
}

case "$1" in
	start)
		start_sab
	;;
	stop)
		stop_sab
	;;
	force-reload|restart)
		stop_sab
		start_sab
	;;
	status)
		load_settings || exit 4
		if is_running; then
			log_action_msg "$DESC: running (pid $(cat "$PIDFILE"))"
		else
			log_action_msg "$DESC: not running"
			[ -f "$PIDFILE" ] && exit 1 || exit 3
		fi
	;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
		exit 3
	;;
esac

exit 0
```

**Comment by PsychoGTI** [comment]
Thanks for the script. I tried altering that just now to see if I could adapt it to a OpenSUSE environment, but doesn't seem to start. There's a couple commands in there that I don't think are recognized by the OS (eg. start-stop-daemon). I may also not have altered the daemon location correctly (changed it to the main directory of where the SAB program files are). I might need to make that a pointer to the sabnzbd.py with all of the flags in place... not sure.

**Comment by Safihre** [comment]
Closing this, it's not a sabnzbd problem specifically. In case we should update information on the wiki how to run on OpenSUSE, let me know :)
