### ISSUE TITLE
webhook notifications

### ISSUE THREAD

**Issue by travisghansen** [sabnzbd/sabnzbd#688]
I may have missed this but is there a way to specify a (or multiple) webhook URLs as part of the notification framework?

Thanks!

**Comment by shypike** [comment]
From release 1.1.0 onward we have a user notification script. You can use that to activate any URL.
https://sabnzbd.org/wiki/scripts/notification-scripts

**Comment by Safihre** [comment]
See nzb-notify project for a whole lot of services that can be used as a Notification Script:
https://github.com/caronc/nzb-notify

**Comment by travisghansen** [comment]
Sounds cool, I'll get my install updated and use the new feature!  Thanks!

**Comment by Safihre** [comment]
@travisghansen working as you hoped? If so, you can close the issue :)

**Comment by travisghansen** [comment]
I haven't checked yet.  I'll upgrade and test it out and comment back with feedback.

**Comment by travisghansen** [comment]
Here's my script for shoving the data into ```Node-RED``` for lots of fun stuff.
```
#!/bin/sh

URI="http://127.0.0.1:1880/sabnzbd"

curl -X POST "${URI}" -d type="${1}" -d title="${2}" -d text="${3}" -d parameters="${4}"
```

Thanks!

**Comment by sintaxx** [comment]
@travisghansen care to elaborate on how to get that working with node-red? im trying to connect google-home-notify with sabnzbd to announce events from sabnzbd
