### ISSUE TITLE
Feature Request - Retry failed download because articles missing after x timeout

### ISSUE THREAD

**Issue by kaigoh** [sabnzbd/sabnzbd#690]
I've done some googling, but am not sure that I have got my terminology correct, so this may have been raised elsewhere...

An issue I seem to come up against is that my downstream NNTP provider can be sluggish receiving the latest Usenet posts. This causes an issue where (quite correctly) Sabnzbd cannot find some or all of the post, therefore the download fails. However, if I retry the download some time later, say twelve hours, the download completes fine with no issue.

Is there any way this could be built into Sabnzbd? i.e. download failes because x% of articles are missing, so wait for a given timeout then try again automatically.

Thanks,

Kai

**Comment by Safihre** [comment]
You should use the new Propagation Delay feature in 1.1.0. You can choose what age s post should be before sabnzbd starts downloading. Before a post is this age, it will wait in the queue.

**Comment by Safihre** [comment]
Any luck using Propagation Delay?

**Comment by kaigoh** [comment]
@Safihre apologies for my tardy reply, I've been away from the internets. Using the Propagation Delay feature seems to tick the boxes. I've noticed a marked improvement in completed downloads. Thanks for the tip.
