### ISSUE TITLE
No par2 job since 1.1

### ISSUE THREAD

**Issue by John-Gee** [sabnzbd/sabnzbd#692]
Hello,
Since I moved to 1.1 from 1.0.3 I believe (not sure anymore), I have many jobs that fail, but then manually I am able to run par2 and repair things.
My guess is par2 was never called.
I don't see anything related in the logs, nor in the UI, and I'm not sure what to change in the UI settings for that.

This may very well not be a bug but an issue on my end, I'm just not sure what.

Thank you!

**Comment by Safihre** [comment]
Can you set logging to Debug and send a log to Safihre@sabnzbd.org when it has happened? You do have all the jobs set to +Delete in the queue?

**Comment by John-Gee** [comment]
Wow so quick!

I do have my jobs set on +Delete yes, though I cannot guarantee for the auto ones that failed before I saw them, but since I've never seen anything else..

As for Debug, I just did, and will look for the next logs.

Thank you!

**Comment by Safihre** [comment]
Any more problems?

**Comment by John-Gee** [comment]
Not since then, but I haven't really downloaded lately.
I'll close this for now.

Thank you!
