### ISSUE TITLE
QQ: Web UI issues

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#696]
Using git pulled, master branch.

Version:	1.1.x [unknown]
Uptime:	1m
Config File:	/opt/.sabnzbd/sabnzbd.ini
Used cache:	Cached 50 articles (18 MB)
Parameters:	/opt/sabnzbd/SABnzbd.py -d -f /opt/.sabnzbd/sabnzbd.ini
Python Version:	2.7.12 (default, Jul 01 2016, 15:34:22) [GCC] [UTF-8]

I appear to be having an issue that started recently, where the web ui "resets" and I can't seem to figure out why. The logs just stop, then startup begins. Nothing jumped out at me from the logs. Its only recently and i noticed when i keep repeatedly being prompted to login. It appears downloading is working normally in between blurps, but i'd love for it to stop. Has anyone else noticed this behaviour?

Also, why does the queue have to load prior to the webui being active? Can't it be populated after the webui is loaded?  (not a complaint, just always wondered'

**Comment by Safihre** [comment]
Did you enable debug logging?
Could you send a log to safihre@sabnzbd.org?

**Comment by mgaulton** [comment]
Working on it

**Comment by Safihre** [comment]
Very strange, I thought it was #642 but sometimes it just seems to crash randomly in middle of loading files.
What OS are you on?

**Comment by Safihre** [comment]
Actually, it's always with 3 sec after a decoding operation.
Can you check if you can upgrade to yEnc 0.4?
https://bitbucket.org/dual75/yenc
Download it, and run ```setup.py install```

**Comment by mgaulton** [comment]
OpenSuse Leap 42.1  64bit with latest packages. I updated before i opened the ticket and waited until it continued happening.
I"ve installed yenc 0.4, shall I montiro to see if it continues?

**Comment by mgaulton** [comment]
So it does appear to be still happening. Sending logs off again.

**Comment by Safihre** [comment]
All crashes are still within exactly 3 sec of something decoding.. Something is going wrong there.
Otherwise I see some RSS activity around a crash, could you maybe temporarily disable your RSS feeds, see if that makes a difference?

**Comment by mgaulton** [comment]
sure. disabling now.

**Comment by mgaulton** [comment]
after disabling all but the one main RSS, running as a foreground app for a number of hours, i've now restored the startup scripts and started it that way, to see if the behaviour returns.

**Comment by mgaulton** [comment]
aaaaand as i finish writing that, it happened again :)

**Comment by Safihre** [comment]
With only difference the startup script?

**Comment by mgaulton** [comment]
Basically, yes. Looking it over now, but its never really changed in a couple years, except for minor tweaks, nothing recently.

**Comment by Safihre** [comment]
Maybe run it foreground with all RSS and see what happens? If really the script, maybe it's some optimization that disables anoying services?

**Comment by mgaulton** [comment]
i made a change to the startup script, going to see if it still happens. then i'll try that. I can't think of any reason it would only start doing it recently when the startup hasn't changed. but meh :) I'll keep you updated. Thanks again.

**Comment by Safihre** [comment]
No more crashes with your change? Can you share it? In case someone else needs it 👍

**Comment by mgaulton** [comment]
Really the only change was adding an explicit PATH statement to the script rather than relying on the init environment for the path.

**Comment by Safihre** [comment]
Sounds a bit like #686, seems the path to python is important.. Something to keep in mind for us in case of similar problems! 
Assuming it's fixed, so closing it :)

**Comment by mgaulton** [comment]
I think its good now, thanks for your patient help.
