### ISSUE TITLE
Should fetch be it's own event notification?

### ISSUE THREAD

**Issue by travisghansen** [sabnzbd/sabnzbd#697]
Just utilizing the new notification script feature (which is great!) and noticed I got 2 notifications of type ```download``` in the scenario when the nzb file is getting fetched vs uploaded directly.  Is that the intended behavior?

Thanks!

**Comment by shypike** [comment]
We lumped together some events under the same category, so that we don't get too many categories.
Of course no choice is ideal.

**Comment by travisghansen** [comment]
@shypike fair enough.  I noticed paused and resuming also fall under the download type with specific 'text' data.

Thanks!
