### ISSUE TITLE
Sabnzbd icon not visible on dark mode in macOS Sierra

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#698]
Reported on forum and on reddit, since I don't have Mac someone else needs to check this 😉

> There's a bug in macOS Sierra. When you use dark mode the menu bar icon which shows the speed and time left for a download is in black font so it doesn't show. Here's a screen shot to show what I am talking about.
> http://imgur.com/a/6V6KJ

**Comment by shypike** [comment]
The font color should probably  be revered. The main issue is how to find out whether this "dark mode" has been enabled in the first place. At worst we could add a "special" to set it.

**Comment by Safihre** [comment]
Maybe this?
http://stackoverflow.com/questions/37108924/python-code-to-detect-dark-mode-in-os-x-ei-capitan-to-change-the-status-bar-menu

**Comment by iandol** [comment]
`defaults read -g AppleInterfaceStyle` returns `Dark` so does work on macOs Sierra when in dark mode, but I think requires spawning a shell process from Python. The other method suggested was:

```python
center = NSDistributedNotificationCenter.defaultCenter()
center.addObserver_selector_name_object_(self,"enableDarkMode",'AppleInterfaceThemeChangedNotification',None)
```

I'm not a python programmer so can't test if this works.

**Comment by shypike** [comment]
As soon as I have upgraded to Sierra, I'll try.
It works fine on El Capitan.

**Comment by Safihre** [comment]
It seems Apple has fixed some bug in latest Sierra updates, because on both my machines it works again (also for SABnzbd 1.1.0).
Closing this!
