### ISSUE TITLE
sab project

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#699]
https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/

noticed our projects tab is empty.. 

example: https://github.com/cherrypy/cherrypy/projects

**Comment by jeffgeorge** [comment]
The "Projects" tab is just new Github functionality we're not using yet. Conveniently, unlike stuff like the Github Wiki, you can't turn it off.

It just comes down to if we feel a Trello-style Kanban board would be helpful to the project or not. I'm not sure it would, as we've only got 45 open issues right now and it's pretty clear what's in what status based on labels / milestones.

**Comment by thezoggy** [comment]
which is why i linked to the github page that talks about them and an example of how someone else uses them.

**Comment by Safihre** [comment]
I do like the Projects feature, but since it's really just @shypike and me doing the development, it works quite well with just the milestones and labels.
Or what added bonus would the Projects feature offer?

**Comment by Safihre** [comment]
Working a bit more with the labels now, to make it more clear what's what.
When more people join active development, we can do the projects feature 👍
