### ISSUE TITLE
Replace par2-classic.exe by par2cmdline.exe

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#702]
I was made aware of a whole range of jobs (mostly anime) that fails in SABnzbd **on Windows** because multicore-par2 chokes on joining the files with the error ```Could not write x bytes to "x" at offset 0: The parameter is incorrect```, which looks to be the only trigger for _par2-classic.exe_ (seems we've long been aware of this bug).
Unfortunately, after par2-classic joins the files it also chokes on verifying the output and uses 100% CPU until you manually kill it.

However, when I try the latest build **for Windows** of par2cmdline (v0.6.13) and use that as "par2-classic.exe", it works fine!
Since par2-classic is reallllllllllyyyyyyyy old, maybe using par2cmdline as fallback is a better idea? It is only used in verryyy rare cases, and now it seems that even in those cases it fails..

[Example NZB](https://github.com/sabnzbd/sabnzbd/files/514834/FFF.Shingeki.no.Kyojin.-.01.BD.1080p-FLAC.FF000966.nzb.gz)

**Comment by shypike** [comment]
@Safihre 
Is "the latest build for Windows of par2cmdline (v0.6.13)" just the classic program recompiled? Not another multi-core thing?

**Comment by shypike** [comment]
I'll add it.
