### ISSUE TITLE
Bug: 7zip password support on multipart files fails

### ISSUE THREAD

**Issue by edc71** [sabnzbd/sabnzbd#706]
Could you please implement password support like the rar password support?

TIA

E

**Comment by edc71** [comment]
Did some additional testing...

Seems on a split 7z archive unrar is called instead of 7z.

I have a nzb file with several 7z parts (xxx.7z.001 , 002 etc) and a password field.

The error I get is 'Trying unrar with password 'xxxx' <....> Unusable rar file'

It should be using 7z with -p.

**Comment by Safihre** [comment]
Could you send an example NZB (and the password) to safihre@sabnzbd.org? We're working on it!

**Comment by edc71** [comment]
Mail send ;)

The password is in the nzb file.

**Comment by Safihre** [comment]
Fixed in 6b5cca4, either for 1.2.0 or 1.1.1, depends what the boss thinks 😃

**Comment by edc71** [comment]
TNX for the quick response..

Cant wait for the next release ;)
