### ISSUE TITLE
Queue entries still tagged after deleting

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#708]
If 250 queue entries are selected and delete them these deleted entries are still selected.
If you select 250 more entries you will see 500 selected entries and if you delete them sabnzbd will need even more time to respond.

**Comment by Safihre** [comment]
On Glitter? I can't reproduce this, when I delete multiple items the counter goes down or when I delete a single item it also goes down.

**Comment by ggzengel** [comment]
I had a wild running RSS feed and got 3000 entries. While deleting these I have seen this race condition.
While this I will get a connection lost because of a not responding sabnzbd.
I'm using 1.1.1RC2.

**Comment by Safihre** [comment]
Yes, deleting 250 jobs is not an easy task. If logging is set to Debug or Info, the extra logging will cause major slowdown. 
It ain't made for that, to be honest.

**Comment by ggzengel** [comment]
Normally I have logging disabled (Error/Warning). In this case it was disabled too.

**Comment by Safihre** [comment]
Alternatively we would delete every job seperate, so it has time to "breath" in between, but this will make the total delete time even longer. So for now this is the best we can do, with all the tiny chunks of data to be deleted..

**Comment by thezoggy** [comment]
why not just add a parm to know if its a bulk request or not? then if its a bulk you just do it all at once/optimize for that situation (add to list / process in chunks)?

**Comment by Safihre** [comment]
We know it's a bulk request, because it's 1 request with multiple ID's. 
Not much to optimize, it just needs to go and do all the bookkeeping of removing files and updating the queue files.
