### ISSUE TITLE
Files with parenthesis in name are not saved after downloading on Freenas/Freebsd

### ISSUE THREAD

**Issue by famewolf** [sabnzbd/sabnzbd#709]
I've had a few occasions where a download was in history but not in the download folder.  It looks like in each case the filename had parenthesis in them.   I have every substitution I can enabled in settings so apparently parenthesis need to be replaced with something.   See attached:

![sabnzbd](https://cloud.githubusercontent.com/assets/4558832/19349423/e53efb00-9120-11e6-8ebc-0b1a27097235.png)
![sabnzbd2](https://cloud.githubusercontent.com/assets/4558832/19349424/e5422456-9120-11e6-9c9b-be81e540d443.png)
![sabnzbd3](https://cloud.githubusercontent.com/assets/4558832/19349422/e53df2e6-9120-11e6-9741-01cc3c59c1bc.png)

**Comment by sanderjo** [comment]
The ls commands show what you haven't got.

Why not the other way around: show what you've got. So something like 

```
ls /mnt/volume1/media/downloads
ls /mnt/volume1/media/downloads | grep -i melissa
ls /mnt/volume1/media/downloads | grep -i melissa | grep -i rock
```

**Comment by famewolf** [comment]
From "man ls"   "ls -- list directory contents"

The ls command is equivalent to the dos "dir" command.  It shows what IS in a directory.  I've shown the relevant portion of the ls below as well as ran the other two commands you mentioned in the correct directory.
The file was stored to /media/downloads/music and since I'm linux/freebsd only it's pretty easy to confirm it's not there.  Now I can't guarantee the parenthesis is the cause because I see other folders/files with the parenthesis in them but the file is certainly missing after showing completed. and it's not the first time it happened.


famewolf@hp810-135qe:/media/freenas/media/downloads/music > ls | grep -i melissa
famewolf@hp810-135qe:/media/freenas/media/downloads/music > ls | grep -i melissa | grep -i rock

Here's the section from the full listing where a file starting with M would appear (linux being more case sensitive than windows)

drwxrwxrwx 2 famewolf famewolf        0 Mar 24  2016 Kris Allen - Letting You In [2016] [320+Kbps] [Pirate Shovon]
drwxrwxrwx 4 famewolf famewolf        0 Sep 12 00:50 KT Tunstall - KIN (2016) [MP3~320Kbps]~[Hunter] [FRG]
drwxrwxrwx 2 famewolf famewolf        0 Jun  1 05:28 Ladyhawke - Wild Things [2016]
drwxrwxrwx 3 famewolf famewolf        0 Oct  8 04:20 Lana Del Rey - Ultraviolence (2014) [HDTracls 24-44,1]
drwxrwxrwx 9 famewolf famewolf        0 Mar 15  2016 [Lords-of-Usenet] Partner of SSL-News.info - 3 Doors Down - Us and The Night
drwxrwxrwx 2 famewolf famewolf        0 Sep 12 01:10 Meat Loaf - Braver Than We Are (Deluxe Edition) (2016)
drwxrwxrwx 2 famewolf famewolf        0 Oct  7 01:48 @MetalFreak@Outlaws@}}}Best Metal Ever {{{ [13+14] - `3.Doors.Down.-.Us.and.the.Night.(2016).vol0+1.par2` - 102,32 MB
-rwxrwxrwx 1 famewolf famewolf  7498297 Aug 23 19:30 Michael Buble - Nobody But Me.mp3
drwxrwxrwx 2 famewolf famewolf        0 Jul 10 05:27 Niki & The Dove - Everybody's Heart Is Broken Now [Deluxe] (2016) FLAC
drwxrwxrwx 2 famewolf famewolf        0 Apr  4  2016 Nine Inch Nails - The Slip - Flac
drwxrwxrwx 2 famewolf famewolf        0 Mar 24  2016 Peter Hollens - Misty Mountains Songs Inspired by The Hobbit and Lord of the Rings (2016) FLAC

**Comment by sanderjo** [comment]
The `ls` does show filename with parentheses, like "We Are (Deluxe Edition) (2016)". Do you agree? If so, it is NOT a rule that any download with parentheses fails, right?

I would inspect the sabnzbd.log. Maybe you have categories, or something else is going on.

**Comment by Safihre** [comment]
@famewolf, did you find the problem? :)

**Comment by famewolf** [comment]
Yes,  as you suspected the calling client Headphones moved the files after extraction to another directory.   Sabnzbd did it's own categorization to get it to the music folder but then headphones overrode it and moved it to different ones that separate mp3 and flac music.  I spent some time scratching my head because I couldn't find ANYTHING in the logs that even mentioned the file.  Sorry for the confusion.
