### ISSUE TITLE
sab 1.1.1RC2 -- purge

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#710]
clicking on the purge history button I see:

![sab](http://zoggy.net/sab-purge.png)

whats 'Purge History (page) 5' ?

the xhr shows:
`http://127.0.0.1:8092/sabnzbd/tapi?mode=history&name=delete&del_files=1&value=SABnzbd_nzo_vq1gfr%2CSABnzbd_nzo__p7ety%2CSABnzbd_nzo_801zsf%2CSABnzbd_nzo_8agwqg%2CSABnzbd_nzo_v_azoh%2C&output=json&apikey=xxx&_=1476418955390`

**Comment by thezoggy** [comment]
so it looks like that its deleting a page of history (current page? first page)? and showing the amount of items its going to remove..

**Comment by thezoggy** [comment]
ok that really should be reworded to state its deleting the first history page..  but seems honestly pretty pointless? 

so if one wanted to nuke all history.. they have to pull this up.. and click each section to get it all to be gone.. :(

**Comment by thezoggy** [comment]
ok, set my gui to show 250 items, went to page 2 out of 3..  told it to purge history (page)..  took 7.7s..

**Comment by thezoggy** [comment]
found a bug in glitter.. 
using tab layout..
queue is 400 items.. and your gui is set to display 250 at a time.. so thats two pages. 
i click to view page 2.. now click to view failed items.. which shows 7 but nothing.. because im on page 2 which doesnt exist.. thus when toggling failed/show all we need to reset the page

**Comment by Safihre** [comment]
This button is so you can easily remove specific items from history, for example if you search for a keyword and then hit this button, it will only delete the first page of matches.

**Comment by thezoggy** [comment]
yeah, just saying that the button label needs updating to reflect its use.. delete current history page...  since its pretty vague and scary for most to 'test' what these buttons do

**Comment by Safihre** [comment]
Will change it. The way it is now was just not to introduce another new untranslated bit of text.

**Comment by Safihre** [comment]
Found and fixed the pagination bug!

**Comment by thezoggy** [comment]
ty!
