### ISSUE TITLE
Slack notificatons

### ISSUE THREAD

**Issue by nate8199** [sabnzbd/sabnzbd#712]
Feature request

Notifications to Slack
https://api.slack.com/custom-integrations

Preferably with the option to select the catergories it sends alerts for

**Comment by Safihre** [comment]
Since 1.1.0+ we offer the option for a Notification Script, so any type of service can be added. 
Luckily, there is NZB-Notify by @caronc, which you can use from SABnzbd to send notifications to Slack and _many_ more service!
Checkout: https://github.com/caronc/nzb-notify
