### ISSUE TITLE
Sab fails a ton of my downloads, NZBGet dosn't.

### ISSUE THREAD

**Issue by Pocketpac** [sabnzbd/sabnzbd#715]
I really like Sab, it is nice and clean, and all around looks like a better downloader and it seems to "speak" to couchpotato, sonarr and sickrage better. That being said, it is unusable for me because almost 90% of my downloads fail due to missing files. When I run the same NZB through NZBGet it downloads them no problems. I looked through the log and I can't find any errors beyond it just can't find files.

Anyone able to point me in the right direction?

**Comment by Safihre** [comment]
Could you send us one of the NZBs that fails? This way we can actually do something about it. 
What OS are you in?

**Comment by Safihre** [comment]
@Pocketpac?
