### ISSUE TITLE
Notifications selection based on Categories

### ISSUE THREAD

**Issue by nate8199** [sabnzbd/sabnzbd#716]
Feature Request:

You pointed me to this when I asked about slack notifications..
https://github.com/caronc/nzb-notify

I would like to send notifications with a script in the category page, but it is missing the parameter options and I don't see a way around that.

Unless you can add a category option for alerts on  ~/sabnzbd/config/notify/

or parameter options in the category section

**Comment by Safihre** [comment]
The scripts on the Categories page refer to End of queue scripts, those are different from Notification script. End of queue scripts can do stuff like post process your videos etc. Technically you could also use it to make a Notification script, but not NZB-notify. 
In the Notifications page is where you setup NZB Notify, it will also allow you to select when the script should be called (which events). 
Or did I misunderstood what you would like to do? :)

**Comment by nate8199** [comment]
I guess I'm looking for slightly finer control of the alerts from the notification page.  I don't want alerts for every download, just for certain categories if that makes sense?

**Comment by Safihre** [comment]
That makes sense, so indeed a Feature Request it is. Can't promise it will be implemented quickly though..

**Comment by Renegade605** [comment]
I'll second this feature request. I have multiple people using my server to download and I would like to receive failed download notifications, but only for the downloads I initiate, not everyone's.

**Comment by Safihre** [comment]
Implemented.
