### ISSUE TITLE
7zip linux

### ISSUE THREAD

**Issue by nate8199** [sabnzbd/sabnzbd#719]
I noticed on my Ubuntu 16.04 server I installed the p7zip package but the option shows as unavailable on the config page.  

This is the page the (?) points  to, but has no mention of 7zip.

https://sabnzbd.org/wiki/installation/install-off-modules#toc8

**Comment by thezoggy** [comment]
we will update the wiki to reflect.. it was added in 1.0, the wiki page for extra modules isnt versioned.. so its probably based off 0.7.x which didnt have 7zip support.

https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L76

**Comment by Safihre** [comment]
Did you restart the Sabnzbd  service after installing 7zip? It might not detect it until a restart.

**Comment by nate8199** [comment]
Yes I have restarted multiple times

I also just did  git pull https://github.com/sabnzbd/sabnzbd.git master
and restarted sab, shows up the same

**Comment by Safihre** [comment]
What happens if you run ```7za``` from the terminal?

**Comment by nate8199** [comment]
strange, I had p7zip installed
7za prompted me to install p7zip-full, did that
restarted Sab
7zip on the config page is now gone completely
it is checked as enabled on the special page

I did not check if it disappeared after I updated master from git

**Comment by Safihre** [comment]
It will only show when its missing. If you'd installed Sabnzbd from the PPA everything would have been taken care of and you also get the latest releases almost as quick as via git  :)

**Comment by Safihre** [comment]
Wiki updated.
https://sabnzbd.org/wiki/installation/install-off-modules#toc8
