### ISSUE TITLE
Password field for a job doesn't accept null to clear the password

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#720]
In 1.1.1RC2 and possibly a bit earlier, I noticed that it is impossible to clear the password field for a job, by submitting null.
You can replace it with whatever other character, like a space, but you can't clear the password.
It always has the lock symbol.

This is using Glitter - Night, not sure about the other skins.

**Comment by Safihre** [comment]
You are right, will be fixed.
