### ISSUE TITLE
Same Priority isn't using both servers

### ISSUE THREAD

**Issue by PyRo1509** [sabnzbd/sabnzbd#721]
![image](https://cloud.githubusercontent.com/assets/2517304/19624117/8b80037e-989c-11e6-9669-cf7742669c03.png)

I has separate entires for both US and EU servers. They have the same Priority (0) as they are both unlimited. I give the US 10 connections and the EU 5. This has the effect of biasing more bandwidth to the US servers which are closer to me.

Anyway, after updating from 1.1.0 to 1.1.1RC2 [01d668a] today I noticed that all the connections are going to my EU server and none to the US. I increased the EU connection # and it used all the connections while the US server still got none.  The US server still gets traffic but seems to be only when it is missing from the EU server. Thus as the US server is alphabetically after the EU server it is acting like it has a priority of 1 with the EU a priority of 0.

**Comment by Safihre** [comment]
@PyRo1509 are you sure that both servers have the articles? This behavior might happen when a server is put on the ignore list for this job if it's missing too many articles of it. 
There is no change in server code for a long long time, so the behavior there should be the same across versions. That's why I expect a job specific effect.

**Comment by thezoggy** [comment]
per @shypike from https://github.com/sabnzbd/sabnzbd/issues/377
```I see servers of the same priority share the download.
The fastest one and/or the one with the most connections will take the largest share.```

**Comment by PyRo1509** [comment]
I jumped the gun. I was using a few poor downloads that seemed to be only on the EU servers. Using other downloads it operated as expected.  This is why I closed the issue soon after making it.
