### ISSUE TITLE
sab -- 1.1.1RC2 -- localhost / https / port

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#723]
you can click on the refresh button even if https is not enabled.
also hitting cancel on the popup still auto saves..

**Comment by thezoggy** [comment]
on windows, enabling https, after restart firefox wont load sab.. shows the error:
`SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG`

**Comment by thezoggy** [comment]
changing host from `localhost` to empty.. now I can get to sab via `https://local_ip:port` once adding cert exception.

**Comment by thezoggy** [comment]
putting the non https port empty, causes sab not to start:

```
2016-10-24 22:06:34,009::ERROR::[_cplogging:217] [24/Oct/2016:22:06:34] ENGINE Error in 'start' listener <bound method ServerAdapter.start of <cherrypy.process.servers.ServerAdapter object at 0x03155610>>
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 203, in publish
  File "cherrypy\process\servers.pyo", line 177, in start
  File "cherrypy\process\servers.pyo", line 232, in wait
  File "cherrypy\process\servers.pyo", line 458, in wait_for_occupied_port
IOError: Port 0 not bound on '192.168.0.2'

2016-10-24 22:06:35,130::INFO::[_cplogging:217] [24/Oct/2016:22:06:35] ENGINE Serving on https://192.168.0.2:8092
2016-10-24 22:06:35,131::ERROR::[_cplogging:217] [24/Oct/2016:22:06:35] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "cherrypy\process\wspbus.pyo", line 241, in start
  File "cherrypy\process\wspbus.pyo", line 221, in publish
ChannelFailures: IOError("Port 0 not bound on '192.168.0.2'",)
```

**Comment by thezoggy** [comment]
setting the http port to match the https port.. it starts but shows the warning: ` HTTP and HTTPS ports cannot be the same ` and has disabled https...

**Comment by thezoggy** [comment]
under https, I read `If empty, the standard port will only listen to HTTPS.` as the non http port set in sab will be https.. not ssl standard (443)... we prob should just put what the standard is.. since not everyone will know what it is and wont be able to get to the wiki/help page once they do this.. because the page wont load.

**Comment by thezoggy** [comment]
so looks like there is not a way to https with localhost?

**Comment by Safihre** [comment]
Let me respond point by point 👍 

> you can click on the refresh button even if https is not enabled.
> also hitting cancel on the popup still auto saves..

Yes, same for the QR-codes, every ```<button>``` triggers that unfortunately. Doesn't seem like a problem to me.

> I cant get to sab ui (https://localhost:port). I can still get to the http port just fine.

Yes, this is due to an old bug causing SAB to bind to IPv6 of localhost even though ```ipv6_hosting``` is turned off and a bug in how CherryPy binds to extra HTTPS ports. 
This freaks browsers out and I fixed it recently in develop.
@shypike we need b6972db5a7823e243850fde87368bce74d398fdb and 8e97097dfdcc81c0945fad869b8b7d04ee1e74a5 in 1.1.1.

> btw if you leave SABnzbd Port empty and save.. when sab starts it fails with:

That's a bad idea of course, and so far nobody seems to have done it since this behavior has been the same for years.

> under https, I read If empty, the standard port will only listen to HTTPS. as the non http port set in sab will be https.. not ssl standard (443)... we prob should just put what the standard is.. since not everyone will know what it is and wont be able to get to the wiki/help page once they do this.. because the page wont load.

This is not so bad, because if they would visit ```http://127.0.0.1:8080/sabnzbd/``` they get auto redirected to the HTTPS version ```https://127.0.0.1:8080/sabnzbd/```, so the page _will_ load.

> so it looks like there is not a way to do https with localhost?

If you leave the HTTPS Port empty like you mention above, it will only do HTTPS but on port 8080? 
So exactly what you want?
Side note: it's localhost, it's by definition not exposed to the outside..

**Comment by thezoggy** [comment]
if i normally runs sab as localhost:8082. then i want to do https instead... so now i have to use a different port.. so lets say 8092. but the 8082 port is still being used..  i dont want that... 

and about https and localhost.. maybe i just want a more secure lan?
i dont want a roommate/neighbor sniffing my packets :) 
exposing sab to the outside world (binding adapter) is a whole separate concern...  

`ipv6_hosting` i have enabled...

**Comment by thezoggy** [comment]
btw setting https port to empty and telling it to save, I see:
```
Restarting SABnzbd...

https://192.168.0.2:/sabnzbd/...
```

not sure if you want to detect when no port is set and not add `:` there...

**Comment by thezoggy** [comment]
ok finally got it, had to leave https port empty, so it uses the http port to do https... thus no non-http port..  but had to turn off `ipv6_hosting`.

`If empty, the standard port will only listen to HTTPS.` == confusing because standard port to mean meant 8080/443 since thats the standard port for https...  should probably clarify it to be `If empty, the Sabnzbd Port set above will only listen to HTTPS.`

**Comment by Safihre** [comment]
> btw setting https port to empty and telling it to save, I see: Restarting SABnzbd.. https://192.168.0.2:/sabnzbd/...

Will fix.

> should probably clarify it to be If empty, the Sabnzbd Port set above will only listen to HTTPS.

Will fix.

**Comment by Safihre** [comment]
> ok finally got it, had to leave https port empty, so it uses the http port to do https... thus no non-http port.. but had to turn off ipv6_hosting.

This is fixed after b6972db and 8e97097, just tested 👍 
```
2016-10-25 20:43:32,121::INFO::[_cplogging:219] [25/Oct/2016:20:43:32] ENGINE Serving on https://::1:8080
2016-10-25 20:43:32,786::INFO::[_cplogging:219] [25/Oct/2016:20:43:32] ENGINE Serving on https://127.0.0.1:8080
2016-10-25 20:43:32,795::INFO::[_cplogging:219] [25/Oct/2016:20:43:32] ENGINE Bus STARTED
```

**Comment by thezoggy** [comment]
ty!

**Comment by Safihre** [comment]
Should be all fixed now with latest changes in Develop and RC3!
