### ISSUE TITLE
NZB Order seems to be all over the place

### ISSUE THREAD

**Issue by Pocketpac** [sabnzbd/sabnzbd#725]
I have gone through the options, looked through google, and I can't figure out whats going on.

I have it set to Sort by Age, but it is adding NZB's where it wants to when using Couch/Sonarr/Sickrage. How do I get it to just add any new NZB's to the end of the queue. It is filling up the SSD it is running on because it will download one partially then start up on another then another because new things are popping up at the top and all over the place.

**Comment by Safihre** [comment]
Sort by Age doesn't mean 'sort by when I added the job to the queue', it means 'sort by when the original uploader added the job to usenet'. Inside the NZB it's stored when a file was uploaded to usenet. 
With this turned on, every time a job is added it will re-sort the queue and put the oldest job on top. This option is meant so you're always sure old jobs are tried first, in case the might dissappear (out of retention) while waiting in the queue. This is option still exists from the days when you only had up to few days of retention, not hundreds of days like nowadays.

**Comment by Pocketpac** [comment]
Sorry, I meant to say I Had it set to Sort by Age. I no longer do have it that way. Even with it off it is doing it, I have NZB's all over the place with varying levels of completedness.

**Comment by Safihre** [comment]
And what priority to they have? Maybe your Sonarr or CP categories have different priority linked to them?

**Comment by Pocketpac** [comment]
No, they are all set to normal. It is one of the things I looked at.

**Comment by Safihre** [comment]
So all jobs in your queue are currently set to Normal priority, and none of the categories have a priority other than normal, and Sort by age is turned off? 
And now when you add a new job, it's not added to the bottom of the queue?

**Comment by Pocketpac** [comment]
Ok, I let it go over night, and checked it the next morning, and I must make a small correction. It is not just sticking them every which way, but it isnt obeying the download order either. Here is the bottom of the queue. https://gyazo.com/82781103e551b70bb92c7b663ffc9ea8

**Comment by Safihre** [comment]
Do you have multiple servers? Because it almost seems as if Sab couldn't find the articles for a certain job and used the server to download another job. For example when it's out of retention.  
Maybe you can turn on Debug logging and send me a log after a night? Safihre@sabnzbd.org

**Comment by Pocketpac** [comment]
I think I found the problem, I had a bug in my post-download script that was cleaning up more than it should have, and when the subsequent file starts to unzip it errored because it couldnt find anything. My guess it Sick/Couch/Sonarr was adding back the same nzb and since SAB already had a bunch of files it showed a completed percentage.

Does that sound like a thing that would happen? I don't know how SAB handles failed download/extractions very well.

**Comment by Safihre** [comment]
Doesn't sound like a Sab thing.. But let's see.. Is it any better now with the order?

**Comment by Safihre** [comment]
Let us know if there's still anything we can help!
