### ISSUE TITLE
Duplicate detection fails when jobs come in too fast

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#727]
Only after the first job completes, there will be an entry in History.
So if new jobs come in before the first one is finished, they're not seen as duplicates.
This is good and bad.
You'd want a new job if the first one failed.
On the other hand, you do end up with duplicates if they come in too fast and the first one is OK.
We need to think this through again.

**Comment by thezoggy** [comment]
sounds like a better dupe checker is needed vs just using the static release name..  i know we also use the nzb crc... that should trump the s##e## check?

**Comment by Safihre** [comment]
What can we improve in the checker? We analyze the title and the NZB CRC.

**Comment by shypike** [comment]
The CRC checker just protects against true duplicates, so two NZBs of the exact same post.
The Show/S/E checker should protect against alternative posts of the same episode.
The latter is based only on filename and meta-data from the NZB.
The problem is that the S/S/E checker only uses the history database. Instead it should also check all NZBs in the download queue.

**Comment by ErikBrown2** [comment]
This issue with the duplicates is in my opinion as follows:

1) When the RSS feeds provide multiple NZBs for similar downloads before the first is fully downloaded, then these NZBs are not detected as duplicate.
2) Often multiple NZBs from different sources are available for very similar downloads. But with slightly different names. For instance a NZB name ending on KTR or xpost etc. But often the first part of the NZB name is the same. These are also not detected as duplicates.

To implement a work around for video downloads, I have added the following functionality to my pre-queue and postprocessing scripts:

The pre-queue script has a list of recently added NZB names and their download status in a file on disk. When a new NZB is to be added to the queue, then the pre-queue script checks if the name is already in the list. If it is in the list and with a status that the download was complete, then the new NZB will be rejected. If it is in the list but with a status that the download was not complete (so manually deleted, download failed or still in the queue) then it gets accepted to the queue but in paused mode. 

When a download is complete, then the post processing script opens the NZB list of the pre queue script and marks the NZB as successfully downloaded. It also checks the queue for paused NZBs with similar names. If it finds such NZBs in the queue, then it deletes them. 

To determine if a NZB is similar, I ignore the last part of the NZB name that most likely only mentions the name of the release. For instance, I treat the following two NZBs as duplicates:

A video file 720p HDTV x264-DTOD-xpost
A video file 720p HDTV x264-KTR

but these are different:

A video file 1080p HDTV x264-DTOD-xpost
A video file 720p HDTV x265-KTR

For the NZB name comparison, I ignore the last part of the NZB name after any of the following words, which ever appears further to the end of the NZB name: 1080p, 720p, x264, h264, x265, hevc

I am happy with the functionality in my scripts. It avoids unnecessary duplicate downloads. I use it only for videos but it can be configured also for other download types. I am not sure if you would like to add similar functionality to SABnzbd. I am also happy to share my VB.net based scripts if anybody is interested.

**Comment by Safihre** [comment]
@ErikBrown2 Indeed that's exactly what we should implement for SABnzbd, so that it automatically tries the next one if the first one fails and removes all the duplicates only when 1 of them succeeds.

**Comment by thezoggy** [comment]
> 
> 
> This issue with the duplicates is in my opinion as follows:
> 
>     1. When the RSS feeds provide multiple NZBs for similar downloads before the first is fully downloaded, then these NZBs are not detected as duplicate.
> 
>     2. Often multiple NZBs from different sources are available for very similar downloads. But with slightly different names. For instance a NZB name ending on KTR or xpost etc. But often the first part of the NZB name is the same. These are also not detected as duplicates.
> 
> 
> To implement a work around for video downloads, I have added the following functionality to my pre-queue and postprocessing scripts:
> 
> The pre-queue script has a list of recently added NZB names and their download status in a file on disk. When a new NZB is to be added to the queue, then the pre-queue script checks if the name is already in the list. If it is in the list and with a status that the download was complete, then the new NZB will be rejected. If it is in the list but with a status that the download was not complete (so manually deleted, download failed or still in the queue) then it gets accepted to the queue but in paused mode.
> 
> When a download is complete, then the post processing script opens the NZB list of the pre queue script and marks the NZB as successfully downloaded. It also checks the queue for paused NZBs with similar names. If it finds such NZBs in the queue, then it deletes them.
> 
> To determine if a NZB is similar, I ignore the last part of the NZB name that most likely only mentions the name of the release. For instance, I treat the following two NZBs as duplicates:
> 
> A video file 720p HDTV x264-DTOD-xpost
> A video file 720p HDTV x264-KTR
> 
> but these are different:
> 
> A video file 1080p HDTV x264-DTOD-xpost
> A video file 720p HDTV x265-KTR
> 
> For the NZB name comparison, I ignore the last part of the NZB name after any of the following words, which ever appears further to the end of the NZB name: 1080p, 720p, x264, h264, x265, hevc
> 
> I am happy with the functionality in my scripts. It avoids unnecessary duplicate downloads. I use it only for videos but it can be configured also for other download types. I am not sure if you would like to add similar functionality to SABnzbd. I am also happy to share my VB.net based scripts if anybody is interested.

the context of duplicate is different here.. nzb vs the end content vs end goal.

just because the video file is the same series/episode does not mean its a duplicate, different groups may have used different source+settings.. which would produce different videos of the same content.

also different groups posting the same file, while the end result may be the same the nzb itself is different. and depending on what your wanting, this could be desired because release by x was dmca'ed while release by y group was not. 

then finally, the actual same nzb being cross posted or tried to be processed multiple times.. that 'dupe' is what is handled. by exact title matches / nzb crc.

**Comment by puzzledsab** [comment]
Keep in mind that this is a very complicated task if you dig too deep, and it's basically the main problem that Sonarr and Radarr are trying to solve. Those are larger programs than SABnzbd.

**Comment by ErikBrown2** [comment]
For me as end user of SABnzbd, it does not matter if the video is from group 1 or group 2 and that there are small differences between them. Anyone of them is usually good enough. But I ended up often with multiple versions of the same video. So my script now solves this now nicely.

**Comment by ErikBrown2** [comment]
For me as end user of SABnzbd, it does not matter if the video is from group 1 or group 2 and that there are small differences between them. Anyone of them is usually good enough. But I ended up often with multiple versions of the same video. So my script now solves this now nicely. 

I have added another function to the script. The EndOfQueue script now checks if there is any NZB in the NZB list that is not yet downloaded but also not in the queue. If this is the case, then it deletes the NZB from the NZB list.

**Comment by thezoggy** [comment]
Again it comes down to context. Different releases of the same thing are not dupes.. one may have issues one may be better quality. That's why it's generally better to let the 3rd party app to handle all that which has metadata from the indexer/knows the intent (quality upgrade/failed download replacement/repack/etc). Sab should only care if the same nzb was added to stop user error/bad setups

**Comment by JackDandy** [comment]
> Different releases of the same thing are not dupes  
    
Show/Season/Ep is too blunt for some use cases - if that is indeed one of the entire conditions for a dupe flag.
  
> it's generally better to let the 3rd party app to handle all that  
  
If dupe checking applies to API items, can a "skip_chk_dupe" option be added if there isn't one already.

**Comment by hulleyrob** [comment]
Ive just had this happen today when I accidentally spammed download in sonarr. 

This resulted in 5 (yes ok I thought it hadn't clicked so I spammed it) identical downloads.

I was surprised when the dupe detection didn't pick up on it and it tried to download all 5.

Just adding in case you need a way to recreate it.

**Comment by thezoggy** [comment]
> 

what version of sab are you using.. sab 3.7.2 or 4.0rc1?

**Comment by hulleyrob** [comment]
3.7.2

**Comment by Safihre** [comment]
Closed by #2728 🥳
