### ISSUE TITLE
sab 1.2 -- rss feed

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#728]
might tie this into the category changes?
right now the rss feed will show the list of matches/non matches.. 
if you have several things to manually pick out of the not matched section.. its a pain due to the page refreshing after clicking download. rather than lose the clients place we should just update ui vs doing it on the backend and refreshing...

**Comment by thezoggy** [comment]
also on the rss 'downloaded' section, be nice if we exposed the size/date there and offer the ability to sort on that page..

**Comment by Safihre** [comment]
@thezoggy I pushed some changes to SP's PR #687 in the ```feature/SxxEyy-as-Match-Filter``` branch.
It will now register fetch-moment and display the age of a post.
Didn't implement sorting (yet).

**Comment by Safihre** [comment]
Now also added sorting.

**Comment by thezoggy** [comment]
ty
