### ISSUE TITLE
sab 1.1.1RC3 -- "External internet access"

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#729]
setting:
`config > general > External internet access`
> You can set access rights for systems outside your local network

Looks like that defaults to `No access`..  which would give me the impression that sab would be flat out unreachable. However from testing I can see that the UI and api is in fact still reachable (https) no matter what option I select (rebooting in between).

```
<select name="inet_exposure" id="inet_exposure" class="select">
                            <option value="0" selected="selected">No access</option>
                            <option value="1">Add NZB files </option>
                            <option value="2">API (no Config)</option>
                            <option value="3">Full API</option>
                            <option value="4">Full Web interface</option>
                            <option value="5">Full Web interface - Only external access requires login</option>
                        </select>
```

looking at config code,
```
inet_exposure = OptionNumber('misc', 'inet_exposure', 0, protect=True) # 0=local-only, 1=nzb, 2=api, 3=full_api, 4=webui, 5=webui with login for external
```

logger shows (cleaned up ip/apikey), no user-agent for the external request:
```
2016-11-08 17:00:24,579::DEBUG::[interface:522] API-call from 166.173.###.### [??] {'output': [u'json', u'json'], 'apikey': u'removed', 'mode': u'queue', 'start': u'0'}
```

**Comment by thezoggy** [comment]
also to note, the inet_exposure settings are a bit confusing.. and wiki serves no help.
because i dont know if what im changing affects the ui or api.. or both.. or just one..

**Comment by thezoggy** [comment]
sab host: empty
sab username+pw set..
external internet access: no access
no local network ranges set..
enable https checked
no https port, cert and key set.

only special option i have changed from default is 'fixed_ports'.

**Comment by Safihre** [comment]
It's quite simple: if you don't set a List of local network ranges, than how is SAB supposed to know what's external or internal?

**Comment by Safihre** [comment]
But I will introduce sub-groups in that dropdown to make it more clear what's what!
And add to the text that setting the local network ranges are required.

**Comment by thezoggy** [comment]
to me, local network = private ip range..  and maybe include wan ip...  if that option depends on another.. it should clearly noted/setup in such a way that you infer it.

**Comment by thezoggy** [comment]
good deal..

**Comment by Safihre** [comment]
Since SAB is by default not accessible from other PC's (you have to set the host to 0.0.0.0 manually), people should know what they are doing when changing that. 
But the new text makes it more clear:
![image](https://cloud.githubusercontent.com/assets/5703454/20140236/6c33de18-a68a-11e6-87d5-98c0ddbc53fb.png)

and

![image](https://cloud.githubusercontent.com/assets/5703454/20140230/5c9e550a-a68a-11e6-98a0-d297c5fbbee0.png)

**Comment by thezoggy** [comment]
to me the fist opt group should be `Full API & No Web UI` since you have to infer that by reading the next opt-group....   
offering the option that matches the opt-group label is confusing in itself since the lack of context awareness of the opt-group makes it odd... but by product of not changing the translated texts.. i know..

the list of local network ranges.. can you do cidr format? do you do a list thats denominated by coma? space? can you do wildcard masks? etc... should update our example text and example on wiki

**Comment by Safihre** [comment]
> offering the option that matches the opt-group label is confusing in itself since the lack of context awareness of the opt-group makes it odd... but by product of not changing the translated texts.. i know..

I checked, and in all translations "API" is just "API". So will make the label to say just API, seems to be the best we can do with the texts we have.

> the list of local network ranges.. can you do cidr format? do you do a list thats denominated by coma? space? can you do wildcard masks? etc... should update our example text and example on wiki

Will make it more clear in the wiki that it can be a list, so multiple items separated by a comma. For SAB users this should be more than enough, no need for wildcards etc.
