### ISSUE TITLE
Adding Scripts Folder, breaks notifications 

### ISSUE THREAD

**Issue by thechile** [sabnzbd/sabnzbd#732]
Using latest stable 1.1.1 build if i add a folder info "Folders=>Scripts Folder" and then select the "Notifications" tab i get the below error.

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 2891, in index
    return template.respond()
  File "_usr_share_sabnzbdplus_interfaces_Config_templates_config_notify_tmpl.py", line 3285, in respond
NotFound: cannot find 'lower' while searching for 'lower'
```

**Comment by Safihre** [comment]
Very odd.. I tried to reproduce it on Ubuntu 16.04, but I can't.. I tried with empty folders and with folders full of scripts.
What is the path to the folder? And what files are in that folder?

**Comment by thechile** [comment]
I am using this docker container 

https://github.com/linuxserver/docker-sabnzbd

Within sabnzbd i have tried with /config/data, /config/scripts and /tmp and all result in same error when changing to the notify tab. All other tabs work OK. The only fix is to remove the script path from Folders page.

Container is using Python 2.7.12.

**Comment by Safihre** [comment]
Paging @sparklyballs (the dev for linuxserver), could you confirm if this is working for you?

I tried to get the Docker running, but I am failing miserably.
What is the complete idiots guide to use your Docker? I installed the Docker service successfully on my Ubuntu VM, pulled your docker, but when I do a simple ```run linuxserver/sabnzbd``` the ports are not exposed. But I don't understand what to do after ```docker create --name=sabnzbd -p 8080:8080 -p 9090:9090 linuxserver/sabnzbd``` (or does it need all the other parameters?).

**Comment by sparklyballs** [comment]
@Safihre 

`docker start sabnzbd`

I have tried with empty folders and am not seeing any issues with the notification tab in our docker

@thechile i think you should tell us what's in the scripts also... that could be the most important information.

**Comment by thechile** [comment]
nothing special, just this in my compose. I tried rm/rmi and after rebuild it does the same, so not sure what is happening. 

```
  sabnzbd:
   container_name: sabnzbd
    image: "linuxserver/sabnzbd"
    volumes_from:
      - "shares"
    volumes:
      - "./configs/sabnzbd:/config"
    ports:
      - "9090:9090"
      - "8080:8080"
    environment:
      - "PUID=1001"
      - "PGID=1001"
    restart: "always"
```

I have tried specifying directories that were both empty and with simple bash script and it behaves the same. Bash script was just 

```
#!/bin/bash
touch /tmp/sabnzbd.notification.test
```

**Comment by thechile** [comment]
not sure what changed but i reset everything, tried again and worked as expected this time. thanks.

**Comment by mhann** [comment]
Hi,

I have just run into this issue as well. When I go to the notifications tab I see:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 2891, in index
    return template.respond()
  File "_usr_share_sabnzbdplus_interfaces_Config_templates_config_notify_tmpl.py", line 3285, in respond
NotFound: cannot find 'lower' while searching for 'lower'
Powered by CherryPy 6.0.2
```

The script folder I have it set to is: `/home/sabnzbd/notifications`

An `ls -lah` of that folder gives:

```
root@thunderbird-2:~# ls -lah /home/sabnzbd/notifications
total 12K
drwxrwxrwx  2 root root 4.0K Dec 23 17:49 .
drwx------ 16 root root 4.0K Dec 23 17:57 ..
-rw-r--r--  1 root root   20 Dec 23 17:49 test123.sh
root@thunderbird-2:~#
```

and a cat of that shell file is:

```
root@thunderbird-2:~# cat /home/sabnzbd/notifications/test123.sh
#!/bin/bash
echo ""
root@thunderbird-2:~#
```

This is all I get in sabnzbd stdout:

```
2016-12-23 17:59:59,703::INFO::[_cplogging:217] [23/Dec/2016:17:59:59] HTTP
Request Headers:
  REFERER: https://94.23.255.47:9090/config/folders/
  Remote-Addr: 80.229.21.5
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
  CONNECTION: keep-alive
  COOKIE: user="2|1:0|10:1481916109|4:user|44:OTMwMWUxNDljMDJjNGVhNmEwZmRhZmE4N2IxNGY3NWM=|1e21411c01c022a1a87801c2783cc4fa95c074d49d2eb5bdf06fe571ff2aaa81"; _ncfa=wHjCjXRNjj2owehA%2fasI0zaYbtYAtbTCYzaYMvQrLl4%3dbd%2fg9D0I14snr0jz1xTXwkwz9uaNsoNeN3CHyG0OxiYl085oaY0mu0JmWdJJG9lO; _ga=GA1.1.1872699786.1481816666; login_cookie=64635591321dfc0c1fd210391d1347a2a7c5ea54; login_salt=343; _pk_id.1.9415=81a40301aefe1ea9.1481817382.23.1482510545.1482510537.; snatched_view=list; advanced_toggle_checked=1; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; session_id=d0bbdc121b1c2e23c20055a7e996fe772b501c84
  HOST: 94.23.255.47:9090
  UPGRADE-INSECURE-REQUESTS: 1
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  ACCEPT-LANGUAGE: en-US,en;q=0.8
  ACCEPT-ENCODING: gzip, deflate, sdch, br
2016-12-23 17:59:59,703::ERROR::[_cplogging:217] [23/Dec/2016:17:59:59] HTTP
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 2891, in index
    return template.respond()
  File "_usr_share_sabnzbdplus_interfaces_Config_templates_config_notify_tmpl.py", line 3285, in respond
NotFound: cannot find 'lower' while searching for 'lower'
```

I am running on ubuntu 16.04 and have sabnzbd version: `Version: 1.1.1-0ubuntu1~jcfp1~xenial`

This is not using any docker containers, just a plain sabnzbd install from apt. I have tried both with an empty folder and with the bash script in the folder - same error.

I'm not sure exactly what @thechile meant by 'reset everything'? But I would prefer not to uninstall/reinstall sabnzbd if possible (configuration and all that).

I have also chmodded the folders to 777 for testing purposes and that also made no difference.

Hopefully there is enough information there. If you need anything else let me know and I'll get it for you :)

Thanks,
Marcus

**Comment by thezoggy** [comment]
Why cherrypy 6.0.2.... Running old Sab or did you install cherrypy yourself?

**Comment by Safihre** [comment]
@thezoggy that's the version we include with 1.x.x releases!

**Comment by thezoggy** [comment]
i could have sworn in 1.1.x it was newer than 6.0.2....

**Comment by thezoggy** [comment]
@Safihre just fyi, looks like cherrypy is up to 8.2.0 now as of 10 hours ago.. changelog:
```8.2.0
-----

* #1463: CherryPy tests are now run under pytest and
  invoked using tox.

8.1.3
-----

* #1530: Fix the issue with TypeError being swallowed by
decorated handlers.```

**Comment by Safihre** [comment]
@thezoggy I saw, but doesn't apply to us and doesn't even include the PR that I send in to them weeks ago, sadly.
Guess we'll always be patching CP..

**Comment by Safihre** [comment]
@mhann could you try the 1.2.0Beta1? 
It's now available through the PPA automatic update!
