### ISSUE TITLE
No_penalties Special Switch does not work as intended.

### ISSUE THREAD

**Issue by sabfreezes** [sabnzbd/sabnzbd#734]
Cross-Thread here: 
#733 

In a nutshell, this "switch" is supposed to prevent sab locking out for 1min rather than 10, but despite the checkbox being on or off, it doesn't stick and as per the thread above... still locks out for 10min pointlessly.

Sab v.720 didnt use to do this lockout :(

**Comment by thezoggy** [comment]
as noted in the other issue you created, it does for optional (block/fill) servers, not 'main'.
its been coded this way back in 2009/2010 and that code has not been touched.

**Comment by Safihre** [comment]
@thezoggy in the other thread you mention that the server needs to be optional for the switch to work, but the if statement says opposite? 
So it overwrites the longer penalty with the short one if the switch is on _and_ server not optional?
```python
if (not server.optional) and cfg.no_penalties():
```

**Comment by thezoggy** [comment]
Look at the logic right above it

**Comment by Safihre** [comment]
Aah yes, but he's saying he's getting Too many connections, that one is separate from that check since ```block``` or ```penalty``` variables are never set.
Due to the logic only some penalties get overwritten with the shorter penalty..

```python
                            if ecode in ('502', '400', '481', '482') and clues_too_many(msg):
                                # Too many connections: remove this thread and reduce thread-setting for server
                                # Plan to go back to the full number after a penalty timeout
                                if server.active:
                                    errormsg = T('Too many connections to server %s') % display_msg
                                    if server.errormsg != errormsg:
                                        server.errormsg = errormsg
                                        logging.warning(T('Too many connections to server %s'), server.id)
                                    self.__reset_nw(nw, None, warn=False, destroy=True, quit=True)
                                    self.plan_server(server.id, _PENALTY_TOOMANY)
                                    server.threads -= 1
```

**Comment by sabfreezes** [comment]
@thezoggy @Safihre So after a full day of setting both my main (and backup) servers as Optional... with the no penalties set to ON.... it doesn't seem to have affected the problem.

The 10min lockout still persists.

**Comment by sabfreezes** [comment]
Look @ the idented lines... exactly 10min apart (lockout..reattempt..fail.. lockout again!)

WARNING 13/11/2016 10:37 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 10:27 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 10:21 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 10:18 Too many connections to server reader.usenetbucket.com
WARNING 13/11/2016 10:18 Too many connections to server reader.usenetbucket.com
	WARNING 13/11/2016 10:17 Too many connections to server ssl-us.astraweb.com
	WARNING 13/11/2016 10:06 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 10:03 Too many connections to server reader.usenetbucket.com
	WARNING 13/11/2016 09:56 Too many connections to server ssl-us.astraweb.com
	WARNING 13/11/2016 09:47 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 09:46 Too many connections to server ssl-us.astraweb.com
WARNING 13/11/2016 00:49 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:54 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:53 Too many connections to server ssl-us.astraweb.com
WARNING 12/11/2016 22:53 Too many connections to server ssl-us.astraweb.com

**Comment by thezoggy** [comment]
if i recall correctly from looking at the code, he's hitting too many connections.. block is getting set to true which later determines how much penalty to do...   

honestly first step i'd recommend is try changing your astra password to rule out rogue apps/people that have your credentials. 
2ndly if you have another usp to try, disable astra and try them and see if you have the same problem.. need to find out if its an astra issue specifically or not. if it is astra specifically, show us your server details page (mask username/pw) so we can see what timeout/options you are using.. etc

**Comment by sabfreezes** [comment]
@thezoggy - it shows clearly that its hitting the too many connections in UNB as well as astra in the post above...

**Comment by Safihre** [comment]
Agree with @sabfreezes, if we have such an option, it should be applicable to any type of penalty.
I have now updated the code to work like that: 7c412e6
