### ISSUE TITLE
'Check before download' malfunctioning

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#738]
Users have been reporting that the 'Check before download' feature has been malfunctioning.
Symptoms are that they get stuck at 99% Checking.
So far I have been unable to reproduce.

**Comment by shypike** [comment]
Still think we should remove this one, it's such a can of worms.

**Comment by thezoggy** [comment]
Maybe just suppress it to a special only option.. default to it off.

**Comment by thezoggy** [comment]
@Safihre thoughts on just moving this off to special only for 2.2+

**Comment by Safihre** [comment]
Yeah I thought about it, but then again it's also quite a nice feature. I just have to fix that stupid stalling bug. 
Together with the `failed to import` I should be able to fix this for the next release.
