### ISSUE TITLE
Port changed

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#739]
For some reason my port number randomly changed.  Nothing else in my config was affected.

**Comment by thezoggy** [comment]
only reason a port would change is if the port is used.. you can just enable the special option to not change the port `config > special > fixed_ports`.. but then if the port is in use when it starts.. it throws error/wont start.

**Comment by Safihre** [comment]
I always found it strange that SAB just does that without any notification.
Will add a notification when this happens.

**Comment by labrys** [comment]
@thezoggy I understand starting up on a new port as a backup, however it saving that change to the ini file shouldn't happen.  I believe accidentally starting two instances of sab might have been the cause as its the only thing i run on my configured port.

**Comment by Safihre** [comment]
Normally sabnzbd will detect on startup if an instance of Sabnzbd is running with the same version. But this check doesn't work when you run from develop! 

Changing the port only temporarily is also confusing for users..

**Comment by labrys** [comment]
I always run develop, so that explains that :)

**Comment by Safihre** [comment]
Notification implemented.
