### ISSUE TITLE
Version tag 1.1.1 has version set to 'develop'

### ISSUE THREAD

**Issue by chenry3** [sabnzbd/sabnzbd#740]
Looks like the version in sabnzbd/version.py was set to 'develop' instead of '1.1.x' on the 1.1.x branch as well as tag 1.1.1

1.1.1:
https://github.com/sabnzbd/sabnzbd/blob/1.1.1/sabnzbd/version.py

1.1.0:
https://github.com/sabnzbd/sabnzbd/blob/1.1.0/sabnzbd/version.py

Looks like this was introduced at https://github.com/sabnzbd/sabnzbd/commit/790bcd7bd6dd13c145e6b50aee3c670e2365aa29#diff-629dcde1d9c0500bffd1356b61b7a906

**Comment by Safihre** [comment]
True, but people shouldn't be using those.
Either you use the ```master``` branch or the ```develop``` branch.

**Comment by Safihre** [comment]
Tried to clear up the README to reflect which branch is intended for end-user's.
https://github.com/sabnzbd/sabnzbd/commit/c6d76b18560b8eb37074960dfc3194a47aea2186

**Comment by chenry3** [comment]
Thanks for the response.

Just FYI - I actually discovered this using the 1.1.1 release tag which seems to also have the vesrsion set to develop:

https://github.com/sabnzbd/sabnzbd/blob/1.1.1/sabnzbd/version.py

**Comment by Safihre** [comment]
True, the tags are also just for our reference when we build the releases.
We hope people to just stick to `master` :P

**Comment by thezoggy** [comment]
yeah, ideally the version set in the file should have been 1.1.x to follow the trunk name.. honestly not sure why were creating these branches.. they were only supposed to be created when we needed to do a hotfix for code thats branched from the master/dev...  it just causes confusion. and if we need to get to that code we can just check out by using tags..

**Comment by Safihre** [comment]
@thezoggy Although I personally not a fan of it, it is nessecary:
For example 1.1.1 was released after `develop` was already far ahead of `1.1.x`. It would not have been possible to make a tag for 1.1.1 without the `1.1.x` release branch.

**Comment by thezoggy** [comment]
https://github.com/sabnzbd/sabnzbd/compare/master...1.1.x

can see that 1.1.x branch has 1.2.0 references... once 1.1.1 went to master.. that branch should honestly have gone away. if a new feature branch was needed, you can base it off master at that point.. or checkout via tag
