### ISSUE TITLE
Use regular Python for macOS builds

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#748]
Leaving it here since I know @shypike is busy now:
I always thought that we use ApplePython instead of a more recent version of Python for the macOS builds because otherwise the menu won't work.
However, I just installed Python 2.7.12 on macOS Sierra and after installing `pip install pyobjc` the example code from ["Ridiculously Uncomplicated Mac os x Python Statusbar apps"](https://github.com/jaredks/rumps) gives me a working menu, also directly from Python without even building an app.
So we should be able to do the same, right? And this way we can have 1 installation for all macOS versions?
With up-to-date OpenSSL..

Python 2.7.13rc1 behaved a bit different due to some changes there relating to shared package resources, so might have to take a second look at that.

**Comment by shypike** [comment]
The sole reason for using Apple Python is the connection to the "Foundation" library, enabling the icon en menu in the top menu bar.
If another Python offers that, we can use it instead.

**Comment by Safihre** [comment]
Installing `pyobjc` provides the Foundation module :)

**Comment by Safihre** [comment]
On a clean Sierra VM 2.7.13rc1 also worked, although unlike what the release notes say, it's still using system OpenSSL..
```
Python 2.7.13rc1 (v2.7.13rc1:4d6fd49eeb14, Dec  3 2016, 13:01:23) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Foundation
>>> import AppKit
>>> import PyObjCTools
>>> import objc
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
```

**Comment by Safihre** [comment]
Aah, in OSX 10.6+ they always use the system OpenSSL: http://bugs.python.org/msg283028
Kind of confusing, but I'm not going to risk asking why..

**Comment by Safihre** [comment]
No luck so far: I tried to get it all to work but the `pyObjTools` that you can install via `pip` is newer than the build-in one and now the menu doesn't work.
The errors are very ambiguous and I just don't know enough about ObjectiveC to get it to work.
