### ISSUE TITLE
Configuration UI change suggestion

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#750]
This suggestion concerns the following 2 options:

-Check before download
-Abort jobs that cannot be completed

It's my understanding that if these options are both enabled: The behaviour defined by  "Abort jobs that cannot be completed" would never trigger as "Check before download" would go through all articles and therefore only fail the job when all articles have been tested as missing.

So my suggestion is to convert these 2 options into a radio button type configuration, so that only one of these options can be enabled at a time.

**Comment by jcfp** [comment]
> It's my understanding that if these options are both enabled: The behaviour defined by "Abort jobs that cannot be completed" would never trigger

This is not necessarily true. A server may falsely claim to have an article but not actually have it, have an 'emptied' version instead (i.e. headers present but content removed), or simply supply damaged goods. In all of these cases, pre-check passes but the job may well be halted during d/l by the completion check.

**Comment by Cpuroast** [comment]
Hi, yeah my mistake, I also hadn't considered a failure after pre-check, so for example on large job with a slow connection. Pre-check succeeds, then something happens to the articles during the download and the early abort mechanism will kick in,
I'll close the issue.
