### ISSUE TITLE
Web UI - Drag and Drop imports set category, preventing category detection from taking place.

### ISSUE THREAD

**Issue by richseviora** [sabnzbd/sabnzbd#751]
Observed this issue on my system via web UI. 
Setup:

* Server = SabNzbd v1.1.1 on Win10.
* Client Chrome 54.0.2840.98

Steps to reproduce:

1. Open web client, access config.
1. Add a category with indexer/group tags. IE "TV*". Save, etc. as usual.
1. Go to queue interface, and import a NZB with <meta type="category">TV</meta> via drag and drop function.

Expected result:

NZB is imported and the custom category is applied.

Actual result:

NZB is imported with the default category applied.

Inspection of the POST call to the API revealed that `cat` is being set to `*` (default as per API). I think what it happening is that the API is importing the NZB using the default category as instructed by the web client, instead of assuming no category and therefore applying its usual category processing rules as per [usual](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L770). I don't know the code well enough to trace through to confirm.

**Comment by Safihre** [comment]
Fixed this a while ago, will be in 1.2.0 Beta's soon :)

**Comment by Safihre** [comment]
(thanks for reporting! :+1: always good to know users want to help us find and fix problems!)
