### ISSUE TITLE
Remove option to disable API-key

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#755]
Why do we even offer this option?
It seems like a bad idea.

**Comment by shypike** [comment]
It's off by default.
Just move it to "Specials", in case anyone actually needs it.

**Comment by sanderjo** [comment]
I often use "diabale API-key" when I'm testing some API functionality with curl and I don't want the api-key in the commandline.
Futhermore: the web/api-interface is only available on my LAN, so I don't care too much about security. I have no password on my home-sab-webinterface either.

Moving to Specials is OK for me.

**Comment by shypike** [comment]
@sanderjo Even with SABnzbd restricted to localhost, you are not safe. The security leak is that an external website can access your local SABnbd due to XSS vulnerabilities. The root cause is that web browsers allow external sites to access internal resources.
