### ISSUE TITLE
Web server backend doesn't start in 1.2.0 Beta1 with "enable_cherrypy_logging" enabled

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#758]
Just saw that 1.2.0 Beta1 was out so I decided to give it a try.

It seems not to like my existing ini file. Sab itself starts, icon shows up in the Apple menu bar, but the web server part does not.
Nothing in the logs either.

If I remove my ini file, everything seems fine, wizard shows up, and then sab's UI.

So it seems there's a parameter in my existing ini file that is preventing 1.2.0's web server backend from starting, trying to dig through it to find out what's causing the issue.
This wouldn't be a problem for new installs, but it will be a massive problem for upgrades.

OS is macOS 10.12.2.

Something to note, this would be a lot easier to make a file comparison if the ini file structure wasn't random.

**Comment by Cpuroast** [comment]
Ok found the issue:

If the ini file has "enable_cherrypy_logging" set a value of 1, the web server portion of sab 1.2.0 beta1 does not start.

On a fresh ini file, "enable_cherrypy_logging" does exist but has a value of 0, not 1.

Probably something to fix for beta2.

**Comment by Safihre** [comment]
Oops! That seems to be broken on any OS. Fixed it.

Luckily it's very very rare to have that turned on, it's always been off by default since it creates a huge amount of logging (every request made to the webserver, which are a lot!). 
So you can easily disable it 👍 

Thanks!

**Comment by Cpuroast** [comment]
Yeah, I might have been debugging something at some point, which is why it was turned on in my ini and I simply forgot to turn it off after.
