### ISSUE TITLE
Help with sabnzdb

### ISSUE THREAD

**Issue by Rockfordgun** [sabnzbd/sabnzbd#760]
Hi guys i dunno what to do anymore been struggling with sabnzdb for about 5 days after a server crash.
My downloads were perfect but now everything is haywire i normally used a rollback version and that worked for me but this time im not that lucky. 

Im up to date on all the programs now but when i download it downloads then says repair blocks failed i have tried multiple files but by the looks of things when the file is a smaller size it comes through when the file goes bigger than a gig issues start arising like the repair blocks. 

all the settings are the same before the crash i have all the ini files so my settings are the same i have fixed up the autoprocessing file aswell so there wont be an issue like i say smaller files give success.

any ideas?

**Comment by albino1** [comment]
It's almost certainly DMCA removal.  Try downloading something like an Ubuntu release, and then if that fails then there's another problem.

**Comment by thezoggy** [comment]
this is not a support forum.. use sab's IRC or forums for that. which you can find the addresses for via the sab web config root page or via the sab wiki.

**Comment by Safihre** [comment]
Indeed just sounds like DCMA. Have you tried downloading an actual Linux iso, like some version of Ubuntu?
