### ISSUE TITLE
[1.2.0b1] INSTALL.txt still lists openssl as an optional module

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#761]
...but the release notes say the dependency was dropped.

**Comment by Safihre** [comment]
It says OpenSSL in the INSTALL, not pyOpenSSL. 

It's there to make a mention that without a recent version of OpenSSL we can't guarantee certification validation.

**Comment by jcfp** [comment]
Ah, I see, never mind then. :blush: Guess the thing being listed inbetween a bunch of python modules got me confused there.
