### ISSUE TITLE
Running sabnzbd behind caddy proxy

### ISSUE THREAD

**Issue by Braintelligence** [sabnzbd/sabnzbd#762]
Hi everyone.
When running sabnzbd behind a caddy proxy bound to port 8080 I have a problem with the Sorting page.
When trying to save the sorting the jquery seems to call the page per http and is failing due to mixed content.
When accessing the page via IP address and the SSL port 9090 I can save the sorting and the script calls https correctly.

When trying to proxy port 9090 I get `The client sent a plain HTTP request, but this server only speaks HTTPS on this port.`

I tried to rewrite the URL and stuff, but wasn't successful. Is anyone here running sabnzbd behind caddy and could provide a working Caddyfile?

**Comment by Safihre** [comment]
So you only have the problem with Sorting? You can confirm with any of the other pages just to be sure?
The saving should be 100% identical.

**Comment by Braintelligence** [comment]
Actually I had problems with this on other pages as well.

Surprisingly I just realized that the settings DO save. If I refresh the page the settings are saved but the buttons say Failed and I get the mixed content error in the developer console.

**Comment by thezoggy** [comment]
sounds like bad proxy.. where the page data comes from 'one site' while the assets (js/css/whatever) end up coming from another.. ive seen it when people rewrite localhost stuff to come from their dynamic doman name/host..

**Comment by Safihre** [comment]
I think it's a problem in cherrypy. Because we still use that weird redirect after saving, and I recently read this bug on this new couchpotato alternative:
https://github.com/nosmokingbandit/watcher/issues/53#issuecomment-269847662

Sounds very familiar..

**Comment by Braintelligence** [comment]
Well the functionality isn't really broken, but I'd prefer knowing what I should have to do to make it work or whose "fault" this is, just so I can get a better understanding ^^.

**Comment by thezoggy** [comment]
load up fiddler/firebug/whatever and see the requests and see which are throwing what errors.. is it due to 404 due to bad rewrite? due to 401? due to ssl cert not being accepted?

**Comment by Braintelligence** [comment]
Well for example the request URL `https://subdomain.domain.tld/config/sorting/saveSorting` is called but is canceled due to `http://subdomain.domain.tld/config/sorting/` being served under http.

The same for `/switches/saveSwitches` and `/switches`.

The request headers from saveSorting in my case are:
```
Accept:*/*
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Origin:https://subdomain.domain.tld
Referer:https://subdomain.domain.tld/config/switches/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
X-Requested-With:XMLHttpRequest
```

I don't see any error response code per se, maybe I'm looking in the wrong place, though.

**Comment by Safihre** [comment]
@Braintelligence Do you run from sources or on a Linux machine?
Can you change the file `cherrypy/_cperror.py`, starting at line 217 from:
```python
        abs_urls = []
        for url in urls:
            url = tonative(url, encoding or self.encoding)

            # Note that urljoin will "do the right thing" whether url is:
            #  1. a complete URL with host (e.g. "http://www.example.com/test")
            #  2. a URL relative to root (e.g. "/dummy")
            #  3. a URL relative to the current path
            # Note that any query string in cherrypy.request is discarded.
            url = _urljoin(cherrypy.url(), url)
            abs_urls.append(url)
        self.urls = abs_urls
```
to:
```python
        abs_urls = [tonative(url, encoding or self.encoding) for url in urls]
```

**Indentation is important!**

**Comment by Braintelligence** [comment]
@Safihre Thanks for reaching out. Indentation may be important but in this case I just had to do a list comprehension ;P.

Well I commented out the part that should be left out and created the list comprehension but I get the same error.
Maybe I need to restart the service or the whole server for an effect to appear? Will try this out after the recent downloads are done 😸

**Comment by Braintelligence** [comment]
@Safihre 
After restarting I get this:
```
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 678, in respond
    inst.set_response()
  File "/usr/share/sabnzbdplus/cherrypy/_cperror.py", line 261, in set_response
    response.headers['Location'] = self.urls[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Safihre** [comment]
@Braintelligence sorry my fault!
It should be
```python
        abs_urls = [tonative(url, encoding or self.encoding) for url in urls]
        self.urls = abs_urls
```

**Comment by Braintelligence** [comment]
Looks like this works! Now it says something like "saving process..." with two arrows and then turns into save again.

Is this the expected behavior?

**Comment by Safihre** [comment]
@Braintelligence yes it it 👍 

Will submit a PR probably to CherryPy to change this:
https://github.com/cherrypy/cherrypy/issues/1355#issuecomment-270669958

**Comment by Safihre** [comment]
Because I am not sure of the implications in all situations, this might take a bit more time.
