### ISSUE TITLE
1.2.0rc1: unused copies of jquery?

### ISSUE THREAD

**Issue by jcfp** [sabnzbd/sabnzbd#766]
Noticed the following lingering copies of jquery in the -src release:
- interfaces/Config/templates/staticcfg/js/jquery-1.11.2.min.js (superseded by v3.1.1 in the same dir)
- interfaces/wizard/static/javascript/jquery.js (wizard seems to be using jquery from Config only)

The lack of matches when executing the following grep commands in the basedir of the release suggests both files aren't referenced/used anywhere and should be removed.
```
grep -r 'jquery-1.11.2.min.js' *
grep -r 'jquery.js' *
```

**Comment by Safihre** [comment]
You're right! Will fix it for the Final.

**Comment by Safihre** [comment]
@jcfp I updated the `src` release file, there were only 4 downloads so far anyway!
