### ISSUE TITLE
Sorting keeps switching back

### ISSUE THREAD

**Issue by OmgImAlexis** [sabnzbd/sabnzbd#768]
Every time I sort the list it changes back to the "default" order. Sometimes it lasts in the sorted order for upwards of 2 hours, most of the time it changes back within a minute.

Here's a video showing it, I didn't record the leftmost section as it contains the filenames I'm downloading. https://vid.me/4L9z

**Comment by Safihre** [comment]
Do you have (in Config Switches) the option Sort by Age turned on?

**Comment by OmgImAlexis** [comment]
Ah, yes that'd be it. Maybe disable sorting if that's enabled or give a warning?

**Comment by Safihre** [comment]
You're only the second user to mention it in the past 2 years, so guessing it's not such a much used combination :D

**Comment by keithwoelke** [comment]
I've observed this behavior as well. But doesn't your response go against documentation?

https://sabnzbd.org/wiki/configuration/2.3/switches

Sort by age
When you use a server with a low retention time, you can choose to download the oldest parts of a job first. This way you have more chance on completing the download.

From my interpretation, that switch should have nothing to do with queue sort order?

**Comment by Safihre** [comment]
Agreed, the text should be improved that both the files inside the job as well as the jobs themselves are sorted by Age.
Will do that in the morning.

**Comment by keithwoelke** [comment]
Ah, yes. That is confusing. Can you please also clarify what is meant by "average" age?

Is it sorting the queue old->new? or new->old? I would rather files be sorted old->new and queue sorted new->old.

It seems counter-intuitive that this switch should affect sorting order of both. Why can't I prioritize old parts of files without it affecting queue sort order?

**Comment by keithwoelke** [comment]
Actually, I can see some argument if it's trying to sort the queue old-> new in order to get those older parts first. But still not what I'd prefer as a behavior.

**Comment by Safihre** [comment]
[Wiki updated.](https://sabnzbd.org/wiki/configuration/2.3/switches)
Other kinds of auto-sorting are indeed not supported. You could always try to use pre-queue or post-processing scripts to trigger a sort via the API from time to time.

**Comment by kappaknight** [comment]
Honestly, the program should ALWAYS try to get the oldest parts of the file(s) first. It makes good sense.

With that said, the queue order should be sortable by whatever. As an example, I'm currently trying to get 1080p versions of some older stuff, but I want the nightly airings to come in as soon as they are available. 

There's currently no way for me to set two priorities within the same type of file(s) - so not sure how to go about this if the Sorting order isn't sorting the queue based on the age of the nzb.

**Comment by Safihre** [comment]
Then we have to keep track of what as manually sorted and what was automatically sorted by age, that would be a lot of work for a small usecase. You either want always just the oldest first (turn on the switch in Config > Switches) or you can set it manually. In the manual case you could use priorities to get some downloads to go first. Priorities should always be respected, above age.
