### ISSUE TITLE
Avoid problems with illegal filenames on Windows

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#773]
On Windows, SABnzbd cannot properly handle job names and filenames starting with reserved names (e.g. "con.", "aux.").
Currently the URL-grabber and the queue handler will block when trying to create such files, blocking further operation.
At least the blocking should be prevented.
Given that we must use par2cmdline, we cannot solve the problem completely, but at least the blocking of other jobs must be prevented.
Suggestion: as soon a an illegal filename is detected, send  the job as failed to History along with a clear error message.

Initial attempt to fix the URL-grabber #771

**Comment by Safihre** [comment]
Done! :)
