### ISSUE TITLE
pushover -- update/app

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#774]
in sab for the human readable versions of the priority levels we do:
```
<select name="pushover_prio_startup" id="pushover_prio_startup">
  <option value="-3">Off</option>
  <option value="-2" selected="selected">Very Low</option>
  <option value="-1">Low</option>
  <option value="0">Normal</option>
  <option value="1">High</option>
  <option value="2">Emergency</option>
</select>
```

While these are 'fine' they dont match up 100% with the actual app.. but more importantly they miss the fact of why you'd use 'Low' or 'Very Low' which is to be silent... 

https://pushover.net/api#priority

So not sure if we want to link to this page for info or just update our low options to better reflect what they do.. 

--

Then also I noticed that sabnzbd is missing from the public app list ( https://pushover.net/apps ).. we should submit one on behalf of sabnzbd team.. probably should get shy/whatever email we want to sign up for an account.. team@sabnzbd.org ?

My app settings that I used which looks nice:
```
Type: Application
Description: The automated Usenet download tool
URL: https://sabnzbd.org/
Icon: https://raw.githubusercontent.com/sabnzbd/sabnzbd.github.io/master/images/icons/apple-touch-icon-120x120-precomposed.png
```

**Comment by Safihre** [comment]
Shouldn't Pushover users know what these different levels stand for? That's not SABnzbd's job.

I was reading about the App registration, but then we need to register SAB as a web-app that can send the messages while in our case it's each user's instance of SAB that sends the messages, not sabnzbd.org for example.

**Comment by thezoggy** [comment]
pushover users may know the levels but they arent in sync with what sab calls them.. thats the point. 

we just register the app/set the high level info.. then users come in and clone off that. the fact there is nothing to clone right now.. means the user has to put the info in (which is barely anything) main thing is the icon.

**Comment by Safihre** [comment]
Submitted us, let's see if the list us.

**Comment by thezoggy** [comment]
sab is now listed
