### ISSUE TITLE
Suggestion: auto-fill 'List of local network ranges'

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#775]
It's confusing that `External internet access` set to `No access` only works when `List of local network ranges` is set. So since we already have a function to get the local IPv4 address, I suggest we use that to pre-fill the `List of local network ranges`.
So for example if the IP is `192.168.1.123` then we pre-fill `192.168.1.`.

Reason:
@sanderjo pointed me to this port scanner that revealed a lot of people having their SAB exposed online without a password:
https://www.shodan.io/search?query=glitter

**Comment by thezoggy** [comment]
so the problem with 'assuming' is that you may assume wrong. if you are going to pre-fill list of local network ranges.. you should do all of them.. rfc1918 (private/non-routeable ip space)

```
   The Internet Assigned Numbers Authority (IANA) has reserved the
   following three blocks of the IP address space for private internets:

     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)

Note that only a portion of the "172" and the "192" address ranges are designated for private use. The remaining addresses are "public," and routable on the global Internet.
```

**Comment by thezoggy** [comment]
personally i'd like to see us do it how fail2ban does.. each prefix delimited by space 
`ignoreip = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16`

**Comment by Safihre** [comment]
The aim here is more to keep beginning users from making a mistake by opening up to the internet. The advanced user will know what to fill.

We don't need all those ranges, since we know the actual local IP so we can deduct it from that, right?

**Comment by thezoggy** [comment]
what if they are on the vpn? what if they are on a hotspot/wifi?

**Comment by Safihre** [comment]
How about we only do this for new users? 
So when they then switch to `0.0.0.0` they are protected.
And we do it only once of course.
@shypike @sanderjo

**Comment by sanderjo** [comment]
I don't understand what the SABnzbd settings mean, and which are required when. :-(

I would prefer these radio buttons:
* access SABnzbd only from this device
* access SABnzbd from your LAN
* access SABnzbd from your LAN and Internet (probably needs port forwarding)

FWIW: setting to 0.0.0.0 is now not a proble; most users will be protected by their NAT device. The accessible SAB's seen by Shodan are there because the user did something extra with port forwarding. So they should know what they're doing ...

**Comment by Safihre** [comment]
Will add a bigger warning (Warning-label is automatically translate for other langauges):
![image](https://cloud.githubusercontent.com/assets/5703454/21989901/0babcd36-dc0d-11e6-969b-f1ba5f65fb31.png)
