### ISSUE TITLE
Throttling - More control - Feature Request

### ISSUE THREAD

**Issue by DrDrewZA** [sabnzbd/sabnzbd#776]
Hi guys 

I find myself wishing that I had more control over the throttling of downloads.  If I could throttle at different speeds based on category or even better priority, I would be grinning.

The usefulness of this can be considered by users with sickrage or similar setups where sickrage passes a download to sabnzbd which should then be able to download at a faster rate than say manually added nzbs.  This would mean that fresh episodes being grabbed come down very quickly, while less important/time sensitive downloads come down at a lower, preselected rate, without any user intervention/babysitting being required.  Sickrage can already set the passed NZB's to high priority or forced, so perhaps the feature needs to be that we can select an option that makes high priority or forced downloads ignore the throttling limit, or even better, use a separate limit.

Thoughts?

Drew

**Comment by sanderjo** [comment]
I think you can take there of that via the SAB API and a few lines of code. Some hints:

Show category and priority of first item in the queue (thus being downloaded):
```
$ curl -s 'http://127.0.0.1:8080/sabnzbd/api?output=json&mode=queue&limit=1' | python -mjson.tool | grep -e '"cat"' -e '"priority"'
                "cat": "*",
                "priority": "High",

```
Based on that, you can set the speedlimit to 1000MB/s aka unlimited:
```
$ curl -s 'http://127.0.0.1:8080/sabnzbd/api?mode=config&name=speedlimit&value=1000M' 
ok
```
You can put that into a script and let the OS run that script each few minutes. 
FYI: the above codes is without API-key for easier reading.
HTH

**Comment by Hellowlol** [comment]
There any way to solve this. I would prop ended up having a preque script and a notification script handling this for me.

**Comment by Safihre** [comment]
Right now we cannot do this, throttling specific jobs is just too complicated. 
All we can offer indeed is priorities to get some jobs faster than others.
