### ISSUE TITLE
Suggestion: remove 'Secondary Web Interface'

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#778]
With Glitter, we have desktop and mobile theme in one.
Besides for us dev's for testing, what's the point?

**Comment by Hellowlol** [comment]
I use it for time to time :P

**Comment by Safihre** [comment]
@Hellowlol But for what? :stuck_out_tongue_winking_eye:

**Comment by sanderjo** [comment]
> Besides for us dev's for testing, what's the point?

And dev's know how to switch interfaces

> Suggestion: remove 'Secondary Web Interface'

I agree!

**Comment by Hellowlol** [comment]
I just like to change things up, probably why htpc manger has loads of themes :P

**Comment by Safihre** [comment]
For 1.2.1 we will move it to Specials with a deprecation message in the release note, and then remove it for 1.3.0.

**Comment by shypike** [comment]
1.2.1 should only have bugfixes.
1.3.0 move to Specials
1.4.0 remove (if there was no opposition)

**Comment by danioj** [comment]
I'm so disappointed that this was implemented. I loved to use Gold when on the desktop and use the mobile interface when ... yes ... using the mobile or iPad. Removing a feature which didn't harm anyone or anything. I don't get it.

**Comment by gevrey** [comment]
Yes, I was exactly in the same use case, one skin on desktop, another on mobile.

Please bring it back.

**Comment by Safihre** [comment]
@gevrey @danioj What features is Glitter missing that Plush has?

The second skin required lots of extra code that made already complicated functions more messy.

**Comment by gevrey** [comment]
I am using "smpl black" on desktop. I like it.

>> The second skin required lots of extra code that made already complicated functions more messy.

OK, I understand this rationale.
