### ISSUE TITLE
Change in behaviour?

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#781]
Using the develop branch, i've noticed that my prequeue script which marks some things as 2 (fail and postproc) doesn't seem to be doing the latter part of that. Its just marking it as failed and there is no call to the nzbToMedia script to update the media manager.

Version:	develop [unknown]
Python Version:	2.7.12 (default, Jun 28 2016, 06:57:42) [GCC] [UTF-8]
OpenSSL:	OpenSSL 1.0.2j-fips 26 Sep 2016   [TLS v1.2, TLS v1.1, TLS v1, SSL v3]

####expected 
  	Wanderlust 2012 iNTERNAL DVDRip x264-REGRET cp(tt1655460)	   
CouchPotato: Successfully snatched next highest release! (More)
 
» Download might fail, only 0.0% of required 100.0% available - https://sabnzbd.org/not-complete 
2017-01-18 09:53:59  
######

#####not as expected
  	Wanderlust 2012 BluRay 576p H264-20-40 cp(tt1655460)	 
 Retry
» Pre-queue script marked job as failed 
######

**Comment by Safihre** [comment]
Fixed it.
But of course does require `Post-Process Only Verified Jobs` to be turned on, but you already have that probably!

**Comment by mgaulton** [comment]
Actually, i have Post-Process Only verified off as that's what's recommended by nzbToMedia.

**Comment by Safihre** [comment]
Hmm, so before 1.2.0 it would always run the pp script? Even though it was accept&*fail*?  
That sounds counterintuitive to me since there is nothing to post process.

**Comment by mgaulton** [comment]
Correct, it did run. It does make sense because it still needs to notify the SB / CP instance that it failed so it can snatch the next one. I have some pre-checks that are relevant so sometimes i still need to fail and notify. i.e. TV episodes over a certain size that sometimes do get snatched by SB

**Comment by Safihre** [comment]
Yes but with the option being called accept&**fail**, it would confuse scripts that are supposed to run on completed downloads. 
They expect to run of successful downloads because `Post-Process Only Verified Jobs` would only let those pass.
What do you think @shypike ?

**Comment by thezoggy** [comment]
is there any other way to complete the previous (1.1.x and older) workflow? if not.. prob should revert changes and build a better more robust way.

**Comment by shypike** [comment]
The intention in earlier versions was to allow the PP script to run in order to communicate with down-stream software.
Exactly the use-case that @mgaulton describes.
The PP script should be such that it can handle the situation; it does get a status parameter.
The old behaviour should be restored.

**Comment by Safihre** [comment]
I see now that I made a typo in my first comment I made a typing mistake causing confusion
What I meant to say is `Post-Process Only Verified Jobs` should be turned **off**, which is also what @mgaulton says:
> Actually, i have Post-Process Only verified off as that's what's recommended by nzbToMedia.

So it all works the way it was :)

**Comment by mgaulton** [comment]
Awesome, thanks guys. sorry for the confusion
