### ISSUE TITLE
SSL Errors after upgrading to 1.2.0

### ISSUE THREAD

**Issue by GTunney** [sabnzbd/sabnzbd#783]
Hi I've been getting the below error pop up on Sabnzbd home page every so often since upgrading to Sab 1.2.0, I'm running sab on my QNAP NAS and using QNAP_Stephanes package from qnapclub.eu with embedded libs. I have approached stephane but he has asked me to log on github.

Any suggestions or reasons why I'm getting the erorrs? It doesn't seem to be effecting sabs function.

Python Version:	2.7.13 (default, Jan 7 2017, 02:11:25) [GCC 4.8.4] [UTF-8]
OpenSSL:	OpenSSL 1.0.2j 26 Sep 2016   [TLS v1.2, TLS v1.1, TLS v1, SSL v3]

```
19/01/2017 13:28 [19/Jan/2017:13:28:12] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:661)
```

**Comment by Safihre** [comment]
Do you have your SAB exposed to the internet?
Because what I understand from [the internet](https://alpacapowered.wordpress.com/2014/10/20/ssl-poodle-attack-what-is-this-scsv-thingy/) this error occurs when the client is trying to force a lower encryption standard then the server allows. I expect such things to happen with port-scans.

**Comment by GTunney** [comment]
Hi Safihre,

Yes it is exposed to the internet as I wanted to be able to access anywhere without VPN and use my SSL cert for my domain. Is this a new feature of 1.2.0?

**Comment by Safihre** [comment]
We bumped our SSL handling a bit in 1.2.0, for connecting to news servers and for the interface.
Protocols such as SSLv2 and SSLv3 are considered unsafe by the security community, so these are disabled for the webserver from 1.2.0 on.

**Comment by GTunney** [comment]
Ah ok that will explain it then. My connection is using TLS 1.2 but i'm guessing what your saying is someone is trying to force connection to use SSLv2 and SSLv3?

Guessing only way to stop the errors is to disable access to the internet or put up with them?

**Comment by Safihre** [comment]
We (or better, CherryPy, the web server) should handle this. Showing the appropriate message to whatever client is doing it.

**Comment by GTunney** [comment]
No probs Safihre, If you need me to test anything then just give me a shout on sab forums. I've done some testing to you before (same username as here) so always happy to help where I can to resolve issues.

**Comment by Safihre** [comment]
@GTunney Would you maybe be able to test the fix?
You would need to replace the file
`/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/ssl_builtin.py`
with this version:
https://raw.githubusercontent.com/sabnzbd/sabnzbd/15456f2c2d99228b6cd230a09a5fefcef10b06b7/cherrypy/wsgiserver/ssl_builtin.py

Keep a backup of the original, otherwise it might break the auto-update feature of the QNAP package :)

**Comment by nzbjamz** [comment]
@Safihre How are updates handled? I see that it looks at a txt file on get to get the version and download page. It doesn't look like the package has a `.git` folder so probably not just a repo pull.

**Comment by Safihre** [comment]
The clinton-hall package that we officially list for QNAP does auto-updating by pulling from the `master` branch of the repo. SAB itself doesn't do auto-updates.

**Comment by nzbjamz** [comment]
Thanks! I've requested auto-update for the other SABnzbd qpkg, by QoolBox, as well.

**Comment by GTunney** [comment]
I no longer use Clintons package as I ran into several issues with python and yenc so I now use QNAP_Stephanes QSabnzbd package with embedded python and modules which updates differently to Clintons. I may but wrong but I'm sure QNAP_Stephane is Qoolbox on different forums.

I shall test the file once I get home from work this evening.

**Comment by nzbjamz** [comment]
@GTunney Ah yes, you're right. Qoolbox is QNAP_Stephane, Stéphane.

**Comment by Safihre** [comment]
Is there an official download page we maybe can link to from our wiki?

**Comment by GTunney** [comment]
http://www.qnapclub.eu/index.php?act=detail&qpkg_id=233

Qnapclub.eu is where they are downloaded from at the moment for Stephane's package. How ever this will soon be delivered via adding a 3rd party repo to QNAP app Center once QNAP resolves the detection of x86 or x64 O/S.

**Comment by Safihre** [comment]
@GTunney Did you have time to replace that file to see if it works? :)

**Comment by GTunney** [comment]
@Safihre apologies no not yet, I was too busy trying to sort out the par2 issue I was having. I'll make the changes today although I haven't had the error since submitting the issue, typical.
