### ISSUE TITLE
Feature Request: More post-processing parameters

### ISSUE THREAD

**Issue by nosmokingbandit** [sabnzbd/sabnzbd#785]
I'm the dev of https://github.com/nosmokingbandit/watcher, and I find that post-processing downloads would be a whole lot easier with a few additions to the post-processing parameters.

Sending the nzo_id would be great. I store the nzo_id that is returned when sending an nzb to Sab, so tracking the download afterwards becomes trivial when using that download identifier.

Including the nzb link in would be great as well. This saves steps when marking a certain nzb as failed.

I have everything working well enough now, but I have to make a request back to Sab to get that extra info.

This is obviously not a huge priority, but I'd appreciate anyone looking into implementing this.

**Comment by Safihre** [comment]
You're right! We used to have a Feature request open for it, don't know where it went so we kind of forgot about it.. 
But now it's on the list again :)

**Comment by nosmokingbandit** [comment]
Super cool, thanks!

**Comment by Safihre** [comment]
Will be in 2.0.0. 
Let me know if there's other fields missing.

**Comment by Safihre** [comment]
Example:
```
SAB_SCRIPT test3.py
SAB_ENCRYPTED 0
SAB_BYTES 1044
SAB_DUPLICATE False
SAB_UNWANTED_EXT 0
SAB_FAIL_MSG 
SAB_NZO_ID SABnzbd_nzo_j9iwUN
SAB_CAT *
SAB_COMPLETE_DIR /home/osboxes/Downloads/complete/unicode-inside.rar
SAB_GROUP alt.binaries.boneless
SAB_OVERSIZED False
SAB_PASSWORD None
SAB_STATUS Running
SAB_AVG_BPS 111
SAB_FILENAME unicode-inside.rar.nzb
SAB_AGE 2d
SAB_DOWNLOAD_TIME 0
SAB_BYTES_DOWNLOADED 397
SAB_URL unicode-inside.rar.nzb
SAB_PP_STATUS 0
SAB_REPAIR True
SAB_UNPACK True
SAB_FAILURE_URL 
SAB_PP 3
SAB_PRIORITY 0
SAB_VERSION develop
SAB_FINAL_NAME unicode-inside.rar
SAB_BYTES_TRIED 1044
```

**Comment by Safihre** [comment]
Modified it so Python types like True/False/None are better transmitted:
```
SAB_SCRIPT test3.py
SAB_ENCRYPTED 0
SAB_PP_STATUS 0
SAB_BYTES_TRIED 1044
SAB_DUPLICATE 0
SAB_BYTES 1044
SAB_UNWANTED_EXT 0
SAB_NZO_ID SABnzbd_nzo_lfclgu
SAB_FINAL_NAME unicode-inside.rar
SAB_CAT *
SAB_COMPLETE_DIR C:\Users\jiriv\Videos\Complete\unicode-inside.rar.3
SAB_OVERSIZED 0
SAB_PASSWORD 
SAB_STATUS Running
SAB_AGE 2d
SAB_AVG_BPS 10
SAB_FILENAME unicode-inside.rar.nzb
SAB_DOWNLOAD_TIME 0
SAB_BYTES_DOWNLOADED 397
SAB_PP 3
SAB_URL unicode-inside.rar.nzb
SAB_REPAIR 1
SAB_UNPACK 1
SAB_FAILURE_URL 
SAB_PRIORITY 0
SAB_FAIL_MSG 
SAB_GROUP alt.binaries.boneless
SAB_VERSION develop
```

**Comment by nosmokingbandit** [comment]
This is perfect. Processing completed downloads will be so much easier with this extra info.

Version 2.0.0 should be pretty awesome.

**Comment by OldskoolOrion** [comment]
Oh nice !! I feel it's gonna be a scripty day :-)
