### ISSUE TITLE
Suggestion: remove option to disable QuickCheck

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#788]
_For 1.3.0._ 
Why would one disable it?

**Comment by thezoggy** [comment]
history of issues with it in the past (or at least mentioned) -- looks like edge cases: https://github.com/sabnzbd/sabnzbd/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20quickcheck%20

forums however mention issues that look like disabling quickcheck fixed problems..

* https://forums.sabnzbd.org/viewtopic.php?f=2&t=19398&p=101564&hilit=quickcheck#p101564

* https://forums.sabnzbd.org/viewtopic.php?f=2&t=18907&p=100245&hilit=quickcheck#p100245

**Comment by shypike** [comment]
We could move it to Specials, so it would still be available for diagnostic purposes.
If so, the explanatory text for "Download all par2 files" needs changing too (remove refs to QuickCheck).

**Comment by Safihre** [comment]
👍 We can do that easily, just split the text after the first `.`.
