### ISSUE TITLE
cherrypy -- upgrade

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#790]
can see they are up to `10.1.0` now..
https://github.com/cherrypy/cherrypy/blob/master/CHANGES.rst

not sure how i feel about them using portend now..

**Comment by Safihre** [comment]
Worse, they moved the whole `cheroot` (WSGIServer) out of the package. 
This was exactly the thing we had most problems with.

But not to worry, I'm following the project closly and will update our CherryPy when needed 👍

**Comment by thezoggy** [comment]
might want to add a safety check to only support cherrypy under version x and above version y.. since we cant force to only support included version due to ppa
