### ISSUE TITLE
Plush gold interface - processing succeeded not displaying correctly

### ISSUE THREAD

**Issue by Vards0** [sabnzbd/sabnzbd#793]
Hi

I recently upgraded to version 1.2.0 and have noticed that the "Processing Succeded" notification does not look right.

It displays the html code along with everything else.

I've attached a screen shot below.

Any ideas?

Thanks

![plush-gold](https://cloud.githubusercontent.com/assets/4409210/22285275/9135e698-e2f3-11e6-9b90-eb2a35835a17.png)

**Comment by Safihre** [comment]
I think this is by design. What you're seeing is script output and we don't want scripts being able to insert html. 
What is shown with the Glitter skin?

**Comment by Vards0** [comment]
Hi Safihre

It's doing the same thing:-

![image](https://cloud.githubusercontent.com/assets/4409210/22300419/10999d76-e330-11e6-8a97-a3dcdb06c372.png)

**Comment by Safihre** [comment]
Yes, I just checked and we made this change going from 1.0.x to 1.1.x because it's just too much of a risk to allow the HTML (and thus javascript) to just be shown to the user.

Maybe you can edit the script and just remove the HTML from the result?

**Comment by thezoggy** [comment]
we could also just strip the html ourselves?

**Comment by Safihre** [comment]
Alright, we can do that for the line we display.

**Comment by Safihre** [comment]
@thezoggy the ElementTree solution doesn't work for simple one-liners.
When my script outputs '<br>Hii<span>no</span>' it gives:
```
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Documents\GitHub\sabnzbd\sabnzbd\postproc.py", line 476, in process_job
    script_line = get_last_line(script_log)
  File "C:\Users\<USERNAME>\Documents\GitHub\sabnzbd\sabnzbd\postproc.py", line 900, in get_last_line
    lines = ''.join(xml.etree.ElementTree.fromstring(txt).itertext())
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1312, in XML
    return parser.close()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1665, in close
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: no element found: line 2, column 0
``

**Comment by Hellowlol** [comment]
What about something like https://repl.it/FVbM/0

**Comment by thezoggy** [comment]
@Hellowlol, your solution ends up being too greedy.. only spits out `Processing succeded`. Safihre's method ends up with `Processing succeded   Processing succeded   Processing succeded   Processing succeded`

**Comment by Hellowlol** [comment]
@thezoggy That was the point, i didnt understand why we should keep repeating the same line over and over. I just skimmed the issue, but maybe its intended or needed.

**Comment by thezoggy** [comment]
well if you are over zealous with stripping.. you could be stripping out information thats useful. scripts shouldnt be repeating the same info..  so logically we would want to keep all valid info (text)
