### ISSUE TITLE
Show par2 version (on non-Windows / non-MacOS platforms)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#794]
Apparantly the par2 version is relevant (see https://forums.sabnzbd.org/viewtopic.php?f=2&t=22362#p110460), at least on non-Windows / non-MacOS platforms.

So why not print that version in the sabnzbd.log? 

I made a prototype, which gives this output on my Ubuntu:

```
2017-01-26 09:04:22,797::INFO::[SABnzbd:450] par2 binary... found (/usr/local/bin/par2)
2017-01-26 09:04:22,810::INFO::[SABnzbd:454] par2 binary version: par2cmdline-mt version 0.6.14-mt1
2017-01-26 09:04:22,811::INFO::[SABnzbd:461] par2cmdline binary... found (/usr/local/bin/par2)
```

So that works.

Questions @Safihre 

* what is the difference between par2 and par2cmdline?
* should SAB print the version message after the par2cmdline instead of after the par2?
* should SAB print `par2cmdline-mt version 0.6.14-mt1` or just `0.6.14-mt1`?
* should SAB only print the par2 version in case of non-Windows / non-MacOS, or always?

**Comment by Safihre** [comment]
> what is the difference between par2 and par2cmdline?

Windows vs non-Windows basically.

> should SAB print the version message after the par2cmdline instead of after the par2?
> should SAB print par2cmdline-mt version 0.6.14-mt1 or just 0.6.14-mt1?
> should SAB only print the par2 version in case of non-Windows / non-MacOS, or always?

We could add it, but since we already auto-detect the `-N` and from 1.2.1 also `-B`, we covered all our bases.
In 1.2.0 we wouldn't add `-N` if the user specified it's own par2-parameters, but for 1.2.1 I decided to always do it when it's needed. I think that's what's going wrong in that forum post.

**Comment by thezoggy** [comment]
just to clarify,

```
C:\Program Files (x86)\sabnzbd_0.8.x\win\par2>par2cmdline.exe -V
par2cmdline version 0.6.13
```

vs

```C:\Program Files (x86)\sabnzbd_0.8.x\win\par2>par2.exe -V
Not enough command line arguments.
par2cmdline version 0.4, Copyright (C) 2003 Peter Brian Clements.
Modifications for concurrent processing, Unicode support, and hierarchial
directory support are Copyright (c) 2007-2015 Vincent Tan.
Concurrent processing utilises Intel Thread Building Blocks 4.3 Update 1,
Copyright (c) 2007-2014 Intel Corp.
Executing using the x86 (32-bit) instruction set.

par2cmdline comes with ABSOLUTELY NO WARRANTY.
```

both are par2cmdline.. one is the fork with tbb speedup

**Comment by sanderjo** [comment]
> We could add it, but <snip>

OK, so let's not do it. I'll close this thread.
