### ISSUE TITLE
Release 1.2.0 won't work on Debian 8

### ISSUE THREAD

**Issue by vmdude** [sabnzbd/sabnzbd#795]
Hi,

I have an issue with release 1.2.0, it won't start on debian 8:

```
root@pvr:~# python /root/.sabnzbd/SABnzbd.py -d -f /root/.sabnzbd/sabnzbd.ini
/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_d62b3d91x972e1c0b.c:187:43: fatal error: CoreFoundation/CoreFoundation.h: No such file or directory
 #include <CoreFoundation/CoreFoundation.h>
                                           ^
compilation terminated.
```

Release 1.1.0 works just fine.

Some information about platform:
```
root@pvr:~# uname -a
Linux pvr 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
root@pvr:~# cat /etc/debian_version
8.7
root@pvr:~# python -V
Python 2.7.9
```

**Comment by thezoggy** [comment]
looks like cryptography is saying your missing cffi... can you try installing that?
`pip install cffi`

**Comment by vmdude** [comment]
it seems it's already installed:

```
root@pvr:~# pip install cffi
Requirement already satisfied: cffi in /usr/lib/python2.7/dist-packages
Requirement already satisfied: pycparser in /usr/lib/python2.7/dist-packages (from cffi)
```

**Comment by Safihre** [comment]
It seems you might be missing `dev` headers or something like that?
Since you are on debian, why not use the PPA?

**Comment by thezoggy** [comment]
see if its just outdated...
`pip list --outdated`

let pip just upgrade everything you have installed to latest,
`pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

**Comment by thezoggy** [comment]
also.. running commands as root is a good way to cause permission issues for things not running as root later on...

**Comment by vmdude** [comment]
Updating pip modules works, thanks a lot !

**Comment by Safihre** [comment]
(Y)
