### ISSUE TITLE
ssl - wiki

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#796]
https://sabnzbd.org/wiki/configuration/1.2/configure

needs to be updated to reflect the drop of pyopenssl..

because were not checking to see if a certain version of crypto/cffi is installed.. 
may want to add in the wiki about how to update crypto/cffi/etc thats already installed (since that debian issue sparked this issue):
`pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

**Comment by Safihre** [comment]
If he'd just done a `pip install cryptography --update` the installation would have done that upgrade.

Always found it a bit odd you have to force this `--update` part.

**Comment by Safihre** [comment]
Removed the whole SSL section, since every python install will have SSL support, unlike pyOpenSSL before.
Will remove all the SSL-checks for the next big release, we're not doing all that extra code in case some very exotic person compiled python without SSL.
