### ISSUE TITLE
SSL certificate validation error?

### ISSUE THREAD

**Issue by deanishe** [sabnzbd/sabnzbd#797]
SAB tells me the SSL cert for api.oznzb.com is invalid. [SSL Labs says it's fine](https://www.ssllabs.com/ssltest/analyze.html?d=api.oznzb.com).

**Comment by Safihre** [comment]
It's not fine, see all details here: https://forums.sabnzbd.org/viewtopic.php?f=3&t=22296#p110454

**Comment by Safihre** [comment]
Seems the issue with oznb should be resolved since the SSL checkers now say it's fine again. 

Might take some time for some caches to clear up, but I think  the error should go away soon.

**Comment by deanishe** [comment]
Yeah, it's fine. Seems they must have fixed the issue at their end between my getting the error in SAB and checking with SSL Labs.

Sorry for not checking with SAB again before posting.

**Comment by oznzb-dev** [comment]
yes it was an issues at our end .... sorry for the issue
