### ISSUE TITLE
sab 1.2.0 -- unable to validate cert / RemoteCertificateNameMismatch / RemoteCertificateChainErrors

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#798]
running sab 1.2.0 binary on windows, using https with sab generating its own self signed cert

per browser its unable to verify because the issuer is unknown.
Owner: `This website does not supply ownership information.`

apps like radarr/sonarr show:
`17-1-28 20:55:23.3|Debug|X509CertificateValidationPolicy|Certificate validation for https://192.168.0.2:8000/api?mode=queue&start=0&limit=1&apikey=(removed)&output=json failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors`

but everything 'works'.. just a bit of logging noise because of it all.

**Comment by thezoggy** [comment]
looking through the code, i see mention of `key.pem` and `cert.cert` but cant find where they actually end up..  in the admin folder I see `server.key` and `server.cert`

**Comment by thezoggy** [comment]
side note, X.509 certs per mmc should have the file name ext of: `*.cer;*.crt`

**Comment by thezoggy** [comment]
was about to resolve the `RemoteCertificateChainErrors` part.. cant get rid of the other one though. even tried importing it into trusted certs and other places..  digging more into this.. looks like its because the CN is not my domain we use `SABnzbd` which will never be correct..  thus i need to just hack in sab to generate the key using my ip instead

**Comment by thezoggy** [comment]
ok nuked the certs from the browser/store/etc.

ok ran sab from source on the box and changed out the CN from `SABnzbd` to `192.168.0.2` and had it generate a new key/cert. shut down that instance and copied over the relevant .key/cert to sab. restarted sab+sonarr.. now I see:

`17-1-28 21:52:37.7|Debug|X509CertificateValidationPolicy|Certificate validation for https://192.168.0.2:8000/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json failed. RemoteCertificateChainErrors`

So looks like that fixed the CN mismatch.. now about the ChainError..
> You are not providing an issuer for your certificate and in this way it can't be trusted - this is the cause of the RemoteCertificateChainErrors Exception.

So I've imported my sab cert into trusted chain.. now no more message and all good.

`17-1-28 21:57:07.9|Debug|SabnzbdProxy|Url: https://192.168.0.2:8000/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json`

**Comment by thezoggy** [comment]
To install your certificate in windows XP / Windows 7 do the following.

Launch the Certificates MMC snap-in:
1. Launch `mmc` from start/run
2. Go to `File` > `Add/Remove Snap-in...`
3. Click on `Certificates`
4. Click `Add >`
5. Click `Computer Account`, then `Next`

Now in the Console Root under *Certificates* we need to load the self signed sab cert:
1. Expand `Certificates (Local Computer)`
2. Right Click on `Trusted Root Certificate Authorities`
3. Click on `All Tasks` > `Import...`
4. Click `Next`
5. Click `Browse` and load the `server.cert` in your SABnzbd admin folder.
> Due to the file extension you will have to change the filter to all files *.* to see it.
6. Click `Next` then `Finish`

Now the CN you used will be a valid issuer, thus no longer causing the `RemoteCertificateChainErrors` error.

**Comment by Safihre** [comment]
What can we do? Guess the CN when generating the self-signed certs? Will probably be wrong.

**Comment by thezoggy** [comment]
Set the CN to what the user defined as host...

**Comment by Safihre** [comment]
But that would be `0.0.0.0` if they access it remotely/network.. That doesn't solve anything. 

It's been like this since SAB introduced HTTPS..

**Comment by thezoggy** [comment]
maybe when the user clicks to generate cert we prompt a modal before doing it.. in that modal we prepopulate all our defaults and let the user replace the CN there if they want.. that way they can specify `localhost` or `reverse_proxy_hostname` or `custom.dyndomain.name` or whatever..

**Comment by thezoggy** [comment]
honestly though remotely i dont care cause i dont have a domain/ips change/etc, main thing i needed to fix is LAN based apps...

**Comment by thezoggy** [comment]
Yes, SAB apparently hasnt been generating self signed certs correctly this whole time.. but probably less of an issue in the past because browsers weren't so strict or verbose about it.. let alone 3rd party apps checking them.

Also we used to do a different key before 1.1.x.. which may have masked our mistake.

In sab 1.1.x and older we did a .pkv cert ?
https://github.com/sabnzbd/sabnzbd/blob/1.1.x/sabnzbd/misc.py#L1130

Which use the `.cert` and `.key` file extensions... 
We now do a x.509 cert.. which should have the file name ext of: `.cer` and `.crt`

Additionally we shouldnt have our cert expire after 365 days (1yr)... Other apps do 3650 days... that way its a one time procedure.... 

Prepare for more of these type of support inquires:
http://www.theverge.com/2017/1/26/14396130/http-https-insecure-connections-chrome-firefox

**Comment by Safihre** [comment]
I am not well informed about all these things so easier if you make the changes? Make a PR? 

Not so sure about the modal for now, we're really trying to go for the less=more approach in the Config, so I feel generating the cert should be done with minimal questions (or better, none at all). 
The idea being that it's only a nice service, but you should make your own certs if you want customization.

**Comment by Safihre** [comment]
You could use Javascript to detect the URL domain when hitting the refresh button and send that to the script? 
Would only work of course when generated via the refresh button. 
But indeed, defaulting to `localhost` is better than `Sabnzbd` for CN. 
Didn't occur to me when making this what the real purpose of the fields was..

**Comment by Safihre** [comment]
@thezoggy Do you have time for a PR?
I suggest to add a SAN (subjectAltName) so it's valid for both `localhost` and `127.0.0.1`, which SAB defaults to. Not even sure if you can combine those two, but maybe you can test that?

**Comment by thezoggy** [comment]
ill see if i can knock this out this weekend :)

**Comment by thezoggy** [comment]
at a quick glance, I think we should just do CN of localhost (covers most people).
then expose a field for users to populate the SAN.. thus they could put in `mycool.customdns.name;192.168.0.1` and we use for the SAN list..

**Comment by Safihre** [comment]
Sounds good, how about a pop-up (`prompt()`) when the refresh-icon is pressed? 
And then pre-fill the hostname that the user is currently visiting the page from.

**Comment by thezoggy** [comment]
to make sure I am making this pull off the correct upstream.. this should be off `develop` correct?

not sure why we even have a `1.1.x` branch.. and no i dont think we need a `1.2.x`. 
if we need to do a hotfix we can just checkout off the tag and go off that..

**Comment by Safihre** [comment]
`develop` indeed.

**Comment by thezoggy** [comment]
putting this here for reference:
https://blog.sucuri.net/2016/03/beware-unverified-tls-certificates-php-python.html

and: https://github.com/Sucuri/tls-verify

**Comment by Safihre** [comment]
@thezoggy do you think you'll have something soonish? Then we can put it in 1.2.1.

**Comment by thezoggy** [comment]
so I thought we would be good if I just used the subjectaltname of 'localhost' but that doesnt make the other apps happy.. then I found that using CN of localhost is actually illadvised due to the security risks..   I had code to just accept a list of things the user wants to pass to add as subjectaltnames.. but due to the way its an extension it sucks to progmatically add.. then when we generate a cert on startup if one doesnt exist but https is enabled..  so I went back to just trying to remove CN and only do the SAN method.. but same problem. so im back to where i started.. but i do have some code changes to submit.. but now im not sure we really should be doing localhost for the CN.. maybe just SAN only.. need to test more

**Comment by Safihre** [comment]
@thezoggy, actually by default SABnzbd settings the host is set to `127.0.0.1`, so not `localhost`. The browser-launch on startup will also redirect you there, not `localhost`.
Does that help?

**Comment by thezoggy** [comment]
@Safihre not really.. i mean `localhost` makes the browser happy (as localhost / reserved ip space all get grouped together) but other apps arent happy with it.. as it only stopped complaining until I used `192.168.0.x` as the SAN or CN...  so just made it so it finds the local ip and just uses that.. now the debate is to know if we should just include localhost or not....  

regardless, the user will still get `RemoteCertificateChainErrors` due to CA not being valid (all self sign certs are this way) until they add the cert to the trusted ca

**Comment by thezoggy** [comment]
submitted pull request..  i dont have any way to test the v6 portion..  pretty much the cert should generate with `localhost` and whatever local ip sab can find (same ips we detect on startup)..  so anyways this satisfied my scenario and required no additional user input...  now if people are sensitive about ssl certs and how they are generated (they dont want localhost for example)... they can just generate their own cert. and from what I can read.. the only real pitfall with using localhost is on a shared machine and they wrongly added the cert to the trusted root globally and not just for the account...  anyways i feel pretty confident that this is at least a better way to go than what we were doing before.

**Comment by shypike** [comment]
Local IP addresses aren't stable if they're assigned by DHCP.
Will a changed IP address bite the user later by raising new browser warnings?

**Comment by thezoggy** [comment]
Well if they have DHCP locally... The probably aren't using the IP to do much but rather localhost. Now for example I use DHCP but have static IP assigned out by mac.. thus it doesn't change. The browser warning is going to appear if the exception added is no longer valid... The cert won't magically fix those with chatioc IP changes... Even if you could do a wildcard local cert... Because self signed certificate are purposely designed not to be. The fix for those would to use a reverse proxy and do the cert off that domain or use external domain and do a cert off that. My goal was just to make local apps happy with Sab using HTTPS that validate the x509 values
