### ISSUE TITLE
Can not use ssl provider - EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#801]
` [Errno 111] Failed to connect: EOF occurred in violation of protocol (_ssl.c:590) -1@*.*.*.*:563`

**Comment by Safihre** [comment]
Could you share the URL so we can test?

**Comment by scriptzteam** [comment]
usenet.cat

**Comment by Safihre** [comment]
The status page says ` Secure NNTP (NNTPS) service DOWN`

That could be it? https://usenet.cat/status.html

**Comment by scriptzteam** [comment]
If you can check https://usenet.cat/live.php is 1 min down and 1 min up, its hopping like this but before i dont had any problems, gonna try this -> http://saburl:PORT/config/general/#enable_https_verification and there i disable it :)

**Comment by Safihre** [comment]
That won't work. As the options says, it is intended for HTTPS connections (to indexers/RSS), not newsservers!

It's not a certificate problem, the service is just down..

**Comment by scriptzteam** [comment]
Its not down :D see live status - https://usenet.cat/status.php the html is cached one ;)

**Comment by Safihre** [comment]
The live page only shows NNTP things, no NNTPS at all.

**Comment by scriptzteam** [comment]
https://usenet.cat/status.php

Secure NNTP (**NNTPS**) service UP

Checked at 29-Jan-2017 17:40:47

**Comment by Safihre** [comment]
Its a problem on their side, I just tried NZBGet and it also can't connect 
![image](https://cloud.githubusercontent.com/assets/5703454/22405955/3f6ebee8-e64a-11e6-9d02-ef53febeab38.png)

**Comment by scriptzteam** [comment]
Yes thats that, why there is no option to accept self-signed generated cert. ?

Or like ignore them at all ?

**Comment by Safihre** [comment]
There is, click Advanced and you can set Certificate Validation to Off.
But this also means SSL is useless since anyone can just fake the connection. Could just not use SSL at all.

If you want to trust their specific self-signed certificate, you need to add it to your PC's certificate store as a trusted certificate, which SAB will then pick up.

**Comment by scriptzteam** [comment]
Great now it works as expected thx! :)
