### ISSUE TITLE
sab -- log cryptography module version

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#803]
we should log what version of modules we load (helps troubleshooting)...
(we mention in install.txt about cryptography >= 1.2 but we dont enforce because its an optional module).

sadly _yenc never had a version in its module.. so that one we can skip for now (until sabyenc)...
but `cryptography.__version__` we should log.
```
2017-01-30 12:15:31,463::INFO::[SABnzbd:432] _yenc module... found!
2017-01-30 12:15:31,467::INFO::[SABnzbd:437] Cryptography module... found!
```

**Comment by thezoggy** [comment]
https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L81
looking, cryptography 1.2 was released just over a year ago: Jan 8, 2016

**Comment by thezoggy** [comment]
note, 1.7 -- Support for OpenSSL 1.0.0 has been removed. 
https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#17---2016-12-12

this contradicts our 
https://github.com/sabnzbd/sabnzbd/blob/develop/INSTALL.txt#L79

**Comment by Safihre** [comment]
The 1.2 is arbitrary really. Didn't test older versions, but the functionality we use is probably present in much older versions. Just didn't test them.

**Comment by thezoggy** [comment]
so i wonder if macos users that just install latest cryptography will be broken?

**Comment by Safihre** [comment]
No it works, cryptography added some compatibility things to make it work for macOS. Only on other platforms they require minimal OpenSSL 1.0.0+. 
There's a PyCon talk somewhere where the Cryptography guy explains all this.

**Comment by Safihre** [comment]
For example:
```python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography
>>> cryptography.__version__
'1.5'
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
```

**Comment by Safihre** [comment]
Alright, I tested all the versions and the minimal version that has all the functions we need is `1.0`.
Will update the INSTALL and let it print the version number in the log.
