### ISSUE TITLE
SABnzbd problem with IE11

### ISSUE THREAD

**Issue by schabau** [sabnzbd/sabnzbd#804]
Hello,
In the forum I try to get an access for months. Unsuccessful, I get no activation mail, so I report me here.

I use SABnzbd always on a small Linux server as a daemon.
Today I wanted to change from 0.7.9 to 1.2.0. There are unfortunately problems. I use SABnzbd via IE11 on Win7x64.

First I noticed that the html-login does not respond with IE. After input, nothing happens. The html-login I have now deactivated.

The second and bigger problem. With the IE you can not call the settings. You can see the main window but the top line "General", "Folder" ... is not displayed. On the right side you see two scrollbar? The IE cache has already been deleted!

I tested the whole thing again on another PC with identical system and had the same result.

With the Firefox, the interface of SABnzbd is shown as always.

Best regards

![sabnzbd](https://cloud.githubusercontent.com/assets/25462758/22478291/8db0e48c-e7e9-11e6-91fc-4abb0749776b.jpg)

**Comment by Safihre** [comment]
I think you accidentally enabled Compatibility Mode, or IE did it for you. I can get the same look as you when I add my SAB to the compatibility list:
![image](https://cloud.githubusercontent.com/assets/5703454/22480835/11095de2-e7f3-11e6-96af-70fad0642da7.png)

Removing it from the list and all is good:
![image](https://cloud.githubusercontent.com/assets/5703454/22480849/2021a078-e7f3-11e6-8d13-eb8114d3f381.png)

**Comment by schabau** [comment]
Many Thanks,
that was the problem. But SABnzbd was not in a list for compatibility mode. The "Use Compatibility Mode for Intranet" option was selected. Also the html-login goes so again.

Best regards

**Comment by sanderjo** [comment]
@Safihre ... wow ... you had it right in one hit. Impressive.

@schabau out of curiosity: what kind of hardware en OS is your "small Linux server"?

**Comment by schabau** [comment]
OS = Eisfair
Hardware = http://www.schabau.goip.de/
"Mein kleiner Webserver" ;-)

**Comment by sanderjo** [comment]
Ah, interesting machine. Therefor I think you can handle this:

Your SAB says:

> Sichere (SSL) Verbindungen von SABnzbd zu den Newsservern und HTTPS-
> Webseiten werden verschlüsselt, allerdings ist es nicht möglich die 
> Identität eines Servers mittels Zertifikat zu bestätigen. Python 2.7.9 oder 
> höher, OpenSSL 1.0.2 oder höher und aktuelle lokale CA certificate werden 
> benötigt.

As your python and OpenSSL are OK, the problem must be with your CA certificate store. I would advice you to solve that so that you can securely use HTTPS and NNTPS.

**Comment by schabau** [comment]
The problem or the cause will be clarified very quickly.
This is a small private server and I have there only self-signed certifications. Nothing expensive bought.

Best regards

**Comment by sanderjo** [comment]
Well, it is meant for **outgoing** NNTPS connections (to newsservers) and outgoing HHTPS connections (for RSS / NZB / API sites). So no costs for you involved.

@Safihre and I have built more secure checks into SABnzbd, and we promote users to use them for their security.

**Comment by schabau** [comment]
Now there is the problem that I no longer understand what it is.
Simple reason, I understand only a few English and translate my questions and read the answers by google translator.
You can also contact me by mail, but please in German.

Best regards

**Comment by schabau** [comment]
And, I just checked again, my ca certificate is still valid until 2023.

Best regards

**Comment by Safihre** [comment]
Glad IE 11 works again!
