### ISSUE TITLE
Suggestion: Option to set a tag to naming

### ISSUE THREAD

**Issue by xmicks** [sabnzbd/sabnzbd#806]
I'd like the option to add a 'tag' to my downloads. For instance to a movie I like to set the audio quality: "DTS", "DD5.1" or I like to set video quality: "WEB-DL", "Blur-Ray", "WEB-Rip" enz. So when post-processing the files and renaming it sab should add this tag at the end of the movie/filename.

I usually first download the WEB-DL version and when later available the Blu-Ray rips, but sab names them like there are multiple parts by adding ".1" to the filename.

I'd suggest to add this this feature in the Add NZB menu as well as in the queue.

**Comment by thezoggy** [comment]
just use the release name?

**Comment by Safihre** [comment]
Although I understand your idea and why you want it, I think it's too exotic to implement. 
I think this is out of SAB's scope and more suited for advanced movie sorting software like Couchpotato or [Watcher](https://github.com/nosmokingbandit/watcher) which in turn work well with SAB. 
Or indeed not use the renaming of the file, only use the folder sorting.

**Comment by xmicks** [comment]
I understand your opinions. Will go experimenting with coutchpatato and such others.
