### ISSUE TITLE
Constantly freezing

### ISSUE THREAD

**Issue by trippinshrumes** [sabnzbd/sabnzbd#807]
I'm running this on UBUNTU 16.04 LTS, I7-3770K, 16GB DDR3

I have been using SAB and loved it for quite some time, although with this new release, this has been a CONSTANT issue since. I'm litterally just trying to get to the config page to get my server list out and I'm having issues.

Right now it's not even downloading anything, only running verification checks on a file. This alone is causing SAB to become completely unresponsive. I don't understand why this was a stable release, but I am switching to NZBget until there's either a reason to come back or NZB ends up being worse than SAB.

If you'd like any log files you're more than welcome. I'm leaving it installed during my testing phase of NZB so whatever I can do to help I will. Thanks

**Comment by thezoggy** [comment]
so far no one but you have reported this.

i understand you are frustrated, but ideally you need to provide useful information if you want to get anything resolved instead of 'somethings wrong, fix it'. also sab forums are probably a better place since github is going to make anything and everything public in case you have things in your logs you'd rather not share.

so lets start off with the basics since you haven't answered those yet:
* what version of sab ( 1.1.0? 1.2.0? develop?)?
* where did you get it from (git? package manager? ppa?)? 
* does the problem go away after downgrading?

**Comment by nzbjamz** [comment]
I've noticed Sab get into a state of only checking files... I just stop it, restart it, it hangs on startup, I force stop it again, and start it. It succeeds, complains about db thing then continues to download again (I also restore the orphaned jobs).

**Comment by thezoggy** [comment]
you finding that par2 is crashing? unrar is crashing? sab's db being corrupt to filesystem issues?

**Comment by Safihre** [comment]
@nzbjam @trippinshrumes: so what part of verification is it hanging on? 
If you could switch logging to +Debug and then send me the log at Safihre@sabnzbd.org after it got stuck, then we can try to fix it!

**Comment by nzbjamz** [comment]
Thanks @Safihre! Will do the next time I see it.

**Comment by Safihre** [comment]
@nzbjam are you also on Ubuntu? 
I have someone else on the forum reporting this problem, he's also on Ubuntu.

**Comment by nzbjamz** [comment]
I'm on some QNAP flavor of Linux :P *(no worries, it's not a big deal but I'll follow-up)*

**Comment by Safihre** [comment]
@nzbjamz no more crashes?

**Comment by nzbjamz** [comment]
I've been side-tracked with another non-sabnzbd issue so haven't been running it.

**Comment by Safihre** [comment]
@trippinshrumes any more details?

**Comment by nzbjamz** [comment]
Checking in, I was able to jump start some items by pausing them (while in their checked state) and resuming them. This would change their color from blue to green as well.

**Comment by Safihre** [comment]
Is this on 1.2.1Beta1?

**Comment by nzbjamz** [comment]
On 1.2.0. Will upgrade to 1.2.1Beta1 soon though.

**Comment by Safihre** [comment]
Closing this due to no more response. Can re-open when the problem occurs again and there's log's 👍

**Comment by nzbjamz** [comment]
BTW I'm on 1.2.2 and haven't noticed any issues related to this so far.
