### ISSUE TITLE
SSL: TLSV1_ALERT_UNKNOWN_CA error

### ISSUE THREAD

**Issue by nzbjamz** [sabnzbd/sabnzbd#812]
I've been seeing these error pop up in the error logs in the UI:
```txt
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] unknown error (_ssl.c:590)
```
Is this related to the site running in `https` with its self signed cert? *(I'm running it locally)*
I've made it trusted on the OSX side, though it still complains about `net::ERR_CERT_COMMON_NAME_INVALID`.

When I attempt to refresh the https cert and key (from the Sab config refresh icon) I get:
```txt
 Error creating SSL key and certificate
```

**Comment by nzbjamz** [comment]
When I attempt to refresh the https cert and key (from the Sab config refresh icon) I get:
```txt
 Error creating SSL key and certificate
```

**Comment by thezoggy** [comment]
sounds like you have multiple issues going on..  
all could span from the same issue (missing or outdated openssl or permission issues)... hard to say unless we have more information. 

are you running sab from source or via some qnap package?

**Comment by nzbjamz** [comment]
I'm running it via a qnap package but I've gotten its certs working enough to not have issues in the about page:
<img width="100%" src="https://cloud.githubusercontent.com/assets/25286297/22633248/7f26fa20-ebd4-11e6-858c-425961b3bda5.png">

I don't remember this happening from the start so maybe it needs to just be restarted *(the nas that is)*

**Comment by thezoggy** [comment]
have you reached out to qnap package manager for this then / see if others are having the same issue?
as we (sab team) dont create or do anything with qnap...  and since no one else has brought this up it would appear to be something with your setup or qnap package in general. 

but yes, rebooting may help especially if youve been changing certs or updating your CA

**Comment by nzbjamz** [comment]
Naw, I get that you want to punt but I doubt it's the QNAP package as it hasn't always occured. I did however change machines so if it has to do with the site running locally with https that could be an issue.

**Comment by nzbjamz** [comment]
> but yes, rebooting may help especially if youve been changing certs or updating your CA

I believe rebooting has resolved the issue.

**Comment by thezoggy** [comment]
which makes me think the problem wasnt with sab directly..

**Comment by nzbjamz** [comment]
Ya, but it doesn't mean it's the QNAP package either. I feel like you're shutting out the issue rather early. Afterall I did find other real bugs that have been patched. You're quick to dismiss because of the QNAP angle just leads me to mislead you in the future to get an issue properly addressed.

**Comment by Safihre** [comment]
@nzbjamz Do you maybe still have the log after it said
``Error creating SSL key and certificate```?
If you search in the log, it should show a traceback after that error what is actually going wrong. Would be interested to see what the problem is/was.

We actually catch a different version of the `UNKNOWN_CA` error, didn't know this one also existed and what causes it. Maybe we should add this one.

**Comment by nzbjamz** [comment]
@Safihre The next time it pops up I'll catch the log. It looks like I missed it this go around.
