### ISSUE TITLE
Status on mode=queue&output=xml

### ISSUE THREAD

**Issue by mesa57** [sabnzbd/sabnzbd#813]
sabnzbd version 1.2.0
When I retrieve the sab queue with mode=queue&output=xml
every item in the queue has status downloading in stead of the one which is in effect downloading.
The items which are not downloading should have status 'queued',.

**Comment by Safihre** [comment]
SABnzbd doesn't have such a status, jobs are either downloading or paused. 
There is no need for it to know the difference, it just needs to know which jobs in general to finish downloading.
