### ISSUE TITLE
sab 1.2.1b1 -- cpu string

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#814]
we should put the cpu line after  **System performance (Pystone)** not on the same line due to limited horizontal space.. (600px) 
The cpu string gets truncates the data with no way of seeing the information, for example I see: ` Intel(R) Core(TM) i7-4790…`

**Comment by thezoggy** [comment]
maybe just move the pystone + cpu info to the config root page?

**Comment by Cpuroast** [comment]
Yeah config root page would probably be the best place for it.

**Comment by Safihre** [comment]
I don't think so, because the first Config page is about info about the SABnzbd setup.
I added a tooltip, this way someone really wants to know can find it out.

![image](https://cloud.githubusercontent.com/assets/5703454/22773845/952b452e-eea4-11e6-9525-2e660fa499e2.png)
