### ISSUE TITLE
Develop Branch breaks nzbtomedia post-proc script

### ISSUE THREAD

**Issue by gerbil42** [sabnzbd/sabnzbd#815]
I've been running on Windows from Python source (2.7) for a while now on the develop branch.  Last night I noticed that all of my downloads were failing nzbtomedia postproc (both CouchPotato and SickBeard/SickRage)scripts were failing with the same error message:

```
[12:19:33] [INFO]::MAIN: Auto-detected SECTION:SickBeard
Traceback (most recent call last):
  File "D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "D:\SickRage\contrib\nzbToMedia\nzbToMedia.py", line 732, in main
    download_id='')
  File "D:\SickRage\contrib\nzbToMedia\nzbToMedia.py", line 612, in process
    extractFiles(inputDirectory)
  File "D:\SickRage\contrib\nzbToMedia\core\nzbToMediaUtil.py", line 1097, in extractFiles
    for inputFile in listMediaFiles(src, media=False, audio=False, meta=False, archives=True):
  File "D:\SickRage\contrib\nzbToMedia\core\nzbToMediaUtil.py", line 997, in listMediaFiles
    for curFile in os.listdir(path):
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\D:\\sabnzbd\\Downloads\\complete\\tv\\Black Mirror S03 COMPLETE 720p WEBRip X264-DEFLATE/*.*'
```

In the SAB log the corresponding line looks like this:
`
2017-02-09 12:19:02,762::INFO::[newsunpack:166] Running external script D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py(\\?\D:\sabnzbd\Downloads\complete\tv\Black Mirror S03 COMPLETE 720p WEBRip X264-DEFLATE, Black.Mirror.S03.COMPLETE.720p.WEBRip.X264-DEFLATE.nzb, Black Mirror S03 COMPLETE 720p WEBRip X264-DEFLATE, , tv, alt.binaries.hdtv, 0, )`

The nzbtomedia logs just show "triggered by/Git Update Check" then no progress.

I did a checkout on the master branch to roll back from Develop to 1.2.0 to verify that it was a Sab update that caused the change, not a nzbtomedia change (I also have auto-update turned on for those scripts as well) and the format of the Running external script line changes slightly:

`2017-02-09 17:51:28,523::INFO::[newsunpack:165] Running external script D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py(D:\sabnzbd\Downloads\complete\tv\The Big Bang Theory S10E15 720p HDTV X264-DIMENSIO, The.Big.Bang.Theory.S10E15.720p.HDTV.X264-DIMENSION.nzb, The Big Bang Theory S10E15 720p HDTV X264-DIMENSIO, , tv, alt.binaries.etc, 0, )`

Other lines around this one in the SAB log still use the \\?\ prefix to the path, but not this one, and the PostProc script executed flawlessly for this download. 

Edits - Oops, can't seem to nest bolding the offending part of the logs within a code block markup.

**Comment by Safihre** [comment]
We will change this back for 1.2.1 final. But can you submit an issue with nzbToMedia? 
Because for 2.0.0 (next release) we will be switching to long path (the `\\?\` at the start) on Windows. 
Otherwise if the extraction path is longer than 250 characters, it will fail on Windows. 
I think all he needs to do is use `os.path.join` when adding that `*. *` at the end. Because now the slash at the end is the wrong way for Windows.

**Comment by gerbil42** [comment]
Yeah, I'll see if I can figure out how to do that and link to this thread.

**Comment by clinton-hall** [comment]
The problem is I don't append the `*.*` this is done in the python module os.listdir
There is a patch... but that needs to be done in python
https://bugs.python.org/issue13234
I'll see if there is something I can do in nzbToMedia to support the long path....

**Comment by Safihre** [comment]
@clinton-hall Seems the listdir works if you make it unicode. 
That's also what we do :)

**Comment by clinton-hall** [comment]
Thanks @Safihre 
converted them all to unicode...
Hopefully my scripts will be 2.0.0 compatible.

**Comment by gerbil42** [comment]
Ugh.  I switched back to sab develop to test Clinton's update to nightly last night for this issue, but, out of habit, did a pull on sab develop and got your commit https://github.com/sabnzbd/sabnzbd/commit/caf5adc42dcc574714410ba7b2318f070c6efe0f from last night.

How do I roll that back to the previous state to test Clinton's fix?

**Comment by Safihre** [comment]
You can try: `git checkout tags/1.2.1Beta1`

**Comment by gerbil42** [comment]
Okay, I've done that, and restarted Sab.  We'll see how tonight's downloads go.

**Comment by gerbil42** [comment]
So far so good with the first test.  I can see that the call to the external script still uses the new format with the tags/1.2.1Beta1 checkout.

`2017-02-10 18:15:47,687::INFO::[newsunpack:166] Running external script D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py(\\?\D:\sabnzbd\Downloads\complete\tv\The Vampire Diaries S08E12 720p HDTV X264-DIMENSIO, The.Vampire.Diaries.S08E12.720p.HDTV.X264-DIMENSION.nzb, The Vampire Diaries S08E12 720p HDTV X264-DIMENSIO, , tv, alt.binaries.etc, 0, )`

And everything ended up in the right place from that point, from nzbtomedia - sickrage - plex.

**Comment by Safihre** [comment]
@clinton-hall nice work :)

**Comment by clinton-hall** [comment]
Thanks. To be fair you told me what needed to be done.
I'll merge up to master soon so as far as nzbToMedia is concerned there should be no reason to hold off on implementing the long paths.
