### ISSUE TITLE
Multi-URL RSS feed time-out issue

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#816]
When you have multiple rss urls defined in a comma separated rss feed entry and one of them does not respond or times out, it does not continue checking the rest of them.

**Comment by Cpuroast** [comment]
This is in 1.2.1 Beta1, but I'm pretty sure 1.2.0 was also affected when the multi-url rss feature was added

**Comment by Safihre** [comment]
Fixed!
