### ISSUE TITLE
Ubuntu free space incorrect and does not recognize disk quotas

### ISSUE THREAD

**Issue by marka65** [sabnzbd/sabnzbd#817]
Seems like the free space on ubuntu is not taking into consideration disk quotas for user.

SABnzbd version: develop [1b3146d]
OS: Ubuntu 14.04.5 LTS 3.13.0-86-generic

![image](https://cloud.githubusercontent.com/assets/16505919/22853834/c8b930e6-f0ab-11e6-9d56-d737c6ae8953.png)

![image](https://cloud.githubusercontent.com/assets/16505919/22853836/dc56d32e-f0ab-11e6-895b-5386b75dcac6.png)

**Comment by sanderjo** [comment]
What OS command do you use to find the available quota space? 
In the above example, what is your available space?

Do you know - by any chance - a (pure) python call to find out the available space?

And of curiosity: what kind of Ubuntu system is that? Only used by you, or also others?

**Comment by marka65** [comment]
I'm no Ubuntu guru, and googled it - the first one that came up and that I used was quota -v. Just tried quota -s and that parameter shows the result in more readable format.

![image](https://cloud.githubusercontent.com/assets/16505919/22858698/2bd4145c-f110-11e6-970a-168770ff6ab4.png)

Yes, it is a shared system - a seedbox
Cheers

**Comment by sanderjo** [comment]
And in your example, is "space" what you've used, and "quota" (or "limit") is your limit? The man page says:

> DESCRIPTION
>        quota  displays  users'  disk  usage and limits.  By default only the user quotas are printed. By default space usage and limits are shown in kbytes (and are named blocks for historical reasons).
>        quota reports the quotas of all the filesystems listed in /etc/mtab.  For filesystems that are NFS-mounted a call to the rpc.rquotad on the server machine is performed to get the information.

I installed quota on my Ubuntu, activated it on my disk, but did not set a limit, and (FWIW) here are some outputs:
```
sander@Stream-13:~$ quota -v
Disk quotas for user sander (uid 1000): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2 6358168       0       0           42100       0       0        
```
So, quota and limit "0" mean no limit...
```
sander@Stream-13:~$ quota -wp -f ~
quota: Mountpoint (or device) /home/sander not found or has no quota enabled.
quota: Not all specified mountpoints are using quota.
```

**Comment by marka65** [comment]
Yes, I believe that the space is the amount of data you have used of your quota
```
xxxxxxxx@xxxxxxxx:~$ quota -v
Disk quotas for user xxxxxxxx(uid 1082):
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
      /dev/sda2 2353648  62914560 62914560           10421       0       0

```

```
xxxxxxxx@xxxxxxxx:~$ quota -s
Disk quotas for user xxxxxxxx(uid 1082):
     Filesystem   space   quota   limit   grace   files   quota   limit   grace
      /dev/sda2   2299M  61440M  61440M           10421       0       0

```

```
xxxxxxxx@sxxxxxxx:~$ quota -wp -f ~
quota: Mountpoint (or device) /home/xxxxxxxx not found or has no quota enabled.
quota: Not all specified mountpoints are using quota.
```

**Comment by sanderjo** [comment]
I installed and activated quota on my Ubuntu, set quota on the user "piet", and as piet created new 5MB files ... until quota kicked in. See output below.

So far, based on the output of "quota -v", I would say,
if quota - blocks > 0: still space left to write
if grace - blocks > 0: maybe some space left to write.
if blocks shows a start after the number, blocks is above quota and/or grace.

So a one-liner:
```
$ quota -v | grep "/" |  awk '{ print "Space available:", int($3)- int($2),  "kB\nGrace available:", int($4)- int($2) "kB" }'
Space available: -10000 kB
Grace available: 0kB

```
After removing all the test files:
```
$ quota -v | grep "/" |  awk '{ print "Space available:", int($3)- int($2),  "kB\nGrace available:", int($4)- int($2) "kB" }'
Space available: 10972 kB
Grace available: 20972kB
```
@marka65 Can you run this one-liner on your Ubuntu seedbox?


Unclear: what happens with more than one filesystem? I plugged in a USB memory stick, but alas it was not visable/usable for user "piet".

```
piet@Stream-13:/home/piet$ dd if=/dev/zero of=output-`uuid`  bs=1M  count=5
5+0 records in
5+0 records out
5242880 bytes (5,2 MB, 5,0 MiB) copied, 0,0283907 s, 185 MB/s
piet@Stream-13:/home/piet$ quota -v
Disk quotas for user piet (uid 1001): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2   14148   20000   30000              55       0       0        
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ dd if=/dev/zero of=output-`uuid`  bs=1M  count=5
5+0 records in
5+0 records out
5242880 bytes (5,2 MB, 5,0 MiB) copied, 0,0214474 s, 244 MB/s
piet@Stream-13:/home/piet$ quota -v
Disk quotas for user piet (uid 1001): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2   19268   20000   30000              56       0       0        
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ dd if=/dev/zero of=output-`uuid`  bs=1M  count=5
5+0 records in
5+0 records out
5242880 bytes (5,2 MB, 5,0 MiB) copied, 0,0216479 s, 242 MB/s
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ quota -v

Disk quotas for user piet (uid 1001): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2   24388*  20000   30000   7days      57       0       0        
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ dd if=/dev/zero of=output-`uuid`  bs=1M  count=5
5+0 records in
5+0 records out
5242880 bytes (5,2 MB, 5,0 MiB) copied, 0,0225988 s, 232 MB/s
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ quota -v
Disk quotas for user piet (uid 1001): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2   29508*  20000   30000   6days      58       0       0        
piet@Stream-13:/home/piet$ 
piet@Stream-13:/home/piet$ dd if=/dev/zero of=output-`uuid`  bs=1M  count=5
dd: error writing 'output-b92eebaa-f12a-11e6-b445-97c9f90ac30d': Disk quota exceeded
1+0 records in
0+0 records out
503808 bytes (504 kB, 492 KiB) copied, 0,00365574 s, 138 MB/s
piet@Stream-13:/home/piet$ 
```

The resulting files, with the last file incomplete because it could not be fully written.
```

-rw-r--r-- 1 piet piet 5242880 feb 12 11:25 output-a5a01004-f10d-11e6-975c-3bbe9a87db0d
-rw-r--r-- 1 piet piet 5242880 feb 12 11:26 output-ac61bc9e-f10d-11e6-831d-6b4a88ff3efb
-rw-r--r-- 1 piet piet 5242880 feb 12 11:26 output-b0105a6c-f10d-11e6-8464-fb0cabe049b6
-rw-r--r-- 1 piet piet 5242880 feb 12 14:54 output-b674f634-f12a-11e6-bbeb-ab4d2608ec5b
-rw-r--r-- 1 piet piet  503808 feb 12 14:54 output-b92eebaa-f12a-11e6-b445-97c9f90ac30d
```

**Comment by thezoggy** [comment]
is your disk quota set per day/week/month/lifetime?
also which seedbox company you using (havent seen this ever brought up before in sickbeard/sonarr/etc) thus I'm curious if others already have solutions or having the quota is abnormal.

have you thought about using the download quota to somewhat control how much space you are using daily/weekly/monthly for downloads:
https://sabnzbd.org/wiki/configuration/1.2/switches > Quota

**Comment by marka65** [comment]
Currently I have used up roughly 3% of my disk space quota of 60GB - so I have roughly 1.8GB currently in my home path.

snthostings.com - Basically, depending on how much you pay gives you a variety of bandwidth, disk space storage and applications available on the seedbox.

No I don't have to use any quota settings in sab, all I'm managing is disk space available to me as I fill it up. And that is where I noticed that sab is reporting back what seems to be the full disk space, not what I have available to me.
```
xxxxxxxx@xxxxxxxx:~$ quota -v | grep "/" |  awk '{ print "Space available:", int($3)- int($2),  "kB\nGrace available:", int($4)- int($2) "kB" }'
Space available: 60516876 kB
Grace available: 60516876kB
```
I would expect that one liner to show that 3% is used of my disk space quota, but it doesn't seem to do that.

**Comment by marka65** [comment]
Not sure if this would help, but rutorrents diskspace plugin reports the correct disk space available, and the used disk space.

[https://github.com/rakshasa/rtorrent](url)
[https://github.com/Novik/ruTorrent/wiki/PluginDiskspace](url)

Cheers

**Comment by thezoggy** [comment]
rutorrent natively doesnt support quota, people had to hack in the support by changing the commands it runs...  one of the common thing i found when looking for 'quota + seedbox' on google this past weekend. 

im having a hard time finding any good free space solutions that cover quotas let alone are cross platform.. as most solutions say run x command and grep out the data.. which is a horrible for support and a sure fire way to have it not be reliable due to how many os/flavors are out there.. let alone env paths

**Comment by thezoggy** [comment]
so for linux, we do `os.statvfs()` looks like this should report back the correct info...  but we may need to do some fuzzy logic to get it to return the correct value...

@marka65 can you run this and report back:
`python -c "import os;print os.statvfs('/')"`

and then
`python -c "import os;print os.statvfs('_replace_this_with_your_sab_download_path')"`

**Comment by marka65** [comment]
**Current space stats for reference from rtorrent tooltip: 58.6 GB/60.0 GB**

```
xxxxxxxx@xxxxxxxx:~$ python -c "import os;print os.statvfs('/')"
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=4888390, f_bfree=2118500, f_bavail=1864420, f_files=1250928, f_ffree=909219, f_favail=909219, f_flag=4096, f_namemax=255)
```

```
xxxxxxxx@xxxxxxxx:~$ python -c "import os;print os.statvfs('/home/xxxxxxxx/downloads/sabnzbd/complete')"
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=475204403, f_bfree=276442792, f_bavail=252298037, f_files=120709120, f_ffree=120619460, f_favail=120619460, f_flag=4096, f_namemax=255)
```

**Comment by sanderjo** [comment]
AFAIK os.statvfs() reports on the filesystem, not any quota involved.

Please correct me if I'm wrong.

**Comment by sanderjo** [comment]
@marka65 I haced together some code. Can you report back how it works on your seedbox? 

https://github.com/sanderjo/quota/blob/master/quota.py

**Comment by marka65** [comment]
Excellent - seems to be getting close to it.......

**Current space stats for reference from rtorrent tooltip: 58.6 GB/60.0 GB**

```
xxxxxxxx@xxxxxxxx:~$ python /home/xxxxxxxx/downloads/sabnzbd/complete/quota.py
Debug: line is       /dev/sda2 1412004  62914560 62914560           10433       0       0
used (kB): 1412004
available (kB): 61502556
availablegrace (kB): 61502556
```

**Comment by sanderjo** [comment]
"Close"? It reports 61502556, and 61502556/(1024*1024) = 58.6 GB ... so I would say perfect. Agree?

**Comment by marka65** [comment]
Yep - that's it :)

**Comment by Safihre** [comment]
Although correct, POpen calls are expensive operations that just take too many cpu cycles. Especially since it's performed twice per second (history and queue call) when the interface is open. 
For mee this is just too much of an exotic situation to place such code into Sab.

**Comment by marka65** [comment]
As a thought, does the disk space available have to be updated that frequently? Maybe triggered by some other parameter/process/timer?

**Comment by thezoggy** [comment]
@marka65 `Current space stats for reference from rtorrent tooltip: 58.6 GB/60.0 GB` is that for `/` ?

**Comment by marka65** [comment]
That is to compare to what results are returned from these custom code bits I run. 
I was using rtorrents tooltip from its web interface as a reference since it is reporting the correct space details.

**Comment by sanderjo** [comment]
> Although correct, POpen calls are expensive operations that just take too many cpu cycles

So that means you also don't want subprocess calls? And no other calls the OS command `quota` ?

**Comment by sanderjo** [comment]
I tried some reverse engineering to see if the info is in a file (so no OS command would be needed):

```
piet@Stream-13:~$ quota
Disk quotas for user piet (uid 1001): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/mmcblk0p2   24392*  20000   30000   6days      58       0       0      
```  
Convert those main values to hex:
```
1001  = 0x03E9
20000 = 0x4E20
30000 = 0x7530
```
... and find them in the file /aquota.user: 

sander@Stream-13:~$ sudo hd /aquota.user | grep -B1 1630
00001620  **e9 03** 00 00 00 00 00 00  00 00 00 00 3a 00 00 00  |............:...|
00001630  **30 75** 00 00 **20 4e** 00 00  00 20 7d 01 00 00 00 00  |0u.. N... }.....|

So, yes the userid, soft and hard limit per user are in /aquota.user, but that file is only readable for root, so no solution there. :-(

```
$ ll /aquota.user 
-rw------- 1 root root 8192 feb 12 09:11 /aquota.user
```

**Comment by Hellowlol** [comment]
Why does it have to be called this often? Can't you just cache it and just call popes every 30 sec or so.

**Comment by marka65** [comment]
Maybe it could be as **Hellowlol** suggested, but also do an update at completed download as well. That would mean that on systems with huge bandwidth, the download may take less than 30 secs or so. Then at least the status would be updated to the correct value on completion.

**Comment by Hellowlol** [comment]
This is a rather narrow user case to its to costly you can always write a prequel script they checks before any download starts.

**Comment by thezoggy** [comment]
talked to the peeps in #python and sadly quotas in general is not supported by about anything.. the only solution is to run a subprocess and parse the result.. which is prob not ideal. 

a pre-queue script is honestly prob the best way to go for the avg user.. but obviously wont fix the 'ui'/backend logic. the good thing is that the backend logic wouldnt stop the downloads because it thinks you have more space than you do... the pre-queue would stop and let you deal with it.. 

its an interesting dilemma and something we've not thought of.... personally the last time i can recall a quota is back in mainframe days or on some super strict shared corporate machine back when hard drives were just tiny... 

maybe the easiest solution is just getting a seedbox that doesnt do quotas?

**Comment by marka65** [comment]
I manage my own space so far, but it means more hands on, but hey it works :)

I understand there are limitations and issues because of os and coding languages differences, and appreciate the discussion.

It probably is possible to get seedbox with no quotas I'm guessing, but as everything is, it means it will cost 10-50 times more. That like this issue, has to be weighed up to see if it is worth the effort/cost.

On a side note:
I would presume that sab will be used more and more in a quota'd environment with the state of all governments "war on terror" premise to collect all information. Here in AUS, they passed a law to collect internet data for "war on terror", and would only be used for national security, and now 18 months later, they have said it may be used in civil cases too....

So that being said, people are crazy to not use seedboxes so as to put a lot of this at arms length. It's no guarantee either, as if Mr Snowden is correct about what he revealed - they are watching me type this as we type huh - click!

**Comment by Safihre** [comment]
I always had caching the result on my to-do-list.
So I implemented it now to only do every 10 seconds.

**Comment by Safihre** [comment]
If the disk is 600GB, but you're only allowed to use 60, why not set minimal free space to 540GB?

Closing this now, due to quotas not being widespread and lack of fast way to get the info. In case any of these things change in the future, this can be re-opened and implemented.

**Comment by marka65** [comment]
No real solution through python, so all good.

Setting of the minimal free space to 540GB would only work if one person had their home drive on that disk. Being a shared system, there may be 10-20 people who use the shared drive (who knows), so the disk space could run down to whatever the admin has spliced up the space less any free space left for healthy drive performance.

Cheers
