### ISSUE TITLE
save nzb option - use category subfolders

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#821]
per irc channel, requesting that when sab backups the nzbs it uses the category subfolder instead of just putting them in one folder.

I can see the reason for this, myself have 4035 nzb.gz files in my nzb backup folder.. it gets slow to manage or find anything over time. segmenting them by cat folders is a simple fix for those that use more than one app (sonarr / couchpotato / etc) that makes it easy to find the related nzb. just need to make sure this doesnt mess with dupe checking..

**Comment by Safihre** [comment]
Adding it to the backlog list. I can see the convenience in it, but it also seems like a very specialized use case that doesn't serve a lot of users.

**Comment by Safihre** [comment]
Not implementing this, the use-case is too niche (how many people will have enabled this at all anyway?).

**Comment by thezoggy** [comment]
i prob will just implement this... as ive started to use sab for more than just one category and it can quickly become sub optimal to look though one giant folder of nzbs for the one you want (especially if its not named nicely). at least with it being segmented it makes it a bit easier to cleanup/manage/search through.

**Comment by Safihre** [comment]
Sound good. Just make sure to keep dupe checking working:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/nzbstuff.py#L1642-L1644
`backup_for_duplicates` is enabled by default.
