### ISSUE TITLE
Suggestion: Add check on cleanup unwanted extensions

### ISSUE THREAD

**Issue by xmicks** [sabnzbd/sabnzbd#823]
I mostly download movies which are in mkv format, but sometimes they come in other extensions and when that's the case. They will likely be cleaned up and there are no files left anymore. The 'renamer' will throw an error that something went wrong renaming files. Because all files were deleted.

Nowadays uploaders change extensions to hide files. When those changed extensions get deleted because theyre considered spam, the 'wanted' file(s) get's deleted.

I could just set less parameters, but could also be an option that sab checks if not all files were deleted? And if so don't delete any files or maybe prompt user which files to keep?

**Comment by xmicks** [comment]
In most cases when the extension is changed there will be an par2 file included to rename the files. Sab could do a recruisive par2 check and check extracted files for par2 files. And after that do the extension cleanup.

**Comment by Safihre** [comment]
I don't understand? What kind of things do you have in your cleanup list? By default there's nothing listed, so it will only delete whatever extensions you have put. 
Just empty the cleanup list or only add things you're sure won't be hidden as mkv, like nfo.

**Comment by xmicks** [comment]
For instance I have jpg as an cleanup extension, but an known 'uploader' hides the download as an jpg file. And in almost every download there is spam in form of jpg file. So I really like to keep jpg as an cleanup extension.

**Comment by sanderjo** [comment]
@xmicks 
With "cleanup unwanted extensions" you're mixing up two SABnzbd features. See below.
You want "cleanup, but only after renaming". I think you can do that with a post-processing script after the renaming, with something like `find . -name "*.jpg" -type f -delete`

HTH.

**Unwanted extensions**
List all unwanted extensions. For example: exe or exe, com
Action when an unwanted extension is detected in RAR files

**Cleanup List**
List of file extensions that should be deleted after download.
For example: nfo or nfo, sfv

**Comment by thezoggy** [comment]
unwanted = stop processing nzb item if we find x,y,z
cleanup = delete files if we find x,y,z

**Comment by xmicks** [comment]
O think I am mixing things up, think I meant cleanup list. I'm working now on a post process script.

Thought maybe this was a suggestion, but everything is quite good thought over. 👍  Can't do any harm to think of ways to improve sab!

**Comment by Safihre** [comment]
We debated before if we should add an option to scan for these special `rename.par` files.

**Comment by xmicks** [comment]
I found that par2cmdline has a feature to check for incorrect file names. So I'll just use that feature in a script and and after that remove the cleanup extensions in that same script.
