### ISSUE TITLE
sab -- develop - downloading

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#826]
downloaded 10gb tv season pack to get better test data, and I see the temp folder space show up then go away off and on the whole time.. every 5-10 secs

![sab1](http://zoggy.net/firefox_2017-02-19_17-30-13.png)
then
![sab2](http://zoggy.net/firefox_2017-02-19_17-30-28.png)

looking at the logs while this is happening, it looks like the Temp space is displayed each time a file is assembled..

**Comment by Safihre** [comment]
Hmmm, side-effect. Will take a look how to fix.
