### ISSUE TITLE
"Download" and "Complete" folder speed displayed path should also have a tooltip

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#827]
"Download" and "Complete" folder speed displayed path right below "System performance (Pystone)" should also have a tooltip the same way it was implemented in for the CPU name in:

https://github.com/sabnzbd/sabnzbd/commit/80a2b1685abad392683e6cf1d9d290b3a6e16e77

When path is too long it shows a truncated path with ...

Example:
Download folder speed 41.3 MB/s  (/Users/User/Downlo…)
Complete folder speed 41.4 MB/s  (/Users/User/Downlo…)

This can easily be added to 1.2.1 before it ships, as its impact is very minimal.

**Comment by Safihre** [comment]
Sure!
