### ISSUE TITLE
sab -- glitter / 1.2.1RC1 -- download speed

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#829]
the download history shows `Downloaded in 1 min 19 seconds at an average of 17.8 MB/s` but the **speed** column in glitter says `18.0 MB/s`.

thought at first it was a rounding thing but just now, both say the same thing.. `15.8 MB/s`.. so its not always it is out of sync.

biggest difference so far I've found is: 
`Downloaded in 36 seconds at an average of 17.8 MB/s`
vs
`18.2 MB/s`

looking through my downloads, looks like the variance is usually .2 or .4 MB difference.. rarely is it .1 or less....

**Comment by Safihre** [comment]
There is a difference in the way SAB calculates it and Glitter (amount/time), the discrepancy becomes bigger the faster the download speed was. 
So I think probably a rounding error somewhere.

**Comment by thezoggy** [comment]
why is glitter needing to even compute the speed if sab already does it?

looking briefly at this..  i see all sorts of wasted cpu cycles and 'fixes' to change it from one format to another...

ideally we should make sab return the speed in bytes.. that way the ui/script/whatever can decide what human readable format to use.. 

just like the actual file sizes.. and so on.. 

then we use something like:
https://filesizejs.com/

to convert it easily to whatever format the user wants/we decide..

**Comment by thezoggy** [comment]
side note,

cache buster for favicon is set for 1.1.0:
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Glitter/templates/static/javascripts/glitter.main.js#L105

1.0.0 here:
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Glitter/templates/main.tmpl#L33

**Comment by Safihre** [comment]
Feel free to change all those things :) Yes they should be better, but since it's a hidden option and it's only partly wrong, I didn't do it. 
Also I'm not sure which of the two speeds is actually correct.. Sab's internal calculations I don't completely understand.

**Comment by thezoggy** [comment]
looks like sab do everything in bps (bits per second), which about as low as you can go..  that precision may be needed for things like quota to be accurate. but anyways just means with bps the numbers are going to get pretty large.. also not sure why shy is doing it as a `0.0` as the number should not ever be a faction at that level as there is nothing smaller..  unless he does it because he converts it later to a decimal? float? and it just makes it easier.. but at the added cost of how its stored as a data structure. 

there is plenty of things out there about why you dont want to use decimals with python when you want to do any large values.. bugs :(
https://docs.python.org/2/tutorial/floatingpoint.html

1 Mbps == 1,000,000 bps
150 Mbps == 150,000,000 bps

now using ints.. is there limits in python? `2**31-1` which is `2147483647`:
http://stackoverflow.com/questions/9860588/maximum-value-for-long-integer

2147483647 bps == 2,147.483647 Mbps

now whats the chances of a sab user running into this limit?

now if sab did Kbps instead of bps..
thats where the fractions would come into play.. to get the bps precision..
1 Kbps = 1,000 bps
2147483647 Kbps == 2,147,483.647 Mbps

but i digress.. changing the data type used or the way we do stuff is going to cause a crap ton of extra work (queue/values/quota/etc).
