### ISSUE TITLE
sab -- OSX IO priority

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#830]
I see this in sab startup:
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1210

from the comment it I'm thinking its legacy and we dont even support `10.5` (Leopard) anymore..  but maybe it just means 10.5+
https://forums.sabnzbd.org/viewtopic.php?t=16

but I'm curious to know if its actually still useful for the versions we do support.. 
does it cause more harm than good? we limiting performance?
does it even work with the hardcoded path... has it changed since this was added 7 years ago?

I've seen libc issues plague alpine linux and other setups.. not sure if it carries over to osx.. but simple search makes me think that this may not even be working for el captain and newer peeps:
https://www.google.com/search?q=osx+%2Fusr%2Flib%2Flibc.dylib&ie=utf-8&oe=utf-8

**Comment by Safihre** [comment]
@shypike Seems to have been there for 7+ years, does it maybe indeed limit our performance?
I checked, and on my Sierra machine this command works fine. So it's definitely still there.

**Comment by shypike** [comment]
I don't know, the code was put in by the guy who ported it to OSX.
Since the code is in a try/except, it should be safe.
What does SABnzbd log when running on Sierra? Failure should log "[osx] IO priority setting not supported".

**Comment by Safihre** [comment]
@shypike I can't test performance really.. 
But we don't do anything similar for any other platforms, so maybe we should remove it?

**Comment by Safihre** [comment]
The priority can be set to multiple levels, currenlty it's set to `3=IOPOL_THROTTLE`, [meaning lowest priority](http://www.manpagez.com/man/3/setiopolicy_np/).

**Comment by Safihre** [comment]
No feedback from Alpha1/Beta1 so closing this now.
