### ISSUE TITLE
SAB on Linux: Encoding and locale - Notes and Discussion

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#831]
This item is about SAB on Linux (not on Windows nor MacOS). It's meant for discussion and notes.

SABnzbd prints the encoding it is running under. If it says
`Preferred encoding = UTF-8`
everything is fine and SAB's unrar will safely unrar Unicoded rar files 

If it says something else, for example
`Preferred encoding = ANSI_X3.4-1968`
there will be problems if you have a download with unicoded filenames/directories in it. You can and should correct that setting at the OS level.

Suggestions for improvements in SABnzbd:
1) SAB on Linux should print a Warning or Error if the Preferred Encoding is something else than UTF-8
2) or SAB on Linux can print a Warning if Preferred Encoding != UTF-8, and the rar contains names other than pure ASCII.

And we could leave it at that. It's up to the user and his OS supplier to correct this OS locale settings

**Some background**

On my Ubuntu, default encoding is UTF-8:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

as confirmed by python:
```
$ python -c "import locale ; print locale.getpreferredencoding() "
UTF-8
```

With the "env LANG=..." before a command, you can set it temporarily:
```
$ env LANG=c python -c "import locale ; print locale.getpreferredencoding() "
ANSI_X3.4-1968
```

**Impact of LANG on unrar command**

**Preparation**

```
cd
mkdir we-love-unicode
cd we-love-unicode/
wget https://www.appelboor.com/dump/we-love-unicode/unicode-inside.rar
```

Then unrar with default locale LANG, which is UTF-8, which is correct:
```
sander@Streamer13:~/we-love-unicode$ unrar x unicode-inside.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal
Extracting from unicode-inside.rar
Extracting  ★ ☂ ☊ ☢ Hello World ★ ☂ ☊ ☢ .txt                          OK 
All OK
```
With another UTF-8 defined, OK too:
```
sander@Streamer13:~/we-love-unicode$ env LANG=nl_NL.utf8 unrar x unicode-inside.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal
Extracting from unicode-inside.rar
Extracting  ★ ☂ ☊ ☢ Hello World ★ ☂ ☊ ☢ .txt                          OK 
All OK
```

Impact of non-UTF-8 locale on unrar:

```
sander@Streamer13:~/we-love-unicode$ env LANG=C unrar x unicode-inside.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal
Extracting from unicode-inside.rar
Cannot create ? ? ? ? Hello World ? ? ? ? .txt
No such file or directory
No files to extract
```
So that's not good.

Question: If Preferred Encoding is not UTF-8, and en_US.utf8 is available on the OS, what will happen if SABnzbd would run "env LANG=en_US.utf8 unrar ...." ? Would that result in a succesful unrar?

**Testing** 

I've created two post with Unicode file / directory name in them, so that you can test your setup.

Unicode Filename

http://nzbindex.com/search/?q=unicode+filename+23897489728937489798234&age=&max=25&minage=&sort=agedesc&minsize=&maxsize=&dq=&poster=&nfo=&hidespam=0&hidespam=1&more=0

Unicode Directory name:

http://nzbindex.com/search/?q=Unicode+directory+3838378979878798&age=&max=25&minage=&sort=agedesc&minsize=&maxsize=&dq=&poster=&nfo=&hidespam=0&hidespam=1&more=0

**Comment by sanderjo** [comment]
For reference, I deliberately ran SABnzbd with the wrong encoding:
```
sander@Streamer13:~/git/sab-19feb2017$ env LANG=c ./SABnzbd.py 
2017-02-23 17:44:56,292::INFO::[SABnzbd:1155] --------------------------------
2017-02-23 17:44:56,293::INFO::[SABnzbd:1156] SABnzbd.py-develop (rev=unknown)
2017-02-23 17:44:56,293::INFO::[SABnzbd:1157] Full executable path = /home/sander/git/sab-19feb2017/SABnzbd.py
2017-02-23 17:44:56,294::INFO::[SABnzbd:1169] Platform = posix
2017-02-23 17:44:56,294::INFO::[SABnzbd:1170] Python-version = 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]
2017-02-23 17:44:56,294::INFO::[SABnzbd:1171] Arguments = ./SABnzbd.py
2017-02-23 17:44:56,295::INFO::[SABnzbd:1173] Preferred encoding = ANSI_X3.4-1968

```
"ANSI_X3.4-1968" ... pure ASCII ... brrr.
When I add one of the Unicode NZB's from above, the result is:

```
2017-02-23 17:45:34,068::DEBUG::[newsunpack:736] UNRAR output 
UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal


Extracting from /home/sander/Downloads/incomplete/Unicode dir and file/unicode-dir-with-unicode-file.rar


Would you like to replace the existing file /home/sander/Downloads/complete/_UNPACK_Unicode dir and file/? ? ? ? chess directory/? ? my piece.txt
0 bytes, modified on ????-??-?? ??:??
with a new one
9 bytes, modified on 2017-02-22 16:00

[Y]es, [N]o, [A]ll, n[E]ver, [R]ename, [Q]uit
Program aborted
2017-02-23 17:45:34,068::INFO::[newsunpack:740] Unpacked 0 files/folders in 6 seconds
2017-02-23 17:45:34,069::DEBUG::[newsunpack:474] rar_unpack(): Rars: [u'/home/sander/Downloads/incomplete/Unicode dir and file/unicode-dir-with-unicode-file.rar']
2017-02-23 17:45:34,069::DEBUG::[newsunpack:475] rar_unpack(): Newfiles: []
2017-02-23 17:45:34,070::INFO::[newsunpack:235] Unrar finished on /home/sander/Downloads/incomplete/Unicode dir and file
```
So, as expected, that went wrong.

Let's check the resulting files:
```
sander@Streamer13:~$ ll Downloads/complete/Unicode\ dir\ and\ file/
total 12
drwxr-xr-x 2 sander sander 4096 feb 23 17:45 ./
drwxr-xr-x 5 sander sander 4096 feb 23 17:45 ../
-rw-r--r-- 1 sander sander  172 feb 23 17:45 unicode-dir-with-unicode-file.rar
sander@Streamer13:~$ 
```
So the rar(s) are not unpacked.

QED.

To stay out of these situation, it's most easy for SAB to refuse downloading if Preferred Encoding is  not UTF-8. We introduced Unicode in SAB some time ago, so let's also require that from the OS/startup, otherwise the "Unicode" claim is a bit useless.

**Comment by Safihre** [comment]
@sanderjo why don't you make a PR where you put a WARNING after the log line where we do the preferred encoding? Warn the user that jobs with special naming or containing files with special names will fail. 
But only when not WIN32 and not DARWIN, because there the executables take care of it.

**Comment by sanderjo** [comment]
Like this?

![sab warning no utf-8](https://cloud.githubusercontent.com/assets/1273502/23270464/2be23054-f9f4-11e6-8b51-d6cf34112615.png)

**Comment by Safihre** [comment]
Yes :)
