### ISSUE TITLE
Wrong message about undecryptable file 

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#833]
I'm using 1.2.0 [1be50eb] and get a message about a not decryptable rar file:
> Paused job "something" because of encrypted RAR file (if supplied, all passwords were tried)

If I resume this job the files are decrypted anyway.

I will send you a PM with this NZB and password if you want.

**Comment by Safihre** [comment]
Fixed in 1.2.1. We will release the Final version today.
