### ISSUE TITLE
sab -- 1.2.1 windows compiled vs non -- folder speed test

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#834]
Why does the speed test get half the speed in the binary builds compared to the git version?
I understand 32bit vs 64bit python between the version which prob explain the pystone difference.. but not the disk io...

- Windows binary:
1.2.1 [d32cf57]
Python Version: 	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] [cp1252]

**System performance (Pystone)** 199899 Intel(R) Core(TM) i7-4790…
**Download folder speed** 242.7 MB/s (C:\Users\…)
**Complete folder speed** 346.2 MB/s (C:\Users\…)

- master git:
Version: 	1.2.1 [d32cf57]
Python Version: 	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] [cp1252]

**System performance (Pystone)** 225040 Intel(R) Core(TM) i7-4790…
**Download folder speed** 648.3 MB/s (c:\test\downloads\incomp…)
**Complete folder speed** 703.1 MB/s (c:\test\downloads\comple…) 

> just checked develop branch, same as master:

- develop git:
Python Version: 	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] [cp1252]

**System performance (Pystone)** 228095 Intel(R) Core(TM) i7-4790…
**Download folder speed** 656.1 MB/s (c:\test\downloads\incomp…)
**Complete folder speed** 691.7 MB/s (c:\test\downloads\incomp…)

**Comment by Safihre** [comment]
Do you run with `python -OO SABnzbd.py `?

**Comment by thezoggy** [comment]
running with `-OO` on develop branch:

**System performance (Pystone)** 229939 Intel(R) Core(TM) i7-4790…
**Download folder speed** 645.8 MB/s (c:\test\downloads\incomp…)
**Complete folder speed** 704.5 MB/s (c:\test\downloads\comple…)

**Comment by Safihre** [comment]
For me the results are about the same: ~150MB/s.
Just like a previous discussion about the test: this functionality was never introduced to test speeds like those. All it was meant to do was find out if the user doesn't have some weird mounting or external drive that's slower than they think.
So more "Is it 2MB/s or 40MB/s?" not 700 vs 300.

**Comment by thezoggy** [comment]
its a bit misleading then with it being so up front and in your face when you first load the modal.. same with pystone..

**Comment by Safihre** [comment]
@thezoggy 
It turns out it's the difference between 32bit and 64bit.
I am now also compiling 64bit versions for SABnzbd 2.0.0 and there I also see that the 32bit version gives me 150MB/s while the 64bit one gives me 250MB/s.

Sidenote: on my work's gigabit connection the 64bit version is actually up to 10% faster than the identical 32bit version.
