### ISSUE TITLE
Post Process Issue after update to 1.2.1

### ISSUE THREAD

**Issue by Artwebb1986** [sabnzbd/sabnzbd#835]
In 1.2.0 post processing works fine after upgrading to 1.2.1 i get this 

WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\E:\\!!SAB-DOWNLOAD\\Complete\\TV\\

Im assuming its the !! before the directory name, its been named that since Thursday, ‎January ‎26, ‎2012, ‏‎6:26:20 PM and has worked just fine. I do it so the directory is at the top of the list.

Thanks

**Comment by Safihre** [comment]
We implemented a fix wrongly, so now the paths have the `\\?\` prepended to it.

**Comment by Safihre** [comment]
Will release a fixed version.

**Comment by Safihre** [comment]
Released 1.2.2 with the fix.

**Comment by Artwebb1986** [comment]
Awesome that was quick :)
