### ISSUE TITLE
sab -- version

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#836]
from another dev that supports sab:
> tell someone to use semver, please. :D

http://semver.org/

to be in the correct version we should have done: `2.0.0-alpha.1`

**Comment by Safihre** [comment]
Agreed, but our version-checker is based on the current notation:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L611-L632
So nothing we can really change..

**Comment by thezoggy** [comment]
or you know.. for 2.x we actually update the checker to do semver for 2+

**Comment by Safihre** [comment]
And what about all the people being on 1.x.x, that would break their version checker.

**Comment by thezoggy** [comment]
why would changing code in 2.x branch break people on 1.x?

**Comment by Safihre** [comment]
Because when they fetch `latest.txt`, they can't parse the version-number correctly.
Or you suggest to use different version-naming there? Or a different file to check for the 2.x branch?
We could do all those things, but I don't really see the necessity.
