### ISSUE TITLE
How to set __version__.

### ISSUE THREAD

**Issue by nzbjamz** [sabnzbd/sabnzbd#837]
I noticed in [version.py](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/version.py) it says that its `__version__` value is patched by `setup.py`. Could you explain that a bit more. When I run sab I usually just update repo to the latest tag. Is there some other init step I'm missing?

**Comment by Safihre** [comment]
That's when we build the executables for release, not for normal git users :)

**Comment by nzbjamz** [comment]
Ah, I notice other apps like Sonarr are detecting it as `develop` build. Is the `verisons.py` file the appropriate thing to edit or is there some other place that it could be keying off of.

**Comment by Safihre** [comment]
If you edit it, your `git pull` might complain.
Sonarr and CP should be patched to handle the `develop` just fine.
In the `master` branch we always set the version, since we only push stable releases there.

**Comment by nzbjamz** [comment]
Ah, ok, thanks! I'll pull from master. (It's currently behind, at 1.2.1 atm).

**Comment by Safihre** [comment]
1.2.2 was a Windows-only fix.

**Comment by nzbjamz** [comment]
> Sonarr and CP should be patched to handle the develop just fine.

Sonarr (2.0.0.4613 - Feb 21 2017) complains when testing it's connection and will fail the test with a warning that it doesn't support `develop` builds of Sab.

**Comment by nzbjamz** [comment]
> 1.2.2 was a Windows-only fix.

Ah, I was seeing increased PostProcess fails too (#835).

**Comment by Safihre** [comment]
Really? Because the path-notation is specific for Windows, so your problems cannot be because of the `\\?\` notation.
Maybe something else?

**Comment by nzbjamz** [comment]
> Maybe something else?

Ya, it was just a rise in PostProcess fails. I'll get on the correct branch though 😄 
Thanks for being super helpful!
