### ISSUE TITLE
tag from master

### ISSUE THREAD

**Issue by nzbjamz** [sabnzbd/sabnzbd#838]
While trying to see if an issue was introduced I'm jumping back to 1.2.0. The easy way would be to checkout the tag. However, since the tag is done from the develop branch and not master it lacks things like the version being set. I think it makes sense for the tags to be of the released bits instead of the develop bits.

**Comment by Safihre** [comment]
What else does it lacks besides the version tag?

**Comment by thezoggy** [comment]
the branch doesnt matter when it comes to tags for a release.

the upstream branch can change however because of this.. 

for example:
2.0.0Alpha1 tag comes from the `develop` branch.
1.2.2 tag comes from the `1.2.x` branch.
1.2.0 tag comes from the `develop` branch.
1.1.1 tag comes from the `1.1.x` branch.
1.0.3 tag comes from the `1.0.x` and `master`

but honestly shouldnt be any big deal.. if you want to stay on branch x just use that.. and git pull to stay up to date. if you want to rely on tags.. well just use those... if your on binary builds.. then all of it is irrelevant.

**Comment by nzbjamz** [comment]
@Safihre
> What else does it lacks besides the version tag?

I think it's just a problem of tagging the wrong commit.

@thezoggy 

> the branch doesnt matter when it comes to tags for a release.

Tags are just references to commits. In this case they're taken at the wrong time. They should be taken on the commit that finalizes the version and so should be done from the `master` branch so things like `__version__` are set properly. As it is I have to hunt down when that was set. See [sabnzbd/1.2.0/sabnzbd/version.py](https://github.com/sabnzbd/sabnzbd/blob/1.2.0/sabnzbd/version.py). It means I then have to walk back through the commit history of the master branch looking for the similar commit message (the commit hash is different on the master branch than the develop) and then walk forward looking for the commit that set the version. In this case [the one after](https://github.com/sabnzbd/sabnzbd/commit/494e72a9963a1810e69f4e0f69df7c9dfb9256b0). When it could be as simple as `git checkout 1.2.0`.

**Comment by thezoggy** [comment]
@Safihre fyi 1.2.2 announcement never made it to reddit.

**Comment by thezoggy** [comment]
@nzbjamz what are you doing where you care about the internal version of sab? are you importing sabnzbd then trying to do __version__ ? are you trying to get the version via api call?

**Comment by nzbjamz** [comment]
@Safihre 
> And it will take you exactly to the right place in the right branch. Yes indeed, the version is probably not set, but that's really all.

Then it's not exactly the right place. It's very much in the wrong place. I've already explained why this is. If the version isn't set then apps like Sonarr complain. It's trivial for you to correct tags with git.
```shell
git tag -f -a -m "1.2.0" "1.2.0" 494e72a9963a1810e69f4e0f69df7c9dfb9256b0
git push -f --tags
```

@thezoggy 
> what are you doing where you care about the internal version of sab? are you importing sabnzbd then trying to do version ? are you trying to get the version via api call?

The version being set correctly effects other apps that tie-in to Sab.

**Comment by Safihre** [comment]
I won't force push stuff, not sure what others are using these tags,
But I will try to do this for next releases. Only stable ones though, Alpha/Beta/RC are based on `develop` and don't get `version.py` set.

I am sure CouchPotato and Sonarr handle `develop` tag fine, because we fixed it with them.

**Comment by thezoggy** [comment]
Sonarr and the like don't care about Sab tags and handle version 'develop' (gives warning and assumes 1.1.0).. the API response is what matters

**Comment by nzbjamz** [comment]
@Safihre 
> I won't force push stuff, not sure what others are using these tags,
But I will try to do this for next releases. Only stable ones though, Alpha/Beta/RC are based on develop and don't get version.py set.

Great! I'll reopen if there's a problem in future releases.

> I am sure CouchPotato and Sonarr handle develop tag fine, because we fixed it with them.

As @thezoggy pointed out it's not the tag but the version it's taking its cue from. If it has `develop` it will fail when testing the connection.
