### ISSUE TITLE
unrar: "File too large", SAB says "Unpacking failed, write error or disk is full?"

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#839]
This is a suggestion / for discussion:

The unrar command says "File too large" (as in sabnzbd.log), but SAB just says "Unpacking failed, write error or disk is full?"

(The root cause is that I was saving to a FAT FS, so files > 4.2 GB are not possible.)

Question: is "File too large" unique for those FAT situations? Or, is it useful information for the user?
If so, we could let sabnzbd/newsunpack.py scan for that line, and report it.

If not useful, I will close this thread. 

```
Extracting from /media/sander/INTENSO/Downloads/incomplete/blabla/blabla.r07

...         blabla.iso
File too large
Write error in the file /media/sander/INTENSO/Downloads/complete/_UNPACK_blabla/blabla.iso [R]etry, [A]bort
2017-02-27 21:28:37,375::INFO::[newsunpack:235] Unrar finished on /media/sander/INTENSO/Downloads/incomplete/blabla
2017-02-27 21:28:37,376::INFO::[postproc:383] unpack_magic finished on blabla
```

**Comment by Safihre** [comment]
We can easily catch that exception, feel free to integrate it :)

**Comment by thezoggy** [comment]
so.. a 5 gig file rared will download fine on FAT but when extracted it will puke due to the file size limit. 
thus this is a prime scenario where the download os may have a limitation that the final dest filesystem doesnt.. or vice versa.

(download on windows, store on nas).. 

the issue  https://github.com/sabnzbd/sabnzbd/issues/189
makes me think about this concern, aka: extracting directly to the completed folder then rename vs extract locally then copy+rename to the completed folder...

its hard to know which is the best for everyones work flow.. personally id rather sab do everything it can locally.. since it'd be much easier to predict issues since the remote filsystem may or maynot even say anything back to sab in a meaningful way.

**Comment by Safihre** [comment]
@sanderjo I would add the check here:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/newsunpack.py#L654

**Comment by sanderjo** [comment]
OK, and then just that remark "File too large". That's easy.

Or ... also interpretation "File is too large; bigger dan 4GB max of FAT"? Because I'm not sure if that is the only cause; maybe unrarring a 2GB file with 1GB free on ext3 gives the same error ...
To answer my own question: I will find that out.

**Comment by sanderjo** [comment]
OK, test result on ext3 with too little space to complete the unpack: `No space left on device`. That's a different message, and that's good.

That suggests that `File too large` is really what I suspected "File too large ... for filesystem", which will only happens on FAT, as other filesystems have max file size in the range of what is not downloable.


Full output of manual unrar:
```
sander@haring:~/Downloads/incomplete/iso$ df -h /home/sander/Downloads/incomplete/iso
Filesystem      Size  Used Avail Use% Mounted on
/dev/dm-0        15G   15G  129M 100% /
sander@haring:~/Downloads/incomplete/iso$
sander@haring:~/Downloads/incomplete/iso$ unrar x b-hmbfec.rar

UNRAR 5.00 beta 8 freeware      Copyright (c) 1993-2013 Alexander Roshal


Extracting from b-hmbfec.rar

Extracting  b-hmbfec.iso                                               4%

Extracting from b-hmbfec.r00

...         b-hmbfec.iso                                               8%

Extracting from b-hmbfec.r01

...         b-hmbfec.iso                                              11%
No space left on device
Write error in the file b-hmbfec.iso [R]etry, [A]bort A
Write error in the file b-hmbfec.iso
Illegal seek
Program aborted
```

**Comment by Safihre** [comment]
@sanderjo I see we don't catch 'No space left on device' either. Can you include that one also?

**Comment by Safihre** [comment]
That one should create a WARNING also.

**Comment by sanderjo** [comment]
The code is working, with this output:
![sab and fat](https://cloud.githubusercontent.com/assets/1273502/23491399/5db68f58-fefe-11e6-8132-2825f5d31210.png)

Is this what we want?
