### ISSUE TITLE
Missing files not downloaded on retry anymore

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#840]
My sabnzbd ist on 1.2.1.
Sometimes I get to small part files and sabnzbd doesn't have enough repair block.

With 1.2.0 I deleted the too small rar files in tmp, pressed retry and the download finished.
With 1.2.1 the job stays in history and checks the files again and will certainly fail.

**Comment by Safihre** [comment]
Will have to investigate, never tried this myself yet.

**Comment by ggzengel** [comment]
I use GN and have it very often that the files are incomplete and will complete with a second pass. Even with older uploads.
Perhaps it's a problem with sabnzbd. If a post is not readable or interrupted the file will have gaps.

I have investigated this issue: The NZB file is deleted. If I put a copy in tmp/admin it will make a second download pass.

**Comment by Safihre** [comment]
For for the delay, only now looking into Retry bugs. So from what I understand there is no NZB in the ADMIN folder of the jobs? That should be there, at least the `.nzb.gz` version.

**Comment by ggzengel** [comment]
Since 2.0 this didn't happen any more, because downloads are more stable now.
