### ISSUE TITLE
Improvements to Glitter 

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#842]
I recently updated to 2.0.0Alpha1 and noticed the Secondary Skin option was removed in dc438e6.

I guess I missed the discussion in #778 but I personally use both skins all the time.

I use `Glitter - Night` most of the time, but I strongly prefer the `Plush - gold` interface for mass actions.  Removing the secondary interface means I have to change the config every time I do anything en masse.  

Is there any chance of either restoring the secondary skin option or reworking the mass actions on Glitter to perform more like Plush?

**Comment by Safihre** [comment]
The secondary skin is not coming back, but I would like to improve things for Glitter of course! 
So what do you miss from Plush?

**Comment by labrys** [comment]
In no particular order:

1. The ability to filter the Queue

1. This functionality
![image](https://cloud.githubusercontent.com/assets/1867464/23532436/701f5b5e-ff79-11e6-8dba-711abe1b0da5.png)

1. Delayed application of operations:
![image](https://cloud.githubusercontent.com/assets/1867464/23532466/9119e324-ff79-11e6-8e75-fa978ef75208.png)

1. Having pause / resume status as part of the multi-operation instead of having to apply the operation, then pause/resume.
![image](https://cloud.githubusercontent.com/assets/1867464/23532596/27879c8e-ff7a-11e6-87e2-d02774e6904b.png)

1. Not having to be limited to a single extra column:
![image](https://cloud.githubusercontent.com/assets/1867464/23532689/c3a7c08a-ff7a-11e6-988a-f33c66d5a973.png)

**Comment by Safihre** [comment]
> The ability to filter the Queue

The Search function doesn't work well enough? You know it only shows up when you have set a item-limit.

> This functionality
![image](https://cloud.githubusercontent.com/assets/1867464/23532436/701f5b5e-ff79-11e6-8dba-711abe1b0da5.png)

You can just hold the Shift key to select a range and using the checkbox on the multi-edit bar you can select All or None. Only Invert is missing.

>Having pause / resume status as part of the multi-operation instead of having to apply the operation, then pause/resume.
![image](https://cloud.githubusercontent.com/assets/1867464/23532596/27879c8e-ff7a-11e6-87e2-d02774e6904b.png)

What do you mean? Selecting the pause or resume icon on the multi-edit bar will directly apply it or any new items you select?
![image](https://cloud.githubusercontent.com/assets/5703454/23548415/b886be58-0007-11e7-86f1-39c23bf6d5b7.png)

You are right about delayed application and extra columns..

**Comment by labrys** [comment]
The search should be available regardless of the number of items.  If i want to change X number of similarly named items, in plush I would filter the queue and use the All / Range / Invert to select the proper subset I was interested in.  Its a lot easier than manually clicking a bunch of items in the list (even for a short list).

The pause / resume icons in Glitter do allow for pausing / unpausing selected items, but if I want to set an action set (e.g.  Change priority to High, Set script, and Resume) and then apply it to several different selections (usually selected using the filter method mentioned above) with Glitter I have to apply it in two steps, the action (high + set script) and then the status (resume).  Having them as part of the same action group is a convenience.

Its not that you can't do the same things on Glitter as Plush, its just when doing mass actions, plush is more convenient.

**Comment by Safihre** [comment]
> The pause / resume icons in Glitter do allow for pausing / unpausing selected items, but if I want to set an action set (e.g. Change priority to High, Set script, and Resume) and then apply it to several different selections (usually selected using the filter method mentioned above) with Glitter I have to apply it in two steps, the action (high + set script) and then the status (resume). Having them as part of the same action group is a convenience.

No, you can do them all in the same action? At least that's how it should work. So select the Priority, Script and Resume and then select the ones these 3 things should be applied to.

**Comment by Safihre** [comment]
> The search should be available regardless of the number of items. If i want to change X number of similarly named items, in plush I would filter the queue and use the All / Range / Invert to select the proper subset I was interested in. Its a lot easier than manually clicking a bunch of items in the list (even for a short list).

You know that Select All/None can be done using this button, right?
![image](https://cloud.githubusercontent.com/assets/5703454/23551403/a8d97798-0016-11e7-86f8-8b31e76ff751.png)

Will check what to do with the Search.

**Comment by Safihre** [comment]
I now changed it so that when you Multi-edit the Queue-search will always show, regardless of number of items. 
That actually is quite logical.

**Comment by labrys** [comment]
Yes I know that can select all / none, but without the search filter to only select a small subset its much less useful.

**Comment by labrys** [comment]
As for the pause / resume icon, if it saves that as part of the action to apply, thats fine, but as its selected differently its not obvious that it functions in that way.  The design makes it appear like its intended to function like the trash icon does in that you click it to apply the state for the selected items.

**Comment by labrys** [comment]
Also while discussing the UI (I know its not a feature of either yet) would it be possible to filter lists by additional criteria (e.g. all Paused shows, all items marked DUPLICATE, etc)

**Comment by voidzero** [comment]
I just want to ask you to reconsider the removal of the secondary skin: I was using both, a lot. On my desktop I just really prefer Plush, while on my mobile I prefer Glitter. It was great to see I could use both, really sad to see this removed. So I hope that the feature can come back.

**Comment by Safihre** [comment]
@voidzero What more are you missing from Plush? 

Compared to Plush:

- More columns
- Delay application of options
- ?

New features:

- More filtering
- ?

**Comment by voidzero** [comment]
@Safihre I am just one of those people who stick to a habit once they have it. It's a matter of taste I suppose. It's not that I miss anything from Plush feature wise... just the appearance of it.

But I will concede in the sense that I have gotten used to Glitter. The thing just was that I had a favorite and (semi-)suddenly saw it disappear. And the secondary theme option was something I really liked.

Anyway this all said - from your side I can totally get why you don't want to maintain multiple themes, and Glitter is far from bad. It's actually pretty damn good.

**Comment by albino1** [comment]
I prefer Glitter by a huge margin, but one of the things I do miss from Plush is the NZB Details link after the download finished.  It made it much easier to report a problem to the indexer or leave a useful comment on the file.

**Comment by Safihre** [comment]
Are you sure this is missing from Glitter? Because it has this in the code. Could you take a screenshot of the same NZB that has it in Plush, switch to Glitter and confirm it's not there?

**Comment by albino1** [comment]
Ah, you're right.  I've still got NZBs pushing to an old 0.7.20 install with Plush for all of my automation, whereas I do all of my manual stuff with 2.1.0, so therefore that wouldn't be any included NZB details links in those.  Sorry about that.

**Comment by louisvd** [comment]
One thing I find I am missing in Glitter is the "Refresh" button that exists in Plush.  I find that when I have completed an action, or switch to the TAB with SAB running to check on the progress of a download, that I have to wait for the refresh timeout, or manually refresh the browser page as a whole.  Could you put a Refresh icon back at the top right with all the other action icons?

**Comment by Safihre** [comment]
Ah, you have the refresh rate set to very long times? Not just the default 1 second?

**Comment by louisvd** [comment]
I don't recall ever changing it - it is set to 30 seconds.  I've been running like that since SABnzbd-0.6.7 at least.  Is there a significant performance impact hit by changing this to 1 second, as you mentioned is default?

**Comment by Safihre** [comment]
There is no performance impact really, unless you maybe run it on a mega low power device. Also when the tab is not active, it uses a very low performance mode. 
But you are right, this button could be useful.

**Comment by Safihre** [comment]
The Refresh button will be added to Glitter, but only shown when RefreshRate > 2.

**Comment by louisvd** [comment]
Awesome - sounds like a good solution.  Many thanks.

**Comment by Safihre** [comment]
New request by @OneCDOnly:
https://forums.sabnzbd.org/viewtopic.php?f=4&t=23008&p=113593#p113593

> It would be great to be able to filter the download queue (just like using the 'Search' box), but to show all queue items for a specific category. This might be best done as a drop-down box with the category names populated from those found in the settings. 

> Even better would be one that only shows categories currently in the download queue.

I can imagine it could also work via key words like saying `category:tv,movies`. I think nzbget works like that.

**Comment by OneCDOnly** [comment]
I like the `category:tv,movies` idea. That would be more flexible and wouldn't require a new screen element. :)

**Comment by BlaQPhoeniX** [comment]
Is it possible to get the [ETA hover](http://sx.yoloswag.in/8a2219b4.png) back from Plush?
