### ISSUE TITLE
Title text broken when tab loses focus

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#844]
Win 10 / Chrome / 13a11411a975a3649a661d38c2c0f2152e12625b
![image](https://cloud.githubusercontent.com/assets/1867464/23568015/c636d8ac-0026-11e7-92bd-02bd7c67b91b.png)

**Comment by Safihre** [comment]
This happens when you have switched your skin to Plush in between ;)

**Comment by labrys** [comment]
Ok :)
