### ISSUE TITLE
glitter -- Use global interface settings

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#849]
should add tooltip for `Use global interface settings` under the glitter > web interface option. also noticed that when you enable the check the modal goes away.

**Comment by Safihre** [comment]
What should the tooltip say?

The page is reloaded when you enable it after having it disabled, to re-load the settings, So that's why the modal goes away.

**Comment by thezoggy** [comment]
What does it do? Does it require cookies or localstorage for it to work?

**Comment by Safihre** [comment]
If you have localstorage disabled you will get a big fat warning and for those that need this option, they'll figure it out.

**Comment by thezoggy** [comment]
does this option make it so the 'defaults' in the ui are used across sessions/computers?

**Comment by Safihre** [comment]
Yes, if you change anything in any of the opened sessions it will change everywhere.
