### ISSUE TITLE
unrar takes up to 5 minutes to start in Windows 10

### ISSUE THREAD

**Issue by bartolomesoriano** [sabnzbd/sabnzbd#852]
Noticed that unpacking is really slow to start.  sabnzbd 1.2.2 running under Windows 10 Enterprise Insider Preview 15048.  No errors appear in the log.  There is a delay of up to 5 minutes between when the log shows that unrar is starting and when it actually starts.  unrar version is 64-bit.

**Comment by Safihre** [comment]
This is most likely something specific to your computer. Have you tried without virus scanner for example?

And what times are you looking at in the log? The output is only written to the log when Unrar is finished.

**Comment by bartolomesoriano** [comment]
Thanks for your quick reply.  I will try without virus scanner.  The times i am looking at are these: (from the log)

2017-03-10 10:52:06,674::DEBUG::[newsunpack:572] Running unrar ['C:\\Program Files (x86)\\SABnzbd\\win\\unrar\\x64\\UnRAR.exe', 'x', '-idp', '-o-', '-or', '-ai', '-p-', 'T:\\Downloads5\\Incomplete Downloads\\The.Big.Bang.Theory.S10E18.1080\\archive.part01.rar', '\\\\?\\T:\\Downloads5\\Downloaded TV Episodes\\_UNPACK_The.Big.Bang.Theory.S10E18.1080p.WEB-DL.DD5.1.H264-RARBG\\']
2017-03-10 10:55:45,181::DEBUG::[newsunpack:723] UNRAR output

There is a 3 minute delay there.

**Comment by Safihre** [comment]
Like I said: 

> The output is only written to the log when Unrar is finished.

**Comment by bartolomesoriano** [comment]
Thanks.  I understand, but the behavior has changed (I cannot pinpoint when it started).  In the sabnzbd interface, you can notice the delay from when it shows "unpacking 01/xx" and when it continues with "02/xx"until "xx/xx".  This is the delay I am referring to, and this did not happen before.

**Comment by Safihre** [comment]
Can you try SABnzbd 2.0.0Beta1? 
I included some changes there that might address this issue.

**Comment by bartolomesoriano** [comment]
Of course.  Should I download 64-bit or 32-bit version? I am running 64-bit Windows 10.

**Comment by Safihre** [comment]
Shouldn't make a difference, both should behave the same.

**Comment by bartolomesoriano** [comment]
Thank you! The delay is gone with this version.

**Comment by Safihre** [comment]
Perfect!
