### ISSUE TITLE
Remember password in history

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#855]
SAB should remember the user-provided (or if none, the NZB-provided) password.
This way we can pre-fill it in the Retry dialog.

@shypike what is the best way to add a new column to the database?

**Comment by shypike** [comment]
I'll look into it.

**Comment by shypike** [comment]
I've added the column: https://github.com/sabnzbd/sabnzbd/tree/feature/extra_db_col

**Comment by Safihre** [comment]
Added! Glitter-only.
