### ISSUE TITLE
QQ: what happens to Trying to fetch jobs during restart

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#857]
Occasionally, I have had to restart the machine due to other processes occasionally misbehaving and curious if i should expect those "Trying to fetch" jobs to reappear in the queue? Do these get stored to a DB/File for processing in order to recover from a restart?

**Comment by Safihre** [comment]
They are part of the queue and saved in the NZBQueue file (`queue10.sab` in your `admin` dir), so they are all safe!
