### ISSUE TITLE
sab 2.0.0b1 -- ENGINE Error in HTTPServer.tick

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#860]
just restarted box after windows updates. launched sab and see:
```
2017-03-15 11:01:45,092::ERROR::[_cplogging:219] [15/Mar/2017:11:01:45] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "cherrypy\wsgiserver\__init__.pyo", line 2024, in start
  File "cherrypy\wsgiserver\__init__.pyo", line 2091, in tick
  File "cherrypy\wsgiserver\ssl_builtin.pyo", line 67, in wrap
  File "ssl.pyo", line 363, in wrap_socket
  File "ssl.pyo", line 611, in __init__
  File "ssl.pyo", line 840, in do_handshake
SSLError: [SSL: HTTPS_PROXY_REQUEST] https proxy request (_ssl.c:661)
```

**Comment by thezoggy** [comment]
Now the reason I saw this in the first place.. I have a feeling is when irc starts up... it tries to do an ident request or proxy check when connecting..which kicked off the warning.

I can reproduce this error by doing: `curl -v "https://self-test.sabnzbd.org" -x 192.168.0.3:8080`

anyways, we should catch and discard these requests in sab

**Comment by Safihre** [comment]
I don't understand? Cherrypy allows it to be used as a proxy? Expect when using the ssl port?

**Comment by thezoggy** [comment]
from the curl check, it isnt flat out rejecting the proxy request..  then sab internally throws a traceback. neither case seem optimal.

**Comment by Safihre** [comment]
I don't understand how to fix it, can you look into what changed in cherrypy?

**Comment by thezoggy** [comment]
well in 1.1.1 we were using cherrypy 6.0.2 and in 1.2.0b1 were using cherrypy 8.1.2

**Comment by thezoggy** [comment]
tried cherrypy 8.8.0, same issue..

**Comment by thezoggy** [comment]
sab 2.0.0b1 -- enabled cherrpy logging..  sab does a traceback before the request.. cherrpy does not log the request...

**Comment by Safihre** [comment]
That's strange, don't believe we modify anything related to that:
https://github.com/sabnzbd/sabnzbd/commits/develop/cherrypy

**Comment by thezoggy** [comment]
its not cherrypy but sab that changed the behavior.. i havent had a chance to bisect all the 1.1.1->1.2.0 changes.. but quickly glancing I'm thinking it may be:
https://github.com/sabnzbd/sabnzbd/commit/b6972db5a7823e243850fde87368bce74d398fdb

**Comment by Safihre** [comment]
Hmm but that change is necessary, after 1.0.0 it didn't actually bind to other ports anymore until that change.

**Comment by thezoggy** [comment]
confirmed that the previous mentioned change is not the culprit..

**Comment by thezoggy** [comment]
tracked it down to the 8.1.2 modification to expose errors from builtin.. before it must have just been suppressed... anyways once I added this to the list of errors it now reacts just like sab 1.1.1 did (doesnt throw traceback,doesnt attempt to respond)
