### ISSUE TITLE
"Unblock" server button throws a TypeError

### ISSUE THREAD

**Issue by enilfodne** [sabnzbd/sabnzbd#864]
### Affected versions

1.2.x - 2.x (maybe earlier)

### Platform

Linux

### Synopsis

When using the ```Gitter``` interface and a server has an issue, the ```Unblock``` button appears to be broken, throwing the following exception:

```
Uncaught TypeError: servername is not a function
    at Object.eval (eval at parseBindingsString ((index):94), <anonymous>:3:145)
    at HTMLAnchorElement.<anonymous> ((index):236)
    at HTMLAnchorElement.dispatch ((index):125)
    at HTMLAnchorElement.r.handle ((index):125)
```

AFAIK the ```servername``` function, specified in the inline JS is missing:

```
<a href="#" data-bind="visible: !serveractive(), click: function() { $parent.unblockServer(servername()) }" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span> Unblock</a>
```

As a future TODO, it may a good idea to move completely, to an event-based system and ditch all the inline JS, as it makes debugging and maintaining the code-base impossible.

**Comment by Safihre** [comment]
Fixed.
>As a future TODO, it may a good idea to move completely, to an event-based system and ditch all the inline JS, as it makes debugging and maintaining the code-base impossible.

I know, but with knockoutJS it just seemed like the right thing to do at the time. I wish I had time to do an overhaul of Glitter in something better, but my focus is on SAB's internals now. 
But we could always use some help, if you're interested!
