### ISSUE TITLE
Restarting because of crashed downloader?

### ISSUE THREAD

**Issue by thegranddesign** [sabnzbd/sabnzbd#867]
My log files are repeating the same thing.

SAB starts up, crashes due to `Restarting because of crashed downloader`, attempts to start back up again, then crashes again.

I have no idea how to debug this.  Nothing changed that I know of.  I may have happened after upgrading to 1.2.1?  Not entirely sure though.

What can I do to figure out what's going on?

**Comment by Safihre** [comment]
We have heard this before but were unable to diagnose it so far. 
What OS are you on? What newsservers? 
Can you switch logging to Debug in the Status window? And then share the log here, from when it starts to when it shuts down. 

Side note: have you tried Sabnzbd 2.0.0 to see if it happens there to?

**Comment by thegranddesign** [comment]
@Safihre I'm on Synology and using the pre-built package [here](https://github.com/SynoCommunity/spksrc/tree/master/spk/sabnzbd).  Let me switch to debug mode (if I can) and see if I can give more info.

My newservers are giganews, astra and tweaknews.

**Comment by thegranddesign** [comment]
@Safihre in my sabnzbd.error.log I'm getting:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/volume2/@appstore/sabnzbd/share/SABnzbd/sabnzbd/downloader.py", line 592, in run
    BPSMeter.do.update(server.id, bytes)
  File "/volume2/@appstore/sabnzbd/share/SABnzbd/sabnzbd/bpsmeter.py", line 247, in update
    if sabnzbd.downloader.Downloader.do and not Downloader.do.paused:
NameError: global name 'Downloader' is not defined
```

**Comment by Safihre** [comment]
Oh man, that's a stupid typo I made right there.. 

You can fix it by temporal disabling quota.

**Comment by thezoggy** [comment]
sounds like we should do a 1.2.3 update with this fix and other fixes?

**Comment by thegranddesign** [comment]
@Safihre thanks for the workaround!  That's what I needed! 😀

**Comment by Safihre** [comment]
I think so yeah.. @shypike, agree? 
There was another fix that should go in there probably, can't remember which one exactly.

**Comment by Safihre** [comment]
Fixed and released.
Will do another update of the 2.0.0 series later.
https://sabnzbd.org/downloads

**Comment by Safihre** [comment]
Changes pushed to `master` and to [SynoCommunity ](https://github.com/SynoCommunity/spksrc/pull/2709).

**Comment by thegranddesign** [comment]
@Safihre your quick response is appreciated as well!! ❤️
