### ISSUE TITLE
Before 2.0.0 ships, shouldn't OpenSSL be updated to 1.0.2K?

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#871]
OpenSSL 1.0.2K was released January 26th 2017:

2017-Jan-26 13:45:54 	openssl-1.0.2k

Wouldn't it be a good idea to include the latest 1.0.2 version to get the most recent security fixes?

1.0.2 is LTS and supported until 31st December 2019

**Comment by Safihre** [comment]
SAB doesn't control the OpenSSL version.
It is the version that ships with Python for macOS and Windows or your system OpenSSL on Linux/NAS/etc.

So only if Python brings a new Windows release we can update it.

**Comment by thezoggy** [comment]
The only way to update ssl is if we compiled python ourselves with a newer ssl.... which i looked into once and didnt want  m to tackle.

2.7.14 is coming eventually... It will include newer openssl

**Comment by Safihre** [comment]
Yeah same for me.. The idea of having the compile it and possible effects of tiny errors. No, I'd rather wait for 2.7.14. If a major major problem is found in OpenSSL, they will probably release it sooner anyway.
