### ISSUE TITLE
sab 2.0.0RC1 -- history no longer works with nzb360

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#872]
noticed after upgrading that nzb360 no longer shows history for sab..

```
2017-03-22 00:13:09,930::DEBUG::[interface:486] API-call from 157.xxx.xxx.162 [??] {'output': [u'json', u'json'], 'apikey': u'xxx', 'mode': u'queue', 'start': u'0'}
2017-03-22 00:13:11,214::DEBUG::[interface:486] API-call from 157.xxx.xxx.162 [??] {'output': [u'json', u'json'], 'apikey': u'xxx', 'limit': u'20', 'mode': u'history', 'start': u'0'}
```

**Comment by thezoggy** [comment]
looking into what it's doing... 
```157.xxx.xxx.162 - - [22/Mar/2017:00:32:47] "GET /api?mode=history&output=json&apikey=xxx&start=0&limit=20&output=json HTTP/1.1" 200 33171 "" ""
2017-03-22 00:32:47,628::INFO::[_cplogging:302] 157.xxx.xxx.162 - - [22/Mar/2017:00:32:47] "GET /api?mode=history&output=json&apikey=xxx&start=0&limit=
20&output=json HTTP/1.1" 200 33171 "" ""```

which ends up generating a `API key missing, please enter the API key from Config->General into your 3rd party program` response..

**Comment by Safihre** [comment]
Yes, we made braking changes to the API (it's in the changelog), that's why we have a version bump from 1 to 2.

There was so much useless stuff in all API calls, it was crazy. Things that made no sense in a `queue` or `history` command. 

Should make an issue with NZB360. 
I already did with Sonarr and they already changed it in the develop version.

**Comment by thezoggy** [comment]
yeah, theres always been a lot of stuff in there.. people kept adding stuff rather than want to send 2 api requests

**Comment by thezoggy** [comment]
> we bump from 1 to 2

I don't see that we've ever versioned our api.. let alone are doing it now. it deff would be nice to do so (mentioned it before in priv emails when we wanted to document the api years ago).. so we can make all the changes we want without breaking things without notice...

**Comment by Safihre** [comment]
No but we version the program. 
There is plenty of notice.

**Comment by thezoggy** [comment]
but we dont with regards from running from git.. as the version is always `develop` which is what others have bitched about.. since well you have no idea if develop means 20 commits ago  when this was fine or what. could just as easily be a git checkout back on 1.0 then never updated.

**Comment by Safihre** [comment]
Yes I agree, we should maybe use a tag like also nzbget does it for the git version: `2.0.0-develop`?
Or is that too late now? 

Indeed probably best to default to skip_dashboard!

**Comment by thezoggy** [comment]
from a 3rd party view point.. they probably dont care what it is.. just as long as it contains some sort of version that they can make logic decisions off of..  now i know sonarr devs want us to do semver if possible.. so it makes it easy to parse and predict.. vs us randomly doing things like `2.0.x` which they then then have to hack in support for...  looking at semver... `2.0.0-develop` actually is valid and would work...

**Comment by Safihre** [comment]
Implemented. Also added the `version` to the `history` call.
Tested with Sonarr and CP, they both don't mind this new notation.
