### ISSUE TITLE
NMA Notification

### ISSUE THREAD

**Issue by plato79** [sabnzbd/sabnzbd#874]
Hi, 

Is it possible to add NMA ( Notify My Android ) notification to sabnzbd? Its' API is well documented as far as I know. You may use the same notification options from the pushbullet I think. While I'm not primarily a python programmer I'm also a programmer so I'll check to see if I could do it myself.

**Comment by Safihre** [comment]
You can use NZB-Notify for this as a Notification-script within SABnzbd, it supports a wide range of services: https://github.com/caronc/nzb-notify
