### ISSUE TITLE
Couple SAB of oddities in one post

### ISSUE THREAD

**Issue by Elfman72** [sabnzbd/sabnzbd#876]
So I'm not sure if this is new or not but I have noticed some odd behavior with SAB.  The changes seemed to start after an update do my Synology (Version DSM 6.1-15047 Update 2).  I run SAB within a Synology Docker using the LinuxServer image hosted [here](https://hub.docker.com/r/linuxserver/sabnzbd/).  I believe this image is built to update to the latest version on Github.

So that means I am running 2.0.0RC1 [3f0b84e] of SAB.  Here are the issues that I am currently seeing:

- In Chrome, when I tab away from SAB, the tab name changes to show HTML Code and I hover over it. I have attached an [image](http://i.imgur.com/F0MSbJQ.png).  For some reason, it seems to be inconsistent because as I write this, it isn't happening.  Clicking it and making it the active tab changes it back to 'SABnzbd' like normal.  It could be related the next issue.

- While investigating this, I was going to click the settings button and was challenged to login again. This never happened previously.  Once logged in, everything operates as normal.  Just strange that I am being asked to log in just to look at the settings.  Never had done that before. Like just now, as I was typing this up, I clicked config, it prompted me to log in again and said that SAB only had uptime of 16m. (see next issue below)

- The SAB config page show inaccurate uptime.  My docker container has been running for about 24 hours yet SAB says that there has only had 2h of uptime and that never seems to change.

- I have been seeing more and more warning messages around SABYenc being not available.  Happens mostly in nzb post processing, obviously, but it seems to be happening a lot more with certain downloads.  Is this something I am needing to get installed to help things a long?  If so, how do I do this using Docker as I am not very well versed in the ways of command line linux?(Same goes for OpenSSL and Python Cryptography)

- Post processing was having plenty of issues and as of recently it never seemed to actually unpack anything properly.  So in my completed folder, I sometimes see nothing but rar files and par2 files.  SAB downloads fine, verifies, attempts to unpapck, throws a warning about the SABYenc module not found as well as a warning of not being able to find rar part from another release and then it moves the release to the History as 'Complete' even though SABConnect++ tells me the download failed.  If I look in the folder it downloaded the files to (/downloads/movies/ in this case) this is where I find the par2 files and .rar files.   I was able to download a different item(not related to this release), just fine but it still is throwing the SABYenc warning even though the file unpacks fine and then moves it to its final folder.  Now these issues could very easily be related to the actual release themselves but up until now, SAB has been absolutely rock solid for me for the years I have used it and is usually able to recover from even the most fragmented release.  So that is why I was motivated to make this post and reach out when I saw so many oddities, warnings and failures one after another.

@Safihre I have sent  you my log file through e-mail(safihre@sabnzbd.org)  I'll reference this issue number to make it easier.  There are a couple of specific releases in there that were more prone to the SABYenc warning messages.  It should be some of the most recent releases in the log file I sent you.

First and foremost, thank you for the time to look into this.  I love this tool and use it daily.  I'm hoping it is just something I can tweak to get fully operational.

**Comment by Safihre** [comment]
Your issues all have 1 cause: something is causing sabnzbd to restart. Only then you get logged out and see the Sabyenc warning. 

The question is what is causing it to do that. Not near a computer right now, so can only inspect your log later to see what it is.

**Comment by Safihre** [comment]
Indeed it's a crashing Downloader, caused by some bad connection handling when there are decoding errors that shouldn't happen normally. 

So two pretty bad bugs when there's no Sabyenc..

**Comment by Safihre** [comment]
@Elfman72 Would it be possible for you to run SABnzbd from the SynoCommunity version?
I always keep the `sabnzbd-testing` package up-to-date within a day.

**Comment by Elfman72** [comment]
Hmm, I will try and see if I can't get that stood up and do a test or two and let you know.  I hope you are able to continue investigation if I unable to do additional testing on the SynoCommunity version.  Let me know how it goes and thanks!

**Comment by thezoggy** [comment]
can you update to latest package (2.0.0 RC2) and see if all is well now?

**Comment by Elfman72** [comment]
Updated and checking now.  Will update once the DL completes(or not if that is the case)

**Comment by Elfman72** [comment]
So it seems SAB did crash once again about three hours ago.  Nothing downloading or post processing or unpacking.

**Comment by Safihre** [comment]
Can you share the logs again? So we can see where it crashed?

**Comment by Elfman72** [comment]
Sent and thanks!

**Comment by Safihre** [comment]
Strange, the log says nothing, it looks like a clean kill from the outside(?)
Very different from before (where it said `Restarting because of crashed downloader`). 
Now the log is just:
```
2017-04-01 12:46:16,992::INFO::[postproc:87] Saving postproc queue
2017-04-01 12:46:16,992::INFO::[__init__:971] Saving data for postproc2.sab in /config/admin/postproc2.sab
2017-04-01 12:46:16,993::INFO::[postproc:831] Queue has finished, launching: None (None)
2017-04-02 00:13:15,914::INFO::[sabnzbdplus:1150] --------------------------------
2017-04-02 00:13:15,949::INFO::[sabnzbdplus:1151] sabnzbdplus-2.0.0RC2 (rev=<HASH>1208efdd83d1872)
2017-04-02 00:13:15,949::INFO::[sabnzbdplus:1152] Full executable path = /usr/bin/sabnzbdplus
```

Are you sure the whole NAS wasn't restarted (update?) or another reason the process could be hard-killed?

**Comment by Safihre** [comment]
Any news on this? It is still happening?

**Comment by Elfman72** [comment]
So I don't think I have seen this issue since the last patch.  So thank you!  One thing additionally, since I am running this in a Docker container, is there any way I can get SABYenc installed?  Is that supported?  I am using the fairly standard linuxserver image.  Just wondering if that is even an option.

**Comment by Safihre** [comment]
Good to hear!  

The latest linuxserver Docker image has Sabyenc integrated. I know nothing about Dockers, but you can probably just update it? 
https://github.com/linuxserver/docker-sabnzbd
