### ISSUE TITLE
Consuming all Memory before auto-killed

### ISSUE THREAD

**Issue by astro7467** [sabnzbd/sabnzbd#877]
Seen on RC 1 also. Not seen on beta. 
Tested on Ubuntu MATE 16.04.2 with 8GB, 16GB and 32GB of RAM. 8GB swap on all CONFIGS. 

[  840.726098] Out of memory: Kill process 2338 (sabnzbdplus) score 974 or sacrifice child
[  840.726148] Killed process 2338 (sabnzbdplus) total-vm:44634208kB, anon-rss:31951492kB, file-rss:0kB, shmem-rss:0kB
[  841.497082] oom_reaper: reaped process 2338 (sabnzbdplus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

Changing top-only = 1 then start_paused = 1 make no difference. 

Queue currently has approximately 396 items (via incomplete directory) - has been higher with previous versions. 

Using jcfp PPA. 

* will check back in about 16hrs to see if any specific data or actions requested. 

Thanks

**Comment by Safihre** [comment]
Are you using SABYenc? And do you have some logs maybe?
If not: could you switch logging to `+Debug` in the Status Window and share the logs? 
If you use the `Show logging` it will anonymize your log.

**Comment by astro7467** [comment]
Yes to SABYenc 
`python-sabyenc/xenial,now 2.8.0-0ubuntu1~jcfp1~xenial amd64 [installed])`
Unable to get to web interface.
Have done the following;
for `/etc/default/sabnzbdplus`:
`EXTRAOPTS="--log-all"`
for `sabnzbd.ini`:
`[logging]`
`log_level = 2`
While monitoring the log for a few restarts, I did see different results before the memory timed out, until I realised during one run it was building and passing an argument with every single password from my password file (which is approx 683MB) - I assumed it was just passing the file as a parameter plus forgotten I had grab this file before to try out when I was running into a lot of passworded file issues
Setting was active for Abort if Passworded - so not sure why it was doing this. I have changed it to Pause if Passworded - which still causes a spike up to about 22GB and the web interface to be come unresponsive - but eventually settles down.
I have subsequently changed `sabnzbd.ini` to point to a different file with just a couple of lines.
Will monitor over the next days to see if there is another trigger as the logs did not produce the same result everytime - but this seems to be a valid candidate and probably an edge case.

[sabnzbd.log.zip](https://github.com/sabnzbd/sabnzbd/files/884278/sabnzbd.log.zip)

*Note I manually had to remove some items such as personal host/domain names, Public IP, email addresses etc

**Comment by sanderjo** [comment]
> from my password file (which is approx 683MB)

That's not a typo? So about 68 million passwords in that file?!

**Comment by Safihre** [comment]
That's indeed a crazy amount. And yes, if it detects a passworded Rar during download it will try all your passwords (starting with the one supplied in the interface, followed by one's from the NZB and then the ones from the password file) on that Rar to see if one of them works. It will stop when it found one that words. Having a 600+MB password file is way way beyond reasonable. 

You can stop this by disabling detection of encrypted files and not setting any Unwanted extensions (that's not the same as Cleanup list!). 

What did you have Logging set to before this? Should be Warnings only.

**Comment by Safihre** [comment]
2017-03-31 09:00:52,996::INFO::[misc:1275] Read 63941068 passwords from file /torrent/sabnzbd/scripts/crackstation-human-only.txt

**Comment by Safihre** [comment]
Do we really need to go and add a check for crazy amounts of passwords? :sweat_smile:

**Comment by Hellowlol** [comment]
Why cant we just change get_all_passwords to a generator? I dont understand why this need to be a list.

**Comment by Safihre** [comment]
Of course we can do that, but it would still take hours to check all these passwords.

**Comment by Hellowlol** [comment]
Still better then me having to manually test all the passwords, that would take year :D

**Comment by astro7467** [comment]
I think a solution would be to either just pass the file (not the content) and have the unrar control step through, or have an option to run a user provided script on password detection to manage the unpack which is recommended for edge cases like this.
Alternatively limit the password file read to X passwords or X kilobytes read (special switch setting, default to 1024?)

**Comment by Safihre** [comment]
> I think a solution would be to either just pass the file (not the content) and have the unrar control step through

The unrar command doesn't have an option to supply a password-file, only a password. So SAB needs to start unrar to test every password, and this is not fast because it needs to start the process and parse the output. 
Even if it takes 1-1.5 seconds, it would take 20-28 **hours** to test all your 60million passwords.

> or have an option to run a user provided script on password detection to manage the unpack which is recommended for edge cases like this.

You can already do this: just disable the encryption check, turn off `Post-process only verified jobs` and use a post-processing script to do the unpacking the way you like.

This edge case is so far off the edge that I don't see the need for another extra special setting.

**Comment by Hellowlol** [comment]
I'm gonna send a pr to make this a generator. We dont need to waist memory.

**Comment by Safihre** [comment]
👍 sounds good!

**Comment by thezoggy** [comment]
this issue made me physically laugh out loud when I read over it.. kudos to brightening my day

**Comment by thezoggy** [comment]
honestly we just need to do something like:

```
with open("pw.txt") as infile:
    for pw in infile:
        do_something_with(pw)
```
thus only reads a line at a time..

**Comment by thezoggy** [comment]
we should not load the list of pw's from the file but instead add an option to the variable passed that there is a pw file.. so we know internally to load said file later on during the unpacker.. that way you dont  make a copy of the pw list for the db and pass it along from function to function

**Comment by Safihre** [comment]
@thezoggy this is not worth the time. The easiest is to turn it into a generator with `yield`, reading and returning only one password at a time.

**Comment by Hellowlol** [comment]
My PR will use @thezoggy way and yield one password at the time.

**Comment by thezoggy** [comment]
Safihre is saying it should done with yield, https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/

which only solves the problem of iterating through the list.. not the workflow of passing the list from one function to the next.. which is what I was pointing out in the previous comment..

**Comment by Hellowlol** [comment]
I didnt notoce anyplaces where its passord from function to function. I just checked the unpacking code. Im browsing on my phone. If i can make it more efficient I will.
