### ISSUE TITLE
Failed downloads not executed when download incomplete

### ISSUE THREAD

**Issue by duramato** [sabnzbd/sabnzbd#878]
When sabnzbd encounters an incomplete download, like this:

![image](https://cloud.githubusercontent.com/assets/10121067/23310981/5b5ab58c-faac-11e6-8aff-5b4ece2b0c8d.png)

It doesn't execute the scripts as a failed download, it doesn't execute the script I have configured at all in this case.

**Comment by Safihre** [comment]
That is default behavior. Why execute a script on a broken thing?
But if you still want to, we have an option for that:
`Process only verified jobs`
https://sabnzbd.org/wiki/configuration/1.2/switches#toc3

Or do you already have that enabled?

**Comment by duramato** [comment]
Becouse in my use case, I want the script to send another nzb as that one failed.
I have that option enabled, so should I just disable it?

**Comment by Safihre** [comment]
Yes you should disable that. And probably Sickbeard/NZBToMedia documentation also says that.
That should do the trick!
