### ISSUE TITLE
sab -- 2.0.0RC2 -- par rename of obfuscation not complete

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#880]
just had sab process something and at the end it only un-obfuscated the .m3u and .mp3 file... the .nfo and .sfv are left obfuscated. d/led the release again in another app with no processing.. can see that if I run the .par2 file that it wants to rename (unobfuscate) all of the files.. 

looking at sab logs.. I see it it renames the file from the hash value to the hash value...
`2017-03-30 02:38:59,762::DEBUG::[misc:916] Moving. Old path: \\?\C:\Users\<USERNAME>\downloads\incomplete\Ultra_Music_Festival_2017_-_Sl\<HASH>de29.51d New path: \\?\C:\Users\<USERNAME>\downloads\complete\music\_UNPACK_Ultra_Music_Festival_2017_-_Sl<removed>\<HASH>de29.51d Overwrite: 0`

sent email with more details and fix..

**Comment by Safihre** [comment]
It's not a bug at all, it's a feature. This way QuickCheck will not fail in case of broken sfv/srr/nfo files, if those are the only broken ones. 

If you don't like it, just remove those extensions from the Special setting.

**Comment by thezoggy** [comment]
config > special > `quick_check_ext_ignore (  )` per that, the default would be nothing.. but `nfo, sfv, srr` is currently populated...
wiki has nothing about this option,
https://sabnzbd.org/wiki/configuration/2.0/special

so i guess you just recently added it, which is why ive seen this abnormal behavior... and imho it seems like a bad thing because post extracting we cleanup the pars.. thus to rename the files after the fact is harder to do.. let alone your left with obfuscated files that most likely wont get pp correctly with 3rd party apps because they dont match the media filenames or have valid extension types.

**Comment by Safihre** [comment]
It's new, I just forgot to create the wiki..

**Comment by thezoggy** [comment]
the config special page does not show the correct 'default' for the option or if you change the default
