### ISSUE TITLE
[2.0.0RC2] 100% cpu usage when downloading

### ISSUE THREAD

**Issue by peatnik** [sabnzbd/sabnzbd#881]
sab: 2.0.0RC2 [afd1b19]
sabyenc: 2.8.0

when downloading with this version, cpu usage is at 100% even though download speed is currently at 100 kB/s. i am also not getting the speeds i used to but that may be unrelated (no more than 150mbps when it used to be 600+mbps).
restarting sabnzbd does not help.

**Comment by Safihre** [comment]
First try a real Ubuntu iso, what you describe sounds more like missing articles. 

What OS? 

Maybe switch logging to Debug in the Status window if that doesn't help and share the log here (it will be anonomyzed if you click Show Logging).

**Comment by peatnik** [comment]
os is archlinux.

i don't think it's missing articles because i have tried many different nzbs. the downloads also complete without any issue and show at most a couple of malformed articles.

i will activate debug logging.

**Comment by Safihre** [comment]
When you are trying: what happens when you remove Sabyenc? Then it reverts back to the 1.2.x behavior. 

Alternatively, try an older version from our website and see if that makes a difference.

**Comment by peatnik** [comment]
Removing sabyenc made no difference.

But i noticed something strange:
When i "force" a file that i am certain would download with full speed, download speed stays relatively low (~100 mbit). but as soon as i pause downloading so that only the forced download remains, speed will rocket up. the other downloads are dragging down the speed.
The switch "only fetch articles for top of the queue" fixes that particular problem but obviously kills the overall speed if there are missing articles.
so right now i seem to have the choice between a somewhat steady but slow speed or a high max speed with collapses along the way.

**Comment by sanderjo** [comment]
@peatnik 

> download speed is currently at 100 kB/s.

Is that a typo?

> Removing sabyenc made no difference.

What if you run SABnzbd 1.2.3?

Furthermore: at high CPU load, what does `htop` show?

**Comment by peatnik** [comment]
@sanderjo 
> Furthermore: at high CPU load, what does htop show?

![2017-04-01 13_05_37-0_2 1 ssh](https://cloud.githubusercontent.com/assets/26791404/24578205/0420c3f0-16dc-11e7-9898-9903b1824633.png)

> *kB/s." ... s that a typo?  

no, but that speed is expected for that file. it's just missing on most providers and sabnzbd is falling back to a rarely used provider that only allows a couple of connections.

> What if you run SABnzbd 1.2.3?

i might have to come back to that but i remember upgrading precisely because many slow downloads could completely choke sabnzbd to a halt i.e. 0 kB/s, forcing me to do a sabnzbd restart.
as a positive side effect, 2.0.0Alpha1 through Beta1 improved my speeds from ~60 MB/s on fully available files to 100 MB/s. i haven't seen those speeds in a while though, even though i am using both RC2 and Beta1 on two different machines. The source might be external, e.g. a kernel upgrade since both systems seem to have slowed around the same time, a couple of days ago.
I will have to do more digging and report back. If you have any ideas let me know.

Thanks for the responses so far.

**Comment by Safihre** [comment]
In that case, what if you just try 2.0.0Beta1 again? It's on the downloads page. 
The matching Sabyenc will be available from `pip`.

**Comment by peatnik** [comment]
as i said, i am currently using RC2 and Beta1 on two different machines that are both experiencing this issue. I had upgraded to sabyenc 2.8.0 on the Beta1 client, so i downgraded it to 2.7.0 but nothing changed. 
1 download = ~40 MB/s
2 downloads ~10 MB/s

for reference, here's what it looked like when Alpha1 was released:
![2017-03-10 07_21_59-88 4 mb_s - 20 5 gb left - sabnzbd](https://cloud.githubusercontent.com/assets/26791404/24579073/65715b08-16ee-11e7-8974-4fd4d9ae3483.png)

so i will try alpha1 again when i get the time. what version of sabyenc should i use with it?

**Comment by Safihre** [comment]
2.7.0 Sabyenc for the previous releases before RC2. 

If you have logs to share maybe it can help?

**Comment by peatnik** [comment]
I looked at the debug logs and didn't see anything out of the ordinary. Hold on.

**Comment by Safihre** [comment]
Can send it to bugs@sabnzbd.org. Might be nothing but worth a look..

**Comment by sanderjo** [comment]
> P.S.: is 100% cpu usage (1 core) to be expected with 1 download on a 10.000 passmark cpu? i still haven't solved that issue which might or might not be related to the speed issue.

Depends on your CPU. Check the lines in sabnzbd.log with "CPU" in them, and those two lines here.

Mine:

```
2017-04-01 21:35:20,061::DEBUG::[sabnzbdplus:1205] CPU Pystone available performance is 72484
2017-04-01 21:35:20,061::DEBUG::[sabnzbdplus:1210] CPU model name is Intel(R) Xeon(R) CPU E5335 @ 2.00GHz
```

**Comment by peatnik** [comment]
> Intel(R) Xeon(R) CPU E5335 @ 2.00GHz

i have an Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz which has more than double single core speed and 4x overall speed so if you are not seeing 100% single core utilization then i don't think i should be either.

**Comment by sanderjo** [comment]
At a SAB download speed of  12 MB/s, SAB causes a 98% CPU load.

So if you get 80 - 115 MB/s (like you posted), 100% CPU load is OK and normal.
Remember: that is the load on **one** core. Your other 3 cores can be at low usage.

**Comment by peatnik** [comment]
@sanderjo what's curious to me is that i am seeing 100% cpu usage regardless of the download speed. be it 1 MB/s, 10 MB/s or 100 MB/s. maybe it's more about the open connections because that is usually constant at about 50.

**Comment by thezoggy** [comment]
what process is at 100% something else stuck in the background? sab (python)? par2? rar? etc

**Comment by peatnik** [comment]
@thezoggy see https://github.com/sabnzbd/sabnzbd/issues/881#issuecomment-290913817

**Comment by thezoggy** [comment]
show the process tree.. curious to know if its really sab or something sab spawns.. 
`ps f -g<PID>` or `pstree`

**Comment by peatnik** [comment]
![2017-04-02 08_44_37-0_2 2 ssh](https://cloud.githubusercontent.com/assets/26791404/24585018/dde8a162-1780-11e7-9d11-66cfa517cc7b.png)
![2017-04-02 08_45_53-0_2 2 ssh](https://cloud.githubusercontent.com/assets/26791404/24585019/e06e8d98-1780-11e7-9f18-366108230def.png)

Also, Alpha1 shows the same behaviour. I am at my wits end. Since I do at least get a steady 10 out of 100 MB/s, i'll just give it  a rest for a while. maybe a future system or sabnzbd update will fix the issue.

**Comment by Safihre** [comment]
Any change?

**Comment by peatnik** [comment]
I don't think so but then again, I haven't really changed the sabnzbd configuration. I still don't see speeds above 50-60 MiB/s anymore.
But I have already updated my to-do list for this weekend with trying out the official 2.0 release with the accompanying sabyenc release.

Part of the problem is that it is hard to pinpoint the problem. It might not be sabnzbd. It could be any link in the chain of providers I am using, e.g. usenet, server or internet service provider.
Since time solves a lot of computing problems I was hoping by changing nothing at sabnzbd i could rule it out as the cause but so far no luck.

Also kudos for actually remembering to check on this ticket, I promise I will report here when I notice any significant change for the worse or the better.

**Comment by peatnik** [comment]
I just did more tests and I am no closer to enlightenment.

Machine 1 and Machine 2 are identical in hardware and network connection. Software configuration should be identical, too but it's not an exact mirror.
Same nzb used for all tests, 15 ssl connections to a highwinds provider.
Machine 1:
* sabnzbd: 5 MB/s
* nzbget: 12 MB/s
Machine 2:
* sabnzbd: 25 MB/s
* nzbget: 30 MB/s

Now the same with 30 connections.
Machine 1:
* sabnzbd: 7 MB/s
* nzbget: 20 MB/s
Machine 2:
* sabnzbd: 50 MB/s
* nzbget: 50 MB/s

Now using 3 different USPs with 20 connections each:
Machine 1:
sabnzbd: 22 MB/s
nzbget: 68 MB/s (with peaks to 100)
Machine 2:
sabnzbd: 80 MB/s
nzbget: 45 MB/s (peak to 80 at beginning)


I can't really make sense of these measurements. It seems as though sabnzbd is not the culprit, since Machine 1 and Machine 2 use the exact same RC2 sabnzbd version and configuration with sabyenc 2.8.0.

I am still curious why I am not seeing 100 MB/s on either machine like i used to.

**Comment by thezoggy** [comment]
first off get a good base line.. use dd and benchmark the hdd.. use iperf2/iperf3 to benchmark the network from machine to machine.. figure out if you have issues like nic drivers/bad cabling/etc

**Comment by peatnik** [comment]
I am now on the official 2.0 release with sabyenc 3.0.2.
By now I have to activate the switch to "only grab articles for top of the queue". It makes a huge difference. Without the activated switch, i get ~2-3 MB/s on the slow machine. With activated switch is 20-30 MB/s.
What do you think causes that phenomenon?

**Comment by thezoggy** [comment]
do you have multiple usenet service providers setup in sab? set to different priorities with high # of connections?

**Comment by peatnik** [comment]
I guess so:
* priority 10, 15 connections, provider a
* prio 10, 20 cons, provider b
* prio 10, 15 cons, provider c
* prio 14, 5 cons, provider a, alternate server 1
* prio 15, 5 cons, provider a, alternate server 2
* prio 30, 12 cons, provider d
* prio 30, 25 cons, provider e
* prio 30, 15 cons, provider f
* prio 40, 5 cons, provider g

Though it is very rare to see connections beyond the top 3.

**Comment by thezoggy** [comment]
the more connections = more cpu. and if your trying to fetch articles for multiple jobs.. and the jobs have articles missing/failed.. will cause more providers in your list to be used.. etc etc.

**Comment by Safihre** [comment]
So.. what is happening with this issue? It seems not to be really a SABnzbd problem if I understand the last posts correctly?

**Comment by peatnik** [comment]
I actually switched my main usp to another highwinds which i thought might help. but no dice.
The only thing left for me to do is actually change isp, including hardware, which i wanted to do anyway for various reasons. but it might be july before i get around to that because my setup is not yet migration ready and i am somewhat busy of late.

so it's your call. since this issue hasn't been about RC2 or 100% cpu usage for a while, it might be be best to close it here. i could open a new one when i find the time to migrate hardware and reexamine download speeds. you can also just leave this open and i will report my findings here but it might take me a while.

**Comment by Safihre** [comment]
Feel free to re-open when you find it's a SAB problem 👍

**Comment by peatnik** [comment]
Thanks!
Whatever you did in 2.0.1 fixed the issues for me!

I'm back to 95+ MB/s and i can disable the "only fetch articles for top of queue" option again as big queues with many missing articles don't make download speed slow down to a crawl anymore.

**Comment by Safihre** [comment]
:+1: :)
