### ISSUE TITLE
No CPU reported on Nano Pi Neo 2 (ARM64) running Armbian Linux

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#882]
On my 64-bit ARM (NanoPi NEO2) running Armbian Linux, SAB is not reporting the CPU type.
Cause: /proc/cpuinfo  does not contain "model name", which sabnzbd/utils/getperformance.py searches for.
I don't know if this is something specific for Armbian, or ARM64, or Linux 4.10.
Workaround: sabnzbd/utils/getperformance.py could get the info the line starting with "Hardware". That would yield "sun50iw1p1" ... which is quite ugly, but gives the unique identification.

Any relevant feedback?

```
$ cat /proc/cpuinfo 
processor	: 0
Processor	: AArch64 Processor rev 4 (aarch64)
Hardware	: sun50iw1p1
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

```
            for myline in open("/proc/cpuinfo"):
                if myline.startswith(('model name')):
                    # Typical line:
                    # model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
                    cputype = myline.split(":", 1)[1]	# get everything after the first ":"
                    break # we're done
```

**Comment by Safihre** [comment]
Sure, just add another `if` to the for loop looking for that text, but without the `break`. 
This way the model always takes precedence but there is a fallback in case it doesn't appear.

**Comment by thezoggy** [comment]
want a test set of cpuinfo outputs?
https://github.com/randombit/cpuinfo

**Comment by sanderjo** [comment]
> want a test set of cpuinfo outputs? https://github.com/randombit/cpuinfo

Wow. That's quite an overview. Thank you.

From that list:

```
sander@flappie:~/git/cpuinfo$ cat arm/arm.004
Processor       : Intel StrongARM-1110 rev 8 (v4l)
BogoMIPS        : 147.04
Features        : swp half 26bit fastmult
CPU implementor : 0x69
CPU architecture: 4
CPU variant     : 0x0
CPU part        : 0xb11
CPU revision    : 8
Hardware        : Intel-Assabet
Revision        : 0000
Serial          : 0000000000000000
```
hmmm ... not Hardware is relevant, but Processor.

```
sander@flappie:~/git/cpuinfo$ cat arm/pi2 | grep -i -e "hardware *:" -e "model name" -e "cpu model" -e processor
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
Hardware        : BCM2709
```
And in this case Hardware is the most relevant.

TBC ...

**Comment by Safihre** [comment]
@sanderjo, that's probably why the python-cpuinfo package is so big: https://github.com/workhorsy/py-cpuinfo/blob/master/cpuinfo/cpuinfo.py

There's many more platforms ;)

**Comment by sanderjo** [comment]
I had already tried cpuinfo ... and it doesn't even work on my Aarch4 ... So: Arch! (pun intended)
```
sander@nanopineo2:~$ python -c "import cpuinfo; print cpuinfo.get_cpu_info()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/__init__.py", line 5, in <module>
    from cpuinfo import *
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 1584, in <module>
    _check_arch()
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 1541, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.
```

**Comment by sanderjo** [comment]
This could be a last resort:
```
sander@nanopineo2:~$ python -c "import platform; print platform.platform()" 
Linux-4.10.0-sun50iw2-aarch64-with-Ubuntu-16.04-xenial

sander@nanopineo2:~$ python -c "import platform; print platform.uname()" 
('Linux', 'nanopineo2', '4.10.0-sun50iw2', '#27 SMP Sun Apr 2 03:44:08 CEST 2017', 'aarch64', 'aarch64')
```

**Comment by sanderjo** [comment]
I had a look at the example files referenced to by @thezoggy ... and I see no pattern; all kinds of key names in /proc/cpuinfo.

So I implemented the platform.platform() method. Just two lines of code, and works on all CPU's. In other words: KISS.

Result:
![sabnzbd cpu info](https://cloud.githubusercontent.com/assets/1273502/24678856/89f73696-198c-11e7-9bc1-80a1e2bbe979.png)
So: all system info. Enough and clear enough for analysis.

@Safihre is this OK for you?

**Comment by Safihre** [comment]
Ok for me! If there's no pattern there's only so much we can do.. 
And this would be a fallback, right? In case procinfo doesn't have the info?

**Comment by sanderjo** [comment]
> And this would be a fallback, right? 

Yes ...

> In case procinfo doesn't have the info?

... well ... if the current methods in getperformance.getcpu() can't find any info. On Linux that means: no 'model name' in /proc/cpuinfo, which means non-X86/X86-64, so ARM or MIPS or SPARC or ... :-)
