### ISSUE TITLE
rar and par2 filenames are randomly shortened in tmp folder

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#883]
>2.0.0RC2 [afd1b19]

If I check the tmp files folder for some failed download I see randomly shortened filenames.
The files have sometime extension like .r .ra .vol0 or even shorter.
The nzb has the right file names and after a restart the files have cuts at an other filename position.

**Comment by Safihre** [comment]
What do you have set in Config Specials for folder_max_length?

**Comment by ggzengel** [comment]
Still 256 chars and never changed since years.
The full pathname for these files is 157 chars.

**Comment by Safihre** [comment]
I have looked at the code and can not find a reason why Sab would do this. 
Do you maybe have Info or Debug level logs of such downloads? Are you sure this is not just the way the files are?

**Comment by ggzengel** [comment]
With every new download the files have other length.
Before 2.0.0 I haven't seen this.

**Comment by ggzengel** [comment]
I had a look into the nzo file.
For the good rar files I found them three times with full name.
For the shortened ones I found it two times with full name and one time shortened.

**Comment by Safihre** [comment]
If you could share a log here or with bugs@sabnzbd.org? Thanks!

**Comment by Safihre** [comment]
Actually I think I know why it happens. It's a `sabyenc` thing.
Does the download succeed in the end?

**Comment by ggzengel** [comment]
No. All files have different sizes and repair won't work.

**Comment by thezoggy** [comment]
dont we shorten the files by design in the temp folder so we dont run into extracting issues...  the temp folder shouldnt matter.. what does is the final completed/incomplete folder

**Comment by Safihre** [comment]
No we don't shorten the filename at any point, only the folder name. 
It's a bug in `sabyenc` where the filename is split over 2 chunks. The chunks can be any length and that's why he sees different filenames every time. 
Working on a solution. Same thing happens with for example the CRC code in the footer of the yEnc article, which I also worked around.

**Comment by Safihre** [comment]
Fixed it in `sabyenc` 3.0.0, I think.
Will release another RC today to test.

**Comment by ggzengel** [comment]
I get this:

```
root@sabnzbd:~# pip install sabyenc --upgrade
Downloading/unpacking sabyenc from https://pypi.python.org/packages/bf/48/00c3aa1ec9785664585a52418a6b856fa032bbe2fa885d8e800ee7741651/sabyenc-3.0.1.tar.gz#md5=75b8b34c0a2a002c0ca0461e1fc5b4db
  Downloading sabyenc-3.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-dPyxMg/sabyenc/setup.py) egg_info for package sabyenc
    
Installing collected packages: sabyenc
  Found existing installation: sabyenc 2.8.0
    Uninstalling sabyenc:
      Successfully uninstalled sabyenc
  Running setup.py install for sabyenc
    building 'sabyenc' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/sabyenc.c -o build/temp.linux-x86_64-2.7/src/sabyenc.o -O2
    src/sabyenc.c:22:21: fatal error: sabyenc.h: No such file or directory
     #include "sabyenc.h"
                         ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-dPyxMg/sabyenc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-u4jjI1-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

building 'sabyenc' extension

creating build

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/sabyenc.c -o build/temp.linux-x86_64-2.7/src/sabyenc.o -O2

src/sabyenc.c:22:21: fatal error: sabyenc.h: No such file or directory

 #include "sabyenc.h"

                     ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of sabyenc
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-dPyxMg/sabyenc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-u4jjI1-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-dPyxMg/sabyenc
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by Safihre** [comment]
Oops, will fix that.

**Comment by Safihre** [comment]
@ggzengel Should be fixed now!

**Comment by ggzengel** [comment]
It's working now. Thanks.

After updating to RC3 sabnzbd didn't start anymore and there was no log about any issues.
After installing sabyenc 3.0.2 it started again.
