### ISSUE TITLE
SABNZBd logs 127.0.0.1 as remote IP when behind reverse proxy

### ISSUE THREAD

**Issue by andofrjando** [sabnzbd/sabnzbd#884]
I have SABNZBd running behind an Nginx reverse proxy, where the headers are configured like so:
```
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;
```

When I make calls to the API with an incorrect API key from a remote machine, SAB logs the following:
```
2017-04-04 12:02:59,605::DEBUG::[interface:421] API-call from 127.0.0.1 [curl/7.51.0] {}
2017-04-04 12:02:59,606::WARNING::[interface:190] API Key missing, please enter the api key from Config->General into your 3rd party program: 127.0.0.1>curl/7.51.0
```

It seems Sab is ignoring the X-Forwarded-For header when logging events.

Running SABnzbd Version: 0.7.20 on Ubuntu 16:04 and nginx/1.10.0 (Ubuntu), and Installed from Distro repository.

**Comment by albino1** [comment]
0.7.20 is almost 3 years old, dozens of updates behind, and before at least one complete overhaul.  The first thing you should do is upgrade.

**Comment by andofrjando** [comment]
Wow, I didn't know the repo versions were so out of date. 
Anyway, now running `SABnzbd Version: 2.0.0-develop` from GitHub.

Still get the same address in the log files:
```
2017-04-04 13:46:00,170::DEBUG::[interface:486] API-call from 127.0.0.1 [curl/7.51.0] {}
2017-04-04 13:46:00,171::WARNING::[interface:261] API Key missing, please enter the api key from Config->General into your 3rd party program: 127.0.0.1>curl/7.51.0
```

**Comment by Safihre** [comment]
Have to look into this, how Cherrypy handles that. Will report back!

**Comment by sanderjo** [comment]
> Wow, I didn't know the repo versions were so out of date.
> Anyway, now running SABnzbd Version: 2.0.0-develop from GitHub.

Github is good, but the PPA for Sabnzbd is easier for Ubuntu users.

**Comment by Safihre** [comment]
I will add an additional line of logging instead of just overwriting the IP if a `X-Forwarded-For` header is found, because otherwise an 'attacker' could just provide malicious `X-Forwarded-For` headers and we would never know where it comes from!
