### ISSUE TITLE
[Feature Request] Calculate extraction speed in MB/s

### ISSUE THREAD

**Issue by skaforey** [sabnzbd/sabnzbd#889]
I really like being able to see how fast something downloaded, but I'm also curious to see the extraction speed.  I know it can be roughly calculated since we know the approximate donwload size as well as how long it took, so maybe going one step further and calculating extraction speed in MB/s might be nice.

**Comment by Hellowlol** [comment]
Is this while is unpacking or inside the dropdown in the history tab?

**Comment by Safihre** [comment]
Personally I don't see the need for this at all..

**Comment by thezoggy** [comment]
same... if you really want to do analytics on your sab stuff you prob could just pull said info from your sab `history1.db`...

we use sqlite format.. can query the db and get whatever info you want.. so maybe something like:
`select nzb_name, bytes, time(postproc_time, 'unixepoch') as postproc_time, ((bytes/1024/1024)/postproc_time) || " MB/s" as postproc_speed from history where bytes > 1 and postproc_time > 1 order by postproc_speed desc,bytes`

**Comment by skaforey** [comment]
There is no "need" for it, I just thought it would be nice. 

Again, since we already have the data we need, why not at least make it optional?

**Comment by thezoggy** [comment]
rather focus time and energy on things that appeal to more than 1% of userbase.. also not work on stuff that may cause more questions than answers..

**Comment by Safihre** [comment]
Postproc_time has the time of the whole processing, not just unpack..

**Comment by Hellowlol** [comment]
So history unpack time isnt correct?

**Comment by Safihre** [comment]
It is, but it just isn't saved anywhere as a numeric value after it's done. 
Only in that line `Unpacked 1 files/folders in 7 seconds`.

**Comment by Hellowlol** [comment]
Ok, when i was reading the request i just assumed the user wanted the unpacking speed added to the same text

````Unpacked 1 files/folders in 7 seconds. 1337 MB/s````

**Comment by Safihre** [comment]
We could so it there, but I think it won't really be accurate. Because it also counts the time to start the unrar and I don't think we know the exact size of what we are unpacking

**Comment by skaforey** [comment]
I tried looking at the code a bit to try and do it myself, but I don't know where I can make the modification.  I understand it may be a feature that might not be wanted by everyone, so I figure I can just code it myself.  I don't need it to be an exact speed, I'm just more curious to see the performance of my NAS and how it changes with different sizes and as it gets more full.  If anyone has any pointers on where I can start to make the mods, I'd be happy to do it myself.

**Comment by thezoggy** [comment]
There are disk io scripts to test your nas/PC... Probably better suited than code your own inside Sab don't you think?

**Comment by skaforey** [comment]
I am aware of tests, this is a nice way for real world examples to see (tests != real world all the time).  This would simply be a nice easy, visual way to see the stats at a glance.  I didn't think it would be that big of a deal to make the request, but apparently it's not something that you guys want to add, so I'll just figure it out, and add it to my own build.

**Comment by Safihre** [comment]
Oke sure, change the lines to say this:
```python
    logging.debug('UNRAR output %s', '\n'.join(lines))
    nzo.fail_msg = ''
## NEW LINES
    unpackMBs = (nzo.bytes/1024/1024)/(time() - start)
    msg = T('Unpacked %s files/folders in %s at %.2f MB/s') % (str(len(extracted)), format_time_string(time() - start), unpackMBs)
## END
    nzo.set_unpack_info('Unpack', '[%s] %s' % (unicoder(setname), msg), set=setname)
    logging.info('%s', msg)
```
