### ISSUE TITLE
sab 2.x -- rss/notification notes

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#892]
went to go update the disk full template and forgot it was integrated to sab not an actual 'template' file.. which made me stumble upon some things that need to be fixed.

template files themselves have old invalid wiki link:
`## Documentation: http://sabnzbd.wikidot.com/email-templates`
should point to `https://sabnzbd.org/wiki/extra/email-templates` (or versioned url for 2.x -- read below)

sab webui related:
* "Send RSS notifications" does not trigger when you manually click 'download' only when it auto does it.. needs to be clarified on sab's config page.. otherwise you think its broken/hard to 'test' 

https://sabnzbd.org/wiki/extra/email-templates related:
several variables are missing/outdated.. this whole page needs to be slightly refactored to accommodate the fact that there are 3 type of template groups (email / rss / badfetch) and each group has its own variables.

Perhaps we should version this file (once we fix it.. since these variables havent really changed in 7 years), version it 2.x so we can drop the whole 0.7.0+ mention.. and also take the time to fix things and change stuff if we want going forward).

The table is misleading because you think this table works for all templates.. because of the vague 'use in the email'. Each template group has its own variables and should be broken into their own tables to make it clear..  with a little summary about what each one is for instead of it being after the list.. 

about **email-** (main table) it has some stuff missing/outdated:

* mentions `$output` which doesnt exist.. looks like it should actually be `$stages`
> then beneath it mentions `name` and `actions` which isn't really correct because the user can define whatever they want when they break the dict apart.. 
in our templates we do 'for stage in stages' thus 'stage' not 'for actions in stage'
* missing `$path` and `$script_ret`
> added path and confirmed that its spitting out `\\?\` notation
ex: `\\?\C:\test\downloads\complete\music\blahblahblah`

the 3 groups based on filename grouping contain these variables:
- email-*: the table with the above corrections.
- rss-*: $amount, $feed, $jobs
- badfetch-*: $url, $msg

i know you generally have done the wiki stuff, why I'm posting it here..  let me know if you want me to submit anything. putting these notes here so I dont forget since I'm about to have to get off the comp to go make dinner/run errands.

**Comment by Safihre** [comment]
Yes please submit a PR for this and for the wiki! The text is probably vastly outdated indeed. 

It also doesn't explain (as was pointed out by a tester) that when you want to make changes to a template you need to copy *all* the template files for all languages, not just the ones or language you want to change. Otherwise it stops working or starts sending too many notifications (one for each language).

**Comment by Safihre** [comment]
@thezoggy What else needs to be updated? Now that we updated the wiki?

**Comment by thezoggy** [comment]
well i still wanted to version the file so we could change stuff going forward and not break stuff for legacy..  but havent gotten around to updating the template/making new ones to know what i want to change

**Comment by Safihre** [comment]
@thezoggy ping 😉
