### ISSUE TITLE
Download completed when RAR extract failed

### ISSUE THREAD

**Issue by Ninjouz** [sabnzbd/sabnzbd#896]
Hey guys,

Since the upgrade to 2.0, I've got some download errors like the following but Sabnzbd still report them as successful : 

```
Name Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR
Completed 14/04/2017 16:10
Status Completed
Size 4.9 GB
Categor ysonarr
Path /usenet/series_sonarr/Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR
Source Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR.nzb
Download Downloaded in 11 mins 23 seconds at an average of 7.3 MB/s
Age: 1846d
116 articles were missing
Repair Trying RAR-based verification
[Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR.part01.rar] RAR-based verification failed: Not a RAR file
Unpack [Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR][/usenet/Incomplete/Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR/Game.of.Thrones.S01E05.1080p.BluRay.DTS.x264-ESiR.part01.rar] Unusable RAR file
```

I went to do a manuel par2repair and rar extract with no issues tho.

I dont know why it didn't go through the par2 check / repair ?

**Comment by Safihre** [comment]
Set logging to Debug in the Status window, then when a download fails, check the logs and see what it says for Par2 output. 
Probably some bug in par2.

**Comment by Safihre** [comment]
Regarding the still labeling it successful: you probably have in Config > Switches,  'Post process only verified jobs' turned off.

**Comment by Ninjouz** [comment]
Yeah, i turned it off when using nzbToMedia pp scripts to notify SickRage.
But then I didn't get those issues.
I recently moved to Sonarr / Radarr that query the history endpoint so i just turned it back on.

I've set my sab to debug and will report if something's broken again.

Thanks

**Comment by Safihre** [comment]
Additional question: what OS are you on?

**Comment by Ninjouz** [comment]
Ubuntu 15.10, planning to release upgrade to latest 16.04.

**Comment by Safihre** [comment]
@Ninjouz Any news on this? Do you have debug-logs for us?

**Comment by Ninjouz** [comment]
Hey Safihre,

Ever since turning on the  'Post process only verified jobs', I never got the issue back.
So I guess I cant help you more on this.

**Comment by Safihre** [comment]
Sounds like it's fixed to me :)
