### ISSUE TITLE
urlgrabber crash

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#897]
On start-up running latest dev on win 10 with python 2.7.13

```
2017-04-15 18:24:38,871::ERROR::[urlgrabber:271] URLGRABBER CRASHED
Traceback (most recent call last):
  File "H:\usr\local\sabnzbd\sabnzbd\urlgrabber.py", line 229, in run
    f = open(path, 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\Users\\USER\\AppData\\Local\\sabnzbd\\admin\\future\\CSI.NY.S07E16.1080p.BluRay.x264-TENEIGHTY\t.nzb.gz'
```

**Comment by thezoggy** [comment]
make sure sab has permissions to write to that protected user folder or move the admin folder out of it

**Comment by Safihre** [comment]
Seems more like Sab is expecting a file from before the restart. Since this is on Windows, permissions should be fine. 
Maybe something in the restart of Sab during an url gran is not handled well.

**Comment by labrys** [comment]
@thezoggy doubt its permissions issue as I have over 3k items in my queue and only this one caused an issue

What strikes me as odd is the `\t` in the filename:

`C:\\Users\\USER\\AppData\\Local\\sabnzbd\\admin\\future\\CSI.NY.S07E16.1080p.BluRay.x264-TENEIGHTY\t.nzb.gz`

**Comment by labrys** [comment]
Just confirmed:

```python
>>> with open('h:\\test \t file.txt', 'w') as p:
	pass


Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    with open('h:\\test \t file.txt', 'w') as p:
IOError: [Errno 22] invalid mode ('w') or filename: 'h:\\test \t file.txt'
```

**Comment by sanderjo** [comment]
No problem on Linux.

So \t (aka TAB) apparently is illegal in file names on Windows. https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations and https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits conform that for FAT.

Is your H: FAT, or NTFS, or ... ?

Allowed on recent FAT:
```
SFN: OEM A-Z, 0-9, ! # $ % & ' ( ) - @ ^ _ ` { } ~, 0x80-0xFF, 0x20. LFN: Unicode except NUL, " * / : < > ? \ |
```

```
sander@Streamer13:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> with open('test \t file.txt', 'w') as p:
...     pass
... 
>>> 
```

**Comment by labrys** [comment]
Win 10 NTFS.

**Comment by thezoggy** [comment]
What indexer served up a tab character as part of the filename?

**Comment by Safihre** [comment]
@labrys do your jobs come from RSS feeds? Maybe it's a parsing problem of the RSS parser.

**Comment by labrys** [comment]
@Safihre nope, don't use any RSS feeds
@thezoggy Just checked my snatch history in Medusa's manual snatch - looks like the TENEIGHTY release was from DOGnzb - just confirmed it with a manual snatch and got the same error.

**Comment by thezoggy** [comment]
just tried to grab the nzb from dog.. `CSI.NY.S07E16.1080p.BluRay.x264-TENEIGHTY_.nzb` no tab character.. 
looking at the nzb contents.. the META field has the tab..
`<meta type="name">CSI.NY.S07E16.1080p.BluRay.x264-TENEIGHTY	</meta>`

**Comment by labrys** [comment]
So can I assume that SAB is getting the name from the META field?  AFAIK Medusa (and other SickBeard derivatives) pass the nzb url (when not using blackhole ofc)

**Comment by Safihre** [comment]
No we don't use the meta field, but it probably means that dog did not filter it when sending the URL.

In any case: we need to filter tab-chars out on Windows in our `sanitize_filename` function!

**Comment by Safihre** [comment]
Actually I see we do use the meta header-field `x-dnzb-name`, @thezoggy was right,
Filtering it out now.
