### ISSUE TITLE
API fails with localhost

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#899]
API will only respond with `API Key Incorrect` when accessed via localhost or 127.0.0.1.  Accessing via IP or domain name works as expected.

**Comment by labrys** [comment]
Using `0.0.0.0` for host works.

**Comment by thezoggy** [comment]
or if no key is passed or if api key disabled etc etc.. need to provide output of what your trying to do if you want us to confirm if its an issue vs just user error

**Comment by labrys** [comment]
Was reinstalling CP and I set host to `localhost:8080` with correct API key.  My sab was configured with the hostname as the host.  Using `hostname:8080` in CP worked but `127.0.0.1:8080` or `localhost:8080` did not.  I closed the issue since changing host in sab to `0.0.0.0` allowed both `localhost:8080` and `hostname:8080`.
