### ISSUE TITLE
Tab bar in Chrome

### ISSUE THREAD

**Issue by schabau** [sabnzbd/sabnzbd#901]
Hello,

The SABnzbd-Forum still does not work, so I say again here what problem I have.
I just switched from IE to Chrome and have seen that under Chrome in the Tab bar no information like speed and download time of SABnzbd are output.
Can this be added in a next version?

Best regards

![ie](https://cloud.githubusercontent.com/assets/25462758/25088514/1c5425fa-2377-11e7-8e25-c16d6d44efcd.jpg)
![chrome](https://cloud.githubusercontent.com/assets/25462758/25088520/212bcf56-2377-11e7-9868-3d3438bcf184.jpg)

**Comment by Safihre** [comment]
What is wrong with the forum? 
The tab will only display something when you are actually downloading something.

**Comment by Safihre** [comment]
This also differs between skins, seems before you might be using Plush while in second screenshot it seems to be Glitter or the Login page.

**Comment by schabau** [comment]
The first screenshot was made by IE and the second by Chrome. Each without special skins.

**Comment by schabau** [comment]
And, when registering with a new email address as well as if you forgot your password you get no email.

**Comment by schabau** [comment]
This is also clear to me, that the download speed and the remaining time is displayed only with active downloads.
The screenshots were made at the same time with active downloads.
The skin at SABnzbd is the smpl white skin. He was neglected earlier.

**Comment by Cpuroast** [comment]
Yeah I tried, Plush, Glitter and Simpl.

With Plush and Glitter
Download info is shown in the tab with Chrome, Firefox and Safari

With Simpl
Download info is shown with Firefox and Safari, but not in Chrome.

**Comment by schabau** [comment]
Hello,
It seems to be so again that "smpl white skin" is neglected. I hope for a solution.

**Comment by Safihre** [comment]
The skin is deprecated. Should have put that in the release notes of 2.0.0 but forgot. 
Will take a look if there's a quick fix, but otherwise this is just the way it is. 

We only support Glitter since it can do anything on any screen size and Plush for bug fixes. The technology of smpl is just years and years outdated..

**Comment by schabau** [comment]
Well, smpl white skin is and remains now times the only skin which is clear and not only Colorful what today is probably the most important.
Focus on working and not on optics.

**Comment by schabau** [comment]
And with a next version is the next skin "out of date". Then the thing with different skins does not. Then there are also no problems and users do not have to change because skins are not further developed.

So it's shit.

**Comment by albino1** [comment]
You could just fork it and update it yourself.  That's how Glitter started in the first place.

**Comment by Safihre** [comment]
I cannot seem to fix it because in the new Chrome for some reason using this doesn't work anymore:
```javascript
document.title = 'blalal'
```

**Comment by thezoggy** [comment]
clear browser cache?

**Comment by Safihre** [comment]
> and not only Colorful what today is probably the most important.

Colorful? Glitter uses 1 extra color (green) besides grey so I don't know what you are talking about.

**Comment by schabau** [comment]
Hello,
Both me and many of my friends keep smpl skin much more structured and clearer than glitter or even worse plush.
But well, that is the point of view.
We just hope that smpl is offered for as long as possible alternatively and must live with minor errors.
