### ISSUE TITLE
Sabnzbd reports disk error then pauses

### ISSUE THREAD

**Issue by d3cayx1** [sabnzbd/sabnzbd#903]
I've starting having an issue ever since i upgraded from 0.7.x to the latest version where completely randomly sabnzbd will pause indefinitely after encountering a "disk error." It happens after a download has completed, unpacked and moved correctly, and sabnzbd has moved on to the next one and then seems to try to access a par file from the completed download which no longer exists because it already finished. Unpausing continues the queue perfectly normally with no more errors until the next random "disk error"

Currently on Win 7 64 using sabnzbd v 2.0.0
sample from redacted log
[rarstopsample.txt](https://github.com/sabnzbd/sabnzbd/files/928669/rarstopsample.txt)

**Comment by Safihre** [comment]
I think we will need more and unredacted log. When you use `Show logging` in the Status Window it will already remove any personal info.
It might have to do with the filenames, but these are changed now so harder to diagnose.
Can also send it to safihre@sabnzbd.org
