### ISSUE TITLE
Improve url rewriting 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#904]
Currently we only work with `/sabnzbd` in the URL but for some proxy users this is problematic. 
We should do more relative redirects instead of the hard-coded `/sabnzbd` (or `/`).

**Comment by Safihre** [comment]
Can anyone tell me if this is actually needed?
Since we bind to both `/` and `/sabnzbd` isn't that enough?

**Comment by thezoggy** [comment]
Only reason I can think of is for reverse proxy.. but that's outside my wheelhouse
