### ISSUE TITLE
wizard test connection should backoff 

### ISSUE THREAD

**Issue by ahhdem** [sabnzbd/sabnzbd#907]
This is pretty low priority, but the failed login retry is too aggressive, and causes account lockout (at least, was my experience with giganews, probably true for others)

After clicking test connection, the UI offered no feedback that the credentials were failing before retrying enough times to lockout account.  Ideally, this should be more graceful; I'd be happy with a 1:1 click:login attempt  -- not sure a loop until success is desired? (new to sab)

**Comment by Safihre** [comment]
I am not sure I understand it completly (was on vacation before).
You are saying SAB is retrying multiple times? Because that is not in the code, 1 click = 1 try.

What error do you get after 1 click? What error/message did you expect?

**Comment by ahhdem** [comment]
This was a while ago, so I no longer recall the details any more specifically than described.  I did not receive any error or message from sab, but apparently the multiple failed login attempts was what caused my account lockout, and the wizard was the only place I had ever entered the credentials.

I suppose its possible multiple clicks occurred, but I would hope giganews is blocking after more than 2-3 failed login attempts, as I certainly did not clickstorm or get impatient. What I do recall is going through the steps with no real hiccups or problems until this step, and then suddenly giganews was unreachable. 

Perhaps I was on an old build or something, but it might be worth validating that some message is surfaced in an unauth event.

**Comment by Safihre** [comment]
Verified that it will only send 1 login attempt and will wait for response to that. There's no re-try unless the user clicks multiple times 👍
