### ISSUE TITLE
glitter - cosmetic bug - firefox history title

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#908]
in glitter, if you hover over an entry we show the title, which has some padding (looks like leading/trailing space).

For a long entry like:
`The.Walking.Dead.S04.Special.Inside.The.Walking.Dead.Walker.University.720p.HDTV.X264-W4F`

The tooltip cuts off the trailing space/padding.. the longer the title the more that gets cut off..  seems to be a firefox bug cutting off the tooltip titles at 84 characters.

**Comment by Safihre** [comment]
What can we do about this then? If it's a firefox bug?

**Comment by thezoggy** [comment]
havent dug into it to see if there is anything to do or if its only on a specific version..  will come back to this one

**Comment by Safihre** [comment]
Problem seems to be fixed in FF 54!
![image](https://user-images.githubusercontent.com/5703454/27181718-0bc173b0-51d9-11e7-8d80-bf4dcee21e6f.png)

**Comment by thezoggy** [comment]
it still has a wierd cut off issue, but the actual text wraps and shows everything.. deff just a browser bug.
using ff 54 myself, its better than before..
