### ISSUE TITLE
[FR] Sync multiple instances of sab so only one instance will download at a time

### ISSUE THREAD

**Issue by leram84** [sabnzbd/sabnzbd#909]
Since providers won't allow multiple simultaneous downloads, and i run sab on several machines, i will usually keep everything in a paused state until i need it. Would be great if sab was able to keep tabs on other instances, and only proceed with a download when no other servers are active. Maybe even with a priority setting of some kind, so that a que from one server will stay active before others.

**Comment by Hellowlol** [comment]
Use https://sabnzbd.org/wiki/scripts/pre-queue-scripts ?

**Comment by thezoggy** [comment]
"providers wont allow multiple simultaneous downloads"  -- care to elaborate?
provider = usenet service provider? indexer? your local sab client?

sab can d/l multiple items at once..  you can fetch these from different usenet providers at once yes.. just limited to how many connections you can have open..  just make sure you dont have sab set to only grab stuff from top of queue and that your admin folder isnt on some slow mechanical hdd

**Comment by leram84** [comment]
Hey! sorry for the late reply, i got hit with the flu really hard and kind of checked out for a few days lol. Anyway. @Hellowlol I'm not sure how scripts will help... im not a programmer, but i dont see how any of those parameters can be used to check on other instances of sab before proceeding with a dl. 

@thezoggy Sorry, i guess i wasn't being very clear. I do mean usenet service providers (astra, giga, etc). I have a few, and i dont remember which ones rules are stricter, but i remember that some of them are very aggressive about limiting dl's from multiple ips at the same time. Since my main server is automated, i dont want to start a dl on another machine until i log into the server and pause sab there first. I know many providers will just give you the "too many users" notification and then go back to normal after some time, but i just thought it would be a more elegant solution if sab had some way of keeping all instances of itself in sync in a way that it would intelligently pause all other instances when u start a dl on one machine, and then proceed with the next when the current is done.... kind of like a global que. Hopefully ive explained this better, but the idea is to get all instances of sab on multiple machines to work together and not try to dl at the same time.

**Comment by Cpuroast** [comment]
What you are talking about is essentially clustering/orchestration and that goes well above and beyond what sab was designed for. 

There's also probably only a handful of people running sab in your config, so I highly doubt sab itself will ever support it.

Sabnzbd provides a full API, so people are free to write this type of orchestration layer.

**Comment by leram84** [comment]
ok fair enough. just trying to see if there was an easy fix. ill close this up.

**Comment by Safihre** [comment]
Using a Pre-Queue script you could send an api call to your other sabnzbd instance as soon as a new job is added. Either you can pause the other sabnzbd instance or check if it has active jobs and then add the job to the queue as paused. 
Only problem would be how to activate the queue again. You would need a post processing script for each job that unpauses the other instance, but only if the queue of the current instance is empty. 
Something like this. 

If you ever do end up coding it, share it and we can put it on the website :+1:
