### ISSUE TITLE
Download being marked as complete when par2 verification failed.

### ISSUE THREAD

**Issue by Cheezykins** [sabnzbd/sabnzbd#912]
Sabnzbd version: 2.0.1RC1 [2f52590] (Installed using apt from the JCFP PPA)
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] [UTF-8]
OpenSSL: OpenSSL 1.0.2k 26 Jan 2017   [TLS v1.2, TLS v1.1, TLS v1]
OS: Linux (Ubuntu Server 16.10)

Symptom: Download is marked as complete, even though par2 verification failed.
![image](https://cloud.githubusercontent.com/assets/11211889/25781176/ecb5c152-332d-11e7-9452-7ade1a74ae40.png)

Debug log file: 
[sabnzbd.log.zip](https://github.com/sabnzbd/sabnzbd/files/981585/sabnzbd.log.zip)

Repeating it with the same NZB file results in the same result, so it is not a transient issue.

**Comment by thezoggy** [comment]
just because a parset fails doesnt mean the download failed..
sometimes people post stuff with broken parset, upload as incomplete, etc..   downloading what was uploaded DID complete..

**Comment by Safihre** [comment]
Do you have Post process only verified jobs turned on? In Config Switches.

**Comment by Safihre** [comment]
@Cheezykins any feedback for us?

**Comment by Safihre** [comment]
Can be reopened if issue occurs again.
