### ISSUE TITLE
Turn off gzip compression / reverse proxy in IIS

### ISSUE THREAD

**Issue by 1liminal1** [sabnzbd/sabnzbd#915]
Hi guys,

I have set up a reverse proxy in IIS, but having issues due to gzip compression. I have used this guide to get around it and its working for Sonarr and Couch Potato

https://blogs.msdn.microsoft.com/friis/2016/08/25/iis-with-url-rewrite-as-a-reverse-proxy-part-2-dealing-with-500-52-status-codes/

But SAB is giving me this, anyway to get around this? Ive been told SAB is very reverse proxy friendly?

406 Not Acceptable

identity, gzip

Traceback (most recent call last):
File "cherrypy\_cprequest.pyo", line 670, in respond
File "cherrypy\lib\encoding.pyo", line 220, in __call__
File "cherrypy\_cpdispatch.pyo", line 60, in __call__
File "sabnzbd\interface.pyo", line 326, in index
File "sabnzbd\interface.pyo", line 2686, in NeedLogin
HTTPRedirect: (['/login/'], 303)
Powered by CherryPy 8.1.2

**Comment by thezoggy** [comment]
first time ive ever heard anyone having problems with gzip and a reverse proxy..   mind posting your config?

**Comment by 1liminal1** [comment]
Hi there, 

Here is my IIS config, ill post the SAB after this

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://server:XXXX/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_X_ORIGINAL_ACCEPT_ENCODING" value="{HTTP_ACCEPT_ENCODING}" />
                        <set name="HTTP_ACCEPT_ENCODING" value="" />
                    </serverVariables>
                </rule>
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Form, Img" pattern="^http(s)?://server:XXXX/(.*)" />
                    <action type="Rewrite" value="http{R:1}://sub.domain.com/{R:2}" />
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        <urlCompression doStaticCompression="true" />
    </system.webServer>
</configuration>

**Comment by 1liminal1** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://media:8181/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_X_ORIGINAL_ACCEPT_ENCODING" value="{HTTP_ACCEPT_ENCODING}" />
                        <set name="HTTP_ACCEPT_ENCODING" value="" />
                    </serverVariables>
                </rule>
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Form, Img" pattern="^http(s)?://media:8181/(.*)" />
                    <action type="Rewrite" value="http{R:1}://sab.liminal.net.au/{R:2}" />
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        <urlCompression doStaticCompression="true" />
    </system.webServer>
</configuration>

**Comment by 1liminal1** [comment]
`__version__ = 19
__encoding__ = utf-8
[misc]
win_menu = 1
queue_complete = ""
https_port = 9090
folder_rename = 1
allow_64bit_tools = 1
local_range = ""
password_file = ""
movie_rename_limit = 100M
ionice = ""
https_key = 
cleanup_list = ,
cache_limit = 450M
ignore_unrar_dates = 0
par_option = ""
web_color = Default
enable_recursive = 1
pre_check = 0
replace_spaces = 0
web_color2 = ""
dirscan_speed = 5
enable_filejoin = 1
create_group_folders = 0
api_key = 
never_repair = 0
no_penalties = 0
osx_speed = 1
bandwidth_limit = 0
dirscan_dir = 
disable_api_key = 0
quota_period = m
email_to = ,
rss_filenames = 0
password = 
permissions = ""
quota_day = ""
auto_disconnect = 1
use_pickle = 0
https_chain = ""
warn_empty_nzb = 1
history_limit = 50
enable_date_sorting = 0
replace_dots = 0
movie_sort_extra = -cd%1
quota_size = ""
rss_rate = 60
enable_unzip = 1
download_free = ""
port = 8181
enable_movie_sorting = 0
wait_ext_drive = 5
pre_script = None
ipv6_servers = 1
email_full = 0
log_dir = logs
show_sysload = 2
admin_dir = admin
nzb_backup_dir = ""
tv_sort_countries = 1
date_categories = tv,
ssl_type = v23
sfv_check = 1
date_sort_string = ""
schedlines = ,
host = 192.168.190.11
ignore_samples = 0
sanitize_safe = 0
req_completion_rate = 100.2
enable_tsjoin = 1
auto_browser = 0
fsys_type = 0
pause_on_post_processing = 0
allow_incomplete_nzb = 0
uniconfig = 1
enable_unrar = 1
randomize_server_ip = 0
email_rss = 0
email_account = ""
email_server = ""
allow_streaming = 0
config_lock = 0
quota_resume = 0
api_warnings = 1
wait_for_dfolder = 0
tv_sort_string = ""
fail_hopeless = 0
movie_extra_folder = 0
unpack_check = 1
no_ipv6 = 0
download_dir = 
size_limit = 0
enable_par_cleanup = 1
safe_postproc = 1
cache_dir = cache
complete_dir = 
replace_illegal = 1
nomedia_marker = ""
max_art_opt = 0
par2_multicore = 1
warned_old_queue = 0
language = en
check_new_rel = 1
enable_https = 0
no_dupes = 0
keep_awake = 1
top_only = 0
quick_check = 1
movie_sort_string = ""
email_from = ""
max_art_tries = 3
osx_menu = 1
username = 
email_endjob = 0
tv_categories = ,
rss_odd_titles = nzbindex.nl/, nzbindex.com/, nzbclub.com/
pause_on_pwrar = 1
login_realm = SABnzbd
send_group = 0
refresh_rate = 1
prio_sort_list = ,
movie_categories = movies,
script_dir = 
email_pwd = ""
empty_postproc = 0
ignore_wrong_unrar = 0
nice = ""
email_dir = ""
https_cert = 
web_dir2 = ""
web_dir = Glitter
web_watchdog = 0
fail_on_crc = 1
nzb_key = 
auto_sort = 0
ampm = 0
start_paused = 0
overwrite_files = 0
queue_complete_pers = 0
enable_tv_sorting = 0
folder_max_length = 128
rating_enable = 0
rating_feedback = 1
enable_meta = 1
rating_api_key = ""
warn_dupl_jobs = 1
rating_host = 
flat_unpack = 0
rating_filter_enable = 0
rating_filter_abort_video = 0
rating_filter_pause_audio = 0
rating_filter_pause_encrypted_confirm = 0
rating_filter_pause_encrypted = 0
rating_filter_abort_encrypted_confirm = 0
rating_filter_pause_spam_confirm = 0
rating_filter_abort_keywords = ""
rating_filter_abort_encrypted = 0
rating_filter_pause_keywords = ""
rating_filter_abort_spam_confirm = 0
rating_filter_abort_downvoted = 0
new_nzb_on_failure = 0
rating_filter_pause_downvoted = 0
rating_filter_abort_audio = 0
unwanted_extensions = ,
rating_filter_pause_spam = 0
rating_filter_pause_video = 0
action_on_unwanted_extensions = 0
rating_filter_abort_spam = 0
notified_new_skin = 2
inet_exposure = 5
selftest_host = self-test.sabnzbd.org
load_balancing = 2
enable_7zip = 1
warned_old_queue9 = 0
enable_https_verification = 0
ipv6_hosting = 0
enable_bonjour = 1
enable_all_par = 0
queue_limit = 20
no_series_dupes = 0
bandwidth_max = ""
local_ranges = ,
backup_for_duplicates = 1
sched_converted = 2
script_can_fail = 0
bandwidth_perc = 0
api_logging = 1
allow_duplicate_files = 0
fail_hopeless_jobs = 1
fixed_ports = 0
html_login = 1
prospective_par_download = 1
propagation_delay = 0
ssl_ciphers = ""
quick_check_ext_ignore = nfo, sfv, srr
nr_decoders = 2
[logging]
log_new = 0
max_log_size = 5242880
log_level = 2
log_backups = 5
enable_cherrypy_logging = 0
[growl]
ntfosd_enable = 0
growl_enable = 1
growl_server = ""
notify_classes = startup, download, pp, complete, other
ncenter_enable = 0
growl_password = ""
growl_prio_disk_full = 1
growl_prio_other = 0
growl_prio_download = 0
growl_prio_startup = 1
growl_prio_failed = 1
growl_prio_queue_done = 1
growl_prio_warning = 0
growl_prio_error = 0
growl_prio_complete = 1
growl_prio_pp = 0
growl_prio_new_login = 0
[nzbmatrix]
username = ""
apikey = ""
del_bookmark = 1
[newzbin]
username = ""
url = www.newzbin2.es
bookmark_rate = 60
bookmarks = 0
password = ""
unbookmark = 1
[nzbxxx]
username = ""
apikey = ""
[servers]
[[]]
username = 
priority = 0
enable = 1
displayname = 
name = 
notes = ""
connections = 20
ssl = 1
host = 
timeout = 120
ssl_verify = 1
send_group = 0
password = 
optional = 0
port = 443
categories = Default,
retention = 0
[categories]
[[*]]
priority = 0
pp = 3
name = *
script = None
newzbin = ""
order = 0
dir = ""
[ncenter]
ncenter_prio_download = 0
ncenter_prio_warning = 0
ncenter_prio_queue_done = 1
ncenter_prio_startup = 1
ncenter_prio_failed = 1
ncenter_prio_disk_full = 1
ncenter_prio_error = 0
ncenter_enable = 0
ncenter_prio_complete = 1
ncenter_prio_pp = 0
ncenter_prio_other = 0
ncenter_prio_new_login = 0
[pushover]
pushover_prio_error = 1
pushover_enable = 0
pushover_prio_complete = -1
pushover_prio_warning = 1
pushover_prio_startup = -3
pushover_prio_queue_done = -1
pushover_prio_other = -3
pushover_prio_pp = -3
pushover_prio_disk_full = 1
pushover_device = ""
pushover_token = ""
pushover_prio_failed = -1
pushover_prio_download = -2
pushover_userkey = ""
pushover_prio_new_login = -3
[prowl]
prowl_prio_disk_full = 1
prowl_prio_error = -3
prowl_prio_download = -3
prowl_enable = 0
prowl_prio_failed = 1
prowl_prio_pp = -3
prowl_apikey = ""
prowl_prio_startup = -3
prowl_prio_warning = -3
prowl_prio_other = -3
prowl_prio_complete = 0
prowl_prio_queue_done = 0
prowl_prio_new_login = -3
[acenter]
acenter_prio_warning = 0
acenter_prio_disk_full = 1
acenter_prio_error = 0
acenter_prio_failed = 1
acenter_prio_startup = 0
acenter_prio_queue_done = 1
acenter_enable = 1
acenter_prio_complete = 1
acenter_prio_download = 0
acenter_prio_pp = 0
acenter_prio_other = 0
acenter_prio_new_login = 0
[ntfosd]
ntfosd_prio_queue_done = 1
ntfosd_enable = 0
ntfosd_prio_error = 0
ntfosd_prio_startup = 1
ntfosd_prio_complete = 1
ntfosd_prio_pp = 0
ntfosd_prio_warning = 0
ntfosd_prio_other = 0
ntfosd_prio_disk_full = 1
ntfosd_prio_download = 0
ntfosd_prio_failed = 1
ntfosd_prio_new_login = 0
[pushbullet]
pushbullet_prio_download = 0
pushbullet_prio_queue_done = 0
pushbullet_enable = 0
pushbullet_prio_complete = 1
pushbullet_prio_warning = 0
pushbullet_device = ""
pushbullet_prio_failed = 1
pushbullet_prio_other = 0
pushbullet_apikey = ""
pushbullet_prio_disk_full = 1
pushbullet_prio_pp = 0
pushbullet_prio_startup = 0
pushbullet_prio_error = 0
pushbullet_prio_new_login = 0
[nscript]
nscript_prio_warning = 0
nscript_prio_complete = 1
nscript_prio_other = 0
nscript_prio_queue_done = 1
nscript_prio_failed = 1
nscript_prio_pp = 0
nscript_prio_new_login = 0
nscript_script = ""
nscript_prio_download = 0
nscript_prio_error = 0
nscript_prio_startup = 1
nscript_parameters = ""
nscript_enable = 0
nscript_prio_disk_full = 1
`

**Comment by 1liminal1** [comment]
Hope I have scrubbed that properly :-?

**Comment by thezoggy** [comment]
you dont have to scrub anything, sab does this for you when viewing the log via the gui. speaking off... what version of sabnzbd are you running?

**Comment by 1liminal1** [comment]
Ahh, so that's how you do it, thanks :)

Version:	2.0.0 [55c4bef]

I just copied it directly out of the INI

**Comment by thezoggy** [comment]
well hard to say if your IIS rewrite rules are correct..  not seeing `{C:1}` used for potocol but instead `{R:1}` but anyways this line is what concerns me:
`        <urlCompression doStaticCompression="true" />`

I would not set that.. especially with your problems reported

**Comment by 1liminal1** [comment]
I changed the value to false, but it didnt change anything. 

Whats the ```{C:1}``` ?

Is there anyway to disable gzip within SAB?

**Comment by thezoggy** [comment]
check out: https://forums.iis.net/t/1165899.aspx

**Comment by 1liminal1** [comment]
Yeah, ive seen that and turned it off and moved it down the list. But I still get that;

```406 Not Acceptable

identity, gzip

Powered by CherryPy 8.1.2```

**Comment by thezoggy** [comment]
https://emby.media/community/index.php?/topic/5923-using-iis-or-apache-web-frontend/?p=156366

**Comment by 1liminal1** [comment]
I actually got this working for a brief time today using a server farm instead of a site set up with URL rewrite. 

So I know it works, just have to figure out how other things are interfering with it now. 

But thanks so so much for your help.

**Comment by AdmiralMichael** [comment]
Any fix on this issue? I am having the same issue with IIS on Windows 7 and SABnzbd 2.3.1 [f1695ec].

**Comment by 1liminal1** [comment]
Hey there, 

I set up server farms. If you google it, you can find some great guides.

Shane

**Comment by AdmiralMichael** [comment]
Can it be setup for something like sabnzbd.domain.com?
