### ISSUE TITLE
Calculation error when pausing for "13 hours"

### ISSUE THREAD

**Issue by ali-l** [sabnzbd/sabnzbd#916]
Gets converted to 4320 mins instead of 780 mins.

**Comment by thezoggy** [comment]
just tired this in latest version, `13h` works. `13hours` works. `13 hours` doesnt. the space breaks it.. but `3 hours` is fine.. so bad regex parsing?

**Comment by ali-l** [comment]
Any idea what file this would be located in?

**Comment by ali-l** [comment]
This is a bug with the DateJS dependency, which may or may not have been fixed. I'll have a look there, and maybe update the file if it's been fixed.

**Comment by Safihre** [comment]
Too bad it can't be fixed. There's more errors in that library that we already try to catch. Maybe I can add this case.

**Comment by thezoggy** [comment]
Just replace ` hours` with `hours`... 
To strip the space out

**Comment by ali-l** [comment]
Seems like it's broken for anything between 13 and 48 minutes. But replacing the spaces fixes that too

**Comment by ali-l** [comment]
How does #918 look?

**Comment by Safihre** [comment]
Thanks! Will check and merge when I'm back from my holiday :)

**Comment by thezoggy** [comment]
i just tried this again.. and `13 hours` is working fine for me in latest firefox..

**Comment by ali-l** [comment]
Weird...
`13 hours` seems fine for me too now, on the latest Chrome. Now I see it breaking at/above `17 hours` and `17 minutes`.

**Comment by thezoggy** [comment]
can see that `17 hours` is fine, now its `18 hours` that doesnt work.. aka take the day number + 1. looks like its more of a parsing bug.. and looking at the way were doing the logic.. it may actually be a bug on glitter's end..

**Comment by Safihre** [comment]
This is quite the weird bug.. But you fixed it well!
