### ISSUE TITLE
FYI: Windows: show and search root certificates in Windows store

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#917]
As a FYI:

**Rationale**: With SABnzbd 2.0.0's checking of certificates of NNTPS connections, sometimes users discover problems with a perfectly OK NNTPS server that is not trusted, because of missing root certificates in their own Windows root store. So how can SABnzbd see / detect the Windows root certificates? Here is a first shot: 1) number of certificates and 2) search specific certificate.

On Windows, with Powershell, you can show the show root certificates in the Windows store with

`Get-ChildItem -Recurse Cert:`

No admin-rights needed.

Example start of the output:

```
Location   : CurrentUser
StoreNames : {SmartCardRoot, UserDS, AuthRoot, CA...}

Name : SmartCardRoot

Name : UserDS

Name : AuthRoot

Subject      : CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification S
               ervices Division, O="thawte, Inc.", C=US
Issuer       : CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification S
               ervices Division, O="thawte, Inc.", C=US
Thumbprint   : F18B538D1BE903B6A6F056435B171589CAF36BF2
FriendlyName : thawte Primary Root CA - G3
NotBefore    : 2-4-2008 2:00:00
NotAfter     : 2-12-2037 0:59:59
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid}

Subject      : CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C
               =US
Issuer       : CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C
               =US
Thumbprint   : E12DFB4B41D7D9C32B30514BAC1D81D8385E2D46
FriendlyName : USERTrust (Code Signing)
NotBefore    : 9-7-1999 20:31:20
NotAfter     : 9-7-2019 20:40:36
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, S
               ystem.Security.Cryptography.Oid...}

Subject      : CN=TWCA Root Certification Authority, OU=Root CA, O=TAIWAN-CA, C=TW
Issuer       : CN=TWCA Root Certification Authority, OU=Root CA, O=TAIWAN-CA, C=TW
Thumbprint   : DF646DCB7B0FD3A96AEE88C64E2D676711FF9D5F
FriendlyName : TWCA Root Certification Authority 2
NotBefore    : 28-8-2008 9:47:13
NotAfter     : 31-12-2030 16:59:59
```
I have 328 occurences of "FriendlyName" (thus: certificates), of which 5 seem non-standard (testing on an office desktop)

In python:
```
import subprocess, datetime

print datetime.datetime.now()

output = subprocess.check_output("powershell.exe Get-ChildItem -Recurse Cert:")
# print output

print datetime.datetime.now()
print "Number of certificates:", output.count("FriendlyName") 

```
Output:
```
C:\python27>python powertje.py
2017-05-11 09:36:11.886000
2017-05-11 09:36:15.551000
Number of certificates: 328
```

So that lookup takes 4 seconds, so that is not something we should do synchronously at every SAB startup, but only in self-analysis / troubleshoot cases, or asynchronously.

Search for a certain root certificate:
```
subject = "CN=Let's Encrypt"
print "Root of ", subject, "found:", output.count(subject)
```

```
Number of certificates: 328
Root of  CN=Let's Encrypt found: 1
```

I think this could be useful for SABnzbd.

**Comment by Safihre** [comment]
Should we really add this to SAB? Isn't it enough to ask this from users in cases with problems?

**Comment by sanderjo** [comment]
> Isn't it enough to ask this from users in cases with problems?

I like to try to avoid each repetitive question in the forum: "Help, SAB is complaining about my newsserver" "... on which OS? And which newsserver? And ..." "It's Windows 10, with news.blabla.com", "OK, do this ..."

I prefer SAB itself saying "Your certificate root store is updated. Update it, and/or update the operating system SAB is running on".

**Comment by Safihre** [comment]
Will keep this in mind 👍
