### ISSUE TITLE
CSS is not minified

### ISSUE THREAD

**Issue by drewfreyling** [sabnzbd/sabnzbd#920]
All CSS across all themes are unminified. I'll put a PR for this using clean-css unless there are any objections?

**Comment by Safihre** [comment]
It doesn't matter for sabnzbd really, since the constant API calls are much more data costly than the few kb saved with mimification. 
Would also mean that we would need 2 files for each css. Didn't seem worth the trouble to me..

**Comment by thezoggy** [comment]
we used to run everything through a minifier but it makes it much harder for others to maintain the code/update.. especially when the skins maintainer left and never provided the source..  most people just use an app to access sab remotely using its api... so the gui being a few kb bigger doesnt really hurt most.. as the ones that do rely on sab gui usually are doing it within the LAN or on a fast connection

**Comment by Safihre** [comment]
So indeed, leaving it nice and big.
