### ISSUE TITLE
sab 2.1.0-develop -- need to cleanup rss links

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#922]
on the dev instance when i started it up with `--new` it spammed the console when it cleaned up the RSS info I had.. I noticed it did not sanitize these..

`2017-05-17 00:35:29,615::DEBUG::[rss:166] Purging link https://api.omgwtfnzbs.me/nzb/?id=rLUOD&user=_not_removed_&api=_not_removed_`

**Comment by Safihre** [comment]
You want it to be sanitized in the console? Why? Or what do you mean by sanitize? 

If you mean remove user info, it only does that when clicking `Show logging` to export the log.

**Comment by thezoggy** [comment]
dont really care about the console, but it needs to be sanitized in the logs

**Comment by Safihre** [comment]
I check and for me it does remove the 32 char hashes, it doesn't for you?

**Comment by thezoggy** [comment]
I see it actually does, must not have looked at the right log file.. console/normal log shows:
`2017-05-17 00:35:30,099::DEBUG::[rss:166] Purging link https://api.omgwtfnzbs.me/nzb/?id=5n0FH&user=XXXXXXX&api=XXXXXXXXXXXXXX`
glitter log shows:
`2017-05-17 00:35:30,099::DEBUG::[rss:166] Purging link https://api.omgwtfnzbs.me/nzb/?id=5n0FH&user=<USER>`
