### ISSUE TITLE
Sabnzb 2.0.0 [55c4bef] Glitter Skin Bug

### ISSUE THREAD

**Issue by thenormal** [sabnzbd/sabnzbd#924]
Just letting you guys know, if you're using the Glitter skin (Which I personally love), when you click on those 3 horizontal lines at the top-right corner of you browser and then select an action to perform on queue finish, whether it be shutdown computer or whatever, the program resets it to the original option, that is no action performed once queue is finished. Check it out.

**Comment by Safihre** [comment]
I am not able to reproduce it. Could you tell me which OS and browser you use?

**Comment by thenormal** [comment]
Running WIndows 10 Creator Edition, and latest Chrome build

**Comment by Safihre** [comment]
Fixed it.
