### ISSUE TITLE
unrar: write Error and original files are deleted

### ISSUE THREAD

**Issue by h3llrais3r** [sabnzbd/sabnzbd#927]
Hi, I'm running version 2.0.0 and I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/1945295/26368944/76bc26e4-3ff3-11e7-8be2-a40f352e6860.png)

I assume this is because the path is too long, however, the error does not say it is (although it's more than 260 characters long)

I agree that it should fail on windows when the paths are too long, but it also deletes the original data.
So I basicly need to redownload everthing again 😢 
Is this normal? Any idea how to fix this?

**Comment by Safihre** [comment]
Will be fixed in 2.0.1. Want to release that tomorrow, so maybe you can test it then and let me know if it worked?

**Comment by h3llrais3r** [comment]
Thanks. But I'm running from source... so perhaps I can already test it now?

**Comment by Safihre** [comment]
Yes, just switch to the `develop` branch and do a pull!

**Comment by h3llrais3r** [comment]
Testing it right now : but need some time to dowload.... (approx 2h)

**Comment by Safihre** [comment]
While it's downloading, can you go into the Status and Interface Window and turn on +Debug?
This way we can see the Unrar log.

I just downloaded that file and it worked fine for me, also for older release. So we might need the log.

**Comment by h3llrais3r** [comment]
Debug enabled. But perhaps your path is not longer than 255 chars?

**Comment by h3llrais3r** [comment]
I confirm it's working with the latest develop branch.
I've tested it with 2 downloads that were failing. They are now unpacked with success!
Thanks for your work and support. 👍

**Comment by Safihre** [comment]
:+1:
