### ISSUE TITLE
OpenSSL certificate issue with 2.1.0 Beta 1 macOS bundle

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#928]
This message appears in /config on macOS 10.12.5

OpenSSL:	OpenSSL 1.0.2k 26 Jan 2017   [TLS v1.2, TLS v1.1, TLS v1, SSL v3]

Warning Secure (SSL) connections from SABnzbd to newsservers and HTTPS websites will be encrypted, however, validating a server's identity using its certificates is not possible. Python 2.7.9 or above, OpenSSL 1.0.2 or above and up-to-date local CA certificates are required.

Also, the "Certificate verification" section in advanced server config is now greyed out.

**Comment by Safihre** [comment]
Hmm, I only tested 10.12.3. Updating to 10.12.5 now to see if that's the problem.

**Comment by Safihre** [comment]
10.12.5 it also works for me. Could you try restarting sabnzbd and/or the machine?

**Comment by Cpuroast** [comment]
Just restarted this mac, same behaviour. It's done it on 2 computers.

Neither have any trace of homebrew.

**Comment by Safihre** [comment]
And if you switch back to 2.0.1, no problems?

**Comment by Cpuroast** [comment]
Yes, I can switch back to 2.0.1 and no such issue occurs:

OpenSSL:	OpenSSL 0.9.8zh 14 Jan 2016   [TLS v1, SSL v3, SSL v2]

and "Certificate verification" section in advanced server config is not greyed out.

**Comment by Safihre** [comment]
Same here: If anyone wants to help get this fixed, the build process (except for the certificates to sign the releases) is hosted in a separate repo and run by TravisCI: https://github.com/sabnzbd/sabbuild
Can contact me for more info!
