### ISSUE TITLE
SABnzbd 2.1.0 Beta 1 on macOS doesn't download any nzbs

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#929]
SABnzbd 2.1.0 Beta 1 on macOS doesn't start any nzbs download jobs using any possible method: API, UI Add NZB via http or https, browse, etc.

They all end up immediately as orphaned, with no nzb in the job's __ADMIN__ folder.

Haven't need to download anything so far, which is why I hadn't noticed earlier.

I'll test on Windows tomorrow.

If I go back to 2.0.1, everything works fine again.

Quite a major regression, but heh, those are bound to happen :)

Also, any reason this landed as Beta 1 instead of Alpha 1?
I would assume major changes like adding multipar and changing the python/openssl source for macOS need lots of testing/bake time.

**Comment by Safihre** [comment]
Guess will revert back to Apple Python and old OpenSSL. I tested it a lot on my own systems, so really not sure what could be the difference..
 They are not build systems so they don't have homebrew or anything like that.

**Comment by Cpuroast** [comment]
Yeah, weird then, having the new OpenSSL is a good thing, I'll keep testing to  try and isolate the issue.

**Comment by Safihre** [comment]
I can reproduce the issue now on a different machine. Hope to find something.

**Comment by Safihre** [comment]
I give up, OSX is not producing any helpful logging.
Reverted to using ApplePython with the older OpenSSL and added that version to the release.

If anyone wants to help get this fixed, the build process (except for the certificates to sign the releases) is hosted in a separate repo and run by TravisCI: https://github.com/sabnzbd/sabbuild

**Comment by thezoggy** [comment]
curious if you build osx binaries using brew python or apple python or what.. i know at one point shy got frustrated and couldnt use anything but apple python.. but this was many years ago...

**Comment by Safihre** [comment]
Actually my comment is wrong, I don't use Apple python. I use the official 2.7.23 distributions of the python website, but they link to the system Apple OpenSSL. Which is 0.9.8 from January 2016 that doesn't support higher than TLSv1,  but is allowed to tap into the local certificate storage. 

 With homebrew you get python linked to the latest 1.0.2 OpenSSL, but with its own certificates.  As the bugs describe some systems this seems to fail and it even breaks the simple adding of an NZB, but there is no logging why that would possibly fail.. 

You can see the build logs here: https://travis-ci.org/sabnzbd/sabbuild (it's in the install.sh section).

**Comment by thezoggy** [comment]
wonder if the problem is the build server or setup..  looking at that log.. i see a few things in `Modules not found (conditional imports):` that may be cause for concern.. but since i never build sab exe i dont know if its normal..  i used to build sickbeard exe and i know theres lots of quirks in py2exe.. so i can only assume py2app has similar ones..  

speaking of.. sickbeard and sab used to use similar setup build process...  then in sb world we updated a lot of stuff especially when we moved it to TI.. prob a few things that needs to update on sab's end

comparing the two exe files, you can see the difference:
![sab](http://zoggy.net/firefox_2017-05-27_09-39-25.png)

here was the latest update stuff (yes several years ago):
https://github.com/thezoggy/Sick-Beard/blob/windows_binaries--update/setup.py

i'll have to track down where lad1337 put all the travis related stuff...

**Comment by Safihre** [comment]
The Windows build log is here: https://ci.appveyor.com/project/Safihre/sabbuild

Feel free to submit a PR to add more info to the setup, it should be here:
https://github.com/sabnzbd/sabbuild/blob/master/builder/package.py#L378-L389
And here:
https://github.com/sabnzbd/sabbuild/blob/master/builder/package.py#L554-L562

**Comment by thezoggy** [comment]
will do

**Comment by thezoggy** [comment]
py2exe is so ancient.. wonder if we should move towards a new builder..

* cx_freeze is similar to py2exe but supports more platforms. It also zips bytecode+native modules (same as py2exe).

since were not doing python 2.5 and older.. wonder if nuitka would be an option:

* nuitka - It translates the Python into a C program that then uses libpython to execute in the same way as CPython does, in a very compatible way.  http://nuitka.net/pages/overview.html

**Comment by Safihre** [comment]
@thezoggy I tried Nuitka, but in our dependencies there seems to be some trouble because they modify the contents of functions, which is not allowed. It also seems it can't run C-modules, like sabyenc.
Sounds very promising though!

**Comment by Safihre** [comment]
@Cpuroast Would you be able to test this DMG?

**Comment by Cpuroast** [comment]
Tried the macOS and Win64 builds, both work fine :)

**Comment by Safihre** [comment]
@Cpuroast 
I have spend a whole day on this, and I think I figured it out. Broke my brain a bit 🤣 
Could you try this release? https://github.com/sabnzbd/sabbuild/releases/tag/hb17
It includes the Mozilla certificate storage, since we cannot use the macOS system certificates with this newer OpenSSL.

**Comment by Cpuroast** [comment]
Ok, trying it out:

1st thing I noticed is that SSL v3 should be permanently disabled and never exposed on all platforms.

OpenSSL: | OpenSSL 1.0.2l 25 May 2017   [TLS v1.2, TLS v1.1, TLS v1, SSL v3]

**Comment by Safihre** [comment]
@Cpuroast Yes we can do that in a later stage, for now I just need to know if SABnzbd is functioning normally with this new build-method.

**Comment by Safihre** [comment]
Actually, it just list it as being available but because we use `create_default_contex()` for all SSL connections it's actually disabled when making the connections. Both to newsservers and HTTPS.

**Comment by Cpuroast** [comment]
So far so good, connections to usenet servers are confirmed as using TLS 1.2.

**Comment by Cpuroast** [comment]
Considering TLS v1.3 is nearly done, if this new method is stable and reliable, then having TLS v1.3 support in Sab on mac will be easier.

**Comment by Safihre** [comment]
This we cannot do, it requires python to implement it and I doubt it's coming to 2.7.

**Comment by Cpuroast** [comment]
Who knows, maybe they'll backport it to 2.7 :)

**Comment by Cpuroast** [comment]
for now, wonder when Python 2.7.14 will show, they said mid 2017, we are kinda passed that :)

**Comment by Safihre** [comment]
Actually, OpenSSL doesn't even support TLSv1.3 yet. 
Only in OpenSSL 1.1.1.

I have been experimenting with compiling 2.7 from sources, but it's just a massive hassle.

**Comment by Cpuroast** [comment]
Yeah I read that, 1.3 should be finalized soon enough, and then 1.1.1 will be released.
but I guess for now hanging onto the LTS 1.0.2 with TLS 1.2 is the only way to go for the time being.

**Comment by thezoggy** [comment]
pulled up the cpython source in Mercurial and noticed it hasnt been touched in ages, was pleasantly surprised to see that cpython moved to github: https://github.com/python/cpython/tree/2.7

looking at 2.7.14 changelog:
https://raw.githubusercontent.com/python/cpython/2.7/Misc/NEWS

> - bpo-29572: Update Windows build and OS X installers to use OpenSSL 1.0.2k.

**Comment by Safihre** [comment]
@thezoggy should be noted here that the openssl they are talking about for OSX is only for old OSX versions and that normally they always link into the system openssl on the osx we support. 
So that's why we have to use Homebrew python to get newer OpenSSL.

**Comment by Cpuroast** [comment]
I mean, so far it's been ok, but I would actually push this change to 2.2.1 or 2.3.0, it's too late in the game.
SSL affects a lot of stuff in sab.

It needs more testing and if you want to release 2.2.0 at the end of the week, it's better not to ship this new SSL/certs just yet.

**Comment by Safihre** [comment]
Oh yes this is definitely not for 2.2.0 but for the next one! No rush.

**Comment by Safihre** [comment]
@Cpuroast Will use this new pipeline for 2.2.1 testing releases. Just open new issues in case those don't work as expected when they come out.
2.2.0 will use the old pipeline, but you can keep using the test-release I send you before because it includes everything in 2.2.0 final.
