### ISSUE TITLE
shutdown/suspend not working on Linux

### ISSUE THREAD

**Issue by BrendanBall** [sabnzbd/sabnzbd#931]
When I select on queue finish shutdown or suspend it doesn't work. If I use shutdown then sabnzbd just exits its process, if I choose suspend it does nothing.
Sabnzbd version: 2.0.1-1
Platform: Linux (Arch Linux 4.11.2-1-ARCH kernel)
systemd version: 232-8
If I try use the sab code in python I get the following:

```➜  sabnzbd python2
Python 2.7.13 (default, Feb 11 2017, 12:22:40) 
[GCC 6.3.1 20170109] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import powersup
>>> linux_standby()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'linux_standby' is not defined
>>> powersup.linux_standby()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "powersup.py", line 216, in linux_standby
    if proxy.Get(interface, 'can-suspend', dbus_interface=pinterface):
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'can-suspend'
>>> powersup.linux_shutdown()
➜  sabnzbd
```

**Comment by sanderjo** [comment]
You're doing it wrong: you have to go into the sabnzbd directory. You should see the subdirectory 'sabnzbd', with in that 'powersup.py'. Like this:

```
sander@Stream-13:~$ cd /usr/share/sabnzbdplus/
sander@Stream-13:/usr/share/sabnzbdplus$ ls sabnzbd/powersup.py
sabnzbd/powersup.py
```

or

```
sander@Stream-13:~$ cd git/sabnzbd/
sander@Stream-13:~/git/sabnzbd$ ls sabnzbd/powersup.py
sabnzbd/powersup.py

```


From there, start python, and then it works:
```
sander@Stream-13:~/git/sabnzbd$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabnzbd.powersup as powersup
>>> powersup.linux_shutdown()
```

**Comment by sanderjo** [comment]
@BrendanBall did this answer your question?

**Comment by BrendanBall** [comment]
Sorry I haven't had a chance to test yet,
The python stuff was just me trying to debug why it doesn't work though.
There is definitely still a problem, whether it's an unlisted missing
dependency or an actual bug I'm not sure yet.

**Comment by BrendanBall** [comment]
@sanderjo This makes no difference, I get exactly the same error
```➜  sabnzbd python2
Python 2.7.13 (default, Feb 11 2017, 12:22:40) 
[GCC 6.3.1 20170109] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabnzbd.powersup as powersup
>>> powersup.linux_suspend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'linux_suspend'
>>> powersup.linux_standby()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sabnzbd/powersup.py", line 216, in linux_standby
    if proxy.Get(interface, 'can-suspend', dbus_interface=pinterface):
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'can-suspend'```
```➜  sabnzbd python2
Python 2.7.13 (default, Feb 11 2017, 12:22:40) 
[GCC 6.3.1 20170109] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sabnzbd.powersup as powersup
>>> powersup.linux_shutdown()
➜  sabnzbd ```

**Comment by Safihre** [comment]
Is the `python-dbus` package correctly installed with all its dependencies?

**Comment by BrendanBall** [comment]
@Safihre it seems to be based on my package manager. I don't see python-dbus listed as a direct dependency of sab in the arch package at https://aur.archlinux.org/packages/sabnzbd but it might be a sub dependency somewhere, either way it is installed on my machine. I suspect somewhere it's just a missing dependency, but I need more  time to diagnose hopefully tomorrow. If I find it's just a missing dependency I'll close the issue and get the dependency list fixed in the arch package.

**Comment by BrendanBall** [comment]
ConsoleKit and UPower used by sab to perform shutdown, suspend etc operations seem to be deprecated/unmaintained. Most Linux systems nowadays run systemd which has direct commands to perform these operations through systemctl or loginctl which are both available through DBus. I'm not keen on installing such an unnecessary dependency.

Would anyone else agree that it would be a good idea to support systemd directly? The obvious Ubuntu has been using systemd for a long time, Arch uses systemd, I'm not going to bother googling a list but I'm sure it's popular enough to add support for it?

**Comment by sanderjo** [comment]
So @BrendanBall ... do you know the python command to do a standby resp shutdown via systemd that would work on your ArchLinux?

**Comment by BrendanBall** [comment]
@sanderjo well the systemd DBus api is clearly documented at https://www.freedesktop.org/wiki/Software/systemd/dbus/ , but they say 
"Reboot(), PowerOff(), Halt(), KExec() may be used to ask for immediate reboot, powering down, halt or kexec based reboot of the system. Note that this does not shut down any services and immediately transitions into the reboot process. These functions are normally only called as last step of shutdown, and should not be called directly. To shut down the machine it is a much better choice generally to invoke Reboot() and PoweOff() on the logind manager object. See On logind for more information."

so logind api is at https://www.freedesktop.org/wiki/Software/systemd/logind/ 
"PowerOff(), Reboot(), Suspend(), Hibernate(), HybridSleep() results in the system being powered off, rebooted, suspend, hibernated or hibernated+suspended. The only argument is the PolicyKit interactivity boolean (see above). The main purpose of these calls is that they enforce PolicyKit policy and hence allow powering off/rebooting/suspending/hibernating even by unprivileged users. They also enforce inhibition locks. UIs should expose these calls as primary mechanism to poweroff/reboot/suspend/hibernate/hybrid-sleep the machine."

```gdbus introspect --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1
node /org/freedesktop/login1 {
  interface org.freedesktop.login1.Manager {
----
interface org.freedesktop.DBus.Properties {
  };
```
so 
```
elif method == 'Logind':
    name = 'org.freedesktop.login1'
    path = /org/freedesktop/login1
    interface = org.freedesktop.login1.Manager
    pinterface = None
```

**Comment by sanderjo** [comment]
Ah, Logind, not Manager.

I tried your code (with a bit of quotes added), and I get an org.freedesktop.DBus.Error.AccessDenied

Advice?

Disclaimer: I have zero experience with dbus.

```
>>> import powersup_linux

>>> proxy, interface, pinterface = powersup_linux._get_systemproxy('Logind')

>>> proxy
<ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0x7f7b99713950> :1.3 /org/freedesktop/login1 at 0x7f7b9649f250>


>>> proxy.Get(interface, 'can-hibernate', dbus_interface=pinterface)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 4 matched rules; type="method_call", sender=":1.1005" (uid=1000 pid=8433 comm="python ") interface="(unset)" member="Get" error name="(unset)" requested_reply="0" destination=":1.3" (uid=0 pid=725 comm="/lib/systemd/systemd-logind ")

>>> proxy.Hibernate(dbus_interface=interface)
ERROR:dbus.connection:Unable to set arguments () according to signature u'b': <type 'exceptions.TypeError'>: More items found in D-Bus signature than in Python arguments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: More items found in D-Bus signature than in Python arguments

```

**Comment by BrendanBall** [comment]
I also have zero experience with dbus. I'll try figure it out this weekend.

**Comment by BrendanBall** [comment]
I have created a pull request at https://github.com/sabnzbd/sabnzbd/pull/939 . It will need some testing from people who still use UPower, ConsoleKit or DeviceKit. Also I wasn't able to test the linux_hibernate changes because I don't have hibernation setup on my machine. If no one else can test hibernation then I can always just revert the changes for the hibernation.

**Comment by jcfp** [comment]
Thanks for that. There's a recent [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862673) about this in debian as well, requesting logind support for handling shutdown etc. I'll link to this bug and the pr, maybe the reporter can test the suggested changes; my own system isn't setup for this.

**Comment by sanderjo** [comment]
I'm now abroad, so I can't test right now. Hopefully tomorrow evening.

BTW: d-feet is cool! 
![d-feet screenshot](https://cloud.githubusercontent.com/assets/1273502/26765367/ffae1f4e-497a-11e7-8767-3d7f0dd239f6.png)

**Comment by BrendanBall** [comment]
@sanderjo np, this will only go in the next release if at all so there's no rush at the moment. D-feet is indeed cool to test out existing dbus methods. when you get to actual testing of the dbus methods in the code it's not the greatest experience when dealing with power controls, especially shutdown  :< . Short of commenting out that the actual shutdown call, I'm not sure about the best way to develop around this kind of functionality. One way could be if it's possible to run the code inside a docker container where the container just exits on shutdown. It's probably also possible to mock out dbus in a test, but for that I need to better understand dbus and the python wrapper.

**Comment by sanderjo** [comment]
First results with your PR:

```
>>> import sabnzbd.powersup

>>> sabnzbd.powersup.linux_hibernate()
```

... does not do anything.
```
>>> sabnzbd.powersup.linux_standby()
```
... does work: laptop (Ubuntu 17.04) goes to sleep. Good.

Relevant lines from `journalctl`

```
jun 06 19:30:15 Stream-13 repowerd[729]: LogindSystemPowerControl: dbus_PrepareForSleep(true)

jun 06 19:30:19 Stream-13 systemd[1]: Reached target Sleep.
jun 06 19:30:19 Stream-13 systemd[1]: Starting Suspend...
```

**Comment by Safihre** [comment]
@sanderjo is hibernate enabled on your device? Or only sleep? 
Can you see what the correct hibernate command would be with that browser?

**Comment by BrendanBall** [comment]
@sanderjo so I spent some time today setting up hibernate on my system. There is a small bug in my hibernate where it doesn't actually shutdown completely, though if I turn my pc off forcefully at that point with the power button, and turn it on again it successfully  resumes from hibernate. So we can assume hibernate works on my system. 
I've tested hibernate with my PR and it works exactly the same as just running `systemctl hibernate`.

some relevant journald:
```
Jun 11 10:04:27 brendan-pc systemd[1]: Started Hibernate.
Jun 11 10:04:27 brendan-pc systemd[1]: sleep.target: Unit not needed anymore. Stopping.
Jun 11 10:04:27 brendan-pc systemd[1]: Stopped target Sleep.
Jun 11 10:04:27 brendan-pc systemd[1]: Reached target Hibernate.
Jun 11 10:04:27 brendan-pc systemd-logind[594]: Operation 'sleep' finished.
Jun 11 10:04:27 brendan-pc systemd[1]: hibernate.target: Unit is bound to inactive unit systemd-hibernate.service. Stopping, too.
Jun 11 10:04:27 brendan-pc systemd[1]: Stopped target Hibernate.
Jun 11 10:04:27 brendan-pc dbus[591]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jun 11 10:04:27 brendan-pc NetworkManager[593]: <info>  [1497168267.1025] manager: wake requested (sleeping: yes  enabled: yes)
```

@sanderjo which linux distro are you running? Have you actually setup hibernate on your system? does `systemctl hibernate` also do nothing?

As far as my testing goes the systemd changes works correctly, however I'm not sure who can test all those deprecated apis that we're still supporting to make sure I didn't create a regression.

**Comment by sanderjo** [comment]
Hi @BrendanBall, a status update from my side:

I have a few 'obstacles' in doing the review: 
- I don't fully understand the current SAB powersup.py code
-  Your PR is a lot of changes. Maybe some lines are just indentation changes, but that is not clear to me. Apparantly it was not possible to just put in the systemd stuff with less changes to the rest of the code?
- I wonder why you put in the two special, 'global' variables:
```
_IS_NOT_INTERACTIVE = False
_LOGIND_SUCCESSFUL_RESULT = 'yes'
```
- I have not yet spent enough time on it.

**Comment by BrendanBall** [comment]
those 2 variables are just meant to be constants to make it easier to maintain and read.
eg. `proxy.Hibernate(_IS_NOT_INTERACTIVE, dbus_interface=interface)` vs `proxy.Hibernate(False, dbus_interface=interface)`, you would have no idea what that boolean means.
I had to make quite a lot of changes because the dbus interface for logind is quite different to the others. 
eg. the methods Hibernate, PowerOff, Suspend all take in a boolean parameter compared to the other interfaces whose corresponding methods take in no parameters. 
Checking whether the interface supports a method is also different.
eg. for systemd suspend it's `proxy.CanSuspend(dbus_interface=interface)` which returns a string of `yes` or `no` for some reason. Compared to the other interfaces you check a property with `proxy.Get(interface, 'can-suspend', dbus_interface=pinterface):`.

**Comment by sanderjo** [comment]
Hi,

In the meantime I spoke to @Safihre , and he asked me to just test if your PR works on my Linux (fresh install of Ubuntu 17.10).

The results:

Hibernate does not work:
```
sander@R540:~/git/BrendanBall-sab$ time python -c "import sabnzbd.powersup; print sabnzbd.powersup.linux_hibernate()"
None

real	0m10,489s
user	0m0,400s
sys	0m0,056s
sander@R540:~/git/BrendanBall-sab$
```

... so ... 10 seconds delay, and then ... nothing.


Standby does work:

```
sander@R540:~/git/BrendanBall-sab$ time python -c "import sabnzbd.powersup; print sabnzbd.powersup.linux_standby()"

None

real	0m10,482s
user	0m0,400s
sys	0m0,048s
sander@R540:~/git/BrendanBall-sab$
```

I will test with the current SABnzbd code (so: without systemd), and see what happens.

**Comment by sanderjo** [comment]
Results for SABnzbd 2.1.0:

Hibernate:
```
sander@R540:/usr/share/sabnzbdplus$ time python -c "import sabnzbd.powersup; print sabnzbd.powersup.linux_hibernate()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sabnzbd/powersup.py", line 192, in linux_hibernate
    if proxy.Get(interface, 'can-hibernate', dbus_interface=pinterface):
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'can-hibernate'

real	0m0,465s
user	0m0,404s
sys	0m0,048s
sander@R540:/usr/share/sabnzbdplus$ 
```

Standby:

```
time python -c "import sabnzbd.powersup; print sabnzbd.powersup.linux_standby()"

```

**Comment by BrendanBall** [comment]
@sanderjo That is why this PR exists. Both Ubuntu and arch use systemd, I think ubuntu completely moved over to systemd in 14.10 or 15.04. I don't think any of those deprecated apis support systemd even if you had them installed. 

@sanderjo regarding hibernate not working for my PR, can you please test your hibernate with `systemctl hibernate`. Does that actually hibernate your system or does it also do nothing? If it does nothing then your system isn't setup for hibernate.

**Comment by sanderjo** [comment]
@BrendanBall 

Yes, I will check with `systemctl hibernate`. I'll access to that computer tomorrow.

**Comment by sanderjo** [comment]
Follow-up:

I disable Secure Boot on my Stream-13, and I do get different messages now, but Hiberante is still not working.


sander@Stream-13:~$ systemctl hibernate
Failed to hibernate system via logind: Access denied
A dependency job for hibernate.target failed. See 'journalctl -xe' for details.

sander@Stream-13:~$ sudo systemctl hibernate
sander@Stream-13:~$

**Comment by Safihre** [comment]
The 10 second wait seems to be a general thing, we send the command on all OS's and then wait 10 sec while it executes. 
But indeed, we need to show a `logging.warning` when the hibernation was tried but isn't working. Is this possible? Since it doesn't thrown an error to catch. Maybe we should just store the time and compare if more than 10 seconds passed?

**Comment by sanderjo** [comment]
I now have this (ugly) logging in powersup:

```
sander@Stream-13:~/git/Brendan-sab$ time python -c "import sabnzbd.powersup; print sabnzbd.powersup.linux_hibernate()"
SJ1 2017-06-16 07:58:14
SJ3: proxy from get_sessionproxy not found 2017-06-16 07:58:14
SJ4: proxy from get_systemproxy('Logind') <ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0x7fa4246dbfb0> :1.1 /org/freedesktop/login1 at 0x7fa42aa61050> 2017-06-16 07:58:14
SJ4xx: CanHibernate is no
SJ6xxx: CanHibernate is no
None

real	0m2,971s
user	0m0,832s
sys	0m0,080s
sander@Stream-13:~/git/Brendan-sab$ 
```

**Comment by Safihre** [comment]
Why debug? It seems this should be a `warning` so that the users sees it in the GUI?
Can you share what modifications you made so we can incorporate them?

Want to do a 2.2.0Alpha1 today and would be nice if this can be in it, for testing.

**Comment by BrendanBall** [comment]
@Safihre The thing is we're trying to support multiple interfaces. If we were only supporting systemd then maybe that should be a warning. In my PR if none of the interfaces work then I'm logging to info
```
logging.info('DBus does not support Hibernate')
```
So you can maybe make those lines a warning instead?

@sanderjo so you need to setup hibernate properly on your system before you can test this properly then. can you please give the error logs from journald as to why hibernate doesn't work on your system? As mentioned in the error you can run `journalctl -xe` to get the logs right after you run `systemctl hibernate and get the error. Do you have swap space? As hibernate requires swap space.

**Comment by sanderjo** [comment]
@BrendanBall Yes, I agree, and I appreciate if you could help. However: that is (very probably) a problem on my two computers, not in your code. So I propose I start a thread for each computer so that we can exchange info without polluting this thread. OK?

**Comment by Safihre** [comment]
Oke I will merge it now then, since the situation is the same as now (no warning, just logging).
