### ISSUE TITLE
Drop PowerPC support for OSX

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#932]
Last OSX release supporting PPC was Mac OS X 10.5 Leopard of 2007.
We still supply the binaries of unrar/unzip/par2 to run on it, but I doubt the DMG would even start on it.

**Comment by Safihre** [comment]
Additionally I would like to drop support for 32 bit CPU's.
Apple has stopped selling them since 2008 and has dropped support for 32 bit in OS X 10.8 Mountain Lion of 2012.

**Comment by thezoggy** [comment]
Do we even support 10.5?

**Comment by Safihre** [comment]
Doubt it!

**Comment by shypike** [comment]
PowerPC support has stopped working long ago. Any remains can be removed.
I see no pressing reason to drop 32bit support. Does it cost us anything?

**Comment by Safihre** [comment]
@shypike Mavericks (10.8) is 64bit-**only**, isn't that kind of the lowest version we want to support anyway?

**Comment by Safihre** [comment]
Yes, the 1.x.x series was also only Maverick+, so we can drop 32bit!

**Comment by thezoggy** [comment]
The key is 32bit only cpu.. we are still keeping the 32 utilities correct?

**Comment by Safihre** [comment]
Apple themselves don't support 32bit CPU's anymore since 10.8. 
We haven't supported 10.8 since last year. So 64 bit can go.
