### ISSUE TITLE
sab -- config / line speed

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#934]
we offer: `B/s`, `KB/s`, `MB/s`
might be time to add `GB/s` ?

also we should prob add a little line about the whole Mbps vs MBps.. as its a common issue brought up in irc. internet providers usually list their speeds as Mbps, example with google fiber `1,000 Mbps`

> 8 Megabits per second is equivalent to 1 Megabyte per second (ie. 8 Mbps = 1 MBps)

1G speeds are becoming more common in the usa, and people doing seedboxes a lot of times have 1G or 10G lines....

https://www.verizon.com/home/fios-gigabit-connection/
https://www.centurylink.com/fiber/benefits/
https://fiber.google.com/cities/austin/
https://www.xfinity.com/gig

**Comment by Safihre** [comment]
Sure, why not, I can add GB/s.

For the MPBs we would have to do some conversion with javascript, so the user would then still see the converted MB/s value after page reload (because that's how it's saved in the ini). Wouldn't that be confusing?
@sanderjo Thoughts?

**Comment by Safihre** [comment]
Actually adding GB/s doesn't make sense. You would need a 10GBPs line to theoretically get to speeds of more than 1024MB/s. 
Nobody in their right mind would use SABnzbd in that case 😆

**Comment by sanderjo** [comment]
I would do the opposite: remove B/s, KB/s, and thus only have MB/s. It's 2017, and any speed (DSL, Coax, Fiber, 3G, 4G, FE, GigE, 10GigE) can be represented in MB/s. 

With only MB/s things will we clearer and cleaner, and that avoids mistakes like this one: https://forums.sabnzbd.org/viewtopic.php?f=2&t=22706#p112130

**Comment by labrys** [comment]
@sanderjo personally I like having KB/s.  Not sure I would ever use B/s though.

**Comment by Safihre** [comment]
Some people might still have Bytes or KB in their config's. We would have to do some conversion to always show MB/s but that might be ugly.

**Comment by Safihre** [comment]
I think we stick with the current drop-down, besides this one guy having a problem we haven't had problems of users setting wrong speeds ever since introducing the drop-down.
