### ISSUE TITLE
sabnzbd on macosx opens firefox instead of default browser via applet

### ISSUE THREAD

**Issue by hagabla** [sabnzbd/sabnzbd#941]
Fun fact, if chrome is running it opens chrome, not the default browser

**Comment by Safihre** [comment]
We know, but we cannot fix this. This is a bug in Python and/or macOS, we hope Apple will fix it soon. Something changed on their side, but no clue what.

**Comment by Safihre** [comment]
Apple has fixed it for the next macOS release: https://bugs.python.org/issue30392#msg294865
So eventually it will work again :+1:
