### ISSUE TITLE
Only support PPA for Debian based systems 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#947]
Pinging @jcfp: to avoid users installing ancient versions of Sabnzbd via `apt install sabnzbd` without the PPA, I wondered if it was possible to 'withdraw' sabnzbd from the official repos? 
So that they would have to install it via the PPA (preferably the `nobetas` version) and thus are more up to date? 

Today we had a forum post of a user of a Raspberry that still used 0.7.20, even though that's horribly slow for such systems.

**Comment by jcfp** [comment]
Not sure if it can be done retroactively, or even be worth bothering given the large number of distributions that are based on few base distribution such as ubuntu and debian.

That aside, I would caution against such a step. Most users won't look beyond whatever they find in official repos, and even those that use ppas generally do so only for a specific subset of high interest programs. While I understand a dev's desire to have everyone use the very latest and enjoy the recent improvements asap, for most people 'things just work' as is. The biggest effect of a removal would be probably be losing most of your user base on the effected platforms.

**Comment by thezoggy** [comment]
Won't they get an upgrade notice if we put one in the branch version check file?

**Comment by Safihre** [comment]
Oke it makes sense, maybe better something than nothing.
If they ever click a help-link on SAB older than 1.2 they will land on this page, directing them to upgrade:
https://sabnzbd.org/wiki/configuration/deprecated.html

**Comment by Safihre** [comment]
@jcfp would you mind if I rewrite the wiki page to focus on the PPA first?

**Comment by jcfp** [comment]
@safihre what exact wiki page are we talking about here?

**Comment by Safihre** [comment]
This one: https://sabnzbd.org/wiki/installation/install-ubuntu-repo
So not to first suggest the direct apt-get install without adding the PPA.

**Comment by jcfp** [comment]
No problem
