### ISSUE TITLE
Feature request: Add Dereferer (Anonymous refering) to all links

### ISSUE THREAD

**Issue by Fish2** [sabnzbd/sabnzbd#949]
Add Dereferer (Anonymous refering) to all links to other pages outside of sab so they don't know where you came from with a option to change to a host of your choice.

**Comment by Safihre** [comment]
Which links? The ones to our own website?

**Comment by Fish2** [comment]
yes your site and also github and irc

**Comment by jeffgeorge** [comment]
I can see adding an anonymizer to outbound links from the SABnzbd interface, because that could leak customer IPs to the destination.

**Comment by Safihre** [comment]
Feel free to submit a nice clean PR for this, I personally don't think it's nessecary at all since it's really only GitHub and our own website (IRC is an internal link, like `tel:`/`mailto:`) so doesn't seem worth the trouble to me.

**Comment by thezoggy** [comment]
can do what we did in sb, add config>special argument to set a anon redirect url.
so that way the user can set one/change it if need be. this seemed to make everyone happy and prevent the app from breaking one day if the linked site stopped working


```
What this does is prevents your local SB install from appearing in the backlink statistics of another web-page.
There are a whole bunch of link protection / anonymizers out there, just make sure you use the proper URL (ends with ?) if you change the default.
```

so then when we startup sab we can do something like:
```
        ANON_REDIRECT = check_setting_str(CFG, 'General', 'anon_redirect', 'http://dereferer.org/?')
        # attempt to help prevent users from breaking links by using a bad url
        if not ANON_REDIRECT.endswith('?'):
            ANON_REDIRECT = ''
```

then anywhere we want to use it, you stick the onclick segment in the link like:
`<a href="http://synology.com/" onclick="window.open('${sabnzbd.ANON_REDIRECT}' + this.href, '_blank'); return false;">Synology Indexer</a>`


anywyas ill submit a pull for this if safihre is good with this solution

**Comment by Safihre** [comment]
Oké sounds good.

**Comment by thezoggy** [comment]
started to add this, although I'm somewhat at a lost at what links we need to actually do this to.... only real links we have are to the github related pages...

**Comment by Safihre** [comment]
Exactly why I don't think this is necessary...

**Comment by albino1** [comment]
The only thing I can think of is in 0.7.x (at least in Plush) there was the star icon labeled Open Information URL which opened the NZB Details link to the indexer the NZB came from.  I don't know where that link is in Glitter though, I assume it was removed.

**Comment by Safihre** [comment]
So, I guess we all agree this is not necessary? :+1:

**Comment by TheFreshPrinceOfBel-Air** [comment]
Just weighing in here: I still like this idea. For GitHub links, outbound nzb indexer links (I do still use the Plush theme 😛), and all other external links, I would rather my IP/local port/url base/etc not be leaked out to those external services.

**Comment by Safihre** [comment]
Plush is deprecated in the sense that it's not considered anymore. 
As @thezoggy mentioned, there are no other links, only Github and sabnzbd.org..

**Comment by Safihre** [comment]
If anyone submits a PR, we will consider it of course :l

**Comment by TheFreshPrinceOfBel-Air** [comment]
Cool, will take a look a look at this when I get a chance. @thezoggy how far did you get? Don't want to do duplicate work :)

**Comment by thezoggy** [comment]
I had the config coded then went to figure out where to actually use the code.. and then questioned why we would even do this... so I scraped the code and moved on :)

**Comment by TheFreshPrinceOfBel-Air** [comment]
Yea that seems to be the general consensus. It occurs to me that I could also write a browser extension that will handle the dereferer-ing automatically (which would be nice as this would cover all other apps on my local network, not just Sonarr).
