### ISSUE TITLE
[REQ] Split combined NZB's in seperate download tasks for faster processing

### ISSUE THREAD

**Issue by piejanssens** [sabnzbd/sabnzbd#95]
A combined NZB which for example contains several episodes would be processed faster if it was split into separate download tasks. Downloading ep2 would continue while ep1 is post processed for example. In addition it is much clearer to the end user which of those episodes have failed. Currently if one episode fails it appears as the whole combined NZB failed.

**Comment by Safihre** [comment]
Labeling this as `Won't fix` since it adds complication and with current state of obfuscation, it seems like a feature that wouldn't be too usefull in the future.

**Comment by thezoggy** [comment]
if someone really wanted to do this, sickbeard has had this feature forever ago.. 
https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/nzbSplitter.py

but this only works well when you know what your getting is a tv season pack..

**Comment by Safihre** [comment]
With current levels of obfuscation, this will rarely work anymore nowadays.
