### ISSUE TITLE
Opens Firefox browser instead of default browser

### ISSUE THREAD

**Issue by simon-hayden** [sabnzbd/sabnzbd#951]
**Summary**
When interacting with SABnzb using the menu bar application in Mac OS, a new tab or window is opened in the browser with SABnzb 'Queue' when clicking, for example, 'Idle'. 

Since SABnzb v2.0, this interaction launches the Firefox browser, even though it is not my default browser. Prior to 2.0, this worked as expected. I didn't see an existing issue report on this, which suprised me.

**Expected results**
SABnzb opens tab or window using default browser (Safari in my case)

**Actual Results**
SABnzb opens tab or window using Firefox, regardless of default browser settings, etc

_Mac OS Sierra 10.12.5
MacBook Pro (Retina, 13-inch, Mid 2014)_

**Comment by sanderjo** [comment]
Isn't that the same known problem in MacOS and/or Python (not SABnzbd)? See:

https://forums.sabnzbd.org/viewtopic.php?f=3&t=22676&p=112142
https://forums.sabnzbd.org/viewtopic.php?f=3&t=22715

**Comment by Safihre** [comment]
Indeed, this is an Apple bug that will be fixed in the next update of macOS, not related to sabnzbd at all. 
See: https://github.com/sabnzbd/sabnzbd/issues/941
