### ISSUE TITLE
Action when encrypted RAR is downloaded, abort setting.

### ISSUE THREAD

**Issue by zerocarbthirty** [sabnzbd/sabnzbd#955]
Ver 2.2.0Alpha1 [8483e4a]

Hi, on the listed version when "Action when encrypted RAR is downloaded' is set to "abort" sab appears to still try and unpack the archive using a random piece of the filename. Which is pointless and slows down the processing of other RARs. 

I believe it should simply mark the archive as failed and move forward.

**Comment by Safihre** [comment]
> still try and unpack the archive using a random piece of the filename

Sorry I don't understand, what does it do?

**Comment by zerocarbthirty** [comment]
It says in the 'processing area' under 'show failed' trying to unpack with password "xxxxxxx" where xxxxxx is part of the rar's filename. It's super confusing. If it's set to abort shouldn't it just stop processing?

**Comment by Safihre** [comment]
Maybe you can share the NZB and the filename? That way I can test and understand what it is doing!

**Comment by zerocarbthirty** [comment]
This is exactly what it says in the processing area:

  	<295>-[01	    
» Unpacking: 02/81 
» Trying unrar with password "93] - "295.par2" yEnc" 

no clue why it's doing this.

**Comment by zerocarbthirty** [comment]
It looks like it would be somewhere near here. If it is set to abort it should never get this far.

https://github.com/sabnzbd/sabnzbd/blob/ef1cb05bc8aa5594c8a9abbc9f9ab7cb53f5ccf5/sabnzbd/newsunpack.py#L534

**Comment by Safihre** [comment]
Oke, but if you could share the file I can _much_ much more easily debug :wink:
Can also send it to safihre@sabnzbd.org, if you prefer that!

**Comment by Safihre** [comment]
The job you are sending here is not encrypted, so that's why it wasn't aborted.

**Comment by zerocarbthirty** [comment]
Okay.

This link https://sabnzbd.org/wiki/advanced/password-protected-rars

is why I am confused. Also why would it try to use an arbitrary piece of
the filename as the password rather than just aborting?

**Comment by Safihre** [comment]
The reason it detects it as a password, is because there was a slash in the original filename:
```
<post.post>-[01/72] - "post.post-Sample.mp4" yEnc
```
SABnzbd supports supplying a password by giving them as part of the filename, using a `/` or `{{password}}`.

Did you add this job via RSS?
Did you by any chance change in Config > Specials the value of `rss_odd_titles`, because `nzbindex.nl` is in there normally for this reason so that it gets filtered.

**Comment by Safihre** [comment]
Jobs will only be aborted if they are actually encrypted, independent if a password was found or not.
After the first rar file comes in, we check if it is encrypted, if not the download continues. If it is encrypted, we try all the supplied passwords, and if they (all) fail only then we Abort.

**Comment by zerocarbthirty** [comment]
Hi,

rss_odd_titles is set to this:

nzbindex.nl/, nzbindex.com/, nzbclub.com/

but it wasnt added via RSS it would have been added via SC++

**Comment by zerocarbthirty** [comment]
Also I forgot to say thanks.

at least I know why its doing what its doing even if I cant change it. :)

**Comment by Safihre** [comment]
It's indeed the extension that sending the title of the job in a weird format, causing Sab to try extract it.

**Comment by Safihre** [comment]
That's the job of the extension submitting the NZB to sabnzbd.

**Comment by zerocarbthirty** [comment]
Oh, okay but if I am not mistaken the title of the post includes the '/'
character so it's just passing what is there. I will see if I can figure
out how to change it at the extension then.

'/' is a pretty common character to have in multi-part binaries it usually
shows how many parts/rar files are in an archive like [0/10] etc.

Anyway thank you for your help!
