### ISSUE TITLE
Option to leave base.par2 after +repair action

### ISSUE THREAD

**Issue by zaadstra** [sabnzbd/sabnzbd#956]
Hi,

I upgraded to 2.1.0 from a rather old version.

After download and repair (if needed),  a .par2 file was left.  I like that behaviour very much as I can use it as an integrity file after the files are copied to other places.  Or just when the harddrive got rotten ...
I only use +repair and keep the archives.

I can't find an option to switch this on again.  I think this behaviour has changed in new versions.
Is it possible to create an option to leave the .par2 file (or files after the repair), just as in the old 7.x software?

Thanks,

Hans

**Comment by Safihre** [comment]
This behavior was removed in 2.1.0, but it's back in 2.2.0 (currently still in Alpha testing). 
You need to disable  the option in Config Specials `enable_par_cleanup`.

**Comment by zaadstra** [comment]
Ahh big thanks for your reply and good to hear it will be back.  Did not see a relevant switch now in the Config Specials.
Would it be an option to comment out the 'delete command lines' in one of the .py files?  I'd been browsing somewhat around but did not see it.

**Comment by Safihre** [comment]
No, there's no easy way to hack it back in. 
Give 2.2.0 a try, should be stable enough :)

**Comment by zaadstra** [comment]
Hmmm how soon will it be released and packed by Synocommunity?

**Comment by Cpuroast** [comment]
if you are on the stable version on Synocommunity, whenever 2.2 reaches stable, it's currently on alpha 2.

While Synocommunity has a testing version, it's still on 2.1 also: https://synocommunity.com/package/sabnzbd-testing

**Comment by thezoggy** [comment]
2.2.0 Alpha2 reporting bad par2 settings: 88bc209daf0b961f73fb07e768e2155692e1bb16] PAR2 received incorrect options, check your Config->Switches settings

Haven't seen this before on any previous versions.. on airplane will check more when I land

**Comment by Safihre** [comment]
If you have set par2tbb parameters, these will give problems on Multipar. Been like that since 2.1.0.

**Comment by thezoggy** [comment]
You may want to nuke them if your going to force people to multipar in 2.2.0

**Comment by Cpuroast** [comment]
not sure if nuking them outright is best, maybe notify the user on sabnzb startup that there are invalid par2 params configured.

I think Safihre wants to remove the multipar special flag will eventually.

**Comment by thezoggy** [comment]
I really hope he doesn't. I like the ability to fallback to another par app..

**Comment by Safihre** [comment]
Did you have parameters set? If not, then this is a bug for a seperate issue (we are getting a bit off topic here). 

Having to deal with all the stupid oddities such as long path notation, forbidden windows names and UTF8 that we have to support workarounds for in par2cmdline/par2tbb on Windows that work perfect in Multipar. Why possibly keep those? Multipar has worked impeccably in all cases without workarounds.

**Comment by thezoggy** [comment]
They are listed above

**Comment by Safihre** [comment]
@zaadstra, will push update to SynoCommunity soon. But you'll have to switch to the sabnzbd-testing version.

**Comment by Safihre** [comment]
Submitted to SynoCommunity for the `sabnzbd-testing` packages. Should be available soon.
