### ISSUE TITLE
Feature request: 100% browser width .container

### ISSUE THREAD

**Issue by Djenan** [sabnzbd/sabnzbd#957]
Makes the web UI more space efficient.

**Comment by Safihre** [comment]
No that doesn't work. Everything is set to work with the default Bootstrap CSS size increments so that at every size, it all fits.

**Comment by Djenan** [comment]
Bootstrap is limited in that it attempts cater for all  situations with a single solution. I find it frustrating that the web UI doesn't resize fluidly with the browser window because there's wasted space either side of the .container. Is it possible to contribute a UI?

**Comment by Safihre** [comment]
You can add an extra option in the Interface settings of the  Glitter Status and Interface window to achieve this maybe using some JavaScript.

**Comment by Djenan** [comment]
That's a good idea. Thank you.

If I was keen to keen involved in the project, how would I go about it? I understand if the participant group is closed at the moment.

**Comment by Safihre** [comment]
We gladly welcome contributions, just make your changes and submit a pull request :)

**Comment by Djenan** [comment]
Do I need permissions to publish a branch before submitting a pull request?

**Comment by Safihre** [comment]
Aah, you can just create a Fork on your own account using the Fork button on top.
Then you can submit a pull request back to the main project.

**Comment by Djenan** [comment]
Brilliant! Thank you for your help and your receptive comments :)

**Comment by Safihre** [comment]
That's also how I started with sabnzbd, I hated the old skin Plush :wink:

**Comment by Safihre** [comment]
@Djenan found time to implement the new feature? :)
