### ISSUE TITLE
RSS Checking Interval - at least 15 min. -> Why the F*ck you force people to do this?

### ISSUE THREAD

**Issue by scriptzteam** [sabnzbd/sabnzbd#958]
Please why the foking god you force people to use at least 15 min. What if i want poll my OWN rss every 1 min. or every 5 sec.? Do i really need to go thru source code? Thats silly right ;)

Please add option to do it right, and oh i love sabnzbd but please let give us some freedom, dont be policy! :)

P.S.: for me its just 1 min. job do remove your 15min. "check" but the others may lost :D 

If anyone want 1 minute rss check here it is:
https://github.com/scriptzteam/sabnzbd/commit/94e5b2b540a16c16d1b3aef3e2401ae9a708bbce
https://github.com/scriptzteam/sabnzbd/commit/18d00d9d58ae4f28f522f6d5e010161695bd6f59
https://github.com/scriptzteam/sabnzbd/commit/2fa2cac22c98f86fc5de958a3570bbbb1abb7277

**Comment by Hellowlol** [comment]
I think its about protecting the indexers from abuse and at the same time sabnzbd reputation. I get that your knows your shit running  your own and all but this a tool for the masses. Not everybody is that responsible. Just see how some indexers blocked sickrage a while back.

Anyways thats my 2 cents.

It could be a commandline parameter or something.

**Comment by scriptzteam** [comment]
Just updated my first post to see it is done to get 1 minute check :D

**Comment by Safihre** [comment]
What if you just change it in your sabnzbd.ini?

**Comment by scriptzteam** [comment]
@Safihre, i did it but this way it not worked for me :D and also i wanted to do it in interface not via editing conf file(s) :)

**Comment by Safihre** [comment]
We understand your expert use case and luckily it works like this, but we also have thousands of less experienced users that we want to keep from bombing the indexers just because they think they need 1min syncs 😃

**Comment by thezoggy** [comment]
in the nzedb support channel just this morning:
>	is anyone else seeing nzbget hammering their RSS endpoints? I'm seeing many users making dozens of requests in a minute coming from nzbget
