### ISSUE TITLE
Watching Subfolders Not Named As Categories

### ISSUE THREAD

**Issue by Jdogzz** [sabnzbd/sabnzbd#963]
As a request, it would be nice if the watching feature would recursively search any subfolders in the watching directory that aren't named as a category.

**Comment by Safihre** [comment]
@shypike Any idea why it doesn't do this? It only scans category-named folders.

I can imagine this was done to prevent being too aggressive and only really scanning the Watched-dir, not the Watched-subdirs.
This behavior has been there since 10+ years, so I am a bit hesitant to change it since many users would assume this behavior.

**Comment by jcfp** [comment]
The reason for the current behaviour seems obvious: given enough subdirs, the repeated scanning of the watchdir could have a serious performance impact. There's inevitably going to be users whose choice of watchdir is the root of an entire disk, their "desktop", or the basedir where they hoard all their downloads. The number of subdirs could be insanely large.

Better question is: what's the gain? Why dump an nzb into some random subdir with the intention of adding it to the queue in the default category?

**Comment by Jdogzz** [comment]
I think it is reasonable enough to make the behavior toggleable (and, by default off, so as to preserve the expected behavior for users, as @Safihre pointed out).

@jcfp The performance impact makes sense. The gain, at least in my case, is my experience yesterday when downloading a zipped file of nzbs for an indexer where some of the nzbs were in the root directory, while others were one subfolder deep, and it would of course be tedious for me to go through and bump all the nested nzbs one folder up.

**Comment by thezoggy** [comment]
yeah, not sure this is a proper solution for a bad workflow...

**Comment by Safihre** [comment]
Seeing that this is the first time this switch is requested since the existence of the behavior (10+ years) I do not think we will implement it. It seems to exotic and can just be solved by some dragging and dropping or unpacking the archive with `ignore folders` (this is an option of Unrar).
