### ISSUE TITLE
RSS Feed with commas broken

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#965]
https://forums.sabnzbd.org/viewtopic.php?f=2&t=22833&p=112665

For example `https://rss.domain.tld/rss-genre-download.php?tagid=107, 58, 71, 108, 20, 90, `

**Comment by thezoggy** [comment]
thats invalid url.. but guess we could urlencode it so spaces are %20 ?

**Comment by Safihre** [comment]
It's the `,` that needs the encoding, because it get's wrongly seen as a list-separator by `OptionList`.

**Comment by thezoggy** [comment]
read the email wrong on my phone.. yes `,` should be allowed.. but solution still remains.. we should urlencode

`https://rss.domain.tld/rss-genre-download.php?tagid=107, 58, 71, 108, 20, 90,`
becomes:
`https%3A%2F%2Frss.domain.tld%2Frss-genre-download.php%3Ftagid%3D107%2C+58%2C+71%2C+108%2C+20%2C+90`

reference on what is/isn't allowed:
https://perishablepress.com/stop-using-unsafe-characters-in-urls/
