### ISSUE TITLE
2.2.0a3 issues

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#966]
upgraded to 2.2.0a3 and I see:
` 2017-07-16 12:58pm Enabled Direct Unpack: Jobs will start unpacking during the download, reduces post-processing time but requires capable hard drive. Only works for jobs that do not need repair.`

guess thats being enabled by default?

and then told sonarr to cancel a download for an item, 

```
2017-07-16 13:22:05,219::ERROR::[postproc:498] Post Processing Failed for Parks.and.Recreation.S04E11.720p.WEB-DL.DD5.1.H.264 ()
2017-07-16 13:22:05,219::INFO::[postproc:500] Traceback: 
Traceback (most recent call last):
  File "sabnzbd\postproc.pyo", line 463, in process_job
  File "sabnzbd\emailer.pyo", line 221, in endjob
  File "sabnzbd\notifier.pyo", line 139, in check_cat
NameError: global name 'gtype' is not defined
2017-07-16 13:22:05,219::DEBUG::[config:668] Missing configuration item email,email_cats
```

**Comment by thezoggy** [comment]
so it crashes sab, restarts and tries to notify and crashes.. rinse and repeat..

**Comment by Safihre** [comment]
That's unfortunate, strange that it didn't create the `email_cats` variable. 

Regarding Direct Unpack, the message is telling you that Direct Unpack is now enabled. 
Maybe there's something with your sabnzbd.ini if both the Direct Unpack and `email_cats` are not being saved?

**Comment by thezoggy** [comment]
so i went to the config page after updating 2.2.0a2->a3 and saw the direct unpack option but i must have have enabled it somehow... i never recall doing so however.

**Comment by Safihre** [comment]
We test if the disk speed is above 60MB/s, only then we enable it. If not, it stays disabled.

**Comment by thezoggy** [comment]
finally got sab to stop crashing (told sab to delete item).. went to config > cat and saved. now i see

```
direct_unpack = 0
direct_unpack_tested = 1
email_cats = *,
```

**Comment by Safihre** [comment]
Now enable Direct Unpack again to test it :+1:
