### ISSUE TITLE
Vague Error Message: 481 Internal Error

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#967]
Today I tried to add a new provider, but I get this error when Testing:

![481 internal error](https://user-images.githubusercontent.com/12164957/28252635-8a29aa26-6a4b-11e7-9829-6740079e62be.jpg)

Looking at the code [it appears that's from a failed username/password](https://github.com/sabnzbd/sabnzbd/search?utf8=%E2%9C%93&q=481&type=), but as you can see from the screenshot above, there's no actual indication of what that could possibly mean to the average user.

There should probably be a better error message displayed on the page than "481 Internal error".

OS: `Windows 10 Pro`
SABnzbd: `2.1.0 [443efb5] via the Win installer.`

**Comment by Safihre** [comment]
This is not a sabnzbd error code, it's directly the output of the server. So if it gives this code, we just directly display it to the user just like 'Username and password wrong' messages.

**Comment by albino1** [comment]
Ah, I see.  Good to know, thanks.
