### ISSUE TITLE
"DEBUG::[misc:1464] Applying 493 to /home/sander/Downloads/incomplete"?!

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#968]
I saw lines like `DEBUG::[misc:1464] Applying 493 to /home/sander/Downloads/incomplete` in my log. And I really thought 493 was a rule or filter.

Looking at https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L1464-L1465 I realized it had to with filesystem rights. 
And if so, what is `493` then?

Oh, wait ... decimal versus octal; file system rights are printed in octal. Not decimal, not hexadecimal.

So I changed misc.py a bit, with result:

```
2017-07-20 19:19:02,406::DEBUG::[misc:1464] Applying permissions 0755 (octal) to /home/sander/Downloads/incomplete

```

Agree? Shall I send a PR?

**Comment by Safihre** [comment]
Yes sounds good

**Comment by sanderjo** [comment]
Oh, wait: I did not think about the effect on Windows. Is that OK? Is it used on Windows?

**Comment by Safihre** [comment]
Not used on Windows.
