### ISSUE TITLE
QQ: selective retry from api?

### ISSUE THREAD

**Issue by mgaulton** [sabnzbd/sabnzbd#969]
I have a scenario where i want to retry failed downloads, but only if the script exit code was 1 (retry nzbToMedia for those jobs) i'm not seeing a way to do that.

Is there a way to query the failed job for a status?

**Comment by sanderjo** [comment]
Via the API?

If so: http://127.0.0.1:8080/api?output=json&mode=history gives "report" ... not documented in https://sabnzbd.org/wiki/advanced/api#history_main ... maybe that is the output of the script?

**Comment by Safihre** [comment]
Indeed you can extract it from the `script_line` which will always start with `Exit(1)` or `Exit(0)` depending on the result of the script.

**Comment by mgaulton** [comment]
Awesome, thanks guys.

**Comment by mgaulton** [comment]
Could i get a quick sanity check on this?



print "Starting SABretry..."
geturl = ("http://192.168.2.5:8085/api?output=json&mode=history&apikey=API")
response = requests.get(geturl)
data2 = response.json()
print "History Retrieved..."

for k in data2['history']['slots']:
    print k['name']
    if k['script_line'] == "Exit(1)":

        geturl = ("http://192.168.2.5:8085api?mode=retry&value={}&apikey=API").format(k['nzo_id'])
        response = requests.get(geturl)
        print response
        data2 = response.json()
        pprint(k)
        print  k['script_line']

**Comment by mgaulton** [comment]
nevermind, got it working :) thanks again.
