### ISSUE TITLE
setup wizard access

### ISSUE THREAD

**Issue by obouallou** [sabnzbd/sabnzbd#972]
Once setup is done,  the wizard is still accessible eventhough a login&password configuration is in place.
Anyone can then modify language, see news server address and username.

**Comment by sanderjo** [comment]
> Once setup is done, the wizard is still accessible eventhough a login&password configuration is in place.
> Anyone can then modify language, see news server address and username.

Correct. That is not just during or after the setup wizard; it is always ... UNTIL you fill out a SABnzbd Username/password in Config -> General.

And there are reasons for that:

1. Keep the wizard simple. SABnzbd has a few hundred options or so ... we don't want them in the Wizard. That would scare and/or confuse users
2. Avoid that users lock themselves out.
3. Passwords in plaintext; SABnzbd used to fill out stars for passwords, but password managers were mixing them all over in the SAB interfaces, causing all kinds of problems.

HTH

**Comment by obouallou** [comment]
The wizard is still available AFTER you fill a SABnzbd username/password in config

**Comment by Safihre** [comment]
@sanderjo: @obouallou is right, the wizard should not be available after setting a username/password.

This is quite a bad security flaw and I will fix it right away!

**Comment by sanderjo** [comment]
> The wizard is still available AFTER you fill a SABnzbd username/password in config
Ah, now I understand!

> I think it's a security flaw
Yep.


> the wizard should not be available after setting a username/password.

I would say the wizard should not be available at all after setup...?
