### ISSUE TITLE
sab 2.2.0b1 -- glitter / queue

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#977]
![sab](http://zoggy.net/firefox_2017-07-23_17-37-43.png)
* new move to top/bottom buttons had a Glitter- prefix... seems odd to show that when using glitter.
* worth showing the move to top and bottom when there is only 1 item?
* the 'edit' icon now is the only one without a tooltip..

**Comment by thezoggy** [comment]
just to note, so far testing with direct unpack seems to be fine.

but it is a bit annoying I see the direct unpack icon.. 
![sab2](http://zoggy.net/firefox_2017-07-23_17-40-16.png)
trying to hover over it.. then I get that move/edit/etc overlay..

**Comment by Safihre** [comment]
Fixing the labels, that's indeed bad.
Also fixed that the direct-unpack disappears when hovering, was old behavior from rating icons.

Lot more logs? It only logs when jobs are added and unpacked and then the UnRar output, just like normally Unrar output would.

**Comment by thezoggy** [comment]
think the logs are just hit and miss on how many times it had to directunpack/repair/par/etc.. 
~ note to self, load up the same nzb and compare with and without direct unpack to see log/times/etc.

**Comment by thezoggy** [comment]
just to note, now in sab 2.2.0RC1, can confirm that the hover overlap shows up next to the direct unpack.. but if there is a long title you see:
![sab](http://zoggy.net/firefox_2017-07-28_00-40-56.png)

**Comment by Safihre** [comment]
Yes indeed, that seemed like an elegant solution to me to let the browser handle the cut off nicely.
Why does the icon need to stay on hover?

**Comment by thezoggy** [comment]
you can see that there is still plenty of space, just though it was weird it is hidding it when it didnt need to ?

**Comment by Safihre** [comment]
No the space is taken by the extra history column in your case, which is a real `<td>` with a fixed with otherwise it's impossible to handle.
