### ISSUE TITLE
sab 2.2.0b2 - config / history retention

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#978]
ff 54.0.1 -- the placeholder for the keep max is too long with the limited width set + number type, as creates a funky cut off text:
![sab](http://zoggy.net/firefox_2017-07-24_10-36-36.png)

either we need to increase the width or shorten the placeholder text
chrome also cuts it off, but just at the end..

**Comment by Safihre** [comment]
Agreed.
