### ISSUE TITLE
sab 2.2.0b2 -- nzb report / server section

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#979]
not sure when this changed again, but the 'server' order is random. 
![sab](http://zoggy.net/chrome_2017-07-24_10-42-13.png)

it should be in the same order the user sets (to make it consistent) 
![sab2](http://zoggy.net/chrome_2017-07-24_10-44-48.png)

**Comment by Safihre** [comment]
I remember this, but cannot find any code in olders version that did the sorting. Strange. 
Implemented now.

**Comment by thezoggy** [comment]
ty!
