### ISSUE TITLE
SQL command failed, See log

### ISSUE THREAD

**Issue by joakim93** [sabnzbd/sabnzbd#981]
Have had this problem now for a couple of days.. Haven´t changed anything in my setup

Logs are here : https://gist.github.com/joakim93/4b2daf2c885c861357fbe03d86c257da

**Comment by Safihre** [comment]
It seems somehow your history database got corrupted. 
The only way to fix this is to delete `history1.db` in the `/var/db/sabnzbd/admin` folder (while SABnzbd is shutdown).

**Comment by joakim93** [comment]
That fixed it :) Thanks
