### ISSUE TITLE
feature request - dupe override for repack/proper/real 'tags' on series dupe

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#982]
when using "Detect duplicate episodes in series" option, it has 0 logic except to parse series, season, episode out. so when there is a repack/proper/real release.. sab will detect it as a dupe. we should offer an override (enabled by default?) so that these are allowed through while we still offer the ability to uncheck to restore previous behavior.

**Comment by Safihre** [comment]
Isn't Sab's duplicate detection too simple for that and shouldn't one just use sonarr, etc? 
 
What if the original file was already a repack?

**Comment by thezoggy** [comment]
sab series dupe detection is very very basic..  while personally i tell people to just disable this dupe and use the nzb dupe (crc off nzb) as its much better.. but this request should be very simple to implement and makes the series dupe much better. 

not everyone uses sonarr (i know right) :)

**Comment by Safihre** [comment]
Please go ahead and make it 👍 
Probably need to store if original  was already a repack/proper/etc, otherwise it would allow additional ones.

**Comment by thezoggy** [comment]
have this done, just need to do some testing.. there is just so many inefficient things we do with the way we do stuff for the dupe... that it is so easy to go down a rabbit hole on what to fix/deal with our shortcomings. so i backed out of a lot of changes to make it like a 2 line thing keep it simple so we can just redo the history structure later on..  i just need to make the option now toggle-able so people can turn it off to restore previous behavior. 

I discovered that a bug in 2015 i reported that got fixed? got re-introduced in 0.8.x.. 
the series+season+ep doesnt handle air-by-date (YYYY-MM-DD) shows at all..  or season packs.. or just about much.. its very crude.. thus having logic to search the db to re-parse the nzb names to see if its seen a proper/repack/rerip/etc is costly.. we just need to redo stuff to make this more sensible later on..

**Comment by Safihre** [comment]
Why not make this a big overhaul?
Combine it with what is needed for #727 (so already during download detection).

**Comment by thezoggy** [comment]
there is so many things that should be done, but its outside the scope of time i have to spend.. even this simple change i can only work on code ~1 hour a day on the days I work lately. then when the weekend comes around I'm sick at looking at a computer. :/ anyways ill have this request finished tomorrow

**Comment by thezoggy** [comment]
lets say someone had both dupe by nzb md5 and series season+ep enabled..

they add: `series.s01e02.blah.blah-group`
all good.
then they add: `series.s01e02.REPACK.blah-group`
all good (repack gets punched through)
then they add again: `series.s01e02.REPACK.blah-group`
the nzb md5 check comes first, thus rejecting/whatever they have set. 

this ends up covering both requests. also note that if you go to the dupe item and tell it to 'retry' it bypasses the md5 check and will just download.. thus giving the user the option to just override dupe logic without having to do anything to history.. so all good.

so looks like everything is working, just need to figure out what text to put for the option then ill submit it
