### ISSUE TITLE
FR: Ignore "Abort Jobs" when Post-Processing is changed to Download

### ISSUE THREAD

**Issue by albino1** [sabnzbd/sabnzbd#983]
Currently if you have `Abort jobs that cannot be completed` enabled and you change a file from `+Delete` to `Download` the file will still abort when repair is not possible, even though you're not asking SABnzbd to do any repairing.

It seems to me it would make more sense to only take the `Abort jobs` setting into account when a repair is planned, and if you're manually changing the file Post-Processing setting to `Download` then to ignore that setting because obviously you have a reason for downloading the file without repairing it, or you would just let SABnzbd handle it in the first place.

**Comment by Safihre** [comment]
But, if we detect that the files are damaged and could never be repaired, why would you want that download?

**Comment by albino1** [comment]
Some examples might be where the NZB is grouped files and you only want some of them, or downloading partial RARs/PARs from multiple broken re-uploads to recombine them yourself to complete a file.

I guess my overall point is, why even have a download-only option if it's still bound by the `+Repair` rules?  Do people use `Download` for anything other than testing and weird special use cases like these anyway?  Probably not, and in which case, having your download aborted doesn't seem like the desired outcome, because you're obviously specifically trying to do something with those files.

**Comment by Safihre** [comment]
When you hit Retry it will already ignore the `Abort jobs`, isn't that already some sort of work-a-round?

**Comment by albino1** [comment]
I wasn't aware of that, but I guess that will work since I was just trying to avoid having to change the actual setting every time.  Thanks.
