### ISSUE TITLE
Feature Request - Ability to schedule notifications on or off.

### ISSUE THREAD

**Issue by SgtBatten** [sabnzbd/sabnzbd#985]
I would love the ability to stop sab sending notifications within a set time period.

My use case is this:

I like to get nzb added notifications and job failed notifications for my popular shows throughout the day.
I use pushbullet for notifications. It allows me 400 notifications a month for free.
My Internet provider lets me download and upload for free during a 6 hour window overnight.
My setup adds any content older than 2 weeks to sab as low priority and i set these to download during this free window with scheduling.  I have hundreds of  low priority items in the queue at a time and when they start to download overnight plenty of them fail and i get lots of job failed and new nzb added notifications which eat into my 400 per month.

I would love to turn of notifications during my overnight download window as i can just check the sab history once in the morning.

**Comment by Safihre** [comment]
In SABnzbd 2.2.0 ([currently RC1 is available](https://sabnzbd.org/downloads)) you can limit notifications to certain categories, maybe you can put all those older ones in a special category and exclude that from notifications?
Would that solve it?

**Comment by SgtBatten** [comment]
Hmm that is interesting. I'll have to look into it but I am not sure sonarr and Radarr etc support multiple categories. 

Right now I am trying to remember to turn off notifications when I go to bed.

**Comment by Safihre** [comment]
Alternatively, you can use [NZB-Notify](https://github.com/caronc/nzb-notify) Notification Script.
This supports the same (and more) notification services and since it's a python script, you could just change `sabnzbd-notify.py` to include a if-statement at the top to check for the time:
```python
import datetime
now = datetime.datetime.now()
if now.hour > 22 or now.hour < 8:
    exit(0)
```
