### ISSUE TITLE
More control over URL-fetching

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#988]
Because I have only a few downloads per day I'd like to prefer some downloads:
1. I'd like to pause a single url fetching.
2. I'd like to see the name from RSS while fetching url.

**Comment by Safihre** [comment]
Usually an URL is already fetched before you know even get the chance to see the fetching, only when many are fetching this would be usefull.
It indeed wouldn't hurt to make the Pause-button pause the fetching.
For the next release of SABnzbd.

**Comment by ggzengel** [comment]
Please don't forget to add rss title to the fetch queue if it possible.

**Comment by Safihre** [comment]
@ggzengel I implemented the pausing, but the information about the RSS feed-name is not stored anywhere so I can't really display it.

**Comment by Safihre** [comment]
Found a way. Actually pretty nice to display where the URL is coming from.
Will be in the next (bigger) release of SABnzbd!

**Comment by ggzengel** [comment]
Thank you very much.
This will really help.

Do you know something about jcfp?
The repo stuck at RC1.

**Comment by Safihre** [comment]
He's enjoying is summer holiday 🌴 🌞

**Comment by Cpuroast** [comment]
Does this change means, that if sab is paused, all url fetching is paused too?

Would submitted url fetching still be in the queue, just in a paused state and only when the queue is unpaused would the urls actually be fetched?

**Comment by Safihre** [comment]
No, global pause state is not observed, only individual.

**Comment by Cpuroast** [comment]
All good then :)

**Comment by ggzengel** [comment]
@Safihre I just test the new feature and see you put the RSS queue name which is always the same. Why not putting title in front of the URL?

**Comment by Safihre** [comment]
You requested:
> I'd like to see the name from RSS while fetching url.
This is exactly what you got! 😉 
URL's are way too long, even basic URL's always include API-keys etc.

**Comment by Safihre** [comment]
Ohh, I see we had a miscommunication. 
When you say RSS title you mean the NZB title, not the title of the Feed.

**Comment by ggzengel** [comment]
I wrote or meant the name *from* RSS not the name *of* RSS queue.
I should it write more exactly but it's not my native language.

**Comment by Safihre** [comment]
@ggzengel Your suggestion is much more logical, I will implement that.

**Comment by ggzengel** [comment]
@Safihre thx

**Comment by ggzengel** [comment]
I'm very happy now.
Not only I see the names from RSS but also I see names from nzbFox on clicking NZB links.
Very good improvement. Thank you very much.
