### ISSUE TITLE
Have all time-output in UTC

### ISSUE THREAD

**Issue by ggzengel** [sabnzbd/sabnzbd#989]
My server runs with UTC and new messages are shown with "2 hours ago".
In history the times are right.

**Comment by ggzengel** [comment]
The is a little flaw on updating history details:
If you switch tabs back to sabnzbd the history completion time will be instantly updated but the detail time needs one minute to update.

**Comment by Safihre** [comment]
In Status and Interface settings you can change the time display to anything you want. 
The update of the textual-dates indeed only happens every 1 minute, since the lowest it goes is "x minutes" ago. So not needed to updated more often.

**Comment by ggzengel** [comment]
But I can't change timezone.
History shows completion time with local time (time base from browser) and queue messages are show with UTC (server time).
I have two time bases on the same page.

Only for understanding about this little flaw:
If you change browser tabs you will instantly update queue values (adding new jobs, progress bar) and history (completion time, adding finished jobs) but not history details (name, size and more are static, but not completion time). History details are only updated (completion time calculated) if browser tab is active and 1 min elapse.

**Comment by ggzengel** [comment]
If you parse time with moment you should get always utc time from server an parse it with moment.utc(string,string).
With this changes it works for me:

```
function displayDateTime(inDate, outFormat, inFormat) {
    // What input?
    if(inDate == '') {
        var theMoment = moment()
    } else {



        // UTC
        var theMoment = moment.utc(inDate, inFormat)



    }
    // Special format or regular format?
    if(outFormat == 'fromNow') {
        return theMoment.fromNow()
    } else {
        return theMoment.format(outFormat)
    }
}
```

```
                   var warningData = {
                        index: index,
                        type: glitterTranslate.status[warningSplit[1]].slice(0, -1),
                        text: warningSplit.slice(2).join('<br/>').replace(/ /g, '\u00A0'), // Recombine if multiple lines
                        date: displayDateTime(warningSplit[0], self.dateFormat(), 'YYYY-MM-DD HH:mm'),

                        // UTC
                        timestamp: moment.utc(warningSplit[0], 'YYYY-MM-DD HH:mm').unix(),



                        css: (warningSplit[1] == "ERROR" ? "danger" : warningSplit[1] == "WARNING" ? "warning" : "info"),
                        clear: self.clearWarnings
                    };
```

**Comment by Safihre** [comment]
Your solution works, assuming that SABnzbd always sends UTC dates like on your system. But that's not the case.. For both history and warnings (did not look at Queue yet) it uses local time of the system. 

To make this work for everybody, we should correctly make SABnzbd output UTC times everywhere.
This will be something to implement for the next release of SABnzbd!

**Comment by Safihre** [comment]
@ggzengel You can run SABnzbd from Github right? I just pushed a new commit to develop that should solve this problem. Could you test it?

**Comment by ggzengel** [comment]
I use jcfp's beta repro and make only little changes to not get lost my url queue.

**Comment by ggzengel** [comment]
Isn't it better to use UTC time in all time variables inside sabnzbd code (i.e. response.warnings)?
I don't know what time sources you use but the most should be time.now and can be converted to time.now.utc.
If you use always UTC, the history times are still correct even after switching DST.

**Comment by Safihre** [comment]
That would break compatibility of almost all API calls.
Looking at how other software resolves this I now altered the warnings API to use timestamps, these count from the fixed date and thus are also resistant against timezone and DST changes. MomentJs understands them and will correctly convert them on every update.

**Comment by ggzengel** [comment]
I think to have the right time (mostly on DST switching) in sabnzbd is not so relevant like in some other applications.
But we have started this discussion already and I will add this: https://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices
I would set TIMEZONE=UTC for sabnzbd. Only for scheduled tasks you have to store them with local time zone.

**Comment by Safihre** [comment]
We do what it says in the Stackoverflow answer so that's why I think DST will not be a problem 👍 

> When storing timestamps as a numeric value, use Unix time - which is the number of whole seconds since 1970-01-01T00:00:00Z (excluding leap seconds). If you require higher precision, use milliseconds instead. This value should always be based on UTC, without any time zone adjustment.

**Comment by Safihre** [comment]
@jcfp Could we get a PPA update for RC1? :) Thanks!

**Comment by jcfp** [comment]
Not yet, I'm restoring my pc after hardware failure.

**Comment by labrys** [comment]
Technically CPython's `time.time` generates time as seconds from the epoch, which is platform specific.  On most platforms this would be the same as the Unix Epoch (1970-01-01T00:00:00Z) but it does not have to be.  (But do we care? 😁 )

**Comment by Safihre** [comment]
@jcfp When I was explaining `sabyenc` inner workings to @sanderjo I found that we calculate the CRC but never use it for anything usefull, removing that part makes the download another 15-20% faster. So I will make an RC2 today with an updated `sabyenc`, since I don't want to wait for the next SABnzbd release.

**Comment by ggzengel** [comment]
@jcfp if you have restored your pc and made a new PPA release I would like to have a little notice here for testing this patch.
@Safihre what is about the scheduled times? Would you put user relative time and include TZ and convert them on usage to server relative TZ as described here: http://www.creativedeletion.com/2015/03/19/persisting_future_datetimes.html

**Comment by Safihre** [comment]
No, scheduler times are server times and not going to do anything about that. People having such setup will figure it out.

**Comment by jcfp** [comment]
@ggzengel rc1 is up

@Safihre thanks for the heads-up, I'll deal with rc2 once I find more time

**Comment by Safihre** [comment]
@jcfp thanks! Will probably do 2.3.0 Final next Friday so can also just wait for that. 
We seem to be running into the issue that it's always the same people downloading the testing releases, so really deep bugs will only show up when we do a full release.  For example 2.2.0 had a number of bugs, but even after multiple rounds of testing releases they only came up after the final release.

Anyway, @ggzengel should now be able to confirm if the times are displayed correctly now 👍

**Comment by ggzengel** [comment]
@jcfp Thanks
@Safihre I got the right time now:
> a few seconds ago - Cannot change permissions of /mnt/sabnzbd/tmp

Sabnzbd is not allowed to change permissions and now I see this with no time lag. :-)

**Comment by Safihre** [comment]
👍

**Comment by Safihre** [comment]
@jcfp Thanks for the quick update to 2.3.0!
