### ISSUE TITLE
Direct unpacking default setting

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#991]
I would request that the default setting for Direct Unpack be set to disabled or that the unpack happens in the temporary folder instead.  Direct unpacking to the completed folder can cause issues with scripts that handle post-processing of the completed download folder.

**Comment by Safihre** [comment]
> Direct unpacking to the completed folder can cause issues with scripts that handle post-processing of the completed download folder.

What kind of scripts are that? 
Because at the point that the script is called, it should not matter if things were unpacked using Direct Unpack or normal one. Are the scripts that periodically scan the complete folder? Do they not ignore `_UNPACK_` folders?
Or do you see different files in the folder if Direct Unpack is on?

**Comment by labrys** [comment]
Its an issue with not ignoring _UNPACK_ folders in the script.  Obviously this can (and should) be fixed in the script, but by making a new feature default to disabled it prevents scripts from breaking just because someone updated SAB.  This particular script was one I have for cleaning up completed downloads that weren't fully post-processed by Medusa (or other Sick* forks) (e.g. download already exists in library at a better quality).

**Comment by Safihre** [comment]
It is not enabled by default, it is enabled after we do a diskspeed test during the first download. 
If the diskspeed is fast enough, a WARNING is shown that the feature is enabled. So the user is notified very directly about the change and it's not a hidden thing. 
Plus, how many of our users actually run such scripts... The post processing  time this will save so many regular users is absolutely worth it.
