### ISSUE TITLE
Debian Unstable: "OpenSSL disables TLS 1.0 and 1.1" ... some effects related to SABnzbd

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#994]
Some remarks related to Debian Unstable. As it's Unstable, they are just a FYI / discussion.

Sources
https://www.cyberciti.biz/howto/debian-linux/openssl-drops-tls-1-01-1-support-for-debian-unstable/
https://lists.debian.org/debian-devel-announce/2017/08/msg00004.html
tell:

> I've just uploaded a version of OpenSSL to unstable that disables the TLS 1.0 and 1.1 protocol. This currently leaves TLS 1.2 as the only supported SSL/TLS protocol version.

So I tried with sabnzbdplus-2.2.0RC1 on Debian Unstable to connect to ssl-eu.astraweb.com (which is TLS1, not TLS1.2), and SAB says:

`[Errno 111] [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:661)`
OK, good to know.

Then: SABnzbd stdout:
```
2017-08-08 19:36:09,413::INFO::[sabnzbdplus:1242] SSL version OpenSSL 1.1.0f  25 May 2017
2017-08-08 19:36:09,414::INFO::[sabnzbdplus:1243] SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']
```
Hey, isn't that strange: 'TLS v1.1', 'TLS v1' ? Is that the difference between SSL and OpenSSL and/or libraries?

FWIW / I don't know if this is relevant:
```
2017-08-08 19:36:09,869::DEBUG::[downloader:409] SSL verification test: False
```

For Google: 
```
2017-08-08 19:39:05,536::DEBUG::[downloader:113] ssl-eu.astraweb.com: Re-using address 193.202.122.129
2017-08-08 19:39:05,537::INFO::[newswrapper:283] Failed to connect: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:661) 1@193.202.122.129:563
2017-08-08 19:39:05,545::INFO::[downloader:483] 3@ssl-eu.astraweb.com: Initiating connection
2017-08-08 19:39:05,546::DEBUG::[downloader:113] ssl-eu.astraweb.com: Re-using address 193.202.122.129
2017-08-08 19:39:05,551::INFO::[downloader:483] 4@ssl-eu.astraweb.com: Initiating connection
2017-08-08 19:39:05,551::DEBUG::[downloader:113] ssl-eu.astraweb.com: Re-using address 193.202.122.129
2017-08-08 19:39:05,557::INFO::[newswrapper:283] Failed to connect: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:661) 2@193.202.122.129:563
2017-08-08 19:39:05,567::INFO::[newswrapper:283] Failed to connect: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:661) 3@193.202.122.129:563
```

**Comment by Safihre** [comment]
@sanderjo maybe you can investigate what is wrong with the supported protocol detection and why the connection test fails? 

I wish I had a good way to fix OpenSSL on macOS.. It's still stuck at TLSv1 only..

**Comment by sanderjo** [comment]
sabnzbd/utils/sslinfo.py does something like this:
```
import ssl
for ssl_prop in dir(ssl): 
	if ssl_prop.startswith('PROTOCOL_'):
		print ssl_prop
```
So I tried:
```
print "ssl stuff:"
import ssl
for ssl_prop in dir(ssl): 
	if ssl_prop.startswith('PROTOCOL_'):
		print ssl_prop


print "\nOpenSSL stuff:"
import OpenSSL
for item in dir(OpenSSL.SSL):
	if item.find('METHOD') >= 0:
		print item
```
On my Ubuntu, that gives:
```
sander@Stream-13:~/git/sabnzbd$ python ssl_checker_SJ.py 
ssl stuff:
PROTOCOL_SSLv23
PROTOCOL_TLS
PROTOCOL_TLSv1
PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2

OpenSSL stuff:
SSLv23_METHOD
SSLv2_METHOD
SSLv3_METHOD
TLSv1_1_METHOD
TLSv1_2_METHOD
TLSv1_METHOD
```

On the Debian Unstable I get:
```
root@3149db96ebd4:/# python ssl_checker_SJ.py 
ssl stuff:
PROTOCOL_SSLv23
PROTOCOL_TLS
PROTOCOL_TLSv1
PROTOCOL_TLSv1_1
PROTOCOL_TLSv1_2

OpenSSL stuff:
SSLv23_METHOD
SSLv2_METHOD
SSLv3_METHOD
TLSv1_1_METHOD
TLSv1_2_METHOD
TLSv1_METHOD

```
So
* the same on both systems
* IMHO incorrect information. So: incorrect method?

**Comment by thezoggy** [comment]
@sanderjo what version of ssl is loaded in python? dynamic/static linked?  you could have multiple openssl installed.. and python is using an older version that still supports tls v1

**Comment by sanderjo** [comment]
It's a Docker image, so all's clean.

I tried this, hoping for an error, which did not happen. :-(

```
root@3149db96ebd4:/# python
Python 2.7.13+ (default, Jul 19 2017, 18:15:03) 
[GCC 6.4.0 20170704] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
>>> context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
>>> context.options |= ssl.OP_NO_SSLv2
>>> context.options |= ssl.OP_NO_SSLv3

```

**Comment by sanderjo** [comment]
@thezoggy 

Docker container creation:

```
sed -i -e 's/main$/main contrib non-free/g' /etc/apt/sources.list
apt-get update 
apt-get -y install python
```
Info you requested:
```
root@833f31f4038f:/# python -c "import ssl;print ssl.OPENSSL_VERSION;"
OpenSSL 1.1.0f  25 May 2017
```

```
root@833f31f4038f:/# openssl version
bash: openssl: command not found
```
So:
```
root@833f31f4038f:/# apt-get -y install openssl

root@833f31f4038f:/# openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by sanderjo** [comment]
IMHO this is the situation:

* nothing wrong with Debian Unstable
* nothing wrong with python on this Debian
* the method / trick in SABnzbd to find supported protocols is not correct, and gives false information.

**Comment by thezoggy** [comment]
that 'version' of openssl without the support.. doesnt appear to be what you have installed? as your openssl is from may

**Comment by sanderjo** [comment]
So ... how can SABnzbd see which TLS versions are supported by the OS? Just a few notes:

```
$ lynx --dump 'https://www.ssllabs.com/ssltest/viewMyClient.html' | grep -A8  Protocols | grep -e TLS -e SSL
   TLS 1.3 No
   TLS 1.2 Yes*
   TLS 1.1 Yes*
   TLS 1.0 Yes*
   SSL 3   Yes*
   SSL 2   No
```
Conclusion: my browser/OS supports TLS 1.2, 1.1, 1, and SSL 3 (ouch).

Another, self-contained method:

Start a minimal TLS1.2-webserver (with SAB-keys):
```
sander@Stream-13:~/.sabnzbd/admin$ openssl s_server -accept 4444 -www -cert server.cert -key server.key -tls1_2
```
... and connect:
```
$ curl -k -s https://127.0.0.1:4444/ | grep -i protocol
    Protocol  : TLSv1.2
```
So my curl/OS does support TLS1.2

**Comment by thezoggy** [comment]
there is a bit of work that is needed in python dev to be able to support openssl 1.1.x (tls v1.3). so this probably is why in python 2.x you wont see much from the new openssl changes (1.1.x)

**Comment by Safihre** [comment]
The changes are now [merged for the 2.7 branch to](https://github.com/python/cpython/commit/05b7d9c6675b71d17f5fcf379b3888fba431f14e), so probably there will be support in the next Python release.
The versions reported by Python is indeed how Python was compiled and not on runtime, so probably Python on Debian was not recompiled yet to reflect these changes.

In general there is a discrepancy between what we report on the first Config page and what is actually used. For example it will list SSLv3, but because we use `create_default_context` SSLv3 is actually always disabled.
Not sure how we could improve that or if it really matters.

**Comment by sanderjo** [comment]
> Not sure how we could improve that or if it really matters.

I agree. 

Maybe just change

`SSL supported protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']`

to

`SSL known protocols ['TLS v1.2', 'TLS v1.1', 'TLS v1']`

**Comment by Safihre** [comment]
Agreed!

**Comment by Safihre** [comment]
Let Python fix this! All we can do is report what we have.

**Comment by Safihre** [comment]
@Cpuroast Seems TLSv1.3 support is coming to Python 2.7.14 after all:
https://github.com/python/cpython/commit/b9a860f3bf80b0d4a6c25d0f2f6ef849d9bf3594

Not for the binaries I guess, but at least it should work on the systems that have compatible OpenSSL versions.

**Comment by Cpuroast** [comment]
From the changes to ssl.rst, it looks like TLS 1.3 is going to be in 2.7.15.

2.7.14 is already in RC.

**Comment by thezoggy** [comment]
per the cpthon commit, yes its coming in 2.7.15:
```
+   Whether the OpenSSL library has built-in support for the TLS 1.3 protocol.
+
+   .. versionadded:: 2.7.15
```
