### ISSUE TITLE
"Lost Connection to Sabnzbd"

### ISSUE THREAD

**Issue by antigravity83** [sabnzbd/sabnzbd#996]
Hi there

Constantly getting this error whenever downloading/processing content. Have to reload the webui to get any response, but the error returns within a few seconds. 

Currently receiving the error, and system IOWait is at 1.6%, overall server load is less than 1. 

Running Ubuntu 16.04, Sabnzbd version 2.1.0

Unsure what logs you require?

**Comment by antigravity83** [comment]
Just trying to navigate the settings, and Sabnzbd is extremely slow to respond to any input.

Other services on my server are running fine- so don't believe it's a hardware/resource issue.

I've also tried updating Sab, but I'm getting a Broken Package Dependency error with Par2-tbb

**Comment by Safihre** [comment]
Have you applied all the tips in High speed downloading? https://sabnzbd.org/wiki/advanced/highspeed-downloading.html
So no warnings of missing dependencies? Logging set to Errors/Warnings? 

What is the speed at which you are downloading?

**Comment by Safihre** [comment]
Do you maybe have a Watched folder setup? 

If nothing helps, maybe switch logging to Debug and we can inspect the logs for something.

**Comment by antigravity83** [comment]
Hi Safihre-

No warnings of missing dependencies, and no watched folder. Logging is set to Errors/Warnings

I can download up to around 70MB/s, but the slow speeds and drop outs seem to occur even when no downloads or post processing are occuring. 

I'll apply all the tips in the High Speed Downloading- although I've been downloading at these speeds for quite sometime and only now am I having these issues. I'm wondering if there's some sort of database corruption or something?

Example, I'm trying to get into config to check version - and it takes minutes to load the config page, and navigating around the config area is very slow. No active downloads/post processing.

**Comment by antigravity83** [comment]
I'm also finding when I try to save settings in Config, I'm getting an error. 

But the setting themselves are updating.

**Comment by Safihre** [comment]
So this is independent of a sabnzbd upgrade? 
Then we have to investigate local things. The easiest test is to start from empty and see if that's better. Shutdown SAB and make a copy of your sabnzbd.ini file (location on first page of Config),  then delete it, and delete history1.db.
Start it, and just add only your basic servers and download location. 
How is the speed then?

**Comment by antigravity83** [comment]
I did a complete uninstall/reinstall. Now running 2.2.0

First thing that occured when booting up into Glitter was I get the "Lost Connection to Sabnzbd" error.

Could it be latency? I'm accessing a server with a latency of around 300ms.

**Comment by Safihre** [comment]
Yes could be latency, think the timeout is set to 1 or 2 seconds. 
But you say this didn't happen before? Any idea what you changed?

**Comment by antigravity83** [comment]
Nothing changed that I'm aware. I downloaded a bunch of content overnight, and this morning performance degraded. No content is in the queue anymore, but it's still slow.

**Comment by antigravity83** [comment]
Now I can't connect any of my Usenet providers.

I have four, all with different usernames and passwords, and none of them work? Getting "Invalid Server Details" for each one.

**Comment by Safihre** [comment]
This error is given before the connection is even started, so when any of the basic information is missing. Like port, host and username.

**Comment by antigravity83** [comment]
What is the best way to completely uninstall and reinstall? (Ie what folders should I delete?)

I'm definitely entering the correct data into each required field. Have used SAB for at least 5-6 years and never had issues like this before.

**Comment by Safihre** [comment]
You should delete the whole admin folder (where you found the `sabnzbd.ini` file).
Then it should be a clean start.

**Comment by antigravity83** [comment]
Thanks will give that a short, thanks for your help, much appreciated

**Comment by antigravity83** [comment]
Full reinstall and deleting folders seems to have done the trick. 

Performing excellent now- thanks for your support

**Comment by Safihre** [comment]
Wonder what was the problem, but glad it worked :)

**Comment by thezoggy** [comment]
Ive seen this issue too but when Sab is on a remote box....

Perhaps we could offer a startup argument for those running Sab on a remote server where it makes some things not as agressive to update for the ui..

**Comment by antigravity83** [comment]
Yeah it's on a remote server with not so great latency (300ms).

Attempting to download a lot of files at once seemed to be the trigger. Unsure how or why unfortunately.

**Comment by thezoggy** [comment]
So that's the issue, your browser to your server has so much latency that the JavaScript (ui) is thinking it's timing out waiting on your server response

**Comment by antigravity83** [comment]
Safihre seems to believe a 300ms latency wouldn't cause an issue?

**Comment by thezoggy** [comment]
300ms is probably ok.. but when you have a large queue or history.. the added transfer size means longer ping.. thus the latency is prob more which then is why you see the issue.

**Comment by antigravity83** [comment]
Looks like it's still happening :(

Yeah I get what you're saying, and sounds like it could be the problem. Is there anyway to increase the latency allowance?

I only have 2 items in my queue currently and I'm getting the error. 

No server load or DiskIO

**Comment by thezoggy** [comment]
@antigravity83 comment out this line and see if your issue is gone:
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Glitter/templates/static/javascripts/glitter.main.js#L395

**Comment by antigravity83** [comment]
@thezoggy thanks- will give that a shot :+1:

**Comment by Safihre** [comment]
> I have four, all with different usernames and passwords, and none of them work? Getting "Invalid Server Details" for each one.

I only now found that this is actually a bug in the server testing. Sorry about that.
