### ISSUE TITLE
sab 2.2.0RC2 -- server graphs

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#997]
server graph for Aug,
![sab](http://zoggy.net/firefox_2017-08-09_23-20-28.png)

change the drop down to last month.. doesnt show any data.. even though on RC1 it did:
![sab2](http://zoggy.net/firefox_2017-08-09_23-21-11.png)

> speaking of.. 'this month' / 'this week' can easily be wrong depending on if your machine/browser arent in the same timezone.. perhaps show what the timeperiod were talking about as a tooltip for the relevant 'this'.

> also, should we add 'last month' ?

changed graph back to Aug, noticed its wrong compared to when the page loaded:
![sab3](http://zoggy.net/firefox_2017-08-09_23-22-56.png)

(actually looks like the July data)

**Comment by Safihre** [comment]
Could you copy from the HTML source, the javascript variable `serverData[0]` (0 or whatever the number is for that server)?
I can't reproduce it.

**Comment by thezoggy** [comment]
here you go:
![sab4](http://zoggy.net/firefox_2017-08-10_00-16-09.png)

**Comment by Safihre** [comment]
If you could copy-paste it, I don't have to manually type it to test it 😉

**Comment by thezoggy** [comment]
trying to figure out how...

**Comment by thezoggy** [comment]
window.serverData[0]
```
2017-07-24
:
0
2017-07-25
:
898514253
2017-07-26
:
8067776698
2017-07-27
:
3664549383
2017-07-28
:
13367015011
2017-07-29
:
794861900
2017-07-30
:
5023541046
2017-07-31
:
1840267189
2017-08-01
:
1041360598
2017-08-02
:
901637558
2017-08-03
:
473953646
2017-08-04
:
2997086603
2017-08-05
:
3132215690
2017-08-06
:
5876087240
2017-08-07
:
5204852444
2017-08-08
:
870625693
2017-08-09
:
3320231145
2017-08-10
:
0
```

**Comment by Safihre** [comment]
I tried to reproduce, but I can't.
Maybe you can do a full refresh to clear caches or something?
In Firefox:
![image](https://user-images.githubusercontent.com/5703454/29159799-21becd68-7db0-11e7-9b0d-e347090bd03b.png)
Switch back to August from July:
![image](https://user-images.githubusercontent.com/5703454/29159816-35469c58-7db0-11e7-941e-df264a73ed42.png)

**Comment by thezoggy** [comment]
i see the problem in chrome (latest, new instance) and firefox 55, tried clearing cache but no go. is all this server data in history1.db?

**Comment by Safihre** [comment]
No `totals10.sab`

**Comment by Safihre** [comment]
Could you maybe just send me the raw HTML source of the page at safihre@sabnzbd.org? 
Maybe it's something else on the page doing the damage.

**Comment by thezoggy** [comment]
sure, have another instance of sab.. also doing the same issue.. sending you the info now

**Comment by thezoggy** [comment]
confirm that RC3 fixes the issue. perhaps we should add a month selector up top so it changes all the servers graph.. since right now if I want to see last month I have to go change 5? graphs manually..
