### ISSUE TITLE
Unit and functional tests

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#999]
We really need unit and functional tests.
Biggest hurdle, especially for functional tests: we need a mock-NNTP server.
We could use [NZBGet's NServ](https://nzbget.net/nserv-nntp-server), but that kind of feels wrong...

Anyone that wants to help me with this? 
Especially with the creation of this mock NNTP server.

Tasks and tests:
---

- [ ] Creation of a mock-NNTP server that can:
  - [ ]  Respond to authentication requests
  - [ ]  Respond to data-request with yEnc encoded data
- [ ] Test-platform that can start this server, send requests to it and wait for API-response
- [x] Test-platform for starting of SABnzbd with specific parameters
- [x] Test startup of SABnzbd
  - [x]  Correct binding to HTTP(S) ports
  - [ ]  Response to occupied port
  - [ ]  Response to missing dependencies or wrong encoding
- [ ] Implement functional tests - NNTP authentication
  - [x]  Response to correct login
  - [x]  Response to bad login
  - [ ]  Response to SSL on non-SSL port
  - [ ]  Response to bad certificates
- [ ] Implement functional tests - Downloading
  - [ ]  Can it download a normal file from the mock server
    - [x] NZB added as `.nzb`
    - [ ] NZB added inside `.tar.gz`, or `.zip` or `.rar`
  - [ ]  Can it download a damaged file from the mock server and repair/unpack
  - [ ]  Can it download a obfuscated file from the mock server
  - [ ]  Verification using only RAR-verification (test expected fail and success)
  - [ ]  Verification using only SFV-verification (test expected fail and success)
  - [ ]  Can it download a normal file from the mock server with UTF8 chars in the RAR filenames or the filenames inside the RAR's (both RAR3 and RAR5)
  - [ ]  Can it download a broken and/or obfuscated file from the mock server with UTF8 chars in the RAR filenames or the filenames inside the RAR's (both RAR3 and RAR5)
  - [ ]  Can it detect password jobs during downloading, also when the jobs have UTF8 filenames (both RAR3 and RAR5)
  - [ ]  Can it detect unwanted jobs during downloading, also when the jobs have UTF8 filenames (both RAR3 and RAR5)
  - [ ]  Can it download and repair passworded jobs (both RAR3 and RAR5)
  - [ ]  Test for duplicate detection
  - [ ]  Can it handle 7zip files
  - [ ]  Can it handle zip files
  - [ ]  Can it handle join-files
- [ ] Implement functional tests - RSS filter handeling
- [ ] Implement functional tests - Other config options
  - [ ]  Pre-queue script running
  - [ ]  Post-processing script running
  - [ ]  Notification script running
  - [ ]  Ignore samples option
  - [ ]  Download all par2 option
  - [ ]  Testing of sorting (many sub-tests should be made here!)
  - [ ]  Testing of scheduler (not sure yet how..)
- [ ] Other tests
  - [ ] Is category parsed correctly from NZB (from filename `{{}}file.nzb` or from tag inside NZB)
  - [ ] Is password parsed correctly from NZB (from filename `file{{}}.nzb` or from tag inside NZB)

**Comment by sanderjo** [comment]
Can it be an(other) existing NNTP-server?
Must it be in python code, or can it be in C or Go?

**Comment by Safihre** [comment]
It can be another yes, and the language also doesn't really matter I think. We can use TravisCI and Appveyor to compile it before running the tests.

**Comment by Hellowlol** [comment]
What wrong with using nzbgets nserv? It enven stated that it can be used with other clients.

**Comment by Safihre** [comment]
It's like using Android to test iOS 😁

**Comment by Hellowlol** [comment]
@Safihre Are you gonna use pytest?

**Comment by Safihre** [comment]
No clue, is that the easiest?

**Comment by Hellowlol** [comment]
Yep.

**Comment by Hellowlol** [comment]
Maybe we can use twisted AS nntp server.

**Comment by Safihre** [comment]
Sure, you have experience with it? I don't but it seems interesting.
It doesn't have to by high performance at all, just has to work 💯

**Comment by Safihre** [comment]
I have added super basic tests, it will start SABnzbd and then test for basic API and page-serving functionality.
At least that would prevent what happened with 2.3.0Alpha1 where the Config > Switches page didn't work.

Much more work to do!

**Comment by thezoggy** [comment]
any doc on how to add tests / run it / etc..

**Comment by Safihre** [comment]
Will add docs when there's actually functional tests, the tests are embarrassingly simple right now.
But in case (shutdown SABnzbd first!):
```
pip install pytest pytest-xprocess
pytest
```

**Comment by Safihre** [comment]
Working in this branch: https://github.com/sabnzbd/sabnzbd/tree/feature/pytest
If anyone wants to contribute, just PR against that 👍 
Just added basic testing of adding and removing NZB's.

Thinking of just using the SABnzbd Giganews account for now to test downloading (with the username/password encoded of course) of some of @sanderjo's [test NZB's](https://www.binsearch.info/?q=reftestnzb&max=100&adv_age=1100&server=).

**Comment by Hellowlol** [comment]
Good stuff, i got some stuff i need to finish (sabapi for one) but ill see if i cant get started this week.

**Comment by Safihre** [comment]
AppVeyor was added to also enable automatic Windows platform testing.

**Comment by Hellowlol** [comment]
http://flylib.com/books/en/2.407.1.69/1/ describe how to setup a minimal nntp server using twisted.

**Comment by Safihre** [comment]
@Hellowlol interesting, very extensive.  Doesn't include the yEnc encoding as far as I can see, but good basis!

**Comment by OldskoolOrion** [comment]
I will start looking into this as well as first task.. I used Mozilla's MailMan FakeServer back in the day which was really nice for functional testing of imap-, smtp-, nntp-protocol stuff etc (conforming to rfc) - lot of examples there to start with and easy integratable in automatic workflow by the looks of it. Need to dive in and get my hands dirty to be 100% sure its a good choice of course, since I'm not yet knee-deep in sab's codebase either, and have no helicopter view yet of all the needed reqs. 

Yes it's old and yes it's in that horrible javashit non-language, but if it do exactly what we want and is extremely easy to extend and adept, it's a valid option I think.

Besides that I already checked out some nice Golang based nntp-server & client stuff, which is OS, well supported and even in use live, let alone just as local server for functional testing.. I'm definitely going to dive deeper into that as well, since I still have to start teaching myself Go on a more than basic-level. Very platform-independent, quite fast, good libs and friendly community with quality server-client related packages out there.

And if all this plus stuff that's under investigation fails for us.. then there's always nserv.. but I agree.. out of respect to sab itself and nzbget as well.. it would be more elegant if sab wouldn't have to rely on nserv :-)

Lotsa spare time tomorrow to start rocking.. documentation has been collected.. a lot of source code has been git'd.
Good start to getting to know the codebase while actually doing something useful :-)

**Comment by Safihre** [comment]
I am trying to add a simple unit-test, but I am failing.
How would I test for example `sabnzbd.misc.calc_age` from a test `.py` file in the `tests` directory executed by pytest?
Anyone that can help me out? :)

**Comment by Hellowlol** [comment]
I normally import the stuff I need in conftest.py then in test_misc.py 

‘’’from conftest import misc
def test_calc():
    pass
‘’’

**Comment by Safihre** [comment]
I am considering (due to a project at work) moving the functional tests to an actual functional-testing tool like Selenium. This way we can test _actual_ user flow instead of just API calls.

**Comment by wwwehr** [comment]
@Safihre perhaps one of these?
- https://testingbot.com/open-source
- https://www.browserstack.com/automate/travisci
- https://saucelabs.com/open-source
